### ISSUE TITLE
(MacOS) Dropdowns in the setting menu are opened behind the settings window

### ISSUE THREAD

**Issue by Marrocco-Simone** [godotengine/godot-docs#10002]
**Your Godot version: 4.3**

**Issue description: Dropdowns in the setting menu are opened behind the settings window**

I was trying the 2d tutorial on the starting up docs. When changing the Stretch mode, I noticed the dropdown opened behind the setting window. I can select the options by moving with the arrow keys, but not with the mouse.

Currently using *macOS 12.7.6 21H1320 x86_6* with *Intel i5-6360U (4) @ 2.00GHz* CPU. To replicate, I downloaded the latest version of Godot for Mac, created a new project, opened the edit in full screen and opened the settings.

<img width="1440" alt="Screenshot 2024-09-25 at 17 15 09" src="https://github.com/user-attachments/assets/e5e0efe9-4744-4b90-906a-82cdf5bc984e">

**Comment by tetrapod00** [comment]
That's a bug with the engine itself, not the docs, so please open an issue [in the main repo](https://github.com/godotengine/godot/issues/new/choose)
