### ISSUE TITLE
Timer start() documentation seems incorrect

### ISSUE THREAD

**Issue by nziswat** [godotengine/godot-docs#10012]
**Your Godot version:**
4.3
**Issue description:**
The line 'Starts the timer, if it was not started already.' Seems to be incorrect from what I can tell. Calling start() on a timer that is already running restarts the timer, instead of doing nothing.
Suggested fix: 'Starts the timer, or restarts if it was started already.'

**URL to the documentation page:**
https://docs.godotengine.org/en/stable/classes/class_timer.html

**Comment by AThousandShips** [comment]
Already fixed:
* https://github.com/godotengine/godot/pull/95485
