### ISSUE TITLE
Update Instancing (continued) doc

### ISSUE THREAD

**Issue by cbscribe** [godotengine/godot-docs#1001]
This one is updated:
http://docs.godotengine.org/en/latest/learning/step_by_step/instancing.html

Need to update this one with some better examples and rewrite the text.

**Comment by SuperPrower** [comment]
Hi, I'm not sure if it's ok to write here, but instancing example project, linked in this chapter for version 3.0, is already 'completed' - i.e. there is plenty of balls instanced, and you can even create new ones by clicking LMB; I'm not sure that this is expected from DIY learning example.

**Comment by gemkibeju** [comment]
@cbscribe @SuperPrower I found the same issue a few minutes ago. The first screenshot of the instancing tutorial shows no balls. However, the instancing demo .zip file already has the balls as shown in the "[multiple instances](https://godot.readthedocs.io/en/3.0/getting_started/step_by_step/instancing.html#multiple-instances)" screenshot.

**Comment by cbscribe** [comment]
Good catch, I clearly uploaded the wrong one. I'll update it.

**Comment by Calinou** [comment]
Is this work now finished?
