### ISSUE TITLE
AnimationRootNode should be abstract class？

### ISSUE THREAD

**Issue by GitHub7796** [godotengine/godot-docs#10017]
Your Godot version:

4.3

Issue description:

I'm confused about using AnimationTree's AnimationRootNode, I don't know what it does, I looked through the documentation and found that it was a base class, and I didn't think it should be in the following options
![image](https://github.com/user-attachments/assets/f474ef08-a021-48c7-9a27-767df6006565)

URL to the documentation page (if already existing):

https://docs.godotengine.org/en/stable/classes/class_animationrootnode.html

**Comment by AThousandShips** [comment]
This is for reporting bugs in the documentation, for engine bugs please go [here](https://github.com/godotengine/godot/issues)
