### ISSUE TITLE
Read the docs language+version picker obscures content 

### ISSUE THREAD

**Issue by idbrii** [godotengine/godot-docs#10094]
**Your Godot version:**
4.3

**Issue description:**
Documentation pages now have a floating language+version picker that obscures the content.

**URL to the documentation page:**
All pages

What it looks like now (en and stable in bottom right):
![Screenshot_20241015-204254](https://github.com/user-attachments/assets/a5f0323a-e875-41d7-99ad-600e43ee5978)

It didn't look like this the last time I used the docs. Was this an intentional change? Or something that came with a read the docs upgrade? Maybe it's possible to configure it closer to the old behaviour or make it attached to the bottom of the frame?

Sorry if already discussed to death. I looked for related issues, but didn't find any.

**Comment by mhilbrunner** [comment]
No, you haven't missed anything! There is just a bit of dicussion in #devel and #documentation on the Rocketchat, as this is seemingly a (very) recent change. Likewise, search is/was broken for some users (https://github.com/godotengine/godot-docs/issues/10062).

Thanks for taking the time to open an issue!

**Comment by idbrii** [comment]
Looks like [this](https://github.com/readthedocs/readthedocs.org/issues/11474) is the RTD's migration guide for this change.

Seems the selector I'm talking about is called the [flyout menu](https://docs.readthedocs.io/en/stable/flyout-menu.html#addons-flyout-menu) and it's implementation and configuration are significantly different in this new version.

Not sure if any of that affects the search issue? Cheers!

**Comment by mhilbrunner** [comment]
This should now be fixed by https://github.com/godotengine/godot-docs/pull/10194 as soon as the ReadTheDocs build for 4.3/stable finishes. Thanks for reporting!
