### ISSUE TITLE
2D Getting started docs signals page missing step to make Node2D scene main scene

### ISSUE THREAD

**Issue by abrugsch** [godotengine/godot-docs#10103]
**Your Godot version:**
4.3 stable
**Issue description:**
The getting started docs for signals describes adding a new scene for adding a button, and the code for hooking up the signal to an event handler, but as it's a follow on step from the previous page, the Main scene is still set to the sprite2D scene. Therefore when you play the project, the sprite rotates but the button isn't visible.

A paragraph needs adding to switch the main scene from sprite_2D.tscn to node_2D.tscn in the filesystem pane

**URL to the documentation page:**
https://docs.godotengine.org/en/stable/getting_started/step_by_step/signals.html

**Comment by AThousandShips** [comment]
The tutorial instructs to:
> To add a button to our game, we will create a new scene which will include both a Button and the sprite_2d.tscn scene we created in the Creating your first script lesson.

And then:
> Save your newly created scene as node_2d.tscn, if you haven't already. You can then run it with F6 (Cmd + R on macOS). At the moment, the button will be visible, but nothing will happen if you press it.

**Comment by tetrapod00** [comment]
Closing, since the tutorial already seems to have valid instructions, since it tells you to `Run Current Scene` (`F6`), not to `Run Project`.
