### ISSUE TITLE
"Using the file Browser" section located in a confusing place

### ISSUE THREAD

**Issue by cemore2048** [godotengine/godot-docs#10104]
**Your Godot version:**

4.3

**Issue description:**

The "Using the file Browser" section is located after a section whose instructions take you out of the project creation window. This is confusing because when first reading this section, it seems like it's describing a `Browse` button on the editor. Since the previous section instructed you to exit the project creation window, it's not clear what the "Using the file Browser" section is referring to and sends the reader down a spiral searching for the `Browse` button erroneously.

Perhaps before instructing the user to press the create button, the "Using the file Browser" section can be mentioned if they want to learn more about how to navigate it?

If there is indeed a `Browse` button somewhere else on the editor, maybe a picture of where it's located can help direct the reader to the appropriate spot.

**URL to the documentation page (if already existing):**
https://docs.godotengine.org/en/stable/tutorials/editor/project_manager.html#using-the-file-browser

**Comment by tetrapod00** [comment]
It's intended to describe the `Browse` button on the `Create New Project` window, but I agree that as is it's a bit unclear. There's definitely some easy fix for this.

It's also weird to me that we have tutorial on how a file browser works, and it's on this page specifically. The same file browser is used elsewhere in the editor too. So perhaps a long-term solution is to move this documentation to elsewhere and link to it. The right place might be the new [Interface](https://github.com/godotengine/godot-docs/pull/9632) docs that are in progress?
