### ISSUE TITLE
Any plugins not appear in node list

### ISSUE THREAD

**Issue by Habbie127** [godotengine/godot-docs#10117]
**Your Godot version:**
Godot version is 4.3.stable
**Issue description:**
Any plugins not appear in node list after any plugin folder added in addon and after enable any plugin in settings plugin still any plugin not appear in node list.
**URL to the documentation page:**

If you know how to fix the issue you are reporting please
consider opening a pull request. We provide a tutorial on
using git here: https://docs.godotengine.org/en/stable/community/contributing/pr_workflow.html,
writing documentation at https://docs.godotengine.org/en/stable/community/contributing/docs_writing_guidelines.html
and contributing to the class reference here: https://docs.godotengine.org/en/stable/community/contributing/updating_the_class_reference.html
![1729357813267](https://github.com/user-attachments/assets/c6517dab-c59f-41bb-a68e-492fc3f6785d)

**Comment by tetrapod00** [comment]
This doesn't seem like a docs issue. Bugs should be reported in the main repo (https://github.com/godotengine/godot/issues/new/choose), though from what you posted I'm not sure if this is a bug or a missing feature.

**Comment by mhilbrunner** [comment]
Thanks for reporting, please report it on the main repo as outlined above. Closing, as discussed above :)
