### ISSUE TITLE
Docs use old and removed `PoolVector`

### ISSUE THREAD

**Issue by dustdfg** [godotengine/godot-docs#10146]
**Your Godot version:** 4.4.dev/master

**Issue description:** Docs use old and removed `PoolVector`

**URL to the documentation page:**  https://docs.godotengine.org/en/latest/contributing/development/core_and_modules/core_types.html#allocating-memory

**Comment by tetrapod00** [comment]
See also https://github.com/godotengine/godot-docs/issues/3192, maybe https://github.com/godotengine/godot-docs/issues/6259.
