### ISSUE TITLE
CanvasItem.visible ancestor visibility doesn't work as described

### ISSUE THREAD

**Issue by ArseAssassin** [godotengine/godot-docs#10157]
**Your Godot version:**
4.3.stable

**Issue description:**
Docs for `CanvasItem.visible` says:

> The node is only visible if all of its ancestors are visible

If I create a node structure like so:

```
Label
└ Node
 └ Label2
```

Making `Label` invisible doesn't change the visibility of `Label2`. Don't know if this is intended behavior, but something's off either way.

**URL to the documentation page:**
https://docs.godotengine.org/en/stable/classes/class_canvasitem.html#class-canvasitem-property-visible

**Comment by AThousandShips** [comment]
See the latest version, this has been fixed already in:
* https://github.com/godotengine/godot/pull/97223

**Comment by AThousandShips** [comment]
> Still, based on all this I wouldn't expect ancestors of a non-CanvasItem to be ignored when checking visibility. 🤷

That could be worded better, but it does say "only in parent nodes that inherit from ..." so it means it won't go further up

But it should be more clear with *direct* ancestors (when this was discussed outside of the PR I advocated for that kind of wording, but it seems to have been lost in the PR discussion itself)

**Comment by ArseAssassin** [comment]
Okay thank you, fair enough. 👍
