### ISSUE TITLE
"const float PI" is no longer a valid line of code and should be removed from the docs

### ISSUE THREAD

**Issue by Arnklit** [godotengine/godot-docs#10160]
**Your Godot version:**
4.3.stable

**Issue description:**
"const float PI" is no longer a valid line of code and should be removed from the docs
The constants example shows defining PI, but since the PI constant is now built in, this line of code will cause a "Redifinition of 'PI'." error.

**URL to the documentation page:**
https://docs.godotengine.org/en/stable/tutorials/shaders/shader_reference/shading_language.html#constants

**Comment by AThousandShips** [comment]
This was never really valid code and might be a leftover from older versions, the constants were available in the different shaders already in 4.0
