### ISSUE TITLE
What to do with the Community category now?

### ISSUE THREAD

**Issue by NullConstant** [godotengine/godot-docs#1020]
Since the docs have been restructured to include the top-level Tutorials category, I feel that there is a degree of overlap between it and Tutorials section under Community, which contains articles about 3D, AR/VR and GDNative (some of which are rather extensive yet really hidden, even though they mostly cover somewhat secondary topics/features - still) - all of which I feel could be moved to the new Tutorials category, with VR and GDNative becoming new sections under Tutorials (probably towards the lower end as they're not exactly core topics), and 3D being merged with the existing 3D section.

If we do that though, the only section under Community would be the Contributing section - and this might be just my own personal hunch, but I feel that having a category that contains only one section (though that in turn has multiple articles) would be...weird. (Even though two such categories already exist, namely About and Class Reference.)
The best solution to that IMO would be moving the Contributing section all the way to the top, to the General category (alongside the existing About section), but this is just my own personal thing probably. This would axe the Community category entirely, however.

Thoughts?

**Comment by mhilbrunner** [comment]
Idea was to move the current Community->Tutorials content to the new Tutorials section and use the Community->Tutorials one to point out 3rd party tutorials. (Think KidsCanCode/GDQuest youtube channels, for example)

**Comment by NullConstant** [comment]
It would probably also be worthwhile to point out the various community hubs/communication channels (though arguably the official website already does this, but I don't know if it still will in the same way after the upcoming redesign @bojidar-bg), albeit in a separate article.

- a list of the #godotengine-* IRC channels on Freenode
- stuff on social media (#GodotEngine Twitter tag, the Facebook group)
- the Discord server
etc.

**Comment by mhilbrunner** [comment]
Will do :)

**Comment by akien-mga** [comment]
The point of the Community::Tutorials category was for when we hardly had any reviewer for the docs, to be able to merge tutorial proposals from new contributors which might not fulfill the quality expectations or scope of the main documentation.

@BastiaanOlij put his their just by lack of self-confidence :P but they should obviously be moved to the regular sections. And the category itself is no longer needed, as we now have plenty of reviewers who ensure that all merged PRs are of great quality.

**Comment by mhilbrunner** [comment]
Makes sense, but as said, I'd repurpose it to point out to valuable tutorials/resources on third party sites. I'll submit a PR soonish :)
