### ISSUE TITLE
Localization keys not working on Random Strings

### ISSUE THREAD

**Issue by Karbonicc** [godotengine/godot-docs#10203]
**Your Godot version:**
4.2.1
**Issue description:**
Every once in a while, my translations will break in Godot, with the strings falling back to their original English.
![image](https://github.com/user-attachments/assets/d0b3b1e4-f9cc-4f15-a097-536e35637e2e)
This line should be in Russian, however, it is being displayed in English.
![image](https://github.com/user-attachments/assets/668a8859-01a2-492a-b8a0-78fcae718fbc)
![image](https://github.com/user-attachments/assets/9cba8aa8-aca9-43fb-af22-fa0f466bb275)
The key in the csv file is the same as the one in Godot.
However, if I change the message in godot, and then undo that change, the key now acts as expected. (IE: adding a space, and removing it)
![image](https://github.com/user-attachments/assets/1f1f77dc-9312-4fa7-8133-0eaecb4d48bb)
In this case, the key has not changed at all, but it now works.
This break can happen when unrelated files are changed. It makes for a very risky development environment.
This also makes the bug difficult to consistently reproduce, since it seems to happen at random intervals. There are no errors in the console when it happens, either.

**URL to the documentation page:**
https://docs.godotengine.org/en/stable/tutorials/i18n/internationalizing_games.html

**Comment by tetrapod00** [comment]
Thank you for the report, but this seems like an engine bug, not a docs issue. You should instead report on the [main godot repo](https://github.com/godotengine/godot/issues) (this repo is just for tracking bugs related to the docs).

**Comment by Karbonicc** [comment]
Ah sorry, I'll get to that.

**Comment by tetrapod00** [comment]
I'm closing this issue since it seems to be an engine bug and not a docs issue. I'd recommend reporting this as a bug in the main repo (note that the bug report format there is different, so this can't be transferred directly). Again, thank you for reporting
