### ISSUE TITLE
2D sprite animation: Error loading png with "Add frames from a Sprite Sheet": Unable to load images 

### ISSUE THREAD

**Issue by bernhard-hofmann** [godotengine/godot-docs#10211]
**Your Godot version:**
v4.3.stable.flathub [77dcf97d8]

**Issue description:**
The documentation guides the user to download the `webp` image and use that. When attempting to add the sprite animation, the default file type is `*.tres` and has to be changed to `*.webp` to open that file, but selecting the downloaded image file results in a dialog titled `Warning!` and the text `Unable to load images`: 
![image](https://github.com/user-attachments/assets/d86d5a7d-58f8-4f8e-b134-41445df5a253)
 It would be helpful to know which image formats are supported.

**URL to the documentation page:**
https://docs.godotengine.org/en/stable/tutorials/2d/2d_sprite_animation.html#sprite-sheet-with-animatedsprite2d

**Comment by tetrapod00** [comment]
WebP images are supported by Godot.

I can't reproduce this behavior. I followed the linked tutorial, doing the following steps:
- Using 4.3.stable.mono.
- Download the WebP image from Firefox on Windows 10.
- Either copy the file from my downloads folder into the Godot folder, *or* drag and drop the file into the FileSystem dock in Godot. Both work.
- With a SpriteFrames resource selected (either one in the FileSystem dock, or one in the inspector), click **Add frames from sprite sheet**. Select the image file.
- In the opened window, select the frames, then click **Add X Frames**.

Is there anything else in your setup that might cause different behavior? If you can follow the tutorial steps again, and they don't work, this looks more like a platform-specific engine bug than a documentation issue.

**Comment by bernhard-hofmann** [comment]
Thank you so much @tetrapod00 - the issue was that I was trying to add the image from my downloads folder, not a folder within the project. The documentation already says "... and then copy the image into your project folder." but I did not see it or assumed it did not matter. I feel so stupid. :(
