### ISSUE TITLE
Split Contributing section of docs into contributing to engine and contributing to docs

### ISSUE THREAD

**Issue by skyace65** [godotengine/godot-docs#1022]
Right now the contributing section of the docs covers engine development, testing, and contributing to the docs. I propose that we split the structure of the docs for better organization, and to better suit the needs of those respective areas. 

I'm thinking a structure like this

- Contributing
   - Ways to contribute
   - Contributing to the engine
      -Pull Request Workflow
      -Code Style Guidelines
      -Bug Triage Guidelines
      -Updating the class reference
   - Contributing to documentation
      -Basics of Git
      -Using Visual Studio Code
      -Documentation Guidelines
      -Image Guidelines

The basics of git page would go over how to get started with git, and git commands people should know to contribute to the docs. After that we have a page on using a specific text editor to update the docs, with images specific to that text editor to guide users. I can make a page on VSCode since that's what I use, in the future other contributors could add a page on using Atom or other text editors.

The documentation guidelines would be the page we have now. And the image guidelines would be what we've discussed in Issue #967

**Comment by skyace65** [comment]
@akien-mga , @NathanLovato , what do you guys think?

**Comment by akien-mga** [comment]
I don't know, at least the "Basics of Git" is redundant since that's exactly what "PR workflow" describes.
I don't really understand how "Using Visual Studio Code" relates to writing documentation?

**Comment by NathanLovato** [comment]
The git workflow to contribute to the docs and the engine is more or less the same. Updating the class ref is documentation. Half the docs are in the godot engine repo. Image guidelines should be part of the docs writing guidelines as anyone should follow all of it - it's already been hard enough giving people 2 different pages to read.

With only 7 pages that could already be a little better organized, I wouldn't split and bury them down in 2 separate categories, but rather make the titles a bit clearer and improve the existing content.

**Comment by skyace65** [comment]
Okay, how about this. Instead of splitting the documentation in two, I'd like to heavily modify the PR style workflow page and re-name it to Using Git and Github. The current page isn't as specific as it should be and can confuse people who have no experience with Git.

And add in a page for Image guidelines and Using Visual Studio Code. I think it's important to have pages specific to Text editors so people understand how to use their built in source control tools. As it is the only text editor talked about in documentation is Nano, which is extremely intimidating to newcomers.

**Comment by NathanLovato** [comment]
If you want to improve a page sure, go ahead. For image guidelines, again, I don't think it should be separate from the docs writing guidelines. It's just a few lines of text and a good picture and everyone who contributes to the docs should be aware of it and of the writing style. As I said already: it's hard enough for people to click on 2 links to contribute, let's not add a 3rd one. You can put it around the top of the docs writing guidelines though.

For a VSCode console specific page... no, I don't think it's a good idea. Covering specific external tools in the main docs in general isn't a good idea. For vscode in particular you have great source control guides online, no need to redo it. Adding a list of links to good guides for specific editors as a note would be more than enough.
