### ISSUE TITLE
Split the the Miscellaneous into appropriate catergory.

### ISSUE THREAD

**Issue by ZX-WT** [godotengine/godot-docs#1023]
In my opinion, the category Miscellaneous should be avoided to have a more direct table of content. We should further categorize the items under it and have more item in the list instead.

Here are the current tutorial under miscellaneous :
    Background loading
    Data paths
    Saving games
    Encrypting save games
    Handling quit requests
    Pausing games
    Internationalizing games
    Locales
    Binary serialization API

Internationalizing games and locales are related to translation and I think translation is qualify to have its category. It is an engine feature.

Handling quit requests and Pausing games are related to game process? I don't know what name is appropriate.

Background loading, Data paths, Saving games, Encrypting save games are related to reading,writing files. What's the usual term to describe this operation in programming? I think Binary serialization API can also be included in this category.

Here is my basic idea, any suggestions or comment?

**Comment by NullConstant** [comment]
>Background loading, Data paths, Saving games, Encrypting save games are related to reading,writing files. What's the usual term to describe this operation in programming?

You're probably thinking of I/O (input/output).

Internationalizing games & locales fall into a category often referred to as i18n (internationalization), or l10n (localization).

**Comment by ZX-WT** [comment]
Could we have more discussion about this issue? 
I think we should split it as soon as possible if we all agree with this.

**Comment by pwab** [comment]
I'm fine with adding `I/O` and `Internationalization`.

> Handling quit requests and Pausing games are related to game process? I don't know what name is appropriate.
I would leave these inside a `Miscellaneous` (or `Utilities`) category.

**Comment by ZX-WT** [comment]
> I would leave these inside a Miscellaneous (or Utilities) category.

Ultimately, I would like to eliminate the use of miscellaneous as it is quite ambiguous. I know it is difficult to sort things out. Anyway, at least we can trim down the list inside Miscellaneous. 

Any other suggestions?

Can anyone make a pull request for this? I am not sure how to move things around besides adding new tutorial, I will definitely mess things up.

**Comment by mhilbrunner** [comment]
Think its good enough for now. :) Probably always gonna need Misc. to avoid single-page categories
