### ISSUE TITLE
Godot zip / extracted file does not contain " Mono " file in "GodotSharp" file

### ISSUE THREAD

**Issue by Mirsengar** [godotengine/godot-docs#10239]
I just downloaded Godot Engine 4.3 .NET (mono version) and it doesn't contain "Mono" file in "GodotSharp" file. it only contains Tools and Api files

**Comment by tetrapod00** [comment]
Is this related to the https://docs.godotengine.org/en/stable/tutorials/scripting/c_sharp/c_sharp_basics.html#project-setup-and-workflow section?
If not, please link to the section of docs that has a bug (it was in the issue form for a reason)

**Comment by skyace65** [comment]
Closing per my comment in the linked engine issue.
