### ISSUE TITLE
An "About GDNative" document

### ISSUE THREAD

**Issue by RiverMesa** [godotengine/godot-docs#1024]
So we now have the GDNative C tutorial, which is an excellent addition to the docs, however...the docs don't really explain what GDNative itself *is* (nevermind the fact that said tutorial is kinda tucked away in Community::Tutorials::GDNative right now, so it's barely visible - see #1020), and I think it would be something worth doing since it's not a very 'intuitive' (at first) feature, yet it's quite incredible with how much potential it has.

I do think that a lot of info could be lifted wholecloth from the [GDNative blog post](https://godotengine.org/article/look-gdnative-architecture) for such an article, as well as for documenting some of the GDNative-related classes in the API reference (which is a bit beyond the scope of this issue, but is nonetheless related). 
I don't know how much I'd be able to help out with this myself, since GDNative is ...a bit lower-level than I'm comfortable with documenting.
 
@karroffel @BastiaanOlij

**Comment by BastiaanOlij** [comment]
I think turning some of the information on that blog post into an separate introduction page in the docs. I didn't want to overload the reader in the tutorial. The assumption I think we can make here is that someone goes and follows tutorials after they have been informed that part of the system may be useful to them. They don't go and read tutorials to find that out.

**Comment by lupoDharkael** [comment]
[Here](https://github.com/GodotNativeTools/godot_headers#faq) there is some additional info which should be added to that GDNative introduction page.

**Comment by BastiaanOlij** [comment]
@karroffel I don't think its a bad idea to add a little GDNative introduction page to the docs but I think you're better able to write something sensible.

**Comment by karroffel** [comment]
Yup, I'll work on more and better docs soon :)
