### ISSUE TITLE
Add EditorSceneFormatImporter descriptions

### ISSUE THREAD

**Issue by Hudsonator72** [godotengine/godot-docs#10260]
Godot 4.3

I am currently working on a custom model importer using this class, and it would be nice if there were some descriptions to the callbacks to know exactly what to put. 
This is also my first issue, so please excuse me if I do something wrong

https://docs.godotengine.org/en/stable/classes/class_editorsceneformatimporter.html

**Comment by tetrapod00** [comment]
Thanks for reporting this! However, I believe we don't typically keep individual issues for missing class reference descriptions, since those are already tracked here https://godotengine.github.io/doc-status/.

**Comment by tetrapod00** [comment]
Closing and consolidating into https://github.com/godotengine/godot-docs/issues/7547.
