### ISSUE TITLE
Can't open godot engine, window shows black screen

### ISSUE THREAD

**Issue by luongdn** [godotengine/godot-docs#10272]
**Your Godot version:**
Godot_v4.3-stable_mono_win64

**Issue description:**
Download godot for the first time, extract and open it. The godot engine window opens and splashes the logo for a second and goes into pitch black. I did install .NET SDK 9.0 after, but it still doesn't work.
There are two exe files I tried them both and got the same result.
My windows version: Windows 11 Pro

<img width="1052" alt="image" src="https://github.com/user-attachments/assets/36e6c0ac-c621-4209-a46e-92b44067c59d">

Solution:
Update AMD software and driver. In my case, I did a full install of AMD software.

**URL to the documentation page:**

If you know how to fix the issue you are reporting please
consider opening a pull request. We provide a tutorial on
using git here: https://docs.godotengine.org/en/stable/community/contributing/pr_workflow.html,
writing documentation at https://docs.godotengine.org/en/stable/community/contributing/docs_writing_guidelines.html
and contributing to the class reference here: https://docs.godotengine.org/en/stable/community/contributing/updating_the_class_reference.html

**Comment by luongdn** [comment]
Updated: it seems there is a problem with the UI. If I click around on the black screen, I can sometimes see things pop up, that means it works, only the UI is broken
<img width="690" alt="image" src="https://github.com/user-attachments/assets/444af5ba-e0e8-436b-9bee-28745d898a60">

**Comment by luongdn** [comment]
Ok, so I'm able to work around this by using the command line (from this tutorial https://docs.godotengine.org/en/stable/tutorials/editor/command_line_tutorial.html) by creating a folder with `project.godot` file inside and running `godot-mono -e`.
The project manager screen remains broken.

**Comment by clayjohn** [comment]
What type of computer do you have? Can you post the CPU and GPU here?

It sounds like your computer might not support OpenGL and isn't falling back to DirectX properly.

**Comment by luongdn** [comment]
I have AMD Ryzen 5 5600X and GIGABYTE RX 6700 XT. I should also mention that the project and everything else is working fine, as I'm following along a tutorial, it's just the project manager screen is having problem.

**Comment by clayjohn** [comment]
Could you try the steps described here https://github.com/godotengine/godot/issues/98053? This person has a similar issue and was able to resolve it by uninstalling outdated drivers

**Comment by luongdn** [comment]
Oh it did work. Not sure exactly what the issue is but I did a full install of everything AMD and it works.
