### ISSUE TITLE
Contradictory performance information about `Packed*Array` types

### ISSUE THREAD

**Issue by mechalynx** [godotengine/godot-docs#10300]
**Your Godot version:**

Both stable (4.3) documentation and latest ([0ceba58](https://github.com/godotengine/godot-docs/commit/0ceba58667e0fd08118638057a9a983e0a94e6a5))

**Issue description:**

There is contradictory information within the class reference and the gdscript reference in regards to the performance of `Packed*Array` types versus regular `Array` and typed array classes.

Specifically the class references for:
  - [PackedVector2Array](https://docs.godotengine.org/en/latest/classes/class_packedvector2array.html)
  - [PackedVector3Array](https://docs.godotengine.org/en/latest/classes/class_packedvector3array.html)
  - [PackedStringArray](https://docs.godotengine.org/en/latest/classes/class_packedstringarray.html)
  - [PackedInt64Array](https://docs.godotengine.org/en/latest/classes/class_packedint64array.html)
  - [PackedFloat64Array](https://docs.godotengine.org/en/latest/classes/class_packedfloat64array.html)
  - [PackedColorArray](https://docs.godotengine.org/en/latest/classes/class_packedcolorarray.html)

(but not the class references for `PackedInt32Array`, `PackedFloat32Array`, `PackedVector4Array` and `PackedByteArray`)

all have this paragraph:
> Differences between packed arrays, typed arrays, and untyped arrays: <ins>**Packed arrays are generally faster to iterate on and modify compared to a typed array of the same type**</ins> (e.g. [PackedInt32Array](https://docs.godotengine.org/en/latest/classes/class_packedint32array.html#class-packedint32array) versus Array[int]). Also, packed arrays consume less memory. As a downside, packed arrays are less flexible as they don't offer as many convenience methods such as [Array.map](https://docs.godotengine.org/en/latest/classes/class_array.html#class-array-method-map). Typed arrays are in turn faster to iterate on and modify than untyped arrays.

Reading this, I understand that for performance, `Packed` arrays are optimal, followed by typed `Arrays`, followed by untyped `Arrays` and that `Packed` arrays simply don't have some convenience methods. So if I just want to store an unknown amount of data in an array and I know I only care to iterate over it and add to it, it makes sense to use a `Packed` array type.

Yet in the [gdscript reference](https://docs.godotengine.org/en/latest/tutorials/scripting/gdscript/gdscript_basics.html#packed-arrays) it says:

> GDScript arrays are allocated linearly in memory for speed. Large arrays (more than tens of thousands of elements) may however cause memory fragmentation. If this is a concern, special types of arrays are available. These only accept a single data type. They avoid memory fragmentation and use less memory, <ins>**but are atomic and tend to run slower than generic arrays**</ins>. They are therefore only recommended to use for large data sets

From this I understand that even regular, untyped arrays are allocated linearly in memory. Since this can cause fragmentation, we are provided with `Packed` versions of `Array` but those will be **slower** (which I can only interpret as slower to iterate over and modify, since the way in which they are slower is unspecified) than a regular `Array`. Thus if I want to store an unknown amount of data, there is no clear answer: if I want speed, I should use a regular `Array`, if I'm concerned about fragmentation or memory usage, I should use a `Packed` array type.

**Context, if informative**

For reference on what context led me to this, I'm making a 2d graphing UI element and I want to decide on whether to use `Packed` or typed Arrays as the input type for the data. Since I don't know the size of my dataset (it can be per second samples or per frame samples, which would quickly escalate the array sizes to thousands of elements), what I choose may or may not have an impact on memory usage or performance but I want to pick the safest one for both.

My assumption (prior to re-reading the documentation) was that, intuitively, `Packed` array types should be more efficient in both memory usage and iteration, but might be less efficient when it comes to adding or removing elements (because I'm thinking of them as low-level arrays, a pointer to an offset in allocated memory, where the index is a multiple of a data type size). I searched for answers online and the only properly relevant result I found with this prompt: "are packed arrays faster or slower godot", was [this one](https://www.reddit.com/r/godot/comments/1af73re/packed_arrays/), where the confusion of the OP is the same as mine.

I don't know if the documentation is technically correct and both myself and others are misunderstanding what it means (in which case it should be worded more clearly) or if the contradiction is genuine when read in the context we are considering for array usage. Either way, I don't know what the correct statement is about the performance of array classes, so I didn't open a pull request to fix it.

**Comment by clayjohn** [comment]
The description in the GDScript docs is outdated and no longer applies. 

In Godot 3 we used Pool***Arrays which weren't linearly allocated and indeed could have worse performance than a regular array in some cases. 

Now, both Packed arrays and GDscript arrays can cause fragmentation. And the performance is similar but Packed arrays are faster in a few places. I am 99% that Packed arrays will be faster or as fast as regular arrays in all situations.

**Comment by mechalynx** [comment]
So would this be an accurate correction for the text in the gdscript reference?

Original:
> GDScript arrays are allocated linearly in memory for speed. Large arrays (more than tens of thousands of elements) may however cause memory fragmentation. If this is a concern, special types of arrays are available. These only accept a single data type. They avoid memory fragmentation and use less memory, but are atomic and tend to run slower than generic arrays. They are therefore only recommended to use for large data sets

Amended (based on the paragraph in the class reference):
> PackedArrays are generally faster to iterate on and modify compared to a typed Array of the same type (e.g. PackedInt32Array versus Array[int]) and consume less memory. In the worst case, they will be as fast as a regular Array. Conversely, non-Packed Arrays (typed or not) have extra convenience methods such as [Array.map](https://docs.godotengine.org/en/latest/classes/class_array.html#class-array-method-map) that PackedArrays lack. Consult the [class reference](https://docs.godotengine.org/en/latest/classes/class_packedint32array.html#class-packedint32array) for details on the methods available. Typed Arrays are in turn faster to iterate on and modify than untyped Arrays.
> 
> While all Arrays can cause memory fragmentation if large enough, if memory usage and performance (iteration and modification speed) is a concern and the type of data you're storing is compatible with one of the `Packed` Array types, then using those may yield improvements. However, if you do not have such concerns (e.g. the size of your array does not reach the tens of thousands of elements) it is likely more helpful to use regular or typed Arrays, as they provide convenience methods that can make your code easier to write and maintain (and potentially faster if your data requires such operations a lot). If the data you will store is of a known type (including your own defined classes), prefer to use a typed Array as it may yield better performance in iteration and modification compared to an untyped Array.

If this is good enough, I can open a pull request with this change and also add the mentioned paragraph from the class reference to the classes that lack it (`PackedInt32Array`, `PackedFloat32Array`, `PackedVector4Array` and `PackedByteArray`) unless it doesn't apply to them.

**Comment by tetrapod00** [comment]
That updated summary looks pretty good to me, but I'm not an expert on the internals. I'd suggest submitting it as a PR and we can use GitHub's review features to review rather than going back and forth in an issue 🙂 

For the class reference I *think* that the note can be added to classes which currently lack it, though note that those changes will happen in the main repo, not here. The class reference in this repo is generated from the XML version in the main repo. We have a tutorial about how to update the class ref [here](https://docs.godotengine.org/en/stable/contributing/documentation/updating_the_class_reference.html).

**Comment by mechalynx** [comment]
I forgot the class reference is built from the main repo. So that will be a separate PR.

I'll make a PR in this repo about the documentation change 👍
