### ISSUE TITLE
Godot Docs on vrs no longer accurate

### ISSUE THREAD

**Issue by jamie-pate** [godotengine/godot-docs#10320]
This note says:
```RST
    The Compatibility rendering method does **not** support variable rate
    shading.
```
https://github.com/godotengine/godot-docs/blob/master/tutorials/3d/variable_rate_shading.rst?plain=1#L89

But VRS is now supported in the compatibility renderer.

I would update the docs but I don't understand all the limitations of this system.

See also:
https://github.com/godotengine/godot/pull/93685
https://github.com/godotengine/godot/pull/89894
https://github.com/godotengine/godot/pull/80881
https://github.com/godotengine/godot/pull/60901

**Comment by Calinou** [comment]
As I understand it, the implementation is limited to support in OpenXR, so you can't use an arbitrary texture as the VRS fragment density map.

cc @BastiaanOlij

**Comment by BastiaanOlij** [comment]
Indeed, on compatibility its a feature of OpenXR and ONLY works in VR situations, not of Godots rendering engine, and it will be disabled in many situations (enabling post effects, screen reading, scaling, etc.). And it is a totally different system from Godots VRS implementation.

The XR docs reflect this already and I feel that is enough. Those who are interested in using VRS outside of XR will only be put on the wrong path.
