### ISSUE TITLE
Very large generated HTML files for the class reference

### ISSUE THREAD

**Issue by Calinou** [godotengine/godot-docs#1032]
The generated HTML files for the class reference are very large; each file is around 500 KB each, amounting to a whopping 232 MB `classes/` directory (uncompressed). They seem to contain lots of duplicated code related to the navigation bar.

![File sizes](https://user-images.githubusercontent.com/180032/35473905-efb1eb2c-0386-11e8-9a15-d4de61d22ff0.png)

Example: [class_area.html.zip](https://github.com/godotengine/godot-docs/files/1670239/class_area.html.zip)

**Comment by akien-mga** [comment]
Well that's static HTML, so yes all pages have the complete code for the navbar.

**Comment by Calinou** [comment]
There isn't much that can be done about it, so I'll close this.
