### ISSUE TITLE
Elements are not scrollable in the left nav

### ISSUE THREAD

**Issue by hakanguclu** [godotengine/godot-docs#10352]
**Your Godot version:** Not applicable.

**Issue description:** This issue only happens when viewing the "stable" or versioned docs. It doesn't happen when viewing the "latest" docs. If pages/subpages are expanded in the left nav, the container element becomes scrollable as expected, but it becomes impossible to scroll elements listed at the very top into view. This is due to the fact that container's top margin is set to a fixed number and it's not large enough to accommodate for the "version" and "language" dropdowns that appear when viewing the docs in "stable" or versioned mode. The expected behavior is that the scroll container should dynamically fill the available space in the left nav.

**URL to the documentation page:** Any page. For example: [docs.godotengine.org/en/stable](https://docs.godotengine.org/en/stable/)

**Comment by hakanguclu** [comment]
I opened a PR that fixes this issue: [add flex layout for left nav container](https://github.com/godotengine/godot-docs/pull/10353)

**Comment by LBWright** [comment]
I experienced the same issue. Adding a quick screencast. https://github.com/user-attachments/assets/63411c12-278a-4d8e-9039-2786ad8aed70

**Comment by hakanguclu** [comment]
Closing this issue as [commit 7a79288](https://github.com/godotengine/godot-docs/commit/7a792883194982759aa4286103f172d1579c5fc2) fixes it.
