### ISSUE TITLE
suggest C# addons

### ISSUE THREAD

**Issue by ghost** [godotengine/godot-docs#1039]
hey @reduz and @akien-mga  let's all spend our precious fucking time on some more C# development instead of releasing 3.0

sounds like a god damn fucking plan eh.

bcz mahh C# is sooo much better than fucking Gd Script..yeah no.

https://github.com/godotengine/godot/issues/16127
https://github.com/godotengine/godot/issues/16107
https://github.com/godotengine/godot/issues/16024
https://github.com/godotengine/godot/issues/15923
https://github.com/godotengine/godot/issues/15913
https://github.com/godotengine/godot/issues/15779
https://github.com/godotengine/godot/issues/15763
https://github.com/godotengine/godot/issues/15615
https://github.com/godotengine/godot/issues/15548
https://github.com/godotengine/godot/issues/15371
https://github.com/godotengine/godot/issues/15208
https://github.com/godotengine/godot/issues/15053

want more?

**Comment by DroppingBass** [comment]
https://github.com/godotengine/godot/issues/13922
https://github.com/godotengine/godot/issues/13837
https://github.com/godotengine/godot/issues/13355
https://github.com/godotengine/godot/issues/13007
https://github.com/godotengine/godot/issues/12917
https://github.com/godotengine/godot/issues/12441

get your shit together. C# is a waste of time.

**Comment by DroppingBass** [comment]
gdscript > C#

2d > 3d development

truth fucking hurts

**Comment by DroppingBass** [comment]
engine being hindered by incompetent leadership.
