### ISSUE TITLE
how the godot community treats other human beings

### ISSUE THREAD

**Issue by ghost** [godotengine/godot-docs#1041]
hint: like absolute fucking garbage.

![4](https://user-images.githubusercontent.com/35906388/35490039-97a9a908-0451-11e8-99de-0bd5cbad8fc2.PNG)
![1](https://user-images.githubusercontent.com/35906388/35490040-97d28b48-0451-11e8-9501-42bd0fdc5c0f.PNG)
![2](https://user-images.githubusercontent.com/35906388/35490041-97ea7cd0-0451-11e8-9b7d-07947cd7ab38.PNG)
![3](https://user-images.githubusercontent.com/35906388/35490042-9801156c-0451-11e8-8265-ec4e1307975d.PNG)

@reduz looks like @akien-mga has quite the leadership going over there. great leadership skills! +1!

**Comment by DroppingBass3** [comment]
beautiful and gracious community!
