### ISSUE TITLE
Your first 3D game - no collision detected with "group"

### ISSUE THREAD

**Issue by flochocinco** [godotengine/godot-docs#10420]
**Which demo project is affected:**
Your first 3D game

**Issue description:**
Following tuto, I'm unable to complete "Jump and Squash monsters".

I notice in debug that if condition is never true:
`if collision.get_collider().is_in_group("mob"):`

I probably miss something by reading but if someone want to have a look to my project, I uploaded it here:
https://github.com/flochocinco/Godot_First3dGame

I also noticed that by applying masks and layers monsters do not collide (i.e. stop) against player.

**Comment by flochocinco** [comment]
opened at https://github.com/godotengine/godot-demo-projects/issues/1148

**Comment by tetrapod00** [comment]
I believe the issue was moved here because if you followed the tutorial and the instructions were wrong, it is a problem with the tutorial, not with the demo project, and belongs in this repo.

**Comment by aaronfranke** [comment]
Your game isn't working because the enemies are simply lower than the player. You can fix it by raising the enemies, lowering the player, or making the enemy collision shapes taller.

If there is any tweak we can make to the docs to make this clearer, you are welcome to point out what's missing.

**Comment by flochocinco** [comment]
"because the enemies are simply lower than the player" -> True! I don't understand why the player is not touching the ground. There is no offset (i.e. transform). I tried to offset the hit box of the player but even with that, no collisions are detected.

Is there a way to show hit boxes at run time ?

**Comment by aaronfranke** [comment]
Yes: Debug -> Visible Collision Shapes.

**Comment by flochocinco** [comment]
Thank you @aaronfranke. I figured out my ground collision box was y:1 above
