### ISSUE TITLE
"stable" docs namespace still points to the 2.1 branch

### ISSUE THREAD

**Issue by Omicron666** [godotengine/godot-docs#1052]
![](https://i.imgur.com/EEF4hzj.png) is pointing to http://docs.godotengine.org/en/stable/learning/step_by_step/index.html that is correect but... we see nowhere it is 3.0 and clicking top link 
![](https://i.imgur.com/QbxHCFr.png)

displays a outdated homepage : ![doc homepage](https://i.imgur.com/I1igJvZ.png)

**Comment by akien-mga** [comment]
Same reason as #1051.

**Comment by akien-mga** [comment]
@ericholscher @agjohnson Sorry for the ping, but I think this can only be fixed manually by RTD admins.

A couple weeks ago we created a `3.0` branch here, and the `stable` version was moved from `2.1` to `3.0` (as it should I guess, but that's not what we wanted as our 3.0 version had not been released yet). So I deleted the `3.0` branch, and Eric fixed the issue by resetting our `stable` version to f0c19af (HEAD of our `2.1` branch).

Now 3.0 is released and we want the `stable` version to track the HEAD of the new `3.0` branch, but it doesn't move. I've tried wiping the `stable` version, creating a `3.0` tag, but nothing works. I guess f0c19af is now hardcoded. Could you fix it to make it point to our `3.0` branch (and it should get updated when we push new commits on `3.0`)?

Alternatively, we would *strongly* benefit from an option to configure the behavior of the `stable` version ourselves. I understand the logic behind it, but it doesn't seem to work in all use cases (at least doesn't in ours, where we don't tag stable releases but use stable branches).

**Comment by akien-mga** [comment]
@ericholscher @agjohnson Bump. We have hundreds of users landing on the outdated "stable" version every day and getting very confused. Our only alternative is to disable the "stable" version, and have them land on 404's...

**Comment by ericholscher** [comment]
Is it possible to create a `stable` branch for a short term workaround?

**Comment by ericholscher** [comment]
Sorry, just _really_ busy currently, and fixing this is complciated. I'll try and get to it soon with a proper fix, but it's a complex thing.

**Comment by Omicron666** [comment]
@ericholscher 
It is true that http://docs.godotengine.org/en/latest/ and http://docs.godotengine.org/en/stable/ are offering links each others, but they are no more first timer landing pages.
_The immediate urgent issue, directing people to old stable by default seems solved._

http://docs.godotengine.org/ is now redirecting to http://docs.godotengine.org/en/3.0/
Also currently browsed doc version now noticeably displays its version. 
![](https://i.imgur.com/70RkJnk.png)
also true for latest, 2.1 and... "stable".
"stable" still being 2.1 there, though.

**Comment by akien-mga** [comment]
I'll go for a "stable" Git branch as a workaround for now, thanks for the advice.

**Comment by akien-mga** [comment]
It looks like adding a `stable` Git branch did the trick. I'll just have to sync the `3.0` and `stable` branches manually (and thus have duplicate builds) until a better solution can be found.
