### ISSUE TITLE
Mention that some SurfaceTool related functions only work with PRIMITIVE_TRIANGLES

### ISSUE THREAD

**Issue by LunaSquee** [godotengine/godot-docs#1058]
Recently, I have been working with SurfaceTool and I noticed that some functions don't work with anything but PRIMITIVE_TRIANGLES.

**SurfaceTool** `generate_normals()` checks for PRIMITIVE_TRIANGLES explicitly but it isn't mentioned in the documentation.
**Mesh** `get_faces()` seems to return an empty array when the mesh is not made using PRIMITIVE_TRIANGLES.

There might be more but this is what I've noticed.

**Comment by LunaSquee** [comment]
Oh no, I just noticed that the classes aren't a part of this repository. I'm sorry, I should've ensured that before creating an issue. I don't know if I need to close this or not

**Comment by NullConstant** [comment]
Best to close this one and open a new issue in the engine repo proper.

**Comment by LunaSquee** [comment]
Okay, thanks
