### ISSUE TITLE
Godot documentation website does not serve content over HTTPS

### ISSUE THREAD

**Issue by gemkibeju** [godotengine/godot-docs#1060]
Trying to connect to "https://docs.godotengine.org" makes Firefox give the following error:

> docs.godotengine.org uses an invalid security certificate.
> The certificate is only valid for the following names:
> *.readthedocs.io, readthedocs.io 

Therefore I cannot view the Godot documentation over HTTPS.

**Comment by vnen** [comment]
You can access with this link: https://godot.readthedocs.io

**Comment by mhilbrunner** [comment]
Duplicate of https://github.com/godotengine/godot-docs/issues/146.
