### ISSUE TITLE
Little errata on Image class page

### ISSUE THREAD

**Issue by CarlosAlmarcha** [godotengine/godot-docs#1065]
int get_format ( ) const
**Returns the image’s raw data.**

I think that description has been duplicated from the previous description.
I assume It should probably says: **Returns the image’s format. See FORMAT\_\* constants.**

**Comment by RiverMesa** [comment]
This seems right, but documentation of the API should be done/discussed in the [godot](https://github.com/godotengine/godot) repo itself. From the README:

>Note that the pages in classes/ should not be edited here, they are automatically generated from Godot's XML class references.

So you should probably close this issue and re-open it in the other repo.
