### ISSUE TITLE
UI Anchors relative to the Parent's Pivot ? (not Bounding Box)

### ISSUE THREAD

**Issue by AntohaRDNS** [godotengine/godot-docs#1067]
Path: 
Step by Step  >  Design interfaces with the Control nodes   >    Anchors are relative to the parent container. 

Maybe I'm wrong. But my tests tells that : 
UI Anchors relative to the Parent's Pivot, not Parent's Bounding Box
https://yadi.sk/i/6J9rX3483Rxw6P

**Comment by NathanLovato** [comment]
The system changed after I made this picture. In Godot 2 and 3 up to alpha you'd select the edge the anchor would be relative to

**Comment by NathanLovato** [comment]
Fixing it tonight after work

**Comment by NathanLovato** [comment]
Okay just checked and no, the anchors are not relative to the parent's pivot.

They are still relative to the parent container, and the diagram is correct although I'll admit it's not as clear as it could be. I think to explain the behavior well it'd be best to have at least 2 pictures or better: an animated gif. If anyone is up for the task they can open a new issue or file a PR.

### Regarding anchors

Each anchor value represents a ratio of a control's parent container's width or height and sets this as a reference point to calculate the margins for the corresponding edge. 

There was a typo in the diagram though, just fixed it. Thanks!
