### ISSUE TITLE
Page for performance tips / best practices

### ISSUE THREAD

**Issue by mhilbrunner** [godotengine/godot-docs#1073]
Initially mentioned in https://github.com/godotengine/godot-docs/issues/66.

**Comment by NathanLovato** [comment]
I'd recommend to focus on the profiler first and avoid too generic code performance tips, at least when it comes to GDscript. In my experience working on mobile the main bottleneck has always been rendering. Today unless you target low-end phones it's hard to push a device to its limits without a big... leak? in the code.

Considering the original issue seemed to talk more about gameplay programming. Best practices is also a different story to me - it's more about code and project structure, decoupling.

For beginners and not so experienced developers I think it'd be more useful to insist on the fact that performances come last in game creation. First make sure your gameplay works, that the scope is right - then use the profiler to see where there are chunks of code worth refactoring and optimizing.

**Comment by mhilbrunner** [comment]
Thinking about it some more, you are right: this will probably be best served by existing pages, in part by the existing project workflow page (for best practices), the existing GDScript pages (for some gotchas/performance tips) and the debugger/profiler page (https://github.com/godotengine/godot-docs/issues/160).

Closing this for now.
