### ISSUE TITLE
Update Kinematic Character (2D) Page

### ISSUE THREAD

**Issue by skyace65** [godotengine/godot-docs#1074]
The Kinematic Character (2D) page needs to be updated for 3.0. I'm going to go through and replace all outdated images, update the assets .zip file, make sure the code still works. And if possible add the C# equivalent.

**Comment by cbscribe** [comment]
If you can, this would be the perfect use for the codeblock tabs, as in http://docs.godotengine.org/en/latest/getting_started/step_by_step/scripting.html

**Comment by skyace65** [comment]
Don't worry, I was already planning on doing that.
