### ISSUE TITLE
Update Vector2 2.1 documentation?

### ISSUE THREAD

**Issue by Kinrany** [godotengine/godot-docs#1078]
2.1 docs still [have](https://godot.readthedocs.io/en/2.1/classes/class_vector2.html#class-vector2-reflect) these:

> * Vector2 slide ( Vector2 vec )
> Slides the vector by the other vector.
> * Vector2 reflect ( Vector2 vec )
> Like “slide”, but reflects the Vector instead of continuing along the wall.

However 3.0 docs [have already been updated](https://godot.readthedocs.io/en/3.0/classes/class_vector2.html#class-vector2-reflect) to be more explanatory:

> * Vector2 slide ( Vector2 n )
> Slide returns the component of the vector along the given plane, specified by its normal vector.
> * Vector2 reflect ( Vector2 n )
> Reflects the vector along the given plane, specified by its normal vector.

Could the 2.1 docs be also updated with changes like these?

---

I also noticed that in 2.1 it's `normal.reflect(vector)` and not `vector.reflect(normal)` despite the variable being named `n` in the updated docs. I can't tell if this is an error or a breaking change between 2.1 and 3.0.

**Comment by akien-mga** [comment]
> I also noticed that in 2.1 it's normal.reflect(vector) and not vector.reflect(normal) despite the variable being named n in the updated docs. I can't tell if this is an error or a breaking change between 2.1 and 3.0.

It's a breaking change, so the 3.0 docs don't apply to the 2.1 case. But the 2.1 docs could be updated nevertheless to be clearer.

**Comment by akien-mga** [comment]
It has to be done in the code repository though: https://github.com/godotengine/godot/blob/2.1/doc/base/classes.xml

**Comment by Kinrany** [comment]
I see. I'll fix these two by hand, but can this be done automatically in any way?

**Comment by akien-mga** [comment]
Well writing documentation sentences can't really be automatized :)

Once updated in the docs repo, the online docs can be automatically updated, yes.

**Comment by pwab** [comment]
@akien-mga as the referenced PR was merged manually: is this issue solved then?

**Comment by akien-mga** [comment]
Yes.
