### ISSUE TITLE
Outdated instructions on exporting via command line

### ISSUE THREAD

**Issue by anakimluke** [godotengine/godot-docs#1079]
The code on the [Exporting](http://docs.godotengine.org/en/3.0/getting_started/editor/command_line_tutorial.html#exporting) section of the Command line tutorial page seems to be outdated.
The `-export` option needs to have two tacs at the beginning, like `--export`.
Even after adding the tac, the command `godot.exe --export my_export_preset_name game.exe` won't work.
I found that the following commands seem to work properly:
- `godot.exe my_game/project.godot --export my_export_preset_name game.exe` 
- `godot.exe -e my_game/project.godot --export my_export_preset_name game.exe` 
- `godot.exe --path my_game --export my_export_preset_name game.exe`

Tested on windows and linux.

**Comment by skyace65** [comment]
I'll double check this myself later and make a pull request

**Comment by skyace65** [comment]
I'm having trouble figuring out how to use the command line and I've been busy with other pull requests. I'd reccomend you make a PR to fix this yourself. If you don't know how there's a great guide on the docs [here](http://docs.godotengine.org/en/3.0/community/contributing/pr_workflow.html)

**Comment by anakimluke** [comment]
I would only write based on my guess of how everything works. I think it's better for someone who's read the source code and really knows how it is supposed to work to write the documentation.
