### ISSUE TITLE
String.format examples

### ISSUE THREAD

**Issue by AlexHolly** [godotengine/godot-docs#1080]
Some doc requested in https://github.com/godotengine/godot/issues/5493 for String.format(..)
A quick rewrite from the examples in PR https://github.com/godotengine/godot/pull/5649

Maybe we can add ~3 examples to the String class?
```
#	- No difference between "3.0" String or 3.0 as Float
#	- Choose custom placeholder with pre,in or postfix
#	- Use Array or dictionary both support replacing by index/order or key
#	For more details see https://github.com/godotengine/godot/pull/5649

	#1. Array with dict style
	"Hi, {NAME}({version})".format([["NAME","Godette"],["version","3.0"]]) # "Hi, Godette(3.0)"
	"Hi, {NAME}({version})".format([["version","3.0"],["NAME","Godette"]]) # "Hi, Godette(3.0)"
	
	#2. Array index 
	"Hi, {0}({1})".format(["Godette",3.0]) # "Hi, Godette(3.0)"
	"Hi, {1}({0})".format([3.0,"Godette"]) # "Hi, Godette(3.0)"
	
	#3. Mixed array
	"Hi, {NAME}({0})".format([3.0,["NAME","Godette"]]) # "Hi, Godette(3.0)"
	
	#4. Custom placeholder, array as dict style
	"Hi, (NAME)((version))".format([["NAME","Godette"],["version",3.0]],"(_)") # "Hi, Godette(3.0)"
	
	#5. Custom placeholder, array
	"Hi, (0)((1))".format(["Godette",3.0],"(_)") # "Hi, Godette(3.0)"
	
	#6. With string,int,float as key and value
	"Hi, {NAME}({1})".format([["NAME","Godette"],[1,3.0]]) # "Hi, Godette(3.0)"

	#7. With int as value
	"Hi, {0}({1})".format(["Godette",3]) # "Hi, Godette(3)"

	#8. postfix
	"Hi, 0[](1[])".format(["Godette","3.0"],"_[]") # "Hi, Godette(3.0)"
	
	#9. prefix
	"Hi, []0([]1)".format(["Godette","3.0"],"[]_") # "Hi, Godette(3.0)"

	#10. dictionary
	"Hi, {NAME}({version})".format({"NAME":"Godette","version":"3.0"}) # "Hi, Godette(3.0)"
```

Any ideas where to put it?

What examples would be best?
I use dictionary(10.) most of the time.

@Gfurst Any example you would prefer to see in the String class?

**Comment by vnen** [comment]
It can be added to the page about formatting strings: http://docs.godotengine.org/en/3.0/getting_started/scripting/gdscript/gdscript_format_string.html

**Comment by mhilbrunner** [comment]
So, there are now two ways to format strings with place holders in Godot?
The `%` operator and the `string.format` way added by this PR, if I got this right?

Seems confusing to have two ways to do something with different syntax and feature sets?

**Comment by Gfurst** [comment]
that's pretty good @AlexHolly, I agree that it should go on the page documentation instead, perhaps a more detailed version, something simpler on the class reference.
also try to include something more textually descriptive, for example:
> it takes two arguments, the first being what is replacing the placeholder, the second being an optional  custom placeholder tag, ~~only the first and last characters matter on the string~~
> the placeholder argument can take the form of a dictionary, containing key : value pairs, or a ordered array, with the keys being enumerated
> (?¿) it will replace all matched placeholders, and can take any number of matching

**Comment by AlexHolly** [comment]
Quick first version
Method description missing something like
String.format( var values, String placeholder={_} )

If any docs expert wants to take these information feel free to make any changes and open a PR (otherwise I would have to figure out how the adding docs process works).

----------
`String.format` replaces all key occurrences with the corresponding value. 
The method can handle Arrays and Dictionaries.
- Numbers can be represented as Strings 
	- 3	is the same as "3"
	- 3.0 is the same as "3.0"
- Arrays can be used as key, index or mix style (see examples)
- Order only matters in Arrays used with index or mix style.

# Usage Examples
|Type|Style|Example|Result
|---|---|---|---|
|Dictionary|key|"Hi, {NAME} ({version})".format( {"NAME":"Godette", "version":"3.0"} )|Hi, Godette (3.0)
|Dictionary|index|"Hi, {0} ({1})".format( {"0":"Godette", "1":"3.0"} )| Hi, Godette (3.0)
|Dictionary|mix|"Hi, {0} ({version})".format( {0:"Godette", "version":"3.0"} )|Hi, Godette (3.0)
|Array|key |"Hi, {NAME} ({version})".format( [["version","3.0"], ["NAME","Godette"]] )"|Hi, Godette (3.0)
|Array|index|"Hi, {0} ({1})".format( ["Godette", 3.0] )|Hi, Godette (3.0)
|Array|mix|"Hi, {NAME} ({0})".format( [3.0, ["NAME", "Godette"]] )|Hi, Godette (3.0)


# Placeholder Examples
|Type|Example|Result
|---|---|---|
|Infix(default)        |"Hi, {0} ({1})".format( ["Godette", "3.0"], "{_}" )|Hi, Godette (3.0)
|Postfix        |"Hi, 0% (1%)".format( ["Godette","3.0"], "_%" )|Hi, Godette (3.0)
|Prefix        |"Hi, %0 (%1)".format( ["Godette","3.0"], "%_" )|Hi, Godette (3.0)

# Compare format and %
`String.format` simulates the index behavior by using the Array index as a key where `%` works without any keys. `String.format` has no way to manipulate the representation of numbers.

Example (`format` and `%` in one)|Result
|---|---|
|"Hi, {0} ({version})".format( {0:"Godette", "version":"%0.2f"%3.12345} )|Hi, Godette (3.12)
