### ISSUE TITLE
Dodge the Creeps tutorial code throws an error

### ISSUE THREAD

**Issue by adrinux** [godotengine/godot-docs#1089]
(submitting on behalf of my children)
Working through the [Moving the player](http://docs.godotengine.org/en/3.0/getting_started/step_by_step/your_first_game.html#moving-the-player) section when they 'play the edited scene' this error is thrown:
```
error(26,1): Unexpected token: Identifier:position
```
Here is the code they've entered:
```
extends Area2D

export (int) var SPEED
var velocity = Vector2()
var screensize 

func _ready():
    screensize = get_viewport_rect().size

func _process(delta):
    velocity = Vector2()
    if Input.is_action_pressed("ui_right"):
        velocity.x += 1
    if Input.is_action_pressed("ui_left"):
        velocity.x -= 1
    if Input.is_action_pressed("ui_down"):
        velocity.y += 1
    if Input.is_action_pressed("ui_up"):
        velocity.y -= 1
    if velocity.length() > 0:
        velocity = velocity.normalized() * SPEED
        $AnimatedSprite.play()
    else:
        $AnimatedSprite.stop()

position += velocity * delta
position.x = clamp(position.x, 0, screensize.x)
position.y = clamp(position.y, 0, screensize.y)
```
Followed through the tutorial myself and cant see anything wrong with what they've entered. Any clue what is going wrong?

**Comment by cbscribe** [comment]
Your indentation is incorrect. Those last three lines are part of the `_process()` function, so they need to be indented.
