### ISSUE TITLE
Tutorials > Networking should introduce HTTPRequest (or prior to HTTPClient)

### ISSUE THREAD

**Issue by Omicron666** [godotengine/godot-docs#1103]
Here:
![Networking tutorials](https://i.imgur.com/JqSSodP.png)

Although http://docs.godotengine.org/en/3.0/tutorials/networking/http_client_class.html is a good example of using the HTTPClient class... 
For most use, imho, at least as first tutorial about requesting online resources, people could be suggested using [HTTPRequest](http://docs.godotengine.org/en/3.0/classes/class_httprequest.html) instead, handling redirects and offering signals (and using [HTTPClient](http://docs.godotengine.org/en/3.0/classes/class_httpclient.htm) internally).

**Comment by akien-mga** [comment]
Yes, the docs is like this only because the HTTPClient page was written before HTTPRequest was added. It definitely needs to be reworked into a better page/subsection about low level networking interfaces.

**Comment by mhilbrunner** [comment]
Done with https://github.com/godotengine/godot-docs/pull/1129.
