### ISSUE TITLE
'Your first game' > Moving the player > picture doesn't match the text

### ISSUE THREAD

**Issue by StraToN** [godotengine/godot-docs#1104]
In 'Your first game' > Moving the player section, the text says:

> Now we need to add some functionality that we can't get from a built-in node, so we'll add a script. Click the Player node and click the "Add Script" button:

But the image shows the `CollisionPlayer2D` node selected instead of `Player` node.

![image](https://user-images.githubusercontent.com/1289207/35802447-729e3f46-0a70-11e8-94e4-583e55aa0d2b.png)

https://github.com/godotengine/godot-docs/blob/3.0/getting_started/step_by_step/your_first_game.rst#moving-the-player

**Comment by cbscribe** [comment]
Good catch! I can probably update that this evening if nobody does it first.

**Comment by cbscribe** [comment]
Fixed via fb3be90
