### ISSUE TITLE
EditorInterface.get_editor_viewport() is confusing

### ISSUE THREAD

**Issue by EliasWatson** [godotengine/godot-docs#1109]
`EditorInterface.get_editor_viewport()` returns a `Control` object, but the description and name implies it returns a `Viewport` object. @vnen said the function actually returns the root node of the interface.

The docs should be edited to clarify what this function actually does.

**Comment by vnen** [comment]
Honestly, the whole docs for EditorInterface are pretty bad, it should be remade. Most of the docs are just the function name rearranged to the English grammar.

I originally added a more relevant description when I [first exposed the function](https://github.com/godotengine/godot/pull/6516/files#diff-033f70b20096c319b4a901f4b9e13369R11704), but apparently it was lost in the rearrangements.
