### ISSUE TITLE
Picture under "Creating a theme" is incorrect

### ISSUE THREAD

**Issue by vjrossi** [godotengine/godot-docs#112]
In the "GUI skinning" section, under "creating a theme" it should show a relevant UI image for creating a theme, but instead repeats the previous image.

**Comment by akien-mga** [comment]
Indeed. It looks like it has always been this way, so we probably don't have the proper image around, it would have to be created.

**Comment by RayKoopa** [comment]
I could provide the image, though all images probably need some update as they all still have this older interface skin and style.

**Comment by mhilbrunner** [comment]
Closing this, tracker by the broader issue https://github.com/godotengine/godot-docs/issues/946.
