### ISSUE TITLE
AudioStreamPlayback sample code is a memory leak on deallocation

### ISSUE THREAD

**Issue by hungrymonkey** [godotengine/godot-docs#1120]
I realize that the example code I wrote will memory leak a little bit on every deallocation. Although the code is only useful for bootstrapping, I wondering if a proper deconstructor should be added to encourage good practices.

http://docs.godotengine.org/en/latest/development/cpp/custom_audiostreams.html
```
AudioStreamPlaybackMyTone::~AudioStreamPlaybackMyTone(){
if (pcm_buffer) {
		AudioServer::get_singleton()->audio_data_free(pcm_buffer);
		pcm_buffer = NULL;
}
}
```

we something along the lines of this code.

**Comment by mhilbrunner** [comment]
Probably a good idea :)

**Comment by hungrymonkey** [comment]
@mhilbrunner i dont have time to fix it right now. I might fix it in a few weeks or so. I am doing something right now.
