### ISSUE TITLE
Official Dark theme

### ISSUE THREAD

**Issue by Chaosus** [godotengine/godot-docs#1122]
Currently its existed as one css theme for Stylish/Stylus plugins (in chromium browser), but its not good for mobile cuz its real headache to install these plugins into mobile browser(and I dont know browsers which supports it). And this theme is outdated, means it contains some incorrect colors. So, it would be good if the docs give official dark theme switch (directly inside site) without required plugins..

**Comment by mhilbrunner** [comment]
This should only be done officially if there is enough demand for it, if at all, as it requires maintaining two different themes.

**Comment by Iskustvo** [comment]
Sorry, I am new to Godot, so I have to ask this question :D
Can you explain to me how, where and who is able to "demand" this feature?

Since I am new here, most of the time I'm looking at the documentation and for me, the mentioned Stylish dark theme is way more relaxing.
Like @Chaosus stated, that theme is outdated and can't be used all the time, so I agree that there should be official light and dark themes for the documentation, just like there are light and dark themes for the engine.

**Comment by mhilbrunner** [comment]
Well, everyone can "demand" it (by asking nicely or simply voicing their support).

If it seems this is something a large-ish part of the community wants, there is more reason to implement it.

**Comment by Iskustvo** [comment]
First of all, thank you for a quick reply!
But the most important part of that question was "where".
Should I just "Thumbs up" the comment or will there be some formal kind of discussion?

**Comment by mhilbrunner** [comment]
No, sure, thumb ups are enough :)

**Comment by pwab** [comment]
> [...] it would be good if the docs give official dark theme switch (directly inside site)

If I am not wrong it is only possible to use the default blueish sphinx theme instead of the rtd-theme (see [rtd faq](https://docs.readthedocs.io/en/latest/faq.html#i-want-to-use-the-blue-default-sphinx-theme) for reference). So there is no way of integrating such a theme switch into the docs rtd pages.

As a workaround to achieve this on mobile you can download the html build and alter the css files according to your needs. But this would be a tedious task I guess.

**Comment by Chaosus** [comment]
I thought its possible to implement, I dont know about Sphinx/web so much, and just asking about possibility. I hope there is some experienced web-programmers that could do this at some point of time.

**Comment by NathanLovato** [comment]
From the css's standpoint it's not impossible, although sphinx's styles are complex (~5000 lines of css, half of which is font-awesome). But there's no built-in tool to let the users change the theme. As the website is static you'd probably have to embed some extra custom html/js in every single page to allow for this. I don't think it's that easy, the website couldn't remember your preference without storing some cookie... it's something that should be added upstream in the readthedocs project.

Instead it's possible to hit two birds with one stone if someone adds support for [Zeal](https://zealdocs.org/), which has a dark mode and you can change the theme (like any Qt application): see #252

**Comment by OvermindDL1** [comment]
Firefox on mobile supports extensions fine, and I use a dark reader extension to flip everything to dark themed, however it also at times inverts colors on images (sometimes good, sometimes bad, depending on how the website displays the image).  A properly supported dark theme would be *substantially* preferred, even if it is just a simple cookie switch that adds a class to `body` if set.

**Comment by Calinou** [comment]
Note that the Godot documentation is already available in [DevDocs](http://devdocs.io/godot~2.1/), which has a dark theme option. However, it hasn't been updated to 3.0 yet.

**Comment by Iskustvo** [comment]
Thank you, but it looks like there is the same problem with dark theme and pictures in:
[StepByStep -> Instancing](http://devdocs.io/godot~2.1/learning/step_by_step/instancing)

**Comment by Chaosus** [comment]
@OvermindDL1 The dark reader extension overall looking good(thanks for pointing on firefox), but I think left panel should be dark in dark theme, and not all images should be inverted(yes I understand this plugin is just color inversion of whole output)

@Calinou additionaly it does not have so nice layout as official doc.

**Comment by Chaosus** [comment]
After searching a bit this plugin(exist both in firefox and chromium) does much more near to desirable result
than dark reader
![image](https://user-images.githubusercontent.com/3036176/36109772-6e7cae68-1031-11e8-8749-b56474cf324e.png)

![image](https://user-images.githubusercontent.com/3036176/36109880-ba20baf8-1031-11e8-9f43-ed58c9bb5d20.png)

**Comment by mhilbrunner** [comment]
Closing this as it seems hard to do with RTD currently, support will be via Zeal (https://github.com/godotengine/godot-docs/issues/252) or browser plugins for now.

**Comment by OvermindDL1** [comment]
Hard to do?  Shouldn't it be as easy as a couple lines of javascript to set/reset a special tag on body based on a toggle anchor and a cookie along with a css that specialized based on that tag class?

**Comment by Calinou** [comment]
For future reference, an official dark theme was implemented in #3056.
