### ISSUE TITLE
Write PR template to guide users to the master branch

### ISSUE THREAD

**Issue by mhilbrunner** [godotengine/godot-docs#1123]
Currently, a lot of new contributors submit PRs against the `3.0`.
I assume those should go against `master` instead, at least for the time being.

Manually merging those or asking all contributors one by one in each PR to use `master` gets tedious for both us and them.

What can we do to make this more obvious?

**Comment by mhilbrunner** [comment]
Any ideas, @akien-mga?

**Comment by vnen** [comment]
You can change the target branch in the PRs but I guess this might create some conflicts.

Maybe you can make a PR template to tell the contributor to check the target branch.

**Comment by RiverMesa** [comment]
A PR template is probably the best way to do it, yeah (`PULL_REQUEST_TEMPLATE.md`)


On a somewhat related but admittedly not 100% note, it would probably be a good idea to also include a statement in either the issue or PR template (or in both) about how the API reference is not to be discussed/made PRs for in this repo - even though it's already in the README and it's even bolded, people still do miss it sometimes.

**Comment by NathanLovato** [comment]
Yeah let's write issue and PR templates, maybe put them in the .github folder? Should I write these or you're taking care of it @mhilbrunner ? -> https://github.com/blog/2111-issue-and-pull-request-templates

**Comment by mhilbrunner** [comment]
Sure, I can do it.

**Comment by mhilbrunner** [comment]
@NathanLovato just made out another possible reason: When clicking on "Edit on GitHub" under docs.godotengine.org, you get redirected to https://github.com/godotengine/godot-docs/blob/3.0/index.rst - if you edit this, you end up making a PR against 3.0, not master.

**Comment by mhilbrunner** [comment]
Closing this, I created a PR template:
https://github.com/godotengine/godot-docs/blob/master/PULL_REQUEST_TEMPLATE.md

Additionally, I added a note in the README. However, I will create a new issue as we maybe need to fix the "Edit on GitHub" button on http://docs.godotengine.org.

**Comment by NathanLovato** [comment]
Can you move it to the .github folder, so we can put the issue template and pictures in there? Templates support markdown and I really think we should point people who use the "edit this file on GitHub" to the /latest version of the docs directly. It is also mostly an issue for people who edit from the docs.

**Comment by akien-mga** [comment]
The main issue is that most users are reading the `3.0` docs, as expected: http://docs.godotengine.org/en/3.0/

And there the "Edit on GitHub" button will bring them to the `3.0` branch for the target page, where they'll use the GitHub online editor and end up fixing stuff in that branch without even knowing about it.

Maybe we can find a way to override the "Edit on GitHub" link so that it always brings to the `master` branch (last I checked IIRC it wasn't possible, but maybe we could contribute such an option upstream).

**Comment by mhilbrunner** [comment]
Agree with both of you, which is why I opened https://github.com/godotengine/godot-docs/issues/1138
