### ISSUE TITLE
Tutorial request: How to implement laser with raycasts/particles

### ISSUE THREAD

**Issue by Burnsedia** [godotengine/godot-docs#1127]
We need a shooting with ray-cast ability for energy weapon's in Godot

**Comment by NathanLovato** [comment]
Is this a tutorial request? 2d? 3d? If there's none already, maybe a general tutorial about raycasting would be useful.

**Comment by mhilbrunner** [comment]
https://godot.readthedocs.io/en/3.0/tutorials/physics/ray-casting.html

https://godot.readthedocs.io/en/3.0/classes/class_raycast2d.html#class-raycast2d

https://godot.readthedocs.io/en/3.0/classes/class_raycast.html#class-raycast

(Although those could stand some updates)

If you meant something else, please be more specific. :)

**Comment by Burnsedia** [comment]
both 2d and 3d, when I was a unity user I make Laser weapons for my space games

**Comment by Burnsedia** [comment]
we also need a shooting with particles for both 2d and 3d

**Comment by pwab** [comment]
So it is more a tutorial request for _"How to implement laser with raycasts/particles"_ or something like that.
Should we create a dedicated tutorials tracker page for collecting such suggestions, @mhilbrunner?

**Comment by mhilbrunner** [comment]
@pwab I'll reopen this. I think we discussed this and decided to simply have an issue per tutorial request for now.

**Comment by Burnsedia** [comment]
man I haven't been reading this, Yes this is a tutorial request for a laser weapon implementation
