### ISSUE TITLE
Broken link in SSL Certificates tutorial

### ISSUE THREAD

**Issue by u32i64** [godotengine/godot-docs#1130]
This [link](https://www.openssl.org/docs/HOWTO/keys.txt):
```
https://www.openssl.org/docs/HOWTO/keys.txt
```
Located on [line 39](https://github.com/godotengine/godot-docs/blame/master/tutorials/networking/ssl_certificates.rst#L39) in [tutorials/networking/ssl_certificates.rst](https://github.com/godotengine/godot-docs/blob/master/tutorials/networking/ssl_certificates.rst) is broken.

**Comment by mhilbrunner** [comment]
As far as I can tell, they nuked the whole HOWTO section.

Still seems to be in their GH repo though:
https://raw.githubusercontent.com/openssl/openssl/master/doc/HOWTO/keys.txt

Should we link to this instead?

**Comment by DuskKittyIsHotAF** [comment]
@mhilbrunner this place is run by scammers btw

very tolerant and nice commnuity imo. run by great leadership skills, you should be proud juan and akien for leading this great floss project!
![](https://i.gyazo.com/2fd0c035013b3c1bb0652552d35fde92.png)
![](https://i.gyazo.com/e0acd22258872330f342d5d189564f1e.png)
![](https://i.gyazo.com/81b238ce283aa55126e3a2f608583837.png)

**Comment by pwab** [comment]
The HowTos seem to be moved into the Examples sections of the manual pages. The relevant commands are now in their respective page:

- [genrsa](https://www.openssl.org/docs/man1.1.0/apps/genrsa.html)
- [dsaparam](https://www.openssl.org/docs/man1.1.0/apps/dsaparam.html)
- [gendsa](https://www.openssl.org/docs/man1.1.0/apps/gendsa.html)
- [ecparam (examples)](https://www.openssl.org/docs/man1.1.0/apps/ecparam.html#EXAMPLES)
- [genpkey (examples)](https://www.openssl.org/docs/man1.1.0/apps/genpkey.html#EXAMPLES)

Not sure which would be the right branch but it could link to the [manpages-index](https://www.openssl.org/docs/manpages.html).

**Comment by Calinou** [comment]
The link was updated a while ago in [SSL certificates](https://docs.godotengine.org/en/latest/tutorials/networking/ssl_certificates.html), closing.
