### ISSUE TITLE
get_pos don't work

### ISSUE THREAD

**Issue by jfvvinente** [godotengine/godot-docs#1131]
Hi everyone,

I try do a little objetc move, 

extends Node2D 
var vel = 200#velocidade

func _ready():
	set_process(true)
	pass

func _process(delta):
	var d=0 #direita
	var e=0 #esquerda
	
 if Input.is_action_pressed("direita"):
		d= 1

 if Input.is_action_pressed("esquerda"):
		e= -1
	#if get_pos().x>(640 - 32):
		d=0
	#if get_pos().x<32:
		e=0
	set_pos(get_pos()+Vector2(0,0)*(d+e))
	pass

But don't work: 

> Invalid call. Nonexistent function 'get_pos' in base Node2D. (Node2D.gd)

**Comment by paul-dosenbrot** [comment]
Are you using Godot 3.0? There is no `get_pos()` function in Godot 3.0
Instead you have to use the `position` member variable.
Your example would become:
`position += Vector2(your_x_value, your_y_value)`

**Comment by jfvvinente** [comment]
very tanks
