### ISSUE TITLE
Need better documentation about AnimationTreePlayer

### ISSUE THREAD

**Issue by mysticfall** [godotengine/godot-docs#1132]
The current documentation about `AnimationTreePlayer` is pretty minimal at best, so it's very difficult to figure out how to use it properly, even if it's an essential feature if you want to make a game with complex animation states.

Especially, things like differences between `Mix` and `Blend2` nodes would be helpful. I found that `Mix` didn't act as I supposed it to work but `Blend2` did, but I couldn't figure out the intended usage of `Mix` or if its behavior was due to some bug.

**Comment by akien-mga** [comment]
This was left aside as `AnimationTreePlayer` is queued for a complete refactor for 3.1 or 3.2. But if someone wants to work on better documentation for the current API in the meantime, it wouldn't hurt either.

**Comment by ZX-WT** [comment]
since we got a new animation tree already
https://godotengine.org/article/godot-gets-new-animation-tree-state-machine
I think it is time to write a tutorial.

**Comment by clayjohn** [comment]
@akien-mga This should be closed now with http://docs.godotengine.org/en/latest/tutorials/animation/animation_tree.html
