### ISSUE TITLE
Fix "Edit this on GitHub" link on docs.godotengine.org

### ISSUE THREAD

**Issue by mhilbrunner** [godotengine/godot-docs#1138]
The "Edit this on GitHub" link on docs.godotengine.org currently points to the 3.0 branch.
For stable, it currently points to the stable branch.

Shouldn't this point to master by default? Most fixes we get are writing fixes, nothing that is strictly version-dependant.

**Comment by akien-mga** [comment]
Looks like this might do the trick, trying it locally: https://docs.readthedocs.io/en/latest/vcs.html#github

**Comment by akien-mga** [comment]
rtfd/readthedocs.org#2971 is finally fixed! One needs to ask RTD admins to enable the feature on a per-project basis, but it's now enabled on the `godot` RTD project, which fixed the issue.

All branches should now point to the master branch (2.1, 3.0 and stable branches are building to pick up the change, but 3.1 is already live and pointing to master).
