### ISSUE TITLE
Document the maximum configurable amount of enet peers

### ISSUE THREAD

**Issue by hungrymonkey** [godotengine/godot-docs#1139]
http://docs.godotengine.org/en/latest/classes/class_networkedmultiplayerenet.html?highlight=enet

The godot docs doesnt really tell you the maximum amount of enet peers allowed.

It just have an default of 32. I would change it myself, but I do not know the number.

**Comment by reduz** [comment]
In think the 32 number is per session, you can change it

**Comment by hungrymonkey** [comment]
Per session?

**Comment by mhilbrunner** [comment]
It isn't documented in the official ENet docs (http://enet.bespin.org/group__host.html) or even other bindings like Löve2D. However, digging into the source (https://github.com/erwincoumans/enet/blob/master/btgui/enet/host.c) the limit is ENET_PROTOCOL_MAXIMUM_PEER_ID which seems to be 4096:
https://github.com/lsalzman/enet/issues/41

So yes, it is 32 by default, but you can increase it up to 4096. I will add this to the docs.
