### ISSUE TITLE
Physics: CollisionShape2D: trigger no longer exist

### ISSUE THREAD

**Issue by contested-space** [godotengine/godot-docs#1153]
The doc talks about a trigger option which seem to no longer exist in 3.0 according to online comments.

**Comment by cbscribe** [comment]
Can you link to where in the docs you saw this?

**Comment by contested-space** [comment]
Of course: 
https://github.com/godotengine/godot-docs/blob/3.0/tutorials/physics/physics_introduction.rst

There is a paragraph titled "Triggers".

**Comment by cbscribe** [comment]
Thanks. That doc is definitely in need of an update for 3.0.

**Comment by cbscribe** [comment]
Fixed by #1176
