### ISSUE TITLE
"Viewport and canvas transforms" references "Canvas Layers" tutorial out of order

### ISSUE THREAD

**Issue by gamesoil** [godotengine/godot-docs#1156]
http://docs.godotengine.org/en/3.0/tutorials/2d/2d_transforms.html#canvas-transform

"As mentioned in the previous tutorial, Canvas layers, ..."

However, Canvas Layers is a tutorial that comes after this point.

I'm guessing the order used to be different a while ago but got shuffled around, and this part got missed.

**Comment by mhilbrunner** [comment]
Fixed in master.
