### ISSUE TITLE
Strange STRIKEOUT tag in RigidBody2D docs

### ISSUE THREAD

**Issue by gamesoil** [godotengine/godot-docs#1161]
http://docs.godotengine.org/en/3.0/tutorials/physics/physics_introduction.html#rigidbody2d

> As a result, [STRIKEOUT:this node can’t be scaled]. Scaling the children nodes should work fine though.

I'd be happy to offer a simple patch, but I'm not sure what the author's original intention was. Bold?

**Comment by RiverMesa** [comment]
Probably **bold**, though ~~strikeout would indicate this~~, but it hardly seems appropriate in-context (or to be included in a documentation at all).

**Comment by akien-mga** [comment]
Looking at the old Markdown wiki, it was indeed **bold** which got badly converted by Pandoc: https://github.com/vkbsb/godot/wiki/tutorial_physics_2d#rigidbody2d

**Comment by mhilbrunner** [comment]
Fixed in https://github.com/godotengine/godot-docs/commit/112ad104eeac9458dc781888766962b127ada0df#diff-d2bbc7ed327b4e938f9505253f1d6aa3.
