### ISSUE TITLE
Certain editor settings are relatively undocumented

### ISSUE THREAD

**Issue by Dar13** [godotengine/godot-docs#1163]
Went to set up an external editor for GDScript files via "Editor Settings->Text Editor->External" and had to look into the engine source to find the parameters for the "Exec Flags" field.

In the current documentation there isn't a subsection in the editor manual that this information would go, so perhaps making a new file that contains explanations of the some of the more niche or Godot-specific features.

I'm planning on making a PR for this, opening this for discussion on how best to insert this information.

EDIT: I didn't see or didn't look deeply enough into #395 and #965, so this issue is potentially a duplicate.

**Comment by pwab** [comment]
Yepp, it is a duplicate of #395. Further discussion should be done there or in your PR #1164.

**Comment by Dar13** [comment]
Going to resolve this through either #1164 or #1185, or whatever PR resolves #395. No need for this duplicate to hang around.
