### ISSUE TITLE
2d tutorial article ordering?

### ISSUE THREAD

**Issue by alankemp** [godotengine/godot-docs#1165]
Starting from this index page:  http://docs.godotengine.org/en/3.0/tutorials/2d/index.html

I started reading the first tutorial http://docs.godotengine.org/en/3.0/tutorials/2d/2d_transforms.html

The second paragraph begins "As mentioned in the previous tutorial, Canvas layers,"

But the canvas layers tutorial is the next article, not the previous.  Is the index wrong?  Or was the order changed and this paragraph needs rephrasing?

**Comment by pwab** [comment]
This was already changed in [master branch](http://docs.godotengine.org/en/latest/tutorials/2d/index.html) with #1146.
Cherry pick? @NathanLovato

**Comment by mhilbrunner** [comment]
Fixed.
