### ISSUE TITLE
Compiling with Mono doc needs a tweak for windows

### ISSUE THREAD

**Issue by exts** [godotengine/godot-docs#1167]
On this [page](https://github.com/godotengine/godot-docs/blob/3.0/development/compiling/compiling_with_mono.rst)

It says:

`godot --generate-mono-glue modules/mono/glue` on windows the steps to do this is essentially:

1. cd bin
2. `godot.windows.tools.XX.mono.exe --generate-mono-glue ../modules/mono/glue`

And it'll properly build without any error where XX is 64 (im assuming 32 if 32bit) iirc. I've only tested with 64bit.

**Comment by akien-mga** [comment]
You don't need step 1., you can do `bin/godot.windows.tools.XX.mono.exe --generate-mono-glue modules/mono/glue`.

I'd leave the current command as is, or make it `bin/godot`, and just add explanations that "godot" refers to the compiled Godot binary in the `bin` folder with the suffix specific to your build options. We can't start putting descriptions of all platform-specific potential suffixes everywhere.

**Comment by exts** [comment]
> I'd leave the current command as is, or make it bin/godot, and just add explanations that "godot" refers to the compiled Godot binary in the bin

@akien-mga yea that'd work.
