### ISSUE TITLE
Issue with Docs - Scripting a Scene - Missing Parts of Tutorial

### ISSUE THREAD

**Issue by ArgentArts** [godotengine/godot-docs#1168]
I think there's something missing in the Godot tutorial at Step by Step>Scripting>Scripting a scene. When you go down to Handling a Signal, it tells you to  Select Button, go to Nodes, and ensure Signal is selected. And that's it before getting into scripting. It does not tell you to select "pressed()" and then hit Connect and does not tell you what to do with the window that opens next. It skips all that and gets into scripting. So, if a new programmer (like myself :wink: ) follows what is there, the script won't work. And that can be very frustrating for someone trying to learn. :smiley:

**Comment by skyace65** [comment]
I just checked the docs and this has been fixed, I don't know when though. @Calinou can you close this issue?
