### ISSUE TITLE
Export for iOS Steps are wrong exporting_for_ios.rst

### ISSUE THREAD

**Issue by JPTeasdale** [godotengine/godot-docs#1173]
I don't think these steps are up to date: http://docs.godotengine.org/en/3.0/getting_started/workflow/export/exporting_for_ios.html

First of all, there is no `GodotiOSXCode.zip` in `export_templates.tpz` I think the directory in question is now `iphone.zip`. 

Secondly, I get an error message when I manually unzip iphone.zip and then try to open `godot_ios.xcodeproj` I get this error message in a popup window:

```
<<I_EDITED_OUT_PATH>>/iphone/godot_ios.xcodeproj cannot be opened because the project file cannot be parsed
```

If I use the exporter in GoDot > Project > Export > iOS > *fill in images* > Export Project > Save

It goes though the process and creates an directory, but that directory looks like this:

```
$ ls -a
-Info.plist			Default-Landscape-736h@3x.png
.				Default-Landscape@2x.png
..				Default-Portrait-1366h@2x.png
.a				Default-Portrait-736h@3x.png
.entitlements			Default-Portrait@2x.png
.pck				Images.xcassets
.xcodeproj			dummy.cpp
Default-568h@2x.png		dylibs
Default-667h@2x.png		en.lproj
Default-Landscape-1366h@2x.png	export_options.plist
```

You can see a nameless `.xcodeproj` which makes me believe that there is some other required property that doesn't throw an error in the export settings. 

If I rename that `.xcodeproj` to something like `test.xcodeproj`, I still see the error:
```
<<I_EDITED_OUT_PATH>>/iphone/godot_ios.xcodeproj cannot be opened because the project file cannot be parsed
```

**Comment by JPTeasdale** [comment]
Made a pull request https://github.com/godotengine/godot-docs/pull/1175, will have conversation there.

**Comment by mhilbrunner** [comment]
Fixed in https://github.com/godotengine/godot-docs/commit/8acfe8cdaf88f470232de79605293e2dc4186931 by #1175
