### ISSUE TITLE
"Singletons_autoload" downloadable tutorial cannot be opened in Godot 3.0

### ISSUE THREAD

**Issue by gemkibeju** [godotengine/godot-docs#1178]
https://godot.readthedocs.io/en/3.0/getting_started/step_by_step/singletons_autoload.html

To wit, "Autoload.zip" uses the old file formats of .gd and .scn , meaning it cannot be opened in Godot 3.0

**Comment by pwab** [comment]
I'm pretty sure those PRs try to fix this as well as other points but couldn't be merged yet:

- #912 
- #1133

**Comment by mhilbrunner** [comment]
Fixed by https://github.com/godotengine/godot-docs/pull/1481
