### ISSUE TITLE
Document GodotPayments singleton

### ISSUE THREAD

**Issue by akien-mga** [godotengine/godot-docs#118]
Clone from https://github.com/godotengine/godot/issues/1258 by @leiserfg:

> Can someone write in the wiki how to use this singleton on android? I saw that in the java source but I'can make it work from gdscript.

**Comment by Meriipu** [comment]
What happens with these issues now that GodotPayments was moved out of the tree?

**Comment by akien-mga** [comment]
This is still valid for the first party https://github.com/godotengine/godot-google-play-billing. The current docs explain usage, but there's no direct description of what each method is and does.

We might want to document it on the plugin repo itself though, and link to it from the Godot docs.

CC @timoschwarzer

**Comment by timoschwarzer** [comment]
@akien-mga Speaking for `GodotGooglePlayBilling`, all methods are mostly wrappers around the Google Play Billing API. IMO we can just add links to the respective sections [here](https://developer.android.com/google/play/billing/integrate) in our docs.

**Comment by cbscribe** [comment]
Closing this, as it should be a plugin documentation issue, not a core docs topic.
