### ISSUE TITLE
C++ missing from documentation

### ISSUE THREAD

**Issue by baptx** [godotengine/godot-docs#1187]
C++ is missing from this documentation page:
https://godot.readthedocs.io/en/3.0/getting_started/scripting/index.html

But it should be listed according to this documentation page:
https://godot.readthedocs.io/en/3.0/about/faq.html#which-languages-are-supported-in-godot

> The officially supported languages for Godot are GDScript, Visual Scripting, C# and C++. See the subcategories for each language in the scripting section.

I was told to report this here (https://twitter.com/_eons/status/968891021848432640).

**Comment by mhilbrunner** [comment]
Duplicate of https://github.com/godotengine/godot-docs/issues/140
