### ISSUE TITLE
Viewport methods missing?

### ISSUE THREAD

**Issue by chanon** [godotengine/godot-docs#1188]
In the 3.0 version of the documentation for the `Viewport` class ( http://docs.godotengine.org/en/3.0/classes/class_viewport.html ) it seems a lot of bound methods are missing. For example `set_global_canvas_transform` is not listed.

The 2.1 version of the documentation has it listed:
http://docs.godotengine.org/en/2.1/classes/class_viewport.html#class-viewport-set-global-canvas-transform

It still exists and is bound in viewport.cpp in the master (3.x) branch:
https://github.com/godotengine/godot/blob/master/scene/main/viewport.cpp#L719
https://github.com/godotengine/godot/blob/master/scene/main/viewport.cpp#L2559

It is listed in godot/doc/classes/Viewport.xml in the master branch:
https://github.com/godotengine/godot/blob/master/doc/classes/Viewport.xml#L203

It is *not* listed in
https://github.com/godotengine/godot-docs/blob/master/classes/class_viewport.rst

I am porting my code from 2.1 to 3.0 and have found these 3.0 documentation issues make the job somewhat harder. I understand though that 3.0 is still new, just wanted to report this.

I hope it is not because the method is to be deprecated as in my case I need it to customize the scaling and cropping of the game's display for different device aspect ratios.

**Comment by mhilbrunner** [comment]
I don't think its deprecated; rather, setters and getters for member variables are not documented seperately anymore, only the member variable is. The 3.0 docs still have this:
```
Member Variables

(Transform2D) global_canvas_transform - The global canvas transform of the viewport. The canvas transform is relative to this.
```

It's like with `position`: In 2.1, you'd to `set_position()`/`get_position()` on a node, in 3.0 the common style is accessing the member directly: `node.position` (instead of `node.get_position()` and `node.position = x` (instead of `node.set_position(x)`).

**Comment by chanon** [comment]
Oh! I see. That makes sense, don't know how I missed that.

The set_position thing also confused me before as the 2.1 to 3.0 converter converts set_pos to set_position and I couldn't find set_position in the docs either.

I'm not sure if this will confuse anyone else in the future, but I'm ok now.

**Comment by mhilbrunner** [comment]
Yeah, this should probably go into a Godot 2.1 to Godot 3.0 transitioning guide somewhere.
