### ISSUE TITLE
Tutorial: Custom mouse cursors

### ISSUE THREAD

**Issue by mhilbrunner** [godotengine/godot-docs#1192]
Multiple people on Discord/Q&A were asking how to do custom mouse cursors.

This is the PR that added support, including a demo project:
https://github.com/godotengine/godot/pull/12814

We should document this somewhere, maybe create a tutorial.

**Comment by ZX-WT** [comment]
One question, is there a difference between this and setting the cursor image in the project settings? I notice that using code provide more options. Just want to clarify it before working on this.

**Comment by guilhermefelipecgs** [comment]
> One question, is there a difference between this and setting the cursor image in the project settings? I notice that using code provide more options. Just want to clarify it before working on this.

No difference, in the project settings you just define one shape (```Input.CURSOR_ARROW``` by default) and if you set via script you can define different shapes of cursors.

**Comment by guilhermefelipecgs** [comment]
@mhilbrunner I think most people probably was having difficult with the size of cursor, that must be in 32x32px, maybe we need to add this in de docs to clarify.

**Comment by ZX-WT** [comment]
I wrote a short tutorial, please provide any missing detail, if any, so I can improve it.
