### ISSUE TITLE
Some form of explanation for the formats on the Image page.

### ISSUE THREAD

**Issue by najarvis** [godotengine/godot-docs#1214]
If you look at the image documentation page, it has an enum called "Format", and 37 different formats. These aren't explained at all and I have no idea which one I should use in which instance. For example, I am trying to create a custom .exr image but I have no idea which of these pertains to that.

Edit: [link](http://docs.godotengine.org/en/3.0/classes/class_image.html)

**Comment by pwab** [comment]
These are [Texture Compression Formats](https://en.wikipedia.org/wiki/Texture_compression).

I looked into the [image.cpp](https://github.com/godotengine/godot/blob/master/core/image.cpp) and [image_etc.cpp](https://github.com/godotengine/godot/blob/master/modules/etc/image_etc.cpp) but there aren't much comments besides _LA8 = LumAlpha8 (Lum = Luminance)_ and _DXT1 = DXT1 RGB8 (s3tc)_.

But I found some info in the [OpenGL ES 3.0 spec](http://www.khronos.org/registry/OpenGL/specs/es/3.0/es_spec_3.0.pdf):

- [RGB and RGBA8](https://www.khronos.org/registry/OpenGL/specs/es/3.0/es_spec_3.0.pdf#table.3.2) (Pixel Rectangles)
- [sRGB](https://en.wikipedia.org/wiki/SRGB) on p. 164 (sRGB Texture Color Conversion)
- [ETC and ETC2](https://en.wikipedia.org/wiki/Ericsson_Texture_Compression) which is documented in Appendix C.1, p. 288
- [BTC](https://en.wikipedia.org/wiki/Block_Truncation_Coding) can be found in the [OpenGL ES 4.5 specs](https://www.khronos.org/registry/OpenGL/specs/gl/glspec45.core.pdf#page=663) at p. 645 (Appendix C - Compressed Texture Image Formats) and a bit side information is in the [OpenGL wiki](https://www.khronos.org/opengl/wiki/BPTC_Texture_Compression)
- [DXT](https://en.wikipedia.org/wiki/S3_Texture_Compression), also called S3TC, can be found in a [extension description](https://www.khronos.org/registry/OpenGL/extensions/EXT/EXT_texture_compression_s3tc.txt) and also a bit more info in the [wiki](https://www.khronos.org/opengl/wiki/S3_Texture_Compression)
- [PVRTC and PVRTC2](https://en.wikipedia.org/wiki/PVRTC) is not ducumented in the OpenGL spec but a description of the algorithm can be found in [Fenney2003](http://web.onetel.net.uk/~simonnihal/assorted3d/fenney03texcomp.pdf)

Further reading:

- https://blogs.msdn.microsoft.com/shawnhar/2008/10/28/texture-compression/
- http://renderingpipeline.com/2012/07/texture-compression/
- https://www.fsdeveloper.com/wiki/index.php?title=DXT_compression_explained
- https://www.imgtec.com/blog/pvrtc-the-most-efficient-texture-compression-standard-for-the-mobile-graphics-world/
- https://software.intel.com/en-us/articles/android-texture-compression-a-comparison-study-with-code-sample
- https://docs.unity3d.com/Manual/class-TextureImporterOverride.html
- https://www.khronos.org/registry/DataFormat/specs/1.1/dataformat.1.1.html

**Comment by najarvis** [comment]
Wow, this is really helpful, thank you! I ended up using FORMAT_RGBAF, since that gave 32 bits of data per color channel, which worked great, but I'm sure your comment would be extremely helpful for anyone else who is working with custom images in Godot. Thank you again!

**Comment by pwab** [comment]
You are welcome. And you are totally right that this should be documented somehow. Thanks for pointing this out.

**Comment by Dar13** [comment]
Is godotengine/godot#17399 good enough to close this out @najarvis / @pwab?

**Comment by najarvis** [comment]
Looks great, thank you for this!
