### ISSUE TITLE
The tutorial divide sign

### ISSUE THREAD

**Issue by ondesic** [godotengine/godot-docs#1231]
In the First Game tutorial there is a line
$MobPath/MobSpawnLocation
I have not seen this syntax. What is the "/" sign for?

**Comment by cbscribe** [comment]
The `$` is shorthand for `get_node()` so this is equivalent to `get_node("MobPath/MobSpawnLocation")`. The text after the $ is the node path.

Please note that this forum is for posting and discussing issues with the docs, not for requesting help/support. For that, please see one of the following community sites:

* https://godotengine.org/qa/
* https://godotdevelopers.org/forum/
* https://discord.gg/zH7NUgz
