### ISSUE TITLE
Your first game/dodge the creeps: Main script setup needs to be expanded

### ISSUE THREAD

**Issue by mhilbrunner** [godotengine/godot-docs#1240]
Here:
http://docs.godotengine.org/en/3.0/getting_started/step_by_step/your_first_game.html

In the section "Main script", the tutorial goes over what should be done really fast:

*Next, click on the Player and connect the hit signal. We want to make a new function named game_over, which will handle what needs to happen when a game ends. Type “game_over” in the “Method In Node” box at the bottom of the “Connecting Signal” window. Add the following code, as well as a new_game function to set everything up for a new game: (...)*

This doesn't explain where `the following code` should be added, the player or the main script. It should be added to `Main`, but that can only be inferred from the section title and the prev. paragraph. This should be clarified, and maybe the signal configuration should be expanded a little and be explained more in-depth.

**Comment by cbscribe** [comment]
Agreed this could use some clarification on where the code goes. I'll take this and make a few changes.

However, I'm not sure this is the place to expand on connecting signals, though. By the time you've gotten to this step, you've already connected two signals previously.

**Comment by mhilbrunner** [comment]
Agree in that case, maybe just a link back to that explanation then? Or we can just add a sentence about where the code should go and leave the signal stuff as is. :)
