### ISSUE TITLE
"(from project godot)" in search results

### ISSUE THREAD

**Issue by YeldhamDev** [godotengine/godot-docs#1245]
I don't know if this something from our side, or from ReadTheDocs. But when searching for something, all results have "(from project godot)" besides them.

**Comment by YeldhamDev** [comment]
This doesn't happen anymore. Closing it.

**Comment by pwab** [comment]
I can confirm this. For the lazy ones:

![from_project_godot](https://user-images.githubusercontent.com/19271185/39971430-091e957a-56fb-11e8-9514-4b72a93e4dcb.png)

**Comment by mhilbrunner** [comment]
Seems like this was fixed somewhere, somewhen.
