### ISSUE TITLE
Viewport lacks render_target boolean property

### ISSUE THREAD

**Issue by Zylann** [godotengine/godot-docs#1249]
Godot 3.0.2

Here: http://docs.godotengine.org/en/3.0/tutorials/viewports/viewports.html#render-target
In the viewport docs, it is said: "To set as a render target, just toggle the “render target” property of the viewport to enabled."
I don't see this property, so I'm not sure what I should do instead.

Edit: I think it has been changed to the UpdateMode enum

![image](https://user-images.githubusercontent.com/1311555/37774600-93767c66-2dd8-11e8-9eca-32c342905155.png)

**Comment by clayjohn** [comment]
@akien-mga this has been addressed and should be closed
