### ISSUE TITLE
Shader docs: Visually separate Spatial and CanvasItem built-ins more clearly

### ISSUE THREAD

**Issue by JarLowrey** [godotengine/godot-docs#1252]
https://godot.readthedocs.io/en/3.0/tutorials/shading/shading_language.html#fragment-built-ins

[Playing around with shaders for the first time](https://godotengine.org/qa/26127/simple-shader-not-working?show=26129#a26129). Attempting to get COLOR variable's value didn't go as expected, only setting it worked correctly.

**Comment by bojidar-bg** [comment]
You have mistaken the docs for spatial shader with the ones for canvas item shader below.

Spatial (cut):
![image](https://user-images.githubusercontent.com/5276727/37823795-38b8f4d2-2e93-11e8-9d6d-eb30f39f41cb.png)

Canvas Item:
![image](https://user-images.githubusercontent.com/5276727/37823760-194b33c6-2e93-11e8-8536-43927dab6b0b.png)

Perhaps those docs should be cleared a bit by adding "Spatial" or "Canvas Item" to each of the headings, and maybe moving the discussion following some of the tables to separate pages.
Or maybe, moving all the tables to separate pages for spatial/canvas/particles shaders, and keep them as reference material only.

**Comment by JarLowrey** [comment]
At the minimum I think adding to the heading would be good. Thanks!

**Comment by akien-mga** [comment]
Fixed by #2046.
