### ISSUE TITLE
tutorials/viewports/multiple_resolutions.rst has no documentation for Stretch > Shrink

### ISSUE THREAD

**Issue by jhm-ciberman** [godotengine/godot-docs#1253]
`tutorials/viewports/multiple_resolutions.rst` has no documentation for Stretch > Shrink

![image](https://user-images.githubusercontent.com/7988351/37817112-5bda35b4-2e54-11e8-83fb-dedf9b2d51f2.png)

Branch: 3.0

**Link:** http://docs.godotengine.org/en/3.0/tutorials/viewports/multiple_resolutions.html

**Comment by LinuxUserGD** [comment]
https://github.com/godotengine/godot/issues/17639

**Comment by Calinou** [comment]
This is now documented: https://docs.godotengine.org/en/latest/tutorials/viewports/multiple_resolutions.html
