### ISSUE TITLE
Compress Lossless (PNG)

### ISSUE THREAD

**Issue by hubslave** [godotengine/godot-docs#1257]
Using this method results in Loosy compressed PNG files with artifacts in v3.0.2, here is an example DIFF MAP comparing original PNG file with one created by Compress Lossless (PNG): http://www71.zippyshare.com/v/MKHmzMkK/file.html

**Comment by mhilbrunner** [comment]
As stated in your PR (https://github.com/godotengine/godot-docs/pull/1256), this should be raised on github.com/godotengine/godot instead. Thanks for your time!

**Comment by hubslave** [comment]
https://github.com/godotengine/godot/issues/17726
