### ISSUE TITLE
Missing documentation for type_hint in ResourceLoader

### ISSUE THREAD

**Issue by bartosz-m** [godotengine/godot-docs#1258]
There is no information what correct values could be passed to `ResorceLoader` functions `load` and `load_interactive`.
I've looked directly at source code of `ResorceLoader` but I still have no clue.

**Comment by hungrymonkey** [comment]
I think type hint is used when there are file collisions for the extension format.

Like obj or bin have multiple loaders which means that godot will be confused which ever works.

Having a hint would help godot choose the correct loader

https://github.com/godotengine/godot/blob/master/core/io/resource_loader.cpp#L169

https://github.com/godotengine/godot/blob/master/core/io/resource_loader.cpp#L54

https://github.com/godotengine/godot/blob/master/core/io/resource_loader.cpp#L74

you pass these values.

https://github.com/godotengine/godot/blob/master/modules/vorbis/audio_stream_ogg_vorbis.cpp#L411

**Comment by nathanfranke** [comment]
@hungrymonkey Maybe things have changed in the past 2 years, but

```py
print(ResourceLoader.load("res://icon.png", "Image"))
```

prints `[StreamTexture:1180]`
