### ISSUE TITLE
BackBufferCopy Documentation out of date

### ISSUE THREAD

**Issue by DevinPentecost** [godotengine/godot-docs#1259]
Hi,

The BackBufferCopy Node documentation for 3.0 is out of date.
[http://docs.godotengine.org/en/3.0/classes/class_backbuffercopy.html](http://docs.godotengine.org/en/3.0/classes/class_backbuffercopy.html)
It is still referencing the texscreen() function, which is no longer available in Godot 3.0.

This documentation should be updated with correct references, and the incorrect references should be removed. In addition, useful examples should be provided. Unfortunately I am not an expert on BackBufferCopy Node's and their usages, so if someone with more knowledge on the subject can update the documentation that would be very helpful, especially for those writing shaders.

Thanks

**Comment by DevinPentecost** [comment]
Is the BackBufferCopy Node functioning in 3.0? I have been unable to successfully use it and there does not appear to be any up-to-date documentation beyond [this page](http://docs.godotengine.org/en/3.0/tutorials/shading/screen-reading_shaders.html) but I have not been able to reproduce it's example.

**Comment by mhilbrunner** [comment]
Can't say anything about BackBufferCopy, but maybe the #godotengine-dev IRC channel on Freenode may be able to help? Alternatively, create an issue on the Godot engine repo, as that sees more traffic.

Please keep this issue open so we can fix this in the docs. :)

**Comment by Maujoe** [comment]
Old Issue, can be closed.

**Comment by akien-mga** [comment]
Indeed, this seems fixed in http://docs.godotengine.org/en/latest/classes/class_backbuffercopy.html
