### ISSUE TITLE
Missing data property in Stream

### ISSUE THREAD

**Issue by LinuxUserGD** [godotengine/godot-docs#1269]
Access via GDScript:
```swift
var stream = AudioStreamOGGVorbis.new()
stream.data = bytes
```

Affected documentation (see https://github.com/godotengine/godot/issues/17748 and https://github.com/godotengine/godot/issues/17848):

- http://docs.godotengine.org/en/latest/classes/class_audiostreamsample.html#class-audiostreamsample
- http://docs.godotengine.org/en/latest/classes/class_audiostreamoggvorbis.html#class-audiostreamoggvorbis

**Comment by LinuxUserGD** [comment]
Would this be correct?
```Swift
<member name="data" type="PoolByteArray" setter="set_data" getter="get_data" enum="AudioStreamSample.Data">
Audio's raw data.
</member>
```

**Comment by vnen** [comment]
This should be fixed in the code, by changing the bindings. The documentation XML is generated from that.

**Comment by LinuxUserGD** [comment]
Ok thank you, so the property is used by the engine.
