### ISSUE TITLE
[Discussion] Documenting demos

### ISSUE THREAD

**Issue by StraToN** [godotengine/godot-docs#128]
The preparation task of documenting Godot demos (available here: https://downloads.tuxfamily.org/godotengine/2.0.2/Godot_v2.0.2_stable_demos.zip) has started with the creation of the demos/ folder in the present repo (https://github.com/godotengine/godot-docs/tree/master/demos).

Even though each demo has an empty page already created, we feel that some demos may get out of the "official" list and some may be replaced by new ones. This topic discusses this question.

First things first, I propose to sort current demos in 3 lists:
- Keep and/or improve : these demos will be documented first.
- Replace by a better one : we will need to develop new demos
- Remove

Please help us filling these in this Etherpad: https://v.etherpad.org/p/godot-demos-docs

Then, we will track a new list with whole new demos that you may feel currently missing. Remember each demo will then have its own documentation page. You can propose your ideas in the according section of the previous Etherpad.

Thanks !

**Comment by NathanLovato** [comment]
What's the state of this discussion? We're creating new demos to go specifically with the docs with @cbscribe , +/- separate from the existing ones (which are a bit all over the place). I think Juan wanted to keep them all as is, as feature demos. If we're going to write tuts for demos, I'd rather start from scratch and have them standardized a little as far as the presentation, show sane practices for beginners and try to give more comprehensive overviews of some features.
At least for me, the existing zip demos didn't help much learning the engine.

**Comment by StraToN** [comment]
I think we can close this one. The discussion started before you & @cbscribe started working on new demos, which is definitely better than documenting the existing ones ; if any of the existing demos was to be supported by a tutorial, then it would be reworked anyway.
