### ISSUE TITLE
Godot GridMap Docs Out of Date

### ISSUE THREAD

**Issue by SilverSurfer1221** [godotengine/godot-docs#1283]
The Godot docs on GridMap are very out of date. They can be read here:

http://docs.godotengine.org/en/3.0/tutorials/3d/using_gridmaps.html

Not only do they show the older UI, but they have incorrect information, such as:

> Now, you can build your own level as you see best fit. Use left click to add tiles and right click to remove them. 

Right click no longer removes a placed gridmap item. Instead, it is SHIFT+Right Mouse Click.

**Comment by cbscribe** [comment]
In addition to revising the content and updating the screenshots, this tutorial should probably provide a downloadable sample project so readers can follow along.

**Comment by SilverSurfer1221** [comment]
Yes, and the keyboard/mouse functions need to be documented. For example, what does SHIFT+RMB do? It creates a sort of transparent 3D box that stays in the viewport, like a 3D selection or one of the old BSP portals, but I have no clue what it does as the docs don't cover it.

**Comment by cbscribe** [comment]
>For example, what does SHIFT+RMB do?

That's a selection box - you can click on the GridMap menu and clear/duplicate the selection.

But yeah, there's a lot that needs to be explained. When I was recently working on a tutorial using GridMap, I had to search through pull requests to find out what some of the functionality was.

**Comment by cbscribe** [comment]
Fixed in #1284
