### ISSUE TITLE
Create docs for engine hackers

### ISSUE THREAD

**Issue by akien-mga** [godotengine/godot-docs#129]
Moving https://github.com/godotengine/godot/issues/73 here.

**Comment by pwab** [comment]
I think this is done by:

- [Compiling](http://docs.godotengine.org/en/latest/development/compiling/index.html)
- [Developing in C++](http://docs.godotengine.org/en/latest/development/cpp/index.html)
- [Contributing](http://docs.godotengine.org/en/latest/community/contributing/index.html)
- and the #godotengine-devel

**Comment by mhilbrunner** [comment]
Agree with pwab for now, if anything more concrete is missing, we should open specific issues for those things.
