### ISSUE TITLE
Add constraint during delivery

### ISSUE THREAD

**Issue by git2013vb** [godotengine/godot-docs#1320]
Hi , there is a way to add some constraints/quality control to force any developer to add proper documentation/basic example to any new/old feature in contextual commit?

A game engine without enough/exhaustive documentation is useless to 99% of users in my opinion. 

Thank you.

**Comment by groud** [comment]
No, we don't force anyone here. And we're not going to refuse someone's PR because it's not documented, if it's good to merge, it's good to merge.
But we may try to encourage people to document their code, yes.

**Comment by git2013vb** [comment]
@groud. 
ok it is a free world ofc. I respect that.
But tell me.
What the point to have a feature undocumented? Who are going to use it? Not myself ofc.
Put on some feature in a open source software and don't give any documentation how to use it is the dead of that software in my opinion.

Share knowledge if one the most important rule in open source software. Do you agree?

Thank you for your answer btw.

**Comment by git2013vb** [comment]
I want to add another my thought:
To me is not important the game engine can run with no errors.... If I have to struggle to use it I prefer something that I can use even if is bugged instead to have a well developed software that I don't know how to use it.

This is my point of view. When I read some comments in "slant" about how poor was the documentation I didn't believe and I had to try by myself... You know what? That guy was right.

**Comment by groud** [comment]
> What the point to have a feature undocumented? Who are going to use it? Not myself ofc.

The one who are able to read code and understand things by themselves. Which is actually a lot of people.

We can bikeshed an eternity about how to manage the project. But here are two things that lead our development: 
- We cannot force people to document their code, as people work on the project for free.
- Each PR is reviewed one by one. if we consider a PR brings value to the project, we merge it. Even if it's an undocumented feature. Something that has already been coded is always good to take, it's less work for the project in general.

Anyway, I'll close this issue this has already been discussed several time, as [here](https://github.com/godotengine/godot/issues/2032) or [here](https://github.com/godotengine/godot/issues/16942).

**Comment by git2013vb** [comment]
OK, I read the 2 links :)
Glad that I'm not alone. The way to understand how important is the documentation is to think who will be the game engine user. I will be a developer I agree that can be a bit tricky but nerveless feasible.
But what if the end user is an artist? Visual script have same problem..
How many artists are around that don't are able to use this game engine? In the future will be a developer who will make a game? I don't think so because he is already busy to work in the engine.. or something else as developer. I will  not write anymore about this subject but my opinion remain :) 
Have fun.
