### ISSUE TITLE
Images from Godot 2.x in `Singletons (AutoLoad)` documentation

### ISSUE THREAD

**Issue by kubecz3k** [godotengine/godot-docs#1328]
_bugsquad edit: this issue was taken from the main bug tracker (https://github.com/godotengine/godot/issues/8632)_

http://docs.godotengine.org/en/2.1/learning/step_by_step/singletons_autoload.html

On the above page the autoloader's parameter order has changed.

Current doc image:

![addglobal](https://cloud.githubusercontent.com/assets/7429786/25640000/f63c1558-2f5b-11e7-9147-a448a40a73df.png)

Current screenshot from Godot:

![capture](https://cloud.githubusercontent.com/assets/7429786/25640034/0e6b11f6-2f5c-11e7-89b5-ef0f7b14d01d.PNG)

Notice that the path and the node name params have switched place, which was annoying as I was following along

**Comment by skyace65** [comment]
This issue can be closed since PR #2681 was merged.

**Comment by akien-mga** [comment]
Note that this happens automatically if PRs use certain keywords: https://help.github.com/en/articles/closing-issues-using-keywords
