### ISSUE TITLE
Proof math introduction to rotation in 2d/3d games

### ISSUE THREAD

**Issue by NathanLovato** [godotengine/godot-docs#1346]
The new math tutorial about rotation is interesting but could use a proofing pass to make it easier to read. It has a lot of redundant adverbs, parentheses, typos, passive tense, long sentences, etc.:

https://github.com/godotengine/godot-docs/blob/master/tutorials/math/rotations.rst 

The author is @tagcup. If you have questions about the article, he's the math expert.

A few tools to help spot things to improve (make sure to build the page first as it has a lot of math snippets):

- http://www.hemingwayapp.com/
- https://github.com/amperser/proselint
- A general grammar checker like https://www.languagetool.org/

**Comment by Juankz** [comment]
We could start by fixing the latex syntax as it makes it really hard to understand the text

**Comment by tagcup** [comment]
I don't know what you mean by "fixing the latex syntax" (that's how people have typed math in the past 5 decades), but in general, PDF or the web output is more suitable for proof reading the text.

**Comment by Juankz** [comment]
My bad. When I was reading this article offline it displayed:
`\[\boldsymbol v' = R_z(\delta\theta) \boldsymbol v = \boldsymbol v + \delta \theta \boldsymbol e_z \times \boldsymbol v.\]`

but now that I check it online it shows properly:
![imagen](https://user-images.githubusercontent.com/18577412/40246343-03a471fa-5a8e-11e8-907b-c9591c434c5d.png)
