### ISSUE TITLE
SVG images don't appear in PDF output

### ISSUE THREAD

**Issue by tagcup** [godotengine/godot-docs#1352]
LaTeX does support SVGs (there is a package for that) but sphinx somehow doesn't make use of it? 

Seems like this was [a known issue](https://github.com/sphinx-doc/sphinx/issues/1907) and one workaround is to use [a sphinx extension](http://www.sphinx-doc.org/en/stable/ext/imgconverter.html)

**Comment by Calinou** [comment]
The only way to work around this problem is to render PNG images and use them instead: https://github.com/oemof/oemof-thermal/pull/91

I'd prefer we not bother about this as it'd add more maintenance cost and result in uglier images on hiDPI displays.

**Comment by skyace65** [comment]
Closing this issue as the downloadable PDF of the documentation was removed ( https://github.com/readthedocs/readthedocs.org/issues/8135).
