### ISSUE TITLE
a few "Matrices and transforms" issues

### ISSUE THREAD

**Issue by tagcup** [godotengine/godot-docs#1353]
- The equations are images, they can be typeset using :math: and this might apply to some other pages maybe
- All matrices are transposed. It's the columns, not rows, are the basis vectors. Transform2D internally stores the basis in a transposed form, which I couldn't convince reduz to fix, but the 3D implementation with Basis is correct such that the columns are basis vectors. (since I think it's totally crazy and Transform2D needs to be corrected, I'm not willing to explain this discrepancy between 2D and 3D).

**Comment by aaronfranke** [comment]
> All matrices are transposed. It's the columns, not rows, are the basis vectors.

Note that the exposed behavior is correct. This works as expected, in C# too:

    transform.x = Vector2.ONE

`transform.x` is the X column vector and is accessed with `elements[0]` in `transform_2d.cpp`. This does mean that `elements[0][0]` and `elements[0][1]` access the X column of the matrix, but you can just think of it as accessing (column, row) rather than (row, column).

No need to repurpose the words of row and column (columns are always the actual vectors) just because of differences in how it's stored internally.

**Comment by aaronfranke** [comment]
I'll add some other problems with this article here too. [Article link](https://docs.godotengine.org/en/latest/tutorials/math/matrices_and_transforms.html) and [source link](https://github.com/godotengine/godot-docs/blob/master/tutorials/math/matrices_and_transforms.rst).

![Leonardo](https://docs.godotengine.org/en/latest/_images/tutomat2.png)

This image contains 3 points, all of which have a positive Y component, yet one is below the X axis.

![XY Spaceship](https://docs.godotengine.org/en/latest/_images/tutomat6.png)

The red coordinates are not following Godot's handedness, but the gray ones are.

![Upright ship](https://docs.godotengine.org/en/latest/_images/tutomat9.png)

The Y-is-front on every other image implies that this ship should be facing down in the identity position. Either this image needs to be the other way around, or everything else does.

![Matrix](https://docs.godotengine.org/en/latest/_images/tutomat10.png)

Assuming that "Xy" is equal to `transform.x.y`, the row/column order should be reversed.

![Graph](https://docs.godotengine.org/en/latest/_images/tutomat11.png)

None of these images follow Godot's coordinate system of Y-is-down. They are what you would see in a math class, where Y is up.

IMO an article in the Godot documentation about transforms should reflect *how they work in Godot*.
