### ISSUE TITLE
Clarify purpose of load_steps in TSCN File Format

### ISSUE THREAD

**Issue by noidexe** [godotengine/godot-docs#1354]
http://docs.godotengine.org/en/3.0/development/file_formats/tscn.html
In the document linked above there's the following sentence: 

> The file descriptor looks like [gd_scene load_steps=1 format=2] And should be the first entry in the file. The load_steps parameter should (in theory) be the number of resources within the file, though in practice it’s value seems not to matter.

I think the official docs should be an authoritative source of information without any "it seems", "in theory" "it should" since it's supposed to come from the people creating the engine. I know the person writing the docs wasn't sure but maybe someone from the dev team can clarify whether the value is used or ignored.

**Comment by LinuxUserGD** [comment]
"All scene files should have exactly one scene root. It it does not, Godot will fail to import the file." After manually editing the file?

**Comment by LinuxUserGD** [comment]
Maybe load_steps is the number of external ressources and sub-resources -1 (because counting starts at 0)?

**Comment by Pfeil** [comment]
I have a scene with 4 external resources and 3 "internal" resources. load_steps is 5.
I just removed one external resource, load_steps was reduced to 4.

Not sure what exactly it is counting, but for merge conflicts within projects, it would be useful for game developers to understand the meaning.

**Comment by Calinou** [comment]
`load_steps` is used to display a progress bar when using ResourceInteractiveLoader (or any kind of progressive loading in general). If it was removed, it would no longer be possible to display a progress bar while loading a scene.

**Comment by noidexe** [comment]
https://github.com/godotengine/godot/blob/master/scene/resources/resource_format_text.cpp#L1539
Here is the calculation for the load_steps. I'm not familiar with the code so I didn't find it very easy to follow and it certainly could do with a few more comments, but after reading it and inspecting a number of different tscn files what I understand is that the value of load_steps is:
+1 for every ext_resource
+1 for every sub_resource
+1 for the tscn file itself, which is of course a resource

Examples:
a) .tscn with no ext_resources or sub_resources: load_steps = 1
b) .tscn with 2 ext_resources and 5 sub_resources: load_steps = 8

@Calinou will the resource load anyway without load_steps even if it is unable to display a progress bar?

**Comment by Calinou** [comment]
> will the resource load anyway without load_steps even if it is unable to display a progress bar?

I don't know, try it and see :slightly_smiling_face:

**Comment by Calinou** [comment]
Fixed by https://github.com/godotengine/godot-docs/pull/5001.
