### ISSUE TITLE
Document MainLoop _process

### ISSUE THREAD

**Issue by hungrymonkey** [godotengine/godot-docs#1366]
http://www.gamefromscratch.com/post/2015/01/28/Godot-Engine-Tutorial-Part-3-Program-Lifecycle-and-Input-Handling.aspx

I was reading the documentation for MainLoop and realize that _process and  is not documented in the class docs.

http://docs.godotengine.org/en/latest/getting_started/step_by_step/scene_tree.html?highlight=idle

From my limited understanding, I believe _idle is called for each frame and _iteration is called when each fixed framerate.

I am actually wondering if _iteration is affected by Scenetree::set_paused

Perhaps

```
Called for each fixed rate processing.
```

**Comment by Calinou** [comment]
[`_process` is documented in Node](https://docs.godotengine.org/en/latest/classes/class_node.html#class-node-method-process), not MainLoop.
