### ISSUE TITLE
Godot QA Website Enhancement - Make it easier to see accepted answers

### ISSUE THREAD

**Issue by JarLowrey** [godotengine/godot-docs#1376]
Hopefully this is the correct place to post QA enhancements.

On your profile page, under "All Questions" tab, the site shows how many upvotes and answers each question has. It also highlights questions that have an accepted answer, but this highlight is nearly imperceptible. 

Which question has an accepted answer below? 

![image](https://user-images.githubusercontent.com/7429786/39000196-41950af8-43a8-11e8-8eea-ba3e4498a061.png)

If you put your face against the monitor you'll see the bottom has a slightly darker shade of green, and is thus accepted. I'd appreciate it if widths would change, or if both the outlines were thicker and the colors a bit more contrasted.

**Comment by Omicron666** [comment]
Thanks for your issue, maybe post it here actually https://github.com/godotengine/godot-website/issues :-)

**Comment by JarLowrey** [comment]
https://github.com/godotengine/godot-website/issues/54
