### ISSUE TITLE
Links on page Design interfaces with the Control nodes are broken

### ISSUE THREAD

**Issue by snake3276120** [godotengine/godot-docs#1379]
Build your first game UI in Godot - goes to the top of the same page
 Advanced UI nodes and Themes - broken
Design advanced UI with other Control nodes - broken

**Comment by hungrymonkey** [comment]
http://docs.godotengine.org/en/latest/getting_started/step_by_step/your_first_game.html

http://docs.godotengine.org/en/latest/getting_started/step_by_step/ui_introduction_to_the_ui_system.html

http://docs.godotengine.org/en/latest/getting_started/step_by_step/ui_code_a_life_bar.html

it kinda works

**Comment by hungrymonkey** [comment]
oh ok, if i can fix it i would try. it would probably be fixed in master first

**Comment by hungrymonkey** [comment]
@NathanLovato  

```
git blame ui_introduction_to_the_ui_system.rst

972eb064 learning/step_by_step/ui_introduction_to_the_ui_system.rst        (Nathan           2017-10-09 15:41:32 +0200  28) read `Build your first game UI in Godot <#>`__.

972eb064 learning/step_by_step/ui_introduction_to_the_ui_system.rst        (Nathan           2017-10-09 15:41:32 +0200 353) Control nodes <img/#>`__.
```

Are those docs committed yet? I was looking around and I couldnt find the proper docs for 

> design advanced UI with other Control nodes
>Advanced UI nodes and Themes

Those links seems like placeholders

**Comment by NathanLovato** [comment]
Thanks for the ping, give me a moment, I'll fix it

**Comment by hungrymonkey** [comment]
I would had fix it if i was sure about the links
