### ISSUE TITLE
All localized docs appear in search engines for other languages

### ISSUE THREAD

**Issue by mhilbrunner** [godotengine/godot-docs#1388]
Just searched for "*gdscript base class*" on Google and got a spanish Godot docs page as one of the first results.

![godot-docs-local](https://user-images.githubusercontent.com/1654763/39089097-706962d4-45bf-11e8-95f2-8925a0848ba0.PNG)

Note that this was on google.com, with a US OS, US locale, US browser, US browser language etc.

**Comment by mhilbrunner** [comment]
cc @akien-mga

**Comment by akien-mga** [comment]
It's an outdated fork (2016) of the documentation by @godotfan, not sure what to do about it. I don't administrate it so I can't influence its referencing in Google searches.

Now that we have official translations, hopefully such forks will focus their work on the upstream translations: https://hosted.weblate.org/projects/godot-engine/godot-docs/

**Comment by akien-mga** [comment]
Note that Google did point your to an English page in that Spanish fork, so its locale detection is not broken ;)

**Comment by akien-mga** [comment]
BTW @godotfan, if you want to bring your translation in the new system on Weblate, and eventually retire the godot-doc-en-espanol subdomain to the profit of the official godot-es.readthedocs.io, that would be great :)

**Comment by mhilbrunner** [comment]
Ah, d'oh, of course, somehow missed that. Will close, as its not an issue with the official docs then.
