### ISSUE TITLE
Fix wrong image in step by step GUI tutorial

### ISSUE THREAD

**Issue by rpxomi** [godotengine/godot-docs#1398]
I'm following the step-by-step tutorial on the official Godot website and it shows this option...
![1](https://user-images.githubusercontent.com/31228150/39208279-dae087da-47d8-11e8-8f8b-3ba19d471244.png)

Where is: **Full Rect and Fit Parent**?
![2](https://user-images.githubusercontent.com/31228150/39208321-00a0e7f8-47d9-11e8-8574-fda092559d86.png)

Version
![3](https://user-images.githubusercontent.com/31228150/39208334-0733243c-47d9-11e8-9602-85734b4b5a30.png)

If the documentation is in active development, you can put some kind of notice on the page. Because this is generating a bad user experience, believing that the error is of oneself for not being able to find things.

**Comment by NathanLovato** [comment]
Ah it's just that we forgot to replace this image. Full Rect and Fit Parent was merged with Full Rect 3-4 months ago, and some people helped fixed the page but we missed this picture. Give me a few moments, I'll fix it later today. Thanks for the report!
