### ISSUE TITLE
godot native script

### ISSUE THREAD

**Issue by ghost** [godotengine/godot-docs#1403]
Please add some classes this type of high performance scripts.
This can help me and a lots of developers in development of high performance scripts.

no need to optimize it like gdscript , just make some classes available .
GD_SCRIPT is good but GD_NATIVE is much more performance friendly.

**Comment by hungrymonkey** [comment]
I am confused. GDNative shouldnt be much different than writing godot modules

https://github.com/GodotNativeTools/godot-cpp/tree/master/include/core

Whatever GDNative classes support is whatever Karroffel have time porting over.

**Comment by Calinou** [comment]
There's already documentation about GDNative: https://docs.godotengine.org/en/latest/tutorials/plugins/gdnative/index.html
