### ISSUE TITLE
godot-docs/getting_started/step_by_step/ui_main_menu.rst

### ISSUE THREAD

**Issue by AdelMahjoub** [godotengine/godot-docs#1404]
Misleading tutorial

> Design a title screen
> In the next two tutorials, you will build two responsive UI (user interface) scenes step-by-step using the engine's UI system:

The layout built in the tutorial is not responsive, at best it is a flex layout where the menu options is always centered between the logo and the version

> then, the screen is split into two columns, so we'll use an HBoxContainer

It depends on the viewport, 1024 width is not enough to contain the two column proposed and the columns are not responsive

> Prepare the Main Menu scene
> Let's create the main menu. We'll build it in a single scene. To create an empty scene, click on the Scene menu -> New Scene.
> 
> We have to add a root node before we can save the scene. Your UI's root should be the outermost container or element. In this case it's a MarginContainer. MarginContainer is a good starting point for most interfaces, as you often need padding around the UI. Press Meta+S to save the scene to the disk. Name it MainMenu.
> 
> Select the MarginContainer again, and head to the inspector to define the margins' size. Scroll down the Control class, to the Custom Constants section. Unfold it. Set the margins as such:
> 
> Margin Right: 120
> Margin Top: 80
> Margin Left: 120
> Margin Bottom: 80

Why setting the margin when next we set the layout to full rect, as this will set all margins to 0

> We want the container to fit the window. In the Viewport, open the Layout menu and select the last option, Full Rect.

Let's say we want the margin, if all anchors at 0 the right and the bottom margins value are too low
The anchors should be top 0, left 0, right 1, bottom 1, and the right and bottom margins should be negative

The rest of the tutorial do not make much sense if it is intended to build a responsive layout

**Comment by NathanLovato** [comment]
> a flex layout where the menu options is always centered between the logo and the version

That's a responsive UI: as opposed to a fixed layout, it responds to the window being resized. I know it's popular to think of responsive as *completely different layouts on desktop and mobile* but that's not what the word means, it's just something web designers have to do often as part of their job.

It's not how UI typically works in games. When you port the game from desktop to mobile (rare) you'll likely redesign the controls entirely. So you'll likely make a different UI scene e.g. with round touch-based buttons vs a controller-driven menu on desktop.

If the word responsive is that confusing to you, we can just change it. 

> 1024 width is not enough to contain the two column 

A game's viewport always has a minimum size, and so do mobile phones. A low end device will likely be > 1280 * 720 px. In this tutorial I think the base resolution is 720p so it should never be < 1024px wide.

> Why setting the margin when next we set the layout to full rect, as this will set all margins to 0

I wrote this tutorial during Godot 3 beta and the way the UI layout works changed after that. It's been modified by other contributors but this may have slipped. Back 6 months ago Full Rect didn't change the margins.

**Comment by AdelMahjoub** [comment]
Thanks for the clarification, I should try to better understand how Godot control containers works, at first glance the anchor and margins works exactly as CSS bounding box, and the containers reminds me of css framework containers, but there is more than that I guess.

**Comment by NathanLovato** [comment]
Ah it doesn't work like CSS to me. Anchors act more like percentage-based margin lines (relative to the parent node) and margin like CSS padding, to give you a rough parallel using the web's box model.

In practice it's even more different in that you have a wide range of specific nodes to work with, UI components, so yeah it's really like an app UI framework in that sense - anyway Godot's entire editor UI is built with these nodes

Regarding the docs article should I change some things? Do you think responsive is misleading?

**Comment by AdelMahjoub** [comment]
In the next tutorial I got the point where for games the layout should only be responsive according to a minimum screensize and an aspect ratio and that make sense, the game will run on a device with a fixed screensize, for windowed mode there should be a maximum and a minimum.

I think the title is ok.

In the next tutorial there must be some changes because some options are not available suchs as Full rect and fit the parent.
![ui_gui_step_tutorial_counter_design_2](https://user-images.githubusercontent.com/15039914/39308351-80fba108-4965-11e8-8e4e-d91dbaaf3917.png)

The icon here shouldn't be in a center container as it will break the layout
![ui_gui_step_tutorial_counter_design_4](https://user-images.githubusercontent.com/15039914/39308471-d101814a-4965-11e8-9584-52de4a07fe4c.png)

And couldn't find a way to resize the background for the ep counter when following the tutorial, but in the end folder in the source files it is resized correctly.

Well that must be written in a different Godot version, thanks for your help, I'll keep reading and figure out the changes.

**Comment by NathanLovato** [comment]
> Well that must be written in a different Godot version, thanks for your help, I'll keep reading and figure out the changes

3.0 beta, right before they updated the UI system 😄 I replaced the wrong image yesterday but it can take time for the docs to rebuild, and actually i forgot to cherry pick the change to branches other than master.

For these tuts I'm looking to update the demos for the official demos repo - as there's little on UI now - and make updated video tuts for the hybrid UI workflow introduced in 3.0 stable. Maintaining the text version is a pain as it's something that's visual in nature, I feel it doesn't work well.
