### ISSUE TITLE
C# requirements need to be more explicit. 

### ISSUE THREAD

**Issue by Muzz** [godotengine/godot-docs#1417]
So i just spent half a day debugging an issue as to why the "is" examples in input weren't working.

Turns out, that it's easy to have it use msbuild.exe 14 instead of 15, and to fix it i tried to download the 2017 ms build tools, but that didn't work, until i found out only installing VS community would make it work. 

The documents only state:
`
To use C# in Godot you must have Mono installed (at least version 5.2), as well as MSBuild (at least version 15.0) which should come with the Mono installation.`

Which doesn't mention anything about the .net sdk, or VS community.  Oh right this is for windows as well. 

So i propose that we have links to VS community and a line about the build tools not working for this. 
Kelly thomas's comment here was the only one that helped me getting the correct version of Msbuild working.

https://github.com/godotengine/godot/issues/18152

**Comment by neikeq** [comment]
This may have been fixed by godotengine/godot#18561.
