### ISSUE TITLE
Code containers are cropped in mobile browsers

### ISSUE THREAD

**Issue by eon-s** [godotengine/godot-docs#1430]
Tested on chrome, android.

Code containers get the contents cropped like this:
![cropped_code_in_phone](https://user-images.githubusercontent.com/10215987/39675828-2cdf0004-5137-11e8-985e-3193df91c12b.jpg)

In desktop mode, the contents are not cropped, and in desktop browsers, small windows make scrolls to appear in the code containers.

**Comment by Juankz** [comment]
In mobile just slide your finger and it scrolls

**Comment by Calinou** [comment]
> In case is the later, is it there a way to make it always visible? because some people may not realize that there is more inside if no scroll bar is shown.

I'm not sure if it's possible to always display scrollbars in mobile browsers.

**Comment by Juankz** [comment]
:thinking: To me it was obvious to scroll. I checked a random stackoverflow post and the behavior is the same as in Godot

**Comment by Calinou** [comment]
This is common behavior on mobile browsers (which we can't really override anyway), closing.
