### ISSUE TITLE
Small detail on "Your First Game" tutorial

### ISSUE THREAD

**Issue by CharlesAnjos** [godotengine/godot-docs#1439]
The section describing the mob scripting forgot to put an `$AnimatedSprite.play()` at the end of the `_ready` function. Without it, the mobs don't animate.

**Comment by KellyThomas** [comment]
I think this is taken care of with the inspector:

> Set up the AnimatedSprite like you did for the player. This time, we have 3 animations: fly, swim, and walk. Set the Playing property in the Inspector to “On” and adjust the “Speed (FPS)” setting as shown below.

**Comment by CharlesAnjos** [comment]
Oh damn, that's right. Totally glossed over the Inspector part. So sorry for opening this issue without double-checking there.
