### ISSUE TITLE
Description of Vector2::angle() is incorrect

### ISSUE THREAD

**Issue by mwerezak** [godotengine/godot-docs#1440]
In the 3.0 docs online, it states:
> Be aware that it therefore returns an angle oriented clockwise with regard to the (0, 1) unit vector, and not an angle oriented counter-clockwise with regard to the (1, 0) unit vector (which would be the typical trigonometric representation of the angle when calling Math::atan2(y,x)).

However you can verify yourself that it returns an angle oriented clockwise with regard to the (1, 0) unit vector.

```
print(Vector2(1,0).angle()) ## outputs 0
print(Vector2(0,1).angle()) ## outputs 1.570796
```

**Comment by cbscribe** [comment]
You're right, this is a holdover from 2.1 documentation. Thanks for the tip, I'm doing some edits today, so I'll change it.
