### ISSUE TITLE
FPS Tutorial - Error in Player.gd

### ISSUE THREAD

**Issue by LucSps** [godotengine/godot-docs#1450]
The move_and_slide function in Player.gd receives 5 parameters, with a "true" extra in that function.
This error is in the code to copy in "http://godot-es.readthedocs.io/es/latest/tutorials/3d/fps_tutorial/part_one.html" and in all .rar files to download (part 1, 2, 3, 4, 5, final).

**Comment by Noshyaar** [comment]
Extra parameter is introduced in Master branch, not stable.

Use stable version of the docs: http://docs.godotengine.org/en/stable/tutorials/3d/fps_tutorial/part_one.html

**Comment by Noshyaar** [comment]
Closing as invalid. You need to use the right version of the docs.
