### ISSUE TITLE
FPS Tutorial - Crashed Final Part.rar

### ISSUE THREAD

**Issue by LucSps** [godotengine/godot-docs#1451]
The project is crashed directly in the editor, so it does not open. I have the latest version of Godot (v3.0.2-stable_win64).
In cmd:
running cmdline: "C:\Users\Lucas\Desktop\Godot\Godot_v3.0.2-stable_win64.exe" "--path" "C:/Users/Lucas/Desktop/Godot/doc/Godot_FPS_Finished" "--editor"
ERROR: ProjectSettings::_load_settings_text: Condition ' config_version > 3 ' is true. returned: ERR_FILE_CANT_OPEN
   At: core\project_settings.cpp:495
ERROR: ProjectSettings::_load_settings_text_or_binary: Couldn't load file 'C:/Users/Lucas/Desktop/Godot/doc/Godot_FPS_Finished/project.godot', error code 12.
   At: core\project_settings.cpp:519
OpenGL ES 3.0 Renderer: 67EF:CF

**Comment by Noshyaar** [comment]
Try again with the zip file in stable docs: http://docs.godotengine.org/en/stable/tutorials/3d/fps_tutorial/part_one.html

`3.0.2` is the most recent stable version. It's not the same as `latest`. You need `stable` or `3.0` docs for this.

`latest` refers to custom builds from the source's master branch. This is where you'd use `latest` docs.

**Comment by LucSps** [comment]
The problem is in the part 6 in: http://docs.godotengine.org/en/latest/tutorials/3d/fps_tutorial/part_six.html
The name of the file is Godot_FPS_Finished.zip

**Comment by Noshyaar** [comment]
That link is `latest` docs.

**Comment by Noshyaar** [comment]
Closing as invalid. You need to use the right version of the docs.

Issue about crashing immediately due to incorrect config version should be filed separately on the main repository.
