### ISSUE TITLE
AudioStreamSample.loop_begin and .loop_end use samples not bytes

### ISSUE THREAD

**Issue by CptPotato** [godotengine/godot-docs#1457]
the properties _loop_begin_ and _loop_end_ of _AudioStreamSample_ seem to use **samples** as unit, **not bytes** as written in the [documentation](http://docs.godotengine.org/en/3.0/classes/class_audiostreamsample.html)

**Comment by skyace65** [comment]
This was fixed by https://github.com/godotengine/godot/pull/37921. This issue can be closed.

**Comment by skyace65** [comment]
@GDQuest This was fixed by godotengine/godot#37921. This issue can be closed.
