### ISSUE TITLE
SSL_ERROR_BAD_CERT_DOMAIN when accessing https://docs.godotengine.org

### ISSUE THREAD

**Issue by azurvii** [godotengine/godot-docs#146]
When I access https://docs.godotengine.org, Firefox prompted me the following error:

> docs.godotengine.org uses an invalid security certificate.
> The certificate is only valid for the following names: *.readthedocs.org, readthedocs.org
> Error code: SSL_ERROR_BAD_CERT_DOMAIN

**Comment by akien-mga** [comment]
Ping @punto and @alketii

**Comment by bojidar-bg** [comment]
Note that http://docs.godotengine.org works fine

**Comment by reduz** [comment]
I don't think we ever had a certificate..

**Comment by azurvii** [comment]
the http version does not need a cert, and works just fine as bojidar-bg said. what i was reporting is the https version.
@reduz, you may be right about the docs.godotengine.org, since the error said the cert is for readthedocs.org domain instead (i have no idea about what's the relationship between docs.godot and readthedoc). https://godotengine.org however, has a valid cert signed by CA "Let's Encrypt".

**Comment by vnen** [comment]
If that's not clear https://docs.godotengine.org used to have a valid certificate. Something changed in the ReadTheDocs side.

**Comment by akien-mga** [comment]
@punto- ReadTheDocs has changed the domain for the hosted projects to ``readthedocs.io`` (instead of ``readthedocs.org``. It looks like https://godot.readthedocs.io/en/latest has a valid certificate. Maybe we need to update our DNS config [0] to point to ``readthedocs.io``?

https://read-the-docs.readthedocs.io/en/latest/alternate_domains.html#cname-support

**Comment by mhilbrunner** [comment]
I just fixed this. https://docs.godotengine.org is now serving a proper cert and is encrypted. Big thanks to RTD (see https://github.com/rtfd/readthedocs.org/issues/2652)
