### ISSUE TITLE
FPS Tutorial not Backwards Compatible

### ISSUE THREAD

**Issue by bastisawesome** [godotengine/godot-docs#1473]
So, I'd gone through the FPS tutorial through part 4 before 5 and 6 were added and with the added parts were changes to the base that seem to be impossible, or at least inconvenient, to work with unless you completely reset your code.

**Comment by TwistedTwigleg** [comment]
The entire FPS tutorial was remastered after part 4 to fix some style issues (and other stuff). You may be able to go forward in the tutorial if you start at part 4 with the old tutorial's part 4 project. Unfortunately, I did not design the remaster to be backwards compatible with the old FPS tutorial, as there was quite a few minor changes needed for parts 4-6.

Sorry for the inconvenience!
