### ISSUE TITLE
Documenting how to configure SSL certificates

### ISSUE THREAD

**Issue by azurvii** [godotengine/godot-docs#148]
The instruction on http://docs.godotengine.org/en/latest/tutorials/ssl_certificates.html is outdated. I can find nowhere in the project settings letting me configure the certs. And I'm not quite clear what does the "Filters for non-resource files" part do.

Much appreciate any help on updating the doc and adding some explanation.

Thanks!

**Comment by Anutrix** [comment]
![Annotation 2020-01-31 185816](https://user-images.githubusercontent.com/11459028/73542902-c2d9fc80-445b-11ea-8085-8f6c481a49b4.png)
Isn't this it?

**Comment by Calinou** [comment]
The information in that page is now up-to-date, closing.

Note that you generally don't need to set up SSL certificates manually anymore as Mozilla's certificate bundle is now included in the editor and export templates.
