### ISSUE TITLE
Global url list/file and tokenizing all urls.

### ISSUE THREAD

**Issue by romeojulietthotel** [godotengine/godot-docs#1483]
While fixing some urls (404s, redirects and broken) I realize that it's a cumbersome task to keep them fresh.

A more human scalable way would be to maintain a master list of urls and then instead of inserting a url into each doc we insert a static token. Then via sphinx the token is translated to the url that matches the token. The token never changes and only the global list would need updating. We could make it so that the tokens are human readable and not abstracted too far away from the url.

The global list would contain the url and the token. This would mean just one file or urls would need to be edited and then the sphinx build would do the rest.

**Comment by romeojulietthotel** [comment]
There was a built in extension in Sphinx for this already. See PR https://github.com/godotengine/godot-docs/pull/1494.

**Comment by mhilbrunner** [comment]
Closing this; see discussion in https://github.com/godotengine/godot-docs/pull/1494.
