### ISSUE TITLE
Document the patching tab

### ISSUE THREAD

**Issue by Far117** [godotengine/godot-docs#1484]
It is quite difficult to find any mention of patching .pck files using the patch tab that isn't merely a passing reference. For example, when I click "export patch," nothing seems to happen.

I did find [a twitter post](https://twitter.com/reduzio/status/833439304571551744?lang=en) which teased it, along with a [similar issue](https://github.com/godotengine/godot-docs/issues/154). The similar issue, however, seems to be more concerned with managing multiple packages in general, rather than the automatic and incremental patching system (at least as far as I understand what it's supposed to do).

If the feature is not yet usable, perhaps it should have some indication of that?

**Comment by avencherus** [comment]
I would also love to know more about how it works.

**Comment by Calinou** [comment]
The Patches tab was never made functional and was therefore [hidden](https://github.com/godotengine/godot/pull/34911) in Godot 3.2. Since it will likely be remade from scratch in a future Godot version, I'll close this issue.
