### ISSUE TITLE
C#/Mono: Document ToSignal

### ISSUE THREAD

**Issue by mhilbrunner** [godotengine/godot-docs#1487]
See https://github.com/godotengine/godot-docs/pull/1445

**Comment by neikeq** [comment]
Self-assigned, but feel free anyone to take it if you want to do it sooner.

**Comment by skyace65** [comment]
@gdquest ToSignal was added to the API differences to GDScript page. https://docs.godotengine.org/en/stable/getting_started/scripting/c_sharp/c_sharp_differences.html#yield. I think this issue can be closed.
