### ISSUE TITLE
InputEventMouseButton.factor missing documentation

### ISSUE THREAD

**Issue by alkhimey** [godotengine/godot-docs#1490]
https://github.com/godotengine/godot-docs/blob/31a6f62fd5065f237e1ce282fa794be833e79383/classes/class_inputeventmousebutton.rst#L32

> "float factor - TO TALK in PR, reduz said : i think it’s used for apple touch but i don’t remember what it does"

![screenshot from 2018-06-01 20-45-51](https://user-images.githubusercontent.com/652603/40855364-1215bda2-65dd-11e8-958d-66120fd72d85.png)

**Comment by mhilbrunner** [comment]
Fixed in https://github.com/godotengine/godot/pull/19620 - thanks!
