### ISSUE TITLE
Make contributing to documentation easier.

### ISSUE THREAD

**Issue by romeojulietthotel** [godotengine/godot-docs#1499]
Contributing to docs is cumbersome and prevents some from doing it.

#### Some ideas toward that goal:

1. Allow contributions in the issue tracker and an issue template designed for this purpose
2. Allow just a plain old issue to be opened with the filename to be modded and the mod needed
3. Allow linking to a new issue directly from the docs, maybe with some javascript or a link on each page

4. Continuous integration for the docs for pull requests.

**Comment by mhilbrunner** [comment]
CI was added. Making contributions to the docs easier is a reoccuring topic in the docs team, however, the expertise needed to submit a Pull Request via the GitHub UI isn't that much compared to the one needed to make meaningful contributions to the documentation.

However, we're always open to suggestions.

Note that in general it's fine to point out things like typos in issues or on IRC/Discord (which even has a `documentation` channel).

Also, contributing to the translations is a little easier, as it's mostly done via a web UI.
