### ISSUE TITLE
Nonexistent function 'set_default_cursor_shape' in base 'InputDefault'.

### ISSUE THREAD

**Issue by mwerezak** [godotengine/godot-docs#1511]
But it's clearly listed in the docs for the Input class.

**Comment by vnen** [comment]
Are you using the same version of the docs and of Godot? Note that the `latest` docs point to the current development version, not the last stable.

**Comment by mwerezak** [comment]
@vnen thanks for pointing this out, I wasn't aware of this. I saw v: 3.0 in the corner of the page and assumed it meant stable.

Just checked the stable docs and the entry for `set_default_cursor_shape` wasn't there.
