### ISSUE TITLE
For Loop Dictionary Documenation Misleading

### ISSUE THREAD

**Issue by cwook** [godotengine/godot-docs#1514]
(3.0 latest)
When [describing using for loops on a dictionary](http://docs.godotengine.org/en/latest/getting_started/scripting/gdscript/gdscript_basics.html?highlight=dictionary), the documentation is misleading:
`When iterating over a dictionary, the index is stored in the loop variable.`
The index is not stored in the loop variable, the key is.
The code example should be changed to something like this:
```
var dict = {"a": 0, "b": 1, "c": 2}
for i in dict:
    print(dict[i]) # prints 0, 1, 2
for i in dict:
    print(i) # prints a, b, c
```

**Comment by vnen** [comment]
Well, "key" and "index" are interchangeable words, they mean the same thing in this context.

**Comment by OvermindDL1** [comment]
> Well, "key" and "index" are interchangeable words, they mean the same thing in this context.

Eh, `index` to me means a guaranteed ordering, where `key` to me means an indeterminate ordering, so they don't seem interchangeable to me....

**Comment by mhilbrunner** [comment]
I agree that changing this to 'key' would be more consistent with a dictionary.
