### ISSUE TITLE
Non-English docs appear on the top of Google search results

### ISSUE THREAD

**Issue by ronroniv** [godotengine/godot-docs#1520]
Recently when I search Godot related topics on Google, I often see non-English (especially Ukrainian) docs on the top of the results.

![gooodot](https://user-images.githubusercontent.com/25771553/41481027-743b19c6-710b-11e8-8e78-72d9863a9baf.png)

(FYI, I'm using Google in English from South Korea.)

The pages are mostly in English (which I guess is the reason why Google thinks they are English pages) so it's not major inconvenience, but I think occasional paragraphs, headers, and table of content written in Ukrainian may confuse people.

I wonder if this can be resolved with something like metadata? I'm not sure.

**Comment by akien-mga** [comment]
This is a known issue, and I've actually pushed a potential fix for it a few days ago: b6cb5c3ee7ec86b8730bb14af80c4a4089328175

But I guess we need to give search engines a few more days to catch up, *if* that fix is efficient.

**Comment by ronroniv** [comment]
Looks like the fix is effective. At least for me, most results are now showing English docs at the top (Polygon2D for example), but there are still few keywords ("Godot + Sprite", "Godot + Area" for example) getting Ukrainian docs.

**Comment by akien-mga** [comment]
It seems to be better now in my tests. All of "Godot" + "Polygon2D"/"Sprite"/"Area" gave me the `en` results.

**Comment by BornStellarMakesEternalLasting** [comment]
I also saw `en` results when I googled godot , godot area, godot sprite.

**Comment by ronroniv** [comment]
Same here! For the past few days I've only seen English docs on the top.

**Comment by akien-mga** [comment]
Nice! Fixed by b6cb5c3 then.
