### ISSUE TITLE
Mention that crosshair image needs to be 32x32 in the doc

### ISSUE THREAD

**Issue by medakk** [godotengine/godot-docs#1527]
In the doc for [Customizing mouse cursor](http://docs.godotengine.org/en/3.0/tutorials/inputs/custom_mouse_cursor.html), it is mentioned:

> The custom image must be less than 256x256.

However, according [this PR](https://github.com/godotengine/godot/pull/12814), the custom image size must be 32x32. I spent a bit of time investigating why my custom image wasn't working, and I think this behavior must be reflected in the doc.

**Comment by akien-mga** [comment]
The limitation to 32x32 was lifted in the master branch (https://github.com/godotengine/godot/pull/18002), so the `latest` docs are correct.

The `3.0` docs could indeed be changed, unless https://github.com/godotengine/godot/pull/18002 gets backported to 3.0.4.

**Comment by FeralBytes** [comment]
@hpvb would it be possible to cherry pick 18002 into 3.0.7?

**Comment by Klowner** [comment]
Looks like a note regarding the 32x32 image size requirement was was added to the 3.0 branch docs in 22bcd6b8e. Maybe safe to close this?

**Comment by Calinou** [comment]
Closing per @Klowner's comment.
