### ISSUE TITLE
Your First Game/HUD: Confusing section with inaccurate instructions

### ISSUE THREAD

**Issue by zedwick** [godotengine/godot-docs#1541]
Very new to Godot, had a lot of trouble understanding this section.

There are references to anchors in this section, but in Godot v3.0.4 the button is labelled "Layout". 
There is then a list of settings, some of which I already know are found in the inspector from earlier in the tutorial (Text, for example). However, 'Layout' is not found there. This may have been a little clearer if the layout button had not been called the 'anchor' button earlier, but I think the list makes the settings seem like they would be found in the same place.

I also found that setting the margins to the listed values did not put things in the same places as shown in the image. I had to do a bit of experimenting to find values which worked.

In other parts of the tutorial, the "Notes" box would come after introducing a new concept, but here it seems to come before which left me feeling like I'd missed something.

I also found that the size of the text did not match the image at all, and spent some time trying to figure out how to resize it. the tutorial actually covers this later, but I felt the image led me to believe that is what I should have nearer that point in the tutorial. Especially so considering the red circle indicating the layout button, though I think I ignored the red circle as the image was presenting a final product rather than what I had at the time.

Further down I am given `$MessageLabel.text = "Dodge the\nCreeps!"` in the `show_game_over()` function, where the text value given earlier did not contain a line break. (I used word-wrap in my attempts to match the provided image). I think some consistency may be needed.

**Comment by BornStellarMakesEternalLasting** [comment]
> "...,but in Godot v3.0.4..."

I think it is worth mentioning that the docs have one version - version 3.0. So whether a 
reader is using Godot 3.0.4 or 3.0.0 (like me) the docs will be the same regardless of 
the version used. 

> "This may have been a little clearer if the layout button had not been called the 'anchor' button earlier"

I think the documentation may benifit from telling the reader to click the layout button in 
the 2D editor, then manuver to the bottom of the list that says "Anchors only", then have 
the reader select the anchor. Unless I am missing something and there is a difference between
the anchors only button and the anchor drop-down menu from the inspector. 

>"I also found that setting the margins to the listed values did not put things in the same places as shown in the image"

At first I also had trouble trying to get the margins correct. First I graphically organized the nodes, then I took a look at the margins settings. When I edited the margins settings the new numbers moved my nodes around to points that did not line up with the picture. I should have 
first pressed the layout button, selected the layout, for example "Center Top" then adjusted the 
margins. 

I think the sentence towards the top of the HUD section that says 
>"Arrange the nodes as shown below. Click the “Anchor” button to set a Control node’s anchor:" 

which is just above the picture should instead say something to the effect of 
> "This is what the finished HUD will look like and the layout button you will 
need is at the top of the 2D editor bar. First select the appropriate layout then adjust the 
margins based on the documentation."

**Comment by triptych** [comment]
I think in general this example is way too complicated for a "your first game".  It's more of a "let's tour the basic features" and feels more like a 3rd or 4th game. Also, this tutorial would benefit from having some pauses in the discussion where the player should "run the game" as it is to see if all their code is working to that point.  And I agree, when I was doing the layout part I thought I was doing it wrong because my text looked nothing like the screenshots and the "layout" button was not fully explained.
