### ISSUE TITLE
Website/theme suggestions

### ISSUE THREAD

**Issue by razcore-art** [godotengine/godot-docs#1551]
There's two major things that I personally don't like about the current docs site visuals.

1. sooo much space is wasted and it's especially problematic for those expanding tables as they get trimmed down needlessly
2. there's still no scroll bar on panel to the left which makes it particularly annoying when you expand large submenus like the GDScript API

Anyone around here know how to do some web wizardry? I imagine making the main column expand to occupy the available space is pretty easy, I could probably do that, but I want to know if anyone else is annoyed by these things or is it just me.

![image](https://user-images.githubusercontent.com/1177508/42122191-47bcc76c-7c3e-11e8-812e-2fadb3bfce51.png)

**Comment by Calinou** [comment]
Expanding the column is probably not a good idea, otherwise text lines will become too long, which hurts readability (lines with less than ~80 characters are easier to read).

However, centering the column should be done. Unfortunately, the Read the Docs theme doesn't seem to provide an option for that, so we would have to do it ourselves.

**Comment by razcore-art** [comment]
Yeah I know the theory being the 'row text length', I guess I'd be in the minority, I don't think it's a big deal and I'm more interested in the pictures/tables which get shrunk because of the short column width.

Having that type of table expansion in a fixed width small column is just impractical
![image](https://user-images.githubusercontent.com/1177508/42133735-ae107c0c-7d2e-11e8-9109-6189303769b5.png)

Could be fixed multiple ways, including just having the table fixed size and breaking the line if it gets too long. I'm sure it can be set up somewhere.

Another thing that could be considered is an increase in font size. For comparison:
![image](https://user-images.githubusercontent.com/1177508/42133746-fd853aa2-7d2e-11e8-859a-06d74485a3f6.png)

This would keep the length of the text row within parameters (~ 60-80 words) but will expand the column and give more room for pictures. If the column could be expanded this way that is..

While that panel scroll bar is really a must, no doubt about it, there has to be a way to add a little scroll bar there.

**Comment by NathanLovato** [comment]
The docs now have a new theme. Here they respect my browser's configuration when it comes to font size so that should solve your issue, at least in part. If you want to suggest changes for the new theme, could you open a new issue? http://docs.godotengine.org/en/latest
