### ISSUE TITLE
Dodge the creeps, explain `flip_h = velocity.x < 0` for beginners

### ISSUE THREAD

**Issue by akien-mga** [godotengine/godot-docs#1559]
See https://steamcommunity.com/app/404790/discussions/0/1729828401680097511/

One user on Steam was confused about this code chunk in the Dodge the creeps tutorial:
```gdscript
if velocity.x != 0:
    $AnimatedSprite.animation = "right"
    $AnimatedSprite.flip_v = false
    $AnimatedSprite.flip_h = velocity.x < 0
elif velocity.y != 0:
    $AnimatedSprite.animation = "up"
    $AnimatedSprite.flip_v = velocity.y > 0
```
and especially the part assigning `velocity.x < 0` to `flip_h`.

I think it's good to show this construct as it's quite idiomatic in most programming languages, but it might be worth explaining a bit more for beginners.

Personally I would start by putting parentheses to make the operator precedence clear `flip_h = (velocity.x < 0)`, which is also quite idiomatic when return/assigning the result of a condition test to a variable.

Then if need be, adding a comment to make this more explicit might be good too.

**Comment by cbscribe** [comment]
Good idea. The tutorial is explicitly *not* a "how to code" tutorial, but the boolean assignment can throw some people if they haven't seen it before.
