### ISSUE TITLE
Create new branch when forking godotengine/godot repository

### ISSUE THREAD

**Issue by BornStellarMakesEternalLasting** [godotengine/godot-docs#1569]
Reading the  Community -> Contributing -> Contribute to the Class Reference -> Fork Godot I noticed that cloning the repository and then running the command `git checkout -b your-new-branch-name` results in an error `fatal: Not a git repository (or any of the parent directories): .git` instead there needs to be another command before the `git checkout` command like so `git branch <branch name>`.

**Comment by vnen** [comment]
The `-b` option of `git checkout` already tells it to create a new branch. The error you mention means you were not on the cloned folder when you issued the command. What is missing is a `cd godot` command after the clone.

**Comment by BornStellarMakesEternalLasting** [comment]
Thanks that worked! I verified the `cd godot` command worked by using `git branch --list` and it showed the new branch.
