### ISSUE TITLE
Google sometimes returns results for docs in Ukranian

### ISSUE THREAD

**Issue by voithos** [godotengine/godot-docs#1574]
Not sure if this is the appropriate repo to file this issue in, but here goes.

I've noticed recently that searching Google for certain godot docs ends up linking to Ukranian docs pages instead of English. Example: searching for "[tween godot](https://www.google.com/search?q=tween%20godot)"

Most of that particular docs page doesn't appear to be translated yet, so I wonder if that's causing the issue? (The sidebar is partially in Ukranian, though)
I did test this in an incognito window, so in theory it should behave similarly for others in the US.

**Comment by akien-mga** [comment]
That's the same issue as #1520.

It's improving little by little but apparently there are still some search results that will lead to the /uk domain, as you found out. The fix mentioned in #1520 does seem partially working though, things have improved a lot since the issue originally crept up.

**Comment by mhilbrunner** [comment]
Over time, this should now be fixed thanks to https://github.com/godotengine/godot-docs/pull/3422 after Google reindexes the pages after Akien created the `stable` docs branches for the translations now.

So we'll wait and see. Closing for now!
