### ISSUE TITLE
Instructions on how to generate export templates like the official ones

### ISSUE THREAD

**Issue by akien-mga** [godotengine/godot-docs#158]
See http://steamcommunity.com/app/404790/discussions/0/364042703865087202/

We have the "Batch building templates" page but it's not really user-friendly. We should maybe add a section about building and packaging the templates on the Compiling for {X11,Windows,OSX} pages.

**Comment by akien-mga** [comment]
Especially relevant too is how to build iOS binaries that actually work. Users need to build them for both arches and merge them together using the `lipo` tool, as done in our travis script: https://github.com/GodotBuilder/godot-builds/blob/master/.travis.yml#L136

**Comment by pwab** [comment]
If I am not wrong every entry of the [Compiling section](https://godot.readthedocs.io/en/latest/development/compiling/index.html) contains a guide for building the export templates now. There is room for improvement though (like how to adapt these templates to your needs).

**Comment by mhilbrunner** [comment]
Closing for https://github.com/godotengine/godot-docs/issues/1227.
