### ISSUE TITLE
Error in Weblate

### ISSUE THREAD

**Issue by xavierocampos** [godotengine/godot-docs#1584]
Hello, I'm a regular translator at Weblate and I recently detected a problem, the question is as follows:

There are some text strings in the documentation that affect Godot's translation when translating them.

I detected this problem when translating the word "Transform", exactly this is the string: https://hosted.weblate.org/translate/godot-engine/godot/es/?q=Transform&search=ftx&source=1&target=1&type=all=all&offset=7

When translating this word into Spanish it also affects the Spanish documentation, and in Godot it is correct to translate this word for the interface, but in the documentation part they refer to the Transform class and it is not correct to translate it, so here we have a problem.

I don't know if you've explained it correctly, the point is that there are shared strings and they should be completely independent. I have detected the problem in that chain but I am sure it is a problem that exists in other similar chains.

**Comment by akien-mga** [comment]
I'm not sure to understand what the exact problem is. You can translate "Transform" in the editor interface as you did, while keeping references to the `Transform` class in the docs translation unmodified, no?

**Comment by xavierocampos** [comment]
No, if it is translated in the editor interface it also affects docs translation. It is not the only text string in which this problem occurs, but it is in the text string that you locate this problem.

In some cases this may not be a problem, but in this case it is because in the editor interface, "Transform" is translated as "Transformar", but in docs translation when referring to a "Transform" class it should not be translated.

**Comment by akien-mga** [comment]
I still don't understand though. The editor and docs translations are separate projects, so the translation of the former has no impact on the latter.

If there is a "Transform" msgid in the editor, and it refers to the action of transforming things, then it can be translated to "Transformar" indeed. If it refers to the "Transform" class, it should be left as is. Same rule for the docs.

**Comment by xavierocampos** [comment]
There is the concern, which in theory is as you mention, are separate projects, but in practice what is done in one is affecting the other:

**Editor Interface:**
![editor-interface](https://user-images.githubusercontent.com/9200707/43104429-0af176b4-8e97-11e8-99b6-9d1aa5e1f75b.jpg)

**Doc Translator:**
![doc-translator](https://user-images.githubusercontent.com/9200707/43104445-1926ec6e-8e97-11e8-90eb-e6d6c889436a.jpg)

I don't know the reason why this is happening.

**Comment by mhilbrunner** [comment]
Closing this due to the age of the issue. If this is still an issue, feel free to open a new issue or talk to us on IRC or Discord (the latter has a `#documentation` channel).

Thank you!
