### ISSUE TITLE
Search ignores . and encasing in ""

### ISSUE THREAD

**Issue by BrahRah** [godotengine/godot-docs#1587]
I tried to search .connect and ".connect" in the doc with the search but I don't get the right results. The search just ignores the . and the "" the results are the same as just writing connect. Connect is used a lot as a word but I want to find the .connect that is used after a node in gdscript to find a code example.

**Comment by Calinou** [comment]
I'm not sure if we can do anything about it, as this is a limitation of Read The Docs' search system.

**Comment by Calinou** [comment]
I'll close this as we unfortunately can't do anything about it at our level.
