### ISSUE TITLE
Are should be changed to as.

### ISSUE THREAD

**Issue by jmintb** [godotengine/godot-docs#159]
In the " [Instancing (continued)](http://docs.godotengine.org/en/latest/tutorials/step_by_step/instancing_continued.html)" tutorial are should be changed to as in the following piece of text:
"Make some rooms with furniture, then connect them. Make a house later, and use those rooms are the interior."
I could be wrong but I am pretty sure that are should be as.

**Comment by akien-mga** [comment]
It's easily fixed, but wouldn't you want to edit it yourself and make a pull request? https://github.com/godotengine/godot-docs/blob/master/tutorials/step_by_step/instancing_continued.rst

That's the very reason why the docs are hosted on a git repo ;)

**Comment by jmintb** [comment]
I know, I am just not familiar with using github, but I will give it a try. :)

**Comment by jmintb** [comment]
Okay, so I have now made my first pull request ever, thanks for the encouragment. :)

**Comment by akien-mga** [comment]
You're welcome, you did well :)

Fixed by #161.
