### ISSUE TITLE
Missing step in Scenes and Nodes

### ISSUE THREAD

**Issue by RoloDMonkey** [godotengine/godot-docs#1596]
On the Scenes and Nodes page, there is a step missing when you first try to play the scene.  The docs explain that you need to save the scene first, but they don't mention that you will also have to choose the main scene before the preview will actually play.

**Comment by RoloDMonkey** [comment]
Loosely related to #1510

**Comment by vnen** [comment]
You don't have to choose a main scene if you are playing the current scene (which is what the docs expect). However, it's easy for a beginner to get confused and try to start the project instead, which would need to define a main scene (though this will be warned if trying to play a project with no main scene defined).

**Comment by RoloDMonkey** [comment]
That does not appear to be the case.  I have tested this three times now.  The scene will not play until you choose a main scene.

**Comment by RoloDMonkey** [comment]
Oh, I see it finally.  The screenshot above is highlighting the wrong button.  It is highlighting the "Play" button, not the "Play Scene" button.  I will submit a different pull request with the correct button highlighted.
