### ISSUE TITLE
Out of date tutorials (primarily screenshots)

### ISSUE THREAD

**Issue by Fisto69** [godotengine/godot-docs#16]
when attempting to get into Godot via 

http://docs.godotengine.org/en/latest/tutorials/step_by_step/scenes_and_nodes.html  

i quickly noticed the screenshots are outdated, this causes a couple problems.  first being that if the screenshots are outdated, my confidence in the fact the text itself is up-to-date and will allow me to learn the software without a hitch is not very high.  

and two, arguably the most important for me is the fact that the lack of up-to-date screenshots can cause a problem for a good albiet small percentage of users, i myself, like others that exist use visual references to help learn.. and out-of-date screenshots will make that a bit more difficult. not impossible, but just a bit harder

**Comment by StraToN** [comment]
I agree. I already noticed this in the proofreading available here : https://public.etherpad-mozilla.org/p/godot-docs-proofreading
... which is not finished yet, by the way.
But yes, definitely, we will have to pdate screenshots everywhere in the docs.

**Comment by Fisto69** [comment]
oh sweet, any ETA on when the tutorials should be updated? id wager 2 weeks to maybe a month or so? 

this is assuming the tutorials/website are taking low priority over everything else with the recent big release.

**Comment by akien-mga** [comment]
Check the link above what you just posted?

**Comment by akien-mga** [comment]
Ah maybe you meant for the whole documentation. Can't give an ETA, better use the documentation as is, and see it improve little by little. It's a never-ending work :)

**Comment by Fisto69** [comment]
ah, yes i meant as a whole. i was unsure if you had an actual team dedicated to keeping the tutorials and just all documentation up-to-date or not.

however, im going to close this since it this particular question has been answered and solved.

much appreciated fella's.

**Comment by akien-mga** [comment]
Well let's keep it open as a reminder, the way you formulated the title does make it more general, so let's try to fix all screenshots :)

**Comment by Fisto69** [comment]
oh okay, that is a good point.  my bad.

  fix all the things! ;P.

**Comment by akien-mga** [comment]
I just merged the changes for the Scenes and nodes tutorial, the website should be updated in 5 min or so.

**Comment by Fisto69** [comment]
oh sweet, thats great news.  thanks a bunch.

**Comment by NathanLovato** [comment]
We've got to redo a lot of stuff for Godot 3. Closing the issue for now as it's old and idle - if you have specific screenshots that need update, feel free to open a new issue and list them
