### ISSUE TITLE
Invalid code in GDScript string format examples

### ISSUE THREAD

**Issue by akien-mga** [godotengine/godot-docs#1611]
The "Array/key" example on http://docs.godotengine.org/en/3.0/getting_started/scripting/gdscript/gdscript_format_string.html#format-method-examples is invalid, it doesn't compile.

Something like `["version":"3.0"]` can't be a valid Array.

Also those examples should use code formatting, otherwise quotes are rendered as typographic quotes (“ ”) which are not valid string delimiters.

**Comment by AlexHolly** [comment]
:D #1609

**Comment by akien-mga** [comment]
Duplicate of #1609.
