### ISSUE TITLE
Im new to gdcsript

### ISSUE THREAD

**Issue by Xeonbg2** [godotengine/godot-docs#1616]
I would like a tutorial on how to do basic things cause I cant find one that says what I need. (sorry to be a bother)

**Comment by AlexHolly** [comment]
http://docs.godotengine.org/en/3.0/getting_started/scripting/gdscript/gdscript_basics.html
https://www.youtube.com/watch?v=K5-5j4H4Ypo&vl=en
https://github.com/godotengine/godot-demo-projects

You can ask for more help.
https://godotengine.org/community

**Comment by FeralBytes** [comment]
@Xeonbg2 please be more specific, what kind of basic things? Make it list if multiple basic things and be specific then we can work on filling the gaps.

**Comment by NathanLovato** [comment]
It's not a place to ask for support. Please use Discord, the QA site, the facebook group... https://godotengine.org/community
