### ISSUE TITLE
Need documentation on using export encryption keys.

### ISSUE THREAD

**Issue by Triangle345** [godotengine/godot-docs#162]
There is no where in the documentation where it mentioned the proper use of export encryption keys. A lot of people would want to know how to do this to protect the game from cheaters, hackers, and profit etc.

**Comment by Triangle345** [comment]
figured i would close this issue since this repo isnt getting many views. Also the whole export system kind of needs to be revamped.

**Comment by Calinou** [comment]
This is now documented in [Compiling with script encryption key](https://docs.godotengine.org/en/latest/development/compiling/compiling_with_script_encryption_key.html), closing.
