### ISSUE TITLE
Language in godot-docs/tutorials/3d/fps_tutorial/part_two.rst is unclear

### ISSUE THREAD

**Issue by thenolfar** [godotengine/godot-docs#1620]
Hi,
I believe the language in parts of this tutorial (which is really really great and helps me a lot), is flawed.
In part 2, the paragraph about the state machines  (function set_animation() ), is the following:

"Lets look at set_animation next.

set_animation sets the animation to the that of the passed in animation state if we can transition to it. In other words, if the animation state we are currently in has the passed in animation state name in states, then we will change to that animation.

To start we check if the passed in animation is the same as the animation state we are currently in. If they are the same, then we write a warning to the console and return true.

Next we see if AnimationPlayer has the passed in animation using has_animation. If it does not, we return false.

Then we check if current_state is set or not. If current_state is not currently set, we set current_state to the passed in animation and tell AnimationPlayer to start playing the animation with a blend time of -1 and at the speed set in animation_speeds and then we return true.

If we have a state in current_state, then we get all of the possible states we can transition to. If the animation name is in the list of possible transitions, we set current_state to the passed in animation, tell AnimationPlayer to play the animation with a blend time of -1 at the speed set in animation_speeds and return true."

" to the that of the passed in animation state" - what is that supposed to mean?
"To start we check if the passed in animation" - same

I would be glad for an explanation and can help with translations if you like.

Best

**Comment by FeralBytes** [comment]
> " to the that of the passed in animation state" - what is that supposed to mean?
Should be: "to that of the passed in animation state" - does that make more sense now?

> "To start we check if the passed in animation" - same
Perhaps; "First check if the passed in animation" - does this make it more clear.

Maybe removing the "we" from this tutorial could clear up the language, do you agree?

**Comment by thenolfar** [comment]
> Maybe removing the "we" from this tutorial could clear up the language, do you agree?

I do not think that the "we" is the problem. My main issue was that "the passed" does not have an explicit meaning. It might implicitly mean something like "the previous state the machine was in", but this is not clear. 
There are also many cases where "its" and "it's" are mixed up. Since I assume that someone made this tutorial in their spare time, I am not complaining. I just want to say that the explanations are not very clear due to the language issues.
