### ISSUE TITLE
Your First Game/Main Script Instructions: Confusing section

### ISSUE THREAD

**Issue by kdotca** [godotengine/godot-docs#1625]
Original Text:
Next, click on the Player and connect the hit signal. We want to make a new function named game_over, which will handle what needs to happen when a game ends. Type “game_over” in the “Method In Node” box at the bottom of the “Connecting Signal” window. Add the following code, as well as a new_game function to set everything up for a new game:

Confusion:
click on the Player?
- Brand new to Godot, several things named Player. I was confused but ultimately sorted it. Perhaps adding the word Node will point people to what they need to click (especially since previous paragraph talks about dragging in scenes into Main).

Suggested Text edit:
Next, click on the Player Node and connect the hit signal in the Node editor. We want to make a new function named game_over, which will handle what needs to happen when a game ends. Type “game_over” in the “Method In Node” box at the bottom of the “Connecting Signal” window. Add the following code, as well as a new_game function to set everything up for a new game:

**Comment by cbscribe** [comment]
There is only one thing called "Player". Whether you click on it in the view window or click in the scene tree, the node will be selected. Either way of selecting the object is valid.

**Comment by triptych** [comment]
The purpose of a tutorial is to help someone make a decision about using this game engine. The person filing this issue found this as a stumbling block, so it's a guarantee that many others are doing the same, but are not savvy enough to file an issue. Adding the world "node" helps clarify and make the docs better. So it has my vote as a suggestion.
