### ISSUE TITLE
Using Gridmaps: incorrect file name

### ISSUE THREAD

**Issue by ntfwc** [godotengine/godot-docs#1626]
In "Using Gridmaps", it states there is an exported MeshLibrary called
"MeshLibrary.tscn", but the actual name is "MeshLibrary.tres"

**Comment by FeralBytes** [comment]
URL [Using gridmaps](http://docs.godotengine.org/en/latest/tutorials/3d/using_gridmaps.html?highlight=MeshLibrary)
Please confirm you are refering to this line:
> You can find an already exported MeshLibrary in the project named “MeshLibrary.tscn”.

**Comment by ntfwc** [comment]
Yes, that is the line
