### ISSUE TITLE
Vertex displacement with shaders: broken snippet

### ISSUE THREAD

**Issue by ntfwc** [godotengine/godot-docs#1627]
In "Vertex displacement with shaders", the fbm function snippet fails to build with an undefined
variable "h". Changing it to "height" seems work, though the resulting geometry doesn't quite match the screenshots.

**Comment by clayjohn** [comment]
Good catch. Ill fix this right away. I just updated the variable names recently and completely missed this somehow.

**Comment by ntfwc** [comment]
Reopening, because the 3.0 branch still needs this change too.

**Comment by Calinou** [comment]
This was fixed a while ago (Godot 3.2 is the current release), closing.
