### ISSUE TITLE
Better sidebar behavior

### ISSUE THREAD

**Issue by GammaGames** [godotengine/godot-docs#1637]
I find that I want to use the search bar very often, and the sidebar behaves strangely, if I am deep into the heirarchy and I have scrolled around in the sidebar and main page, the sidebar doesn't scroll back up to the top when I get to the top of the main page.

![peek 2018-08-01 20-53](https://user-images.githubusercontent.com/7832163/43559855-0a79a782-95cd-11e8-84b5-51a703653ec9.gif)

I propose making the search bar sticky at the top, so that it is always accessible to the user. All that has to be done is to change `div.wy-side-nav-search` to be outside of `div.wy-side-scroll`. The logo size could be animated to be smaller as the user scrolls down the heirarchy as well, to save vertical space.

![peek 2018-08-01 21-11](https://user-images.githubusercontent.com/7832163/43560410-7e058cb4-95cf-11e8-826e-ec6904761071.gif)

The docs page already use jquery, so I used the following script to animate the size:
```js
$(".wy-side-scroll").on("scroll", function(e) {
  $(".wy-side-nav-search img").css("height", `${Math.max(100, Math.min(200, 200 - this.scrollTop))}px`);
});
```

**Comment by FeralBytes** [comment]
I like this but I would also like it tested on mobile. Right now the docs work well even on mobile, but with this change I think you just need to make sure that the icon gets small enough to not take up to much realestate.

**Comment by Calinou** [comment]
I'm not fond of animating the logo size (it tends to be distracting). Making it smaller in the first place (and redesigning it to use an horizontal layout) would make it less intrusive in general.

**Comment by GammaGames** [comment]
![image](https://user-images.githubusercontent.com/7832163/43932829-76ad5b7e-9c03-11e8-934b-c94babaf0b63.png)

It's not perfect and needs more work, but at least it doesn't take up a ton of vertical space

**Comment by Calinou** [comment]
I didn't have that in mind — I wanted to see the documentation logo redesigned to be less high, and still have the search field below.

**Comment by GammaGames** [comment]
That makes way more sense lol

**Comment by GammaGames** [comment]
Another possible solution could be to let the logo scroll off the page and keep the search input in the screen. That way when you scroll up the logo is still there, but when you scroll down it would only show the search input. This would also not require a logo rework, but might require some clever css.

**Comment by pwab** [comment]
Any progress here @GammaGames? I'm working a lot with the API documentation and every time I want to search something it is faster to reload the page instead of scrolling back up.

**Comment by GammaGames** [comment]
I haven't, but I understand your frustration! I don't know how sphinx works or how to customize themes so I haven't even looked

**Comment by pwab** [comment]
Okay no problem. Was just running into this issue a few times last week and it drives me crazy.

In the meantime: What about disconnecting the scrolling of the navbar and the content? As far as I know it is possible to deactivate the behaviour that the navigation list scrolls in parallel to the content.
Or maybe an unobtrusive 'Back to top' button at the bottom right which sits at an upper canvas layer?

Not sure if this would be the right solution but it would be at least something.

**Comment by GammaGames** [comment]
I think disconnecting the scrolling would be done regardless, that is the behavior I expected when I first started using the docs. Breaking the search box so it's not in the scrolling div would make the sidebar more useful when the user is 3 layers deep in a tree and it auto-scrolls down a bunch automatically, too.

**Comment by Calinou** [comment]
> Or maybe an unobtrusive 'Back to top' button at the bottom right which sits at an upper canvas layer?

There is one such button on most keyboards, it's called the <kbd>Home/kbd> key :slightly_smiling_face:

**Comment by pwab** [comment]
> There is one such button on most keyboards, it's called the Home key 🙂

On my keyboard if I press the home key only the content side jumps to the top. The nav bar jumps in parallel the same scroll height but not to the search bar. So this won't solve this problem.

But I can see your point and totally agree with you @Calinou that adding a button wouldn't be the right thing.

**Comment by GammaGames** [comment]
This is partially fixable by setting `sticky_navigation` to `False,` in the `conf.py` file, but it looks like sometimes you need to click the sidebar to make scrolling work again. I'm not sure what's up with that, maybe it's just my trackpad being bad? I have a branch with that config but I want to make sure it's working right before I submit a pr.  
It looks like, in order to make the search input stick to the top of the sidebar, it should be fixed upstream in the theme. Someone has an issue open (rtfd/sphinx_rtd_theme/issues/758) and I have a working demo but I need to make it work better before making a pr over there. Since the sidebar doesn't use flexbox elements it's a little bit of a pain to get looking right.

**Comment by Calinou** [comment]
This was implemented by https://github.com/godotengine/godot-docs/pull/3099, closing.
