### ISSUE TITLE
EditorPlugin.add_tool_submenu_item undocumented 

### ISSUE THREAD

**Issue by rcorre** [godotengine/godot-docs#1638]
The use of [add_tool_to_submenu_item](http://docs.godotengine.org/en/3.0/classes/class_editorplugin.html#class-editorplugin-add-tool-submenu-item) is not obvious from the name, and there is no additional documentation.

**Comment by BornStellarMakesEternalLasting** [comment]
The function `add_tool_to_submenu_item` isn't actually on the webpage, but `add_tool_submenu_item` is. I dug through the godot-docs/classes/class_editorplugin.rst and found that the function above it called `add_tool_menu_item` has this description: 

"Adds a custom menu to 'Project > Tools' as ``name`` that calls ``callback`` on an instance of ``handler`` with a parameter ``ud`` when user activates it."

I guess add_tool_submenu_item does the same general thing, but takes it one level deeper to make the menu a bit more customizable. I'm also concerned that the description didn't show up on the website (I may make an issue for that one).

**Comment by sprite-1** [comment]
This is still unclear as of 3.1, `add_tool_submenu_item` takes at least 3 parameters (String, Object, String) meanwhile `add_tool_submenu_item` only takes 2 and the second parameter is an Object, what kind of Object is it expecting there?

**Comment by Capital-EX** [comment]
How does either of these methods work?  I can't seem to get them to do anything...

**Comment by Capital-EX** [comment]
I'm back, I have figured out how to use `add_tool_menu_item` to display a basic popup menu:
```
tool
extends EditorPlugin

var popup
func _enter_tree():
    popup = FileDialog.new()
    add_tool_menu_item("Test", self, "callback")

func callback(ud): 
    add_child(popup)
    popup.popup()

func _exit_tree():
    remove_tool_menu_item("Test")
    popup.free()
```

The way `add_tool_menu_item` is very difficult to understand without an example of its usage.  Loading a `.tscn` file and passing it to `add_tool_menu_item` as the `Object` value will result in the `callback` not being found in the script.  This will intern through an error.
