### ISSUE TITLE
Node.set_owner isn't documented

### ISSUE THREAD

**Issue by m-irigoyen** [godotengine/godot-docs#1642]
The Node.set_owner function is not listed as a member function of class Node in the docs. It is referenced in the description, and in several other pages. However its not in the list of functions, and there's no prototype and description of it.

**Comment by vnen** [comment]
It's not documented because it's just a setter for the `owner` property. The online docs doesn't show the getters/setters (maybe this should be amended) but the in-editor help does.

Essentially, `$Node.set_owner(node)` is the same as `$Node.owner = node`.

**Comment by m-irigoyen** [comment]
Oh, okay ! I didn't know there were differences between the online docs and editor help. Thanks !
