### ISSUE TITLE
MeshDataTool class needs documentation

### ISSUE THREAD

**Issue by aaronfranke** [godotengine/godot-docs#1643]
https://godot.readthedocs.io/en/latest/classes/class_meshdatatool.html

~~I may do this myself later, if I figure out the details of how it works.~~

Notably, it would be important to note how this class differentiates from [SurfaceTool](https://godot.readthedocs.io/en/3.0/classes/class_surfacetool.html). Both classes seem to be about modifying and/or creating `Mesh`es.

**Comment by aaronfranke** [comment]
Isn't that code example missing indentation? Everything is aligned left. I would expect the contents of a for loop to be indented relative to the loop declaration.

**Comment by clayjohn** [comment]
I guess so. The indentation looks fine in the xml document though. https://github.com/godotengine/godot/blame/master/doc/classes/MeshDataTool.xml

Maybe this is an issue with the way the code gets converted to rst?

**Comment by akien-mga** [comment]
`[codeblock]` should use 4 spaces for indentation, tabs are only cosmetic in the XML and stripped.

**Comment by akien-mga** [comment]
Fixed formatting in godotengine/godot@e588c241681032c616a998a9884b30215ea7d4e3.
