### ISSUE TITLE
About the term "Visual Scripting"

### ISSUE THREAD

**Issue by BrahRah** [godotengine/godot-docs#1651]
For me Visual Scripting is a term like programming, I don't like that the docs refer to Godots own Visual Scripting language as just "Visual Script" or "Visual Scripting".  It should have it's own name like GDScript. Godot Visual Script "GDVScript" would be an easy fitting choice.

**Comment by FeralBytes** [comment]
I could start changing the references to be Godot Visual Script, but I want some dev input first.

**Comment by vnen** [comment]
I also would like a proper name, but this should be changed first in the editor/core. "GDVScript" is not a good choice though, it looks too similar to GDScript that's hard to differentiate in a quick glance.

**Comment by mhilbrunner** [comment]
This is out of scope of the docs. Feel free to take this to the https://github.com/godotengine/godot-proposals repository instead, although it's now been named Visual Script for years :)
