### ISSUE TITLE
Guide for switching from Unity to Godot

### ISSUE THREAD

**Issue by bojidar-bg** [godotengine/godot-docs#166]
Since there is a huge inflow of new/potential users right now, it would be nice to have a guide for transitioning them from Unity's way of thinking to the Godot way of thinking.

Adapted from IRC (meeting on -devel, 2-nd of June):
**[reduz]** as you and many probably noticed, the change of license in Unity generated a lot of people angry and an unexpected large amount of new Godot users and discussions of Godot as an alternative in many places
**[reduz]** I´ve seen two things used as argument from people that would like to switch, one is of course support for C#, which I guess we´ll have to eventually implement. The second is documentation or tutorials on how to move workflow from Unity to Godot. Some sort of ¨map¨ of how something you do in Unity is done in Godot
**[reduz]** do you think we could assemble some sort of mini team to work on this kind of documentation? I know Unreal has a large article about this for Unity users, but anything that could ease their transition, specially for advanced users, while at the same time being able to show how we do many of the same things in Godot better would be fantastic

**Comment by EnderNator10** [comment]
any way to covert unity assets to godot i bought some assets i wana transfer!
