### ISSUE TITLE
Document connect return value

### ISSUE THREAD

**Issue by rcorre** [godotengine/godot-docs#1691]
[`Object.connect`](https://godot.readthedocs.io/en/3.0/classes/class_object.html#class-object-connect) returns an `int`. The documentation doesn't actually explain what this `int` means.

**Comment by akien-mga** [comment]
This is fixed in the 3.1 / latest documentation already, it returns an `Error` code: https://godot.readthedocs.io/en/latest/classes/class_object.html#class-object-connect
