### ISSUE TITLE
add_to_group doesn't document the "persistent" parameter

### ISSUE THREAD

**Issue by rcorre** [godotengine/godot-docs#1698]
In [`add_to_group`](http://docs.godotengine.org/en/latest/classes/class_node.html?highlight=is_in_group#class-node-add-to-group), what does the `persistent` parameter do? Based on digging through the code a little, my guess is it affects whether duplicating the node will add the new clone to the same group, but I'm not sure.

**Comment by skyace65** [comment]
Information on the persistent parameter was added at some point. This issue can be closed.
