### ISSUE TITLE
Update bit flags export docs

### ISSUE THREAD

**Issue by ghost** [godotengine/godot-docs#1709]
Originally reported here: https://github.com/godotengine/godot/issues/21349
The bit flag property editor cannot edit hintless bit flags anymore (as of the time of writing).

https://github.com/godotengine/godot/pull/21369 fixes the issue by deprecating the following syntax:
```gdscript
# deprecating
export(int, FLAGS) var v = 0

# in favor of
export(int, FLAGS, "hint,text") var v = 0
export(int, FLAGS, "hint", "text") var v = 0
```

The docs here: http://docs.godotengine.org/en/latest/getting_started/scripting/gdscript/gdscript_basics.html#exporting-bit-flags needs to be updated.

**Comment by Meriipu** [comment]
docs in question appears to have been moved here
https://docs.godotengine.org/en/latest/getting_started/scripting/gdscript/gdscript_exports.html#exporting-bit-flags
