### ISSUE TITLE
`Parser Error: Identifiers not found: screensize`

### ISSUE THREAD

**Issue by kbad10** [godotengine/godot-docs#1710]
```
extends Area2D

export (int) var speed #how fast the player will move

func _ready():
	screensize = get_viewport_rect().size

func _process(delta):
	var velocity = vector2() #player's movement vector
	if Input.action_pressed("ui_right"):
		velocity.x += 1
	if Input.actio_pressed("ui_left"):
		velocity.x -= 1
	if Input.is_action_pressed("ui_down"):
        velocity.y += 1
	if Input.is_action_pressed("ui_up"):
		velocity.y -= 1
	if velocity.length() > 0:
		velocity = velocity.normalized() * speed
		$AnimatedSprite.play()
	else:
		$AnimatedSprite.stop()
		
	position += velocity * delta
	position.x = clamp(position.x, 0, screensize.x)
	position.y = clamp(position.y, 0, screensize.y)

```
This is the code from the tutorial. When I tried to run it. It throws error:
`Parser Error: Identifiers not found: screensize`

Please help

**Comment by volzhs** [comment]
you didn't define `screensize` variable.
please use community channels for a question.
https://godotengine.org/qa/ or facebook, discord... etc

**Comment by kbad10** [comment]
I did define `screensize` in 4th line. Did I define it wrong?

**Comment by cbscribe** [comment]
That doesn't declare the variable, it just tries to assign a value to it. You have to declare variables with `var`. See my answer at https://github.com/kidscancode/Godot3_dodge/issues/8 for further details.

This is not the correct forum for getting help with your projects. In future, please use one of the community channels, as suggested above.
