### ISSUE TITLE
RigidBody center of mass with Bullet/GodotPhysics

### ISSUE THREAD

**Issue by HugoSlt** [godotengine/godot-docs#1711]
As discussed in [this issue](https://github.com/godotengine/godot/issues/21487), it's not obvious what the center of mass of a `RigidBody` is, especially since Bullet and GodotPhysics have different conventions.

We should add a note in the docs that mentions : 
 - GodotPhysics defines the center of mass as the average of the `collisionShapes` centers
 - Bullet defines the center of mass as the `RigidBody` center
 - Thus with Bullet we can manually set the center of mass where we want by adjusting the relative positions of the `RigidBody` and its children
 - Optionally, maybe also add a note on how to compute the center of mass of a complex imported mesh. If Godot doesn't have a built-in function, then maybe we could just mention that Blender has the "_Origin to Center of Mass (Surface)_" and "_Origin to Center of Mass (Volume)_" functions with `shift + ctrl + alt + c` ("_Set Origin_")

**Comment by pwab** [comment]
What an interesting observation! This could explain some headaches I got while I've worked with RigidBodies and Joints.

Just a quick sidenode:
The information that _GodotPhysics defines the center of mass as the average of the collisionShapes centers_ could also be added to the [RigidBody2d docs](https://godot.readthedocs.io/en/latest/classes/class_rigidbody2d.html). This could be mentioned when documenting these functions:

- add_central_force
- apply_central_impulse
- add_torque
- apply_torque_impulse
