### ISSUE TITLE
Why are so many functions missing from docs?

### ISSUE THREAD

**Issue by marlboro** [godotengine/godot-docs#1729]
I just finished searching for a method I'm using in the 3.0 docs.  It does not exist according to the docs.  This has happened to me multiple times and I know the functions exist because the sample code runs fine.  So, I finally decided to look at the 2.1 docs and low-and-behold the functions exist and are well documented.

My latest example was on RigidBody2D.  Check out the difference between 3.0 and 2.1...

[RigidBody2D from 3.0](http://docs.godotengine.org/en/3.0/classes/class_rigidbody2d.html)
[RigidBody2D from 2.1](http://docs.godotengine.org/en/2.1/classes/class_rigidbody2d.html)

Am I doing something wrong here (like compiling in some sort of compatibility or 2.x mode)?  If not, why are so many methods missing?

Thanks!

**Comment by akien-mga** [comment]
They're not missing but part of the properties now, so e.g. `angular_damp` can be accessed directly, or via its setters of getters `set_angular_damp` and `get_angular_damp`. They're properly documented in the in-editor docs, but not yet in the HTML version.
