### ISSUE TITLE
Document fixed_fps and disable_render_loop flags

### ISSUE THREAD

**Issue by HugoSlt** [godotengine/godot-docs#1731]
`fixed_fps` and `disable_render_loop` are command line flags that can be used to simulate the game at faster (or slower) than real-time, it is useful for eg for AI training. They are described here https://github.com/godotengine/godot/pull/7269 but currently they are mentioned nowhere in the docs.

Maybe we could add those to the [command line tutorial](https://github.com/godotengine/godot-docs/blob/master/getting_started/editor/command_line_tutorial.rst) ?

**Comment by Xrayez** [comment]
Just recently started to experiment with these for unit testing purposes, partly documented in bitwes/Gut#120.

**Comment by Calinou** [comment]
All command-line options are now documented in [Command line tutorial](https://docs.godotengine.org/en/latest/getting_started/editor/command_line_tutorial.html), closing.
