### ISSUE TITLE
Requesting improvement to GDScript Style Guide

### ISSUE THREAD

**Issue by char0xff** [godotengine/godot-docs#1736]
The [GDScript Style Guide](http://docs.godotengine.org/en/latest/getting_started/scripting/gdscript/gdscript_styleguide.html) should also talk about:
1) Using classes' members in place of set/get methods, or viceversa.
2) How we should name enums. Like constants?
3) Commenting style guidelines.

I'm not making the changes myself because I don't know which is the correct/preferred style.

**Comment by cbscribe** [comment]
Great suggestions! I can take a swing at this after I finish some updates to the "Getting started" section

**Comment by aaronfranke** [comment]
1. GDScript has `setget` for properties (accessed like members, but logic in `get`/`set` methods). What exactly do you mean by your question? Both regular members and properties are useful for their own use cases. I don't think you should be calling a `get` or `set` method when that method is already used as a `setget` for the property.

2. This is done thanks to @Calinou in #2996

3. This is done thanks to me in #2868

**Comment by Calinou** [comment]
Closing, as I believe all points have been addressed above.
