### ISSUE TITLE
Update dependency list for X11

### ISSUE THREAD

**Issue by vnen** [godotengine/godot-docs#174]
Since godotengine/godot#4905 there's a new dependency for `xrandr`, so it should be added the documentation. It's called `libxrandr-dev` in Ubuntu and `libxrandr` in Arch, but I don't know about the other distros.

**Comment by vnen** [comment]
Ping @Hinsbart :wink:

**Comment by akien-mga** [comment]
`"pkconfig(xrandr)"` should work on any pkgconfig-aware distro (Mageia for sure, Fedora probably).

**Comment by akien-mga** [comment]
Fixed by #175.
