### ISSUE TITLE
'Games' category in tutorials section

### ISSUE THREAD

**Issue by pwab** [godotengine/godot-docs#1747]
I saw this [PR](https://github.com/godotengine/godot-docs/pull/1737) being rejected and I totally agree with it not being in the Getting started section of the docs. But why not moving it into a separate one with tutorials in which 'full games' from the first node to somehow playable states are being created step by step?

If I search the docs for game tutorials I can only find Doge the Creeps, the FPS tutorial, the VR starter tutorial and the community links. So we could extend this list with such a category and don't have to fit these tutorials into specific categories like 2D or GUI or Animation when they show everything at once.

This would also help writing tutorials for the demos because some of them don't fit into specific docs categories (as [this issue](https://github.com/godotengine/godot-demo-projects/issues/251) may intend).

So my suggestion would be to append a "Games" category to the Tutorials section (and move that Pong tutorial into this category). Just to be clear:

```
Tutorials
    2D
    3D
    Audio
    ...
    Debug
    Games  <---   New category
        Pong
        GameABC
        GameXYZ
        ...
```

**Comment by pwab** [comment]
This might become obsolete after #3390 is accepted.

**Comment by NathanLovato** [comment]
Yes, we're moving towards a reference manual and will avoid game creation / step-by-step tuts in the docs. Thanks for the update, I'll close the issue now.
