### ISSUE TITLE
Definition of virtual, const and vararg function classifications in the docs

### ISSUE THREAD

**Issue by wyattbiker** [godotengine/godot-docs#1753]
In the API docs, e.g. http://docs.godotengine.org/en/3.0/classes/class_node.html you see functions classified as `virtual`, `const` and  `vararg`. I am trying to understand what that means with respect to the functions.

So I am guessing `virtual` classification is similar to abstract, and must be defined in your code (E.g. callbacks). But `const` or `vararg` classification I am not so sure. What does this classification mean?

Examples.

```
void    _ready ( ) virtual
Node    get_child ( int idx ) const
Variant rpc ( String method ) vararg
```

**Comment by LikeLakers2** [comment]
From what I can tell:

* `virtual` means that the function is supposed to be overridden in your own code, with your own code. For example, if you want something to run when the node is ready (nodes have finished being added), you would override `_ready()`. By default, these typically do nothing.
* `const` seems to mean that the function, given the same arguments and same context every time, will always return the same value. For example, `get_child(5)` will always return the child at index 5, assuming that no child nodes are ever removed. `get_parent()` will always return the same parent, assuming the node hasn't been moved to another parent in the scene tree. And so on.
* `vararg` means that the method can accept any number of arguments (including no arguments) after the ones explicitly shown. For example, `print()` is a `vararg` function, which means you can pass more than one argument to it and it will react accordingly. In the case of `print()`, it will just print the arguments in order, on the same line.

**Comment by vnen** [comment]
`const` actually means that the function has no side-effect, i.e. it won't change any property of the object when called.

**Comment by wyattbiker** [comment]
Thanks for the explanations which make sense. It does need to be explained in the docs (unless it is described some place and I did not find it) because I know i asked elsewhere and I had differing answers.
