### ISSUE TITLE
list of new 3.1 features to be documented

### ISSUE THREAD

**Issue by ZX-WT** [godotengine/godot-docs#1762]
- [ ] 2d mesh #1766 

- [ ] softbody #1665

- [ ] ik #1665

- [ ] csg tools #1414

- [ ] animation tree #1765 

- [ ] visual shader editor #1764 

- [ ] ragdoll #1763 

Above are some features that need basic doc, they are now as news on the godot website, let's move it into the docs and improve it if possible. :)

**Comment by pwab** [comment]
There already is a tracker for the 3.1 documentation: https://github.com/godotengine/godot-docs/issues/1603

Would you mind adding your list there and close this issue?
