### ISSUE TITLE
FPS tutorial part 1 : key pressed + mouse move == camera stutters

### ISSUE THREAD

**Issue by oskude** [godotengine/godot-docs#1774]
http://docs.godotengine.org/en/3.0/tutorials/3d/fps_tutorial/part_one.html
http://docs.godotengine.org/en/3.0/_downloads/Godot_FPS_Part_1.zip

running that part 1 example code i get following behavior:
https://youtu.be/l2EBvHFPN8c

i first only move the mouse, and camera movement is smooth. then i press `d` to strafe right and move the mouse at the same time, and the camera movement stutters. is it just me, or?

> this is with godot 3.0.6 on linux 4.18.10 with nvidia 410.57 blob.

**Comment by oskude** [comment]
but of course, disabled vsync in project settings and camera does not stutter anymore while pressing movement key and moving mouse!

**Comment by Calinou** [comment]
Try running the demo with 3.1 alpha as well; this should not occur with V-Sync enabled (as it's forced on many platforms).

**Comment by oskude** [comment]
just build godot from git master, no key+mouse camera stutter with vsync.

awesome, thank you!
