### ISSUE TITLE
Health Bar does not update!

### ISSUE THREAD

**Issue by KoopHauss** [godotengine/godot-docs#1781]
I'm following along in the Step-by-step procedures and am currently on the section about controlling UI with code. There some coding examples given for you to put in and connect signals that are supposed to make the health bar and I think the number update with each hit from the enemy until the player is dead. 

neither the Health Bar nor the number are updating when the enemy hits the player. The animations for the enemy and player do play.

**Comment by volzhs** [comment]
can you attach your sample project to reproduce it?

**Comment by KoopHauss** [comment]
How do I do that. I keep getting an error message "We don't support that file type."

**Comment by KoopHauss** [comment]
[Controling UI - Copy.zip](https://github.com/godotengine/godot-docs/files/2439409/Controling.UI.-.Copy.zip)

Hopefully this is it . . . I'm really not sure if I did this right?

And just to add a bit more detail:

- When I run the game the HP bar is already empty and the number shows "0" in the game; while the enemy and player simulate the battle with the enemy attacking the player until player fades away simulating death. 

- Also the Life bar does not fade away like it should
