### ISSUE TITLE
Tileset Tutorial?

### ISSUE THREAD

**Issue by KoopHauss** [godotengine/godot-docs#1788]
Your tileset tutorial needs a major overhaul. There is very little explanation (if any at all) why you need to do what the directions are telling you to do i.e. 

"We will be creating a TileSet resource. While this resource exports properties, it’s pretty difficult to get complex data into it and maintain it. Here is what it would look like to manually edit the resource:

../../_images/tileset_edit_resource.png
There’s enough properties to get by. With some effort, editing this way can work. But the easiest way to edit and maintain a tileset is exporting it from a specially-crafted scene!"

What is the context here? What am I supposed to be realizing or understanding?
Another Example:
"Continue adding all the tiles, adjusting the offsets if needed (that is, if you have multiple tiles in a single source image). Again, remember that their names must be unique."

How am I supposed to know how to adjust the offsets? How am I supposed to know if I should? Where is the context?

I created a tilemap, and neither of the ramp tiles lined up with the floor or wall tiles. There is a huge gap between the 90 degree sides; the bottom of the ramps overlap the top of the plain brick tiles. So I did it again, messed with the offsets and that through everything off! now I'm lost, because there isn't enough content to reference to create a usable tileset/map!

And still no one has gotten on either one of the other issues I've submitted. The tileset tutorial is HORRIBLE! Seems as if it was written by a content creator who is just too involved with other things that they couldn't take the time to actually write a descent tutorial.

**Comment by pwab** [comment]
> And still no one has gotten on either one of the other issues I've submitted.

Please be aware that Godot is an opensource project and people here are working on these issues in their freetime. Expecting an answer in less than a day is something that you have to pay for when using other software products. Just be patient and someone will look after your issues.

In the meantime you can get help on the [community sites](https://godotengine.org/community).
