### ISSUE TITLE
F1/F2/F3 do nothing for me

### ISSUE THREAD

**Issue by increpare** [godotengine/godot-docs#1815]
on 

http://docs.godotengine.org/en/3.0/getting_started/step_by_step/intro_to_the_editor_interface.html

it says to press F1/2/3 to change 2D/3D/Script editor, but they do nothing for me in the editor? (godot v. 3.0.6 on OSX 10.13.6 )

**Comment by increpare** [comment]
(alt+123 only work in 2d and 3d mode, once I got to the script editor the text control takes over and alt+1/2/3 result in typing "¡™£" )

**Comment by skyace65** [comment]
Info on what keys to use for macOS was added to this page at some point. This issue can be closed.
