### ISSUE TITLE
Help newcomers find issues to work on by clarifying the Ways to contribute page

### ISSUE THREAD

**Issue by estellerostan** [godotengine/godot-docs#1816]
On the one hand, as a newcomer who wants to start contributing to the Godot Engine (like myself :grin:), one might get confused as to why there is no [junior job](https://github.com/godotengine/godot/issues?q=is%3Aissue+is%3Aopen+label%3A%22junior+job%22 "Godot Engine junior jobs") issues, after reading the [Contributing code section](https://godot.readthedocs.io/en/3.0/community/contributing/ways_to_contribute.html#contributing-code "Ways to contribute — Godot Engine latest documentation") on the Ways to contribute page. 
On the other hand, it turns out that the issues labeled [hero wanted!](https://github.com/godotengine/godot/labels/hero%20wanted! "Godot Engine junior jobs?") and [Hacktoberfest](https://github.com/godotengine/godot/labels/Hacktoberfest "Godot Engine junior jobs?") seem to be where it's at, according to the Godot Engine devblog [here](https://godotengine.org/article/hero-wanted-31-version "Godot Engine - Hero wanted! 3.1 version)") and [here](https://godotengine.org/article/become-godot-contributor-hacktoberfest-2018 "Godot Engine - Become a Godot contributor for Hacktoberfest 2018").

The solution would be to still redirect readers to Godot Engine's GitHub issues tracker but this time to issues with the right label. 

First, I'd like to make sure of what the right label is/ are before modifying the docs.
After that, I'd like to create a PR to resolve this issue.

Thanks in advance.

**Comment by aBARICHELLO** [comment]
I think during October the label junior-job gets replaced with Hacktoberfest, that's why you're getting a 'no issues' error. During the rest of the year they return to their normal name.

**Comment by estellerostan** [comment]
Thank you for the quick answer and the explanation!

Maybe it is worth mentioning in the docs, isn't it?
If not I'll close this issue.
