### ISSUE TITLE
Link from API docs to the engine source code

### ISSUE THREAD

**Issue by starry-abyss** [godotengine/godot-docs#1847]
In API docs, could we have not only the "Edit on GitHub" link for the doc itself, but also a link to view the corresponding Godot source code? 
Ideally, per function, but one link per class/doc page is good too.

**Comment by Anutrix** [comment]
Any update?

**Comment by NathanLovato** [comment]
I'm closing this older issue as someone opened another one, more recent, higher up in the tracker, and there's some discussion there. See #4314 to participate to the discussion.
