### ISSUE TITLE
Sphinx search does not parse two-letter words

### ISSUE THREAD

**Issue by freemanfromgodotengine** [godotengine/godot-docs#185]
Searching at docs.godotengine.org for 'OS' returns 0 results.
I think it should return at least http://docs.godotengine.org/en/latest/classes/class_os.html

**Comment by akien-mga** [comment]
It works fine on the official readthedocs instance: http://read-the-docs.readthedocs.io/en/latest/search.html?q=OS&check_keywords=yes&area=default
Or on the official Sphinx website: http://www.sphinx-doc.org/en/stable/search.html?q=OS

So I need to find out what's wrong with our config. Had a quick look and couldn't tell so far.

**Comment by OvermindDL1** [comment]
Most search things like that require a minimum length of 3 chars for both indexing and searching purposes, may just need to find how to tune that to 2?

**Comment by akien-mga** [comment]
Yeah but I can't find where/how.

**Comment by OvermindDL1** [comment]
Hmm, it looks like it might be this:  http://www.sphinx-doc.org/en/stable/config.html#confval-applehelp_min_term_length
Although I've not used sphinx ever before so I might be off...

**Comment by OvermindDL1** [comment]
Looks like a sphinx bug perhaps?
https://github.com/sphinx-doc/sphinx/issues/1918
https://github.com/sphinx-doc/sphinx/pull/2621

**Comment by timoschwarzer** [comment]
Three letters don't work either. (Searching for "iOS" doesn't give any results)

**Comment by pwab** [comment]
It seems they [fixed it](https://github.com/sphinx-doc/sphinx/pull/2621):

- ["ios"](http://docs.godotengine.org/en/latest/search.html?q=ios&check_keywords=yes&area=default) can be found now.
- ["iOS"](http://docs.godotengine.org/en/latest/search.html?q=iOS&check_keywords=yes&area=default#) can be found now (and is case sensitive)
- ["OS"](http://docs.godotengine.org/en/latest/search.html?q=OS&check_keywords=yes&area=default#) can be found now.
- ["gd"](http://docs.godotengine.org/en/latest/search.html?q=gd&check_keywords=yes&area=default#) can be found now.
- even ["x"](http://docs.godotengine.org/en/latest/search.html?q=+x&check_keywords=yes&area=default#) returns results

**Comment by akien-mga** [comment]
Nice :)

**Comment by acsr** [comment]
I tested this under the current 2.0.0.dev20190213 branch:

Instead of mentioned here https://github.com/godotengine/godot-docs/issues/185#issuecomment-356102309 as solved and successfull (and in the latest changelog for 2.0 as fixed),  two character or lesser terms were only found in Python modules or special roles/directives explaining Sphinx syntax.

Results:

"OS" was only found in 
    * sphinx.ext.autosectionlabel (Python module, in Module Autosectionlabels)

"3D Objects" and "3D-Objects" were **not** found in regular docs.

"gd" was **not** found in regular docs.

"x" was found in 
    * sphinx.ext.autosectionlabel (Python module, in Module Autosectionlabels)
    * term (example) (reStructuredText role, in Markup Test Rendering)  in regular docs.

**Remark:** The term x was found in the regular docs in one special document, the highlight javascript then highlighted  all occurences even in all words, but nowhere else in the >30 source documents. the found occurence was enclosed in in a ``.. rst:role:: term (example)``markup.

in our test we used this source:

```
.. _searchtest::

==========
Searchtest
==========

This is  testfile containing possible targets for common searches in the Manual.

Test if the following terms work quotetd:

| "3D-Objects" and "3D Objects"
| "ios" should be found.
| "iOS" should be found (and is case sensitive)
| "OS" should be found.
| "gd" should be found.
| even "x" should return results

This is in **Inline Text** ios iOS OS gd x 3D-Objects and 3D Objects

and literal::

    ios iOS OS gd x 3D-Objects and 3D Objects

And in Headers?

This a Paragraph about Codecs
=============================

Containing infos aubout decoding videos.

Caveeats
========

Instead of mentioned here https://github.com/godotengine/godot-docs/issues/185 as successfull, 
two or lesser terms were only found in Python modules or special roles/directives explaining Sphinx syntax.

When we tested:

"OS" was only found in 
    * sphinx.ext.autosectionlabel (Python module, in Module Autosectionlabels)

"3D Objects" and "3D-Objects" were **not** found in regular docs.

"gd" was **not** found in regular docs.

"x" was found in 
    * sphinx.ext.autosectionlabel (Python module, in Module Autosectionlabels)
    * term (example) (reStructuredText role, in Markup Test Rendering)

```

**Comment by acsr** [comment]
FYI: https://github.com/sphinx-doc/sphinx/pull/2621/files did not fix that for us.
