### ISSUE TITLE
BBCode documentation is missing most details

### ISSUE THREAD

**Issue by bojidar-bg** [godotengine/godot-docs#186]
Briefly mentioned [on QA](http://godotengine.org/qa/5615/richtextlabel-the-transfer-carriage-a-new-line).

Currently the [BBCode language reference](http://docs.godotengine.org/en/latest/reference/bbcode_in_richtextlabel.html) doesn't even contain information about the list of supported tags, a basic syntax example (we can't assume everyone has been using a BBCode-enabled forum all his life, right?), and probably a few helpful tips, if needed.

**Comment by akien-mga** [comment]
Information should maybe be merged to some extent with that of http://docs.godotengine.org/en/latest/contributing/updating_the_class_reference.html#tags-available-for-improved-formatting

**Comment by DimitriyPS** [comment]
But there's nothing about the alignment of the text. In addition:
`[Class]
[method methodname]
[method Class.methodname]
`
I don't think this applies to RichTextLabel. 

Therefore:
1. There is a full list of BB codes for RichTextLabel;
2. There are extraneous codes confusing about the possibility RichTextLabel.

**Comment by akien-mga** [comment]
Which is why I wrote `to some extent` :)

**Comment by akien-mga** [comment]
i.e., the BBcode reference page should list the common tags, and the page about contributing to the docs should link to the BBcode reference + list the additional tags.

**Comment by StraToN** [comment]
I have some time to spare, so here's the list of bbcodes in RightTextLabel (we will add them in the docs a bit later). Of course, ending tags [/...] exist as well

- [b] : bold text
- [i] : italic text
- [u] : underlined text
- [indent] : increases indent level
- [code] : code formatted text
- [table] [table=] : defines a table. If [table=<nb_cols>] is used, defines a table with <nb_cols> columns.
- [cell] [cell=] : defines a cell. If [cell=<cols_span>] is used, the cell merges <cols_span> columns in one.
- [center] : center aligned
- [fill] : filled align ?
- [right] : right aligned
- [ul] : defines an itemized list
- [ol] : defines a numbered list
- [url] [url=] : defines an url. Shows a text replacement if [url=<url>]Replacement text[/url] is used.
- [img] : image
- [color=] : use a color for text. Either use html names of colors, or hexadecimal notation.
- [font=] : use a specific font

**Comment by DimitriyPS** [comment]
It turns out he can do more than I expected.

**Comment by pwab** [comment]
> [...] we will add them in the docs a bit later [...]

Was added to the [docs page](http://docs.godotengine.org/en/latest/learning/features/gui/bbcode_in_richtextlabel.html) as it seems. Is something still missing here?

**Comment by akien-mga** [comment]
I don't see `[ul]` and `[ol]`, but I don't remember them being supported.

**Comment by pwab** [comment]
[This ](https://github.com/godotengine/godot/blob/34c988cfa92f19c232b65990704816ba1c7d2622/scene/gui/rich_text_label.cpp#L1552-L1770) seems to be the relevant part.

And here we have:

```
if (tag.begins_with("/") && tag_stack.size()) {
} else if (tag == "b") {
} else if (tag == "i") {
} else if (tag == "code") {
} else if (tag.begins_with("table=")) {
} else if (tag == "cell") {
} else if (tag.begins_with("cell=")) {
} else if (tag == "u") {
} else if (tag == "s") {          //use strikethrough (not supported underline instead)
} else if (tag == "center") {
} else if (tag == "fill") {
} else if (tag == "right") {
} else if (tag == "ul") {         <---
} else if (tag == "ol") {         <---
} else if (tag == "indent") {
} else if (tag == "url") {
} else if (tag.begins_with("url=")) {
} else if (tag == "img") {
} else if (tag.begins_with("color=")) {
} else if (tag.begins_with("font=")) {
```

**Comment by akien-mga** [comment]
Indeed. It seems to have no visual effect in RichTextLabel in the current master branch though (the tags are properly parsed, but it looks like plain text).

**Comment by StraToN** [comment]
@akien-mga Could this issue be added to an existing issue? [`bbcode` issues search](https://github.com/godotengine/godot/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aopen+bbcode) displays many issues currently.
