### ISSUE TITLE
gdnative-cpp-example build instructions

### ISSUE THREAD

**Issue by pcbeard** [godotengine/godot-docs#1875]
After cloning https://github.com/BastiaanOlij/gdnative_cpp_example, I then ran these commands:

cd gdnative_cpp_example
git submodule init
git submodule update

This added the godot-cpp submodule, but didn't automatically add the godot_headers submodule. I had to cd into godot-cpp, and do git submodule init update within that directory to get the headers. I think this could be made clearer in the tutorial.

**Comment by brempusz** [comment]
I think there is a bug in the instructions; Instead of `git submodule --init update --recursive` it should be `git submodule update --init --recursive` (tested on `git version 2.20.1.windows.1`).

--



--

**Comment by Calinou** [comment]
The commands in the [GDNative C++ example](https://docs.godotengine.org/en/latest/tutorials/plugins/gdnative/gdnative-cpp-example.html) were updated a while ago, closing.
