### ISSUE TITLE
Move Godot's philosophy to the beginning of the step by step

### ISSUE THREAD

**Issue by exts** [godotengine/godot-docs#1880]
Logically step by step introduces you into godot, the philosophy comes after it introduces you to godot which doesn't make sense.

https://docs.godotengine.org/en/latest/getting_started/step_by_step/godot_design_philosophy.html

Shouldn't it tell you the philosophy of godot first before trying to introduce you into godot? Reading/Flow wise it makes more sense than to do that last.

**Comment by exts** [comment]
I also believe the scene tree section should be much higher as well, maybe even before Scenes & Nodes.

https://docs.godotengine.org/en/latest/getting_started/step_by_step/scene_tree.html

**Comment by Isfaaq** [comment]
Working on it.

**Comment by Calinou** [comment]
Is this still desired now? While I like the idea, I fear it might be considered unnecessarily verbose by beginners.

**Comment by exts** [comment]
> This page is here to help you understand how Godot works,

Is in the beginning of that page, I think beginners and experienced dev's should be introduced to godot this way. They can always skip the prologue, a lot of people do when reading books ;)

**Comment by NathanLovato** [comment]
We're going to rewrite the getting started section. I'll open an issue to give a complete proposal for it. Closing yours for now as a result, but it makes sense and we've taken note of it as part of the docs audit. Thanks!
