### ISSUE TITLE
Audio Buses page has a link that redirects to itself (latest docs)

### ISSUE THREAD

**Issue by wingedadventurer** [godotengine/godot-docs#1882]
https://docs.godotengine.org/en/latest/tutorials/audio/audio_buses.html

Image:

![cc_2018-10-22-21-11-53-4556516](https://user-images.githubusercontent.com/26509794/47313418-311bf680-d63f-11e8-8bd4-eba353be25f5.png)

I suppose it should redirect to Audio Streams?

**Comment by merumelu** [comment]
Yeah this seems wrong. It also happens again later in the document for other links as well :smile:.
