### ISSUE TITLE
In the autoload.zip project, incorrect script binding

### ISSUE THREAD

**Issue by dlivias** [godotengine/godot-docs#1885]
If I press "Open script" in Scene 1 then I will go to Scene2.gd. Easy to fix by rebinding, but I'm newbie at Git.
Project link: https://github.com/godotengine/godot-docs/blob/4e81102708491ffc84e6833b42240a465d8584c5/getting_started/step_by_step/files/autoload.zip

**Comment by skyace65** [comment]
This was fixed by PR #2289. This issue can be closed.
