### ISSUE TITLE
Not clear how to run a demo project (or they didn't work?)

### ISSUE THREAD

**Issue by adam4235** [godotengine/godot-docs#1888]
I'm new to Godot and have been trying it out.  I'm on XUbuntu 18.04 so I downloaded the 64-bit Linux version and ran it from a console in my home directory's Downloads folder.  I followed the Getting Started guide which says "From the Templates tab you can download open source project templates and demos to help you get started faster."  I clicked the Templates tab, chose the "2D Pong Demo" example, and clicked Install.  However, nothing happened after that - it showed "Success!" and had 2 buttons "Retry" and "Install", and clicking each of them just installed it again.  But the project didn't appear in the Project List, nor in my Downloads folder where the executable resides.

I worked around the issue by going to the repository of the demos in my web browser, downloading all of them, then clicking "Import" in Godot to import the Pong project.  It successfully imported and ran.  Is this the method that must be used to install a demo?  If so, the documentation should be updated.

**Comment by pwab** [comment]
I'm working on windows 10 right now so it might differ from the 64-bit Linux version (but it shouldn't). I had no problems running the demo:

![template](https://user-images.githubusercontent.com/19271185/47481364-a0f2d280-d833-11e8-97b1-7508f9749ca0.gif)

>  I clicked the Templates tab, chose the "2D Pong Demo" example, and clicked Install.

After clicking on Install a new window should appear. Step by step:

1. Choose your demo and click on its name
2. Click on Download (then wait)
3. Click on Install (to start the installation routine)
4. Click on Browse (to choose an empty folder)
5. Click on Create Folder (to create an empty folder and change the directory to it)
6. Type in the folders name
6. Click on OK
7. Click on Edit and Run (then wait)
8. Godot Engine should start and you can click on the Play button (to run the demo)

**Comment by adam4235** [comment]
Comparing with the video you posted above, I see that on my system, when I click on the Pong demo, there is no "Download" button that appears, only an "Install" or "Close" button.  So I guess this is a bug rather than a documentation issue?  Should I move it to a different category?  Here's a screenshot of what I see:
![screenshot_2018-10-25_12-33-46](https://user-images.githubusercontent.com/31423103/47512340-5df42780-d852-11e8-93f4-a13a4d7639c4.png)

**Comment by adam4235** [comment]
Comparing with the video you posted above, I see that on my system, when I click on the Pong demo, there is no "Download" button that appears, only an "Install" or "Close" button.  So I guess this is a bug rather than a documentation issue?  Should I move it to a different category?  Here's a screenshot of what I see:
![screenshot_2018-10-25_12-33-46](https://user-images.githubusercontent.com/31423103/47512340-5df42780-d852-11e8-93f4-a13a4d7639c4.png)

**Comment by adam4235** [comment]
Oh wait, I tried again to click on "Install", and this time it brought up the "Install Project" dialog which asks for a folder.  I'm not sure what happened the first time, whether it didn't appear or whether I didn't notice it.  It's possible that I just got confused about having to click 2 different "Install" buttons.

I'm not sure why your video has a "Download" button though - maybe it's a slightly different version of Godot?

**Comment by pwab** [comment]
> I'm not sure why your video has a "Download" button though - maybe it's a slightly different version of Godot?

I was using 3.1 alpha version and you are using the stable 3.0.6. I wasn't aware that there is a difference in this dialog until I saw your screenshot.

Maybe the fact that this dialog will be changed in 3.1 will help prevent that kind of confusion. But you are right that the docs could be more precise in explaining how to properly install a template.
