### ISSUE TITLE
Proper scons path to build with XCode

### ISSUE THREAD

**Issue by theOtherHolmes** [godotengine/godot-docs#1893]
**Godot version:**
3.1 alpha, within XCode

**OS/device including version:**
macOS El Capitan 10.11.6

**Issue description:**
I have been following the steps to [set up Xcode as an IDE](http://docs.godotengine.org/en/3.0/development/cpp/configuring_an_ide.html#doc-configuring-an-ide-xcode).

When I try to build, I immediately get an error that Xcode "can't exec" the scons build tool because "permission denied."

I'm wondering if I did not provide the proper path to scons.  When the documentation says _Set the Build tool to the path to scons_, which path does it mean?  Does it mean the scons folder deep in my MacPorts folder (this is, I think, what was installed when I ran the python install script for scons)? Is it a particular file within that folder? Is it something in the scons folder that's still in my Downloads folder (the same folder from which I executed the python scons install script)?

Thanks.

**Comment by samgreen** [comment]
FYI this is also the docs repo, you'll probably get faster help in the Discord, and if you continue to have trouble building you might get more attention in the engine repo.

I added `scons` to my `PATH` variable in my environment so it was accessible everywhere. I believe this is what the documentation means.

You want to `cd` to the build folder and then execute `scons ...` you DO NOT WANT any prefix to this like `/usr/bin/scons ...`.

Hopefully that helps.

**Comment by Calinou** [comment]
I'll close this as the question was answered above.
