### ISSUE TITLE
Add sphinx.ext.autosectionlabel for easier referencing of sub sections

### ISSUE THREAD

**Issue by merumelu** [godotengine/godot-docs#1896]
There are times when you want to reference a sub section of another document (like [here](https://github.com/godotengine/godot-docs/pull/1895#discussion_r229017746)). However, the way `:ref:` works you'd need to add a new reST label for that section in the target document first.

A Spinx extension [`sphinx.ext.autosectionlabel`](http://www.sphinx-doc.org/en/master/usage/extensions/autosectionlabel.html) exists which auto generates labels for each section in a document, maybe we could add this extension to make referencing sub sections easier?

**Comment by NathanLovato** [comment]
We've been sticking to manual labels. @Calinou is there any plan to use that extension or should we close the issue?

**Comment by Calinou** [comment]
@NathanLovato Manual labels have been working fine for us so far. I wouldn't bother with an extension since we don't link to subsections that often.
