### ISSUE TITLE
Minimal jitter?

### ISSUE THREAD

**Issue by BillWelden** [godotengine/godot-docs#1913]
The page http://docs.godotengine.org/en/3.0/getting_started/workflow/assets/importing_scenes.html has the phrase "Failing to do this may result in minimal jitter."

Did you mean either "Failing to do this may result in some small amount of jitter." or "Doing this will result i miminal jitter."

"minimal jitter" means "the smallest possible amount of jitter", which is, of course, a good thing.

**Comment by akien-mga** [comment]
Fixed by #1992.
