### ISSUE TITLE
Shading Reference Overhaul

### ISSUE THREAD

**Issue by clayjohn** [godotengine/godot-docs#1921]
I plan on overhauling the shader documentation. Currently the shading language reference is fairly comprehensive and well put together. However, there is a lot of information on a [single page](http://docs.godotengine.org/en/latest/tutorials/shading/shading_language.html) and it is becoming increasingly difficult for new users to navigate.

My current idea is to split the Shading language document into a sub-directory containing a few different documents that cover: shaders generally, the Godot shading language, and the different shader types individually. In the process of doing this I will also add a lot more information on shaders and try to make the docs more accessible for new users. 

### Proposed Layout
Shading
- Shading language
  - Shaders
  - Shading language reference
  - Spatial shaders
  - Canvas item shaders
  - Particle shaders
- Shader materials
- Intro to shaders: 2D and 3D water
- ...

#### Shaders
The Shaders doc will introduce the reader to the concept of shaders and to Godot specific shader features (shader_types, render_modes, how a shader fits within a material etc.). It should be a point of first entry for those looking for reference information about shaders in Godot. It is not an introductory tutorial. It contains high-level information about shader_types; render_modes; and vertex, fragment, and light shaders as well as information about shaders generally. 

#### Shading language reference
This will contain the parts of the shading language reference that are not touched by the Shaders doc and the three shader type docs. It will serve as a useful page for more advanced users to read about things such as data types, flow control built-in functions etc. It will remain reference style documentation. I will edit it and expand on it as necessary.

#### Shader types
The three shader_type documents will contain what is in the shading language reference under [Shader types in depth](http://docs.godotengine.org/en/latest/tutorials/shading/shading_language.html#shader-types-in-depth). There will be one document for each shader_type that will contain render_modes, built-ins, and a description of how to use the shader. Most of this information is already contained in the shading language reference, however, I will expand upon it and organize it in an easier to follow fashion.

I decided to organize the documentation by shader type (spatial, canvas_item, particle) instead of processor function (vertex, fragment, light) because I figured different processor functions within the same shader type have more in common than the same processor functions from different shader types. For example, the vertex and fragment functions in spatial shaders have more in common than the vertex shader from a canvas_item shader has with a vertex shader from a spatial shader. Additionally, this provides a place to present information about render_modes. A description of the different processor functions generally will also be provided in the Shader doc, so there is not much of a need for them to have their own pages.

This is a fairly comprehensive overhaul of the shader section of the tutorials so feedback would be really helpful. I want to make sure that the changes are structured in the most intuitive logical way so that shaders are as accessible as possible for new users. 

related: #494, #1252, #1903

**Comment by akien-mga** [comment]
Fixed by #2046.
