### ISSUE TITLE
PSA: Added "proofreading" label for PRs waiting for a proofreader

### ISSUE THREAD

**Issue by akien-mga** [godotengine/godot-docs#1925]
Hi everyone,

I see that we have quite a few tutorial additions waiting for review in the current PR backlog, so I've added a `proofreading` label for those which have a sizeable text addition that needs to be reviewed for both style and content.

Once a contributor has reviewed it/approved it, they can remove the `proofreading` label (or comment that proofreading is done, if they don't have issue triage permissions).

This is a proposal to improve the workflow, feel free to comment/suggest a different/refined workflow :)

**Comment by mhilbrunner** [comment]
Closed, PSA noted :P
