### ISSUE TITLE
Document 3D Physics (Skeletons + Collision Shapes)

### ISSUE THREAD

**Issue by clayjohn** [godotengine/godot-docs#1934]
From a Reddit comment:
> Something that needs a mention in the documentation is that concave collision shapes can only interact with convex shapes. This was frustrating to figure out.
Something I was trying to find last night but couldn't figure out nor find a tutorial for was how to have a collision shape be transformed by a skeleton.
I have an incredibly low poly hand that I generated a concave collision shape for. The mesh for the hand animates just fine, but the collision shape doesn't move and I have no idea how to have it also be animated.

**Comment by NathanLovato** [comment]
Should be addressed by #4040
