### ISSUE TITLE
New Design for The Docs

### ISSUE THREAD

**Issue by djrm** [godotengine/godot-docs#194]
New design needed for The Documentation

so share ideas here

**Comment by eska014** [comment]
From the old pad https://pad.riseup.net/p/godot-website-pLdyglOTYFW9:

> Documentation: Needs navbar.

Just using the same navbar as the main site would be cohesive

**Comment by vnen** [comment]
If we are to design a Sphinx theme, I guess that using the website's palette (fonts, colors) would be nice.

**Comment by StraToN** [comment]
The most important thing we need, is the navigation bar to allow the display of hierarchical topics, whatever the level (though we should limit it to 3 levels, even if sub-subsections remain possible).

**Comment by NathanLovato** [comment]
Where is this at? Still an issue?

**Comment by StraToN** [comment]
@NathanLovato Apart from the left panel TOC showing too many levels (which problem has already been addressed by https://github.com/rtfd/sphinx_rtd_theme/pull/456 , yet the PR hasn't been merged at the moment).

**Comment by NathanLovato** [comment]
Alright, let's close for now and open a new, more specific discussion if need be.
