### ISSUE TITLE
KinematicBody's move_and_slide() return value incorrect in godot-docs

### ISSUE THREAD

**Issue by ageofabenius** [godotengine/godot-docs#1950]
KinematicBody's move_and_slide() description in Godot Docs shows the following for its return value: "Returns the movement that remained when the body stopped."  This was tested with a simple collision,  move_and_slide()'s return value was printed out as the KinematicBody object with a CollisionShape node approached and collided with a StaticBody object with a CollisionShape node.  From this it was seen that move_and_slide()'s return value is not the movement that remained (the portion of the movement that could not be completed due to a collision with another object), move_and_slide()'s return value is instead the movement that was completed (a Vector3 of the exact displacement of the object over the move).  This meant that once the collision occurred and the object stopped moving, all return values from move_and_slide() were (0.0,0.0,0.0).

**Comment by MunWolf** [comment]
If this was once true it no longer is so this can be closed...
