### ISSUE TITLE
Singletons (AutoLoad) example project broken

### ISSUE THREAD

**Issue by corrigentia** [godotengine/godot-docs#1966]
Both ``Scene1.tscn`` and ``Scene2.tscn`` have the ``Scene2.gd`` script attached; thus the scenes seem to fail switching from one to the other.

Solution: 

FileSystem tab -> 
double-click Scene1.tscn -> 
Scene tab -> 
click Scene1 -> 
Inspector tab -> 
scroll down to the Node heading -> 
Script -> 
drop-down menu -> 
Load -> 
Scene1.gd -> 
Open.

An additional minor gripe would be that the zip archive contained a ``_MACOSX`` folder (directory) that served no functional purpose.

**Comment by SimoB** [comment]
Same problem found, I was not able to find the autoload.zip file on the repo to submit a pull request with the fix!

**Comment by skyace65** [comment]
This was fixed by PR #2289. This issue can be closed.
