### ISSUE TITLE
not clear whether "const G = A + 20" would be valid

### ISSUE THREAD

**Issue by sudoman** [godotengine/godot-docs#1970]
On this page:

https://docs.godotengine.org/en/3.0/getting_started/scripting/gdscript/gdscript_basics.html#constants

it's not clear whether `const G = A + 20` would be valid. `A` is a constant variable declared above `G`, so it's plausible, but it's not included as an example, so I don't know.

**Comment by clayjohn** [comment]
I'm assuming you've tried this out by now, but it is valid, I will add an example to the docs.

**Comment by akien-mga** [comment]
Fixed by #1993.
