### ISSUE TITLE
not clear what is meant by tools running in editor

### ISSUE THREAD

**Issue by sudoman** [godotengine/godot-docs#1972]
https://docs.godotengine.org/en/3.0/getting_started/scripting/gdscript/gdscript_basics.html#tool-mode

> Scripts, by default, don’t run inside the editor and only the exported properties can be changed. In some cases it is desired that they do run inside the editor...

It's unclear to me running inside the "editor" means. Does it mean that `tool` code runs in the game editor, as opposed to the game itself? Which editor: the whole editing suite, or the property editor, for instance?

**Comment by bojidar-bg** [comment]
The "editor" in general refers to the Godot engine editor, which is the thing opened after the project manager. Thus tool scripts run in the whole editor (which happens to include a property editor ("inspector"), 2d/3d editor ("viewport"), etc.)

**Comment by akien-mga** [comment]
We now have a dedicated tutorial for this: https://docs.godotengine.org/en/latest/tutorials/misc/running_code_in_the_editor.html
