### ISSUE TITLE
improper indentation in code block

### ISSUE THREAD

**Issue by sudoman** [godotengine/godot-docs#1974]
https://docs.godotengine.org/en/3.0/getting_started/scripting/gdscript/gdscript_basics.html#coroutines-signals

^ the last code block in this section has improper indentation.

**Comment by clayjohn** [comment]
@akien-mga You fixed this when you fixed the mixed tabs and spaces in commit  a0e32ac it just needs to be cherry picked for the 3.0 branch.

**Comment by Calinou** [comment]
This was fixed in `3.1` and `3.2` a while ago, closing.
