### ISSUE TITLE
Move FAQ to main docs page

### ISSUE THREAD

**Issue by n-pigeon** [godotengine/godot-docs#198]
FAQ section is currently in Advanced section. I think there is not much if any advanced topics there, but many very useful and interesting ones. I think it would be good idea to not hide it and move to main docs page for better exposure :)

**Comment by StraToN** [comment]
I totally agree on this one. I planned to move it as soon as we have the new docs organization defined.

**Comment by akien-mga** [comment]
Fixed with the docs reorganization.
