### ISSUE TITLE
Possible error: "to tag scenes which are enemies" is unclear

### ISSUE THREAD

**Issue by sudoman** [godotengine/godot-docs#1986]
<https://docs.godotengine.org/en/3.0/getting_started/step_by_step/scripting_continued.html#groups>

> One example would be to tag scenes which are enemies

Do you mean "tag enemies in a scene"?

**Comment by sudoman** [comment]
Based on early documentation before this point, it seemed as if scenes couldn't be nodes, thus the reason why that quote seemed incorrect. However there is some evidence a bit later on in the docs that imply that scenes can be nodes.

**Comment by bojidar-bg** [comment]
A scene is a node plus its children and their properties. Maybe it is not clear enough by that point in the docs, in which case it would be nice to clear it.

I think that the text "to tag scenes which are enemies" can be safely removed or, perheaps, put as a paragraph below the UI and code examples, explaining it in more detail.

**Comment by clayjohn** [comment]
I think an easy fix would be to just change "scenes" to "nodes", the rest of the section refers to the enemies as nodes.

**Comment by akien-mga** [comment]
Fixed by #1991.
