### ISSUE TITLE
Tutorial doesn't say to center or wrap text

### ISSUE THREAD

**Issue by sudoman** [godotengine/godot-docs#1997]
https://docs.godotengine.org/en/3.0/getting_started/step_by_step/your_first_game.html#hud

When following the instructions, I noticed that the "Dodge the Creeps!" text floated off of the side of the page and that text was not horizontally centered for that and the other label. I was able to figure out how to fix that in the inspector, but it might be useful to include those instructions in the docs.

**Comment by sudoman** [comment]
It looks like one of the scripts may already account for the lack of line wrapping:

````
    $MessageLabel.text = "Dodge the\nCreeps!"
````

**Comment by cbscribe** [comment]
Addressing this with a new 3.1-focused revision.
