### ISSUE TITLE
In "Particle" section of tutorial, "Visibility Rect" is confusing

### ISSUE THREAD

**Issue by sudoman** [godotengine/godot-docs#1998]
https://docs.godotengine.org/en/3.0/getting_started/step_by_step/your_first_game.html#particles

In the first image at the above link, the `Visibility Rect` is set as `Rect3`. However, when I click on that option, i'm presented with the option to change `x`, `y`, `h`, and `w` variables, not to change it from `AABB` to `Rect`.

I downloaded the demo source code, and that version uses `AABB` for that option, not `Rect3`. It appears to use the default values of the four variables.

**Comment by clayjohn** [comment]
related: #1714

**Comment by skyace65** [comment]
@sudoman the particles section of that tutorial was removed in the update to 3.1 (it's too complicated to just be a small section of the tutorial), you can close this issue.

**Comment by sudoman** [comment]
Thanks! : )
