### ISSUE TITLE
Document supported constructors for matrices in shading language

### ISSUE THREAD

**Issue by akien-mga** [godotengine/godot-docs#2025]
We recently rejected this PR in the engine repo (godotengine/godot#23295), and it raised the issue that we don't properly document what constructors are supported for `mat2`, `mat3` and `mat4` in the shading language. It would be good to add it to http://docs.godotengine.org/en/latest/tutorials/shading/shading_language.html

See https://github.com/clayjohn/godot/blob/master/servers/visual/shader_language.cpp#L1386-L1392 (and further down below, we also support `mat3(mat3)` for example).

**Comment by clayjohn** [comment]
I'm just about finished the overhaul of the shading language stuff. I will add this at the same time.

**Comment by clayjohn** [comment]
Actually, looking into this now, we have already documented all the supported constructors for matrices in  http://docs.godotengine.org/en/latest/tutorials/shading/shading_language.html#constructing

**Comment by akien-mga** [comment]
Ah indeed, I overlooked that. Thanks!
