### ISSUE TITLE
3.1: Document new TileSet editor

### ISSUE THREAD

**Issue by akien-mga** [godotengine/godot-docs#2060]
@MarianoGnu added a new TileSet editor in 3.1, which currently lacks documentation.

godotengine/godot#20585 has some documentation that could be adapted for the official docs. This video can also help understand how it works: https://www.youtube.com/watch?v=a4QvkFno5UU

@YeldhamDev and @guilhermefelipecgs can maybe help too.

**Comment by Duroxxigar** [comment]
@akien-mga I'd like to go ahead and take this on. I just noticed it and was about to make an issue about this. It'll be my first contribution, so it might take a second to get everything set up initially.
