### ISSUE TITLE
Document problems with GCC 6

### ISSUE THREAD

**Issue by vnen** [godotengine/godot-docs#208]
There are godotengine/godot#4623 and godotengine/godot#4673 reporting problems with GCC 6 optimizations. Until they are properly resolved, there should be a warning about the compiler on the documentation.

**Comment by StraToN** [comment]
Does this affect all OS, or only X11?

**Comment by vnen** [comment]
It affects GCC. If you build with Mingw using GCC 6, the problems will show on Windows too.
