### ISSUE TITLE
input map does not recognize shift state with key left/right/up/down

### ISSUE THREAD

**Issue by rxadmin** [godotengine/godot-docs#2087]
In the input map I have defined new entries for: shift+arrow key, e.g. if have "ui_map_left" defined as key "shift+left".

In _input I check using is_action("ui_map_left"). If I press the left/right/up/down with shift the correct action is performed. Also this action is repeated. If I keep shift+left pressed the action is fired multiple times.

However, if I press left/right/up/down without the shift the same action is performed, but without the repeat. So I have to repress the left/right/up/down key to fire the action again.

Godot version: 3.0.6
OS: Windows 10 Enterprise, 64 bit

**Comment by skyace65** [comment]
You're in the wrong place, All engine bugs should be reported [here](https://github.com/godotengine/godot/issues). godot-docs issues is for issues with Godot's documentation.
