### ISSUE TITLE
Shower of Bullets demo not found

### ISSUE THREAD

**Issue by Rubonnek** [godotengine/godot-docs#2088]
A demo called "Shower of Bullets" is mentioned in the Custom Drawing tutorial, but the demo was removed in commit 85b8aeebc17fd568ea56e4ba707199794167341c of the godot-demo-projecs repo.

https://github.com/godotengine/godot-docs/blob/13a53c907f18e5d2b5be442e040a18f6c9da9445/tutorials/2d/custom_drawing_in_2d.rst#L28-L31

**Comment by clayjohn** [comment]
I think the entire bullet point should just be removed. Custom drawing is not meant as a cheap way to draw hundreds of thousands of objects.

**Comment by bojidar-bg** [comment]
> Custom drawing is not meant as a cheap way to draw hundreds of thousands of objects.

Then, a cheap way of drawing thousands of objects should be mentioned.

**Comment by clayjohn** [comment]
Currently Godot doesn't have a clear-cut method for drawing thousands of objects on screen at once. Depending on your hardware, it should be possible with either nodes or custom drawing. In the future (once batching is implemented) there will be a better option for drawing a lot of nodes without incurring the cost of a bunch of draw-calls.

Custom drawing avoids the overhead of updating the node itself, so in that way it may be a little faster, it also avoids allocating the full memory for a node. 

Maybe it would be better to say:
"Drawing a large number of simple objects. Custom drawing avoids the overhead of using nodes which makes it less memory intensive and potentially faster."
