### ISSUE TITLE
how to show hosted weblate translate godot engine docs in to language es_MX

### ISSUE THREAD

**Issue by Small-Develop** [godotengine/godot-docs#2098]
hello a question I hope someone can guide me, I want to help translate the godot engine documentation into Spanish but I have seen that there is already a translated part, how can I do it so that we can see what has already been translated

this is the link of your translation
https://hosted.weblate.org/translate/godot-engine/godot-docs/es_MX/?type=todo

because I see in http://docs.godotengine.org/en/3.0/ in the part of Read the Docs it does not appear in Languages es_MX
![fdra](https://user-images.githubusercontent.com/30481286/50678697-a1db7980-0fc5-11e9-8e76-b0103829b46e.PNG)

someone can explain to me what steps I need to follow to be able to visualize and show  the documentation that is being translated. thanks

**Comment by akien-mga** [comment]
I'm the one who has to create a new ReadTheDocs instance, sync translations in https://github.com/godotengine/godot-docs-l10n, ask RTD admins to extend the timeout for the new instance as our builds are heavy, and then it would appear.

But I only do it once a language has a high level of completion rate, which is not the case yet for `es_MX`. Once it reaches ~15% or so I could add it.

That being said, I think it would be a lot more productive to help complete the international Spanish translation (`es`), and then copy it and adapt it to Mexican Spanish specifics. Godot's documentation is huge, and translating it all from scratch when it's already 50% translated in international Spanish seems like a lot of duplicate effort.
