### ISSUE TITLE
Post Import Script docs are very outdated/incorrect

### ISSUE THREAD

**Issue by thirite** [godotengine/godot-docs#210]
The [docs here](docs.godotengine.org/en/latest/tutorials/3d/importing_3d_scenes.html) are outdated and the example given does not work for Godot 2.1 RC1.

The example given should look something like this instead (just tested and it works 100%):

```
tool # needed so it runs in editor
extends EditorScenePostImport

func post_import(_scene):
    # do your stuff here
    # scene contains the imported scene starting from the root node
    _scene.set_name("MyScene") # renames the scene's root node
    return _scene
```

It seems having the arg named as "_scene" rather than "scene" is necessary, as well as returning the _scene at the end of the function.

What with Godot 2.1 RC1 having auto-update scenes enabled by default, Import Scripts are going to become very important for modifying those scenes automatically as well.

**Comment by mhilbrunner** [comment]
This seems fixed now for 3.0.
