### ISSUE TITLE
"mere" adjective hard to understand for some non-native speakers

### ISSUE THREAD

**Issue by cobreen** [godotengine/godot-docs#2110]
On http://docs.godotengine.org/en/3.0/getting_started/step_by_step/resources.html page

I found wrong spelling

Resources are mere data containers. This means that they don’t do any action nor process any information. Resources just contain data.

Wrong word is "mere" must be "more".

**Comment by bojidar-bg** [comment]
"Mere" is valid English. "More" would make no sense there.

[Wiktionary](https://en.wiktionary.org/wiki/mere#Etymology_4):
> Just, only; no more than, pure and simple, neither more nor better than might be expected.

[theFreeDictionary](https://www.thefreedictionary.com/mere):
> adj [..] being nothing more than something specified

Probably it can be switched to some better-known word, for example, "just", "no more than", or "simply".
