### ISSUE TITLE
"Rupee" Zelda reference in UI tutorial is not localization friendly

### ISSUE THREAD

**Issue by akien-mga** [godotengine/godot-docs#2114]
As discussed in #1957, the "Rupee" name used to refer to green gems in the "Design the GUI" tutorial has two issues:
- "Rupee" is actually the name of the currency of India and various other countries. Its use in the English version of The Legend of Zelda is an example of Engrish. As such the reference might be lost to many readers, especially if they're not familiar with the English version of Zelda.
- It's hard for translators to get right, as they might also miss the reference and translate it as e.g. "roupie" in French (the currency) instead of using the proper translation from the Legend of Zelda series, if they know it/find it.

All in all, it's not worth the trouble :) It should be replaced by e.g. Emerald (since it's green), but images referring to the name need to be adapted accordingly.

**Comment by yehjaemin** [comment]
@akien-mga 
Hi, is it alright if I do this? It seems like there's no one assigned and I didn't find a related pull request.
