### ISSUE TITLE
Update iOS export doc for 3.1

### ISSUE THREAD

**Issue by akien-mga** [godotengine/godot-docs#2152]
The docs on exporting to iOS are partly outdated, and do not stress out the exact export steps in a user-friendly manner. Since there is no One-Click Deploy for iOS, and using Xcode is tricky, this should be updated to be easy to use and reliable.

See the discussion on godotengine/godot#17802.

The export dialog does some validation of the application identifier in 3.1, but AFAIK it does not validate other fields, while some of them are mandatory if you don't want to have weird errors in Xcode or when installing. This should be documented clearly (and ideally improved on the engine side too eventually, but for 3.1 we're running out of time).

CC @BastiaanOlij

**Comment by akien-mga** [comment]
See also godotengine/godot#19996.

**Comment by BastiaanOlij** [comment]
I'll find some time to document this over the weekend as I've now successfully exported my project and have a decent idea of how it works.

I'm also putting a few fixes through and an enhancement (though I'm guessing the enhancement might not make it into the 3.1 release :) )

**Comment by Calinou** [comment]
This is likely done by now, closing. Please open new issues if things are still missing in the current iOS exporting documentation.
