### ISSUE TITLE
Update iOS compilation doc for 3.1

### ISSUE THREAD

**Issue by akien-mga** [godotengine/godot-docs#2153]
See issue in godotengine/godot#20383 due to not preparing the iOS template as the engine and Xcode expect it.

@hpvb's build scripts for official 3.0.6 can be used to see what may be missing from current docs: https://notabug.org/hp/godot-scripts

Note that `x86_64` builds should be added (were not used yet in 3.0.6).

@hpvb can maybe also share insights from his current 3.1 beta buildsystem.

See also #2152.

**Comment by Calinou** [comment]
This is likely done by now, closing. Please open new issues if things are still missing in the current iOS compilation
 documentation.
