### ISSUE TITLE
TileMaps/TileSets

### ISSUE THREAD

**Issue by 10jasper10** [godotengine/godot-docs#2154]
Here are my three issues:
They are terrible to import, setting up textures and the hitboxes takes time, especially the hitboxes.

You can't select multiple tiles to place at once. (You can use a program like tilled tough)

Tilesets are in no way ordered, you can try but their id is scrambled when exporting as a tileset, you can name them 1 2 3 but they will be ordered 1 3 2 even if the layout had them 1 2 3! (Makes it hard to use with tilled)

This makes it hard to work with tilemaps in general.

**Comment by clayjohn** [comment]
This is the repo for Godot's documentation. If you want to suggest changes to Godot, please submit an issue in the [proper repository](https://github.com/godotengine/godot).

**Comment by 10jasper10** [comment]
My error, i have been redirected somewhere in the process.
