### ISSUE TITLE
(Arch) Cross-compiling for Windows: mingw-w64-gcc is no longer in the official repositories. The current instructions are outdated.

### ISSUE THREAD

**Issue by FlashDaggerX** [godotengine/godot-docs#2157]
I'm not sure how recently, but MinGW is no longer in the official repositories. MinGW can be picked up from the AUR now.

[Link to the documentation in question](https://docs.godotengine.org/en/3.0/development/compiling/compiling_for_windows.html#cross-compiling-for-windows-from-other-operating-systems)
[Link to documentation file in godot-docs repository](https://github.com/godotengine/godot-docs/blob/master/development/compiling/compiling_for_windows.rst#cross-compiling-for-windows-from-other-operating-systems)
[Link to mingw-w64-gcc (AUR)](https://aur.archlinux.org/packages/mingw-w64-gcc/)

**Comment by FlashDaggerX** [comment]
This issue is still relevant in master (083432da3ef621b309ebc9d54f7b7fa4a4b39c58).

**Comment by akien-mga** [comment]
CC @Calinou
