### ISSUE TITLE
FPS Tutorial Turret RayCast Error?

### ISSUE THREAD

**Issue by GETASFAR** [godotengine/godot-docs#2164]
While I was working on the FPS Tutorial, I noticed that the game crashed whenever I told a turret to use raycast. After looking at the code, I believe I found the problem.

This is the code provided in the tutorial when you swap a turret to raycast:
        node_raycast.look_at(current_target.global_transform.origin + PLAYER_HEIGHT, Vector3(0,1,0))

This is what was crashing the game.
Once I changed this to:
node_raycast.look_at(current_target.global_transform.origin + Vector3(0, PLAYER_HEIGHT, 0), Vector3(0,1,0))

The code was working and was no longer crashing the game.

I figured I should bring this up just in case others were having this problem as well, and requesting that the tutorial be fixed so no one else would be having the problem.

**Comment by skyace65** [comment]
I don't know when this was fixed, but the tutorial now shows the correct code in the docs. You can close this issue.
