### ISSUE TITLE
Make a dedicated series for C#

### ISSUE THREAD

**Issue by Nwott** [godotengine/godot-docs#2171]
As of right now, the documentation does not clearly explain the differences between GDScript and C# well. I suggest that you make a section for different languages supported by the Godot Engine. There should be a clear explanation on how to script using C#. The only current explanations are how to set it up and copy paste texts.

**Comment by Calinou** [comment]
Most of the differences should be documented here already: https://docs.godotengine.org/en/latest/getting_started/scripting/c_sharp/c_sharp_differences.html

Please open new issues if there are still undocumented differences (after searching for possible duplicates).
