### ISSUE TITLE
"Matrices and transforms" article offers very little practical uses later on

### ISSUE THREAD

**Issue by wingedadventurer** [godotengine/godot-docs#2174]
The [Matrices and transforms](https://docs.godotengine.org/en/latest/tutorials/math/matrices_and_transforms.html#doc-matrices-and-transforms) article starts off nicely with clear explanations and several practical uses. However the subsections later on (affine inverse, multiplications, tips) just throw some math definitions at you (which I had trouble understanding even though I passed several math courses in college), and don't show any practical uses. Same for the 3D part at the end of article where several pictures and examples would be very useful.

**Comment by aaronfranke** [comment]
Also, the article has numerous issues: https://github.com/godotengine/godot-docs/issues/2174

Aside from fixing all of those issues, it would be nice if you could share some suggestions for the article.

**Comment by wingedadventurer** [comment]
- End of `Operations/Scale` subsection:
`For those who have been living on this planet long enough, a good reference of how transform works is this:` (image of turtle) `A matrix is used similarly to a turtle. The turtle most likely had a matrix inside (and you are likely learning this many years after discovering Santa is not real).`
This part is completely aimed at people who know about how the turtle works, and doesn't really provide much help to newcomers. I'd remove it, or at least move them to `Matrix tips` section.
- `Transform`, `Inverse transform`, `Orthonormal matrices`, and almost all the subsections after those could use a visual explanation -- the spaceship with these effects applied -- like the previous ones have. Matrices and their operations are I believe best understood when you're able to see them in action.
- Finally, those subsections can have one or two use cases (Why would I ever multiply 2 matrices?), like some other articles provide a ton of.
