### ISSUE TITLE
Undocumented bind_child_mode_to_bone

### ISSUE THREAD

**Issue by rcorre** [godotengine/godot-docs#2177]
[Skeleton.bind_child_node_to_bone](https://docs.godotengine.org/en/latest/classes/class_skeleton.html#class-skeleton-method-bind-child-node-to-bone) says only:

> Deprecated soon.

The documentation should still specify:

1. What the function currently does
2. What you should use instead

I want to attach a node to a single bone in a skeleton, and this sounded like the function I needed, but now I'm somewhat lost. After some digging, I think I probably want a [BoneAttachment](https://docs.godotengine.org/en/latest/classes/class_boneattachment.html?highlight=boneattachment), but it would be nice if the docs actually pointed you here. I'd be happy to make this change if someone can confirm that I'm actually correct.

**Comment by akien-mga** [comment]
This has been documented as "Deprecated soon." since the first open source commit of the engine in 2014... Yet it's still used in the engine internally, so either @reduz changed his mind, or he completely forgot about it.

**Comment by akien-mga** [comment]
Same thing for `get_bound_child_nodes_to_bone` and `unbind_child_node_from_bone` BTW.
