### ISSUE TITLE
Multiple viewports: only render some objects in some viewports

### ISSUE THREAD

**Issue by remram44** [godotengine/godot-docs#2179]
*Apologies if there is some obvious way to do this, but I could not find it. I have searched the bug tracker and asked on Riot and Discord. I understand not many people are making split-screen games at this day and age.*

**Godot version:**
3.0.6

**Issue description:**
I am using a split-screen setup for local multiplayer, but I need some objects to be invisible to some players. This doesn't seem to be possible, short of duplicating the whole scene and all its objects.

It would be nice to have a way to do this, either by hiding some objects before drawing happens for a specific viewport/camera, or only rendering a specific group on each viewport/camera, etc.

If this is possible, at least a doc improvement seems required (which I'm happy to help with!)

**Steps to reproduce:**
Have multiple viewports rendering the same scene (via [setting the world property from code](http://kidscancode.org/blog/2018/07/godot3_splitscreen/)).

**Comment by akien-mga** [comment]
Transferred the issue to the docs repository as the feature works already, it just needs to be better documented.

From a quick glance at the docs, I'd say we need:
- Improve the documentation of the Camera class to mention in its Description that the `[member cull_mask]` is used to define what `[VisualInstance]`s will render in this Camera, based on their `[member VisualInstance.layers]` (this should be done in `Camera.xml` in the engine repo)
- Improve the [Viewports tutorial](http://docs.godotengine.org/en/latest/tutorials/viewports/viewports.html) to mention this too, likely in the Camera section.

**Comment by Asaurus1** [comment]
> Transferred the issue to the docs repository as the feature works already, it just needs to be better documented.
> 
> From a quick glance at the docs, I'd say we need:
> 
> * Improve the documentation of the Camera class to mention in its Description that the `[member cull_mask]` is used to define what `[VisualInstance]`s will render in this Camera, based on their `[member VisualInstance.layers]` (this should be done in `Camera.xml` in the engine repo)
> * Improve the [Viewports tutorial](http://docs.godotengine.org/en/latest/tutorials/viewports/viewports.html) to mention this too, likely in the Camera section.

per EON-S this might not be possible in 2D as cameras do not have visual layers. I am personally looking for a feature like this in 2D. If the 2D case is not the same as the 3D case (i.e. just update the docs), is it worth expanding the scope here to include an implementation of view layers in 2D?

**Comment by moonLight-7k** [comment]
I want to contribute to solve this issue

**Comment by tetrapod00** [comment]
This is resolved in 4.3/stable, by https://github.com/godotengine/godot-docs/pull/2768 and by https://github.com/godotengine/godot/pull/74688 and prior class reference PRs. Closing.

If there are still improvements that need to be made for 2D, which uses a separate system, I'd recommend a new issue that identifies problems with the current 4.x docs.
