### ISSUE TITLE
Build timeouts on rtd.org since mid July (longer than 900 s)

### ISSUE THREAD

**Issue by akien-mga** [godotengine/godot-docs#218]
Looks like we are now facing build timeouts on https://readthedocs.org/projects/godot due to our documentation taking too long to build.

The default RTD timeout is 900 s (15 min), and we used to have build ranging from 400 s to 600 s until two weeks ago, so it worked fine.

We recently switched to our long wished-for tree-like navigation scheme (7b5e983 and 52b63a9), and had to overwrite the default rtd.org config for that, which seemingly increased the build time:
- Before, 400 s: https://readthedocs.org/projects/godot/builds/4212858/
- After, 880 s: https://readthedocs.org/projects/godot/builds/4219602/

We need to investigate what makes the build time longer, and how we can decrease it. Some ideas on the cause:
- the tree-like navigation might take ages to build (could be checked offline by building with and without the option)
- the default rtd config that we now overwrite might have had optimizations that we should readd

Potential solutions:
- compare the final conf.py of the two builds linked above to see what we might be missing
- fix some of the current warnings of our builds, that couldn't hurt
- see with @agjohnson if we could get a timeout increase, as our docs are only going to get bigger (especially as the API reference gets filled little by little and new tutorials are written). https://github.com/rtfd/readthedocs.org/issues/1767 mentioned exposing the possibility to configure a higher timeout limit for Gold members/donators; I can't check if it's implemented as I still haven't setup a donation yet, but it's on my todo list :)

**Comment by agjohnson** [comment]
Ah yes, `collapse_navigation` cuts down on build time considerably for large doc sets, so this doesn't surprise me all that much. Warning here: with sufficiently large enough doc sets, the build time and memory consumption becomes a considerable load on our build infrastructure -- 1h builds is not uncommon here.

@akien-mga for now, extending the timeout is a manual process for site admins, it's not directly tied to gold subscriptions. Donations/subscriptions help us a great deal, but we also get the economics of open source -- sustainability in open source shouldn't have to be projects trading money. I'm happy to bump up the timeout either way.

If there is anyone involved with the project financing or, if applicable, someone familiar with maybe commercial use, I'd be really interested in getting some feedback here -- feel free to email me at anthony@readthedocs.org.

**Comment by akien-mga** [comment]
Thanks for the fast answer @agjohnson.

For the time being we'd be glad for a timeout extension to have things working -- we rarely update docs several times a day so I hope we shouldn't be too big a burden on the infrastructure for the time being. I'm committed to looking for ways to cut down our build time though.

A possibility I had in mind originally was to split our class reference (the `classes/*.rst` auto-generated files) to their own project, as they're bound to be updated less often, and are IMO what take the most time building. But it might bring other challenges to make proper cross-references, common search function, etc.

Another possibility would be to have a cache of the previous build and only build the difference. It should dramatically decrease the build times, but I guess it's something you've already thought of upstream and if it's not there (yet), there is likely a good reason.

Regarding `collapse_navigation: False`, this is a feature very dear to our project leaders, so we'd like to keep using it even if it means longer builds -- as long as it stays reasonable.

> If there is anyone involved with the project financing or, if applicable, someone familiar with maybe commercial use, I'd be really interested in getting some feedback here

Do you mean about Godot's financing, or generally-speaking about way to get financing for open source projects? Regarding Godot, for the time being we're fully independent and supported by Software Freedom Conservancy which manages our donations.
Our funds are therefore also donation-based and limited, though I am in mind to advocate that we setup (small ;)) regular donations to the various open source services we're using for our project (TuxFamily, Hosted Weblate, Read The Docs).

**Comment by reduz** [comment]
@agjohnson  I understand and really appreciate the work you guys are doing, and even more the fact you are providing hosting for our documentation, this is invaluable for our project. 

However, we are having constant frustration with being unable to tweak the documentation to the way we need, and having to hack things around is what is leading to problems like the build timeouts mentioned above.  Godot is a very large project and has a very large amount of documentation, and our users constantly express frustration about not finding things or not understanding how things are organized. More to the point:

1) We can't get rid of headings showing up in the TOC. Our TOC has more than one level at many places due to how many areas it has to cover, and having the headings show up causes great confusion.
2) We _need_ to show documentation to show as a tree, where you can collapse and uncollapse sections at well, in order to discover what is a subsection, so we can't go by without this feature.

Here is how we would like our documentation to show:, see how it is much cleaner than what ReadTheDocs offers to us:

https://docs.unity3d.com/Manual/index.html

So, given we can't really find enough flexibility in RTD, we are seriously considering moving away from it and laying out our custom sphinx doc generator.

So, In all truth, if you can manage to figure out a way for our documentation to look and work like the example above, we would make a very generous donation to your organization, which would be the equivalent of how much it would cost us to hire a developer to make a custom theme and host the doc ourselves. I know that for you, this only means a small amount of tweaking, but we are in desperate need of a solution, which RTD is currently not flexible enough to provide.

**Comment by reduz** [comment]
@agjohnson In the worst case if you guys can't do it, we can pay for the work involved as long as you would accept it and merge it.

**Comment by akien-mga** [comment]
Just to clarify for @reduz, there are three components of RTD that we are using:
- The RTD open source software that runs readthedocs.org, and that we could host ourselves if we wanted, and which is basically a web interface to automatically trigger sphinx builds of the documentation based on our GH repo. The source is at https://github.com/rtfd/readthedocs.org
- The (free) hosting that the RTD team provides on readthedocs.org, and thus using the above-mentioned software.
- The sphinx_rtd_theme which is the default Sphinx theme used by RTD. This is not forced onto us, and we can of course use another theme or fork it to adapt it to our needs; though we'd love of course to use upstream features and prevent us from having to work on something which is not our core purpose. Source at https://github.com/snide/sphinx_rtd_theme/

Most of the frustration you mentioned with features of our online docs are linked to the sphinx_rtd_theme and not with the readthedocs.org software and hosting. We could build the docs locally and upload the static HTML + PDF to our own server and have the same output as on rtd.org, albeit it would be more manual work.

**Comment by agjohnson** [comment]
Okay, lots of feedback here, I'll address sequentially:

@akien-mga extending the timeout should be fine in, especially the case of low build frequency. We're mostly concerned about build queue fairness here. If these builds become a resource hog, we're happy to find a compromise that gets you the docs you want.

Regarding financing, I was mostly curious who your users are -- are they companies developing private products/indie game developers/etc? Do they have money?

Also regarding financing: asking open source projects for money is not what I want out of the ecosystem. As you said, you rely on donations, and donations are not sustainable.

We are trying to rely on our in-house ads, as funding through donations/gold subscriptions is not sustainable for us, however I see our in house ads are disabled on your project. If this is a problem of ethos, we'd love feedback here. If this is a simple matter of aversion to advertising, understand that this is how we pay for our time to be full-time engineers on the project -- and, to clarify, this doesn't mean our time is paid for, we are severely underfunded and overworked here.

@reduz Regarding timeouts, I understand the frustration with timeouts. Ping us when it's an issue though, build resource constraints are required for us -- we don't have the budget to scale out our servers to allow unconstrained builds.

@reduz For headings in your TOC, see sphinx_rtd_theme option `navigation_depth`

> So, given we can't really find enough flexibility in RTD, we are seriously considering moving away from it and laying out our custom sphinx doc generator.

@reduz The largest issue seems to be simply a matter of build time constraints, this is entirely on our end. We do offer contract support for projects and doc development, but this doesn't seem like it should be necessary. Feel free to email me at anthony@readthedocs.org for this.

@akien-mga The issue with collapsable navigation is more of a constraint around Sphinx, as for whatever reason, it causes a huge spike in resource usage.

Also, in the case of splitting out API refs, look into intersphinx.

Have to run to catch a train, sorry for the dump of information, but hopefully some of this helps.

**Comment by akien-mga** [comment]
@agjohnson Regarding our users, they're (for now) mostly indie developers working alone or in small studios (so likely without much money either, and happy to have an open source and forever free of charge engine :)), a bunch of free software lovers and gamedev hobbyists like me, and maybe a few bigger studios - but I don't know of any big name yet. We're aiming for the top though, and hopefully our user base will continue growing to encompass also bigger studios, as we have a solution of great quality and performance (IMO).

Regarding in-house ads, I don't think we disabled them (actually just checked in the settings, they're enabled). At first I was confused to see those popup a couple months after we started using RTD, but I've recently seen the nice explanations in the Advertising section of the admin panel and I fully agree with your motives. As it's just one small ad in the left panel, usually discreet and related to sponsored projects, I find it just fine.

Regarding the `navigation_depth` option, I believe it does not match our needs as it applies to the whole TOC, when what we need would be to limit the depth at the page level, and not the TOC one. I've opened an issue about it on https://github.com/snide/sphinx_rtd_theme/issues/312.

**Comment by reduz** [comment]
@agjohnson I suggest you give another check at the link I supplied. They have different navigation depths, yet headings to not appear  anywhere in the TOC. 

What we need is not limiting navigation depth, but simply disabling headings from appearing in the TOC.

**Comment by agjohnson** [comment]
@reduz The `toctree` directive `:titlesonly:` is what you want then. This is not an issue limited to the RTD theme.

**Comment by akien-mga** [comment]
Thanks for the hint @agjohnson, I'll try it out asap. /me has a hard time learning all Sphinx features :D

**Comment by StraToN** [comment]
@agjohnson I just tried your hint, unfortunately it doesn't seem to work. I still can expand each page in the TOC and access subheaders in it.

**Comment by akien-mga** [comment]
@agjohnson We'd still be interested in a timeout extension as right now we seem to be playing very close to the limit, sometimes lucky enough to have a build in ~800s, but sometimes above: https://readthedocs.org/projects/godot/builds/

**Comment by reduz** [comment]
@agjohnson , @akien-mga , @StraToN : Hi guys, have there been any news from this?

As far as I understand, :titlesonly: fails to work, and we didn't hear back from a timeout extension.

@agjohnson As mentioned before, If you guys could help us fix these issues and make our doc work the way we intend, we would very gladly do a generous donation to your project.

**Comment by agjohnson** [comment]
Sorry, this completely fell off my radar. I bumped up the timeout limit, we might need to continue increasing if the upper limit is higher than I thought.

**Comment by akien-mga** [comment]
I think it has been working pretty fine over the last few months, so closing as fixed.
