### ISSUE TITLE
Can't edit the group of multiple nodes at same time

### ISSUE THREAD

**Issue by maxiestuinge** [godotengine/godot-docs#219]
If I select only one node in the Scene panel, i can edit the Group info of that node in the Nodes editor.
But if i select more than one, i can't.

I think that is very usual to change the group of multiple nodes at same time.

My suggestion is:

"If the user selects nodes that're in different groups, don't show anything in the Groups panel. But if the user try to edit the group of nodes in the same group (of without group) then shows the Group tab of the Nodes panel as if you edit only one node and applies changes to all the selected nodes"

Many thanks.

**Comment by vnen** [comment]
I didn't understand. Is this a documentation issue?

**Comment by maxiestuinge** [comment]
Hi vnen, no. This is a request for an editor feature (i didn't found the proper way to add a tag to this threath, sorry).

**Comment by bojidar-bg** [comment]
Please, reopen at https://github.com/godotengine/godot
