### ISSUE TITLE
Enhance C# docs for [Export] keyword

### ISSUE THREAD

**Issue by akien-mga** [godotengine/godot-docs#2194]
See godotengine/godot#25956.

GDScript has extensive examples for (I assume) all the export hints that are supported: https://docs.godotengine.org/en/latest/getting_started/scripting/gdscript/gdscript_basics.html#exports

For C#, there's only https://docs.godotengine.org/en/latest/getting_started/scripting/c_sharp/c_sharp_differences.html#export-keyword
It's not clear how to go from this to e.g. `[Export(PropertyHint.MultilineText)]` as @somnivore pointed out in that issue.

I don't know if this page should list *all* combinations, but it should maybe show some examples or the various syntaxes and link to the GDScript export docs for the comprehensive list (provided the information on the C# page is enough for users to do the conversion themselves).

**Comment by akien-mga** [comment]
CC @neikeq. It would also help knowing if things like godotengine/godot#24891 are bugs or just due to not using an undocumented feature.

**Comment by Calinou** [comment]
Now that we have a dedicated page for [GDScript exports](https://docs.godotengine.org/en/latest/getting_started/scripting/gdscript/gdscript_exports.html), should we have a dedicated page for C# exports?
