### ISSUE TITLE
Documentation changelog

### ISSUE THREAD

**Issue by eon-s** [godotengine/godot-docs#2199]
Would be good to have a brief changelog for the documentation when a minor version changes, with a list of the new sections at least.

This way, the community can be aware of the new content to read and to help others, do some revisions and organize translation efforts.

**Comment by clayjohn** [comment]
This is a great idea! It'll go a long way to show people that we are making progress.

**Comment by clayjohn** [comment]
For a start, 38 brand new tutorials, this list doesnt include the countless improvements, fixes and updates that the tutorials have received, nor does it cover the class reference.

**Step-by-step:**
- [Signals](http://docs.godotengine.org/en/latest/getting_started/step_by_step/signals.html)
- [Exporting](http://docs.godotengine.org/en/latest/getting_started/step_by_step/exporting.html)

**Project Workflow:**
- [Best practices](http://docs.godotengine.org/en/latest/getting_started/workflow/best_practices/index.html) (Ten part series)

**2D:**
- [2D lights and shadows](http://docs.godotengine.org/en/latest/tutorials/2d/2d_lights_and_shadows.html)
- [2D meshes](http://docs.godotengine.org/en/latest/tutorials/2d/2d_meshes.html)

**3D:**
- [CSG](http://docs.godotengine.org/en/latest/tutorials/3d/csg_tools.html)
- [Animating thousands of objects](http://docs.godotengine.org/en/latest/tutorials/3d/vertex_animation/index.html)

**Physics:**
- [Ragdoll system](http://docs.godotengine.org/en/latest/tutorials/physics/ragdoll_system.html)
- [Softbody](http://docs.godotengine.org/en/latest/tutorials/physics/soft_body.html)

**Animation:**
- [2D skeletons](http://docs.godotengine.org/en/latest/tutorials/animation/2d_skeletons.html)
- [AnimationTree](http://docs.godotengine.org/en/latest/tutorials/animation/animation_tree.html)

**Viewports:**
- [Using a Viewport as a texture](http://docs.godotengine.org/en/latest/tutorials/viewports/using_viewport_as_texture.html)
- [Custom post-processing](http://docs.godotengine.org/en/latest/tutorials/viewports/custom_postprocessing.html)

**Shading:**
- [Shading Reference](http://docs.godotengine.org/en/latest/tutorials/shading/shading_reference/index.html)
- [Intro to shaders: 2D and 3D water](http://docs.godotengine.org/en/latest/tutorials/shading/intro_to_shaders_water_workshop.html) (7 video tutorials)
- [Migrating to Godot’s shading language](http://docs.godotengine.org/en/latest/tutorials/shading/migrating_to_godot_shader_language.html)
- [Vertex displacement with shaders](http://docs.godotengine.org/en/latest/tutorials/shading/vertex_displacement_with_shaders.html)
- [Advanced post-processing](http://docs.godotengine.org/en/latest/tutorials/shading/advanced_postprocessing.html)

**VR:**
- [VR starter tutorial](http://docs.godotengine.org/en/latest/tutorials/vr/vr_starter_tutorial.html)

**Platform-specific:**
- [Customizing the Web export HTML page](http://docs.godotengine.org/en/latest/tutorials/platform/customizing_html5_shell.html)

**Multi-threading:**
- [Thread safe APIs](http://docs.godotengine.org/en/latest/tutorials/threads/thread_safe_apis.html)

**Miscellaneous:**
- [Fixing jitter and stutter](http://docs.godotengine.org/en/latest/tutorials/misc/jitter_stutter.html)
- [Running code in the editor](http://docs.godotengine.org/en/latest/tutorials/misc/running_code_in_the_editor.html)
- [Change scenes manually](http://docs.godotengine.org/en/latest/tutorials/misc/change_scenes_manually.html)

**Compiling:**
- [Optimizing a build for size](http://docs.godotengine.org/en/latest/development/compiling/optimizing_for_size.html)
- [Compiling with script encryption key](http://docs.godotengine.org/en/latest/development/compiling/compiling_with_script_encryption_key.html)

**Engine development:**
- [Binding to external libraries](http://docs.godotengine.org/en/latest/development/cpp/binding_to_external_libraries.html)

**Creating 3D content:**
- [Making trees](http://docs.godotengine.org/en/latest/content/3d/making_trees.html)

**Comment by eon-s** [comment]
Looks good, thanks for adding it :D  
https://docs.godotengine.org/en/3.1/about/docs_changelog.html
