### ISSUE TITLE
VideoPlayer documentation out of date

### ISSUE THREAD

**Issue by shawkes** [godotengine/godot-docs#2202]
VideoPlayer documentation states:
>The only format accepted is the OGV Theora, so any other format must be converted before using in a project.

But webm is supported (vp8 and vp9) to the best of my knowledge. Maybe others are supported too? I could only find the issue for webm. No clue on the supported audio codecs for the webm container (vorbis and ??).

I'm not sure what needs to be added, hence creating an issue rather than fixing it.

**Comment by skyace65** [comment]
This seems to have been fixed a while ago by this PR [https://github.com/godotengine/godot/pull/19067](url). You can close this issue.
