### ISSUE TITLE
Improve GDScript builtin types documentation

### ISSUE THREAD

**Issue by akien-mga** [godotengine/godot-docs#2204]
The current documentation for built-in types is quite terse: http://docs.godotengine.org/en/latest/getting_started/scripting/gdscript/gdscript_basics.html#built-in-types

While it's good that this page is not too heavy with examples and details, it should still detail stuff like that `int` are signed 64-bit integers, and thus taking values in [-2^63, 2^63-1] (see godotengine/godot#26113). Same for float, etc.

**Comment by NathanLovato** [comment]
It seems the info is now present: https://docs.godotengine.org/en/latest/getting_started/scripting/gdscript/gdscript_basics.html#built-in-types

Closing for now, please reopen if the issue still applies.
