### ISSUE TITLE
Duplicate paragraph in the Godot documentation

### ISSUE THREAD

**Issue by rogeriodec** [godotengine/godot-docs#2226]
I saw a duplicate paragraph in the Godot pt_BR documentation.
However, I do not see any Weblate option to delete this duplicate paragraph.

Here it is (https://docs.godotengine.org/pt_BR/latest/getting_started/editor/unity_to_godot.html): 

> Observamos anteriormente que não há solução perfeita para definir uma arquitetura de projeto. Qualquer solução funcionará para a Unity e Godot, então este ponto tem uma importância menor.
> 
> Observamos anteriormente que não há solução perfeita para definir uma arquitetura de projeto. Qualquer solução funcionará para a Unity e a Godot, então este ponto tem uma importância menor.

**Comment by akien-mga** [comment]
That's not a duplicate paragraph, but an incorrect translation: https://hosted.weblate.org/translate/godot-engine/godot-docs/pt_BR/?checksum=98be25725fd2622d
