### ISSUE TITLE
Should internal groups be documented?

### ISSUE THREAD

**Issue by CowThing** [godotengine/godot-docs#2230]
For example `Camera2D` nodes will call the function `_camera_moved(xform, screen_offset)` on every node that is in the camera's group. You can connect to it in GDScript like this:

```GDScript
extends Sprite

var group = ""

func _notification(what: int) -> void:
	match what:
		NOTIFICATION_ENTER_TREE:
			group = "__cameras_" + str(get_viewport().get_viewport_rid().get_id())
			add_to_group(group)
		
		NOTIFICATION_EXIT_TREE:
			remove_from_group(group)


func _camera_moved(xform, screen_offset):
	position = (screen_offset - xform.origin) / xform.get_scale()
```

But there's no documentation that describes this, the only way to know it exists is to look at the source code. I don't know what other nodes do this, or if this should even be something that should be used.

**Comment by zacryol** [comment]
Perhaps document these internal groups more in-depth within the "contributing to/understanding engine source" sections, and at least mention them in the main Groups page.

Just a quick snippet regarding `get_groups()` that says "Hey, the engine uses some groups internally as well, so `get_groups()` will likely return more than just what you added this Node to yourself."
