### ISSUE TITLE
Explain the difference between trimesh and convex body

### ISSUE THREAD

**Issue by rcorre** [godotengine/godot-docs#2232]
The `MeshInstance` menu has these options:

- Create trimesh static body
- Create convex static body
- Create trimesh collision sibling
- Create convex collision sibling

What do trimesh and convex mean in this context?
How should I choose one or the other?
Is one more precise and one more performant?

**Comment by clayjohn** [comment]
A trimesh is going to follow closer to your original mesh. Including concave sections. While a convex static body is going to encapsulate the exterior of the mesh, but will flatten out concave sections. 

[here](http://webee.technion.ac.il/control//info/Projects/Students/2013/David%20Shalom%20and%20Guy%20Greenhouse/WWW/clip_image009.jpg) is a useful image demonstrating the difference. 

Your right, this should be documented somewhere.

**Comment by rcorre** [comment]
Wow, looking back on this 18 months later like "did I really not know that?" :laughing:
