### ISSUE TITLE
Document how to use MultiMesh

### ISSUE THREAD

**Issue by hidemat** [godotengine/godot-docs#2240]
I successfully created a quad using SurfaceTool and MeshInstance. But MultiMesh states that it's a high performance mesh for when you have thousands of meshInstances. However, I have no clue how to build, for example, a quad using MultiMesh.

**Comment by clayjohn** [comment]
Take a look at this tutorial which uses multimeshes to draw thousands of meshes http://docs.godotengine.org/en/latest/tutorials/3d/vertex_animation/animating_thousands_of_fish.html

**Comment by hidemat** [comment]
Ah thank you. I will look, into it. I'm sure that is exactly what I need.

**Comment by groud** [comment]
Note that Github is not the place to ask for questions about how to use the engine, but to report bugs and ask for new features.
Please use the other community channels next time ;)

**Comment by hidemat** [comment]
Right. Sorry that's what I meant to do. To suggest a more detailed explanation of how to implement MultiMesh and MultiMeshInstance in the docs.

**Comment by groud** [comment]
Ok, changing the title then. :)

**Comment by clayjohn** [comment]
You are asking for an even more in-depth tutorial than the one that already exists?

**Comment by hidemat** [comment]
Well not the more than the one you shared. I'm referring to the "class reference" in the editor. When you get to the section within MultiMesh that points to a tutorial, none are referenced. So for a total noob like myself, I thought there were no tutorials. So I clicked on the link to suggest one, and here is where I ended up. :)

**Comment by clayjohn** [comment]
That's completely understandable! It should be linked. 

I have actually been meaning to do that for awhile. The link-to-tutorial section is actually fairly new and so it is not super filled out yet.

**Comment by hidemat** [comment]
Gotcha. Sorry not sure how much I'm supposed to write here, but I appreciate your help and your efforts, and have learned how to use MultiMesh. So thank you very much. I'll stop bugging ya XD.

**Comment by clayjohn** [comment]
No problem! Thanks for making a note of this!

**Comment by clayjohn** [comment]
@akien-mga this can be closed now.
