### ISSUE TITLE
"Step by Step" > "Signals" > "Shooting example" is confusing

### ISSUE THREAD

**Issue by eureton** [godotengine/godot-docs#2247]
This section mentions a `Player` multiple times. However, no such thing has been introduced in the guide so far (neither in **Signals**, nor further up).

A `Bullet` scene is also mentioned and referenced in the code without having first been introduced.

These confuse the reader. The **Signals** section will benefit if it:
- either precedes **Shooting example** by a presentation of `Player` and `Bullet`
- or removes **Shooting example** altogether

**Comment by cbscribe** [comment]
This tutorial is intended to show the use of signals, not how to build a full project. As it says at the beginning of this section:

> As another example of signal usage, let’s consider a player character that can rotate and shoot towards the mouse. Every time the mouse button is clicked, we create an instance of the bullet at the player’s location. See Instancing for details.

Assuming you have a player that shoots bullets, this shows how to use signals to handle that. A tutorial on signals shouldn't need to explain movement or instancing - there are already other tutorials for that.

If anything, this document should have more examples like this demonstrating various signal use cases.

Maybe there should be a link at the beginning to the movement tutorial as well as the instancing one? Or maybe a change in the order? I like having signals presented fairly early, and they're going to be used in the "Dodge the Creeps", so introducing them to the reader is good. What about splitting into "Signals" and "More Signals" sections?

**Comment by eureton** [comment]
> Assuming you have a player that shoots bullets, this shows how to use signals to handle that.

I agree, it does. My point here is not to argue the _what_, but the _how_. As a first-time reader, I found the section confusing and jarring, that's all. Jarring because all previous sections in the Step-by-step guide had been nice and smooth.

> A tutorial on signals shouldn't need to explain movement or instancing - there are already other tutorials for that.

Right. However, those tutorials are further down in the index and not linked.

> Maybe there should be a link at the beginning to the movement tutorial as well as the instancing one?

Yes, that would definitely improve the experience! :+1:
Also, I think **Shooting example** deserves a section of its own.

**Comment by eureton** [comment]
@cbscribe It's not clear to me how I should proceed from here.

Should I let this issue remain open in the pipeline?
Should I submit a PR with my suggestions above?
Something else entirely?

**Comment by cbscribe** [comment]
I was thinking about your suggestion to move it to its own section. I'd be happy to do that, I just have a couple other things on my plate to take care of first.
