### ISSUE TITLE
Create a page about godot and version control

### ISSUE THREAD

**Issue by Scony** [godotengine/godot-docs#2263]
There should be a doc page explaining what should be stored in VCS (e.g. git) and what should be ignored

**Comment by clayjohn** [comment]
Do you have anything in mind in particular? 

I tend to include everything from my project folder in git. But to me this seems like a very project-dependant choice. I dont have a lot of heavy art assets so it works out okay.

**Comment by Scony** [comment]
Today I've learned that `.import/` dir is not necessary, but for example `*.import` files are crucial. And this is just one example, I suspect there is much more.

**Comment by clayjohn** [comment]
That point in particular is mentioned in the import process doc https://docs.godotengine.org/en/latest/getting_started/workflow/assets/import_process.html

If you stumble on any others please make note of them. If we can find enough it would be worthwhile to make a doc. As it is right now im not sure that there is enough content to make a doc useful. 

That's just my perspective, i wont let that stand in the way if someone puts a doc together.

**Comment by Scony** [comment]
Okay, if I find something more, I'll reopen. If not, maybe I'll provide MR in my spare time.

**Comment by aaronfranke** [comment]
@Scony For reference, this is what should be ignored: https://github.com/github/gitignore/blob/master/Godot.gitignore
