### ISSUE TITLE
Update AnimationPlayer docs to 3.1

### ISSUE THREAD

**Issue by golddotasksquestions** [godotengine/godot-docs#2266]
The new AnimationPlayer changed it's UI/UX drastically yet the 3.1 docs still explain the 3.0 Animation Player. https://docs.godotengine.org/en/3.1/getting_started/step_by_step/animations.html
https://docs.godotengine.org/en/latest/getting_started/step_by_step/animations.html

**Comment by cbscribe** [comment]
Fixed in #2267
