### ISSUE TITLE
binary serializer - documentation flaw

### ISSUE THREAD

**Issue by Marqin** [godotengine/godot-docs#227]
Godot is made to work not only on PC. This means it could get compiled&run on platforms that have 8 byte integers and 64 bit floats. What will happen then to [binary serializer](http://docs.godotengine.org/en/latest/reference/binary_serialization_api.html)?

Will it crop bytes? Or will it produce & send via network something bigger and not documented here?

**Comment by akien-mga** [comment]
No idea, cc @reduz

**Comment by mhilbrunner** [comment]
cc @reduz

**Comment by hungrymonkey** [comment]
https://github.com/godotengine/godot/blob/master/core/io/marshalls.h

https://github.com/godotengine/godot/blob/master/core/io/marshalls.cpp

io/marshall have support for 8 byte or 64 bit int.

**Comment by hungrymonkey** [comment]
https://github.com/godotengine/godot/blob/master/core/io/marshalls.cpp#L873

https://github.com/godotengine/godot/blob/master/core/io/marshalls.cpp#L137

https://github.com/godotengine/godot/blob/master/core/io/marshalls.cpp#L87

https://github.com/godotengine/godot/blob/master/core/io/marshalls.cpp#L829

https://github.com/godotengine/godot/blob/master/core/io/stream_peer.cpp#L217

from the looks of it, the 64 bit is detected properly

**Comment by Calinou** [comment]
Closing, as this is not an issue strictly related to documentation. Also, this appears to be fixed since Godot 3.0 at least according to @hungrymonkey.
