### ISSUE TITLE
Arrays

### ISSUE THREAD

**Issue by wakadoodle** [godotengine/godot-docs#2270]
Hi I have a problem with arrays I know what an array is but I do not know how to use or make an array. especially when I have to make a Simon game where the pattern needs to stay the same and increase each time you do the previous pattern correctly please help!

**Comment by cbscribe** [comment]
This is not a tech support site, it's for reporting and discussing issues with the Godot documentation. If the docs are not helping you:
https://docs.godotengine.org/en/latest/getting_started/scripting/gdscript/gdscript_basics.html#array

You can try one of the following:
* Q&A site: https://godotengine.org/qa
* Discord: https://discord.gg/zH7NUgz
* Subreddit: https://reddit.com/r/godot
