### ISSUE TITLE
Emulate Touchscreen is moved to Input Devices section

### ISSUE THREAD

**Issue by volzhs** [godotengine/godot-docs#2275]
https://docs.godotengine.org/en/3.1/getting_started/step_by_step/exporting.html

> The first step is to open “Project Settings” and find the Handheld section. Enable the Emulate Touchscreen option.

![Screenshot_20190322_002715](https://user-images.githubusercontent.com/8281454/54764463-30fa4400-4c3b-11e9-9e4a-d08027c94210.png)

**Comment by cbscribe** [comment]
Fixed in #2285
