### ISSUE TITLE
State machine tutorial 

### ISSUE THREAD

**Issue by Feniks-Gaming** [godotengine/godot-docs#2283]
Godot version:
3.1

OS/device including version:
Windows 10 but any

Issue description:
I would like to request doc tutorial on implementation of finite state machine in Godot games. I struggle to find any written guides on this subject and only found videos. I think finite state machines are such a common feature in games that the way to implement them should be described in the docs.

Steps to reproduce:
N/A

Minimal reproduction project:
N/A

**Comment by oldmerkum** [comment]
There is a demo project for this that I found helpful:
[godot 2d state machine demo](https://github.com/godotengine/godot-demo-projects/tree/master/2d/finite_state_machine
)
It took quite a bit of time for me to understand how their code worked, so make sure to parse it carefully.

**Comment by NathanLovato** [comment]
Closing as there's a page on this topic in the docs now: https://docs.godotengine.org/en/latest/tutorials/misc/state_design_pattern.html
