### ISSUE TITLE
Create docs that link to external tutorials

### ISSUE THREAD

**Issue by bugmenot2** [godotengine/godot-docs#229]
There are external tutorials on how to use Godot Engine, maybe a doc page that links to them could be useful.

External resources:
[http://godot-engine.zeef.com/andre.antonio.schmitz](url) (collection of tutorials)
[http://www.gamefromscratch.com/page/Godot-Game-Engine-tutorial-series.aspx](url)

**Comment by StraToN** [comment]
Documentation refactoring is currently in progress and will feature a "Community" category. It may eventually contain a page for external tutorials.

**Comment by bugmenot2** [comment]
Ok, thanks. By the way, how is it possible to give a hand with documentation?

**Comment by StraToN** [comment]
Have a look at the Contributing section of the current RTD documentation : http://docs.godotengine.org/en/latest/contributing/_contributing.html 😉

**Comment by bugmenot2** [comment]
Thanks

**Comment by mhilbrunner** [comment]
This was done in the mean time, the community section now has pages with links to third-party community resources and tutorials.
