### ISSUE TITLE
Problem while save scene

### ISSUE THREAD

**Issue by AkaRyu** [godotengine/godot-docs#2293]
So, i've got this : 
```gdscript
save_game.open("user://savegame.save", File.READ)
while not save_game.eof_reached():
        var current_line = parse_json(save_game.get_line())
        # Firstly, we need to create the object and add it to the tree and set its position.
        var new_object = load(current_line["filename"]).instance()
        get_node(current_line["parent"]).add_child(new_object)
        new_object.transform.origin= Vector3(current_line["transformx"], current_line["transformy"],current_line["transformz"])
```
And i got this error: Invalid get Index 'filename' (on base:'Nil')

Can someone explain me how to solve it and why this happen? ^^

Thanks 👍 !

**Comment by bojidar-bg** [comment]
Can't say for sure, but it seems like `current_line` ends up `== null`, probably because the contents of that line were not valid JSON -- for example because the line was empty.

**Comment by AkaRyu** [comment]
That was a stupid error x')

**Comment by bojidar-bg** [comment]
@AkaRyu I would suggest explaining what the error was, unless it is too specific to your game. That way, other users who stumble across this GH issue might be able to apply a similar solution to their problems.
