### ISSUE TITLE
update SHADOW_COLOR uniform description

### ISSUE THREAD

**Issue by TheDuriel** [godotengine/godot-docs#2296]
https://docs.godotengine.org/en/3.1/tutorials/shading/shading_reference/canvas_item_shader.html#light-built-ins

This is actually implemented and works. It's questionable if it works the way it is meant to, but it is still useful in its current form.

**Comment by clayjohn** [comment]
It appears it works exactly as it should. It sets the color of the shadow cast by a light. I have made a PR to remove the qualifier.

**Comment by Chaosus** [comment]
Closed via #2301
