### ISSUE TITLE
Folders/naming convention for organizing images

### ISSUE THREAD

**Issue by rolfpancake** [godotengine/godot-docs#23]
# What

The img-folder looks like a cluttered depot of unsorted images.
What about a simple folder structure (like creating a folder for each doc-page) or naming convention (docpage_ham_and_eggs.png)?
## Pro
- If an image is outdated, it can be found and replaced very fast (without the need to search the images title at first)
- If a page is deleted the corresponding folder can be deleted as well (no gathering all included images)
- If someone wants to add an image with an existing name (which seems to be _not that_ unlikely) it has to be renamed at first to not override another (just annoying)
## Con

I know this would take much editing (every file, that uses images plus the renaming/resorting of images itself) and has no huge effect. But it could be done step by step and would be an improvement in the long run.

**Comment by akien-mga** [comment]
I had thought about this too, but there are issues with putting the doc file name in the image file name, or making folders for each page:
- if you rename a doc page, the convention is broken, so either you rename the images too, or the repo starts being inconsistent
- same thing if you move the doc page around
- it makes sharing images harder: there are images that could be used in more than one page, and thus what page should "own" them?

On the other hand I agree that the /img folder might look (and will clearly grow to become) very cluttered, and we might indeed get file name conflicts after a while.

What I'd tend towards would be to keep the current system (everything in /img directly, it also makes it easier for contributors to understand where they should put their files), but rename them to more descriptive names. It should not necessarily contain the doc page name, but have a name that tells well what it's about, so that it can be better reused in other pages.

Then we could very easily write a bash script that parses all .rst files and outputs a list of pages and images that they rely on, to be able to track the dependencies in a visual way.

**Comment by StraToN** [comment]
What about an img/shared/ folder in which we move images that are displayed in at least 2 pages?

**Comment by akien-mga** [comment]
> What about an img/shared/ folder in which we move images that are displayed in at least 2 pages?

The problem with this is that it's not future-proof:
- if an image was using in only one tutorial, but then a contributor wants to reuse it in a new tutorial, should it be moved to /img/shared?
- respectively, if an image was shared but the removed from the 2nd tutorial that used it, should it be moved out of /img/shared?

Basically, when using git, we should try to limit as much as possible the usage of ``git mv``. Moving a file makes its history much harder to read (at least on GitHub, where it will just show as first commit in the history the last commit where the file was renamed).

On the other hand, even if it makes the history harder to read, we might end up moving doc files around a bit as the documentation continues growing and the categories evolve. But if all these movements can be made independently of the /img folder (and /files too btw), that's really for the best.

**Comment by StraToN** [comment]
@akien-mga That was just an idea.
My opinion goes to keeping the cluttered img/ folder.
The main reason, IMO, is that anyway, commits will only add new images that belong to these commits, and *.rst files with them. Thus, it'll be easy to know which images were pushed with which *.rst file. 

We are not supposed to sort or move images after they were pushed. It is thus necessary (and much easier as this will eventually happen only once) to name images with a proper name that does NOT link to a *.rst file.

**Comment by akien-mga** [comment]
I generally agree. We should probably try to decide on a naming convention for the files anyway to keep some consistency, and maybe try to rename the existing files accordingly, and document it in the doc writing guidelines. See e.g. the first files with a numbered prefix, the files in the middle with random content-based names, and the files at the end all named "tutosthg{1,2,3..}": https://github.com/godotengine/godot-docs/tree/master/img

I'm also just throwing ideas, I don't have a clear opinion of what *should* be done yet :)

**Comment by rolfpancake** [comment]
I see, I did not elaborate my point well enough. Thanks for the wisdom. Lessons learned :)
The naming convention seems to be a good solution when combined with 'put an image into the img folder and never move it elsewhere' and 'never rename an image'.

I start throwing ideas for a naming convention:

- no upper-case letters
- use only a-z, 0-9 and _ as delimiter (use - as delimiter for word combinations?)
- no numbering (001_abc, 002_abc etc.)
- try to keep the name short (abbreviations?)
- use meaningful descriptions

I would like to kind of categorize images. Not depending on the page where they will be placed but rather depending on what is shown. Therefore 'tags' could be suggested like:

- `gui_` (for screenshots of the godot gui)
- `app_` (for screenshots of games/apps)
- `structure_` (for visualization of foldertrees, datasets, inheritence etc.)
- `gdscript_` (for pictures of gd-scripts)

What also comes to my mind:
- What about filetypes, resolutions and filesizes? Always use png? Keep it as small as possible or should it be 'retina ready'?
- What about using animated gifs e.g. for showing menu actions in tutorials?
    - Therefore a `menu_` and `anim_` tag could be useful as well

**Comment by mhilbrunner** [comment]
At least there are per-folder `img/` folders for the docs now.

**Comment by StraToN** [comment]
Pinging @NathanLovato for his opinion on the subject.
Should we define image naming conventions?

**Comment by mhilbrunner** [comment]
IMO, it currently isn't a large problem (yet). Priority should first be to get near a number of images that this problem actually becomes one, and to get docs updated as much as possible for 3.0.

I'd delay any work on this to after 3.0 is relased

**Comment by akien-mga** [comment]
I'd say this has been fixed when we moved images to relative paths (`img/` folders in the same folder as the doc files).
