### ISSUE TITLE
Implement auto-translation

### ISSUE THREAD

**Issue by rogeriodec** [godotengine/godot-docs#2307]
Currently, the automatic machine translation is so advanced that virtually all of the text is being translated perfectly (at least to Portuguese).
Although I read English, sometimes when I want to be faster, I translate with the right mouse button in Chrome.
Therefore, I believe that inserting a button for machine translation (such as [this](http://free-website-translation.com/), for example, ) at the top of the documentation pages could be quite satisfying for most users.
This eliminates virtually all the waiting for someone to do an official translation (besides helping in the official translation).

**Comment by akien-mga** [comment]
We already have a good amount of documentation in pt_BR BTW: http://docs.godotengine.org/pt_BR/latest/
