### ISSUE TITLE
New features in Godot 3.1 video tutorial series

### ISSUE THREAD

**Issue by NathanLovato** [godotengine/godot-docs#2308]
We are working on a Free tutorial series for the GDquest channel and the official docs dedicated to the new features in Godot 3.1 (with a few bonus tutorials). We're planning 25-30 tutorials.

By Free, I mean that the tutorials themselves are copyleft. We will release them all on our channel, but also e.g. as torrent, so you can download them from the manual and watch them offline, share them with students, etc.

You can see our progress in our project board: https://github.com/orgs/GDquest/projects/1

I'll edit this post a bit later with a list of planned videos.
For now I'm just posting so you know we've already made 30% of the content and we're working on it with @guilhermehto, Pigdev, and @razcore-art.

**Comment by NathanLovato** [comment]
@akien-mga How would you like us to add the videos to the manual? Would you like to host the videos on one of your servers? May we start to release the individual videos on the channel as we make them, so before we put them up as torrent?

Any requests?

Also, if anyone has suggestions regarding distribution, that'd be most welcome. We don't have e.g. a peertube instance to allow anyone to stream them using a libre platform, but if somebody wants to host them on their instance, or to provide a server for Godot, we can put them up there as well.

**Comment by ZX-WT** [comment]
I think you miss the new 3D IK feature?

**Comment by NathanLovato** [comment]
@ZX-WT Thanks for the heads up, I added a task for it.

**Comment by NathanLovato** [comment]
We will start rolling out the tutorials on GDquest tomorrow. This way we can keep the channel going, and the Kickstarter backers can start to see that we're producing the content they funded.

And I'll be available to put them in the Godot docs anytime.

**Comment by Calinou** [comment]
@NathanLovato Should this be closed now that Godot 3.2 is out?

**Comment by NathanLovato** [comment]
Sure!
