### ISSUE TITLE
Documentation on exported arrays

### ISSUE THREAD

**Issue by Gnumaru** [godotengine/godot-docs#2310]
On the folowing page

https://docs.godotengine.org/en/3.1/getting_started/scripting/gdscript/gdscript_basics.html

The docs for 3.1 say that exported arrays are shared between all instances. Here's an excerpt from the page: "Exporting arrays works, but with an important caveat: While regular arrays are created local to every class instance, exported arrays are shared between all instances. This means that editing them in one instance will cause them to change in all other instances"

But upon testing this behaviour on godot 3.1 on windows x64, standard version, that's not what happens. If I use the folowing script to export an array...

<pre>
extends Node
export(Array) var arr : Array
func _ready():
	var astring = ''
	astring += name + ' '
	astring += str(arr.size()) + ' '
	for i in arr:
		astring += str(i) + ' '
	print(astring)
</pre>

attach it to two nodes and edit the values, the values for each node remain independent. And upon playing the scene, the printed values are diferent for each node. Thus the documentation must be updated to note that exported arrays work as with any exported variable, retaining an exclusive value for each instance instead of sharing the values as if it was some kind of static property

**Comment by Calinou** [comment]
Closing in favor of https://github.com/godotengine/godot-docs/issues/2909, which has more information about the issue at hand.
