### ISSUE TITLE
C# example mismatching GDScript example in your_first_game.rst

### ISSUE THREAD

**Issue by Sioma112233** [godotengine/godot-docs#2316]
Hey, I am currently reading [this tutorial](https://docs.godotengine.org/en/3.1/getting_started/step_by_step/your_first_game.html)
And there's an example there that wants to Disable a CollisionBody2D.
in GDScript it shows:
``` gdscript
$CollisionShape2D.call_deferred("set_disabled", true)
```
which I've noticed was recently changed (in master) to 
``` gdscript
$CollisionShape2D.set_deferred("disabled", true)
```
this is while the C# example is:
``` cs
GetNode<CollisionShape2D>("CollisionShape2D").Disabled = true;
```

The tutorial also mentions the following:
>> Disabling the area’s collision shape can cause an error if it happens in the middle of the engine’s collision processing. Using call_deferred() allows us to have Godot wait to disable the shape until it’s safe to do so.

and yet it's not done in the C# example.
is it on purpose? I am new to the engine but I've noticed there's CallDefered/SetDefered methods available to us in C#, yet when I tried to use `SetDefered` it didn't work with the C# property name but did work with the GDScript property name (same name but GDScript's starts with lowercase)

so few things:
1. if it's a mistake and the C# example need fixing I can gladly do the change
    if not, maybe add some note that in C# it's not necessary
2. is it a bug that `SetDefered` expects the GDScript property name instead of the C#'s property name?

**Comment by clayjohn** [comment]
Seems to have just be changed here https://github.com/godotengine/godot-docs/commit/d6246b8382e43ad9c57ecfeada153810cff26796

@Ursus-Z

**Comment by Ursus-Z** [comment]
Hi!

The original GDScript code for 3.0 was $CollisionShape2D.disabled = true.

This was changed for 3.1 to $CollisionShaped2D.**call_deferred**.

I recently changed this to **set_deferred**, but I didn't update the C# code as I'm not sure about the proper syntax.  Sorry, I should have mentioned that in my PR.

I'm assuming it would apply to C#, too. Any thoughts, @akien-mga or @cbscribe ? 

If it needs changed, would you mind updating the C# code? ;)

**Comment by Sioma112233** [comment]
closing, as I see it was fixed after another issue was opened about this #2358
