### ISSUE TITLE
Problem with Requests

### ISSUE THREAD

**Issue by AkaRyu** [godotengine/godot-docs#2324]
Hi, i have done this : 

`func _ready():
    _make_post_request("https://gist.githubusercontent.com/AkaRyu/9c0e4c5bf1f1593ce49f70b100b43d8d/raw/","{Niveaux:{01:{Auteur:Template, FileSave:{Block:[[res://Scene/IceLand/IceHole.tscn, -2, 3.4, -1.5, IceHole, /root/Editor], [res://Scene/CastleSand/CastleSandDontTouch.tscn, -2.5, 4.4, -1.5, DontTouch, /root/Editor]]}},}}",false)
    pass

func _make_post_request(url, data_to_send, use_ssl):
    # Convert data to json string:
    var query = JSON.print(data_to_send)
    # Add 'Content-Type' header:
    var headerr="Authorization:"
    headerr+=token
    var headers = [headerr]
    $HTTPRequest.request(url, headers, use_ssl, HTTPClient.METHOD_POST, query)
    

`
Can someone tell me  why this doesn't work? ^^ The value of the gist doesn't change

**Comment by akien-mga** [comment]
This GitHub repository is for issues with the documentation, not for support requests.

Please use other [community platforms](https://godotengine.org/community) for that, such as the Q&A: https://godotengine.org/qa
