### ISSUE TITLE
Plane constructor needs more information

### ISSUE THREAD

**Issue by mistermashu** [godotengine/godot-docs#2327]
On the `Plane` documentation page, the sentence `Creates a plane from the four parameters “a”, “b”, “c” and “d”.` means nothing to people who don't know what `a`, `b`, `c`, and `d` are. It should elaborate a little so I can understand what it means and how to use it.

**Comment by Calinou** [comment]
[This seems to have been better documented a while ago](https://docs.godotengine.org/en/latest/classes/class_plane.html#method-descriptions), closing.
