### ISSUE TITLE
Default value typo in Getting Started > Instancing tutorial

### ISSUE THREAD

**Issue by Calebm90** [godotengine/godot-docs#2329]
After you've created your Physics Material and set the Bounce value to 1, the tutorial asks you to set the value back to 0.5 - it should be set to 0.05 to return the original functionality of the ball.

**Comment by bitbutter** [comment]
The default bounce value seems to be 0. Shouldn't it be set back to 0 to return the original bounciness?

**Comment by Calebm90** [comment]
Just checked and it does seem to be a default value of 0, so the correction should be 0 instead of 0.05.  The current value of 0.5 adds too much bounce to the ball and it was a bit confusing trying to figure out why.

**Comment by akien-mga** [comment]
See #2459, there are many issues in this section and it would be better to simply remove it/replace it by something more friendly to new users.

**Comment by pycbouh** [comment]
As the initial issue was fixed in #2380 and #2459 seems to supersede this on a bigger scope, shouldn't this be closed?

**Comment by akien-mga** [comment]
Indeed, thanks.
