### ISSUE TITLE
Add a more in-depth review of what is involved in console ports.

### ISSUE THREAD

**Issue by willnationsdev** [godotengine/godot-docs#2330]
Based on Reddit comments:

[reduz giving commentary on people's confusion in /r/godot](https://www.reddit.com/r/godot/comments/b7w7f2/we_are_becoming_stronger/ejvp1l0/):

> It really puzzles me how people misunderstands console support. There is no engine on the planet you can download and export to consoles out of the box.
> Maybe Unity and Unreal did fantastic marketing, but reality is that you need to get licensed to be able to export to consoles (which is not easy). Those engines are also not free on consoles, and you will get revenue share or have to pay upfront.
> If you manage to get licensed (which is very difficult) You also have to pay for the devkits which are really expensive.
> And lastly, no matter the engine, you need to comply with a lot of technical and legal requirements to be able to publish the game.
> Even most indies resort to third party companies to port their games to consoles because of this, it's not just an "export and runs". You can already find such companies for Godot, so saying that there is no "Console" support is very naive.

[Someone in /r/gamedev not satisfied with that response](https://www.reddit.com/r/gamedev/comments/b9exan/gamemaker_studio_2_will_support_methods/ek500ec/):

> I don’t buy this.
> The issue isn’t that you can’t press a button and have your game appear on a console. It’s that there is no clear path for getting your game running a console, on a technical level, as an indie dev. Devs generally understand that you need to do extra work to get the game running on different hardware, including all the licensing stuff.
> I previously emailed the company listed on the Godot website, enquiring about products or services they could offer an indie dev for porting to consoles and I didn’t get a response.
> Other open source projects, such a Haxe and Monogame at least give indications about their console support, who to contact, and insights about what to expect of the process for getting your game running on a console. Godot on the other hand has a vague stance on their console support. This isn’t helpful to me when I am trying to evaluate engines, since I have specific platforms in mind from the beginning and I need to rule out engines that aren’t capable of delivering the kind of console support I need.

I've encountered many people who feel like our documentation could do a better job of explaining what steps are actually involved in porting to console, either through interacting with Lone Wolf Technologies or forming a relationship with a platform publisher on one's own in order to join the ranks of companies *like* LWT. If LWT doesn't always respond, are there reasons for that?

There just seems to be too much ambiguity in what we have there at this moment, given the number of people I hear asking these same questions over the last couple years. Thoughts?

**Comment by Calinou** [comment]
> If LWT doesn't always respond, are there reasons for that?

Companies delivering expensive services tend to not bother with smaller indies who may not have the budget to pay upfront. I'm not sure much can be done about that :slightly_smiling_face: 

How much public information can we obtain about the console publishing process? I'm afraid asking LWT or Pineapple Works directly may prove difficult, since they are both under console NDAs.

**Comment by akien-mga** [comment]
> How much public information can we obtain about the console publishing process? I'm afraid asking LWT or Pineapple Works directly may prove difficult, since they are both under console NDAs.

Well it's up for them to decide what they can or can't say, you're free to ask.

**Comment by Cevantime** [comment]
I'm not sure if this should be mentionned here but the link the Lone Wolf Technology website is dead. Is this company still active ? There isn't much reference to it on the web.

**Comment by Calinou** [comment]
- Implemented by https://github.com/godotengine/godot-docs/issues/3516. See also [Godot and consoles, all you need to know](https://godotengine.org/article/godot-consoles-all-you-need-know/).
