### ISSUE TITLE
3.1 link broken

### ISSUE THREAD

**Issue by rogeriodec** [godotengine/godot-docs#2332]
When clicking when the 3.1 link for this page https://docs.godotengine.org/en/3.0/tutorials/3d/working_with_3d_skeletons.html it points to this page https://docs.godotengine.org/en/3.1/tutorials/3d/working_with_3d_skeletons.html, which is redirected to https://docs.godotengine.org/en/3.1/community/tutorials/3d/working_with_3d_skeletons.html, but this link is not working.

**Comment by akien-mga** [comment]
This page was removed from 3.1 and latest documentation, so it's normal that it can't be found.

But it's weird that it gives a redirection issue instead of 404.

**Comment by NathanLovato** [comment]
I'll close if you don't mind as the issue affects an "archived" version of Godot and the docs. I would imagine really few users still use 3.0. But let me know if we should still address the issue.
