### ISSUE TITLE
"Add Call Func Track" option does not exist in Godot 3.1

### ISSUE THREAD

**Issue by georgikoemdzhiev** [godotengine/godot-docs#2335]
The "Add Call Func Track" option does not exist in Godot 3.1. I am using Godot 3.1 stable and I was following the *FPS Tutorial* and I noticed that the "Add Call Func Track" option is nowhere to be found in the new Godot 3.1. The documentation should be updated so that it is aligned with the changes of Godot 3.1 (e.g. use "**Call Method Track**" instead of *Add Call Func Track*) .

**Comment by skyace65** [comment]
This was fixed by PR #2467. so this issue can be closed.
