### ISSUE TITLE
Double dashes are converted to long dashes

### ISSUE THREAD

**Issue by robgraeber** [godotengine/godot-docs#2336]
Double dashes are converted to long dashes across the docs.

For example: https://docs.godotengine.org/en/3.1/getting_started/editor/external_editor.html

`--line {line} {file}` is rendered as: `–line {line} {file}`.

Looks like there is a sphinx setting to turn it off: http://www.sphinx-doc.org/en/master/usage/configuration.html#confval-smartquotes

**Comment by Calinou** [comment]
Is there a way to disable smart quotes on a per-file or per-folder basis? This way, we can leave it enabled in other pages.

**Comment by robgraeber** [comment]
I couldn’t see any easy way to have per-file configs, but from what I read the one-off fix is to either wrap double dashes strings in a code block like ```Enter the command ``command -abc --efg`` to do stuff.``` or escape it manually like ```Enter the command “command -abc -//-efg to do stuff.”```
