### ISSUE TITLE
Mistakes in 'Matrices and transforms'

### ISSUE THREAD

**Issue by ghost** [godotengine/godot-docs#236]
There are a few mistakes in the [Matrices and transforms](http://docs.godotengine.org/en/latest/tutorials/matrices_and_transforms.html) page. I've described the ones I saw below...

When explaining how to get the original coordinates from a transformed object, the docs say this:

> ``` gdscript
> var final_pos = x.dot(new_pos) + y.dot(new_pos)
> ```

This would mean `final_pos` is a scalar, not a vector. Instead, I think `Vector2( x.dot(new_pos), y.dot(new_pos) )` should be used.

There's also some inconsistency in spacing (either side of `=`) about halfway down, although this isn't really an issue:

> ``` gdscript
> m = m.rotated(PI/2) # rotate 90°
> m=m.translated( Vector2(2,0) )
> ```

Near the end, the docs say this:

> Because in matrix math, A + B is not the same as B + A.

and this:

> ``` gdscript
> # due to reverse order, parenthesis are needed
> var global_xform = gradparent_matrix + (parent_matrix + child_matrix)
> ```

In both cases, I think the `+` should be `*`, as A + B is identical to B + A, and adding matrices doesn't chain their transformations. As far as I know, the brackets aren't necessary either, it's just the order of the operands to `*` that matter. In other words, `A*B != B*A` but `A*(B*C) == (A*B)*C`.

Right at the end, there's a missing comment:

> ``` gdscript
> pos = t.origin + pos  (only translate)
> ```

(should be)

> ``` gdscript
> pos = t.origin + pos # (only translate)
> ```

**Comment by bojidar-bg** [comment]
Feel free to open a PR

**Comment by JuanNeedsToApologize** [comment]
Awww.. ArcFahuto or w/e. The guy that was nice as fuck in IRC but the godot community treated him like garbage, to the point he deleted his account.

Anyways, this is not priority at all, voting to close @bojidar-bg
