### ISSUE TITLE
Should the high dynamic range page be deleted?

### ISSUE THREAD

**Issue by skyace65** [godotengine/godot-docs#2364]
The bottom part of the [HDR page](https://docs.godotengine.org/en/3.1/tutorials/3d/high_dynamic_range.html) is outdated, and looks like it was made for Godot 2.0. All the settings for HDR in the environment node in Godot 3.0 and newer are well documented in the[ Environment and Post Processing page](https://docs.godotengine.org/en/3.1/tutorials/3d/environment_and_post_processing.html). So is there a reason to keep the rest of the page or should the whole thing be deleted?

**Comment by clayjohn** [comment]
Is the sRGB -> Linear stuff contained in other pages as well?

**Comment by skyace65** [comment]
@clayjohn The [importing images page](https://docs.godotengine.org/en/3.1/getting_started/workflow/assets/importing_images.html#srgb) has this on SRGB.

"Godot uses Linear colorspace when rendering 3D. Textures mapped to albedo or detail channels need to have this option turned on in order for colors to look correct. When set to “Detect” mode, the texture will be marked as SRGB when used in albedo channels."
