### ISSUE TITLE
Compiling for iOS is outdated

### ISSUE THREAD

**Issue by vnen** [godotengine/godot-docs#237]
It does not reflect the `isim`/`iphone` merge. It also has the binary name in the command, which should not be done.

**Comment by StraToN** [comment]
I'd be glad to edit this. Can you give me a hint on what needs to be written instead? I have no idea.
http://docs.godotengine.org/en/latest/development/compiling/compiling_for_ios.html

**Comment by akien-mga** [comment]
Fixed already by cc8c1d2, fd276ae and b9f1f65.
