### ISSUE TITLE
FPS tutorial Part 4 - Wrong Xbox joypad axis mapping under Linux Mint

### ISSUE THREAD

**Issue by xhokir** [godotengine/godot-docs#2374]
While following the [FPS tutorial Part 4](https://docs.godotengine.org/en/3.1/tutorials/3d/fps_tutorial/part_four.html), the proposed joypad axis input mapping for XBox controller was not the correct one for me, using Linux Mint 19. I got the behaviour correct by setting the following mapping for X11 OS:

- In `process_view_input(delta)` function:
```
if OS.get_name() == "Windows":
	joypad_vec = Vector2(Input.get_joy_axis(0, 2), Input.get_joy_axis(0, 3))
elif OS.get_name() == "X11":
	joypad_vec = Vector2(-Input.get_joy_axis(0, 2), Input.get_joy_axis(0, 3))
elif OS.get_name() == "OSX":
	joypad_vec = Vector2(Input.get_joy_axis(0, 3), Input.get_joy_axis(0, 4))
```
- In `process_input(delta)` function:
```
if OS.get_name() == "Windows":
	joypad_vec = Vector2(Input.get_joy_axis(0,0), -Input.get_joy_axis(0,1))
elif OS.get_name() == "X11":
	joypad_vec = Vector2(Input.get_joy_axis(0,0), -Input.get_joy_axis(0,1))
elif OS.get_name() == "OSX":
	joypad_vec = Vector2(Input.get_joy_axis(0,1), Input.get_joy_axis(0,2))
```

Edit : I am using Godot 3.1 stable x11.64

**Comment by Tornadowarnung** [comment]
I'm having similar issues on Pop!_OS 18.10 64-bit with a XBox 360 Controller.

For the left stick (`process_input(delta)` in the tutorial) I observe the same behavior as mentioned above:
```
if OS.get_name() == "Windows":
	 joypad_vec = Vector2(Input.get_joy_axis(0,0), -Input.get_joy_axis(0,1))
elif OS.get_name() == "X11":
	joypad_vec = Vector2(Input.get_joy_axis(0,0), -Input.get_joy_axis(0,1))
elif OS.get_name() == "OSX":
	joypad_vec = Vector2(Input.get_joy_axis(0,1), Input.get_joy_axis(0,2))
```

However for the right stick (`process_view_input(delta)` in the tutorial) I cannot seem to get any value for the stick moving to the left, no matter what axis I try. However with following code everything works as expected:

```
if OS.get_name() == "Windows":
	joypad_vec = Vector2(Input.get_joy_axis(0, 2), Input.get_joy_axis(0, 3))
elif OS.get_name() == "X11":
	joypad_vec = Vector2(Input.get_joy_axis(0, 6), Input.get_joy_axis(0, 2))
elif OS.get_name() == "OSX":
	joypad_vec = Vector2(Input.get_joy_axis(0, 3), Input.get_joy_axis(0, 4))
```

The joypad axis in the input map in the project settings yield the same result as above for me.

**Comment by Calinou** [comment]
This isn't a documentation issue, but a bug with some controllers not using correct axis mappings. See https://github.com/godotengine/godot/issues/35575.
