### ISSUE TITLE
Naming conventions case for files

### ISSUE THREAD

**Issue by clabe45** [godotengine/godot-docs#2376]
I would like to adhere to any existing conventions for file name casing. Currently, I can't find any specific file naming conventions in the docs. It feels ambiguous, because
* most tutorials use snake case, but
* I mostly see nodes using Pascal case, and by default, scenes are saved with their root node's name.

Should I use snake case, Pascal case, or does it even matter?

**Comment by bojidar-bg** [comment]
There is a [styleguide page](https://docs.godotengine.org/en/latest/getting_started/scripting/gdscript/gdscript_styleguide.html), though it is GDScript-only, and not for file and node naming.

**Comment by clabe45** [comment]
Yes, I can't find it there.

**Comment by KevMorelli** [comment]
This post has the answer for file naming conventions, I can't find anything for nodes

https://godotengine.org/qa/20575/gdscript-file-naming-convention

**Comment by clabe45** [comment]
Thank you

**Comment by eerbin13** [comment]
What case is recommended for preloaded *.tres files?
