### ISSUE TITLE
Document dictionary keys being case sensitive

### ISSUE THREAD

**Issue by mhilbrunner** [godotengine/godot-docs#2378]
https://github.com/godotengine/godot-docs/pull/2370

Keys being sensitive should IMO be mentioned here:
http://docs.godotengine.org/en/3.0/classes/class_dictionary.html

**Comment by cbscribe** [comment]
That's a property of Strings, not of Dictionary keys. "Dot" notation is a shorthand for string keys, as noted here: [GDScript Basics](https://docs.godotengine.org/en/latest/getting_started/scripting/gdscript/gdscript_basics.html#dictionary)

Dot notation isn't mentioned at all on the API page. Perhaps a link, or even a copy of the examples on the GDScript page?

**Comment by mhilbrunner** [comment]
>Dot notation isn't mentioned at all on the API page. Perhaps a link, or even a copy of the examples on the GDScript page?

Agreed. This should really be pointed out.

**The below isn't important, I'm just procrastinating :P**

---

>That's a property of Strings, not of Dictionary keys

Isn't it a property of the dictionaries hash function, or the comparison function?

The string just holds the data, how it is interpreted is up to the user.

Now, to be fair, I don't know of any programming language with a dictionary implementation that is *not* case sensitive by default, so it being case sensitive would be (and was) my assumption.

So in a way, I agree, it is a property of strings that we have the convention of mostly doing case sensitive operations on them by default.

But for many languages there are widely used implementations of dictionaries that ignore case, or tutorials on how to implement them.

And, for example, the C# reference for dictionaries at least points out:
https://docs.microsoft.com/en-us/dotnet/api/system.collections.generic.dictionary-2
>For example, you can use the case-insensitive string comparers provided by the StringComparer class to create dictionaries with case-insensitive string keys.

*For posterity's sake, as I was curious and went down the rabbit hole: [Dictionary](https://github.com/godotengine/godot/blob/1e2b3ac407a39b6dc4b2835bfed86f50c7e71ddc/core/dictionary.cpp#L40) uses [VariantHasher](https://github.com/godotengine/godot/blob/75c89aaaef94a972fe257d5b6589862853847387/core/variant.h#L435), which calls [Variant::hash()](https://github.com/godotengine/godot/blob/master/core/variant.cpp#L2678) which calls [String::hash()](https://github.com/godotengine/godot/blob/master/core/ustring.cpp#L2128) for strings. The dictionary uses [OrderedHashMap](https://github.com/godotengine/godot/blob/master/core/ordered_hash_map.h) internally.*

**Comment by mhilbrunner** [comment]
In hindsight, I agree. I'll close this :)
