### ISSUE TITLE
Custom Drawing 2D: Add section on drawing anti-aliased lines

### ISSUE THREAD

**Issue by bitbutter** [godotengine/godot-docs#2379]
Currently the custom drawing in 2D tutorial demonstrates how to create aliased lines only:
https://docs.godotengine.org/en/latest/tutorials/2d/custom_drawing_in_2d.html

For many use cases, dynamically drawn *antialiased* lines are necessary to match an existing game aesthetic (e.g. a dynamically drawn HUD targeting display in a futuristic FPS, or trajectory preview in a minimalist 2d artillery/angry birds game). I think the article needs the addition of information on how to achieve dynamically drawn antialiased lines.

This is motivated by a personal need! In Unity I used the [Vectrosity](https://assetstore.unity.com/packages/tools/particles-effects/vectrosity-82?aid=1100l355n&gclid=Cj0KCQjw19DlBRCSARIsAOnfRehmEcfaI6pxiBOM47DfXPDEAGQxqvosYcUfq9ejn3sud-nkr23ohhEaApJvEALw_wcB&utm_source=aff) plugin to draw antialiased lines, I'm wondering how to do this in Godot.

**Comment by Calinou** [comment]
I think this functionality should be added in core for all kinds of 2D line drawing. Currently, `draw_line()` offers an `antialiased parameter` but it doesn't work well in all situations (e.g. with translucent lines). See https://github.com/godotengine/godot/issues/12840 and https://github.com/godotengine/godot/issues/8289.

As a workaround, you may be able to use Line2D/Path2D + Curve2D with a texture that features an one-pixel gradient (see [this example project](https://github.com/godotengine/godot-docs/files/3081588/2d_line_drawing.zip) I made).
