### ISSUE TITLE
New Optimization Tutorials

### ISSUE THREAD

**Issue by clayjohn** [godotengine/godot-docs#2395]
Now that we have a dedicated optimizations section, it would be good to work on a few optimization tutorials. 

For now, I suggest adding at least four:
- Optimization generally (things like sharing resources)
- Optimizing 3D games (generic tips on optimization)
- Optimizing 2D games (generic tips on optimization)
- Optimizing scenes for frustum culling (could fold into 3D, but likely worth its own tutorial with good examples + gifs as this topic comes up A LOT)

**Comment by clayjohn** [comment]
Here is a suggested Table of Contents from @lawnjelly https://github.com/lawnjelly/Misc/blob/master/Optimization/Optimization.md

**Comment by NathanLovato** [comment]
Closing as you two wrote all those pages already. Feel free to reopen if the task wasn't done. Note I'd open new issues when it's time to update pages for Godot 4.0, so they don't sink in the tracker and we can add them to the 4.0 milestone.
