### ISSUE TITLE
format() method in use on string arrays with multiple named placedholders

### ISSUE THREAD

**Issue by Dr-Primary** [godotengine/godot-docs#2400]
This is mostly a feature request but I thought it might help some people if some changes were made to the documentation as well.  

Currently .format() method only works with strings and not string arrays; it is also limited in that I can only use one named placeholder for each invocation of the .format() method.  

I am creating a game that is very dialogue rich and the gender of the main character as well as several side characters are determined by the player.  This requires a lot of automated dialogue formatting.
The work-arounds I have found involve me creating a for-loop to step through each dialogue block with a different statement each time as shown in my example below:

######
	for i in range(0,TextArray0unformatted.size()):
		TextArray0unformatted[i] = TextArray0unformatted[i].format({'WaterPlayerName' : global.WaterPlayerName})
		TextArray0unformatted[i] = TextArray0unformatted[i].format({'WaterPronounPossessive' : global.WaterPossessivePronoun})
		TextArray0.append(TextArray0unformatted[i].format({'AstralPlayerName': global.AstralPlayerName}))
######

It would be far more convenient if I could instead have the code look like the following:
######
      TextArray0.append( TextArray0unformatted.format({'WaterPronounPossessive' : global.WaterPossessivePronoun}, {'AstralPlayerName': global.AstralPlayerName}, {'WaterPronounPossessive' : global.WaterPossessivePronoun}))
######

If there is a way to do the above that I am unaware of, then please include it in the docs otherwise I think it would be worth mentioning my work-arounds in the doc.

**Comment by AlexHolly** [comment]
Is this what you are looking for?

https://docs.godotengine.org/en/3.1/getting_started/scripting/gdscript/gdscript_format_string.html#format-method-examples

```
TextArray0unformatted[i] = TextArray0unformatted[i].format(
{
'WaterPlayerName' : global.WaterPlayerName,
'WaterPronounPossessive' : global.WaterPossessivePronoun,
'AstralPlayerName': global.AstralPlayerName
})
```

**Comment by Calinou** [comment]
This seems to be more of a feature request than a documentation issue. Please open an issue on the [Godot Proposals](https://github.com/godotengine/godot-proposals) repository with example use cases, but note that proposals that can easily be abstracted away in functions may be rejected.
