### ISSUE TITLE
3.1 shading language doc page missing

### ISSUE THREAD

**Issue by Vultraz** [godotengine/godot-docs#2402]
This link is broken: [https://docs.godotengine.org/en/3.1/tutorials/shading/shading_language.html](url).

The 3.0 version of the page works fine.

**Comment by Vultraz** [comment]
Oops, sorry. Didn't realize there was a docs repo. 😬 I got the link from this popup on the 3.0 page:
![image](https://user-images.githubusercontent.com/3558659/56635032-c744de00-66af-11e9-860d-ee807e2a357e.png)

**Comment by skyace65** [comment]
I think we can close this issue since it seems to be resolved.
