### ISSUE TITLE
The new Inspector Plugins tutorial snippets are wrong

### ISSUE THREAD

**Issue by mrcdk** [godotengine/godot-docs#2416]
The tutorial: https://docs.godotengine.org/en/latest/tutorials/plugins/editor/inspector_plugins.html

Both snippets show functions and classes that aren't available on Godot 3.1 or later.

Issues:
- `add_custom_property_editor()` doesn't exist in `EditorInspectorPlugin` Only `add_property_editor()`, `add_custom_control()` and `add_property_editor_for_multiple_properties()` exist.
- The second snippet omits the `extends` so it will automatically extend `Reference` which wouldn't work in this case because all the `add_*()` functions before only accept a `Control` node.
- ~~`EditorSpinSlider` isn't exposed to GDScript so it won't work.~~
  - Fixed by https://github.com/godotengine/godot/pull/32944

**Comment by lonevox** [comment]
I believe this can be closed because later edits fixed all of these issues.

**Comment by pycbouh** [comment]
Indeed, I rewrote it some time ago and it should be good (in the latest branch at least).
