### ISSUE TITLE
Unclear how to submit reference/class documentation patches

### ISSUE THREAD

**Issue by mitchcurtis** [godotengine/godot-docs#2417]
https://github.com/godotengine/godot-docs#contributing-changes says:

> To edit an existing page, locate its .rst source file and open it in your favorite text editor. You can then commit the changes, push them to your fork and make a pull request. Note that the pages in classes/ should not be edited here, they are automatically generated from Godot's XML class references.

It links to this repo, but doesn't explain how to edit those XML class references. The following topics should be covered:

- How to generate the HTML docs from the XML files to verify that your changes are correct. This is not covered at all. Building the documentation in godot-docs results in generated HTML reference docs, but they seem to be outdated compared to the XML files.
- How to format the documentation in those XML files.
- How to link (e.g. [PopupMenu]) to other types and functions from a function's documentation, etc.

https://github.com/godotengine/godot/blob/master/CONTRIBUTING.md doesn't explain this, neither does https://docs.godotengine.org/en/3.1/community/contributing/documentation_guidelines.html#how-to-contribute.

Eventually I found this page:

https://docs.godotengine.org/en/3.1/community/contributing/updating_the_class_reference.html#doc-updating-the-class-reference

While this seems to explain most of what contributors need to know, it doesn't appear to explain how to build the docs; it only explains how to update them from the sources: ./bin/godot.x11.tools.64 --doctool.

That page should be linked to from e.g. https://github.com/godotengine/godot-docs#editing-existing-pages.

**Comment by akien-mga** [comment]
> While this seems to explain most of what contributors need to know, it doesn't appear to explain how to build the docs; it only explains how to update them from the sources: ./bin/godot.x11.tools.64 --doctool.

It does explain how to edit the XML too: https://docs.godotengine.org/en/latest/community/contributing/updating_the_class_reference.html#how-to-edit-class-xml

**Comment by mitchcurtis** [comment]
Yes, I saw that, that's why I mentioned it, but how do you build the docs (generate HTML from the XML) once you've edited them?

**Comment by mitchcurtis** [comment]
I see you closed it as well... I'm sorry, but are you sure you guys _want_ doc contributions?

**Comment by akien-mga** [comment]
The issue asked about how to submit changes to the class reference, which is already documented, so I added a link to that doc page in the README to make it clearer, thus fixing this issue. This is why it's closed.

I missed the fact that you wanted to know how to then sync the godotengine/godot XML reference with the copy which is in godot-docs. This is a step done by repo maintainers usually, and it's the first one any contributor asks about it, so it's not documented. The XML docs are visible in Godot itself, so you can see your changes by building the engine and checking the in-editor help.

For the reference, the workflow to update the RST classref is (assuming that you have `godot` and `godot-docs` clones next to each other):
```
rm -f godot-docs/classes/class_*
cd godot/doc
make rst
cp _build/rst/* ../../godot-docs/classes
cd ../../godot-docs
git add classes
git commit -m "Sync classref with current source"
```

**Comment by akien-mga** [comment]
Why do you want to build the HTML version exactly?

If it's because you wanted to make a PR of those changes, this is not necessary. You should only update the XML version which is the reference version, and I will update the RST copy myself once in a while.

**Comment by mitchcurtis** [comment]
> The XML docs are visible in Godot itself, so you can see your changes by building the engine and checking the in-editor help.

Thank you. This is the part that was unclear to me. Can you please document this somewhere so that contributors know that this is the official way of verifying that changes made to the XML files are correct when viewed in the generated documentation?

Perhaps also explain that the build output should be examined to see if there are any documentation errors, if that is how it works? That will save me from pushing patches with doc errors.

> Why do you want to build the HTML version exactly?

Because editing an XML file is not enough to know that certain syntax (like linking to functions, types, etc.) works as expected. I wasn't aware that the typical workflow is actually to view the (modified) generated documentation in the editor itself.

**Comment by mitchcurtis** [comment]
For example, should there be a step between 3 and 4 [here](https://docs.godotengine.org/en/latest/community/contributing/updating_the_class_reference.html#how-to-contribute)?

I suppose most patches won't link to functions, but the patches I had in mind are specifically about linking to other functions to make the API more discoverable. For example, Popup's documentation has no mention of how to hide it. That could be fixed by linking to the hide() function.

Perhaps a new paragraph [here](https://docs.godotengine.org/en/latest/community/contributing/updating_the_class_reference.html#how-to-edit-class-xml):

> Edit it using your favourite text editor. If you use a code editor, make sure that it doesn’t change the indent style: tabs for the XML, and 4 spaces inside BBcode-style blocks. More on that below.
> 
> **To check that the modifications you've made are correct, build godot as described <link here>, run the editor and open the help for the page you modified.**

**Comment by mitchcurtis** [comment]
I tried to submit a patch but I don't know how to link to a certain page:

https://github.com/godotengine/godot-docs/pull/2418

**Comment by NathanLovato** [comment]
Closing as your patch was merged. Please reopen if this needs more changes.
