### ISSUE TITLE
Resource vs Dictionary example doesn't throw error as described

### ISSUE THREAD

**Issue by tyoungjr** [godotengine/godot-docs#2420]
Hi there,

The code described [here ](https://docs.godotengine.org/en/stable/getting_started/step_by_step/resources.html) , doesn't throw the error when the referenced dictionary is deleted. 

```
extends Node2D
# https://docs.godotengine.org/en/stable/getting_started/step_by_step/resources.html
# this demonstrates the reference county nature of resources vs dictionaries 

class MyObject:
	extends Object
	var dict = {} 
	
func _ready():
	var obj1 = MyObject.new()
	var obj2 = MyObject.new()
	obj1.dict.greeting = "hello"
	obj2.dict = obj1.dict 				# 'obj2.dict now references obj1's dictionary 
	obj1.free()							# 'obj1' is freed and the dictionry too!
	print(obj2.dict.greeting) 			# 'Error? 
	
	#assert(obj2.dict == null)
	
	# to avoid this , we must manually duplicate the dictionary 
	obj1 = MyObject.new()
	obj1.dict.greeting = "hello copy" 
	obj2.dict = obj1.dict.duplicate() 	# passing a copy not a reference 
	obj1.free()							# obj2's dictionary still exists.
	print(obj2.dict.greeting)
```

**Comment by Calinou** [comment]
@tyoungjr Can you still reproduce this in Godot 3.2?

**Comment by tyoungjr** [comment]
@Calinou Yes...
![image](https://user-images.githubusercontent.com/2190286/75814278-1ab79c00-5d57-11ea-9d78-7c1fa9aa5de9.png)

**Comment by tyoungjr** [comment]
I'm not sure how big of an issue this is, memory is weird on esp on Windows and objects may stick around before garbage is collected. Feel free to close this and maybe add a link to this docs about Godots memory allocation scheme for clarity.

**Comment by Calinou** [comment]
@tyoungjr This might be fixed in the `master` branch thanks to changes to memory allocation.
