### ISSUE TITLE
AnimationTree AdvanceCondition is undocumented

### ISSUE THREAD

**Issue by rcorre** [godotengine/godot-docs#2439]
From https://docs.godotengine.org/en/3.1/tutorials/animation/animation_tree.html#statemachine:

> Advance Condition will turn on auto advance when this condition is set. This is a custom text field that can be filled with a variable name. The variable can be modified from code (more on this later).

Although it says "more on this later", there is no further mention of advance conditions.

I'm wondering:

- Is it just a variable name, or can it be an expression?
- Where does the variable live? On the AnimationTree? On the AnimationPlayer? Can I reference a variable from another object?

**Comment by guilhermefelipecgs** [comment]
> Although it says "more on this later", there is no further mention of advance conditions.

"more on this later" it's referring to https://docs.godotengine.org/en/3.1/tutorials/animation/animation_tree.html#controlling-from-code
Maybe we should put a link there.

> * Is it just a variable name, or can it be an expression?
> * Where does the variable live? On the AnimationTree? On the AnimationPlayer? Can I reference a variable from another object?

It's just a variable (boolean). You can't create any expression in this field. You need to set it from code like this: `$animation_tree["parameters/conditions/my_advance_condition"] = true # or false`
