### ISSUE TITLE
Step by step » Control the game’s UI with code (small issues)

### ISSUE THREAD

**Issue by mikatuo** [godotengine/godot-docs#2447]
https://docs.godotengine.org/en/3.1/getting_started/step_by_step/ui_code_a_life_bar.html

I was following the Step by Step docs and noticed a few issues.

# Images

- [lifebar_tutorial_number_animation_messed_up.gif](https://github.com/godotengine/godot-docs/blob/f484dc4b8653f8ba1448842e76b260d4d02efc1d/getting_started/step_by_step/img/lifebar_tutorial_number_animation_messed_up.gif) - the lifebar should not fade out on player death. The fade effect is added later on in the "Fade the bar when the Player dies" section

- [lifebar_tutorial_player_died_signal_enemy_connected.png](https://github.com/godotengine/godot-docs/blob/f484dc4b8653f8ba1448842e76b260d4d02efc1d/getting_started/step_by_step/img/lifebar_tutorial_player_died_signal_enemy_connected.png) - is not in sync with the `start` project from [ui_code_life_bar.zip](https://github.com/godotengine/godot-docs/blob/f484dc4b8653f8ba1448842e76b260d4d02efc1d/getting_started/step_by_step/files/ui_code_life_bar.zip). Perhaps, a better image:
![Screenshot_30](https://user-images.githubusercontent.com/7230306/57552628-2889d400-7375-11e9-9675-b8222533b56b.png)
 
# Code (ui_code_life_bar.zip)

## The `start` project

`GUI/Tween` - the `tween_completed()` signal is connected to a non existing method
![Screenshot_30](https://user-images.githubusercontent.com/7230306/57552954-283e0880-7376-11e9-83db-6e807cbef433.png)

## The `end` project

`GUI/Tween` - the `tween_completed()` signal is connected to a non existing method - same as in the `start` project

`Characters/Player` - the `health_changed()` signal is connected to a non existing method
![Screenshot_32](https://user-images.githubusercontent.com/7230306/57553436-245eb600-7377-11e9-9d3d-37af6d9a3774.png)

**Comment by NathanLovato** [comment]
Thanks for the report, I'll fix it as part of our upcoming doc sprints. I'm starting with contributions to the code reference though.
