### ISSUE TITLE
Array concatenation not documented on Array API page

### ISSUE THREAD

**Issue by youreperfect** [godotengine/godot-docs#2452]
Array has no .join() or .concat() method and the correct way to join arrays in GDScript is using the + operator, but this is not mentioned on the Array API page

**Comment by clayjohn** [comment]
It's documented [here](http://docs.godotengine.org/en/latest/getting_started/scripting/gdscript/gdscript_basics.html#operators). I'm not sure it makes sense to document features of the language under the classref. 

The purpose of the API page is to document methods and properties that belong to the specific class. The "+" operator isn't a method of Array (although you could make the argument that it is).

**Comment by youreperfect** [comment]
I would argue that any class that does anything with the + operator other than add numbers together is overloading the operator and the overload should be documented as part of the class.

For example the + operator in C++ may be described in places like: https://www.geeksforgeeks.org/operators-c-c/

but QList's operator overload is listed in its class documentation:
https://doc.qt.io/qt-5/qlist.html#operator-2b

because it is peforming behavior, that is concatentation, that is different than the "standard" behavior of adding numbers together - but in cases like Array, + is doing something specific to the class.

**Comment by clayjohn** [comment]
You make a convincing argument. :)

My suggestion would be to add it under the "description" section in https://github.com/godotengine/godot/blob/master/doc/classes/Array.xml

If you havent contributed before, check out http://docs.godotengine.org/en/latest/community/contributing/index.html specifically the section titled "Contribute to the class reference"
