### ISSUE TITLE
Website's article about KinematicBody has misinformation about move_and_slide_with_snap

### ISSUE THREAD

**Issue by groug** [godotengine/godot-docs#2458]
Hi,

I know it's not per se godot-docs but the article about Godot 3.1 and KinematicBody is wrong (or maybe the code changed since then): snap and floor_normal arguments are swapped in the example.
When searching for move_and_slide_with_snap doc on google, this article is among the first results, I was confused yesterday why my code didn't work (and then saw on the official doc the article is wrong).

Link: https://godotengine.org/article/godot-31-will-get-many-improvements-kinematicbody

**Comment by clayjohn** [comment]
I don't believe that those articles are maintained as the API changes. For better or for worse Godot changes quickly so it is always best to look to the official docs for information.

**Comment by Calinou** [comment]
Closing per @clayjohn's comment above. Examples in news articles are generally not updated over time.
