### ISSUE TITLE
Instancing docs gives wrong example about overriding Bounce property in PhysicsMaterial

### ISSUE THREAD

**Issue by akien-mga** [godotengine/godot-docs#2459]
In the Instancing tutorial, there's a section which tells you to modify the Bounce and friction properties in an instance and see that it doesn't impact other instances/the original scene... but it does!

http://docs.godotengine.org/en/latest/getting_started/step_by_step/instancing.html#editing-instances

This is because bounce and friction were changed from direct properties to properties of a PhysicsMaterial resource, which is shared by default.
The docs were updated to mention the PhysicsMaterial workflow, but now the whole point they were trying to make no longer works.

One could teach users how to make resources unique at this point (as done in #2412), but this would probably be confusing this early in the Step by step tutorial. I'd suggest to drop the references to PhysicsMaterial, Bounce and Friction, and instead focus on other properties which behave the typical way.

**Comment by Nutriz** [comment]
Hi, I will fixing this. I wanted to use modulate to change the color of one instance, but...no revert button for it. I noticed Gravity Scale have revert button, but a lot of properties don't have it.
The user can be confused about this (I'm also) is there an explication and must we explain this ?
