### ISSUE TITLE
API documentation missing for C++

### ISSUE THREAD

**Issue by muiz6** [godotengine/godot-docs#2460]
Although tutorials are available on how to setup the c++ bindings. API documentation is missing which is making calling engine methods really confusing.
(I personally am having a really hard time with AnimatedSprite2D)

**Comment by Calinou** [comment]
The C++ API documentation is very close from the GDScript one. Is there anything specific that needs to be noted?

**Comment by mhilbrunner** [comment]
Closing, as there hasn't been much discussion or consensus and the issue's a year old now - if you aim to create part of your game in C++, you'll generally be fine with translating either from GDScript or by reading the implementation C++ files, Godot's code is fairly readable (for C++ that is).
