### ISSUE TITLE
drag_margin_left is not specific

### ISSUE THREAD

**Issue by urusuru** [godotengine/godot-docs#2477]
How to get the margin of camera2D, it is not specific, the information provided in the docs.

**Comment by cbscribe** [comment]
What exactly are you asking? "How to get the margin" is the same as any property of any node:

    $Camera2D.drag_margin_left

Can you be more specific with what you think may be needed or what you're trying to do?

**Comment by urusuru** [comment]
I am trying to get the margin by using "get_drag_margin()" but the info doesn't say what I have to put in to get the "left" side.

All of the directions have set_drag_margin() and get_drag_margin() but I don't understand how to get which one of them.

**Comment by cbscribe** [comment]
Direct property access is the preferred method. Every property has a getter and setter behind the scenes, but they are for example hidden from the autocomplete. Just use the property, that's what it's there for.

Related: #2284

**Comment by Calinou** [comment]
Closing, as the original question has been answered.
