### ISSUE TITLE
GDScript Super function documentation

### ISSUE THREAD

**Issue by n-pigeon** [godotengine/godot-docs#249]
How to use Super Functions should be added to GDScript docs.

I would add it, but I don't understand this topic thoroughly very well, so I'm afraid to misinform somebody xD

**Comment by eska014** [comment]
This is already documented: http://docs.godotengine.org/en/latest/reference/gdscript.html#referencing-functions

>To call a function in a base class (i.e. one `extend`-ed in your current class), prepend `.` to the function name:
> ```
> .basefunc(args)
> ```

**Comment by n-pigeon** [comment]
Ups xD

**Comment by KiwwiPity** [comment]
> This is already documented: http://docs.godotengine.org/en/latest/reference/gdscript.html#referencing-functions

But in the case that a method in the base class gets shadowed in the derived one (has the same name), how do it?
There's some `base` or `super` thing to so?
