### ISSUE TITLE
No documentation for PopupDialog

### ISSUE THREAD

**Issue by mitchcurtis** [godotengine/godot-docs#2495]
I want to create a save menu and figured I'd use a dialog since they already have (based on my experience with other UI toolkits) the Save/Cancel buttons. However, not only does it not have a description, but it seems that it has no generated reference documentation, which leads me to believe that it has no API of its own (i.e. beyond that which it inherits from Popup).

**Comment by mitchcurtis** [comment]
It literally has no API of its own:

https://github.com/godotengine/godot/blob/b16c309f82c77d606472c3c721a1857e323a09e7/scene/gui/dialogs.h#L90

https://github.com/godotengine/godot/blob/b16c309f82c77d606472c3c721a1857e323a09e7/scene/gui/dialogs.cpp#L338

Why even make this class public in that case? :/

**Comment by akien-mga** [comment]
It's been like this since Godot was open sourced in 2014, and nothing uses it in the editor code, so I guess it was simply never really noticed and deprecated. Could likely be dropped in 4.0.

**Comment by mitchcurtis** [comment]
Ah, I see... so what solution would you recommend for a dialog in that case? Regular PopupPanel with some buttons? Or is there a ready-made solution already available?

**Comment by TheDuriel** [comment]
Its a skinnable base type, and thus somewhat valuable. But could probably be dropped.

**Comment by akien-mga** [comment]
Closing in favour of godotengine/godot#30637.
