### ISSUE TITLE
Suggest workaround for `textureSize()` due to OpenGLES 2.0 limitations

### ISSUE THREAD

**Issue by silverkorn** [godotengine/godot-docs#2498]
Related to this issue: https://github.com/godotengine/godot/issues/28885 ,

OpenGL ES 2.0 does not support shader function `textureSize()` so a workaround would be to use/pass the constant `TEXTURE_PIXEL_SIZE` instead.

Is it possible to add this information in the documentation?
Thank you!

**Comment by akien-mga** [comment]
Fixed by #2811.
