### ISSUE TITLE
First Project Works With C#, All Further Projects Do Not

### ISSUE THREAD

**Issue by OriginalAGP** [godotengine/godot-docs#2499]
The title says it all. And that's for both Mono and Visual C# compilers. Windows 10. I tried having one compiler at a time installed, then both. Added Mono to the system path. Nothing. But that first project still works (with Visual Studio).

 modules/mono/editor/csharp_project.cpp:183 - Parse error: Unexpected token: Symbol
 Failed to determine namespace and class for script: res://Models/Ship.cs
 modules/mono/editor/godotsharp_builds.cpp:383 - Condition ' metadata_err != OK ' is true. returned: false
 editor/editor_node.cpp:4666 - A Godot Engine build callback failed.

**Comment by aaronfranke** [comment]
This is the documentation repo, you may be looking for https://github.com/godotengine/godot
