### ISSUE TITLE
Small error in the tutorial Scripting (continued) > Processing

### ISSUE THREAD

**Issue by aldatsa** [godotengine/godot-docs#250]
If I understood correctly I think that it should be:

> Which will show a counter increasing each frame.

instead of:

> Which will show a counter increasing each second.

http://docs.godotengine.org/en/latest/tutorials/step_by_step/scripting_continued.html#processing

**Comment by akien-mga** [comment]
Indeed. Feel free to make a pull request :)

**Comment by aldatsa** [comment]
Done! I'm enjoying Godot, keep up the good work!
