### ISSUE TITLE
Outdated C# namespaces in C# API differences to GD Script page

### ISSUE THREAD

**Issue by BLaDoM** [godotengine/godot-docs#2501]
[API differences to GDScript](https://docs.godotengine.org/en/3.1/getting_started/scripting/c_sharp/c_sharp_differences.html) page in the docs contains an outdated notation in both the [Array](https://docs.godotengine.org/en/3.1/getting_started/scripting/c_sharp/c_sharp_differences.html#array) and [Dictionary](https://docs.godotengine.org/en/3.1/getting_started/scripting/c_sharp/c_sharp_differences.html#dictionary) sections, mentioning _Godot.Array_ and _Godot.Dictionary_ instead of _Godot.Collections.Array_ and _Godot.Collections.Dictionary_ respectively.

**Comment by neikeq** [comment]
Fixed by #2502
