### ISSUE TITLE
GDScript - Spacing between methods

### ISSUE THREAD

**Issue by aaronfranke** [godotengine/godot-docs#2505]
In many GDScript projects, I have seen several ways to separate functions. Sometimes one line:

```
func _ready():
    print("ready")

func _process(delta):
    print("process")
```

But sometimes two:

```
func _ready():
    print("ready")


func _process(delta):
    print("process")
```

I have also seen functions separated by 3 or more lines. I think that we should probably have no more than 2, but what should the policy be between 1 and 2 lines? Situationally? User discretion? Encourage one over the other? Disallow one or the other entirely?

We should probably decide on something and put it in [the style guide](https://docs.godotengine.org/en/3.1/getting_started/scripting/gdscript/gdscript_styleguide.html).

**Comment by NathanLovato** [comment]
We've used both at GDquest, but use 2 now. It makes the code a lot easier to read, as you may have empty lines inside of methods or between variable definitions. It's instantly clear that 2 line gaps separate methods. From the [GDquest gdscript guidelines](https://github.com/GDquest/gdquest-projects/blob/master/guidelines/gdscript-guidelines.md):

```
Always leave 2 blanks lines between methods to visually distinguish them and other code blocks.
```

The Python pep8 recommends 2 lines between functions or classes inside python modules for the same reason (and inside a class 1 line between methods). To me, it has a practical benefit.

**Comment by Calinou** [comment]
I agree with recommending 2 lines between functions. My projects currently separate functions with one blank line only, but I'll gladly switch to 2 if this recommendation gets added to the style guide.

**Comment by aaronfranke** [comment]
What about before methods?

    var x
    
    func test():

vs

    var x
    
    
    func test():
