### ISSUE TITLE
GDScript: update the style guide for static type hints

### ISSUE THREAD

**Issue by aaronfranke** [godotengine/godot-docs#2506]
In the [static typing article](https://docs.godotengine.org/en/3.1/getting_started/scripting/gdscript/static_typing.html), and in many projects, I have seen this:

    var number: int = 5

But I have also seen this fairly often, with a space before the colon:

    var number : int = 5

We should probably decide on something and put it in [the style guide](https://docs.godotengine.org/en/3.1/getting_started/scripting/gdscript/gdscript_styleguide.html).

**Comment by NathanLovato** [comment]
We've looked into that with my team, and looking at the godot repository, found `var number: int = 5` as the most commonly used one. This is also the style used in Python's PEP document for static type hints.
For methods, `func method_name(argument: int) -> void:`

I'll work on that on Monday for the Write the Docs event if that's fine by you.

**Comment by NathanLovato** [comment]
That's also the style we used when we wrote the static gdscript docs with Guilherme: https://docs.godotengine.org/en/latest/getting_started/scripting/gdscript/static_typing.html

Reviewed by vnen, who implemented static type hints, among others.

**Comment by NathanLovato** [comment]
Python PEP document: https://www.python.org/dev/peps/pep-0484/

**Comment by akien-mga** [comment]
If you enable Editor Settings > Text Editor > Completion > Add Type Hints, it will indeed use the `variable: type` format, so that should likely be used as reference.
