### ISSUE TITLE
'zh_CN' edit link is broken

### ISSUE THREAD

**Issue by zszen** [godotengine/godot-docs#2507]
![](https://user-images.githubusercontent.com/1890538/58932542-b7ccb080-8796-11e9-8bc8-c5073176f741.png)

link: https://github.com/godotengine/godot-docs-l10n/blob/master/docs/index.rst

![](https://user-images.githubusercontent.com/1890538/58932560-cb781700-8796-11e9-89f7-41d98239eda7.png)

I want fix some wrong infomation. But the edit link don't work.

**Comment by akien-mga** [comment]
The translations should not be edited on GitHub, but on Weblate: https://hosted.weblate.org/projects/godot-engine/godot-docs/

I'll see if I can customize what this edit link points to.

**Comment by akien-mga** [comment]
The link should be fixed once rtfd/readthedocs.org#5799 is resolved. It will then point to the original .rst file in the `godot-docs` repo, i.e. the English version.

That might still be confusing, so I might disable the "Edit on GitHub" button on localized instances instead, with something like this:
```diff
diff --git a/conf.py b/conf.py
index 62b21070..d8818f56 100644
--- a/conf.py
+++ b/conf.py
@@ -68,7 +68,7 @@ html_theme_options = {
 
 # VCS options: https://docs.readthedocs.io/en/latest/vcs.html#github
 html_context = {
-    "display_github": True, # Integrate GitHub
+    "display_github": !tags.has("i18n"), # Integrate GitHub
     "github_user": "godotengine", # Username
     "github_repo": "godot-docs", # Repo name
     "github_version": "master", # Version
```

**Comment by akien-mga** [comment]
Fixed, localized instances no longer show "Edit on GitHub".
