### ISSUE TITLE
Documentation fails to build due to a recursion error

### ISSUE THREAD

**Issue by Calinou** [godotengine/godot-docs#2513]
I've been getting a documentation build error since a few days on my CI build system (which uses Fedora 30) [(full log)](https://gitlab.com/Calinou/godot-builds-ci/-/jobs/223746340):

```text
Recursion error:
maximum recursion depth exceeded while calling a Python object

This can happen with very large or deeply nested source files.  You can carefully increase the default Python recursion limit of 1000 in conf.py with e.g.:
    import sys; sys.setrecursionlimit(1500)
```

According to my [pipeline logs](https://gitlab.com/Calinou/godot-builds-ci/pipelines), this seems to occur since https://github.com/godotengine/godot-docs/commit/f51015697d1fb2ad114232e3be16aa5af55d4f4e.

**Comment by jaehallen** [comment]
I also encountered the same problem in Windows 10 and arch

**Comment by jbwyatt4** [comment]
Can confirm. Manjaro Linux x64.

Here is most of my output:

writing output... [ 81%] getting_started/workflow/best_practices/scenes_versus_swriting output... [ 82%] getting_started/workflow/best_practices/what_are_godot_writing output... [ 82%] getting_started/workflow/export/changing_application_ic/home/j/code/build/godot-docs/classes/class_@gdscript.rst:600: WARNING: Could not lex literal_block as "gdscript". Highlighting skipped.
/home/j/code/build/godot-docs/classes/class_node.rst:899: WARNING: Could not lex literal_block as "gdscript". Highlighting skipped.
/home/j/code/build/godot-docs/classes/class_particlesmaterial.rst:163: WARNING: undefined label: class_particlesmaterial_method_set_param (if the link has no caption the label must precede a section header)
/home/j/code/build/godot-docs/classes/class_particlesmaterial.rst:163: WARNING: undefined label: class_particlesmaterial_method_set_param_randomness (if the link has no caption the label must precede a section header)
/home/j/code/build/godot-docs/classes/class_particlesmaterial.rst:163: WARNING: undefined label: class_particlesmaterial_method_set_param_texture (if the link has no caption the label must precede a section header)
/home/j/code/build/godot-docs/classes/class_particlesmaterial.rst:165: WARNING: undefined label: class_particlesmaterial_method_set_param (if the link has no caption the label must precede a section header)
/home/j/code/build/godot-docs/classes/class_particlesmaterial.rst:165: WARNING: undefined label: class_particlesmaterial_method_set_param_randomness (if the link has no caption the label must precede a section header)
/home/j/code/build/godot-docs/classes/class_particlesmaterial.rst:165: WARNING: undefined label: class_particlesmaterial_method_set_param_texture (if the link has no caption the label must precede a section header)
/home/j/code/build/godot-docs/classes/class_particlesmaterial.rst:167: WARNING: undefined label: class_particlesmaterial_method_set_param (if the link has no caption the label must precede a section header)
/home/j/code/build/godot-docs/classes/class_particlesmaterial.rst:167: WARNING: undefined label: class_particlesmaterial_method_set_param_randomness (if the link has no caption the label must precede a section header)
/home/j/code/build/godot-docs/classes/class_particlesmaterial.rst:167: WARNING: undefined label: class_particlesmaterial_method_set_param_texture (if the link has no caption the label must precede a section header)
/home/j/code/build/godot-docs/classes/class_particlesmaterial.rst:169: WARNING: undefined label: class_particlesmaterial_method_set_param (if the link has no caption the label must precede a section header)
/home/j/code/build/godot-docs/classes/class_particlesmaterial.rst:169: WARNING: undefined label: class_particlesmaterial_method_set_param_randomness (if the link has no caption the label must precede a section header)
/home/j/code/build/godot-docs/classes/class_particlesmaterial.rst:169: WARNING: undefined label: class_particlesmaterial_method_set_param_texture (if the link has no caption the label must precede a section header)
/home/j/code/build/godot-docs/classes/class_particlesmaterial.rst:171: WARNING: undefined label: class_particlesmaterial_method_set_param (if the link has no caption the label must precede a section header)
/home/j/code/build/godot-docs/classes/class_particlesmaterial.rst:171: WARNING: undefined label: class_particlesmaterial_method_set_param_randomness (if the link has no caption the label must precede a section header)
/home/j/code/build/godot-docs/classes/class_particlesmaterial.rst:171: WARNING: undefined label: class_particlesmaterial_method_set_param_texture (if the link has no caption the label must precede a section header)
/home/j/code/build/godot-docs/classes/class_particlesmaterial.rst:173: WARNING: undefined label: class_particlesmaterial_method_set_param (if the link has no caption the label must precede a section header)
/home/j/code/build/godot-docs/classes/class_particlesmaterial.rst:173: WARNING: undefined label: class_particlesmaterial_method_set_param_randomness (if the link has no caption the label must precede a section header)
/home/j/code/build/godot-docs/classes/class_particlesmaterial.rst:173: WARNING: undefined label: class_particlesmaterial_method_set_param_texture (if the link has no caption the label must precede a section header)
/home/j/code/build/godot-docs/classes/class_particlesmaterial.rst:175: WARNING: undefined label: class_particlesmaterial_method_set_param (if the link has no caption the label must precede a section header)
/home/j/code/build/godot-docs/classes/class_particlesmaterial.rst:175: WARNING: undefined label: class_particlesmaterial_method_set_param_randomness (if the link has no caption the label must precede a section header)
/home/j/code/build/godot-docs/classes/class_particlesmaterial.rst:175: WARNING: undefined label: class_particlesmaterial_method_set_param_texture (if the link has no caption the label must precede a section header)
/home/j/code/build/godot-docs/classes/class_particlesmaterial.rst:177: WARNING: undefined label: class_particlesmaterial_method_set_param (if the link has no caption the label must precede a section header)
/home/j/code/build/godot-docs/classes/class_particlesmaterial.rst:177: WARNING: undefined label: class_particlesmaterial_method_set_param_randomness (if the link has no caption the label must precede a section header)
/home/j/code/build/godot-docs/classes/class_particlesmaterial.rst:177: WARNING: undefined label: class_particlesmaterial_method_set_param_texture (if the link has no caption the label must precede a section header)
/home/j/code/build/godot-docs/classes/class_particlesmaterial.rst:179: WARNING: undefined label: class_particlesmaterial_method_set_param (if the link has no caption the label must precede a section header)
/home/j/code/build/godot-docs/classes/class_particlesmaterial.rst:179: WARNING: undefined label: class_particlesmaterial_method_set_param_randomness (if the link has no caption the label must precede a section header)
/home/j/code/build/godot-docs/classes/class_particlesmaterial.rst:179: WARNING: undefined label: class_particlesmaterial_method_set_param_texture (if the link has no caption the label must precede a section header)
/home/j/code/build/godot-docs/classes/class_particlesmaterial.rst:181: WARNING: undefined label: class_particlesmaterial_method_set_param (if the link has no caption the label must precede a section header)
/home/j/code/build/godot-docs/classes/class_particlesmaterial.rst:181: WARNING: undefined label: class_particlesmaterial_method_set_param_randomness (if the link has no caption the label must precede a section header)
/home/j/code/build/godot-docs/classes/class_particlesmaterial.rst:181: WARNING: undefined label: class_particlesmaterial_method_set_param_texture (if the link has no caption the label must precede a section header)
/home/j/code/build/godot-docs/classes/class_particlesmaterial.rst:183: WARNING: undefined label: class_particlesmaterial_method_set_param (if the link has no caption the label must precede a section header)
/home/j/code/build/godot-docs/classes/class_particlesmaterial.rst:183: WARNING: undefined label: class_particlesmaterial_method_set_param_randomness (if the link has no caption the label must precede a section header)
/home/j/code/build/godot-docs/classes/class_particlesmaterial.rst:183: WARNING: undefined label: class_particlesmaterial_method_set_param_texture (if the link has no caption the label must precede a section header)
/home/j/code/build/godot-docs/classes/class_particlesmaterial.rst:185: WARNING: undefined label: class_particlesmaterial_method_set_param (if the link has no caption the label must precede a section header)
/home/j/code/build/godot-docs/classes/class_particlesmaterial.rst:185: WARNING: undefined label: class_particlesmaterial_method_set_param_randomness (if the link has no caption the label must precede a section header)
/home/j/code/build/godot-docs/classes/class_particlesmaterial.rst:185: WARNING: undefined label: class_particlesmaterial_method_set_param_texture (if the link has no caption the label must precede a section header)
/home/j/code/build/godot-docs/classes/class_particlesmaterial.rst:201: WARNING: undefined label: class_particlesmaterial_method_set_flag (if the link has no caption the label must precede a section header)
/home/j/code/build/godot-docs/classes/class_particlesmaterial.rst:203: WARNING: undefined label: class_particlesmaterial_method_set_flag (if the link has no caption the label must precede a section header)
/home/j/code/build/godot-docs/classes/class_particlesmaterial.rst:205: WARNING: undefined label: class_particlesmaterial_method_set_flag (if the link has no caption the label must precede a section header)
/home/j/code/build/godot-docs/community/contributing/pr_workflow.rst:384: WARNING: Could not lex literal_block as "shell". Highlighting skipped.
/home/j/code/build/godot-docs/community/contributing/pr_workflow.rst:397: WARNING: Could not lex literal_block as "shell". Highlighting skipped.
/home/j/code/build/godot-docs/development/cpp/custom_modules_in_cpp.rst:302: WARNING: Could not lex literal_block as "gdscript". Highlighting skipped.
/home/j/code/build/godot-docs/development/cpp/custom_modules_in_cpp.rst:346: WARNING: Could not lex literal_block as "gdscript". Highlighting skipped.

Recursion error:
maximum recursion depth exceeded while calling a Python object

This can happen with very large or deeply nested source files.  You can carefully increase the default Python recursion limit of 1000 in conf.py with e.g.:
    import sys; sys.setrecursionlimit(1500)
make: *** [Makefile:60: html] Error 2

**Comment by Calinou** [comment]
I got it to build by using Python 2 instead of Python 3, but I'm not sure if this is related to the issue.
