### ISSUE TITLE
Improve RegEx documentation

### ISSUE THREAD

**Issue by plokmijnuhby** [godotengine/godot-docs#2522]
The current documentation is okay as far as it goes, but in terms of how to write a regex, it simply states, "For a more in-depth look, you can easily find various tutorials and detailed explanations on the Internet." This is not good enough, because while most implementations of regex support *, ?, and other common patterns, the exact details vary between systems. Are (?R) groups supported? What metacharacters are available? Are matches multiline, are they case sensitive? Does . match newlines? Can we have at least some information on what Godot regexes actually are?

**Comment by Calinou** [comment]
The [regex module](https://github.com/godotengine/godot/tree/master/modules/regex) in Godot is based on PCRE2, but I don't know if there are specific caveats with regexes in Godot.

**Comment by plokmijnuhby** [comment]
Could you add a note to that effect? Perhaps you could point people to [this page](https://perldoc.perl.org/perlreref.html), or [this one](https://www.pcre.org/current/doc/html/pcre2compat.html).

**Comment by bojidar-bg** [comment]
I guess we could also link people to https://www.pcre.org/current/doc/html/pcre2pattern.html.

**Comment by rslepon** [comment]
Version 2.1 documentation (https://docs.godotengine.org/en/2.1/classes/class_regex.html) had a list of supported features:
"Currently supported features:
* Capturing () and non-capturing (?:) groups
* Any character .
* Shorthand character classes \w \W \s \S \d \D
* User-defined character classes such as [A-Za-z]
* Simple quantifiers ?, \* and +
* Range quantifiers {x,y}
* Lazy (non-greedy) quantifiers \*?
* Beginning ^ and end $ anchors
* Alternation |
* Backreferences \1 and \g{1}
* POSIX character classes [[:alnum:]]
* Lookahead (?=), (?!) and lookbehind (?<=), (?<!)
* ASCII \xFF and Unicode \uFFFF code points (in a style similar to Python)
* Word boundaries \b, \B"

Perhaps it could be copied into the 3.x documentation and modified, if necessary. If doing so, note that "\*" above should be "*", and "\*?" above should be "*?", I believe.
