### ISSUE TITLE
Running the game

### ISSUE THREAD

**Issue by Blackhornet2134** [godotengine/godot-docs#2523]
Why is that when ever I run the game first off the screen doesn't even load up, it just sits there in the corner of my screen with the logo. Then if it decides to load the controls (script) doesn't even run I tried re typing the code, new code, and restarting the program nothing changes.

**Comment by clayjohn** [comment]
This is the repo for the Godot documentation. If you are having trouble running the editor try posting on the Godot repo. https://github.com/godotengine/godot

**Comment by bojidar-bg** [comment]
@Blackhornet2134 In case you are still having this problem, please reopen the issue on the [main Godot repository](https://github.com/godotengine/godot), including a sample project and OS specs.
Going to close this one, as it does not appear related to the documentation.
