### ISSUE TITLE
Fix signals section of GDScript documentation

### ISSUE THREAD

**Issue by aspenforest** [godotengine/godot-docs#2526]
**Link to doc: [GDscript signals](http://docs.godotengine.org/en/latest/getting_started/scripting/gdscript/gdscript_basics.html#signals)**

**Problem:**
The signal "data_found" is defined as being able to forward a single parameter variable, while the signal handler is defined as expecting two variables as input from the emit_signal function.

# your_notifier.gd

signal data_found(data)

var your_data = 42

func _process(delta):
   if delta == your_data:
      emit_signal("data_found", your_data)

# your_handler.gd

func your_handler(data, obj):
   print("Your handler was called from: ", obj.get_name(), " with data: ", data)

# your_game.gd

func _ready():
   var notifier = your_notifier.new()
   var handler = your_handler.new()

   notifier.connect("data_found", handler, "your_handler", [notifier])

**Comment by NathanLovato** [comment]
The example doesn't make sense to me, more importantly.

```
   signal data_found(data, obj)

   var your_data = 42

   func _process(delta):
      if delta == your_data:
         emit_signal("data_found", your_data)
```

I think it's more useful to have examples that relate to an actual game, with code that gives some context. I'm preparing a PR to replace the examples

**Comment by aspenforest** [comment]
Thank you Nathan for improving the signals documentation 👍
