### ISSUE TITLE
ArrayMesh takes PoolVector2Array, not PoolRealArray

### ISSUE THREAD

**Issue by raymoo** [godotengine/godot-docs#2530]
The documentation for the UV format of `ArrayMesh` says
```
UV array (array of Vector3 UVs or float array of groups of 2 floats (u,v)).
```
But it actually takes a `PoolVector2Array` rather than a `PoolRealArray`. When I read this initially I thought it meant to pass in a `PoolRealArray` in the format `[u1, v1, u2, v2, ...]`.

**Comment by clayjohn** [comment]
Already fixed in latest: see [here](http://docs.godotengine.org/en/latest/classes/class_arraymesh.html) in PR https://github.com/godotengine/godot/pull/28473
