### ISSUE TITLE
How does SSL work exactly with HTTPRequests?

### ISSUE THREAD

**Issue by aspenforest** [godotengine/godot-docs#2531]
**Issue:**
I'm trying to access a remote API server (website) through HTTPS. 
I do a regular HTTPRequest.request with SSL handshake = true with the websites public key cert pointed to in the project settings, and it fails to connect, returning RESULT_SSL_HANDSHAKE_ERROR.

When I do a request with SSL handshake = false and the cert removed from the project settings, but the URL begins with **https://** it connects fine and I get access to the API (confused).

When I repeat the above experiment with the url beginning with **http://** it gives RESULT_CONNECTION_ERROR. 

How does the remote server register my connection as secure for the second experiment when the SSL handshake has been disabled and the cert removed from project settings, but the API works just fine?

I can't make any sense of this and the documentation about SSL connections is just lacking.

**Comment by Calinou** [comment]
The Godot editor and export templates bundle the [Mozilla certificate bundle](https://github.com/godotengine/godot/blob/master/thirdparty/certs/ca-certificates.crt). Therefore, you don't need to add your own bundle (which will *override* the included bundle).

We should rename the project setting and tweak the ProjectSettings class reference to make this clearer.
