### ISSUE TITLE
"Mouse and input coordinates" example doesn't follow the C# style guide

### ISSUE THREAD

**Issue by Calinou** [godotengine/godot-docs#2540]
In the [Mouse and input coordinates](https://docs.godotengine.org/en/latest/tutorials/inputs/mouse_and_input_coordinates.html) C# example snippet, C# 7.0's operator pattern matching is used, but the [C# style guide](https://github.com/godotengine/godot-docs/blob/master/getting_started/scripting/c_sharp/c_sharp_style_guide.rst) advises to stick to C# 6.0 for now.

*Originally reported here: https://godotengine.org/qa/46714/does-godot-mono-support-operator-pattern-matching-casting*

**Comment by neikeq** [comment]
The style guide was for only for the docs, and we decided long ago to allow C# 7 as well. The style guide doesn't reflect this though.
The error from that QA question is because this user is using MSBuild 14.0. C# 7 requires MSBuild 15.0 or higher.
