### ISSUE TITLE
Missing tutorial for WebSocket 

### ISSUE THREAD

**Issue by qichunren** [godotengine/godot-docs#2546]
There are five tutorials about networking:
* High level multiplayer
* Making HTTP requests
* HTTP client class
* SSL certificates
* WebRTC

http://docs.godotengine.org/en/latest/tutorials/networking/index.html

I guess some people are really waiting to learn about WebSocket topic.
Can we expect a tutorial for it anytime soon?

**Comment by akien-mga** [comment]
I'm sure @faless has this planned for coming weeks already.
