### ISSUE TITLE
JSON.parse("") error code 43 is not documented in the @GlobalScope.Error enum

### ISSUE THREAD

**Issue by aspenforest** [godotengine/godot-docs#2550]
JSON.parse("") returns a JSONParseResult object whose error property is set as 43, which
is not documented in the @GlobalScope.Error enum.

**Comment by bojidar-bg** [comment]
Fixed by https://github.com/godotengine/godot/pull/30120. According to the [now-updated docs](http://docs.godotengine.org/en/latest/classes/class_@globalscope.html#enum-globalscope-error), 43 is `ERR_PARSE_ERROR`
