### ISSUE TITLE
[X11] libpng16 is required but not listed in requirements

### ISSUE THREAD

**Issue by Houkime** [godotengine/godot-docs#2554]
Scons needs libpng16 (named as on debian) to build godot but 

https://github.com/godotengine/godot-docs/blob/master/development/compiling/compiling_for_x11.rst doesn't list it

**Comment by Houkime** [comment]
Oops. It seems like it is an implicit dep, but it wasnt' satisfied because on debian 8 i am building on there is only libpng12.

It is another issue probably then.

**Comment by akien-mga** [comment]
This is a recent change, previously Godot could build against either libpng12 or libpng16. The docs page should be updated accordingly.

**Comment by Houkime** [comment]
There should also be a mention that libpng and freetype can be builtin with for example a flag builtin_libpng=yes.
I found it in the source.

**Comment by akien-mga** [comment]
I'm actually changing default flags to builtin now, so I'll update the docs afterwards.
