### ISSUE TITLE
Confusing Path2d usage in Your first game / outdated info

### ISSUE THREAD

**Issue by epuscasu** [godotengine/godot-docs#2559]
Been going through the docs, got to a part that's confused me (the animated part):
https://docs.godotengine.org/en/3.1/getting_started/step_by_step/your_first_game.html#spawning-mobs

The docs show the three dots on the top left and, with each click, one curve control node is added. This should be the final result:

![image](https://user-images.githubusercontent.com/11788042/59980225-7d1ea100-95fb-11e9-916f-12235cc119fd.png)

Compared to the current behavior, where creating a Path2D displays a point that looks exactly like a curve control point (when actually I think it's the node's bounding box, thanks Discord's @KidsCanCode) and, with every click, way more "control points" appear along the way, leading me to believe I'm duplicating them or not using the correct tool (which, according to the animation, should act more like connecting points instead of creating rectangles). This is the end result:

![image](https://user-images.githubusercontent.com/11788042/59980235-9293cb00-95fb-11e9-9c05-003603f22dd6.png)

I'm thinking this could also be a suggestion for the interface itself - either allow the user to disable the bounding box points or have them differentiated from the actual curve control points.

Also, some other person encountered the same issue a while ago, so more users might do the same while following the docs (https://www.reddit.com/r/godot/comments/9d43nc/need_help_with_path2d/)

**Comment by cbscribe** [comment]
Closing this as it's an editor issue, not a docs one. See https://github.com/godotengine/godot/issues/30012
