### ISSUE TITLE
Need docs on C# and GD Interaction

### ISSUE THREAD

**Issue by exts** [godotengine/godot-docs#2562]
I think I see this question popup every other day and I don't believe we have any documentation on how C# and GD interact with each other. Maybe having a basic guide that explains how to do this and the limitations of the interaction would solve a lot of repeated questions on discord.

I lack experience so I call out on our c# dev's to take on such task :)

**Comment by exts** [comment]
Posted a bounty for this issue: https://www.bountysource.com/issues/76023684-need-docs-on-c-and-gd-interaction

**Comment by paulloz** [comment]
There is some (old-ish) info about that in #1425.
