### ISSUE TITLE
Play a audio file with a script

### ISSUE THREAD

**Issue by Schweini07** [godotengine/godot-docs#2565]
It would be really nice if you could play a audio file with a script. So you don't have to use a AudioStreamPlayer.

**Comment by LikeLakers2** [comment]
First off, if this is a suggestion for the engine as a whole, then that would go in the [engine's repository](https://github.com/godotengine/godot) rather than this (the documentation repository).

Second off, what would be the point of removing the AudioStreamPlayer from the equation?
