### ISSUE TITLE
Add a line length guideline to the GDScript style guide

### ISSUE THREAD

**Issue by Calinou** [godotengine/godot-docs#2567]
Unlike many other languages, the [GDScript style guide](http://docs.godotengine.org/en/latest/getting_started/scripting/gdscript/gdscript_styleguide.html) currently doesn't recommend a maximum line length. We should probably adopt a guideline for this, so that people can write code more consistently across projects.

Values around 80 seem to be quite common in most high-level languages, but in my experience, it tends to feel a bit short when indenting code with tabs (or 4 spaces). This is why some Python formatters such as [Black](https://github.com/ambv/black) default to 88 characters:

> You probably noticed the peculiar default line length.  *Black* defaults to 88 characters per line, which happens to be 10% over 80.  This number was found to produce significantly shorter files than sticking with 80 (the most popular), or even 79 (used by the standard library). In general, [90-ish seems like the wise choice](https://youtu.be/wf-BqAjZb8M?t=260).

If we recommend a line length in the style guide, we can then enable the line length guideline in the script editor by default :slightly_smiling_face:

**Comment by aaronfranke** [comment]
When it comes to programming video games, some things can get unavoidably long, or at least would look less clear if they were shortened. I think it should be a loose guideline for sure, but recommending a maximum amount of columns is a good idea. 80 seems too short, 90 sounds better.

By the way, this could also be added to the C# style guide, but C# code tends to be slightly longer and I'd recommend no less than 100 columns for C#.

We could also include a colored line in the editor, as [some other editors](https://cdn.app.compendium.com/uploads/user/e7c690e8-6ff9-102a-ac6d-e4aebca50425/f4a5b21d-66fa-4885-92bf-c4e81c06d916/File/13c86fa46ba744ab96d830cbd7251071/scala_samples_in_nb.jpg) do, to visually show a recommended maximum width.

**Comment by cbscribe** [comment]
I don't think 80 is unreasonable. It's not supposed to be a hard limit - the purpose is to let you know that you might be trying to do too much on one line. It's a visual reminder to the programmer that "hey, you're getting a bit long there, buddy." It's perfectly acceptable to go past it when necessary.

I did a quick survey of the docs and there isn't much code that goes past it. Even in the VR tutorial, which has some of the deepest nesting, there's only a handful of lines like

    body.apply_impulse((raycast.global_transform.origin - body.global_transform.origin).normalized(), direction_vector * 1.2)

that blow well past any reasonable limit.

I would vote for sticking with 80, but I'd be fine with 88 if that were the consensus too.

> we can then enable the line length guideline in the script editor by default

This is a good suggestion.

> We could also include a colored line in the editor, as some other editors do, to visually show a recommended maximum width.

FYI, this can be enabled in the editor here:

![Screen Shot 2019-06-29 at 9 52 14 AM](https://user-images.githubusercontent.com/3812514/60387119-a607c180-9a53-11e9-9d7f-b27e4553566a.png)

And "Line Length Guideline Color" can be set in the "Highlighting" section.
