### ISSUE TITLE
Inverse Kinematics tutorial is confusing and incomplete

### ISSUE THREAD

**Issue by Xananax** [godotengine/godot-docs#257]
I've had people ask me why they aren't getting IK after implementing the functions in the [Inverse Kinematics Tutorial](http://docs.godotengine.org/en/latest/tutorials/3d/inverse_kinematics.html).

After checking out the tutorial, I told them it has nothing to do with IK. This tutorial merely teaches how to get a parent bone.

It seems it was intended to become a full-fledged IK tutorial, since it has variables names `IK_Error` and `IK_bone_length`, but it ends abruptly after merely teaching how to loop through bones to get parents.

The link at the top (http://freespace.virgin.net/hugo.elias/models/m_ik2.htm) is also dead.

I propose to either:

a) Rename the tutorial to "How to find parent bones", remove the last part about re-parenting, and making it clear that though this is useful _to implement IK_, it's not actually about IK.

b) Remove the tutorial entirely

c) Continue the tutorial?

I realize that finding the parent bone and re-parenting are good tips, but they belong in some snippets section, not in a tutorial.

This is mildly important, imho; One of the things that drove me to Godot was to read in the doc it had IK. I didn't go into details, just read a bit and was reassured, as IK is an essential part of my project. Upon discovering it actually doesn't, I just went "oh well", and I'm working on my own implementation, because I like Godot for other reasons and the lack of native IK is not the end of the world; but other people might get really confused or even angry.

**Comment by Bonfi96** [comment]
I've remade the illustration of the kinematics tutorial and made a [pull request](https://github.com/godotengine/godot-docs/pull/255) yesterday as I noticed that the tutorial was pretty rough. I think that it should be kept as it's useful, but I agree with the fact that it has to be shomehow reshaped.

**Comment by Xananax** [comment]
The new image is definitely better, sure, but...

Maybe I didn't explain myself properly:
As it stands, the tutorial is almost completely unrelated to IK.

So I'd think this image only makes things more confusing. It trumps people into thinking the tutorial will actually tell them how to do IK, when in fact the tutorial is about the specific Godot syntax to walk up a bone chain, and has no other information about IK, nor in general, nor in Godot (apart from a few names of concepts that one has to look up elsewhere).

I don't intend to be harsh, maybe you're the original author, but I'd say, maybe at the very least add a big bold disclaimer that warns that the tutorial is unfinished?

In its current shape, the tutorial does more harm than good. I mod the unofficial Godot Discourse Server, and we've had people ask us a few times why their IK wasn't working, though they had followed the tutorial point by point. We have to then proceed to explain how the tutorial is not about IK, and direct them to other places. As I said earlier, I've been myself victim of this confusion.

**Comment by Bonfi96** [comment]
I'm not the author of the tutorial, I just couldn't stand that sketch. As you said the tutorial doesn't talk about ik, but it could if it got expanded in a meaningful way

**Comment by akien-mga** [comment]
The IK tutorial was contributed by @slapin on the old OpenProject wiki. I then imported it in the new sphinx-based one, and might have renamed it to have a more general name that it had (the original title was very lengthy and not so "documentation"-like). It could be that I chose the new name poorly :)

Ideally we'd want to have a "Community" section in the docs where we gather tutorials from community members that might not be yet of "Official" quality (but might become once they've been worked on enough to be easy to read and straight to the point).

So, PRs welcome to improve this one :)

**Comment by Xananax** [comment]
> PRs welcome

I'm trying to implement my own IK system for 2D (analytical, 2 joints), I might do a write up about it when (if!) I'm done. The maths flies a bit over my head though and I'm not sure I'm the best person to do a write up about something I can barely get to work. I also have not tried at all to do iterative solutions yet. But yes, if when it works, no one has tackled this, I'd be happy to document the process.

**Comment by songproducer** [comment]
Just realised wayback machine has a cache of that article:

http://web.archive.org/web/20160531030510/http://freespace.virgin.net/hugo.elias/models/m_ik2.htm

**Comment by Xananax** [comment]
I'm trying to implement an analytical solution, which the article doesn't help with, but I suck at math.
If someone was willing to shed some light on why what I'm doing is not working:
https://github.com/Xananax/godot_tests

I'd be willing to do a write-up on how to do that.
I do intend to implement an iterative solution too, once that is done.
