### ISSUE TITLE
Following GUI tutorial steps not matching results

### ISSUE THREAD

**Issue by epuscasu** [godotengine/godot-docs#2574]
https://docs.godotengine.org/en/3.1/getting_started/step_by_step/ui_game_user_interface.html#add-the-progress-bar

Adding the TextureProgress node makes the Title and Number nodes to no longer stay centered and don't lead to the result shown in the tutorial:

![image](https://user-images.githubusercontent.com/11788042/60367174-3a433b80-99f6-11e9-9032-f91dee15bf0c.png)

[edit] The next steps also lead to different results.
Some more inconsistencies - https://docs.godotengine.org/en/3.1/_images/ui_gui_step_tutorial_counter_design_4.png

This shows a CenterContainer but nowhere does the tutorial say anything about adding such a node or what it's supposed to do.

The youtube video linked also approaches the whole thing way differently, not sure which one to take as the most recent / accurate way to create GUI's.

**Comment by KarstenHoehne** [comment]
i am getting the same results
