### ISSUE TITLE
Missing documentation on visual scripting editor

### ISSUE THREAD

**Issue by songproducer** [godotengine/godot-docs#258]
I realise it's not official yet, but I'd really like to know how to use this just to do basic things like play an animation, sound or move a character. Can someone who knows how to do simple things with the visual script editor please make a simple tutorial?

**Comment by vnen** [comment]
You might want too look at the demos, it might give some insight: https://github.com/godotengine/godot-demo-projects/tree/master/visual_script

**Comment by songproducer** [comment]
Thanks!

**Comment by cbscribe** [comment]
Closed by e1e18aa14 with additional content underway.

http://docs.godotengine.org/en/latest/learning/scripting/visual_script/visual_script_basics.html
