### ISSUE TITLE
Extend GDScript Basics with a looped Coroutine

### ISSUE THREAD

**Issue by HaSa1002** [godotengine/godot-docs#2583]
I just searched over an hour to find a solution, why coroutines don't work with loops. As I now found out you have to save the new state explicitly. What is different from coroutines I know.

I'd suggest to add an example to the reference (I know it is stated there) and something like the following snippet into the GDScript Basics:
Remember to save the new function state when using multiple yields per funtion:
```
func co_func():
    for i in range(1, 5):
        #Do stuff
        yield()

func _ready():
    var co = co_func()
    while co is GDScriptFunctionState && co.is_valid():
        co = co.resume()
```

**Comment by Xrayez** [comment]
Might also be worth adding a warning about yielding to signals with looping.
https://github.com/godotengine/godot/issues/30269#issuecomment-508260002:
> Also, you don't need to use while, the completed signal is only emitted when the function didn't yield anymore.

Namely:
```gdscript
while co is GDScriptFunctionState::
        co = yield(co, 'completed')
```
is redundant, simple `if` statement is enough:
```gdscript
if co is GDScriptFunctionState::
        co = yield(co, 'completed')
```
(I'd use `while` for consistency though, ehehe).

**Comment by HaSa1002** [comment]
I don't get it. I have to `while` there, 'cause there is more than one `yield`?

**Comment by Xrayez** [comment]
In case of "yielding to a signal", the idea is that you *don't* have to use a while loop. Not sure whether the same could be applied to other types of `yield`ing. In your case you could try the same technique (second snippet). So `yield(co, 'completed')` could essentially replace the need for a while loop.

**Comment by HaSa1002** [comment]
@Xrayez is the warning still required? If so what kind of warning should that be? How should I word the warning. I'm not completly getting how to use the concept and since I don't know I don't know what to write. Personally I think a warning might be useful to tell people that this bug exists in versions prior to 3.2.

**Comment by Xrayez** [comment]
@HaSa1002 I felt like this deserves another PR so I wrote it separately in the next section actually (Coroutines & signals): #2644.

**Comment by HaSa1002** [comment]
Thinking about your example a couple of days now, I realize what confused me: The usage of yield to resume a coroutine. That brings me that, I should update the example to be a bit bigger to show how to use a looped coroutine i.e. with the _process function to not block the the games execution.

**Comment by Xrayez** [comment]
I don't use `resume` that often but I think in your example this is the way it should be done actually, because you're responsible to resume the function manually. The difference with yielding to signals is when once it's emitted, it's resumed automatically for you. Actually here's an example to demonstrate this:

```gdscript
func _ready():
	var co = co_func()
	co.connect('completed', self, '_on_function_completed')

	while co is GDScriptFunctionState && co.is_valid():
		co = co.resume() # still resuming manually

func co_func():
	for i in range(1, 5):
		#Do stuff
		print(i)
		yield()

func _on_function_completed():
	print('done')
```
Prints:
```
1
2
3
4
done
```

**Comment by HaSa1002** [comment]
This was done iirc.
