### ISSUE TITLE
Please explain that assert statements are *removed*, not just ignored in a release build

### ISSUE THREAD

**Issue by sszigeti** [godotengine/godot-docs#2607]
It was my incorrect assumption that I can write code like this:

    assert my_thread.start(self, "_thread_start") == OK

However, in a release build this entire line will be removed so potentially crucial parts of the code can vanish, crippling the build.

If this is true ([as it was explained to me on Reddit](https://www.reddit.com/r/godot/comments/cb7mo7/should_assert_statements_be_used_at_all_removing/etdoamh/)) then I think it would be great if this was better explained in the documentation, both at the assert statement and in sections about exporting.

**Comment by HaSa1002** [comment]
If you'd like check if your thread started correctly only during debug and want your thread to start in a release build, then you would want to do something like this:
```gdscript
var t_res = my_thread.start(self, "_thread_start")
assert(t_res == OK)
```
Ignores in this conext means **not executed**.
Although I'd want to check if the thread runs in a release build too. So I'd add a crippled construct like this:
```gdscript
var t_res = my_thread.start(self, "_thread_start")
if t_res != OK:
   #Catch the error and do something with it. Perhaps this thread is critical?
   print("Thread didn't started")
   #Now you want to debug your build so perhaps add a breakpoint or more likely:
   assert(false)
```
I agree, a simple rephrasing of the explaning sentence in [GDScript Basics](https://docs.godotengine.org/en/3.1/getting_started/scripting/gdscript/gdscript_basics.html?highlight=ignored#assert-keyword)
and an additional sentence in the [reference](https://docs.godotengine.org/en/3.1/classes/class_@gdscript.html?highlight=assert#class-gdscript-method-assert) would be a bit clearer.

**Comment by Calinou** [comment]
This was documented in #2687, closing.
