### ISSUE TITLE
Add to docs info about clang and LLVM packages

### ISSUE THREAD

**Issue by qarmin** [godotengine/godot-docs#2614]
LLVM and clang packages should be added to all os, but for now it is visible only in OpenBSD - https://godot.readthedocs.io/en/latest/development/compiling/compiling_for_x11.html

**Comment by Calinou** [comment]
You need either GCC or Clang to build Godot, not both. GCC is still the recommended option for users, but Clang is better for development as it can be used with LLD (for faster linking) and can provide more helpful errors.
