### ISSUE TITLE
The InputEvent graph is outdated

### ISSUE THREAD

**Issue by Zylann** [godotengine/godot-docs#2619]
http://docs.godotengine.org/en/3.1/tutorials/inputs/inputevent.html

It mentions `_input_event` for GUI, but now it should be `_gui_input`.

**Comment by HaSa1002** [comment]
We should update that and replace the Image perhabs with a SVG Version for future updates? That would ease the further updating of it.

**Comment by HaSa1002** [comment]
Related with #2581
