### ISSUE TITLE
How do you change tiles at runtime?

### ISSUE THREAD

**Issue by modernretrocoder** [godotengine/godot-docs#2632]
I want the player to be able to swap every instance of tile 'X' in a scene with every instance of tile 'Y' in a scene by pressing a button in-game. For example, when the player presses the 'x' key, every 'Black' tile will turn into a 'White' tile and every 'White' tile will turn into a 'Black' tile. How would I go about achieving this? (Both tiles are stored in the same Tilemap.)

**Comment by HaSa1002** [comment]
So first of all your friend the [TileMap API Reference](https://docs.godotengine.org/en/3.1/classes/class_tilemap.html)
I'd try the `get_used_cells_by_id(int id) const` with your black and white tiles. Then iterate on those arrays and use `set_cellv(...)` with the iteration element and the tile id.

**Comment by Nutriz** [comment]
No issue here, so...to close ?
