### ISSUE TITLE
No documentation for TriangleMesh

### ISSUE THREAD

**Issue by daemeh** [godotengine/godot-docs#2653]
I can see the C++ interface for TriangleMesh in the Godot source code, but I can't figure out what the GDScript interface is(the help page is empty) - for example how do I get the vertices?

**Comment by clayjohn** [comment]
TriangleMesh is not meant to be accessed by users directly. It is only used internally for some physics operations. 

You are likely mixing it up with the [ArrayMesh](http://docs.godotengine.org/en/latest/classes/class_arraymesh.html) which provides access to a mesh directly where you can edit its vertices etc.

**Comment by daemeh** [comment]
Indeed, thank you. I'm using ArrayMesh to access vertices now.
