### ISSUE TITLE
Clean up use of "idle", "fixed", "physics", etc. when talking about process mode.

### ISSUE THREAD

**Issue by vortexofdoom** [godotengine/godot-docs#2660]
Started this issue as a place to document all the times that I find potentially confusing references to the process mode of various classes. Anyone else is welcome to chime in/add suggestions for how to potentially resolve this.

https://docs.godotengine.org/en/3.1/classes/class_kinematicbody2d.html#class-kinematicbody2d - mentions "fixed" process mode when no such mode exists, presumably means physics.

**Comment by cbscribe** [comment]
Good catch, although a with a quick grep through the xml, I don't find any other references besides the KinematicBody/KinematicBody2D one, at least in the API reference. There could be more in the godot-docs repo.

**Comment by Calinou** [comment]
I can't find too many confusing references to fixed process mode nowadays, so I'll close this.
