### ISSUE TITLE
Include filename in class reference

### ISSUE THREAD

**Issue by SeleckyErik** [godotengine/godot-docs#2663]
Oftentimes I use the `Class Reference` section of the docs to get an idea of what functionality this or that class supports. However, there are cases when either the doumentation is not sufficient or I want or need to know the exact implementation details and I need to look at the source code. That's when I would find it helpful if each of the class reference pages listed which file is the class located in since the filename doesn't always match the class name.

**Comment by bojidar-bg** [comment]
Duplicate of #1847.
