### ISSUE TITLE
Fix warnings reported by Sphinx

### ISSUE THREAD

**Issue by Calinou** [godotengine/godot-docs#2664]
Sphinx currently emits several warnings when building HTML documentation:

```text
.../classes/class_gdnativelibrary.rst:33: WARNING: Unknown target name: "godot".
.../classes/class_gdnativelibrary.rst:99: WARNING: Unknown target name: "godot".
.../index.rst:63: WARNING: Undefined substitution referenced: "weblate_widget".
.../community/contributing/pr_workflow.rst:384: WARNING: Could not lex literal_block as "shell". Highlighting skipped.
.../community/contributing/pr_workflow.rst:397: WARNING: Could not lex literal_block as "shell". Highlighting skipped.
```

We should aim to fix these, so that we can set up continuous integration using Sphinx's strict mode (`-W`, which turns warnings into errors).

**Comment by Calinou** [comment]
It seems the warnings in `class_gdnativelibrary.rst` can be fixed by replacing `"godot_"` with `"godot\_"`. This should be changed in `makerst.py` somehow.

**Comment by cur33** [comment]
I've been looking into this issue since it seems like no one else is. It's a weird one, since it seems so easy to fix. I noticed that `makerst.py` has a function called `rstize_text` which escapes text, and it seems to work well enough to just call that on the `PropertyDef.default_value.name` field after checking that the field isn't None. Is that a sufficient solution, or should it be more sophisticated?

**Comment by cur33** [comment]
I only tested it on that one XML file, so I'm working on testing it on the whole repo (I have to finish setting it up since this is my first time working on it).

**Comment by Calinou** [comment]
For reference, here are the warnings as of 2020-07-09 we need to fix to enable strict mode on GitHub Actions:

```text
/home/runner/work/godot-docs/godot-docs/classes/class_basematerial3d.rst:26: WARNING: unknown document: ../tutorials/3d/spatial_material
/home/runner/work/godot-docs/godot-docs/tutorials/3d/csg_tools.rst:252: WARNING: undefined label: doc_spatial_material (if the link has no caption the label must precede a section header)
/home/runner/work/godot-docs/godot-docs/tutorials/misc/gles2_gles3_differences.rst:92: WARNING: undefined label: class_bakedlightmap (if the link has no caption the label must precede a section header)
```

**Comment by NathanLovato** [comment]
Is this issue still relevant?

**Comment by Calinou** [comment]
@NathanLovato We now build docs on CI using the `-W` sphinx-build option, which turns warnings into errors. Since CI is passing fine lately, we can now close this.
