### ISSUE TITLE
SpringArm node lesson

### ISSUE THREAD

**Issue by Mintormo** [godotengine/godot-docs#2673]
In Godot 3.1 there is a new node SpringArm to which there are no lessons, examples and descriptions in the documentation. Could you add all this?

**Comment by tetrapod00** [comment]
Resolved by https://github.com/godotengine/godot-docs/pull/10156. This can be closed.

**Comment by tetrapod00** [comment]
Closing as resolved by https://github.com/godotengine/godot-docs/pull/10156.
