### ISSUE TITLE
Compiling for X11 (Linux, *BSD)

### ISSUE THREAD

**Issue by ricardoalcantara** [godotengine/godot-docs#2679]
Reading the documentation for "Compiling for X11 (Linux, *BSD)" on PopOS, distro based on Ubuntu, I installed all the Distro-specific oneliners but even after that I got this error:
Package freetype2 was not found...No package 'freetype2' found

I fixed that by installing this lib: libfreetype6-dev

apt install libfreetype6-dev

Is it just my distro or should it be documented too?

**Comment by akien-mga** [comment]
It's not needed anymore in the master or 3.1 branches as the bundled version is built automatically.

**Comment by ricardoalcantara** [comment]
I compiled the version 3.1.1 from this link

https://downloads.tuxfamily.org/godotengine/3.1.1/godot-3.1.1-stable.tar.xz

![image](https://user-images.githubusercontent.com/2466466/62503053-e2ec7400-b7c8-11e9-8866-5a86d3b8d5ad.png)

**Comment by akien-mga** [comment]
That's only a temporary issue, 3.1.2+ will no longer use system freetype by default.

If you do custom builds that you want to distribute on different distros, you should likely also use `builtin_freetype=yes builtin_libpng=yes builtin_zlib=yes` (which are the only three dependencies which were taken from the system before 3.1.2).

I'll readd it to the `3.1` docs to prevent confusion though.

**Comment by akien-mga** [comment]
Fixed by 0d0baba5.
