### ISSUE TITLE
Optimizing Viewports with VisualServer

### ISSUE THREAD

**Issue by clayjohn** [godotengine/godot-docs#2688]
I'm going to put together a tutorial on using a Viewport through the VisualServer to generate textures while loading. 

This method is faster than the typical Viewport method when you are generating textures at load time. However, it stalls the main thread while generating so it is not as good when you need to generate textures while the game is running. 

https://gist.github.com/clayjohn/80d9b1e52e1b9a23445504e85a8d7890

**Comment by skyace65** [comment]
Closing this issue as it's been open for several years, and there doesn't need to be a issue created before a page can be created.
