### ISSUE TITLE
Step by Step >> Your first game: Simplify choosing animations code

### ISSUE THREAD

**Issue by frsrz** [godotengine/godot-docs#2700]
[https://docs.godotengine.org/en/3.1/getting_started/step_by_step/your_first_game.html](url)

May I suggest changing 'choosing animations' code from:

![imagen](https://user-images.githubusercontent.com/238637/62890999-ef327d00-bd44-11e9-9d61-9fcead5d8da5.png)

to:

![imagen](https://user-images.githubusercontent.com/238637/62891049-0b361e80-bd45-11e9-92d7-73686d11c118.png)

IMHO is simpler and results in a more attractive player movement.

**Comment by mhilbrunner** [comment]
cc @cbscribe

**Comment by cbscribe** [comment]
Closing, as the code has been revised multiple times since this issue was opened.
