### ISSUE TITLE
Services for iOS -- More detail for IAP

### ISSUE THREAD

**Issue by GraigR** [godotengine/godot-docs#2715]
Services for iOS, particularly for IAP, would benefit from more detail. Currently I'm trying to implement and finding consistent issues I cannot resolve (for example consumable purchases being restored on opening app etc). The issues don't seem to be Apple-side.
In any case, the current documentation assumes too much knowledge on the part of the developer, and tutorial-style walkthru for both consumable and non-consumable IAPs would be very much appreciated.

**Comment by Toshiwoz** [comment]
Hi, I'm glad you decided to open an issue here, I'm just adding this link to what I've found about IOS IAP:
https://docs.godotengine.org/en/3.1/tutorials/platform/services_for_ios.html
If there are other references in the official documentation that would be helpful... I think.

**Comment by GraigR** [comment]
Someone on reddit pointed me to this: https://github.com/godotengine/godot/issues/25718

This is likely the source of many issues, but isn’t documented at all. I think at least auto finish and finish methods need to be added to the docs ASAP

**Comment by stonekase** [comment]
Anyone here know how i can access GameCenter.request_identity_verification_signature(); in grscript? It appears to return 0 instead of a dictionary.

**Comment by Xioor** [comment]
https://github.com/godotengine/godot-docs/pull/4465

**Comment by skyace65** [comment]
This was fixed by #4465. Closing this issue.
