### ISSUE TITLE
section headings

### ISSUE THREAD

**Issue by approxdec** [godotengine/godot-docs#2716]
hello.
there is Suggestion for restructuring the docs #1589
but my request is more simple.
the web docs have headings
GENERAL
GETTING STARTED
TUTORIALS
DEVELOPMENT
COMMUNITY
CLASS REFERENCE
could they please be included in the compilation of the pdf 
and i suppose that also means the epub?
this would help in referencing between the web docs and a personal .pdf version.

**Comment by Calinou** [comment]
We don't have control over how PDFs are generated by Sphinx, so I'm afraid we can't change that. Moreover, PDF builds are currently disabled as they were taking too much time on Read the Docs' servers.
