### ISSUE TITLE
Signals: Mention the posibility to use arguments and include an example in the Step by Step

### ISSUE THREAD

**Issue by golddotasksquestions** [godotengine/godot-docs#2721]
Signals are one of the biggest question marks for newcomers to Godot and the [Step by Step tutorial](https://docs.godotengine.org/en/3.1/getting_started/step_by_step/signals.html) is widely shared and appreciated. However does not even mention the signals most powerful feature: to send along arguments of various kinds!

I became aware of it only much later when I randomly stumbled on this Q&A:
https://godotengine.org/qa/6755/user-signals-with-arguments

It would be nice to have it mention under custom signals along with an example

**Comment by oldmerkum** [comment]
https://docs.godotengine.org/en/latest/getting_started/scripting/gdscript/gdscript_basics.html#data
See _Signals_ within the _Data_ subsection.

Maybe a restructure of the _Signals_ topic?

**Comment by oldmerkum** [comment]
See issue #2629 for a discussion on organizing the documentation of _Signals_.

**Comment by golddotasksquestions** [comment]
Thanks for pointing out the mention of arguments in the GDScrip-Basics page. The problem with this imho: https://github.com/godotengine/godot-docs/issues/2735

**Comment by oldmerkum** [comment]
Yes, I was actually looking at that issue you started too.
Kind of difficult to even know where to start with that one...

**Comment by Calinou** [comment]
This was done in #2886, closing.
