### ISSUE TITLE
The shading language docs for 3.1 are missing

### ISSUE THREAD

**Issue by Keelar** [godotengine/godot-docs#2724]
When viewing the [3.0 docs](http://docs.godotengine.org/en/3.0/tutorials/shading/shading_language.html) at the top it says:

> You are not reading the most recent version of this documentation. [3.1](http://docs.godotengine.org/en/3.1/tutorials/shading/shading_language.html) is the latest version available.

but when going to that page it says:

> SORRY. This page does not exist yet.

**Comment by akien-mga** [comment]
It was renamed to http://docs.godotengine.org/en/3.1/tutorials/shading/shading_reference/index.html

ReadTheDocs doesn't allow to add redirects only for specific versions, so this can't be fixed.
