### ISSUE TITLE
Improve Transform2D tutorial or class documentation

### ISSUE THREAD

**Issue by golddotasksquestions** [godotengine/godot-docs#2726]
I'm trying to figure out how to skew a Sprite with Transform 2D, as it was suggested by @bojidar-bg  [here](https://github.com/godotengine/godot/issues/31742#issuecomment-525743140).

Problem is the [ Transform2D class docs](https://docs.godotengine.org/en/3.1/classes/class_transform2d.html#class-transform2d-method-affine-inverse) are in are written in a language I don't speak, and the [tutorial ](https://docs.godotengine.org/en/3.1/tutorials/math/matrices_and_transforms.html)is also not much better:

```
Affine inverse

The affine inverse is a matrix that does the inverse operation of another matrix, 
no matter if the matrix has scale or the axis vectors are not orthogonal. 
The affine inverse is calculated with the affine_inverse() method:

var mi = m.affine_inverse()
pos = m.xform(pos)
pos = mi.xform(pos)
# pos is unchanged

If the matrix is orthonormal, then:

# if m is orthonormal, then
pos = mi.xform(pos)
# is the same is
pos = m.xform_inv(pos)
```

So I still don't know how to skew.
A skew example would be nice. Especially since the only alternative to skew anything apparently is to write Shader code which is not much easier either.

> A matrix is used similarly to a turtle. The turtle most likely had a matrix inside (and you are likely learning this many years after discovering Santa is not real).

???

**Comment by golddotasksquestions** [comment]
Thank you for your reply and taking the time to clean up these docs!
I am aware this is Linear Algebra and someone with a math background will be able to follow this tutorial.
However all I want it to do is to skew a Sprite. Do you think it should be a requirement to have studied math or GLSL in order to skew a Sprite in Godot?
I think it's fine that this is not already built into the Godot editor (though of course I would prefer if it was), we cannot have everything at once, 
But if the only way to do it is the hard way, I would be at least hope this route is explained somewhere to the regular folk. Skewing is not something that obscure or rare. Even your parents did it, to make you. ;)

**Comment by aaronfranke** [comment]
The matrices and transforms tutorial does need serious updating, see also #1353 and #2174

> A matrix is used similarly to a turtle. The turtle most likely had a matrix inside (and you are likely learning this many years after discovering Santa is not real).

What in the world? It seems that this has existed since back when the docs repo began. In any case, that's got to go, and I think I'll rewrite this article this weekend.

But to provide some immediate help:

Skew the sprite to lean left: t.x = (1, 0) t.y = (1, 1) (for right, make t.y.x negative)

Skew the sprite to be vertically distorted: t.x = (1, 1) t.y = (0, 1) (likewise you can negate t.x.y)

**Comment by golddotasksquestions** [comment]
Thank you!

**Comment by cbscribe** [comment]
> and I think I'll rewrite this article this weekend.

That will be fantastic. Tag me when you submit the PR and I'll review.

Please feel free to use anything from here if it's helpful:
http://kidscancode.org/godot_recipes/math/transforms/

**Comment by Giwayume** [comment]
For those wondering, to skew a 2D matrix in the X or Y axis by a certain number of degrees [as can be done in CSS](https://developer.mozilla.org/en-US/docs/Web/CSS/transform-function/skewX), use these functions:

```
func skew_x(transform: Transform2D, degrees: float) -> Transform2D:
	transform.y.x += transform.x.x * tan(deg2rad(degrees))
	return transform

func skew_y(transform: Transform2D, degrees: float) -> Transform2D:
	transform.x.y += transform.y.y * tan(deg2rad(degrees))
	return transform
```
