### ISSUE TITLE
instantiated segment2d keep updating their position

### ISSUE THREAD

**Issue by sooonism** [godotengine/godot-docs#2728]
I am new to godot and I faced some issues, not sure if is godot 3.1 bug.

![spider_bug001](https://user-images.githubusercontent.com/2647094/63924581-172b1b80-ca7b-11e9-9eae-968ae0652cb4.gif)

i want to instantiate an area2d node with child collider(segment2d, green line) and line2d(purple line). as you can see my purple line is instantiated correctly, but the green line(segment2d collider) keeps changing its position whenever the new instance called.
but what i do is just instantiate area2d(parent) and change the point vectors for both children, purple line and green line(intentionally offset X to easy to see). Somehow the old greenline will take the new position with the new greenline.

`var s = silk.instance()
	silkcontainer.add_child(s)
	s.line.set_point_position(0,start)
	s.line.set_point_position(1,end)
	s.detect.shape.set_a(start + Vector2(10,0))
	s.detect.shape.set_b(end  + Vector2(10,0))`

and my node setup for silk:
<img width="237" alt="Screen Shot 2019-08-29 at 4 42 59 PM" src="https://user-images.githubusercontent.com/2647094/63925227-468e5800-ca7c-11e9-894d-d90b52ac51d5.png">

**Comment by bojidar-bg** [comment]
Try moving the whole collision shape, instead of modifying the collision shape's shape. If you have to modify the shape, make it "Local to Scene" or manually duplicate the resource every time you make an instance.

This is needed since Resource-s are passed by reference even when instancing a scene.

**Comment by sooonism** [comment]
@bojidar-bg Wow, it took me a while to find that "Local to Scene" in the Inspector/Recourse. Thanks, you are a big help.

**Comment by skyace65** [comment]
For future reference engine bugs should be reported here https://github.com/godotengine/godot/issues . This place is for any issues with the documentation.
