### ISSUE TITLE
Document the plugin creation dialog

### ISSUE THREAD

**Issue by merumelu** [godotengine/godot-docs#2732]
The editor has a GUI dialog that was added a while ago which creates all files neccessary for an editor plugin. The editor plugin tutorials should be updated to mention this dialog.

**Comment by skyace65** [comment]
Where is this dialog? I can't find it

**Comment by willnationsdev** [comment]
@skyace65 When you go to the Project Settings' plugins tab, in the top-right is a "Create" button. Clicking that button will now open a dialog for generating the boilerplate necessary for a plugin.
