### ISSUE TITLE
Document exporting projects for macOS (with code signing)

### ISSUE THREAD

**Issue by Calinou** [godotengine/godot-docs#2739]
Now that [code signing is supported](https://github.com/godotengine/godot/pull/9468), we should have a page dedicated to exporting for macOS. The page would document how to sign projects for macOS (and other OS-specific caveats, if any).

@BastiaanOlij Has anything changed in macOS code signing since the pull request was merged? I'd like your input on this :slightly_smiling_face:

**Comment by BastiaanOlij** [comment]
Owh that is going back down memory lane :)

No I think the code signing process is still the same but the next macOS will introduce notarising an application. I have not yet had time to dive into that, will soon have to for work so I'll let you know what I learn :)

**Comment by Calinou** [comment]
It would also be interesting to document how to debug an exported project (that is, running it from a terminal while getting standard output).

**Comment by jamie-pate** [comment]
I found this script related to exporting, notarizing and signing:
https://gist.github.com/johngirvin/4e0fdc1e3651c3f15fc491810ecd911a

**Comment by dploeger** [comment]
Would this also include documentation about how the entitlements need to be set up? Basically, how the complete section in the exporter works?

![2020-12-08 at 12 28](https://user-images.githubusercontent.com/203453/101478392-e6f64c00-3950-11eb-8a51-6dcfe2d7cea7.png)

**Comment by dploeger** [comment]
Ah, looking at the referenced issue, there's also some hints on these points. Maybe we can find an Apple site that documents those things and link to it.

**Comment by dploeger** [comment]
Well, actually those are the available entitlements, right? https://developer.apple.com/documentation/bundleresources/entitlements

Hm. Maybe we could even optimize that by creating that plist file directly from Godot. It can be just Xml really if I'm not mistaken. But that should be an issue in the engine project, right?

**Comment by Calinou** [comment]
> The tooltips there are pretty empty currently. smile

We can't have tooltips for export preset settings currently.

**Comment by skyace65** [comment]
This was fixed by #5105 and can be closed
