### ISSUE TITLE
Incorrect screenshot in tutorial?

### ISSUE THREAD

**Issue by 1vanK** [godotengine/godot-docs#2745]
https://github.com/godotengine/godot-docs/blob/master/tutorials/animation/cutout_animation.rst

> Create a RemoteTransform2D node as a child of the torso. Call it remote_arm_l. Create another RemoteTransform2D node inside the first and call it remote_hand_l.

But on screenshot remote_Arm_l and remote_arm_l

**Comment by clayjohn** [comment]
Looks like one screenshot is off. The one below has the correct names. So may be best to just make a note under the image in the tutorial rather than redoing all the images and gifs.

**Comment by Nutriz** [comment]
If I understand, there is only one wrong screenshot, so why we can't just edit it or take a new one ?
If it's ok i can do it. I just have to build a new tree of Sprites/RemoteTransform2D nodes, take a screenshot of it and mix that with the left part of [this screenshot](https://github.com/godotengine/godot-docs/blob/master/tutorials/animation/img/tuto_cutout9.png)
