### ISSUE TITLE
Clarify autoloading scripts on the documentation.

### ISSUE THREAD

**Issue by carllacan** [godotengine/godot-docs#2752]
The [documentation on Autoload](https://docs.godotengine.org/en/3.1/getting_started/step_by_step/singletons_autoload.html) states:

> You can use AutoLoad to load a scene or a script that inherits from Node. Note: when autoloading a script, a Node will be created and the script will be attached to it. This node will be added to the root viewport before any other scenes are loaded.

From this paragraph I (wrongly) understood that you can Autoload any script, and that if that script does not inherit from Node then a Node will be created anyway and added to the root.

I created a script that inherited from Object and was confused why it wasn't Autoloading. That was 100% my fault for misunderstanding the documentation, of course, but I would not have lost so much time if it had stated something like the following:

> You can use AutoLoad to load a scene or a script. Since the object instantiated from the script will be added to the viewport your script must inherit from Node.

Additionally: perhaps a warning that you are trying to autoload something that is not a Scene or a Node-inheriting script could be very useful.

**Comment by oldmerkum** [comment]
> You can use AutoLoad to load a scene or a script that inherits from Node.

It already says that if your scene or script inherits from Node, then autoload will work. It should be inferred that if your scene or script does not inherit from Node, then be prepared to bang your head against a wall trying to debug why autoload does not work.

**Comment by Calinou** [comment]
Shouldn't the engine itself print an error message when attempting to autoload a script that doesn't extend from Node or any of its descendents?

**Comment by akien-mga** [comment]
It does in 3.2:
![Screenshot_20200313_115533](https://user-images.githubusercontent.com/4701338/76615064-8fda5c80-6521-11ea-9ac9-521051b470ad.png)
