### ISSUE TITLE
Document DUPLICATE_USE_INSTANCING

### ISSUE THREAD

**Issue by rcorre** [godotengine/godot-docs#2770]
The [DUPLICATE_USE_INSTANCING](http://docs.godotengine.org/en/latest/classes/class_node.html#enumerations) flag for [`Node.duplicate`](http://docs.godotengine.org/en/latest/classes/class_node.html#class-node-method-duplicate) just says:

> Duplicate using instancing

What does this mean? What would it mean to duplicate an object without instancing?

**Comment by Jummit** [comment]
I think the difference is like duplicating a scene file and inheriting it.

**Comment by alexchond** [comment]
I added some details.
Pushing now

**Comment by Meriipu** [comment]
This might have been fixed in the committed pull request? Only issue I see is there is a newline which detaches the added clarification from the specific enum flag a bit.

**Comment by Calinou** [comment]
@Meriipu Indeed. I'll close this as resolved. Thanks for bringing it to my attention :slightly_smiling_face:
