### ISSUE TITLE
Document the difference between get_node and get_node_or_null

### ISSUE THREAD

**Issue by rcorre** [godotengine/godot-docs#2771]
[`get_node_or_null`](http://docs.godotengine.org/en/latest/classes/class_node.html#class-node-method-get-node-or-null) says:

> Similar to get_node, but does not raise an error if path does not point to a valid Node.

[`get_node`](http://docs.godotengine.org/en/latest/classes/class_node.html#class-node-method-get-node) says:

> If the path does not exist, a null instance is returned

This seems contradictory. The former suggests `get_node` will throw an error on an invalid path, but the latter suggest it returns `null`, making both of these functions apparently the same.

**Comment by Calinou** [comment]
This was cleared up in the documentation: https://github.com/godotengine/godot/blob/a1fcac640061c45e9dc55b1189e82aed3e2672fb/doc/classes/Node.xml#L252-L253

**Comment by rcorre** [comment]
I looked into it some more and realized that _both_ return `null`, but `get_node` will _log_ and error To me, logging an error is very different from "raising" an error). The latter suggests that it will actually halt execution, which is not true in this case, but is true in other places "raise an error" is used, e.g.:

https://docs.godotengine.org/en/3.1/getting_started/scripting/gdscript/gdscript_basics.html#variables:

> trying to assign an incompatible value will raise an error

I tried to clarify this in https://github.com/rcorre/godot/commit/38fc09e6696b46cf5839e25dac5d19d6f03018fc but just realized I referenced the wrong issue.

**Comment by Calinou** [comment]
@rcorre I think it would make sense to make `get_node()` failures raise an error in 4.0 (i.e. stopping the project execution when running it from the editor).

**Comment by Calinou** [comment]
@rcorre Did you open a pull request for https://github.com/rcorre/godot/commit/38fc09e6696b46cf5839e25dac5d19d6f03018fc? If so, could you link to it so I can close this? Thanks in advance :slightly_smiling_face:

**Comment by rcorre** [comment]
@Calinou oops, I apparently never did. I have now :)
