### ISSUE TITLE
Update the documentation for generating Android build templates

### ISSUE THREAD

**Issue by m4gr3d** [godotengine/godot-docs#2773]
Following [PR #31919](https://github.com/godotengine/godot/pull/31919), there's a new gradle command to generate the Android build templates.

The documentation should thus be updated accordingly.

**Comment by m4gr3d** [comment]
Note: In the process, I'll also update the IDE setup documentation to include Android Studio.

**Comment by akien-mga** [comment]
Fixed by #2796.
