### ISSUE TITLE
Time is too long to build html files and to load online pages

### ISSUE THREAD

**Issue by Rindbee** [godotengine/godot-docs#2779]
When using `make html`, we can use sphinx-build with `-j` option. And it's easy to get the number of cores for threaded build. 
Each html files has a long toctree list (more than 700 lines, even the context is short). Maybe we can set `collapse_navigation = True`.
It's not a good idea to put all class refences in a directory, it's hard to find the relationships among them. Maybe it's better to use toctree to map the inherited relation, eg, create a directory for `Object`, move `class_object.rst` to `object/index.rst`; then create a directory for `JSON`, move `class_json.rst` to `object/json/index.rst`, the same as other class refences.
I hope I have already made it clear, and it's useful.

**Comment by Calinou** [comment]
@Rindbee Is this better now that #2780 has been merged? It makes clean builds much faster on my i7-6700K.

**Comment by Rindbee** [comment]
yes，
