### ISSUE TITLE
"standalone" feature tag doesn't seem to exist

### ISSUE THREAD

**Issue by homer666** [godotengine/godot-docs#2782]
The documentation page on [feature tags](https://docs.godotengine.org/en/latest/getting_started/workflow/export/feature_tags.html) mentions a tag called "standalone", which is for non-editor builds (in effect, any exported game). It doesn't actually appear in the "Override For..." dropdown in project settings though, neither in the screenshot on that page or in the latest build (godotengine/godot@b671b6ad2). It also doesn't appear as a default feature tag in any export presets. I don't know if this is a documentation error or a missing feature.

**Comment by Calinou** [comment]
> It doesn't actually appear in the "Override For..." dropdown in project settings though, neither in the screenshot on that page or in the latest build (godotengine/godot@b671b6a).

I forgot to add them to the "Override For..." dropdown when implementing them in https://github.com/godotengine/godot/pull/20464. I'll work on it :slightly_smiling_face:

> It also doesn't appear as a default feature tag in any export presets. I don't know if this is a documentation error or a missing feature.

Since it's always defined and can't be removed, it doesn't appear in the export presets' additional feature tags list.
