### ISSUE TITLE
Expand Variant Class doc entry

### ISSUE THREAD

**Issue by Feniks-Gaming** [godotengine/godot-docs#2788]
Currently Variant class states that it is most important data type in Godot but then has 3 line long description that tells me nothing about it . For the "most important data type" it's rather bare bones I have still no idea what it is why would I ever want to use it or even how to use it.

**Comment by Torguen** [comment]
I was also seeing that documentation.
I understood that Variant can save many types of data but nothing else.
I don't understand what a difference there is between Variant and Godot.Collections.Array

**Comment by Calinou** [comment]
I'll close this issue as https://github.com/godotengine/godot/pull/32900 was merged.
