### ISSUE TITLE
encrypting save games page should not use OS.get_unique_ID() until implemented

### ISSUE THREAD

**Issue by razvanc-r** [godotengine/godot-docs#280]
http://docs.godotengine.org/en/stable/tutorials/engine/encrypting_save_games.html talks about `OS.get_unique_ID()` but looking at `core/os/os.cpp` the implementation is simply:

```cpp
String OS::get_unique_ID() const {

    ERR_FAIL_V("");
}
```

missing... this should be fixed immediately, I mean the docs.

*edit*: correction, it has to be specified explicitly that `get_unique_ID` only works on Android and iOS for now.

**Comment by solfen** [comment]
fix attempt in pull request #284
