### ISSUE TITLE
HTTPRequest can't load images

### ISSUE THREAD

**Issue by maksimp04** [godotengine/godot-docs#2800]
download_ready() signal returns 0 bytes in "body" argument. Tried to use several links, same result.

**Comment by Calinou** [comment]
Does it work when you attach the following script to any node?

```gdscript
func _ready():
    # Create an HTTP request node and connect its completion signal
    var http_request = HTTPRequest.new()
    add_child(http_request)
    http_request.connect("request_completed", self, "_http_request_completed")

    # Perform the HTTP request. The URL below returns a PNG image as of writing.
    var http_error = http_request.request("https://via.placeholder.com/500")
    if http_error != OK:
        print("An error occurred in the HTTP request.")

# Called when the HTTP request is completed.
func _http_request_completed(result, response_code, headers, body):
    var image = Image.new()
    var image_error = image.load_png_from_buffer(body)
    if image_error != OK:
        print("An error occurred while trying to display the image.")

    var texture = ImageTexture.new()
    texture.create_from_image(image)

    # Assign to the child TextureRect node
    $TextureRect.texture = texture
```

**Comment by maksimp04** [comment]
> Does it work when you attach the following script to any node? (Make sure to add a TextureRect child to the node.)
> 
> ```gdscript
> func _ready():
>     # Create an HTTP request node and connect its completion signal
>     var http_request = HTTPRequest.new()
>     add_child(http_request)
>     http_request.connect("request_completed", self, "_http_request_completed")
> 
>     # Perform the HTTP request. The URL below returns a PNG image as of writing.
>     var http_error = http_request.request("https://via.placeholder.com/500")
>     if http_error != OK:
>         print("An error occurred in the HTTP request.")
> 
> # Called when the HTTP request is completed.
> func _http_request_completed(result, response_code, headers, body):
>     var image = Image.new()
>     var image_error = image.load_png_from_buffer(body)
>     if image_error != OK:
>         print("An error occurred while trying to display the image.")
> 
>     var texture = ImageTexture.new()
>     texture.create_from_image(image)
> 
>     # Assign to the child TextureRect node
>     $TextureRect.texture = texture
> ```
> 
> (taken from [Unpackaged images question on the Godot Q&A](https://godotengine.org/qa/40181/unpackaged-images-question?show=40229#a40229))

Hi! The piece of code that you send was very useful! Thanks! But I don't properly understand the solution, i think that's because I removed "Download file" string from HTTPRequest paremeter.
