### ISSUE TITLE
Document graphics rendering quirks (OpenGL, Vulkan)

### ISSUE THREAD

**Issue by clayjohn** [godotengine/godot-docs#2808]
As discussed in https://github.com/godotengine/godot/issues/17234

Often we run into "bugs" that are in actual fact just quirks relating to how OpenGL or computer graphics work in general. It would be useful to document some common ones in one place.

cc @zireael07

**Comment by Calinou** [comment]
Some items to document could be:

- Line widths when using line drawing
- Transparency sorting
- Z-fighting
- MSAA limitations (specifically, what it *doesn't* work on)
