### ISSUE TITLE
EMPHASISE the importance of release_debug target

### ISSUE THREAD

**Issue by KoBeWi** [godotengine/godot-docs#2813]
And by EMPHASISE I mean **E M P H A S I S E**.

See this https://github.com/godotengine/godot/issues/32476 and this https://github.com/godotengine/godot/issues/32195. More issues like these can appear, so docs should clearly say that the default build is slower unless you use `release_debug` target. Also it should mention that different targets have different names (https://github.com/godotengine/godot/issues/32195#issuecomment-533545978).

I myself learned about this, like, last month >_>

**Comment by Calinou** [comment]
I'm of the opinion that we should build optimized release builds by default, but this would break existing build scripts :slightly_smiling_face:

We should change the note on "Compiling for X11" to be a warning so it's more prominent. Once this is done, we should copy it to other compiling pages.

**Comment by follower** [comment]
Would it also be helpful to provide a warning message in the build script output? (And maybe also warn if there are multiple binaries?)

I mean, no one reads documentation, right? :D (Or, for that matter, tool output... :D )

**Comment by KoBeWi** [comment]
> I mean, no one reads documentation, right?

Actually, if you don't read this part of documentation, you won't know how to compile the engine (assuming you don't use some third-party tutorial). So the idea is to make sure that EVERYONE who reads how to compile would know that their build will be slower by default.

**Comment by KoBeWi** [comment]
The equivalent of "release_debug" is now default after the recent buildsystem rework, so closing.
