### ISSUE TITLE
Note where the "keytool" and "adb" commands are located on windows

### ISSUE THREAD

**Issue by nice-shot** [godotengine/godot-docs#2830]
In the step-by-step exporting guide (https://docs.godotengine.org/en/3.1/getting_started/step_by_step/exporting.html) under the android section, the docs say to run the "keytool" and the "adb" command with a few parameters.
When doing a fresh install of Java and Android Studio on windows, these commands will not be added to the command line.
I suggest either mentioning where to find these binaries on Windows or referencing a guide on how to add them to the PATH environment variable. I'm not sure about Mac but I think a similar issue exists there as well.

**Comment by nice-shot** [comment]
It's also worth mentioning that the keytool command requires the user to run cmd as adminstrator

**Comment by Calinou** [comment]
> It's also worth mentioning that the keytool command requires the user to run cmd as adminstrator

Why would this be necessary? As long as you specify an output path that is writeable to by the current user, you shouldn't have to run it as an administrator.

**Comment by nice-shot** [comment]
Oh, then maybe it was my mistake. I think I ran the command inside the Java folder which needs admin access.
In general the docs do state that exporting to mobile may require more searching and experimentation but right now, a novice windows user who just wants to export to android will definitely encounter problems if he follows the current instructions.

**Comment by follower** [comment]
BTW typo in issue title: "abd" -> "adb"

**Comment by skyace65** [comment]
@Calinou this page was removed with #4886. I think this issue can be closed.
