### ISSUE TITLE
Use Babel for translation?

### ISSUE THREAD

**Issue by remram44** [godotengine/godot-docs#2850]
Hi,

I am used to using gettext for all my translation needs, so I was taken aback by the fact that Godot has poor support for PO files and recommends using CSVs. Being able to accept translations from the community on Transifex has helped a lot with localizing my open-source projects.

As you mention, xgettext will not be able to automatically extract strings to be translated. So I got to work and **I wrote a plugin for Babel to be able to extract strings from scene files** (GDScript is close enough to Python that the Python parser can extract those).

So using a config like this, Godot will extract strings automatically to a POT file:
```
[python: **.gd]
encoding = utf-8

[godot_scene: **.tscn]
encoding = utf-8
```
You just have to run `pybabel extract -F babelrc -k Label/text -k LineEdit/placeholder_text -k tr -o translations.pot .`

The plugin is [here on GitHub](https://github.com/remram44/pybabel-godot) and installable using [`pip install babel babel-godot`](https://pypi.org/project/Babel-Godot/). I also made [an example project](https://github.com/remram44/godot-l10n-example) with a script that extract strings automatically.

Is there interest in adding this to the [Localization using gettext](https://docs.godotengine.org/en/3.1/tutorials/i18n/localization_using_gettext.html) page? I hate to be pushing my own code on other people but this seems like it would be useful. I'm also not sure if the process of setting up Babel is too complex for the target user going through the localization tutorial.

I also welcome comments on babel-godot itself. For example, I wrote it so that which properties should be translated is specified by `-k`, for example `-k text` will translate all "text" properties (found on most Controls) and `-k LineEdit/placeholder_text` will translate the property "placeholder_text" on LineEdit nodes. I'm not sure how friendly that is in practice.

I'll see if I can do something about supporting plural rules next.

**Comment by Calinou** [comment]
This sounds great! I didn't even know about Babel (other than the JavaScript compiler of the same name).

Feel free to open a pull request to document this at the bottom of the existing page.
