### ISSUE TITLE
Rename idx to track_idx in the Animation Resource docs

### ISSUE THREAD

**Issue by golddotasksquestions** [godotengine/godot-docs#2856]
It is already very hard to find anything in the [Animation resource docs](http://docs.godotengine.org/en/stable/classes/class_animation.html) because it has so many methods, many of which are poorly documented and have extremely long names.

Many of those method names have both the word "key" and "track" in them, but "idx" is used as argument for tracks and key_idx for keys. I became aware of this difference only when someone commented on [this proposal](https://github.com/godotengine/godot-proposals/issues/158).

For the sake of avoiding this confusion and more readability, I request to use track_idx and key_idx instead.

**Comment by LikeLakers2** [comment]
I actually started on a PR for this right after making that comment in the other PR. https://github.com/godotengine/godot/pull/32842 :)
