### ISSUE TITLE
Edit code  in demo 2d move error.

### ISSUE THREAD

**Issue by IEXWER** [godotengine/godot-docs#2859]
extends RigidBody2D

func get_input():
    if Input.is_action_pressed('right'):
        add_central_force(Vector2(5, 0)
    if Input.is_action_pressed('left'):
        add_central_force(Vector2(-5, 0)
    if Input.is_action_pressed('down'):
        add_central_force(Vector2(0, 2)
    if Input.is_action_pressed('up'):
        add_central_force(Vector2(0, 2)
 
func _physics_process(delta):
    get_input()

//////////////////////////
The ide printed "expected else after ternary if" in the second if.
How to fix it and what's the problem in my code?

**Comment by IEXWER** [comment]
thx!!!

**Comment by IEXWER** [comment]
Maybe there is a wrong place to ask a question. Sorry.
I can't delete this issue.

**Comment by akien-mga** [comment]
You're missing indentation.

This is indeed the wrong place to ask for support, see https://godotengine.org/community for other platforms like the Q&A, Discord, Reddit, forum, etc.
