### ISSUE TITLE
GIFs have been replaced with PNGs in "Your first game"

### ISSUE THREAD

**Issue by NelloDev** [godotengine/godot-docs#2861]
The latest version of [Your first game](https://docs.godotengine.org/en/latest/getting_started/step_by_step/your_first_game.html) is using PNGs where it should be using GIFs. This isn't a big problem in the first example located in the [Overview](https://docs.godotengine.org/en/latest/getting_started/step_by_step/your_first_game.html#overview) where it says "Here is a preview of the final result:" only to show a static image.

Later in the [Spawning mobs](https://docs.godotengine.org/en/latest/getting_started/step_by_step/your_first_game.html#spawning-mobs) section it's a larger issue because the following instructions tell you to follow the actions performed in the GIF: "After placing point 4 in the image [..]"

The only other example I found on this page was in the [Node setup](https://docs.godotengine.org/en/latest/getting_started/step_by_step/your_first_game.html#node-setup) section.

The version of this page in the [godot-docs repository](https://github.com/godotengine/godot-docs/blob/master/getting_started/step_by_step/your_first_game.rst) is what I compared to.

**edit:** I've noticed another issue on this page so instead of opening multiple issues I'll dump it here

https://docs.godotengine.org/en/latest/getting_started/step_by_step/your_first_game.html#main-script

It says "Now **connect the timeout()** signal of each of the Timer nodes (StartTimer, ScoreTimer ,and **MobTimer**) to the main script" but then 3 paragraphs later also says "Now click on **MobTimer** in the scene window then head to inspector window, switch to node view then **click on timeout() and connect the signal.**"

**Comment by bruvzg** [comment]
All GIFs are affected (multiple `Getting started` and `Tutorials` pages), it's regression from #2820 (`conf.py` changes), cc @drfloob.

**Comment by NelloDev** [comment]
Oh sorry I searched "GIF" in issues and that one didn't pop up. What about the second issue, where it tells you to connect MobTimer and then 3 paragraphs later tells you to connect it again? I shouldn't have combined them but they were on the same page sorry
