### ISSUE TITLE
Issues with section of Exporting in Getting Started

### ISSUE THREAD

**Issue by NelloDev** [godotengine/godot-docs#2864]
In [Exporting#Preparing the project](https://docs.godotengine.org/en/3.1/getting_started/step_by_step/exporting.html#preparing-the-project) it instructs the reader to update their copy of Player.gd to match the one provided in the article: "Here is the full script for the player, with comments noting what we’ve changed:"

One change that isn't marked by a comment is a move of where var velocity is declared. In [Your first game#Moving the player](https://docs.godotengine.org/en/stable/getting_started/step_by_step/your_first_game.html#moving-the-player) it's declared in _process(delta) but on this page it's been moved to the top of the file where it's declared with the rest of the variables. A comment mentioning its move would be appreciated

This page also has us remove 2 lines

`position.x = clamp(position.x, 0, screen_size.x)`
`position.y = clamp(position.y, 0, screen_size.y)`

and they were the only use of the screen_size variable. It's declared at the top of the file with the other variables and also assigned a value in _ready(). Both lines should probably be removed since the variable is unused

One last nitpick: Player.gd on the Exporting page doesn't conform to [GDScript style guide#Blank lines](https://docs.godotengine.org/en/latest/getting_started/scripting/gdscript/gdscript_styleguide.html#blank-lines)

**edit:**

In the same section, [Exporting#Preparing the project](https://docs.godotengine.org/en/3.1/getting_started/step_by_step/exporting.html#preparing-the-project), it tells the reader to go to Project Settings > Input Devices > Pointing and says "Before we change the input method, in the project settings go to [...]".  It never tells the player to go back and enable "Emulate Touch From Mouse"

**Comment by Calinou** [comment]
The full script probably needs to be updated to follow the article's latest changes.
