### ISSUE TITLE
Add a quote style guideline to the GDScript style guide

### ISSUE THREAD

**Issue by Calinou** [godotengine/godot-docs#2869]
The [GDScript style guide](http://docs.godotengine.org/en/latest/getting_started/scripting/gdscript/gdscript_styleguide.html) currently doesn't make any recommendations as for quotes. While the Godot script editor defaults to double quotes, I've seen many people use single quotes in their projects (even though it's still a minority in my experience).

I personally use the following style in my projects, inspired by the Python [black](https://github.com/ambv/black) formatter:

```gdscript
# Normal string
"hello world"
# Use double quotes as usual to avoid escapes
"hello 'world'"
# Use single quotes as an exception to avoid escapes
'hello "world"'
# Both quote styles would require 2 escapes, prefer double quotes if it's a tie
"'hello' \"world\""
```

In this style, double quotes are the "default" way to quote strings, *unless* a single-quoted string makes it possible to escape less characters compared to a double-quoted string. In this case (and only in this case), the string should use single quotes.

What do you think about adopting this style?

**Comment by tmilker** [comment]
@Calinou Is this essentially an arbitrary choice? Are there any performance implications for using single vs. double quotes in GDScript?
