### ISSUE TITLE
Maybe a little mistake in the Docs

### ISSUE THREAD

**Issue by SmartySmart702** [godotengine/godot-docs#2870]
I'm not sure if it's a mistake but maybe someone can look at this? 

https://docs.godotengine.org/en/latest/getting_started/workflow/export/android_custom_build.html

"Install Java

Android SDK does not come with Java, so it needs to be installed manually. Instal Java SDK (not runtime or JRE). OpenSDK 8 is recommended, otherwise Oracle’s Java SDK for version 8 will work. Later versions may not work for Android development."

Is OpenSDK 8 right or should it mean OpenJDK?

And it would be nice to include links to the websites where you can download the tools.

**Comment by Calinou** [comment]
This is indeed a typo, just like "Instal Java SDK" :wink:

I'll fix it.
