### ISSUE TITLE
Is it a good idea to explain the possible reason why HTTPREQUEST get_body_size() returns -1

### ISSUE THREAD

**Issue by garyday2001** [godotengine/godot-docs#2874]
The [source code of httprequest](https://github.com/godotengine/godot/blob/4a726998bd28121dde1d212f363d9eba7efa0caf/scene/main/http_request.cpp#L332-L334) gives some reasons to why returning -1 but it is not shown in the doc. 

// No body len (-1) if chunked or no content-length header was provided.
// Change your webserver configuration if you want body len.
body_len = client->get_response_body_length();

Is it a good idea to add more explanation to the doc of httprequest?

**Comment by Calinou** [comment]
> Is it a good idea to add more explanation to the doc of httprequest?

Of course :slightly_smiling_face: I'll do that.
