### ISSUE TITLE
add_style_override

### ISSUE THREAD

**Issue by JCruzMi** [godotengine/godot-docs#2884]
I can't, I don't know, how to change the style of a panel.
I am using the function I saw add_style_override in a tutorial, but this one is already old and tells me that it does not exist for panel

**Comment by Calinou** [comment]
`Control.add_style_override()` was renamed to `Control.add_stylebox_override()` in 3.0. The rest of the method should work as it did in Godot 2.x.

**Comment by Calinou** [comment]
Closing, as the question was answered above. Please open other issues if you still have questions about the documentation.
