### ISSUE TITLE
Not clear what "Theme Properties" are and how to retrieve and set them

### ISSUE THREAD

**Issue by mwerezak** [godotengine/godot-docs#2889]
Right now I'm trying to set the font of a label in response to the mouse hovering over it.

In the editor there is a "Custom Font" property, but there doesn't appear to be any such property on Label objects themselves.

In the documentation for Label, "font" is listed as a "Theme Property", but apparently this is not the same thing as a regular property since I'm unable to access or set it using the standard syntax for accessing or setting a property in gdscript or in C#.

Presumably its documented somewhere, but something this basic should be more accessible.

**Comment by Calinou** [comment]
Check the `add_*_override` and the `has_*_override` methods in [Control](https://docs.godotengine.org/en/latest/classes/class_control.html). Since there are no methods to clear overrides, you will need to save the previous value using `get_*` and set it again to effectively "clear" the value.

In the examples above, `*` can be `color`, `constant`, `font`, `icon`, `shader` or `stytlebox`.

**Comment by Calinou** [comment]
There is now a demo about using GUI theme overrides: https://github.com/godotengine/godot-demo-projects/tree/master/gui/theming_override

**Comment by pycbouh** [comment]
And the related docs, both in Control and Theme class reference, and in GUI section of tutorials have been greatly improved 😛

**Comment by berarma** [comment]
Maybe my fault, but with the improved docs and all, I find it very confusing that it's called "theme properties" in the API for the objects, and the explanations talk about theme parameters or overrides. Same thing different names on different places. Is there any reason for that?

**Comment by YuriSizov** [comment]
@berarma It should never be called theme parameters in any docs, that makes no sense. If there is a place that calls properties parameters, it's an issue worth fixing. Overrides is used to specifically refer to when you override theme properties on a specific control, whereas just calling it properties may refer to properties defined in themes in general.

**Comment by berarma** [comment]
I saw it [here](https://docs.godotengine.org/es/4.x/classes/class_control.html).

Excerpt:

> [Theme](https://docs.godotengine.org/es/4.x/classes/class_theme.html#class-theme) resources change the Control's appearance. If you change the [Theme](https://docs.godotengine.org/es/4.x/classes/class_theme.html#class-theme) on a Control node, it affects all of its children. To override some of the theme's parameters, call one of the add_theme_*_override methods, like [add_theme_font_override](https://docs.godotengine.org/es/4.x/classes/class_control.html#class-control-method-add-theme-font-override). You can override the theme with the Inspector.

If I'm correct that this should be called properties instead of paramaters then I can make a PR.
