### ISSUE TITLE
Prefix the new script with extends and comments

### ISSUE THREAD

**Issue by SensArice** [godotengine/godot-docs#2908]
Each time I create a new GDscript, I need to enter a extends in front of it. This is inconvenient compared to unity. 
I want to add extends and comments automatically when I add a new script to an object. 
This will let the novice know what it is for. 
I didn't succeed in writing the script at first, but I didn't succeed in a few days, and it was a year before I knew that was the reason, because I used to put UsingUnityEngel in front of the script.

**Comment by Calinou** [comment]
This should happen automatically if you right-click a node and choose **Attach Script**. You can configure the template that will be used (make sure it's not **Empty**).

**Comment by skyace65** [comment]
In addition to what Calinou said you're in the wrong place. This is for issues with documentation, engine issues go [here](https://github.com/godotengine/godot/issues).

**Comment by Calinou** [comment]
Closing, as this issue is off-topic for the documentation repository.
