### ISSUE TITLE
Since it is a tutorial, please add a clear explanation.

### ISSUE THREAD

**Issue by chesscommands** [godotengine/godot-docs#2910]
[Control the game’s UI with code](https://docs.godotengine.org/en/3.1/getting_started/step_by_step/ui_code_a_life_bar.html)

There is no explanation below.

`
func _process(delta):
    var round_value = round(animated_health)
    number_label.text = str(round_value)
    bar.value = round_value
`

However, it is important code.

Or could you understand it by reading the page?

Is this issue the same as below?
https://github.com/godotengine/godot-docs/issues/2875

**Comment by akien-mga** [comment]
> Or could you understand it by reading the page?

I think so yes, everything used in this code snippet has been either introduced and explained before, or is explained right next to the snippet.

**Comment by chesscommands** [comment]
Read again.
Sorry for the issue.
