### ISSUE TITLE
Show latest Godot docs in search

### ISSUE THREAD

**Issue by nikhilCad** [godotengine/godot-docs#2912]
I do not know if this is possible or not, but is there any way that the Google search results always yield the latest Godot docs.
3/4 times I end up on a 3.0 docs page and I have to click to go to the latest version of the docs page.

**Comment by nikhilCad** [comment]
Or alternatively, redirect to latesr branch instead of 3.1 when opening an old docs page

**Comment by Calinou** [comment]
Does Read the Docs make it possible to index only certain branches in search engines? Also, in rare cases, the documentation in `latest` (master branch) may be incompatible with what's written in the latest stable branch. I don't think this is the case right now, but it will likely happen at some point with the move to 4.0.

**Comment by akien-mga** [comment]
> Does Read the Docs make it possible to index only certain branches in search engines, or alter the HTML depending on the branch? (We could add `<meta name="robots" content="noindex">` in the `<head>` to handle this then).

That would be worth researching. I think we can at least conditionally add stuff to the `<head>` template.

IMO only `latest` and `stable` should be indexed, the rest should use `noindex`.

**Comment by merumelu** [comment]
>Does Read the Docs make it possible to index only certain branches in search engines, or alter the HTML depending on the branch?

Yes, you can [add a robots.txt](https://docs.readthedocs.io/en/stable/faq.html#how-can-i-avoid-search-results-having-a-deprecated-version-of-my-docs) to the docs root directory.
