### ISSUE TITLE
im kinda new to the scene so yea

### ISSUE THREAD

**Issue by BloodPawsey** [godotengine/godot-docs#2927]
Here is my script i found it on a page to learn if ur new and i dont think it is corret btw

extends Node2D

# Variables
var screen_size
var pad_size
var direction = Vector2(1.0, 0.0)
	
# Constant Ball Speed (Pixels/ A Second)
const INITIAL_BALL_SPEED = 80
# Speed of the ball (Pixels/ A Second)
var ball_speed = INITIAL_BALL_SPEED
# Constant Pad Speed 
const PAD_SPEED = 150
	
func _ready():
    screen_size = get_viewport_rect().size
    pad_size = get_node("left").get_texture().get_size()
    set_process(true)
		
func _procces():
	var ball_pos = get_node("ball").get_pos()
	var left_rect = Rect2( get_node("left").get_pos() - pad_size*0.5, pad_size )
	var right_rect = Rect2( get_node("right").get_pos() - pad_size*0.5, pad_size )
	
# Integrate new ball position

# Flip when touching the roof or the floor
	if ((ball_pos.y < 0 and direction.y < 0) or (ball_pos.y > screen_size.y and direction.y > 0)):
		direction.y = -direction.y
		direction.y = -direction.y
			
# Flip and increase speed when touching the pads
	if ((left_rect.has_point(ball_pos) and direction.x < 0) or (right_rect.has_point(ball_pos) and direction.x > 0)):
    direction.x = -direction.x
    direction.y = randf()*2.0 - 1
    direction = direction.normalized()
    ball_speed *= 1.1
# Check if game ended
    if (ball_pos.x < 0 or ball_pos.x > screen_size.s):
	    ball_pos = screen_size*0.5
	
	get_node("ball").set_pos(ball_pos)
	
# Move Left Pad
var left_pos = get_node("left").get_pos()

if (left_pos.y > 0 and Input.is_action_pressed("left_move_up")):
    left_pos.y += -PAD_SPEED * delta
if (left_pos.y < screen_size.y and Input.is_action_pressed("left_move_down")):
    left_pos.y += PAD_SPEED * delta

get_node("left").set_pos(left_pos)

# Move right pad
var right_pos = get_node("right").get_pos()

if (right_pos.y > 0 and Input.is_action_pressed("right_move_up")):
    right_pos.y += -PAD_SPEED * delta
if (right_pos.y < screen_size.y and Input.is_action_pressed("right_move_down")):
    right_pos.y += PAD_SPEED * delta

get_node("right").set_pos(right_pos)

**Comment by IndoorFossil** [comment]
Its a pong game

**Comment by skyace65** [comment]
I can't find this tutorial in Godot's Documentation. Could you please provide a link?

**Comment by BloodPawsey** [comment]
https://docs.godotengine.org/en/2.1/learning/step_by_step/simple_2d_game.html

**Comment by skyace65** [comment]
That's the Godot 2.1 documentation. It's a significantly older version of the engine and if you're new to Godot you should be learning 3.1. 

The pong tutorial wasn't updated for newer versions of the engine, but if you need a beginner tutorial you should start with the your first game tutorial [here](https://docs.godotengine.org/en/3.1/getting_started/step_by_step/your_first_game.html) or other tutorials in the step by step section of the documentation.

**Comment by akien-mga** [comment]
Note that this repository is for contributing to the documentation, not for user support. See other community platforms like the Q&A, Discord, Facebook or Reddit to get help from the community. godotengine.org/community

**Comment by BloodPawsey** [comment]
Ok thanks
