### ISSUE TITLE
token_identifier

### ISSUE THREAD

**Issue by jamesbunani** [godotengine/godot-docs#2933]

**Comment by Calinou** [comment]
@jamesbunani Did you have a question? I'll close this issue as it doesn't make sense as it currently is.

**Comment by jamesbunani** [comment]
Yes sir! i have a question about godot engine.
Please! help me!
Yesterday, I downloaded Godot Engine v3.1.1.1, decompressed it and started
creating my first game with this game engine but unfortunately for me
debugging the script of my game doesn't work at all.
here is the error I encountered:
"modules/gdscript/gdscript/gdscript_tokenizer.cpp:1104 - Condition '
tk_rb[ofs].type != TK_IDENTIFIER ' is true. returned: StringName()
"

I don't know what to do to make the Godot software work properly please
help me if you have the solution to my problem.

Le sam. 16 nov. 2019 à 16:15, Hugo Locurcio <notifications@github.com> a
écrit :

**Comment by Calinou** [comment]
@jamesbunani This repository isn't intended for user support, please use one of the other [community channels](https://godotengine.org/community) instead.
