### ISSUE TITLE
Add explanation for 'velocity = move_and_slide(velocity)'

### ISSUE THREAD

**Issue by golddotasksquestions** [godotengine/godot-docs#2934]
I never understood why move and slide has to be assigned to the variable velocity to make it work even though I went over the [KinematicBody2D tutorial page](https://docs.godotengine.org/en/3.1/tutorials/physics/using_kinematic_body_2d.html) at least 20 to 30 times over the months.
```
var velocity = Vector2(1, 0)
velocity = move_and_slice(velocity)
```

Today user Grimdakka on Reddit made [this comment](https://www.reddit.com/r/godot/comments/dxovz1/may_be_an_stupid_question_2d_movement/f7u8rmk?utm_source=share&utm_medium=web2x) and now it all makes sense. I wish we would have that explanation in the docs as well:

> You need to save the new velocity after move_and_slide does its magic because you're going to pass it to move_and_slide again next frame. Otherwise the velocity would never change between frames except via input.

**Comment by NathanLovato** [comment]
I'll fix that now. The explanation you got isn't correct to me, or too vague. You can modify the `velocity` variable anytime after all.

The short explanation is that the `move_and_slide` function takes a velocity as an input, and it returns a new velocity. That new velocity corresponds to the speed your character should have after it moved, and potentially collided. For example, if you hit the floor, you don't want your character to keep its downwards speed. The floor should stop its fall. That's what the returned velocity is.

Here's what's happening in greater details. Imagine we have a character and a wall.

`move_and_slide` takes a velocity as an input, that is to say a speed in a given direction. The function moves your character, and it if collides, the function solves the collision, and it projects the remainder of its velocity or motion vector along the surface your character collided with. This is what "slide" means in this context: projecting a vector along a surface.

Then, the function moves your character again and if there's a collision, it keeps doing the same thing. Up to 5 times by default.

Finally, the function returns the final projected velocity vector after all these potential collisions. If the character did not collide with anything this frame, the returned velocity is the same as the input velocity. If the character collided with something, it will be different, depending on the game and the context: if it falls on the floor, moves along a shallow slope, a steep slope, etc.

**Comment by golddotasksquestions** [comment]
I think the key "aha" moment for me was to realize thanks to that comment, that `move_and_slide(some_vector_variable)` crunches some numbers, moves the KB2D while checking for collisions and then (that was the new bit) also returns `some_vector_variable`.

This paragraph I don't understand at all:

> ``move_and_slide()`` may also recalculate the kinematic body's velocity several
times in a loop as, to produce a smooth motion, it moves the character and
collides up to 5 times by default.

So it calculates the same thing 5 times? Five times per physics tick? What for? Why would that make the motion smoother? Why calculate the collision 5 times? Why "up to"? When does it calculate the same thing less often and why is 5 a good number to repeat that loop and not just 4 or 6?

**Comment by NathanLovato** [comment]
> and then (this was the new bit:) also returns some_vector_variable.

This is documented already, it's in the class reference:

> Returns the linear_velocity vector, rotated and/or scaled if a slide collision occurred. To get detailed information about collisions that occurred, use get_slide_collision().

In the script editor in Godot, you can Ctrl click on any method or property to open its documentation.

> Five times per physics tick? What for? 

_Up to_ 5 times _by default_. Actually, now it seems it's 4. You control this with the `max_slides` parameter.

```
move_and_slide(linear_velocity: Vector2, floor_normal: Vector2 = Vector2( 0, 0 ), stop_on_slope: bool = false, max_slides: int = 4, floor_max_angle: float = 0.785398, infinite_inertia: bool = true)
```

That helps to smooth out the motion because when you move a character from the code, it moves in a straight line, but if it moves along a curved shape (think of Sonic the hedgehog and round slopes),  it may hit the collider early and not move along the curve.

![Screenshot from 2019-12-25 09-58-17](https://user-images.githubusercontent.com/12694995/71440337-20608800-26fd-11ea-980d-28887f992517.png)

So we let the character stop along the curve, project it's velocity based on the collision data, and move it again:

![Screenshot from 2019-12-25 10-00-17](https://user-images.githubusercontent.com/12694995/71440438-61f13300-26fd-11ea-83d5-664b3b04aa91.png)

Up to four times by default. If you have a game with round curves you may need to increase that number.

Why four by default? It probably just works well for most games, so unless you make a special kind of game, you don't have to worry about it as a Godot user.

**Comment by golddotasksquestions** [comment]
Thank you for the detailed explanation and the graphics, that helps a lot!
Did I understand this correctly, it's 4 times per physics tick? When are those 4 times taking place? After the parser completely finished going through the _physics_process()? Or right in between somewhere? Only the last of the 4 is at the end?

**Comment by NathanLovato** [comment]
> Did I understand this correctly, it's 4 times per physics tick? 

Up to 4 times, by default, per call to move_and_slide. Most of the time it'll be moving the character only once. But 4 times if there are at least 3 collisions happening in a row (which happens on curved surfaces).

> When are those 4 times taking place? 

I can't say without looking at how the physics engine works in Godot. That's something to ask somebody who's working on the physics engine itself I think.

**Comment by golddotasksquestions** [comment]
Thank you Nathan, this already helps me a lot to have a rough idea about what is happening.

**Comment by NathanLovato** [comment]
You're welcome! And the PR will add some details to the KinematicBody2D guide
