### ISSUE TITLE
Change Java to OpenJDK in Exporting docs

### ISSUE THREAD

**Issue by qarmin** [godotengine/godot-docs#2953]
Since Oracle want money when people use Java SDK in commercial projects, I think that better is to add link to free OpenJDK instead Java SDK - https://godot.readthedocs.io/en/latest/getting_started/step_by_step/exporting.html#android

**Comment by Calinou** [comment]
We can link to [AdoptOpenJDK](https://adoptopenjdk.net/) builds for this purpose.

**Comment by Sauermann** [comment]
The Godot Android Export documentation
https://docs.godotengine.org/en/latest/getting_started/workflow/export/android_custom_build.html
already contains a link to AdoptOpenJDK.
