### ISSUE TITLE
Tcp communication between client and server in Godot script

### ISSUE THREAD

**Issue by Mohini-byte** [godotengine/godot-docs#2960]

**Comment by Meriipu** [comment]
might need more info

**Comment by Calinou** [comment]
Note that we may not accept new tutorials anymore: https://github.com/godotengine/godot-docs/issues/3390

**Comment by Meriipu** [comment]
For instance using websockets? Or explicit tcp via the low-level packet stuff?
(I am not really up for this at the moment personally, either way, but somebody might).

I made my first comment here because this issue seemed a bit vague.

**Comment by Calinou** [comment]
@Meriipu We already seem to have WebSocket demos, so this would be about raw TCP (StreamPeer class).

**Comment by skyace65** [comment]
Closing due to lack of info. And if a tutorial is what is being asked for, as Calniou says the docs have moved away from that for most cases.
