### ISSUE TITLE
Mouse buttons 

### ISSUE THREAD

**Issue by MAX-71** [godotengine/godot-docs#2962]
func _input(event):
   if event is InputEventMouseButton:
        if event.button_index == BUTTON_LEFT and event.pressed:
`button_index` TYPE INT == `pressed` TYPE BOOL
 ERROR BY COMPARISON OF TYPES
            print("Left button was clicked at ", event.position)
        if event.button_index == BUTTON_WHEEL_UP and event.pressed:
            print("Wheel up")

**Comment by bojidar-bg** [comment]
I can't understand what this issue is about. Mind if you elaborate a bit?

**Comment by MAX-71** [comment]
GREAT FORGIVENESS. Without running the code, I made a hasty conclusion. Since `button_index` is an INT type, and  `.pressed` type is BOOL. When comparing for equality, it usually gives an error.

**Comment by bojidar-bg** [comment]
Oh. But operator precedence does not work like that. `event.button_index == BUTTON_LEFT and event.pressed` means `(event.button_index == BUTTON_LEFT) and event.pressed`, that is the equality is tested first, while the `and` operator takes two booleans (one from the equality check and one from `event.pressed`).
