### ISSUE TITLE
Problema sobre enemigos

### ISSUE THREAD

**Issue by bazoka33** [godotengine/godot-docs#2971]
Hola!
Estoy desarroyando mi primer juego, este trata sobre un personaje que esquiva abejas y moscas.  Pero tengo un problema, las abejas cuando aparecen se quedan donde han aparecido.
Ademas, no me funciona el comando para remover los enemigos.
Me podrian ayudar?
Gracias.

Os dejo los scripts y una foto de lo que me pasa.

[Player.txt](https://github.com/godotengine/godot-docs/files/3936140/Player.txt)
[Mundo.txt](https://github.com/godotengine/godot-docs/files/3936141/Mundo.txt)
[Abeja.txt](https://github.com/godotengine/godot-docs/files/3936142/Abeja.txt)
![Sin título](https://user-images.githubusercontent.com/58604242/70388709-b7b3a480-19b5-11ea-9204-66a08e5880a4.png)

**Comment by Calinou** [comment]
Please don't ask support questions here. Use one of the other [community channels](https://godotengine.org/community) instead.
