### ISSUE TITLE
get_node_and_resource docs are confusing

### ISSUE THREAD

**Issue by rcorre** [godotengine/godot-docs#2975]
The docs for [`Node.get_node_and_resource`](https://docs.godotengine.org/en/latest/classes/class_node.html#class-node-method-get-node-and-resource) seem contradictory:

> If several nested resources are specified in the NodePath, the last one will be fetched.

To me, that says that `get_node_and_resource("Area2D/CollisionShape2D:shape:extents")` will fetch `extents`, because that is the "last" of several "nested" resources. However, the docs instead show this:

```
print(get_node_and_resource("Area2D/CollisionShape2D:shape:extents")) # [[CollisionShape2D:1161], [RectangleShape2D:1156], :extents]
```

So it seems the _first_ resource is fetched, and the remaining resources are just returned as an "extra" nodepath.

**Comment by akien-mga** [comment]
It's confusing but it was hard to document this weird method, which has a confusing behaviour :)

It does give you the last *resource*, which is `shape`. `extents` is a Vector2 property, not a Resource. There are some resources which have subresources as properties, in which case the method actually gives you the last Resource specified.
