### ISSUE TITLE
Godot Shader Array Support

### ISSUE THREAD

**Issue by TheRealNOIG** [godotengine/godot-docs#2984]
I was unable to find any mention of array support for Godot's shader language in the docs.
Array support was added in [#3050](https://github.com/godotengine/godot/pull/30500) for OpenGL and in [#31180](https://github.com/godotengine/godot/pull/31180) for Vulkan.

I feel like the best place to but this info would be in the [variables ](https://docs.godotengine.org/en/3.1/tutorials/shading/migrating_to_godot_shader_language.html#variables)section in the Migrating to Godot’s shading language page. The reason for this would be because this would be the most likely place for someone to look if trying to find this information and this section already mentions that "These variables are not uniforms, so they are not editable from the main program." which is consistent to the current implementation of arrays.

Additionally array support per variable should be added to [data-types](https://docs.godotengine.org/en/3.1/tutorials/shading/shading_reference/shading_language.html#data-types) table in Shading language page

Some addition information about the current limitation of arrays should be added somewhere and I would love to get a discussion on that started.

Current limitations of arrays:
 - Constants cant be arrays
 - Sampler cant be arrays
 - Arrays cannot be multidimensional
 - No array uniforms
 - Arrays cant be initialized using array constructor syntax (e.g. float[5](1.0, 1.0, 1.0, 1.0, 1.0))

**Comment by TheRealNOIG** [comment]
I forgot to mention that this feature was added in version 3.2 which is currently in beta

**Comment by clayjohn** [comment]
Sounds like you may be reading an old version of the docs. The docs were updated at the same time the feature was added http://docs.godotengine.org/en/latest/tutorials/shading/shading_reference/shading_language.html#arrays

**Comment by TheRealNOIG** [comment]
Thank you for that information. It looks like I was using the 3.1 docs.
