### ISSUE TITLE
Godot API reference page "@C#" can't be opened on docs.godotengine.org

### ISSUE THREAD

**Issue by acmepjz** [godotengine/godot-docs#2985]
I'm not sure if you are already noticed, but the Godot API reference page "@C#" (i.e. the first item in the page http://docs.godotengine.org/en/3.1/classes/index.html ) can't be opened. The reason is simple: '#' is a reserved character for URLs.

This also affects the generation of HTML Help in Windows.

Maybe you can rename the page file name to "CSharp" or so?

**Comment by akien-mga** [comment]
Duplicate of #947
