### ISSUE TITLE
your_first_game instructions for HUD labels confusing

### ISSUE THREAD

**Issue by mpounsett** [godotengine/godot-docs#2987]
In the [Hud](https://docs.godotengine.org/en/3.1/getting_started/step_by_step/your_first_game.html#hud) instructions, looking at the section arranging the nodes in the scene, the first instruction here references the `Anchor` button, but the screen capture has the `Layout` button circled.  After a bit of fiddling it eventually became clear that `Layout` is the correct button, but the documentation should be updated to reflect this.

Some more precise instructions for setting the margins and anchors of the nodes in this section would be very helpful:

- an indication that the font settings should be repeated for each node
- the screen capture shows grab points on the `MessageLabel` border, but those grab points aren't present in Godot 3.1.2 after following these instructions; it's not clear to me if this is because the screen capture is from an earlier version of Godot, or if it's because there are steps missing from the instructions
- it appears that it's necessary to turn on `AutoWrap` for the `MessageLabel` node, but that instruction is missing (without it, the label overflows the Display Width set on the project)
- a note that the setup instructions for these Nodes' geometry is order-dependent would be helpful—for example, setting the Margin of the `StartButton` node before selecting `Center Bottom` from the `Layout` menu doesn't have the desired results, even it might seem efficient for the user to set the margin at the same time as setting the text field.

**Comment by skyace65** [comment]
Which image are you referring to with grab points? [This one](https://docs.godotengine.org/en/3.1/_images/ui_anchor.png)?

**Comment by mpounsett** [comment]
Yes, that's the one.

**Comment by NathanLovato** [comment]
This was addressed by #3523. Closing the issue.
