### ISSUE TITLE
Request for Image Documentation

### ISSUE THREAD

**Issue by smashbrosonic** [godotengine/godot-docs#2992]
There seems to be no information on how to import an image for use as an image object. I was attempting to use an image into an image texture, but it then proceeded to refuse to accept the image format I gave it. It would be helpful to know what formats are compatible, and how to import one as an image texture.

"The selected resource (StreamTexture) does not match any type expected for this property (Image)."

[ImagesExample.zip](https://github.com/godotengine/godot-docs/files/3984563/ImagesExample.zip)
[DisplayDemo.tscn.zip](https://github.com/godotengine/godot-docs/files/3984576/DisplayDemo.tscn.zip)
![Screenshot_2019-12-19_09-24-31](https://user-images.githubusercontent.com/35270078/71191156-1f35e380-2243-11ea-912c-b3386a4a53ac.png)

Update:
Solved the issue. It appears that the images I was using were already textures.

**Comment by Calinou** [comment]
Should I close this as resolved? That said, we could have an exhaustive list of image formats supported by Godot.

**Comment by smashbrosonic** [comment]
Thank you so much for taking time out of your day to reply. I think that the issue is resolved. I'm just curious as to how to add a tutorial on the documentation. That would be cool.
