### ISSUE TITLE
Broken link in localized FAQ

### ISSUE THREAD

**Issue by dawadam** [godotengine/godot-docs#3014]
In this part of FAQ (in french version) :

https://docs.godotengine.org/fr/latest/about/faq.html#what-is-gdscript-and-why-should-i-use-it

The link to gdScript guide is broken :

https://docs.godotengine.org/fr/latest/about/gdscript_basics

Must be :

https://docs.godotengine.org/fr/latest/getting_started/scripting/gdscript/gdscript_basics.html#doc-gdscript

**Comment by Calinou** [comment]
It seems this doesn't occur on the English version, clicking on the link in the [English FAQ](https://docs.godotengine.org/en/latest/about/faq.html#what-is-gdscript-and-why-should-i-use-it) will point to [this page](https://docs.godotengine.org/en/latest/getting_started/scripting/gdscript/gdscript_basics.html#doc-gdscript).

**Comment by dawadam** [comment]
I wrote (please read in the parentheses) :

> In this part of FAQ (in french version) :

**Comment by Calinou** [comment]
@dawadam I noticed, I was just saying this is specific to localized versions. The way those pages is generated is a bit different from the English version.

**Comment by akien-mga** [comment]
Fixed the broken link in the French and German documentations.
