### ISSUE TITLE
3.1. Animation Introduction Tutorial still explains 3.0.6 AnimationPlayer

### ISSUE THREAD

**Issue by golddotasksquestions** [godotengine/godot-docs#3018]
https://docs.godotengine.org/en/3.1/tutorials/animation/introduction_2d.html

**Comment by skyace65** [comment]
The latest version of the animation introduction is updated for Godot 3.1, but it was never backported to the 3.1 branch. With 3.2 coming out soon it might not be worth it to do that.

**Comment by golddotasksquestions** [comment]
I found two minor issues in the Latest branch:

> See the **animation panel reference** below for details.

Links nowhere.

```
This creates a new track and our first keyframe at the beginning of the timeline:
https://docs.godotengine.org/en/latest/_images/animation_track.png

The sprite track

The track name consists of a Node Path, followed by a colon, followed by a reference to its property, that we would like to modify.

In our example, the path is AnimationPlayer/Sprite and the property is position.

The path always starts at the AnimationPlayer node’s parent (so paths always have to include the AnimationPlayer node itself).
```
This is still 3.0.6

**Comment by skyace65** [comment]
Thanks! I just made a PR to fix those issues.
