### ISSUE TITLE
Inverse Kinematics and Working with 3D Skeletons M.I.A

### ISSUE THREAD

**Issue by somnivore** [godotengine/godot-docs#3019]
https://docs.godotengine.org/en/3.1/community/tutorials/3d/inverse_kinematics.html
https://docs.godotengine.org/en/3.1/community/tutorials/3d/working_with_3d_skeletons.html

Neither of these links appear to function.  Not in 3.1 or in latest.

![image](https://user-images.githubusercontent.com/28724859/71606279-2e673c00-2b35-11ea-9997-2643ad257c23.png)

However, their 3.0 counterparts work fine:

https://docs.godotengine.org/en/3.0/community/tutorials/3d/inverse_kinematics.html
https://docs.godotengine.org/en/3.0/tutorials/3d/working_with_3d_skeletons.html

Both pages include redirects to the 3.1 docs, which do not resolve.

![image](https://user-images.githubusercontent.com/28724859/71606310-679fac00-2b35-11ea-94f7-124c2cd42a3d.png)

Here, these tutorials are listed in the 3.0 side bar.

![image](https://user-images.githubusercontent.com/28724859/71606328-83a34d80-2b35-11ea-972a-80d6bc41aa34.png)

Here in latest, they are gone.  Searching for either of them returns no results.

**Comment by skyace65** [comment]
That's because those pages were removed from documentation. I do not know why though.

**Comment by akien-mga** [comment]
Fixed, I removed the now invalid redirects (which incidentally will break them on 3.0, but there's no way around it).

> That's because those pages were removed from documentation. I do not know why though.

They were not good.
