### ISSUE TITLE
Add a tutorial for creating a custom backend (export script) for Godot

### ISSUE THREAD

**Issue by sunnystormy** [godotengine/godot-docs#3035]
Hi all! I'm writing to request a tutorial on creating a custom Godot backend for the target platform the user would like to compile for. The reason being is due to the growth of open-source ISAs like RISC-V and OpenPOWER. It would be wonderful to learn how to compile Godot-created content for these platforms for future technology demonstrations, and eventually, for running games upon Free/Libre Open Source Hardware!

Thank you!

--EDIT--

I should also state that, operating system-wise, I am thinking of exporting for Linux on RISC-V/OpenPOWER.

**Comment by Calinou** [comment]
I think it makes sense to merge the required SCons/source changes to build Godot for those ISAs (just like ARM).

**Comment by Calinou** [comment]
- Implemented by https://github.com/godotengine/godot-docs/pull/6345.
