### ISSUE TITLE
Add an (optional) dark theme

### ISSUE THREAD

**Issue by nikhilCad** [godotengine/godot-docs#3041]
Please add a button somewhere in the docs to switch to a dark theme.
I am addicted to dark themes, thanks to Sublime Text.
I am currently using a browser plugon for it, but it is not very efficient.

**Comment by Calinou** [comment]
Related to #1122. Now that we have `(prefers-color-scheme: dark)` CSS media query, this is easy to do.

**Comment by nikhilCad** [comment]
Chrome mobile users cannot even use extensions.

**Comment by Calinou** [comment]
@nikhilCad This doesn't rely on a browser extension, just a [built-in CSS media query](https://caniuse.com/#feat=prefers-color-scheme).
