### ISSUE TITLE
How to use Rayshape2D to not to slip on slope and walke normally....?

### ISSUE THREAD

**Issue by banti101** [godotengine/godot-docs#3043]
a brief user description on Rayshape2D..... 
on a slope my character always sliding. but i want to walk my character normally on a low angle slope , where on high angle slope he should be drag_down automatically, like he is sliding. i did some research and found about Rayshape2D. but don't know much about it . any help will be appreciated.

**Comment by NathanLovato** [comment]
Hi! This is not the place to ask for support. In Godot, you would probably use KinematicBody2D and the move_and_slide method to not slide on slopes. I wouldn't recommend using RayShape2D at the moment. If you want to use raycasting, you'd better create RayCast2D nodes instead, they're more stable.

For support, you can go to one of the communities listed on the official website: https://godotengine.org/community

Good luck with your projects!
