### ISSUE TITLE
Is there a plan to support Chinese?

### ISSUE THREAD

**Issue by joesdu** [godotengine/godot-docs#3050]
Is there a plan to support Chinese?

**Comment by volzhs** [comment]
are you expecting this? https://docs.godotengine.org/zh_CN/latest/

**Comment by joesdu** [comment]
> are you expecting this? https://docs.godotengine.org/zh_CN/latest/

Thanks very much

**Comment by Feniks-Gaming** [comment]
Would you mind closing an issue if this answered your question
