### ISSUE TITLE
No classes option

### ISSUE THREAD

**Issue by DeJake** [godotengine/godot-docs#3068]
It just says request docs with a link here. How do I get the classes option?

**Comment by Feniks-Gaming** [comment]
Could you expand your question with more than one sentence so we know what is your problem. No class option s where, what are you trying to do etc?!

**Comment by Calinou** [comment]
As of Godot 3.1, the **Classes** button at the top of the scrpt editor was replaced by the **Search Help** button:

![image](https://user-images.githubusercontent.com/180032/72671845-55889d80-3a51-11ea-8288-944fc1ffa331.png)
