### ISSUE TITLE
Alignment of sidebar navigation is broken in the latest branch of the documentation.

### ISSUE THREAD

**Issue by Jakob-PB** [godotengine/godot-docs#3081]
As of very recently it seems that the navigation sidebar for the live version of the documentation site has issues with rendering. This appears to only effect the "latest" version branch of the documentation and none of the other versions are effected. This issue applies to the current stable versions of Firefox, Chrome, and Edge on Windows 10.

Should be fairly easy to reproduce, simply switch the documentation version to "latest" and you will see something like the following image. Note the bottom left corner.

![Annotation 2020-01-19 235640](https://user-images.githubusercontent.com/6045198/72702330-eaee6500-3b17-11ea-9343-97ce77adbfbb.png)

**Comment by akien-mga** [comment]
Regression from #3073, cc @Calinou.
