### ISSUE TITLE
Seperate documentation versions for Godot 2.x and Godot 3.x?

### ISSUE THREAD

**Issue by hubbyist** [godotengine/godot-docs#309]
Since compatibility will break with introduction of Godot 3.x, a separate version of documentation for Godot 2.x will be necessary for a some time IMO.

Just think of it when I read early 2017 as the planned date for Godot 3.x. By that time my students will already be in half way through their projects, so a sudden change in tutorials and class reference on internet will be problematic?

WDYT?

**Comment by akien-mga** [comment]
There's already a branch for 2.1.x, which is used by the `/stable` and `/2.1` versions of the docs:
- http://docs.godotengine.org/en/stable/
- http://docs.godotengine.org/en/2.1/

The master branch is used for the `/latest` version, which will be then forked to a 3.0 branch when 3.0 is released, and continue it way towards 3.1, and so on and so forth.
- http://docs.godotengine.org/en/latest/

**Comment by hubbyist** [comment]
Will there be stable2.x and stable3.x or stable will be following Godot3.x development?

**Comment by akien-mga** [comment]
`/stable` will always be the latest stable, but previous stable releases will stay accessible at `/2.1`, `/3.0`, `/3.1`, etc.

**Comment by akien-mga** [comment]
So, fixed already as far as I'm concerned :)
If you're writing documentation for students, give them the `/2.1` link to ensure they stay on the version used in the course.
