### ISSUE TITLE
Create a Godot Shader Language style guide

### ISSUE THREAD

**Issue by aaronfranke** [godotengine/godot-docs#3091]
We have style guides for GDScript and C#, but there is currently no style guide for GDSL. We should probably create one. I was looking over a pull request in the demo projects repository which adds some shader code, and it had some questionable things in it (such as no space around addition and multiplication), but I found there is no style guide to reference for what *should* be done.

Since GDSL is based on GLSL, and GLSL is based on C's syntax, perhaps we should adopt a style similar to Godot's internal C++ code? It might also be a good idea to write a C++ style guide, but that's a whole other beast by itself.

CC @Chaosus @clayjohn @JFonS @reduz (since y'all have contributed heavily to shaders, at least from what I can gather with a git blame), CC @nathanwfranke (since I know you use shaders a lot), and of course anyone else who uses shaders is welcome to chime in (btw, I have not).

**Comment by clayjohn** [comment]
Great idea. I think we should start from the style guide for the C++ source and then just add things as appropriate. 

For example: for vector access, use ``xyz`` when vector is treated as a vector and ``rgb`` when vector is being used as a color.

**Comment by Chaosus** [comment]
Well, I don't know whether it has any importance or not - the majority of users just copy/paste shaders from sources like ShaderToy where styles are different and (I think) they don't want to touch internals afterward if they work correctly. 

But I could help in writing some guidelines, of course.
