### ISSUE TITLE
Docs sidebar not wide enough

### ISSUE THREAD

**Issue by clayjohn** [godotengine/godot-docs#3092]
Right now a few of the class names are so long that the sidebar forces them onto a new line (e.g. VisualShaderNodeVectorScalarSmoothStep), separate from their "+" button, but they still run off the side of the sidebar. This looks incredibly odd, especially since the docs have open space on either side. 

CC: @Calinou since you've been handling all the website updates recently :)

![Screenshot 2020-01-21 at 9 25 38 PM](https://user-images.githubusercontent.com/16521339/72867738-c966b800-3c94-11ea-94cb-db8b36ac7b57.png)

**Comment by Calinou** [comment]
I think this was already an issue before I centered the documenation's main page. I'm not sure how easy it is to enlarge the sidebar slightly. If this isn't possible, we could make overflowing text result in an ellipsis so it doesn't break into multiple lines.

**Comment by akien-mga** [comment]
This is probably something that would be worth discussing with upstream at https://github.com/readthedocs/sphinx_rtd_theme. Implementing a ad hoc solution like widening the sidebar could be done, but eventually me might get an even longer name and the same issue again. A solution is likely necessary for better handling of long, unbreakable section names.

**Comment by Calinou** [comment]
Adding the following CSS snippet leads to an acceptable solution for class reference headers, but it's not great in other sections:

```css
.wy-menu-vertical li.current a {
    white-space: nowrap;
}
```

![Class reference titles](https://user-images.githubusercontent.com/180032/72923395-42c2e100-3d4f-11ea-8b47-9baf4fe31636.png)

![GDScript titles](https://user-images.githubusercontent.com/180032/72923468-6e45cb80-3d4f-11ea-9c19-0ca42795f122.png)

**Comment by KieranCarden** [comment]
@Calinou throwing `display: flex` on the same selector you did `white-space: nowrap;` should solve both problems.

<img width="1218" alt="Screen Shot 2020-01-28 at 5 48 05 PM" src="https://user-images.githubusercontent.com/4044137/73315707-6924c880-41f6-11ea-881a-4249c29be6aa.png">
<img width="1226" alt="Screen Shot 2020-01-28 at 5 48 23 PM" src="https://user-images.githubusercontent.com/4044137/73315709-6c1fb900-41f6-11ea-9b27-05ea5ae59bfd.png">
