### ISSUE TITLE
Mention caveats about exporting for Windows with embedded PCK and/or UPX

### ISSUE THREAD

**Issue by xix-xeaon** [godotengine/godot-docs#3093]
*Bugsquad edit:* Moved to a docs issue. See https://github.com/godotengine/godot-docs/issues/3093#issuecomment-577064497

----

**Godot version:**
Godot_v3.2-beta5_x11.64

**OS/device including version:**
Kubuntu/19.10

**Issue description:**
As recommended by reduz in godotengine/godot#27140 I used UPX to compress the executable (and the difference is so dramatic (40mb to 14mb: 65% reduction) it should really be a standard feature in my opinion) but it does not work with the Embed Pck option.

Exporting with Embed Pck for Linux/X11 gives an error but works anyway (the same as godotengine/godot#32513). But after using UPX running the executable only gives the dialog "Error: Could not load game data at path '.'. Is the .pck file missing?"

Doing the same for Windows Desktop has no error on export (and runs fine on my machine using Wine (not affected by godotengine/godot#33466), but when running UPX I get "upx: Articore.exe: CantPackException: superfluous data between sections (try --force)". Using --force leads to the same result as for the Linux/X11 version.

In godotengine/godot#18404 dns says "Godot packing/embed it the wrong way" but closed the issue since Godot 3 no longer had the Embed Pck option at that point, I don't know if it was re-implemented the same way.

**Steps to reproduce:**
New Project, Export, Embed Pck, UPX

**Comment by akien-mga** [comment]
Moving this to the documentation - this cannot be fixed in the engine, so there should be a warning about not using UPX to compress executables with embedded PCK.

In general, I would advise against using UPX in any situation as it's unreliable. It's simpler to just zip your game if you really want to save on download size - installed size for a 30 MB binary once unzipped should not matter.

**Comment by akien-mga** [comment]
The warning should likely go there: https://docs.godotengine.org/en/latest/development/compiling/optimizing_for_size.html#using-upx-to-compress-binaries

IMO it might be better to just drop this section too, but YMMV.

**Comment by akien-mga** [comment]
The page about exporting for Windows should have a section about embedding PCK and the caveats of that option. godotengine/godot#33466 should also be mentioned there (it should hopefully be fixable, but won't be fixed in 3.2).
