### ISSUE TITLE
The description in "Lights and Shadows" of the 'Reverse Cull Faces' option lacks important information

### ISSUE THREAD

**Issue by Two-Tone** [godotengine/godot-docs#3108]
[It's the last bullet point in this section](https://github.com/godotengine/godot-docs/blob/master/tutorials/3d/lights_and_shadows.rst#shadow-mapping). 

The info it lacks is that it doesn't mentioned that when enabled you'll need to set the bias to a _negative_ number because if you don't you'll end up with a [huge gap between the shadow and the object casting it](https://cdn.discordapp.com/attachments/566119566707654658/670824347946188810/unknown.png), one that you can't fix by just adjusting the contact option as [you'll end up with very broken looking shadows](https://cdn.discordapp.com/attachments/566119566707654658/670824188399058964/unknown.png).

However, [a negative bias will result in the shadows "bleeding" weirdly, even with a bias that is barely into the negative](https://gfycat.com/PhysicalCapitalAustraliankelpie). This can be worked around by having the bias at or barely below 0 and then barely upping the Contact value, [but that results in a weird graphical glitch on any faces that are at a shallow angle to the light source](https://gfycat.com/WavyUnderstatedBluefish), that might be a bug with Contact though?

I'd also like for it to mention where enabling Reverse Cull Faces is useful as the current description doesn't tell you anything.

**Comment by Calinou** [comment]
> that might be a bug with Contact though?

Contact shadows are known to be broken and may be hidden from the editor in the future. See https://github.com/godotengine/godot/pull/35316.

**Comment by Two-Tone** [comment]
Instead of hiding it, wouldn't it be better to fix it?

**Comment by Calinou** [comment]
@Two-Tone I have no idea how to fix it, and reduz is busy working on the Vulkan renderer :slightly_frowning_face:

**Comment by Two-Tone** [comment]
CptPotato's work in there looked great, I wonder why he thought it wasn't ready.  I wonder what it looks like with the camera moving.

**Comment by Skaruts** [comment]
I seem to get good results with 0.001 bias and reverse cull face. 

Without reverse cull face, if I lower the bias enough to leave no gaps (below 0.01), I always get self-shadowing artifacts. But then  with 0.001 bias, if I turn reverse cull face on, then everything seems to look just right. 

Is this the intended behavior/usage of that setting?

**Comment by Calinou** [comment]
> Without reverse cull face, if I lower the bias enough to leave no gaps (below 0.01), I always get self-shadowing artifacts. But then with 0.001 bias, if I turn reverse cull face on, then everything seems to look just right. No gaps, no artifacts.

Is this the intended behavior/usage of that setting?

Reverse cull face is best used with a slight *negative* bias (between -0.01 and -0.01).
