### ISSUE TITLE
Bottom sidebar's shadow doesn't follow it

### ISSUE THREAD

**Issue by YeldhamDev** [godotengine/godot-docs#3113]
While scrolling the sidebar, the bottom's shadow stays put and doesn't follow it:
![Screenshot_20200127_212440](https://user-images.githubusercontent.com/30739239/73225434-96289b00-4164-11ea-9f63-3ef2c8c77d08.png)

**Comment by Calinou** [comment]
I know what's causing this; the shadow needs to be hidden via JavaScript when the header isn't made fixed yet. This can be done by setting `::after` pseudoelement's background to `transparent`.

**Comment by KieranCarden** [comment]
Looks like making `.wy-side-nav-search` have `position: relative` instead of `position: static` fixes it as well? Unless I'm missing a reason why static is being used.

**Comment by Calinou** [comment]
@KieranCarden This solves the issue, but the shadow shouldn't be visible in the first place when the user hasn't scrolled enough. The shadow is used to indicate [elevation](https://material.io/design/environment/elevation.html).

**Comment by Calinou** [comment]
@KieranCarden I found a simpler way to solve this; it doesn't involve any complex selector.
