### ISSUE TITLE
Collada import no longer supports scene merging, docs need updating to match. 

### ISSUE THREAD

**Issue by Muzz** [godotengine/godot-docs#312]
I'd edit them myself, but i don't know enough to make accurate information. 
http://docs.godotengine.org/en/stable/tutorials/3d/importing_3d_scenes.html

Or should i give it my best shot and then let people who know better check it?

**Comment by mhilbrunner** [comment]
Just add/fix what you can and submit a PR, it will be reviewed anyway. :)

**Comment by mhilbrunner** [comment]
Seems this was fixed in the mean time.
