### ISSUE TITLE
Mention that spritesheets can also be used with AnimatedSprite

### ISSUE THREAD

**Issue by nikhilCad** [godotengine/godot-docs#3125]
https://docs.godotengine.org/en/latest/tutorials/2d/2d_sprite_animation.html#sprite-sheet-with-animationplayer

It says outdated info that AnimatedSprite does not support spritesheets. This is a huge deal for pixel games I think. Please fix this.

**Comment by Calinou** [comment]
Please open a pull request for this :slightly_smiling_face:

**Comment by robinlamb** [comment]
Can I work on updating this page?

**Comment by Calinou** [comment]
@robinlamb Sure, go ahead :slightly_smiling_face:

**Comment by robinlamb** [comment]
Thank you.  I have started working on this.  I took some screenshots to show how to use a spritesheet with AnimatedSprite and committed them to the image folder in my fork.  Next, I will put them on the page and edit the text to show that you can easily use a spritesheet with AnimatedSprite.

**Comment by robinlamb** [comment]
I created a pull request with an update to the tutorial.  https://github.com/godotengine/godot-docs/pull/3159

**Comment by nikhilCad** [comment]
@robinlamb thank you very much. I have my entrance exam in April and only saw what has happened to this issue just now. Thank you!

**Comment by nikhilCad** [comment]
#3159 got merged so closing
