### ISSUE TITLE
Vector2 Get X/Y values in Visual Script

### ISSUE THREAD

**Issue by larix45** [godotengine/godot-docs#3129]
I try to get vc2's (Vector2) x value. But when I try to do this by draging from variadable block I have a problem. There is no option to get this value. Please help. Thanks.

**Comment by larix45** [comment]
After digging in documentation I found a Solution

**Comment by Calinou** [comment]
As far as I know, this isn't implemented yet. See https://github.com/godotengine/godot-proposals/issues/219.

**Comment by larix45** [comment]
Ok I found solution. You can add manually "Get" block, and then edit it in inspector to Build-in type. Then select Vector2 and select x on y. So this works fine, but I think it should be implemented in easer to use way.
