### ISSUE TITLE
It looks like a mistake in a vector tutorial illustration

### ISSUE THREAD

**Issue by phoenixweiss** [godotengine/godot-docs#313]
I found it here: http://docs.godotengine.org/en/stable/tutorials/vector_math.html#coordinate-systems-2d
In coordinate systems 2D section
http://docs.godotengine.org/en/stable/_images/tutovec1.png
Proper coordinates should be (2,3) instead of (3,2), because of (x,y) pattern.
![tutovec1](https://cloud.githubusercontent.com/assets/3630353/21129982/79520506-c116-11e6-8c7a-8659d90b0a70.png)

**Comment by bojidar-bg** [comment]
Ouch, looks like yet another documenter was working instead of sleeping :wink:
