### ISSUE TITLE
Adding supported image types list

### ISSUE THREAD

**Issue by Lisapple** [godotengine/godot-docs#3132]
As suggested in issue #2992, it would be a great addition to add a complete list of all supported image/texture formats. That can be added to "Docs » Project workflow » Assets workflow » Importing images" page.

It would be useful to check for a particular workflow with Godot, even if most of the image type of wildly supported among 2D/3D software.

For Godot 3.2, so far I found the following image/texture formats supported (from `/modules` folder in Godot project, I haven't tested all formats):
  * Scalable Vector Graphics (`.svg`)
  * Portable Network Graphic (`.png`)
  * Truevision Targa (`.tga`)
  * JPEG (`.jpg` and `.jpeg`)
  * WebP (`.webp`)
  * Bitmap (`.bmp`)
  * PowerVR texture (`.pvr`)
  * Radiance HDR (`.hdr`)
  * OpenEXR (`.exr`)
  * DirectDraw Surface (`.dds`)

I don't see the need to include more information (about pros/cons) for each format, Godot offers many options when generating textures that can override theses specifications.

**Comment by Calinou** [comment]
> JPEG (.jpg, and not with .jpeg extension)

The `.jpeg` extension should work according to the source code: https://github.com/godotengine/godot/blob/dfcfa7d256809130af827f33d4cfeffcedc01dc3/modules/jpg/image_loader_jpegd.cpp#L126

**Comment by Lisapple** [comment]
> The `.jpeg` extension should work according to the source code: https://github.com/godotengine/godot/blob/dfcfa7d256809130af827f33d4cfeffcedc01dc3/modules/jpg/image_loader_jpegd.cpp#L126

Yes, exact! I edited the list.
