### ISSUE TITLE
Color in blank space on docs.godotengine.org

### ISSUE THREAD

**Issue by regakakobigman** [godotengine/godot-docs#3140]
In the docs, there is a text pane, a sidebar, and two blank spaces to the left and right. It may be less distracting to make these blank spaces blend in with the sidebar and text pane, respectively.

A. Here is what it looks like right now:

![Neither](https://user-images.githubusercontent.com/42157525/73615458-f6409680-45d5-11ea-92ac-67a04aa6e181.png)

B. Here is what it would look like if we darkened the left space to match the sidebar:

![Darkened](https://user-images.githubusercontent.com/42157525/73615460-fa6cb400-45d5-11ea-8d8e-b8a4431c6114.png)

C. Here is what it would look like if we lightened the right space to match the text pane:

![Lightened](https://user-images.githubusercontent.com/42157525/73615461-fa6cb400-45d5-11ea-8511-0a0abce19b3e.png)

D. Here are both steps combined:

![Both](https://user-images.githubusercontent.com/42157525/73615462-fa6cb400-45d5-11ea-868a-7d37dd6b6f64.png)

This may end up looking slightly different if #3139 is implemented. The dark space on the left would be shortened, and the white space on the right would be lengthened.

Which (A, B, C, D) do you prefer?

**Comment by Calinou** [comment]
See #3119. I had the idea you suggested in mind too, but I'm not sure if it actually looks better that way.

**Comment by akien-mga** [comment]
Making the left part dark basically makes the sidebar much bigger, it doesn't look better to me. At most the C. variant might be OK, but it adds a weird imbalance between the gray area on the left and an expending white main section to the right, which I don't see as an improvement. So of all those, I think the current design works best.

**Comment by mhilbrunner** [comment]
I'm closing this due to the lack of clear consensus.

See https://github.com/godotengine/godot-docs/pull/3119 for additional discussion.

Thanks for taking the time to submit an issue!
