### ISSUE TITLE
engine.startGame signature change 

### ISSUE THREAD

**Issue by evandikt** [godotengine/godot-docs#3146]
**Godot version:**
since godot 3.2 ?

**OS/device including version:**
Linux aralgor 5.4.14-2-MANJARO x86_64 GNU/Linux

Hi,
i notice the `engine.startGame` has a new signature in js generated file ...

https://docs.godotengine.org/en/latest/tutorials/platform/customizing_html5_shell.html#engine.startGame

Now there is 2 params (execName, mainPack)

Exec params is like that params : https://docs.godotengine.org/en/latest/tutorials/platform/customizing_html5_shell.html#engine.setExecutableName

**Comment by Calinou** [comment]
cc @Faless

**Comment by akien-mga** [comment]
This was changed by @Relintai in godotengine/godot#32448 to fix an Emscripten compat change. The docs need to be updated accordingly.

**Comment by Relintai** [comment]
Sorry, seems like I skimmed over this part of the doc. I'll create a pr.

**Comment by Relintai** [comment]
https://github.com/godotengine/godot/pull/36014 should close this issue, as it will make the api consistent with the docs. I'm mentioning it because it's in a different repository.
