### ISSUE TITLE
Out of date docs download

### ISSUE THREAD

**Issue by jamesreiati** [godotengine/godot-docs#3149]
The [downloads section](https://readthedocs.org/projects/godot/downloads/) for the docs don't include the 3.2 documents. Can someone with the appropriate permissions make a build download for the 3.2 recent docs? I would like to have an offline copy, but don't want to install the toolchain necessary to build the docs myself.

**Comment by clayjohn** [comment]
I think the decision was to stop building the docs. :/ As you can see there isn't even a full build of the 3.1 or 3.2 versions of the docs.

But I won't leave you empty handed. Calinou provides the HTML files for the docs in his nightly builds https://hugo.pro/projects/godot-builds/ 😄

**Comment by Calinou** [comment]
@clayjohn We could look at setting up Travis CI on this repository to build and upload the latest documentation to the TuxFamily server using SFTP. This way, we'd have an officially-maintained solution :slightly_smiling_face:

**Comment by skyace65** [comment]
Closing this issue as downloadable versions of the docs were removed.
