### ISSUE TITLE
Inheritance graphic update

### ISSUE THREAD

**Issue by jcmonkey** [godotengine/godot-docs#3153]
https://docs.godotengine.org/en/3.2/development/cpp/inheritance_class_tree.html

Under this document page there is a resource graphic that could use the addition of the mono module. 

mono->script->resource.

GDScript already has one that shows it inherits from script, but there isn't one for mono.

Now i understand this might be a minor issue, but it may help some people in the future.

Just thought i would let you guys know about it.

PS. if there was a page explaining how the mono module works added in the future, that would also be great. thanks!

**Comment by Xrayez** [comment]
This certainly needs an update especially for Godot 4.0.

I've discovered [Sourcetrail](https://www.sourcetrail.com/) source explorer and with the compilation database support added in godotengine/godot#32848 we could create instructions on how to create a Sourcetrail project to view Godot's inheritance and other neat stuff there:

![object-many](https://user-images.githubusercontent.com/17108460/82325107-57ed0b00-99e3-11ea-8446-e3e0df307f7b.png)

@fire may also give some ideas, as I've found this through one of his replies at Godot's Discord. 🙂

**Comment by Calinou** [comment]
[Sourcetrail doesn't support saving the whole graph to an image yet.](https://github.com/CoatiSoftware/Sourcetrail/issues/426) Is there anything else we could use for this?

**Comment by fire** [comment]
On Windows, compilation db works.

```
scons platform=windows use_llvm=yes use_mingw=yes -j16 target=debug werror=no compiledb=yes",
```

This uses https://github.com/mstorsjo/llvm-mingw.

1. scoop install sourcetrail
1. Launch source trail
1. Add compilation json to the project.
1. Index every single file
1. Search for `ClassDB` term
1. Save as SVG.
1. Note that my version is a custom engine, so you need to refresh. DON'T USE.

[ClassDB.zip](https://github.com/godotengine/godot-docs/files/4912229/ClassDB.zip)

**Comment by fire** [comment]
[NOTE not latest master and customized]

Converted svg to png with affinity designer.

![ClassDB](https://user-images.githubusercontent.com/32321/87301918-43019500-c4c5-11ea-84cc-4a787c74fbfa.png)

**Comment by hazarek** [comment]
> [NOTE not latest master and customized]
> 
> Converted svg to png with affinity designer.
> 
> ![ClassDB](https://user-images.githubusercontent.com/32321/87301918-43019500-c4c5-11ea-84cc-4a787c74fbfa.png)

Always use the predefined Godot color palette and font for diagrams, and it should be suitable for dark mode.

**Comment by RadiantUwU** [comment]
https://docs.godotengine.org/en/stable/contributing/development/core_and_modules/inheritance_class_tree.html

**Comment by RadiantUwU** [comment]
Still here.
