### ISSUE TITLE
Sidebar and Main Page should scroll independently

### ISSUE THREAD

**Issue by un0btanium** [godotengine/godot-docs#3155]
I am working myself through the documentation and on desktop the sidebar always moves with the main page. I find this very annoying because I expect the sidebar and main page to scroll seperately. If I reach the bottom of the main page, the sidebar most of the time will also be scrolled down to the bottom and I have to scroll back up again. It would be much less intrusive fo the user for the scrollbar to not move with the main page.

Is there an obvious reason for this behaviour I am missing or just a limitation of the used documentation software?

**Comment by Calinou** [comment]
I'm not sure if we have any control over this, unfortunately.

**Comment by un0btanium** [comment]
Bummer.
