### ISSUE TITLE
Add Godot API for translations? All references to the Godot API ( :ref:`class_name` )in translations are broken

### ISSUE THREAD

**Issue by JiRuifanCR** [godotengine/godot-docs#3162]
I am a docs translator and the Godot API(the final chapter of the docs) doesn't seem to be open for translation and therefore aren't present in any of the translated docs. As a result, all the :ref:class_names to the Godot API are broken. Is it possible to add the Godot API chapter to the Weblate translations? Or maybe I am doing something wrong?
I sincerely apologize if this shouldn't be here, I've posted this at multiple places(including the docs translation github repository godot-docs-l10n) and there doesn't seem to be an answer(maybe I overlooked something). This repo is visited more often so I thought I might as well post here... but if this shouldn't be here, this issue is also open at godot-docs-l10n. :)

**Comment by Calinou** [comment]
As far as I know, there are no plans to translate the class reference due to its sheer size. Keeping it up-to-date would likely prove to be a nightmare :slightly_smiling_face: 

However, we should look into fixing the `:ref:` blocks so the point to the English class reference.

**Comment by akien-mga** [comment]
We might make it translatable eventually, but not now. There's still a lot of content to translate in the tutorials first before doubling the size of the strings catalog with the API reference.

The API reference also needs to be more complete and stable before we open it for translation.

In the meantime, links should be fixed automatically to point to the English version indeed.

**Comment by mhilbrunner** [comment]
>The API reference also needs to be more complete and stable before we open it for translation.

The API reference is also the least useful to translate, as it requires the most english skills to use anyway. The other docs are more useful, as the Godot editor may be used in whichever language. No so option for the GDScript API.

I'm closing this for now, we'll revisit if we ever decide to translate the GDScript API docs.
