### ISSUE TITLE
Mesh methods to get and set materials are not typed correctly

### ISSUE THREAD

**Issue by Saitodepaula** [godotengine/godot-docs#3172]
In the [3.2 Docs page for Mesh](https://docs.godotengine.org/en/3.2/classes/class_mesh.html), two methods are not typed correctly:

`get_surface_material` is typed as `surface_get_material`
`set_surface_material` is typed as `surface_set_material`

**Comment by clayjohn** [comment]
Nope, those are correct. You are mixing up the functions in [MeshInstance](https://docs.godotengine.org/en/3.2/classes/class_meshinstance.html) with those in Mesh.

The naming is confusing and will be changed in 4.0.

**Comment by Saitodepaula** [comment]
Hum, sorry, indeed I was mixing up. Maybe a warning in the beginning of the Mesh page clarifying this for newcomers would be good, because a Google search for "Godot mesh" is probably what most people would do (I did) when looking for MeshInstance methods.
