### ISSUE TITLE
Document how to get class information in Godot Engine

### ISSUE THREAD

**Issue by Aireek** [godotengine/godot-docs#3177]
I've seen videos of people having a clickable window that shows the class and information in Godot. How do I go about getting that?

![image](https://user-images.githubusercontent.com/61104563/74600248-8a8e0d00-505c-11ea-8eb5-3e36537f1dd6.png)

**Comment by akien-mga** [comment]
Press "Search Help" on the top rated that of the script editor (visible in this screenshot).

This could likely be documented in the Editor Manual section.

**Comment by robinlamb** [comment]
I think a good place to put this would be in Introduction to Godot's Editor, along with screenshots.  I would be happy to make these changes.

**Comment by Aireek** [comment]
I felt silly when I realized I just didn't click the right button, but after that I was able to take off and find everything I needed

**Comment by robinlamb** [comment]
I have made the edits on this page and created a pull request. https://github.com/godotengine/godot-docs/pull/3298

**Comment by pycbouh** [comment]
The PR was not properly linked, but #3298 did indeed add the information about "Search Help". So, this is resolved now?

![image](https://user-images.githubusercontent.com/11782833/79733865-71286c00-82fe-11ea-8788-55a7318f985d.png)
https://docs.godotengine.org/en/latest/getting_started/step_by_step/intro_to_the_editor_interface.html#the-workspaces

**Comment by akien-mga** [comment]
Yes, fixed by #3298.

We removed the "Request Docs" button in master / 3.2.2 so the first screenshot might need to be redone, though it's low priority IMO (it's still fully understandable as is).
