### ISSUE TITLE
New website is very difficult to use in portrait mode on tablets

### ISSUE THREAD

**Issue by nok-ko** [godotengine/godot-docs#3186]
I find browsing the docs on my iPad in portrait mode impossible, as the sidebar covers up half of the page content, and I can't scroll horizontally.

![Screen Shot 2020-02-17 at 16 42 49](https://user-images.githubusercontent.com/13428215/74694371-bf0ce080-51a4-11ea-8bad-45fb76cad538.png)

**Comment by Calinou** [comment]
I'm not sure if this can be fixed easily, as this basically means we need to override *all* mobile breakpoints in the CSS so the iPad in portrait mode will use the mobile navigation bar.

**Comment by nok-ko** [comment]
@Calinou Adding a "Collapse Sidebar" button would be good, at least. 😅

**Comment by Calinou** [comment]
@nok-ko We don't need to collapse the sidebar on wider displays, so I'd prefer not.

**Comment by pycbouh** [comment]
Actually, it seems like a bug, that happens at exactly 768px wide viewport. In responsive mode in Chrome DevTools at 767px it's in mobile mode:
![image](https://user-images.githubusercontent.com/11782833/76626031-71885700-6549-11ea-8c45-d195c54f16f7.png)

At 769px it's in wide mode:
![image](https://user-images.githubusercontent.com/11782833/76626072-87961780-6549-11ea-8019-f72ece1c9e82.png)

But at exactly 768px it's this issue:
![image](https://user-images.githubusercontent.com/11782833/76626116-9c72ab00-6549-11ea-94f2-c367c6261cd4.png)

There is probably a rogue rule with a wrong media query.
