### ISSUE TITLE
Every tutorials that refers to PoolVector (C++) or Pool*Array (scripting) should be reviewed for 4.0

### ISSUE THREAD

**Issue by pyacier** [godotengine/godot-docs#3192]
After this [Convert all references and instances of PoolVector to Vector #36311](https://github.com/godotengine/godot/pull/36311) PoolVector do no longer exist, all tutorials referring to it need review.

**Comment by tetrapod00** [comment]
Closing, since after https://github.com/godotengine/godot-docs/pull/10329 the remaining references to Pool*Array, including a single tutorial, have been removed. I have to trust that in the four years since this was reported, the rest of the tutorials were updated correctly.
