### ISSUE TITLE
Creating MacOS export templates documentation missing?

### ISSUE THREAD

**Issue by diegodelarocha** [godotengine/godot-docs#3194]
Hi there, I've been learning how to compile the engine, and have found that there's instructions on how to create [Windows export templates](https://docs.godotengine.org/en/latest/development/compiling/compiling_for_windows.html#creating-windows-export-templates), but not for [Compiling for MacOS](https://docs.godotengine.org/en/3.2/development/compiling/compiling_for_osx.html), I think adding this would be very helpful to folks using this platform primarily, since they might just miss other platform examples.

**Comment by Calinou** [comment]
[This pull request](https://github.com/godotengine/godot/pull/36332) should greatly decrease the need for documenting the export template build process, as SCons will do it for you (like with HTML5 export templates).

The script to do so for now is:

```bash
# Build macOS export templates
scons platform=osx tools=no target=release_debug
scons platform=osx tools=no target=release

# Copy template files
cp -r misc/tools/osx_template.app/ bin/
mkdir -p bin/osx_template.app/Contents/MacOS/
cp bin/godot.osx.opt.debug.64 bin/osx_template.app/Contents/MacOS/godot_osx_debug.64
cp bin/godot.osx.opt.64 bin/osx_template.app/Contents/MacOS/godot_osx_release.64

# Create a ZIP archive
cd bin/
zip -r9 osx.zip osx_template.app/
```

**Comment by diegodelarocha** [comment]
Ah thanks for adding this for the future @Calinou 💜 That worked for now 🔥 Also quite grateful future pulls will do it automatically!
