### ISSUE TITLE
RichLabelText: remove get_total_character_count() if it's broken for years

### ISSUE THREAD

**Issue by golddotasksquestions** [godotengine/godot-docs#3195]
https://github.com/godotengine/godot/issues/36381
https://github.com/godotengine/godot/issues/12884

related:
https://github.com/godotengine/godot-proposals/issues/481#issuecomment-586636127

**Comment by Calinou** [comment]
This isn't a valid issue for the documentation repository, as the class reference isn't tracked here.

**Comment by golddotasksquestions** [comment]
@Calinou 
Adding what you proposed here would work too. Don't know why I did not think of that:
https://github.com/godotengine/godot/issues/36381#issuecomment-588963972
