### ISSUE TITLE
"Your first game" rewrite/restructure

### ISSUE THREAD

**Issue by Serge108** [godotengine/godot-docs#3205]
### So I've kind of finished **"Your first game" tutorial** from https://docs.godotengine.org/en/3.2/getting_started/step_by_step/your_first_game.html.
I had no experience in programming before so I learnt basics (vaiables, arrays, functions, cycles, conditions, etc) from other sources.

This is the feedback from the complete beginner with programming in general and, particularly, with GDScript.

Main inconvenience of the tutorial (for me) was that after finishing the Player scene an author goes rampage and writes lines of the code, whose validity I can't check. I can't play a scene and check if things work, for the code stays incomplete up to the end of the tutorial. Like if an author developed this small game, cleaned the code, revised it, changed it and **completely forgot about the reader's workflow.**

It would be OK and understandable if author at least give explanation smth like
"This code is here because this will be connected with this and it will work like that, just look at the evrthngisclear.gif"

Or maybe it was more of an overview of the engine than tutorial. I could not appreciate it though, for I did not manage to connect all those scenes in one working piece. I also was not able to track my mistakes for the same reason: inability to play incomplete scenes and check the code I've written.

There is a hope that this tutorial will be remade more consistent and workflow friendly.

**Comment by skyace65** [comment]
@cbscribe should this issue be closed since your PR was merged?

**Comment by cbscribe** [comment]
I think so - a new issue can be opened for any specific concerns someone may have.
