### ISSUE TITLE
Clearly Document Label's Use of "Visible" Characters

### ISSUE THREAD

**Issue by TheUltimateAbsol** [godotengine/godot-docs#3208]
**Describe the project you are working on:**
A visual-novel like game. It needs to display an exact amount of characters for every sentence using a "typing" animation.

The text is read in from an external file (and therefore is not hardcoded into the scene).

**Describe the problem or limitation you are having in your project:**
The Label class uses numbers from get_total_character_count() to determine the "visible_characters" property. However, this behavior is not documented at all.

Also, the wording of "get_total_character_count()"'s description mistakenly leads me to assume that all "whitespace" characters are ignored. However, this is not the case, as it will count '\r' as a printable character.

**Describe the feature / enhancement and how it helps to overcome the problem or limitation:**
Make these above features known in the documentation

**Describe how your proposal will work, with code, pseudocode, mockups, and/or diagrams:**
Add a description to the "visible_characters" property that clearly defines its behavior. This could be something like "Restricts the number of visible characters to display, as determined by get_total_character_count(). Set to -1 to disable."

Also change the description of "get_total_character_count()" from "Returns the total number of printable characters in the text (excluding spaces and newlines)." to "Returns the total number of printable characters in the text (excluding the space character ' ' and newline character '\n' ).

**If this enhancement will not be used often, can it be worked around with a few lines of script?:**
This addition to the documentation of course can be ignored, but it will cause potential headaches for others trying to understand the Label class.

**Is there a reason why this should be core and not an add-on in the asset library?:**
Not applicable.
If it was in the asset library, it would take much more effort for people to access this information.

**Comment by Calinou** [comment]
This is a documentation request, not a feature proposal, so I moved it.

**Comment by skyace65** [comment]
This was fixed in https://github.com/godotengine/godot/pull/55636. This issue can be closed.
