### ISSUE TITLE
If somebody could get this working that be great

### ISSUE THREAD

**Issue by MysticShadow117** [godotengine/godot-docs#3215]
WARNING: NOT SAFE FOR WORK!!!!!!
[ppppu-NXG-master.zip](https://github.com/godotengine/godot-docs/files/4269864/ppppu-NXG-master.zip)

**Comment by clayjohn** [comment]
This repo is for submitting issues about the Godot engine documentation. 

Given that you have posted something that looks suspiciously like a virus, I will be closing this issue.
