### ISSUE TITLE
Script debugging

### ISSUE THREAD

**Issue by mannyobb** [godotengine/godot-docs#3221]
I am trying to make a game but every time i press F6 to see whether everything is working correctly it comes up with this: 
Script inherits from native type 'KinematicBody2D', so it can't be instanced in object of type: 'Sprite'

**Comment by mannyobb** [comment]
how do you fix this

**Comment by Saitodepaula** [comment]
What about pressing F5?

Post a picture of the screen, and a minimal project to reproduce, and I think this issue does not belong here, but to https://github.com/godotengine/godot.

**Comment by Calinou** [comment]
This repository isn't intended to be used for support questions. Please use one of the other [community channels](https://godotengine.org/community) instead).
