### ISSUE TITLE
Tutorial example code not functional your_first_game.rst line 296

### ISSUE THREAD

**Issue by sijpkes** [godotengine/godot-docs#3231]
When completing the tutorial section I found the following issue with the GDscript code example at lines 294-8 in:

[getting_started/step_by_step/your_first_game.rst](https://github.com/godotengine/godot-docs/blob/d4fd0de7ae3468a518df7b186934ee901028edd9/getting_started/step_by_step/your_first_game.rst)

This is either missing a step (position could be out of scope), but the example works when specifying the object instance:

```ts
296:	$AnimatedSprite.position += velocity * delta
297:	$AnimatedSprite.position.x = clamp($AnimatedSprite.position.x, 0, screen_size.x)
298:	$AnimatedSprite.position.y = clamp($AnimatedSprite.position.y, 0, screen_size.y)

**Comment by cbscribe** [comment]
In what way is it not functional? This tutorial has been working for quite some time now.

**Comment by akien-mga** [comment]
This should work fine if your script is on the `Player` `Area2D` node. It also inherits Node2D and can have its `position` changed, like `$AnimatedSprite`. The `AnimatedSprite` should move together with its parent `Area2D`.

**Comment by sijpkes** [comment]
@akien-mga Thanks for this, I'm not sure what you mean. If I remove the `$AnimatedSprite.` and just use `position.x` the sprite will not move. Is it something to do with how/where I am attaching the script or my nesting? 

@cbscribe It's not functional (for me) in the way I described in the question.

**Comment by sijpkes** [comment]
Ok, I've figured it out.  I had put these lines in _process function instead of the Input movement lines from the tutorial.  I must have jumped ahead. 

```gdscript
velocity.x = Input.get_action_strength("move_right") - Input.get_action_strength("move_left")velocity.y = Input.get_action_strength("move_down") - Input.get_action_strength("move_up")
```

**Comment by cbscribe** [comment]
I'm not sure where you jumped to. This tutorial doesn't use `get_action_strength()` anywhere.
