### ISSUE TITLE
Wrong shortcuts in step-by-step guide?

### ISSUE THREAD

**Issue by bwasty** [godotengine/godot-docs#3244]
I'm following the step-by-step guide using 3.2 on macOS and [this page](https://docs.godotengine.org/en/stable/getting_started/step_by_step/intro_to_the_editor_interface.html) mentions the shortcuts F1-F3 for switching workspaces. They don't work - it seems they're actually Alt+1 through Alt+3 (only on macOS perhaps?).
Similar for F4 to 'search the reference' - in the editor settings I found Shift+F1 for 'Search Help' - is that what is meant?

**Comment by pycbouh** [comment]
You are correct, macOS often has different default shortcuts. Excerpt from `editor/editor_node.cpp`:

```
#ifdef OSX_ENABLED
	ED_SHORTCUT("editor/editor_2d", TTR("Open 2D Editor"), KEY_MASK_ALT | KEY_1);
	ED_SHORTCUT("editor/editor_3d", TTR("Open 3D Editor"), KEY_MASK_ALT | KEY_2);
	ED_SHORTCUT("editor/editor_script", TTR("Open Script Editor"), KEY_MASK_ALT | KEY_3);
	ED_SHORTCUT("editor/editor_help", TTR("Search Help"), KEY_MASK_ALT | KEY_SPACE);
#else
	ED_SHORTCUT("editor/editor_2d", TTR("Open 2D Editor"), KEY_F1);
	ED_SHORTCUT("editor/editor_3d", TTR("Open 3D Editor"), KEY_F2);
	ED_SHORTCUT("editor/editor_script", TTR("Open Script Editor"), KEY_F3); //hack needed for script editor F3 search to work :) Assign like this or don't use F3
	ED_SHORTCUT("editor/editor_help", TTR("Search Help"), KEY_MASK_SHIFT | KEY_F1);
#endif
```

Docs should definitely reflect that, and maybe note somewhere a reason for this difference.

**Comment by bwasty** [comment]
Found another one: in [this section](https://docs.godotengine.org/en/stable/getting_started/step_by_step/instancing.html#multiple-instances), Ctrl-D should be Cmd-D (or Cmd+D? Seems shortcuts are sometimes written with 'plus', sometimes with a dash).

**Comment by pycbouh** [comment]
So I think we should do two things here:
1. Start mentioning macOS shortcuts wherever they differ, at least in the most straightforward way:
> Press <kbd>F1</kbd> (or <kbd>Alt + 1</kbd> on macOS)
2. Introduce an article with a list of all default key mappings for every supported OS. This article can then be used by both users and contributors to check, if there are differences for a particular shortcut they want to refer.
