### ISSUE TITLE
Camera2D "zoom" variable should zoom in the view.

### ISSUE THREAD

**Issue by OGMP-Gyrth** [godotengine/godot-docs#325]
When you use the zoom variable in the Camera2D shouldn't the objects in it's view be bigger? Like how a real camera's zoom would?
Right now it "sees" more when the zoom is larger than 1.

**Comment by vybr** [comment]
Use a value smaller than 1 (e.g. 0.5 to zoom in 2x). The zoom value multiplies the size of the camera's viewports which is why it works backwards to how you think it would.

**Comment by noidexe** [comment]
Yeah that can be very confusing.

**Comment by akien-mga** [comment]
I'm not sure why this is open on the docs repo? Is it a request to change the zoom logic in the engine (in which case it pertains to https://github.com/godotengine/godot), or to improve the documentation about the existing logic?

**Comment by NathanLovato** [comment]
Not relevant to the docs repo indeed, please discuss it on https://github.com/godotengine/godot
