### ISSUE TITLE
CameraServer should get a note about missing implementations

### ISSUE THREAD

**Issue by pwab** [godotengine/godot-docs#3255]
The [CameraServer](https://docs.godotengine.org/en/latest/classes/class_cameraserver.html) only works on OSX and iOS (based on ARKit). The implementation for Android based on ARCore is pending. There are no implementations for Linux or Windows - so it's not possible to access a webcam on those systems yet.

This should be documented in the description of the CameraServer and maybe also in the [CameraFeed](https://docs.godotengine.org/en/latest/classes/class_camerafeed.html) class.

This issue is based on a discussion in the [merged CameraServer PR](https://github.com/godotengine/godot/pull/10643#issuecomment-595565386) and the confusion that arised in the [Godot Q&A](https://godotengine.org/qa/56944/how-to-use-webcam-cameraserver-camerafeed-in-3-2-and-windows).

**Comment by jumpy88** [comment]
Hello @pwab, @BastiaanOlij, I've started doing some experiments with uvc and v4l2 to accede a USB camera from linux. I'd like to discuss this with you but I don't know which one could be the right place for this. Could be here or do you have a better idea?

**Comment by pwab** [comment]
Hey @jumpy88 indeed this should be moved to somewhere else. But I'm also not sure where. Maybe we could use the repository where the CameraServer implementation-test is embedded:
https://github.com/BastiaanOlij/godot3_test_projects/tree/master/TestCameraServer

What do you think @BastiaanOlij ?

**Comment by jumpy88** [comment]
Great! Let me know as you take a decision so that we can start discussing about which could be the best solution.

**Comment by BastiaanOlij** [comment]
Sorry for the late reaction, yes we should talk more about this because I would love people to start implementing more support for the camera server and maybe look into if GDNative can play a bigger role. Also not sure about the best place to discuss is.

**Comment by jumpy88** [comment]
@BastiaanOlij don't worry, 13 hours is not "late reaction" if you take into account the time zone ;)
Well, it seems we all agree one point: we don't know which is the right place for our conversation xD
What about if we start discussing in private messages? Can @pwab and I write an e-mail to your publicly visible address so that you can create a common conversation with both of us?
