### ISSUE TITLE
mislead for the RPC_MODE_MASTER

### ISSUE THREAD

**Issue by alexzheng** [godotengine/godot-docs#3259]
according to the document
RPC_MODE_MASTER = 2
Used with Node.rpc_config() or Node.rset_config() to set a method to be called or a property to be changed only on the network master for this node. Analogous to the master keyword. Only accepts calls or property changes from the node's network puppets, see Node.set_network_master().

a function tagged as master, for example:
master func test():
print("test")

can only be called from the node's network puppets.
However, when call rcp("test") on the network master of that node, this function will called on that peer locally as mastersync.
but in this way it is not called from the the node's network puppets.

So it is NOT ONLY accepts calls or property changes from the node's network puppets.
It can also accept rpc calls from local peer if thelocal peer is the master of the node.

Also the RPC_MODE_PUPPET have the same problem.

**Comment by Faless** [comment]
@alexzheng what version of Godot are you using? Can you provide a minimum reproduction project?

**Comment by Faless** [comment]
Closing as stale.
