### ISSUE TITLE
Please integrate the GDScript document into the help system of the Editor.

### ISSUE THREAD

**Issue by alexzheng** [godotengine/godot-docs#3260]
https://docs.godotengine.org/en/stable/getting_started/scripting/gdscript/index.html
The script language reference is a quit useful document for daily use when write gdscript.
It would be quit useful if it is integrated into the editors Search Help system and search by the keyword for reference.

Thanks.

**Comment by Calinou** [comment]
The editor class reference only contains classes, not static documentation pages. I'm not sure if we can do anything about this.

**Comment by Calinou** [comment]
I'll close this, as this is more of an editor [feature proposal](https://github.com/godotengine/godot-proposals) than a documentation issue.
