### ISSUE TITLE
Update binary serialization docs

### ISSUE THREAD

**Issue by evandikt** [godotengine/godot-docs#3264]
Hi,

It's possible to assign name to Transform2d / Basis / Transform values ?
Like Vector2 / Plane / Quad 

http://docs.godotengine.org/en/latest/tutorials/misc/binary_serialization_api.html#transform2d

Thx :)

**Comment by aaronfranke** [comment]
Additionally, there is some wrong (or outdated) information in these files... I'll fix it.
