### ISSUE TITLE
GDNative C++ example issue at Example.cpp, sprite is not moving

### ISSUE THREAD

**Issue by GeorgeGRz** [godotengine/godot-docs#3269]
Hello, today I managed to get started using Godot engine using C++. I decided to follow the guide on the official documentation([GDNative C++ example](https://docs.godotengine.org/en/3.1/tutorials/plugins/gdnative/gdnative-cpp-example.html#building-the-c-bindingsrl)). Tho I had to place more code in order for this example to work.I changed **GODOT_CLASS(GDExample,Sprite) to GODOT_SUBCLASS(GDExample,Sprite)** and also added a public property(I know its bad practise but i wanted to see the example) godot_object ** owner; . I managed to build everything and run the code but I could not move the sprite.

**Comment by Calinou** [comment]
Can you create a ZIP archive containing the whole project and upload it here (by drag-and-dropping it)?

**Comment by GeorgeGRz** [comment]
I just got the version of master and everything was solved.Thank you!
