### ISSUE TITLE
Left panel sections are blocked by search bar when accessing their pages

### ISSUE THREAD

**Issue by YeldhamDev** [godotengine/godot-docs#3280]
When accessing a page, the section in the left panel that contains its title is placed at the top, but it's not taking into account the search bar:
![Screenshot_20200316_143035](https://user-images.githubusercontent.com/30739239/76784607-db07a000-67ab-11ea-82c5-7788943ba33b.png)

CC @Calinou

**Comment by pycbouh** [comment]
It should be fixed on `latest` with #3394 and all its predecessors.

![image](https://user-images.githubusercontent.com/11782833/79730221-3243e780-82f9-11ea-925d-2d01c3136740.png)
