### ISSUE TITLE
Should add an "Installation" tutorial for all platforms

### ISSUE THREAD

**Issue by sunnystormy** [godotengine/godot-docs#33]
It took me a while to realize that I needed to perform a "chmod +x" on the downloaded file in order to get the Godot Engine to run on my Linux machine. I'm not accustomed to ".64" files, nor have I ever encountered one prior to this application.

I think creating an "Installation" section in the documentation would be useful for all future users of the engine.

**Comment by akien-mga** [comment]
Having a whole installation section would be difficult to fill, as basically there is nothing to install. Godot is self-contained, and on all supported desktop platforms, Godot can be started out of the box by launching the binary.

On the other hand it's true that on Linux (and maybe OSX, *BSD and Haiku, did not check) it is necessary to make the binary executable. On Unix, the extension does not mean anything, so the ".64" here is just the last part of the binary's name, indicating that it's the 64-bit version of Godot; there is no proper extension per se (as is common with Unix binaries).

I'll try to find a visible place to put this information though, as it's not necessarily obvious to all Linux users, if e.g. they're not used to downloading third-party binaries.

**Comment by StraToN** [comment]
Having to make the binary executable is not specifically a Godot-related problem. A lot of Linux-version programs downloaded as already compiled binaries are extremely often made non-executables, certainly for security reasons. This is also generally true for runnable Java JARs downloadable through the web.

And even so, the terminal returns an explanatory error when trying to run an a binary that was not `chmod +x`-ed. Double clicking the binary to run it often does nothing in this case, and it is a big miss in Linux' file managers as you never understand immediately WHY your binary didn't run. The same goes for errors and/or segfaults. I'd love the file manager to raise a terminal if a crash happened during execution, and not when execution ended correctly. 

Short story: when a binary does not run when double-clicking it, always have the reflex to run it from the terminal.

**Comment by sunnystormy** [comment]
@akien-mga Thank you for clarifying, I think just adding a comment somewhere to make it more obvious will make a big difference. I ended up doing a hefty web-search before realizing that it was just a matter of changing the behavior of the file. : /

**Comment by akien-mga** [comment]
It could be cool to have such contextual information displayed on hover on the download section of the website before clicking the "Linux 64-bit" link. It could also be added for other platforms too, e.g. the windows binaries could show a line explaining that they are self-contained and don't need installation, just to be run.

@alketii Would that be doable? See e.g. http://www.mageia.org/downloads/ that has such a behaviour (though we should have *much less* info, and a cooler design ;))

An alternative could be to expand some text just below the link after clicking it, giving this contextual information (maybe in a more verbose way than what could be done on hover).

**Comment by reduz** [comment]
We could provide a zip or tar.gz file, as those keep the executable bit
when uncompressed

**Comment by akien-mga** [comment]
> We could provide a zip or tar.gz file, as those keep the executable bit when uncompressed

Right, that would be a good idea IMO (especially as on the OP website we had a bad mime type and browsers were trying to "read" the .64 Linux file instead of downloading it; and there are also antiviruses on Windows that will annoy users trying to download our .exe binaries).
