### ISSUE TITLE
Weird "0:" in properties tables 

### ISSUE THREAD

**Issue by Janglee123** [godotengine/godot-docs#3302]
https://docs.godotengine.org/en/3.2/classes/class_popupmenu.html#properties
https://docs.godotengine.org/en/3.2/classes/class_popup.html#class-popup

**Comment by pycbouh** [comment]
It stands for "override". This means that the property is defined in a parent class and its value is overridden in this class. For example, look at `window_title` in `AcceptDialog` and in its parent `WindowDialog`:
https://docs.godotengine.org/en/3.2/classes/class_acceptdialog.html#class-acceptdialog
https://docs.godotengine.org/en/3.2/classes/class_windowdialog.html#class-windowdialog

I agree, that documentation does not make it obvious whatsoever.
