### ISSUE TITLE
Docs say that KinematicBody2D does not receive collision information from some body types, which is wrong

### ISSUE THREAD

**Issue by zatherz** [godotengine/godot-docs#331]
https://github.com/godotengine/godot-docs/blob/master/tutorials/2d/physics_introduction.rst
![spectacle d17465](https://cloud.githubusercontent.com/assets/4568670/22042065/da184a94-dd09-11e6-9455-9133a119603d.png)

This is false, as you can receive collision information (including collisions with static bodies and kinematic bodies) with the `is_colliding` and `get_collider_*` methods.

**Comment by bojidar-bg** [comment]
I think the docs are speaking about `body_enter` signals and the such.

**Comment by skyace65** [comment]
@GDQuest this issue can be closed. This page was moved to the physics section some time ago and the wrong information was removed at some point.
