### ISSUE TITLE
Tileset: Provide complete Bitmasks reference textures for 2x2, 3x3 minimal, and 3x3

### ISSUE THREAD

**Issue by golddotasksquestions** [godotengine/godot-docs#3316]
[The documentation on Tileset and Tilemaps](https://docs.godotengine.org/en/3.2/tutorials/2d/using_tilemaps.html) desperately needs complete example Bitmask textures.
Noone really knows how to set them correctly, which just adds to the gigantic clusterfuck of a UI UX fail that this Tileset resouce is.
https://github.com/godotengine/godot/issues/37360

**Comment by golddotasksquestions** [comment]
Having tested them for a while now, I would suggest we add this 2x2 bitmask reference:
https://michagamedev.files.wordpress.com/2018/02/image5.png
![image](https://user-images.githubusercontent.com/47016402/79511461-a05d8580-803f-11ea-8f91-745135f70d21.png)

and this 3x3 minimal:
![image](https://user-images.githubusercontent.com/47016402/79511478-aa7f8400-803f-11ea-836b-53f21bf5653b.png)
Both are from[ this tutorial](https://michagamedev.wordpress.com/2018/02/24/181/).

I think we really need a similarly organized 3x3 reference as well, but I have no idea what that would look like and online searches yield no results.

**Comment by golddotasksquestions** [comment]
I made top down versions as well for the 3x3minimal, Those would be good additions as well:

green: floor
cyan: wall
yellow: wall top

"When you want to draw the floor":
![complete_3x3min_drawing_floor](https://user-images.githubusercontent.com/47016402/84060673-e63e2680-a9bc-11ea-94da-8aab4d2436d7.png)

"When you want to draw the walls":
![complete_3x3min_drawing_wall](https://user-images.githubusercontent.com/47016402/84060714-f81fc980-a9bc-11ea-91b4-35d64c3a0dd5.png)

"When you want to draw the walls, but have thicker walls" (have to use rectangular subtiles + alpha, otherwise you don't get equally thick horizontal and vertical walls, subtile size is x64 y88 in this case):
![complete_3x3min_drawing_wall_thicc](https://user-images.githubusercontent.com/47016402/84060881-3ddc9200-a9bd-11ea-9f24-b0121de59cf5.png)

**Comment by nightblade9** [comment]
@golddotasksquestions what settings does this template work with? I thought I set it up correctly, but I just get a pink wall:

![image](https://user-images.githubusercontent.com/31222662/86842584-69fa3a00-c073-11ea-9bc0-dbf64087292a.png)

**Comment by nightblade9** [comment]
For anyone else looking at this as a template in the future, I must point out that the following settings are required for this to work:

- TileMap cell size: 64x64
- Tileset AutoTile BitMask mode: 3x3 (minimal)
- Tileset subtile size: 64x64

Then it works fine.  If you use 32x32 subtiles, not only does it take forever to mask out, but you end up with just a solid pink blob.

![image](https://user-images.githubusercontent.com/31222662/86871876-1acefc00-c0a9-11ea-9127-f8f38314b9ae.png)

**Comment by golddotasksquestions** [comment]
@nightblade9 Yes, I set the size of those templates so it works with the default values, which is 64x64.

**Comment by Calinou** [comment]
Thanks for providing templates!

What would be the best way to expose them? Should we create a demo project containing them with the correct settings already in use, and refer to it in the documentation?

**Comment by nightblade9** [comment]
@Calinou I think many people - like me - would look at the AutoTile docs and expect to see a template there. I don't know if many people use the demo projects (I never have so far).

**Comment by golddotasksquestions** [comment]
@Calinou In future, I would envision some sort of bitmask "overlay" or template right within the Tileset editor, but for now I would think adding those templates and reference sheets to the documentation, with a few lines of description saying what they are and why they work well (with the default values). Like I did above. Adding a screenshot of the Inspector settings could also help with the top down versions.

**Comment by nightblade9** [comment]
I agree with @golddotasksquestions . The best would be to click a button and some "standardized" bitmask applies itself to your tileset, based on some sort of template.

But devs are smart! If you have the template and bitmask in the docs, I think that will be enough for most of us, most of the time. The real time-suck right now is tweaking the tile size + template + bitmask until it works, and then you just never touch it.

**Comment by mechPenSketch** [comment]
I want to add onto this thread, condensing 3x3 minimal template so that after accounting for flipping and rotating, these tile are all you need. This way, once the feature is ready, the new reference sheet will be ready to be deployed onto the doc.

However, I've noticed that 3x3 is missing a reference sheet, so I guess I can work on that first.

Starting with this 3x3 (minimum) sheet:
![3x3 minimum](https://user-images.githubusercontent.com/47016402/87044533-f5e89f00-c1f6-11ea-9178-67b2e357ee8a.png)
I can then add on diagonal lines. I will be doing my workings here until I can post the final reference sheet.

**Comment by mechPenSketch** [comment]
I think the regular 3x3 should be split into 2 categories based on usage, whether it's for filling space or drawing line. On this basis, 2 templates can be provided.

Following my previous workings, I can do a template for the former. Hopefully, 3x3 doesn't need all 256 tiles, but I need to test whether I can get away with cutting corners.

**Comment by golddotasksquestions** [comment]
@mechPenSketch You are missing a number of Tiles for a complete 3x3 Tileset, which would have 256 tiles. See this comment:

**Comment by devEyesgood** [comment]
I spent about 15 hours creating a grass tileset using the 256 tile template shown above.  I assumed the red sub-sections would indicate an edge touching the same kind of adjacent tile and I assumed the white sub-sections did not.  The result is something that doesn't look as expected.

![256-tile-fail](https://user-images.githubusercontent.com/16976618/120006469-e907a200-bfa6-11eb-857c-7a54348634f6.png)

Does anyone know what I might have done incorrectly?

**Comment by golddotasksquestions** [comment]
Can you share a minimal project with this til set so we can test it?

**Comment by devEyesgood** [comment]
@golddotasksquestions I will happily provide the tileset if it will help figure out the issue.  All I did was create a new 2d scene node, add a tilemap to it, create the tileset from the attached image and did the bitmasking as shown.

![SweetGrass3x3Bitmask](https://user-images.githubusercontent.com/16976618/120091328-05efc280-c0d8-11eb-8a60-0e493288a0b6.png)

**Comment by devEyesgood** [comment]
Update:  Ok, I have been thinking about this 256-tile scenario with the 3x3 bitmask and I believe I have figured out how this needs to work.  The tiles in the spritesheet are 64x64, but there are many combinations built in the bitmask logic that would never be relevant on a tilemap with a grid size that matches 64x64.  The bitmask is designed to interpret relationships between sub-tiles, NOT whole tiles.  Therefore, if the tilemap gridsize were reduced to 1/3 of the tileset size (64 / 3 = 21.33) or rounded to 22, the bitmask would be able to properly associate the sub-tile relationships as they are placed on the tilemap.

I reduced my tilemap size to 21x21 and here is what it looks like using my 64x64 256-tile autotile with the bitmask set to 3x3.
![3x3BitMask_Solution](https://user-images.githubusercontent.com/16976618/120108782-ae337480-c134-11eb-9c5d-ea6cd75d2d5e.png)

In order for this to work precisely, I would need to create a tileset that can be divided evenly into 9 equal parts (22px bitmask = 66px tile).  I also would need to be pixel-perfect at the connecting points of the tiles, as shown here.

![MyTileMakerTemplate](https://user-images.githubusercontent.com/16976618/120109050-c2c43c80-c135-11eb-8b45-dff2880d8e89.png)

I am going to play around a bit more with this, but I hope my discovery helps the community to use the 3x3 bitmask effectively.

Here's to progress!

**Comment by Drachenbauer** [comment]
I wonder, why everyone here, who creates a full 3xe tbitmask, uses a whide rectangle with a bit empty space in the bottom right corner.

the 256 tiles will fit perfectla in a square of 16x16 tiles:
![full 3x3 bitmask](https://user-images.githubusercontent.com/47259059/159081297-88528dfb-3661-480a-bb63-161e226942cd.png)
in this order it´s easy to create all possoble combinations of connections.

**Comment by devEyesgood** [comment]
> I wonder, why everyone here, who creates a full 3x3 bitmask, uses a wide rectangle with a bit empty space in the bottom right corner.
> 
> the 256 tiles will fit perfectly in a square of 16x16 tiles: ![full 3x3 bitmask](https://user-images.githubusercontent.com/47259059/159081297-88528dfb-3661-480a-bb63-161e226942cd.png) This is the most compact order and holds no empty tiles in this order it´s easy to create all possible combinations of connections. just draw the first two in the top right corner,copy them to the right and in the copied ones add a position, that none of them have yet. repeat these two steps until the row is full and than with rows down until the whole square is filled.

Very good point.  I was following a previous template and it was easier to keep track if mine were in the same position.

**Comment by golddotasksquestions** [comment]
To be honest I tried my own patters for the full 256 3x3 various times and never got it to work. No idea why, where I made the mistake. My only success with full 256 3x3 was thanks to using the [TilePipe tool](https://aleksandrbazhin.itch.io/tilepipe) by aleksandrbazhin.

**Comment by SeanRamey** [comment]
@Calinou So, what exactly happened to these reference bit masks for all these tileset possibilities?? Seems completely absent from the documentation now.

**Comment by nightblade9** [comment]
@SeanRamey  there are plenty of samples in this issue that you can use.

**Comment by SeanRamey** [comment]
> @SeanRamey there are plenty of samples in this issue that you can use.

Yes, but I'm thinking of others too, not just myself. The docs should have these, and apparently did at some point, but now they dont?

**Comment by strawstack** [comment]
I often search the internet for the templates that are in this issue. I get frustrated when I can't find them in the docs. The way I found them this time was searching "Godot autotile templates" then looking at images. I though I'll just download what I can and create my own templates from scratch since these templates seems to have largely vanished from the internet. I clicked a link to this post, and it seems like many other people have a similar issue. I guess I'll add these templates to my own repo and start a personal collection then make a Youtube tutorial that links to my repo.

**Comment by strawstack** [comment]
Also, this video shows off a DualGrid system which it would be nice if Godot supported: https://youtu.be/jEWFSv3ivTg?si=3YpaVI0FArZPbdde

I though maybe I could make an EditorScript or EditorPlugin that would allow me to make a DualTile map tool, but it seems like an EditorScript at least cannot receive events like "tilemap changed" when one is using the editor.

**Comment by strawstack** [comment]
Here's my repo with various templates if it's useful to anyone: https://github.com/strawstack/GodotTileTemplate
Feel free to add an issue if there is another template I should add.

**Comment by Bound2bCoding** [comment]
I ended up writing my own bitmasking code which, not trying to toot my horn, ended up being a much faster solution for my turn-based survival game.   This leaves me with just having to use the 16-tile sprite layout. I have videos up on my YouTube channel which discuss my solution step-by-step if I remember correctly.  Here is a link to the [video](https://www.youtube.com/watch?v=LEZGrHyWNmQ). Thanks for memorializing these templates.

**Comment by OriginlessGamer** [comment]
I wanted to contribute here as well. I made a free tile generator tool which you can try out here: 
https://originlessgamer.itch.io/procedural-tile-generator

22.05.2026:
It applies the generated texture to a tilemap automatically. At the moment of posting this, it only supports 16, 32, 64 resolutions and only flat tiles, not the ones with walls as others previously shared. 

**Updated on 01.06.2026:**
- It now supports the tilemaps with walls, because I added 4 color channels (white, red, blue, green), which allow you to achieve the 3D effect
