### ISSUE TITLE
Tileset: Documentation needs to mention that Autotile bitmask only work properly with complete tilesets

### ISSUE THREAD

**Issue by golddotasksquestions** [godotengine/godot-docs#3317]
Here: https://docs.godotengine.org/en/3.2/tutorials/2d/using_tilemaps.html

To be precise: Completely set bitmask patterns, not necessarily the Tilesets textures themselves.
See https://github.com/godotengine/godot/issues/37360

**Comment by golddotasksquestions** [comment]
@Calinou Why is this labeled "enhancement"? How am I supposed to know which bitmask patterns are necessary if they are not documented anywhere?

**Comment by zyansheep** [comment]
This isn't necessary as of https://github.com/godotengine/godot/pull/27565 (wildcard bit implementation) and there should be a page on autotiling in general instead.

**Comment by golddotasksquestions** [comment]
@zyansheep If that's the case, can you help explaining what exactly is going on in https://github.com/godotengine/godot/issues/37360?

**Comment by zyansheep** [comment]
Sure, it implements a wildcard bit that can match many different bit masks. This allows you to create a smaller tileset by having certain tiles match a broad range of 3x3 bit masks.

**Comment by skyace65** [comment]
It seems like this issue was resolved and can be closed.
