### ISSUE TITLE
signals arg csharp example missing args?

### ISSUE THREAD

**Issue by rakkarage** [godotengine/godot-docs#3327]
https://github.com/godotengine/godot-docs/blob/master/getting_started/step_by_step/signals.rst

should these last two csharp examples about signals with args have args like the gd ones? thanks

    public class Main : Node
    {
        [Signal]
        public delegate void MySignal();
    }

**Comment by nathanwfranke** [comment]
Are you asking why it's not `public delegate void MySignal(bool value, int other_value);`?

**Comment by pycbouh** [comment]
Yes, they should. Good catch.

More examples of signals in C# are available here, if you need them:
https://docs.godotengine.org/en/stable/getting_started/scripting/c_sharp/c_sharp_differences.html#signal-keyword
https://docs.godotengine.org/en/stable/getting_started/scripting/c_sharp/c_sharp_features.html#c-signals
