### ISSUE TITLE
How to instance using code needs to be easier to find 

### ISSUE THREAD

**Issue by golddotasksquestions** [godotengine/godot-docs#3338]
In the Godot subreddit and in Discord, questions like "how do I instance a scene in code?" come up all the time, and I don't think it's those users fault for not searching the documentation. 
This info this is hard info to find in the documentation. The two pages that come up when using the docs search bar ([1](https://docs.godotengine.org/en/3.2/getting_started/step_by_step/instancing.html), [2](https://docs.godotengine.org/en/3.2/getting_started/step_by_step/instancing_continued.html#doc-instancing-continued)) should mention it, or at least link to it, but they don't.

The only place to find this info is [here](https://docs.godotengine.org/en/3.2/getting_started/step_by_step/scripting_continued.html#instancing-scenes). But it's nearly impossible to find by using either the online documentation search field or a search machine like Google. Either you stumble on it, reading page through page of the documentation, learn about it through some tutorial or shared a direct link.

I've remarked [here ](https://github.com/godotengine/godot-docs/issues/3097)that this needs to be fixed, but it really deserves it own issue.

It's really dead simple to instance a scene in Godot:
```
var scene = load("res://scene.tscn").instance()
add_child(scene)
```
but the documentation anyone finds when doing an online search for "godot instance" "how to instance a scene in godot" Is two full pages of endless text that make it seem a million times more complicated for no reason. 
This is really something very basic and a incredibly common operation even a beginner would want to do. I believe the code sample should be right near the top of the first Instancing tutorial page and there should be a link to the in depth code explanation.

**Comment by Calinou** [comment]
Should we add this information in the class reference as well (in PackedScene and/or Node)?

**Comment by golddotasksquestions** [comment]
Idk. Maybe a link to [this page](https://docs.godotengine.org/en/3.2/getting_started/step_by_step/scripting_continued.html#instancing-scenes) would be enough?
I just know I have been trying to look up this up multiple times so I could provide a link to someone in the community channels, and it always was incredibly hard to dig up because does not show up in searches and the pages about instances that do, don't provide this information and don't have a link to it either. More links to it would definitely be a good thing.

**Comment by akien-mga** [comment]
> The only place to find this info is [here](https://docs.godotengine.org/en/3.2/getting_started/step_by_step/scripting_continued.html#instancing-scenes).

This is the Step by Step tutorial, which is meant for *every* user to start with to get familiar with the engine's concepts. Skipping it does mean that you miss important information.

**Comment by willnationsdev** [comment]
There is also a demonstration of how to do this in the step by step page on [Resources](https://docs.godotengine.org/en/3.2/getting_started/step_by_step/resources.html#loading-scenes).

**Comment by golddotasksquestions** [comment]
@akien-mga 
Not everyone is learning the same way. Just because you think users should learn this way, does not mean they will, want or can learn like that. I for one would have never started to learn and use Godot if there were no video Tutorials. I find text tutorials incredibly tiring and only resort to them if I cannot find a video tutorial.

Every user is different. The documantation should be constructed so that as much users as possible find the information they are looking for, regardless of their learning needs of preferences.
There is no reason not to link commonly used and basic info throughout the documentation so that it is more easy to find regardless where you are coming from.

All of that is besides the point though, because even if the first thing you did as a novice Godot user is the step by step, and you try to look it up again because you forgot, it is still incredibly hard to find using search machines or the build in websearch.

**Comment by golddotasksquestions** [comment]
@willnationsdev 
also the difference to "Will load when the script is instanced" and "Will load when parsing the script" means exactly nothing to someone who does not have extensive programming background. 
@KoBeWi [here ](https://www.reddit.com/r/godot/comments/fsz77h/how_do_you_instantiate_an_object/fm4ns1k?utm_source=share&utm_medium=web2x) mentioned that you can use preload anywhere in script and it will have the same effect as when it is used onready. If that's really the case, then I think this should be mentioned there as well (in plain speak also a non veteran programer can understand, like KoBeWi did there)

**Comment by willnationsdev** [comment]
@golddotasksquestions 

> the difference to "Will load when the script is instanced" and "Will load when parsing the script"

Not even really accurate either, so that should be re-worded. Afaik, `load()` will load the dependent resource at runtime when the logic executes and `preload()` makes the scene file load the dependent resource when the scene itself is loaded (whichever scene contains the script with the `preload()` statement).
