### ISSUE TITLE
Automatically redirect docs.godotengine.org to HTTPS

### ISSUE THREAD

**Issue by zyansheep** [godotengine/godot-docs#3342]
Hello! This might not be the right place to ask this, but...
Today I just noticed that the docs.godotengine.org domain is not served over https. This is not horrible, but it could open certain users up to MITM attacks that spoof links to lead to bad websites. Is it possible to implement Lets Encrypt for the server hosting the docs?

EDIT: There is an HTTPS version however, the HTTP version does not redirect to it.

**Comment by pycbouh** [comment]
Just in case this nginx rule before the `listen 443 ssl` rule should suffice:

```
server {
        listen 80;
        server_name your_hostname;
        return 301 https://$host$request_uri;
}
```

**Comment by Calinou** [comment]
@pycbouh While we're at it, it would be a good idea to [enable HSTS](https://scotthelme.co.uk/setting-up-hsts-in-nginx/) as well.

**Comment by akien-mga** [comment]
> And if everything is handled by RTD, then this is a withstanding issue: readthedocs/readthedocs.org#4641

Some RTD users seem to use a JS redirect in their sphinx theme to work this around: https://github.com/runwayml/model-sdk/pull/28

Otherwise, I don't know if it's something we can configure on our side. It does seem like not given all the users of RTD on custom domains with the same problem that we have. CC @punto-

**Comment by zyansheep** [comment]
It should be mostly fine to leave the HTTP page up if google and other search engines list the site as HTTPS in search results. I couldn't find anything related to this but is it possible to `Disallow:` http urls in robots.txt or somehow modify the google web console?

**Comment by mhilbrunner** [comment]
After https://github.com/godotengine/godot-docs/pull/3422 and https://github.com/godotengine/godot-docs/pull/3461, search engines should now start greatly preferring `https://` versions of the URLs as our canonical URLs.
