### ISSUE TITLE
Some "step by step" UI images outdated

### ISSUE THREAD

**Issue by winston-yallow** [godotengine/godot-docs#3348]
Some images in the step by step guide are outdated. I would like to recreate these with the current 3.2 version (nothing more, no content changes).
I could check all images and make a PR if this is a wanted update.

**Comment by pycbouh** [comment]
Sure, stable version should use the most recent UI images, if possible. Go ahead.

**Comment by winston-yallow** [comment]
I've started working on this. I noticed that not only the images are outdated but also some descriptions could be adjusted. For example it states that the animation sprites editor automatically opens once a SpriteFrames resource is created which is not always the case.

What would be better:
1. Track all these inaccuracies in a seperate issue and keep this to just the images for now.
2. Fix them as I go, but then this will probably take me a bit longer as I just started.

**Comment by pycbouh** [comment]
You can certainly create a single PR with various improvements to the "Step by step" guide.

**Comment by winston-yallow** [comment]
Hey, sorry for the late note. I will not be able to do this because of a lack of time. I had some unexpected events and therefore did not make any progress on this. If anyone else wants to do this please feel free to do so. I may have more time in a few weeks and will check then if this is still open, but until then I will not be able to work on this.
