### ISSUE TITLE
Scenes and Nodes image text difficult to read

### ISSUE THREAD

**Issue by aidenpain** [godotengine/godot-docs#3351]
So I just got into looking at Godot Engine and I came across this image in both the [Scenes and Nodes](https://docs.godotengine.org/en/stable/getting_started/step_by_step/scenes_and_nodes.html#nodes) and the [Instancing](https://docs.godotengine.org/en/stable/getting_started/step_by_step/instancing.html#introduction) tutorial sections:

![tree_old](https://user-images.githubusercontent.com/25288606/78720214-46e4b080-78f3-11ea-883c-9c33ed8ff607.png)

The image itself has dark text with a transparent background, and because the background of the documentation page is dark, it's hard to read. I imagine what happened was the documentation's theme was changed at some point (it looks fine on the GitHub page, which has a white background). I made a quick copy of it in Inkscape, this time with a white background:

![tree_revised](https://user-images.githubusercontent.com/25288606/78720108-16047b80-78f3-11ea-96d7-44a0f7102201.png)

I figured changing this would be as good a first PR as any, so please let me know if there's any issue with this or if I should change anything!

**Comment by pycbouh** [comment]
Yes, some images were added before a dark theme became available. They do indeed need to be updated. Make sure you check it against both dark and light themes. Dark theme can be disabled in CSS.

**Comment by Calinou** [comment]
I did a pass in https://github.com/godotengine/godot-docs/pull/3130 but it seems I missed a few images.
