### ISSUE TITLE
Statements Don't Agree With Code

### ISSUE THREAD

**Issue by Bruce200** [godotengine/godot-docs#3356]
In Getting Started -> Scripting -> GDScript -> GDScript Basics
Under Statements and Control Flow
It says " `;` as a statement separator is entirely optional."
Later, in the code, it uses colons at the ends of the `if`, `elif`, and `else` statements.
```
if [expression]**:**
statement(s) 
elif [expression]**:**
statement(s) 
else: 
statement(s)**:**
```
I don't know enough about Godot and GDScript to know which is the correct one (or if both are) and make the edit, and was hoping someone a bit more knowledgeable could clarify that.

**Comment by Calinou** [comment]
`;` is a semicolon, `:` is a colon. Colons are required at the end of `if`, `elif`, `else` and `match`, but semicolons are *never* required anywhere.

**Comment by Bruce200** [comment]
> `;` is a semicolon, `:` is a colon. Colons are required at the end of `if`, `elif`, `else` and `match`, but semicolons are *never* required anywhere. Semicolons allow you to place multiple statements on the same line, but doing so is generally discouraged as it makes the code more difficult to read.
> 
> It works pretty much the same way as in Python.

Thanks. I'll go in and fix it.

**Comment by Bruce200** [comment]
Okay, thanks. It definitely confused me. I did make a change, but you can probably undo it. Sorry. Glad we came up with a clear solution.

**Comment by Calinou** [comment]
@Bruce200 I don't see any open pull request from you on this repository, did you forget to open one?

**Comment by Bruce200** [comment]
Hmmmm. I thought I did. If there isn't one I either forgot or it possibly got uploaded? IDK. Check that the text is the same as at the beginning. If there is a semicolon in the first paragraph of the **Statements amd Control Flow** section then I forgot to open one. If there is a colon, it was appended or merged or whatever it is called.

**Comment by Bruce200** [comment]
*  **Statements and Control Flow**

**Comment by akien-mga** [comment]
I don't see any problem with this section:
https://github.com/godotengine/godot-docs/blob/master/getting_started/scripting/gdscript/gdscript_basics.rst#ifelseelif

![Screenshot_20200409_223725](https://user-images.githubusercontent.com/4701338/78938540-b228b100-7ab2-11ea-8089-b6a56103ebc7.png)

`:` starts a code block (which should be indented) following control flow statements.
It's not linked to `;` which can be used to separate statements which are not already separated by a line break.

**Comment by Bruce200** [comment]
I fixed a piece that was saying that a semicolon should be what you use instead of a colon, and that it is optional to use said semicolon. It said this in text, not in code. It should be fine now.

**Comment by akien-mga** [comment]
I'm not sure where you fixed it, but no change made by you was merged in this repository recently.

This is not a wiki but a git repository. If you changed it in your own fork, it's only changed for you, and you have to make a pull request that we would have to merge for the change to make it to the official docs.

**Comment by Bruce200** [comment]
I'm almost positive the pull request was merged.

**Comment by Bruce200** [comment]
Never mind. Just checked and it wasn't. I made a pull request, though. But I'm not sure if it is there.

**Comment by Bruce200** [comment]
Yeah. It is gone.?.

**Comment by akien-mga** [comment]
You made a pull request on your own fork, and merged it yourself on your fork.

**Comment by Bruce200** [comment]
Oops. I'm newer to github. I think it might not be necessary to change. I wss just confused.

**Comment by aaronfranke** [comment]
@Bruce200 I see that you created the change directly on GitHub. This caused the line endings to change, which isn't good. Instead, you should clone your repo locally, using the command line or using a GUI Git client, then open the file, change it, save, commit, push, and open a PR. If you need help, I created [this video](https://www.youtube.com/watch?v=0XKy8YpP5Ww) which shows my Git workflow.

**Comment by cbscribe** [comment]
Closing this as it seems it was a non-issue. Feel free to re-open if you find something else that needs to be addressed about this topic.
