### ISSUE TITLE
Add troubleshooting avenues for building [export templates] for Android

### ISSUE THREAD

**Issue by k4y4k** [godotengine/godot-docs#3361]
Howdy.

I have spent a long time, much too long, on figuring out why scons would not list `android` as an available platform when attempting to build export templates for Android from a fresh clone of the 3.2 branch from the repo + one small module.

I triple-checked that I had all of the prerequisites, version numbers, the whole shebang. Long story short, the missing link was that the environment values `ANDROID_HOME` and `ANDROID_NDK_ROOT` were unset, and these are mentioned nowhere on the docs or in the forums that I could see.

Thus, I would like to suggest that there is a small troubleshooting section or an aside added to the [Compiling for Android](https://docs.godotengine.org/en/latest/development/compiling/compiling_for_android.html#building-the-export-templates) section that mentions checking these two variables.

Thank you!

Edit: to be clear, [this (rather buried) issue](https://github.com/godotengine/godot/issues/27091) helped me solved my problem, and I came across it by chance after a very specific set and order of keywords entered into Google.

**Comment by Calinou** [comment]
Both of those variables are already mentioned on the page. The page is currently quite long, so I'm not sure if making it even longer is a good idea :slightly_frowning_face:

**Comment by k4y4k** [comment]
Wh-- **oh my God you're kidding me**. My bad :flushed:

**Comment by k4y4k** [comment]
Is it possible we could draw more attention to them, however?

**Comment by Calinou** [comment]
Nevermind, the current Troubleshooting section of the page isn't that long. So we can add a new item to it. I removed my previous comment as it's no longer relevant.
