### ISSUE TITLE
Mixed English and Ukrainian Language on uk urls

### ISSUE THREAD

**Issue by Onirik79** [godotengine/godot-docs#3367]
Like screenshot:

![godot](https://user-images.githubusercontent.com/12321983/78983127-dc668700-7b23-11ea-9eec-9d3e73fb34ff.png)

Google translate say it is Ukrainian and not russian language.
So far it has happened to me with uk urls.
No big problem because I can switch to en urls.

Maybe is a "World Wide Web URL Country Code confusion"
uk ->United Kingdom
ua -> Ukraine
Source:
http://www.bitmedia.com/cc/url1.htm

**Comment by akien-mga** [comment]
These are not country codes but language codes, and "uk" is the language code for Ukrainian. "en" is the language code for English.

Google seems bad at understanding that, but that will eventually be fixed once the Ukrainian translation is further along.
