### ISSUE TITLE
Android exporting requirements

### ISSUE THREAD

**Issue by jumpy88** [godotengine/godot-docs#3373]
[Exporting tutorial](https://github.com/godotengine/godot-docs/blob/master/getting_started/step_by_step/exporting.rst) says:
> Before you can export your project for Android, you must download the following software:
> - Android SDK: https://developer.android.com/studio/
> ...

but Android SDK is not actually required (and it's not so lightweight to be negligible). You just need:
- OpenJDK or Java JDK
- keytool
- adb

**Comment by Calinou** [comment]
That's true, but standalone `adb` isn't exactly easy to find last time I checked.

**Comment by jumpy88** [comment]
mmm...maybe it'd be better differentiating for operating systems:
- Debian/Ubuntu/Linux Mint: sudo apt install adb
- Fedora/openSUSE/CentOS: sudo yum install android-tools
- macOS: brew cask install android-platform-tools
- Windows: ...don't know which is the best option, maybe following [this guide](https://www.xda-developers.com/install-adb-windows-macos-linux/) or installing the entire Android SDK

**Comment by Calinou** [comment]
@jumpy88 Unfortunately, installing `adb` from Linux distribution repositories will likely give the user an old version. This is because repositories are typically frozen in a release's lifecycle.

**Comment by jumpy88** [comment]
I couldn't find the current adb stable version to check how old is the repository one. In general you are right, but we just need it to install the .apk file. What I can say is I'm using
`Android Debug Bridge version 1.0.39`
with Android 6.0 (I know, it's quite old) and it works fine. We could add a warning saying to check version compatibility if something goes wrong (and advice installing Android SDK just in case it is required).

**Comment by akien-mga** [comment]
As of Godot 3.3+ you do need the Android SDK for `apksigner` and `adb` (they're located automatically based on the Android SDK location configured in the editor settings).
This is also needed for custom builds, which is the workflow for the AAB support which will soon be mandatory.
