### ISSUE TITLE
Not clear how to specify the default font for CanvasItem::draw_string

### ISSUE THREAD

**Issue by Asaurus1** [godotengine/godot-docs#3374]
Per https://www.reddit.com/r/godot/comments/95pbpb/how_to_draw_a_string_using_the_default_font/, it might be a good idea to somewhere document how to draw a string in the default godot font. I am happy to put in a pull request if we can come to an agreement on the best place to put it. Modifying https://docs.godotengine.org/en/latest/classes/class_font.html#class-font or https://docs.godotengine.org/en/latest/classes/class_canvasitem.html#class-canvasitem-method-draw-string don't seem like the best ideas since they're class-generated documents, but I can't think of a better place.

**Comment by Calinou** [comment]
I'm trying the following snippet but it doesn't work if no theme is defined anywhere in the project:

```gdscript
extends Node2D

var font

func _ready():
	var control = Control.new()
	add_child(control)
	font = control.theme
	print(font) # [Object:null]

func _draw():
	draw_string(font, Vector2(), "Hello world")
```

**Comment by KoBeWi** [comment]
```
draw_string(Control.new().get_font("font"), Vector2(64, 64), "Hello world")
```
Maybe there should be some way to access the default theme globally. Like `Engine.get_default_theme()`.
