### ISSUE TITLE
Navigating through a complex dictionary is not mentioned on the docs or not clear.

### ISSUE THREAD

**Issue by MaximoTG98** [godotengine/godot-docs#3376]
So I am new to storage systems, and when parsing a complex json file I don't know **how to go to a key inside of another key in a dictionary**. I looked in these pages and didn't found it, searched on the q&a and few videotutorials and I'm not able to find how to do so.
Adding the explanation would be very helpful. Thanks.

https://docs.godotengine.org/en/latest/classes/class_dictionary.html#dictionary &
https://docs.godotengine.org/en/latest/getting_started/scripting/gdscript/gdscript_basics.html#dictionary

**Comment by Calinou** [comment]
```gdscript
func _ready():
    var dict = {
        "foo": {
            "bar": {
                "baz": true,
            },
        },
    }

    print(dict.foo.bar.baz) # Prints "True"
