### ISSUE TITLE
X isnt declared in the current scope, how do i fix this??

### ISSUE THREAD

**Issue by GerboPawa** [godotengine/godot-docs#3381]
extends Node2D

var noise = preload("res://Blocks/Scripts/softnoise.gd")
var block = preload("res://Blocks/Scenes/Block.tscn")

enum block_types{
	Block1,
	Block2,
	Block3
}

var world_depth = 32
var surface_heigth = 32
var chunk_width = 16

func _ready():
	
	var softnoise = noise.SoftNoise.new(5368568732)
	for x in range(0,chunk_width):
		var y= floor(softnoise.openSimplex2D((get_global_transform().origin.x/16+x)*0.1,0)*surface_heigth*0.2)
		
		
	new_block(Vector2(x*32,y*32),block_types.Block1)

func new_block(pos,type):
		var new_block = block.instance()
		new_block.translate(pos)
		new_block.block_type = type
		add_child(new_block)
		pass

**Comment by nathanwfranke** [comment]
Please fill out the issue template.

If you need help with your code, I would recommend checking out [the Discord](https://discordapp.com/invite/zH7NUgz)

**Comment by Calinou** [comment]
I'll close this issue per @nathanwfranke's comment. Please use one of the other [community channels](https://godotengine.org/community) for support questions.
