### ISSUE TITLE
Wrong language strings in docs

### ISSUE THREAD

**Issue by chepulis** [godotengine/godot-docs#3414]
I've stumbled upon two occasions of wrong language in the latest docs:

[Ukranian, i think?](https://docs.godotengine.org/uk/latest/tutorials/shading/shading_reference/canvas_item_shader.html)
<img width="786" alt="image" src="https://user-images.githubusercontent.com/11724303/79700217-dcd9ed00-829c-11ea-8b52-091cf227a041.png">

[And this should say "Constants"](https://docs.godotengine.org/fi/latest/tutorials/shading/shading_reference/shading_language.html#constants)
<img width="755" alt="image" src="https://user-images.githubusercontent.com/11724303/79700225-e8c5af00-829c-11ea-88eb-419af5c0eefd.png">

**Comment by pycbouh** [comment]
There is no issue here. First link is to a Ukrainian doc (hence /uk) and the second is to a Finnish one (hence /fi). These documents are not fully translated and are displayed partially in English. You can change your language using this menu:

![image](https://user-images.githubusercontent.com/11782833/79701132-347b5700-82a3-11ea-9794-b1d9a94f1491.png)

**Comment by chepulis** [comment]
Ah! I was mistaken by the search engine sending me to random places.
