### ISSUE TITLE
Linking to generic "stable" or "latest" URLs in the docs instead of specific versions

### ISSUE THREAD

**Issue by nice-shot** [godotengine/godot-docs#3417]
**Your Godot version:**
Any

**Issue description:**
When making Godot related searches on google, the documentation pages that show up are usually for specific older versions. For example, when I search ["Godot Tree"](https://www.google.com/search?q=godot+tree&oq=godot+tree&aqs=chrome.0.69i59j0l5j69i60l2.1735j0j7&sourceid=chrome&ie=UTF-8) I get the documentation page for Godot 3.0 tree class.
The page does include a note saying that this is not the latest version, but it points to a godot 3.2 URL instead of pointing to a more generic URL like "stable" or "latest". This means that future google results will keep pointing to specific versions that will probably be out of date.
I suggest pointing whenever possible to generic URLs and not version specific

**URL to the documentation page (if already existing):**
For example: https://docs.godotengine.org/en/3.0/classes/class_tree.html

**Comment by pycbouh** [comment]
This is a known issue. See #3262. If you have any suggestions on how to fix it, feel free to share them in the aforementioned issue. Keep in mind, that most of the server stuff is controlled by ReadTheDocs.

**Comment by Calinou** [comment]
Related to #1574.

**Comment by mhilbrunner** [comment]
https://github.com/godotengine/godot-docs/pull/3422 should fix this slowly but surely, Akien just created the `stable` branches for the translations, and `stable` is now what Google should point to by default.

Closing, and let us know if it still happens in a while :)
