### ISSUE TITLE
animatedsprite

### ISSUE THREAD

**Issue by MasterrenderStudio** [godotengine/godot-docs#3418]
**Your Godot version: v3.2.1**

**Issue description: i create new animation name "idle". i delete it couse i want to use another name,, but it tells me that no animation for idle. i didnt use it and i dont need it but it always shown, so i decide to create name "idle" but no animation. it is just for fix the bug shown**

**URL to the documentation page:**

**Comment by Calinou** [comment]
Please don't ask support questions here, as this issue tracker is meant to be used for documentation issues only. Use one of the other [community channels](https://godotengine.org/community) instead.
