### ISSUE TITLE
make qthelp fails on Debian Bullseye

### ISSUE THREAD

**Issue by Philius** [godotengine/godot-docs#3428]
make qthelp
sphinx-build -b qthelp -d _build/doctrees   . _build/qthelp
Running Sphinx v1.8.5
loading translations [en]... done

Extension error:
Could not import extension sphinx_search.extension (exception: No module named 'sphinx_search')
make: *** [Makefile:91: qthelp] Error 2

I have the following sphinx packages installed:
libjs-sphinxdoc
python3-sphinx
python3-sphinx-rtd-theme
sphinx-common
sphinx-rtd-theme-common

**Comment by Calinou** [comment]
Run `pip3 install -r requirements.txt` in the godot-docs root directory to install local dependencies.

**Comment by Philius** [comment]
Works.
Odd I didn't need to do that on Debian Buster.
Closing.
