### ISSUE TITLE
Browser issue with Godot documentation

### ISSUE THREAD

**Issue by Miezpiez** [godotengine/godot-docs#3430]
Code examples in the online Godot documentation pages are (all) corrupted for me:
They show every "x" as " (a single quote)
They show every "y" as a blank space

This makes checking the documentation kinda challenging.
I have the issue on different browsers (FireFox as well as Chrome) and on different PCs. I suspect it's a font, CSS and/or encoding issue and I've looked into it a lot but haven't been able to fix it. It only happens in code examples on the pages (within the html code tag?).
![extend](https://user-images.githubusercontent.com/33601566/80005120-72ef5c80-84c3-11ea-8db8-6433d72edd41.jpg)

**Comment by pycbouh** [comment]
This looks like Monaco. Are you on an older Mac?

**Comment by Calinou** [comment]
@pycbouh The font smoothing definitely reads like Windows to me.

@Miezpiez Can you change the default monospace/fixed-width font in your browser settings?

**Comment by pycbouh** [comment]
> The font smoothing definitely reads like Windows to me.

It can still be a Monaco clone on Windows 🙂 Out of all fonts we list for monospace, only Monaco matches in glyphs. But it can be something custom, I guess.

**Comment by Miezpiez** [comment]
This is up-to-date FireFox on Win 10. I will try and see what can be done with the mono font.

**Comment by Miezpiez** [comment]
Yeah, it IS displaying mono styled HTML with Monaco ... perhaps my Monaco font is weirdly glitched.

**Comment by Miezpiez** [comment]
Right - brute force fixed it by removing my Monaco font :-)
That seems to have worked, thanks for the hints, people!
