### ISSUE TITLE
"You are not using the most recent version" should point to "stable"

### ISSUE THREAD

**Issue by aaronfranke** [godotengine/godot-docs#3433]
![Untitled](https://user-images.githubusercontent.com/1646875/80045794-8821b680-84d6-11ea-8601-1f1fcbb137b9.png)

Currently, this notice links you to the "3.2" branch. Instead, it should link to "stable", since that will always be the most recent stable version.

**Comment by Calinou** [comment]
It seems this note isn't present in the `godot-docs` repository, but is rather added by Sphinx itself. I'm not sure if we can change it.

**Comment by Piralein** [comment]
The current Version looks like this:

![grafik](https://github.com/godotengine/godot-docs/assets/48352564/8d48a6da-1f76-4117-9449-3af000758e85)

All Versions <= 3.4 have this warning. Newer versions don't have this warning. Closing as this problem seems to be fixed.
