### ISSUE TITLE
Search behaves unexpectedly for a search bar

### ISSUE THREAD

**Issue by engineer0x47** [godotengine/godot-docs#3434]
**Operating system, Browser, Browser Version:**
All

**Issue description:**
Clicking in the "search bubble" on the Godot Docs website does not work as a search box

- "Search bubble" does not allow typing, but the cursor changes to a typing cursor on hover
- "Search bubble" pops up a jarring search box
- Clicking a doc link takes you to the section, but clears the "search bubble"
- Typing search text in the popup and pressing "enter" puts the text in the bubble.  This text looks editable but is not.
- Search results are destroyed after use

If the "search bubble" is always meant to make a distracting popup, make it a button instead.  Search results are destroyed after use, don't make it look like one can go back and look at the results.

**Screenshots (greatly appreciated if it’s a style issue)**

**Comment by Calinou** [comment]
We now use the [readthedocs-sphinx-search](https://github.com/readthedocs/readthedocs-sphinx-search) plugin, which provides support for "instant" searching without having to reload the page. It has a slightly unusual interface, but I don't think we can change it much at this point.

**Comment by engineer0x47** [comment]
I'll see about improving this in the upstream tool readthedocs-sphinx-search.  Thank you for looking at it.
