### ISSUE TITLE
xcode compile could be more precise

### ISSUE THREAD

**Issue by toger5** [godotengine/godot-docs#345]
in the docs it is not clear (for beginners) that the values in parentheses in the [post build action](http://docs.godotengine.org/en/stable/reference/configuring_an_ide.html#scheme-setup) are just placeholders and need to be replaced by the actual path.
It also would be cool to mention that selecting the Godot target for the: "Provide build settings from: " property

<img width="687" alt="screen shot 2017-02-17 at 22 25 30" src="https://cloud.githubusercontent.com/assets/16718859/23082001/0bc624e4-f560-11e6-9eeb-668fadc6ec00.png">

gives access to: ${PROJECT_DIR}
```ln -f ${PROJECT_DIR}/godot/bin/godot.osx.tools.64 ${PROJECT_DIR}/godot/bin/godot```

**Comment by StraToN** [comment]
I don't see any mention to values in parenthesis anywhere. Did you mean brackets? Just to be sure.

**Comment by toger5** [comment]
## copy pasted from the official 

Scheme Setup
Edit Build Scheme of External Build Target:

Open scheme editor of external build target
Expand the Build menu
Goto Post Actions
Add a new script run action
Write a script that gives the binary a name that Xcode will recognize

> in the following line the parenthesise have to be replaced with the actual path, or the Xcode macro `${PROJECT_DIR}` but that is not easy to figure out with the description.

e.g. ln -f “$SRCROOT”/bin/godot.osx.tools.64 “$SRCROOT”/bin/godot
Build the external build target
Edit Run Scheme of External Build Target:

Open the scheme editor again
Click Run
Set the Executable to the file you linked in your post build action script
Check Debug executable if it isn’t already
You can go to Arguments tab and add an -e and a -path to a project to debug the editor not the project selection screen
Test It:

set a breakpoint in platform/osx/godot_main_osx.mm
it should break at the point!

**Comment by toger5** [comment]
I checked the new changes you did! It is great now. Thank you!
