### ISSUE TITLE
Too many items in same lvl in class reference

### ISSUE THREAD

**Issue by toger5** [godotengine/godot-docs#346]
The class reference in the browser is really hard to use since it is sooo long. and I always have to scroll again...
Would it be categorise them by inheritance or just self made categories (like Nodes/3d,2d Resources/ Mesh/ Materials/  ....)?

**Comment by akien-mga** [comment]
It would be non trivial to do (keep in mind that the class reference is autogenerated from the `classes.xml` file of the main repo, any custom categories would have to be derived from it), and I'm not sure it would be that useful. It would make it harder to find classes at the end of a branch, as you would have to expand all higher level categories to find the page. Currently your best friend is the search function of your browser to find the right page :)

**Comment by StraToN** [comment]
A solution, as asked by @reduz, is to put the left panel in an IFrame.

**Comment by toger5** [comment]
I think this is more or less solved but the search function. So I close
