### ISSUE TITLE
Duplicated Export Documentation

### ISSUE THREAD

**Issue by Sauermann** [godotengine/godot-docs#3469]
**Your Godot version:** V3.2.1

**Issue description:**
Currently there are two documents describing how to export for Android. See links below.
They differ regarding the installation procedure for several aspects like Android SDK and JDK.

I suggest to streamline these two documents, so that they do not differ regarding dependencies installation.

**URL to the documentation page (if already existing):**
https://docs.godotengine.org/en/latest/getting_started/workflow/export/exporting_for_android.html
https://docs.godotengine.org/en/latest/getting_started/workflow/export/android_custom_build.html

**Comment by Calinou** [comment]
There are two ways to export to Android: the old way (described in Exporting for Android), and the new way (Custom builds for Android).

I don't know if the old way will be removed sometime in the future (probably not in 4.0, I doubt it).
