### ISSUE TITLE
Node#get_parent() return value is wrong if node doesn't have parent

### ISSUE THREAD

**Issue by nicktgn** [godotengine/godot-docs#3471]
**Your Godot version:**
3.2.1.stable

**Issue description:**
The description of the `get_parent()` method says:
> returns an empty `Node` if the node lacks a parent.

But it seems that it actually returns `null` if node doesn't have a parent.

**URL to the documentation page:**
https://docs.godotengine.org/en/3.2/classes/class_node.html#class-node-method-get-parent

**Comment by pycbouh** [comment]
I think it's the documentation issue. `null` is a perfectly sensible value here and "empty `Node`" makes no sense. There is no "empty" quality to a `Node`.

**Comment by cbscribe** [comment]
The `get_node()` description correctly states 
> If the path does not exist, a [code]null instance[/code] is returned
so I will update `get_parent()` to match that.
