### ISSUE TITLE
Tween Cheatsheet-Link improvement

### ISSUE THREAD

**Issue by Sauermann** [godotengine/godot-docs#3474]
**Your Godot version:** V3.2.1

**Issue description:**
In https://github.com/godotengine/godot/blob/316b60aa68bc348b8d6ab125ee2fb7cd3793cb49/doc/classes/Tween.xml#L19 there is a link to the `tween_cheatsheet.png`. The link however looks broken on the documentation-website.

In order to access the cheatsheet, currently I need to copy the string from the website and paste it into the url-bar of the browser.
I would expect that I can click on the link in order to access the cheatsheet.

**URL to the documentation page (if already existing):**

https://docs.godotengine.org/en/stable/classes/class_tween.html

**Comment by Calinou** [comment]
This is because reStructuredText doesn't allow including markup in bold/italic text :slightly_frowning_face: 

I'll open a PR to update the class reference. This should be fixed once the Web class reference is synced with the editor class reference.

**Comment by Sauermann** [comment]
Thanks for resolving this issue.
