### ISSUE TITLE
Documentation - update order

### ISSUE THREAD

**Issue by huhund** [godotengine/godot-docs#3475]
**Describe the problem or limitation you are having in your project:**

The update order of engine features such as input, animation, physics and collision response is unknown.

- It is important to know the order the engine executes to avoid hunting bugs that are expected behaviour depending on the update order
- Developers need to know the update order to minimise frame lags in the input->logic->render cycle
- The order of _integrate_forces() and _physics_process() works differently between 2D and 3D physics.

**Describe the feature / enhancement and how it helps to overcome the problem or limitation:**

Documenting the order of updates and callbacks, e.g. like this:
https://docs.unity3d.com/Manual/ExecutionOrder.html

**Comment by Calinou** [comment]
See #37702 for context.

**Comment by Calinou** [comment]
@madmiraal @aaronfranke Any pointers on this? (I don't expect anyone to know the execution order by heart, but help would be appreciated.)

**Comment by madmiraal** [comment]
The `Main::iteration()` loop function is here:
https://github.com/godotengine/godot/blob/db1eb909fe1e6067743892d7544160a1a40b9e43/main/main.cpp#L2116-L2270
Documenting what happens here will get you 80% of the way there.

**Comment by Calinou** [comment]
Closing in favor of https://github.com/godotengine/godot-docs/issues/5492, which has more information about the issue at hand.
