### ISSUE TITLE
[TRACKER] Needed redirects for Godot 4.0

### ISSUE THREAD

**Issue by mhilbrunner** [godotengine/godot-docs#3495]
- [ ] https://github.com/godotengine/godot-docs/pull/3412

**Comment by Calinou** [comment]
Out of curiosity, how are page redirects created with Sphinx?

**Comment by mhilbrunner** [comment]
Currently we create them manually in the ReadTheDocs admin dashboard, there you can edit a list of redirects (i.e. [source URL] -> [destination URL]).

**Comment by Vennnot** [comment]
Looks like this just needs one more and it's done!

**Comment by Calinou** [comment]
> Looks like this is already done!

Indeed, https://docs.godotengine.org/en/latest/tutorials/3d/spatial_material.html redirects to https://docs.godotengine.org/en/latest/tutorials/3d/standard_material_3d.html.
