### ISSUE TITLE
Search's "No results found" message is difficult to read when using the dark theme

### ISSUE THREAD

**Issue by Calinou** [godotengine/godot-docs#3498]
**Issue description:**

When using the dark theme, the "no results found" text is difficult to read since it's black on dark gray:

![image](https://user-images.githubusercontent.com/180032/81094461-d2a62880-8f03-11ea-8fef-bd2e0e5d0566.png)

**URL to the documentation page:** Visit https://docs.godotengine.org/en/latest/ and perform a search with a word that's not found in the documentation.

cc @pycbouh

**Comment by pycbouh** [comment]
Yeah, I saw that, but the issue is that these styles are applied inline instead of using classes. First and foremost it's the issue in the instant search plugin, I think. We can probably add our overrides using `!important`, but it's ugly...

**Comment by Calinou** [comment]
> We can probably add our overrides using !important, but it's ugly...

I'd argue ugly code is better than ugly appearance for the end user. :stuck_out_tongue:

**Comment by pycbouh** [comment]
@Calinou I've pinged the guys behind the extension in case they can fix it on their side before making local changes here. If they do so, I'll update our styles properly, if not, I'll do it ugly 🙂
