### ISSUE TITLE
Get X node missing in 3.2

### ISSUE THREAD

**Issue by Zarkaa** [godotengine/godot-docs#3507]
hello, i use visual scripting and i need the X only of a variable vector 2, but the node "get x" isn't in the new version 3.2 (it's the same probleme with Y)
how can i do that please ?

**Comment by mhilbrunner** [comment]
Github issues are not meant for support, but for bug reports. :)

 Have a look at the various [community channels](https://godotengine.org/community).

I've found the Discord to be a good place to ask questions. It even has a `visualscript` channel. If you get no answer there, maybe ask in the general channel!
