### ISSUE TITLE
SSL certificates aren't needed, they are optional.

### ISSUE THREAD

**Issue by vetu11** [godotengine/godot-docs#3511]
**Your Godot version:**
3.2.1-stable

**Issue description:**
In the second paragraph it says that SSL are needed.

> For SSL to work, certificates need to be provided. 

I am using the HTTPRequest without any SSL certificates added to the project and I'm able to successfully make an HTTPS request.

**URL to the documentation page:**
https://docs.godotengine.org/en/3.2/tutorials/networking/ssl_certificates.html
https://github.com/godotengine/godot-docs/blob/master/tutorials/networking/ssl_certificates.rst

**Comment by Calinou** [comment]
This is because the editor (and export templates) bundle [SSL certificates from Mozilla](https://github.com/godotengine/godot/blob/master/thirdparty/certs/ca-certificates.crt). The documentation needs to be updated to reflect this.
