### ISSUE TITLE
Screen shot in Documentation (anchors)

### ISSUE THREAD

**Issue by git2013vb** [godotengine/godot-docs#3534]
**Your Godot version:**
3.2.1
**Issue description:**
screen shot are not right (wrong copy and paste I guess)
**URL to the documentation page:**
 https://docs.godotengine.org/en/latest/tutorials/gui/size_and_anchors.html
https://docs.godotengine.org/en/stable/tutorials/gui/size_and_anchors.html

**Comment by skyace65** [comment]
Could you please be more specific? I don't see anything wrong with them.

**Comment by git2013vb** [comment]
Yes, of course :)
![image](https://user-images.githubusercontent.com/13235119/82328814-3df9fb00-99d8-11ea-8ab6-c3943e6f97dc.png)
The numbers are wrong :)

**Comment by pycbouh** [comment]
You cut out the part with anchors. `Left` and `Right` anchors are set to 1, which requires margins to have negative values to have the depicted result:

![](https://docs.godotengine.org/en/stable/_images/marginend.png)

**Comment by git2013vb** [comment]
> You cut out the part with anchors. `Left` and `Right` anchors are set to 1, which requires margins to have negative values to have the depicted result:
> 
> ![](https://camo.githubusercontent.com/985ecf2e61a3e9bcd301747c202421d6a5165999/68747470733a2f2f646f63732e676f646f74656e67696e652e6f72672f656e2f737461626c652f5f696d616765732f6d617267696e656e642e706e67)

Its the other one that is wrong :)

**Comment by pycbouh** [comment]
Yes, that one does seem incorrect.
