### ISSUE TITLE
Instant search results are broken

### ISSUE THREAD

**Issue by pycbouh** [godotengine/godot-docs#3565]
**Your Godot version:**
Any.

**Issue description:**
Instant search popup started to generate broken search results today. It appends `.html` extension twice, making links invalid.

This is probably related to readthedocs/readthedocs.org#7070 and readthedocs/readthedocs-sphinx-search#50.

I guess something RTD related must be updated? Also, we probably shouldn't depend on `master tip` in case of `sphinx-search` despite their recommendation to do so.

**URL to the documentation page:**
Example of a link: https://docs.godotengine.org/en/stable/classes/class_editorsettings.html.html

**Comment by akien-mga** [comment]
It seems to work fine on `latest`, I think a rebuild of `stable` and `3.2` will fix it.

**Comment by pycbouh** [comment]
Search seems to be working fine now on `stable` and `3.2`, and #3567 addresses the second part.
