### ISSUE TITLE
"Design a title screen": bad setup for MarginContainer

### ISSUE THREAD

**Issue by jwittenbach** [godotengine/godot-docs#3571]
**Your Godot version:**
v3.2.1.stable.official

**Issue description:**
Working through `Getting started -> Step-by-step -> Design a title screen`, and it seems like there are a couple of errors in the walk-through for setting up the outer `MarginContainer` node at:
https://github.com/godotengine/godot-docs/blob/master/getting_started/step_by_step/ui_main_menu.rst#prepare-the-main-menu-scene

1. The tutorial recommends using the "Full Rect" layout, which means that the right and bottom anchor values will be set to 1. However, it then recommends right and bottom margin values that are _positive_, but this will force the position of the contianer to fall _outside_ of the Viewport on the right and bottom. The margin values for right and bottom need to be _negative_ instead.
2. The tutorial recommends setting the margin values _before_ clicking `Layout -> Full Rect`. However these operations in that order in the current version of Godot will change the margin values to the values that they would need to be in order to keep the node in the same location, which is not the desired outcome here. The order of these two operations simply needs to be reversed.

If folks agree with my assessment on these, I'm happy to submit a PR with updates.

**URL to the documentation page:**
https://docs.godotengine.org/en/stable/getting_started/step_by_step/ui_main_menu.html

**Comment by skyace65** [comment]
Those seem like issues that should be fixed, PRs are always welcome!

**Comment by jwittenbach** [comment]
Actually just realized that I was confusing `Control -> Margins` (defined for all control nodes) with `Control -> Custom Constants -> Margins` (only defined for `MarginContainer`. Either can be used to get the desired results, though the sign on the margin values is different between the two approaches. So while my suggested change would not be incorrect, it is also not necessary.

Closing issue.
