### ISSUE TITLE
Change the line in documentation.

### ISSUE THREAD

**Issue by boruok** [godotengine/godot-docs#3583]
**Your Godot version:**
3.2.1
**Issue description:**
According to this [https://godotengine.org/article/csharp-android-support](url) article, Godot Engine **supports C# on Android** since 3.2, change the line documentation.
**URL to the documentation page:**
[https://docs.godotengine.org/en/latest/getting_started/scripting/c_sharp/c_sharp_basics.html#current-gotchas-and-known-issues](url)
in **Current gotchas and known issues** section.

**Comment by pycbouh** [comment]
I'm not sure which line are you referring to. The docs state that Android is in fact supported for Mono projects:

> Exporting Mono projects is supported for desktop platforms (Linux, Windows and macOS), Android, HTML5, and iOS.

Can you be more specific?

**Comment by boruok** [comment]
I've readed "exporting Mono projects is supported for desktop platforms (Linux, Windows and macOS), **Android, HTML5, and iOS. UWP is not currently supported.**"
hm, confused. Articles says C# now works on Android, meanwhile on documentation Mono **Android, HTML5, and iOS. UWP is not currently supported**.

**Comment by skyace65** [comment]
Hi, I'm going to assume that English isn't your first language.
"exporting Mono projects is supported for desktop platforms (Linux, Windows and macOS), Android, HTML5, and iOS." is one sentence. "UWP is not currently supported." is a separate sentence.

**Comment by pycbouh** [comment]
We can rephrase it a bit better, perhaps, so that two sentences are not blurred together.

**Comment by boruok** [comment]
> Hi, I'm going to assume that English isn't your first language.
> "exporting Mono projects is supported for desktop platforms (Linux, Windows and macOS), Android, HTML5, and iOS." is one sentence. "UWP is not currently supported." is a separate sentence.

chesus, i've missed dot in sentence. I sware that comma was here.

**Comment by boruok** [comment]
> We can rephrase it a bit better, perhaps, so that two sentences are not blurred together.

please, that will be helpful.
