### ISSUE TITLE
Unexpected Assign

### ISSUE THREAD

**Issue by SkeeVitch** [godotengine/godot-docs#3590]
#extends` KinematicBody2

const ACCELERATION = 10
const MAX_SPEED = 100
const FRICTION = 400

var velocity = Vector2.ZERO
func _physics_process(delta):
	var input_vector = Vector2.ZERO
	input_vector.x = Input.get_action_strength("ui_right") - Input.get_action_strength("ui_left")
	input_vector.y = Input.get_action_strenght("ui_up") - Input.get_action_strength("ui_down")
	input_vector = input_vector.normalized()
	
	if input_vector = Vector2.ZERO:
		velocity += input_vector * ACCELERATION * delta
	else:
 		velocity = velocity.move_toward(Vector2.ZERO, FRICTION * delta)

	print(velocity)
	move_and_collide(velocity * delta * MAX_SPEED)

I keep getting an unexpected assign issue error for the if input_vector = Vector2.ZERO:   
I don't know what I'm doing wrong?

**Comment by cbscribe** [comment]
`==` is for comparison.

This repository is for discussion of and contribution to the Godot docs. It is not for tech support. Please use one of the [Community Sites](https://godotengine.org/community) to get help.
