### ISSUE TITLE
how do i filter methods on godot (btw im new to godot dont judge me plz)

### ISSUE THREAD

**Issue by mrn00bpro** [godotengine/godot-docs#3597]

**Comment by skyace65** [comment]
This isn't the place to ask for help with the engine. If you need help checkout the Godot Discord, facebook group or IRC. These issues are for issues with the documentation.

**Comment by mrn00bpro** [comment]
oh ok thanks

**Comment by mrn00bpro** [comment]
but whats irc?

**Comment by Calinou** [comment]
@mrn00bpro IRC is Internet Relay Chat, a chat platform used by Godot users and developers. See https://godotengine.org/community.
