### ISSUE TITLE
What is NetworkedMultiplayerENet.transfer_channel?

### ISSUE THREAD

**Issue by mrimvo** [godotengine/godot-docs#3598]
**Your Godot version:**
3.2.1

**Issue description:**
Please explain the purpose of transfer_channels in NetworkedMultiplayerENet. Why should we use it? Is it possible for the receivers to subscribe to channels and in that way choose what data/RPCs to receive? Please clarify.

**URL to the documentation page (if already existing):**
https://docs.godotengine.org/de/stable/classes/class_networkedmultiplayerenet.html?#class-networkedmultiplayerenet-property-transfer-channel

**Comment by Calinou** [comment]
From http://enet.bespin.org/Features.html:

> ## Channels
>
> Since ENet will stall delivery of reliable packets to ensure proper sequencing, and consequently any packets of higher sequence number whether reliable or unreliable, in the event the reliable packet's predecessors have not yet arrived, this can introduce latency into the delivery of other packets which may not need to be as strictly ordered with respect to the packet that stalled their delivery.
>
> To combat this latency and reduce the ordering restrictions on packets, ENet provides multiple channels of communication over a given connection. Each channel is independently sequenced, and so the delivery status of a packet in one channel will not stall the delivery of other packets in another channel.
