### ISSUE TITLE
godot-docs search is broken (links have extraneous ".rst" in URI)

### ISSUE THREAD

**Issue by jjphung** [godotengine/godot-docs#360]
Searching "kinematicbody2d" on the godot docs website leads to this for all 7 results:
![screen shot 2017-03-27 at 3 28 13 am](https://cloud.githubusercontent.com/assets/6497318/24352191/7167cffa-129d-11e7-9e67-d3e2d67cb2c4.png)

I don't know if this is supposed to happen but searching "node2d" leads to the correct documentation for it. In order to get the documentation for kinematicbody2d, a google search can be made. Thanks!

**Comment by bojidar-bg** [comment]
This is a semi-known problem with the search -- sphinx somehow manages to give us a `.rst.html` link. E.g. here is the top result for `"kinematicbody2d"` on master:

`http://docs.godotengine.org/en/stable/classes/class_kinematicbody2d`**`.rst.html`**`?highlight=kinematicbody2d`

**Comment by akien-mga** [comment]
It seems to be this upstream bug: https://github.com/rtfd/readthedocs.org/issues/2708
