### ISSUE TITLE
Shearing is now possible

### ISSUE THREAD

**Issue by Jummit** [godotengine/godot-docs#3604]
**Issue description:**

There is an outdated note about shearing in the docs
> You can’t set the raw values of a Transform2D in the editor, so you must use code if you want to shear the object.

**URL to the documentation page (if already existing):**

https://docs.godotengine.org/en/latest/tutorials/math/matrices_and_transforms.html

**Comment by Calinou** [comment]
We should probably keep the part about 2D shearing for educational purposes, but add a note at the top to say that this is now offered out of the box in Node2D.
