### ISSUE TITLE
Correctness of AnimationPlayer's methods is affected when paired with an AnimationTree

### ISSUE THREAD

**Issue by mrushyendra** [godotengine/godot-docs#3610]
**Your Godot version:**
3.2 (and 4.0 as well)

**Issue description:**
This issue is a superset of points raised in godotengine/godot#38956 and godotengine/godot#34947.

When an `AnimationPlayer` object is paired with an `AnimationTree`, several properties and methods exposed by the `AnimationPlayer` class may not work as expected. Some of these include:

Properties:
```
current_animation
assigned_animation
current_animation_position
current_animation_length
playback_default_blend_time
playback_active
playback_speed
```

Methods:
```
is_playing()
get_current_animation()
get_assigned_animation()
seek()
seek_delta()
advance()
is_valid()
get_current_animation_position()
get_current_animation_length()
set_default_blend_time(), get_default_blend_time()
is_active(), set_active()
set_speed_scale(), get_speed_scale()
get_playing_speed()
```
While it may be clear cut that some of these properties/methods would not be valid when paired with an `AnimationTree`, others are more subtle.

The issues occur because an `AnimationTree` runs pretty independently, and uses its member `AnimationPlayer* player` primarily for its `Map<StringName, AnimationData> animation_set`. `AnimationTree::_process_graph()` calls `AnimationTree::_update_caches()` to get the `animation_set` from the `player` and  populate its `track_cache`, instead of calling `AnimationPlayer::play()` directly.

(https://github.com/godotengine/godot/blob/d2be503ebb79b168782c1fb97136ac86016cec6d/scene/animation/animation_tree.cpp#L526-L537)

Since this is a design decision and not a bug, it would be helpful to mention this issue in the `AnimationTree`'s class documentation.

**URL to the documentation page (if already existing):**
https://docs.godotengine.org/en/stable/classes/class_animationtree.html
https://docs.godotengine.org/en/stable/classes/class_animationplayer.html

**Comment by DarkMessiah** [comment]
> Since this is a design decision and not a bug, it would be helpful to mention this issue in the AnimationTree's class documentation.

I think it would be right if the AnimationTree controlled the AnimationPlayer and you could get all properties of AnimationPlayer correctly.
