### ISSUE TITLE
GDScript style guide: remove multiple blank lines between functions

### ISSUE THREAD

**Issue by vnen** [godotengine/godot-docs#3613]
The style guide recommends two blank lines between functions:

https://docs.godotengine.org/en/latest/getting_started/scripting/gdscript/gdscript_styleguide.html#blank-lines

I believe that's unnecessary blank space, leading to files with more lines than what they need. The indentation makes it clear when a new function begins.

One blank line should be enough separation.

**Comment by Calinou** [comment]
The standard in Python is to use 2 blank lines between functions, so @NathanLovato suggested that we do the same. If we want to deviate from this, we need strong approval from the community.

**Comment by NathanLovato** [comment]
In PEP8 part of the point is to separate (sub-)class methods visually from module functions, but also sub-classes between them. Considering you also have one line returns inside functions, the two lines do help with visual separation.

We've had long discussions about every point in the style guide in the past, especially this one. I'm fine with whatever change but let's pick one and stick to it because that's an unending topic. I'll try to find the original discussion.

**Comment by vnen** [comment]
Well, I'm not active on Discord so I missed this discussion (which it's kind of my fault too, but I can only keep up with so many channels).

From [PEP8](https://www.python.org/dev/peps/pep-0008/#blank-lines):

> Surround top-level function and class definitions with two blank lines.
>
> Method definitions inside a class are surrounded by a single blank line.
>
> Extra blank lines may be used (sparingly) to separate groups of related functions. Blank lines may be omitted between a bunch of related one-liners (e.g. a set of dummy implementations).

----

In GDScript we don't really have "top-level" functions. Everything is "method definitions inside a class", which are supposed to have a single blank line if we are following this. Might be a minor semantic distinction but also may be that we changed the spirit of that guideline when translating to GDScript. It makes more sense in Python because you can have top-level statements as well, which is also not a thing in GDScript.

If you don't want to discuss gain I'm fine to close this but I want to add an exception: I brought this up because I'm editing the docs and I noticed the spaces added in #3487. So at least in the docs, when showing example snippets, maybe we don't need to add the extra space. I don't think they're helpful there.

Might be a matter of taste but I feel that in a snippet with two or three small functions adding the extra space seems way too much.

For example, the inner class topic: https://docs.godotengine.org/en/3.2/getting_started/scripting/gdscript/gdscript_basics.html?#inner-classes

![gdscript-doc-blank-lines](https://user-images.githubusercontent.com/5599796/83333225-dbc1b580-a275-11ea-99ba-f0727669b5c8.png)

It's almost like the `print_value_of_a` function is standing on its own, not a part of the `SomeInnerClass`. This also strays from PEP8 in which "[m]ethod definitions inside a class are surrounded by a single blank line."

----

So even if the style guide doesn't change, I argue for the exception in small snippets.

**Comment by NathanLovato** [comment]
> If you don't want to discuss gain I'm fine to close this

No, it's not that I don't want it to be discussed, of course, people are welcome to discuss it anytime. It's more than I'd like to see it settled once and for all because the format of a lot of code, including the docs snippets and official demos, and the community-written code formatter depend on it.

> For example, the inner class topic: https://docs.godotengine.org/en/3.2/getting_started/scripting/gdscript/gdscript_basics.html?#inner-classes

I think the example should change in that case because the point is to differentiate the class's methods from its inner classes. As in Python:

```gd
class SomeInnerClass:
    var a = 5

    func print_value_of_a():
        print(a)


func _init():
    var c = SomeInnerClass.new()
    c.print_value_of_a()
```

It's not about semantics for me, it's about making it easier to differentiate blocks of related code at a glance. And to make any codebase as easy to read as possible across projects, especially when they get complex.

With unrealistic samples like these, it's hard to see a difference:

```gd
func some_function():
    # ...


func other_function():
    # ...


class SomeInnerClass:
    func some_function():
        # ...

    func other_function():
        # ...
```

But when files get several pages long, when you start working with a team, it helps. Let me prepare a small example.

**Comment by NathanLovato** [comment]
Here's a side-by-side comparison of the same code, with only the 2 line returns changed.

![Screenshot from 2020-05-30 10-33-17](https://user-images.githubusercontent.com/12694995/83334040-005f6280-a261-11ea-96ff-53a061baf67f.png)

I think the discussion also happened in part on the issue tracker, I'll try to find the original.

**Comment by NathanLovato** [comment]
It starts here on the tracker: https://github.com/godotengine/godot-docs/issues/2997#issuecomment-569977715

**Comment by vnen** [comment]
It makes more sense in a longer file, indeed. I don't want to revive the discussion.

I still argue for the exception on small snippets in the docs, given that's often incomplete code (even in the more "real-world" examples) and not something you will be copying and pasting into a project.

In particular for the "GDScript basics" page, which have tons of such snippets.

**Comment by NathanLovato** [comment]
> I still argue for the exception on small snippets in the docs, given that's often incomplete code (even in the more "real-world" examples) and not something you will be copying and pasting into a project.

The screenshot above itself looks off. Do you find it problematic in the entire docs? I don't know of many cases where snippets have two functions only several lines of code.

Moving forward, ideally, we could run all code in the docs through a code formatter and never worry about it. In which case it'd be the same rule everywhere.

**Comment by vnen** [comment]
> Moving forward, ideally, we could run all code in the docs through a code formatter and never worry about it. In which case it'd be the same rule everywhere.

I'm not confident that a formatter would work properly on the small snippets. Usually those expect well-formed files in the first place. This is assuming the can already work only inside the code blocks.

> I don't know of many cases where snippets have two functions only several lines of code.

Maybe it's only the GDScript basics page. There's some places where multiple functions are needed to illustrate a point, but they are only a few lines long (often only one). E.g. when explaining coroutines or how to connect signals.

**Comment by NathanLovato** [comment]
> I'm not confident that a formatter would work properly on the small snippets.

GDformat, the python one, works as long as the code has no errors. We also have a tool at gdquest to extract code from markdown documents for our courses. 

> There's some places where multiple functions are needed to illustrate a point, but they are only a few lines long (often only one). E.g. when explaining coroutines or how to connect signals.

Feel free to change the handful of snippets you saw.

I recall they're generally abstract and through the style guide, we also wanted to require all code to be more concrete. While foobar examples can make sense for a developer, it never hurts to replace that by a real-world minimal example. E.g. for coroutines, waiting for an animation or for a function that does a server request to finish.

**Comment by vnen** [comment]
> While foobar examples can make sense for a developer, it never hurts to replace that by a real-world minimal example. E.g. for coroutines, waiting for an animation or for a function that does a server request to finish.

I tend to agree but I also think if the example throws too many unrelated things, it will just be more confusing to understand the actual feature you are presenting.

> Feel free to change the snippets directly. We don't have to be too pretty about the documentation, it's something we can edit much more iteratively than the engine. The latest docs branch is like a staging area for the next release.

I opened the PR with my changes: #3623.

----

I feel that this matter is mostly solved now, since we won't be changing the style guide.
