### ISSUE TITLE
Node.editor_description documentation missing

### ISSUE THREAD

**Issue by sulai** [godotengine/godot-docs#3621]
**Your Godot version:**
3.2.1

**Issue description:**
Node.editor_description documentation missing

**URL to the documentation page (if already existing):**
https://docs.godotengine.org/en/stable/classes/class_node.html

**Comment by Calinou** [comment]
The way the property is bound means it's not part of the class reference. I don't know if this can be solved.

**Comment by KoBeWi** [comment]
`gizmo_extents` in Position2D has similar problem. I think it's ok if they don't have description, their name is descriptive enough.

**Comment by follower** [comment]
>  their name is descriptive enough.

I'll admit it's not 100% clear to _me_ what the _purpose_ is. :)

Is "Editor Description" equivalent to "a comment about the node--displayed in the editor--to assist in documenting your project"?

**Comment by Mickeon** [comment]
This is no longer the case in Godot 4.
![image](https://user-images.githubusercontent.com/66727710/198717193-e1984111-504b-4654-9089-ef2eec2aaa20.png)
