### ISSUE TITLE
About delta

### ISSUE THREAD

**Issue by Shaterpox** [godotengine/godot-docs#3627]
It might be great if there is has desrciption and some tutorial about delta

**Comment by Calinou** [comment]
I think the use of `delta` is well documented by now. For instance, in [Your first game](https://docs.godotengine.org/en/latest/getting_started/step_by_step/your_first_game.html).

That said, we don't mention what `delta` is exactly in [Physics introduction](https://docs.godotengine.org/en/latest/tutorials/physics/physics_introduction.html). We should do it there as well for completeness' sake.
