### ISSUE TITLE
Optimization Using Multimeshes c# code is wrong

### ISSUE THREAD

**Issue by Dr-Primary** [godotengine/godot-docs#3659]
Godot_v3.2-stable_mono_win64

C# code is non functional in the tutorial.  The current code has you create a new multimesh and assign it to a dummy variable but never actually assign that multimesh to the node that is in the scene.  as a consequence that dummy variable's changes never appear in the scene. The code needs to look like this:

```csharp
using Godot;
using System;

public class YourClassName : MultiMeshInstance
{
	public override void _Ready()
	{
         // Create the multimesh.
         Multimesh = new MultiMesh();
         // Set the format first.
         Multimesh.TransformFormat = MultiMesh.TransformFormatEnum.Transform3d;
         Multimesh.ColorFormat = MultiMesh.ColorFormatEnum.None;
         Multimesh.CustomDataFormat = MultiMesh.CustomDataFormatEnum.None;
         // Then resize (otherwise, changing the format is not allowed)
        Multimesh.InstanceCount = 1000;
        // Maybe not all of them should be visible at first.
        Multimesh.VisibleInstanceCount = 1000;
        // Set the transform of the instances.
        for (int i = 0; i < Multimesh.VisibleInstanceCount; i++)
        {
             Multimesh.SetInstanceTransform(i, new Transform(Basis.Identity, new Vector3(i * 20, 0, 0)));
        }
        }
}
```

https://docs.godotengine.org/en/3.2/tutorials/optimization/using_multimesh.html

**Comment by Calinou** [comment]
@Dr-Primary There's no `_Ready()` method in your snippet, is that intended? Also, is the class name change needed?

**Comment by Dr-Primary** [comment]
Ah i forgot that part, thanks! Its fixed now.  The class name change just makes it more clear to C# coders imo.  In c# you can't use the MultiMeshInstance directly but need to inherit it to your own class which you will have to name,
