### ISSUE TITLE
Sound: AudioStreamPlayer2D drag and drop a wav

### ISSUE THREAD

**Issue by CristianNieto** [godotengine/godot-docs#3661]
**Your Godot version: v3.2.2 beta4 

**Issue description: On AudioStreamPlayer2D, I can not Drag and drop a wav file to Stream property.

**Comment by skyace65** [comment]
This sounds like an engine bug, not a documentation issue.

**Comment by Calinou** [comment]
Closing, as this isn't a documentation issue.
