### ISSUE TITLE
Light documentation is missing units

### ISSUE THREAD

**Issue by aaronfranke** [godotengine/godot-docs#3670]
**Your Godot version:** 3.2

**Issue description:**

> float light_energy
> 
> The light’s strength multiplier.

The documentation is missing information on what units the energy is in. What are the units? Lumens? Lux? Candelas? This should be added to the documentation. @clayjohn 

**URL to the documentation page (if already existing):**

https://docs.godotengine.org/en/latest/classes/class_light.html#class-light-property-light-energy

**Comment by clayjohn** [comment]
It's a multiplier! Which is what it says in the documentation.

**Comment by aaronfranke** [comment]
What does it multiply? Obviously 2.0 is double 1.0, but what does 1.0 represent?

@clayjohn Right now @fire is working on a way to import lights from GLTF files, which are [very well documented](https://github.com/KhronosGroup/glTF/tree/master/extensions/2.0/Khronos/KHR_lights_punctual) but we don't know how to convert this into Godot units.

**Comment by clayjohn** [comment]
It multiplies the strength of the light. 1.0 is default brightness and 2.0 is double brightness.

> Right now @fire is working on a way to import lights from GLTF files, which are very well documented but we don't know how to convert this into Godot units.

I guess you'll have to create an arbitrary conversion factor to convert from Blender to Godot. This is a known problem. I made https://github.com/godotengine/godot-proposals/issues/723 to address it. But in 3.2 there is no perfect way to translate Blender units into Godot units (or non-units in this case).

**Comment by aaronfranke** [comment]
https://github.com/godotengine/godot/pull/39430 documents the current behavior, and https://github.com/godotengine/godot-proposals/issues/723 covers the issue of the lack of physical units in Godot, so I'll close this as resolved. Thanks!
