### ISSUE TITLE
Move "Code Style Guidelines" above "PR Workflow" in the "Contributing" section

### ISSUE THREAD

**Issue by noidexe** [godotengine/godot-docs#3686]
**Your Godot version:**
N/A

**Issue description:**
I wanted to submit my first PR so I started following the "Contributing" section step by step. 
I reach the PR Workflow section and managed to submit my PR correctly but then travis complained about clang-format errors. 
I asked around and learned how to fix it and now I'm reading the rest of the docs and the "Coding Style Guidelines" sections has an answer to that. 
I know I maybe should've read the complete contributing section first but I'm probably not the only one, so I think it would make more sense if the guidelines appeared before the pr workflow. 

**URL to the documentation page (if already existing):**
https://docs.godotengine.org/en/latest/community/contributing/index.html

**Comment by akien-mga** [comment]
I don't know about this, as the PR workflow is also valid for other types of contributions like writing documentation both in godotengine/godot and godot-docs, which each have their pages describing the style conventions. Moving the PR workflow page after all those pages (i.e. basically as the last page in the section) would make it harder to come by.

The "Ways to contribute" introductory page does refer to both pages in a prominent note in the code contribution section:
![Screenshot_20200614_112409](https://user-images.githubusercontent.com/4701338/84589825-a69a9300-ae31-11ea-981e-aa8b5503eb59.png)

**Comment by noidexe** [comment]
> I don't know about this, as the PR workflow is also valid for other types of contributions like writing documentation
I see. I wasn't considering that. Well I guess it makes sense. Thanks for the clarification.
