### ISSUE TITLE
Add a page synthetically listing all features supported in Godot

### ISSUE THREAD

**Issue by Calinou** [godotengine/godot-docs#3727]
I wonder if there would be an use for listing every feature supported by Godot. I was going through my old Google Docs and have found one such list written by reduz back in 2016. Here are its contents for posterity:

<details>

- Supported platforms
  - Windows Vista, 7, 8, 8.1, 10 (Desktop)
  - OS X
  - Linux (Ubuntu, Debian, Fedora, Arch Linux, and more), client and dedicated server
  - Android >= 4.0
  - iOS (iPhone and iPad)
  - HTML5 (through Emscripten)
  - Haiku
- 2D Graphics
  - Fonts
    - Bitmap fonts supporting outlines, shadows and gradients
    - Optional signed distance-field for large fonts
    - Dynamic fonts using Freetype
  - GUI
    - Standard GUI elements
    - Standard label
    - Rich text label (uses BBCode)
    - Button
    - Panels with tabs and scrolling
    - Checkbox
    - Check button (like on iOS)
    - Radio button
    - Horizontal/Vertical sliders
- 3D Graphics
  - GLES 2.0
    - Shadows
    - Supports self shadowing
    - Directional light shadows
      - Orthogonal
      - PSSM 2-splits
      - PSSM 4-splits
    - Omni light shadows
      - DPSM (shadow map)
    - Spot light shadows (single texture)
    - Shadow filtering
      - PCF5
      - PCF13 
      - ESM
    - Anti-aliasing
      - FXAA
    - Shaders
    - HDR
    - sRGB
    - Bloom
    - Color correction/adjustment
      - Brightness, contrast, saturation
    - Culling
      - View Frustum Culling
    - Mipmapping
      - Disabled
      - Trilinear filtering
      - Anisotropic filtering
- Animations
  - Animation Player
    - Direct Kinematics
    - Inverse Kinematics
- Audio
  - Linux
    - Alsa
    - PulseAudio
      - Mono channel
      - Stereo channel
      - 5.1?
      - 7.1?
- Networking
  - TCP
  - UDP
- Window management
  - Resizing window (or disallowing its resize)
  - Fullscreen with working Alt-Tab (even on Linux)
- Physics
  - SAT solver
  - Body types
    - Kinematic
    - Rigid
    - Vehicle
    - Static
  - Separate thread capable (or multithreaded?)
- Editor
  - Import
    - OBJ file format
    - COLLADA file format
  - Export ?
  - Node/Resource system
  - TileMap/GridMap
  - Animation Editor
  - Visual Shader Editor
- Configuration files
  - ConfigFile (INI)
  - JSON
  - Plain text parsing
- Scripting
  - GDScript
- Plugin system
</details>

I think this could be a useful resource for decision makers and developers looking to switch from another engine to Godot. What do you think?

**Comment by akien-mga** [comment]
I think that's a good idea. It's a lot of work to figure it all out and put everything in the right categories, but it's quite useful to be able to have an overview like this.
