### ISSUE TITLE
The Encrypting Save Games tutorial has a long nonsense paragraph.

### ISSUE THREAD

**Issue by CowThing** [godotengine/godot-docs#373]
http://docs.godotengine.org/en/latest/learning/features/misc/encrypting_save_games.html
The entire "Why?" section is long, and a waste of time to read. It could be shortened significantly.

**Comment by akien-mga** [comment]
Many consider it's the funniest section of the documentation and a hidden gem, I don't see why it should be removed. I love it personally.

**Comment by neikeq** [comment]
What would even be the point of the docs without this paragraph?

**Comment by MoraleMuffin5** [comment]
Sounds like some alt-right edgy shit. @CowThing is 100% right.
