### ISSUE TITLE
RENDER_2D in enum Monitor does not exist

### ISSUE THREAD

**Issue by lazyvainglory** [godotengine/godot-docs#3731]
**Your Godot version:**
Godot_v3.2.1-stable_win64

**Issue description:**
The enums RENDER_2D_ITEMS_IN_FRAME & RENDER_2D_DRAW_CALLS_IN_FRAME does not exist

![image](https://user-images.githubusercontent.com/45304248/85835590-e2d1da00-b7c7-11ea-9ded-d91b9ff7bab3.png)

**URL to the documentation page:**
https://docs.godotengine.org/en/stable/classes/class_performance.html

**Comment by clayjohn** [comment]
``RENDER_2D_ITEMS_IN_FRAME`` and ``RENDER_2D_DRAW_CALLS_IN_FRAME`` were added in 3.2.2 which is now stable. You are running 3.2.1 but looking at the docs for 3.2.2.

Please download the [latest stable build](https://godotengine.org/download/) and enjoy the new features and bugfixes :)
