### ISSUE TITLE
Mention that C# scripts should be compiled to impact the editor ([Export], [Signal], [Tool])

### ISSUE THREAD

**Issue by akien-mga** [godotengine/godot-docs#3740]
**Your Godot version:**
3.2.2

**Issue description:**
Add mention to that for C#, scripts much be compiled before `[Export]` and `[Signal]` hints can be used in the inspector.

Same should likely be done for `[Tool]` scripts if not the case already.

See godotengine/godot#39917.

**URL to the documentation page (if already existing):**
https://docs.godotengine.org/en/stable/getting_started/step_by_step/your_first_game.html

**Comment by balloonpopper** [comment]
This already appears to be in place. @akien-mga 

https://github.com/godotengine/godot-docs/blob/master/getting_started/step_by_step/your_first_game.rst
Line 200 : "If you're using C#, you need to (re)build the project assemblies whenever you want to see new export variables or signals. "
Line 461 : "// Don't forget to rebuild the project so the editor knows about the new signal."
461 is repeated again on line 1047

**Comment by Calinou** [comment]
@balloonpopper We should still document this on the [C# basics](https://docs.godotengine.org/en/latest/getting_started/scripting/c_sharp/c_sharp_basics.html) page, as it's relevant for all C# users.
