### ISSUE TITLE
Documentation versioning

### ISSUE THREAD

**Issue by profelis** [godotengine/godot-docs#375]
Now exist only `latest` build version of documentation http://readthedocs.org/projects/godot/
Will be great to compile/publish documentation every major release (2.0, 2.1, ... latest)

And yes, previous version can be found in builds log http://readthedocs.org/projects/godot/builds/

**Comment by akien-mga** [comment]
I don't understand what you're asking for. The page you linked explicitly shows that we *do* have documentation versioning, with a branch for 2.1, a stable branch (currently the same as 2.1), and the latest branch (master).

![spectacle t12711](https://cloud.githubusercontent.com/assets/4701338/25313122/7dfca808-2828-11e7-8663-74019c8f5455.png)

**Comment by profelis** [comment]
This issue is clone of very old issue https://github.com/godotengine/godot/issues/6369 . And yes, it's fixed already
