### ISSUE TITLE
Background Loading is outdated

### ISSUE THREAD

**Issue by Ansraer** [godotengine/godot-docs#3764]
**Your Godot version:**
4.0

**Issue description:**
As far as I can tell reduz replaced the entire Interactive Loading system with godotengine/godot#36640.
Instead of ResourceLoader::load_interactive users should now use:
```
Error ResourceLoader.load_threaded_request(path: String, type_hint: String = "", use_sub_threads: bool = false)
ThreadLoadStatus ResourceLoader.load_threaded_get_status(path: String, r_progress: Array = [  ] ) 
Resource ResourceLoader.load_threaded_get(path: String)
```
However, the documentation hasn't yet been updated to reflect this change.

**URL to the documentation page:**
https://docs.godotengine.org/en/latest/tutorials/io/background_loading.html
https://github.com/godotengine/godot-docs/blob/master/tutorials/io/background_loading.rst

**Comment by HolonProduction** [comment]
The issue was already fixed and can be closed.
