### ISSUE TITLE
Documentation for Node.add_child_below_node() is unclear as to which node is what

### ISSUE THREAD

**Issue by jamie-pate** [godotengine/godot-docs#3769]
**Your Godot version:**
3.2.2

**Issue description:**
The documentation for Node.add_child_below_node() does not specify whether the node you want to add is `node` or `child_node`. It's not clear which argument is the existing node and which is the node you are adding.

**URL to the documentation page (if already existing):**
https://docs.godotengine.org/en/stable/classes/class_node.html?highlight=add_child_below_node#class-node-method-add-child-below-node

**Comment by akien-mga** [comment]
Fixed by godotengine/godot#40265.
