### ISSUE TITLE
Skeleton 3D

### ISSUE THREAD

**Issue by Hromon** [godotengine/godot-docs#3771]
**Your Godot version:**
3.2.2
**Issue description:**
Hello, i would like to see a section in the skeleton documentation in 3D from code.
**URL to the documentation page (if already existing):**
nope, it fact so sad :(

**Comment by clayjohn** [comment]
Here is the documentation for Skeleton https://docs.godotengine.org/en/stable/classes/class_skeleton.html

In 3.2.2 it is just named "Skeleton", not "Skeleton3D". Maybe that is why you were confused?

**Comment by Hromon** [comment]
I'm don't understand how link skeleton(bones) to Vertex in SurfaceTool or ArrayMesh

**Comment by Hromon** [comment]
And silence...

**Comment by Calinou** [comment]
@Hromon Contributors work on documentation in a best-effort basis. There's no warranty provided :slightly_smiling_face:

**Comment by Hromon** [comment]
Soooo, how to make it?

**Comment by Calinou** [comment]
@Hromon Please stop bumping this issue. It won't help potential contributors write documentation about using skeletons any faster.

**Comment by Hromon** [comment]
> @Hromon Please stop bumping this issue. It won't help potential contributors write documentation about using skeletons any faster.

Writing the documentation is good, but I am not rushing you to the dock, I ask you to at least explain here how it works, because I am not the only one who wants to find out and I can help them if you finally , start answering questions.

**Comment by Teashrock** [comment]
Guys, what's the problem to just answer a question? There's how to make it:
1. Stop writing the docs for ONE minute. 
2. Answer the question like any of another Godot questions. 
3. Continue writing the docs. 
4. ????
5. PROFIT!

**Comment by Teashrock** [comment]
Sorry if I'm rude, but is that really SO hard to not be lazy?

**Comment by Teashrock** [comment]
@clayjohn @Calinou Documentation is a good thing, but it's not to write fast, and he just asked a question for one or a coupoe of minutes. Why not just reply, answer?

P. S. I myself can't answer because I don't know. If you don't know too, just say it. Please.

**Comment by clayjohn** [comment]
@Teashrock I don't know.

Also, this is not the place to come demanding help. Documentation workers are volunteers and they work very hard to bring you the docs. If you need immediate assistance, please ask for help on one of the [Community Channels](https://docs.godotengine.org/en/stable/community/channels.html). 

Further, we are not walking encyclopedias. Most of the time to document a feature we need to spend hours learning how it works in detail. Its not just a matter of taking a few seconds to answer your question.

**Comment by Hromon** [comment]
> @Teashrock I don't know.
> 
> Also, this is not the place to come demanding help. Documentation workers are volunteers and they work very hard to bring you the docs. If you need immediate assistance, please ask for help on one of the [Community Channels](https://docs.godotengine.org/en/stable/community/channels.html).
> 
> Further, we are not walking encyclopedias. Most of the time to document a feature we need to spend hours learning how it works in detail. Its not just a matter of taking a few seconds to answer your question.

Thy for answer, but i asked and could not get an answer from community. No one knows how :D

**Comment by Calinou** [comment]
@Teashrock I've never worked with skeletons in Godot, so I don't know the answer.

**Comment by Teashrock** [comment]
@clayjohn @Calinou 
Okay, thanks for your replies. Sorry for bothering you.
