### ISSUE TITLE
Add better description to signals

### ISSUE THREAD

**Issue by JarLowrey** [godotengine/godot-docs#378]
Not all signals are immediately self-explanatory, but the docs do not have a description beyond the name/params of the signal.

https://godotengine.org/qa/14667/where-can-i-find-documentation-on-signals?show=14676#c14676

**Comment by StraToN** [comment]
SIgnals are actually described in the `classes.xml` file. We simply need to get these descriptions in the Python script that builds API pages in documentation.

**Comment by StraToN** [comment]
Fixed by commits a514518aa86d96d2f900519ae2ba5a59769d0b07 [2.1] and b21a1232baf9db42cc57e32ecaf5abc0d0b05c86 [master]

**Comment by mhilbrunner** [comment]
Most signals are now documented in the class ref.
