### ISSUE TITLE
Request for updated ePUB Ebook version of the Documentation

### ISSUE THREAD

**Issue by lonku** [godotengine/godot-docs#3789]
**3.2**

**Last e-Reader version available to download is 3.1**

**https://readthedocs.org/projects/godot/downloads/**

**Comment by akien-mga** [comment]
I disabled Epub and SingleHTML builds in ae7277c1e446971d698c5b818a8f5919851c27ba as they take too long and would cause doc builds to timeout, preventing us from updating the docs. Then I disabled PDF builds for the same reason in 370022acf46ab547c062f5039cea2c3dbee74cfb.

But let's give them another try in the `3.2` branch which is updated discretely and not several times a day like `master`.

**Comment by akien-mga** [comment]
Yep the PDF build still fails as there's gazillions of LaTeX warnings from `pdflatex`, the logs reach 4 MB and ReadTheDocs kills the build: https://readthedocs.org/projects/godot/builds/11452256/

Checking if Epub-only works.

**Comment by akien-mga** [comment]
Epub seems to build OK now, so I enabled it for the `3.2` and `stable` branches: https://readthedocs.org/projects/godot/downloads/

**Comment by lonku** [comment]
perfect. thanks!
