### ISSUE TITLE
Button - doc should link to a "how to use it" tutorial

### ISSUE THREAD

**Issue by monk-e-boy** [godotengine/godot-docs#3798]
**Your Godot version:**
3.2.2

**Issue description:**
Look up how to use a Button - no instructions

![image](https://user-images.githubusercontent.com/17924807/87547893-acd79580-c6a3-11ea-8e1d-025f47773443.png)

GUI does not show how to use a button.

I would like to see how to answer the following questions:

"How do I print hello world when I click on a button"

"How do I instruct my game to save when I click on a button"

**URL to the documentation page (if already existing):**
https://docs.godotengine.org/en/stable/classes/class_button.html

**Comment by Calinou** [comment]
> "How do I instruct my game to save when I click on a button"

This is too complex to be described in a code sample. The "print hello world" part is fine to me, though.
