### ISSUE TITLE
Don't clear old search term when entering new search term.

### ISSUE THREAD

**Issue by jmdejong** [godotengine/godot-docs#3804]
When searching for a certain term, that term is displayed in the search bar.
When clicking the search bar, a search window pops up with a new empty search input.
The old search term is not in the input anymore.

This is annoying when the new search term is very similar to the old search term; for example when you made a typo in the old search term and you want to correct that.
There is no way to change the search term without completely re-entering the search term.

My prefered solution would be to show the old search term in the search input field.
Clearing the field manually is only a minimal effort.
If the text is selected then clearing it is usually only one keypress of any key except an arrow key.
Search inputs for all other websites that I know of work like this.

I'm not entirely sure if this is even intended behaviour. I have tested this in both firefox 78.0.2 and opera 69.0.3686.57 and it gave the same behaviour.

**Comment by Calinou** [comment]
This is an issue with the Sphinx search plugin. Please report it here instead: https://github.com/readthedocs/readthedocs-sphinx-search
