### ISSUE TITLE
draw_multiline_colors width and antialiased not implemented info missing

### ISSUE THREAD

**Issue by Reiqy** [godotengine/godot-docs#3845]
**Your Godot version:**
3.2.2

**Issue description:**
Method description for draw_multiline states that width and antialised parameters are not implemented and have no effect. The same applies for draw_multiline_colors but the same statement is missing. The description is misleading at the moment.

**URL to the documentation page (if already existing):**
https://docs.godotengine.org/en/3.2/classes/class_canvasitem.html#class-canvasitem-method-draw-multiline-colors

**Comment by akien-mga** [comment]
Fixed by https://github.com/godotengine/godot/pull/40822.

**Comment by ChildishGiant** [comment]
![image](https://user-images.githubusercontent.com/13716824/155250307-c1db8909-c803-4c75-af14-890ff9e0becb.png)
On [latest](https://docs.godotengine.org/en/latest/classes/class_canvasitem.html#class-canvasitem-method-draw-multiline-colors) width is still listed as a feature :sweat_smile:

**Comment by Calinou** [comment]
> ![image](https://user-images.githubusercontent.com/13716824/155250307-c1db8909-c803-4c75-af14-890ff9e0becb.png) On [latest](https://docs.godotengine.org/en/latest/classes/class_canvasitem.html#class-canvasitem-method-draw-multiline-colors) width is still listed as a feature sweat_smile

The `master` branch does support width and antialiasing for line drawing, as it uses an entirely different implementation relying on triangle strips: https://github.com/godotengine/godot/pull/43828

Backporting this to `3.x` is technically possible, but it would require a full rewrite of the feature in question (in addition to supporting batching).

**Comment by ChildishGiant** [comment]
Is this change not in 4.0 then? I assumed that the latest docs would be for 4.0 but they might be for main which is different?

**Comment by Calinou** [comment]
The latest class reference no longer lists it indeed: https://docs.godotengine.org/en/latest/classes/class_canvasitem.html?highlight=canvasitem#class-canvasitem-method-draw-multiline-colors

I guess it wasn't implemented for `draw_multiline_colors()`, only for `draw_polyline_colors()`. cc @Chaosus
