### ISSUE TITLE
Misleading/ easy to misunderstand Singleton documentation

### ISSUE THREAD

**Issue by Incblob** [godotengine/godot-docs#3864]
A singleton is defined in wikipedia as an object of which exists only one instance.
In Godot checking the singleton box in an Autoload object merely allows referencing that object with the "Object.parameter" pattern.

The documentation states it will:
"Act like a singleton, since GDScript does not support global variables by design"

Which it only does in referencing, **not** in that there is only one instance of it. 

So maybe change the check box to "Global Reference" or something more appropriate? Or make it clear in the docu that a godot singleton has little to do with a traditional singleton? 
It's a bit confusing at the moment by saying that it will "act like" a singleton.

Thank you for your time :)

Here is the discussion which prompted this request: https://www.reddit.com/r/godot/comments/i2alxp/exporting_variables_in_singleton_script/

And the link to the docu:
**https://docs.godotengine.org/en/stable/getting_started/step_by_step/singletons_autoload.html**

**Comment by Calinou** [comment]
Renaming singletons entirely sounds difficult, as they're referenced in lots of other places throughout the editor itself and in unofficial tutorials (which we can't edit).

**Comment by Incblob** [comment]
I see, perhaps make it clear in the docu that the singleton checkbox only allows for global referencing and does not actually act like a singleton? 

Of course, there are more important things to be working on, i just misunderstood the function of the singleton and suspect that beginners in godot transitioning from other languages might be similarly confused. 
If you have the time to clarify the docs that's great :)
