### ISSUE TITLE
The visual script docs are for 3.0 but it looks different in 3.2

### ISSUE THREAD

**Issue by jasperbrooks79** [godotengine/godot-docs#3869]
**Your Godot version:**
Godot 3.2.2

**Issue description:**
The official docs for visual script, uhmmm the boxes don't look like that at all, in 3.2, I think it was made for 3.0, it's just confusing, sadly . .

**URL to the documentation page (if already existing):**

https://docs.godotengine.org/en/stable/getting_started/scripting/visual_script/getting_started.html?highlight=visual%20script

Is there any way you can make a more comprehensive visual script official docs, atm. it needs more examples . . :O <3

**Comment by skyace65** [comment]
Closing this as Visual Scripting is being removed from Godot in 4.0.
