### ISSUE TITLE
Make the documentation theme reusable

### ISSUE THREAD

**Issue by pradyunsg** [godotengine/godot-docs#3873]
**Your Godot version:** N/A
**URL to the documentation page:** N/A

**Issue description:**

Hi there! I've been working toward revamping https://sphinx-themes.org/, to modernize and update that website ([current draft](https://pradyunsg.me/sphinx-themes/)). Looks like Godot's documentation is written with Sphinx, and uses a highly customized variant of the Sphinx RTD Theme.

I'd love to add this theme to the gallery, but for that it needs to be a reusable Sphinx theme (much like Sphinx RTD Theme is). Would there be any interest in factoring out the customisations made for this documentation, into a reusable Sphinx Theme?

**Comment by Calinou** [comment]
The custom CSS/JavaScript are here: https://github.com/godotengine/godot-docs/tree/master/_static

It's all we use to customize the default Sphinx RTD theme.

**Comment by pradyunsg** [comment]
Oh, that's great! I saw that there was an `_templates` folder as well, so I instinctively thought that there was deeper customization beyond JS/CSS. :)

Is there any way I can help factor this out into a custom theme?

**Comment by Calinou** [comment]
@pradyunsg Maybe you could try to do it in a personal repository, then we can take its contents and upload it in a repository owned by the @godotengine organization.

**Comment by tetrapod00** [comment]
Closing due to lack of response. If you're still interested in working on this after so long, feel free to leave a comment and I'll reopen this.
