### ISSUE TITLE
Make the documentation a Kindle e-book

### ISSUE THREAD

**Issue by Bruce200** [godotengine/godot-docs#3883]
**Your Godot version:**

> You probably want to go back and support old versions; maybe you could make the various version's documentations a series of books.

**The Idea:**

> If the documentation was made a free Kindle book, this would allow people on any mobile devices, as well as desktop versions via Kindle Cloud Reader or the desktop app for macOS 10.10 and up as well as most Windows versions. 

**Why:**

> This would just be a great thing overall, as it would alleviate many of the problems that have been had downloading for offline viewing through ePubs, and give a better user experience than PDFs (you will no longer have to flip back to the page you were on every time you reopen the file). This just seems like a better way to do offline docs reading. I'm not sure how hard it would be to take the docs and make them an e-book, but the work could definitely pay off.

Thanks to all the great people out there that do maintain the docs!

**Comment by Calinou** [comment]
The Kindle AZW format is a proprietary format. I doubt there are any plans to support it in Sphinx/Read the Docs, so I'll close this.
