### ISSUE TITLE
Remove unnecessary uses of "simple", "simply", and "easy"

### ISSUE THREAD

**Issue by fdmarcin** [godotengine/godot-docs#3887]
**Issue description:**
Currently, these words appear this many times in `.rst` files, (excluding `class...` files):

| Word | Occurrences |
|---|---|
|simple | 201 |
|simply | 89 |
|easy | 61 |
|~please~ | ~58~ |

- ~**please**: in my opinion, it's unnecessary almost in all cases - it makes the writing more _polite_, but it makes it less easy to read.~
- **simple / simply / easy**: it's often easy to misjudge if a task is really _easy_ or a concept _simple_, and in cases when we say it is, but it turns out the opposite for the reader, they might feel frustrated or incompetent. Approximately 50-80% of the time, it's safe to edit these out too. See _Don't Say Simply_ ([article](https://www.knowledgeowl.com/home/dont-say-simply-jim-fisher) or [talk](https://www.writethedocs.org/videos/prague/2018/don-t-say-simply-jim-fisher/)) for context.

**Proposal:**
I could pick up this task, but first wanted to get your opinion :)

**Comment by fdmarcin** [comment]
Ah, I've just found the [docs writing guidelines](https://docs.godotengine.org/en/stable/community/contributing/docs_writing_guidelines.html#docs-writing-guidelines) too 😃 

> Ban these 8 words: obvious, simple, basic, easy, actual, just, clear, and however

**Comment by Calinou** [comment]
I think it's better to leave in most occurrences of "please" (unless they're repeated too often in a single page), but feel free to open a pull request to remove occurrences of "simple", "simply" and "easy".

**Comment by fdmarcin** [comment]
@Calinou Okay, thanks! I edited the title and description of this. If you want, you can assign me to this issue.

**Comment by Xrayez** [comment]
"Please" is more like an apology for making you do a workaround, so justifiable IMO. 😛

<details> <summary>Regarding "simple" and "simply"</summary>

![4bgoon](https://user-images.githubusercontent.com/17108460/90267906-e1836c00-de5e-11ea-92db-6bec37c8e71c.jpg)

</details>

**Comment by fdmarcin** [comment]
FYI, with holiday downtime, I started working on this. Sorry about the delay :sweat_smile: 

(My fork is up to date with `master` btw)
