### ISSUE TITLE
compiling to uwp and installing via an app container

### ISSUE THREAD

**Issue by Ahmed0425** [godotengine/godot-docs#391]
exactly as the title says
I managed to compile to uwp but got an error says that the app can run only via an app container
there should be a tutorial on how to make that app container (for both editor and games)
thanks in advance

**Comment by vnen** [comment]
There are Microsoft tutorials about making app packages. Godot should be able to export the package directly (though the exporter has changed and the UWP export hasn't been updated yet). There are docs about [how to make the export templates](http://docs.godotengine.org/en/latest/development/compiling/compiling_for_uwp.html#creating-uwp-export-templates).

TBH the easiest way to test is to run via Visual Studio, [which is also documented](http://docs.godotengine.org/en/latest/development/compiling/compiling_for_uwp.html#running-uwp-apps-with-visual-studio), Making packages by hand shouldn't be necessary.

**Comment by akien-mga** [comment]
So is there something to improve in the documentation, or is it good enough already?

**Comment by vnen** [comment]
I can't see what else is needed besides the page about how to [export for UWP](http://docs.godotengine.org/en/latest/learning/workflow/export/exporting_for_uwp.html).

**Comment by akien-mga** [comment]
Thanks, let's close then.
