### ISSUE TITLE
Brief method and property descriptions in class references

### ISSUE THREAD

**Issue by hazarek** [godotengine/godot-docs#3913]
**Your Godot version:**
3.2.3rc official

**Issue description:**
Some method and property descriptions are too long and contains tabs(`\t`), new lines(`\n`) and code blocks in xml files. So It cannot be parsed as a brief description. I want to format like this table. because I prefer to quickly browse through short descriptions;
https://gist.github.com/hazarek/0c8196e7758d4eadf063ba02e1eb703e

Example markdown table;
|  Method | Returns | Description |
|-------------- | -------------- | -------------- | 
| **clear**() | `void` | Clears all cells. | 
| **fix_invalid_tiles**() | `void` | Clears cells that do not exist in the tileset. | 
| **get_cell**(x, y) | `int` | Returns the tile index of the given cell. If no tile exists in the cell, returns `[constant INVALID_CELL]`. | 
| **get_cell_autotile_coord**(x, y) | `Vector2` | Returns the coordinate (subtile column and row) of the autotile variation in the tileset. Returns a zero vector if the cell doesn't have autotiling. | 
| **get_cellv**(position) | `int` | Returns the tile index of the cell given by a Vector2. If no tile exists in the cell, returns `[constant INVALID_CELL]`. | 

**URL to the documentation page (if already existing):**
https://github.com/godotengine/godot/blob/eb9cbdc3692bdc77b6114ceb771f72fd6cd91a73/doc/classes/TileMap.xml#L161
for example TileMap set_cell method description, contains tabs(`\t`), new lines(`\n`) and code blocks;
```xml
...
			<argument index="6" name="autotile_coord" type="Vector2" default="Vector2( 0, 0 )">
			</argument>
			<description>
				Sets the tile index for the cell given by a Vector2.
				An index of [code]-1[/code] clears the cell.
				Optionally, the tile can also be flipped, transposed, or given autotile coordinates. The autotile coordinate refers to the column and row of the subtile.
				[b]Note:[/b] Data such as navigation polygons and collision shapes are not immediately updated for performance reasons.
				If you need these to be immediately updated, you can call [method update_dirty_quadrants].
				Overriding this method also overrides it internally, allowing custom logic to be implemented when tiles are placed/removed:
				[codeblock]
				func set_cell(x, y, tile, flip_x, flip_y, transpose, autotile_coord)
				    # Write your custom logic here.
				    # To call the default method:
				    .set_cell(x, y, tile, flip_x, flip_y, transpose, autotile_coord)
				[/codeblock]
			</description>
...
```
# My Suggestion

While converting xml to markdown with python, I noticed that descriptions are written in the XML element as rich text without character limit and rules([Unstructured data](https://en.wikipedia.org/wiki/Unstructured_data)). The following XML elements are needed;

```xml
<brief_mehod_description> </brief_mehod_description> 
<brief_member_description> </brief_member_description>
etc..
```
Rules of The Brief Decriptions;

1. Brief descriptions cannot exceed 140 characters
2. Brief descriptions cannot contain code blocks,  links, tabs(`\t`) and new lines(`\n`).
3. Brief descriptions only can contain, bold, italic and inline code

Sorry for my english, thank you.

**Comment by Calinou** [comment]
> While converting xml to markdown with python, I noticed that descriptions are written in the XML element as rich text without character limit and rules(Unstructured data). The following XML elements are needed;

Unfortunately, adding more XML tags will make the class reference XML even more verbose than it already is. We don't want to scare new contributors from contributing documentation.

**Comment by hazarek** [comment]
> > While converting xml to markdown with python, I noticed that descriptions are written in the XML element as rich text without character limit and rules(Unstructured data). The following XML elements are needed;
> 
> Unfortunately, adding more XML tags will make the class reference XML even more verbose (and deeply-nested) than it already is. We don't want to scare new contributors away from contributing documentation.
> 
> Also, it's not always possible to have a 140-character sentence that accurately describes what a method does while also mentioning important caveats (such as possible security issues or risks of data loss).

The current spaghetti documents are even scarier. There will be a brief version as optional and additionally, the descriptions will remain as they are. It's better to be flexible and structured database than written like a novel. I know what I want is not easy, there are too many description and it is written in novel style. These are my personal opinion, If you want, you can close the this issue. thanks
