### ISSUE TITLE
Add more channels with visual script tutorials, in docs . .

### ISSUE THREAD

**Issue by jasperbrooks79** [godotengine/godot-docs#3915]
**Your Godot version:**
3.2

**Issue description:**
Need more links, to GOOD visual script tutorials, in official docs . .

Found SpaceSharkStudio, has a 32-part video, make a 2D game in Godot, please consider adding, to list . .
https://www.youtube.com/watch?v=iE8X0kWtjO0&list=PLxw4Pmjew9pzVgENhgnlzjjNgoRm89TEg

Made a ' make a 3D game in Godot using visual script ', as well . .
https://www.youtube.com/watch?v=IHvw_YQC_o4&list=PLazdpb1e7pKIHT-poPT55FSYTfLhHRo6i

**URL to the documentation page (if already existing):**
https://docs.godotengine.org/en/stable/community/tutorials.html?highlight=tutorials

Please consider making a separate list, specific for visual scripting, with SpaceSharkStudios on it, other good visual script stuff, since is not so much, for noobs . . .

An idea, took a long time, to learn all the stuff . . :O :O . .

**Comment by skyace65** [comment]
Closing this as Visual Script was removed for Godot 4.
