### ISSUE TITLE
Update readthedocs-sphinx-search

### ISSUE THREAD

**Issue by stsewd** [godotengine/godot-docs#3953]
Looks like you are using an old version of the extension https://github.com/godotengine/godot-docs/blob/70e9184552ab9cf83a2654650210b9674980e3af/requirements.txt#L13

We updated the endpoint used by the search extension, so old versions will stop working soon. Please use the new version of the extension https://github.com/readthedocs/readthedocs-sphinx-search (we have releases in pypi now ;))

**Comment by skyace65** [comment]
@Calinou is this something you would know how to update?

**Comment by pycbouh** [comment]
We need to update https://github.com/godotengine/godot-docs/blob/master/requirements.txt to the appropriate hash, and then deploy.

**Comment by stsewd** [comment]
Also, please keep in mind the extension is still in beta, so till 1.0 we may be breaking some stuff. But hopefully the API isn't going to change (the html structure, css classes and js functions may change). Anyway, I'll let you know in case something breaking happens
