### ISSUE TITLE
Tint the background of code blocks red for examples of bad code

### ISSUE THREAD

**Issue by Omicron666** [godotengine/godot-docs#3962]
**Issue description:**
redish background would help convey information about what not to do for bad code, instead of greenish background,
especially when followed by good code again

**URL to the documentation page (if already existing):**
https://docs.godotengine.org/en/stable/getting_started/scripting/gdscript/gdscript_styleguide.html#type-hints
there are several spots in doc, of that kind

**Comment by Calinou** [comment]
Do we have a way to add a custom CSS class to a Sphinx codeblock? We need to find a way to do that before this can be done.

**Comment by pycbouh** [comment]
There doesn't seem to be such option in the `code-block` directive: https://www.sphinx-doc.org/en/master/usage/restructuredtext/directives.html#directive-code-block. We can probably wrap such codeblocks into something and use CSS specificity to override the color?
