### ISSUE TITLE
Script templates How-To

### ISSUE THREAD

**Issue by Hinsbart** [godotengine/godot-docs#398]
Now that there are custom script templates, I guess we should provide a page explaining how to add and use them. (Add the script to <godot_config_dir>/script_templates, list of placeholders, etc..)

**Comment by Calinou** [comment]
Note that Godot 3.2 onwards supports [per-project script templates](https://github.com/godotengine/godot/pull/31111).

**Comment by Xrayez** [comment]
I've written a proposal for creating a script template manager to make this obvious, this would automatically make the feature accessible/self-explanatory, also creating demand for this feature: godotengine/godot-proposals#748.

What existing section would be best suited to document this? Perhaps [Misc](http://docs.godotengine.org/en/latest/tutorials/misc/index.html) section? Or even [Scripting](http://docs.godotengine.org/en/latest/getting_started/scripting/index.html)?

**Comment by Calinou** [comment]
@Xrayez I'd put it in Scripting personally.
