### ISSUE TITLE
TreeItem.CELL_MODE_CUSTOM has very little documentation on how to use it

### ISSUE THREAD

**Issue by LikeLakers2** [godotengine/godot-docs#3981]
**Your Godot version:** 3.2.2 (Steam)

**Issue description:**
Hi! I'm messing around in Godot, making some UI, and I find that TreeItem has a CELL_MODE_CUSTOM mode. However, I can't seem to tell what it does, or how I'm supposed to use it. It sounds like it could be a powerful tool, yet the documentation seems pretty vague on how I'm supposed to use CELL_MODE_CUSTOM.

I think the main factor in why it's confusing is that there's no example of how to use it, combined with the non-intuitive name. Is it meant to be used with [`TreeItem.set_custom_draw`](https://docs.godotengine.org/en/stable/classes/class_treeitem.html#class-treeitem-method-set-custom-draw) so that I can draw any node I want onto it -- and if so, how? Or is it a popup, since there's the `Tree.custom_popup_edited` signal (and what does "custom popup edited" mean as a whole? how would it be triggered?)?

Hopefully this can be sorted out and clarified.

**URL to the documentation page (if already existing):**
https://docs.godotengine.org/en/stable/classes/class_treeitem.html#class-treeitem-constant-cell-mode-custom

**Comment by Xrayez** [comment]
This puzzled me as well. According to [this question](https://godotengine.org/qa/32862/how-to-get-a-color-picker-button-in-a-tree), it may seem like it doesn't even work.

I assumed that Godot editor inspector uses `Tree` for editing properties, but grepping for it doesn't show any results in `editor_inspector.cpp` nor `editor_properties.cpp`.

But I've found that `TreeItem::set_custom_draw()` is used once in `find_in_files.cpp` once for highlighting search results, apparently:

![image](https://user-images.githubusercontent.com/17108460/142736610-3e20a64a-c286-48d1-b4a0-6adfe8f9a735.png)

It doesn't seem to be super useful for replicating editor inspector stuff, as `Tree` doesn't provide a way to embed custom controls.

**Comment by tetrapod00** [comment]
Closing as implemented by https://github.com/godotengine/godot/pull/92112 in 4.3.
