### ISSUE TITLE
Update to sphinx-tabs 1.3.0

### ISSUE THREAD

**Issue by akien-mga** [godotengine/godot-docs#3982]
Version 1.3.0 of our [sphinx-tabs](https://github.com/executablebooks/sphinx-tabs/blob/master/CHANGELOG.md) extension has been released today.

We currently use version 1.1.13 (as defined in `requirements.txt`), so upgrading should simply be a matter of changing the hardcoded number, but we should also review the upstream changelog to see if there are any changes that impact our use of the extension (either positively or negatively).

**Comment by mhilbrunner** [comment]
This was done (see https://github.com/godotengine/godot-docs/pull/4572 and https://github.com/godotengine/godot-docs/commit/a912322c601eab7dd72d26d1a98b39d6d62fd524)
