### ISSUE TITLE
Class description cross-reference tracker 

### ISSUE THREAD

**Issue by golddotasksquestions** [godotengine/godot-docs#3988]
**Your Godot version:** latest

**Issue description:**
The goal of this tracking issue is to help Godot (beginner) users to find the class API they are looking for, not just with those who already know the ins and outs of OOP and how Godot system is set up.

A positive example is the AnimationPlayer class reference. 
As a beginner, if I wanted to do something to my Animation, my brain used to think "AnimationPlayer", because that's what I add in the Editor. The natural instinct therefore is to look up AnimationPlayer API. The documentation helps my brain by pointing to the Animation Resource in the first sentence in the description, with a direct link to it. Before that link was added, I used to waste incredible amount of time to look for a property of method in the wrong classes because I could not find it in the AnimationPlayer class.

**Comment by Calinou** [comment]
The goal of this issue is to get *you* to list such entries as well :slightly_smiling_face:

**Comment by golddotasksquestions** [comment]
Add a single sentence pointing users looking for further [Sprite3D](https://docs.godotengine.org/en/latest/classes/class_sprite3d.html) properties (like the billboard property) to [SpriteBase3D](https://docs.godotengine.org/en/latest/classes/class_spritebase3d.html#class-spritebase3d) and vice versa.

**Comment by akien-mga** [comment]
> Add a single sentence pointing users coming to Sprite3D in search for Sprite3D related properties, which are not found in Sprite3D (like the billboard property) to SpriteBase3D and vice versa.

For the reference, as I pointed out on Reddit, it's not really practical to add to every Node a manual reference to each class they inherit from. This information is already given at the top of the page with the "Inherits:" line, and class reference users need to be made aware of it. Maybe this line should be more prominent, and/or there could be an introduction line that says: "This class inherits additional properties, methods, constants and signals from its parent classes:".

On second thought though, it's true that for classes which inherit an *abstract* class (i.e. one that can't be instantiated directly) like Sprite3D does with SpriteBase3D, it might make sense to make this explicit in the description as the abstraction is an implementation detail that shouldn't matter to the end user.

So we could indeed add another explicit reference to it in the description. For 4.0, there's also StandardMaterial3D that inherits the abstract BaseMaterial3D, or Node2D and Control inheriting the abstract CanvasItem.

I'd draw the limit at those abstract parent classes though, I don't think that it would make sense to mention explicitly that e.g. Light2D or Sprite2D inherit Node2D and thus also have Node2D methods and properties in their API - that's something that the "Inherits:" line conveys and that users need to learn to use the class reference efficiently (which I think should be covered in a manual page about the class reference as I mentioned in https://github.com/godotengine/godot-docs/issues/3969#issuecomment-690235905).

**Comment by golddotasksquestions** [comment]
You are thinking in technical terms Akien, I'm trying to argument from the flow perspecive of a user who's brain is not yet molded to the exact shape and form of Godots system logic and OOP.

Therefore I don't see a need to link to everything, just if there is a very common path where new users might look for something in the wrong place. It that fits a technical criteria, imho does not matter, expecially not if all that's needed is to add a link in the first sentance. Much like Wikipedia has a link at the top of many pages, paraphrasing: "This referes to XYZ. Click here for XZY."

**Comment by akien-mga** [comment]
> It that fits a technical criteria, imho does not matter, expecially not if all that's needed is to add a link in the first sentance. Much like Wikipedia has a link at the top of many pages, paraphrasing: "This referes to XYZ. Click here for XZY."

Well, again, that link already exists:
![Screenshot_20200910_170911](https://user-images.githubusercontent.com/4701338/92751543-5b3c4600-f388-11ea-9dca-cbe9b5a90780.png)

**Comment by golddotasksquestions** [comment]
Well, I know where to find that link, you know, any contributor knows and anyone using the engine for a lot for a good while.
I also know you can just look in the Inspector and see which Parent has the property.

The problem is if you are a novice or come into Godot without extensive programming background both of these options might not be apparent until much later. 

I'm asking to work towards the minds of beginners, you reply "the information is there". 
Well we know it's there. Let's just help beginners to find it, not by making life harder for them, but by making it easy to get into the groove of how this engine works and flows. For this to happen, it would help tremendously to provide save passage over the steppingstones beginners commonly bump into when first using the engine. A link is such a passage.

**Comment by Calinou** [comment]
@golddotasksquestions Done here: https://git.io/JUCAD

**Comment by NathanLovato** [comment]
There's definitely a need for some links when the context calls for it. Do you have more of these in mind at the moment? If not, would you be ok if we closed this one and if you opened a new issue when you have a list of links you feel should be added? So we can triage your reports.

Problem-driven issues with a well-defined scope tend to get addressed quickly, and they're easier for us to triage, keep track of, and know when to close via a pull request.

**Comment by golddotasksquestions** [comment]
> Do you have more of these in mind at the moment?

No, not from the top of my head. I just remember I have been in this situation a number of times before. If you want separate issues for them, I can't guarantee I will open a new one every time I encounter that, because writing new issues always is an interruption to my flow is just more effort than a comment (compare to https://github.com/godotengine/godot/issues/16863), but I will try to write as much issues as I can to the best of my abilities non the less.

**Comment by NathanLovato** [comment]
Thanks. You don't have to open issues every time, do what´s comfortable for you. For instance, you could write a quick note on your computer when you stumble upon a class that lacks a cross-reference and share the list as one issue later.

Tracker issues like these tend to sink and get lost in the issue tracker. Few contributors look for existing issues they can add to, we often have people open duplicate issues; GitHub's search takes some getting used to, which doesn't help.
