### ISSUE TITLE
InputEventMIDI descriptions are lacking

### ISSUE THREAD

**Issue by robbertzzz** [godotengine/godot-docs#3992]
**Your Godot version:**
3.2

**Issue description:**
The page about InputEventMIDI doesn't really tell the reader what anything does or means. If you know how MIDI works it makes sense, but a general explanation about the basics behind MIDI would be good to have.

**URL to the documentation page (if already existing):**
https://docs.godotengine.org/en/stable/classes/class_inputeventmidi.html

**Comment by skyace65** [comment]
I'm not very experienced with audio, but if you could give me some descriptions I'll make a PR for this.

**Comment by robbertzzz** [comment]
This article is probably the clearest for non-musicians: https://www.cs.cmu.edu/~music/cmsip/readings/MIDI%20tutorial%20for%20programmers.html

What I'm missing mostly in the docs is a description of what all the parameters mean. I had to Google which numeric pitch was linked to which musical pitch for example. It could also help for anyone mildly interested to just get an idea of how midi works in general if they're thinking about linking up their midi devices (which loads of people have nowadays). 

More experienced users will be able to use midi for other things (it's just a communication protocol after all), but I'm assuming they'll know what they're doing anyway.

**Comment by aaronfranke** [comment]
@robbertzzz Do you have any example projects I can try which successfully read MIDI input and can provide MIDI output? I have some MIDI devices that are detected by the OS and I can get input and output working but I have no idea how to use them in Godot. I tried `func _input(input_event): print(input_event)` in a script and I don't get any prints from MIDI.

**Comment by Calinou** [comment]
[MIDI output is not supported yet](https://github.com/godotengine/godot-proposals/issues/2321) - this should be pointed out in the documentation.
