### ISSUE TITLE
Better dark mode CSS for docs.godotengine.org

### ISSUE THREAD

**Issue by hazarek** [godotengine/godot-docs#4003]
**Your Godot version:**
3.2

**Issue description:**
Headers and Strong words are same color and font-family in dark mode and cannot be distinguished from other paragraphs

**URL to the documentation page (if already existing):**
https://github.com/godotengine/godot-docs/blob/c0156f55b530e4e0067e4d1cec49580f9c1baa61/_static/css/custom.css#L95

<img width="776" alt="cap 7" src="https://user-images.githubusercontent.com/36481442/93007400-63a3a500-f571-11ea-8fe7-c138afd34282.png">

the improvement I made (only color and brightness);
 
<img width="762" alt="cap 6" src="https://user-images.githubusercontent.com/36481442/93007434-ba10e380-f571-11ea-929f-64aa7eb70f24.png">

```
--body-color: rgba(255, 255, 255, 0.70);

b, strong {
    font-weight: 500;
    color: white;
}

}
h1, h2, h3, h4, h5, h6, legend, .rst-content .toctree-wrapper p.caption {
    color: #79A8F6;
    font-weight: 500;
}
```
header color variation, you understand what i mean, font styles should also be enriched.;
<img width="730" alt="cap 8" src="https://user-images.githubusercontent.com/36481442/93007627-7dde8280-f573-11ea-872b-a4fa7b29d745.png">

edit;
I highly recommend the background color to be #222222.
<img width="791" alt="cap 2" src="https://user-images.githubusercontent.com/36481442/93007816-d57ded80-f575-11ea-9105-2937a1ccad33.png">

**Comment by Calinou** [comment]
This is a good idea, but we don't want to make headings' colors too close to link colors. Otherwise, people might think they're clickable.

Using a yellow color is an alternative, but it feels less visually coherent since we don't use a yellow tint anywhere else (except in warning admonitions).

**Comment by hazarek** [comment]
@Calinou Dark mode requires different approach than white mode. just bold is not enough. And current contrast is too low. You can't use bluish background with RGBA color(--body-color: rgba(255, 255, 255, 0.85); 
Material design suggests #121212 for background, I think this is very dark, #222222 is the ideal darkness.

normal text = medium emphasis
headers ,bold words = High emphasis
![0_bgklbsQ1PLNbUeHD](https://user-images.githubusercontent.com/36481442/93028848-59d87b00-f61f-11ea-8ffb-602d465bb2ce.png)
