### ISSUE TITLE
reference sibling objects in _ready function

### ISSUE THREAD

**Issue by fusillator** [godotengine/godot-docs#4011]
**Your Godot version:**
v3.2.2.stable.official

**Issue description:**
Hi I'm wondering if this part of the tutorial is correct
```
    When you open a scene in the game, Godot creates nodes one by one,
    following the order in your Scene dock, from top to bottom. GUI and
    Player are not part of the same node branch. To make sure they both
    exist when we access each other, we have to use the _ready function.
    Godot calls _ready right after it loaded all nodes, before the game
    starts. It's the perfect function to set everything up and prepare the
    game session.
```
in the tutorial the function _ready of the GUI node gets a reference of the sibling Player. Furthermore the GUI node is above Player node in the tree.
Using _ready function of a node may not guarantee the existence of its siblings and the call get_node may result in an error.
Shouldn't _ready be used in a common parent?
 
**URL to the documentation page:**
[Set up the Lifebar with the Player's max_health](https://docs.godotengine.org/en/stable/getting_started/step_by_step/ui_code_a_life_bar.html#set-up-the-lifebar-with-the-player-s-max-health)

**Comment by NathanLovato** [comment]
The tutorial is outdated and going to be deleted from the docs. I'll open a PR in a moment to do some cleanup and close the issue.
