### ISSUE TITLE
Persian language in Godot documents.

### ISSUE THREAD

**Issue by ALipAkrohk** [godotengine/godot-docs#4013]
Many Persian language users are eager to learn Godot.
### Please translate the Godot document into Persian.
RTL languages ​​were not even supported in the engine itself, Please prioritize UTF-8 support.

**Comment by MrMorteZw** [comment]
No

**Comment by mitsuha-miamizu** [comment]
yes

**Comment by MrMorteZw** [comment]
be morteza ali ghasam ke no

**Comment by akien-mga** [comment]
Godot's documentation is translated as a community effort on Weblate. You're welcome to help translate the content in Persian: https://hosted.weblate.org/projects/godot-engine/godot-docs/

Once it will be significantly complete, I'll create a godot-fa instance to host the translated docs pages.
