### ISSUE TITLE
Documentation for exporting game as embeddable iOS/Android views

### ISSUE THREAD

**Issue by bfelbo** [godotengine/godot-docs#4018]
Split out from https://github.com/godotengine/godot-proposals/issues/1473 based on @m4gr3d's suggestion. Please see answers to remaining questions there.

**Describe the feature / enhancement and how it helps to overcome the problem or limitation:**
Godot added support for [embedding your game inside an Android app](https://github.com/godotengine/godot/pull/39855) and there's a [proposal for adding identical support to iOS as well](https://github.com/godotengine/godot-proposals/issues/1473). These are incredible features, which can unlock many Godot developers, who need specific iOS/Android features (see e.g. https://github.com/godotengine/godot-proposals/issues/1272, https://github.com/godotengine/godot-proposals/issues/1175, https://github.com/godotengine/godot-proposals/issues/242, https://github.com/godotengine/godot-proposals/issues/1427, https://github.com/godotengine/godot-proposals/issues/1184). Additionally, there's other benefits as listed in https://github.com/godotengine/godot-proposals/issues/1473.

This proposal focuses on adding more documentation on how to use export your game as embeddable iOS/Android views. It would be great to make it more clear how to do this as it would unlock many Godot developers, who need:

- iOS/Android features (see linked issues above)
- Lots of UI (e.g. multiplayer UI for chat/guilds/voice or spatial UI like for Pokemon Go)
- Support for adding the game inside an existing app (similar to Snapchat games)

There's a lot of possibilities once this is unlocked so it would be great to add more documentation to help Godot developers use this feature.

**Comment by humbinal** [comment]
I am looking for the documentation of this implementation, but I have not found it. Who can help me? I'm very anxious to implement this in android project，thank you！

**Comment by dboylx** [comment]
> Hey folks, apologies for the delay. We'll be working to resolve this issue in the coming weeks (before the end of the year).

Is it available now?

**Comment by ran-bg** [comment]
any updates about subview architecture?

**Comment by madhawa-se** [comment]
This is a very useful feature. unfortunately I couldn't find any documents on this yet.

**Comment by madhawa-se** [comment]
@Calinou Thanks but I'm trying to find subview implementation docs. Couldn't find any documents regarding this implementation

**Comment by Calinou** [comment]
> @Calinou Thanks but I'm trying to find subview implementation docs. Couldn't find any documents regarding this implementation

There are none yet. Unfortunately, m4gr3d ran out of time to work on this feature, so it'll take a while for this to be documented (if ever).

**Comment by tamashalcyon** [comment]
Hey! Any news on this? Is there any documentation on it? I would really love to try out integrating a Godo game into an Android app :)

**Comment by Calinou** [comment]
> Hey! Any news on this?

There's still no ETA for documenting this feature. I don't know if @m4gr3d still plans to document it, but I doubt anyone else knows how to use it unfortunately.

**Comment by BadKiko** [comment]
It's a shame that there is no documentation on this topic (

**Comment by KristijanZic** [comment]
Any documentation on this???

**Comment by m4gr3d** [comment]
> Any documentation on this???

The Android documentation for this is available at https://docs.godotengine.org/en/latest/tutorials/platform/android/android_library.html

**Comment by KristijanZic** [comment]
> > Any documentation on this???
> 
> The Android documentation for this is available at https://docs.godotengine.org/en/latest/tutorials/platform/android/android_library.html

Love you man 😘🎉
