### ISSUE TITLE
VideoPlayer API: Add ".ogv" under supported file types

### ISSUE THREAD

**Issue by golddotasksquestions** [godotengine/godot-docs#4021]
**Your Godot version:**
3.2.2 stable

**Issue description:**
According to the VideoPlayer API only .webm and .ogg are supported file types. Since many video and animation editing software does not have a ogg export, naturally I would look for an .ogg converter online. My impression though is that they never really work well, some sites from search results just don't have .ogg when you actually try to do the conversion, even if they seem to have it in the search result.

.ogv seems to be the container format and works fine with Godot and also is a widely available conversion format. Online converting to .ogv works really well in my experience.

My point is while technically correct, users might be mislead by "ogg", waste a lot of time (as I have) with services that don't work and instead should search for "ogv".

**URL to the documentation page (if already existing):**
https://docs.godotengine.org/en/stable/classes/class_videoplayer.html

**Comment by Calinou** [comment]
It's `.ogv` (or `.ogg`!), not `.ovg` :slightly_smiling_face:

**Comment by golddotasksquestions** [comment]
`It's .ogv (or .ogg!), not .ovg slightly_smiling_face`
Good catch!
