### ISSUE TITLE
NetBSD needs to be added to the documentation

### ISSUE THREAD

**Issue by notepade** [godotengine/godot-docs#4029]
**Your Godot version:**
3.2.2 and 3.2.3

**Issue description:**
There needs to be instructions on compiling for NetBSD. A bug is being looked at for being able to compile it for NetBSD https://github.com/godotengine/godot/issues/42145 and adding NetBSD to the official documentation would be a big help.

**URL to the documentation page (if already existing):**
https://docs.godotengine.org/en/stable/development/compiling/compiling_for_x11.html

**Comment by Calinou** [comment]
Which specific steps are required to compile Godot on NetBSD (compared to other BSDs)?

**Comment by notepade** [comment]
Up till now, I haven't required any fancy additional steps to get to where I am at with NetBSD. Any required packages I believe are in the NetBSD repos. I will need someone else to verify that also uses NetBSD if there are any missing packages from NetBSD if that is causing any issues because I installed every package from the requirements list into NetBSD.

**Comment by akien-mga** [comment]
Can you give the command that one should use to install all dependencies on NetBSD? As done for other OSes.

**Comment by akien-mga** [comment]
Needs confirmation but I think what's necessary would be something like `pkg_add pkg-config py37-scons`. The rest of the dependencies seem to be already installed in a basic installation with X11.
