### ISSUE TITLE
Exporting for the Web links to customization of the HTML page 6 times

### ISSUE THREAD

**Issue by NathanLovato** [godotengine/godot-docs#4034]
This page could use some edits and simplification: https://docs.godotengine.org/en/stable/getting_started/workflow/export/exporting_for_web.html

It links to the same page every other paragraph. Reported by @pycbouh

**Comment by akien-mga** [comment]
Note that @Faless has some changes queued that may simplify the export workflow for HTML5, and would likely be included in 3.2.4.

**Comment by skyace65** [comment]
The page only links to that page once now in master and 3.6.
