### ISSUE TITLE
Rewrite of the Getting Started section: plan

### ISSUE THREAD

**Issue by NathanLovato** [godotengine/godot-docs#4035]
The task: Rewrite the getting started guide to explain key concepts of Godot and help users get started in a couple of hours. The content should frequently link to other pages in the user manual for more information.

Notes:

_1. By rewrite, I do not mean to throw away everything and restart from zero. But there is a lot of writing and editing work involved with this task.
2. Multiple sub-sections in the current Getting Started section are going to move to other sections. In general, we want Getting started to be one short series, and then link people to other parts of the docs they want to explore. See #3969 for more information._

## Introduction and goals

Godot has different kinds of users with varied skills and needs. The current step-by-step guide contains mixed content, sometimes with language that's too technical for many users. As many persons wrote it over several years, it also lacks coherence.

This task aims to make the series accessible enough so people who are new to game creation, but not entirely new to programming, can follow it. Having some programming foundations is a pre-requisite to learn an extensive API like Godot's.

For people who have no programming experience, we will link to comprehensive free resources to get them started:

1.  Harvard's intro to computer science, CS50, a [free open courseware](https://cs50.harvard.edu/x/2020/), and relies on open-source technologies.
2.  The free ebooks and Udemy courses by Al Sweigart are great for self-paced learning: [Automating the boring stuff with Python](https://automatetheboringstuff.com/), and Invent with Scratch for young adults.

The getting started guide should not cover engine features in-depth. Instead, it will link to pages that cover given topics in greater depth.

The getting started section should help users:

1.  Understand the fundamental concepts of Godot, like nodes, scripting, the scene tree, and more.
2.  Get a sense of available features, how they work, and see if Godot is a good match for their projects.
3.  Know their way around the editor.
4.  Get started creating 2D and 3D games with Godot.
5.  Find more information about specific aspects of the engine.

## The plan

The plan below is a list of topics the Getting Started section should cover. The order and topics are subject to change, of course. This redesign of the getting started series is meant to make it more coherent and to use consistent writing and language.

The Getting Started section page should explain how the guide works and the pre-requisites for each series. In particular, it should link beginners to free resources to learn to code.

I'm also going to work on a landing page for the docs linking to other sections as a separate task.

1.  Introduction
    1.  Introduction to Godot and general overview its features: a guide to help answer questions such as "Is Godot for me? What can it do for me?"
    2.  First look at the editor and its interface.
    3.  Overview of Godot's main concepts: brushing over the scene nodes, scenes, scripts, scene tree, signals, in a short page. Unlike the current pages about scripting, instancing, etc., the goal is to give you a sense of how Godot works in a few minutes.
    4.  Learning new features: a guide to using the built-in code reference, online documentation, and best practices to get help on available communities.
2.  Nodes and Scenes: a longer introduction to nodes, their features, and composing them into reusable scenes
3.  Creating your first scene
4.  Introduction to scripting: overview of available programming languages
5.  GDScript hands-on: a non-exhaustive, brief, but hands-on introduction to GDScript, adding behavior to a scene.
6.  Reacting to changes with signals: a short intro to signals, and using them in the previously created scene.
7.  Creating instances of a scene: intro to instancing, changing properties in the original scene, modifying the instance
8.  Creating your first 2D Game (already available, Dodge the Creeps)
9.  Creating your first 3D Game

## Moving or removing existing content

I would move some existing content in the Step-by-step series to other places, and link to it from the getting started series:

1.  Signals documentation could be in Scripting.
2.  Exporting is covered in Project Workflow, I'd keep it all there and link to the corresponding section.
3.  File System to either Scripting or Input and Output.
4.  Resources: we could brush over the basics of resources in Getting Started, explaining that all images etc. you put into nodes are resources. The page contains more technical and reference-like information that should move to… Scripting?
5.  The intro to animation should be in Animation. It doesn't need to be a tutorial about animating a splash screen.
6.  SceneTree is a technical article that explains Godot's internals and initialization.
7.  Singletons -\> Scripting

To remove:

1.  GUI tutorials
2.  Splash screen tutorial

## To review and integrate

<https://github.com/godotengine/godot-docs/pull/2958/files>

**Comment by NathanLovato** [comment]
@cbscribe may I ask you for feedback on this plan? I already sent you the short list, but if you have any more suggestions or critiques, they'd be welcome.

**Comment by cbscribe** [comment]
I like the overall flow. 

Questions:

- Several things are being proposed to move to "Scripting". That section is currently divided by language. If signals are discussed in there, will this need to be duplicated in the GDScript and C# sections?
- Signals are pretty fundamental node functionality. I think I'd rather see them in the "Nodes and Scenes" section, or in part 5.
- Agreed on Animation, Exporting, and Resource
-

**Comment by NathanLovato** [comment]
Thanks. Editing to include a part about signals.

Even with an intro to signals in getting started, I think we'd need a more complete signals documentation somewhere else.

And I'm unsure where to put it, but how about:

1. Having a page about the node tab and signals editor in an Editor manual section?
2. For scripting, would it work to have a new sub-section with articles that are relevant to all supported languages? There, I'd put signals, groups, possibly some more docs about the scene tree, resources... because there can be quite a lot to say about all these.

**Comment by cbscribe** [comment]
I'm not quite sure either.

> Having a page about the node tab and signals editor in an Editor manual section?

It doesn't feel like it belongs in the editor section - that would just be about the location where you can access the feature in the UI, not about its purpose/use. One of the main uses of signals is communication between nodes. Talking about that in the editor section, which comes before everything about nodes and scenes, doesn't seem right.

> For scripting, would it work to have a new sub-section with articles that are relevant to all supported languages? There, I'd put signals, groups, possibly some more docs about the scene tree, resources... because there can be quite a lot to say about all these.

Doing that starts to be complicated because you're going to either talk around the details or need to show code examples, at which point you might as well be in the language section. While you can show both GDScript and C# in the code tabs, in the actual written text it becomes awkward.

On the other hand you'd have a lot of duplicated pages between the GDScript and C# sections, covering the exact same things.

**Comment by NathanLovato** [comment]
> Talking about that in the editor section, which comes before everything about nodes and scenes, doesn't seem right.

There might be a misunderstanding. I mean to have:

1. An intro page about signals in Getting Started
2. A complete reference of the signal connection through the editor in the Tutorials (soon manual) -> Editor section
3. A complete signals docs in the Scripting section.

The rationale for 2. being that the editor UI works the same regardless of the language, and while it's part of Godot's declarative code for me, it's also editor UI.

But again, not sure what's best either.
