### ISSUE TITLE
Change NinePatchRect's patch margin descriptions

### ISSUE THREAD

**Issue by Error7Studios** [godotengine/godot-docs#4044]
**Your Godot version:**
3.2.3.stable

**Issue description:**
NinePatchRect `patch_margin_left` and `patch_margin_right` descriptions are confusing (and possibly wrong?)

(current descriptions)
`patch_margin_left`
The height of the 9-slice's left column.

`patch_margin_right`
The height of the 9-slice's right column.

**Proposed change:**
Use **_width_** instead of **_height_** in those descriptions.

**URL to the documentation page (if already existing):**
https://docs.godotengine.org/en/stable/classes/class_ninepatchrect.html

**Comment by InfiniteAnts** [comment]
I submitted a pull request for this [here.](https://github.com/godotengine/godot/pull/42511)
