### ISSUE TITLE
Error in Tutorial "Your first game", type conversion

### ISSUE THREAD

**Issue by ZedMcJack** [godotengine/godot-docs#4047]
In Main node script, in event _on_MobTimer_timeout() there are 2 similar errors
1. Code `direction += GD.RandRange(-Mathf.Pi / 4, Mathf.Pi / 4);`
Error: Cannot implicitly convert type double to float. An explicit conversiot exists (are you missing a cast?)
2. Code `mobInstance.LinearVelocity = new Vector2(GD.RandRange(150, 250),0).Rotated(direction);`
Error: Argument 1: cannot convert from double to float

My Godot version is at 3.1.2

**Comment by Calinou** [comment]
> My Godot version is at 3.1.2

Can you test this with the latest stable version, which is [Godot 3.2.3](https://godotengine.org/article/maintenance-release-godot-3-2-3) as of writing?

**Comment by ZedMcJack** [comment]
I tried downloading the latest Mono build 3.2.3 but it failed to compile even after downloading Mono & VS so I switched to GDScript version in hope I wont stumble on new error in my first contact with engine. If I disregard my mix up of documentation it ok so far.

**Comment by greenmoggle** [comment]
I just had a look into this and it's a simple fix. `GD.RandRange` returns a double where `direction` is expecting a `float` and `Vector2` is also expecting a float. Prefacing `GD.RandRange` with `(float)` solves this issue. Happy to make a pull request for this one.

**Comment by greenmoggle** [comment]
Actually I had another look and the tutorial gets you to create a function called `RandRange` but instead uses the inbuilt `GD.RandRange` later on in the tutorial which causes the type issue. Removing the `GD.` fixes it.

**Comment by greenmoggle** [comment]
#4062

**Comment by ZedMcJack** [comment]
Thanks for looking into this

**Comment by Calinou** [comment]
Reopening, as this issue is still relevant as far as I know. The pull request fixing it hasn't been merged yet.
