### ISSUE TITLE
Color docs should have a little image showing the color of each constant

### ISSUE THREAD

**Issue by ShatReal** [godotengine/godot-docs#4060]
**Your Godot version:**
3.2.2
**Issue description:**
Not really an issue, but the constants section on the color page lacks any color. It's just a bunch of text. I mean, I know all the colors have names, but I don't know them all, and I don't want to look them all up to see what color they are.
**URL to the documentation page (if already existing):**
https://docs.godotengine.org/en/stable/classes/class_color.html

**Comment by Calinou** [comment]
This will be implemented by https://github.com/godotengine/godot-docs/pull/3881 once it's merged.

**Comment by ShatReal** [comment]
Oh, ok, thanks for letting me know.

**Comment by Calinou** [comment]
Reopening, as this issue is still relevant until the PR in question is merged :slightly_smiling_face:

**Comment by NathanLovato** [comment]
Closed in https://github.com/godotengine/godot-docs/commit/d585cf540e0fd12483361f159af5595ef3da2d68
