### ISSUE TITLE
TextEdit: get_word_under_cursor returns text under caret, not mouse

### ISSUE THREAD

**Issue by me2beats** [godotengine/godot-docs#4061]
**Your Godot version:**
3.2.3

**Issue description:**
`TextEdit` `get_word_under_cursor()` returns text under caret, not under mouse
But documentation says:
> Returns a String text with the word under the **mouse cursor** location.

**URL to the documentation page:**
https://docs.godotengine.org/ru/stable/classes/class_textedit.html#class-textedit-method-get-word-under-cursor

**Comment by greenmoggle** [comment]
Perhaps it would be better described as:

**Returns the word under the caret (text cursor) location.**

**Comment by Feniks-Gaming** [comment]
https://github.com/godotengine/godot/pull/43501 should close it
