### ISSUE TITLE
Review and update docs contribution guidelines

### ISSUE THREAD

**Issue by NathanLovato** [godotengine/godot-docs#4065]
Following #4064, I'm editing the documents about contributing to the docs.

Tasks:

- [ ] Separate docs-related contribution guides from other contribution guides in the index page.
- [ ] Proofread docs-related pages to simplify the language.
- [ ] Cross-reference documents.

**Comment by NathanLovato** [comment]
@akien-mga the page about contributing to the documentation redirects readers to the README file. However, part of the information they need is still in the docs page, including links to other pages.

How about moving all the information from the readme to the documentation's contributing section and linking to it? This way, all info about contributing would be in one place.

**Comment by akien-mga** [comment]
Yeah I agree, we should consolidate everything into the docs pages, and reference them from the README.

**Comment by NathanLovato** [comment]
Thanks, I'm on it!
