### ISSUE TITLE
Misleading and incomplete OpenSimplexNoise reference

### ISSUE THREAD

**Issue by hazarek** [godotengine/godot-docs#4078]
**Your Godot version:**
3.2.3rc3official

**Issue description:**
_Misleading information:_ Doc says the all ranges are in [-1,1], this is not true, I'll prove it.
_Missing information:_ There is no information about the min and max values ​​of the properties, only the following was written for octave;
> Note: The maximum allowed value is 9.

**URL to the documentation page:**
https://docs.godotengine.org/en/latest/classes/class_opensimplexnoise.html

Values do not exceed the range [-0,8,0,8] (approximately) at normal settings. it becomes infinitive when the critical threshold is exceeded.(negative persistence)

![b](https://user-images.githubusercontent.com/36481442/90769424-e6319f80-e2f8-11ea-9df5-7bb8b5c95f34.gif)
If it exceeds the range [-1,1], the documentation is lying. Here I proved it, and More useful information about parameters should be given.

that is, you can never dynamically get the value -1 and 1 at runtime (not valid for textures, values stored in arrays can be normalized)

**Comment by Calinou** [comment]
Fixed by https://github.com/godotengine/godot/pull/43279 (3.x) and https://github.com/godotengine/godot/pull/56718 (4.0).
