### ISSUE TITLE
Inconsistency in documentation regarding dictionaries

### ISSUE THREAD

**Issue by atgote** [godotengine/godot-docs#408]
In the article http://docs.godotengine.org/en/stable/learning/scripting/gdscript/gdscript_advanced.html#doc-gdscript-more-efficiently
there is a sample source, where it is stated that

`# same example, lua-style support`
`...`
`d.mother = "rebecca" # this doesn't work (use syntax below to add a key:value pair)`
`d["mother"] = "rebecca" # this works`

but in the article http://docs.godotengine.org/en/stable/learning/scripting/gdscript/gdscript_basics.html#doc-gdscript
is another sample source, which reads exactly opposite:

`var d = {} # create an empty Dictionary`
`d.Waiting = 14 # add String "Waiting" as a key and assign the value 14 to it`
`...`

So, is it allowed to create new keys in dictionaries using the following syntax:

`dictionary.new_key = "new value"`?

I'm new to GScript, so I cannot tell which one is valid or invalid neither I will take responsibility for submitting changes on github (possible these were for different versions of engine/language?)...

**Comment by akien-mga** [comment]
I think the latter might be wrong, but the best to confirm would be to check. Even if you're new to GDScript, you should be able to tell whether it works or if the compiler yells at you ;)

**Comment by vnen** [comment]
Both `d.mother = "rebecca"` and `d["mother"] = "rebecca"` works. I use that first style a lot.

**Comment by akien-mga** [comment]
Even for a first assignment? (i.e. if `d` currently doesn't have any `mother` key)

**Comment by vnen** [comment]
> Even for a first assignment? (i.e. if d currently doesn't have any mother key)

Yes. In fact, I just tested on the stable release to be sure and its working.

**Comment by akien-mga** [comment]
Thanks, so we need to fix the first example then.
