### ISSUE TITLE
Update Environment docs following implementation of Glow in GLES2

### ISSUE THREAD

**Issue by akien-mga** [godotengine/godot-docs#4091]
**Your Godot version:**
3.2.x / stable

**Issue description:**
The [Environment and post-processing](https://docs.godotengine.org/en/stable/tutorials/3d/environment_and_post_processing.html) manual page has a section on the Glow effect: https://docs.godotengine.org/en/stable/tutorials/3d/environment_and_post_processing.html#glow

But the end of the section mentions that this is only supported on GLES3, which is no longer true since Godot 3.2.

Moreover, for 3.2 the parameters need to have different values to achieve similar results due to the lack of HDR support, so this should likely be noted here too.

The GLES2/GLES3 difference page could also call it out (and reference the updated Environment page).

CC @clayjohn @Calinou 

**URL to the documentation page (if already existing):**
https://docs.godotengine.org/en/stable/tutorials/3d/environment_and_post_processing.html#glow

**Comment by Calinou** [comment]
I incorrectly thought Bicubic Upscale only worked when using GLES3, but it actually works in GLES2 *as long as your GPU supports the shader4 extension*. This extension is often supported on recent desktop GPUs, but not GLES2-only mobile devices. See https://github.com/godotengine/godot-docs/pull/3978.
