### ISSUE TITLE
casecmp_to Godot API doc not clear

### ISSUE THREAD

**Issue by CitrusWire** [godotengine/godot-docs#4096]
**Your Godot version:**
n/a

**Issue description:**

```
int casecmp_to ( String to )

Performs a case-sensitive comparison to another string. Returns -1 if less than, +1 if greater than, or 0 if equal.
```
This makes no sense (I'm assuming it's a Computer Science thing for sorting). How is a string comparison going to return "greater" and "less than"? In every other language I've used, when you do a string comparison the results are either pass or fail.

**URL to the documentation page:**
https://docs.godotengine.org/en/latest/classes/class_string.html

**Comment by Calinou** [comment]
> In every other language I've used, when you do a string comparison the results are either pass or fail.

Use the `==` operator for that :slightly_smiling_face:

**Comment by CitrusWire** [comment]
@Calinou - Maybe, but that's not what this doc suggests.

I opened it as a bug because the purpose of documentation is to clearly explain something to a user. If the current doc is confusing a user then it's faulty == bug. :-)

**Comment by Calinou** [comment]
> If the current doc is confusing a user then it's faulty == bug. :-)

We only use the `bug` label for incorrect information, not missing information.
