### ISSUE TITLE
Add C# code examples to random_number_generation.rst

### ISSUE THREAD

**Issue by NathanLovato** [godotengine/godot-docs#4098]
We have a freshly-merged page about RNG: #4024 

It has GDScript code examples but lacks C# equivalent. If someone would like to translate the examples to C#, it'd be a nice addition.

**Comment by graphnode** [comment]
I'm guessing [Your first game](https://docs.godotengine.org/en/stable/getting_started/step_by_step/your_first_game.html) tutorial should be updated too?

Since I just started: Are we supposed to use `RandomNumberGenerator` or the `Godot.GD`?

**Comment by Calinou** [comment]
> Since I just started: Are we supposed to use RandomNumberGenerator or the Godot.GD?

Global-scope random functions require less boilerplate to use, but give you less control over randomization since they use a "global" random seed. See [Random number generation](https://docs.godotengine.org/en/latest/tutorials/math/random_number_generation.html) for more information.

**Comment by raulsntos** [comment]
This seems to have been at least partially implemented by https://github.com/godotengine/godot-docs/pull/5249, there are still a few examples that remain GDScript only and the page may have gotten outdated for both GDScript and C# by now (e.g.: it still seems to recommend to use `randomize()` but that's no longer necessary).

**Comment by tetrapod00** [comment]
This seems fully resolved, after https://github.com/godotengine/godot-docs/pull/9822, https://github.com/godotengine/godot-docs/pull/10283, and https://github.com/godotengine/godot-docs/pull/8072.
