### ISSUE TITLE
Mention texture limits in GLES2 differences tutorial

### ISSUE THREAD

**Issue by clayjohn** [godotengine/godot-docs#4102]
Many GLES2 devices only support up to 8 texture units. This means only 8 textures can be used total. 

Specifically, now that https://github.com/godotengine/godot/pull/42446 is merged, it should also mention that devices with only 8 texture units can only use the first 6 levels of glow.

**Comment by InfiniteAnts** [comment]
I did a pull request: #4191

**Comment by clayjohn** [comment]
Closed by #4191
