### ISSUE TITLE
Rename Tutorials section to Manual

### ISSUE THREAD

**Issue by NathanLovato** [godotengine/godot-docs#4107]
We’re moving towards a reference manual, we should have a label that better suggests that.

**Comment by Mickeon** [comment]
What's your opinion on this 2 years later?

**Comment by Calinou** [comment]
> What's your opinion on this 2 years later?

I think it's a good idea to rename the section, but it'll break many pull requests.

**Comment by Mickeon** [comment]
Manual is a much more appropriate name for what the current "Tutorials" section are used for. It would be worth it in the long run, I feel.

**Comment by NathanLovato** [comment]
It could be automated, I think it shouldn't be too hard as it's mostly about renaming a directory. It's def. best to do a sprint merging or closing as many PRs as possible before that.
