### ISSUE TITLE
Document parallax backgrounds in 2D

### ISSUE THREAD

**Issue by NathanLovato** [godotengine/godot-docs#4117]

**Comment by hsandt** [comment]
I'm just coming from https://gamedev.stackexchange.com/questions/202912/godot-parallax-background-is-not-covering-the-entire-screen and while I understand why it's optimal to only repeat textures once (for a maximum of 2x2 when looping on X and Y), this means the user must place the textures precisely at the topleft (or only top for Y, left for X) for exact looping, else a parallax layer will leave some "hole" at certain camera positions.

I think this should be documented better in the API (which is great so users can see it directly from Godot help) and, additionally, on the new page suggested in this issue in more details.

**Comment by tetrapod00** [comment]
Done in https://github.com/godotengine/godot-docs/pull/9587? I believe that the `Parallax2D` node documented there may be different than what was available in 2020. It should still satisfy this issue.

**Comment by tetrapod00** [comment]
Closing as completed by https://github.com/godotengine/godot-docs/pull/9587.
