### ISSUE TITLE
Edit 3D lights and shadows

### ISSUE THREAD

**Issue by NathanLovato** [godotengine/godot-docs#4122]
The page could be reorganized and writing improved. I'd focus on lighting first, then adding shadows, then troubleshooting common issues with lights and shadows (bias, etc.).

**Comment by tetrapod00** [comment]
While it doesn't *exactly* follow this guideline, this page was thoroughly rewritten for 4.x in https://github.com/godotengine/godot-docs/pull/6355, and includes some troubleshooting. As such, I'm closing this as resolved.
