### ISSUE TITLE
Document Navigation features

### ISSUE THREAD

**Issue by NathanLovato** [godotengine/godot-docs#4135]
We should add a new Navigation section covering navigation and AI-related tool.
In particular, this section would cover 2D and 3D navigation and pathfinding. I would also include an article giving an overview of tools at your disposal to implement AI. For example, the VisibilityEnabler and Notifier nodes or creating a line of sight with RayCast and detecting other agents with Area nodes.

Guides could include:

    Real-time navigation (3D)
    Real-time navigation (2D)
    Navigation on a TileMap?
    Path and PathFollow
    Astar and Astar2D

**Comment by Calinou** [comment]
@smix8 Can this issue be closed now?
