### ISSUE TITLE
Document theme capabilities and overriding theme properties

### ISSUE THREAD

**Issue by NathanLovato** [godotengine/godot-docs#4149]
For the User Interface section.

**Comment by Calinou** [comment]
This demo can be linked to in the page: https://github.com/godotengine/godot-demo-projects/tree/master/gui/theming_override

**Comment by skyace65** [comment]
I would consider this fixed by #5162

**Comment by pycbouh** [comment]
Indeed, with https://github.com/godotengine/godot-docs/pull/5162, https://github.com/godotengine/godot-docs/pull/5180 and https://github.com/godotengine/godot/pull/50429 we have improved documentation on theming a lot. I think maybe tutorials could still benefit from a little dive into the API side of things, but for the most part this is handled.
