### ISSUE TITLE
Edit Custom drawing in 2D

### ISSUE THREAD

**Issue by NathanLovato** [godotengine/godot-docs#4184]
The article needs some stylistic changes (titles feel informal: Why?, But…, OK, How?). It doesn’t follow our writing guidelines.

**Comment by KoBeWi** [comment]
To add to that, the tutorial seems to have been written before `draw_arc()` was a thing and it shows incorrect way of drawing arcs and circle outlines. The `draw_circle_arc()` can now be done with a single line.

**Comment by jynus** [comment]
I think some changes were already applied for the titles.

I am doing now as part of #7521 a deeper review, updating the code to 4.X syntax and changing the example to something hopefully more practical (showing different usages of direct drawing- lines, circles, text, etc.) and entertaining. I've written most of the bulk text but I will need some extra time to polish it.

![draw_tutorial](https://github.com/godotengine/godot-docs/assets/8576860/84740b5c-9152-4a85-aead-a114a346f7d5)
