### ISSUE TITLE
Revert button -> Instancing doc

### ISSUE THREAD

**Issue by CitrusWire** [godotengine/godot-docs#4196]
**Your Godot version:**
3.2.3

**Issue description:**
Quote from doc:
> Notice that a grey "revert" button appears next to the adjusted property. When this button is present, it means you modified a property in the instanced scene to override its value in the saved scene. Even if that property is modified in the original scene, the custom value will remain. Pressing the revert button will restore the property to the value in the saved scene.

I don't know if this is a editor bug, or unclear text.
My parsing of that quoted text tells me that the revert button is only shown if there are changes to the scene since it was last saved.
Which in turn means that when you load a scene, it should never have a revert button. Yet whenever I open demo scenes, they all have that revert button on values that I assume are changed from the default. I can go "Scene -> Reload Saved Scene", but the revert buttons remain.

**URL to the documentation page (if already existing):**
https://docs.godotengine.org/en/stable/getting_started/step_by_step/instancing.html

**Comment by pycbouh** [comment]
This doc uses "the saved scene" to refer to the packed scene, and "the instanced scene" to refer to an instance of said packed scene.

**Comment by CitrusWire** [comment]
@pycbouh - Thanks for the explanation but I'm afraid it doesn't clear things up for me. This is probably in large part because I don't know what a "packed scene" is (found - https://docs.godotengine.org/en/stable/classes/class_packedscene.html - but that doesn't help me).

I think the simplest way to clarify is to ask what the revert button is *meant* to do:
1) It resets the value back to the Godot Default
2) It resets the value back to the last time the scene was saved
3) Some other behaviour?

I'm assuming (3). I've tried re-reading this ticket, including the docs quote and your reply and it's still not clear to me what that button does, so I suspect it may be confusing others too.
Once I figure out what's going on with that button I'll hopefully be able to suggest some clearer text that might work there.

**Comment by pycbouh** [comment]
> This is probably in large part because I don't know what a "packed scene"

This is exactly the subject of the article on Instancing you've linked in your issue. The term is mentioned multiple times before the paragraph you have the problem with. I suggest you take another look at it.

**Comment by CitrusWire** [comment]
> > This is probably in large part because I don't know what a "packed scene"
> 
> This is exactly the subject of the article on Instancing you've linked in your issue. The term is mentioned multiple times before the paragraph you have the problem with. I suggest you take another look at it.

Thanks, I know. And I did read it - the description (short and long) a couple of times in fact - but still didn't understand it. I didn't say that because I was trying to remain positive. That page doesn't make sense to me because I don't understand Godot yet. Taking a third look I still don't grok it. And that's heading off-topic anyway. :-)

**Comment by Piralein** [comment]
The page was completely rewritten by [master-commit](https://github.com/godotengine/godot-docs/commit/d6cc5614cb637598de58d4bd181f9b593d38722a) and was backportet to 3.x (3.4) with [backport-commit](https://github.com/godotengine/godot-docs/commit/501cbd41d4f08835bc08f231f49be32debd8557c).

The quoted paragraph was also changed and should be more understandable now.

> This icon indicates you are overriding a value from the source packed scene. Even if you modify the property in the original scene, the value override will be preserved in the instance. Clicking the revert icon will restore the property to the value in the saved scene.

[3.2 Version](https://docs.godotengine.org/en/3.2/getting_started/step_by_step/instancing.html#editing-instances) / [3.4 Version](https://docs.godotengine.org/en/3.4/getting_started/step_by_step/instancing.html#editing-scenes-and-instances)
