### ISSUE TITLE
Translation: find a way so the translators on Weblate won't waste their time translating docs that will likely be polished.

### ISSUE THREAD

**Issue by pyacier** [godotengine/godot-docs#4197]
**The issue:** 

When the update of the whole documentation came, an new and unfinished but merged documentation, will be added to be translated on Weblate and the translators from 45 languages will translate it.

If between this update and the next one, the documentation is finished, when the next update come, all the changed strings in this documentation will need a verification from a translator for all the 45 languages.

Example: 100 changes in 45 languages, 4500 verification.

Those changes that could have been done before the merge of this documentation are mostly formatting changes, corrections or style changes.

**An aggravating factor but not the main issue:**

Weblate don't point what have changed in a string.

**Why the issue appear only now ?** 

Because most of the time, it take long before a documentation is translated, so the changes happen before any translation. Until I complete the french translation and maintain it in this state.

**A solution:**

Thoroughly reviewing any new documentation before merging it.

**Is it possible ?**

I don't know.

What do you think, to achieve that, is there a need of more reviewers or it is simply stopping merging prematurely before full review, something else ?

**Comment by Calinou** [comment]
> Thoroughly reviewing any new documentation before merging it.

This is precisely what @NathanLovato has been doing. However, he sometimes chooses to merge and then fix things after merging, since it's quicker for him.

Relying on GitHub's code review feature to apply changes is probably a better way to go, as we wouldn't have to merge two commits anymore. (We can squash and merge the commits created by GitHub's code review feature.)

**Comment by pyacier** [comment]
As the discussion advance on Discord I understand that I don't understand how documentations are made.

So, as @clayjohn said, I just would like a way so the translators on Weblate won't waste their time translating docs that will likely be polished.

Maybe the title of the issue need to be changed.

**Comment by NathanLovato** [comment]
It's a fair request. I think it's a problem of having a dedicated writer and editor to take care of the docs: proof it all, and work with other contributors and devs to complete it so there's no need for small changes later. It's not the case for now.

The problems with small formatting changes aren't due to people not reviewing PRs, but rather because the docs were written by 200+ contributors and dozens of different reviewers over years. Each contributor has a different experience and writing skills. It's really difficult to unify the style in that case.

> However, he sometimes chooses to merge and then fix things after merging, since it's faster for him to work this way.

Note that when I do that lately, I instantly edit. Or when I can add changes to the original PR, I do that directly.

I've only merged things to be improved later once or twice in the past, for cases where it was beneficial to the users but nobody would have time to edit pages, like the best practices series. They still need edits to that day regarding the wording, but the content is solid and useful to users.

**Comment by kushagra-shukla** [comment]
> **The issue:**
> 
> When the update of the whole documentation came, an new and unfinished but merged documentation, will be added to be translated on Weblate and the translators from 45 languages will translate it.
> 
> If between this update and the next one, the documentation is finished, when the next update come, all the changed strings in this documentation will need a verification from a translator for all the 45 languages.
> 
> Example: 100 changes in 45 languages, 4500 verification.
> 
> Those changes that could have been done before the merge of this documentation are mostly formatting changes, corrections or style changes.
> 
> **An aggravating factor but not the main issue:**
> 
> Weblate don't point what have changed in a string.
> 
> **Why the issue appear only now ?**
> 
> Because most of the time, it take long before a documentation is translated, so the changes happen before any translation. Until I complete the french translation and maintain it in this state.
> 
> **A solution:**
> 
> Thoroughly reviewing any new documentation before merging it.
> 
> **Is it possible ?**
> 
> I don't know.
> 
> What do you think, to achieve that, is there a need of more reviewers or it is simply stopping merging prematurely before full review, something else ?

An approach could be to use page hits data i.e. which translation pages are hit most and stage changes accordingly. It will create inconsistencies between documents of different languages. But as some translations (say French) is used very frequently then it makes sense to prioritize translation for this particular language. While put hold on other translations until some staging period say 5 days or so, during which document can undergo few improvements. After polishing is done in the document then after the staging period all translations can be done. This way number of translation can be drastically reduced (total translations = 45-X + X*100 ; assuming 100 changes occurred in staging period and X = number major high hit languages) at the cost of bringing temporary inconsistencies in the document of different languages for the staging period. However, it is less likely that it will cause major issues or confusion as person reading French translation is not very likely to view Mandarin or Hindi translation of the same document. After the staging period when the document has matured then the document for all languages will be consistent.

**Comment by NathanLovato** [comment]
The docs translation string files are updated manually and occasionally. The issue really is that minor changes happen on the English docs, in this repository. That's about it.

**Comment by pyacier** [comment]
It's the interest of the community that docs in the source language, English, are available as soon as possible. If there is a lake of workforce, waiting for a finished state before merging them will take to long.
So, the only solution is trying to help on this side.

For me, this issue can be closed.

**Comment by NathanLovato** [comment]
Thanks

**Comment by akien-mga** [comment]
For the reference, here are some comments about this that I wrote on Discord:

> Regarding small changes in the translations, I don't think there's any way around it unless we decide that the existing strings are frozen, even if the language, spelling, style, etc. could use improvement.
>
> Note that the translations track the stable branch, so they don't change a lot based on work done in the master branch. And more often that not, having a new tutorial merged and accessible early means that readers can also suggest and make fixes to improve the text.
>
> But if that's really a problem, I could defer the introduction of new pages in the translation template. So when a new page lands on stable, I wouldn't add it to the template for e.g. 2 months, to give it time to mature. That means that localized instances would have the English version of that page for those 2 months.
>
> Or defer the introduction of new pages in the stable branch, but workflow wise it complicates things as I would no longer be able to use git merge to sync master changes with stable, and would indeed have to make the branches diverge and cherry-pick relevant changes manually, leaving out big pages until they're "ready" (which can take a few days or a few months depending on resources and what potential problems the page has).
>
> All in all, while I acknowledge the problem, I'm not sure that potential solutions are worth the trouble, when it comes to the workflow of doc writers and the experience of doc readers. The documentation is always evolving, and there won't ever be a time when a given page can be considered "perfect". As pages get good, changes become some of those tiny annoyances you mention like adding a missing comma or inline code formatting.
>
> Eventually, maybe Weblate will get a feature to highlight what part of a string changed compared to the previous one used for the translation now marked as fuzzy.
