### ISSUE TITLE
Add .app generation to OS X post compile bash script

### ISSUE THREAD

**Issue by toger5** [godotengine/godot-docs#423]
thanks to @bruvzg I know that starting a n application without it being bundled in a .app folder can result in the application loosing focus. which is annoying since than click inputs don't work anymore.

those commands (from @bruvzg) bundles the compiled binary.

could be added to post compile script for OS X.

```
user@host:~/godot$ cp -r misc/dist/osx_tools.app ./Godot.app
user@host:~/godot$ mkdir -p Godot.app/Contents/MacOS
user@host:~/godot$ cp bin/godot.osx.opt.tools.64 Godot.app/Contents/MacOS/Godot
user@host:~/godot$ chmod +x Godot.app/Contents/MacOS/Godot
```

**Comment by bruvzg** [comment]
It would be better to generate an Info.plist on the fly to have up-to-date version information.
[SCons / Creating Bundles](https://bitbucket.org/scons/scons/wiki/MacOSX#markdown-header-creating-bundles)
[About Information Property List Files](https://developer.apple.com/library/content/documentation/General/Reference/InfoPlistKeyReference/Articles/AboutInformationPropertyListFiles.html)

Also note that on OSX 10.8+ stdout and stderr from bundled apps go nowhere.
`OS_OSX::vprint` could be added to use `NSLog` to get output into `Console.app`

**Comment by mhilbrunner** [comment]
Isn't this something to change in Godot/Scons? In which case the Godot repo may be a better fit for this issue.

**Comment by Calinou** [comment]
See https://github.com/godotengine/godot/issues/16415.

**Comment by mhilbrunner** [comment]
Closing this, obsoleted by above issue in the main repo
