### ISSUE TITLE
Connecting Signal - Outdated doc

### ISSUE THREAD

**Issue by CitrusWire** [godotengine/godot-docs#4237]
Godot 3.2.3

https://godot-es-docs.readthedocs.io/en/latest/getting_started/step_by_step/signals.html

That has a step-by-step guide for connecting a timer signal to a script.
THe blurb says:
> Note that the Timer node is red - this is not an error, but is a visual indication that it’s the node that is emitting the signal.

And there's a screenshot that shows it too.

But for me it's not read, it's blue (which makes more sense from a "red is bad" perspective). The dialog is different too so I guess it has changed. I see:

![image](https://user-images.githubusercontent.com/72134064/95566557-9d08ec80-0a19-11eb-8300-f2a85edc0dc1.png)

(You're welcome to use that as the new screenie)

(I'd also suggest the "Advanced" tab should be closed in the screenshot too as that's the default).

**Comment by CitrusWire** [comment]
Other things that have changed:
1) 
The big warning that says:
> The target node must have a script attached or you’ll receive an error message.

Doesn't seem to be necessary either as it doesn't seem to be possible to select a node that doesn't have a script.

2) 
> On the bottom of the window is a field labeled “Method In Node”

is now "Receiver Method"

**Comment by pycbouh** [comment]
It says "blue" in the actual Godot Docs, both in stable (https://docs.godotengine.org/en/stable/getting_started/step_by_step/signals.html) and in latest (https://docs.godotengine.org/en/latest/getting_started/step_by_step/signals.html). This is some outdated mirror you're reading.

**Comment by CitrusWire** [comment]
Hmmm. Good point.

But then, Readthedocs (https://readthedocs.org/projects/godot/) says that:

> This project contains the official documentation for the MIT-licensed Godot game engine.

And the actually-hosted-by-godot docs link to that "outdated mirror" (bottom left):
https://docs.godotengine.org/en/stable/

So... ?

**Comment by pycbouh** [comment]
I don't see where it links to the host `godot-es-docs.readthedocs.io`. Official docs are available either via the RTD host `godot.readthedocs.io` or via our official domain `docs.godotengine.org`.

**Comment by CitrusWire** [comment]
Yep, just looked at the URL, it is different, and the "es" in there would suggest it's Spanish, but it's actually English (I don't speak Spanish so that'd be a weird thing for me to reading :-) ).

I got to the docs through a search engine query. Now that I look, my docs tabs are a mixture of godotengine.org and the RTD link.

Looks like RTD have some weirdness going on at their end.

**Comment by pycbouh** [comment]
Yes, that mirror often appears in Google if you look for the docs. Not sure if we can or should do anything about it. Anybody is free to host a mirror of this documentation, as it's MIT-licensed. This particular one hasn't been updated for almost 2 years though.

**Comment by Calinou** [comment]
Has anyone managed to contact the owner of godot-es-docs? We have a more up-to-date Spanish translation in the official documentation now.

**Comment by CitrusWire** [comment]
It's a variant of a problem I've come across before in other projects.

Search for something and get back a page for version 1.3, whereas the project is now on 2.4 or something. That's usually obvious because the URL has "1.3" in it rather than "latest" and "stable".

It's definitely something that falls under "should" do something about; otherwise you end up with situations like this which isn't useful for anyone. :-/

**Comment by pycbouh** [comment]
@Calinou Seeing as they don't even host their own fork but rather an outdated commit from the master Godot repo, I don't know if we can contact them in any form. Is there some PM system on RTD? That's the only account of theirs available. Might be worth messaging the RTD team instead.

**Comment by Calinou** [comment]
> Is there some PM system on RTD?

I don't think there's one, just like on GitHub actually.

**Comment by CitrusWire** [comment]
https://docs.readthedocs.io/en/stable/contribute.html

> 
> Ask usage questions (“How do I?”) on StackOverflow.
> Report bugs, suggest features or view the source code on GitHub.
> Discuss topics on Gitter.
> On IRC find us at #readthedocs.

**Comment by pycbouh** [comment]
@CitrusWire Our docs are SEO'd to give `stable` the most priority, but you can personally open any URL with 3.2 in it instead. This problem here is different because that's a third-party mirror set up off of the back of this repo by an unknown person.

**Comment by CitrusWire** [comment]
@pycbouh - yeah, the outdated-versioning thing is not a problem I've seen with Godot, so excellent job there. :-)

I mentioned it as a variant because at its core it's an issue with search engines not really knowing what the definitive version of a doc is. It's actually difficult for a search engine to solve.

---

Thanks for the clarification. I'd come to that conclusion after your earlier helpful posts. Thanks.

**Comment by Calinou** [comment]
I sent an e-mail to Read the Docs about this situation.

**Comment by NathanLovato** [comment]
Should we close the issue? It's not a change we need to make to this repository, right?

**Comment by CitrusWire** [comment]
Well, this part is still the case with current:


> The big warning that says:
> > The target node must have a script attached or you’ll receive an error message.

> Doesn't seem to be necessary either as it doesn't seem to be possible to select a node that doesn't have a script.

**Comment by NathanLovato** [comment]
Thanks, I'm on it.
