### ISSUE TITLE
Document a low level workflow using Servers

### ISSUE THREAD

**Issue by crisestudio** [godotengine/godot-docs#4240]
**Your Godot version:**
3.2.3

**Issue description:**
I want to use godot more like a framework, closer to libgdx, but I don't want to use a real framework because I would lose all the nice goodies that Godot has.
So, my issue is that I was told my idea is possible if I use low level servers in Godot.
But I've found this area is really poorly documented.

Maybe some basic small tutorial or game or project with example code could help with my issue.

**Comment by clayjohn** [comment]
Have you read the servers tutorial in the official docs?

https://docs.godotengine.org/en/stable/tutorials/optimization/using_servers.html

**Comment by crisestudio** [comment]
> Have you read the servers tutorial in the official docs?
> 
> https://docs.godotengine.org/en/stable/tutorials/optimization/using_servers.html

My question was more in the sense of making a small 2D demo so people can study it.

**Comment by Calinou** [comment]
> My question was more in the sense of making a small 2D demo so people can study it.

We're in the process of reworking the documentation to remove step-by-step tutorials *with the exception* of introductory 2D and 3D game tutorials (using the high-level node system). Therefore, a low-level demo would now be considered off-topic in the official Godot documentation.

That said, nothing prevents a third party from creating such a tutorial.

**Comment by skyace65** [comment]
Closing this issue per what Calinou said above.
