### ISSUE TITLE
Certain details missing on the "Your first game" part of the documentation

### ISSUE THREAD

**Issue by TheNamesGregoryAndounuts** [godotengine/godot-docs#4244]
**Issue description:**
I'm reading the step by step guide and I noticed that a certain detail of the instructions got left out, which I feel needs clarification.

> Click the Main node and you will see the Mob property in the Inspector under "Script Variables".
> 
> You can assign this property's value in two ways:
> 
>     Drag Mob.tscn from the "FileSystem" panel and drop it in the Mob property .
>     Click the down arrow next to "[empty]" and choose "Load". Select Mob.tscn.
> 
> Next, select the Player node in the Scene dock, and access the Node dock on the sidebar. Make sure to have the Signals tab selected in the Node dock.
> 
> You should see a list of the signals for the Player node. Find and double-click the hit signal in the list (or right-click it and select "Connect..."). This will open the signal connection dialog. We want to make a new function named game_over, which will handle what needs to happen when a game ends. Type "game_over" in the "Receiver Method" box at the bottom of the signal connection dialog and click "Connect". Add the following code to the new function, as well as a new_game function that will set everything up for a new game:

After this point it asks me to add code to a script without specifying which should be appended with this code. It could be most likely the main.cs script, but I don't want to leave anything to chance, as it might be needed to be added to the player script. Sorry for coming across as a big dumb-dumb, just thought that bit needed editing.

**URL to the documentation page:**
https://docs.godotengine.org/en/stable/getting_started/step_by_step/your_first_game.html

**Comment by skyace65** [comment]
I've read this over several times and it indicates clearly that you need to add the code to the main script. "Add the following code to the new function" The tutorial has you create a function in the previous sentence in the main script. And doing that, by connecting a signal, brings up the main script in the code editor and shows you the new function. There's nothing ambiguous about how this is worded. This issue should be closed.
