### ISSUE TITLE
FPS Tutorial (Part 5): Missing instruction

### ISSUE THREAD

**Issue by ReturnMinusOne** [godotengine/godot-docs#4246]
(Godot version 3.2.2)

The tutorial specifies that the code for Sticky_Grenade.gd is almost identical to that of Grenade.gd, with a few exceptions. Most of these exceptions are listed, but one is missing.

The following code:

`grenade_mesh = $Grenade`

needs to be changed to:

`grenade_mesh = $Sticky_Grenade`

The error message that shows up (with the first line) is less than informative: "Invalid set index 'visible' (on base: 'null instance') with value of type 'bool'."

**URL to the documentation page:** https://docs.godotengine.org/en/3.2/tutorials/3d/fps_tutorial/part_five.html

**Comment by Calinou** [comment]
Note that the FPS tutorial was removed from the `master` branch in https://github.com/godotengine/godot-docs/pull/4074. This is part of the changes about moving towards a reference manual: https://github.com/godotengine/godot-docs/issues/3390

**Comment by ReturnMinusOne** [comment]
Oh, I see, thank you. A bit of a shame though, as this tutorial is very substantial and I've learned a lot from it so far.

Hopefully someone will be able to rewrite it for Godot 4.

**Comment by NathanLovato** [comment]
Even if you learned a lot from the FPS tutorial, like many of our older tuts in the docs, it taught many programming practices I at least wouldn't recommend with Godot. It would've needed many changes.

Anyway, in general, we're removing most step-by-step tuts from the official manual and focusing on writing a complete manual. Tutorials and other tips would best fit in a community-driven wiki, on top of community websites.

Should I close the issue in such a case or should we still fix it as it's in the stable docs?

**Comment by ReturnMinusOne** [comment]
I suppose it does make sense to prioritise the docs. Still, until Godot 4.0 is released, it seems worthwhile to make small time-saving changes to the educational content already available, if not complete rewrites.

I haven't found a timeline showing when we can expect 4.0 to launch, so I can imagine more beginners using the FPS tutorial just to get familiar with GDScript (at least in its current form) and the editor.

That said, it does sound like 4.0 is approaching quickly, so maybe the tutorial will become outdated sooner than I would expect. In either case, someone searching for the error I mentioned might well land on this thread and find out what the problem is, so feel free to close it if needed.

(Incidentally, I found a second error in the "Grabbing and throwing objects" section, where the "fire_grenade" action is checked instead of the "fire" action. I thought it best to mention it here instead of creating a new issue, which might lead back to the same conversation about the tutorial's relevance.)

**Comment by skyace65** [comment]
Closing due to the tutorial being removed in the 3.x version of the docs.
