### ISSUE TITLE
Tree Order - Getting started

### ISSUE THREAD

**Issue by CitrusWire** [godotengine/godot-docs#4252]
https://docs.godotengine.org/en/stable/getting_started/step_by_step/scene_tree.html

A few related things:

> Tree order
> 
> Most node operations in Godot, such as drawing 2D, processing, or getting notifications are done in tree order. This means that parents and siblings with a lower rank in the tree order will get notified before the current node.

1) What does this mean? Especially the last sentence. The screenshot below that suggests that things are run top to bottom, but that doesn't seem to be what this paragraph is saying (although, I'm not actually sure what this paragraph is saying as "lower rank" could mean a number of things due to there being various possible ways that "ranking" could happen). Also, what's the "current node" in this context?

2) "notified" = notifications? In which case I'll point to: https://github.com/godotengine/godot-docs/issues/4232 - notifications aren't explained anywhere that I can find, and the doc that does cover in getting-started them basically says "you don't need to know about them" - which is fine, but then you can't use them later). Should use "Signals" instead (That's assuming they're synonyms at this level of abstraction).

The next subsection '"Becoming active" by entering the Scene Tree' does talk about notifications, but it puts them into the context of the GDScript functions they relate to, so it's fine.

**Comment by NathanLovato** [comment]
The getting started series is getting a rewrite. See #4035 for more info.

The sentence is confusing. Here are some answers until we address the issue.

The tree order means top-to-bottom,  but deepest nodes execute code before their parent. This happens to the final scene tree, when you run the game and click the "Remote" tab under the Scene dock.

Say we have this structure:

![Screenshot from 2020-10-12 13-59-52](https://user-images.githubusercontent.com/12694995/95785579-3f7fd480-0c93-11eb-8cfe-78b4076cfa1a.png)

The tree order means ActiveTurnQueue get callbacks before UI, but e.g. Godot will call the `_ready()` and `_unhandled_input()` callbacks of Bear, BugCat, and BugCat2 before ActiveTurnQueue. This allows deeper nodes in the tree to handle details and leave the parent node as a fallback. It's especially useful with user interface when it comes to input callbacks.

Regarding notifications, there are already some docs about them, for example: https://docs.godotengine.org/en/stable/getting_started/workflow/best_practices/godot_notifications.html

The sentence that says you don't need to know about them is poorly phrased, it's more like "you don't need to worry about them yet". Notifications are a feature that's different from signals. Most users never touch them but they can be useful as you start coding complex games.
