### ISSUE TITLE
Fragment built-ins "VIEW" is described as being the vector from camera to fragment, when it is actually the vector from fragment to camera.

### ISSUE THREAD

**Issue by Arnklit** [godotengine/godot-docs#4267]
**Your Godot version:**
3.2.3

**Issue description:**
Fragment built-ins "VIEW" is described as being the vector from camera to fragment, when it is actually the vector from fragment to camera.

**URL to the documentation page:**
https://docs.godotengine.org/en/stable/tutorials/shading/shading_reference/spatial_shader.html#fragment-built-ins

**Comment by clayjohn** [comment]
Are you sure? Keep in mind, VIEW is in camera space, not in world space. 

I guess either way it needs to be updated. Because it is a normalized direction, rather than a vector from one point to another.

**Comment by clayjohn** [comment]
Thanks for the explanatory image. It's very helpful for me to put my head back on straight. Yes the view vector is relative to the fragment. 

It is the direction to the camera from the current fragment. It is used in conjunction with light direction and surface normal to compute lighting.
