### ISSUE TITLE
Make clear that free() doesn't set any references to it to null (in release builds)

### ISSUE THREAD

**Issue by Demindiro** [godotengine/godot-docs#4270]
**Your Godot version:**
3.2.2

**Issue description:**
While investigating a segmentation fault in a release build I realized one of the scripts was calling a method on an object that has been freed in the previous frame with `queue_free`. I assumed that all references to freed objects were automatically set to null since that is what seems to be happening in the editor (and debug builds).

That said, I'm not sure how [is_instance_valid](https://docs.godotengine.org/en/stable/classes/class_@gdscript.html?highlight=get_stack#class-gdscript-method-is-instance-valid) is supposed to work then (and it seems it indeed doesn't work at all). Is there something I'm misunderstanding?

**URL to the documentation page (if already existing):**
https://docs.godotengine.org/en/stable/classes/class_object.html#class-object-method-free

**Comment by Calinou** [comment]
See https://github.com/godotengine/godot/issues/35534.

**Comment by Calinou** [comment]
Closing in favor of https://github.com/godotengine/godot-proposals/issues/1589. See the last comment in that proposal.
