### ISSUE TITLE
Various class_dictionary issues

### ISSUE THREAD

**Issue by CitrusWire** [godotengine/godot-docs#4272]
I just got myself very confused by the dictionary documentation on my first attempt to use dictionaries. 

https://docs.godotengine.org/en/stable/classes/class_dictionary.html

A) The "Creating a dictionary:" section is a prime example of why comments in code docs are really *really* important. https://github.com/godotengine/godot-docs/issues/4188 - had there been one here for `another_dir`, I would not have just lost a bunch of time wondering why my dict declaration wasn't working.

B) Code examples should be self-contained. In this case ("Creating a dictionary") the `key1, key2, key3` variables are not declared, so there's no reason for the reader to assume they're referencing variables rather than simple strings.

C) The dictionaries are all called "_dir". Isn't that usually shorthand for directory? Should they not be `_dict`?

D) No-where is it explained in this doc that there are two incompatible ways of declaring dictionaries. Nor are the caveats and inconsistencies between them explained.

E) In fact, there's no coverage at all of the Lua-style syntax!

F) It may be worth noting the behaviour of Dictionaries and `const`. It's implied as a result of the "always passed by reference", but not everyone will make the connection if it's not spelled out.

G) "Dictionaries will preserve the insertion order when adding elements, even though this may not be reflected when printing the dictionary." - If you're including this sentence, an example of how to get things out in order would be nice if it's not the default behaviour.

H) "Erasing elements while iterating over them is not supported and will result in undefined behavior." - This note could benefit from referencing the `erase()` method which I guess is the way you're meant to do that.

I) "Returns the size of the dictionary (in pairs)." - what does that mean (the "in pairs" bit is confusing)? A better phraseology wouldn't use the word "size" because that's the word being defined. I'm assuming this is what it means: "Returns the number of keys in the dictionary".

**Comment by Feniks-Gaming** [comment]
> D) No-where is it explained in this doc that there are two incompatible ways of declaring dictionaries. Nor are the caveats and inconsistencies between them explained.

Could you please expand on what you mean. I am willing to attempt to fix this doc entry but I am unsure what do you mean by this. Can you give me example of those "two incompatible ways of declaring dictionaries"

>E) In fact, there's no coverage at all of the Lua-style syntax! 

Isn't that covered under tutorial linked on this wiki page or are you talking about something else? https://docs.godotengine.org/en/stable/getting_started/scripting/gdscript/gdscript_basics.html#dictionary
