### ISSUE TITLE
Shader TIME description is unusable

### ISSUE THREAD

**Issue by Duehok** [godotengine/godot-docs#4282]
**Your Godot version:** 3.2.2, valid also for 4.0

**Issue description:**
Description of the TIME global:

> in float TIME | Global time, in seconds. It's subject to the rollover setting (which is 3,600 -1 hour- by default).

"Global time" is meaningless.
Is it form epoc?
From boot?
From app start?
From something else?

Is it platform-dependent?

Is it subject to the engine's time_scale property?

**URL to the documentation page:**
https://docs.godotengine.org/en/stable/tutorials/shading/shading_reference/canvas_item_shader.html#global-built-ins

**Comment by Calinou** [comment]
> Is it form epoc?

No.

> From boot?

No.

> From app start?

Yes.

> From something else?

No.

> Is it platform-dependent?

No.

> Is it subject to the engine's time_scale property?

No, but you can control the `TIME` variable's time scale separately from the engine time scale since 3.2.2 thanks to https://github.com/godotengine/godot/pull/38995. For the record, `TIME` isn't not affected by pausing either.

**Comment by Calinou** [comment]
Fixed by #4283 and #4284.

**Comment by spikeyarmaku** [comment]
Although it was updated in the CanvasItem shader page, it hasn't been updated here: https://docs.godotengine.org/en/stable/tutorials/shaders/shader_reference/spatial_shader.html#doc-spatial-shader
