### ISSUE TITLE
Add FOG, RADIANCE, and IRRADIANCE  builtins to Spatial shader reference

### ISSUE THREAD

**Issue by clayjohn** [godotengine/godot-docs#4290]
**Your Godot version:**
Master

**Issue description:**
Now that https://github.com/godotengine/godot/pull/41415 is merged, we need to add entries for ``FOG``, ``RADIANCE``, and ``IRRADIANCE``.

out vec4 FOG | If written to, blends final pixel color with FOG.rgb based on FOG.a
out vec4 RADIANCE | If written to, blends environment map radiance with RADIANCE.rgb based on RADIANCE.a
out vec4 IRRADIANCE | If written to, blends environment map IRRADIANCE with IRRADIANCE.rgb based on IRRADIANCE.a

**URL to the documentation page:**
https://docs.godotengine.org/en/latest/tutorials/shaders/shader_reference/spatial_shader.html

**Comment by MaxMorse** [comment]
Do these go under Light Built-ins?

**Comment by clayjohn** [comment]
Nope. They go under fragment!

**Comment by skyace65** [comment]
@clayjohn you can close this issue now.
