### ISSUE TITLE
animating_thousands_of_fish.html redirects too many times

### ISSUE THREAD

**Issue by rcorre** [godotengine/godot-docs#4294]
**Issue description:**
The link to the "Animating Thousands of Fish" tutorial says:

```
This page isn’t working. docs.godotengine.org redirected you too many times.
```

**URL to the documentation page:**
https://docs.godotengine.org/en/stable/tutorials/3d/vertex_animation/animating_thousands_of_fish.html

**Comment by skyace65** [comment]
The link seems to be working for me. I'm not sure what's going on.

**Comment by skyace65** [comment]
Is your issue with the link "https://docs.godotengine.org/en/stable/tutorials/3d/vertex_animation/animating_thousands_of_fish.html" or is there a link to that page somewhere else in the docs that isn't working?

**Comment by rcorre** [comment]
Sorry about this everyone. It appears to be working now. :bow:
