### ISSUE TITLE
Change distance fade description on Spatial Material tutorial page

### ISSUE THREAD

**Issue by Syntaxxor** [godotengine/godot-docs#4295]
**Your Godot version:**
Godot 3.2.3/Godot 3.2 Docs
**Issue description:**
On the bottom of the Spatial Material tutorial page, it mentions Proximity and Distance Fading. The description for Proximity Fade is fine, but it says, "Keep in mind enabling these enables alpha blending..." which may be misleading. Distance fade doesn't require alpha blending if you use a dithering mode. It may be a good idea to flesh out that page with more details on Distance Fade and its modes.
**URL to the documentation page (if already existing):**
https://docs.godotengine.org/en/3.2/tutorials/3d/spatial_material.html

**Comment by skyace65** [comment]
What exactly is alpha blending and why is it bad? I'd like to document this but the page doesn't specify, and the example gif is showing proximity fade.

**Comment by Syntaxxor** [comment]
> What exactly is alpha blending and why is it bad? I'd like to document this but the page doesn't specify, and the example gif is showing proximity fade.

Alpha blending requires a special sort of rendering that is more performance-intensive and doesn't allow for depth mapping, so you can't have shadows. It's basically just compositing transparent objects on top of the rendered scene.

**Comment by skyace65** [comment]
Thanks!
