### ISSUE TITLE
Instructions for triggering Self-Contained mode is unclear

### ISSUE THREAD

**Issue by pajcek11** [godotengine/godot-docs#4298]
**Issue description:**
The explanation for Self-contained mode of saving is a bit unclear to me.
It sounds like, just by adding an empty file called ._sc_ or _sc_ into the root directory, that the game will magically create a folder called editor_data where the game is saved.

- do I add ._sc_ to //res: before exporting, or to the folder with the binary after exporting
- do I have to create the editor_data folder in //res: , or in the exported folder , or not at all??
- once exported, how to ensure the game will have write access to the game folder (as opposed to the default appdata)?
- and finally, do I use the classic user://savegame.save method? will it automatically reroute "user" to be the "editor_data" folder in the game folder?

**URL to the documentation page (if already existing):**
https://docs.godotengine.org/en/stable/tutorials/io/data_paths.html

Pleae help! Thank you!

**Comment by Calinou** [comment]
Self-contained mode is only for the editor, not exported projects.

**Comment by Calinou** [comment]
The documentation now clarifies that [self-contained mode is only supported in the editor](https://docs.godotengine.org/en/stable/tutorials/io/data_paths.html#self-contained-mode), closing.

As for making self-contained mode work in exported projects, see [this proposal](https://github.com/godotengine/godot-proposals/issues/2474). A workaround using `OS.get_executable_path()` is mentioned.
