### ISSUE TITLE
Link to Lone Wolf Technology website is dead

### ISSUE THREAD

**Issue by Cevantime** [godotengine/godot-docs#4326]
As the title says, the hyperlink to the Lone Wolf Technology Website is dead. It looks like the site isn't online anymore.
Does anyone have any news about this company ?

**Comment by fire** [comment]
Pinging @punto- .

**Comment by fire** [comment]
> puntoToday at 13:16
> Yes, my server went down :(
> puntoToday at 13:17
> I'm working on a new website but the person making it gave birth so she's taking a break

**Comment by Cevantime** [comment]
@punto @fire 
As a web developer, I'll be glad to help if you need anything.

**Comment by skyace65** [comment]
@gdquest the Lone Wolf Technology website is back up, this issue can be closed.

**Comment by Calinou** [comment]
Closing per @skyace65's comment. I can confirm it's back up :slightly_smiling_face:
