### ISSUE TITLE
"GDNative C" example page has a dead link to the "GDNative-demos repository"

### ISSUE THREAD

**Issue by Arnklit** [godotengine/godot-docs#4329]
**Your Godot version:**
3.2.3.Stable

**Issue description:**
"GDNative C" example page has a dead link to the "GDNative-demos repository". It links to this page which does not exist: https://github.com/godotengine/gdnative-demos/tree/master/c/SimpleDemo

**URL to the documentation page:**
https://docs.godotengine.org/en/stable/tutorials/plugins/gdnative/gdnative-c-example.html

**Comment by Calinou** [comment]
This is fixed in the [`latest` version of the documentation already](https://docs.godotengine.org/en/latest/tutorials/scripting/gdnative/gdnative_c_example.html). It needs to be backported to the `stable` branch.

**Comment by skyace65** [comment]
@Calinou you can close this issue
