### ISSUE TITLE
NinePatchRect scales center and sides, not tiles

### ISSUE THREAD

**Issue by osmiumforge** [godotengine/godot-docs#4333]
**Your Godot version:**
3.2

**Issue description:**
On the docs, and also the description of the node itself, a NinePatchRect "*tiles the texture's centers and sides*". NinePatchRect actually stretches the center and sides, and a tiling option is currently unavailable

**URL to the documentation page:**
[https://docs.godotengine.org/en/stable/classes/class_ninepatchrect.html#enum-ninepatchrect-axisstretchmode](https://docs.godotengine.org/en/stable/classes/class_ninepatchrect.html#enum-ninepatchrect-axisstretchmode)

**Comment by Calinou** [comment]
> and a tiling option is currently unavailable

Have you tried the Tile and Tile Fit modes? I believe the latter only works when using GLES3 though.

**Comment by osmiumforge** [comment]
Neither exist on GLES2, which I am using
