### ISSUE TITLE
List all the methods and properties that class has access to in class description including those of ancestors on single page.

### ISSUE THREAD

**Issue by Feniks-Gaming** [godotengine/godot-docs#4341]
**Your Godot version:**
Latest stable 3.2.3

**Issue description:**

One of the biggest issue of working with Godot docs class references for me is a need to jumpi to every ancestor of a class to figure out what methods and properties class has access to. 

Lets take **[OptionButton](https://docs.godotengine.org/en/stable/classes/class_optionbutton.html#class-optionbutton)**  as example. 

Say. I would like this button to expand when I put text in it. Just by looking at it's limted docs I can't do it. I need to back up to it's ancestor and open another page for **[Button](https://docs.godotengine.org/en/stable/classes/class_button.html#class-button)** to find `expand_icon`.  

Then I also want to toggle it when pressed so I need to open another page for **[BaseButton](https://docs.godotengine.org/en/stable/classes/class_basebutton.html#class-basebutton) to find `toggle_mode`**. 

Then I want to figure out why it's doing some crazy resizing shaningas so I need to open yet another page for **[Control](https://docs.godotengine.org/en/stable/classes/class_control.html#class-control)**  

Finally I need to open **[Node](https://docs.godotengine.org/en/stable/classes/class_node.html#class-node)** for something else. 

As a result, I am now jumping between 5 different tabs, it gets even more difficult to navigate if I want to access those docs from within editor. 

It would be more convenient if we has all the available methods in one place on each entry. They could be separated into 2 sections `class_methods` and `ancestor_classes_methods` this would give us better overview of what class can truly do without needing to open multiple tabs. We could even make `ancestor_classes_methods` collapsible so user can fold them if they don't want to read them. But it makes everything easier to grasp on one screen than needing to check 5 or 6 different classes to see if something is possible somewhere up the inheritance chain. 

**URL to the documentation page (if already existing):**

https://docs.godotengine.org/en/stable/classes/class_optionbutton.html#class-optionbutton one of many examples but applies to whole documentation.

**Comment by Calinou** [comment]
Even if you collapse inherited methods/properties by default, including them in the generated page would make the HTML very large. This would make it slow to render and make offline copies of the documentation much larger.
