### ISSUE TITLE
int(x) is not equal to floor(x) for negative values

### ISSUE THREAD

**Issue by AlexTheRegent** [godotengine/godot-docs#4358]
**Your Godot version:** 
3.2.3 stable

**Issue description:** 
In documentation it is said that `floor` method returns float and "If you need an integer, you can use int(s) directly". This note (or at least cited part) should be removed because this statement is incorrect for negative values in `floor` method. Casting to an int will truncate value toward zero, and `floor` downward value towards negative infinity.

Test code: 
```
	if int(-3.4) == floor(-3.4):
		print("int(-3.4) == floor(-3.4)")
	else:
		print("int(-3.4) != floor(-3.4)")
```

Output:
`int(-3.4) != floor(-3.4)`

**URL to the documentation page:** 
https://docs.godotengine.org/en/stable/classes/class_@gdscript.html#class-gdscript-method-floor

**Comment by Feniks-Gaming** [comment]
@Calinou can we close it as we are apparently getting floori() that will return int so there is no much point in redoing it.

**Comment by Calinou** [comment]
@Feniks-Gaming I've actually heard otherwise, and having a `floori()` function that returns an act might actually be added.

**Comment by Mickeon** [comment]
Indeed it has and it's been documented appropriately. What to make of this PR?

**Comment by Calinou** [comment]
@Mickeon Sounds good, I guess this can be closed then.
