### ISSUE TITLE
https://docs.godotengine.org/en/stable/tutorials/inputs/input_examples.html

### ISSUE THREAD

**Issue by cjpdev** [godotengine/godot-docs#4359]
Godot version: 3.2.3 Stable and Latest

Issue description:
The  C# Mouse (wheel) button example has a small error.  The if condition uses `as` but it should be `is`. 

Exampe code:

```
public override void _Input(InputEvent inputEvent)
{
    if (inputEvent as InputEventMouseButton mouseEvent && mouseEvent.Pressed)
    {
        switch ((ButtonList)mouseEvent.ButtonIndex)
        {
            case ButtonList.Left:
                GD.Print("Left button was clicked at ", {mouseEvent.Position});
                break;
            case ButtonList.WheelUp:
                GD.Print("Wheel up");
                break;
        }
    }
}
```

URL to the documentation page:
https://docs.godotengine.org/en/latest/tutorials/inputs/input_examples.html
https://docs.godotengine.org/en/stable/tutorials/inputs/input_examples.html

**Comment by skyace65** [comment]
@Calinou this issue can be closed since the PR was merged.
