### ISSUE TITLE
Screenshots is older than the stable version ( animation & singletons autoload )

### ISSUE THREAD

**Issue by mrwanashraf** [godotengine/godot-docs#436]
in [doc (animation)](http://docs.godotengine.org/en/stable/learning/step_by_step/animations.html) & [doc (singletons autoload)](http://docs.godotengine.org/en/stable/learning/step_by_step/singletons_autoload.html) the screenshots of godot interface is older than the stable version interface which makes it more difficult for someone to follow the example.

**Comment by mhilbrunner** [comment]
Will be the case for a lot of old docs page. Opened a broader issue to track and fix these outdated places:
https://github.com/godotengine/godot-docs/issues/946
