### ISSUE TITLE
Clarify that String.rstrip (and lstrip) takes a list of characters rather than a pattern

### ISSUE THREAD

**Issue by bonbonmiel** [godotengine/godot-docs#4365]
**Your Godot version:** 3.2.3.stable

**Issue description:**
The fact that `rstrip` takes a list of characters and not a pattern is not clear.
![image](https://user-images.githubusercontent.com/71937306/99126846-3f168880-2607-11eb-8e9b-5c71a4d38ab3.png)

So it can't be used for example to strip a file extension: `"abc.tscn".rstrip(".tscn")`. I thought it was a bug.
I think the docs should mention:
 - explicitely the fact that `lrstrip` don't take a pattern but a string of eligible characters,
 - that one should use `trim_prefix` and `trim_suffix` to remove a pattern.

**URL to the documentation page (if already existing):**
https://docs.godotengine.org/en/stable/classes/class_string.html#class-string-method-rstrip
https://docs.godotengine.org/en/stable/classes/class_string.html#class-string-method-lstrip

**Comment by Calinou** [comment]
What do you mean by "pattern"? In the source code, neither `trim_prefix` nor `lstrip` use a glob matching function.

**Comment by bonbonmiel** [comment]
@Calinou a substring actually.
 - `"babaabba".rstrip("ab")` -> `""`
 - `"babaabba".trim_suffix("abba")` -> `"baba"`

**Comment by Xrayez** [comment]
Those should be documented as a set of delimiters encoded within a parameter string used to strip the original string, I've stumbled upon similar confusion in godotengine/godot#45048, and likely worth to cross-reference `strip_edges()` and `trim_suffix()`.
