### ISSUE TITLE
State design pattern tutorial missing from repo?

### ISSUE THREAD

**Issue by MSGoodman** [godotengine/godot-docs#4371]
**Your Godot version:**
v3.2.3

**Issue description:**
I noticed a minor grammatical error while reading the [state design pattern tutorial](https://docs.godotengine.org/en/stable/tutorials/misc/state_design_pattern.html) and thought I could make a quick PR to fix it, but it doesn't appear to be in this repo at all? Perhaps I'm looking in the wrong place, but searching the entire project for "state design pattern" returned nothing for me.

**URL to the documentation page:**
https://docs.godotengine.org/en/stable/tutorials/misc/state_design_pattern.html

**Comment by pycbouh** [comment]
`stable` docs are in `stable` branch, `master` branch is available as `latest` docs: https://docs.godotengine.org/en/latest/tutorials/misc/state_design_pattern.html

The page is indeed no longer there in master. It was either removed or moved. In case it was moved, you should edit it at its new location. If it was removed, you can probably make a PR against `3.2` or `stable` branch.

**Comment by MSGoodman** [comment]
Thank you for the incredibly fast reply! And thank you for the information on the distinction between `stable` and `master`/`latest`. I'd be happy to consider this a closed issue then, and I'll make a PR against `3.2`.
