### ISSUE TITLE
Reduce or rephrase comparisons between GDScript and Python

### ISSUE THREAD

**Issue by pycbouh** [godotengine/godot-docs#4378]
*(Sorry for not following the template, it's more of a meta issue)*

There is a striking number of people believing that GDScript is very much related to Python in many of its aspects. This is a misconception that is very often used as an argument when suggesting improvements to GDScript or just general questions about it. While languages do share syntactic similarities, they are very different in practice.

Docs help fuel this confusion, as the language is introduced several times as "similar to Python" or even "based on Python" (paraphrasing, [[1]](https://docs.godotengine.org/en/stable/getting_started/scripting/gdscript/gdscript_basics.html), [[2]](https://docs.godotengine.org/en/stable/about/list_of_features.html#scripting), [[3]](https://docs.godotengine.org/en/stable/about/faq.html#what-were-the-motivations-behind-creating-gdscript), [[4]](https://docs.godotengine.org/en/stable/getting_started/step_by_step/godot_design_philosophy.html#all-inclusive-package)). This needs to be addressed either by reducing the number of such mentions or by rephrasing them as clear as possible. I understand that the intention is probably to give a point of reference for less experienced in programming, but it also invites people more experienced or more confident in it to make unnecessary connections between the languages.

Our Discord server, for one, is full of misguided people asking about those similarities daily, criticizing the language in a vein with "Well, Python can do it, why can't GDScript". Proposals about GDScript 2.0 changes are also a great source of such misconceptions, and vnen has to repeat himself a lot that these are very different languages. So I think we need to put some distance.

**Comment by Xananax** [comment]
Indeed this is a daily occurrence. Additionally, people who have only a passing understanding of Godot tell other people in generic gamedev channels that "Godot uses Python".

I propose to say something like "originally inspired by Python, GDScript differs..." (regardless of actual history) or to "despite resemblance with Python..."

**Comment by Feniks-Gaming** [comment]
I agree with it also it's useless because if you don't know ow python then "just like python feature A" is giving you zero information. Documentation should stand on it's own.
