### ISSUE TITLE
Add detailed information about the PR review workflow

### ISSUE THREAD

**Issue by gvekan** [godotengine/godot-docs#4379]
**Your Godot version:**
stable
**Issue description:**
As someone who started contributing to the Godot project a couple of months ago I have no idea how the workflow of getting my PR reviewed and merged, works. Almost all of my PRs are stuck, waiting on the reviewer to review.  One has no reviewer at the moment.
All I've found is this unofficial information:
https://www.reddit.com/r/godot/comments/cwj46p/why_is_there_so_many_pulled_request_waiting_for/
I'm suggesting that someone that knows could extend either _Pull request workflow_ or _Bug triage guidelines_ with the following information about the review workflow:

- How you get a reviewer.
- In what time frame can you expect to get feedback either about the code or if it's undesired i.e doesn't solve a problem, unnecessary, solves simple problem, occurs rarely etc.
- How the workflow is for the reviewer, if it is like the reddit post, what order the PRs are looked at etc.
- What you could do if your PR doesn't get a reviewer or doesn't get feedback.

**URL to the documentation page (if already existing):**
https://docs.godotengine.org/en/stable/community/contributing/pr_workflow.html
or
https://docs.godotengine.org/en/stable/community/contributing/bug_triage_guidelines.html

**Comment by pycbouh** [comment]
That's a pretty outdated reddit thread. Currently the engine is going through some major changes and as such a lot of PRs are backing up. There is no process for assigning reviewers, they either track down related issues themselves or are appointed by someone other maintainer based on their area of expertise.

To make sure your PR is required and welcome, start with a proposal or a bug. New features should be reviewed as a concept before you spend time working on them. Bugfixes require documented ways to reproduce them and making sure it is actually a bug. I think that just as much is stated in the [best practices for contributors article](https://docs.godotengine.org/en/stable/community/contributing/best_practices_for_engine_contributors.html).

**Comment by gvekan** [comment]
@pycbouh I see, there's no defined process.
Just to clarify:

- Getting a reviewer for your PR is based on the luck that a reviewer finds it? 

- There is no limit on how long time it takes before the feedback comes, mostly because the major changes?

Now I wonder:
- Is there any chance that a PR never gets feedback and is left or does the reviewers try to look at all?
- Is all you can do as a contributor just wait, would it be inappropriate to remind the reviewer because of the staggering amount of PRs?

**Comment by Calinou** [comment]
> Now I wonder:

- Is there any chance that a PR never gets feedback and is left or does the reviewers try to look at all?

Unfortunately, there's a non-zero chance that this can happen. This can happen in any open source project, large or small. It's not exclusive to Godot in my experience.

> Is all you can do as a contributor just wait, would it be inappropriate to remind the reviewer because of the staggering amount of PRs?

Feel free to join the `#godotengine-devel` IRC channel on freenode and ask for your PR to be reviewed there.
