### ISSUE TITLE
404 when clicking on "Edit on GitHub" link

### ISSUE THREAD

**Issue by AaronRecord** [godotengine/godot-docs#4381]
**Your Godot version:**
(don't think it's relevant but it's 3.2.3.official.stable)
**Issue description:**
Clicking on the "Edit on GitHub" button gives a 404
button links to:
[https://github.com/godotengine/godot-docs/blob/master/tutorials/optimization/cpu_optimization.rst](https://github.com/godotengine/godot-docs/blob/master/tutorials/optimization/cpu_optimization.rst)
**URL to the documentation page:**
[https://docs.godotengine.org/en/stable/tutorials/optimization/cpu_optimization.html](https://docs.godotengine.org/en/stable/tutorials/optimization/cpu_optimization.html)

**Comment by Calinou** [comment]
This is because that particular page only exists on the `stable` (`3.2` on GitHub) branch, not `latest` (`master` on GitHub).

**Comment by skyace65** [comment]
Closing per Calnou's comment
