### ISSUE TITLE
Clarify Array.find() not using type casting as expected

### ISSUE THREAD

**Issue by 1shevelov** [godotengine/godot-docs#4404]
**Your Godot version:**
3.2.3.stable.official

**Issue description:**
As an unsophisticated Godot user I expect this method to make automatic type casting when comparing argument to array values. Direct comparisons like int(1) == float(1) and String(1) == int(1) yield TRUE and I expect the find() method to work the same.

I suggest to add a note to this method's description that it does not make type casting and user should check the type of the argument and members of the array.
If there are other functions that do not use type casting I suggest to explain it too.

**URL to the documentation page (if already existing):**
https://docs.godotengine.org/en/stable/classes/class_array.html#class-array-method-find

**Discussion:**
https://godotforums.org/discussion/24680/1-1-0-in-array-find

_P.S. Really, I would prefer the modification of Array.find() to make it work consistently with Godot rules as a dynamically typed language, as I understand them, and use type casting. But I do not have the expertise to evaluate this proposal._

**Comment by Calinou** [comment]
> Direct comparisons like int(1) == float(1) and String(1) == int(1) yield TRUE and I expect the find() method to work the same.

GDScript is strongly-typed, not weakly typed. This shouldn't be the case…

**Comment by 1shevelov** [comment]
@Calinou, it's confusing because by Array.find() method description I derive that it works like this:

> func find(arr: Array, argument) -> bool:
>     for a in arr:
>         if a ==argument:
>             return true
> return false

and of course I assume that comparison uses standard GDScript rules with transparent type casting...

So a note in method's docs would be nice... Especially that console does not give hints for values types and it can be very confusing like in this example:

> var arr: Array = []
> for i in 3:
>     arr.append(float(i))
> print(arr)
> print(arr.find(1))

where output is:

> [0, 1, 2]
> -1

(Searching for 1 and not getting it while print shows that it's present in array. [A good explanation here](https://godotforums.org/discussion/comment/43819/#Comment_43819).)

Now that I understand how it works I can make my own function or check values types. The problem is in novice users experience only.

I'll close the issue because nobody supports it. But I'm still sure in it
