### ISSUE TITLE
Keyword lookup missing in offline documentation

### ISSUE THREAD

**Issue by Haledire** [godotengine/godot-docs#4405]
**Your Godot version:**
3.2.3
**Issue description:**
Searching for Keywords directly is oddly difficult due to the structure of the page which lists them (GDScript Basics)

In Example:  Search the word `match` in the in-engine docs and you get `String.match()` and no reference to the `match` keyword.
The list of keywords is oddly hidden in what appears more as a tutorial page vs a documented listing of all the keywords / operators such as a page like `@Globalscope`.  Perhaps an `@Keywords` page that references gdscript_basics would be more search friendly?  The format of the basics page seems more like someone mashed a tutorial and formal documentation together.

Granted, I realize these aren't exactly Properties or Methods which would usually come up in search.  It'd be similar to `@Globalscope`'s enum list not showing up.  Searching the website the first time oddly didn't bring it up immediately (my internet having some sort of hiccup perhaps), but it's odd this listing isn't available in the engine docs anywhere as it's a tutorial page essentially.

Another example - `export` > it's a tutorial page.  It doesn't exist in the offline docs.  There's not even a link to it when you search for it.

If this is just a concern of redundancy feel free to close.  Just felt I should voice my concern about it. 

**URL to the documentation page (if already existing):**
https://docs.godotengine.org/en/stable/getting_started/scripting/gdscript/gdscript_basics.html

**Comment by Calinou** [comment]
GDScript keywords are not classes, and are therefore not present in the *class* reference.

> Another example - export > it's a tutorial page. It doesn't exist in the offline docs. There's not even a link to it when you search for it.

The offline class reference only aims to contain the class reference, not manual pages.
