### ISSUE TITLE
FPS Tutorial MacOS Xbox360 Controller

### ISSUE THREAD

**Issue by rsin46** [godotengine/godot-docs#4412]
Using Godot version 3.2, docs https://github.com/godotengine/godot-docs/blob/3.2/tutorials/3d/fps_tutorial/part_four.rst

The correct axes for MacOS with an Xbox 360 controller is as follows:
Walking:
`		elif OS.get_name() == "OSX":
			joypad_vec = Vector2(Input.get_joy_axis(0, 0), -Input.get_joy_axis(0, 1))`
Rotation:
`		elif OS.get_name() == "OSX":
			joypad_vec = Vector2(Input.get_joy_axis(0, 2), Input.get_joy_axis(0, 3))`

Tested on MacOS 10.15.7 Catalina.

**Comment by Calinou** [comment]
The tutorial should really have used actions instead of hardcoded axes…

Either way, the FPS tutorial was removed from the `master` branch as the documentation is moving towards being a reference manual: https://github.com/godotengine/godot-docs/issues/3390

**Comment by rsin46** [comment]
Yes makes sense, hopefully this tutorial can remain in another repo as it has been really informative for a beginner.
