### ISSUE TITLE
Curve3D offsets are reported in pixels when in fact they are in meters

### ISSUE THREAD

**Issue by siorys88** [godotengine/godot-docs#4416]
This part of the Curve3D documentation is wrong, probably carried over from Curve2D:
```

-  Vector3 interpolate_baked ( float offset, bool cubic=false ) const

Returns a point within the curve at position offset, where offset is measured as a pixel distance along the curve.
```
The offset value is in meters/editor units, not in pixels. The method get_closest_offset also returns values in meters/editor units, not in pixels.

**Comment by Calinou** [comment]
See also #4339.
