### ISSUE TITLE
Document how to use the class reference

### ISSUE THREAD

**Issue by akien-mga** [godotengine/godot-docs#4425]
**Your Godot version:**
3.2 / master

**Issue description:**
Many users don't necessarily have experience with reading API documentation or with object-oriented programming (and thus the fact that methods for a given Node might actually be defined in one of the classes it inherits from).

We should have an introduction page that goes over how to use the class reference (in editor and/or online, it's the same, but it can give editor-specific tips too like Ctrl+Click on names to go to their documentation).

This Reddit post has a good start to introduce some of the relevant concepts: https://www.reddit.com/r/godot/comments/k65j0k/str_vs_string/gej2ecq/?utm_source=reddit&utm_medium=web2x&context=3

This could likely go in the Introduction section of Getting started: https://docs.godotengine.org/en/latest/getting_started/introduction/index.html

**Comment by skyace65** [comment]
This was fixed by #4251.
