### ISSUE TITLE
HTTP.Request fails when exporting to Android

### ISSUE THREAD

**Issue by cshiffl** [godotengine/godot-docs#4428]
**Your Godot version:**
v3.2.3.stable.official
**Issue description:**
My GoDot application works when running in Windows; however, when I export to Android, the application breaks with an error stating "**ERROR**: getaddrinfo failed! Cannot resolve hostname.    At: drivers/unix/ip_unix.cpp:112:_resolve_hostname() - getaddrinfo failed! Cannot resolve hostname." 

Additional Info - 
URL that fails - https://www.googleapis.com/identitytoolkit/v3/relyingparty/verifyPassword?key=%s" % API_KEY   (Where API_KEY is my Firebase API Key)

**URL to the documentation page:**
https://docs.godotengine.org/en/stable/classes/class_httprequest.html#class-httprequest

**Comment by cshiffl** [comment]
Meant to put under engine and not docs. Closing and reopening under engine

**Comment by Calinou** [comment]
Superseded by https://github.com/godotengine/godot/issues/44097.
