### ISSUE TITLE
Write a new Getting Started guide for 3.0

### ISSUE THREAD

**Issue by NathanLovato** [godotengine/godot-docs#444]
Following the [3.0 docs meeting notes](https://docs.google.com/document/d/15_UsNhjm34iew3WZMktlWe1bs_h82EDQzgKbEIHwLkk/edit?usp=sharing), we're working on a completely new getting started guide with Chris Bradfield, from [kidscancode](https://www.youtube.com/channel/UCNaPQ5uLX5iIEHUCLmfAgKg), for 3.0.

It targets 2 groups of people:

1. Beginners, people who have never made games before
2. Developers and students, people with programming experience, and/or coming from other engines

We're using a [Trello board](https://trello.com/b/BxdbFCzL/godot-30-docs) to organize our work as it's iterative in nature. We'll likely produce new demos along the way.

**If you have teaching or writing experience, a good level of English, and want to join forces to produce extra tutorials, please get in touch! [@NathanGDquest](https://twitter.com/NathanGDquest) and [@kidscancode](https://twitter.com/KidsCanCode)**

Planned articles (the list isn't final):

- [x] Replacement game creation series for pong
    - [x] Add Visual Scripting version
- [x] Intro to the editor's UI (#997)
- [x] Overview of the physics bodies
- [x] GDscript styleguide
- [x] Revised vector math guide
- [x] Overview of the anim tools
- [ ] How to animate characters
- [x] User Interface Design
- [x] User Interface Step-by-Step tutorial
- [ ] The new particle system
- [ ] Visual Scripting intro
- [ ] Shader intro

**Comment by GuiltyPixel** [comment]
Oi, thanks for this. I will withdraw my PR. I was coming to this conclusion regarding a rewrite myself and I was going to ask before proceeding to update content. I do have teaching experience and recently updated my knowledge on the subject. Count me in.

**Comment by cbscribe** [comment]
Added a couple of items to the checklist.

**Comment by potato20** [comment]
Any update on this? really looking forward to it.

**Comment by NathanLovato** [comment]
@potato20 It's mostly done now. We're releasing a collab series on shaders with Baastian Olij today, but in video format. Aside from that we should wait for 3.1 to cover anything related to animation as the system got an overhaul, and for particles I think a video would be a lot more efficient than a text-based tutorial as it's all visual in nature. I'm working on a series for my Godot course, could release the intro tutorials for free.

**Comment by potato20** [comment]
Awesome, great news.

IMO, video-based is great, but hopefully the full source code can be put up somewhere? i love text-based tutorials for their convenience i.e. copy-paste.

**Comment by cbscribe** [comment]
Closing this as it was absorbed into #946 and we'll be starting up a 3.1 tracker soon
