### ISSUE TITLE
is_equal_approx() description just repeads method name without explaining what approximation actually means

### ISSUE THREAD

**Issue by golddotasksquestions** [godotengine/godot-docs#4452]
**Your Godot version:** 3.2.3 stable, latest

**Issue description:**
These methods look like something I would want to use to compare floating point positions for instance, but without knowing what kind of approximation this is, I can't tell what those really methods do.

So both the GDScript method and the Vector2 method needs a better description defining "approximately"

**URL to the documentation page (if already existing):**
https://docs.godotengine.org/en/stable/classes/class_@gdscript.html#class-gdscript-method-is-equal-approx
https://docs.godotengine.org/en/stable/classes/class_vector2.html#class-vector2-method-is-equal-approx

**Comment by aaronfranke** [comment]
Do you have a suggestion of what to put? Ideally we don't need users to care about the fine details of how it works under the hood, but I agree that we could give some more information and direct more users to it. Maybe add "using an epsilon value"?

**Comment by golddotasksquestions** [comment]
I don't care so much about what is under the hood if the documentation does a decent job to explain what a method does. But here it just repeats the method name, giving no explanation at all what "approximately" means. 

I also don't have a suggestion because my source code reading skills really suck terribly, and I did not went through the ordeal to painfully trail and error this one until I figure it out.

**Comment by KoBeWi** [comment]
Maybe instead of explaining approximation, the description should just specify usage?

**Comment by golddotasksquestions** [comment]
Hm, well explaining usage is always welcome in documentation, but in this specific case explaining what kind of approximation this is, is clearly necessary, as it is THE central thing this method does.

Basic example:
Does approximation mean the values are rounded before comparison? If so to what decimal point?

What's the point of this method if I can't tell what it does with my values.

**Comment by dt192** [comment]
It appears to be within 0.001%

**Comment by zacryol** [comment]
This seems to have been taken care of.

> Here, approximately equal means that `a` and `b` are within a small internal epsilon of each other, which scales with the magnitude of the numbers.

https://docs.godotengine.org/en/stable/classes/class_@gdscript.html#class-gdscript-method-is-equal-approx

**Comment by KoBeWi** [comment]
Closing per above comment.
