### ISSUE TITLE
iPhone project export error when trying to open exported proj

### ISSUE THREAD

**Issue by pixelmad** [godotengine/godot-docs#4453]
3.2.3

export iPhone proj from material testers demo - no changes

Xcode 11.6 opening error:
The project ‘Material Testers’ is damaged and cannot be opened due to a parse error. Examine the project file for invalid edits or unresolved source control conflicts.

**Comment by pixelmad** [comment]
[Material Testers.xcodeproj.zip](https://github.com/godotengine/godot-docs/files/5683602/Material.Testers.xcodeproj.zip)

added Xcode proj file

**Comment by Calinou** [comment]
Please don't ask support questions here, as this issue tracker is meant to be used for bug reports only. Use one of the other [community channels](https://godotengine.org/community) instead.

**Comment by pixelmad** [comment]
why isn't this a bug report? its incorrect ???

**Comment by pixelmad** [comment]
its really not at all clear what the functionality of a community channel might be? or where to put something like this?
it would seem this is the place for this!!

**Comment by Calinou** [comment]
> it would seem this is the place for this!!

No, this repository is meant to host issues pertaining the documentation (such as incorrect or missing information), not the engine itself or trouble you may be having with a specific export platform.
