### ISSUE TITLE
call_group documentation does not explain limited amount of arguments

### ISSUE THREAD

**Issue by kuroodo** [godotengine/godot-docs#4460]
**Your Godot version:**
3.2.3

**Issue description:**
In the documentation for the call_group method, when hovering over the "vararg" text it states: "this method accepts any number of arguments after the ones described here". But in fact there is a limit of exactly 5 arguments as described in this issue which was closed: https://github.com/godotengine/godot/issues/39830 therefore I assume this is not a source-code bug.
I believe this is the file the user was referring to: https://github.com/godotengine/godot/blob/3.2/core/object.h

**The documentation implies that you can set any number of arguments, when in fact you can only set a maximum of 5.**

**URL to the documentation page:**
https://docs.godotengine.org/en/stable/classes/class_scenetree.html?#class-scenetree-method-call-group

**Comment by akien-mga** [comment]
Fixed by https://github.com/godotengine/godot/pull/44385
