### ISSUE TITLE
Algolia search implementation

### ISSUE THREAD

**Issue by leroy** [godotengine/godot-docs#4461]
Algolia is a search engine with offers a free service for opensource projects.

https://www.algolia.com/for-open-source/

Algolia would greatly improve the UX on the docs.

Example of a readthedocs implementation:
https://github.com/readthedocs/sphinx_rtd_theme/issues/761

I would love to create a PR if the maintainers are open to this.

Some credentials would have to be requesters by the maintainers.

**Comment by Calinou** [comment]
Keep in mind we use an "instant search" plugin that makes a search modal pop up when you click the search field. The Algolia implementation should probably remove this instant search plugin.

**Comment by leroy** [comment]
@Calinou Let me know if i can help out in any way. Would love to create a PR.

See:
https://tailwindcss.com/

For an example implementation of the search

**Comment by leroy** [comment]
I went ahead and started building a prototype.

![image](https://user-images.githubusercontent.com/3531171/108485527-4ea80c00-729d-11eb-847b-1d553347dc34.png)

I also applied for the public crawling program to be able to build a demo with real data. Will follow up with a PR soon!

**Comment by leroy** [comment]
@Calinou i applied for the DocSearch project of Algolia.

I just received an e-mail confirming the setup is complete on their end.

See:

https://github.com/algolia/docsearch-configs/blob/master/configs/godotengine.json

**Comment by LikeLakers2** [comment]
I'm not a Godot team member, so I'm not sure how much weight my words would carry, but I'm not entirely sure I see the need for an AI-powered search? While using the docs search function isn't always great (it seems it tends towards non-class-ref pages before class ref pages), I think it gets the job done. I'm not sure why we'd want to fix what (in my eyes, at least) isn't broken.

**Comment by Calinou** [comment]
> Mind you, I'm not against it. I just wanted to voice that I'm not sure I understand why we'd want it.

The current search results are pretty bad when you use short search terms such as "input", and I'm confident that using Algolia could deliver better search results.

However, Algolia is proprietary SaaS we don't control, and this was a reason Akien isn't especially favorable to using it.

**Comment by leroy** [comment]
> Mind you, I'm not _against_ it. I just wanted to voice that I'm not sure I understand why we'd want it.

My number one reason is the current UX of the search and the responsiveness of the search results. I'm all up for finding a better solution for that instead of using "Algolia's AI powered search".

**Comment by Calinou** [comment]
@leroy After some discussion, we decided that it'd be a good idea to try out Algolia on the `/latest` branch. If it turns out to work well, we can then deploy it to other versions.

However, [godotengine.json](https://github.com/algolia/docsearch-configs/blob/master/configs/godotengine.json) is configured to index the `/stable` branch. Should I open a pull request to index the `/latest` branch there instead?

**Comment by leroy** [comment]
@Calinou Wooo! That's great news! Very cool to hear you guys are open to the concept. I think that's a proper way to request the change. I'll make sure to send the Algolia team an e-mail aswell.

I think if you decide to go ahead with using Algolia we can look into getting a Algolia indexer to run on push through Github Actions instead of the opensource one. But that's for another time.

**Comment by Calinou** [comment]
@leroy I updated the indexing in https://github.com/algolia/docsearch-configs/pull/3977. Could you open a pull request against this repository with the required changes to add Algolia? Thanks in advance :slightly_smiling_face:

**Comment by mhilbrunner** [comment]
We've since implemented Algolia search (see above PR) and also disabled it again as we weren't satisfied. Stumbled upon this issue as I was spelunking in search stuff. RTD's new Beta search may be worth a try. Anyway, going to close this issue now :)
