### ISSUE TITLE
No basic information on how to feed BitmapFont

### ISSUE THREAD

**Issue by red1939** [godotengine/godot-docs#4467]
**Your Godot version:**
3.2.3.stable.official

**Issue description:**
There is no notice in the documentation what are the restrictions on the data produced by BMFont. Inside of the code, there is no validation whether the format is correct (like `BMF` which is present in the binary header). It's assumed that the format is text. Why not binary?

Additionally, it seems that the code needs 32-bit channel texture. Why?

There is a setting for using distance fields. This option is not present when exporting from BMFont, so one starts to question when it should be turned on. And if yes, then should the user assume that 8-bits on one channel represents a normalized signed float?

**URL to the documentation page (if already existing):**
https://docs.godotengine.org/en/stable/classes/class_bitmapfont.html#bitmapfont

**Comment by Calinou** [comment]
> There is a setting for using distance fields. This option is not present when exporting from BMFont, so one starts to question when it should be turned on. And if yes, then should the user assume that 8-bits on one channel represents a normalized signed float?

Distance field fonts are currently reported as broken: https://github.com/godotengine/godot/issues/8022

**Comment by red1939** [comment]
@Calinou I know. I've seen commented out code in the TextServer. But, as we are in the repo of documentation, I ignore the fact that it doesn't work as we are marching towards 4.0. I just want to know what is the vision that will be - one day - realized by Godot.

**Comment by Calinou** [comment]
> I just want to know what is the vision that will be - one day - realized by Godot.

We don't have a goal to bring back SDF font support for 4.0. It may happen if a contributor implements it, but it's not a blocker for 4.0's release.
