### ISSUE TITLE
Small question, are timer values tracked stored as a floating point?

### ISSUE THREAD

**Issue by GhbSmwc** [godotengine/godot-docs#4469]
Reading this info: https://docs.godotengine.org/en/stable/classes/class_timer.html , it stated that ``wait_time`` is a floating point representing the amount of seconds.
Is the timer:
- a number handled internally by decrementing that value by a fractional amount (made-up example is a game is set to 100 fps, so it is subtracting it by 0.01), or;
- as an integer or “fixed-point” number representing the “frames” between each seconds? This is a little worrying as because how floating point numbers work, they:

 - - Cannot represent repeating digits. If a given number, in reduced fraction form, whose denominator's prime factors contain at least 1 number not being 2, will be rounded (if all prime factors are 2, then it should terminate, unless more than 24 bits are needed).

 - - Lose precision with large numbers. The further away from zero, the bigger the spacing between the closest representable numbers. With enough arithmetic operations, precision loss will accrue.

**Comment by Calinou** [comment]
Timer values are currently stored as `float`s, but there's a pull request to make them use `double`s: https://github.com/godotengine/godot/pull/38880

**Comment by GhbSmwc** [comment]
Interesting, however, do they change “continuously”; Meaning that every frame (or step, minecraft calls them “ticks”), they increment/decrement by a fractional amount:
![image](https://user-images.githubusercontent.com/13095760/102677143-feaeab00-416e-11eb-8ded-d26b41ce8db4.png)

or do they increment by whole numbers staying the same number in between intervals?:
![image](https://user-images.githubusercontent.com/13095760/102677255-83012e00-416f-11eb-89af-836ee3a359e8.png)

**Comment by Calinou** [comment]
> Made up example: from real-world 0 seconds to 1, the value is incremented by a fractional amount in between real world 0 → 1 seconds

Indeed, Timers are incremented by a fractional amount.

**Comment by GhbSmwc** [comment]
Interesting. This also means they'll drift apart from their real values. Can the user simply uses an integer that measures how many frames as an alternative? This will be good timers displayed as MM:SS:cc (minutes:seconds:centiseconds).

**Comment by Calinou** [comment]
> Can the user simply uses an integer that measures how many frames as an alternative?

Sure, increment a variable in `_process(delta)` or `_physics_process(delta)` or use `Engine.get_idle_frames()`/`Engine.get_physics_frames()`.

That said, doing so is FPS-dependent by nature, and is therefore not recommended.

**Comment by GhbSmwc** [comment]
Then let's do it in “physics frame” rather than “display frames” (or rendering). If redstone timers ([displays using restone lamps](https://www.youtube.com/watch?v=Fyjgmr0WX9U)) in minecraft uses game ticks or redstone ticks (which is 2 game ticks), they're using what is happening in the game rather than the framerate rendering.

This is also useful should the developer offer the option for players to have the game be 30 or 60fps, without affecting the timer rate since they're separate. After all, movement is physics, and movement have to do with time, else it isn't movement.

**Comment by GhbSmwc** [comment]
> That said, doing so is FPS-dependent by nature, and is therefore not recommended.

Also, in general, is recommended that if anything happens in the game besides graphics/rendering, to have code handled under physics processes (like when you spawn in a level, sets your XY position)? Hopefully having most things in the physics side won't break.

**Comment by Calinou** [comment]
> Also, in general, is recommended that if anything happens in the game besides graphics/rendering, to have code handled under physics processes (like when you spawn in a level, sets your XY position)? Hopefully having most things in the physics side won't break.

No, that should be done in dedicated functions or just in `_ready()`.

**Comment by GhbSmwc** [comment]
Oh, I see (I was wrong), so setting the XY pos is a 1-time thing, while continuous things like a timer, sprite movement, etc. is handled under the physics process.

**Comment by aaronfranke** [comment]
@GhbSmwc Yes, timers stop working after a few days due to this. See this bug report: https://github.com/godotengine/godot/issues/38878

I opened this PR to hopefully fix the problem (pending review): https://github.com/godotengine/godot/pull/38880

**Comment by GhbSmwc** [comment]
Also, physics's frames and render frames, besides the timer that counts downwards. How does godot make sure when the next frame should be processed so that it doesn't “run too fast” (avoid running the next frame without any delay (e.g. no shorter than 1/60th of a second), contrary of having large loops and lots of sprites processed that would slow down the game)? Does that too also use floating point?

**Comment by Calinou** [comment]
> Also, physics's frames and render frames, besides the timer that counts downwards. How does godot make sure when the next frame should be processed so that it doesn't “run too fast” (avoid running the next frame without any delay (e.g. no shorter than 1/60th of a second), contrary of having large loops and lots of sprites processed that would slow down the game)? Does that too also use floating point?

For the idle step, Godot processes the frame as soon as it can, with a `delta` parameter that represents the time elapsed in seconds in the last frame.

For the physics step, Godot waits until the physics step frequency is reached, then processes a frame, with a `delta` prameter that represents the tile elapsed in seconds in the last frame. This will generally always be `0.016667` by default, unless the physics step is struggling to keep up and is running slowly. In that case, `delta` will be larger.

**Comment by GhbSmwc** [comment]
> For the physics step, Godot waits until the physics step frequency is reached, then processes a frame, with a `delta` prameter that represents the tile elapsed in seconds in the last frame. This will generally always be `0.016667` by default, unless the physics step is struggling to keep up and is running slowly. In that case, `delta` will be larger.

So it waits first, then process the code relating to the physics frame.

When handling that, does it rely on an internal timer that always count upwards and is floating point?

**Comment by Calinou** [comment]
Closing, as the original issue with timers not working after a long duration is resolved. I don't think there is much that can be changed in the Timer documentation, and using frames isn't a viable alternative in most scenarios due to games running at a variable framerate.
