### ISSUE TITLE
Unclear language regarding reuse of Materials for optimization.

### ISSUE THREAD

**Issue by rcorre** [godotengine/godot-docs#4470]
**Your Godot version:**

**Issue description:**
https://docs.godotengine.org/en/latest/tutorials/performance/gpu_optimization.html#reuse-shaders-and-materials says

> If materials can't be reused, at least try to re-use shaders (or StandardMaterial3Ds with different parameters but the same configuration).

I'm unclear what the difference between "parameters" and "configuration" are. Can someone provide an example of materials with "different parameters but the same configuration" vs parameters with different configuration?

**URL to the documentation page:**
https://docs.godotengine.org/en/latest/tutorials/performance/gpu_optimization.html#reuse-shaders-and-materials

**Comment by clayjohn** [comment]
Good question! "configuration" here refers to things that that are enabled or disabled with a checkbox. For example ``heightmap_enabled`` changes the underlying shader. 

"Parameters" are things that can change without enabling or disabling features. ``heightmap_scale`` or ``albedo_color`` for example.

**Comment by Calinou** [comment]
> Good question! "configuration" here refers to things that that are enabled or disabled with a checkbox. For example heightmap_enabled changes the underlying shader.

As far as I know, this is less common in Godot 4.0 since static branching is used more often in StandardMaterial3D.
