### ISSUE TITLE
Reference alternative formatter ClangFormat for CLion

### ISSUE THREAD

**Issue by a-ivanov** [godotengine/godot-docs#4491]
**Your Godot version:**
4

**Issue description:**
CLion has built-in support for `clang-format` formatter (mapped on default formatting shortcut), including `.clang-format` file settings detection and application.
It is described in official docs: https://www.jetbrains.com/help/clion/clangformat-as-alternative-formatter.html#config-files.

Maybe we should reference this in IDE beautifier plugins description?

**URL to the documentation page (if already existing):**
https://docs.godotengine.org/en/stable/community/contributing/code_style_guidelines.html#ide-plugin

**Comment by Calinou** [comment]
> Maybe we should reference this in IDE beautifier plugins description?

Sure, feel free to open a pull request for it :slightly_smiling_face:
