### ISSUE TITLE
Tree order unclear

### ISSUE THREAD

**Issue by CitrusWire** [godotengine/godot-docs#4495]
**Issue description:**
This sentence (under Tree Order) doesn't make any sense to me. I've read it at least 3 times and I'm still not clear what it's trying to say (and English is my native language).

> This means that parents and siblings with a lower rank in the tree order will get notified before the current node.

In a similar vein, while looking at Autoload page, it mentions that you can change the order of the scripts, but not what order the engine reads the scripts in (top to bottom or bottom to top).

> The order of the entries as they are added to the global scene tree can be manipulated using the up/down arrow keys.

**URL to the documentation page (if already existing):**
https://docs.godotengine.org/en/stable/getting_started/step_by_step/scene_tree.html

https://docs.godotengine.org/en/stable/getting_started/step_by_step/singletons_autoload.html

**Comment by Omicron666** [comment]
> **Issue description:**
> This sentence (under Tree Order) doesn't make any sense to me. I've read it at least 3 times and I'm still not clear what it's trying to say (and English is my native language).
> 
> > This means that parents and siblings with a lower rank in the tree order will get notified before the current node.

Isn't image illustration following helpful enough ?
Should it placed before this sentence, and just after first time "tree order" terms is used?

> In a similar vein, while looking at Autoload page, it mentions that you can change the order of the scripts, but not what order the engine reads the scripts in (top to bottom or bottom to top).
> 
> > The order of the entries as they are added to the global scene tree can be manipulated using the up/down arrow keys.

It reads in sequential order from top to down. First entry being added first. Should it be reformulated/explicited?

*I guess anything reducing cognitive complexity in explanation/documentation should/could be used. (like for developping code)*

**Comment by CitrusWire** [comment]
Thanks for the comments.

> Isn't image illustration following helpful enough ?

That's the thing, the image clearly says "nodes are read top down". I don't know what that sentence is saying, but to me at least it doesn't say that.


> It reads in sequential order from top to down. First entry being added first. Should it be reformulated/explicited?

Definitely worth saying explicitly.

> I guess anything reducing cognitive complexity in explanation/documentation should/could be used. (like for developping code)

Very much agree, but more even than that, ordering of things is culture specific (and software domain specific too even within cultures). Even something as "basic" as reading isn't always left-to-right. So spelling out ordering is very important.
