### ISSUE TITLE
"Edit on GitHub" link doesn't work

### ISSUE THREAD

**Issue by Crypton33** [godotengine/godot-docs#4499]
Happens on this documentation page:

https://docs.godotengine.org/en/stable/getting_started/step_by_step/resources.html

When you click on the "edit on github" it redirects to the 404 page

**Comment by Calinou** [comment]
This is because many URLs have changed on the `master`/`latest` branch. We haven't been able to fix this so far with redirects since they apply to all branches at the same time.
