### ISSUE TITLE
Partially unreadable image on the "Resources" page

### ISSUE THREAD

**Issue by Crypton33** [godotengine/godot-docs#4500]
Happens on this documentation page:

https://docs.godotengine.org/en/stable/getting_started/step_by_step/resources.html

The image looks like this on my PC:

![obraz](https://user-images.githubusercontent.com/5208256/103347999-f7559e80-4a98-11eb-8e6b-8c5e02174315.png)

The labels on the right are unreadable and the whole image doesn't look very good.

**Comment by Calinou** [comment]
@Crypton33 Why do you close the issues right after opening them?

**Comment by Crypton33** [comment]
> 
> 
> @Crypton33 Why do you close the issues you've opened right after opening them? They should be left open as long as they're relevant.

I've closed them cause I found out that the "resources" page no longer exists in the latest branch
