### ISSUE TITLE
Unused CenterContainer in Design The GUI tutorial

### ISSUE THREAD

**Issue by Rubonnek** [godotengine/godot-docs#4524]
**Your Godot version:**
3.2

**Issue description:**
A `CenterContainer` is shown in the following image but a `CenterContainer` is never mentioned nor used anywhere in the final state of the Design The GUI tutorial.

![ui_gui_step_tutorial_counter_design_4](https://user-images.githubusercontent.com/8337880/103722549-3c4c6a00-4f9e-11eb-90d7-19e4ce1fe3a5.png)

**URL to the documentation page:**
https://docs.godotengine.org/en/stable/getting_started/step_by_step/ui_game_user_interface.html

**Comment by Piralein** [comment]
This Tutorial was only available up until version [3.3 Docs](https://docs.godotengine.org/en/3.3/getting_started/step_by_step/ui_game_user_interface.html), The [3.4 Docs](https://docs.godotengine.org/en/3.4/getting_started/step_by_step/ui_game_user_interface.html) version is already 404.

The tutorial and image in question was removed by [#5412](https://github.com/godotengine/godot-docs/pull/5412)

Reference:
[Tutorial File in 3.3](https://github.com/godotengine/godot-docs/blob/3.3/getting_started/step_by_step/ui_game_user_interface.rst) and [Image File in 3.3](https://github.com/godotengine/godot-docs/blob/3.3/getting_started/step_by_step/img/ui_gui_step_tutorial_counter_design_4.png)

I was not able to find the Tutorial with keywords like "emerald" or "bomb". (3.5/master Branch)
I was also unable to find the image, assuming its still a .png file. (3.5/master Branch)

This can likely be closed as outdated.

**Comment by YuriSizov** [comment]
Yes, indeed, documentation prior to 3.4 is in maintenance mode and we don't plan to update it further.
