### ISSUE TITLE
Is : INV_CAMERA_MATRIX World space to view space transform ?

### ISSUE THREAD

**Issue by barakooda** [godotengine/godot-docs#4525]
given the usual workflow:
https://learnopengl.com/Getting-started/Coordinate-Systems
  Projection * Camera Space * WorldSpace * Vector

isn't usually inverse camera matrix:
is 
from view space to world space ? 

what special about Godot ?
 
"INV_CAMERA_MATRIX World space to view space transform."
https://docs.godotengine.org/en/stable/tutorials/shading/shading_reference/spatial_shader.html#doc-spatial-shader

**Comment by clayjohn** [comment]
The naming is a bit unclear right now. It certainly doesn't follow convention. We already have plans to update the names which is tracked in https://github.com/godotengine/godot/issues/16863

At any rate, the documentation is currently correct, so I will close this issue.
