### ISSUE TITLE
Provide a means for users to select full width of page documentation

### ISSUE THREAD

**Issue by AnmAtAnm** [godotengine/godot-docs#4532]
**Your Godot version:**
N/A

**Issue description:**
Godot Docs use a common design of a horizontally centered column. This can be waste a significant amount of screen real estate for the developer. 

Example from a full screen browser window on a 15" MacBook Pro:
<img width="819" alt="Screen Shot 2021-01-09 at 10 52 06 PM" src="https://user-images.githubusercontent.com/9916202/104116524-2f958200-52ce-11eb-82c8-ff6c324e48ae.png">

For those that will sacrifice the legibility of shorter lines for the ability to read more info without scrolling, a button to toggle off the extra wide margins would be greatly appreciated. This should be backed by some sort of view preferences cookie, for future pages opened at the site.

(Similar mechanism could be applied to light/dark mode, overriding the system setting preferences, but that's another issue.)

**Comment by pycbouh** [comment]
> (Similar mechanism could be applied to light/dark mode, overriding the system setting preferences, but that's another issue.)

And such issue is already reported, but the thing is that this setting won't be applied until on the client side, with JavaScript, and this will cause a disturbing flicker of the opposite (default) theme. Which would be extremely unpleasant for dark theme users.

> For those that will sacrifice the legibility of shorter lines for the ability to read more info without scrolling, a button to toggle off the extra wide margins would be greatly appreciated.

Sure, we could do it, but as you mention yourself, there is a reasonable line width that is considered comfortable for reading by most and anything beyond that grants diminishing returns. So why would that downgrade (optional, but that's not important right now) be preferable to just scrolling? You can also change your zoom level, if you want to fit more at a glance (though at a smaller screen this may render texts unreadable after a certain point).

**Comment by AnmAtAnm** [comment]
> Sure, we could do it, but as you mention yourself, there is a reasonable line width that is considered comfortable for reading by most and anything beyond that grants diminishing returns.

Not diminishing returns. Trade offs. The current design trades legibility for less information on screen. People obviously value more information on screen, or there wouldn't be a market for large monitors, especially in the target audience, software developers. But I'm not even comparing to a large monitor. The example screenshot above is a laptop screen, which still has nearly 50% of the page area blank.

Compare to...
 * [Unity Scripting Docs](https://docs.unity3d.com/ScriptReference/CompositeCollider2D.html) Full page width
 * [Oracle's JavaDocs](https://docs.oracle.com/javase/7/docs/api/java/lang/String.html) Full page width
 * [Boost C++ library docs](https://www.boost.org/sgi/stl/OutputIterator.html) Full page width
 * [Microsoft .NET APIs](https://docs.microsoft.com/en-us/dotnet/api/system.string?view=net-5.0) Centered column between two useful navigation sidebars, but configured such that it nearly fills a laptop screen.
 * [Python APIs](https://docs.python.org/3/library/string.html) Limited width, but substantially wider than Godot's API docs
 * [GTK#](https://developer.gnome.org/glib/stable/glib-Strings.html#GString), a C# lib with docs built with monodoc: Limited, but even wider than Python's width

![Screen Shot 2021-01-10 at 10 58 23 AM](https://user-images.githubusercontent.com/9916202/104132905-065c0c80-5335-11eb-854e-2e73a3e21727.png)

But I do understand this is a trade off. I'm not asking this to be the default (though if I were the page designer....). I'm asking the option to be exposed.

> So why would that downgrade (optional, but that's not important right now) be preferable to just scrolling?

Information on screen. Preferably to scrolling in many developer use cases, such as working in another window, but needing to glance at the tutorial or API.

To make this concrete, see this screenshot, when I have edited the margins to fill the screen:
![Screen Shot 2021-01-10 at 10 25 09 AM](https://user-images.githubusercontent.com/9916202/104131973-1ffa5580-532f-11eb-8d20-689486dd76f7.png)

Compared to the previous screenshot, I can see all the entries of CursorShape enum (somewhat random selection), the identifiers (perhaps the most important part of an enum in API docs) are close together and easier to read/compare, and I can still see the three methods below which any changes to the fairly ample spacing.

> You can also change your zoom level, if you want to fit more at a glance (though at a smaller screen this may render texts unreadable after a certain point).

That completely misses the point, making less page content visible than the default view.

(The more I compare, the stronger I feel that the current width is a poor design choice, probably taken from the standards of prose like blogs and news articles, and applied to developer docs without much consideration for the audience.)

**Comment by Calinou** [comment]
I'm not convinced that wider lines actually help with readability, even if you take into account the fact that it requires less scrolling.

If you find scrolling too painful, consider using other methods of scrolling (<kbd>Space</kbd> / <kbd>Shift + Space></kbd>, <kbd>Page Up</kbd> / <kbd>Page Down</kbd>, …).

**Comment by pycbouh** [comment]
> People obviously value more information on screen, or there wouldn't be a market for large monitors, especially in the target audience, software developers

Hey, I'm on an ultra-wide display, I know how it feels, but I think that the amount of information is perfectly reasonable. Scrolling works even in unfocused windows, and the excessive screen space is better utilized by putting another app side by side. Nobody reads this wide:

![image](https://user-images.githubusercontent.com/11782833/104134922-c3824f00-539d-11eb-9d48-29eab54fd0ab.png)

(That image is at 125% system scale on 3440x1440, btw)

> That completely misses the point, making less page content visible than the default view.

I was actually suggesting to zoom out, not zoom in. So it would be more content, not less.

---
All that said, I'm not against making the body a bit wider in our docs.

**Comment by akien-mga** [comment]
I think we could try to make it a bit wider, as shown in https://github.com/godotengine/godot-docs/issues/4532#issuecomment-757528285 we do seem to have somewhat less width than other docs.
But indeed full width doesn't sound like a good option to have IMO.

> GitHub also has a limited width, and it's quite close to the Godot documentation's in terms of characters per line. Yet most people seem to be fine with it

Actually it does seem significantly higher in GitHub, see this (monospace, so not 100% accurate) comparison:

![Screenshot_20210112_122633](https://user-images.githubusercontent.com/4701338/104308930-aa7aba80-54d1-11eb-9951-a3a8e5ff6021.png)

**Comment by AnmAtAnm** [comment]
Since GitHub was also mentioned, this what I see.  Both windows are wide enough to not see further growth of the content column. GitHub does appear to have a larger font, but it is wider (~800px to Godot's ~700px)
<img width="1338" alt="Screen Shot 2021-01-12 at 9 21 55 PM" src="https://user-images.githubusercontent.com/9916202/104410145-990ad000-551c-11eb-924c-cc3a24d7f32c.png">

Scaling down the GitHub site to match font size, the content width still seems noticeable larger.

I do understand maintenance/effort concerns.  I think a wider content column is a reasonable low-effort solution to bring the Godot docs inline with other documentation sites.

@Calinou Thanks for the pointer to stylus. I did adjust the `max-width`s for the doc site.
