### ISSUE TITLE
Regex not working

### ISSUE THREAD

**Issue by georgetye** [godotengine/godot-docs#4533]
I tried putting the example code for regex on the documentation into my script:

```
var regex = RegEx.new()
regex.compile("\\w-(\\d+)")
var result = regex.search("abc n-0123")
if result:
    print(result.get_string())
```

And got this error on the second line: `Unexpected token: Identifier: regex`

**Comment by pycbouh** [comment]
Can you show how this code looks in your editor, when it's causing the error?

**Comment by georgetye** [comment]
Nevermind, I realize now that it's because I didn't have the bottom 4 lines inside of a function!
