### ISSUE TITLE
player controlled cut/growth animation

### ISSUE THREAD

**Issue by MinecraftPlaye** [godotengine/godot-docs#4540]
**Your Godot version:**
3.2.3

**Issue description:**
Hi there,

I'm wondering how I can create a cut/growth animation in Godot. I currently have a 3d mesh floating in my scene. 
I know want to have a invisible and player controlled plane (easy) in my scene. The part where I'm not sure how I can achieve this in Godot is when it comes to rendering only everything which is behind my plane. Everything which is in front of it should not be rendered. Would be really nice to have some documentation on how to achieve such a animation.

Something similar to this (at that time frame), just as an animation in Godot: https://youtu.be/lCKOYXzpOao?t=461

**Comment by Calinou** [comment]
Please don't ask support questions here, as this issue tracker is meant to be used for bug reports only. Use one of the other [community channels](https://godotengine.org/community) instead.
