### ISSUE TITLE
Vector3/2 lerp is still called linear_interpolate

### ISSUE THREAD

**Issue by 3top1a** [godotengine/godot-docs#4544]
**Your Godot version:** 
latest, as of today

**Issue description:**
A while ago linear_interpolate was changed to lerp, but the docs still call it linear_interpolate

**URL to the documentation page (if already existing):**
https://docs.godotengine.org/en/latest/classes/class_vector3.html
https://docs.godotengine.org/en/latest/classes/class_vector2.html

**Comment by Calinou** [comment]
This is because the online class reference in the `master` branch hasn't been updated yet.

**Comment by skyace65** [comment]
Class reference got updated and both of those pages say "lerp" instead of "linear_interpolate" now. This issue can be closed.
