### ISSUE TITLE
Minor inconsistency - margin getter/setter noted separately in StyleBoxTexture

### ISSUE THREAD

**Issue by Haledire** [godotengine/godot-docs#4558]
**Your Godot version:**
3.2.3

**Issue description:**
StyleBoxTexture page lists margin setters redudantly
`set_margin_size()` and `get_margin_size()` are the setters and getters for margin_left, margin_right, etc.
When mentioned as the setters, it's listed as `set_margin_size(value)` which seems incorrect, as this function requires identifying the margin being set `(MARGIN margin, float value)`

get_margin() is also being listed as `get_margin()` in the getters of these properties, but it also requires `(Margin margin)`.

I assume the redundancy in listing the functions is to clarify the usage of the functions, but they should probably be marked as needing to reference the actual function call or have the proper syntax listed.

**URL to the documentation page (if already existing):**
https://docs.godotengine.org/en/stable/classes/class_styleboxtexture.html#class-styleboxtexture

**Comment by tetrapod00** [comment]
Seems to be fixed since 3.5.
