### ISSUE TITLE
The "C# API differences to GDScript" page (or somewhere) should mention "onready"

### ISSUE THREAD

**Issue by 31** [godotengine/godot-docs#4563]
**Your Godot version:**
3.2.3 (stable)

**Issue description:**
Currently the C# differences doc doesn't mention `onready`. When someone reads GDScript while trying to learn/use C#, the `onready` keyword can trip them up, since C# has no equivalent. (In C# you must declare a field/property and initialize the value in `_Ready()`.)

I think it's worth mentioning, to make it clear how to accomplish this in C#, and that Godot has no plug-and-play alternative set up for C# users. (Although libraries do exist to somewhat fill in this feature.)

**URL to the documentation page (if already existing):**
https://docs.godotengine.org/en/latest/tutorials/scripting/c_sharp/c_sharp_differences.html
https://docs.godotengine.org/en/stable/getting_started/scripting/c_sharp/c_sharp_differences.html

**Comment by skyace65** [comment]
If you can provide a code example of doing this in C# I'll add it to the docs

**Comment by 31** [comment]
Thanks! Something like this (from https://docs.godotengine.org/en/latest/tutorials/scripting/gdscript/gdscript_basics.html#onready-annotation):

```
@onready var my_label = get_node("MyLabel")
```

would be:

```cs
private Label _myLabel;

public override void _Ready()
{
    _myLabel = GetNode<Label>("MyLabel");
}
```
