### ISSUE TITLE
There is no example of using bsearch_custom in the documentation

### ISSUE THREAD

**Issue by Arnklit** [godotengine/godot-docs#4564]
**Your Godot version:**
3.2.3.Stable

**Issue description:**
There is no example of using bsearch_custom in the documentation. You need to pass it a custom function, but without an explanation of what parameters and return values it expects I haven't been able to get it to work. I assume it's very similar to sort_custom which does have an example, but what I've tried doesn't work.

**URL to the documentation page (if already existing):**
https://docs.godotengine.org/en/3.2/classes/class_array.html#class-array-method-bsearch-custom

**Comment by hungrymonkey** [comment]
I will write it. The object thing is quite odd but i figure it out

```
extends Node

# Declare member variables here. Examples:
# var a = 2
# var b = "text"

var custom = preload("Custom.gd")
# Called when the node enters the scene tree for the first time.
func compare(a,b):
	return a.getV() < b.getV()

func _ready():
	print("start")
	var p = custom.new()

	p.setV(8)
	var c = [custom.new(), custom.new(), custom.new(), custom.new(), 
		custom.new(), custom.new(), custom.new(), custom.new(), custom.new(),
		custom.new(), custom.new(), custom.new(), custom.new(), custom.new(), custom.new()]
	for i in c.size():
		c[i].setV(i + 1)
	

	print(c.bsearch_custom(p, self, "compare", true))
	print("done")
```

```
extends Object


var val = 0

func _ready():
	pass # Replace with function body.
	
func setV(a):
	val = a

func getV():
	return val
	
func _to_string():
	return String(val)
	
func compare(a, b):
	a.getV() < b.getV()
```

**Comment by donn-xx** [comment]
FYI: In 4.3.dev there is still actual no example for bsearch_custom in the help.

**Comment by KoBeWi** [comment]
The example was added in 3.x branch: https://github.com/godotengine/godot/commit/1716423c9797c0f8c368e2bc8ace018db384f66d
Not sure why it wasn't ported to `master` (4.x), it might need some tweaks.
