### ISSUE TITLE
Add a custom 404 error page

### ISSUE THREAD

**Issue by Calinou** [godotengine/godot-docs#4567]
We should add a custom 404 page to better guide users back to the documentation. See https://github.com/readthedocs/readthedocs.org/issues/2551.

**Comment by humitos** [comment]
Godot is already using [`sphinx-notfound-page` extension](https://sphinx-notfound-page.readthedocs.io/), and the 404 pages look like this one https://docs.godotengine.org/en/stable/notfound. So, I think this issue can be closed now
![Screenshot_2022-08-25_13-20-20](https://user-images.githubusercontent.com/244656/186651207-32d0f13d-b92c-4e79-8859-3ef677297a00.png)
.

**Comment by Calinou** [comment]
This was implemented by https://github.com/godotengine/godot-docs/pull/4624, closing.
