### ISSUE TITLE
Iterating dictionaries and deleting

### ISSUE THREAD

**Issue by CitrusWire** [godotengine/godot-docs#4568]
**Your Godot version:**
3.2.3

**Issue description:**
It is unclear what the behaviour is when iterating over dictionaries. Iterating dictionaries and alterating them in the process is rarely a good thing, but sometimes it's necessary to free() a dictionary of Objects.

This brings up two things.

It says:

> Erasing elements while iterating over them is not supported and will result in undefined behavior.

But for `erase` it says: 
> Does not erase elements while iterating over the dictionary.

So which is it? That's an explicitly defined behaviour.

Furthermore, it's unclear what the erase quote means; will it store up all the erases until the iteration is over then execute them, or will it simply be a no-op?
Further clarification of this on the docs would be helpful.

**URL to the documentation page (if already existing):**
https://docs.godotengine.org/en/stable/classes/class_dictionary.html

**Comment by pycbouh** [comment]
I think your first quote from the docs perfectly answers your further questions: **it's undefined behavior, don't do it**. This is typical for many programming languages due to how memory is allocated for collections. You can use two loops and an intermediate `objects_to_delete` array to work around this without accidentally accessing invalid memory.

**Comment by CitrusWire** [comment]
Thanks. I'm aware of all of this, but then the `erase()` method explicitly *does* define the behaviour, albeit unclearly. Hence my suggesting clarification for the dcs.

**Comment by pycbouh** [comment]
What do you suggest we add there? Currently it says that it doesn't do what is expected of it. I guess we can reiterate from the previous quote that you shouldn't call it while iterating.

**Comment by CitrusWire** [comment]
I don't know what to suggest there because I don't know what the behaviour is.

a) Is `erase()` a no-op, in which case the entire top-warning is superfluous because it's impossible to erase values during an iteration.

b) Are erase's stacked up and then executed after the iteration is completed? In which case the top-warning is outright wrong.

c) Some other behaviour?

**Comment by pycbouh** [comment]
> I don't know what the behaviour is.

It's undefined. And a user shouldn't call this method. That's it. We cannot define the undefined behavior. The only issue I see in the description is that it is affirmative ("does not erase") instead of cautionary ("has undefined behavior"). We can make it more generalized.

**Comment by CitrusWire** [comment]
I believe we are talking at odds here.

* If it is as you say, undefined, then the `erase()` method documentation is wrong in trying to define it.

* If it the erase() method line is correct, then the behaviour is not undefined because as far as I can see, erase() is the only way to delete things from a dictionary (outside of clear()), and the behaviour of erase when deleting things is defined, albeit unclearly.

**Comment by hungrymonkey** [comment]
@CitrusWire To be honest, the docs will will be improved by deleting two letters.

> Does not erase elements while iterating over the dictionary. 

>Do not erase elements while iterating over the dictionary.

**Comment by tetrapod00** [comment]
This was resolved at some point, using the last suggestion in this issue. The 4.3 docs say:
> Note: Do not erase entries while iterating over the dictionary. You can iterate over the [keys](https://docs.godotengine.org/en/4.3/classes/class_dictionary.html#class-dictionary-method-keys) array instead.
