### ISSUE TITLE
ButtonGroup is documented, even though is not present in 3.0 anymore

### ISSUE THREAD

**Issue by YeldhamDev** [godotengine/godot-docs#457]
The [ButtonGroup](https://godot.readthedocs.io/en/latest/classes/class_buttongroup.html) node is documented, but it doesn't exist any more in Godot 3.0.

**Comment by akien-mga** [comment]
It doesn't seem to be a bug, ButtonGroup as a node no longer exists, but it's now a Resource in the BaseButton class.

**Comment by YeldhamDev** [comment]
@akien-mga I see... But I don't understand how is it useful as a resource though.
