### ISSUE TITLE
"Exporting for Android" missing info on Adb and Jarsigner

### ISSUE THREAD

**Issue by ShatReal** [godotengine/godot-docs#4575]
**Your Godot version:**
3.2.3
**Issue description:**
I need to have paths for those two slots in order to export to android, but the docs don't say what they are.
**URL to the documentation page:**
https://docs.godotengine.org/en/stable/getting_started/workflow/export/exporting_for_android.html#setting-it-up-in-godot

**Comment by Calinou** [comment]
There is no longer information about adb on that page as the setup is now handled differently since https://github.com/godotengine/godot-docs/pull/4520.

**Comment by m4gr3d** [comment]
@Calinou yes that sounds good to me. I've created https://github.com/godotengine/godot-docs/pull/4582 to that effect.

@Calinou It should be just as easy to revert the `revert` once 3.2.4 is stable, correct?

**Comment by Calinou** [comment]
> @Calinou It should be just as easy to revert the revert once 3.2.4 is stable, correct?

Yes :slightly_smiling_face:

**Comment by Calinou** [comment]
Solved by https://github.com/godotengine/godot-docs/pull/4582.

**Comment by akien-mga** [comment]
But now there's no documentation for people testing 3.2.4 RCs either :|

**Comment by Calinou** [comment]
@akien-mga I'm not sure how to solve this. We could add the information for both versions in the same page, but it'd make the page long and convoluted until 3.2.4 stable is released.

**Comment by akien-mga** [comment]
Yeah I guess we should link to the PR in the meantime.
