### ISSUE TITLE
Godot does not support Perforce intergration

### ISSUE THREAD

**Issue by Syraleaf** [godotengine/godot-docs#4584]
**Your Godot version:**
v3.2.3 stable

**Issue description:**
Disclaimer first because I can see the reactions already. Yes, Godot *can* run with perforce but not in its default setup. Godot does not *support* P4.

There does not seem to be a perforce add-on, nor does it seem to natively work very well with perforce (read-only causes a lot of errors in the engine) The features page as well as the File system page mention Perforce by name as something that works well with Godot. 
Based on the reactions in the discord it does not seem that there are any plans to support it either. 

I propose that the sentences are changed in such a way that it shows that there's the option to build your own integration but that there's nothing like that out of the box at the moment.

I'm not familiar with the other source control tools but I would recommend double checking those too if I'm correct about perforce support

**URL to the documentation page:**
https://godot-es-docs.readthedocs.io/en/latest/getting_started/step_by_step/filesystem.html
https://godotengine.org/features

**Comment by pycbouh** [comment]
First of all, this is not the official documentation, it's just some unmaintained mirror. This is the actual documentation: https://docs.godotengine.org/en/stable/getting_started/step_by_step/filesystem.html

Second of all, the article doesn't mention an integration: Godot doesn't come with any kind of VCS support out of the box. It only mentions Perforce among others under this statement:
> Godot tries its best to play along with SVN, Git, Mercurial, Perforce, etc.

This notion comes from the fact that Godot uses text-based files (and not binary files) for everything that relates to its project files. There is no other guarantee given there.

I agree that the statement of the Features page is a bit too enthusiastic though:
> Friendly filesystem usage that works great with version control systems like Git, Subversion, Mercurial, PlasticSCM, Perforce, you name it.

**Comment by Calinou** [comment]
**Note to future readers:** godot-es-docs is no longer online as it was taken down. We requested ownership since its owner is no longer active and effectively shut it down last sweek.
