### ISSUE TITLE
Flawed example code in your firist game

### ISSUE THREAD

**Issue by NO-MEANINGS** [godotengine/godot-docs#4589]
**Your Godot version:**
v3.2.3.stable

**Issue description:**
in step by step tutorial > your first game:
The code calculating the speed of player sprite is wrong.  In the original code the variable speed is not multiplied, which causes the actual speed is only 1 pixel/sec. Such a low speed is hard to tell at a glance.

**URL to the documentation page:**
https://docs.godotengine.org/en/stable/getting_started/step_by_step/your_first_game.html

**Comment by pycbouh** [comment]
The `speed` property is applied in the `_process` function:

![image](https://user-images.githubusercontent.com/11782833/105985088-12252e00-60ac-11eb-956d-a16fa304821c.png)
