### ISSUE TITLE
Add [member] links like [method]

### ISSUE THREAD

**Issue by cbscribe** [godotengine/godot-docs#459]
Currently in the docs, we can write [method Node.foo] to link to a class method.  Now that 3.0 has member variables which will be replacing many of the methods, we need to be able to link to them as well.

Format can follow method:

Tag | Effect | Usage | Result
-- | -- | -- | --
[member Class.membername] | Link to another class's member | See [member Node2D.position]. | See :ref:`position <class_node2d_position>`.

**Comment by bojidar-bg** [comment]
Since the RST is generated by the [makerst.py](https://github.com/godotengine/godot/blob/master/doc/tools/makerst.py) script in the other repo, I guess we might close this one, as there is nothing to be implemented here. WDYT?

**Comment by cbscribe** [comment]
Moved issue to main repo: https://github.com/godotengine/godot/issues/11137
