### ISSUE TITLE
Add something that says "oh yeah you have to connect the meta_clicked signal" for a RichTextLabel's url BBCode

### ISSUE THREAD

**Issue by ShatReal** [godotengine/godot-docs#4590]
**Your Godot version:**
3.2.3
**Issue description:**
The guide for a RichTextLabel's BBCode doesn't mention anything about having to connect the meta_clicked signal when making a url. This is confusing.
**URL to the documentation page (if already existing):**
https://docs.godotengine.org/en/stable/tutorials/gui/bbcode_in_richtextlabel.html

**Comment by Calinou** [comment]
In my experience, URLs have always been clickable by default.

**Comment by pycbouh** [comment]
I've not checked it myself lately, but I've had a person on Discord for whom this didn't work automatically and required `meta_clicked` to be implemented. Worth double-checking I guess.

**Comment by skyace65** [comment]
This was fixed in #5246. This issue can be closed.

**Comment by pycbouh** [comment]
Good call!
