### ISSUE TITLE
strange easter egg at tutorials/io/encrypting_save_games.rst

### ISSUE THREAD

**Issue by RoniPerson** [godotengine/godot-docs#4595]
**Your Godot version:**
3.2.3

**Issue description:**
When searching in the docs about savegames i found this tutoial and the introduction was really strange. At first I thought someone had writen his political opinion in this article. Looking at the source it seems as if this should be an easter egg. But on a discord I found someone else also not getting the easter egg. So I think this easter egg should be removed or a visible disclaimer should be added. The thing about easter eggs is that if you don't get them you don't notice them. But in this case if you don't get it you think it's a political statement. And i think most of the people wont get it.

And by the way does someone know to what it is an easter egg?

**URL to the documentation page (if already existing):**
https://github.com/godotengine/godot-docs/blob/master/tutorials/io/encrypting_save_games.rst

**Comment by pycbouh** [comment]
> And i think most of the people wont get it.

This is not the consensus that we've reached. Maybe the term "easter egg" is not used correctly, but this is still a cheeky prologue to the otherwise serious article aimed to poke fun at the situation.
