### ISSUE TITLE
CanvasItem.draw_string() documents wrong position

### ISSUE THREAD

**Issue by Birdulon** [godotengine/godot-docs#4599]
**Your Godot version:** 3.2.4beta6

**Issue description:**
`CanvasItem.draw_string()` claims to use position as the top-left corner unlike `Font.draw()` which uses position as the baseline, however the former simply calls the latter and therefore uses position as baseline. (https://github.com/godotengine/godot/blob/06895e0c9e312ac02b8fa8a0058dcc306b9a8018/scene/2d/canvas_item.cpp#L934)

**URL to the documentation page:**
https://docs.godotengine.org/en/stable/classes/class_canvasitem.html?highlight=CanvasItem#class-canvasitem-method-draw-string
see also: https://docs.godotengine.org/en/stable/classes/class_font.html#class-font-method-draw

**Comment by Calinou** [comment]
[Feel free to open a pull request to fix this](https://docs.godotengine.org/en/latest/community/contributing/updating_the_class_reference.html) :slightly_smiling_face:

**Comment by Birdulon** [comment]
Fixed by https://github.com/godotengine/godot/pull/45577 and https://github.com/godotengine/godot/pull/47098
