### ISSUE TITLE
Physics Introduction needs full reorganization

### ISSUE THREAD

**Issue by genete** [godotengine/godot-docs#46]
I think that Physics introduction is a bit messy. I have not a good structure because I need to understand the usage and meaning of each node, but someone with better knowledge could reorganize it.

**Comment by NathanLovato** [comment]
Chris is working on a new 2d physics guide, and as there are breaking changes for 3.0 we'll improve them. Akien and Straton reorganized the 2.x docs since the post.
Closing for now. We can open a new discussion over when the new tutorials arrived.
