### ISSUE TITLE
404 URL Online Tutorials in String class reference from within Godot editor

### ISSUE THREAD

**Issue by corrigentia** [godotengine/godot-docs#4610]
**Your Godot version:** 3.2.3.stable.official

**Issue description:**

`label: "class reference"`

new_gd_script.gd
\>
member variable
```GDScript
const test:String = "text"
```
\>
Ctrl-click on `String`
\>
Online Tutorials

[docs.godotengine.org/en/latest/getting_started/scripting/gdscript/gdscript_format_string.html](https://docs.godotengine.org/en/latest/getting_started/scripting/gdscript/gdscript_format_string.html)

\>
404

        \          SORRY            /
         \                         /
          \    This page does     /
           ]   not exist yet.    [    ,'|
           ]                     [   /  |
           ]___               ___[ ,'   |
           ]  ]\             /[  [ |:   |
           ]  ] \           / [  [ |:   |
           ]  ]  ]         [  [  [ |:   |
           ]  ]  ]__     __[  [  [ |:   |
           ]  ]  ] ]\ _ /[ [  [  [ |:   |
           ]  ]  ] ] (#) [ [  [  [ :===='
           ]  ]  ]_].nHn.[_[  [  [
           ]  ]  ]  HHHHH. [  [  [
           ]  ] /   `HH("N  \ [  [
           ]__]/     HHH  "  \[__[
           ]         NNN         [
           ]         N/"         [
           ]         N H         [
          /          N            \
         /           q,            \
        /                           \
**URL to the documentation page:**
related:

[https://docs.godotengine.org/en/latest/tutorials/scripting/gdscript/gdscript_format_string.html](https://docs.godotengine.org/en/latest/tutorials/scripting/gdscript/gdscript_format_string.html)

"See [this page](https://docs.godotengine.org/en/stable/tutorials/scripting/gdscript/gdscript_format_string.html) for [...]"
\>
404

The documentation directory structure has been rearranged, losing its simple one-to-one correspondence/mapping, so it can't be easily handled between "`stable`" & "`latest`" with

```
updatedUrl
```

in 

[https://github.com/godotengine/godot-docs](https://github.com/godotengine/godot-docs) /  _static/js/custom.js 

3rd & almost surely unrelated part:
Romanian project manager interface translation:

Projects ==> Proiecte
Templates ==> Șabloane

Templates > (Sort) Sorare ==> Sortare [missing letter]
Templates > Pong with GDScript > (Close) Aproape (adjective close) ==> Închide (verb close)

**Comment by Calinou** [comment]
> Romanian project manager interface translation:
>
> Projects ==> Proiecte
> Templates ==> Șabloane
>
> Templates > (Sort) Sorare ==> Sortare [missing letter]
> Templates > Pong with GDScript > (Close) Aproape (adjective close) ==> Închide (verb close)

[You can fix this on your own for the next Godot version](https://docs.godotengine.org/en/latest/community/contributing/editor_and_docs_localization.html#doc-editor-and-docs-localization) :slightly_smiling_face:
