### ISSUE TITLE
Add to Your first game tutorial Record label

### ISSUE THREAD

**Issue by Summersay415** [godotengine/godot-docs#4614]
**Your Godot version:**
3.2.3.stable

**Issue description:**
Add to Your first game tutorial Record label. It displays record and saves it on disk, and then game started loads from disk.

**URL to the documentation page (if already existing):**
https://docs.godotengine.org/en/latest/getting_started/step_by_step/your_first_game.html

**Comment by Calinou** [comment]
@NathanLovato Do we consider this to be minimal enough to be part of a "Your first game" tutorial?

**Comment by NathanLovato** [comment]
No, to me, it's beyond the scope. The 2d and 3d tuts are already big enough, and other sections lacking a lot of work.

To document serialisation, we should flesh out and update the I/o section instead.
