### ISSUE TITLE
classes documentation not updated from source repository

### ISSUE THREAD

**Issue by dbu** [godotengine/godot-docs#4639]
it seems that classes documentation shown online is not up to date with the source code. i created https://github.com/godotengine/godot-docs/pull/4638 but was told that this is the wrong place to fix it. looking at the godot source code, there is a minimal fix https://github.com/godotengine/godot/commit/995388cf6fd4300f9eaa7b6ac7a48210ec655249 but the docs repository is not updated with that:

https://docs.godotengine.org/en/stable/classes/class_tilemap.html#class-tilemap-method-map-to-world
https://docs.godotengine.org/en/3.2/classes/class_tilemap.html#class-tilemap-method-map-to-world

**Comment by pycbouh** [comment]
The online docs are not updated automatically, it is done by hand from time to time. Once a month, maybe. It will be synced, don't worry.
