### ISSUE TITLE
release the doc in a zip file or make it more clear how to build the doc

### ISSUE THREAD

**Issue by ghost** [godotengine/godot-docs#4640]
**Your Godot version:**
3.2.3
**Issue description:**
my issue is having to build the documentation and the lack of information about how to build it, would be nice if the documentation was released in html like blender does https://docs.blender.org/manual/en/2.91/
**URL to the documentation page (if already existing):**
https://docs.godotengine.org/en/stable/

**Comment by pycbouh** [comment]
Are these instructions not sufficient?

https://docs.godotengine.org/en/latest/community/contributing/building_the_manual.html

**Comment by DaniV5** [comment]
nah man, fuck python and fuck that shit
i'll just kill myself

**Comment by Calinou** [comment]
You can get offline HTML builds in a ZIP on [this page](https://hugo.pro/projects/godot-builds/).
