### ISSUE TITLE
Explain AI

### ISSUE THREAD

**Issue by Gamemap** [godotengine/godot-docs#4664]
**Your Godot version:**
    3.2.3 Windows 64Bit
**Issue description:**
    Add a page to explatin how to code an AI-System. (follow, flee, align to walking, pursue, wandering, ...)

   If someone know how to code this in 2D/3D, please write a documentation. (Sadly I don't know)

  Sorry if I have writing mistakes,
  Gamemap

**Comment by pycbouh** [comment]
Hi! Creating an AI system is a very goal-specific task, the design of such a system would greatly depend on what type of game you're creating, what play interactions are, what challenges you plan to implement, and a million other specific things. In other words, there is no single solution to this and you need to make your own research to make a system that fits your needs.

While we could provide an example of sorts, it would ultimately not be useful in general. And outside of the scope of our engine documentation. Luckily, there is nothing Godot-specific to building an AI. You can look for any game programming resource online that has good reviews and use whatever they teach you to make a Godot game.

And do check our [step by step guide](https://docs.godotengine.org/en/latest/getting_started/step_by_step/index.html), which explains how to make a simple, casual game. It has enemies, so in a sense it has an AI. Maybe it can be a starting point for you. You can then read up on navigation and pathfinding to enhance that little project and go from there.

**Comment by Gamemap** [comment]
Thank you I will look at the tutorial!

Could you explain me how I can get a rotation of an object in 3d as Vector for angel_to ?

I mean: `Vector2(1,0).rotated(obj.rotation_variable)`     
(rotation_variable = float; see https://docs.godotengine.org/en/stable/classes/class_node2d.html#class-node2d-property-rotation
`Vector2.rotated` see https://docs.godotengine.org/en/latest/classes/class_vector2.html#class-vector2-method-rotated
`Vecor3.rotated` see https://docs.godotengine.org/en/latest/classes/class_vector3.html#class-vector3-method-rotated)

Do I need to do this to get a similar result in 3D? `Vector3(1,0,0).rotated(Vector3(1,0,0), obj.rotation_variable)`
I think that I haven't understood the documentation.

Maybe you can help me,
Gamemap

**Comment by Calinou** [comment]
@Gamemap Support questions should be asked on one of the other [community channels](https://godotengine.org/community) (not GitHub), as this issue tracker is meant to be used for documentation issues only.

**Comment by Gamemap** [comment]
Ok, sorry.

I will look there.
Gamemap
