### ISSUE TITLE
VS Build Tools for C# needs updated list of components

### ISSUE THREAD

**Issue by juanitogan** [godotengine/godot-docs#4672]
**Your Godot version:** 3.2.3

**Issue description:**  C# doc out of date

**URL to the documentation page:**

https://docs.godotengine.org/en/stable/getting_started/scripting/c_sharp/c_sharp_basics.html#windows-visual-studio

The page says "Make sure you at least have the .NET Framework 4.5 targeting pack installed...."  If only choosing that, you get unhelpful errors when trying to run Dodge the Creeps C#.

Currently, the minimum I can find is .NET SDK (which adds .NET 5.0 Runtime and .NET Core 3.1 Runtime) and .NET Framework 4.7.2 targeting pack.  The .NET SDK is critical as that is what allows more helpful errors telling you which targeting pack is missing.  If the doc is difficult to keep up to date, perhaps it could be worded differently.

Also, the main Godot download page (https://godotengine.org/download/windows) should point to this setup info.

Screenshot of the minimal install I found:

![image](https://user-images.githubusercontent.com/2923222/108668637-baa29400-7498-11eb-923c-be4dfb183dd8.png)

**Comment by Calinou** [comment]
@juanitogan Feel free to open a pull request for this :slightly_smiling_face:

**Comment by skyace65** [comment]
@Calinou This looks like it was already fixed in the master branch and 3.3 branch. Should this issue stay open? Or close it when 3.3 releases?

**Comment by Calinou** [comment]
@skyace65 We should cherry-pick this to the `3.2` branch just in case first.

**Comment by skyace65** [comment]
@Calinou Looks like that's already happened in #4764
