### ISSUE TITLE
Illustrate Vector2's angle_to(to) and similar methods

### ISSUE THREAD

**Issue by mechPenSketch** [godotengine/godot-docs#4676]
**Your Godot version:**
3.2.3.stable.official

**Issue description:**
It's hard to imagine what is the angle returned from Vector2's method `angle_to(Vector to)` as well as `angle_to_point(Vector to)`.

I suggest adding an image under each of the respective method descriptions. This image contains a graph that illustrate what angle is being returned.

Here is an example of the graph, this one demonstrating `angle_to(Vector to)`:
![godoc_vector_angle_to](https://user-images.githubusercontent.com/15977859/108860012-c4f39800-7628-11eb-80ab-8d84c5a6ac48.png)

Disclaimer: This image is already compressed as instructed in [Image contribution guidelines](https://docs.godotengine.org/en/stable/community/contributing/docs_writing_guidelines.html).

For the graph, I tried following the format similar to the ones in [Vector Math](https://docs.godotengine.org/en/stable/tutorials/math/vector_math.html), but I can't follow through perfectly. I can't get the right arrowhead, and I don't know the font used there. Anyone knows what tools to use?

I would also need advice for the folder placement for the images.

Once this suggestion is approved, I can also create graph for `angle_to_point(Vector to)` as well as `angle()`.

**URL to the documentation page (if already existing):**
https://docs.godotengine.org/en/stable/classes/class_vector2.html#class-vector2-method-angle-to

**Comment by Calinou** [comment]
The class reference can't have inline images, so these images would have to be hosted in the godot-docs repository and linked using an `[url=]` tag.

**Comment by Torguen** [comment]
Surely it is not "to" who establishes the positive X axis?

**Comment by Torguen** [comment]
I think you are confused, the image is from "angleToPoint"?

**Comment by mechPenSketch** [comment]
> I think you get confused, I think the image is from "angleToPoint"?
> 
> Also the Right axis is set by the vector "to" according to my studies.

The image shown in the first post doesn't show the correct angle, but I have corrected it by the time I made the appropriate pull request.

**Comment by Torguen** [comment]
Could you provide me with the link to the extraction please?

**Comment by mechPenSketch** [comment]
> Could you provide me with the link to the extraction please?

https://github.com/godotengine/godot-docs/pull/4678 is where I've added the images.

**Comment by KoBeWi** [comment]
`angle_to_point()` is now outdated btw, see https://github.com/godotengine/godot/pull/43072#issuecomment-966654422

**Comment by mechPenSketch** [comment]
Change pending.

**Comment by Calinou** [comment]
> Change pending.

This issue should be left open until the corresponding PR is merged 🙂
