### ISSUE TITLE
QA users tab is broken

### ISSUE THREAD

**Issue by LoneDespair** [godotengine/godot-docs#4677]
**Your Godot version:**
3.2.3-stable

**Issue description:**
Not really sure where to report this, but this page is broken https://godotengine.org/qa/users

**URL to the documentation page:**
https://godotengine.org/qa/users

**Comment by Calinou** [comment]
I don't know why that's happening. My guess is that someone registered with an username that causes a PHP exception somehow.

**Comment by pycbouh** [comment]
So if they post a question, even the main page will be broken?

**Comment by Calinou** [comment]
> So if they post a question, even the main page will be broken?

New accounts require their first post to be approved before it can be seen by others, so that shouldn't be an issue.

**Comment by skyace65** [comment]
The QA page is now the forum which no longer has this problem, closing this issue.
