### ISSUE TITLE
Document more clear that `Tabs` control is an alternative to `TabContainer` and not its part.

### ISSUE THREAD

**Issue by me2beats** [godotengine/godot-docs#4682]
**Your Godot version:**
3.2.3

**Issue description:**
I have seen several times that users add `Tabs` as child nodes of a `TabContainer`, thinking `Tabs` is related to `TabContainer` in some way.

**URL to the documentation page (if already existing):**
https://docs.godotengine.org/ru/stable/classes/class_tabs.html

**Comment by zacryol** [comment]
I was also confused by that at first.
