### ISSUE TITLE
"Your first game" page's C# example missing speed limitation implementation

### ISSUE THREAD

**Issue by pellul** [godotengine/godot-docs#4708]
**Your Godot version:**
3.2

**Issue description:**
Under the [Your first game > Main scene > Main script](https://docs.godotengine.org/en/3.2/getting_started/step_by_step/your_first_game.html#main-script) section, the mob's speed is hardcoded in the C# example while it is not in the GDScript one.

It would be nice to have the speed based on the exported variables defined in the [#Enemy Script](https://docs.godotengine.org/en/stable/getting_started/step_by_step/your_first_game.html#enemy-script) section.

If it's not possible to use them in C#, then showing a warning would be less confusing imho.

I would have loved to submit a PR, but I am still learning and I don't know if it's feasible or not at the moment.

GDScript: 
```GDScript
func _on_MobTimer_timeout():
    # Choose a random location on Path2D.
    $MobPath/MobSpawnLocation.offset = randi()
    # Create a Mob instance and add it to the scene.
    var mob = Mob.instance()
    add_child(mob)
    # Set the mob's direction perpendicular to the path direction.
    var direction = $MobPath/MobSpawnLocation.rotation + PI / 2
    # Set the mob's position to a random location.
    mob.position = $MobPath/MobSpawnLocation.position
    # Add some randomness to the direction.
    direction += rand_range(-PI / 4, PI / 4)
    mob.rotation = direction
    # Set the velocity (speed & direction).
    mob.linear_velocity = Vector2(rand_range(mob.min_speed, mob.max_speed), 0)
    mob.linear_velocity = mob.linear_velocity.rotated(direction)
```

C#:
```C#
public void OnMobTimerTimeout()
{
    // Choose a random location on Path2D.
    var mobSpawnLocation = GetNode<PathFollow2D>("MobPath/MobSpawnLocation");
    mobSpawnLocation.Offset = _random.Next();

    // Create a Mob instance and add it to the scene.
    var mobInstance = (RigidBody2D)Mob.Instance();
    AddChild(mobInstance);

    // Set the mob's direction perpendicular to the path direction.
    float direction = mobSpawnLocation.Rotation + Mathf.Pi / 2;

    // Set the mob's position to a random location.
    mobInstance.Position = mobSpawnLocation.Position;

    // Add some randomness to the direction.
    direction += RandRange(-Mathf.Pi / 4, Mathf.Pi / 4);
    mobInstance.Rotation = direction;

    // Choose the velocity.
    mobInstance.LinearVelocity = new Vector2(RandRange(150f, 250f), 0).Rotated(direction);
```

**URL to the documentation page:**
[Your first game (v3.2 "stable")](https://docs.godotengine.org/en/3.2/getting_started/step_by_step/your_first_game.html)
[Your first game (v3.1)](https://docs.godotengine.org/en/3.1/getting_started/step_by_step/your_first_game.html)
[Your first game (v3.0)](https://docs.godotengine.org/en/3.0/getting_started/step_by_step/your_first_game.html)

**Comment by paulloz** [comment]
This is already fixed on [latest](https://docs.godotengine.org/en/latest/getting_started/first_2d_game/05.the_main_game_scene.html#main-script) (the page was just moved in #4687).

**Comment by pellul** [comment]
Thanks!

I close.
