### ISSUE TITLE
re-add the satirical paragraph

### ISSUE THREAD

**Issue by grolongo** [godotengine/godot-docs#4717]
@akien-mga franchement, qu'importe si des bas du front se sentent offensés, d'autant plus sur un sujet aussi anodin que celui-là... Car tu parles d'une controverse, mais quelle controverse exactement ? De celle de trois tordus sans capacité de discernement et d'autocritique pour qui la vérité les fait sortir de leur confort qu'ils pensaient peut-être moral ?

D'autant plus que le sujet dont lequel tu parles dans ton texte est important, en plus d'être une œuvre créative en soit à sa juste valeur.

Laisse les cons s’effaroucher (de leur bon droit) dans leur coin merde ! Ce n'est pas une raison pour qu'une frange hyper vocale, mais insignifiante n'ai aucune influence sur toi quelle qu’en soit la raison, et encore moins à en arriver à te faire autocensurer.

Sérieusement, en tant que français toi-même, avec tout ce qui s'est passé récemment, Charlie Hebdo, Samuel Paty ou bien même Jyllands-Posten pour te ramener au Danemark, cela ne te met t-il pas mal à l'aise avec du recul d'en arriver là ?

ref: b872229427dddb9b749f46af597e85e25cf2955a

**Comment by pycbouh** [comment]
In the interest of having a productive discussion with all of the community members, please submit your reports in English.

That said, the question of the article about encrypting save files is closed.
