### ISSUE TITLE
Add C# example for setting custom MarginContainer properties

### ISSUE THREAD

**Issue by klianc09** [godotengine/godot-docs#4719]
**Your Godot version:** 3.2.2

**Issue description:** There is an example on how to set the custom margin properties of a MarginContainer from script. However there is only an example with GDScript, I'd like to set these properties from C# though. 
My Issue is two-fold though: I don't even know if it is possible to do it from C#, since I couldn't find any instructions on it anywhere online. But I assume it is possible and just not documented anywhere.

**URL to the documentation page (if already existing):** https://docs.godotengine.org/en/stable/classes/class_margincontainer.html

**Comment by Calinou** [comment]
Using `set("custom_constants/item_name", value)` for theme items is an alternative way to do `add_constant_override("item_name", value)`. Just use the latter in C#, it's more type-safe.
