### ISSUE TITLE
Upstream our pygments lexer for GDScript

### ISSUE THREAD

**Issue by cbscribe** [godotengine/godot-docs#472]
I noticed in the following in `conf.py`:

    # Pygments (syntax highlighting) style to use
    pygments_style = 'sphinx'
    highlight_language = 'gdscript'

But according to http://pygments.org/ there isn't a gdscript parser.  This is a suggestion that we should probably add one.  Especially once the demos are showing gdscript next to C#, which *does* have a parser, it'll be very visibly different to look at.

Thoughts?  Any takers who are good with regex?

**Comment by akien-mga** [comment]
You mean this? :)
- https://github.com/godotengine/godot-docs/blob/master/extensions/gdscript.py
- https://bitbucket.org/birkenfeld/pygments-main/pull-requests/617/added-gdscript-lexer/diff

**Comment by akien-mga** [comment]
BTW @djrm, we should probably update the lexer for 3.0 (both here and on your upstream PR), and then make some more noise upstream for them to actually start looking at it after one year.

**Comment by djrm** [comment]
@akien-mga i updated it to 3.0 recently #452, but let me know if there is something missing

**Comment by djrm** [comment]
also yeah, i should create a new PR to pygments, and see if i can get it merged

**Comment by cbscribe** [comment]
Ah!  I just looked here: https://bitbucket.org/birkenfeld/pygments-main/src/7941677dc77d4f2bf0bbd6140ade85a9454b8b80/pygments/lexers/ and didn't see it!

**Comment by djrm** [comment]
@akien-mga here is the new PR https://bitbucket.org/birkenfeld/pygments-main/pull-requests/732/added-gdscript-lexer/diff

lets see if we can get it merged

**Comment by NathanLovato** [comment]
GDScript is available in pygments and chroma now, closing
