### ISSUE TITLE
Where is the "Set" method in AnimationTree class doc?

### ISSUE THREAD

**Issue by Torguen** [godotengine/godot-docs#4721]
**Your Godot version:**
3.2.4 rc3 mono

**Issue description:**
The "Set" method that can be seen in the official AnimationTree tutorial is not documented in the documentation for the AnimationTree class.

Tutorial:
https://docs.godotengine.org/es/stable/tutorials/animation/animation_tree.html#controlling-from-code

![Captura2](https://user-images.githubusercontent.com/19652075/109971413-83cd4900-7cf6-11eb-9e44-cfa57a0113a9.PNG)

**URL to the documentation page:**
Class AnimationTree, where is the "Set" method?

https://docs.godotengine.org/es/stable/classes/class_animationtree.html#class-animationtree

**Comment by pycbouh** [comment]
`set` is a method of the basic `Object` class:
https://docs.godotengine.org/es/stable/classes/class_object.html#id4

**Comment by Torguen** [comment]
Ohh, Ok! Thanks.
