### ISSUE TITLE
iOS plugin documentation for the 3.2 branch

### ISSUE THREAD

**Issue by mbrlabs** [godotengine/godot-docs#4735]
**Your Godot version:**
3.2.4 rc4

**Issue description:**
I think all the documentation PRs (#4213 and #4693) dealing with the new iOS plugin system targeted `master` and not `3.2` and have not been cherry-picked. I don't know what the workflow here is, but this should probably be included in the `3.2` documentation branch before 3.2.4 ships ;)

**URL to the documentation page:**
See the linked PRs

**Comment by skyace65** [comment]
Closed by #4737.
