### ISSUE TITLE
Document the bitmap font import and usage workflow

### ISSUE THREAD

**Issue by davthedev** [godotengine/godot-docs#4743]
### Describe the project you are working on

A 2D game that uses bitmap fonts

### Describe the problem or limitation you are having in your project

I have a bitmap font in Angelcode, .fnt file fomat, created using BMFont (https://www.angelcode.com/products/bmfont/) .
I can import this font format without issue in Godot; it is automatically converted into an appropriate BitmapFont resource.

Here is an example for you to try: 
[bitmap_font_resource_example.zip](https://github.com/godotengine/godot-proposals/files/6125209/bitmap_font_resource_example.zip)

To get the file imported, I have to
- Select a Label node, for example, and target its Custom Font property
- Click "Load" in the font resource slot submenu. The file chooser appears. The .fnt file does not show up inside the explorer.
- Set the file type filter to All files
- Now all file types are visible, I can select my .fnt file

From this point, the bitmap font is correctly imported and can be used. But it is not straightforward to get it done.

My first reflexe was to create a new BitmapFont and add the .fnt file from there, which is not possible. This is confusing. I had to guess the correct procedure with trial and error. No documentation was found either about that possibility, which gives great results for my needs. This deserves to be more visible!

As far as I can remember, there was a way to generate bitmap fonts inside Godot 2. It was removed. Is the feature treated as an easter egg? Seems so! :smile: 

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

- In the Font resource import dialog, add an option for .fnt files and make them visible by default as recognized file type.
- Document the bitmap font import process.

Maybe: rework the overall font import UX so that the process is similar for bitmap and dynamic fonts.

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

The .fnt file is added as a recognizable type from the Font resource import dialog.

### If this enhancement will not be used often, can it be worked around with a few lines of script?

No, it is a UX issue.

### Is there a reason why this should be core and not an add-on in the asset library?

Font resources are part of the core.

**Comment by davthedev** [comment]
> The bitmap font generation feature was never reimplemented in Godot 3.x because bitmap fonts are generally on the way out. For most games, using DynamicFont is a better idea (and MSDF in 4.0). When using pixel art fonts, you can disable antialiasing in the DynamicFontData resource.

If the font is from a TTF file, disabling the antialiasing is enough, sure!

My case covers pixel fonts that are read from images & descriptor files; not proper TTF font files. Initially I can render a character grid from a TTF font, and this is fine to use an external software for that. Next, I edit the rendered characters in their bitmap form to add gradients, details & colors. Alternately, I can draw my glyphs from scratch, pixel by pixel.
See examples of such fonts there : https://opengameart.org/content/bitmap-font-pack.

Do you mean that deprecation of .fnt file support is on the roadmap?

**Comment by Calinou** [comment]
> Do you mean that deprecation of .fnt file support is on the roadmap?

No, but we don't intend to implement an official bitmap font generator.
