### ISSUE TITLE
Document upgrading a project between Godot versions

### ISSUE THREAD

**Issue by Calinou** [godotengine/godot-docs#4744]
We should have a documentation page about upgrading from a Godot version to another (e.g. 2.x to 3.2, 3.2 to 4.0). It should document all breaking changes, what to do and give a rough estimate of the time required/complexity of each task.

See the [Laravel upgrade guide](https://laravel.com/docs/8.x/upgrade) for an example of such a page.

## Suggested table of contents

- *Foreword:* Should I upgrade my Godot version?
  - Mention example cases where this is a good idea, and other cases where this is a bad idea.
- Link to the [Godot release policy](https://docs.godotengine.org/en/latest/about/release_policy.html) page
- Subpage about upgrading from 2.x to 3.2
- Subpage about upgrading from 3.2 to 4.0

**Comment by skyace65** [comment]
I'm not sure if there's a reason to make a 2.x to 3.2 guide now. I feel like anyone who was going to upgrade their project would have done so already.

**Comment by hsandt** [comment]
In the meantime we got https://docs.godotengine.org/en/latest/tutorials/migrating/upgrading_to_godot_4.html to upgrade from Godot 3 to 4.

Should we close this issue as we consider the job done, or recycle it to track what's left to do on said page?

**Comment by Calinou** [comment]
Closing per @hsandt's comment.
