### ISSUE TITLE
Specify that KinematicBody uses up_direction in move_and_slide() for is_on_floor(), is_on_ceiling() and is_on_wall()

### ISSUE THREAD

**Issue by maksutheam** [godotengine/godot-docs#4747]
**Your Godot version:**
3.2.3-stable

**Issue description:**
Today I spend an hour figuring out why my KinematicBodys `is_on_floor()` function returned `false`, even though I was calling `move_and_slide()` and the KinematicBody was clearly on the floor. It was because `is_on_floor()` uses `up_direction` in `move_and_slide()` to determine if it collides with a ceiling, a wall or a floor, but this value is set to (0, 0) by default, so it considers every collision to be a wall.

I would suggest that the description for `is_on_floor()` (also `is_on_ceiling()` and `is_on_wall()` too, since their descriptions are very similar) would be amended to
"Returns `true` if the body is on the floor/wall/ceiling. Only updates when calling `move_and_slide`, based on the `up_direction` value passed to that function".
This way it would be more clear that they specifically use `up_direction` to check for floors/walls/ceilings, and the user could notice that everything is a wall by default.

**URL to the documentation page (if already existing):**
https://docs.godotengine.org/en/latest/classes/class_kinematicbody.html#class-kinematicbody-method-is-on-floor
https://docs.godotengine.org/en/latest/classes/class_kinematicbody.html#class-kinematicbody-method-is-on-ceiling
https://docs.godotengine.org/en/latest/classes/class_kinematicbody.html#class-kinematicbody-method-is-on-wall

**Comment by tetrapod00** [comment]
This was resolved by https://github.com/godotengine/godot/pull/56631.
