### ISSUE TITLE
ReferenceRect documents more variables than exist (border_width)

### ISSUE THREAD

**Issue by gabeklavans** [godotengine/godot-docs#4750]
**Your Godot version:**
3.2.3 stable mono

**Issue description:**
The online docs for stable list `ReferenceRect` as having the `border_width` property, but the in-editor docs do not list this and when trying to set this property the engine generates this error:
```
"Invalid set index 'border_width' with value of type 'float'."
```

**URL to the documentation page:**
https://docs.godotengine.org/en/stable/classes/class_referencerect.html#class-referencerect-property-border-width

**Comment by Calinou** [comment]
This is because the property in question was added in 3.2.4 beta, not 3.2.3. See https://github.com/godotengine/godot-docs/issues/4616.

**Comment by gabeklavans** [comment]
Ah ok, thanks for the ref. 

Just curious, do you know why the doc release didn't get synced with the engine release? I can understand delays and such since it's all voluntary work, of course, but was there some other outstanding delay involved?

**Comment by Calinou** [comment]
> Just curious, do you know why the doc release didn't get synced with the engine release? 

It was done by mistake and wasn't reverted.

**Comment by gabeklavans** [comment]
> It was done by mistake and wasn't reverted.

Gotcha. Can't wait for the release!
