### ISSUE TITLE
I can find no information in the manual about how the two "Loop Wrap" modes in the Animation Player differ

### ISSUE THREAD

**Issue by Arnklit** [godotengine/godot-docs#4761]
**Your Godot version:**
3.2.4.RC5

**Issue description:**
I can find no information in the manual about how the two "Loop Wrap" modes in the Animation Player differ.
<img width="327" alt="Godot_v3 2 4-rc5_win64_jUD4ItByrU" src="https://user-images.githubusercontent.com/4955051/111632114-0fad9d80-87ec-11eb-80f9-a8227dbdf70e.png">
Searching for "Loop Wrap" or "Clamp Loop" or "Wrap Loop" return no useful results.

**URL to the documentation page:**
NA

**Comment by skyace65** [comment]
The differences are already documented here https://docs.godotengine.org/en/stable/tutorials/animation/introduction_2d.html

**Comment by skyace65** [comment]
When searching "wrap loop" the information on that page is the third result
<img width="1193" alt="Screen Shot 2021-03-19 at 7 59 09 AM" src="https://user-images.githubusercontent.com/6080368/111777161-4a194800-8889-11eb-915b-99bd30ec0c93.png">

**Comment by Arnklit** [comment]
Ah my bad. I never use 2D and was animating 3D characters so my brain just dismissed an article mentioning 2D out of hand. Should that not be moved to a general article about the animation player instead then?

**Comment by skyace65** [comment]
That page was renamed in the master branch already since it's general animation information. I'll open a PR tonight and see if it can be changed for the 3.2 branch

**Comment by skyace65** [comment]
@Calinou can you close this issue please? For some reason the PR getting merged didn't do it.
