### ISSUE TITLE
Explain zip/pck exporting in more detail

### ISSUE THREAD

**Issue by JamesC01** [godotengine/godot-docs#4768]
**Your Godot version:**
3.2.3

**Issue description:**
The documentation here: is unclear. It doesn't explain that you have to extract the zip file in order for it to work with the .exe. I assumed the exe would load the zip file, like it does with the pck file, based on what is written in the docs.

**URL to the documentation page (if already existing):**
[exporting projects](https://docs.godotengine.org/en/stable/getting_started/workflow/export/exporting_projects.html#pck-versus-zip-pack-file-formats)

**Comment by Calinou** [comment]
>  It doesn't explain that you have to extract the zip file in order for it to work with the .exe. 

You don't need to extract the generated ZIP file – in fact, you shouldn't. It works exactly like a PCK file, except it has a different format.

However, [automatically loading the ZIP file is currently broken](https://github.com/godotengine/godot/pull/42123). As a workaround, you can create a launcher script that uses the `--main-pack` command line argument to specify the path to the ZIP file.

**Comment by JamesC01** [comment]
Thanks. I suppose the only problem I have with godot right now, is knowing if something is an engine bug, or if I'm not doing something properly. I think it should be mentioned in the documentation that it's broken. Also, do you have any idea when this will be fixed? Will godot 3.3 fix it?

**Comment by Calinou** [comment]
> Thanks. I suppose the only problem I have with godot right now, is knowing if something is an engine bug, or if I'm not doing something properly. I think it should be mentioned in the documentation that it's broken.

This is what https://github.com/godotengine/godot-docs/pull/4771 does :slightly_smiling_face: 

> Also, do you have any idea when this will be fixed? Will it be fixed in godot 3.3?

I don't know if the fix will be merged in time for 3.3.

> Also, while I'm here, the zip file doesn't include all images in the original project, despite the images having the same format and import settings. Is this another engine bug, or have I done something wrong?

Like PCK exporting, the ZIP archive will only contain files that are considered *resources* by Godot. To export files that aren't resources, you need to add them to the non-resource export filter in the Export dialog.

**Comment by JamesC01** [comment]
> Like PCK exporting, the ZIP archive will only contain files that are considered _resources_ by Godot. To export files that aren't resources, you need to add them to the non-resource export filter in the Export dialog.

That also doesn't work. I put *.png in the non-resource export filter, and out of floor_tiles.png and icon.png, icon.png only ends up in the zip. floor_tiles.png is being used in the test, but only the .import shows up in the zip.

**Comment by Calinou** [comment]
> And also, the floortiles are considered a StreamTexture in the inspector, so that's a resource, right?

Yes. Is `floor_tiles.png` used anywhere in the project's scene files?

**Comment by JamesC01** [comment]
> Yes. However, is `floor_tiles.png` used anywhere in the project's scene files? Is it placed inside a folder that contains a `.gdignore` file?

Yes, it's in the same folder as the icon.png "Assets", and it's used multiple times in multiple scenes as the texture property for Sprite.

**Comment by JamesC01** [comment]
I've tried doing this with multiple projects. Even the basic "dodge the creeps" tutorial. It only exports the icon.png, and ignores all other .png's. It kept the font in the zip, though.

**Comment by JamesC01** [comment]
@Calinou Hey, did you see my previous messages? Do you this this is a bug with the engine?

**Comment by Calinou** [comment]
> @Calinou Hey, did you see my previous messages? Do you think this is a bug with the engine?

Maybe. I can't know for certain without access to a minimal reproduction project. If you can upload one, please create an issue on the main Godot repository.

**Comment by JamesC01** [comment]
Will do.
