### ISSUE TITLE
Doc search results in web browser show `function(n){return e.call(this,n,tn)}` instead of any results in 3.2/3.3/stable

### ISSUE THREAD

**Issue by 31** [godotengine/godot-docs#4786]
**Your Godot version:**
`stable`, `3.2`, `3.3` online docs.

Doesn't occur in `latest`.

**Issue description:**
The "instant" search results look like this:

![image](https://user-images.githubusercontent.com/331300/112741152-6cc1f580-8f48-11eb-988d-0a719a15fa7a.png)

Pressing enter takes me to a page that does work, although it took me a while to realize I could do that. 😄 

Expected, more like `latest`:

![image](https://user-images.githubusercontent.com/331300/112741166-9d099400-8f48-11eb-94b7-2fa9faf97335.png)

Running Windows 10, repros on Chrome 89.0.4389.90, Edge 89.0.774.63, Firefox 87.0.

No errors show up in the debug console. 😕 

**URL to the documentation page:**
Example:
https://docs.godotengine.org/en/stable/index.html?rtd_search=raycast
https://docs.godotengine.org/en/3.2/index.html?rtd_search=raycast
https://docs.godotengine.org/en/3.3/index.html?rtd_search=raycast
Works in latest:
https://docs.godotengine.org/en/latest/index.html?rtd_search=raycast

**Comment by Calinou** [comment]
Tentative fix, we'll see if it works in ~30 minutes: https://github.com/godotengine/godot-docs/commit/09f1bce2de5f7af5517e3ca8ccb9d974f7a871d7

**Comment by 31** [comment]
This is now working for me in all three branches. Thanks! 🎉
