### ISSUE TITLE
GetNode() Inconsistencies (C#)

### ISSUE THREAD

**Issue by BlueStaggo** [godotengine/godot-docs#4794]
**Your Godot version:**
stable

**Issue description:**
For C#, some pages get nodes like this: `var node = GetNode<Node>("Node");`
Other pages do this: `var node = (Node) GetNode("Node");`
Why can't it all be the same? I'd suggest `GetNode<T>()` instead of `(T) GetNode()`.

**URL to the documentation page (if already existing):**
`var animSprite = GetNode<AnimatedSprite>("AnimatedSprite");` [Your first game](https://docs.godotengine.org/en/stable/getting_started/step_by_step/your_first_game.html#enemy-script)
`var node2D = (Node2D) GetNode("Node2D");` [Vector math](https://docs.godotengine.org/en/stable/tutorials/math/vector_math.html#vector-operations)
Make sure to show C# and not GDScript.

**Comment by akien-mga** [comment]
Fixed by #4876.
