### ISSUE TITLE
Explain how to scale pixel art perfectly

### ISSUE THREAD

**Issue by ShatReal** [godotengine/godot-docs#4804]
**Your Godot version:**
3.3 rc7
**Issue description:**
I see people asking this question a lot - why are my pixels not the same size? I think the docs should explain that just setting a Stretch Aspect isn't enough to have perfect pixel scaling - you also need to scale by a whole number factor.
**URL to the documentation page (if already existing):**
https://docs.godotengine.org/en/latest/tutorials/rendering/multiple_resolutions.html

**Comment by Calinou** [comment]
Integer scaling isn't trivial to implement, as it requires more than a few lines of code. We'd probably have to link to a script such as https://github.com/Yukitty/godot-addon-integer_resolution_handler.

**Comment by golddotasksquestions** [comment]
> Integer scaling isn't trivial to implement

@Calinou It is fairly easy. Maybe we can make a small demo project? There is not much more to it than [this](https://www.reddit.com/r/godot/comments/mhperh/why_is_my_pixel_art_game_stretching_like_this/gt0yw2x?utm_source=share&utm_medium=web2x&context=3).
Maybe we can also make a docs page that lists [all these steps here](https://www.reddit.com/r/godot/comments/fah25e/best_way_to_achieve_pixel_perfect_rendering/fiydmwz?utm_source=share&utm_medium=web2x&context=3)?
How to get pixel art game to look as expected (which usually means pixel perfect)  is really one of the most frequent questions on the community channels. Godot default settings are not pixelart friendly at all. A docs page and demo would be a great step to rectify this and to give community members a page to direct newcomers to.

**Comment by Calinou** [comment]
This was documented by https://github.com/godotengine/godot-docs/pull/5027, closing.
