### ISSUE TITLE
Quanternion SLERP function has incorrect parameter names in description

### ISSUE THREAD

**Issue by Saitodepaula** [godotengine/godot-docs#4805]
**Your Godot version:**
3.2.4 rc3 official

**Issue description:**
Quaternion SLERP function is described as below:

`Quat slerp ( Quat b, float t )`

But then, the description uses the terms **TO** and **WEIGHT**, not **B** and **T**.

`Returns the result of the spherical linear interpolation between this quaternion and to by amount weight.`

The SLERPNI function has the same issue.

**URL to the documentation page:**
https://docs.godotengine.org/en/stable/classes/class_quat.html#class-quat-method-slerp

**Comment by kleonc** [comment]
Fixed by https://github.com/godotengine/godot/pull/48105.

**Comment by Calinou** [comment]
Closing per @kleonc's comment. Note that the online version will only be updated on the class reference is synchronized with the one from the main Godot repository.
