### ISSUE TITLE
Document the scene inheritance concept and possible workflows

### ISSUE THREAD

**Issue by akien-mga** [godotengine/godot-docs#481]
Moved from https://github.com/godotengine/godot/issues/3354.

@kubecz3k had started to work on a demo back then.

**Comment by DevmanAuthor** [comment]
hi

**Comment by aaronfranke** [comment]
I recommend that the documentation for this has a section that compares it to other engines. Godot scenes are basically the same as Unity's Prefabs on top of being runnable scenes.

**Comment by mason-bially** [comment]
So there is currently a section in the docs that compares Unity's prefabs to the Godot scene system (while explaining the scene system) that seems like a place to start on a scene system description.

What would layout for this documentation look like? This feels like it should be in the "Getting Started" area somewhere. And perhaps move some of the disparate information into it and link back and flesh out some of the related areas (unity prefabs, project workflows, etc.)

Actually right now it seems like best practices includes quite a bit of information about the scene system.

**Comment by synalice** [comment]
I'd say this issue can be safely closed. All that's being discussed here already exists in the documentation:

- https://docs.godotengine.org/en/stable/getting_started/introduction/key_concepts_overview.html#overview-of-godot-s-key-concepts
- https://docs.godotengine.org/en/stable/getting_started/introduction/godot_design_philosophy.html#object-oriented-design-and-composition

**Comment by tetrapod00** [comment]
I do think that Scene Inheritance could be documented more. There is not a lot of information in this issue, and https://github.com/godotengine/godot-docs/issues/5529 is more recent and has some more discussion, so I'm consolidating this into that issue.
