### ISSUE TITLE
Section titles in left sidebar lost style; API bullet points missing

### ISSUE THREAD

**Issue by 31** [godotengine/godot-docs#4813]
**Your Godot version:**
latest, stable, 3.2, 3.3

---
**Issue description:**
The section titles no longer have style:
![image](https://user-images.githubusercontent.com/331300/113543960-0a52a000-95ad-11eb-8118-f3773c9998b2.png)

API bullet points are missing:
> ![image](https://user-images.githubusercontent.com/331300/113544038-2bb38c00-95ad-11eb-9c40-f38d47f6925e.png)

Expected:
![image](https://user-images.githubusercontent.com/331300/113543974-0fafea80-95ad-11eb-8cdd-50128a97e2a7.png)
> ![image](https://user-images.githubusercontent.com/331300/113543998-18a0bc00-95ad-11eb-8b15-1f561e10f9f4.png)

---

Looks like the section labels lost their classes:

was: `<p class="caption"><span class="caption-text">General</span></p>`
now: `<p><span class="caption-text">General</span></p>`

---

**URL to the documentation page:**
Screenshots from:
https://docs.godotengine.org/en/stable/classes/class_collisionobject.html#class-collisionobject-method-input-event
(I happened to have an old tab open with the old state for the old screenshots.)

**Comment by akien-mga** [comment]
See https://mobile.twitter.com/readthedocs/status/1379112319590965249 - cc @Calinou

**Comment by akien-mga** [comment]
Should be fixed by #4818.
