### ISSUE TITLE
@GDScript move_toward(from, to, delta) expects two arguments not three, return value is not always a float

### ISSUE THREAD

**Issue by golddotasksquestions** [godotengine/godot-docs#4820]
**Your Godot version:**
Godot 3.2.3 stable, Godot 3.3 rc7

**Issue description:**
The method description says there are three arguments and explains the use of all three, while in actuality the code demands for only two arguments: "to" and "delta".
Also the API documentation says it returns a float, while it can be used with Vector2s as well (returning a Vector2).
delta can also be integer or float value, but strangely enough not a Vector2.

testcode:
```swift
var test_vec = Vector2(100,100)

func _process(delta):
	test_vec = test_vec.move_toward(Vector2.ZERO, 5)
	print(test_vec)
```

**URL to the documentation page:**
https://docs.godotengine.org/en/stable/classes/class_@gdscript.html#class-gdscript-method-move-toward

**Comment by akien-mga** [comment]
You're confusing the builtin method `move_toward` (which is not a member method of a class) with the `Vector2` member method of the same name: https://docs.godotengine.org/en/stable/classes/class_vector2.html#class-vector2-method-move-toward

The builtin one is for use on types like `int` and `float` (you can't do `1.0.move_toward(2.0, 0.5)` but you can do `move_toward(1.0, 2.0, 0.5)`.

**Comment by golddotasksquestions** [comment]
Well the documentation is still wrong when I Ctrl click on move_toward. @akien-mga

**Comment by akien-mga** [comment]
That's a bug with the editor then, not the documentation. It's confusing the two.
