### ISSUE TITLE
Impossible to document methods not exposed in GDScript

### ISSUE THREAD

**Issue by frankiezafe** [godotengine/godot-docs#4821]
**3.2**

**Issue description:**
I'm trying to build a complete documentation of a complex class. Therefore, I have created an xml for this class, and added a tag 'method' for protected methods (only a few of them). When I compile, I get a list of  'error: no declaration matches' for all methods not referenced in '_bind_method'. Is there a way to avoid this error by providing a special tag in the xml?

The code is complex enough to buidl a consistent description of its process.

**URL to the documentation page:**
https://gitlab.com/polymorphcool/godot_module_boids/-/commit/7e130cd6c9aeef17636ae996d5090c498f90f42c

**Comment by akien-mga** [comment]
The XML class reference is only intended for the scripting API exposed to scripting languages (GDScript, C#, VisualScript, GDNative, etc.).

To document the C++ API of your module, you'll have to use another system (e.g. doxygen).

**Comment by frankiezafe** [comment]
Ok, got it.
