### ISSUE TITLE
Android Export fails.

### ISSUE THREAD

**Issue by ca3games** [godotengine/godot-docs#4826]
**Your Godot version:**
3.2.3

**Issue description:**
Android export fails, It says "It can't find keystore" even after following the documentation steps.

**URL to the documentation page:**
https://docs.godotengine.org/en/stable/getting_started/workflow/export/android_custom_build.html

**Comment by Calinou** [comment]
Please don't ask support questions here, as this issue tracker is meant to be used for bug reports only. Use one of the other [community channels](https://godotengine.org/community) instead.
