### ISSUE TITLE
Complying with licenses contradicts godotengine.org/license

### ISSUE THREAD

**Issue by ShatReal** [godotengine/godot-docs#4828]
**Your Godot version:**
3.2.3
**Issue description:**
"Complying with licenses" says that the dev must "include the license text" while godotengine.org/license states that the dev just has to link to that page.
**URL to the documentation page:**
https://docs.godotengine.org/en/latest/about/complying_with_licenses.html

**Comment by LikeLakers2** [comment]
I'm assuming we're referring only to the Godot Engine license, and not the licenses for the third-party libraries?

If so, I would like to point out one section, [Inclusion](https://docs.godotengine.org/en/latest/about/complying_with_licenses.html#inclusion), on that page: 

> The license does not specify how it has to be included, so anything is valid as long as it can be displayed under some condition. These are the most common approaches (only need to implement one of them, not all).

For the Godot Engine at least, this does not seem to contradict this line from <https://godotengine.org/license>:

> The Godot Engine developers consider that a link to this page (godotengine.org/license) in your game documentation or credits would be an acceptable way to satisfy the license terms. 

To elaborate: In this case, the line from the documentation states that you must allow the license to be displayed in some way. Meanwhile, the line from the website license page elaborates on this, by saying that the developers consider a link to that page to be a way of displaying the license.

Of course, I am no legal professional, so if you have any doubts, it's not too hard to copy-paste Godot's LICENSE file.

That said, it may be worth editing the documentation page to explicitly mention "Linking to <https://godotengine.org/license> is a valid way of satisfying the license". That is, assuming that the Godot team actually means it the way I explained above.

**Comment by pycbouh** [comment]
You don't even need to copy it, you can simply use a method

https://docs.godotengine.org/en/stable/classes/class_engine.html#class-engine-method-get-license-text

**Comment by ShatReal** [comment]
> > Of course, I am no legal professional, so if you have any doubts, it's not too hard to copy-paste Godot's LICENSE file.
> 
> You don't even need to copy it, you can simply use a method
> 
> https://docs.godotengine.org/en/stable/classes/class_engine.html#class-engine-method-get-license-text

Wow I had no clue that method existed lol
