### ISSUE TITLE
Error in tutorial "Your first Spatial shader: part 2"

### ISSUE THREAD

**Issue by Imerion** [godotengine/godot-docs#4830]
**Your Godot version:**
3.2.3

**Issue description:**
There are two parts of the tutorial that seem to be wrong, making the tutorial fail unless you have good knowledge of how shaders work.

The first is a simple miss:
>float height(vec2 position, float time) {
>  float h = wave(position);
>}

To work, it should read:
>float height(vec2 position, float time) {
>  float h = wave(position);
>  return h;
>}

The other might be due to my incompetence, but as it is in the tutorial it produces the error "error(16): No matching function found for: wave". This seems to be due to the part marked in bold here:
>float height(vec2 position, float time) {
>  float d = wave((position + time) * 0.4, **8.0**) * 0.3;
>  d += wave((position - time) * 0.3, **8.0**) * 0.3;
>  d += wave((position + time) * 0.5, **4.0**) * 0.2;
>  d += wave((position - time) * 0.6, **4.0**) * 0.2;
>  return d;
>}

Removing the bold parts above makes the shader work, though I'm not sure how these values were supposed to be included. 

Perhaps it should read:
>float height(vec2 position, float time) {
>  float d = wave((position + time) * 0.4 * 8.0) * 0.3;
>  d += wave((position - time) * 0.3 * 8.0) * 0.3;
>  d += wave((position + time) * 0.5 * 4.0) * 0.2;
>  d += wave((position - time) * 0.6 * 4.0) * 0.2;
>  return d;
>}

**URL to the documentation page:**
https://docs.godotengine.org/en/3.1/tutorials/shading/your_first_shader/your_second_spatial_shader.html

**Comment by clayjohn** [comment]
You are looking at an old version of the docs. Those issues are already resolved in stable. We should be able to just backport the PRs to the 3.1 version of the docs though.

**Comment by Imerion** [comment]
Oh, I see! I'm sorry, must have ended up there by accident. Should I close this issue?

**Comment by Calinou** [comment]
I cherry-picked the fix to the `3.1` branch: https://github.com/godotengine/godot-docs/commit/f3607cb52a9ff50b6bea125ea9a533596ad6e69a

**Comment by Imerion** [comment]
Yes, that looks good!
