### ISSUE TITLE
2D Movement Overview: Rotation + Movement Incorrect

### ISSUE THREAD

**Issue by Aiyush-G** [godotengine/godot-docs#4841]
Current Stable Version of the Docs. ([https://docs.godotengine.org/en/stable/tutorials/2d/2d_movement.html](https://docs.godotengine.org/en/stable/tutorials/2d/2d_movement.html)) 

The Rotation + Movement (Asteroids Style) appears to be incorrect. The Vector2() of input 'up' and 'down' have the x and y co-ordinates the wrong way around. It should be:

```
if Input.is_action_pressed("down"):
        velocity = Vector2(0, -speed).rotated(rotation) # Error Was Here
    if Input.is_action_pressed("up"):
        velocity = Vector2(0, speed).rotated(rotation) # Error Was Here
```

This is my first contribution to Godot :)

EDIT: This may have been the intended behaviour at the time, however, this sort of movement is unintuitive and the above makes more sense.

Thanks
AG

**Comment by golddotasksquestions** [comment]
Welcome welcome!
Hm, I have tested this code right now, with the code copied straight from the documentation, as well as your code.

Can you describe what makes the current movement unintuitive for you?
To me it seems like it moves exactly how I wold expect it to (towards the mouse position and away from the mouse position):

Documentation code:

https://user-images.githubusercontent.com/47016402/115115174-28e46e00-9f93-11eb-94a8-4fd325cab8d8.mp4

While I find your proposed code change very interesting as a controller, I honestly find it also much more confusing: The KB rotates around the mouse position. The further the mouse form the KB, the greater the the radius of rotation. It's a lot harder to control where to move the KB to. The mouse position as target location to move to does not really work anymore:

https://user-images.githubusercontent.com/47016402/115115315-13bc0f00-9f94-11eb-81e0-79d77686e532.mp4

This control scheme change however could be very interesting if one would like to switch from a freely moving KB to one that is locked in an orbit of a planet for example. But I'm not sure if that would be a too specific example/usecase for this page, what do you think?

**Comment by Aiyush-G** [comment]
Hmmm... upon second thoughts your analysis makes complete sense. In order to maintain snippets of code , alike the ones provided above (alongside a short informative video, like the one kindly provided) I believe that we should look into creating a repository where we can collate and host snippets of code / mechanics that would be useful to others. I reckon that we could do this in a different repo alongside a GitHub pages so we can allow people to view these on a statically generated website. In terms of submission that could be done by opening up and issue or I could integrate something into the website that allows this. I think that this is very different to the current asset store as the assets within it are rather broad and complement rather large mechanics in comparison to this? What are your thoughts on this idea? I would be more than happy to help head-up the process. Although at the start it shouldn’t be tricky.

Kindest
Regards

**Comment by golddotasksquestions** [comment]
Yeah I think that sounds like a great idea. Just a collection of short and simple controller scripts, with a video next to them so you can immediately see what they do. All the Godot user would have to do is to copy and paste it into their scene and it immediately works.

**Comment by Aiyush-G** [comment]
Yes exactly, I'll work on it in my own repo when I get time and then overtime it could be expanded to other scripts that should be useful :)

**Comment by golddotasksquestions** [comment]
If you now don't think anymore the example script in the docs should be changed, you can now safely close this issue.
