### ISSUE TITLE
Incorrect spelling of "Example" in FAQs

### ISSUE THREAD

**Issue by CoderNinja123** [godotengine/godot-docs#4859]
```
**Your Godot version:**

**Issue description:**

**URL to the documentation page:**
```

(Sorry if these fields were important, this is actually a spelling error in the docs that I found, not with the actual engine)

In the FAQs page [(here)](https://docs.godotengine.org/en/stable/about/faq.html), if you scroll down to [here](https://docs.godotengine.org/en/stable/about/faq.html#why-does-godot-aim-to-keep-its-core-feature-set-small), instead of "example", "exemple" was written in the following sentence:

> One exemple of this would be advanced artificial intelligence functionality.

**Comment by pycbouh** [comment]
> Sorry if these fields were important

Well, you've actually provided the answers to the second and third sections anyway 🙄 And Godot version an be important because the docs are also versioned.

Feel free to open a PR if you want for this typo.

**Comment by CoderNinja123** [comment]
Whoops! Looks like I didn't pay a lot of attention to the fields. I'll update the issue anyway. Thanks!
