### ISSUE TITLE
Project Settings page should mention Feature Tag overrides

### ISSUE THREAD

**Issue by Gromph** [godotengine/godot-docs#4860]
**Your Godot version:**
3.3

**Issue description:**
Several times I searched for how to override project settings per platform and some how didn't find the page about using Feature Tags to override project settings. I actually found out about it by looking at the source code for project_settings.cpp

So I'm suggesting to mention and link to the Feature Tags page: https://docs.godotengine.org/en/3.3/getting_started/workflow/export/feature_tags.html

On the Project Settings Page:
https://docs.godotengine.org/en/stable/classes/class_projectsettings.html

**URL to the documentation page (if already existing):**
https://docs.godotengine.org/en/stable/classes/class_projectsettings.html

**Comment by Calinou** [comment]
This is already mentioned at the top of the page: https://github.com/godotengine/godot/blob/c7b97f077a0f62d9e280adbddddc901f35e4f40f/doc/classes/ProjectSettings.xml#L9

**Comment by pycbouh** [comment]
Please don't close the issue as the PR has not yet been merged.
