### ISSUE TITLE
M1 MAC complie code to Application 

### ISSUE THREAD

**Issue by RobThePole** [godotengine/godot-docs#4875]
**Godot version 3.3**

**Going through the steps on the Godot page for compling with a M1 Mac to complie the stable release does not work without changing the code for building**

**https://docs.godotengine.org/en/stable/development/compiling/compiling_for_osx.html:**

**The code here needs to be replace for building a application version of Godot** 

**cp -r misc/dist/osx_tools.app ./Godot.app mkdir -p Godot.app/Contents/MacOS cp bin/godot.osx.opt.tools.universal Godot.app/Contents/MacOS/Godot chmod +x Godot.app/Contents/MacOS/Godot**

**The code below is the fixed version here is a link to video made by me compling and running the code below

https://youtu.be/yafTKFZ3nbs

time stamp is 5:20 **

**cp -r misc/dist/osx_tools.app ./Godot.app mkdir -p Godot.app/Contents/MacOS cp bin/godot.osx.tools.universal Godot.app/Contents/MacOS/Godot chmod +x Godot.app/Contents/MacOS/Godot

** unverified change to the documentation under the user bruvzg if you look at the history under the GitHub page for the documentation **

**Comment by akien-mga** [comment]
The instructions is correct, it's for a build done with `target=release_debug` (while by default if you don't specify the target, it's `target=debug`, i.e. unoptimized).

It's mentioned on the line before the one you want to edit, but it could be made clearer by using `target=release_debug` from the start.

**Comment by RobThePole** [comment]
This is my first time posting a bug report so should I go in and edit the compiling for macOS page and go in and update the compile options to use target=release_debug by default instead?

**Comment by Calinou** [comment]
Clsoing, as build target options have changed in 4.0 in favor of `target=editor`, `target=template_debug` and `template=release`. The rest of the documentation has been updated to explain how to build Universal 2 export template binaries (Intel + Apple Silicon).
