### ISSUE TITLE
Property formatted shortcuts display with spaces on the documentation website

### ISSUE THREAD

**Issue by pycbouh** [godotengine/godot-docs#4879]
**Your Godot version:**
Any.

**Issue description:**

After one of the recent RTD updates shortcuts made with `:kbd:` started to show up with broken visuals. We use spaces for nice formatting of key bindings, <kbd>Ctrl + Alt + Del</kbd>, but those spaces seem to be handled as individual entities now, resulting in this:

![chrome_2021-04-27_19-39-44](https://user-images.githubusercontent.com/11782833/116284394-b72bd180-a795-11eb-87b7-23ae87205926.png)
![chrome_2021-04-27_19-58-22](https://user-images.githubusercontent.com/11782833/116284402-b8f59500-a795-11eb-95cd-ab9be176e121.png)

Layout now suggests that every sequence of characters between spaces and spaces themselves are now wrapped in individual tags. I guess that we need to adjust styles from referring to `.kbd` to start referring to `.kbd.compound`.

![chrome_2021-04-27_19-58-42](https://user-images.githubusercontent.com/11782833/116284490-cf035580-a795-11eb-84d6-113ac88d2093.png)

Though that's not the case for single keys, so a fix would probably be more complicated than that:

![image](https://user-images.githubusercontent.com/11782833/116285145-85ffd100-a796-11eb-814f-f8bff120c43f.png)

**URL to the documentation page:**
Related to all articles with key bindings mentioned. Here's one for example: https://docs.godotengine.org/en/stable/getting_started/scripting/gdscript/gdscript_styleguide.html#comment-spacing

**Comment by hpnrep6** [comment]
Adding the style:
`.kbd:empty {
    display: none;
}`

seems to solve this issue, but that seems a bit too hacky.  (and _might?_ cause some formatting issues if spaces were used intentionally, though not entirely sure how common that use case is)

**Comment by pycbouh** [comment]
Spaces are indeed used intentionally, but that doesn't solve the issue, it only hides the spaces. The problem is that after some changes on the RTD side of things the layout now has nested `.kbd` elements. This creates unnecessary wrapping around each button identifier (and each space) on top of the styling applied to the topmost `.kbd` element.

Your proposed change hides the whitespaces, but it still has the unnecessary styles applied to the identifiers:

![image](https://user-images.githubusercontent.com/11782833/122554831-24dfd580-d042-11eb-9786-3eb128d8faa1.png)

It should look like this <kbd>Ctrl + K</kbd>, not like this <kbd><kbd>Ctrl</kbd> + <kbd>K</kbd></kbd> or this <kbd><kbd>Ctrl</kbd><kbd> </kbd>+<kbd> </kbd><kbd>K</kbd></kbd>.

**Comment by mhilbrunner** [comment]
From what I can tell, this is mostly on us not using `kbd` correctly?

E.g, on [2D > Coding the player](https://docs.godotengine.org/en/latest/getting_started/first_2d_game/03.coding_the_player.html) we currently do the following:

``:kbd:`Cmd + R` ``

which results in:

![godot1](https://user-images.githubusercontent.com/1654763/125476081-0559f84c-b101-4588-be82-54fc6de55c23.PNG)

But if we instead do

``:kbd:`Cmd` + :kbd:`R` ``

the result is:

![godot2](https://user-images.githubusercontent.com/1654763/125476111-0abf33fb-8a3c-4f70-bffa-43a2ed017835.PNG)

And from all examples online I found and indeed the HTML spec, it seems it *is* meant to be used that way, not like we're currently doing:

https://html.spec.whatwg.org/multipage/text-level-semantics.html#the-kbd-element
