### ISSUE TITLE
Android SDK setup: cmake and ndk package not found

### ISSUE THREAD

**Issue by Andrea-Miele** [godotengine/godot-docs#4890]
**Godot version:**
3.3.stable

**OS/device including version:**
Windows 10 Microsoft Surface Pro X 
**Issue description:**
I tried to install the tools required for android export via sdkmanager.bat but it returns `Warning: Failed to find package 'cmake;3.10.2.4988404'`

**Steps to reproduce:**
-Download cmdline-tools from the official site
- run `sdkmanager.bat "platform-tools" "build-tools;30.0.3" "platforms;android-29" "cmdline-tools;latest" "cmake;3.10.2.4988404" "ndk;21.4.7075529"`

**Comment by akien-mga** [comment]
I can't reproduce the issue on Linux, the command works fine for me even after upgrading to the latest `cmdline-tools` version.

```
$ ./cmdline-tools/bin/sdkmanager --sdk_root=. --list | grep cmake
  cmake;3.10.2.4988404 | 3.10.2       | CMake 3.10.2.4988404            | cmake/3.10.2.4988404/
  cmake;3.10.2.4988404                                                                     | 3.10.2       | CMake 3.10.2.4988404                                                
  cmake;3.18.1                                                                             | 3.18.1       | CMake 3.18.1                                                        
  cmake;3.6.4111459                                                                        | 3.6.4111459  | CMake 3.6.4111459
```

Might be a Windows-specific issue if Google packaged a new CMake version for Windows and yanked `3.10.2.4988404`.

**Comment by Andrea-Miele** [comment]
The output of sdkmanager --list | findstr cmake:
`  cmake;3.18.1                                                                             | 3.18.1       | CMake 3.18.1`
Also ndk package is not found:
`  ndk;16.1.4479499                                                                         | 16.1.4479499 | NDK (Side by side) 16.1.4479499
  ndk;17.2.4988734                                                                         | 17.2.4988734 | NDK (Side by side) 17.2.4988734
  ndk;18.1.5063045                                                                         | 18.1.5063045 | NDK (Side by side) 18.1.5063045
  ndk;19.2.5345600                                                                         | 19.2.5345600 | NDK (Side by side) 19.2.5345600
  ndk;20.0.5594570                                                                         | 20.0.5594570 | NDK (Side by side) 20.0.5594570
  ndk;20.1.5948944                                                                         | 20.1.5948944 | NDK (Side by side) 20.1.5948944`
I already updated cmdline-tools

**Comment by akien-mga** [comment]
That's weird as you also lack recent NDK versions, so there's definitely something wrong with your Android SDK or cmdline-tools version.

```
$ ./cmdline-tools/latest/bin/sdkmanager --list | grep ndk
Warning: IO exception while downloading manifest
  ndk;21.4.7075529     | 21.4.7075529 | NDK (Side by side) 21.4.7075529 | ndk/21.4.7075529/    
  ndk-bundle                                                                               | 22.1.7171670 | NDK                                                                 
  ndk;16.1.4479499                                                                         | 16.1.4479499 | NDK (Side by side) 16.1.4479499                                     
  ndk;17.2.4988734                                                                         | 17.2.4988734 | NDK (Side by side) 17.2.4988734                                     
  ndk;18.1.5063045                                                                         | 18.1.5063045 | NDK (Side by side) 18.1.5063045                                     
  ndk;19.2.5345600                                                                         | 19.2.5345600 | NDK (Side by side) 19.2.5345600                                     
  ndk;20.0.5594570                                                                         | 20.0.5594570 | NDK (Side by side) 20.0.5594570                                     
  ndk;20.1.5948944                                                                         | 20.1.5948944 | NDK (Side by side) 20.1.5948944                                     
  ndk;21.0.6113669                                                                         | 21.0.6113669 | NDK (Side by side) 21.0.6113669                                     
  ndk;21.1.6352462                                                                         | 21.1.6352462 | NDK (Side by side) 21.1.6352462                                     
  ndk;21.2.6472646                                                                         | 21.2.6472646 | NDK (Side by side) 21.2.6472646                                     
  ndk;21.3.6528147                                                                         | 21.3.6528147 | NDK (Side by side) 21.3.6528147                                     
  ndk;21.4.7075529                                                                         | 21.4.7075529 | NDK (Side by side) 21.4.7075529                                     
  ndk;22.0.7026061                                                                         | 22.0.7026061 | NDK (Side by side) 22.0.7026061                                     
  ndk;22.1.7171670                                                                         | 22.1.7171670 | NDK (Side by side) 22.1.7171670
```

If you used sdkmanager to install `cmdline-tools;latest`, make sure that you're using the `sdkmanager` version from `cmdline-tools/latest/bin/sdkmanager` and not any other location.

**Comment by Andrea-Miele** [comment]
I downloaded my sdk from https://developer.android.com/studio/#command-tools so it is updated. I'm using the latest cmdline-tools

**Comment by Andrea-Miele** [comment]
I think it's a problem related to the android sdk with windows ARM systems. I'll close the issue when I check it

**Comment by akien-mga** [comment]
Did you find a solution? It would be nice to document it here for other users who might have the same issue.
