### ISSUE TITLE
Godot iOS Serivces documentation lists iCloud as Singleton but doesn't say any methods

### ISSUE THREAD

**Issue by Tekuzo** [godotengine/godot-docs#4900]
**Your Godot version:**
3.3 Stable
**Issue description:**
The below listed page states the following 

> At the moment Godot provides StoreKit, GameCenter, iCloud services plugins.

On the page it only has the methods for the StoreKit and GameCenter Plugins, there currently isn't documentation for iCloud. I was hoping to be able to use this to implement cloud saves in my game.

Thank You
**URL to the documentation page (if already existing):**
https://docs.godotengine.org/en/stable/tutorials/platform/ios/plugins_for_ios.html

**Comment by Calinou** [comment]
cc @naithar

**Comment by akien-mga** [comment]
Reopening as the docs should mention it.
