### ISSUE TITLE
Add C++ to the "First 2D Game"

### ISSUE THREAD

**Issue by parkovski** [godotengine/godot-docs#4901]
**Your Godot version:** 3.3

**Issue description:** I translated the "First 2D Game" Dodge the Creeps tutorial to C++. I'd like to integrate it into the docs if possible, or if needed get feedback on what could make it more tutorial worthy.

**URL to the documentation page (if already existing):** https://github.com/parkovski/godot-dodge-cpp (link to my translation of the game).

I use Windows but I've also built (but not run) the project in WSL Ubuntu. I don't expect trouble with other platforms but can't test them myself.

**Comment by pycbouh** [comment]
There are currently no plans to integrate any other languages for code samples into the online documentation. We don't even have full C# coverage, and C++ support is not really packed with the engine, as it requires another project to code and compile against. I guess it wouldn't hurt linking to your project somehow, though, as an example of a translation from GDScript to C++. Maybe a link could be added to the GDNative pages.

**Comment by Calinou** [comment]
Duplicate of https://github.com/godotengine/godot-docs/issues/140.

**Comment by parkovski** [comment]
Thanks, I'll do that. Just wanted to make this available for anyone trying to use C++ with Godot because it's kind of tricky at times.
