### ISSUE TITLE
"Exporting for Android" Editor Settings/Export/Android does not match 3.3

### ISSUE THREAD

**Issue by ShatReal** [godotengine/godot-docs#4917]
**Your Godot version:**
3.3
**Issue description:**
It doesn't match. `adb`, `jarsigner`, `time_stamping_authority_url`, `custom_build_sdk_path`, and `android_sdk_path` are all not shown in the image in the stable documentation.
**URL to the documentation page:**
https://docs.godotengine.org/en/stable/getting_started/workflow/export/exporting_for_android.html#setting-it-up-in-godot

**Comment by Calinou** [comment]
Duplicate of https://github.com/godotengine/godot/issues/22099.
