### ISSUE TITLE
Any vectorial illustration needed for the docs?

### ISSUE THREAD

**Issue by Bonfi96** [godotengine/godot-docs#492]
Hi!
Last year I remade some of the illustrations of the math section and a bunch of others as I wanted the docs to look better. 
I'll do another round so if you find any illustration, not screenshot, that may need some tweaks let me know!

**Comment by toger5** [comment]
@Bonfi96
Great you would do someillustrations.
I dont know about any atm.
I suggest you go through the doc yourself.
Might be the fastest. For me it also would take some time to find missing ones.

But ill write as soon as i find some which arent that nice or if there is an area of the docs which would benifit from illustrations!

**Comment by pwab** [comment]
I quickly skipped through the img directory and listed the images which aren't screenshots:

```
activescene.png
anchors.png
architecture_diagram.jpg
canvaslayers.png
Control.png
hdr_gamma.png
input_event_flow.png
instancing.png
instancingpre.png
inverse_kinematics.png
mipmaps.png
motion_diagram.png
motion_reflect.png
Node2D.png
nodes_resources.png
Object.png
openworld_instancing.png
raycast_falsepositive.png
raycast_projection.png
Reference.png
shape_rules.png
shooter_instancing.png
singleton.png
Spatial.png
stretch.png
tilemap.png
tree.png
tutomat...png
tutovec...png
tuto_3d11.png
unity-to-godot.png
viewport_transforms2.png
```

Most of them are graphs or mathmatical figures which are quite nice.
**Personally** I just don't like these ones:

Name              | Image
------------------|-----------------------------------------------------------------------------------------------------------
anchors.png       | ![anchors.png](https://github.com/godotengine/godot-docs/blob/master/img/anchors.png?raw=true)
instancing.png    | ![instancing.png](https://github.com/godotengine/godot-docs/blob/master/img/instancing.png?raw=true)
instancingpre.png | ![instancingpre.png](https://github.com/godotengine/godot-docs/blob/master/img/instancingpre.png?raw=true)
shape_rules.png   | ![shape_rules.png](https://github.com/godotengine/godot-docs/blob/master/img/shape_rules.png?raw=true)
stretch.png       | ![stretch.png](https://github.com/godotengine/godot-docs/blob/master/img/stretch.png?raw=true)
tree.png          | ![tree.png](https://github.com/godotengine/godot-docs/blob/master/img/tree.png?raw=true)

**Comment by reduz** [comment]
Feel free to contribute nicer ones!

**Comment by Bonfi96** [comment]
Yup I'll go through the docs myself a bit at a time, I asked because people goes through the docs while developing and they may have noticed something ugly.
Thanks for pointing those out @pwab I'll definitely remake them with a cleaner look.

**Comment by cbscribe** [comment]
Be aware, there's a project underway to rewrite a lot of these docs: #444

As we're tackling those, the needs for illustrations might change. I wouldn't want to see you put any work into redoing any of the existing images if they wind up needing to be replaced.

**Comment by Bonfi96** [comment]
That's good news, I'll try to not remake the ones you seem you guys are going to replace. On the other hand we could find a way to make new illustrations for the new articles. For example, if a writer has an idea it's enough that he sketches it on paper and then I can start to work on it

**Comment by pwab** [comment]
@cbscribe
> I wouldn't want to see you put any work into redoing any of the existing images if they wind up needing to be replaced.

Doesn't #444 only affects docs of master (3.x branch)? So if these images are remade for 2.x branch they wouldn't be replaced at all - or did I miss something?

**Comment by Bonfi96** [comment]
@cbscribe you guys got any plans about the Instancing pages? They are not in #444 checklist so I just want to make sure. The GUI pages are being reworked so I'd skip them.
I guess I'll start with the Stretch Mode image

**Comment by cbscribe** [comment]
No, I'm not aware of anyone who's stepped up to work on the instancing doc.

**Comment by NathanLovato** [comment]
```you guys got any plans about the Instancing pages?```

@Bonfi96 The plan is to replace the entire getting started section. It's just that the job is organic and it's going to happen over time. Pages like instancing and the intro to nodes need a complete makeover. As part of the Kickstarter project, I've got to produce an entire intro series to some of Godot's core concepts. If nobody rewrites it by then, I'll take care of it.

Can we put source files in common for the docs' illustrations? This way we can standardize the style a little bit, and more importantly have some template shapes and colors for all future contributors to use.
What do you work with for the source files? Inkscape? I guess we should work with SVG: easy to share, gonna be compatible with Krita soon, lightweight, git friendly, mac and windows users friendly (works for affinity designer / sketch / illustrator users), can render in the browser

**Comment by Bonfi96** [comment]
There are svg source files for the drawings I did last year (mostly the math section), all I did was re make the old illustrations making some tweaks, no major restyling was done.
As you said svgs are easy to work with, I'm using Inkscape, and I wouldn't mind go through them to standardize them. 

We should come up with a color pallette and some base shapes (having a consistent style for flow charts or similar diagrams is important).
The font I used before is Lato wich is the same as the docs, I think it fits pretty well in the illustrations and it is also flexible as it has many variants.

About rendering svg directly in the browser, I'm not sure if there is any specific reason why it hasn't been done before (could be that sphinx can't render the svgs to pdf or epub? No idea)

**Comment by cbscribe** [comment]
@Bonfi96 I'm rewriting the vector page. Are you still willing/available to update and work on the illustrations? I have a few that need changing and a few other new ones needed.

**Comment by Bonfi96** [comment]
Sure, let me know the details

**Comment by mhilbrunner** [comment]
Will close this for now as it seems you finished this, to keep the issue list manageable. I think IRC/Discord would be better for this discussion anyway, as its not really a "issue" :) However, if you still need it, feel free to reopen. Thanks for helping out with the vector art!
