### ISSUE TITLE
Document about to attach debugger to official macOS binaries which are notarized

### ISSUE THREAD

**Issue by Thoughtquake** [godotengine/godot-docs#4927]
When I upgraded from 3.2.3 to 3.3 I lost the ability to run Godot under lldb (debugger) or attach afterward. From what I can tell so far, I think it's because of the way binaries are signed. Specifically, without the "com.apple.security.get-task-allow" entitlement, lldb doesn't have permission to attach.

I've also tested this on 3.3.1 rc1 and have the same problem, but 3.2.3 still works fine. 

I'm new to the whole concept of "entitlements" on macOS, so I haven't yet figured out how to fix this or if I'd need to compile the engine myself to do it.

I'm running on macOS 11.3.1.

To reproduce (on Mac only):
1. Open Terminal
2. Install xcode command-line tools if you haven't already: xcode-select --install
3. Change directory to the location of the Godot binary (inside the Godot.app package, i.e.: cd /Applications/Godot.app/Contents/MacOS
4. Run the following: lldb ./Godot
5. Enter the following command: run

Observed on 3.3 (the problem):
"error: process exited with status -1 (Error 1)"

Observed on 3.2.3 (working as expected):
"Process #### launched" message, followed by Godot appearing after a short delay.

Why this matters:
I'm using GDNative and need to debug my C++ code running within Godot's process.

**Comment by akien-mga** [comment]
I moved this to the docs repo as it should be documented somewhere here.

As for the entitlements used in official builds, they'll be documented via https://github.com/godotengine/godot/pull/48893 (and should be mentioned in the Compiling for OSX docs too).

**Comment by Xrayez** [comment]
If I'm using official Godot build scripts to make custom builds of Godot and don't provide code signing credentials in `config.sh`, would those builds be able to be debugged in macOS? To paraphrase: would those builds be ad-hoc signed by default?

**Comment by akien-mga** [comment]
> To paraphrase: would those builds be ad-hoc signed by default?

No, signing needs to be done on macOS and the scripts are designed to run on Linux, so the signing and notarization is done through an external macOS machine which you're not connecting to if you don't provide credentials (you're also not expected too, it's a private machine :)).

**Comment by skyace65** [comment]
This was fixed by #5105. This issue can be closed
