### ISSUE TITLE
Revise/edit Shader documentation

### ISSUE THREAD

**Issue by cbscribe** [godotengine/godot-docs#494]
Adding this issue for discussion of revisions and/or additions to the new shader docs here (thanks @reduz ):
https://github.com/godotengine/godot-docs/tree/master/learning/features/shading

Also, now that we have some good documentation to start from, we need to add a shader intro/tutorial to the todo list.

**Comment by NathanLovato** [comment]
Got an intro to shaders with Godot 3 series planned as part of the Kickstarter, but it won't come out before 2018 I think. Got other content to take care of in priority. But it's planned, it's been funded by the backers, so if no one else takes on the task there's at least some guaranteed content eventually.

**Comment by ZX-WT** [comment]
tutorial about the visual shader editor should be added as well
https://godotengine.org/article/visual-shader-editor-back

**Comment by akien-mga** [comment]
Fixed by #2046.
