### ISSUE TITLE
Remove the note that only GLES2 support batching

### ISSUE THREAD

**Issue by me2beats** [godotengine/godot-docs#4966]
**Your Godot version:**
3.3

**Issue description:**
Godot supports batching in GLES3 now
The note should be removed

**URL to the documentation page:**
https://docs.godotengine.org/en/stable/tutorials/optimization/batching.html

**Comment by akien-mga** [comment]
Feel free to make a PR to the `3.3` branch to remove it :)

**Comment by mhilbrunner** [comment]
Closed by https://github.com/godotengine/godot-docs/pull/5051
