### ISSUE TITLE
Documentation link to C# bindings is wrong

### ISSUE THREAD

**Issue by makoConstruct** [godotengine/godot-docs#4979]
link "C#" here: https://docs.godotengine.org/en/stable/about/list_of_features.html just hrefs the same page as the link "GDScript" above it, pointing to the gdscript documentation instead of the C# documentation.

**Comment by swanandx** [comment]
Can I fix this and submit a PR? It will be amazing for my first contribution to godot docs

**Comment by pycbouh** [comment]
> Can I fix this and submit a PR? It will be amazing for my first contribution to godot docs.

Sure 🙂 

> The link in the [.rst file](https://github.com/godotengine/godot-docs/blob/master/about/list_of_features.rst) on GitHub seems correct though.

You are looking at the `master` branch, and the user report is about the stable version of the docs. It seems that sometime before the link was fixed in master but the fix was never ported back to stable. You can open a PR against `3.3` branch, so it can be added to stable.

**Comment by swanandx** [comment]
Thank you, I will do it 😀

**Comment by swanandx** [comment]
Done 👍 , opened a PR against branch 3.3 fixing the link 😄 . Thank you for letting me contribute a little to this amazing documentation. Looking forward to contribute more ❤️

**Comment by mhilbrunner** [comment]
Fixed by https://github.com/godotengine/godot-docs/pull/4980
