### ISSUE TITLE
Object::get_signal_connection_list returns an array, but the format of it's values is not documented.

### ISSUE THREAD

**Issue by nathanfranke** [godotengine/godot-docs#4985]
**Your Godot version:**
3.3.2

**Issue description:**
The documentation only says that `get_signal_connection_list` returns an `Array`, but it does not specify the entries in each dictionary returned.

Here is the behaviour, as defined by [Connection](https://github.com/godotengine/godot/blob/3.x/core/object.h#L416-L421) and [_get_signal_connection_list](https://github.com/godotengine/godot/blob/3.x/core/object.cpp#L1331-L1336)
```
source: Object
signal: String
target: Object
method: String
flags: int
binds: Array
```

**URL to the documentation page (if already existing):**
https://docs.godotengine.org/en/stable/classes/class_object.html#class-object-method-get-signal-connection-list

**Comment by Mickeon** [comment]
This has been solved by https://github.com/godotengine/godot/pull/67880 (in 4.0)
