### ISSUE TITLE
Add/Remove Script Icon in Scene-Tree-Panel is not updating

### ISSUE THREAD

**Issue by whiteshampoo** [godotengine/godot-docs#4986]
**Your Godot version:** 
3.3.2

**Issue description:**
The icon for adding/removing a script in the Scene-Tree-Panel (top-left) is not updating wenn adding/removing a script in the inspector.

**Comment by pycbouh** [comment]
This is a repository for the documentation. For bug reports with the Godot editor please use the main repository https://github.com/godotengine/godot
