### ISSUE TITLE
Shared library module example does not compile

### ISSUE THREAD

**Issue by hungrymonkey** [godotengine/godot-docs#499]
I am trying to write a shared module as provided in this link

http://docs.godotengine.org/en/latest/development/cpp/custom_modules_in_cpp.html

The only difference between my module and the one in the sample is just the names.

The static compile works but neither of the shared library SCsub cannot compile

I tried both SCsub config files

```
$scons platform=x11
scons: Reading SConscript files ...
Could not detect MinGW. Ensure its binaries are in your PATH or that MINGW32_PREFIX or MINGW64_PREFIX are properly defined.
Enabling ALSA
Enabling PulseAudio
cdir is: /home/rice/godot
Checking for C header file mntent.h... (cached) yes
scons: done reading SConscript files.
scons: Building targets ...
[Initial build] 
[Initial build] Linking Program        ==> bin/godot.x11.tools.64
/bin/ld: cannot find -lmumble.x11.tools.64
collect2: error: ld returned 1 exit status
scons: *** [bin/godot.x11.tools.64] Error 1
scons: building terminated because of errors.
```
I am using week old godot master

**Comment by OvermindDL1** [comment]
> /bin/ld: cannot find -lmumble.x11.tools.64

I'm not seeing anything about mumble on the linked page, are you sure they are identical?  Do you have things left over in your build cache?

**Comment by hungrymonkey** [comment]
I following the example in the linked page. The only difference between my module and the example is the name change.



Basically I change

Summator->Mumble
summator->mumble

I believe that is the only difference. 

Please note: I would had used summator name before I reported the issue but i can build the static library. So I do not think this issue is my end.

**Comment by hungrymonkey** [comment]
well i decided to just copy paste it

same result

```
[ 27%] Compiling ==> thirdparty/libwebp/utils/thread_utils.c
[ 28%] Compiling ==> thirdparty/libwebp/utils/utils.c
[ 28%] Compiling ==> modules/webp/register_types.cpp
[ 28%] Compiling ==> modules/webp/image_loader_webp.cpp
[ 28%] Linking Static Library ==> modules/libmodules.x11.tools.64.a
Ranlib Library         ==> modules/libmodules.x11.tools.64.a
[ 31%] Compiling ==> editor/editor_about.cpp
[ 61%] Compiling ==> editor/project_manager.cpp
[ 65%] Linking Static Library ==> editor/libeditor.x11.tools.64.a
Ranlib Library         ==> editor/libeditor.x11.tools.64.a
[ 82%] Compiling ==> core/engine.cpp
[ 86%] Linking Static Library ==> core/libcore.x11.tools.64.a
Ranlib Library         ==> core/libcore.x11.tools.64.a
[ 87%] Linking Program        ==> bin/godot.x11.tools.64
/usr/bin/ld: cannot find -lsummator.x11.tools.64
collect2: error: ld returned 1 exit status
scons: *** [bin/godot.x11.tools.64] Error 1
scons: building terminated because of errors.
```

**Comment by OvermindDL1** [comment]
Wonder if the docs are broken (I've not tested yet but this is something I'll need in a bit, hence my interest).

Can you upload a git repo that we can clone and immediately build?

**Comment by hungrymonkey** [comment]
https://github.com/hungrymonkey/godot/tree/shared_summator

i am working on this repo. it behind godot master a week. 

https://github.com/hungrymonkey/godot/tree/shared_summator

or you can pull from godot master and copy over the summator directory

**Comment by hungrymonkey** [comment]
well master compiled a shared library. Closing this bug

**Comment by haxpor** [comment]
@hungrymonkey are you successfully compiled on Linux? I'm on macOS and based on 2.1.4 release, I can get static one compiled, but not shared dynamic one.

I came from this [comment](https://godotengine.org/qa/16495/getting-c-to-compile-as-a-shared-object-dll?show=17013#c17013) that suggest the doc might be broken for other platforms rather than Linux. So wanna make sure.

**Comment by hungrymonkey** [comment]
this bug was meant for linux on the master branch only. It was fixed and compiled.

@haxpor create a new bug i guess.

**Comment by hungrymonkey** [comment]
Just to be clear, the example was compiling. I do not think the doc was incorrect. I just so happened to be hitting a bug in the master branch

**Comment by hungrymonkey** [comment]
```
YASM is necessary for WebM SIMD optimizations.
WebM SIMD optimizations are disabled. Check if your CPU architecture, CPU bits or platform are supported!
Checking for C header file mntent.h... (cached) no
scons: done reading SConscript files.
scons: Building targets ...
[ 88%] Linking Program        ==> bin/godot.osx.tools.64
ld: library not found for -lsummator.osx.tools.64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
scons: *** [bin/godot.osx.tools.64] Error 1
scons: building terminated because of errors.
```

I tried osx p=osx use_llvm=yes

seems broken

**Comment by hungrymonkey** [comment]
I just tested master and it the compile still works

**Comment by haxpor** [comment]
@hungrymonkey Thank you so much for your time. Sorry to not reply sooner. This confirms my test on macOS as well. I will file a new issue for macOS. Thanks!
