### ISSUE TITLE
Sphinx Search not working as expected

### ISSUE THREAD

**Issue by stefano-elysium** [godotengine/godot-docs#5000]
**Your Godot version:** 3.3.2.stable.official
**Issue description:**
When searching for a specific class, I expect the search function to find it it.
It does not find it.
For example, searching "InputEventMouseMotion" does not find it:
https://docs.godotengine.org/en/stable/search.html?q=InputEventMouseMotion&check_keywords=yes&area=default
I expect it to bring up this page as the first result:
https://docs.godotengine.org/en/stable/classes/class_inputeventmousemotion.html

It seems like the search bar is setup to search through the content only and not use the page names as first priority.

**URL to the documentation page:** Up above

**Comment by Calinou** [comment]
We don't have much control over how Sphinx search does its indexing, but class reference pages *are* supposed to appear in results. I don't know what's preventing the page from appearing in the results.

That said, we are currently [trying out Algolia](https://github.com/godotengine/godot-docs/pull/4884) on the `master` branch (https://docs.godotengine.org/en/latest/), so you could test it there instead.

**Comment by akien-mga** [comment]
This seems fixed now:
https://docs.godotengine.org/en/stable/search.html?q=InputEventMouseMotion&check_keywords=yes&area=default
