### ISSUE TITLE
Custom Modules Tutorial Docs reference files that don't exist in core

### ISSUE THREAD

**Issue by georgeoffley** [godotengine/godot-docs#5009]
**Your Godot version:**
3.2.2-stable

**Issue description:**
The custom modules documentation is including files that do not exist. For example in the [Custom modules in C++](https://github.com/godotengine/godot-docs/blob/master/development/cpp/custom_modules_in_cpp.rst) page the header for the `register_types.cpp` includes this line `#include "core/class_db.h"` and the `class_db.h` does not exist in core. This seems to be the case in the examples for the following files:

- `register_types.cpp`
- `summator.h`

**URL to the documentation page:**
https://github.com/godotengine/godot-docs/blob/master/development/cpp/custom_modules_in_cpp.rst

**Comment by Calinou** [comment]
For reference, this is because many core files were moved or renamed in the `master` branch. We'll wait until things stabilize before updating links.

**Comment by georgeoffley** [comment]
Understood! Thanks for clarifying.

**Comment by skyace65** [comment]
Looks like this was fixed by #5205. If something is still wrong please reopen this issue.

**Comment by FrasherGray** [comment]
I am having this problem for version 4.0.2, not only with "core/class_db.h" but also "core/reference.h"

**Comment by skyace65** [comment]
> I am having this problem for version 4.0.2, not only with "core/class_db.h" but also "core/reference.h"

Both of those files are not referenced on the custom modules doc page on the 4.0 branch. Do not comment about something on a different page on an issue that has been closed. If you're having this problem with a different doc page open a new issue.
