### ISSUE TITLE
Controllers, gamepads, and joysticks tutorial references Godot 4.0 as current version

### ISSUE THREAD

**Issue by dweremeichik** [godotengine/godot-docs#5012]
**Your Godot version:** 

Stable (3.3.2)

**Issue description:** 

The Controllers, gamepads, and joysticks tutorial mentions features from the 4.0 branch as if it is the current stable branch. [This section](https://docs.godotengine.org/en/stable/tutorials/inputs/controllers_gamepads_joysticks.html#which-input-singleton-method-should-i-use) specifically.  While nice to know about, it isn't useful. It would be more useful to speak on how to create/choose deadzones in any version of Godot. 

**URL to the documentation page:**

https://docs.godotengine.org/en/stable/tutorials/inputs/controllers_gamepads_joysticks.html

**Comment by Calinou** [comment]
I wonder if https://github.com/godotengine/godot/pull/42976 could be remade for 3.4 instead. This way, we don't have to maintain significantly different versions of the documentation (which is always an annoyance when cherry-picking stuff).

**Comment by aaronfranke** [comment]
@Calinou Indeed, the code is too different to cherry-pick, but [it can be remade from scratch](https://github.com/aaronfranke/godot/tree/3.x-input-get-axis) if desired.

**Comment by Calinou** [comment]
> @Calinou Indeed, the code is too different to cherry-pick, but [it can be remade from scratch](https://github.com/aaronfranke/godot/tree/3.x-input-get-axis?rgh-link-date=2021-07-23T03%3A36%3A15Z) if desired.

Sounds good to me, thanks for looking into it :slightly_smiling_face:
