### ISSUE TITLE
Inline code blocks intersect each other in shader Shading references

### ISSUE THREAD

**Issue by hpnrep6** [godotengine/godot-docs#5013]
**Your Godot version:**
3.2.2

**Issue description:**
Row height in the reference tables are not tall enough to properly fit two rows of code blocks (where one is directly on top of another), resulting in them intersecting each other.

![Screenshot from 2021-06-17 22-59-04](https://user-images.githubusercontent.com/57055412/122500469-d9391780-cfc0-11eb-9db6-042d600270cc.png)

![Screenshot from 2021-06-17 22-58-30](https://user-images.githubusercontent.com/57055412/122500473-dc340800-cfc0-11eb-8dc3-9dd13994f351.png)

**Suggestion**
One fix may be to increase the row height, though not sure how that would affect the overall doc formatting.

**URL to the documentation page:**
[Spatial shaders](https://docs.godotengine.org/en/latest/tutorials/shaders/shader_reference/spatial_shader.html)
[Shading language](https://docs.godotengine.org/en/latest/tutorials/shaders/shader_reference/shading_language.html)

**Comment by pycbouh** [comment]
We do seem to have a smaller than usual line height in the tables, as well as a lot of conflicting styles for that section, ultimately being overwritten by the default styles (using better specificity and a completely new set of classes).

![image](https://user-images.githubusercontent.com/11782833/122556091-c4ea2e80-d043-11eb-9cef-3366cb8594e9.png)

I'm pretty sure that `html.writer-html5` selector was introduced recently, and it seem to affect a lot of our styles. We should probably do a pass on the `custom.css` and see where this should be added to restore the overrides (this includes the recent changes with `!important`, those are likely unnecessary).

**Comment by Calinou** [comment]
Still reproducible on latest `master` with theming changes:

![image](https://user-images.githubusercontent.com/180032/206823375-fedd1a5d-a773-41a8-b374-3522e9668cfb.png)

**Comment by YuriSizov** [comment]
I've actually increased line height in class ref tables, slightly, but not in all tables. I didn't want to break anything by accident, but I guess we should just do it for everything.
