### ISSUE TITLE
The latest documentation side menu cannot scroll down on the phone device

### ISSUE THREAD

**Issue by Chaosus** [godotengine/godot-docs#5025]
**Your Godot version:**
Don't matter

**Issue description:**
When I open up the latest documentation on my Android phone (XIAOMI MI MAX 1) and open a side menu I cannot scroll down it with my fingers to see the full content of that menu, it stuck:

<details>
<summary>Screenshot from phone</summary>

![image](https://user-images.githubusercontent.com/3036176/122709843-c4ca7880-d267-11eb-9d26-10e0e8ae2f80.png)

</details>

Stable documentation and the PC version of this page works correctly on my phone.

**URL to the documentation page:**
https://docs.godotengine.org/en/latest/

**Comment by Calinou** [comment]
I can confirm this on Chromium 90 on an OnePlus 6. This only happens on the `master` branch, not `stable` or `3.3`. This is likely a regression from https://github.com/godotengine/godot-docs/pull/4884.

cc @leroy

**Comment by dweremeichik** [comment]
Can also confirm in Firefox 81.1.1 on Android.

**Comment by hpnrep6** [comment]
Issue appears to be caused by `.wy-side-scroll { overflow: inherit; }` in algolia.css, since it's no longer present when that line is removed.
