### ISSUE TITLE
Registering Scripts as classes is confusing if you don't work with NativeScript

### ISSUE THREAD

**Issue by golddotasksquestions** [godotengine/godot-docs#5028]
**Your Godot version:** Godot 3.3.2

**Issue description:**
The example should imho always try to show the most simple usecase first. More sophisticated usecases (such as using NativeScripts), can be great additional examples, but confuse beginners trying to learn.

In this case, it took me a good while and some experimentation until I figured out that everything under _ready(): is only specific to NativeScripts and I don't need any of it for GDScript.

So instead of the current example I would propose something like this:

```
extends Node

# Declare the class name here
class_name ScriptName, "res://path/to/optional/icon.svg"

func _ready():
    print("This is printed from a registered script class named ", name)
```

And then say something along the lines: "In case you want to register your NativeScript class, your would reference it like this:"
And then show the current example and screenshot.

Also the icon does not show up for me, even though I copy/pasted the file path t the svg from the FileSystem.

**URL to the documentation page (if already existing):**
https://docs.godotengine.org/en/3.3/getting_started/step_by_step/scripting_continued.html#register-scripts-as-classes

**Comment by Calinou** [comment]
> Also the icon does not show up for me, even though I copy/pasted the file path t the svg from the FileSystem.

You may have to restart the editor. Also, if the SVG fails to import because NanoSVG can't import it, the icon may not show up. As a workaround, use a PNG icon instead (32×32 recommended to support hiDPI).

**Comment by golddotasksquestions** [comment]
Restarting the editor worked, thanks!

So it should probably be added to the documentation.
Instead of 

> You may add a comma and an optional path to an image to use as an icon. You will then find your new type in the Node or Resource creation dialog.

it should probably say

`You may add a comma and an optional path to an image to use as an icon. After an engine restart, you will then find your new type in the Node or Resource creation dialog.  If the SVG fails to import because NanoSVG can't import it, the icon may not show up. As a workaround, use a PNG icon instead (16×16 minimum, 32×32 recommended to support hiDPI).`

**Comment by Calinou** [comment]
Note that the page you linked to no longer exists in the `/latest` version of the documentation.

**Comment by mhilbrunner** [comment]
Icon part resolved by https://github.com/godotengine/godot-docs/pull/5031.

**Comment by skyace65** [comment]
Information on how to register a script as a class was moved to [this page](https://docs.godotengine.org/en/3.3/getting_started/step_by_step/scripting_continued.html#register-scripts-as-classes) and overhauled. From what I'm seeing the NativeScript stuff isn't there anymore. This issue can be closed.
