### ISSUE TITLE
Red rectangle around "@" character in code block examples

### ISSUE THREAD

**Issue by hpnrep6** [godotengine/godot-docs#5032]
The "@" characters in code blocks have a rectangular outline around them in: 

[WebRTC](https://docs.godotengine.org/en/latest/tutorials/networking/webrtc.html)
[Custom modules in C++](https://docs.godotengine.org/en/latest/development/cpp/custom_modules_in_cpp.html)
[Importing 3D scenes](https://docs.godotengine.org/en/latest/tutorials/assets_pipeline/importing_scenes.html)
[NodePath](https://docs.godotengine.org/en/latest/classes/class_nodepath.html) (Not sure if this one is intentional or not though)

![Screenshot from 2021-06-21 13-43-31](https://user-images.githubusercontent.com/57055412/122805461-1dfdd080-d297-11eb-8385-887e6cb49d2e.png)

**Comment by Calinou** [comment]
This is because incorrect syntax highlighting is used. It should be disabled on this specific code block using the `.. highlight`` reStructuredText directive.

**Comment by MaaaxiKing** [comment]
@hpnrep6, rename this topic to "Red rectangle around `@`(s) in code block example in WebRTC tutorial", because "outline" is understood as what an outline actually is: drawn edge of an image.

**Comment by Calinou** [comment]
For the record, this also happens with the `Node.print_tree_pretty()` description.

I think the easiest way to work around this would be to disable those red rectangles entirely by overriding the CSS.

**Comment by mhilbrunner** [comment]
I'll have a look at disabling this later if nobody else does, already poked around the CSS lately so may as well

**Comment by mhilbrunner** [comment]
Note: also see https://github.com/godotengine/godot-docs/issues/5080
