### ISSUE TITLE
Wrong shortcut listed to search reference in Script workspace.

### ISSUE THREAD

**Issue by DanklyTuned** [godotengine/godot-docs#5038]
**Your Godot version:** 3.3.2

**Issue description:**
In the Script workspace the shortcut to search reference documentation is F1, not Shift+F1.

**URL to the documentation page:**
https://docs.godotengine.org/en/stable/getting_started/step_by_step/intro_to_the_editor_interface.html

**Comment by hpnrep6** [comment]
Can confirm, shortcut appears to be Shift+F1 in 3.2.3, but is F1 in 3.3.2 and the master branch.

**Comment by Calinou** [comment]
The shortcut was changed in 3.3: https://github.com/godotengine/godot/pull/45708
