### ISSUE TITLE
Migrating to Godot's shading language "vertex attributes" link wrong.

### ISSUE THREAD

**Issue by z1dev** [godotengine/godot-docs#5050]
**Your Godot version:**
Stable online documentation. 3.3.2 if it matters.

**Issue description:**
In "Migrating to Godot's shading language" under the [vertex attributes](https://docs.godotengine.org/en/stable/tutorials/shading/migrating_to_godot_shader_language.html?#vertex-attributes) header, the link for "For a complete list, see the Shading language reference" goes to the [Shading Language](https://docs.godotengine.org/en/stable/tutorials/shading/shading_reference/shading_language.html#doc-shading-language) page and with a bad anchor.

The closest page I found is [Spatial shaders - Vertex built-ins](https://docs.godotengine.org/en/stable/tutorials/shading/shading_reference/spatial_shader.html#vertex-built-ins) and [CanvasItem shaders - Vertex built-ins](https://docs.godotengine.org/en/stable/tutorials/shading/shading_reference/canvas_item_shader.html#vertex-built-ins). I'm new at shaders so I might be mistaken here.

The phrasing is also not clear, as it suggests we have to manually pass in attributes to our shaders, instead of using the built-ins, but after visiting the correct pages, this wouldn't cause misunderstandings I guess.

**URL to the documentation page:**
https://docs.godotengine.org/en/stable/tutorials/shading/migrating_to_godot_shader_language.html?#vertex-attributes

**Comment by clayjohn** [comment]
Ah, yep that link is certainly out of date. Each shader type has its own reference page now in additional to the shading language reference page.
