### ISSUE TITLE
Ref<MyReference> example does not compile

### ISSUE THREAD

**Issue by hungrymonkey** [godotengine/godot-docs#506]
http://docs.godotengine.org/en/latest/development/cpp/object_class.html#id2

The error below is basically

Ref<MyReference> myref = memnew(MyReference);
```


modules/summator/summator.cpp:44:17: error: use of undeclared identifier 'call_func'
    this->_cb = call_func(args, 1, err);
                ^
modules/summator/summator.cpp:62:15: error: use of overloaded operator '=' is ambiguous (with operand types 'Ref<FuncRef>' and 'FuncRef *')
    this->_cb = memnew(FuncRef);
    ~~~~~~~~~ ^ ~~~~~~~~~~~~~~~
core/reference.h:144:7: note: candidate function
        void operator=(const Ref &p_from) {
             ^
core/reference.h:177:7: note: candidate function
        void operator=(const Variant &p_variant) {
```

I believe the proper way to use reference is
```
Ref<MyReference> myref = Ref<MyReference>(memnew(MyReference));
```

**Comment by bojidar-bg** [comment]
It seems wrong indeed. Should be something like this, AFAIK:
```
Ref<MyReference> myref;
myref.initialize();
```

**Comment by hungrymonkey** [comment]
@bojidar-bg Do you know where is the xml page for that code sample?

I couldnt find it. I guess allow someone else to fix the bug?

**Comment by neikeq** [comment]
> I believe the proper way to use reference is
> `Ref<MyReference> myref = Ref<MyReference>(memnew(MyReference));`

This: `Ref<MyReference> myref(memnew(MyReference));`
