### ISSUE TITLE
Rand_range's Upper Bound

### ISSUE THREAD

**Issue by emshuttles** [godotengine/godot-docs#5061]
**Your Godot version:**
v3.3.2

**Issue description:**
It is not clear from the documentation whether the function rand_range's upper bound is inclusive or exclusive.

**URL to the documentation page (if already existing):**
https://docs.godotengine.org/en/latest/classes/class_@gdscript.html

**Comment by akien-mga** [comment]
As it's float, both ends are exclusive I think. The probably to get a round 0.0 or 1.0 without floating point precision errors in `rand_range(0, 1)` should be close to 0.

**Comment by emshuttles** [comment]
Interesting. Well, if I get a definitive answer, I'll gladly make a PR to edit this function's docs.

**Comment by Calinou** [comment]
This is how `rand_range()` (renamed to `randf_range()` is implemented in `master`:

https://github.com/godotengine/godot/blob/6ef0b8fcd3ba2bcedbfae4a9575b9ca7488da34b/core/math/random_pcg.cpp#L49-L51

This is how `randf()` (random float between 0.0 and 1.0) is implemented in `master`:

https://github.com/godotengine/godot/blob/6ef0b8fcd3ba2bcedbfae4a9575b9ca7488da34b/core/math/random_pcg.cpp#L49-L51

**Comment by emshuttles** [comment]
Thank you!
