### ISSUE TITLE
Documentation for OS.get_time_zone_info() does not tell if the bias is in seconds or minutes, etc.

### ISSUE THREAD

**Issue by atirut-w** [godotengine/godot-docs#5062]
**Your Godot version:**
3.3.2

**Issue description:**
I was working on a Godot API to communicate with Game Jolt's Game API and had to convert UNIX time stamp to local time. Not knowing what unit the bias is in gave me a trouble.

**URL to the documentation page:**
https://docs.godotengine.org/en/stable/classes/class_os.html#class-os-method-get-time-zone-info

**Comment by z1dev** [comment]
The documentation doesn't say anything at all regarding the information this function might return. I would like it if it was improved too.

**Comment by Calinou** [comment]
> I was working on a Godot API to communicate with Game Jolt's Game API and had to convert UNIX time stamp to local time. Not knowing what unit the bias is in gave me a trouble.

What was the unit of the bias in the end?

**Comment by skyace65** [comment]
This was fixed in https://github.com/godotengine/godot/pull/54056 and https://github.com/godotengine/godot/pull/49123. This issue can be closed.
