### ISSUE TITLE
Remove spaces after and before opening, and before closing parenthesis

### ISSUE THREAD

**Issue by MaaaxiKing** [godotengine/godot-docs#5074]
**Your Godot version:**
3.3.2.stable.mono
**Issue description:**
The parentheses are gratuitous. For example, write `_enter_tree()` instead of `_enter_tree ( )`.
**URL to the documentation page (if already existing):**
E.g., https://docs.godotengine.org/en/stable/classes/class_node.html#:~:text=Methods

**Comment by Calinou** [comment]
Unfortunately, as far as I know, we can't remove those without breaking formatting. This is a reStructuredText limitation.

**Comment by MaaaxiKing** [comment]
Isn't it possible to edit it manually, even without zero-width spaces? I'd feel honored if I could help with that.

**Comment by Calinou** [comment]
> Isn't it possible to edit it manually, even without zero-width spaces? I'd feel honored if I could help with that.

The class reference in this repository is generated automatically using [this script](https://github.com/godotengine/godot/blob/master/doc/tools/makerst.py). It should not be edited manually.

**Comment by MaaaxiKing** [comment]
Okay, then it's the only good solution to replace the normal spaces. But then use narrow no-break space (`HTML &#8239;`).

**Comment by Calinou** [comment]
Unfortunately, neither `\u200b` nor `\u200c` work to add an invisible space that preserves formatting:

![image](https://user-images.githubusercontent.com/180032/124981391-ce105f00-e035-11eb-88d1-92d2fc5252fb.png)

**Comment by MaaaxiKing** [comment]
Although it doesn't work, I want to make clear that narrow no-break space would be bad anyway, I forgot that it does have a width. The reason why I suggested another one than zero-width space is that I wasn't sure if a line break is possible. It is. So a zero width no-break space (`&#65279;`) or a word joiner (`&#8288;`) would be better.

**Comment by tetrapod00** [comment]
I don't know when, but at some point this was changed. In the stable docs as of 4.3, there are no spaces around parentheses.

![msedge_t1zX60a2Nd](https://github.com/user-attachments/assets/f415ca80-96fc-46fb-b085-a0f860767672)
![msedge_TdgrqGxtnD](https://github.com/user-attachments/assets/c2f63335-aa2e-44f2-ac40-eb4ba539e03d)

**Comment by tetrapod00** [comment]
Closing this as completed (I don't know when and I can't be bothered to check)
