### ISSUE TITLE
[ Undocumented ] HTTPClient *not* supported for HTML5 exported games

### ISSUE THREAD

**Issue by Grass-H0PEr** [godotengine/godot-docs#508]
**=== Problem ===**

`HTTPClient` has not been implemented for `HTML5 platform exported games`.
According to this issue : https://github.com/godotengine/godot/issues/8897

Open issue for implementing `HTTPClient` for `HTML5`
is found here https://github.com/godotengine/godot/issues/4226

Very important to mention this
in the documentation for users.

Just found a question on godotengine/QA 
where a user was confused and frustrated as a result of this omission.

&nbsp;
**=== All Pages for** `HTTPClient` **in the Docs ===**

No mention of networking not being implemented 
for Web export in any of these relevant Docs:

_Docs » LEARNING » Project workflow » Export » **Exporting for the Web**_ :
http://docs.godotengine.org/en/latest/learning/workflow/export/exporting_for_web.html

_Docs » LEARNING » Engine features » Networking » **HTTP client class**_ :
http://docs.godotengine.org/en/latest/learning/features/networking/http_client_class.html?highlight=HTTPClient

_Docs » LEARNING » Engine features » Networking » **SSL certificates**_ :
http://docs.godotengine.org/en/latest/learning/features/networking/ssl_certificates.html?highlight=HTTPClient

_Docs » CLASS REFERENCE » Godot API » **HTTPClient**_ :
http://docs.godotengine.org/en/latest/classes/class_httpclient.html?highlight=HTTPClient

_Docs » CLASS REFERENCE » Godot API » **HTTPRequest**_ :
http://docs.godotengine.org/en/latest/classes/class_httprequest.html?highlight=HTTPClient

&nbsp;
**=== My limitations ===**

I'd update this myself, 
but I am nowhere near fluent nor competent enough in HTTP / networking
to confidently explain the matter clearly + correctly.

Further, I'm unsure if there are currently alternate ways to implement networking
for Web game exports without using `HTTPClient`.

&nbsp; &nbsp; &nbsp; Proposals for a generic warning note to apply 
&nbsp; &nbsp; &nbsp; \+ clarification appreciated

&nbsp;
**=== If no networking at all is implemented for HTML5 export 
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp;Pages like these also seem effected : ===**

_Docs » LEARNING » Engine features » Networking » **High level multiplayer**_ :
http://docs.godotengine.org/en/latest/learning/features/networking/high_level_multiplayer.html?highlight=network+TCP

_Docs » CLASS REFERENCE » Godot API » **TCP\_Server**_ :
http://docs.godotengine.org/en/latest/classes/class_tcp_server.html

_Docs » CLASS REFERENCE » Godot API » **IP**_ :
http://docs.godotengine.org/en/latest/classes/class_ip.html
http://docs.godotengine.org/en/latest/classes/class_ip_unix.html

_Docs » CLASS REFERENCE » Godot API » **PacketPeer + subclasses**_ :
http://docs.godotengine.org/en/latest/classes/class_packetpeer.html
 » http://docs.godotengine.org/en/latest/classes/class_networkedmultiplayerpeer.html
 »  » http://docs.godotengine.org/en/latest/classes/class_networkedmultiplayerenet.html
 » http://docs.godotengine.org/en/latest/classes/class_packetpeerstream.html
 » http://docs.godotengine.org/en/latest/classes/class_packetpeerudp.html

_Docs » CLASS REFERENCE » Godot API » **StreamPeer + subclasses**_ :
http://docs.godotengine.org/en/latest/classes/class_streampeer.html
 » http://docs.godotengine.org/en/latest/classes/class_streampeerbuffer.html
 » http://docs.godotengine.org/en/latest/classes/class_streampeerssl.html
 » http://docs.godotengine.org/en/latest/classes/class_streampeertcp.html

_Docs » CLASS REFERENCE » Godot API » **SceneTree**_ :
http://docs.godotengine.org/en/latest/classes/class_scenetree.html?highlight=network#class-scenetree-get-network-connected-peers

&nbsp;
**=== Conclusion ===**

Networking features (**not being implemented for certain platforms**) 
really must be documented for general users of Godot
to prevent future confusion + frustration.

1. Could someone clarify for me whether all networking is unsupported for HTML5, or just HTTPClient specific functionality?
2. Depending on scope of network features not implemented
relevant docs need to reflect this until implemented. 
3. A simple note explaining the limitations for HTML5 web exported games
could be written once, then applied at the top of each relevant page.
4. &nbsp; _( once implemented, the note can simply be removed )_

&nbsp; 
 
At the very least, 
warning should be applied to pages :
-  Docs » _Related to Web Export_
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; _( warn that networking will not work )_
-  Docs » LEARNING » _Networking tutorials_

_but preferably also_
- Docs » CLASS REFERENCE » classes not implemented
&nbsp; &nbsp; _so users don't build a complete example --or full project-- 
only to find out it won't work when they get to the export documentation_

&nbsp; 
 
Thanks to anyone who wants to update this in the Docs.

Alternate thanks to anyone who helps clarify + propose a warning message to add to these pages.

**Comment by reduz** [comment]
Yeah we were discussing that to make this work, it will need to somehow be
hacked.. as the APIs in htnl5 are more low level.

**Comment by Grass-H0PEr** [comment]
And that's fine, 
things take time =]

I just want to update the documentation in the meantime 
so users don't keep getting unexpected results from their exported projects

**Comment by Grass-H0PEr** [comment]
Example:
> "Godot always supported standard networking via UDP, TCP and some high level protocols such as SSL and HTTP."

from http://docs.godotengine.org/en/latest/learning/features/networking/high_level_multiplayer.html

is true... but only to an extent + implies it will (currently) work on all exported projects
