### ISSUE TITLE
API improvements and simple GUI change that would massively help beginners

### ISSUE THREAD

**Issue by yossi2010** [godotengine/godot-docs#5082]
**Your Godot version:**
3.3.2
**Issue description:**
Lack of AddLocalForce, AddLocalTorque in the RigidBody API as opposed to AddCentralForce(Transform.basis.Xform())
Lack of simple VectorToLocal and VectorToGlobal as opposed to Transform.basis.XformInv()
to_local (or ToLocal) doesn't ignore translation and is not fit for transforming vectors/directions.

GUI lacks a simple way to create primitives with 1 click. IMO this should be trivial as opposed to the current way of creating primitives that includes multiple steps.

**URL to the documentation page (if already existing):**
https://docs.godotengine.org/en/stable/classes/class_rigidbody.html

It would be a massive convenience having these, especially for beginners

**Comment by pycbouh** [comment]
Hello. If you want to propose API changes or enhancements to the editor's UI, then you need to create dedicated proposals for each feature or change in the [Godot Proposals repository](https://github.com/godotengine/godot-proposals). You will be asked to provide actual limitations and problems that you need those enhancements to solve, as well as describe your proposed solutions to the presented problem.

This repository is for documentation issues.
