### ISSUE TITLE
Missing explanation for return values from Tween methods

### ISSUE THREAD

**Issue by snoopdouglas** [godotengine/godot-docs#5091]
**Your Godot version:**
3.3.2

**Issue description:**
Tween's `interpolate_property` and `start` methods return `bool`s, but there's no explanation in the docs for what they mean.

They always seem to return `true` whenever I use them, but in order to avoid a warning I need to capture the value for an `assert` or something, so it'd be good to know for sure that `true` is what I should expect on success - if that is indeed the case.

**URL to the documentation page:** 
https://docs.godotengine.org/en/stable/classes/class_tween.html

**Comment by timothyqiu** [comment]
They return false if the requested operation can't be completed successfully. For example, when trying to start the tween before being added to the scene tree, or any of the parameters does not make sense (e.g. when object is null for `interpolate_*` methods).

... and these methods are all changed to return nothing in 4.0 in <https://github.com/godotengine/godot/pull/36844> 🤣

**Comment by akien-mga** [comment]
Fixed by https://github.com/godotengine/godot/pull/56639.
