### ISSUE TITLE
ChromeOS documentation

### ISSUE THREAD

**Issue by videlanicolas** [godotengine/godot-docs#5098]
**Your Godot version:**

v3.32.stable.official

**Issue description:**

Since Godot is supported in Linux, can we say it's supported in ChromeOS as well? I'm using it in ChromeOS already and it would've be nice to see in the docs how to install/run the editor in ChromeOS + shortcut mapping (search button + 1 for F1 for example). Given that I've not seen that ChromeOS is a supported platform in Godot (I've not seen the editor as an APK in PlayStore or in the Chrome Web Store), do we want to add ChromeOS related documentation? I volunteer to test/write the documentation missing pieces if so.

**URL to the documentation page (if already existing):**

https://docs.godotengine.org/en/stable/getting_started/editor/default_key_mapping.html

**Comment by Calinou** [comment]
Does a vanilla ChromeOS let you run native ARM64 binaries of your choice? If not, the only way to run Godot is to use the [web editor](https://editor.godotengine.org/).

**Comment by videlanicolas** [comment]
> Does a vanilla Chrome OS let you run native Linux (ARM or x86) binaries of your choice?
Depends on the board listed [here](http://dev.chromium.org/chromium-os/developer-information-for-chrome-os-devices). [Some boards have ARM and others have x86_64](
https://chromium.googlesource.com/chromiumos/docs/+/master/containers_and_vms.md#what-architecture-works-on-my-system). It is possible to run native Linux apps and have a GUI, I'm able to run Godot and Blender as Linux binaries. No GPU support though (yet apparently).

> Note that Godot has no official Linux ARM binaries yet,
The current Linux binary works on my ChromeOS (Jinlon).

**Comment by videlanicolas** [comment]
Ok I found https://github.com/flathub/org.godotengine.Godot to install Godot through flatpak as a Linux app in ChromeOS.

1. Is this officially supported by the Godot team? (seems to be officially supported).
2. Can we add it as supported in [here](https://docs.godotengine.org/en/stable/about/faq.html)?

**Comment by Calinou** [comment]
> Is this officially supported by the Godot team? (seems to be officially supported).

It's in a semi-official state. While I maintain it, it has many blocker issues depending on the platform you're targeting, since you can't export to Android from the Flatpak and C# support is missing. This is why we don't promote it on the website yet.

**Comment by videlanicolas** [comment]
Sounds good, thanks for the explanation!
