### ISSUE TITLE
RootMotionView is undocumented

### ISSUE THREAD

**Issue by algorev** [godotengine/godot-docs#5106]
**Your Godot version:** Godot v3.3.2.stable (from Steam)

**Issue description:**

_Seen behavior:_ Among the nodes available in the Spatial>VisualInstance nodes, there is the RootMotionView node, whose icon is the default grey Node icon. Its tooltip reads "RootMotionView", without any more precision. The documentation page describes its API (I have not checked whether it is correct or not, but I have no reason to think it might not be) without any description of either the node or its properties.

_Expected behavior:_ The node is properly documented, both in the docs and in the editor.

**URL to the documentation page (if already existing):** https://docs.godotengine.org/en/stable/classes/class_rootmotionview.html

**How to reproduce:**

1. Go in the editor and open the "add child node" dialog. Find the RootMotionView node (Node>Spatial>VisualInstance>RootMotionView). Look at either its tooltip or its description.
2. Go in the docs at the page for RootMotionView.

**Comment by Calinou** [comment]
RootMotionView is an editor-only helper, so there isn't much to say about it really.

**Comment by Calinou** [comment]
> Among the nodes available in the Spatial>VisualInstance nodes, there is the RootMotionView node, whose icon is the default grey Node icon

See https://github.com/godotengine/godot/issues/50698.

**Comment by algorev** [comment]
Still, if it weren't supposed to be used, it wouldn't be in the list of nodes right? As @Calinou mentioned, it's even got an icon, even if it wasn't correctly imported in the build.

I personnally think that if it's user-facing, it ought to be documented, so that people can use it (e.g. in tool scripts)
If it isn't supposed to be user-facing and can't be hidden, then a note in the docs saying that this is just an internal API with no guarantees or docs can be just as good.
Anyway, just leaving the docs blank here seems incomplete to me.

It's my first issue on this project, though, so i don't know what the usual approaches for this kind of case are.

-------- Original Message --------

**Comment by Calinou** [comment]
> Anyway, just leaving the docs blank here seems incomplete to me.

Disregard the comment which I since removed :slightly_smiling_face: I ended up completing the documentation here: https://github.com/godotengine/godot/pull/50697
