### ISSUE TITLE
Arc Polygon function missing final point

### ISSUE THREAD

**Issue by LoermansA** [godotengine/godot-docs#5107]
I'm getting started with Godot C# and needed a function to draw part of a circle. I found and used this tutorial:

[Custom drawing in 2D](https://docs.godotengine.org/en/latest/tutorials/2d/custom_drawing_in_2d.html)

However, I think the C# code has an error. When calculating the segments, it misses one final point on the radius.

`var pointsArc = new Vector2[nbPoints + 1];`

should be

`var pointsArc = new Vector2[nbPoints + 2];`

and

`for (int i = 0; i < nbPoints; ++i)`

should be

`for (int i = 0; i <= nbPoints; ++i)`

Try it for an arc of 180 degrees and nbPoints value of 10, you'll see what I mean.

I hope this helps.

Arjan

**Comment by Calinou** [comment]
The issue is not specific to the C# code sample; it's there in the GDScript code sample too.

**Comment by Calinou** [comment]
> `for (int i = 0; i < nbPoints; ++i)`

Can't we change it to `for (int i = 0; i < nbPoints; i++)`?

**Comment by LoermansA** [comment]
> > `for (int i = 0; i < nbPoints; ++i)`
> 
> Can't we change it to `for (int i = 0; i < nbPoints; i++)` to fix this? I'd prefer this personally. Pre-incrementation always looked uncanny to me, and tends to cause difficult-to-notice issues like this.

Tried that, but didn't give the desired result.

**Comment by paulloz** [comment]
Post/Pre incrementation doesn't change anything in this context. The issue is apparently me writing stupid code in the docs a couple of years ago.  
I'm fixing this in a new PR.
