### ISSUE TITLE
Document distributing the Godot editor with a custom feature profile

### ISSUE THREAD

**Issue by k-cabral** [godotengine/godot-docs#5114]
**Your Godot version:** 3.3

**Issue description:**
A common use case for [EditorFeatureProfile](https://docs.godotengine.org/en/stable/classes/class_editorfeatureprofile.html) is allowing educators to reduce the mental load on their students by providing an instance of the engine with reduced features.

The best way to achieve this, currently, is by distributing Godot in self-contained mode, as described in [the related paragraph on the Data Paths tutorial](https://docs.godotengine.org/en/stable/tutorials/io/data_paths.html#doc-data-paths-self-contained-mode), and setting up the intended FeatureProfile beforehand. However, _this usage is not suggested on the EditorFeatureProfile class reference, nor are there are any tutorials describing this use case_.

**Proposed solution:**
I'm willing to create a pull request improving the documentation in that regard, but first I'd like to understand what would be the best approach:
- Adding a new paragraph to the EditorFeatureProfile description, describing this use case and pointing to the relevant documentation (the paragraph linked above). however this would imply linking to the Godot Docs website, which usually occurs only in the "Tutorials" section.
- Adding a link to the Data Paths tutorial in the "Tutorials" section of the EditorFeatureProfile reference. I don't think this would solve the issue, because there would be no context to why it's being linked, i.e. an explanation of the use case mentioned above.

The actual best solution, I believe, would be to write a full tutorial on how to set up this use case, which could then be linked under "Tutorials" from the EditorFeatureProfile. However, I neither have the time nor the qualification to do that right now.

P.S.: I do realize that changes to the class reference should be made to the [other repository](https://github.com/godotengine/godot), however I believe this is a better place to discuss this specific issue.

**URL to the documentation page (if already existing):**
[EditorFeatureProfile class reference](https://docs.godotengine.org/en/stable/classes/class_editorfeatureprofile.html)
[Data Paths tutorial](https://docs.godotengine.org/en/stable/tutorials/io/data_paths.html)

**Comment by pycbouh** [comment]
There is an issue about creating a doc on managing editor features (https://github.com/godotengine/godot-docs/issues/5065). A mention that you can distribute Godot editor with it preconfigured can go there when that article is created.

> P.S.: I do realize that changes to the class reference should be made to the [other repository](https://github.com/godotengine/godot), however I believe this is a better place to discuss this specific issue.

It's completely fine to create an issue in either repository.
