### ISSUE TITLE
style guide for long if statements

### ISSUE THREAD

**Issue by dpensi** [godotengine/godot-docs#5115]
**Issue description:**
In the style guide there's a case that is not specified:
```

if selection.size() == 1 and (
    selection[0] is RoomDesign or \
    selection[0] is DeckDesign ):
```
or

```
if selection.size() == 1 and (
    selection[0] is RoomDesign or \
    selection[0] is DeckDesign
):
```
whitch one is good? whitch one is bad?

**URL to the documentation page (if already existing):** 
https://docs.godotengine.org/en/stable/getting_started/scripting/gdscript/gdscript_styleguide.html

**Comment by AnidemDex** [comment]
**Personally**, when multiple lines comes I preffer do it this way:
```swift
if (
    <first_condition>
    <bool_test> <second_condition>
    <bool_test> <third_condition>
    ...
    <bool_test> <n_condition>
    ):
```
or
```swift
if (<first_condition>
    ...
    <bool_test> <n_condition>
    ):
```

According to [Python PEP8](https://www.python.org/dev/peps/pep-0008/#multiline-if-statements), it suggest that closing bracket `):` would be in the same line as the last condition*, and the boolean test** (`and`, `&&`, `or`, `||`) will be a line _before_ the condition. However, is not limited to the options that they suggest in the PEP.

I _really_ don't like multilines inside the if, or multilines at all. In a script i use to do:
```swift
var condition:bool = (
    <first_condition>
    <bool_test> <second_condition>
    ...
    <bool_test> <n_condition>
    )

if condition:
    ...
```
```swift

var first_condition:bool = <condition>
var second_condition:bool = <condition>
...
var n_condition:bool = <condition>

if first_condition <bool_test> second_condition ... <bool_test> n_condition:
    ...
```
---
In the OP case, I would do something like
```swift
var selection_equal_to_one = selection.size() == 1
if selection_equal_to_one:
  var selection_is_room = selection[0] is RoomDesign
  var selection_is_deck = selection[0] is DeckDesign
  if selection_is_room or selection_is_deck:
    ...
```
or
```swift
func is_room(object:Object) -> bool:
  return object is RoomDesign

func is_deck(object:Object) -> bool:
  return object is RoomDesign

...
#inside another function
  if not selection.size() == 1:
    if is_room(selection[0]) or is_room(selection[0]):
      ...
 ```
 or
 ```swift
 if not selection.size()==1:
  if (selection[0] is RoomDesign) or (selection[0] is RoomDeck):
    ...
 ```
 
 Again, is my personal behaviour. I preffer expend a little more writing explicit things for my future me, than writing things that _just works_.
 
 An style guide about multiline if statements would be good.
\* conditions may be the same as `expression` in the linked documentation, but I'm not sure. I dont want to make confusions about that word.
** I'm not sure if `boolean test` is the right definition about those words.
