### ISSUE TITLE
changing_application_icon_for_windows: Suggested Windows .ico resolutions will not work correctly

### ISSUE THREAD

**Issue by amonroejj** [godotengine/godot-docs#5118]
**Your Godot version:**
3.3.2

**Issue description:**
Docs currently say:

> Your ICO file should at least contain icons in the following resolutions: 16x16, 48x48 and 256x256.

They should say:

> Your ICO file must contain the six sizes 256x256, 128x128, 64x64, 48x48, 32x32, and 16x16.

![image](https://user-images.githubusercontent.com/2057161/127237863-74640aab-51cf-4ed1-b947-97941fbe84ee.png)

This is due to the way Godot uses rcedit to replace the icons in the .exe. If you supply an .ico with fewer than six sizes, leftover sizes from the default godot icon _will remain, and will be mixed with_ your supplied icon:

![image](https://user-images.githubusercontent.com/2057161/127238013-9c481c9c-7344-4ab3-aed1-a5828c858dab.png)

**URL to the documentation page:**
https://docs.godotengine.org/en/3.0/getting_started/workflow/export/changing_application_icon_for_windows.html

If you know how to fix the issue you are reporting please
consider opening a pull request. We provide a tutorial on
using git here: https://docs.godotengine.org/en/stable/community/contributing/pr_workflow.html,
writing documentation at https://docs.godotengine.org/en/stable/community/contributing/docs_writing_guidelines.html
and contributing to the class reference here: https://docs.godotengine.org/en/stable/community/contributing/updating_the_class_reference.html

**Comment by pycbouh** [comment]
> https://docs.godotengine.org/en/3.0/getting_started/workflow/export/changing_application_icon_for_windows.html

Well there's your problem, you're reading outdated docs. Here's the actual article: https://docs.godotengine.org/en/stable/getting_started/workflow/export/changing_application_icon_for_windows.html

**Comment by amonroejj** [comment]
Alas, the second Google search result for "godot exe icon" leads to the 3.0 page, which is how I ended up there.

**Comment by pycbouh** [comment]
Yes, that can happen. Unfortunately, we've have little influence on Google at this point as we're giving all the appropriate information with the pages.

You can make sure that the version of the docs is appropriate by checking this block at the bottom left of the screen:

![image](https://user-images.githubusercontent.com/11782833/127242966-3c31f111-e067-4c71-b2f1-5b7700bf05ad.png)
