### ISSUE TITLE
AnimationPlayer: Better explain "Trigger" and "Capture" Update Modes

### ISSUE THREAD

**Issue by golddotasksquestions** [godotengine/godot-docs#5127]
**Your Godot version:** 3.3.2 stable, 3.4 beta2

**Issue description:**
I have been using Godot and the AnimationPlayer now for almost three years almost daily and I still don't know what "Trigger" and "Capture" update modes are useful for, or what to do with it, how to test this functionality. I was hoping I would develop an intuitive understanding over time, or come across some 3rd party tutorial explaining it, but it seems like this day will never come.

The [AnimationPlayer Documentation](https://docs.godotengine.org/en/3.4/tutorials/animation/introduction.html#id15) is very sparse on this topic to say the least:

> Trigger: Only update the property on keyframes or triggers

What are "triggers"? This is the only place in the I've heard about this and it's not explained any further. I have no clue what so ever what the difference to "Descrete" mode could be.

> Capture: The current value of a property is remembered, and it will blend with the first animation key found

This sounds like it could be useful, but I have no idea what that means in practice and how it would differ to the "Continous" update mode exactly.

The [API docs of the Animation Resource](https://docs.godotengine.org/en/3.4/classes/class_animation.html#class-animation) unfortunately is not helping either:

> UPDATE_DISCRETE = 1 --- Update at the keyframes and hold the value.
> UPDATE_TRIGGER = 2 --- Update at the keyframes.

Well I know keyframes exist to update property values ... But if Trigger does not hold and not interpolate the value like "discrete" or "continuous" would do, what does it do?

> UPDATE_CAPTURE = 3 --- Same as linear interpolation, but also interpolates from the current value (i.e. dynamically at runtime) if the first key isn't at 0 seconds.

This is more explicit and helpful than the explanation in the AnimationPlayer tutorial, and maybe enough for an API reference, but after reading this I'm still not really sure how to apply "Capture" update mode, how to test it, make use of it. After reading this (which is hard to find for a beginner), I would go to the AnimationPlayer tutorial page, expecting a more detailed explanation, but the opposite is the case.

**URL to the documentation page (if already existing):**

https://docs.godotengine.org/en/3.4/tutorials/animation/introduction.html#id15

under UPDATE MODE constants:
https://docs.godotengine.org/en/3.4/classes/class_animation.html#class-animation

**Comment by Calinou** [comment]
> Capture: The current value of a property is remembered, and it will blend with the first animation key found
> 
> This sounds like it could be useful, but I have no idea what that means in practice and how it would differ to the "Continous" update mode exactly.

The Capture mode is only useful if your first keyframe's time is set to a value greater than zero. This is to allow blending the *existing* value (outside the animation) with the first keyframe found in the animation. After the first keyframe, other keyframes will be blended with the continuous blend mode.

This can be used as an alternative to Tween when you want to move a node that could be anywhere to a fixed location.

**Comment by timothyqiu** [comment]
> Well I know keyframes exist to update property values ... But if Trigger does not hold and not interpolate the value like "discrete" or "continuous" would do, what does it do?

If you keyframe `current_animation` of `AnimationPlayer`, it'll be trigger by default. You just want to set the property at the exact position in time. It's equivalent to a `set_current_animation` keyframe on a method calling track.
