### ISSUE TITLE
Dodge the Creeps tutorial shouldn't use `ui_*` builtin actions for character control

### ISSUE THREAD

**Issue by akien-mga** [godotengine/godot-docs#5147]
**Your Godot version:**
3.3, 3.4, latest

**Issue description:**
See this [Twitter thread](https://twitter.com/HeroicoGames/status/1422550096730894340) for context. It's not the first time that I see users being confused by `ui_*` actions, and I think official tutorials shouldn't encourage the bad practice of reusing such actions for character controllers.

The `ui_*` actions are builtin actions used by Controls internally for UI-specific needs. We shouldn't encourage users to bind a gameplay action to e.g. `ui_left` to move the player to the left. Instead, they should be taught how to define their own actions and create e.g. `move_left`, `move_right`, etc. This also makes the code a lot more explicit, as we're moving the player, not navigating the UI.

There's also `ui_select` used later on to start the game. Here one can argue that it's indeed a UI shortcut, but `ui_select` is meant to select (and not activate) any control. So here we're making users define a shortcut which conflicts with the existing selection behavior of whichever Control currently has focus.

Instead, we should define a custom action here too (e.g. `start_game`).

**URL to the documentation page (if already existing):**
https://docs.godotengine.org/en/stable/getting_started/step_by_step/your_first_game.html
https://docs.godotengine.org/en/latest/getting_started/first_2d_game/03.coding_the_player.html
https://docs.godotengine.org/en/latest/getting_started/first_2d_game/07.finishing-up.html

**Comment by seancwall** [comment]
I agree -- I'm looking to fix this.  I'll create a pull request soon.
