### ISSUE TITLE
Clarify the 'Your First Game' Tutorial for 3.0

### ISSUE THREAD

**Issue by mightyCelu** [godotengine/godot-docs#516]
I just did the 'Your First Game' tutorial for godot 3.0 and encountered some issues.

If one follows the tutorial step, some tasks are missing or yield different results than described:

- [X] The Mob's animations are never started
- [X] The direction computation for spawned Mobs did not work for me, the 90° rotation seemed to be the problem (might have been an error on my side). I fixed this by rotating the Mob's AnimatedSprite instead of adding the pi/2 term which I think is a clearer, more understandable approach.
- [X] The last sentence of the 'Main Scene' paragraph, "Now add a script to 'Main'" is misplaced, before scripting there is a paragraph about subclassing the Mob scene
- [X] The MessageTimer should be `one_shot`, otherwise the "Dodge the Creeps!" message will vanish when restarting after game over.
- [x] The image showcasing the anchor does not reflect the current Godot UI (3.0, 409e58e67)
- [x] The label's example settings do not yield the desired result: entering the margin values seems to override the previously set anchor
- [X] The instruction for modifying the label's font is too late, also there is no note about modifying the fontsize. The reader will be confused because even though following the instructions the result won't match the example images
- [X] Adding the HUD-scene to Main is never mentioned by the tutorial, this makes the 'Connecting HUD to Main' paragraph confusing

**Comment by cbscribe** [comment]
Thanks for the feedback. We need people going through the steps and finding gaps so we can make it better.

A few of these things, like the UI issues, are Godot changes that happened after the guide was written.

The rest will be addressed in the second draft, which is happening soon.

**Comment by cbscribe** [comment]
See #517 

I don't think we should worry about making too many more changes to the text just yet. Better to wait for 3.0 beta, when we won't just be chasing feature and UI changes.

**Comment by mightyCelu** [comment]
Thanks for the update. I converted the list in the issue to a task list and checked of the points that were resolved in the PR. Also I fixed a typo.

**Comment by cbscribe** [comment]
Updated with #544

> The Mob's animations are never started

This was clearly indicated in the text

> The direction computation for spawned Mobs did not work for me, the 90° rotation seemed to be the problem (might have been an error on my side). I fixed this by rotating the Mob's AnimatedSprite instead of adding the pi/2 term which I think is a clearer, more understandable approach.

This was a good fix, much clearer and removes possibly confusing code.

> The MessageTimer should be one_shot, otherwise the "Dodge the Creeps!" message will vanish when restarting after game over

This was already in the text, but I added a clarification

> The instruction for modifying the label's font is too late, also there is no note about modifying the fontsize. The reader will be confused because even though following the instructions the result won't match the example images

This was also already in the text, but I updated the image to reflect the text instructions

**Comment by mightyCelu** [comment]
Thanks for the changes. Sorry I missed some of the instructions even though I double checked before opening the issue.

**Comment by velenux** [comment]
To start the Mob animations, I added a simple `process()` function to the `Mob.gd` script, I'm not sure if it's the correct solution, but it worked for me :)

```
func _process(delta):
    $AnimatedSprite.play()
```

**Comment by cbscribe** [comment]
This is unnecessary, since it's setting the property every frame. You could put that in the `_ready()` function, but it's more straightforward to just check the "Playing" box in the Inspector.

**Comment by mightyCelu** [comment]
I initially also enabled it in either the ready or process function. Only after posting this issue I noticed that the text actually mentions checking the 'Playing' box.
Since it looks like I am not the only one missing this point and earlier in the tutorial the same effect was achieved using different means, maybe this could be made a bit more explicit.

**Comment by cbscribe** [comment]
Closed by #956

**Comment by cbscribe** [comment]
It sounds like you didn't make a new DynamicFont resource first. Inside the DynamicFont resource is where you load the font file.

Also, Github issues is for reporting and discussing bugs and software issues, not a place for individual technical support. Please use one of the community support sites found here: https://godotengine.org/community - the Discord and Q&A sites are particularly active and you will get help there.
