### ISSUE TITLE
Incorrect method usage in "Using Servers" page

### ISSUE THREAD

**Issue by Jummit** [godotengine/godot-docs#5168]
**Your Godot version:**

latest

**Issue description:**

The "Optimization using Servers" page gives the wrong parameters to a method:

```gdscript
func _ready():
    # Create the body.
    body = Physics2DServer.body_create()
    Physics2DServer.body_set_mode(body, Physics2DServer.BODY_MODE_RIGID)
    # Add a shape.
    shape = RectangleShape2D.new()
    shape.extents = Vector2(10, 10)
    # Make sure to keep the shape reference!
    Physics2DServer.body_add_shape(body, shape) # doesn't work, needs RID instead of Shape
```

Shapes need to be created using `Physics2DServer.shape_create` and initialized with `Physics2DServer.shape_set_data`, although I'm not sure, hence why I didn't create a pull request.

**URL to the documentation page:**

https://docs.godotengine.org/en/latest/tutorials/performance/using_servers.html#creating-a-2d-rigidbody-and-moving-a-sprite-with-it

**Comment by Calinou** [comment]
See how the Bullet Shower demo does it: https://github.com/godotengine/godot-demo-projects/blob/89978a74211579629349b058a8799859d5d98d13/2d/bullet_shower/bullets.gd#L33-L40

**Comment by anose001** [comment]
Seems like since the introduction of Godot 4 the example "Creating a 2D RigidBody and moving a sprite with it" on the [Using Servers](https://docs.godotengine.org/en/4.2/tutorials/performance/using_servers.html) page is out of date or at least doesn't work properly.
