### ISSUE TITLE
There are three instances of 'printt' in documentation

### ISSUE THREAD

**Issue by graydwarf** [godotengine/godot-docs#5181]
Seen in v3.2.3 and latest

Do a documentation search for 'printt' to find and fix all three instances.
![image](https://user-images.githubusercontent.com/6061635/129745270-730e2cf2-8a96-405a-945e-44080d730390.png)

Once on a given problem page, do a page search for 'printt'.

**Comment by clayjohn** [comment]
``printt()`` is the name of a GDScript function. It prints multiple items with a tab between each. The second "t" stands for "tab". I.e. "print tab"

https://docs.godotengine.org/en/latest/classes/class_@gdscript.html?highlight=Printt#class-gdscript-method-printt

It is similar to ``prints()`` which prints with a space between each argument.

**Comment by graydwarf** [comment]
Oh. I did a search for print in our online documentation thinking it might
be but misunderstood the results. My bad. Thanks!

**Comment by clayjohn** [comment]
No problem! 

Closing now.
