### ISSUE TITLE
String format operator missing from the operator precedence list

### ISSUE THREAD

**Issue by nobuyukinyuu** [godotengine/godot-docs#5193]
**Your Godot version:**
3.3.3

**Issue description:**
The operator precedence list for GDScript seems to be missing the precedence of the format operator `%` (or is ambiguous about contextual difference between format and modulo).  Strings being formatted in statements like `"out=a:%s" if condition else "b:%s" % val` may be ambiguous based on usage scenarios presented in the Format Strings doc as the operator is never used in compound statements in the examples.

**URL to the documentation page:**
https://docs.godotengine.org/en/stable/getting_started/scripting/gdscript/gdscript_basics.html#operators
https://docs.godotengine.org/en/stable/getting_started/scripting/gdscript/gdscript_format_string.html

**Comment by Calinou** [comment]
cc @vnen

**Comment by zacryol** [comment]
For reference, I just checked, and 
```
var val = "eee"
print("one %s" if true else "two %s" % val)
print("one %s" if false else "two %s" % val)
print(("one %s" if true else "two %s") % val)
``` 
gives the output 
```
one %s
two eee
one eee
```
so the format string does have higher precedence than the ternary

**Comment by vnen** [comment]
It's not missing, it's just the same as the remainder/modulo operator since it uses the same symbol (`%`) which is grouped together with multiplication is division.
