### ISSUE TITLE
Incorrect default glow blend mode

### ISSUE THREAD

**Issue by atirut-w** [godotengine/godot-docs#5208]
**Your Godot version:**
3.3.3

**Issue description:**
The list of blend mode says that Screen is the default mode despite Softlight being the actual default in Godot although I'd like the engine to instead change the default to Screen because it's looks better than Softlight.

**URL to the documentation page:**
https://docs.godotengine.org/en/3.3/tutorials/3d/environment_and_post_processing.html

**Comment by Calinou** [comment]
> although I'd like the engine to instead change the default to Screen because it's looks better than Softlight.

We can't change default setting values in Godot 3.x to preserve compatibility with existing projects.

**Comment by atirut-w** [comment]
Can Screen be made into default in 4.0 then? Because it look so much better.

**Comment by Calinou** [comment]
> Can Screen be made into default in 4.0 then? Because it look so much better.

Done: https://github.com/godotengine/godot/pull/52227
