### ISSUE TITLE
Overview of the UI system

### ISSUE THREAD

**Issue by NathanLovato** [godotengine/godot-docs#522]
The current docs lack a hub article for the UI system. This is a complete intro to the core concepts behind it, all in one place. It serves as a hub to learn more about various parts of the API:
- Control vs Node2D
- anchors
- containers
- simple nodes

TODO:

- [x] Write section dedicated to the Layout menu as it works differently from Anchor
- [x] Write an intro to the interactive anchor tool (unavailable now)
- [x] Write a note about the 2 available workflows: containers or layout mode

**Comment by NathanLovato** [comment]
PR up: https://github.com/godotengine/godot-docs/pull/511

**Comment by groud** [comment]
Copy-paste from fb:
I see some mistake, which is normal as the new anchor system is very close to the old one but not really:
- In the figure in the section "Anchors are relative to the parent container", the right margin should be negative. Indeed, the right side of the node is at the left of the anchor pin (so the offset is negative).
- "The margin changes with the anchors" this is a little bit confusing, as indeed the values of the margin in the property editor never change if the parent is resized. It's more like the node sides are bound to each respective anchor. The figure is also confusing too, as i would expect the right and bottom margin to be negative (if they were not in a container).
- In fact, It's better to consider that the anchors and margins are not considered if a node is a child of a container, as it is the parent that decides those values. (in some cases this is false, like for the MarginContainer I belive)
- In fact you have two ways to build GUIs in Godot, either using anchors and margins OR containers, mixing both is possible but may not work in all situations.

For me it would be a lot more understandable if we distinguish strongly the two possible workflows: anchors/margins-based or container-based.

As I worked a lot on the new control anchors/margins system, if you need more input on that don't hesitate to mail me.

The remaining parts are perfect
