### ISSUE TITLE
Suggestions for Squash the creeps

### ISSUE THREAD

**Issue by ghost** [godotengine/godot-docs#5230]
**Your Godot version:**
3.4-beta4
**Issue description:**
In "Moving the player with code" it says:
> Here's where the magic happens. Select the CameraPivot and rotate it 45 degrees around the X axis (using the red circle). You'll see the camera move as if it was attached to a crane.

I think this should be -45 degrees since rotating it 45 degrees just shows the default gray background.

In "Spawning monsters" it says:
> The grid is a bit distracting for me. You can toggle it by going to the View menu in the toolbar and clicking View Grid.

I'm not sure the docs should use first-person. Who's me? 😛 

>     var mob_spawn_location = get_node("SpawnPath/SpawnLocation")
>     # ...
>     var player_position = $Player.transform.origin

Both `get_node()` and `$` are used in the same code block with no explanation.

In "Jumping and squashing monsters" it says:
> Set its Collision -> Layer to "enemies" and unset its Collision -> Mask, leaving the mask empty.

But the squashing only works when I have the collision mask set to the world layer for some reason. Either that, or I am really bad at playing the game.

In "Killing the player" it says:

> Try the game again by pressing F5. If everything is set up correctly, the character should die when an enemy runs into it.

But I think it should also mention that the game is expected to crash here as well.

In "Character animation" it says:

> Open the player scene, select the player node, and add an animation player node.

I think this should be `AnimationPlayer` as that's the name of the node.

**URL to the documentation page (if already existing):**
https://docs.godotengine.org/en/latest/getting_started/first_3d_game/index.html

**Comment by Florian-Schoenherr** [comment]
as this seems a little like a meta-issue and I have only a small "bug" to note:
in https://docs.godotengine.org/en/latest/getting_started/first_3d_game/09.adding_animations.html#animating-the-mobs
the wording is reversed/confused, it should be:

Open the Player scene, select the AnimationPlayer node and open the float animation. Next, click on Animation -> Copy. Then open Mob.tscn and add an AnimationPlayer node. Then, on the animation dock, click Animation -> Paste. That's it; all monsters will now play the float animation.

**Comment by skyace65** [comment]
This was fixed in #6121
