### ISSUE TITLE
Tutorial link to OpenGameArt.org page is landing on access denied page 

### ISSUE THREAD

**Issue by graydwarf** [godotengine/godot-docs#5258]
**Issue description:**
'https://opengameart.org/users/tgfcoder' link on 'https://docs.godotengine.org/en/stable/tutorials/2d/2d_sprite_animation.html' page is landing on an 'Access Denied' page. Assume it's not just me that is getting access denied.

https://github.com/godotengine/godot-docs/blob/master/tutorials/2d/2d_sprite_animation.rst - about the 3rd paragraph in the Note section.

Not sure what artwork we were linking to so can't recommend a fix.

**Comment by Calinou** [comment]
I can confirm this too – tgfcoder likely deleted their account.
