### ISSUE TITLE
Overview of the Animation Tools

### ISSUE THREAD

**Issue by NathanLovato** [godotengine/godot-docs#526]
Show what's possible with the anim tools. It's not only for visual anim: used to control any property (callbacks to the set() method)
- the basics (keys, AnimPlayer and path to properties, etc.)
- animating colliders
- animating "hidden" properties (inside resources, e.g. shaders)
- function calls
- the api's most useful functions

**Comment by dploeger** [comment]
I'll cover the basics about the AnimationPlayer UI.

**Comment by NathanLovato** [comment]
Edited your comment with the parts you'll write

**Comment by dploeger** [comment]
The draft will live here: https://github.com/dploeger/godot-docs/blob/master/526/features-animation-introduction-2d.md

**Comment by dploeger** [comment]
Reviewed the draft and updated some things based on the doc writer guidelines. Could you please review it now?

**Comment by NathanLovato** [comment]
Reviewing now

**Comment by dploeger** [comment]
Updated the documentation based on your suggestions. Please review again.

**Comment by NathanLovato** [comment]
It's a lot better already! Still some long bullet lists, but as it is it's good to add to the official docs imo - already a lot better than previously available content. Thank you very much for your hard work!
