### ISSUE TITLE
Add tutorial section detailing how to actually contribute to the engine to the tutorials.

### ISSUE THREAD

**Issue by SilencedPerson** [godotengine/godot-docs#5265]
### Describe the project you are working on

a game

### Describe the problem or limitation you are having in your project

I would like to start contributing to development of Godot. There is infinite amount of small paper cuts that require some love and i would like to be among people to do something about them. However I don't really know where to start, I never really contributed any code to open source project let alone C++ and the task at hand seems daunting. I am sure I can learn C++ but where do i start with the rest of the process? For now i am stuck making proposals bringing attention to the small issues.

The idea of contributing is very alien to me, I don't even know how to contribute to the documentation itself.

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

While right now, i can go to Youtube and learn thousand ways of how to make games in Godot, the entry point to the contribution side of this is clouded in mystery and the existing documentation is not very helpful. Improve the documentation and the community will provide the tutorials eventually.

What is the step 1?
What is the step 2?
and the step after that?

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

Add this to the tutorials section.

![image](https://user-images.githubusercontent.com/82024211/133770058-9b12b5b7-ba8e-4988-bc81-ba06bfaf9ead.png)

I mean the existing documentation is nice but i am no smarter than i started. I still don't know the step 1 and quite frankly.
I require little bit more hand holding on this topic and i imagine lot of Godot users too.

![image](https://user-images.githubusercontent.com/82024211/133770777-c8998ca9-9737-4f4e-85e2-18d4b9922b80.png)
![image](https://user-images.githubusercontent.com/82024211/133770870-619102e2-f0c6-4367-932b-e8b2208fdf1e.png)

I mean, did this tell you what to do first?
There is soo much foreword but the step 1 is still no more clearer than it was before i read this.

### If this enhancement will not be used often, can it be worked around with a few lines of script?

No, i am afraid this cannot be worked around with a script...

### Is there a reason why this should be core and not an add-on in the asset library?

This is about documentation and tutorials.

**Comment by skyace65** [comment]
I agree with pycbouh. I think what the documentation covers right now is good enough.

**Comment by skyace65** [comment]
Closing per my and Yuri's comments
