### ISSUE TITLE
Wrong variable name in Dictionary page

### ISSUE THREAD

**Issue by MrMandolino** [godotengine/godot-docs#5269]
**Issue description:**
In the Dictionary type page, there's a miswritten variable after the example code (`points_dict ` -> `points_dir`).

![immagine](https://user-images.githubusercontent.com/54510819/133933534-11746a51-ff1a-4d13-b3cb-61d86f950737.png)

**URL to the documentation page:**
https://docs.godotengine.org/en/stable/classes/class_dictionary.html

**Comment by pycbouh** [comment]
Feel free to open a PR! 🙂 Make sure to do that on the main repo, as that's where the class reference is tracked: https://github.com/godotengine/godot/tree/master/doc/classes

Refer to the documentation on [contributing to the class reference](https://docs.godotengine.org/en/stable/community/contributing/updating_the_class_reference.html).

**Comment by zacryol** [comment]
https://github.com/godotengine/godot/pull/53076
