### ISSUE TITLE
How to Animate Characters

### ISSUE THREAD

**Issue by NathanLovato** [godotengine/godot-docs#528]
Current rigging system in 3.0 and differences with a regular modular anim workflow:
- how to rig character (fake bones)
- building the setup anim
- designing interactive anims, toggling flags and collisions (link to and from the overview article)
- playing sound from anim
- animating sprites for modular animators

**Comment by JuanNeedsToApologize** [comment]
Not a high priority at all, voting to close.

**Comment by NathanLovato** [comment]
With the many changes in Godot 3.1 regarding anim, this needs a rethink. Not sure it fits the Getting Started section anymore either now there's more content.
