### ISSUE TITLE
Text instructions in "Your First Game" are GDScript-specific

### ISSUE THREAD

**Issue by wlwl2** [godotengine/godot-docs#5280]
**Your Godot version:**
stable for the docs

v3.3.3.stable.mono.official [b973f997f] for the engine I'm using.

**Issue description:**

`extends Area2D` doesn't exist in C#:

```
Add the following at the top of the script, after `extends Area2D`:
```

There is another issue where I can probably do the fix, but the Edit on Github link is broken.

**URL to the documentation page (if already existing):**
https://docs.godotengine.org/en/stable/getting_started/step_by_step/your_first_game.html#preparing-for-collisions

**Comment by pycbouh** [comment]
> the Edit on Github link is broken.

Ah, it's not broken, it just always links to the master branch (we cannot do anything about it I'm afraid). Just substitute `master` with `3.4` and you'll get the relevant doc:

https://github.com/godotengine/godot-docs/blob/3.4/getting_started/step_by_step/your_first_game.rst

Feel free to open a PR!
