### ISSUE TITLE
Why is the value of value changed to 5？

### ISSUE THREAD

**Issue by MorseSUN** [godotengine/godot-docs#5282]
using Godot;
public class stats : Node
{            
      [Export]  private int Max_Health=8;
      public int health;
      public int set_health
    {   
        get { return health; }
        set
        {
            this.health=value;
            GD.Print(set_health);
            GD.Print(health);
            GD.Print(this.health);
            if (set_health<=0)
            {
            EmitSignal(nameof(shuchuxinhao));                       
            }   
        }    
    }
           public override void _Ready()
    {
        health=Max_Health;
        GD.Print(health);
    }  
     [Signal] delegate void shuchuxinhao();
     
![@M0{WN9$U0G4 3GQ$C$2ILR](https://user-images.githubusercontent.com/91387924/134781316-87c8ef6d-5d1c-4a9d-bb30-8a25d4834981.png)

}

**Comment by MorseSUN** [comment]
![AZV3I QXX5IR PXZ25 0D$F](https://user-images.githubusercontent.com/91387924/134781665-0ad1b34a-2888-4701-a7a2-ba12dfff2ed9.png)
I don't know what went wrong.This problem has been bothering me for nearly 2 days.Is there a god who can help me?

**Comment by pycbouh** [comment]
Hi! This is an issue tracker for Godot documentation. If you need help with your project, you need to join one of our community platforms, such as Discord or forums, and look for assistance there.

https://godotengine.org/community
