### ISSUE TITLE
CollisionObjects Overview

### ISSUE THREAD

**Issue by cbscribe** [godotengine/godot-docs#530]
Overview of the CollisionObject(2D) types: Area(2D), StaticBody(2D), RigidBody(2D), KinematicBody(2D). Goal is to help beginners understand when and why to choose a particular class.

- Definitions
- Use cases for each body type
- Using collision shapes
- Brief code examples

**Comment by NathanLovato** [comment]
Ping @Calinou as you wrote the 3D page, and I believe you mentioned a 2D page was planned too?

**Comment by Calinou** [comment]
@NathanLovato Yes, I'm currently working on a page for 2D collision shapes :slightly_smiling_face:

**Comment by NathanLovato** [comment]
I assigned you then if you're on it.

**Comment by Calinou** [comment]
This was addressed by https://github.com/godotengine/godot-docs/pull/4040 and https://github.com/godotengine/godot-docs/pull/4203, closing.
