### ISSUE TITLE
Inconsistent naming conventions when loading classes in GDScript Basics page

### ISSUE THREAD

**Issue by scottmpowell** [godotengine/godot-docs#5308]
**Your Godot version:** stable, 3.4, 3.3, 3.2

**Issue description:**
The GDScript basics page uses inconsistent naming conventions in the "Classes as resources" section. 

`var my_class = load("myclass.gd")`
and
`const MyClass = preload("myclass.gd")`

This is inconsistent with the Godot Style Guide, which says to use PascalCase when loading a class into a constant or a variable. Just a minor typo, so it should be easy to clarify. 

**URL to the documentation page (if already existing):**
https://docs.godotengine.org/en/stable/getting_started/scripting/gdscript/gdscript_basics.html#classes-as-resources

**Comment by Calinou** [comment]
Fixed by https://github.com/godotengine/godot-docs/pull/5309.
