### ISSUE TITLE
Revise Vector Math Article

### ISSUE THREAD

**Issue by cbscribe** [godotengine/godot-docs#532]
Language needs to be cleaned up - it's currently too informal and "jokey". The basic content is solid, but needs to be more concise.

**Comment by cbscribe** [comment]
Intro completed with #572

Advanced content still needs work.

**Comment by pwab** [comment]
Saw this [feedback on reddit](https://www.reddit.com/r/godot/comments/7yl7ys/godot_30_finally_wrapped_my_head_around_vector/) about the math article section:

> **Forward vector**
> Speaking from my experience, it took me quite a white to figure out why my maths was not working out because I did not know that -z in an objects local coordinate system was forward. (-1) * get_global_transform().basis.z was not too intuitive for me, other engines provide convenience methods for that.
>
> **Lerping**
> I know there is a class for tweening/lerping, but if you want to do it manually such as with Vector3.linear_interpolate(), there are not a lot of examples on how to use it correctly. The blog I linked helped a lot in that regard.
>
> --- [MrMinimal](https://www.reddit.com/user/MrMinimal)

The blog article mentioned can be found here:
http://codetuto.com/2016/01/godot-engine-movement-and-rotation-basics/

**Comment by aaronfranke** [comment]
Related: #2753

By the way, is the "3.0 Getting started" milestone still relevant?

**Comment by NathanLovato** [comment]
Is this issue still relevant?

**Comment by Meriipu** [comment]
I think so, unless anything changed since https://github.com/godotengine/godot-docs/pull/572

**Comment by NathanLovato** [comment]
Okay, so advanced vector math needs editing, thanks!

**Comment by cbscribe** [comment]
Closing, as this has been updated since. Feel free to open a new issue if you find something missing.
