### ISSUE TITLE
Add a community-driven export template repository

### ISSUE THREAD

**Issue by JeffVenancius** [godotengine/godot-docs#5330]
**Your Godot version:**
3.3.3
**Issue description:**
As people can choose how to build their release binaries, it would make sense to have a repo with the most used ones. If many project doesn't uses 3D, for example, instead of create a new build from source, which takes time, people could simply download it from the repo.
It is, indeed, a huge scope to do it for every possible way, but as I've said, it would be only with the most used ones, and people could vote in that, also.
One thing it could be potentially done is to automatize this and even create builds that cuts some resources besides modules (unused nodes, etc) - I'm working on something like this.

Well, I've made a repo as an experiment today, feel free to, I don't know, get the idea:
https://github.com/TheCowOhBoy/GodotBuildsLibrary

**URL to the documentation page (if already existing):**
https://docs.godotengine.org/en/stable/development/compiling/optimizing_for_size.html

**Comment by pycbouh** [comment]
I've not seen a lot of interest in the community to provide custom export template configurations. It would not be a very efficient system, as if you want to start customizing templates, it's better done on a per-project basis. We also cannot build all the variations, as compiling production builds takes several hours for each release that we publish (not to mention that you need to host it somewhere, and we don't have an unlimited amount of space for it either).

I think providing a customizable GitHub action may be a better idea. You'd just set it up in your repo and it'll do the necessary heavy-lifting for you.

**Comment by pycbouh** [comment]
This should also probably be a proposal? At first I considered you might want us to maintain an article on the docs that lists the templates provided by community. But it seems that you want a proper web portal for that instead, so it's not really relevant to this repository.

**Comment by JeffVenancius** [comment]
Oh, right. Sorry,I didn't know where to put because it was kinda of grey to me. I think I'll post it again there. Better yet, I'll work on that idea a litlle more before that. Thanks!

**Comment by Calinou** [comment]
Also, third-party builds should be linked to with care for security reasons. If a third-party is compromised for any reason, you'll be spreading malware through your exported projects :slightly_smiling_face:
