### ISSUE TITLE
Incomplete docs in latest version - listening to player input

### ISSUE THREAD

**Issue by SuPythony** [godotengine/godot-docs#5358]
**Your Godot version:**
Latest docs

**Issue description:**
The end of the summary is incomplete.

**URL to the documentation page:**
https://docs.godotengine.org/en/latest/getting_started/step_by_step/scripting_player_input.html

**Comment by pycbouh** [comment]
The line was added in https://github.com/godotengine/godot-docs/pull/4325 like that.

@NathanLovato can you take a look and tell if there was something important that needed to be added there, or if it's enough to just add a generic remark?

**Comment by NathanLovato** [comment]
A generic remark will do the job. No need to add a link as there's the next button right next to the text, if that's what you meant.
