### ISSUE TITLE
Suggest building server in debug mode first and most prominently

### ISSUE THREAD

**Issue by johnfn** [godotengine/godot-docs#5360]
**Issue description:**

The docs suggest to build a release build for server builds. The first thing you'll want to do when working on multiplayer games is to make a debug build, so we should probably suggest that first. The documentation should have 3 commands to paste into the terminal - the debug server build, the release server build, and the headless build.

I make this suggestion because I followed the instructions and didn't realize that I was in release mode for a while (because I didn't expect that to be what I had built). 

**URL to the documentation page (if already existing):**

https://docs.godotengine.org/en/stable/development/compiling/compiling_for_osx.html#compiling-a-headless-server-build

**Comment by Calinou** [comment]
An headless editor build can be used as a game server, and it's always a debug build. Therefore, I'm not sure we need to advertise building a debug server build.

**Comment by johnfn** [comment]
Let me give you my perspective of how a novice (me :P) reads these lines, with all my misconceptions in-tact:

> To compile a headless build which provides editor functionality to export projects in an automated manner, use:

Huh? I don't need editor functionality. I just want a local sever to run on the terminal. This seems like overkill, maybe it's for CI or something - I don't really understand the purpose of this. 

> "To compile a server build which is optimized to run dedicated game servers"

Ah yes, that sounds like exactly what I want! (Obviously, I'm wrong here :P)

Anyway, the 4.0 change sounds great - can't wait! 😉
