### ISSUE TITLE
rename collision_layer in Physics2DShapeQueryParameters to collision_mask

### ISSUE THREAD

**Issue by eitantsu** [godotengine/godot-docs#5364]
**Your Godot version:**
3.3.4
stable docs

**Issue description:**
in the page about Physics2DShapeQueryParameters, collision_layer should be changed to "collision_mask", as mask is the correct one here.
as can be seen in the 3d PhysicsShapeQueryParameters, in which it is named correctly.

**URL to the documentation page:**
[https://docs.godotengine.org/en/stable/classes/class_physics2dshapequeryparameters.html](https://docs.godotengine.org/en/stable/classes/class_physics2dshapequeryparameters.html)
[https://docs.godotengine.org/en/stable/classes/class_physicsshapequeryparameters.html](https://docs.godotengine.org/en/stable/classes/class_physicsshapequeryparameters.html)

**Comment by zacryol** [comment]
This seems to have already been fixed for 4.0
Even on 3.x, the property has internally been renamed, but gets exposed via `collision_layer` still to maintain compatibility.

**Comment by zacryol** [comment]
you can see at https://github.com/godotengine/godot/blob/3.x/servers/physics_2d_server.cpp#L226

```cpp
ClassDB::bind_method(D_METHOD("set_collision_layer", "collision_layer"), &Physics2DShapeQueryParameters::set_collision_mask);
ClassDB::bind_method(D_METHOD("get_collision_layer"), &Physics2DShapeQueryParameters::get_collision_mask);
```

**Comment by eitantsu** [comment]
yeah i see it now, guess i'll close this then.
