### ISSUE TITLE
Add missing properties in NavigationPolygon's documentation

### ISSUE THREAD

**Issue by felaugmar** [godotengine/godot-docs#5365]
**Your Godot version:**
3.4 RC 2

**Issue description:**
These added properties are missing in the `NavigationPolygon` doc-page.
![image](https://user-images.githubusercontent.com/11199582/139856343-44106c21-6167-463c-bdba-601ef9e532c4.png)

**URL to the documentation page (if already existing):**
https://docs.godotengine.org/en/3.4/classes/class_navigationpolygon.html

**Comment by felaugmar** [comment]
Looks like it's on purpose for these properties to be hidden in the documentation, I'm closing this issue.

**Comment by Calinou** [comment]
Indeed, `PROPERTY_USAGE_NOEDITOR | PROPERTY_USAGE_INTERNAL` will do that :slightly_smiling_face:
