### ISSUE TITLE
Tell why to use Node instead of Node2D in your first game

### ISSUE THREAD

**Issue by SuPythony** [godotengine/godot-docs#5366]
**Your Godot version:**
Latest docs

**Issue description:**
In the starting of the page we are told to use `Node` for the root node and not `Node2D`. But it doesn't tell why. I think there should be an explanation why to prefer or not prefer `Node` over `Node2D`.

**URL to the documentation page (if already existing):**
https://docs.godotengine.org/en/latest/getting_started/first_2d_game/05.the_main_game_scene.html

**Comment by rossunger** [comment]
I made a PR:
https://github.com/godotengine/godot-docs/pull/5530

**Comment by SuPythony** [comment]
Great! So we could have used Node2D too, or would it break the game?

**Comment by SuPythony** [comment]
I just checked the docs page but it hasn't been updated on the website. The repository is updated but the website isn't. When does the documentation website update?

**Comment by SuPythony** [comment]
Ok! So, as I am currently learning Godot, and I read the latest version of the docs, will it be a problem later on?

**Comment by Calinou** [comment]
> Ok! So, as I am currently learning Godot, and I read the latest version of the docs, will it be a problem later on?

You should read the `stable` branch, as `latest` contains information that's only relevant for Godot 4.0alpha.
