### ISSUE TITLE
Tutorial: Porting from 2.1 to 3.0

### ISSUE THREAD

**Issue by cbscribe** [godotengine/godot-docs#537]
From the Sept Patreon poll.

I'm willing to take a stab at it, but anyone's welcome to take this one.  I'm thinking it'll probably need to wait until at least Beta.

**Comment by jaggygames** [comment]
I'd love to know how to even tackle porting from 2.1 to 3.0. Not sure what needs to change or what can be just copied over.

**Comment by mhilbrunner** [comment]
Relevant:
https://github.com/dploeger/godot-migrationnotes

**Comment by NathanLovato** [comment]
We're still missing the latest version of the project Godot 2 to 3 converter, aren't we? If a 2.1.x update comes out with it soon after 3.0 it may be best to wait for it rather than writing a comprehensive guide that may become obsolete fast.

**Comment by mhilbrunner** [comment]
Sure, we may hope so, but IMO that isn't very realistic. IMO the changes are enough that you'd probably need a strong AI to figure it out in all circumstances. No automatic converter will be able to figure out that your numbers are in degrees but get used for `CanvasLayer.rotation ` somewhere which is no in radians.

We should at least polish up the migration notes dploeger painstakenly assembled and keep it around somewhere in the docs.

**Comment by Calinou** [comment]
I'll close this as Godot 3.0 was released a long time ago (January 2018). A tutorial for converting a project from Godot 2.1 to Godot 3.0 would likely not be very relevant by now.

People who are looking for a Godot 2.1 -> 3.0 migration guide should refer to https://github.com/dploeger/godot-migrationnotes.
