### ISSUE TITLE
4.0 - Step by step instancing example error in zip 

### ISSUE THREAD

**Issue by ueco-jb** [godotengine/godot-docs#5373]
**Your Godot version:**
4.0.dev.custom_build.9f46ce865

**Issue description:**
Syntax for importing and creating new variables changed in development version:
https://godotengine.org/article/gdscript-progress-report-new-gdscript-now-merged
ZIP file in Step by step instancing tutorial are outdated.

**URL to the documentation page:**
https://docs.godotengine.org/en/latest/getting_started/step_by_step/instancing.html#in-practice

**Comment by NathanLovato** [comment]
The whole getting started series isn't ported to Godot 4 yet, and won't be until Godot 4 is at least in beta: anything is subject to change until then, meaning this intro series could break anytime.

**Comment by ueco-jb** [comment]
Yeah, now I know. It was more or less explained in issue I created, but thank you.

**Comment by skyace65** [comment]
Fixed by https://github.com/godotengine/godot-docs-project-starters/pull/3
