### ISSUE TITLE
EditorSceneImporter doc is stale

### ISSUE THREAD

**Issue by rcorre** [godotengine/godot-docs#5385]
**Your Godot version:**

3.4

**Issue description:**

https://github.com/godotengine/godot/blob/3.4/doc/classes/EditorSceneImporter.xml#L45-L53 does not match https://docs.godotengine.org/en/3.4/classes/class_editorsceneimporter.html#class-editorsceneimporter-method-import-animation-from-other-importer (3 args vs 4).

**URL to the documentation page:**

https://docs.godotengine.org/en/3.4/classes/class_editorsceneimporter.html#class-editorsceneimporter-method-import-animation-from-other-importer

If you know how to fix the issue you are reporting please
consider opening a pull request. We provide a tutorial on
using git here: https://docs.godotengine.org/en/stable/community/contributing/pr_workflow.html,
writing documentation at https://docs.godotengine.org/en/stable/community/contributing/docs_writing_guidelines.html
and contributing to the class reference here: https://docs.godotengine.org/en/stable/community/contributing/updating_the_class_reference.html

(sorry, source looks right to me, so I'm not sure).

**Comment by skyace65** [comment]
Looks like it's been fixed now. This issue can be closed.
