### ISSUE TITLE
Demo: Scaling

### ISSUE THREAD

**Issue by cbscribe** [godotengine/godot-docs#539]
From the Aug Patreon poll.

Demonstrate options for scaling to various resolutions.

**Comment by Calinou** [comment]
I'll close this, as this is now implemented in the [3D Viewport Scaling Demo](https://github.com/godotengine/godot-demo-projects/tree/master/viewport/3d_scaling) in addition to the [Multiple resolutions](https://docs.godotengine.org/en/latest/tutorials/viewports/multiple_resolutions.html) page.
