### ISSUE TITLE
Make translation of shortcut list and command-line interface command list read-only? 

### ISSUE THREAD

**Issue by dewcked** [godotengine/godot-docs#5390]
**Your Godot version:**
3.4
**Issue description:**
commands in command-line interface tutorial and shortcut keys and editor settings in shortcuts tutorial don't need translation.
There are tons of copy-and-paste things to translate. and If original string is changed, it might be better not to translate them.

**URL to the documentation page (if already existing):**
https://docs.godotengine.org/en/stable/getting_started/editor/command_line_tutorial.html

https://docs.godotengine.org/en/stable/getting_started/editor/default_key_mapping.html

**Comment by Calinou** [comment]
These pages should ideally still be translated, but the key/option names should be left unchanged.

**Comment by pycbouh** [comment]
Note that the key mapping page will ultimately be generated from sources. So I'm not sure how the translation will be implemented in the end. (Probably with some XML file similar to class ref?)

**Comment by dewcked** [comment]
Oh.. then I should just let it be for now.
