### ISSUE TITLE
Some strings have double colons at the end.

### ISSUE THREAD

**Issue by dewcked** [godotengine/godot-docs#5392]
**Your Godot version:**
3.4
**Issue description:**
Some strings have double colons at the end. Do they need fix?
**URL to the documentation page (if already existing):**
Following search shows all strings that have double colons at the end.
https://hosted.weblate.org/translate/godot-engine/godot-docs/en/?offset=1&q=source:+r"\:\:$"&sort_by=-priority%2Cposition&checksum=
General usage of colon in my opinion
https://hosted.weblate.org/translate/godot-engine/godot-docs/en/?offset=1&q=source%3A+r"[^\%3A]{1}\%3A%24"&sort_by=-priority%2Cposition&checksum=

**Comment by pycbouh** [comment]
Strings with double colons at the end are shorthand syntax to start a code block afterwards. They don’t need fixing, but maybe we should consider replacing them with full notation if it looks confusing for translators.

**Comment by dewcked** [comment]
Thank you for clear explanation 👍

**Comment by yilmazdurmaz** [comment]
Only after about 30 translations with double colon, I thought about it might be a feature and there is only this issue to explain it.

> Strings with double colons at the end are shorthand syntax to start a code block afterwards

I have recently translated "how to contribute" parts and haven't seen this one documented there. Although a small detail, I think it will be much better to document it there.
