### ISSUE TITLE
Demo: Mini-RPG

### ISSUE THREAD

**Issue by cbscribe** [godotengine/godot-docs#540]
From the Sept Patreon poll.

Not sure about the scope of this one. Whatever "Mini" means to you.

**Comment by MoraleMuffin5** [comment]
I'd do this, if jitter was fixed and the renderer supported AMD and NVIDIA GPUs..

Doesn't seem like a high priority though

"Kicking to 3.1, wait, 4.0"

**Comment by keyboardmuffin45** [comment]
Not an issue at all, voting to close this.

**Comment by Taulborg01** [comment]
@cbscribe not really a high priority. Focus should be on 3d imo.
