### ISSUE TITLE
Document how to customize AndroidManifest.xml and include additional resources

### ISSUE THREAD

**Issue by Gromph** [godotengine/godot-docs#5402]
**Your Godot version:**
3.4

**Issue description:**
Support was added for adding custom items to AndroidManifest.xml, but it doesn't appear to be document.
This issue mentions it: https://github.com/godotengine/godot/issues/25062
It also mentions it is documented on the Custom Builds for Android page, but it that page doesn't say anything about AndroidManifest.xml

Looking through the export source(platform\android\export\export_plugin.cpp) I found that it is supported to customize AndroidManifest.xml  by creating a file AndroidManifest.conf in the right place. For example create the file in your godot project folder:
android/game/AndroidManifest.conf

Containing:
```
[application]
<meta-data android:name="com.google.android.gms.games.APP_ID" android:value="@string/app_id" />
<meta-data android:name="com.google.android.gms.version" android:value="@integer/google_play_services_version"/>
```

It also appears to support a gradle.conf file, but I didn't try it out.

Also related is I needed to include an ids.xml   in res/values.  I stumbled upon that it will auto include and merge the file if in the right place. For example I created:
android/game/res/values/ids.xml
```
<?xml version="1.0" encoding="utf-8"?>

<resources>
  <string name="app_id">1234</string>
</resources>
```

I assume it would be possible to include other android resources the same way, but haven't verified yet.

**URL to the documentation page (if already existing):**
https://docs.godotengine.org/en/latest/tutorials/export/android_custom_build.html

**Comment by m4gr3d** [comment]
@Gromph The `AndroidManifest.conf` and `gradle.conf` are leftovers of previous logic which is considered deprecated for Godot 3.x.
There will be fully removed in Godot 4.x.

Can you create an issue in the Godot issue tracker and describe what you're trying to accomplish.

Thanks!
