### ISSUE TITLE
Sidebar doesn't display properly in NetSurf

### ISSUE THREAD

**Issue by curiousjunior** [godotengine/godot-docs#5410]
you may blame web browser for not implementing html5, css3 and javascript, but to me it's a feature that doesn't eat all my laptop's resources so that I don't need to close online docs when working in the editor

![godot_netsurf](https://user-images.githubusercontent.com/79333625/143288432-0caa96f6-f288-4900-9ab8-15a94c0de77a.png)

**Comment by Calinou** [comment]
Can you reproduce this on https://docs.godotengine.org/en/3.0/ ? If so, this is an issue with the Read the Docs Sphinx theme and should be reported upstream.

**Comment by curiousjunior** [comment]
yeah, it's reproducible

ok, I reported this to upstream https://github.com/readthedocs/sphinx_rtd_theme/issues/1257

**Comment by Calinou** [comment]
Closing as this is an upstream issue.
