### ISSUE TITLE
General lack of clarity for Camera2D properties and methods.

### ISSUE THREAD

**Issue by Mickeon** [godotengine/godot-docs#5417]
**Your Godot version:**
v3.4.stable
**Issue description:**
Some sections of Camera2D's documentation seem to be written too vaguely. Its properties depend on each other, yet these refer to each other inconsistently in their own descriptions. It doesn't help that some Camera2D's property names can be somewhat confusing, further hurting the readability of the documentation.

General list of issues:
- Missing explanations to mitigate the confusion between Camera2D properties with similar names.
- Small, but several, unintuitive word choices, such as different terms being used to refer to the same concept (e.g. target or tracked node, camera move or camera scroll), or vague definitions that cause ambiguity (camera position, offset)

A specific list of examples:
- **align**: _"Aligns the camera to the **tracked** node"_ inconsistency with `smoothing_enabled` and `rotating`'s description (_"camera smoothly moves towards the **target**"_ and _"the camera rotates with the **target**"_, respectively);
- **rotating**: "If true, the camera rotates with the target" is a possibly misleading description, as the Camera2D node itself does rotate through its parent class Node2D's `rotation` properties;
- **smoothing_speed**: _"Speed in pixels per second of the camera's smoothing effect"_, may not actually be speed in pixels per second. https://github.com/godotengine/godot/issues/49747#issuecomment-864444744
- **limit_smoothed**: _"This has no effect if smoothing is disabled."_ should reference the property directly _"This property has no effect if `smoothing_enabled` is set to false"_;
- **offset_h**: _"Note: Offset H is used only to force offset relative to margins. It's not updated in any way if drag margins are enabled and can be used to set initial offset"_ may be worded better. _"Offset H"_ should not be capitalised like this, as it refers to the property directly;
- **offset_v**: Should have the same note as offset_h instead of referring to it, for integrity and consistency with similar documentation;
- **get_camera_position ( )**: Lack of further detail on what the returned value is, missing comparison to `get_camera_screen_center ( )`, despite both returning similar values upon first glance;
- **make_current ( )**: _"Make this the current 2D camera for the **scene (viewport and layer)**, in case there are many cameras in the scene"_ is very awkwardly worded (perhaps even incorrect?), missing reference to the `current` property that serves a similar purpose;
- **reset_smoothing ( )**: _"This has no effect if smoothing is disabled"_ should reference the property directly _"This method has no effect if `smoothing_enabled` is set to false"_.

Some of these examples are down to opinion, but the main issue is a lack of consistency. The Camera2D node has some minor, cumulative complexities that should be explained more clearly.

**URL to the documentation page (if already existing):**
https://docs.godotengine.org/en/stable/classes/class_camera2d.html?#class-camera2d-property-current

**Comment by Calinou** [comment]
Feel free to open a pull request for this on the main Godot repository :slightly_smiling_face: 

See [Contributing to the class reference](https://docs.godotengine.org/en/latest/community/contributing/updating_the_class_reference.html) for guidelines.
