### ISSUE TITLE
Can't export only PCK file

### ISSUE THREAD

**Issue by curiousjunior** [godotengine/godot-docs#5420]
**Your Godot version:** 3.4.stable.official.206ba70f4

**Issue description:**
```
$ godot --path ~/.steam/steam/steamapps/common/Godot\ Engine/demos/3d/platformer --export pck platformer.pck
Godot Engine v3.4.stable.official.206ba70f4 - https://godotengine.org
 
reimport: begin: (Re)Importing Assets steps: 1
	reimport: step 0: shine.png
ERROR: Invalid export preset name: pck.
The following presets were detected in this project's `export_presets.cfg`:

        "Linux/X11"
        "Android"

   at: _fs_changed (editor/editor_node.cpp:801)
reimport: end
```

**URL to the documentation page:** https://docs.godotengine.org/en/stable/getting_started/workflow/export/exporting_projects.html#exporting-from-the-command-line

**Comment by Calinou** [comment]
The documentation's example command  points to an export preset named `pck`, but it's a confusing name for an export preset name.
