### ISSUE TITLE
Why the movement need to multiple `delta` when using `MoveAndSlide()` ?

### ISSUE THREAD

**Issue by steelywing** [godotengine/godot-docs#5432]
**Your Godot version:**

3.4

**Issue description:**

In the following movement code, `MoveAndSlide()` will care about `delta`, why it need to multiple `delta`? may be just change the `FallAcceleration = 14` (it = 75 in the doc) and not multiple `delta` is fine?

```
        // Ground velocity
        _velocity.x = direction.x * Speed;
        _velocity.z = direction.z * Speed;
        // Vertical velocity
        _velocity.y -= FallAcceleration * delta;
        // Moving the character
        _velocity = MoveAndSlide(_velocity, Vector3.Up);
```

And, is it good to notice `MoveAndSlide()` will care about `delta`?

**URL to the documentation page:**

https://docs.godotengine.org/en/latest/getting_started/first_3d_game/03.player_movement_code.html

**Comment by Henodude** [comment]
This is so the y velocity will smoothly decrease. If it did not multiply by ``delta``,  gravity would apply differently depending on the framerate. ``move_and_slide()`` does already multiply by ``delta`` for movement, but you still need to multiply by ``delta`` for any form of acceleration. 
Hope this helped.

**Comment by steelywing** [comment]
> This is so the y velocity will smoothly decrease. If it did not multiply by `delta`, gravity would apply differently depending on the framerate. `move_and_slide()` does already multiply by `delta` for movement, but you still need to multiply by `delta` for any form of acceleration. Hope this helped.

If so, why X and Z don't multiple the `delta`? and [godot move_and_slide() doc](https://docs.godotengine.org/en/stable/classes/class_kinematicbody.html#class-kinematicbody-method-move-and-slide) says

> linear_velocity is the velocity vector (typically meters per second). Unlike in move_and_collide, you should *not* multiply it by delta — the physics engine handles applying the velocity.

**Comment by Henodude** [comment]
> If so, why X and Z don't multiple the `delta`?

In this example, the x and z velocities are set to direction * speed and don't accelerate, so you don't need to multiply anything by ``delta``. If you add or subtract any value for acceleration (in this case, ``fall_acceleration``), you should multiply the acceleration value by ``delta``, because it will make the value update smoothly. We're not actually multiplying the y velocity by ``delta`` here, only ``fall_acceleration``. 

Hope this makes sense.

**Comment by steelywing** [comment]
I make a Test for this issue

```cs
using Godot;
using System.Diagnostics;

public class Player : KinematicBody
{
    private Stopwatch duration = new Stopwatch();
    private bool useDelta = false;
    // ...

    public override void _PhysicsProcess(float delta)
    {
        // ...

        // Vertical velocity
        // Change this line
        // _velocity.y -= FallAcceleration * delta;
        // to this
        _velocity.y -= FallAcceleration * (useDelta ? delta : (1/60f));

        if (Input.IsKeyPressed((int)KeyList.Key1))
        {
            Engine.IterationsPerSecond = Input.IsKeyPressed((int)KeyList.Shift) ? 60 : 30;
            GD.Print($"IterationsPerSecond: {Engine.IterationsPerSecond}");
        }

        if (Input.IsKeyPressed((int)KeyList.Key2))
        {
            useDelta = Input.IsKeyPressed((int)KeyList.Shift);
            GD.Print($"Use delta: {useDelta}");
        }

        if (IsOnFloor() && !duration.IsRunning && Input.IsActionJustPressed("jump"))
        {
            duration.Restart();
            _velocity.y += 60;
            GD.Print("Timer start");
        }

        if (IsOnFloor() && duration.IsRunning && duration.ElapsedMilliseconds > 1000) 
        {
            duration.Stop();
            GD.Print(duration.Elapsed);
        }
    }
}
```

Press `1` will set `IterationsPerSecond` to `30`, `Shift+1` to `60`
Press `2` to use fixed `FallAcceleration` (no `delta`), `Shift+2` to multiple `delta`

In the test, if multiple `delta`, the duration of 30FPS jump become double of 60FPS.
if don't multiple `delta`, the duration is same.

**Comment by steelywing** [comment]
Thanks, I made a test to change `IterationsPerSecond` in runtime, *you are right*, but I still don't understand why need to multiple the `delta`  🤦‍♂️
