### ISSUE TITLE
How ARRAY_BONES and ARRAY_WEIGHTS are used in procedural mesh generation?

### ISSUE THREAD

**Issue by Luk3M** [godotengine/godot-docs#5434]
**Your Godot version:** 3.2.1

**Issue description:** I was trying to generate a mesh by script, and I'm having some doubts with managing bones, their weights and creating a skeleton.

The documentation link below is a great source for explaining about vertex, but all the examples avoid bones. The part:

`ARRAY_BONES = 6 | PoolRealArray of groups of 4 floats or PoolIntArray of groups of 4 ints`

Does not explain what those 4 ints were supposed to mean. Maybe it's something obvious, and me being a noob in 3d graphics might be a issue, but `ARRAY_TANGENT` has a exaplanation of their floats, and it would be nice having one in `ARRAY_BONES` and `ARRAY_WEIGHTS` too.

**URL to the documentation page (if already existing):**
https://docs.godotengine.org/en/stable/tutorials/content/procedural_geometry/arraymesh.html

**Comment by pycbouh** [comment]
As far as I know, you use `ARRAY_BONES` to store the indices of bones that affect any given vertex, with up to 4 bones having an effect on a single vertex. Your model may have many bones, all of which are indexed in some manner, and to know which of the bones out of all of them affect each vertex you use their indices here. `ARRAY_WEIGHTS` contains a weighted value of how much each bone affects the vertex. It would probably be a float between 0.0 and 1.0.

E.g.
```
bones:   [   3,   12,   45,    1 ]
weights: [ 0.1, 0.65, 0.23, 0.94 ]
```

You can read it as bone number 12 has a weight of 0.65.

Each set of 4 values in those arrays is read as belonging to a single vertex. So if you have an array of vertices of a size 10, you'll have 40 entries for bones and weights. Godot, internally, expects all 4 items to be present, so if you edit this data manually (e.g. using the mesh data tool) keep in mind to give all 4 bones and all 4 weights.

**Comment by Luk3M** [comment]
> As far as I know, you use `ARRAY_BONES` to store the indices of bones that affect any given vertex, with up to 4 bones having an effect on a single vertex. Your model may have many bones, all of which are indexed in some manner, and to know which of the bones out of all of them affect each vertex you use their indices here. `ARRAY_WEIGHTS` contains a weighted value of how much each bone affects the vertex. It would probably be a float between 0.0 and 1.0.
> 
> E.g.
> 
> ```
> bones:   [   3,   12,   45,    1 ]
> weights: [ 0.1, 0.65, 0.23, 0.94 ]
> ```
> 
> You can read it as bone number 12 has a weight of 0.65.
> 
> Each set of 4 values in those arrays is read as belonging to a single vertex. So if you have an array of vertices of a size 10, you'll have 40 entries for bones and weights. Godot, internally, expects all 4 items to be present, so if you edit this data manually (e.g. using the mesh data tool) keep in mind to give all 4 bones and all 4 weights.

Thank you! If I have the time, I'll add this information in the tutorial.

**Comment by Luk3M** [comment]
> Godot, internally, expects all 4 items to be present, so if you edit this data manually (e.g. using the mesh data tool) keep in mind to give all 4 bones and all 4 weights.

I was changing the documentation, but I wanted to make sure before an PR:

Can I assume that I can fill an group of 4 in `ARRAY_BONES` with -1 if there's less than 4 bones influencing a vertex? Or should I use an random index (e.g. 0) and then put the weight in `ARRAY_WEIGHTS` at 0.0? I guess that is essentially the same thing, but I don't know if there's some special performance case in any method.
