### ISSUE TITLE
"Edit on GitHub" button gives an 404 on tutorial sections of the docs

### ISSUE THREAD

**Issue by Luk3M** [godotengine/godot-docs#5435]
**Your Godot version:** 3.2.1

**Issue description:** The button "Edit on GitHub inside the documentation redirects to the wrong URL.

When clicking it on the page [Using the ArrayMesh](https://docs.godotengine.org/en/stable/tutorials/content/procedural_geometry/arraymesh.html), the url it redirects the user is:
* `https://github.com/godotengine/godot-docs/blob/master/tutorials/content/procedural_geometry/arraymesh.rst`

The correct URL would be:
* `https://github.com/godotengine/godot-docs/blob/master/tutorials/3d/procedural_geometry/arraymesh.rst`

This appears to happen in every page under the [Creating content](https://docs.godotengine.org/en/stable/tutorials/content/index.html) series of tutorials in the docs (including itself).

**URL to the documentation page:** https://docs.godotengine.org/en/stable/tutorials/content/procedural_geometry/arraymesh.html

**Comment by Calinou** [comment]
URLs have changed on the `master` branch as part of a content reorganization. However, this change won't be carried over to old documentation branches such as `3.3` and `3.2`. Therefore, this can't be resolved as the *Edit on GitHub* URL can't be customized on a per-page basis (and it's not possible to make redirects for those).
