### ISSUE TITLE
Document the RESET track in the AnimationPlayer

### ISSUE THREAD

**Issue by and-rad** [godotengine/godot-docs#5438]
**Your Godot version:**
3.4 & above

**Issue description:**
The RESET track in the `AnimationPlayer` node is not documented. Relevant PRs that contain some info about the functionality are:
- https://github.com/godotengine/godot/pull/43115
- https://github.com/godotengine/godot/pull/55653

**URL to the documentation page (if already existing):**
https://docs.godotengine.org/en/stable/tutorials/animation/introduction.html talks about creating Animation Players, so this might be a good place to put it.

**Comment by zacryol** [comment]
should probably be right at the end of this section: https://docs.godotengine.org/en/latest/tutorials/animation/introduction.html#adding-a-track

**Comment by zacryol** [comment]
I also see an immediate self-contradiction in that page a bit earlier
![image](https://user-images.githubusercontent.com/60046681/150652416-0204cb52-4d58-4a8f-ad24-51bc5a16a8d0.png)

**Comment by zacryol** [comment]
> should probably be right at the end of this section: https://docs.godotengine.org/en/latest/tutorials/animation/introduction.html#adding-a-track

though there's also https://docs.godotengine.org/en/latest/tutorials/animation/animation_track_types.html
