### ISSUE TITLE
Document how to erase ProjectSettings custom setting

### ISSUE THREAD

**Issue by me2beats** [godotengine/godot-docs#5497]
**Your Godot version:**
3.4

**Issue description:**
In docs I couldn't find info how to remove a setting from ProjectSettings that I add from a plugin using `set_setting()`
But it seems setting the setting to null works

**URL to the documentation page (if already existing):**
this info could be somewhere here https://docs.godotengine.org/en/stable/classes/class_projectsettings.html

**Comment by skyace65** [comment]
Could you give an example of a plugin with project settings so I can test this?

**Comment by me2beats** [comment]
```gdscript
tool
extends EditorPlugin

func _enter_tree():

	ProjectSettings.set_setting("my_section/my_group/my_prop", 1) #(1)
	ProjectSettings.set_setting("my_section/my_group/my_prop", null) #(2)

```
(1) creates `my_prop` value 
(2) erases it immediately

**Comment by Calinou** [comment]
You can check out [this add-on](https://github.com/Calinou/godot-photo-mode-demo/tree/master/addons/photo_mode) (`master`) for a "proper" way of adding custom project settings with hints and all that.

**Comment by skyace65** [comment]
Ok I think I get most of that now. But what's the reason to delete a setting this way with code instead of going to project settings, clicking on the setting and using the delete button?

**Comment by me2beats** [comment]
There could be a lot of cases, mainly using plugins tho.
For example erasing the whole group or even a section of properties.
Plugin settings could be used to for project related settings of a plugin, so for example another plugin to remove settings of unused plugins would be created.

**Comment by skyace65** [comment]
@me2beats Thank you, I've opened a PR to document this.
