### ISSUE TITLE
Your first 2D game - 4.0 readying

### ISSUE THREAD

**Issue by BryanQuigley** [godotengine/godot-docs#5498]
**Your Godot version:** 4.0

**Issue description:** There are a few places where things have changed in 4.x.  I'm stuck on a few, but appear to be mostly easy fixes?

https://docs.godotengine.org/en/latest/getting_started/first_2d_game/04.creating_the_enemy.html 
Many node names have changed slightly.

https://docs.godotengine.org/en/latest/getting_started/first_2d_game/05.the_main_game_scene.html
export doesn't work here either, this is where I got stuck

**Comment by TechnicalSoup** [comment]
> **URL to the documentation page:** https://docs.godotengine.org/en/latest/getting_started/first_2d_game/03.coding_the_player.html uses export, tried changing to @export but that didn't work

I found that changing **export** to **@export** worked - and I was able to see that variable in the Inspector. You're correct in that it should be shown with the preceding @ symbol in this guide/tutorial.

I'm using the 4.0 build from 20220118 on Windows 11 (64 bit)

**Comment by BryanQuigley** [comment]
Thanks, I think I must have not been inspecting the right thing. That first one works now. The last export I need to find new syntax I guess?

**Comment by TechnicalSoup** [comment]
> The last export I need to find new syntax I guess?

I think the format for the second export will be `@export var mob_scene: PackedScene` although I haven't actually tested that out myself yet. I'll have a go at it in the next few days and let you know if it works.

**Comment by BryanQuigley** [comment]
That worked with one other change:
var mob = mob_scene.instantiate() #was instance

Also had to change some rand_range -> randi_range

**Comment by acristin** [comment]
There are a few renames needed for the 4.0 beta. 

In section 5, "The main game scene":
* [Position2D has been renamed Marker2D](https://github.com/godotengine/godot-proposals/issues/5199)
* [PathFollow2D.origin is now PathFollow2D.progress_ratio](https://github.com/godotengine/godot/commit/bb936b2e273cc3ae1c7d775a0ab7e0e7e2a256a9).

I made an attempt at a fix, but I haven't tested the C# and C++ changes for origin -> progress_ratio. I'll try to verify those soon and update the PR if needed, but the guesses seem reasonable.

**Comment by TheYellowArchitect** [comment]
This is the last one remaining from making the tutorial fully compatible with 4.0
https://github.com/godotengine/godot-docs/issues/6234

**Comment by YuriSizov** [comment]
This was fixed by multiple PRs, namely https://github.com/godotengine/godot-docs/pull/6275 (wasn't linked properly). If there are any missing renames or examples of outdated syntax, please open new issues.
