### ISSUE TITLE
Document that `InstancePlaceholder` shouldn't be used in tool

### ISSUE THREAD

**Issue by me2beats** [godotengine/godot-docs#5504]
**Your Godot version:**
3.4

**Issue description:**
![test](https://user-images.githubusercontent.com/16458555/148709602-608f3800-b417-4e25-81ca-ac8f4d715fe8.JPG)

`Placeholder` is a scene that has `Load As Placeholder` enabled
when I do `scene - reload saved scene`, `_ready()` is called and the child is printed.
But it prints `Control`, and I expect it to be a `InstancePlaceholder`
because I didn't `create_instance()` etc
And if I hit F6, it prints `InstancePlaceholder` as expected

I kinda understand why this is happening (to work in the editor as with a regular node - Control in this case).
but at the same time this means that I cannot use this in tool mode, since the node will be created/replaced automatically immediately.

I had an idea to use it in the plugin as a part of the UI scene.

**URL to the documentation page (if already existing):**
https://docs.godotengine.org/ru/stable/classes/class_instanceplaceholder.html

**Comment by KoBeWi** [comment]
Well, the first sentence of the description already mentions that:
> Turning on the option Load As Placeholder for an instanced scene in the editor causes it to be replaced by an InstancePlaceholder when running the game.

Indirectly, but it doesn't imply at all that the node will be replaced in the editor. The option just marks the instance to be replaced at runtime.
