### ISSUE TITLE
Put an isometric autotile templates on the Using TileMaps page.

### ISSUE THREAD

**Issue by ShatReal** [godotengine/godot-docs#5505]
**Your Godot version:**
3.4.2

**Issue description:**
The page doesn't have one. I made one (3x3 minimal). Please tell me if this one is acceptable.

![iso3](https://user-images.githubusercontent.com/69117768/148872077-38c98848-dd56-47a2-81a7-bfa7550f2f80.png)

**URL to the documentation page (if already existing):**
https://docs.godotengine.org/en/latest/tutorials/2d/using_tilemaps.html

**Comment by ShatReal** [comment]
I made a 2x2 version
![2_1](https://user-images.githubusercontent.com/69117768/148874483-bb2cf103-7bca-4ae8-a922-df4e6481e9bc.png)

**Comment by ShatReal** [comment]
Actually, I think these may be better
![large](https://user-images.githubusercontent.com/69117768/148879955-b27816ff-9c4a-45bd-a797-17152a166e7a.png)
![small](https://user-images.githubusercontent.com/69117768/148879957-7e1b4d1d-9146-4fbb-b36a-258275d809d2.png)

**Comment by ShatReal** [comment]
Closed by #6164

**Comment by Calinou** [comment]
Reopening, as the associated pull request hasn't been merged yet.

**Comment by ShatReal** [comment]
the page has been split into two, this issue isn't relevant anymore
