### ISSUE TITLE
4.0 Packed*Array pass by reference

### ISSUE THREAD

**Issue by cdemirer** [godotengine/godot-docs#5511]
**Your Godot version:**
latest - 4.0.dev (dcd2364da)

**Issue description:**
In `Built-in types` section, it says:
> (Packed arrays such as PackedByteArray are still passed as values.)

However, the current & (as far as I know) expected behavior is that they pass by reference in almost all cases. 
It might be the case that they pass by value when provided as an argument to non-gdscript functions only: https://github.com/godotengine/godot/pull/36492#issue-569558185

**URL to the documentation page:**
https://docs.godotengine.org/en/latest/tutorials/scripting/gdscript/gdscript_basics.html#built-in-types

**Comment by tetrapod00** [comment]
Closing as fixed in https://github.com/godotengine/godot-docs/pull/7603.
