### ISSUE TITLE
add_child has a confusing argument called legible_unique_name

### ISSUE THREAD

**Issue by lyuma** [godotengine/godot-docs#5515]
**Your Godot version:**
4.0.dev 49482966
**Issue description:**
add_child has a new boolean argument called `legible_unique_name` which defaults to `false`, and the docs currently say.

```
If legible_unique_name is true, the child node will have a human-readable name based on the name of the node being instantiated instead of its type.
```

I cannot understand what this means. Is it supposed to be true or false in a tool script? what about runtime? which is more performant?

I am inclined to use the default argument of `false`, but fire told me I should use true. I don't understand why.

**URL to the documentation page:**
https://docs.godotengine.org/en/latest/classes/class_node.html#class-node-method-add-child

If you know how to fix the issue you are reporting please
consider opening a pull request. We provide a tutorial on
using git here: https://docs.godotengine.org/en/stable/community/contributing/pr_workflow.html,
writing documentation at https://docs.godotengine.org/en/stable/community/contributing/docs_writing_guidelines.html
and contributing to the class reference here: https://docs.godotengine.org/en/stable/community/contributing/updating_the_class_reference.html

**Comment by pycbouh** [comment]
It is mostly used by the editor, so I guess it can make sense to use it in some tool scripts, when you are changing the scene itself.

You don't need to use it if you give a node a name yourself. But if you don't it can be useful to replace those seemingly random numerical names which you can see during the runtime, e.g. `@@10`, with a human-identifiable name based on the type of the node, e.g. `VScrollBar`.

![image](https://user-images.githubusercontent.com/11782833/149511964-831df1f6-3714-4e74-8625-f2ccf2bdb01c.png)

**Comment by Mickeon** [comment]
I was browsing here out of interest. Turns out this has been addressed by https://github.com/godotengine/godot/pull/64463.

**Comment by YuriSizov** [comment]
Indeed, this is addressed now.
