### ISSUE TITLE
Add NavigationServer examples.

### ISSUE THREAD

**Issue by Xyotic** [godotengine/godot-docs#5531]
**Your Godot version:** 3.5.1-beta1

**Issue description:**
Currently, the documentation lacks NavigationServer2D and NavigationServer3D examples
There should be basic examples on how to set up a simple navigation mesh (maybe just a plane),
how to request a path using map_get_path,
and how to set up agents to use with the collision avoidance system. 

**URL to the documentation page (if already existing):**
https://docs.godotengine.org/en/latest/classes/class_navigationserver2d.html?highlight=navigationserver
https://docs.godotengine.org/en/latest/classes/class_navigationserver3d.html?highlight=navigationserver

**Comment by skyace65** [comment]
Examples for all 3 of those have been added to the navigation section of the docs [here](https://docs.godotengine.org/en/latest/tutorials/navigation/index.html).

**Comment by Xyotic** [comment]
Thanks!
