### ISSUE TITLE
Stable branch displaying some older 3.3 docs.

### ISSUE THREAD

**Issue by snailrhymer** [godotengine/godot-docs#5548]
**Your Godot version:** "Stable"

**Issue description:** The docs at https://docs.godotengine.org/en/stable/ state that they are 3.4 docs:

![image](https://user-images.githubusercontent.com/61291296/151072353-7a44994f-c4a2-46e8-a0c5-32884781a300.png)

 There are at least two instances (and likely many more - I encountered one naturally and didn't have to look far for another) where docs at least as old as 3.3 are being shown.

1. [Documentation changelog](https://docs.godotengine.org/en/stable/about/docs_changelog.html), e.g. under "Shading". See v: stable:

![image](https://user-images.githubusercontent.com/61291296/151071226-af7f8375-3524-498e-8699-046019874575.png)

v: 3.3:

![image](https://user-images.githubusercontent.com/61291296/151071360-75deed51-3ed2-4659-9f85-701562207dc1.png)

v: 3.4:

![image](https://user-images.githubusercontent.com/61291296/151071278-4bce6702-be05-4b12-95e3-1b63dd3cfee5.png)

2. [Contributing](https://docs.godotengine.org/en/3.3/community/contributing/index.html). The contents page, but also many of the links.

v: stable:

![image](https://user-images.githubusercontent.com/61291296/151071884-78eaf8e0-1c2f-407f-a0b5-6838b04864de.png)

v: 3.3:

![image](https://user-images.githubusercontent.com/61291296/151071963-a86171d8-5d47-44f8-b342-64774925a4eb.png)

v:3.4:

![image](https://user-images.githubusercontent.com/61291296/151072040-6c50693d-7cda-435c-9f17-fafd2654fbf9.png)

**URL to the documentation page:** Included above

**Comment by mhilbrunner** [comment]
Yeah we didn't push 3.4 to the stable docs yet as there were some CI issues. Will fix today, thanks!

**Comment by mhilbrunner** [comment]
Fixed in https://github.com/godotengine/godot-docs/commit/e1a544c0f85bce87c15b11e619a7e48f1e9fb529, this should be up on the website in an hour or so :)
