### ISSUE TITLE
Broken formatting and missing paragraphs on "Creating Android plugins" page

### ISSUE THREAD

**Issue by szymonm-google** [godotengine/godot-docs#5559]
**Your Godot version:**
Docs version: 3.4

**Issue description:**
Broken formatting and missing paragraph on 

Missing paragraph ("3."):
<img width="211" alt="image" src="https://user-images.githubusercontent.com/80777504/151442787-b7135cca-f99a-46be-a7c6-2b5419f27f44.png">

Broken formatting:
<img width="398" alt="image" src="https://user-images.githubusercontent.com/80777504/151442995-e1bfb7e3-fde0-42b9-b6ba-8e9a7ef9da63.png">

<img width="204" alt="image" src="https://user-images.githubusercontent.com/80777504/151443139-31ab4c27-a8bc-4de7-ac31-429bc3fa9dea.png">

Missing paragraph "remote:" and copy-paste issues:
<img width="379" alt="image" src="https://user-images.githubusercontent.com/80777504/151443638-0df7090b-3660-4c83-abcd-df22a82bbb95.png">

**URL to the documentation page:**
https://docs.godotengine.org/en/3.4/tutorials/platform/android/android_plugin.html

**Comment by Calinou** [comment]
Fixed by https://github.com/godotengine/godot-docs/pull/5560.
