### ISSUE TITLE
Collission Mask has been moved from PhysicsBody2D to CollissionObject2D

### ISSUE THREAD

**Issue by karl-run** [godotengine/godot-docs#5561]
**Your Godot version:**
v3.4.2.stable.official [45eaa2daf]

**Issue description:**
In the "Your first 2D game » Creating the enemy" section of the docs it seems that the P"hysicsBody2D > PhysicsBody2D > Mask" property has been moved to ColissionObject2D, without the docs having been updated to reflect this.

**URL to the documentation page:**
https://docs.godotengine.org/en/stable/getting_started/first_2d_game/04.creating_the_enemy.html

**Comment by skyace65** [comment]
This was fixed by #5485 a few days ago. This issue can be closed.
