### ISSUE TITLE
(4.0) Menu items sometimes show in a different position

### ISSUE THREAD

**Issue by seppoday** [godotengine/godot-docs#5569]
**Your Godot version:**
4.0 alpha 1 
**Issue description:**
![image](https://user-images.githubusercontent.com/62170071/151660284-bc7b1cc8-156c-4034-8eaf-0a702a491db7.png)

**URL to the documentation page:**

If you know how to fix the issue you are reporting please
consider opening a pull request. We provide a tutorial on
using git here: https://docs.godotengine.org/en/stable/community/contributing/pr_workflow.html,
writing documentation at https://docs.godotengine.org/en/stable/community/contributing/docs_writing_guidelines.html
and contributing to the class reference here: https://docs.godotengine.org/en/stable/community/contributing/updating_the_class_reference.html

**Comment by Calinou** [comment]
Duplicate of https://github.com/godotengine/godot/issues/45740.
