### ISSUE TITLE
Docs: Screenshots for project folder and Godot's FileSystem are not consistent

### ISSUE THREAD

**Issue by d3ce1t** [godotengine/godot-docs#5571]
As you can see at https://docs.godotengine.org/en/stable/getting_started/first_2d_game/01.project_setup.html, dodge_assets shouldn't be in the FileSystem.

![image](https://user-images.githubusercontent.com/3706385/151671262-f52d01ce-d36b-4291-b296-93751d5684fd.png)

![image](https://user-images.githubusercontent.com/3706385/151671276-c69713c5-ad45-491a-81bc-d848eb13510d.png)

I guess it should show something like this:

![image](https://user-images.githubusercontent.com/3706385/151671308-9c501fcf-637c-4cef-b784-e02f6575446a.png)

**Comment by skyace65** [comment]
You're right, it should look like the bottom image. You can open a PR to fix this.

**Comment by d3ce1t** [comment]
Sorry, I'm not gonna be able to do it in the short term
