### ISSUE TITLE
is_action_released is in documentation but not stable release

### ISSUE THREAD

**Issue by digiraver** [godotengine/godot-docs#5575]
**Your Godot version:**
3.4.2 stable (Steam)

**Issue description:**
In the 'stable' documentation it discusses the is_action_released option of the Input method. According to my stable version of Godot is_action_released does not exist.

**URL to the documentation page:**
https://docs.godotengine.org/en/stable/classes/class_inputevent.html#class-inputevent-method-is-action-released

From my Godot screen...
![godotDOC](https://user-images.githubusercontent.com/301322/151699968-237af789-acdc-4465-a0f9-2c08f51d25b3.png)
![godotDOC2](https://user-images.githubusercontent.com/301322/151700065-b775453e-88af-40df-9942-787a3e74aae1.png)

**Comment by Calinou** [comment]
Did you use `Input.is_action_released()` or `event.is_action_released()`? These are not the same, as `event` is of type InputEvent.

**Comment by aaronfranke** [comment]
Closing due to the above. The docs are for `InputEvent` but the user is trying to call this method on the `Input` singleton.
