### ISSUE TITLE
`warp_mouse_position` documentation is misleading

### ISSUE THREAD

**Issue by navett52** [godotengine/godot-docs#5576]
**Your Godot version:**
3.4.2

**Issue description:**
At least on the Linux version of visual server the `warp_mouse_position` function uses the passed `Vector2` as an offset from the top left of the window, it does not use the `Vector2` to set the position to in-engine coordinates (local or global), which is what the following description led me to believe.
> Sets the mouse position to the specified vector.

**URL to the documentation page (if already existing):**
https://docs.godotengine.org/en/stable/classes/class_input.html#class-input-method-warp-mouse-position

**Comment by TechnicalSoup** [comment]
I did a little test on my Windows 11 install and noticed a similar behaviour. Basically the warp occurs to an absolute location referenced to the top left of the window.

Interestingly I was able to put negative values in the vector and warp the cursor to a position beyond the game window (obviously not in full screen mode). I believe this is only possible is the cursor/mouse is not captured by the game window.

From the little bit of digging I did through the code, for Windows the warp is done in screen coordinates, relative to the focused window. The windows API call will limit/clip this to make sure the cursor doesn't move off the screen.

Without having looked over the code for the other platforms, I'm guessing the behaviour will be similar there. If this is the desired operation of the function I'm happy to put a more detailed description into the docs.
