### ISSUE TITLE
Broken Links in class_inputevent.html

### ISSUE THREAD

**Issue by SolsticeProjekt** [godotengine/godot-docs#5580]
It's in the docs for stable.

There's two $DOCS_URL variables instead of the actual words making the link.

https://docs.godotengine.org/en/stable/classes/class_inputevent.html

Simply search for $DOCS_URL in the source of the webpage to find the two broken links.
The *latest* version of the docs does not contain that error, btw.

The URL's in the stable release should point to:

https://docs.godotengine.org/en/stable/tutorials/inputs/input_examples.html with their respective tags.

Thank you.

**Comment by akien-mga** [comment]
Thanks for the report. Fixed by https://github.com/godotengine/godot/commit/1891c8e172786c05d3e3217e275765c47695dfbb.
