### ISSUE TITLE
"First 2D Game" tutorial has outdated font workflow

### ISSUE THREAD

**Issue by b4ux1t3** [godotengine/godot-docs#5584]
**Your Godot version:**
3.4.2.stable.mono

**Issue description:**
The instructions in the "First 2D Game" tutorial seem to reference an incorrect or outdated workflow for adding fonts into a project.

Here's a screenshot of the instructions and the screenshot included with them side by side with what the stable release UI looks like:
![image](https://user-images.githubusercontent.com/5150833/152656676-eb8b7217-fc7a-41f9-bc79-62fbd357d594.png)

**URL to the documentation page:**
https://docs.godotengine.org/en/stable/getting_started/first_2d_game/06.heads_up_display.html

I am planning on spinning up a PR shortly with updated instructions and screenshot(s?). I just want to finish working through the section I'm on to make sure I don't need to update anything else!

**Comment by b4ux1t3** [comment]
I just noticed that there are screenshots in the `img` directory for the newer workflow. I'll use those as the reference screenshots.

**Comment by b4ux1t3** [comment]
Actually, upon closer examination of master, the correct workflow is already documented. It looks like there's a mismatch between the official docs (link in the initial post here) and what exists in master [here](https://github.com/godot/godot-docs/blob/master/getting_started/first_2d_game/06.heads_up_display.rst). I take it to mean that the official site docs will (soon?) reflect the updated workflow.

**Comment by pycbouh** [comment]
`master` version is not the `stable` version of the docs, it's the `latest` version of the docs. It was indeed updated, but we still need a PR for the `3.4` branch to fix the stable version.

There was a bit of a mixup, but basically this PR (https://github.com/godotengine/godot-docs/pull/5564) needs to be remade for the `3.4` branch, then it can be merged, then it can be synced with `stable`, and only then you'll see it on the website :)

**Comment by b4ux1t3** [comment]
Gotcha! I'll close this, since it's not relevant given the larger picture. Thanks for the info!
