### ISSUE TITLE
GDScript "Exporting arrays" section needs to be updated for new `@export` syntax in 4.0

### ISSUE THREAD

**Issue by AttackButton** [godotengine/godot-docs#5592]
### Godot version

v4.0.alpha.custom_build [f425d403f]

### System information

Windows 8 and 10

### Issue description

Can't specify the type of the elements using the @export in the new annotation system (https://docs.godotengine.org/en/latest/tutorials/scripting/gdscript/gdscript_exports.html#exporting-arrays) in compassion with the old system.

I tried @export_array(NodePath) or something similar with no success.

This is the only way to export arrays right now, I think:
`@export var waypoints: Array = []`

As the @export accept no argument and is for simple variables, there are nothing like the examples below in the new system yet:

```
@export(Array, NodePath) var new_paths
@export(Array, PackedScene) var scenes
@export(Array, int) var ints = [1, 2, 3]
```

![image](https://user-images.githubusercontent.com/25422687/153396280-9f4f0f77-59cd-44e8-b59a-edc689a98359.png)

The workaround is to just set the types one by one in the editor.

### Steps to reproduce

Try to export an array with specified type of the elements using the new annotation system.

**Comment by AttackButton** [comment]
> I believe the correct syntax is:
> 
> `@export var waypoints: Array[int] = [2, 3]`

Thanks, it's working. As @akien-mga said, it's just the docs needing an update.

**Comment by trash-max** [comment]
> I believe the correct syntax is:
> 
> `@export var waypoints: Array[int] = [2, 3]`

Thanks, it's really working.
Please, update export section in docs.

**Comment by pycbouh** [comment]
> Please, update export section in docs.

PRs are welcome 🙃

**Comment by mohamedAdhamc** [comment]
> > Please, update export section in docs.
> 
> PRs are welcome 🙃

will do right now xd

**Comment by mhilbrunner** [comment]
Closed by https://github.com/godotengine/godot-docs/pull/5653
