### ISSUE TITLE
Improve the Shader Language built-in functions Descriptions

### ISSUE THREAD

**Issue by golddotasksquestions** [godotengine/godot-docs#5594]
**Your Godot version:** 3.4 - 4.0 alpha2

**Issue description:**

The description for these built in functions often are really insufficient and quite frankly bad, because they often just state the function name in capital letter, provide no context, or use only more technical jargon, or even worse explain code with other code, like `b[i] < a[i] ? 0.0 : 1.0`

Those descriptions clearly have been written by someone a long time ago when there was not such a diverse group of people coming to Godot. _By_ someone with a lot of technical expertise _for_ someone else with already a lot of technical expertise. However documentation is not only used for people to learn how to _apply_ API, but also _how to use it_. I therefore I believe the documentation should be phrased as agnostic to the readers background as it can be in order to make it as accessible as possible.

In this particular case it would help to have more worlds actually describing what each function does while trying to avoid using other jargon in the explanation if possible, maybe a tiny example of it's use. Piecing this info together from other sources around the web is extremely frustrating and time consuming and often for beginners learning about shader just not enough due to Godots slightly custom shader language implementation.

**URL to the documentation page (if already existing):**
https://docs.godotengine.org/en/stable/tutorials/shaders/shader_reference/shading_language.html#built-in-functions
https://docs.godotengine.org/en/latest/tutorials/shaders/shader_reference/shading_language.html#built-in-functions
(the div layout also seems broken in the latest docs version)

**Comment by clayjohn** [comment]
Most of these descriptions are copied from the official OpenGL docs put out by Khronos without much editing, so there is certainly room for improvement. 

One of the barriers that contributors face here is the horrible table-formatting used by the docs. To put items in a table you have to use an ASCII table format. So it is very painful to add additional width to columns to fit in more detailed descriptions.

**Comment by Calinou** [comment]
> One of the barriers that contributors face here is the horrible table-formatting used by the docs. To put items in a table you have to use an ASCII table format. So it is very painful to add additional width to columns to fit in more detailed descriptions.

We'll probably have to give up the table format and use formatting similar to https://docs.godotengine.org/en/3.4/tutorials/platform/html5_shell_classref.html.

**Comment by clayjohn** [comment]
> We'll probably have to give up the table format and use formatting similar to https://docs.godotengine.org/en/3.4/tutorials/platform/html5_shell_classref.html. It's probably more readable on narrow displays anyway 🙂

Definitely, that looks much better!

**Comment by clayjohn** [comment]
It shouldn't be too hard to use the formatting of https://docs.godotengine.org/en/3.4/tutorials/platform/html5_shell_classref.html and improve the descriptions. Here is roughly what it would look like:

![Screenshot 2022-02-22 230913](https://user-images.githubusercontent.com/16521339/155274895-b8883ba7-17b7-488f-a053-1919f5552cbd.png)


![Screenshot 2022-02-22 225935](https://user-images.githubusercontent.com/16521339/155273968-d00251ae-8afd-41c9-95a6-5b0b8bdf701c.png)

**Comment by clayjohn** [comment]
> > It shouldn't be too hard to use the formatting of [docs.godotengine.org/en/3.4/tutorials/platform/html5_shell_classref.html](https://docs.godotengine.org/en/3.4/tutorials/platform/html5_shell_classref.html) and improve the descriptions. Here is roughly what it would look like:
> 
> I can look into opening a PR for this (unless someone else started working on it already).

I just did enough to produce the screenshots I posted above. I was planning on updating the descriptions as well, but, if you want to convert the formatting first, I can come in and update the descriptions after. I am happy either way.
