### ISSUE TITLE
Your First 2D Game: HUD Font Data Out-of-Date

### ISSUE THREAD

**Issue by chillen** [godotengine/godot-docs#5615]
**Your Godot version:** 3.4.2

**Issue description:** When adding a Custom Font for the ScoreLabel, the tutorial shows an outdated UI which cannot be followed, and needs to be updated to create a new DynamicFont instead.

**URL to the documentation page:** [https://docs.godotengine.org/en/3.4/getting_started/first_2d_game/06.heads_up_display.html](https://docs.godotengine.org/en/3.4/getting_started/first_2d_game/06.heads_up_display.html)

**Current Tutorial:**
![image](https://user-images.githubusercontent.com/3520361/154283831-421610ef-7d55-422a-977c-959a54199ea1.png)

**Godot 3.4.2 Label Settings:**
![image](https://user-images.githubusercontent.com/3520361/154284031-f0fae1e0-eb02-44d4-852c-a41e37c5c878.png)

**Comment by skyace65** [comment]
@Calinou this issue can be closed.
