### ISSUE TITLE
Help Transitioning from 3 to 4

### ISSUE THREAD

**Issue by Cerno-b** [godotengine/godot-docs#5626]
I am currently testing Godot 4 alpha and it seems to me like certain functions do not exist anymore or have moved to other modules.

Example:
* Godot 3: `OS.get_screen_size`
* Godot 4: `???`

Is there a section in the manual that lists all the changes to that map Godot 3 features to Godot 4?
If not, I think it would be a great idea to get people up to speed without losing too much time when making the jump.

Since there is going to be some confusion due to a lot of Q&A pages in forums or tutorials being geared towards Godot 3, a transition section would be helpful to get older solution to work.

**Comment by pycbouh** [comment]
A migration guide will be available after the API changes are done and it is stable enough to document. The issue is already tracked in https://github.com/godotengine/godot-docs/issues/4960.

**Comment by Cerno-b** [comment]
Thank you and sorry for the duplicate
