### ISSUE TITLE
Update the copyright note in the footer of the docs

### ISSUE THREAD

**Issue by ARez2** [godotengine/godot-docs#5635]
**Your Godot version:**
3.4 stable

**Issue description:**
Scrolling down to the very end of the docs it says "© Copyright 2014-2021, Juan Linietsky, Ariel Manzur and the Godot community (CC-BY 3.0)". This needs to be updated to the year 2022.

**URL to the documentation page:**
https://docs.godotengine.org/en/stable/ 

EDIT: I think i have found the place to change it: in the "conf.py" on line 80. However since i am not home right now i cannot fix it myself.

EDIT #2: i have found a way to do it in the browser. I have now opened a pull request!

**Comment by ARez2** [comment]
EDIT: Is it possible to change the label after opening? Because i cant seem to find the option to do so

**Comment by pycbouh** [comment]
> EDIT: Is it possible to change the label after opening? Because i cant seem to find the option to do so

Labels are assigned by maintainers. And it is fine to classify this as a bug.

**Comment by ARez2** [comment]
Alright!

**Comment by ARez2** [comment]
Closing this as i have found a way to edit the conf.py file online.

**Comment by pycbouh** [comment]
Issues get closed when the PR is merged, so we need to keep this open for now.

**Comment by ARez2** [comment]
Oh sorry, i didn't knew that! Thanks for the heads up.
