### ISSUE TITLE
Inconsistent reference syntax (proposal).

### ISSUE THREAD

**Issue by setanarut** [godotengine/godot-docs#5645]
**Your Godot version:**
3.4.2

**Issue description:**
In-editor reference pages and https://docs.godotengine.org use different syntaxes. docs.godotengine.org pages are formatted according to C++ syntax, not GDscript syntax. In Gdscript syntax, type definitions comes after the variable name(`a: int`). In documents, it comes first.(`int a`) The return value type also does not conform to the Gdscript syntax.

**URL to the documentation page (if already existing):**

https://docs.godotengine.org/en/latest/classes/class_node2d.html
<img width="610" alt="Ekran Resmi 2022-02-25 13 38 52" src="https://user-images.githubusercontent.com/36481442/155701965-21ad6ae3-2fc5-4676-b756-0581004a306a.png">

On pages in the editor (screenshot below) for example, apply_scale should be written as 
 `apply_scale(ratio: Vector2) -> void`.  

<img width="705" alt="Ekran Resmi 2022-02-25 13 39 06" src="https://user-images.githubusercontent.com/36481442/155701885-0702a1bd-6a38-438e-8100-79a8a9cd932a.png">

**Comment by Calinou** [comment]
> The return value type also does not conform to the Gdscript syntax.

I'm not sure if changing this in the built-in class reference makes sense. People have likely gotten used to the current table-style formatting, and aligning names like this can be beneficial to readability.

For changing that part of the editor, I would recommend opening a [discussion](https://github.com/godotengine/godot-proposals/discussions) on the Godot proposals repository (and link to this issue in the discussion).

**Comment by hazarek** [comment]
> People have likely gotten used to the current table-style formatting, and aligning names like this can be beneficial to readability.

I could never get used to this C++ style table view and I am one of those people. I always keep my eye on the right side for the return type because I'm used to the Go language.

<img width="938" alt="Ekran Resmi 2022-02-25 17 36 21" src="https://user-images.githubusercontent.com/36481442/155735721-2a53c6a8-d937-4a20-b189-d3a92244a1ea.png">
