### ISSUE TITLE
Godot Docs Listening Summary Truncated

### ISSUE THREAD

**Issue by NobleValerian** [godotengine/godot-docs#5649]
**Your Godot version:**
3.4 Branch

**Issue description:**
Docs > Step by step > Listening to player input > Summary
Truncated at bottom of web page, despite relevant copy existing in github file.

**URL to the documentation page:**
https://docs.godotengine.org/en/stable/getting_started/step_by_step/scripting_player_input.html#summary

If you know how to fix the issue you are reporting please
consider opening a pull request. We provide a tutorial on
using git here: https://docs.godotengine.org/en/stable/community/contributing/pr_workflow.html,
writing documentation at https://docs.godotengine.org/en/stable/community/contributing/docs_writing_guidelines.html
and contributing to the class reference here: https://docs.godotengine.org/en/stable/community/contributing/updating_the_class_reference.html

**Comment by Calinou** [comment]
Fixed by cherry-picking https://github.com/godotengine/godot-docs/pull/5469 to the `3.4` branch. (This will only apply to the `stable` branch once 3.4.3 is released, which will happen this week.)
