### ISSUE TITLE
I have to say that for those who want to learn the development engine editor, there is no decument

### ISSUE THREAD

**Issue by wslyx** [godotengine/godot-docs#5652]
**Your Godot version:**
3.4.2
**Issue description:**
I have to say that for those who want to learn the development engine editor, the documents can't be read.

I want to understand the principle of Godot engine, but there are no documents to help me learn the system

**Comment by Karmavil** [comment]
If you are using the Godot's version 3.4 I recommend you select the corresponding documentation (3.4 version) in the bottom left corner (or just follow this_link: https://docs.godotengine.org/en/3.4/.
At this moment, the stable version is 3.x and the incoming version is ***latest*** (the link **clayjohn** shared above) but you should either update your godot or use the documentation for the version you are going to use

**Comment by Karmavil** [comment]
Hi it's me again.. I just realized that I am using 3.4.3.stable .. my apologizes. I've got confused because I've been using a custom build 3.5.beta

**Comment by akien-mga** [comment]
> Have you seen the docs on engine development? [docs.godotengine.org/en/latest/development/cpp/index.html](https://docs.godotengine.org/en/latest/development/cpp/index.html)

That's indeed the documentation. See also https://docs.godotengine.org/en/latest/community/contributing/index.html and in general anything under the "Development" and "Contributing" sections.
