### ISSUE TITLE
Bullet points in enumerator description have the same level as the enumerators

### ISSUE THREAD

**Issue by timothyqiu** [godotengine/godot-docs#5658]
**Your Godot version:** 3.4.3 

**Issue description:**

Bullet points in `HandleType`'s enumerator description are at the same level as the enumerators.

**URL to the documentation page:**

https://docs.godotengine.org/en/latest/classes/class_displayserver.html#enum-displayserver-handletype
https://docs.godotengine.org/en/stable/classes/class_os.html#enum-os-handletype

**Comment by Calinou** [comment]
This is an issue with [makerst.py](https://github.com/godotengine/godot/blob/master/doc/tools/make_rst.py) in the main Godot repository.
