### ISSUE TITLE
Visual profiler is undocumented

### ISSUE THREAD

**Issue by EricEzaM** [godotengine/godot-docs#5664]
**Your Godot version:**
All

**Issue description:**
Usage of the visual profiler is not documented - best I could find is this tweet: https://twitter.com/reduzio/status/1175146275546771456

**URL to the documentation page:**
https://docs.godotengine.org/en/latest/tutorials/scripting/debug/the_profiler.html

**Comment by tetrapod00** [comment]
Closing, since this was documented in https://github.com/godotengine/godot-docs/pull/6976.
