### ISSUE TITLE
Highlights make reading difficult.

### ISSUE THREAD

**Issue by hazarek** [godotengine/godot-docs#5665]
**Your Godot version:**
Godot 3 alpha 3

**Issue description:**
Highlights make reading difficult and there is no easy way to turn off highlights when using the search bar. (Except manually deleting the URL). I have to change this address every time.
<img width="341" alt="Ekran Resmi 2022-03-07 20 30 36" src="https://user-images.githubusercontent.com/36481442/157086652-8a31178a-7edd-4fa1-b782-eee5ab61407f.png">

**URL to the documentation page:**
https://docs.godotengine.org/en/latest/classes/class_string.html?highlight=String
<img width="860" alt="Ekran Resmi 2022-03-07 20 15 44" src="https://user-images.githubusercontent.com/36481442/157085440-b05baf86-31db-4e95-81d5-831a1aa29c79.png">

It is very pointless that the search highlighting is still stuck on the redirected page. All browsers already have a search feature. It's ridiculous to impose that.

**Comment by akien-mga** [comment]
I also find these highlights bothersome. We could tweak the CSS to make them less prominent, or see if they can be outright disabled.

I also always need to edit the URL manually whenever I use the search to find a page that I want to link to users on another platform. Overall, I'd be fine if we found a way to fully disable the `?highlight=` part added by the search component.

**Comment by Calinou** [comment]
I haven't found a way to fully disable the `?highlight=` part, but we can remove it from the URL via JavaScript and make the highlight invisible via CSS.

**Comment by ebot102** [comment]
Hey there! I would like to try an tackle this issue. Should these changes be made within the `_static/css/custom.css` and `_static/cs/custom.js` files, or is there a better place to make the changes? Thanks!

**Comment by Calinou** [comment]
> Hey there! I would like to try an tackle this issue. Should these changes be made within the `_static/css/custom.css` and `_static/cs/custom.js` files, or is there a better place to make the changes? Thanks!

You'll proably need to modify both files to ensure that 1) no temporary highlight flash appears, 2) the `&highlight=` part of the URL is removed.

**Comment by ebot102** [comment]
For removing the `?highlight=*` portion of the URL: would it be best to redirect the user to the same page without the highlight tag, or simply try to replace it without needing to reload the page?
