### ISSUE TITLE
[3.4] Duplicated "Submitting to the Asset Library"

### ISSUE THREAD

**Issue by timothyqiu** [godotengine/godot-docs#5667]
**Your Godot version:** 3.4.3

**Issue description:**

There are two "Submitting to the Asset Library" articles in the documentation. They are basically the same except for some wording in the last few paragraphs.

**URL to the documentation page:**

https://docs.godotengine.org/en/stable/community/asset_library/submitting_to_assetlib.html
https://docs.godotengine.org/en/stable/community/asset_library/uploading_to_assetlib.html

**Comment by aaronfranke** [comment]
In master: https://github.com/godotengine/godot-docs/tree/master/community/asset_library

`submitting_to_assetlib` is the one that should be kept. It was renamed in #4260 but it looks like it was accidentally duplicated when the documentation was backported in #5412.

**Comment by akien-mga** [comment]
Fixed by #5668.
