### ISSUE TITLE
Theme regression in toctree after dependencies upgrade

### ISSUE THREAD

**Issue by akien-mga** [godotengine/godot-docs#5676]
**Issue description:**
I updated Sphinx and various dependencies a couple of weeks ago, and since then there's a small visual regression in the toctree: https://github.com/godotengine/godot-docs/pull/5643

Before:
![image](https://user-images.githubusercontent.com/4701338/157880649-609a812f-c2d7-4091-9312-768daf53f130.png)

After:
![image](https://user-images.githubusercontent.com/4701338/157880779-31f7dd38-3b31-410c-96a0-3ae29e8ba7ad.png)

The `+`/`-` icon became bigger, changed color (both might be fine if that's by choice in the upstream theme) and most importantly the 
spacing is off.

On the "After" screenshot you can also see that the expanding "Creating instances" sub-section doesn't have a `-` icon.
Both "Before" and "After" still have the behavior that the `-` icon is hidden for the currently open page unless hovered (which is IMO weird but well).

**URL to the documentation page:**
Compare https://docs.godotengine.org/en/latest with e.g. https://docs.godotengine.org/en/3.3

**Comment by Calinou** [comment]
This is what I get on the online version (`latest`, `3.4` and `stable`). It's different than on the screenshots above:

![image](https://user-images.githubusercontent.com/180032/158240715-afa49707-9bb8-4db8-b0d6-87036077f0e6.png)

![image](https://user-images.githubusercontent.com/180032/158240749-3c57ed5a-b82a-4c81-be58-32c1ff703a79.png)
