### ISSUE TITLE
Documentation for @GDScript seems truncated

### ISSUE THREAD

**Issue by Chaosus** [godotengine/godot-docs#5692]
**Your Godot version:**
Class reference / Latest

**Issue description:**
GDScript functions seems truncated beyond the `str` function.

![image](https://user-images.githubusercontent.com/3036176/158311081-af524f05-e8f7-4566-b6aa-683d69d80d8b.png)

**URL to the documentation page:**
https://docs.godotengine.org/en/latest/classes/class_@gdscript.html

**Comment by raulsntos** [comment]
`@GDScript` used to have a lot more documentation but it was copied to `@GlobalScope` in https://github.com/godotengine/godot/pull/43612 and removed from `@GDScript` in https://github.com/godotengine/godot/pull/44911

But the documentation for `type_exists` was lost in the process.

**Comment by Chaosus** [comment]
Ah, nvm, I confused it with a @GlobalScope indeed.
