### ISSUE TITLE
Download Full documentation HTML not working

### ISSUE THREAD

**Issue by CristianoSimao** [godotengine/godot-docs#5698]
I am trying download all the godot documentation in the link: https://nightly.link/godotengine/godot-docs/workflows/build_offline_docs/master/godot-docs-html-stable.zip

My internet conection is slow but works, in the past (year ago) I have download the full documentation (260 MB approximately) and all works ok.

But now the download stops in 50MB approximately and display "error". I try this 8 times in different days.
**Please, can anyone upload the full documentation in a zip file here in GitHub? Or provide other server link?**

Apparently the conection from "nightly" servers are aborting after some minutes canceling the download.

**Comment by Calinou** [comment]
nightly.link only creates stable download links to GitHub Actions' servers. Right now, the URL is `https://pipelines.actions.githubusercontent.com/Nd46sHc1Nwf8enqeh6djeDfO05yRKeQaTGxF0O8Nup6lDDEaGO/_apis/pipelines/1/runs/4224/signedartifactscontent?artifactName=godot-docs-html-stable&urlExpires=2022-03-18T22%3A53%3A26.4453996Z&urlSigningMethod=HMACV2&urlSignature=xxxxx` (with the URL signature removed).

**Comment by CristianoSimao** [comment]
Thank you very much!
The link https://0x0.st/oNbR.zip worked perfectly.

**Comment by Calinou** [comment]
Closing, as there isn't anything actionable that can be done about the root issue on our end. Using download manager software with the resulting URL *might* work, but only if the link doesn't expire too fast and only if the server supports HTTP range requests.
