### ISSUE TITLE
Very long pages with no TOC

### ISSUE THREAD

**Issue by setanarut** [godotengine/godot-docs#5701]
**Your Godot version:**
Godot 3.4.3 or Godot 4 alpha 4

**Issue description:**
There are very long reference pages with no TOC. I have to use the search bar on the left first and then the browser's search bar to find what I'm looking for. Then It's easy to get lost in the huge pages.

**URL to the documentation page (if already existing):**
https://docs.godotengine.org/en/latest/tutorials/scripting/gdscript/gdscript_basics.html#classes

<img width="802" alt="Ekran Resmi 2022-03-21 22 35 43" src="https://user-images.githubusercontent.com/36481442/159355019-2673d72a-0ef9-4964-b67e-3addbbc85c78.png">

Github's auto-generated table of contents in the RST file. [godotengine.org](https://docs.godotengine.org/en/latest/tutorials/scripting/gdscript/gdscript_basics.html#) doesn't have this TOC.

https://user-images.githubusercontent.com/36481442/159352131-4b275e79-dccf-4740-a02c-b8e9512e3da9.mov

# Enhancement request

1. As an alternative to the slow and cumbersome docs.godotengine.org site. Documents should be adapted to GitHub Flavored Markdown format and put on Github. So anyone who wants can fork and find what they're looking for.
2. or add TOC to the docs.godotengine.org. (My second reluctant choice.)

**Comment by Calinou** [comment]
> As an alternative to the slow and cumbersome docs.godotengine.org site. Documents should be adapted to GitHub Flavored Markdown format and put on Github. So anyone who wants can fork and find what they're looking for.

Godot used to use a GitHub wiki (with Markdown formatting), but it ended up being too limited, especially since note/warning blocks can't be created with just Markdown. There are nonstandard Markdown extensions that make this possible, but GitHub doesn't support rendering those.

**Comment by hazarek** [comment]
> It ended up being too limited, especially since note/warning blocks can't be created with just Markdown.

Note and warning boxes can be easily converted into quote blocks with a script. I even tried it and converted it. only links need to be rendered to relative links.

> **NOTE**: _Lorem ipsum dolor sit amet._

> **WARNING**: _Be realistic, demand the impossible!_

---

> so I guess we need to add a manual table of contents at the top of long pages such as GDScript reference.

It's useless if it's not one of the fixed menus in the corner like this;

https://user-images.githubusercontent.com/36481442/159363665-0e06931b-65b8-445d-b491-9e81bb2bd22b.mov


An real world example (no quotes in this example but can be added); 
https://github.com/vlang/v/blob/master/doc/docs.md

---

> NOTE: _Why do you prefer old-fashioned static site builders like Sphinx? There are faster and more modern technologies._

**Comment by BWPanda** [comment]
Can we re-open this please? This still seems to be an issue (limited levels in sidebar menu, and no TOC for pages (specifically GDScript Reference))...

**Comment by setanarut** [comment]
> Can we re-open this please? This still seems to be an issue (limited levels in sidebar menu, and no TOC for pages (specifically GDScript Reference))...

ok

**Comment by tetrapod00** [comment]
https://github.com/godotengine/godot-docs/pull/9989 brought the [GDScript reference](https://docs.godotengine.org/en/latest/tutorials/scripting/gdscript/gdscript_basics.html) page one level higher in the sidebar, so the page now has one level of header navigation in the sidebar:
![image](https://github.com/user-attachments/assets/f21ad49e-93de-435b-bc48-2cff7f9c8228)

In addtion to that, we can promote some of the existing headers slightly so that they appear in the sidebar navigation.

I'm not opposed to an actual TOC at the top of the page in addition to that, too.

**Comment by dalexeev** [comment]
@setanarut This isn't fixed yet, let's keep it open for now. We either need to add a table of contents/navigation or split the page into multiple pages for this issue to be considered fixed.
