### ISSUE TITLE
Rigidbody damping documentation is wrong

### ISSUE THREAD

**Issue by ilmai** [godotengine/godot-docs#5712]
**Your Godot version:**
3.4.4

**Issue description:**
For linear_damp and angular_damp in RigidBody/RigidBody2D documentation, it claims the value will replace the value from project settings / area. For example, here's what RigidBody documentation says:

_The body's linear damp. Cannot be less than -1.0. If this value is different from -1.0, any linear damp derived from the world or areas will be overridden._

In reality, the value is _additive_ with the value from the project and area, verified by testing and looking at the source code.

**URL to the documentation page:**
https://docs.godotengine.org/en/stable/classes/class_rigidbody.html
https://docs.godotengine.org/en/stable/classes/class_rigidbody2d.html

If you know how to fix the issue you are reporting please
consider opening a pull request. We provide a tutorial on
using git here: https://docs.godotengine.org/en/stable/community/contributing/pr_workflow.html,
writing documentation at https://docs.godotengine.org/en/stable/community/contributing/docs_writing_guidelines.html
and contributing to the class reference here: https://docs.godotengine.org/en/stable/community/contributing/updating_the_class_reference.html

**Comment by Calinou** [comment]
The description in `master` is entirely different: https://github.com/godotengine/godot/blob/391633760b0ea292af079287faf79c1aee6d9254/doc/classes/RigidDynamicBody3D.xml#L181-L182

Maybe this description should be backported to `3.x`?

**Comment by ilmai** [comment]
Yeh I noticed the behavior has changed in 4.x, since they added the damping modes. In those terms, 3.4 documentation claims it works like replace mode, but actually it works like combine mode.

**Comment by akien-mga** [comment]
Fixed by https://github.com/godotengine/godot/pull/61545
