### ISSUE TITLE
"Aces Fitted" is not mentioned in the manual

### ISSUE THREAD

**Issue by Arnklit** [godotengine/godot-docs#5730]
**Your Godot version:**
3.4.4

**Issue description:**
"Aces Fitted" is not mentioned in the manual page with the other tonemapping options.
>**Mode:** Tone mapping mode, which can be Linear, Reindhart, Filmic, or Aces.

Also it might be nice to link to some place that can explain these tonemapping options in more detail.

**URL to the documentation page (if already existing):**
https://docs.godotengine.org/en/stable/tutorials/3d/environment_and_post_processing.html#tonemap

**Comment by Calinou** [comment]
> Also it might be nice to link to some place that can explain these tonemapping options in more detail.

I improved their documentation in https://github.com/godotengine/godot/pull/59411. We could copy-paste what I wrote there.
