### ISSUE TITLE
Optimization are pointing the same articles in 2D and 3D headline

### ISSUE THREAD

**Issue by iulover99** [godotengine/godot-docs#5733]
**Your Godot doc version:**
Stable
**Issue description:**
There are same articles in both 2D and 3D headline, they pointing to the same page, also 2D the "Optimizing 3D performance" article of the 3D
**URL to the documentation page:**
https://docs.godotengine.org/en/stable/tutorials/performance/index.html
![image](https://user-images.githubusercontent.com/41776348/161610370-5552bcf4-17d9-49f5-9100-1f677e3d974e.png)

If you know how to fix the issue you are reporting please
consider opening a pull request. We provide a tutorial on
using git here: https://docs.godotengine.org/en/stable/community/contributing/pr_workflow.html,
writing documentation at https://docs.godotengine.org/en/stable/community/contributing/docs_writing_guidelines.html
and contributing to the class reference here: https://docs.godotengine.org/en/stable/community/contributing/updating_the_class_reference.html

**Comment by skyace65** [comment]
@Calinou you can close this now.
