### ISSUE TITLE
Array export has either changed or is bugged

### ISSUE THREAD

**Issue by GamesOnAcidzz** [godotengine/godot-docs#5751]
**Godot 4 Alpha 6**

**Array export syntax has either changed or is bugged, I have checked the latest docs and it just doesn't work**

**URL to the documentation page:**
![image](https://user-images.githubusercontent.com/103296087/162552515-f9e0222c-c429-4d82-bbb0-add52db4168d.png)

**Comment by Calinou** [comment]
Shouldn't it be `@export var scenes: Array[PackedScene]` now?

**Comment by GamesOnAcidzz** [comment]
yes it, hope they update the documentation

**Comment by Calinou** [comment]
Reopening, as the issue still needs to be fixed in the documentation.
