### ISSUE TITLE
Fix RETURN_VALUE_DISCARDED warning in *Designing the mob scene* in Mob.gd

### ISSUE THREAD

**Issue by ohnoimdead** [godotengine/godot-docs#5753]
**Your Godot version:**

3.4.4.stable.official

**Issue description:**

The return value from ```move_and_slide()``` in ```Your first 3D game » Designing the mob scene``` isn't used which causes a code warning that can be confusing to learners. This is addressed in the actual code example (link below) but not in the documentation.

https://github.com/godotengine/godot-docs/blob/4060179184d1059a16ceb91d0a48c765c62784aa/getting_started/first_3d_game/04.mob_scene.rst#L269-L271

<img width="968" alt="image" src="https://user-images.githubusercontent.com/35269/162611054-2144c574-1f4d-4ba3-ad79-0bdaadd1a618.png">

Where this is addressed in the actual code:

https://github.com/godotengine/godot-3d-dodge-the-creeps/blob/0b7d43cae85580ebdfacdb5ba88f64d3307b9c14/dodge_the_creeps_3d/Mob.gd#L15

Suggestion is to add the ```warning-ignore``` comment to the documentation to bring it inline with the actual example, or to explicitly handle the return value with something like:

```var _disregard = move_and_slide(velocity)```

**URL to the documentation page (if already existing):**

https://docs.godotengine.org/en/stable/getting_started/first_3d_game/04.mob_scene.html

**Comment by Calinou** [comment]
Feel free to open a pull request for this on the `3.4` branch :slightly_smiling_face: 

(The functions have changed in `master`, so that warning isn't relevant there.)

**Comment by ohnoimdead** [comment]
> Feel free to open a pull request for this on the `3.4` branch 🙂

💥

**Comment by skyace65** [comment]
This issue was fixed by #5756. Closing.
