### ISSUE TITLE
Document the new Multiplayer nodes in the class reference

### ISSUE THREAD

**Issue by GamesOnAcidzz** [godotengine/godot-docs#5755]
**Godot 4 Alpha 6**

*Multiplayer (MultiplayerSpawner, MultiplayerSynchronizer) nodes don't have description on their methods and signals**

**Comment by Calinou** [comment]
cc @Faless

**Comment by thiagola92** [comment]
This issue can be closed, right?

https://docs.godotengine.org/en/stable/classes/class_multiplayersynchronizer.html  
https://docs.godotengine.org/en/stable/classes/class_multiplayerspawner.html

**Comment by skyace65** [comment]
Closing this issue since those nodes have been documented.
