### ISSUE TITLE
Invalid code in Tree documentation

### ISSUE THREAD

**Issue by Verthae** [godotengine/godot-docs#5768]
**Your Godot version:**
Godot 3.4.4
**Issue description:**
In looking over how to handle custom popups for a `Tree` node, I came across the documentation for `get_edited()` 
```
func _ready():
    $Tree.item_edited.connect(on_Tree_item_edited)
```
Apparently this has been listed since 3.3, but this is an invalid call for `connect()` and doesn't really help describe how to use this.

This call is styled as if it were 4.0 code:

- calling the signal as if it were a property, much like in 4.0
- calling connect on said Signal
- using `the name of the function` as if it were a 4.0 Callable object

This is adding more difficulties into using this node as there isn't even a proper description on how to build what you see in the in the Theme preview window anywhere.

Much like there is no documentation on being able to use `CELL_MODE_RANGE` on a `TreeItem` to create a popup list via a comma separated `set_text()` value, which I literally just stumbled upon while writing this bug report yet is mentioned nowhere.

**URL to the documentation page:**
https://docs.godotengine.org/en/stable/classes/class_tree.html#class-tree-method-get-edited
https://docs.godotengine.org/en/3.3/classes/class_tree.html#class-tree-method-get-edited

**Comment by Calinou** [comment]
> Apparently this has been listed since 3.3, but this is an invalid call for connect() and doesn't really help describe how to use this.

The syntax is valid for Godot 4.0, but not Godot 3.x. I guess this was cherry-picked without adapting the syntax back to Godot 3.x.

**Comment by akien-mga** [comment]
Fixed by https://github.com/godotengine/godot/pull/60791.
