### ISSUE TITLE
Tween page should mention set_active right below the usage example for multiple tweens

### ISSUE THREAD

**Issue by return2monki** [godotengine/godot-docs#5769]
**Your Godot version:**
3.4.4

**Issue description:**
New to Godot, followed a tutorial (https://www.youtube.com/watch?v=lI8a3R0-_KE) that used the code shown in the docs and pasted it twice then modified it for a transparency fade in/out instead of position change.

This worked right away, however I noticed that when you close the game while being behind the in-game tree as it was transparent it would say: "start: Tween was not added to SceneTree!" it didn't affect gameplay but I wanted to get rid of the error. It took me too long to figure out. All I had to change was turning the last start() into set_active().

Maybe this is obvious but I think it's worth just mentioning set_active for when you're using both body_entered and body_exited, especially as the error you get in the console is kind of misleading/confusing.

**URL to the documentation page (if already existing):**
https://docs.godotengine.org/en/stable/classes/class_tween.html

**Comment by return2monki** [comment]
Going to close since this might not be that relevant anymore with the new scenetreetween.

**Comment by Calinou** [comment]
> Going to close since this might not be that relevant anymore with the new scenetreetween.

Feel free to [open a pull request](https://docs.godotengine.org/en/latest/community/contributing/updating_the_class_reference.html) on the `3.x` branch of the main Godot repository nonetheless :slightly_smiling_face:
