### ISSUE TITLE
Tilemap page is completely broken

### ISSUE THREAD

**Issue by OverseeingDev** [godotengine/godot-docs#5770]
**Your Godot version:**
N/A
**Issue description:**
Page appears completely broken on a 1440p screen with chrome Version 100.0.4896.127. I will report back as I test more devices.
![image](https://user-images.githubusercontent.com/77766651/164313905-59c75427-66b9-4a37-a210-3dc97a95f5dd.png)

**URL to the documentation page:**
[Broken page](https://docs.godotengine.org/en/stable/tutorials/2d/using_tilemaps.html#:~:text=You%20can%20flip%20and%20rotate,menu%20in%20the%20upper%2Dright.)

If you know how to fix the issue you are reporting please
consider opening a pull request. We provide a tutorial on
using git here: https://docs.godotengine.org/en/stable/community/contributing/pr_workflow.html,
writing documentation at https://docs.godotengine.org/en/stable/community/contributing/docs_writing_guidelines.html
and contributing to the class reference here: https://docs.godotengine.org/en/stable/community/contributing/updating_the_class_reference.html

**Comment by OverseeingDev** [comment]
Changing versions using the bottom version selection and then coming back seems to have fixed the issue. Cannot reproduce anymore. I will close this issue for now.

**Comment by Calinou** [comment]
This issue is likely a duplicate of https://github.com/godotengine/godot-docs/issues/4790, since the URL you linked contains a text fragment.

**Comment by OverseeingDev** [comment]
Indeed that seems to be the issue
