### ISSUE TITLE
Document WeakRef (maybe create a short tutorial)

### ISSUE THREAD

**Issue by mhilbrunner** [godotengine/godot-docs#580]
See https://github.com/godotengine/godot/issues/4306.

**Comment by StraToN** [comment]
Indeed, I wasn't even aware of this feature. I suppose this is specific to GDScript, should this go in this category?

**Comment by Keplar1995** [comment]
This is not an issue at all @mhilbrunner, voting to close it.

**Comment by mhilbrunner** [comment]
Would probably make sense there, yes :)
