### ISSUE TITLE
PoolVector3Array is missing from Mono

### ISSUE THREAD

**Issue by AntonioNoack** [godotengine/godot-docs#5806]
**Your Godot version:**
v3.4.4.stable.mono.offical[419e713a2]

**Issue description:**
I was looking at extracting triangle/vertex information from meshes, and while looking trough the docs, I found ArrayMesh.GetFaces() which returns a PoolVector3Array (https://docs.godotengine.org/en/stable/classes/class_poolvector3array.html). However, when I wanted to use that class in C#, it doesn't exist. Instead, there Vector3[] is used.

I recommend, that a small section is added to the docs that tells you that.
E.g. `The class PoolVector3Array does not exist in the C# Mono environment. Vector3 arrays are used instead.`

**URL to the documentation page (if already existing):**
https://docs.godotengine.org/en/stable/classes/class_poolvector3array.html

**Comment by Calinou** [comment]
Isn't that the case for all Pool*Array types (and Packed*Array in `master`)?

**Comment by AntonioNoack** [comment]
Probably. I only noticed it because of my experiment. I haven't done a lot with Godot yet.

**Comment by kleonc** [comment]
> I recommend, that a small section is added to the docs that tells you that.
> E.g. `The class PoolVector3Array does not exist in the C# Mono environment. Vector3 arrays are used instead.`

I think it's already mentioned:  [3.4 docs](https://docs.godotengine.org/en/3.4/tutorials/scripting/c_sharp/c_sharp_differences.html#array) ([source](https://github.com/godotengine/godot-docs/blob/3.4/tutorials/scripting/c_sharp/c_sharp_differences.rst#array)) (it seems unchanged in the newer versions).

Is it not enough? If not, any improvement suggestions?

**Comment by AntonioNoack** [comment]
@kleonc well I found awkward to be missing. I think it would be good to add, as long as there is no dedicated C# Docs. I might not be the only developer who wonders about it. Knowing the return type of a function is important, so you know how to further process the data for your needs.

**Comment by kleonc** [comment]
>I think it would be good to add, as long as there is no dedicated C# Docs.

C# class reference is documented within the assemblies. But yeah, there's no official on-line/in-editor class reference for C# (however [here's example of unofficial one](https://paulloz.github.io/godot-csharp-api/index.html)). 

And to be clear: do you suggest to add a note about C# to the GDScript's class reference? For example something like:
```
Note: In C# there's no PoolVector3Array class, Vector3[] is used instead.
```

in [here](https://docs.godotengine.org/en/3.4/classes/class_poolvector3array.html#description)?

---

>Knowing the return type of a function is important, so you know how to further process the data for your needs.

Again, it's documented within the assemblies. You can check the return type within your IDE (at least you should be able to do so):

![Code_u5kEP1OIPa](https://user-images.githubusercontent.com/9283098/167702023-106706b3-1337-45cd-97dc-12de38cd1575.png)
![Code_HO28jwjnq3](https://user-images.githubusercontent.com/9283098/167702027-6b3a0498-126b-46f4-9739-2fdf212f6ec7.png)
![Code_pixotc2m8o](https://user-images.githubusercontent.com/9283098/167702030-718e941b-3bf9-4c24-bb9a-22d6401660ca.png)
![rLD9KRneSn](https://user-images.githubusercontent.com/9283098/167705772-480c6418-1448-4373-8a58-35ca66b7179a.png)
![Code_75kmeWA4he](https://user-images.githubusercontent.com/9283098/167705777-52400ad7-e7fb-48a0-a6aa-1baa397b1cba.png)

**Comment by AntonioNoack** [comment]
"in [here](https://docs.godotengine.org/en/3.4/classes/class_poolvector3array.html#description)?" yes.

Good to know there is unofficial C# Docs :)

and yeah, I just used Godot with VSCode (because it feels better than the built-in editor), but didn't setup the project fully, because I wasn't aware you could do that properly. That way I didn't have Godot assemblies, which showed me anything.

Plus when going after the tutorial on https://gist.github.com/paulloz/30ae499c1fc580a2f3ab9ecebe80d9ba to do that, the menus aren't showing up, but that probably should be another bug report 😄.
![Screenshot (1041)](https://user-images.githubusercontent.com/20659579/167777397-2d3ce696-4527-42a1-a2b0-046b53196e61.png)

**Comment by AntonioNoack** [comment]
I created a bug report for that :)
https://github.com/godotengine/godot/issues/60940

**Comment by raulsntos** [comment]
This is already documented in the [_C# API differences to GDScript_](https://docs.godotengine.org/en/3.4/tutorials/scripting/c_sharp/c_sharp_differences.html#array) page.

It may still be worth it to add a mention to this in the `Pool*Array` classref (somewhat related discussion in https://github.com/godotengine/godot/pull/70852).
