### ISSUE TITLE
Following url from in-editor docs gives "You are not reading the most recent version of this documentation. 3.5 is the latest version available."

### ISSUE THREAD

**Issue by AaronRecord** [godotengine/godot-docs#5812]
**Your Godot version:**
3.4.4
**Issue description:**
3.5 is still in beta as of the time writing this, so either this warning:
![image](https://user-images.githubusercontent.com/50304111/167518201-aa7071bb-bce2-411b-a39d-3e72dde86666.png)
should not show up, or the tutorial links:
![image](https://user-images.githubusercontent.com/50304111/167518243-64a4293b-6474-4084-95f3-eef7fdaaac3c.png)

should refer to the latest documentation if that is preferred.
**URL to the documentation page (if already existing):**
(or any other)
https://docs.godotengine.org/en/3.4/tutorials/networking/http_request_class.html

**Comment by akien-mga** [comment]
This feature is too difficult to get right, anytime we create a new development branch for an upcoming release it infers it as the latest stable (they expect us to use semver and thus use a pre-release branch name but that means yet another duplicate documentation instance and it's bad to SEO to rename that branch when it's finally released).

So I disabled it (will need a rebuild of all branches, it's static).
