### ISSUE TITLE
Any tutorial or docs for GDNative ?

### ISSUE THREAD

**Issue by Chaosus** [godotengine/godot-docs#582]
I didnt find section on http://docs.godotengine.org/en/latest/learning/scripting/index.html 
Is it planned to future ?

**Comment by akien-mga** [comment]
Yes, when @karroffel or other GDNative wizards get to it.

**Comment by mhilbrunner** [comment]
Closed by #https://github.com/godotengine/godot-docs/pull/832.

Also see:
- https://godotengine.org/article/look-gdnative-architecture
- https://godotengine.org/article/dlscript-here
