### ISSUE TITLE
Isn't the web description of angle_to_point wrong?

### ISSUE THREAD

**Issue by ltsdw** [godotengine/godot-docs#5822]
**Your Godot version:** 3.4.4.stable

**Issue description:**

it says that a.angle_to_point(b) is equivalent to (b-a).angle()

![Screenshot-16-05-2022_16-18-51](https://user-images.githubusercontent.com/44977415/168667427-d2602eab-e40d-4271-b565-aa980dde78ab.png)

shouldn't it be that it's equivalent to (a-b).angle()?

```gdscript
    var A: Vector2 = Vector2(14, 12)
    var B: Vector2 = Vector2(10, 6)

    print((B-A).angle()) # -2.158799
    print((A-B).angle()) # 0.982794
    print(A.angle_to_point(B)) # 0.982794
```

**URL to the documentation page (if already existing):** [class-vector2-method-angle-to-point](https://docs.godotengine.org/en/latest/classes/class_vector2.html?highlight=angle_to_point#class-vector2-method-angle-to-point)

**Comment by Calinou** [comment]
See https://github.com/godotengine/godot/issues/60453.

**Comment by ltsdw** [comment]
Oh, I could swear I searched for angle_to_point on the issues before posting this one.

thank you. closing.
