### ISSUE TITLE
Update the "First Look at Godot's editor" project manager section to match headings within Godot v3.4

### ISSUE THREAD

**Issue by nickjfrench** [godotengine/godot-docs#5839]
**Your Godot version: **3.4.4

**Issue description:** Update the First Look at Godot's Editor page to change things like Project Manager tabs/buttons to match what is present in 3.4.4. This includes things like the Template tab being renamed as the Asset Library.

**URL to the documentation page (if already existing):** getting_started/introduction/first_look_at_the_editor.rst

**Comment by Calinou** [comment]
The screenshots also need to be updated.

**Comment by akien-mga** [comment]
Fixed by #5849.
