### ISSUE TITLE
Customize the main document scroll bar for easier readability

### ISSUE THREAD

**Issue by lesleyrs** [godotengine/godot-docs#5850]
**Your Godot version:**
Any
**Issue description:**
The default scroll bar can be hard to see as it doesn't stand out that much
**URL to the documentation page (if already existing):**
Any

The rust book has a scroll bar that stands out really well making it way less effort to see where you are on the page.

Would like to see something similar for Godot docs if it's possible.

**Comment by YuriSizov** [comment]
Which scrollbar is that? Can you show a screenshot? Note that browsers don't support customization of scrollbars equally, and implementing a completely custom scrollbar with some HTML and JS trickery is not a good option for so little gain.

**Comment by return2monki** [comment]
https://doc.rust-lang.org/stable/rust-by-example/

https://i.imgur.com/JM3ZpLr.png

The color changes based on which theme you choose

**Comment by Calinou** [comment]
The table of contents' scroll bar is already customized, but the main document scrollbar isn't.
