### ISSUE TITLE
Clarify that 'set_drag_preview' method of Control makes the preview the child of the called Control

### ISSUE THREAD

**Issue by linky00** [godotengine/godot-docs#5858]
**Your Godot version:**
v3.4

**Issue description:**
The `set_drag_preview` method on the Control documentation should probably explicitly say that the preview you hand it will become the child of the control that is being called. The phrase 'The control must not be in the scene tree' misled me to believe that the control is never in the scene tree; perhaps it's obvious to most people, but clarification would be nice!

**URL to the documentation page (if already existing):**
https://docs.godotengine.org/en/stable/classes/class_control.html#class-control-method-set-drag-preview

**Comment by YuriSizov** [comment]
This is incorrect, the preview is not added directly to the control that originates it. It gets added to the topmost ancestor control of that node.
