### ISSUE TITLE
TreeItem.get_children() description incorrect

### ISSUE THREAD

**Issue by NationalityNZ** [godotengine/godot-docs#5871]
**Your Godot version:**
Alpha 9

**Issue description:**

The documentation states this for get_children():
"Returns the TreeItem's first child item or a null object if there is none."

However, get_children() actually returns an array with all children, returning an empty array if there are none.

**URL to the documentation page:**
https://docs.godotengine.org/en/stable/classes/class_treeitem.html?highlight=TreeItem

**Comment by YuriSizov** [comment]
You're looking at the stable docs, but your Godot version is [I assume Godot 4] alpha 9. This method description is correct for the stable version of Godot 3.x.

Godot 4 description is also correct in the latest docs: https://docs.godotengine.org/en/latest/classes/class_treeitem.html?highlight=TreeItem#class-treeitem-method-get-children

**Comment by NationalityNZ** [comment]
Sorry, you are correct. I thought I was looking at the latest docs.
