### ISSUE TITLE
Add Documentation section that exposes Engine Architecture

### ISSUE THREAD

**Issue by KiwwiPity** [godotengine/godot-docs#5877]
**version:** 3.4.3

**Issue description:** There's no documentation about how the engine works.

Some map (using diagrams) of the engine layout/architecture; rendering pipeline, engine-server co-relation, etc.
Also how the type-system relates to, and essential stuff that anyone should know (there's info out there, but it looks spread and hidden).

Just in case, there exists already something like that?

**Comment by Calinou** [comment]
This documentation already exists: https://docs.godotengine.org/en/latest/development/cpp/index.html

Please be more specific if you need documentation on a subject that isn't already covered.

**Comment by skyace65** [comment]
Closing per Calinou's comment and the lack of a response.
