### ISSUE TITLE
Anchor docs are outdated. 

### ISSUE THREAD

**Issue by capnm** [godotengine/godot-docs#588]
http://docs.godotengine.org/en/latest/learning/step_by_step/ui_introduction_to_the_ui_system.html?highlight=anchor#place-ui-elements-precisely-with-anchors

The inspector ui changed to (godot tip):

![gd-anchor](https://user-images.githubusercontent.com/4047289/32770945-8c9cdfaa-c921-11e7-84c9-d5c99907aced.png)

**Comment by NathanLovato** [comment]
We're aware of it. I don't have time to rewrite the UI pages atm, it'll have to wait some more unless someone else rewrite it.

**Comment by mhilbrunner** [comment]
Closed in #918
