### ISSUE TITLE
Script templates page is outdated

### ISSUE THREAD

**Issue by KoBeWi** [godotengine/godot-docs#5887]
**Your Godot version:**
4.0 Alpha 10

**Issue description:**
The script templates page wasn't updated after https://github.com/godotengine/godot/pull/53957
The templates are now per node type and folder organization has changed.

Some related issue: https://github.com/godotengine/godot/issues/61614

**URL to the documentation page:**
https://docs.godotengine.org/en/latest/tutorials/scripting/creating_script_templates.html

**Comment by jynus** [comment]
Let me know what do you think of this first draft- some behaviours I wasn't fully sure if intended, like what the editor does when more than one script is set as default for the same node- I documented the current status of the latest alpha, but I am open to corrections and opening issues if necessary.
