### ISSUE TITLE
Change heightmap tutorial to use new PlaneMesh resource

### ISSUE THREAD

**Issue by BastiaanOlij** [godotengine/godot-docs#591]
Might tackle this myself when I have a minute but just in case the original author wants to pick it up.

In Godot 3.0 you don't need to use blender to create the plane object. Instead you can use the new PlaneMesh resource.

Obviously once @Zylann terrain engine is finished this whole tutorial becomes obsolete :)

**Comment by brainsick** [comment]
I'm interested in pursuing this update for 3.0.  Currently stuck on two issues.

The first shader is a fragment shader attached to MeshInstance / Geometry / Material Override.

```
shader_type spatial;

uniform sampler2D heightmap;
uniform vec4 color : hint_color;

// http://docs.godotengine.org/en/latest/community/tutorials/3d/mesh_generation_with_heightmap_and_shaders.html?highlight=heightmap#shader-magic
// http://docs.godotengine.org/en/latest/learning/features/shading/shading_language.html#fragment-built-ins
void fragment() {
	// no DIFFUSE, best guess ...
	ALBEDO = color.rgb * texture(heightmap, UV).rgb;
}
```

Issue 1: I'm not certain what to port DIFFUSE to.  The above code results in a blue tint on the object that I don't understand.

The second shader is a vertex shader.  When I add the following function to the existing shader, the mesh does raise a little, but it's not taking the heightmap into account.

```
shader_type spatial;

uniform sampler2D heightmap;
uniform vec4 color : hint_color;

// http://docs.godotengine.org/en/latest/community/tutorials/3d/mesh_generation_with_heightmap_and_shaders.html?highlight=heightmap#shader-magic
// http://docs.godotengine.org/en/latest/learning/features/shading/shading_language.html#fragment-built-ins
void fragment() {
	// no DIFFUSE, best guess ...
	ALBEDO = color.rgb * texture(heightmap, UV).rgb;
}

void vertex() {
	float height_range = 0.2;
	
	vec2 xz = VERTEX.xz;
	float h = texture(heightmap, UV).g * height_range;
	VERTEX = vec3(xz.x, h, xz.y);
}
```

Issue 2: I'm guessing that I'm using VERTEX wrong?  I didn't see a SRC_VERTEX analog and the [docs](http://docs.godotengine.org/en/latest/learning/features/shading/shading_language.html#vertex-built-ins) don't indicate whether the vertex built-ins are in, out, or inout.

I feel like I'm close, but not quite getting it.

[PlaneHeightmapVertexShader30.zip](https://github.com/godotengine/godot-docs/files/1620991/PlaneHeightmapVertexShader30.zip)

**Comment by antoniotorresm** [comment]
I updated this guide to 3.0 (PR #1007). I left the Blender part because that's how it was in the prior version, although it is mentioned that it can be done with Godot planes. Do you think it would be better if we removed the Blender part and just created a Godot plane?

**Comment by Wildcarde** [comment]
I'd vote for the moving to the plane mesh, it might help add to the documentation overall since there's no clear examples for using a planemesh (or any primitive mesh types) currently.

**Comment by clayjohn** [comment]
This issue should be closed via PR #1540. 

The mesh generation tutorial has been replaced by a new tutorial named: 'vertex displacement with shaders'. It uses Godot's built in PlaneMesh instead of a plane in Blender and it uses shaders instead of a heightmap.

**Comment by skyace65** [comment]
This issue was fixed a year ago and can be closed.

**Comment by Calinou** [comment]
Closing per @skyace65's comment.
