### ISSUE TITLE
Step by step: Using signals says it will add main scene

### ISSUE THREAD

**Issue by hcs64** [godotengine/godot-docs#5919]
**Your Godot version:** 3.4.4

**Issue description:** The guide says we'll be adding a new main scene, but the newly created scene with the Button is never made the main scene. The instructions do say to play the current scene with F6, not the whole project with F5, but it's easy to miss. Seems to be present on both stable and master branches, though "main" is only quoted in stable.

**URL to the documentation page:** https://docs.godotengine.org/en/stable/getting_started/step_by_step/signals.html

 (Apologies if this is spurious, this is my first day using Godot)

**Comment by cbscribe** [comment]
I think the wording here is fine - we're making a "main" scene not a project main scene. Maybe this should just be worded that we're making a new "container" scene. 

The point here is to make a scene that contains both the Button and the Sprite. It really doesn't matter if it's set as the project main scene, that has no bearing on the tutorial.

**Comment by cristiadu** [comment]
> 

The problem is more that, if you don't run from the scene, the project will complain about the Timer component not being there for the script to reference it, as the project main scene is set as the Sprite scene per previous doc when we created it.

It's not a big deal, more of a silly miss that I also had and was very confused on why the tutorial was working. Maybe a "PS" to avoid having that in the future?

**Comment by cristiadu** [comment]
> I think the wording here is fine - we're making a "main" scene not a project main scene. Maybe this should just be worded that we're making a new "container" scene.
> 
> The point here is to make a scene that contains both the Button and the Sprite. It really doesn't matter if it's set as the project main scene, that has no bearing on the tutorial.

The problem with the docs is more that, if you don't run from the scene, the project will complain about the Timer component not being there for the script to reference it, as the project main scene is set as the Sprite scene per previous doc when we created it.

It's not a big deal, more of a silly miss that I also had and was very confused on why the tutorial was working. Maybe a "PS" to avoid having that in the future?
