### ISSUE TITLE
Define standard referencing/formatting behavior for class and property names in classref and manual pages

### ISSUE THREAD

**Issue by snailrhymer** [godotengine/godot-docs#5932]
**Your Godot version:** Latest

**Issue description:**

In the class refs, class/method/property names are always linked as a reference.

It would be good to make this convention clear, say by adding a line to [contributing to the class refs/](https://docs.godotengine.org/en/latest/community/contributing/class_reference_writing_guidelines.html#improve-formatting-with-bbcode-style-tags) that the relevant tags should always be used for class/method/property names.

***

For manual pages, there doesn't seem to be an established convention. It is unclear:

1. When a class name should contain a link to the class ref (never/once per page/once per section/always?)
2. How property names should be formatted (I've seen no formatting, **bold**, and `code` in use).
3. _What_ property name to use (consider e.g. `albedo_texture` in a `StandardMaterial3D`, which appears as "Texture" under the heading "Albedo").
4. How inspector subsection names should be formatted (e.g. how should a tutorial instruct users to find `material_override` on a `MeshInstance3D`? It's under the "Geometry" subheading, under "GeometryInstance3D").

***

Consistency will make the docs feel more cohesive, and allow users to gain familiarity with how the docs relate to the editor/engine.

Establishing this convention clearly will also help contributors, particularly new ones - currently I have to scan through the manual until I can find a representation of the behavior I need (e.g. how property names are formatted). Having all this information in one place (as a new section in [docs_writing_guidelines](https://docs.godotengine.org/en/latest/community/contributing/docs_writing_guidelines.html), say) would reduce the need for this.

**Comment by YuriSizov** [comment]
Is this report complete? If so, I don't understand what the problem is.

**Comment by snailrhymer** [comment]
No, sorry - I mispressed enter while editing the title. I'm currently writing the body of it.
