### ISSUE TITLE
Doc page tips for older versions sometime mention previous as stable and sometimes current as stable

### ISSUE THREAD

**Issue by Anutrix** [godotengine/godot-docs#5935]
**Your Godot version:**
3.2, 3.3, 3.4, 3.5, stable

**Issue description:**
3.1 page tip calls 3.0 and 2.1 stable.
3.2 page tip calls 3.1 ***previous*** stable.
3.3 page tip calls 3.2 ***previous*** stable.
3.4 page tip calls 3.3 ***current*** stable.
3.5 page tip calls 3.4 ***current*** stable.
stable page tip calls ***3.3(?)*** current stable.

This tip:
![image](https://user-images.githubusercontent.com/11459028/179208889-1b94f485-6d8b-4ad5-af81-e0e2c2405385.png)

**URL to the documentation page:**
https://docs.godotengine.org/en/3.1
https://docs.godotengine.org/en/3.2
https://docs.godotengine.org/en/3.3
https://docs.godotengine.org/en/3.4
https://docs.godotengine.org/en/3.5
https://docs.godotengine.org/en/stable

**Comment by akien-mga** [comment]
I fixed most of those a wild ago, but I'll do another pass on the old docs.

**Comment by akien-mga** [comment]
Should be fixed with https://github.com/godotengine/godot-docs/commit/7a86ac6a3067e3265ff148fb0889f2a59662807b (`3.4`) and a similar commit for all previous branches. (Currently still building, and it's not impossible that some of the older branches like `2.1` won't build nowadays... we'll see.)
