### ISSUE TITLE
Documentation missing method keyword in C#

### ISSUE THREAD

**Issue by jihadkhawaja** [godotengine/godot-docs#5942]
**Your Godot version:**
Godot mono stable 3.4.4

**Issue description:**
The documentation missing the ".Instance()" instead of "scene.()" after scene. even though it exist in the .rst repository file for the C# tab only.
![image](https://user-images.githubusercontent.com/47315122/179424520-bf49d508-e1ac-4689-9e30-9c47b49cfb9a.png)
![image](https://user-images.githubusercontent.com/47315122/179424504-d3681165-0ac6-47a3-9115-f44885be8a4f.png)

**URL to the documentation page:**
https://docs.godotengine.org/en/stable/tutorials/scripting/nodes_and_scene_instances.html

**Comment by YuriSizov** [comment]
> even though it exist in the .rst repository file for the C# tab only.

Your screenshot of the repository is from the `master` branch, but the link to the docs that you've shared is from `stable`. It is indeed missing in `stable` branch, and relevant 3.x branches:
https://github.com/godotengine/godot-docs/blob/stable/tutorials/scripting/nodes_and_scene_instances.rst
