### ISSUE TITLE
C# documentation (probably) instructs installing wrong version of .NET SDK

### ISSUE THREAD

**Issue by miv391** [godotengine/godot-docs#5944]
v3.4.4.stable.mono.official [419e713a2], Windows 10

This page https://docs.godotengine.org/en/stable/tutorials/scripting/c_sharp/c_sharp_basics.html#prerequisites says that "Install the latest stable version of .NET Core SDK (3.1 as of writing)." So I installed the version 3.1 and it somewhat works. Building and running the game works, but as I use VS Code as an editor, C# features do not work at all, no code completion, no code formatting. Finally I uninstalled .NET Core 3.1 and installed .NET 6 and now C# features work.

I suggest that the text 

> Install the latest stable version of .NET Core SDK (3.1 as of writing).

is be changed to 

> Install the latest LTS version of .NET Core SDK.

Explicitly saying what version should be installed is bad if the version number is not actively updated. Also, Microsoft doesn't use term "stable" on their page, they use terms "LTS" and "preview".

I didn't make a PR for this as I am not 100% sure that installing .NET 6 is really the correct SDK to install.

**Comment by YuriSizov** [comment]
.NET Core and .NET 6 are not the same thing. .NET Core is the older tech that was separate from the main .NET framework as a light-weight, cross-platform solution. Now it is united again, but Godot [doesn't support .NET 6 solutions](https://github.com/godotengine/godot-proposals/issues/2333) yet. Instead, for cross-platform support we rely on Mono.

So indeed, you need to have .NET Core 3.1 installed for Godot. The fact that your VS Code plugin doesn't work can mean that it doesn't support .NET Core 3.1 or you need to configure it somehow. This also means you are limited by which language features you can use in C#. The docs are correct in that regard.

> Explicitly saying what version should be installed is bad if the version number is not actively updated.

An explicitly stated version is there to indicate the one that has been tested and is guaranteed to work. With an open-bracket definition like "use the latest stable" version there is no indication which versions were actually evaluated, and new major releases can very easily turn incompatible. Thankfully, .NET 3.1 is the latest support version for .NET Core branding, so there shouldn't be any confusion.

> Microsoft doesn't use term "stable" on their page, they use terms "LTS" and "preview".

LTS means "long term support". Not every stable release is an LTS release. It's an extra marker. And obviously "preview" is not a stable version either. "Stable" here is the correct term, and it is generally accepted in tech world for any product that is released and versioned.

PS. @neikeq Can you confirm everything I've said?

**Comment by nobuyukinyuu** [comment]
As of about a month ago, code completion on vscode's c# plugin specifically requires the dotnet 6 sdk to be installed in order to work.  This is not a godot issue, but an issue with the plugin.  If you check the description of the plug-in, it will point this out because it's not always obvious that this is the problem, especially when migrating from an earlier version.  This is also reflected in the OmniSharp console logs.

**Comment by YuriSizov** [comment]
Thanks for confirming, @nobuyukinyuu
