### ISSUE TITLE
Blend shapes are supported in GLES2

### ISSUE THREAD

**Issue by MJacred** [godotengine/godot-docs#5954]
**Issue description:**

Blend shapes are supported in GLES 2: https://github.com/godotengine/godot/pull/48480, https://github.com/godotengine/godot/pull/51363

**URL to the documentation page:**

[Blend shapes are not supported in GLES2](https://docs.godotengine.org/en/latest/tutorials/rendering/gles2_gles3_differences.html#blend-shapes)

Can make a PR later this week to update docs. Need to check merged PRs, if there are more PRs than the ones above (found both by accident).

**Comment by clayjohn** [comment]
Great catch!

The text can be updated with something like "In GLES2 Blend Shapes are implemented on the CPU. Accordingly, they may not perform as well as Blend Shapes in GLES3. When using Blend Shapes in GLES2, limit the number of Blend Shape that are updated each frame."
