### ISSUE TITLE
Dynamic character controller

### ISSUE THREAD

**Issue by kubecz3k** [godotengine/godot-docs#596]
I was unable to find any info in our docs on how to use dynamic character control. I think we should have at least couple of sentences on how to use them.

**Comment by Keplar1995** [comment]
Not a big problem or issue at all, voting to close this.

**Comment by pwab** [comment]
I stumbled upon this issue and it confuses me a lot. I never heard about a  "_dynamic character controller_" before but the term is in the [docs](http://docs.godotengine.org/en/latest/learning/features/physics/kinematic_character_2d.html?highlight=dynamic%20character%20controller) and embedded in a [demo project](https://github.com/godotengine/godot-demo-projects/blob/f61c760e629c81f570ec9be2eedd3f36c902ca12/2d/physics_platformer/project.godot#L13). I searched the godots codebase but couldn't find any reference apart from an old [commit title](https://github.com/godotengine/godot/commit/32b1b472af379b3ea3b155a38158f08aed1e92e1). Was there something renamed or removed?

**Comment by NathanLovato** [comment]
Godot seems to use some physics terms. I think we could remove the parts about "dynamic controllers" as they don't contribute to understanding how godot's physics nodes work.

For the difference, from the user's perspective it probably doesn't matter:

```
*Dynamics* is the branch of applied mathematics (specifically classical mechanics) concerned with the study of forces and torques and their effect on motion, as opposed to *kinematics*, which studies the motion of objects without reference to its causes.
```

**Comment by NathanLovato** [comment]
Dynamics and kinematics are two approaches to body mechanics. From wikipedia:

> Dynamics is the branch of applied mathematics (specifically classical mechanics) concerned with the study of forces and torques and their effect on motion, as opposed to kinematics, which studies the motion of objects without reference to its causes.

@kubecz3k I'd assume it's just the RigidBody node with the option to rotate off.

**Comment by NathanLovato** [comment]
But this page is bound for a rewrite anyway - @cbscribe was working on kinematic vs rigid bodies

**Comment by akien-mga** [comment]
Basically it's just as @NathanLovato put it from Wikipedia:
- Dynamic character controller == _integrate_forces == https://github.com/godotengine/godot-demo-projects/blob/master/2d/physics_platformer/player.gd
- Kinematic character controller == _physics_process == https://github.com/godotengine/godot-demo-projects/blob/master/2d/platformer/player.gd

**Comment by pwab** [comment]
Thanks for the clarification but I am not sure how this should be handled in the docs.
If this is just a _RigidBody node with the option to rotate off_ then the term could be mentioned in the RigidBody API documentation but why dealing with it any further?

**Comment by NathanLovato** [comment]
@pwab people coming from other engines, people who studied some areas of computer science etc. will likely know the word and understand the difference - making it easier for them to pick the right node for their needs. The page already explains what this is: `A dynamic character controller uses a rigid body [...]`

**Comment by pwab** [comment]
> To me the page is clear enough as it is [...]

I totally agree! This issue exists because @kubecz3k suggested to improve the documentation concerning this term and I only wanted to know what needs to be added.

I do not intend to change anything of this specific paragraph - I just wanted to help closing this issue :sweat_smile:

**Comment by Calinou** [comment]
The current page seems clear enough to me (and other people in this discussion), so I'll close this.
