### ISSUE TITLE
Docs content can be moved left/right, making the navigation on the left obscure the content.

### ISSUE THREAD

**Issue by OrakMoya** [godotengine/godot-docs#5971]
**Your Godot version:** This is just a bug on the website as a whole

**Issue description:** When using a plugin that allows scrolling with the middle mouse button on firefox (eg. "Middle Mouse Button Scroll"), the docs content can be moved left/right. This makes the navigation on the left obscure the content. [See here.](https://i.imgur.com/eh83dlP.png)

**Comment by tetrapod00** [comment]
I can reproduce this (in Firefox with ScrollAnywhere) in 3.5 and 4.1, but not in 3.6, 4.2, 4.3, stable, or latest. At some point I guess one of the theme changes fixed this.

As such I'm closing this as resolved.
