### ISSUE TITLE
Plane, some parameters name are inconsistent

### ISSUE THREAD

**Issue by sent44** [godotengine/godot-docs#5976]
**Your Godot version:**
4 alpha 12

**Issue description:**
Variant intersects_segment(`from`: Vector3, to: Vector3)
Returns the intersection point of a segment from position `begin` to position end with this plane. If no intersection is found, null is returned.
-- I didn't create PR because I don't know which one do you use, `from` or `begin`

and

bool is_point_over(`plane`: Vector3)
Returns true if `point` is located above the `plane`.
-- Is parameter name is `point`? Or `plane` is correct and then what is this `plane` mean?

**URL to the documentation page:**
https://docs.godotengine.org/en/latest/classes/class_plane.html#class-plane

**Comment by jynus** [comment]
I think my patch should fix this discrepancy- although it won't be show automatically if/when merged.
