### ISSUE TITLE
[Shaders] theres no documentation on migrating from 3.x to 4.x

### ISSUE THREAD

**Issue by nonunknown** [godotengine/godot-docs#5979]
**Your Godot version:**
4 alpha 12

**Issue description:**

There's a lot of keywords changes in shaders for 4.x, one example is `source_color` which in 3.x was called `hint_color` so having docs stating the old keywords and new keywords in a table would be awesome!!!!

**Comment by Calinou** [comment]
Duplicate of https://github.com/godotengine/godot-docs/issues/4960.
