### ISSUE TITLE
Include C# examples for Step by Step Tutorial

### ISSUE THREAD

**Issue by a2937** [godotengine/godot-docs#5989]
**Your Godot version:**
v3.4.4-stable_mono_win64

**Issue description:**
I'd like to add tabs featuring C# source code to the already existing documentation if possible. 
It would encourage those wanting to try the Mono API an opportunity to do it without having to run around scatter-brained trying to figure out all the differences. I would be more than happy to add the examples as I'm learning this new engine. 

**URL to the documentation page (if already existing):**
https://docs.godotengine.org/en/stable/getting_started/step_by_step/scripting_first_script.html

**Comment by Calinou** [comment]
Feel free to open a pull request for this :slightly_smiling_face: 

Please open a PR against the version in `master`, rather than the one in `stable`.

**Comment by a2937** [comment]
I have started a PR. I believe this is what you are after. #5991
