### ISSUE TITLE
» Step by step » Design the GUI 

### ISSUE THREAD

**Issue by matrem** [godotengine/godot-docs#599]
http://docs.godotengine.org/en/latest/learning/step_by_step/ui_game_user_interface.html#replace-the-label-s-font

"Count container has a minimum" it's not the count countainer but the Background one

It was setup in http://docs.godotengine.org/en/latest/learning/step_by_step/ui_game_user_interface.html#create-the-bars-base

Further it says : "In the Rect section set the node’s Min Size back to 100" speaking about the count node
http://docs.godotengine.org/en/latest/learning/step_by_step/ui_game_user_interface.html#add-the-ui-components-to-the-final-gui
So it's not clear where is the error.

When completing the step, it appears the min size should be set on the count node in order to the bar to align well.

**Comment by matrem** [comment]
BTW, It seems to me that each time the doc say "save the scene and rename node" (for inherited scenes), it should say "rename node and save the scene" so when saving the scene has already the good name.

**Comment by NathanLovato** [comment]
Thanks, will fix this on the next write the docs. Got some more changes to add now the UI system changed as well.
