### ISSUE TITLE
Your first 2D game -> Creating the player scene: Missing information about creating a trail.

### ISSUE THREAD

**Issue by sbalia** [godotengine/godot-docs#5997]
**Your Godot version:** 3.4.4.stable.mono

**Issue description:**
Per the first page of "Your first 2D game", there should be a trail left behind the player. But when you read how to create the player scene, there is no information about it. 

If we go to the godot-demo-projects repository, that project has trail functionality (https://github.com/godotengine/godot-demo-projects/tree/master/2d/dodge_the_creeps).

My question is: was it done intentionally (due to some complexity)? Or it's just the missing part?

![image](https://camo.githubusercontent.com/1a6502972db8aaa087b38926c8a394809f866f20043f2ddfd7cb7ee06cb9daf1/68747470733a2f2f646f63732e676f646f74656e67696e652e6f72672f656e2f6c61746573742f5f696d616765732f646f6467655f707265766965772e676966)

**URL to the documentation page (if already existing):**
https://docs.godotengine.org/en/stable/getting_started/first_2d_game/02.player_scene.html

**Comment by Calinou** [comment]
The trail is likely drawn using a CPUParticles2D node. I assume it was removed for complexity reasons during the tutorial's development.

cc @NathanLovato

**Comment by cbscribe** [comment]
Yes, that's what happened as I recall. I thought I remembered it being taken out of the demo project, but maybe we should leave it in there as a little easter egg for those who download it.

**Comment by sbalia** [comment]
@Calinou , Yes, it's indeed implemented with a CPUParticles2D node.
I'm just curious. To be honest, when I discovered that, I was confused a bit (what part did I miss from the guide), but after a quick look at the demo repository, everything was clear :)

**Comment by Calinou** [comment]
It might be worth remaking the GIF to use the final project without the particle, as to not be misleading.

**Comment by sbalia** [comment]
Closing the issue as the PR was merged.
