### ISSUE TITLE
Script/Webapp for translations changes tracking

### ISSUE THREAD

**Issue by StraToN** [godotengine/godot-docs#6]
In order to ease documentation translators' work, we intend to build a script/webapp showing concrete differences between English files versions between commits in time.

For following explanations, French (FR) example is taken. It will of course be valid for ALL translations.
English (EN) translation is supposed to be the basis of ALL translations.

Here are all the requisites:
- Sort commits from EN and FR chronologically
- Display them on a timeline : http://pasteboard.co/1CKx8ZKH.png
- Show a diff tool displaying the differences between the previous EN commit which happened before last FR commit, and the latest EN commit. That way, FR translator can impact all changes that happened between the last EN commit which was already impacted to FR, and the latest (most recent) EN commit, even if there were 100+ EN commits in-between.
- In the image example: hoi2djn is the last EN commit that was impacted in FR (dq22a21). However, the latest EN commit is 12315aq, which is not impacted in FR yet.
- Each commit hash would be a link to the commit on GH 
- Files that do not exist between EN and FR should be notified (eg: French user-made tutorials not existing in English, and the inverse)

We think this application should be accessible from a web page.

**Comment by StraToN** [comment]
Pretty old entry, but still interesting : https://github.com/blog/683-cross-repository-compare-view

**Comment by pwab** [comment]
Maybe I got something wrong here but why the normal way of [translating sphinx messages](http://www.sphinx-doc.org/en/stable/intl.html) for a [readthedocs project](http://docs.readthedocs.io/en/latest/localization.html#project-with-multiple-translations) (using gettext) combined with weblate (like for the [engine itself](https://hosted.weblate.org/projects/godot-engine/godot/)) is not used?

**Comment by StraToN** [comment]
@pwab I suppose we didn't have an idea of this feature at this time :) OR, it maybe appeared meanwhile. Anyway, I think this issue can be closed now since using *.po will help a lot keeping track of what's translated and what's not.
