### ISSUE TITLE
Step by step » Control the game’s UI with code

### ISSUE THREAD

**Issue by matrem** [godotengine/godot-docs#600]
http://docs.godotengine.org/en/latest/learning/step_by_step/ui_code_a_life_bar.html

> Here’s what you’ll create: the bar and the counter animate when the character takes a hit. They fade when it dies.

duplicated

**Comment by matrem** [comment]
http://docs.godotengine.org/en/latest/learning/step_by_step/ui_code_a_life_bar.html#download-and-explore-the-start-project
.zip only contains start and end folders (no tutorial and exercise)

**Comment by matrem** [comment]
"In the FileSystem dock double click on LevelMockup.tscn to open it"
Already open when loding the project

**Comment by matrem** [comment]
"You can also right click on the GUI node and activate the Editable Children checkbox "
Already checked (perhaps sentence should be reformulated) + image missing.

**Comment by matrem** [comment]
"image:: img/lifebar_tutorial_TextureProgress_default_max_value.png"
image missing

**Comment by matrem** [comment]
"Because GUI is higher than Player in the scene tree, Godot will call its _ready function first. If we got the health value then it would still be at 0."
Here it seems to say that we won't be able to get player health in gui ready function.

But here it seems to say that we can :
"Also call update_health at the end of the _ready function to initialize"

Testing it work on the current master branch (perhaps because health is initialized at declaration time not in the ready?)

**Comment by matrem** [comment]
http://docs.godotengine.org/en/latest/learning/step_by_step/ui_code_a_life_bar.html#animate-the-loss-of-life-with-the-tween-node
Missing animated_health initialization

Perhaps we should replace update_health() call in ready by
<animated_health = $"../Characters/Player".health>

**Comment by matrem** [comment]
> Tween.interpolate_property(self, "modulate", start_color, end_color, 1.0, Tween.TRANS_LINEAR, Tween.EASE_IN)

tween should be lowercase

**Comment by akien-mga** [comment]
cc @NathanLovato

**Comment by NathanLovato** [comment]
Thanks for the detailed feedback. I'll fix all this during the next write the docs event.

**Comment by MoraleMuffin5** [comment]
Accepts feedback/documentation from a github issue post

Prejudiced against users who don't use git for documentation

Pick one.

**Comment by NathanLovato** [comment]
I deleted the comments as I fixed them*
