### ISSUE TITLE
Undocumented metadata `_tab_name`, `_tab_icon`, etc. for children of `TabContainer`

### ISSUE THREAD

**Issue by MatthijsMud** [godotengine/godot-docs#6002]
**Your Godot version:**
Godot 3.4.4.stable.mono

**Issue description:**
The documentation for `TabContainer` does not seem to include any information about the metadata `_tab_name` , `_tab_icon`, `_tab_hidden`, and `_tab_disabled`.

---

The class `TabContainer` by default uses the name of a child `Control` for the title of its corresponding tab. There are however cases imaginable where a user might want to use text that is not allowed for node names (i.e. duplicate names for tabs, tabs without text, or tabs with special characters). This can be done by calling [`set_tab_title`](https://docs.godotengine.org/en/stable/classes/class_tabcontainer.html#class-tabcontainer-method-set-tab-title). [`set_tab_icon`](https://docs.godotengine.org/en/stable/classes/class_tabcontainer.html#class-tabcontainer-method-set-tab-icon), [`set_tab_hidden`](https://docs.godotengine.org/en/stable/classes/class_tabcontainer.html#class-tabcontainer-method-set-tab-hidden), and [`set_tab_disabled`](https://docs.godotengine.org/en/stable/classes/class_tabcontainer.html#class-tabcontainer-method-set-tab-disabled) serve similar purposes, respectively changing the icon, visibility and enabledness of the tab. 

In version 3.X this appears to be done by setting the above metadata on the relevant node. Version 4 seems to have moved some of the metadata.

By manually changing the metadata in the text file a user could preview the changes in the editor [without messing around with signals](https://github.com/godotengine/godot/issues/26194#issuecomment-665827954), needing to write a `tool` script, or waiting for the editor UI to be improved. 

**URL to the documentation page (if already existing):**
Some of the pages related to `TabContainer` don't seem to mention this feature (or implementation detail), so it is just something one might stumble upon instead.

- [Using Gui Containers](https://docs.godotengine.org/en/stable/tutorials/ui/gui_containers.html#tab-container)
- [TabContainer](https://docs.godotengine.org/en/stable/classes/class_tabcontainer.html)

**Comment by YuriSizov** [comment]
The editor improvements are already being worked on in https://github.com/godotengine/godot/pull/58749

**Comment by MatthijsMud** [comment]
Allright, I wasn't aware that metadata wasn't normally documented; it makes sense when considering it an implementation detail, thus allowing for changing it between versions without considering it a breaking change.

When researching I might have been focused a bit too much on the metadata aspect that I have missed those improvements. Looks nice.
