### ISSUE TITLE
Step by step » SceneTree : entering the scene and ready calling

### ISSUE THREAD

**Issue by matrem** [godotengine/godot-docs#601]
I would say the 3rd point of this http://docs.godotengine.org/en/latest/learning/step_by_step/scene_tree.html#becoming-active-by-entering-the-scene-tree
is not really correct, or misleading

because it seems after testing : 
- everyone node has his _enter_tree() called top bottom,
- and then _ready is called from the depth top bottom
_ready seems not to be called as soon as all child of a node and the node are inside the scene.

Also,  here it seems to confirm this : http://docs.godotengine.org/en/latest/learning/step_by_step/ui_code_a_life_bar.html#set-up-the-lifebar-with-the-player-s-max-health
> Godot calls _ready right after it loaded all node

**Comment by MoraleMaduzo** [comment]
@matrem Hi there,

This is unfortunately not a high priority issue at all. Voting to close

**Comment by cbscribe** [comment]
Closing as I think this was addressed by the linked rewrite. Feel free to open a new issue if you feel the need is still there.
