### ISSUE TITLE
FPS Tutorial is Missing from 3D category( Doc 3.4 )

### ISSUE THREAD

**Issue by ToufiqueAzad** [godotengine/godot-docs#6011]
Hi
This tutorial is missing from latest/stable documentation.
https://docs.godotengine.org/en/3.3/tutorials/3d/fps_tutorial/index.html

**Comment by Calinou** [comment]
The FPS tutorial was removed in https://github.com/godotengine/godot-docs/pull/4074 as part of [moving the official documentation towards a reference manual](https://github.com/godotengine/godot-docs/issues/3390).
