### ISSUE TITLE
Dodge the Creeps tutorial: doubts on instructions when connecting game_over signal

### ISSUE THREAD

**Issue by magmax** [godotengine/godot-docs#6028]
**Your Godot version:**
3.2.3

**Issue description:**
I'm very very new to godot and I'm following the tutorial. It is very good, despite I miss some explanations some times.

I'm lost in this piece of the tutorial:
![image](https://user-images.githubusercontent.com/584026/182768715-3656bfb9-f540-4290-8423-2b3f25ee4834.png)

When I select the `Player` node and try to assign the `hit` signal to the `game_over` function, Godot only allows me to create the function inside `Player` and not in `Main`:

![image](https://user-images.githubusercontent.com/584026/182768984-259b4ae3-f06a-4012-a714-bf0722fe4928.png)

I'm not sure what I've missed but seeing the final solution it looks like the `game_over` function [is created on `main.gd`](https://github.com/godotengine/godot-demo-projects/blob/master/2d/dodge_the_creeps/Main.gd#L10) and [it is linked from Main Node.](https://github.com/godotengine/godot-demo-projects/blob/master/2d/dodge_the_creeps/Main.tscn#L54).

So I'm not sure if I missed any step or it is a documentation error. Anyway, help will be appreciated.

**URL to the documentation page (if already existing):**
https://github.com/godotengine/godot-docs/blob/master/getting_started/first_2d_game/05.the_main_game_scene.rst

**Comment by Calinou** [comment]
> 3.2.3

[Godot 3.2.x is not supported for bug fixes anymore](https://docs.godotengine.org/en/stable/about/release_policy.html#release-support-timeline), so please upgrade to [3.4.4](https://godotengine.org/article/maintenance-release-godot-3-4-4) and check if the issue still occurs there.

**Comment by magmax** [comment]
@Calinou tested on version 3.4.5 and same problem.

**Comment by Calinou** [comment]
This part of the documentation was changed by https://github.com/godotengine/godot-docs/pull/6007. Was the previous form clearer?

**Comment by magmax** [comment]
That part is fine, @Calinou . I added it just as context. My problem is in the next 2 paragraphs: If I open the `Player` node and try to connect a new handler to the `hit` signal, the handler function is created in the `Player` script, and not in `Main` as it should. I still do not know what I'm doing wrong.

**Comment by YuriSizov** [comment]
Are you sure you select the Player node in the Main scene, and not the Player scene?

**Comment by magmax** [comment]
> Are you sure you select the Player node in the Main scene, and not the Player scene?

that was it!
I missed the part "Click the Instance button (represented by a chain link icon) and select your saved Player.tscn.".

Thank you very much!
