### ISSUE TITLE
Remove old simple_2d_game and move input action map docs

### ISSUE THREAD

**Issue by matrem** [godotengine/godot-docs#603]
This interesting link is not referenced in the step_by_step menu :
http://docs.godotengine.org/en/latest/learning/step_by_step/simple_2d_game.html#doc-simple-2d-game-input-actions-setup

I discover it from this page :
http://docs.godotengine.org/en/latest/learning/features/inputs/inputevent.html#actions

**Comment by matrem** [comment]
But this is because it does not seem to be updated to 3.0

**Comment by NathanLovato** [comment]
It should be deleted, it's been replaced by [](http://docs.godotengine.org/en/latest/learning/step_by_step/your_first_game.html)

**Comment by NathanLovato** [comment]
To do:

- [ ] rewrite/move input action docs from http://docs.godotengine.org/en/latest/learning/step_by_step/simple_2d_game.html#doc-simple-2d-game-input-actions-setup to http://docs.godotengine.org/en/latest/learning/features/inputs/inputevent.html#inputmap (or to a new page with complete explanations?)
- [ ] Remove simple 2d game: http://docs.godotengine.org/en/latest/learning/step_by_step/simple_2d_game.html

**Comment by MoraleMuffin5** [comment]
Awww, this is pretty rich. @NathanLovato (someone that is literally prejudiced against non-git users), telling others what to do.

![](http://forums.d2jsp.org/html/emoticons/bangin.gif)

**Comment by brainsick** [comment]
It looks like simple 2d game was removed in 56b66d4.  The input map item is still outstanding then?

**Comment by Calinou** [comment]
Is this now considered resolved?

**Comment by NathanLovato** [comment]
Yup, let's close for now.
