### ISSUE TITLE
Reference to HTTPRequest in HTTPClient isn't working

### ISSUE THREAD

**Issue by thiagola92** [godotengine/godot-docs#6042]
**Your Godot version:** 3.5

**Issue description:** Reference to HTTPRequest in HTTPClient is not working

**URL to the documentation page:** https://docs.godotengine.org/en/stable/classes/class_httpclient.html#class-httpclient

![image](https://user-images.githubusercontent.com/9352894/183269836-8ef23b72-08b8-42fe-81fc-2a52896acb76.png)

**Comment by Calinou** [comment]
This is because reStructuredText doesn't allow URLs within bold/italic text.
