### ISSUE TITLE
NavigationServer2D documentation links to a tutorial that uses the deprecated Navigation2D class

### ISSUE THREAD

**Issue by timcode77** [godotengine/godot-docs#6055]
**Your Godot version:** v3.5.stable.official [991bb6ac7]

**Issue description:** The NavigationServer2D documentation points to a tutorial that uses deprecated Navigation2D.

**URL to the documentation page:** https://docs.godotengine.org/en/latest/classes/class_navigationserver2d.html

The "tutorial" in question is here: https://github.com/godotengine/godot-demo-projects/tree/3.4-b0d4a7c/2d/navigation

In general, the new NavigationServer2D documentation is very poor, giving no real indication of how to use it.

**Comment by Calinou** [comment]
> In general, the new NavigationServer2D documentation is very poor, giving no real indication of how to use it.

A lot of pull requests were recently opened to improve navigation documentation:

- https://github.com/godotengine/godot-docs/pull/6044
- https://github.com/godotengine/godot-docs/pull/6045
- https://github.com/godotengine/godot-docs/pull/6046
- https://github.com/godotengine/godot-docs/pull/6048
- https://github.com/godotengine/godot-docs/pull/6049
- https://github.com/godotengine/godot-docs/pull/6050
- https://github.com/godotengine/godot-docs/pull/6051
- https://github.com/godotengine/godot-docs/pull/6052
- https://github.com/godotengine/godot-docs/pull/6053
- https://github.com/godotengine/godot-docs/pull/6054
