### ISSUE TITLE
Better way to make icons in GIMP

### ISSUE THREAD

**Issue by KoBeWi** [godotengine/godot-docs#6056]
**Your Godot version:**
3.5

**Issue description:**
I stumbled upon this when reading some discussion
https://docs.godotengine.org/en/stable/tutorials/export/changing_application_icon_for_windows.html#creating-an-ico-file
The doc links a video tutorial to make icons in GIMP. But there is a much better way. There is a plugin for GIMP called "iconify" that does the same thing as in the video, but with a single click. I think it's worth to mention it in the docs.

The plugin registry, where I originally got the plugin, seems to be dead, but here's some archived page (I think?):
https://github.com/pixlsus/registry.gimp.org_static/blob/master/registry.gimp.org/files/iconify2_1.scm
Not sure how do you install this now.

**Comment by Calinou** [comment]
Does the plugin work with the latest GIMP version? Is it expected to work with GIMP 3.0 which should come out next year if it follows release plans?

**Comment by KoBeWi** [comment]
I tested it and it doesn't work in 2.99.16. It wasn't updated in years, so I guess it's not a viable option (unless someone updates it .-.)

**Comment by tetrapod00** [comment]
Closing this per discussion above.
