### ISSUE TITLE
Improve the `Interactive rebase` doc

### ISSUE THREAD

**Issue by nonunknown** [godotengine/godot-docs#6064]
**Your Godot version:**
master

**Issue description:**

I'm new to contributing, when the pr reviewer request a `squash` into my commits, I tried following this documentation:

https://docs.godotengine.org/en/latest/community/contributing/pr_workflow.html#the-interactive-rebase

it says to execute: ` git rebase -i upstream/master`

but in my case I dont have upstream/master, so in order to improve, the doc could have:

```
In case the above command doesnt work, it means you dont have upstream remote, do the following:

`git remote add upstream git@github.com:godotengine/godot.git`

```

I'm proposing this, from a POV from someone who wants to contribute but doesnt know almost nothing about git, and the person who made this documentation could imagine this kind of situation.

cc @QbieShay

**Comment by QbieShay** [comment]
It's higher up in the doc 
![image](https://user-images.githubusercontent.com/7917475/183977732-381caf5b-6f54-4da5-81b0-33190543ef97.png)

**Comment by YuriSizov** [comment]
Indeed, while we often link to the specific section of this article, it is written in order and assumes you have a setup as described. Or know git to recognize what you may be missing.

Having a dedicated remote called `upstream` for the main repository is a pretty common practice with OSS development (and your own forked repository should be `origin`).

That said, since we link to the interactive rebase section often, we can add a note about what `upstream/master` is and propose to read the preceding part of the article.

**Comment by smix8** [comment]
For Windows and macOS users that work with the official git GUI tools 90% of the pr doc is also convoluted linux console command irrelevance. I guess the pullrequest workflow could benefit from a simple tutorial that shows the basic steps to contribute to Godot with using the official GUI tools for those two platforms. Especially the often required rebasing and force pushing is needlessly complicated with console commands for new users while it is a simple drag&drop and buttonpress in the GUI tool.

**Comment by YuriSizov** [comment]
I use GUI application for git (SourceTree), but I find that rebases are better done through CLI, directly in VS Code. You need to edit code and it just ends up being quicker.

Any official apps for Git (or GitHub) are pretty awful, so I'd avoid making instructions for them and recommend using them.

**Comment by nonunknown** [comment]
> It's higher up in the doc ![image](https://user-images.githubusercontent.com/7917475/183977732-381caf5b-6f54-4da5-81b0-33190543ef97.png)

very weird I didnt saw that.... I'm ashamed!

**Comment by Calinou** [comment]
> should I close this proposal then?

Yes :slightly_smiling_face:

**Comment by QbieShay** [comment]
No need to be ashamed, it's a big page.
