### ISSUE TITLE
Create a comprehensive reference for using Skeleton2D and Bone2D / Inverse Kinematics

### ISSUE THREAD

**Issue by timcode77** [godotengine/godot-docs#6069]
**Your Godot version:** v3.5.stable.official [991bb6ac7]

**Issue description:** The documentation for Skeleton2D and Bone2D is not sufficient to begin using Skeleton2D and Bone2D. For the user who wants to create animations and simulations using Inverse Kinematics etc, the docs are not helpful.

**URL to the documentation page (if already existing):**
Some basics are touched on here: https://docs.godotengine.org/en/stable/tutorials/animation/2d_skeletons.html

One of the problems with that tutorial is that it blends together a tutorial on 2D mesh deformation and skeleton/bones. Yes, these things are often used together, but there are other use cases for skeletons / bones that don't involve mesh deformation. Additionally, the tutorial (and nowhere else in the docs that I can find) are the following editor functions explained:

- Make IK Chain
- Clear IK Chain
- Make Custom Node(s) from Bone(s)
- Clear Custom Bones

- Reset to Rest Pose
- Overwrite Rest Pose

I think we need a comprehensive tutorial for Skeleton2D and Bone2D that explains all of this.

**Comment by timcode77** [comment]
Apologies - I located the relevant tutorial.

**Comment by Calinou** [comment]
> Apologies - I located the relevant tutorial.

Could you link to the tutorial here? This will help others who stumble upon this issue from a web search :slightly_smiling_face:

**Comment by timcode77** [comment]
> > Apologies - I located the relevant tutorial.
> 
> Could you link to the tutorial here? This will help others who stumble upon this issue from a web search 🙂

Of course! Good idea. Updated the original above.
