### ISSUE TITLE
Isn't  "destructor" misleading?

### ISSUE THREAD

**Issue by matrem** [godotengine/godot-docs#607]
http://docs.godotengine.org/en/latest/learning/scripting/visual_script/nodes_purposes.html#destructor

destructor ? is really the good name for that?

**Comment by johnorchard** [comment]
I think this is usually referred to as de-structuring, but given the example in the screenshot and the use of the word "constructor", I would think that "deconstructor" would be the most consistent.

**Comment by NullConstant** [comment]
(To me, at least), a destructor would imply something akin to the OOP idea of a destructor, which this is pretty clearly not.

**Comment by mhilbrunner** [comment]
If I'm not missing anything, this should be raised as an issue in the https://github.com/godotengine/godot repo instead, as the name for the Visual Script node is defined there.
