### ISSUE TITLE
How to compile Godot Editor for Android

### ISSUE THREAD

**Issue by AndyAnon14** [godotengine/godot-docs#6086]
Godot version: 3.5

Issue description: Would like to see a guide on how to compile the Godot Editor for Android. The current guide only shows how to compile an Android Template, and not the full editor.

URL to the documentation page:
https://docs.godotengine.org/en/latest/development/compiling/compiling_for_android.html

**Comment by Calinou** [comment]
The two changes you need to make is to use the `tools=yes` SCons option, and use `./gradlew generateGodotEditor` instead of `./gradlew generateGodotTemplates` in `platform/android/java`.

**Comment by AndyAnon14** [comment]
Thank you for the clarification. I will open a pull request for the edits.

**Comment by AndyAnon14** [comment]
Issue closed, clarification provided in comments.

**Comment by Calinou** [comment]
Reopening, as this still needs to be documented.

**Comment by AndyAnon14** [comment]
Opened a pull request; https://github.com/godotengine/godot-docs/pull/6089

**Comment by AndyAnon14** [comment]
Submitted pull request #6115 to update the instructions to include compiling the Godot Editor for Android.

**Comment by skyace65** [comment]
Closing this issue as #6115 fixed it.
