### ISSUE TITLE
Step by step : Nodes and Scenes - move label out of date?

### ISSUE THREAD

**Issue by chrismigut** [godotengine/godot-docs#6140]
**Your Godot version:**
v3.5.stable.flathub [991bbac7]

**Issue description:**
Move mode and Pan mode act similar, with only moving the window. 
Following along the tutorial the steps about selecting the label and than move doesn't work. 

expected
![image](https://user-images.githubusercontent.com/10051729/188477000-9175ea2f-5729-4454-9038-87071e09f083.png)

actual
![image](https://user-images.githubusercontent.com/10051729/188477255-7bb0acb2-d164-44a1-bb73-f327b3ff407a.png)

![image](https://user-images.githubusercontent.com/10051729/188477405-b5d21048-b86a-43a6-a1a7-fee0a12621f4.png)

This is an issue with the linux version of godot or documentation out of date. 

**URL to the documentation page:**
https://docs.godotengine.org/en/stable/getting_started/step_by_step/nodes_and_scenes.html#changing-a-node-s-properties

**Comment by skyace65** [comment]
I just tested this on Windows 10, as well as on OpenSuse tumbleweed with the flathub version (3.5.1) and it's working as it should for me where clicking and dragging moves the node. If you're still having this issue please report it in the engine repository [here](https://github.com/godotengine/godot), as that is a bug.
