### ISSUE TITLE
vec_type min ===> Maximum (Stable Version)

### ISSUE THREAD

**Issue by tuto193** [godotengine/godot-docs#615]
http://docs.godotengine.org/en/stable/learning/features/shading/shading_language.html 
In the Built-In Functions:
...

vec_type **min** ( vec_type,vec_type ) | Maximum
-- | --

Should be:

vec_type **max** ( vec_type,vec_type ) | Maximum
-- | --

**Comment by MuffinMan50** [comment]
@tuto193 This is not a big issue at all, Juan told me on reddit.

Voting to close.

**Comment by Meriipu** [comment]
I think this can be closed?

**Comment by Calinou** [comment]
Indeed, this was solved in the current version of [Shading language](https://docs.godotengine.org/en/latest/tutorials/shading/shading_reference/shading_language.html) a while ago.
