### ISSUE TITLE
`change_scene` and `change_scene_to` have been renamed

### ISSUE THREAD

**Issue by Jayman2000** [godotengine/godot-docs#6156]
**Your Godot version:**
v4.0.alpha.custom_build [d2a6a187f]

**Issue description:**
Now that godotengine/godot#63596 is merged, `change_scene` needs to be replaced with `change_scene_to_file` and `change_scene_to` needs to be replaced with `change_scene_to_packed`.

**URL to the documentation page:**
<https://docs.godotengine.org/en/latest/tutorials/scripting/scene_tree.html?highlight=change_scene#changing-current-scene>

**Comment by Kirrby** [comment]
made a pr
