### ISSUE TITLE
Theme methods parameter list use 'theme_type', description refers to 'node_type'

### ISSUE THREAD

**Issue by qaptoR** [godotengine/godot-docs#6157]
**Your Godot version:**
3.5 stable

**Issue description:**
Parameter list for many Theme methods refer to 'theme_type', but method description uses 'node_type'

![image](https://user-images.githubusercontent.com/40372043/189329322-da64c592-83ef-4cd0-a92e-7eef58d417aa.png)

**URL to the documentation page:**
https://docs.godotengine.org/en/stable/classes/class_theme.html#class-theme-method-get-constant

If you know how to fix the issue you are reporting please
consider opening a pull request. We provide a tutorial on
using git here: https://docs.godotengine.org/en/stable/community/contributing/pr_workflow.html,
writing documentation at https://docs.godotengine.org/en/stable/community/contributing/docs_writing_guidelines.html
and contributing to the class reference here: https://docs.godotengine.org/en/stable/community/contributing/updating_the_class_reference.html

**Comment by akien-mga** [comment]
Fixed by https://github.com/godotengine/godot/pull/65568.
