### ISSUE TITLE
`print_line()` description is outdated

### ISSUE THREAD

**Issue by KoBeWi** [godotengine/godot-docs#6165]
**Your Godot version:**
4.0

**Issue description:**
`print_line()` accepts any number of Variant arguments and will convert them to string and print separated by spaces. It's functionally the same as `prints()` in GDScript. The docs still mention formatting or `itos()`, which are no longer necessary.

**URL to the documentation page:**
https://docs.godotengine.org/en/latest/development/cpp/common_engine_methods_and_macros.html

**Comment by Calinou** [comment]
>  The docs still mention formatting or itos(), which are no longer necessary

`vformat()` is still useful if you need quick access to things like zero-padding, rounding, etfc.
