### ISSUE TITLE
Minor typo in vector math documentation

### ISSUE THREAD

**Issue by borlox** [godotengine/godot-docs#619]
Hello,

the vector math documentation contains a typo in the 2nd formular for the dot product.
The [vector_dot2.png image](https://github.com/godotengine/godot-docs/blob/master/learning/features/math/img/vector_dot2.png) 

![grafik](https://user-images.githubusercontent.com/21562/33487766-9e6bffb4-d6ae-11e7-9a14-9bc56fe28065.png)

should be replaced by something like this: 

![grafik](https://user-images.githubusercontent.com/21562/33487802-c0d3c47e-d6ae-11e7-9c4d-cdb05b8c727f.png)

Thank you for the extensive and helpful documentation!
Jan

**Comment by akien-mga** [comment]
BTW, we could maybe dehardcode those images and use Sphinx's math support instead: http://www.sphinx-doc.org/en/stable/ext/math.html (haven't checked if it's sufficient though, or how it looks like)

**Comment by cbscribe** [comment]
Good catch! That was a dumb mistake :P  

I'll try out the math support - if it works, it'll be useful elsewhere too.

**Comment by cbscribe** [comment]
I tried out the sphinx math support, the result:
![screen shot 2017-12-02 at 9 11 24 am](https://user-images.githubusercontent.com/3812514/33517892-e0ffc88c-d740-11e7-8960-c5d0bdc33fbe.png)

Equations have to be written in Latex form (there are many useful online editors to generate):

    .. math::
    
    A \cdot B = \left \| A \right \|\left \| B \right \|\cos \Theta

Requirements: latex must be installed, and `latex` and `dvipng` available in the path.

**Comment by MoraleMaduzo** [comment]
Not a high priority at all.. voting to close this.

**Comment by mhilbrunner** [comment]
This can be closed as it was fixed in #620.

**Comment by cbscribe** [comment]
Closed by #620
