### ISSUE TITLE
RigidDynamicBody2D referenced but not in 4.0b

### ISSUE THREAD

**Issue by Black-Virtue** [godotengine/godot-docs#6191]
**Your Godot version: 4.0b**

**Issue description: Documentation lists non-existant type**

**URL to the documentation page: https://docs.godotengine.org/en/latest/getting_started/first_2d_game/04.creating_the_enemy.html**

Documentation references RigidDynamicBody2D, only RigidBody2D exists in 4.0b.
Unsure if this is a feature yet to be included or documentation referencing to a name in flux.

**Comment by Calinou** [comment]
RigidDynamicBody2D was renamed back to RigidBody2D recently.
