### ISSUE TITLE
Enhancing overall C# Documentation

### ISSUE THREAD

**Issue by ghost** [godotengine/godot-docs#6194]
**Your Godot version:** 3.5.stable

**Issue description:** Dear fellow contributors, I'm new to Godot and Game Making and have recently decided to make an open-world game using Godot. I did my research and have considered using C# for the reason of Performance and Libraries. After completing some tutorials and reading (a lot) of Godot's documentation, it seemed to me that C# is in a third-world position in terms of Documentation. For instance, most of "Your first 3D Game" scripting [https://docs.godotengine.org/en/stable/getting_started/first_3d_game/](url) ranging from methods to signals to variables are suggested in GDScript and the only reference you can get is the code in the C# tab which can, for beginners, be an additional burden. On top of that, almost all of Godot API's documentation [https://docs.godotengine.org/en/stable/classes/](url) is based on GDscript only, which makes your task in C# even harder.

I have considered switching to GDScript many times but doing so would mean I would have to rewrite a lot of my existing C# code and connections into GDscript just because one method or signal or object didn't work.

**URL to the documentation page (if already existing):**

**Comment by Calinou** [comment]
This issue isn't very actionable in this current state. We welcome contributions that add C# code samples for code blocks that currently only have GDScript.

As for displaying the class reference with PascalCase syntax, there is https://github.com/godotengine/godot-docs/pull/4406 but it's too hacky to be mergeable right now.
