### ISSUE TITLE
set_input_as_handled doesn't exist in 4.0/latest

### ISSUE THREAD

**Issue by FyiurAmron** [godotengine/godot-docs#6195]
**Your Godot version:**
4.0 beta-1

**Issue description:**
Official docs for 4.0/latest mention `SceneTree.set_input_as_handled()` in input HowTo tutorials, but it doesn't exist anymore. Also, there's no mention of a method to mark input events as handled that would be supported in 4.0 there.

**URL to the documentation page:**
https://docs.godotengine.org/en/latest/tutorials/inputs/inputevent.html#how-does-it-work

- it points to

https://docs.godotengine.org/en/latest/classes/class_scenetree.html#class-scenetree-method-set-input-as-handled

which doesn't exist anymore. (verified it in the editor, the method is no more)

(https://docs.godotengine.org/en/stable/classes/class_scenetree.html#class-scenetree-method-set-input-as-handled does exist and works, though)

**Comment by hsandt** [comment]
Seems fixed now, it says `Viewport.set_input_as_handled` which I suppose can simply be called via `get_viewport().set_input_as_handled()` on any Node script.

**Comment by FyiurAmron** [comment]
@hsandt good point, they have indeed fixed it in the meantime ( https://docs.godotengine.org/en/latest/tutorials/inputs/inputevent.html#how-does-it-work points to valid https://docs.godotengine.org/en/latest/classes/class_viewport.html#class-viewport-method-set-input-as-handled ), so I'm closing this.
