### ISSUE TITLE
No explanation about breakpoints in Scripting/Core featurer/debug

### ISSUE THREAD

**Issue by Esnos33** [godotengine/godot-docs#6207]
**Your Godot version:**
3.5
**Issue description:**
No info how to set breakpoints manualy. I found out about it from this site:
https://www.gdquest.com/tutorial/godot/gdscript/debugging/
and there is no information about breakpoints and about F9 shortcut.
**URL to the documentation page (if already existing):**
https://docs.godotengine.org/en/stable/tutorials/scripting/debug/overview_of_debugging_tools.html

**Comment by tetrapod00** [comment]
Closing, since this was fixed by https://github.com/godotengine/godot-docs/pull/7271.
