### ISSUE TITLE
update() in Custom Drawing 2D

### ISSUE THREAD

**Issue by romarro** [godotengine/godot-docs#6208]
**Your Godot version:**
4.0 beta1
**Issue description:**
In the documentation page for Custom Draw 2D at updating drawing there is a reference to the update() method
This method doen't exist anymore in the GDScript 2.0.

I can only presume that queue_draw() is the function to be called instead of update(). Is this right?

**URL to the documentation page:**
tutorials/2d/custom_drawing_in_2d.rst

If you know how to fix the issue you are reporting please
consider opening a pull request. We provide a tutorial on
using git here: https://docs.godotengine.org/en/stable/community/contributing/pr_workflow.html,
writing documentation at https://docs.godotengine.org/en/stable/community/contributing/docs_writing_guidelines.html
and contributing to the class reference here: https://docs.godotengine.org/en/stable/community/contributing/updating_the_class_reference.html

**Comment by LL3006** [comment]
Yes that's right, CanvasItem.update() has been renamed to queue_redraw() in godotengine/godot#64377. I'll submit a PR shortly.
