### ISSUE TITLE
crash on audio file rename

### ISSUE THREAD

**Issue by VivoCyber** [godotengine/godot-docs#6210]
godot 3.5

my godot crash in some audio action like rename imported mp3 file. even some time in import mp3 and ...

but operation (like import or rename ) is done and when reopen godot is completed.

**Comment by skyace65** [comment]
Godot crashing when renaming a file is an engine bug, not a documentation bug, and for engine bugs an issue should be created in the engine repository. I just tested renaming a MP3 in 3.5.1 and had no issues, but if you're still having problems please create an issue in the engine repository [here](https://github.com/godotengine/godot/issues).
