### ISSUE TITLE
2D Dodge The Creeps Tutorial - Question on stretch viewport

### ISSUE THREAD

**Issue by TheYellowArchitect** [godotengine/godot-docs#6224]
**Your Godot version:**
4.0 beta 1

**Issue description:**
UI in [this image](https://docs.godotengine.org/en/latest/_images/setting-stretch-mode.png) literally does not exist

> Also, scroll down to the bottom of the section and, under the "Stretch" options, set Mode to "2d"

4.0 doesn't have the "2d" option (default is disabled), so what is the proper choice/alternative for it? (I am a newbie)

**URL to the documentation page:**
https://docs.godotengine.org/en/latest/getting_started/first_2d_game/01.project_setup.html

**Comment by Calinou** [comment]
The `2d` stretch mode was renamed to `canvas_items`.

**Comment by TheYellowArchitect** [comment]
Thank you. I am waiting for my pull requests to be merged, then i plan to mass image-update dodge the creeps tutorial (in this case, i didnt know what image is the proper one for the new project settings ui to replace)
