### ISSUE TITLE
Spatial Node does not exist in 4.0

### ISSUE THREAD

**Issue by TheYellowArchitect** [godotengine/godot-docs#6241]
**Your Godot version:**
4.0 beta1

**Issue description:**
https://docs.godotengine.org/en/latest/tutorials/3d/introduction_to_3d.html?highlight=spatial#spatial-node

First section, cannot find this node. I have not used 3.x branch, but I assume it has been renamed to Node3D (bless whoever did the renamings for 4.x, as they are all more intuitive)

Anyway, someone please confirm that `Spatial` node is just `Node3D` and I will do a pull request renaming that section appropriately.

**Comment by clayjohn** [comment]
You are right, ``Spatial`` was renamed to ``Node3D``!
