### ISSUE TITLE
Default coding style question

### ISSUE THREAD

**Issue by TheYellowArchitect** [godotengine/godot-docs#6245]
**Your Godot version:**
4.0 beta1

**Issue description:**
I honestly don't know whether to ask here or on godotengine. It's not really a bug, its more of a question which is important for docs.

When I have a node "AudioStreamPlayer" and make a scene out of it, Godot's default string is `audio_stream_player.tscn` instead of `AudioStreamPlayer.tscn` promoted by docs.
For signals, let's say I have object "PlayerGun". Godot's default string is `_on_player_gun_visibility_changed` instead of `_on_PlayerGun_visibility_changed` promoted by docs.

Anyway, somewhere in the docs I remember it says something about style, but engine's styling made by devs > docs

This question is not negligible, because if styling is consistent, it makes the docs better and also all the userbase will adopt that style, hence avoiding silly compiler typos here and there. I am also curious myself to know what is the way/styling recommended by the developers, or veteran users of Godot

**Comment by TheYellowArchitect** [comment]
Related to https://github.com/godotengine/godot-docs/issues/6245

**Comment by TheYellowArchitect** [comment]
I think so too, but I am awaiting for more devs to confirm, because I don't want to spend days changing the docs (including uploading new images) then suddenly "X was intended, pull request denied lol"

**Comment by snoopdouglas** [comment]
This also seems to be the case with `.gd` and `.cs` filenames.

**Comment by Calinou** [comment]
> This also seems to be the case with `.gd` and `.cs` filenames.

`.cs` file names must match the class name (this is a C# language requirement), so they must keep using PascalCase.
