### ISSUE TITLE
3D Game Tutorial Movement 4.0 incompatible code

### ISSUE THREAD

**Issue by TheYellowArchitect** [godotengine/godot-docs#6255]
**Your Godot version:**
4.0 beta1

**Issue description:**
Does anyone know how to fix this code?
https://docs.godotengine.org/en/latest/getting_started/first_3d_game/06.jump_and_squash.html#coding-the-squash-mechanic
(scroll down a bit)

I converted everything else, but this one I cannot do.
It's the only logic preventing a full update of the 3D tutorial onto 4.0
https://github.com/godotengine/godot-docs/pull/6243

**URL to the documentation page:**
https://docs.godotengine.org/en/latest/getting_started/first_3d_game/06.jump_and_squash.html#coding-the-squash-mechanic

**Comment by TheYellowArchitect** [comment]
Fixed in https://github.com/TheYellowArchitect/godot-docs/pull/1

**Comment by Calinou** [comment]
> Fixed in [TheYellowArchitect#1](https://github.com/TheYellowArchitect/godot-docs/pull/1)

This was merged in your fork, not in the upstream repository yet :slightly_smiling_face:

**Comment by Piralein** [comment]
Fixed by #6243.
