### ISSUE TITLE
Variant Duplicate

### ISSUE THREAD

**Issue by TheYellowArchitect** [godotengine/godot-docs#6258]
Everything within this outdated link https://docs.godotengine.org/en/latest/development/cpp/variant_class.html is contained within https://docs.godotengine.org/en/latest/classes/class_variant.html?highlight=variant

My suggestion is to **completely** delete https://docs.godotengine.org/en/latest/development/cpp/variant_class.html. Its only content which is unique, is the 3 references to c++ code, which could be its own section in the final Variant link, probably at the bottom like:

"C++ Source Code
[]variant.h
[]dictionary.h
[]array.h"

**Comment by YuriSizov** [comment]
(Note that the link now is https://docs.godotengine.org/en/latest/contributing/development/core_and_modules/variant_class.html)

While the articles duplicate each other in part, the class reference one is aimed at the engine users, and this one is aimed at engine contributors and module developers. We sure need to overhaul the engine internals documentation, but I don't see a reason to delete this article.
