### ISSUE TITLE
New 4.0 scons build options

### ISSUE THREAD

**Issue by Anutrix** [godotengine/godot-docs#6274]
**Your Godot version:**
Godot 4.0

**Issue description:**
After https://github.com/godotengine/godot/pull/66242, it would be helpful for new engine contributors if the compiling options are updated at https://docs.godotengine.org/en/latest/development/compiling/index.html.

**URL to the documentation page (if already existing):**
Pages listed at https://docs.godotengine.org/en/latest/development/compiling/index.html.

**Comment by corjohnson** [comment]
I've also noticed that when I just run `scons` on windows, it uses the most cores/threads available by default, specifying `scons -j 4` as an example actually resulted in a slower build than if I just used `scons`, I'm not sure if this is a change from godot build options side or if it's specific to the way scons version 4.4.0 is doing stuff

**Comment by Calinou** [comment]
> I'm not sure if this is a change from godot build options side or if it's specific to the way scons version 4.4.0 is doing stuff

This is indeed a change that was done in Godot.

**Comment by YuriSizov** [comment]
This issue is actually closed by https://github.com/godotengine/godot-docs/pull/6316.
