### ISSUE TITLE
sort_custom is not stable

### ISSUE THREAD

**Issue by tcoxon** [godotengine/godot-docs#6278]
**Your Godot version:** 3.4.5-stable

**Issue description:**

Documentation for `Array.sort_custom` does not specify the algorithm used or whether the result of sorting is stable. I took a look at the source code and it appears to use [introsort](https://en.wikipedia.org/wiki/Introsort), which is not stable.

It would be useful to document this as sorting stability is often a very useful feature. It can be easy mistake for a developer to assume it is stable (or not know that there are unstable algorithms), write code that relies on stability, and end up with bugs in their project.

**URL to the documentation page (if already existing):** https://docs.godotengine.org/en/stable/classes/class_array.html#class-array-method-sort-custom

**Comment by Calinou** [comment]
> It would be useful to document this as sorting stability is often a very useful feature. It can be easy mistake for a developer to assume it is stable (or not know that there are unstable algorithms), write code that relies on stability, and end up with bugs in their project.

Please open a [proposal](https://github.com/godotengine/godot-proposals) for making `sort_custom()` stable :slightly_smiling_face:
