### ISSUE TITLE
Rename "GDScript more efficiently"

### ISSUE THREAD

**Issue by Griatch** [godotengine/godot-docs#63]
The tutorial [GDScript more efficiently](https://github.com/godotengine/godot-docs/blob/master/reference/gdscript_more_efficiently.rst) strikes me as misleadingly named. The title (and introduction) suggests that it's a guide to optimizing GDScript code (which would be interesting and give more insight into the language's underpinnings). But apart from some examples of GDScript usage that seems to have little to do with efficient use, there is no real discussion of performance from the perspective of a GDScript user. Rather, this tutorial is squarely aimed at exemplifying GDScript code to developers coming from statically typed languages like C or Java. 

So I suggest renaming this tutorial to something more informative like "_GDScript compared to static languages_".

**Comment by akien-mga** [comment]
I wouldn't make it a "compared to static languages" page. From a quick glance, it does give example of how similar stuff is done in static languages, but the purpose is more to show how to use dynamic languages in the most efficient way (not as performance-wise, but for code quality).

I'm not against changing the name though if we come up with something that describes it better.

**Comment by Griatch** [comment]
@akien-mga 

It's certainly dominated by a side-by-side comparison between static languages and GDScript, but there are also a few mention of specific dynamic features like duck typing. So how about 
"*An introduction to dynamic languages*" ?

**Comment by noidexe** [comment]
What about "Writing idiomatic GDScript"?

**Comment by NathanLovato** [comment]
Fixed!
