### ISSUE TITLE
Instructions for project setup of first 2D game reference an unavailable mode

### ISSUE THREAD

**Issue by savvystrider** [godotengine/godot-docs#6341]
**Your Godot version:**
3.5

**Issue description:**
At the end of the 2D "Setting up the project," the instructions say to open Project Settings and "set Mode to canvas_items and Aspect to keep." However, the only modes I see available are "disabled," "2d," and "viewport." 

**URL to the documentation page:**
https://docs.godotengine.org/en/latest/getting_started/first_2d_game/01.project_setup.html

**Comment by Calinou** [comment]
You're reading the `/latest` documentation, which only applies to Godot 4.0.beta. Switch to the `/stable` documentation instead, as the warning in the header tells you.
