### ISSUE TITLE
Variant hyperlink retargeting to latest rather than stable doc

### ISSUE THREAD

**Issue by Skyvastern** [godotengine/godot-docs#6358]
**Your Godot version:**
3.5.1

**Issue description:**
In data_preferences.rst, there's a hyperlink `Variant` under section **Array vs. Dictionary vs. Object** where the link `Variant` retargets to `latest` rather than `stable` class reference page.

**URL to the documentation page:**
https://docs.godotengine.org/en/stable/tutorials/best_practices/data_preferences.html

**Solution**
I tried to update the link from [latest](https://docs.godotengine.org/en/latest/development/cpp/variant_class.html) to [stable](https://docs.godotengine.org/en/stable/development/cpp/variant_class.html). But the data_preferences.rst is using `:ref` keyword to refer to files. But I'm not well versed with the syntax, and going through it will take time. So opening this issue so someone aware of it's functioning can work upon this issue.

**Comment by Calinou** [comment]
This was fixed by https://github.com/godotengine/godot-docs/pull/6359, closing.
