### ISSUE TITLE
Typo in ZIPreader docs

### ISSUE THREAD

**Issue by oganm** [godotengine/godot-docs#6370]
**Your Godot version:** 4.0 beta4

**Issue description:** ZIPReader documentation has the example

```
func read_zip_file():
    var reader := ZIPReader.new()
    var err := reader.open("user://archive.zip")
    if err == OK:
        return PackedByteArray()
    var res := reader.read_file("hello.txt")
    reader.close()
    return res
```
that will return an empty `PackedByteArray()` if `reader.open()` returns `OK` while trying to read a file if `reader.open` returns an error. Likely the opposite was intended

**URL to the documentation page:** https://docs.godotengine.org/en/latest/classes/class_zipreader.html?highlight=zipreader

**Comment by Calinou** [comment]
Feel free to [open a pull request *on godotengine/godot*](https://docs.godotengine.org/en/latest/community/contributing/updating_the_class_reference.html) for this :slightly_smiling_face:

**Comment by akien-mga** [comment]
Fixed by https://github.com/godotengine/godot/pull/68581.
