### ISSUE TITLE
Export to RecalBox

### ISSUE THREAD

**Issue by djcaesar9114** [godotengine/godot-docs#6377]
**Your Godot version:**
stable

**Issue description:**
The documentation doesn't explain how to export a game to RecalBox.

**URL to the documentation page (if already existing):**

**Comment by Calinou** [comment]
[As part of moving the documentation towards being a reference manual](https://github.com/godotengine/godot-docs/issues/3390), I think this is better left to a third-party tutorial.

**Comment by skyace65** [comment]
From what I'm seeing on the website for Recalbox it's entire focus is on retro consoles that are no longer made. Godot does not export for these consoles  and has no plans to. Windows is listed as a supported system [here](https://www.recalbox.com/database/), though I can't find any information on their website on if you can actually run modern windows games or not. If you can you would just follow what's on the exporting for windows page.
