### ISSUE TITLE
Update the syntax highlighter for GDScript to include new keywords

### ISSUE THREAD

**Issue by Piralein** [godotengine/godot-docs#6381]
Godot 4.0 Docs

With the addition of new annotations like @export_group and @export_subgroup the highlighter needs to be updated to include all new keywords.
It could also be extended with build-in class names that are already in use but not highlighted, like "Button".

(oh and NodePath is listed twice :P)

Example of build-in classes not highlighted:
https://docs.godotengine.org/en/latest/tutorials/scripting/gdscript/gdscript_exports.html

**Comment by Calinou** [comment]
Related to https://github.com/godotengine/godot-docs/issues/4562.

**Comment by mhilbrunner** [comment]
Closed by https://github.com/godotengine/godot-docs/pull/6383
