### ISSUE TITLE
Introduction to the animation features can't find Create button.

### ISSUE THREAD

**Issue by Baa14453** [godotengine/godot-docs#6401]
**Your Godot version:**
3.5.1

**Issue description:**
In the second to last sentence of the Adding a track section it says "As we don't have a track already set up for the transform/location property, Godot asks whether it should set it up for us. Click Create."

There's no picture or indication to where this button is and I can't see it anywhere:
![Untitled](https://user-images.githubusercontent.com/9057997/202901909-de6d3981-4088-4bc0-be03-d8898d1c7e06.png)

**URL to the documentation page:**
https://docs.godotengine.org/en/stable/tutorials/animation/introduction.html#adding-a-track

**Comment by skyace65** [comment]
You skipped over the previous paragraph which tells you "click on the key button"
