### ISSUE TITLE
funcref renamed to Callable

### ISSUE THREAD

**Issue by jomiq** [godotengine/godot-docs#6443]
**Your Godot version:**
v4.0.beta6.official [7f8ecffa5]

**Issue description:**
Documentation code examples mentions `funcref` which is superseded by `Callable`

**URL to the documentation page:**
[Godot interfaces](https://docs.godotengine.org/en/latest/tutorials/best_practices/godot_interfaces.html)
[Scene organizaton](https://docs.godotengine.org/en/latest/tutorials/best_practices/scene_organization.html)

**Comment by raulsntos** [comment]
This has been fixed by:
- https://github.com/godotengine/godot-docs/pull/6542
- https://github.com/godotengine/godot-docs/pull/7371
- https://github.com/godotengine/godot-docs/pull/7505
