### ISSUE TITLE
Missing Documentation Website

### ISSUE THREAD

**Issue by IXLLEGACYIXL** [godotengine/godot-docs#6452]
**Your Godot version:**
GD 4
**Issue description:**
There is a Missing Webpage in the docs
When i click on "See this Page" at the top it throws an "site not found" error

**URL to the documentation page:**
https://docs.godotengine.org/en/latest/development/cpp/unit_testing.html

**Comment by Calinou** [comment]
This is because the page in question does not exist in the stable branch. The feature is not available in 3.x, so the warning isn't relevant here.

We can probably try to do a fetch request on the page URL and see if it exists at all before displaying the link.

**Comment by YuriSizov** [comment]
> We can probably try to do a fetch request on the page URL and see if it exists at all before displaying the link.

We already prefetch it, so I guess doing a `fetch(url, { method: 'HEAD' })` wouldn't be too expensive. Though that may create a jump when the notice is added. I can experiment with it a bit.
