### ISSUE TITLE
Localized class reference is outdated in `master`

### ISSUE THREAD

**Issue by AndreiSchapov** [godotengine/godot-docs#6469]
**Your Godot version:**
4.0 Beta 7

**Issue description:**
My system locale is RU, Godot defaults to documentation URLs specific to that locale, that, despite "latest" being selected, shows deprecated information. So the article on Tilemap Class opens via this URL:
https://docs.godotengine.org/ru/latest/classes/class_tilemap.html
many of the methods are deprecated or have a different sets of parameters. Since the documentation isn't localized into ru it's quite easy to get confused: I couldn't understand why I am sometimes seeing deprecated methods despite always viewing the latest branch.
only after explicitly opening the EN version of the same page I can see the relevant methods and properties of the Tilemap class. This might affect other articles and locales. I think the non-localized articles should by default link to the EN articles of the same documentation branch.

**URL to the documentation page:**
https://docs.godotengine.org/ru/latest/classes/class_tilemap.html
https://docs.godotengine.org/en/latest/classes/class_tilemap.html

**Comment by Calinou** [comment]
Both of your links are to `/latest`, it's just that the localized class reference hasn't been synced yet (as the translation effort hasn't started yet).

**Comment by akien-mga** [comment]
Fixed.
