### ISSUE TITLE
is passthrough mode possible for pico 4 ?

### ISSUE THREAD

**Issue by flobotics** [godotengine/godot-docs#6477]
hi,
is there passthrough available for pico 4 in godot 4 ?  I know in Project->export i can set "passthrough" to "Non", "Optional" or "Required" . But that does not change anything in the app ?

With passthrough support i mean, is AR game development possible ? 

So perhaps pico 4 support is new and it is not possible right now ?

thx

**Comment by Calinou** [comment]
cc @BastiaanOlij

**Comment by flobotics** [comment]
hi @Calinou , i looked at your provided community channels url, but they are , how should i say , "social media style, just say something and fastly forget" . So i know this media, and my request runs down the "chat-line" and its forgotten :)

I think, githubs issue is a nice way, if it gets not overflown.

But i dont see it right now for the godot repositories , or?

Or perhaps create a "dummy-godot-request-githup-repo" where only the issue tracker is used ?

just my simply opinion :) 

 i wanna help not disturb you

**Comment by BastiaanOlij** [comment]
@flobotics we do have a nice and helpful XR community on our discord server so do check in.

I think @Calinou was mostly pointing out that this is the godot-docs repo, not godot itself, though we do frown on support questions as it just pollutes the issue list and makes it harder to find things to fix. We do have the Q/A system specifically for this.

As for your question, No at the moment PICO does not support passthrough as far as I know. Only Meta has implemented passthrough through a vendor extension. I didn't see a passthrough extension in PICOs list. But I'm sure this will change in the distant future.

**Comment by naeu** [comment]
@flobotics A developer made AR work with the Pico 4 a while back, I'm quite sure that there was a video on YouTube with an AR desktop Miku using the Pico 4 shortly after the headset was released. I did a quick search [and found a tweet](https://twitter.com/dwarph/status/1595343188914745345) (25 Nov) suggesting that `PXR_Boundary.EnableSeeThroughManual` will enable passthrough. They have [a demo video](https://twitter.com/stents_dev/status/1592513100531601409) using AR.

I checked the Unity Integration SDK (v211) and it has this static function:
```csharp
/// <summary>
/// Get the camera image of the device and use it as the environmental background. Before calling this function, make sure you have set the clear flags of the camera to solid color and have set the background color of the camera to 0 for the alpha channel.
/// Note: If the app is paused, this function will cease. Therefore, you need to call this function again after the app has been resumed.
/// </summary>
/// <param name="value">Whether to enable SeeThrough: `true`-enable; `false`-do not enable.</param>
public static void EnableSeeThroughManual(bool value)
{
    PXR_Plugin.Boundary.UPxr_SetSeeThroughBackground(value);
}
```

Which calls an imported function
```csharp
[DllImport(PXR_API_DLL, CallingConvention = CallingConvention.Cdecl)]
public static extern int Pxr_SetSeeThroughBackground(bool value);
```

Which is located in `libopenxr_api.so` on the Pico 4
```bash
PICO:/ $ grep -r Pxr_SetSeeThroughBackground product/lib* system/lib* vendor/lib* 2>&1 | grep -v denied                                                                                                   
Binary file system/lib/libopenxr_api.so matches
Binary file system/lib64/libopenxr_api.so matches
Binary file system/lib64/libpxrinitsceneoverlayapi.so matches
```
IDK why `libpxrinitsceneoverlayapi.so` exports it too.
```bash
$ objdump -T libopenxr_api.so | grep Pxr_SetSeeThroughBackground
00010a0d g    DF .text	0000004c  Base        Pxr_SetSeeThroughBackground
$ objdump -T libpxrinitsceneoverlayapi.so | grep Pxr_SetSeeThroughBackground
000000000001a83c g    DF .text	0000000000000078  Base        Pxr_SetSeeThroughBackground
```

In any case, PICO _does_ support passthrough if you call the functions directly, using the Unity Integration SDK as a guide. For Godot you could try making a GDNative/GDExtension script that calls `Pxr_SetSeeThroughBackground`.

**Comment by flobotics** [comment]
hi @naeu ,

thanks for the info, but its only simple pass-through. No vslam info, no "vr-anchors" , etc. possible.

I hope pico will support godot more in future
