### ISSUE TITLE
subresources of Resource's duplicate is ambiguous

### ISSUE THREAD

**Issue by Wuqiqi123** [godotengine/godot-docs#6479]
Godot version:*stable*

**Issue description:**
As documentation below, false subresources means shared between resource copies for efficiency.
But it also says "If subresources is true, this method will only perform a shallow copy." 

**Is this wrong?**
 The right version is "If subresources is ```false```, this method will only perform a shallow copy."?

![image](https://user-images.githubusercontent.com/37368540/206891754-616b9212-bea2-41a9-8da2-f51e60793962.png)

**URL to the documentation page:**
https://docs.godotengine.org/en/stable/classes/class_resource.html

**Comment by RedMser** [comment]
This is already fixed in the Godot 4.0 documentation btw, see https://github.com/godotengine/godot/pull/67072

I don't know if documentation changes will get cherry-picked to 3.x though.

**Comment by akien-mga** [comment]
Fixed by https://github.com/godotengine/godot/pull/86642.
