### ISSUE TITLE
Some keyboard shortcuts not mentioned in editor settings>shortcuts or the documentation itself

### ISSUE THREAD

**Issue by lesleyrs** [godotengine/godot-docs#6494]
**Your Godot version:**
Any

**Issue description:**
I was trying to find how to select upwards in Godot editor and ctrl+shift+up/down wasn't working, then I came across an old gdquest video https://www.youtube.com/watch?v=rMx35lyXCpk and he mentioned that shift+up/down works and it still does after trying. I can't find shift+up/down being mentioned in the text editor settings anywhere?

**URL to the documentation page (if already existing):**
https://docs.godotengine.org/en/stable/tutorials/editor/default_key_mapping.html#text-editor

There's no mention of this shortcut in this page or Godot editor itself, more shortcuts probably missing too. Why?

**Comment by YuriSizov** [comment]
> Your Godot version:
> Any

Can you be more specific than "Any"? Different versions can have different shortcuts. The documentation page needs to be manually updated for each version, and I'm pretty sure it hasn't been done for Godot 4, for example. As for the built-in settings page, it fully reflects the customizable shortcuts. It is possible, that the shortcuts that you're trying to use is not customizable. But to check that we need to know the exact version of the engine that you are using.

**Comment by lesleyrs** [comment]
I wasn't very specific because this is half a question and half a request, I went through this page https://docs.godotengine.org/en/stable/tutorials/editor/default_key_mapping.html#text-editor on several versions including 4, some 3.x, and 2.1 and on the really old ones the page doesn't even exist. The newer ones all don't seem to include this piece of info when searching for "shift".

So I'm wondering where gdquest got this info from in 2017 if not from the source code because it's quite important.

That the editor hides non customizable shortcuts makes sense then, but they should still be mentioned somewhere.

I can say this applies to both newest versions though, 3.5.1 and 4 beta 8
