### ISSUE TITLE
Add JetBrains Rider to "Configuring an IDE"

### ISSUE THREAD

**Issue by quentinguidee** [godotengine/godot-docs#6495]
**Your Godot version:**

N/A

**Issue description:**

Currently, the "Configuring an IDE" section mentions [JetBrains CLion](https://www.jetbrains.com/clion/).

However, CLion is not the right JetBrains IDE to contribute to Godot. The vast majority of files are skipped by the parser because they are too large, and using android's CMakeLists is a bit of a hack that doesn't help CLion. It also parses test files in loop, probably lost in the project.

[JetBrains Rider](https://www.jetbrains.com/rider/) is a much better IDE for working on Godot.
- Rider analyses the project using the `.sln` solution that we can generate by following the steps for Visual Studio Community.
- It understands C++ perfectly.
- It doesn't fail parsing project files.
- It doesn't loop on test files.
- We can run the project by using the play button instead of manual terminal compilation, and without additional configuration, because it understands the .sln solution.

Here's the official comparison between Rider and CLion: https://www.jetbrains.com/products/compare/?product=clion&product=rider.

Therefore, I suggest to add JetBrains Rider to the list. However, it is still useful to keep CLion in the list.

**URL to the documentation page:**

https://docs.godotengine.org/en/stable/development/cpp/configuring_an_ide/index.html

**Comment by Maran23** [comment]
Have you managed to get Jetbrain's Rider to work?
If so, it may make sense if you try to contribute the instructions to the docs.
I will be glad to review and test it. :)

So far I have only managed to get the startup configuration to work, e.g. build with `scons`, start godot and attach the debugger. Autocompletion (IntelliSense) does not work.
I didn't messed around with the found `.sln` files as they didn't worked for me. Will try it again another day.
