### ISSUE TITLE
Add separate system requirements page

### ISSUE THREAD

**Issue by lostminds** [godotengine/godot-docs#6497]
**Your Godot version:**
4.0beta8

**Issue description:**
The minimum requirements needed to run exported games on different platforms is currently placed under the "Platforms" heading in the "List of features" page (not yet updated for 4.0). I think this makes it hard to find for users looking for this information as you can't find it searching for "requirements". And even though I'd consider supporting a platform a feature I wouldn't call a minimum system requirement a feature, so to me it feels like an unexpected place for the information. 

So, as discussed in https://github.com/godotengine/godot-proposals/discussions/5946#discussioncomment-4438455 I'd suggest moving this minimum system requirements list for the different platforms to a new separate page with the name "System requirements" under "About". And then link to this from other pages in the docs (like the list of features or export instructions) where users might be interested in this information. All to help make this information easier to find and help developers in the process of publishing games for multiple platforms.

**URL to the documentation page (if already existing):**
https://github.com/godotengine/godot-docs/blob/master/about/list_of_features.rst#platforms

**Comment by Calinou** [comment]
Relevant discussion: https://github.com/godotengine/godot-proposals/discussions/5946
