### ISSUE TITLE
Howto build godot-4-engine with debug symbols ?

### ISSUE THREAD

**Issue by flobotics** [godotengine/godot-docs#6514]
hi,
i git cloned the godot-4-engine repo and build it with scons. I can run it. 

Now i want to debug the engine with visual-studio-community-2022 , i created a c++ project and set debug exe path to the binary i build with scons. But when i start debugging, it starts godot-4-editor, but then in visual-studio it stops, even the godot-4-editor is still running ?
But i cannot use breakpoints, because it stopped in visual-studio ?

After some searching i found https://github.com/Calinou/godot-debug-builds  and thought, perhaps i am missing debug symbols ? How can i enable them ?

thx for help

**Comment by flobotics** [comment]
i build it with

`scons debug_symbols=true vsproj=true dev_mode=true`

but when i then open the created visual studio solution .sln file, and start debugging, Error couldn´t load project data at path ...

<img width="295" alt="godot-missing-pck" src="https://user-images.githubusercontent.com/11964445/209484502-82563fee-ae2b-424c-a061-e3ecae99d312.png">


What do i wrong ?

**Comment by flobotics** [comment]
i found this https://docs.godotengine.org/en/stable/development/compiling/compiling_for_windows.html#doc-compiling-for-windows

and https://github.com/godotengine/godot/issues/31537

so i tried

`scons vsproj=true tools=yes`

but always when i try to debug in visual studio, godot runs, but in vs it returns program ends with return 0 ? so i cannot debug

**Comment by YuriSizov** [comment]
If you are building Godot 4, you need to refer to the latest documentation, not the stable one. That's for 3.x.

See https://docs.godotengine.org/en/latest/development/compiling/introduction_to_the_buildsystem.html

**Comment by flobotics** [comment]
hi @YuriSizov ,

thanks, but there is no info that helps me with debugging with vs ? or missed i something ?

**Comment by YuriSizov** [comment]
@flobotics The part about Visual Studio didn't change, but other options did. For example, if you want to build an editor executable, you need to do

```
scons target=editor
```

Then if you want to build it with various debugging features enabled, you add `dev_build=yes`, so

```
scons target=editor dev_build=yes
```

This already enables debug symbols. You can still combine it with `vsproj=yes`, as described in the [Visual Studio article](https://docs.godotengine.org/en/latest/development/cpp/configuring_an_ide/visual_studio.html).

```
scons target=editor dev_build=yes vsproj=yes
```

You can also enable debug symbols individually with `debug_symbols=yes` instead of `dev_build=yes`. Note that it's yes/no, not true/false for these options.

**Comment by flobotics** [comment]
@YuriSizov thx for the visual studio article, i added -e --path C:\Users\......\one-of-my-projects-dir\   but, the thing is, i can set breakpoints at the beginning, in main setup functions, but then the GUI where you select the project to load appears, while this i am still in debugger mode, but if i select a project. The program in visual studio returns 0 and ends. No debugging anymore ?

i compiled it with all the settings you named, and more :) , but i got no luck

what do i wrong ?

**Comment by YuriSizov** [comment]
@flobotics The project manager and the editor are two different processes. If you launch into the project manager first, you won't be able to debug the editor after selecting the project.

To launch directly into the editor with the project open you indeed need to use `-e` and `--path`. The path must point to a directory where the `project.godot` is located. If you launch into the project manager still, despite providing the path, make sure it's correct and that you do have a Godot project in that directory.

**Comment by flobotics** [comment]
@YuriSizov hmmm, i use -e --path C:\....      the path is correct, but it always starts with the project manager. When i there, choose the project, which path i used for --path   the program in vs-debugger ends, and the editor starts, no debugging anymore 

- path is correct
- there is a project in that path

?

**Comment by flobotics** [comment]
i installed visual studio community 2019 with c++  and now it works so far

@YuriSizov thanks for your help

**Comment by YuriSizov** [comment]
That shouldn't be a problem, but I'm glad it works for you now.
