### ISSUE TITLE
Outdated Scene Tree mono documentation

### ISSUE THREAD

**Issue by MagmaGuy** [godotengine/godot-docs#6519]
**Your Godot version:**
4.0 Beta 10

**Issue description:**
Scene tree documentation - C# section uses what is probably the old method method, using `GetTree().ChangeScene(...)` when it seems as though it ought to be using the new `GetTree().ChangeSceneToFile(...)`.

Likewise, the entry after that uses `GetTree().ChangeSceneTo(...)` when it should be using `GetTree().ChangeSceneToPacked(...)`.

**URL to the documentation page:**
https://docs.godotengine.org/en/latest/tutorials/scripting/scene_tree.html#changing-current-scene

**Comment by raulsntos** [comment]
You are right. For context this was updated in https://github.com/godotengine/godot-docs/pull/6175 for GDScript, the C# examples are outdated.
