### ISSUE TITLE
"Organization of the documentation" section has wrong navigable links

### ISSUE THREAD

**Issue by thadguidry** [godotengine/godot-docs#6533]
**Your Godot version:**  latest

**Issue description:** _Organization of the documentation_ paragraphs have wrong navigable links, such as [Engine Development](https://docs.godotengine.org/en/latest/index.html#sec-devel)

**URL to the documentation page:**  https://docs.godotengine.org/en/latest/about/introduction.html#organization-of-the-documentation

If you know how to fix the issue you are reporting please
consider opening a pull request. We provide a tutorial on
using git here: https://docs.godotengine.org/en/stable/community/contributing/pr_workflow.html,
writing documentation at https://docs.godotengine.org/en/stable/community/contributing/docs_writing_guidelines.html
and contributing to the class reference here: https://docs.godotengine.org/en/stable/community/contributing/updating_the_class_reference.html

**Comment by thadguidry** [comment]
@YuriSizov Possibly an easy fix for you?

**Comment by YuriSizov** [comment]
It's a regression from https://github.com/godotengine/godot-docs/pull/6510. I guess we should just remove the links and format the names as bold instead.
