### ISSUE TITLE
Timer's time_left and start() description documentation error or confusion

### ISSUE THREAD

**Issue by Mperonen** [godotengine/godot-docs#6537]
**Your Godot version:**
Godot Engine v4.0.beta1.official [20d667284]

**Issue description:**
Documentation for time_left value states: "Note: You cannot set this value. To change the timer's remaining time, use [start]"

However start() function does not change or set timer's remaining time, it instead sets a new wait_time value as described in start() function's documentation.

**URL to the documentation page:**
https://docs.godotengine.org/en/latest/classes/class_timer.html#class-timer-property-time-left

**Comment by YuriSizov** [comment]
The documentation continues with

> This also resets the remaining time to [wait_time](https://docs.godotengine.org/en/latest/classes/class_timer.html#class-timer-property-wait-time).

You cannot change the remaining time without changing wait time.
