### ISSUE TITLE
Error in Tutorial "Your first 2D game", "coding the player"

### ISSUE THREAD

**Issue by jcreek** [godotengine/godot-docs#6539]
**Your Godot version:**
4.0.beta10.mono

**Issue description:**
Following the guide exactly with C# selected gives a `_Process` function of:

```c#
public override void _Process(double delta)
	{
		var velocity = Vector2.Zero; // The player's movement vector.

		if (Input.IsActionPressed("move_right"))
		{
			velocity.x += 1;
		}

		if (Input.IsActionPressed("move_left"))
		{
			velocity.x -= 1;
		}

		if (Input.IsActionPressed("move_down"))
		{
			velocity.y += 1;
		}

		if (Input.IsActionPressed("move_up"))
		{
			velocity.y -= 1;
		}

		var animatedSprite2D = GetNode<AnimatedSprite2D>("AnimatedSprite2D");

		if (velocity.Length() > 0)
		{
			velocity = velocity.Normalized() * Speed;
			animatedSprite2D.Play();
		}
		else
		{
			animatedSprite2D.Stop();
		}
		
		Position += velocity * delta;
		Position = new Vector2(
			x: Mathf.Clamp(Position.x, 0, ScreenSize.x),
			y: Mathf.Clamp(Position.y, 0, ScreenSize.y)
		);
	}
```

This throws an error on the line `Position += velocity * delta;` as `CS0019: Operator '*' cannot be applied to operands of type 'Vector2' and 'double'` - given I've followed the tutorial exactly this seems likely to be either an issue with the documentation or with the beta of Godot 4.0, I'm an experienced C# dev but have never done game development before, so it's also possible I've misunderstood something, but after double-checking I don't think so. 

**URL to the documentation page:**
https://docs.godotengine.org/en/latest/getting_started/first_2d_game/03.coding_the_player.html

**Comment by raulsntos** [comment]
The example is outdated, the `delta` parameter is a `double` in 4.0, in order to multiply a `Vector2` it needs to be converted to `float` first. There are likely many other outdated examples in the documentation.

This should work:

```csharp
Position += velocity * (float)delta;
```

**Comment by jcreek** [comment]
Thanks @raulsntos - I am delighted to confirm that that fixes it! Is there an established process here for creating PRs to solve issues? I'm happy to create the relevant PRs, and raise further issues as I follow the tutorial through :)

**Comment by raulsntos** [comment]
Take a look at the [_Contributing_](https://github.com/godotengine/godot-docs/blob/master/README.md#contributing) section of the README.md. More specifically the [_Contributing to the online manual_](https://docs.godotengine.org/en/latest/community/contributing/contributing_to_the_documentation.html) page in the documentation.

Let me know if you run into any issues. You can also reach me and other contributors on [RocketChat](https://chat.godotengine.org/).
