### ISSUE TITLE
Error in Tutorial "Your first 2D game", "the main game scene" 

### ISSUE THREAD

**Issue by jcreek** [godotengine/godot-docs#6549]
**Your Godot version:**
4.0.beta10.mono

**Issue description:**
Following the tutorial for C#, the function `OnMobTimerTimeout` has a line `var mob = MobScene.Instance<Mob>();`, which throws an error `'PackedScene' does not contain a definition for 'Instance' and no accessible extension method 'Instance' accepting a first argument of type 'PackedScene' could be found (are you missing a using directive or an assembly reference?)`

**URL to the documentation page:**
https://docs.godotengine.org/en/latest/getting_started/first_2d_game/05.the_main_game_scene.html

**Comment by piyushmulatkar** [comment]
I am also getting a relatively same error in gdscript

**Comment by raulsntos** [comment]
The `Instance` method was renamed to `Instantiate` in 4.0.

**Comment by femmiennine** [comment]
Hi, I encountered the same issue. Has this been fixed? And what is the solution? 

> **Your Godot version:** 4.0.beta10.mono
> 
> **Issue description:** Following the tutorial for C#, the function `OnMobTimerTimeout` has a line `var mob = MobScene.Instance<Mob>();`, which throws an error `'PackedScene' does not contain a definition for 'Instance' and no accessible extension method 'Instance' accepting a first argument of type 'PackedScene' could be found (are you missing a using directive or an assembly reference?)`
> 
> **URL to the documentation page:** https://docs.godotengine.org/en/latest/getting_started/first_2d_game/05.the_main_game_scene.html

**Comment by YuriSizov** [comment]
@femmiennine It's the same method, it's just been renamed. The linked tutorial should have correct code snippets right now. Make sure your class is marked as partial.
