### ISSUE TITLE
Outdated example project

### ISSUE THREAD

**Issue by piyushmulatkar** [godotengine/godot-docs#6564]
**Your Godot version:Latest(4.x)**

**Issue description:The instance project (instace.zip) is made in godot 3.0 where it should be made in latest version.**

**URL to the documentation page:https://github.com/godotengine/godot-docs/blob/master/getting_started/step_by_step/files/**

**Comment by FuzzyHerbivore** [comment]
Hey! So, I downloaded the zip and fixed the project, seems to work fine now in 4.0b10.
I'm a bit of a noob though, so not sure what to do now. Especially since it's a zip file. Should I fork from main and PR with a new zip?

**Comment by FuzzyHerbivore** [comment]
#6583

**Comment by skyace65** [comment]
https://github.com/godotengine/godot-docs-project-starters/pull/3
