### ISSUE TITLE
Default easings/transitions in SceneTreeTween

### ISSUE THREAD

**Issue by chucklepie** [godotengine/godot-docs#6567]
**Your Godot version:**
3.5.1

**Issue description:**
It's probably obvious to most but it would be nice for the Scene Tree Tween to explicitly state default values used when you start using it with no other method calls, e.g. if you call tween_property and tween_method, is the default transition linear with ease in/out?

This would avoid people doing this on every tween creation, 'just in case'
mytween.tween_property(...).set_trans(Tween.TRANS_LINEAR).set_ease(Tween.EASE_IN_OUT)

**URL to the documentation page (if already existing):**
https://docs.godotengine.org/en/stable/classes/class_scenetreetween.html

**Comment by sarice8** [comment]
I just hunted through the source code to find tween.h, to answer this question too.   It seems important since the default settings are an important part of the new api.

**Comment by Calinou** [comment]
> I just hunted through the source code to find tween.h, to answer this question too. It seems important since the default settings are an important part of the new api.

[Feel free to open a pull request on godotengine/godot for this](https://docs.godotengine.org/en/latest/contributing/documentation/updating_the_class_reference.html) :slightly_smiling_face:
