### ISSUE TITLE
Mistake on generic GetNodeOrNull() description.

### ISSUE THREAD

**Issue by guilleatm** [godotengine/godot-docs#6577]
**Your Godot version:** v4.0.beta10.mono.official.d0398f62f

**Issue description:** little mistake in description of `T Node.GetNodeOrNull<T>(NodePath path) where T : class` method, no error is logged.

**URL to the documentation page:** I found the error in the help while coding, I don't know where it is in the documentation, the description of the non generic method is okay.

This is my first issue :)

**Comment by raulsntos** [comment]
The documentation for C# is included on the source code, for `Node.GetNodeOrNull` you can find it in [NodeExtensions.cs](https://github.com/godotengine/godot/blob/91713ced81792b10fdc9367b7f355738e5d52777/modules/mono/glue/GodotSharp/GodotSharp/Core/Extensions/NodeExtensions.cs). Pull requests to update it are welcomed :slightly_smiling_face:.

**Comment by guilleatm** [comment]
I made a pull request: https://github.com/godotengine/godot/pull/71168
