### ISSUE TITLE
"Instancing" demo scene crashes when trying to edit the ball properties

### ISSUE THREAD

**Issue by bunnynerd** [godotengine/godot-docs#6588]
**Your Godot version:** tested on v3.4.4.stable.official [419e713a2] and v3.5.1.stable.official [6fed1ffa3]

**Issue description:** When editing the ball.tcsn scene in the Instancing project included on the page, Godot will crash when you save the change to its bounce property. When you reopen the project it gives the following error:

![image](https://user-images.githubusercontent.com/105619424/211971002-829a0198-9935-4cad-9bd9-5488f7193a26.png)

**URL to the documentation page:** https://docs.godotengine.org/en/stable/getting_started/step_by_step/instancing.html

**Comment by skyace65** [comment]
Issue is no longer happening with the latest version of Godot (4.2) or that project (4.)
