### ISSUE TITLE
a place for general performance tips

### ISSUE THREAD

**Issue by vsrinu26f** [godotengine/godot-docs#66]
guide how to achieve common tasks (eg: how to make character customizabe. how to make camera follow ball. how to use two cameras/viewports for left and right eye (or see zoomed thru a scope of a gun).

**Comment by MoraleMuffin5** [comment]
Those are not performance tips, those should just be regular tutorials.

**Comment by pwab** [comment]
This is something for the [Tutorials section](https://godot.readthedocs.io/en/latest/community/tutorials/index.html) and I think the title is a bit misleading here.
The suggested tutorial topics are good points but maybe this should be tracked in a kind of "_What tutorials you want to see?_"-issue.

**Comment by mhilbrunner** [comment]
Closing this. Created new issues for each specific issue.
