### ISSUE TITLE
Keyboard shortcuts are unreadable in dark theme

### ISSUE THREAD

**Issue by paulloz** [godotengine/godot-docs#6607]
When using the dark theme, keyboard shortcuts are basically written white on white and are therefore unreadable:
![image](https://user-images.githubusercontent.com/437025/212469156-67ca3e36-b092-46a6-913d-9fddc4a5e51b.png)
![image](https://user-images.githubusercontent.com/437025/212469165-7067ded6-b706-42d6-825a-110ce246a583.png)

Screenshots were taken on Windows, there is no difference between Firefox and Chrome.

**Comment by YuriSizov** [comment]
Probably a regression from the recent base theme update. I recall it changing something about kbds. We should have all the necessary styles in place, so probably just need to adjust the selectors.
