### ISSUE TITLE
Mono/C# editor config Docs for 4.x incorrect re: Mono

### ISSUE THREAD

**Issue by thoraxe** [godotengine/godot-docs#6610]
**Your Godot version:**
4.0-beta12

**Issue description:**
The editor settings appear to be incorrect.

> In Godot's Editor → Editor Settings menu:
> Set Mono -> Editor -> External Editor to Visual Studio.
> Set Mono -> Builds -> Build Tool to dotnet CLI.

There is no "build tool" settings in Mono or anywhere in the Editor Settings menu. Searching for "build" returns zero results. Searching for "dotnet" returns zero results. 

![Screenshot from 2023-01-14 10-15-34](https://user-images.githubusercontent.com/94413/212479165-f8ecb4ac-56bc-40d6-b230-4248af5ea43d.png)

**URL to the documentation page:**
https://docs.godotengine.org/en/latest/tutorials/scripting/c_sharp/c_sharp_basics.html

**Comment by raulsntos** [comment]
The documentation is outdated. There is no _Build Tool_ setting in 4.0, we always use the _dotnet CLI_. Pull requests to update it are welcomed :slightly_smiling_face:.
