### ISSUE TITLE
Broken Link

### ISSUE THREAD

**Issue by AntonioNoack** [godotengine/godot-docs#6616]
**Your Godot version:**
-

**Issue description:**
Hi, the link [creating modules in C++ is well documented](https://godot.readthedocs.io/en/latest/reference/custom_modules_in_c++.html) on https://godotengine.org/article/godot-getting-more-languages is broken, as it redirects to a 404 page.

**URL to the documentation page:**
https://godotengine.org/article/godot-getting-more-languages

If you know how to fix the issue you are reporting please
consider opening a pull request. We provide a tutorial on
using git here: https://docs.godotengine.org/en/stable/community/contributing/pr_workflow.html,
writing documentation at https://docs.godotengine.org/en/stable/community/contributing/docs_writing_guidelines.html
and contributing to the class reference here: https://docs.godotengine.org/en/stable/community/contributing/updating_the_class_reference.html

**Comment by YuriSizov** [comment]
That's a very old blogpost, links in such posts ought to be outdated at some point. As you can see, it even predates us having a domain name for the documentation.

We can try updating the links, but there may simply be no relevant document anymore half a decade later.

In the meantime, if you want the latest version of this doc, it's here: https://docs.godotengine.org/en/latest/contributing/development/core_and_modules/custom_modules_in_cpp.html
