### ISSUE TITLE
Instructions to find CI artifacts in "Testing pull requests" are outdated

### ISSUE THREAD

**Issue by akien-mga** [godotengine/godot-docs#6625]
**Issue description:**
The instructions we have to download CI artifacts in the "Testing pull requests" page are outdated, as the GitHub Actions interface changed a while ago.

We need to update the screenshots and text to make sure users can find artifacts, as it's far from obvious, even more so in the current interface.

**URL to the documentation page:**
https://docs.godotengine.org/en/latest/contributing/workflow/testing_pull_requests.html

**Comment by Calinou** [comment]
We could recommend using nightly.link for all users (even those with a GitHub account), as its UX is likely better (and won't be affected by GitHub UI changes).

**Comment by tetrapod00** [comment]
Seemingly fixed in https://github.com/godotengine/godot-docs/pull/7702.
