### ISSUE TITLE
Broken link on Contributing page - 404

### ISSUE THREAD

**Issue by coppolaemilio** [godotengine/godot-docs#6639]
**Issue description:**
When you try to follow the link "Edit on Github" of this page it redirects to a 404 page (https://github.com/godotengine/godot-docs/blob/master/community/contributing/index.rst)

![image](https://user-images.githubusercontent.com/2206700/213692325-7544e30c-4f57-4fba-97de-d74afc0850d9.png)

**URL to the documentation page:**

https://docs.godotengine.org/en/stable/community/contributing/index.html

**Comment by YuriSizov** [comment]
Technically a duplicate of

- https://github.com/godotengine/godot-docs/issues/4499
- https://github.com/godotengine/godot-docs/issues/5435
- https://github.com/godotengine/godot-docs/issues/4381

We do have some control over the template responsible for this, though. Maybe it is solvable.

**Comment by skyace65** [comment]
Looks like this was fixed at some point.
