### ISSUE TITLE
FAQ: Confusing wording in GDScript usage examples

### ISSUE THREAD

**Issue by allenwp** [godotengine/godot-docs#6651]
**Your Godot version:**
documentation: latest

**Issue description:**
In the FAQ the following sentence is somewhat confusing:
> There are several reasons to use GDScript--especially when you are prototyping, in alpha/beta stages of your project, or are **not** creating the next AAA title--but the most salient reason is the overall reduction of complexity.

The bolded "**not**" in the above text appears out of place and suggests to the reader that it may be a typo. To make this wording more clear, I would suggest revising this text to read:

> especially when you are prototyping, in alpha/beta stages of your project, **or working towards anything other than the next AAA title**

Alternatively, if this is actually a typo, the correct text should read:

> especially when you are prototyping, in alpha/beta stages of your project, **or creating the next AAA title**

Which is the intended meaning of this line of the FAQ? I am happy to open a pull request with the fix, but I wanted to confirm the intent of the sentence before making the change.

**URL to the documentation page:**
https://docs.godotengine.org/en/latest/about/faq.html#what-is-gdscript-and-why-should-i-use-it

**Comment by BWPanda** [comment]
I suspect the *not* is correct, just not written in the best English.

I understand this sentence to mean that GDScript is best used for small-to-medium projects (i.e. prototypes, alpha/beta stages, non-AAA titles). It doesn't make sense to me that this is saying AAA titles should use GDScript, considering the other examples given.

**Comment by AThousandShips** [comment]
I'd say it's clear English, only chance I'd make is to use "aren't" instead of "are not"
