### ISSUE TITLE
Code from "3D gizmo plugins" tutorial does not work.

### ISSUE THREAD

**Issue by winston-yallow** [godotengine/godot-docs#6656]
**Your Godot version:**
v4.0.beta14.official [28a24639c]

**Issue description:**
The code in the tutorial has the following errors:

```
Invalid call. Nonexistent function 'get_node3d' in base 'EditorNode3DGizmo'.
```
```
Invalid call to function 'add_handles' in base 'EditorNode3DGizmo'. Expected 5 arguments.
```

**URL to the documentation page:**
https://docs.godotengine.org/en/latest/tutorials/plugins/editor/3d_gizmos.html

**Comment by YuriSizov** [comment]
I think this tutorial needs to be rewritten for 4.0, which introduces new subgizmos, which seem to be much more pleasant to work with.

**Comment by winston-yallow** [comment]
Yeah, but that's a different topic. This was just fixing it to have a minimal working state again. The tutorial over all could use some love and more explanations, but I think that would be better for a separate issue/PR.

Related enhancement issue to make the gizmo tutorial more complete #2713

**Comment by YuriSizov** [comment]
Yep, I agree. Just thought I'd put the idea on the radar for anyone willing :)
