### ISSUE TITLE
weblate "information for translators" link is broke 

### ISSUE THREAD

**Issue by mr-c** [godotengine/godot-docs#6664]
https://hosted.weblate.org/projects/godot-engine/#information links to https://docs.godotengine.org/en/latest/community/contributing/editor_and_docs_localization.html but that link is broken

Maybe a redirect to https://docs.godotengine.org/en/latest/contributing/documentation/editor_and_docs_localization.html#doc-editor-and-docs-localization would fix that?

Perhaps this sphinx extension will help https://pypi.org/project/sphinxext-rediraffe/

**Comment by YuriSizov** [comment]
Indeed the link should be https://docs.godotengine.org/en/latest/contributing/documentation/editor_and_docs_localization.html. RTD has a system for redirects, we just haven't added the new ones to it yet.

cc @akien-mga @timothyqiu about updating the description on Weblate.

**Comment by timothyqiu** [comment]
I updated that description. The link was probably not updated after the last directory restructuring.
