### ISSUE TITLE
Possibly outdated animation code in "Dodge the Creeps 2D"

### ISSUE THREAD

**Issue by hmturnbull** [godotengine/godot-docs#6694]
**Your Godot version:**

**Issue description:**
In the *Creating the Enemy* section of *Dodge the Creeps 2D*, the Enemy script section currently says to start the animation by directly setting the `playing` property like this:
```
func _ready():
    $AnimatedSprite2D.playing = true
    var mob_types = $AnimatedSprite2D.frames.get_animation_names()
    $AnimatedSprite2D.animation = mob_types[randi() % mob_types.size()]
```

Since the `playing` property isn't even in the class documentation (so far as I could tell), I'm wondering if it would make more sense to change it to something like the following:
```
func _ready():
	var mob_types = $AnimatedSprite2D.frames.get_animation_names()
	$AnimatedSprite2D.animation = mob_types[randi() % mob_types.size()]
	$AnimatedSprite2D.play()
```

However, I think the indents that currently consist of four spaces should probably be replaced with tabs to match how modern GDScript is written.

**URL to the documentation page:**
https://docs.godotengine.org/en/latest/getting_started/first_2d_game/04.creating_the_enemy.html#

**Comment by skyace65** [comment]
Closing this issue. Fixed by #6699.
