### ISSUE TITLE
How to use general/commonly used additional capabilites of a particular platform:

### ISSUE THREAD

**Issue by vsrinu26f** [godotengine/godot-docs#67]
say android accelerometer, camera, swipes gestures etc..

**Comment by NathanLovato** [comment]
It's too broad of an issue, and a bit old. Closing for now. Please add specific issues and outline the problem of the current docs to help contributors know what they should work on. E.g.:
- List unique features on Android
- Write a step-by-step tutorial for touch gestures on mobile
- etc.
