### ISSUE TITLE
Stable "Real Time Navigation" uses node names with "3D" suffix from 4.x

### ISSUE THREAD

**Issue by winston-yallow** [godotengine/godot-docs#6711]
**Your Godot version:**
Godot 3.5.1

**Issue description:**
Docs mention `NavigationAgent3D` and `NavigationObstacle3D` which are the new names in Godot 4. The "3D" suffix should be dropped.

**URL to the documentation page:**
https://docs.godotengine.org/en/stable/tutorials/navigation/real_time_navigation_3d.html

**Comment by winston-yallow** [comment]
I mean, it's a simple fix, but which branch specifically would I target for a PR? `stable` or `3.5`?

**Comment by smix8** [comment]
It is the same with NavigationObstacle(3D) so you might want to cover that as well in your pr.

**Comment by winston-yallow** [comment]
Good catch, I updated issue and PR

**Comment by YuriSizov** [comment]
Fixed by https://github.com/godotengine/godot-docs/pull/6718.
