### ISSUE TITLE
Include full GDScript to GLSL type mapping in Godot Shading Langauge Reference

### ISSUE THREAD

**Issue by KLee1248** [godotengine/godot-docs#6723]
**Your Godot version:** 
4.0beta15 (although the missing documentation is also present in stable)

**Issue description:**
In the Shading Language reference (shading_language.rst) there is a list of all of the types that are supported when using the shader language. There is a corresponding list later in the documentation of how some of the types match to GDScript, but this is incomplete, especially for types where it's unclear what the corresponding type should be (e.g. `bvec[2,3,4]` should be an `int` or `mat4` should be a `Projection`).

This is very frustrating as a user, because the `set_shader_parameter` Variant type needs to be exactly correct (e.g. `Array[bool]` can't be passed for `bvec4`) and there's no way to know what it should be just looking at the documentation (that I know of).

It appears that the actual conversion happens here: https://github.com/godotengine/godot/blob/0a9e6e478e3183d7bf3c5cb895c706bc6275d3ea/drivers/gles3/storage/material_storage.cpp#L1884

and that the Variant types are described as hints here: https://github.com/godotengine/godot/blob/c24fa7906154c58f891ced5ba7172107f180069d/editor/shader_globals_editor.cpp#L136

Could we expand the table to include all of the types (and some descriptions of how the conversion works where it's not obvious)?

Also, once we create this table, can we link it from the documentation for `set_shader_parameter` so that it's easy to find for people struggling their way through learning shaders (like me!).

**URL to the documentation page (if already existing):**
https://docs.godotengine.org/en/latest/tutorials/shaders/shader_reference/shading_language.html
https://docs.godotengine.org/en/latest/classes/class_shadermaterial.html

**Comment by Calinou** [comment]
Feel free to open a pull request for this :slightly_smiling_face:
