### ISSUE TITLE
Signal.get_connections() returns arrays of dictionary

### ISSUE THREAD

**Issue by asdfer-1234** [godotengine/godot-docs#6728]
**Your Godot version:**
4.0 beta 12

**Issue description:**
On the documentation, the get_connections() function on class_signal.rst says it returns an array of callables, but the function returns an array of dictionary with two keys: signal and callable

**URL to the documentation page:**
https://docs.godotengine.org/en/latest/classes/class_signal.html#class-signal-method-get-connections

**Comment by YuriSizov** [comment]
I'm not sure it's a documentation problem. It's probably an unintended side-effect from some changes.

**Comment by KoBeWi** [comment]
The dictionary has 3 keys, with the third being connection flags.
