### ISSUE TITLE
Ambiguous explanation on Viewport and ViewportContainer

### ISSUE THREAD

**Issue by OppositeNor** [godotengine/godot-docs#6743]
**Your Godot version:**
Godot 3.5 mono
**Issue description:**
In the documentiation of Viewport, in the description it described: "If a viewport is a child of a ViewportContianer, it will automatically take up its size, otherwise it must be set manually." which is kind of ambiguous of saying "who will automatically take up who's size," which can mean Viewport take up ViewportContainer's size or the other way. Maybe specify what the "it"s are referring to will be easier to understand?
**URL to the documentation page (if already existing):**
https://docs.godotengine.org/en/3.5/classes/class_viewport.html#class-viewport
https://docs.godotengine.org/en/3.5/classes/class_viewportcontainer.html#class-viewportcontainer

**Comment by clayjohn** [comment]
The Viewport will automatically take on the ViewportContainers size. Or put differently. The ViewportContainer will automatically resize the Viewport
