### ISSUE TITLE
Incorrect screen-reading shader documentation

### ISSUE THREAD

**Issue by lostminds** [godotengine/godot-docs#6758]
**Your Godot version:**
4.0rc1

**Issue description:**
The current description on how to do screen reading shaders describe using the old SCREEN_TEXTURE, DEPTH_TEXTURE etc but these have been removed in favor of a new uniform hint in 4.0 as described in this pull request: https://github.com/godotengine/godot/pull/70967

It would also be a good addition on this page to mention how you can access these textures in Visual Shaders

**URL to the documentation page:**
https://docs.godotengine.org/en/latest/tutorials/shaders/screen-reading_shaders.html

**Comment by clayjohn** [comment]
Will be fixed by https://github.com/godotengine/godot-docs/pull/6559
