### ISSUE TITLE
Outdated Docs for Godot 4 - Your First 2D Game

### ISSUE THREAD

**Issue by andrehgdias** [godotengine/godot-docs#6767]
**Your Godot version:**
v4.0.beta10.official [d0398f62f]

**Issue description:**
I wanted to know if there are any plans to update the docs while version 4 is still in beta.
I'm learning Godot now and going through the docs, tutorials and demos we notice a lot of outdated code.
Some issues have already been highlighted at previous issues and PRs, such as #6744 #6763

I'm going through the 2D path so I could update it along the way. Right now I'm reading [Your First 2D Game](https://docs.godotengine.org/en/stable/getting_started/first_2d_game/index.html#your-first-2d-game).

**URL to the documentation page (if already existing):**
https://docs.godotengine.org/en/stable/getting_started/first_2d_game/03.coding_the_player.html

The about link is the 2D version of Dodge the Creeps! tutorial which has some outdated code, for example, now some node has a 2D suffix like AnimatedSprite2D but in the docs it's just AnimatedSprite.

**Comment by YuriSizov** [comment]
> I wanted to know if there are any plans to update the docs while version 4 is still in beta.

Godot 4 is no longer in beta, it's in the release candidate stage. And the docs are being constantly updated, as long as there are contributors who report issues and provide PRs. This is open source, we rely on each other here :)

**Comment by andrehgdias** [comment]
So if I encounter something that needs fixing, I just need to open a issue and push a PR?

**Comment by YuriSizov** [comment]
Sure, feel free to do both, or either.

**Comment by Piralein** [comment]
By the way, you are linking to the stable version of the documentation, which is for the 3.x version of godot.
Make sure you read the [latest](https://docs.godotengine.org/en/latest/getting_started/first_2d_game/index.html) version of the docs.
You can change/see the version beneath the navigation menu.

**Comment by andrehgdias** [comment]
> By the way, you are linking to the stable version of the documentation, which is for the 3.x version of godot. Make sure you read the [latest](https://docs.godotengine.org/en/latest/getting_started/first_2d_game/index.html) version of the docs. You can change/see the version beneath the navigation menu.

yeah I noticed that soon after, I'll be closing this issue
but it would be nice to select the version of the docs at the text on top of the sidebar, right now it only displays the version and you have to change it down at the footer

**Comment by Calinou** [comment]
> but it would be nice to select the version of the docs at the text on top of the sidebar, right now it only displays the version and you have to change it down at the footer

I doubt the version selector's location can be changed easily, since we use Read the Docs' default theme (albeit with custom CSS and JavaScript).
