### ISSUE TITLE
Permanent URL for documentation page revisions

### ISSUE THREAD

**Issue by FeatherAntennae** [godotengine/godot-docs#6791]
**Your Godot version:**
Irrelevant.

**Issue description:**
- I need to reference the Godot documentation for a report and a thesis.
- I need the reference to reflect the same content in the future, even if the content changed or was removed.
- I cannot bundle all the required references as offline dumps or screen captures in my report and thesis. 
- I currently use the revision number in the footer to find and link to the specific commit in GitHub directly as a workaround.
- The workaround isn't very friendly to readers which aren't tech-savvy.

**Proposed change:**
- Click the revision number in the footer to get a permanent URL to this revision of the documentation page.  
  Could look something like : `https://docs.godotengine.org/en/35ca085e/tutorials/inputs/inputevent.html`

I do not know if it's possible or realistic to keep links to a specific revision of each page of the documentation. It might require generating the page on demand, without links and with a warning to avoid the need to keep millions of pages that will almost never be accessed.

Because of this, I also suggest an alternative.

**Perhaps more realistic alternative:**
- Add a way to view a page revision's history by date and revision number directly in the documentation.  
  Could be generated using the commit messages?

It is a pretty niche use case, and an inevitable part of referencing pages on the internet. Feel free to close this issue if none of the suggestions are realistic. It would at least leave traces of the decision behind if someone else eventually seeks the same thing. :stuck_out_tongue: 

**URL to the documentation page (if already existing):**
Irrelevant.

**Comment by YuriSizov** [comment]
I don't think this is feasible with ReadTheDocs.

**Comment by mhilbrunner** [comment]
We currently don't plan on hosting online docs for each revision. We aren't even hosting online docs for each patch release, only major and minor versions get their own docs.

The Git commits contain the source files the docs are built from (ie. the class XML files, or the docs RST files) and can be referenced online, or mechanisms like the Wayback machine can be used as suggested.
