### ISSUE TITLE
Exporting for Android, NDK version with command line tool not match

### ISSUE THREAD

**Issue by CsloudX** [godotengine/godot-docs#6829]
**Your Godot version:**
Godot4.0

**Issue description:**
![image](https://user-images.githubusercontent.com/35988767/221462163-148b5073-7463-49fa-b0ef-59b08a5c02dc.png)

**URL to the documentation page:**

If you know how to fix the issue you are reporting please
consider opening a pull request. We provide a tutorial on
using git here: https://docs.godotengine.org/en/stable/community/contributing/pr_workflow.html,
writing documentation at https://docs.godotengine.org/en/stable/community/contributing/docs_writing_guidelines.html
and contributing to the class reference here: https://docs.godotengine.org/en/stable/community/contributing/updating_the_class_reference.html

**Comment by skyace65** [comment]
Fixed by #6996. Closing this issue.
