### ISSUE TITLE
`_input_event` does not travel in reverse depth-first order as documented

### ISSUE THREAD

**Issue by ShatReal** [godotengine/godot-docs#6843]
**Your Godot version:**
4.0 rc6 and 3.5.1

**Issue description:**
On both versions of Godot, I made several Area2Ds with a script that would print its name when it receives a click event. They printed in a seemingly random order and not in tree order, and the order wasn't the same when trying again. All Area2Ds were the children of the same node.

Also:

> If this ray hits an object, it will call the [CollisionObject._input_event()](https://docs.godotengine.org/en/stable/classes/class_collisionobject.html#class-collisionobject-method-input-event) function in the relevant physics object (bodies receive this callback by default, but areas do not. This can be configured through [Area](https://docs.godotengine.org/en/stable/classes/class_area.html#class-area) properties).

When I instanced the Area2D the input pickable property was set to true by default. I think this might be wrong.

Also, on the latest docs:
> When sending events to its child and descencand nodes

Does that mean "descended"?

**URL to the documentation page:**
https://docs.godotengine.org/en/latest/tutorials/inputs/inputevent.html
https://docs.godotengine.org/en/stable/tutorials/inputs/inputevent.html

**Comment by mhilbrunner** [comment]
Most of these were fixed now, the last issue mentioned by the just merged https://github.com/godotengine/godot-docs/pull/8607. If the engine behaviour still seems unexpected, that may be worth opening an issue on the main repository. Thanks for reporting!
