### ISSUE TITLE
Add '3.x' or 'lts' version for Godot 3 documentation

### ISSUE THREAD

**Issue by SysError99** [godotengine/godot-docs#6850]
**Your Godot version:**
3.5.1
**Issue description:**
Documentation is now reflecting to 4.0 as stable version, renders search engine method for finding the previously stable branch inefficient. We should at least have substitute branch for all Godot 3 versions.
**URL to the documentation page (if already existing):**

**Comment by clayjohn** [comment]
We do https://docs.godotengine.org/en/3.5/

You can select the version in the bottom left hand corner

**Comment by SysError99** [comment]
> We do https://docs.godotengine.org/en/3.5/
> 
> You can select the version in the bottom left hand corner

That's not what I meant, I know that 3.5 exists, but '3.x' or any of future versions of Godot doesn't.

**Comment by clayjohn** [comment]
I see what you mean now. You want something like "stable-3" that will automatically update to the most recent stable 3.x branch. I'm not sure how helpful that would be at this point given that 3.6 is planned to be the last 3.x release
