### ISSUE TITLE
Godot .Net Linux installations not working like in the docs

### ISSUE THREAD

**Issue by axvemi** [godotengine/godot-docs#6859]
**Your Godot version:**
4.0
**Issue description:**
I'm following the install explanation documented on: https://docs.godotengine.org/en/stable/about/faq.html#linux
It works for the GDScript version, but not for the .Net version.
It doesn't work neither the command, nor the shortcut
**URL to the documentation page:**
https://docs.godotengine.org/en/stable/about/faq.html#linux

If you know how to fix the issue you are reporting please
consider opening a pull request. We provide a tutorial on
using git here: https://docs.godotengine.org/en/stable/community/contributing/pr_workflow.html,
writing documentation at https://docs.godotengine.org/en/stable/community/contributing/docs_writing_guidelines.html
and contributing to the class reference here: https://docs.godotengine.org/en/stable/community/contributing/updating_the_class_reference.html

**Comment by YuriSizov** [comment]
Please elaborate what doesn't work? What are you attempting to do and how do you determine that it didn't work? .NET version is exactly the same as the standard version. It just has one extra module in it.

**Comment by axvemi** [comment]
Trying to run it with the command godot won't start it (even after copying it to the folder like with the GDScript version). The shortcut provided doesn't open it either

**Comment by skyace65** [comment]
Closing this issue as it's not a doc issue, In the future I'd recommend you reach out to the community channels [here ](https://godotengine.org/community/)for this kind of support. In the event that the download from the site is the problem, and it's not something on your end, the best place to open an issue would be the main engine repository. But again, for this kind of problem go to the community channels for help first.
