### ISSUE TITLE
Renderer option for XR projects?

### ISSUE THREAD

**Issue by LMOlivera** [godotengine/godot-docs#6864]
**Your Godot version:** 4.0

**Issue description:** I was about to check how XR works on Godot when I found out that I have 3 renderer options, but I am not sure which one to choose. Can you add which Renderer should be chosen according to the target device? (example, "Compatibility" for Quest2).

**URL to the documentation page (if already existing):**https://github.com/godotengine/godot-docs/blob/master/tutorials/xr/setting_up_xr.rst

**Comment by skyace65** [comment]
There is a note about using mobile vs Forward+ on the page right now, but that should use the actual names and not vulkan desktop vs mobile, and mention not to use compatibility

@BastiaanOlij is there any reason to use one vs the other for individual headsets? or is mobile best for everything assuming the project doesn't need something that's only in Forward+?

**Comment by dsnopek** [comment]
For the moment, I think most folks are using the gl_compatibility renderer for XR, due to the need to do some more performance optimizations on the other renderers. I guess it's a question of how much we want to document (hopefully) temporary limitations?

**Comment by BastiaanOlij** [comment]
yeah I think it's to early to really make a good call on this. The hope in the future is that `Forward +` is solely for high end PCVR, `Mobile` for just about everything else. We're only falling back to `gl_compatability` at the moment due to the performance issues we're having but we feel these will be solvable.
