### ISSUE TITLE
Stable version of documention should list a precise version number

### ISSUE THREAD

**Issue by novalis** [godotengine/godot-docs#6866]
**Your Godot version:**
3.5.1

**Issue description:**
The docs don't tell me what actual version number stable is.  I assume it's 4.0, but it would be nice to immediately.  Maybe where it says "v: stable" at the bottom, it should say "v: stable (4.0)"?  Or maybe just under the "Godot docs" header where it says "stable"?  Basically, I want to immediately know whether I'm looking at the right version without having to keep track of what's currently considered "stable".

**URL to the documentation page (if already existing):**
https://docs.godotengine.org/en/stable/classes/class_os.html

**Comment by YuriSizov** [comment]
Yeah, I agree. I always found the "latest/stable" note in the sidebar lacking any context to an average user. I'll look into it.
