### ISSUE TITLE
Typo in Godot Docs: Introduction to Godot

### ISSUE THREAD

**Issue by zayeed-bs** [godotengine/godot-docs#6870]
![image](https://user-images.githubusercontent.com/74665895/222577036-d6f08f98-4485-4d39-9d81-00acdd177713.png)

Here, *"Argentinan"* should be replaced with *"Argentinian"*.

**Comment by YuriSizov** [comment]
This is fixed by https://github.com/godotengine/godot-docs/pull/6849.
