### ISSUE TITLE
GDExtension C++ example: _process virtual function declaration is incorrectly `void _process(float delta);`

### ISSUE THREAD

**Issue by Jordyfel** [godotengine/godot-docs#6871]
**Your Godot version:**
4.0

**Issue description:**
The function should be `void _process(double delta);`, which can be confirmed by using `override` and looking at which of the two generates an error. I remember reading in a blog post that doubles have replaced floats in most of the API in Godot 4, which got me thinking. This is consistent in the entire example, not just the declaration in the header. I have not yet compiled to test as I'm just now following the example.

**URL to the documentation page:**
https://docs.godotengine.org/en/stable/tutorials/scripting/gdextension/gdextension_cpp_example.html

**Comment by paddy-exe** [comment]
Fixed by https://github.com/godotengine/godot-docs/pull/7113
