### ISSUE TITLE
GDExtension C++ example: the provided .gdextension file does not work

### ISSUE THREAD

**Issue by Jordyfel** [godotengine/godot-docs#6872]
**Your Godot version:**
4.0

**Issue description:**
Copy-pasting the provided text for the .gdextension file does not work, opening the project in Godot fails to load the extension. And why would it, since the names of the libraries listed in it are different than the ones generated from the provided SConstruct file. Copy-pasting the contents of the .gdextension file in the test project in godot-cpp works just fine.

**URL to the documentation page:**
https://docs.godotengine.org/en/stable/tutorials/scripting/gdextension/gdextension_cpp_example.html

**Comment by Calinou** [comment]
cc @paddy-exe
