### ISSUE TITLE
"Your first 3D game" has several mistakes

### ISSUE THREAD

**Issue by mazingtech** [godotengine/godot-docs#6878]
**Your Godot version:4.0.stable.mono**

**Issue description:**
1. Properties of Vector2/Vector3 are suppose to be in uppercase;
2.Parameter "delta" are suppose to be a double, instead of float
3._velocity = MoveAndSlide(_velocity, Vector3.Up); is not right either. 

**URL to the documentation page (if already existing):**
https://docs.godotengine.org/en/stable/getting_started/first_3d_game/03.player_movement_code.html

**Comment by wzwywx** [comment]
My math is rusty but is PI/4 90 degrees or is it 45 degrees?

The comments for the code in the second script in this section (https://docs.godotengine.org/en/stable/getting_started/first_3d_game/04.mob_scene.html#removing-monsters-off-screen) says that the rotation range is between -90 to 90 degrees.

**Comment by 3lijah** [comment]
Also the C# snippets don't compile. I have working here: https://www.reddit.com/r/godot/comments/11ib90a/comment/jb1tko6/
