### ISSUE TITLE
"Player scene and input actions" has outdated screenshots.

### ISSUE THREAD

**Issue by Sslaxx** [godotengine/godot-docs#6889]
**Your Godot version:**
4.0 stable

**Issue description:**
On this page, under the "Creating input actions" section, the picture https://docs.godotengine.org/en/4.0/_images/left_inputmap.webp is using an outdated screenshot (Godot 4 stable has a dropdown list instead of the "Use Physical Keycode" checkbox).

**URL to the documentation page:**
https://docs.godotengine.org/en/4.0/getting_started/first_3d_game/02.player_input.html

**Comment by Hex-4** [comment]
If no one is working on this, I'd be happy to do it!
