### ISSUE TITLE
Navigation2d Overview References Incorrect Methods

### ISSUE THREAD

**Issue by Snayff** [godotengine/godot-docs#6894]
**Your Godot version:**
4.0 

**Issue description:**
Tutorial code refers to non existent methods:
- `set_target_location` not found -> should be `set_target_position`
- `get_next_location` not found -> should be `get_next_path_position`

**URL to the documentation page:**
https://docs.godotengine.org/en/stable/tutorials/navigation/navigation_introduction_2d.html

**Comment by smix8** [comment]
Fix #6823 is not merged and missing the setter.
