### ISSUE TITLE
Parser bug (Please report)

### ISSUE THREAD

**Issue by gonzalezharry** [godotengine/godot-docs#6898]
Godot version: 4.0

Hi! I saw this error in the Output console while coding. 
![Godot5](https://user-images.githubusercontent.com/100316997/222974161-c2578e56-e6c6-48ac-b865-006e55514e01.png)

That's all the code I had in the script when the error popped out, below are a bunch of comments (Next to be turned into pseudocode) that summarize what the script will do. 
I deleted the - sign at the end of the y value assignament of the Vector2, and the console stopped sending that message.
PS: The tile object to which I'm assigning the position isn't defined in the script. That's because I was iterating through the tiles_subset array, then decided to do an index-based iteration, but forgot to change tile to tiles_subset[i]. (As I said the console stopped sending the message as soon as I deleted the - sign, which happend before correcting the variable name)
PS2: After correcting the variable name (tile changed to tiles_subset[i]) I rewrote the - sign at the end of the Vector2 y value assignment (without typing any value next to it) and the console sent the error again.
Hope this helps, if any more information is necessary don't hesitate on letting me know!

**Comment by and-rad** [comment]
You might be in the wrong place for this. This is the repository for the Godot documentation. If you want to report an error with the engine, https://github.com/godotengine/godot/issues would be the place to do that.

**Comment by gonzalezharry** [comment]
You're right. Thanks!
