### ISSUE TITLE
Instancing Physics Material

### ISSUE THREAD

**Issue by bbacle** [godotengine/godot-docs#6916]
**Your Godot version:**

4.0

**Issue description:**

Instancing Physics Material Bounce not found in right-clicking on Physics Material
Instead you must click on the down arrow beside Physics Material & then click on Edit to get to "Bounce," where you change its value.

**URL to the documentation page:**

https://docs.godotengine.org/en/stable/getting_started/step_by_step/instancing.html

**Comment by Piralein** [comment]
`Let's try this. Open Ball.tscn and select the Ball node. In the Inspector on the right, click on the PhysicsMaterial property to expand it.`

do you mean this?
It doesn't say right click, you have to use the left click to open it. Right click opens the context menu for the resource itself.

**Comment by skyace65** [comment]
Closing this issue. As Piralein said, the current documentation does correctly explain how to get to the bounce property.
