### ISSUE TITLE
No longer bbcode field

### ISSUE THREAD

**Issue by ryugold777** [godotengine/godot-docs#6924]
Godot 4.0

There's no longer bbcode field in godot 4.0

https://docs.godotengine.org/en/stable/tutorials/ui/bbcode_in_richtextlabel.html

simply remove and add the field on to the top on the docs

**Comment by Calinou** [comment]
The screenshots on that page need to be updated in general – not only the inspector screenshot, but also the effect examples as the default project font is now different.

I can work on this next week.

**Comment by ryugold777** [comment]
> The screenshots on that page need to be updated in general – not only the inspector screenshot, but also the RichTextEffect examples as the default project font is now different in 4.0. (Let's get rid of that blurry font example :slightly_smiling_face:)
> 
> I can work on this next week.

Ok thanks to make It godot update and better.
