### ISSUE TITLE
Downloading the documentation for offline use only available for v4.0

### ISSUE THREAD

**Issue by BaIthamel** [godotengine/godot-docs#6925]
**Your Godot version:**
3.5
**Issue description:**
All download links via nightly.link direct to the master branch build regardless of the source of the link.
Since 3.6 is still in development it does not make sense that there are no download links available for 3.* builds.
This is very relevant for the 3.5 index page which reads:

> You can also [download an HTML copy](https://nightly.link/godotengine/godot-docs/workflows/build_offline_docs/master/godot-docs-html-stable.zip) for offline reading (updated every Monday). Extract the ZIP archive then open the top-level index.html in a web browser.

The build linked is the master branch which is v4.0.

**URL to the documentation page:**
https://docs.godotengine.org/en/3.5/index.html

If you know how to fix the issue you are reporting please
consider opening a pull request. We provide a tutorial on
using git here: https://docs.godotengine.org/en/stable/community/contributing/pr_workflow.html,
writing documentation at https://docs.godotengine.org/en/stable/community/contributing/docs_writing_guidelines.html
and contributing to the class reference here: https://docs.godotengine.org/en/stable/community/contributing/updating_the_class_reference.html

**Comment by skyace65** [comment]
This was fixed for the 3.6 branch in May this year. Given that 3.6 is in the release phase now we're not going to be doing a similar change for the 3.5.
