### ISSUE TITLE
First 2D Game - error issue

### ISSUE THREAD

**Issue by MistaGyro** [godotengine/godot-docs#6926]
FIXED: Remade the project from scratch and it worked. I found that my mobspawnlocation node was a path2D like mobpath instead of PathFollow2D
I'm new to Godot and I'm struggling with the 2D game tutorial to no avail (and made a Github account to ask)
Godot version: 4.0 Beta

Within this part of the code on 'Dodge the Creeps', when I run the game as the tutorial asks, I get the error `invalid set index 'progress' (on base: 'path2D') with value of type of float 'float'` that highlights the line `mob_spawn_location.progress_ratio = randf()` heres the code:

```
extends Node

@export var mob_scene: PackedScene
var score

func _ready():
	new_game()


func _process(delta):
	pass


func game_over():
	$ScoreTimer.stop()
	$MobTimer.stop()

func new_game():
	score = 0
	$Player.start($StartPosition.position)
	$StartTimer.start()

func _on_score_timer_timeout():
	score += 1

func _on_start_timer_timeout():
	$MobTimer.start()
	$ScoreTimer.start()

func _on_mob_timer_timeout():
	var mob = mob_scene.instantiate()
	
	var mob_spawn_location = get_node("MobPath/MobSpawnLocation")
	mob_spawn_location.progress_ratio = randf()
	
	var direction = mob_spawn_location.rotation + PI / 2
	
	mob.position = mob_spawn_location.position
	
	direction += randf_range(-PI / 4, PI / 4)
	mob.rotation = direction
	
	var velocity = Vector2(randf_range(150.0, 250.0), 0.0)
	mob.linear_velocity = velocity.rotated(direction)
	
	add_child(mob)
```

Here's the tutorial page I am at: https://docs.godotengine.org/en/stable/getting_started/first_2d_game/05.the_main_game_scene.html

**Comment by Piralein** [comment]
`FIXED: Remade the project from scratch and it worked. I found that my mobspawnlocation node was a path2D like mobpath instead of PathFollow2D`

Is your problem solved, or is there something that should be changed inside the tutorial?

**Comment by Piralein** [comment]
Closing as stale.

If you find a bug or want to share a suggestion to improve the documentation feel free to open a new issue.
