### ISSUE TITLE
Project manager overview minor mistake

### ISSUE THREAD

**Issue by pavel-zhigulin** [godotengine/godot-docs#6936]
**Your Godot version:**
v4.0.stable.official [92bee43ad]

**Issue description:**
On page **First look at Godot's editor** in paragraph **The Project Manager** there is line

> At the top of the window, there is another tab named "Templates".

I don't see any tab with such name.  I believe "Template" should be replaced by "Asset Library Projects"

**URL to the documentation page:**
https://docs.godotengine.org/en/stable/getting_started/introduction/first_look_at_the_editor.html#the-project-manager

**Comment by YuriSizov** [comment]
Thanks for your report, this is a duplicate of https://github.com/godotengine/godot-docs/issues/6892
