### ISSUE TITLE
Misspelling in 'Custom post-processing' shader code

### ISSUE THREAD

**Issue by mhaneman** [godotengine/godot-docs#6950]
**Your Godot version:**
4.0

**Issue description:**
There is a misspelling / wrong code in line 4 of the shader code:
uniform sampler2D screen_texture : hint_screen_texture, repeat_disabled, filter_nearest;

should be changed to:
uniform sampler2D screen_texture : hint_screen_texture, repeat_disable, filter_nearest;

**URL to the documentation page:**

If you know how to fix the issue you are reporting please
consider opening a pull request. We provide a tutorial on
using git here: https://docs.godotengine.org/en/stable/community/contributing/pr_workflow.html,
writing documentation at https://docs.godotengine.org/en/stable/community/contributing/docs_writing_guidelines.html
and contributing to the class reference here: https://docs.godotengine.org/en/stable/community/contributing/updating_the_class_reference.html

**Comment by SaumyaBhushan** [comment]
I would like to work on this issue
