### ISSUE TITLE
2D Sprite Animation sample screenshot says "KinematicBody2D"

### ISSUE THREAD

**Issue by epw** [godotengine/godot-docs#6956]
**Your Godot version:** 4.0

**Issue description:** While the actual code on the 2D Sprite Animation tutorial page has been updated to say CharacterBody2D instead of KinematicBody2D, the screenshots do not:

- https://docs.godotengine.org/en/stable/_images/2d_animation_tree1.png
- https://docs.godotengine.org/en/stable/_images/2d_animation_tree2.png

It's a small issue to be sure, but could confuse a newcomer so seems worth mentioning.

**URL to the documentation page:** https://docs.godotengine.org/en/stable/tutorials/2d/2d_sprite_animation.html

**Comment by Piralein** [comment]
this was already fixed by #7030
