### ISSUE TITLE
Incorrect description of the operator < between Arrays

### ISSUE THREAD

**Issue by tjw123hh** [godotengine/godot-docs#6964]
**Your Godot version:** 4.0.stable

**Issue description:** The documentation says 

> If all elements are equal, it compares the length of both arrays and returns false if the left operand Array has fewer elements, otherwise it returns true.

 But the opposite is true in practice.

**URL to the documentation page:** https://docs.godotengine.org/en/stable/classes/class_array.html

**Comment by Mickeon** [comment]
I feel like this would be closed by https://github.com/godotengine/godot/pull/69451 .

**Comment by AThousandShips** [comment]
Not merged yet

**Comment by Mickeon** [comment]
A man can dream (give it time)
