### ISSUE TITLE
No way to covert PackedByteArray to PackedVectorArray.

### ISSUE THREAD

**Issue by Egor-Stasenko** [godotengine/godot-docs#6966]
**Your Godot version:** 4.0

**Issue description:** Messing around with compute shaders I came across a lack of few methods in the PackedByteArray class especially .to_Vector3_array(), and also to other vector type arrays. I think they must be there because PackedVector3Array (and others) has .to_byte_array() method.

**URL to the documentation page:** https://docs.godotengine.org/en/4.0/classes/class_packedbytearray.html

**Comment by clayjohn** [comment]
I don't think a ``to_Vector3_array()`` or equivalent exists right now. So this isn't so much a documentation bug as a feature request. Perhaps it would be worth opening an issue in the [godot-proposals](https://github.com/godotengine/godot-proposals) repository instead?

There has been a little discussion around conversion to/from PackedVector3Arrays, but so far it has mostly been for internal code (see e.g. https://github.com/godotengine/godot/pull/67853). I agree that proper marshalling to/from all the packed***array types would be very helpful for compute shaders

**Comment by Egor-Stasenko** [comment]
Oh, thanks. I was not sure in which repository should I ask for this.
