### ISSUE TITLE
Exporting for web page is possibly outdated

### ISSUE THREAD

**Issue by Pennycook** [godotengine/godot-docs#6970]
**Your Godot version:**

v4.0.stable.official [92bee43ad]

**Issue description:**

The exporting for web page currently says:

> You can choose the Export Type to select which features will be available:
> 
> Regular: is the most compatible across browsers, will not support threads, nor GDExtension.
> 
> Threads: will require the browser to support [SharedArrayBuffer](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/SharedArrayBuffer). See [Can I use SharedArrayBuffer](https://caniuse.com/sharedarraybuffer) for details.

I don't see these options in Godot 4.0.  Instead, I see:

![image](https://user-images.githubusercontent.com/857660/224571099-fb33a5a7-f4d1-4a13-8c66-b1357a3618c3.png)

I might be missing something, but based on what I'm observing in Godot 4.0 I think this section needs two changes:

1. To reference "Variant/Extensions Support" instead of "Export Type"
2. To explain that exporting for web always requires SharedArrayBuffer

If I'm wrong about the behavior above, please consider this a request for improved documentation.  I can't find "Export Type" anywhere, and I haven't been able to find a way to disable SharedArrayBuffer.

**URL to the documentation page:**

https://docs.godotengine.org/en/stable/tutorials/export/exporting_for_web.html

**Comment by skyace65** [comment]
Most of this was fixed by #6886. However there's still no description for extensions support.
