### ISSUE TITLE
4.0 Documentation still referring to "Script Variables" section in Inspector

### ISSUE THREAD

**Issue by Griiimon** [godotengine/godot-docs#6987]
In the 4.0 documentation it still says "Scripting Variables" referring to the field in the Inspector, which now displays the name of the actual script instead. Don't know if it's the only occurrence.

https://docs.godotengine.org/en/stable/getting_started/first_2d_game/03.coding_the_player.html

![image](https://user-images.githubusercontent.com/25064539/225454849-618e1642-fbe3-4165-a155-215772072c08.png)

**Comment by maymer75** [comment]
Mine shows up as "Script Variables" with the Speed property there like it says. A problem I ran into is the @ in front of the "export" keyword is a syntax error in GDScript so it wasn't showing up at all until I removed that, then I can see it.

![image](https://user-images.githubusercontent.com/455386/230786970-7bb468e5-707f-49df-afa2-f38943ba9a23.png)

**Comment by maymer75** [comment]
please ignore my prior comment, I was on v3.5, sorry.

**Comment by daveTheOldCoder** [comment]
"Script Variables" also occurs here:
https://docs.godotengine.org/en/stable/getting_started/first_2d_game/05.the_main_game_scene.html#main-script
