### ISSUE TITLE
missing @ on the style guide

### ISSUE THREAD

**Issue by Flipkickisreal** [godotengine/godot-docs#6988]
**4.0**

**export is now @export**

**https://docs.godotengine.org/en/stable/tutorials/scripting/gdscript/gdscript_styleguide.html**

If you know how to fix the issue you are reporting please
consider opening a pull request. We provide a tutorial on
using git here: https://docs.godotengine.org/en/stable/community/contributing/pr_workflow.html,
writing documentation at https://docs.godotengine.org/en/stable/community/contributing/docs_writing_guidelines.html
and contributing to the class reference here: https://docs.godotengine.org/en/stable/community/contributing/updating_the_class_reference.html
![image](https://user-images.githubusercontent.com/42154453/225469216-adf94849-0427-418e-9845-ab2183d7380e.png)

**Comment by mhilbrunner** [comment]
Fixed in https://github.com/godotengine/godot-docs/pull/6498
