### ISSUE TITLE
add support for MOONRAY since its open source now

### ISSUE THREAD

**Issue by eddilara** [godotengine/godot-docs#6990]
add support for moonray Renderer  now that its open source

https://github.com/dreamworksanimation/openmoonray

**Comment by clayjohn** [comment]
This is the repository for the Godot documentation. We use this bug tracker to track issues with the docs themselves. I have a feeling you meant to create a proposal in the proposals repository https://github.com/godotengine/godot-proposals

That being said, proposals are intended more for when people have a clear proposal and a plan for implementing it. What you should open is a [discussion](https://github.com/godotengine/godot-proposals/discussions) in the proposals repository. That is the best place to make a simple suggestion and discuss with others whether other people support your idea.
