### ISSUE TITLE
Warning documentation still uses Godot 3.x script syntax

### ISSUE THREAD

**Issue by doctor-g** [godotengine/godot-docs#6994]
**Your Godot version:** 4.0.0

**Issue description:**

The documentation page for the GDScript warning system claims to be up to date, but it uses the old bodge syntax (#warning-ignore) rather than the new one (@warning_ignore). 

**URL to the documentation page:**
https://docs.godotengine.org/en/4.0/tutorials/scripting/gdscript/warning_system.html

If you know how to fix the issue you are reporting please
consider opening a pull request. We provide a tutorial on
using git here: https://docs.godotengine.org/en/stable/community/contributing/pr_workflow.html,
writing documentation at https://docs.godotengine.org/en/stable/community/contributing/docs_writing_guidelines.html
and contributing to the class reference here: https://docs.godotengine.org/en/stable/community/contributing/updating_the_class_reference.html

**Comment by gelvinp** [comment]
I've had a PR to fix this (#6586) since January.

**Comment by skyace65** [comment]
This was fixed by #8250.
