### ISSUE TITLE
Documentation mistake: @GlobalScope snappedf() and snappedi() 

### ISSUE THREAD

**Issue by andrew8890** [godotengine/godot-docs#6995]
Godot 4

Minor documentation mistake for @GlobalScope snappedf() and snappedi(). Both method examples use snapped().

https://docs.godotengine.org/en/stable/classes/class_@globalscope.html#class-globalscope-method-snappedf

**Comment by MisoMosiSpy** [comment]
Is anyone working on this? I want to learn how to update class reference so I would like to submit a PR for this.

**Comment by andrew8890** [comment]
MisoMosiSpy, 
Please go ahead. I don't know how to do a PR.
