### ISSUE TITLE
Documentation mistake: CUSTOM_DATA type enums don't exist or have been renamed to another enum in MultiMesh.

### ISSUE THREAD

**Issue by JoshuaColell** [godotengine/godot-docs#6998]
**Your Godot version:**
4.0

**Issue description:**
If you scroll down, you'll see that on the line: 
`multimesh.custom_data_format = MultiMesh.CUSTOM_DATA_NONE`

The code won't actually work, since CUSTOM_DATA_NONE or any other CUSTOM_DATA enum (like CUSTOM_DATA_FLOAT) doesn't exist.

**URL to the documentation page:**
https://docs.godotengine.org/en/stable/tutorials/performance/using_multimesh.html#multimesh-example

**Comment by clayjohn** [comment]
Those options have been removed. The code block should be updated to remove the lines setting color_format and custom_format

**Comment by JoshuaColell** [comment]
Alright, thanks!

**Comment by clayjohn** [comment]
Reopening to track this until it gets fixed. We will close it when we merge a pull request removing the out of date lines of code

**Comment by mateuseap** [comment]
@clayjohn I did it in the above PR! Just removed the out-of-date lines of from the GDScript code and C# code as well
