### ISSUE TITLE
2D Sprite Animation (Outdated info)

### ISSUE THREAD

**Issue by Coder2195Text** [godotengine/godot-docs#6999]
**Your Godot version:** 4.0 stable

**Issue description:** Tutorial on 2d sprite animation is outdated with images and API calls

Docs:
![image](https://user-images.githubusercontent.com/63069499/225772420-8a60fddf-d720-452e-bd92-d4e17e470d9c.png)

API reference
![image](https://user-images.githubusercontent.com/63069499/225772464-3e12b285-9ee0-40b6-a3db-132e03633fc6.png)

**URL to the documentation page:** https://docs.godotengine.org/en/stable/tutorials/2d/2d_sprite_animation.html

If you know how to fix the issue you are reporting please
consider opening a pull request. We provide a tutorial on
using git here: https://docs.godotengine.org/en/stable/community/contributing/pr_workflow.html,
writing documentation at https://docs.godotengine.org/en/stable/community/contributing/docs_writing_guidelines.html
and contributing to the class reference here: https://docs.godotengine.org/en/stable/community/contributing/updating_the_class_reference.html

**Comment by ShatReal** [comment]
I'm using 4.0 too but I do see the first five buttons.

**Comment by Coder2195Text** [comment]
> I'm using 4.0 too but I do see the first five buttons.

Can I see ur spriteframes

**Comment by Coder2195Text** [comment]
I opened clean godot on an remote vnc

Still the same

![image](https://user-images.githubusercontent.com/63069499/226068175-5ae3cfeb-4552-4028-9970-3a6b563969a7.png)
