### ISSUE TITLE
TileMap 2D Navigation Atsar tutorial out of date

### ISSUE THREAD

**Issue by terminator98202** [godotengine/godot-docs#7000]
**4.0**

**TileMap 2D Navigation Atsar tutorial out of date**

**https://docs.godotengine.org/en/4.0/classes/class_tilemap.html**

The 2D Navigation Astar Demo in the TileMap documentation is out of date pls fix so we can learn how to use Astar tilemaps in Godot 4

**Comment by terminator98202** [comment]
Thanks! I'm unable to download the .zip for the 4.0 version of the astar demo from github though could you fix that please?

**Comment by TheYellowArchitect** [comment]
@terminator98202 

git clone https://github.com/godotengine/godot-demo-projects/tree/master/2d/navigation_astar **will not work.**
git clone https://github.com/godotengine/godot-demo-projects does work. 
Give it a try. Then open godot editor and navigate onto navigation_astar folder

**Comment by terminator98202** [comment]
Thanks!
