### ISSUE TITLE
Duplicate docs search results

### ISSUE THREAD

**Issue by jwmcgettigan** [godotengine/godot-docs#7015]
**Your Godot version:**
4.0

**Issue description:**
Similar to https://github.com/godotengine/godot-docs/issues/5650, there are duplicate search results.
Appears to always show three duplicates of every result.
![image](https://user-images.githubusercontent.com/1691061/226143406-3b32b786-2ef5-4ee4-b856-3989952f474d.png)

**URL to the documentation page:**
https://docs.godotengine.org/en/stable/search.html?q=onready&check_keywords=yes&area=default

**Comment by skyace65** [comment]
This was fixed at some point. There are no longer duplicate results.
