### ISSUE TITLE
Can not print the external address

### ISSUE THREAD

**Issue by siller11** [godotengine/godot-docs#7019]
**4.0**

**Query_external_address() cannot print the ip out **

`extends Node2D

@onready var main_menu = $CanvasLayer/MainMenu
@onready var address_entry = $CanvasLayer/MainMenu/MarginContainer/VBoxContainer/adden
@onready var health_bar = $CanvasLayer/HUD/HealthBar
@onready var hud = $CanvasLayer/HUD

const Player1 = preload("res://players/player1/player.tscn")
const Player2 = preload("res://players/player2.tscn")
const PORT = 9999
var enet_peer = ENetMultiplayerPeer.new()

func _on_host_button_pressed():
	main_menu.hide()
	hud.show()
	
	enet_peer.create_server(PORT)
	multiplayer.multiplayer_peer = enet_peer
	multiplayer.peer_connected.connect(add_player2)
	multiplayer.peer_disconnected.connect(remove_player)
	
	add_player1(multiplayer.get_unique_id())
	
	upnp_setup()
	
func _on_join_button_pressed():
	main_menu.hide()
	hud.show()
	
	enet_peer.create_client(address_entry.text, PORT)
	multiplayer.multiplayer_peer = enet_peer

func add_player1(peer_id):
	var player1 = Player1.instantiate()
	player1.name = str(peer_id)
	add_child(player1)

func add_player2(peer_id):
	var player2 = Player2.instantiate()
	player2.name = str(peer_id)
	add_child(player2)

func remove_player(peer_id):
	var player = get_node_or_null(str(peer_id))
	if player:
		player.queue_free()

func upnp_setup():
	var upnp = UPNP.new()
	var discover_result = upnp.discover()

	if discover_result == UPNP.UPNP_RESULT_SUCCESS:
		if upnp.get_gateway() and upnp.get_gateway().is_valid_gateway():
			
			var map_result_udp = upnp.add_port_mapping(9999,9999,"godot_udp", "UDP", 0)
			var map_result_tcp = upnp.add_port_mapping(9999,9999,"godot_tcp", "TCP", 0)
			
			if not map_result_udp == UPNP.UPNP_RESULT_SUCCESS:
				upnp.add_port_mapping(9999,9999,"", "UDP")
			
			if not map_result_tcp == UPNP.UPNP_RESULT_SUCCESS:
				upnp.add_port_mapping(9999,9999,"", "TCP")

	var external_ip = upnp.query_external_address()
	
	upnp.delete_port_mapping(9999, "UDP")
	upnp.delete_port_mapping(9999, "TCP")

	print("join wtih the ip: %s" % external_ip)`

**Comment by skyace65** [comment]
Please do not open issues in the documentation that are problems with your project you're trying to solve. These issues are only for things that we know are wrong with the docs that need to be changed. You can use places such as Discord, the forums, or Reddit for when you need help
