### ISSUE TITLE
Specify what "changes" means inside Range.value_changed signal

### ISSUE THREAD

**Issue by shunlog** [godotengine/godot-docs#7040]
**Issue description:**
It is not clear enough that the `value_changed` signal on a Range-based node will not be called if the new value is equal to the previous value. One might make the assumption that when they set the value of a Range via code, it will always emit this signal, therefore it should be made clear that when the new value equals the previous value, the signal [will not be sent](https://github.com/godotengine/godot/blob/1d14c054a12dacdc193b589e4afb0ef319ee2aae/scene/gui/range.cpp#L81).

**URL to the documentation page (if already existing):**
[https://github.com/godotengine/godot-docs/blob/33c61914b4207b5864bc9008c225a7f1d7e28465/classes/class_range.rst](https://github.com/godotengine/godot-docs/blob/33c61914b4207b5864bc9008c225a7f1d7e28465/classes/class_range.rst)

**Comment by YuriSizov** [comment]
> One might make the assumption that when they set the value of a Range via code, it will always emit this signal

Godot doesn't emit "changed" signals when you set the value yourself via code. This a part of the overarching design, and applies to all classes, more or less.

I'm also not convinced that the assumption you describe is realistic. Do you have an example of that happening, someone being confused?

**Comment by YuriSizov** [comment]
> Still, we should make it clear that "changed" means "set to a different value" and not just "set".

Well, that's kind of in the word. The signal is called "changed", not "set".



> [value_changed](https://docs.godotengine.org/en/latest/classes/class_range.html#class-range-signal-value-changed) is emitted, though.

Yeah, true, this specific one is an exception which we didn't solve properly for 4.0.

**Comment by shunlog** [comment]
Ok, whatever
