### ISSUE TITLE
GDScript style guide upgrade to 4.0: documentation comments should use double hash `##`

### ISSUE THREAD

**Issue by hsandt** [godotengine/godot-docs#7050]
Doc comments are explained on the [dedicated page](https://docs.godotengine.org/en/latest/tutorials/scripting/gdscript/gdscript_documentation_comments.html), but the GDScript style guide does not use them everywhere relevant.

**Comment by tetrapod00** [comment]
Seemingly fixed in https://github.com/godotengine/godot-docs/pull/7412.
