### ISSUE TITLE
Let RTD build PRs

### ISSUE THREAD

**Issue by umarcor** [godotengine/godot-docs#7060]
ReadTheDocs supports building versions of the docs for PRs. See https://docs.readthedocs.io/en/stable/pull-requests.html and https://docs.readthedocs.io/en/stable/guides/pull-requests.html.

It would be helpful to have the feature enabled for this repo as it would allow contributors to check that the build in CI is properly seen.

**Comment by YuriSizov** [comment]
RTD builds are really slow and limited in resources. Enabling this would just hammer them down, and make deploys take hours.

If you want to test the visuals, build the docs locally. Drop the classes folder if you must, or use the flag to build specific pages to speed things up.

**Comment by umarcor** [comment]
Fair enough.
