### ISSUE TITLE
Using ImmediateMesh wrong function names

### ISSUE THREAD

**Issue by qustrolabe** [godotengine/godot-docs#7067]
**Your Godot version:**
stable (4.0)
**Issue description:**
"Using ImmediateMesh" page shows usage of **ImmediateMesh** with wrong function names like `begin()`, `end()`, `clear()`  (for some reason code almost identical to Using SurfaceTool code example). Actual functions names are `surface_begin()`, `surface_end()`, `clear_surfaces()` and others.
**URL to the documentation page:**
https://docs.godotengine.org/en/stable/tutorials/3d/procedural_geometry/immediatemesh.html

**Comment by mateuseap** [comment]
I've check it out the info about [`ImmediateMesh` class](https://docs.godotengine.org/en/stable/classes/class_immediatemesh.html#class-immediatemesh-method-surface-end) and updated the methods names used in the **Using `ImmediateMesh`** 3d tutorial to match the methods names present in the class info page.
