### ISSUE TITLE
Step by step / Creating instances / In practice - Link to legacy sample project

### ISSUE THREAD

**Issue by MrDixioner** [godotengine/godot-docs#7071]
This section contains a link to the sample project for engine version 3.x. When you open it in version 4, a project conversion window appears, which can be confusing for beginners. You need to replace the project reference for version 4.
Project link: [instancing.zip](https://docs.godotengine.org/en/stable/_downloads/0f77439a03c9c1eb57dab630d028b82d/instancing.zip)

**Comment by skyace65** [comment]
Fixed by https://github.com/godotengine/godot-docs-project-starters/pull/3
