### ISSUE TITLE
Tutorial - Creating instances - In practice - Outdated project file "instancing.zip" made with Godot 3.x.

### ISSUE THREAD

**Issue by einholzstuhl** [godotengine/godot-docs#7108]
**Your Godot version:**
4.0.1

**Issue description:**
Outdated project file. When I imported the provided project file "instancing.zip" I get the warning message that this project has been created in Godot version 3.x and needs to be converted to the newer version.

**URL to the documentation page:**
https://docs.godotengine.org/en/stable/getting_started/step_by_step/instancing.html

If you know how to fix the issue you are reporting please
consider opening a pull request. We provide a tutorial on
using git here: https://docs.godotengine.org/en/stable/community/contributing/pr_workflow.html,
writing documentation at https://docs.godotengine.org/en/stable/community/contributing/docs_writing_guidelines.html
and contributing to the class reference here: https://docs.godotengine.org/en/stable/community/contributing/updating_the_class_reference.html

**Comment by jynus** [comment]
Thank you for reporting! I can confirm that the given project was for Godot 3.X and it didn't work out of the box in Godot 4.

I've updated the instancing.zip example to Godot 4.0 here: https://github.com/godotengine/godot-docs/raw/4f2ff35ad802a7f1fbe9f5e9558f1e3856f6eafc/getting_started/step_by_step/files/instancing.zip Can you try it and see if the new version works for you?

I've created PR #7211 hoping to fix this issue.

Thank you!

**Comment by skyace65** [comment]
Fixed by #7222
