### ISSUE TITLE
[3.5/3.6] Wrong Android SDK version in "Exporting for Android" page

### ISSUE THREAD

**Issue by NianoTT** [godotengine/godot-docs#7111]
**Your Godot version:** 
3.5/(3.6)

**Issue description:** 
The "Export to Android" page states SDK 31 in the list of requirements, however the SDK version has been bumped up to 32 in 3.5.2 (and from what I understand will be 33 in 3.6).

**URL to the documentation page:** 
https://docs.godotengine.org/en/3.5/tutorials/export/exporting_for_android.html

**Comment by skyace65** [comment]
Fixed by #9105.
