### ISSUE TITLE
Advanced post-processing documentation page refers to DEPTH_TEXTURE 

### ISSUE THREAD

**Issue by mcccclean** [godotengine/godot-docs#7118]
**Your Godot version:** 
4.0.stable

**Issue description:** 
When explaining how to read the depth buffer, the "Advanced post-processing documentation page" instructs the user to use `DEPTH_TEXTURE`, which was deprecated in favour of `hint_depth_texture`.

**URL to the documentation page:** 
https://docs.godotengine.org/en/stable/tutorials/shaders/advanced_postprocessing.html#depth-texture

**Comment by Piralein** [comment]
Fixed by #7119.
