### ISSUE TITLE
Skeleton2D Modification bug on scene reload

### ISSUE THREAD

**Issue by dippinpahwa** [godotengine/godot-docs#7124]
Godot version: 4.0.1
I am using SkeletonBone2DTwoBoneIK modifier with the Skeleton2D bone rig, the bones which are modified turn yellow which ensures the influence of that modifier. However, when I reload the scene the bones turn white and the influence is disabled (in editor) while the property inspector remains unchanged.
I am fixing it by deleting a modifier and undo it to restore the influence

**Comment by clayjohn** [comment]
This repository is for the Godot documentation. Bugs with Godot itself are tracked over at https://github.com/godotengine/godot. Could you please open a bug report there and include all the required information from the template?
