### ISSUE TITLE
scripting_first_script - C# Typo

### ISSUE THREAD

**Issue by frederic-spielmann** [godotengine/godot-docs#7128]
**Your Godot version:**
v4.0.1.mono.stable

**Issue description:**
![Attach node script](https://docs.godotengine.org/en/stable/_images/scripting_first_script_attach_node_script.webp)

We expect the user to have a filename Sprite2D.gd / Sprite2D.cs

However in the code example the class name is ```Sprite``` instead of ```Sprite2D```

```c#
using Godot;

public partial class Sprite : Sprite2D
{
}
```

```C#
using Godot;

public partial class Sprite : Sprite2D
{
    private int Speed = 400;
    private float AngularSpeed = Mathf.Pi;

    public override void _Process(double delta)
    {
        Rotation += AngularSpeed * (float)delta;
        var velocity = Vector2.Up.Rotated(Rotation) * Speed;

        Position += velocity * (float)delta;
    }
}
```

Fix : 
```C#
using Godot;

public partial class Sprite2D : Godot.Sprite2D
{

    private int Speed = 400;
    private float AngularSpeed = Mathf.Pi;

    public override void _Process(double delta)
    {
        Rotation += AngularSpeed * (float)delta;
        
        var velocity = Vector2.Up.Rotated(Rotation) * Speed;

        Position += velocity * (float)delta;
    }
}
```

**URL to the documentation page:**
- [scripting_first_script.html](https://docs.godotengine.org/en/stable/getting_started/step_by_step/scripting_first_script.html)

Pull request #7129

**Comment by Piralein** [comment]
Fixed by #7371
