### ISSUE TITLE
ImmediateMesh

### ISSUE THREAD

**Issue by CandJGaming** [godotengine/godot-docs#7131]
I'm not finding a node named ImmediateMesh, but the documents suggest it exists and that it is the replacement to immediateGeometry. When I do "extends ImmediateMesh " the class is found.

**Comment by YuriSizov** [comment]
Which version of Godot are you using? Which pages suggest it exists? There is a template for issue reports for a reason, you should not remove it.

**Comment by CandJGaming** [comment]
There was no template, but whatever. 
![image](https://user-images.githubusercontent.com/105566572/230773014-108103d4-f2da-401a-8cdb-2fb6a7f04b94.png)
I tried it on 4.0 and 4.04.
I'm led to believe it exists here. 
https://docs.godotengine.org/en/stable/classes/class_immediatemesh.html

**Comment by CandJGaming** [comment]
![image](https://user-images.githubusercontent.com/105566572/230773277-416a9bd0-2fae-4d7b-8bd6-d0eb21df5236.png)

**Comment by YuriSizov** [comment]
`ImmediateMesh` is a resource, and not a node. You cannot assign a script extending it to a node, neither can you use `_ready` and `_process` in such a script. You assign an instance of the `ImmediateMesh` resource to nodes that take a mesh resource, like `MeshInstance2/3D` or `MultiMeshInstance2/3D`.

**Comment by DevKnightlie** [comment]
The confusion around ImmediateMesh being descended from Node - which it used to be - is that the online docs linked by the v4 IDE take you to a page which says it is, and which claims to be "Up to date for Godot 4.1"

https://docs.godotengine.org/en/4.1/tutorials/3d/procedural_geometry/immediatemesh.html
