### ISSUE TITLE
Hi. I'm going nuts trying to find the right documentation for high level multiplayer for godot 4. 

### ISSUE THREAD

**Issue by DocMine** [godotengine/godot-docs#7142]
**Your Godot version:**
4.0.3
**Issue description:**
The website seems to have old documentation; 
**URL to the documentation page:**
https://docs.godotengine.org/en/stable/tutorials/networking/high_level_multiplayer.html
If you know how to fix the issue you are reporting please
consider opening a pull request. We provide a tutorial on
using git here: https://docs.godotengine.org/en/stable/community/contributing/pr_workflow.html,
writing documentation at https://docs.godotengine.org/en/stable/community/contributing/docs_writing_guidelines.html
and contributing to the class reference here: https://docs.godotengine.org/en/stable/community/contributing/updating_the_class_reference.html

**Comment by YuriSizov** [comment]
There isn't a new multiplayer article yet, but it is in works.

**Comment by Geams** [comment]
The multiplayer property (type MultiplayerAPI) is missing from the property table with the SceneTree docs.
[Doc](https://docs.godotengine.org/en/latest/classes/class_scenetree.html)

**Comment by mhilbrunner** [comment]
Fixed by https://github.com/godotengine/godot-docs/pull/7675
