### ISSUE TITLE
Incorrect syntax for "node configuration warnings" on "Running code in the editor" page 

### ISSUE THREAD

**Issue by iznaut** [godotengine/godot-docs#7155]
**Your Godot version:** 4.0.2.stable

**Issue description:** There are a number of issues with the example code for node configuration warnings:

- `_get_configuration_warning` should have an "s" at the end (`_get_configuration_warnings`)
- `_get_configuration_warnings()` needs to return an array of strings, not a string

**URL to the documentation page:** https://docs.godotengine.org/en/stable/tutorials/plugins/running_code_in_the_editor.html#reporting-node-configuration-warnings

**Comment by jynus** [comment]
Indeed, this should be resolved, I can see the fix on both HEAD and stable.
