### ISSUE TITLE
Scoop command in windows compilation instructions is missing MinGW 

### ISSUE THREAD

**Issue by EhoNo1** [godotengine/godot-docs#7157]
**Your Godot version:** Stable (4.0)

**Issue description:** 
The instructions for compiling for source on windows provide a simple scoop command to " install MinGW and other dependencies". The command implies that MinGW is included but MinGW **is not included** in the command and is not found by the provided compilation command if the user fails to install it separately.

**URL to the documentation page:**
https://docs.godotengine.org/en/stable/contributing/development/compiling/compiling_for_windows.html

I simply added `mingw` to the end, but I'm entirely unfamiliar with the majority of these tools so I cannot verify if this is a safe version or the intended way to install.

**Comment by EhoNo1** [comment]
Made a pull request to fix this to practice contributing ( #7158). Would appreciate pointers and proofreading to ensure I've done it correctly.

**Comment by mhilbrunner** [comment]
Fixed in https://github.com/godotengine/godot-docs/pull/7158.
Hah, see, now there's a pointer: If you include a text like "Fixes #7157" in your PR description, Github will autoclose the issue.
Thanks again!
