### ISSUE TITLE
Outdated Viewport Capture Example Code

### ISSUE THREAD

**Issue by Puppyguarb** [godotengine/godot-docs#7162]
**Your Godot version:**
4.0.2.stable

**Issue description:**
The following code snippet included in the documentation causes an Invalid Call error in Godot v4.0.2.stable:
`var img = get_viewport().get_texture().get_data()`

**URL to the documentation page:**
https://docs.godotengine.org/en/stable/tutorials/rendering/viewports.html

**Comment by jynus** [comment]
Thank you for reporting.

I can confirm:

> Invalid call. Nonexistent function 'get_data' in base 'ViewportTexture'.

Original tutorial used `get_data()` inherited from Texture; on Godot 4.0+ it is `get_image()` from Texture2D

There is also minor changes needed on texture setup for it to work. 

Created #7210
