### ISSUE TITLE
Outdated procedural geometry, ImmediateMesh tutorial, marked as up to date

### ISSUE THREAD

**Issue by eon-s** [godotengine/godot-docs#7172]
**Your Godot version:**
4.0 documentation

**Issue description:**

Procedural geometry, ImmediateMesh tutorial, mentions
```
Unlike the SurfaceTool or ArrayMesh, ImmediateMesh is an actual node.
```

But ImmediateMesh is not a node, is a Resource, and the code below refers to a Node too.

PS: I'll add that I haven't done procedural geometry in any version of Godot so I don't know if the rest of Procedural Geometry tutorials are correct but some users reported problems following instructions there, so maybe everything is outdated.

**URL to the documentation page:**

https://docs.godotengine.org/en/stable/tutorials/3d/procedural_geometry/immediatemesh.html

**Comment by trollusk** [comment]
+1. Also could whoever updates the page please include an example of making a simple 3D mesh, eg a cube?
