### ISSUE TITLE
MeshDataTool documentation uses nonexistent function in an example

### ISSUE THREAD

**Issue by MichaelMacha** [godotengine/godot-docs#7176]
**Your Godot version:**
4.0.2

**Issue description:**
The documentation on MeshDataTool suggests I use the function surface_remove from ArrayMesh; but no such function exists.

**URL to the documentation page:**
https://docs.godotengine.org/en/stable/classes/class_meshdatatool.html#class-meshdatatool-method-create-from-surface

I _think_ it's trying to clear the surfaces, but this is honestly something I'm still learning to do with Godot and probably shouldn't correct myself.

**Comment by clayjohn** [comment]
Yes, it should use [``clear_surfaces``](https://docs.godotengine.org/en/stable/classes/class_arraymesh.html#class-arraymesh-method-clear-surfaces) instead
