### ISSUE TITLE
Using NavigationAgents tutorial provides unworking example

### ISSUE THREAD

**Issue by EhoNo1** [godotengine/godot-docs#7192]
**Your Godot version:**
Doc Version: Latest (4.0)
Editor Version: 4.0.2.stable

**Issue description:**
Using the provided script template for Actor as Node3D does not produce a working example. 
Creating a MVP with the script provided does create a moving agent. Adding a call to the `set_movement_target()` of an arbitrary vector into the `_ready()` function does not produce any movement either.

Here is a screenshot of the scene tree of the MVP:
![image](https://user-images.githubusercontent.com/37421719/233260969-e60e2ff7-a203-42f3-816e-8b73403e7338.png)
And the navigation mesh has been baked:
![image](https://user-images.githubusercontent.com/37421719/233261316-da9c8310-b5e7-492d-8f59-4d6452704e66.png)

**URL to the documentation page:**
https://docs.godotengine.org/en/latest/tutorials/navigation/navigation_using_navigationagents.html

I can provide a copy of my MVP if requested. (Not uploading it in this message because I'm unsure of the generally accepted way to share it.)

**Comment by mhilbrunner** [comment]
We just merged https://github.com/godotengine/godot-docs/pull/7195 to fix this, thanks for reporting!

The updated version should appear in a bit on the above mentioned `latest` URL, and on the `stable` version of that page once we sync that manually, so until then take care to reference the latest version :)
