### ISSUE TITLE
AnimatedSprite2D checkbox Playing is not in Inspector anymore?

### ISSUE THREAD

**Issue by gennadiysofronov** [godotengine/godot-docs#7213]
v4.0.2.stable.official [7a0977ce2]

In the documentation there is an article that recommends check the box _Playing_, but there is no such checkbox.

[https://docs.godotengine.org/en/stable/tutorials/2d/2d_sprite_animation.html](url)

![image](https://user-images.githubusercontent.com/34471973/233855607-fcac9b62-5886-43f3-ac72-e3c4d70a01a3.png)

![image](https://user-images.githubusercontent.com/34471973/233855838-baaec833-79b6-45fb-a3b6-793469466d18.png)

Another issue is that because of absense of that checkbox AnimationPlayer node can't play any animation from AnimatedSprite2D.
Maybe that feature is obsolete? Then corrections in documentation must be done.

**Comment by cbscribe** [comment]
Yes, this should be changed to indicate that in 4.0, AnimatedSprite is played using the play button in the SpriteFrames panel.
