### ISSUE TITLE
Document IntelliSense setup for vscode.

### ISSUE THREAD

**Issue by HolonProduction** [godotengine/godot-docs#7218]
Until recently I was just compiling Godot without any debug tools because I did not know how to set them up. Recently I noticed the excellent explaination in the [docs](https://docs.godotengine.org/en/stable/contributing/development/configuring_an_ide/visual_studio_code.html). However for me vscode still complained about wrong imports and IntelliSense did not work properly (compiling and debugging worked though). I was able to solve it by using `"compiledb=yes"` and the following C/C++ configuration file
```json
{
    "configurations": [
        {
            ...
            "compileCommands": "compile_commands.json"
        }
    ],
    "version": 4
}
```
Not quite sure wether this applies only to Windows but I believe it might be worth a note in the docs.

**Comment by YuriSizov** [comment]
> Not quite sure wether this applies only to Windows but I believe it might be worth a note in the docs.

This is specific to the toolchain that you use. For example this file would always generate empty to me, and I use MSVC. What does work is having a `c_cpp_properties.json` with these lines added:

```
            "includePath": [
                "${workspaceFolder}/platform/windows/**",
                "${workspaceFolder}/**"
            ],
```

Also worth having defines in there to control which code blocks are highlighted in respect to the pre-processor:

```
            "defines": [
                ...
                "TOOLS_ENABLED",
                "TESTS_ENABLED",
                "DEBUG_ENABLED"
            ],
```
