### ISSUE TITLE
Click and Deploy image reference is wrong

### ISSUE THREAD

**Issue by kevinloustau** [godotengine/godot-docs#7226]
**Your Godot version:**
v4.0.2.stable.official [7a0977ce2]

**Issue description:**
The icons from the editor and the doc are differents:

Doc:
<img width="206" alt="image" src="https://user-images.githubusercontent.com/4235617/234413311-a2eea740-a214-4ab8-aeb7-031e0a5588f3.png">

Editor:
<img width="183" alt="image" src="https://user-images.githubusercontent.com/4235617/234413415-04ab3346-7562-400b-b99f-1c99f863e52c.png">

**URL to the documentation page:**
https://docs.godotengine.org/en/stable/tutorials/export/one-click_deploy.html

**Comment by jynus** [comment]
![remote_debug](https://user-images.githubusercontent.com/8576860/235558898-a9b7d6e5-5bb0-4fcb-a578-5a5c3d9ed9fd.png)

I wonder if we should keep calling it one-click deploy, given it now requires 2 clicks :-D.
