### ISSUE TITLE
Outdated languages use incorrect "stable" version identifier

### ISSUE THREAD

**Issue by winston-yallow** [godotengine/godot-docs#7233]
**Your Godot version:**
4.0

**Issue description:**
The docs for some languages (at least for german) are outdated, which would be fine in itself if it wouldn't say "stable".
I propose to name it "3.x" or whatever specific version it is for. This would also improve search engine results for the docs in germany. Currently, search engines like google will only show the german outdated version of the docs when a class exists in both 3.x and 4.x. When changing the german docs label to "3.x" this will lead to two distinct URLs for the same class, so both the up-to-date english result and the outdated german result will be shown.

**URL to the documentation page:**
https://docs.godotengine.org/de/stable/

**Comment by YuriSizov** [comment]
We are discussing ways to improve the branch naming scheme. But in this case this is technically "correct", as we simply haven't switched the translations to 4.0 yet. We should do it, and then fixes and updates can refresh everything.

**Comment by winston-yallow** [comment]
That sounds like a good plan, I mostly care for improving search results. As it currently is I have different Firefox containers for different google settings, so I always need to switch to the "Godot Google" container to have usable search results that force exclude anything except English. People new to the engine probably won't even notice the issue until they try to use the code :sweat_smile:

**Comment by akien-mga** [comment]
This is fixed.
