### ISSUE TITLE
Dodge the Creeps Tutorial

### ISSUE THREAD

**Issue by andersonmodeste** [godotengine/godot-docs#7245]
4.0

I am using godot docs. The mobs are not animating in the main screen (they animate when tested in the mob scene AND
the mobs are colliding with each other despite de-selecting 1 in mask in collision of the mob node.

code used: func _ready()
                        var mob_types = $AnimatedSprite2D.sprite_frames.get_animation_names()
                        $AnimatedSprite2D.play(mob_types[randi() % mob_types.size()])

(https://docs.godotengine.org/en/stable/getting_started/first_2d_game/04.creating_the_enemy.html):

If you know how to fix the issue you are reporting please
consider opening a pull request. We provide a tutorial on
using git here: https://docs.godotengine.org/en/stable/community/contributing/pr_workflow.html,
writing documentation at https://docs.godotengine.org/en/stable/community/contributing/docs_writing_guidelines.html
and contributing to the class reference here: https://docs.godotengine.org/en/stable/community/contributing/updating_the_class_reference.html

**Comment by AV77** [comment]
This section of the docs is correct(at least on the stable branch), I completed it just a couple of days ago.

**Comment by andersonmodeste** [comment]
Well I'm not sure what my issue is. I've just completed the HUD. When I test, I get no animation for the creeps and they keep colliding. My version is recent. Actually I just realised it's 4.0.2. Perhaps I'll just delete and start over from the creation of the mobs since that's the issue.

Sent from Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by Piralein** [comment]
Could you resolve the issue or is it still a problem?
If you have any suggestions to improve this section feel free to share them as well.

**Comment by Piralein** [comment]
closing as stale.
Feel free to open a new issue, if you encounter a problem with the documentation.
