### ISSUE TITLE
Old deg2rad function still used in 4.0 documentation

### ISSUE THREAD

**Issue by honzah70** [godotengine/godot-docs#7247]
**Your Godot version:**
4.0

**Issue description:**
Using old function deg2rad instead of new deg_to_rad. Below are pages still containing deg2rad.

**URLs to the documentation pages:**
https://docs.godotengine.org/en/stable/tutorials/scripting/evaluating_expressions.html
https://docs.godotengine.org/en/stable/getting_started/first_2d_game/05.the_main_game_scene.html
https://docs.godotengine.org/en/latest/tutorials/2d/custom_drawing_in_2d.html
https://docs.godotengine.org/en/latest/tutorials/performance/using_servers.html

**Comment by jynus** [comment]
Thank you for the report, @honzah70. After the merged patch, it should be fixed now.
