### ISSUE TITLE
Sidebar categories are not expanded on the latest versions of build dependencies

### ISSUE THREAD

**Issue by comminux** [godotengine/godot-docs#7250]
**Your Godot version:**
v4.0.2.stable.official (Steam)

**Issue description:**
I found that as a result of building documentation for offline use, none of the sidebar categories can expand for the master and 4.0 branches. 

Using git bisect, a problematic commit was discovered: https://github.com/godotengine/godot-docs/commit/b68c505789bdbd78b2d4f563cc9534212d335a40

There are no such problems with the documentation from the 3.5 branch.
To build documentation, I use pip with up-to-date versions of the required dependencies:
`pip install sphinx_copybutton sphinxext-opengraph sphinx-notfound-page sphinx_tabs sphinx_rtd_theme sphinx`

And the following command:
`sphinx-build -j 12 -b html . .\build\master\`

Chrome DevTools Console:
```
custom.js?6:241 Uncaught ReferenceError: $ is not defined
    at custom.js?6:241:1
(anonymous) @ custom.js?6:241
index.html:10047 Uncaught ReferenceError: jQuery is not defined
    at index.html:10047:7
(anonymous) @ index.html:10047
```

**UPD.** Using fixed versions of packages solves the problem.
`pip install "sphinx_copybutton==0.5.1" "sphinxext-opengraph==0.7.5" "sphinx-notfound-page==0.8.3" "sphinx-tabs==3.4.0" "sphinx_rtd_theme==1.1.1" "sphinx==4.4.0"`

Now I don't know if I need to leave this task open?

**URL to the documentation page:**
All pages are affected by this

**Comment by adamscott** [comment]
Did you try updating your requirements with `pip3 install -r requirements.txt`?

**Comment by comminux** [comment]
I directly installed the latest version packages without specifying the required versions from requirements.txt
Thanks to you, I now know this way to install the required dependencies.

**Comment by adamscott** [comment]
But using the latest requirements, I cannot reproduce on my side, unfortunately.

**Comment by comminux** [comment]
I cleaned up the local pip storage and reinstalled all the required dependencies. The problem with building on current versions of batch dependencies happens both on Arch Linux with python 3.10 and on Windows with python 3.11.

My package versions:
```
godot-docs> pip list
Package                       Version
----------------------------- ---------
alabaster                     0.7.13
Babel                         2.12.1
certifi                       2022.12.7
charset-normalizer            3.1.0
colorama                      0.4.6
contourpy                     1.0.7
cycler                        0.11.0
docutils                      0.18.1
fonttools                     4.39.3
idna                          3.4
imagesize                     1.4.1
Jinja2                        3.1.2
kiwisolver                    1.4.4
MarkupSafe                    2.1.2
matplotlib                    3.7.1
numpy                         1.24.3
packaging                     23.1
Pillow                        9.5.0
pip                           23.1.2
Pygments                      2.15.1
pyparsing                     3.0.9
python-dateutil               2.8.2
requests                      2.29.0
six                           1.16.0
snowballstemmer               2.2.0
Sphinx                        6.2.1
sphinx-copybutton             0.5.2
sphinx-notfound-page          0.8.3
sphinx-rtd-theme              1.2.0
sphinx-tabs                   3.4.1
sphinxcontrib-applehelp       1.0.4
sphinxcontrib-devhelp         1.0.2
sphinxcontrib-htmlhelp        2.0.1
sphinxcontrib-jquery          4.1
sphinxcontrib-jsmath          1.0.1
sphinxcontrib-qthelp          1.0.3
sphinxcontrib-serializinghtml 1.1.5
sphinxext-opengraph           0.8.2
urllib3                       1.26.15
```

**Comment by mhilbrunner** [comment]
I could only reproduce this once with outdated dependencies; updating them via `requirements.txt` *and doing a full clean rebuild* in Sphinx afterwards fixed it. (Delete the output folder, and/or run `make clean`)

**Comment by comminux** [comment]
I will close this issue, because the problem is inherently solved by using requirements.txt .
However, it seems to me that incompatibility with the latest versions of dependencies from the pip repository still remains.
