### ISSUE TITLE
StartButton size

### ISSUE THREAD

**Issue by tacopill** [godotengine/godot-docs#7251]
**Your Godot version:**
4.0.2.stable.official [7a0977ce2]

**Issue description:**
StartButton details doesn't tell if I should keep the same size for the button, make it bigger or smaller. 

So, I'm using the default size and that's kind of tiny, and doesn't match the picture in the tutorial

![image](https://user-images.githubusercontent.com/50280385/235363445-4ed7b9a0-7ecf-4e29-bb9d-5955ea46726a.png)

**URL to the documentation page:**
https://docs.godotengine.org/en/stable/getting_started/first_2d_game/06.heads_up_display.html#startbutton

**Comment by jynus** [comment]
Hi,

Re:

> I'm using the default size and that's kind of tiny, and doesn't match the picture in the tutorial

Please note that the tutorial suggests at the beginning to setup a project size of 480x720 at https://docs.godotengine.org/en/stable/getting_started/first_2d_game/01.project_setup.html :

> This game is designed for portrait mode, so we need to adjust the size of the game window. Click on Project -> Project Settings to open the project settings window and in the left column, open the Display -> Window tab. There, set "Viewport Width" to 480 and "Viewport Height" to 720.

and I think it shows it clearly how to do it on a screenshot on that same page.

Regarding sizes, I agree that the tutorial is not clear enough. Even if the tutorial intended for users to "adjust it at will", it should at least provide some guidance. As it is now, it says to adjust the font, but not the size everywhere. UI is not necessarily intuitive for new users. I believe the intention was to override all 3 visual Nodes. I will try to send a more polished set of suggested instructions, even if it is ultimately left to the reader's liking.

In particular, this part is incomplete:

> Once you've done this on the ScoreLabel, you can click the down arrow next to the Font property and choose "Copy", then "Paste" it in the same place on the other two Control nodes. Set the "Font Size" property of the ScoreLabel under "Theme Overrides > Font Sizes". A setting of 64 works well
