### ISSUE TITLE
[Your first 3D Game > Character animation > Animating the mobs] Copy animation UI

### ISSUE THREAD

**Issue by MichaelNZ404** [godotengine/godot-docs#7257]
**Your Godot version:**
v4.0.2.stable.official [7a0977ce2]

**Issue description:**
The section states to use _Animation > Copy_, and _Animation > Paste_. From what I can tell these copy and paste options do not exist under the Animation menu (I see "New", "Manage Animations", "Duplicate", and so forth but no copy or paste)

![image](https://user-images.githubusercontent.com/4734163/235428464-f9e02f03-c32d-4eba-8b8f-644ce54b132b.png)

I was able to complete the tutorial by copying the entire _AnimationPlayer_ node from _player.tscn_ to _mob.tscn_

**URL to the documentation page:**
https://docs.godotengine.org/en/stable/getting_started/first_3d_game/09.adding_animations.html#animating-the-mobs

**Comment by Alex2782** [comment]
Godot v4.2.dev4

`Copy` and `Paste`: I was able to run it in the Manage Animations window.
![image](https://github.com/godotengine/godot-docs/assets/41921395/7015ff58-5522-45df-acb8-10b075283e9c)


**Copy**

![Bildschirmfoto 2023-09-09 um 00 13 49](https://github.com/godotengine/godot-docs/assets/41921395/e85a187d-9f84-4957-a13f-7cb7e1b9d070)

**Paste**

![Bildschirmfoto 2023-09-09 um 00 14 48](https://github.com/godotengine/godot-docs/assets/41921395/245648c0-7876-4ba2-b2df-74f2c3bf5f9d)

**Comment by skyace65** [comment]
Fixed by #8955.
