### ISSUE TITLE
Potential mistatement in the GDExtension tutorial

### ISSUE THREAD

**Issue by MichaelMacha** [godotengine/godot-docs#7261]
**Your Godot version:**
4.0.2

**Issue description:**
Unclear, potentially incorrect statement on GDExtension page.

**URL to the documentation page:**
https://docs.godotengine.org/en/stable/tutorials/scripting/gdextension/gdextension_cpp_example.html

Near the end, we have this text:

> Here, our ADD_SIGNAL macro can be a single call first taking the signals name, then having pairs of the type specifying the parameter name and the value of each parameter we'll send along with this signal.

This specifies, if I'm understanding it, that `PropertyInfo` contains parameters which are:

1.  the parameter name
2.  the value of each parameter

In appearance, its parameters specify this:

1. the parameter name
2. the _type_ of each parameter

The C++ line in question:

`    ADD_SIGNAL(MethodInfo("position_changed", PropertyInfo(Variant::OBJECT, "node"), PropertyInfo(Variant::VECTOR2, "new_pos")));`

Notably, it also specifies parameters in the reverse order in the text, but this is minor.

`PropertyInfo` seems to say nothing about the property value itself, likely intentionally; as this is done later with `emit_signal` and may be different each time.

I would offer to correct it myself, but as I am currently learning from this tutorial, I could be wrong and it might be inappropriate. That said, I was hung up on the statement for a little while, and it's probably a typo.

Thank you!

**Comment by paddy-exe** [comment]
Hey @MichaelMacha Thanks for raising this issue! Yes indeed it seems like I accidentally left a misunderstanding in that section. The sentence rather applies to the GDScript exposed signal and not the C++ macro. Also the parameter name and the type of the parameter are switched as well. I'd appreciate it if you want to contribute and fix this issue.

**Comment by MichaelMacha** [comment]
Done, and awaiting review. I described it as I understood it, if I'm correct then this should take care of it!
