### ISSUE TITLE
"The path to the Blender executable" is unclear

### ISSUE THREAD

**Issue by andreymal** [godotengine/godot-docs#7270]
["Importing .blend files directly within Godot"](https://docs.godotengine.org/en/4.0/tutorials/assets_pipeline/importing_scenes.html#importing-blend-files-directly-within-godot) says:

>configure the path to the Blender executable in the Editor Settings (Filesystem > Import > Blender > Blender 3 Path).

"the path to the Blender executable" means that I should set `/usr/bin/blender`. However, when I set it, Godot 4.0.2 prints a warning:

>modules/gltf/register_types.cpp:72 - Blend file import is enabled, but the Blender path doesn't point to an accessible directory. Blend files will not be imported.

"directory"??? The documentation doesn't say anything about directories!

But okay, when I set `/usr/bin`, importing .blend files works.

I think the documentation should say something like:

>configure the path to **the directory containing** the Blender executable in the Editor Settings (Filesystem > Import > Blender > Blender 3 Path).

(By the way [1], I don't understand why Godot requires a directory instead of an executable file, but that's probably a topic for another issue)

(By the way [2], autodetecting doesn't work for some reason, but that's probably a topic for yet another issue)

**Comment by Jazztache** [comment]
This also occurs on the current source-compiled build of Godot. I get this outputted as part of the console (KDE Konsole) output.

Neofetch:
```
OS: Arch Linux x86_64 
Kernel: 6.3.9-arch1-1 
Packages: 1648 (pacman) 
Shell: fish 3.6.1 
Resolution: 1920x1080, 1920x1080, 1920x1080 
DE: Plasma 5.27.6 
WM: KWin 
Theme: [Plasma], Breeze [GTK2/3] 
Icons: [Plasma], breeze-dark [GTK2/3] 
Terminal: konsole 
Terminal Font: LiterationMono Nerd Font Mono 14 
CPU: Intel i7-10700K (16) @ 5.100GHz 
GPU: NVIDIA GeForce RTX 2060 
Memory: 6136MiB / 15914MiB
```

Godot Output:
```
Godot Engine v4.1.rc.custom_build.46424488e - https://godotengine.org
OpenGL API 3.3.0 NVIDIA 535.54.03 - Compatibility - Using Device: NVIDIA - NVIDIA GeForce RTX 2060
 
Editing project: /ssd/Testing/SVGTestingGodot
Godot Engine v4.1.rc.custom_build.46424488e - https://godotengine.org
Vulkan API 1.3.242 - Forward+ - Using Vulkan Device #0: NVIDIA - NVIDIA GeForce RTX 2060
 
WARNING: Blend file import is enabled in the project settings, but no Blender path is configured in the editor settings. Blend files will not be imported.
     at: _editor_init (modules/gltf/register_types.cpp:73)
kf.service.services: KApplicationTrader: mimeType "x-scheme-handler/file" not found
kf.kio.workers.trash: Directory "/hdd/.Trash-1000" exists but didn't pass the security checks, can't use it
kf.kio.workers.file: copy() QUrl("file:///home/jazztache/Models/Blender Donut/Donut_1723Fri23Jun23.blend") to QUrl("file:///ssd/Testing/SVGTestingGodot/Donut_1723Fri23Jun23.blend") mode= 420
kf.kio.workers.file: the file doesn't have any xattr
```

**Comment by Calinou** [comment]
> https://github.com/godotengine/godot/blob/f8dbed4d0aef09ae7f4e3d66213268dba23a31d6/modules/gltf/editor/editor_scene_importer_blend.cpp#L270-L276

This is the part that does automatic detection: https://github.com/godotengine/godot/blob/f8dbed4d0aef09ae7f4e3d66213268dba23a31d6/modules/gltf/editor/editor_scene_importer_blend.cpp#L270-L276

It only works if `blender` is in the system `PATH`, and it does *not* work if either Godot or Blender are installed using a Flatpak.

**Comment by andreymal** [comment]
Since https://github.com/godotengine/godot/pull/85448 is merged, this change should be reverted now 🙃

**Comment by ChildishGiant** [comment]
As of v4.2.2.stable.arch_linux this is still the case, `/usr/bin/blender` errors but `/usr/bin/` works.
