### ISSUE TITLE
OnMobTimerTimeout C# Script do not work

### ISSUE THREAD

**Issue by FlyGameDev** [godotengine/godot-docs#7285]
**Your Godot version:*4*

**Issue description:*The C# script for OnMobTimerTimeout method don't work and throw this message: 

Line error: Mob mob = MobScene.Instantiate<Mob>();

Main.cs:38 @ void Main.OnMobTimerTimeout(): System.NullReferenceException: Object reference not set to an instance of an object.
                 System.NullReferenceException
                 Main.cs:38 @ void Main.OnMobTimerTimeout()
				 Main.cs:38 @ void Main.OnMobTimerTimeout()
                 Main_ScriptMethods.generated.cs:45 @ Boolean Main.InvokeGodotClassMethod(Godot.NativeInterop.godot_string_name& , Godot.NativeInterop.NativeVariantPtrArgs , Godot.NativeInterop.godot_variant& )
                 CSharpInstanceBridge.cs:24 @ Godot.NativeInterop.godot_bool Godot.Bridge.CSharpInstanceBridge.Call(IntPtr , Godot.NativeInterop.godot_string_name* , Godot.NativeInterop.godot_variant** , Int32 , Godot.NativeInterop.godot_variant_call_error* , Godot.NativeInterop.godot_variant* )

*

**URL to the documentation page:*https://docs.godotengine.org/en/stable/getting_started/first_2d_game/05.the_main_game_scene.html*

**Comment by raulsntos** [comment]
If `MobScene` is null, make sure it is assigned.

![image](https://user-images.githubusercontent.com/3903059/236440707-5a60c8ff-756f-4884-8540-0bb7d52e9fcf.png)

**Comment by FlyGameDev** [comment]
Thank you, it worked perfectly.
