### ISSUE TITLE
3D ->Introduction to 3D -> 3D viewport -> Default environment still acts as if new projects came with a default environment resource

### ISSUE THREAD

**Issue by Dancovich** [godotengine/godot-docs#7304]
This is about this page:
https://docs.godotengine.org/en/stable/tutorials/3d/introduction_to_3d.html#default-environment

This section gives the impression new projects still come with a default_env.tres file containing a default environment, and that users are expected to work with this default environment. The screenshot even shows the file in the FileSystem tab.

I believe this section should be removed. Also, even though the section about Environment does mention the WorldEnvironment node, I believe it would be good if it also linked to the [Environment and post-processing](https://docs.godotengine.org/en/stable/tutorials/3d/environment_and_post_processing.html) section, which is where the user learns about the relationship between the WorldEnvironment node, the Camera3D node and, overall, how to setup environments in 3D scenes.

**Comment by travisby** [comment]
The same exists for the 2d page https://docs.godotengine.org/en/stable/getting_started/first_2d_game/01.project_setup.html

The screenshot suggests that I have:
* art
* fonts
* default_env.tres
* icon.png
* icon.png.import
* project.godot

files/directories, while in stead I have:

* .
* ./art
* ./.gitattributes
* ./.godot
.* /.gitignore
* ./fonts
* ./project.godot
* ./icon.svg
* ./icon.svg.import

This was with 4.1!  It looks like the ENV file does not exist at all, and the extension for the icon has been replaced with svg.
