### ISSUE TITLE
Control and derived class common information.

### ISSUE THREAD

**Issue by ghost** [godotengine/godot-docs#7320]
v4.0.2.stable.official [7a0977ce2]

  The disclaimer at the end of the description for the Control class of:

Note: Theme items are not Object properties. This means you can't access their values using Object.get() and Object.set(). Instead, use the get_theme_* and add_theme_*_override methods provided by this class.

  should really be added to the end of the description for every class that is derived from Control so that the user is clear that this is where the theme information can be obtained/changed for the Control concerned without having to know to read the Control class documentation specifically.  The text maybe should be amended to indicate in the current class or a base class thereof.

https://docs.godotengine.org/en/stable/classes/class_control.html

**Comment by YuriSizov** [comment]
I don't think this is a good idea. The principles of OOP suggest that extending classes inherit all behavior of extended classes, unless they override it. Following your suggestion, we need to duplicate every bit of information from extended classes in their extending children. That's not going to improve documentation for the reader. And adding only some of the details is rather arbitrary and caters to nobody's needs.

So I'm going to close this, as it goes against our best practices.
