### ISSUE TITLE
NavigationPolygon Outdated tutorials

### ISSUE THREAD

**Issue by wkppp** [godotengine/godot-docs#7325]
**Your Godot version:**
Godot 4.0.2
**Issue Description:**
Outdated tutorials
**URL to the documentation page:**
https://docs.godotengine.org/en/stable/classes/class_navigationpolygon.html

**Comment by smix8** [comment]
What parts of that page should be outdated? Or are you referring to the linked "2D Navigation Demo" in the Godot asset library?
