### ISSUE TITLE
Procedual 2D NavigationMesh: Unexpected "Identifier" in class body

### ISSUE THREAD

**Issue by wkppp** [godotengine/godot-docs#7326]
**Your Godot version:**
Godot 4.0.2
**Issue description:**
When I run the code I copied in the docs I am getting this error and no region is created. I am trying to use the Procedual 2D NavigationMesh
Line 6:Unexpected "Identifier" in class body.
Line 15:Unexpected "Identifier" in class body.
Line 16:Unexpected "Identifier" in class body.
Line 18:Unexpected "Identifier" in class body.
Here's the code:
extends Node2D

var new_2d_region_rid: RID = NavigationServer2D.region_create()

var default_2d_map_rid: RID = get_world_2d().get_navigation_map()
NavigationServer2D.region_set_map(new_2d_region_rid, default_2d_map_rid)

var new_navigation_polygon: NavigationPolygon = NavigationPolygon.new()
var new_outline: PackedVector2Array = PackedVector2Array([
    Vector2(0.0, 0.0),
    Vector2(50.0, 0.0),
    Vector2(50.0, 50.0),
    Vector2(0.0, 50.0),
])
new_navigation_polygon.add_outline(new_outline)
new_navigation_polygon.make_polygons_from_outlines()

NavigationServer2D.region_set_navigation_polygon(new_2d_region_rid, new_navigation_polygon)

**Comment by smix8** [comment]
That example is a code snippet, it is not a runnable script.

A runnable script requires function bodies where you would integrate parts of that code snippet and the error tries to tell you that.

**Comment by Piralein** [comment]
Closing per above comment.

If you have a suggestion for improving this section or found a bug with the code snippets provided, feel free to open a new issue about it.
