### ISSUE TITLE
Add documentation of enum types

### ISSUE THREAD

**Issue by feois** [godotengine/godot-docs#7327]
**Your Godot version:** v4.0.2

**Issue description:** There doesn't seem to be any documentation of enum types' methods (`keys()`, `values()`, etc.). I don't even know that enums have methods until I google it.

**URL to the documentation page (if already existing):**

**Comment by YuriSizov** [comment]
Indeed, enums don't have any methods because they don't really exist as their own entity. I think we can simply add a link to the dictionary documentation with that line, so it's clearer you can use those in this case.
