### ISSUE TITLE
how do i track vr headset

### ISSUE THREAD

**Issue by Catlover19** [godotengine/godot-docs#7331]
what code plz i'm doing this on chromebook

**Comment by and-rad** [comment]
You should ask this on one of the support channels like Discord or Reddit. This repository is for issues related to the official Godot documentation pages.

**Comment by Piralein** [comment]
As already stated, this repository is for issues related to the documentation of Godot.
Please see [Godot Community Channels](https://godotengine.org/community/) to get help implementing VR features.

You can find more information about setting up XR in Godot in the [Godot documentation - XR section](https://docs.godotengine.org/en/stable/tutorials/xr/index.html)
