### ISSUE TITLE
"Using Signals" in Godot Engine stable documentation giving incorrect instructions

### ISSUE THREAD

**Issue by minorthreatmikey** [godotengine/godot-docs#7347]
Your Godot version: 4.0.2

Issue description: I'm trying to follow documentation and got lost when when getting to signals section. Here is what it says:

`To add a button to our game, we will create a new main scene which will include both a button and the Sprite2D.tscn scene that we scripted in previous lessons.`

It then proceeds to show a picture of the Sprite2D.tscn file being dragged to the right spot. However, I don't have a Sprite2D.tscn file in my filesystem dock. I only have a 2Sprite2D.gd. This script was created on a node, not a scene. Did I do something wrong or is this a bug? My frustration on this part made me lose interest and skip ahead to first 2D game section.

URL to the documentation page: https://docs.godotengine.org/en/stable/getting_started/step_by_step/signals.html#scene-setup

**Comment by Piralein** [comment]
The tutorial assumes you started with the [Creating your first script](https://docs.godotengine.org/en/stable/getting_started/step_by_step/scripting_first_script.html) page and then did the [Listening to player input](https://docs.godotengine.org/en/stable/getting_started/step_by_step/scripting_player_input.html) page, before this one.

A scene is a collection of nodes, which in turn have scripts attached to them.

The page could be more clear about this, or be rewriten to not rely on the preview tutorial this much.

**Comment by minorthreatmikey** [comment]
Yes, that is what I did.

Going back to the scripts page, I now see the line that says "Save the scene as sprite_2d.tscn if you haven't already". I missed have missed that important step as it was in the middle of the "Hello World" part that you are told to delete.

Thanks!
