### ISSUE TITLE
Typo in Shadow documentation

### ISSUE THREAD

**Issue by zixin96** [godotengine/godot-docs#7357]
**Your Godot version:**
4.0
**Issue description:**
 
Shouldn't one of the bias be Shadow bias instead? 

> Increasing Shadow Normal Bias does not cause as much peter-panning as increasing Shadow Normal Bias

Thanks. 

**URL to the documentation page:**
https://docs.godotengine.org/en/stable/tutorials/3d/lights_and_shadows.html

**Comment by clayjohn** [comment]
Yes, the second one should be "shadow bias" not "shadow normal bias"
