### ISSUE TITLE
Physics Introduction: Use RigidBody2D C# Code Example incorrectly casts type PhysicsDirectBodyState2D

### ISSUE THREAD

**Issue by VestedGrammar** [godotengine/godot-docs#7358]
**Your Godot version:*
4.0 Stable mono
**Issue description:**

The C# example code contains 

`public override void _IntegrateForces(Physics2DDirectBodyState state)`

pretty sure that this should be

`public override void _IntegrateForces(PhysicsDirectBodyState2D state)`

**URL to the documentation page:**

https://docs.godotengine.org/en/stable/tutorials/physics/physics_introduction.html#using-rigidbody2d

If you know how to fix the issue you are reporting please
consider opening a pull request. We provide a tutorial on
using git here: https://docs.godotengine.org/en/stable/community/contributing/pr_workflow.html,
writing documentation at https://docs.godotengine.org/en/stable/community/contributing/docs_writing_guidelines.html
and contributing to the class reference here: https://docs.godotengine.org/en/stable/community/contributing/updating_the_class_reference.html

**Comment by raulsntos** [comment]
You are correct, the class was renamed in 4.0 (see https://github.com/godotengine/godot/pull/37361). Feel free to open a pull request to update it :slightly_smiling_face:.

**Comment by VestedGrammar** [comment]
Not overly familiar with GIT, but : https://github.com/godotengine/godot-docs/pull/7360

I think I did a pull request?

**Comment by VestedGrammar** [comment]
Pull request was approved.
