### ISSUE TITLE
Offline documentation for Godot 4 not working

### ISSUE THREAD

**Issue by brokolja** [godotengine/godot-docs#7366]
https://docs.godotengine.org/en/stable/# for Godot 4 mentions offline documentation as ePub or in DevDocs but the downloadable epub contains errors only (nothing but errors) and DevDocs has no Godot 4 but <=3.5  docs.

**Comment by Calinou** [comment]
> [docs.godotengine.org/en/stable/#](https://docs.godotengine.org/en/stable/#) for Godot 4 mentions offline documentation as ePub or in DevDocs but the downloadable epub contains errors only (nothing but errors) and DevDocs has no Godot 4 but <=3.5 docs.

Does the HTML download work? Which apps did you try to open the ePub file? The ePub file is quite large and won't open correctly on old/low-end devices.

**Comment by stevenctl** [comment]
The HTML download 404s

**Comment by Treeway7** [comment]
The HTML download works just fine. Not sure about the ePub download, I can't get it to open.
However, as of writing, I'm using Godot 4.1, and the docs on `master` are for 4.2. DevDocs has no option for any 4.X versions of the docs.

**Comment by hsandt** [comment]
At least the instructions using Preferences > check Godot version won't work as only v2 and v3 are displayed:

![image](https://github.com/godotengine/godot-docs/assets/1067772/21fa340e-b84b-4cc9-9f5f-2a33d98a8020)

**Comment by skyace65** [comment]
EPUB's of the docs were fixed by #7498. The DevDocs link should be removed though, I assume no one has any interest in updating it.
