### ISSUE TITLE
CharacterBody2D method get_slide_collision() has a buggy GDScript code example

### ISSUE THREAD

**Issue by golddotasksquestions** [godotengine/godot-docs#7374]
**Your Godot version:**
Godot 4.0.2

**Issue description:**

```swift
for i in get_slide_collision_count():
    var collision = get_slide_collision(i)
    print("Collided with: ", collision.collider.name)
```

The KinematicBody2D unfortunately does not have a collision property anymore in Godot4 the the user has to use a method to get the collider.

```swift
for i in get_slide_collision_count():
    var collision = get_slide_collision(i)
    print("Collided with: ", collision.get_collider().name)
```

**URL to the documentation page:**
https://docs.godotengine.org/en/stable/classes/class_characterbody2d.html#class-characterbody2d-method-get-slide-collision

**Comment by yashmistri** [comment]
[https://github.com/godotengine/godot/blob/master/doc/classes/CharacterBody2D.xml](url)
[https://github.com/godotengine/godot-docs/blob/master/classes/class_characterbody2d.rst](url)
my understanding is that the class documentation in the godot_docs repo is generated by XML files in the godot repo.
in both the linked godotengine/godot XML file and godotengine/godot-docs RST file it seems the code example is correct

[https://docs.godotengine.org/en/latest/classes/class_characterbody2d.html#class-characterbody2d-method-get-slide-collision](url)
in the "latest" version of the docs the code example is correct
in "stable" and "4.0" it's incorrect

**Comment by golddotasksquestions** [comment]
@yashmistri Thanks, I guess this means it will be changed with the next update, so I can close.
