### ISSUE TITLE
Tween cheat sheet needs updating

### ISSUE THREAD

**Issue by KoBeWi** [godotengine/godot-docs#7405]
**Your Godot version:**
4.1 master

**Issue description:**
https://github.com/godotengine/godot/pull/76899 added a new TRANS_SPRING to Tween, so the cheat sheet linked in the documentation needs to be updated. It can be generated by https://github.com/wandomPewlin/godotTweeningCheatSheet (the tool was not officially updated to Godot 4 yet, but new code can be found in an issue)

**URL to the documentation page (if already existing):**
https://raw.githubusercontent.com/godotengine/godot-docs/master/img/tween_cheatsheet.png

**Comment by spikeyarmaku** [comment]
It needs updating again. The URL currently throws error 404.

**Comment by KoBeWi** [comment]
The link is up-to-date in latest version (4.1)
