### ISSUE TITLE
Warning on tutorial page for importing translations is out of date

### ISSUE THREAD

**Issue by LaurenOopsum** [godotengine/godot-docs#7413]
Your Godot version: 4.0

Issue description:

The tutorials documentation page for importing translations warns that there is no native way to save an Excel file as a UTF-8 encoded CSV. However, when I use Save As in Excel I do have the option in the drop-down to choose a UTF-8 encoded CSV file format. The link on the documentation page that confirms this as an issue and offers a workaround was last updated about 6 years ago. I'm thinking Excel has updated since then and this warning is likely no longer needed. 

URL to the documentation page:

https://docs.godotengine.org/en/stable/tutorials/assets_pipeline/importing_translations.html

**Comment by MisoMosiSpy** [comment]
Yes, it is indeed supported in latest excel, I will raise the pull-request with the fix.
![image](https://github.com/godotengine/godot-docs/assets/52410428/d8674734-ccc3-42f5-9e07-e798c43c8438)
