### ISSUE TITLE
CTRL + D : Duplicate : Shortcut not working

### ISSUE THREAD

**Issue by MelPeslier** [godotengine/godot-docs#7415]
**Your Godot version:**

**Issue description: CTRL + D Shortcut not working**

**URL to the documentation page: https://docs.godotengine.org/en/stable/tutorials/editor/default_key_mapping.html**

Can't use CTRL + D shortcut

**Comment by MisoMosiSpy** [comment]
I was able to use Ctrl+D successfully in Scene and File system dock. Where do you see this issue?

**Comment by MelPeslier** [comment]
I can't ctrl + d lines of code

**Comment by MisoMosiSpy** [comment]
> I can't ctrl + d lines of code

Yes that is correct, for some reason the correct shortcut for it is "Ctrl + Shift + D".
