### ISSUE TITLE
Godot docs are freezing due to a long running task - scrolling freezes every few seconds.

### ISSUE THREAD

**Issue by jasonjmcghee** [godotengine/godot-docs#7432]
**Your Godot version:**
Godot 4.0 docs
Chrome 112
Windows 11

**Issue description:**
The Godot docs are freezing due to a long task running - scrolling freezes every few seconds.

Possibly related to algolia?
![image](https://github.com/godotengine/godot-docs/assets/1522149/d4bcf9c8-c32d-4f20-915c-8ab532f8511e)

**URL to the documentation page:**
https://docs.godotengine.org/en/stable/tutorials/shaders/compute_shaders.html

**Chrome Profile:**
[godot_docs_slowdown.zip](https://github.com/godotengine/godot-docs/files/11583321/godot_docs_slowdown.zip)

**Comment by tetrapod00** [comment]
Can this be closed, since Algolia was removed in https://github.com/godotengine/godot-docs/pull/8568?
