### ISSUE TITLE
Documentation on android custom builds is outdated.

### ISSUE THREAD

**Issue by liyaowhen** [godotengine/godot-docs#7437]
4.02
Documentation on android custom builds is outdated

(https://docs.godotengine.org/en/stable/tutorials/export/android_custom_build.html)

I was trying to implement Admob on my game when I got stumped where it said that I had to enable "Use Custom Build". But when I looked online, supposedly "Use Custom Build" was renamed to "Use Gradle"

**Comment by skyace65** [comment]
This was fixed by #7884.
