### ISSUE TITLE
Access to unique nodes isn't limited by it's scene

### ISSUE THREAD

**Issue by dustdfg** [godotengine/godot-docs#7444]
**Your Godot version:**
4.0.1 (AppImage downloaded form site) Linux Debian 10

**Issue description:**
 Docs says that unique nodes are limited by it's scene but I found that no. My project that works fine https://github.com/dustdfg/unique_nodes_example_godot

**URL to the documentation page:**
https://docs.godotengine.org/en/stable/tutorials/scripting/scene_unique_nodes.html

P.S I even don't know if I need to place it here but I don't know where... I am sorry for it

**Comment by dustdfg** [comment]
https://github.com/godotengine/godot/issues/66536

**Comment by YuriSizov** [comment]
Yes, https://github.com/godotengine/godot/issues/66536 is a better place to discuss the issue.
