### ISSUE TITLE
typo in NavigationAgent2D and NavigationAgent3D

### ISSUE THREAD

**Issue by yashmistri** [godotengine/godot-docs#7445]
**Your Godot version:**
4.0

**Issue description:**
typo in description of property 'target_desired_distance':
'to' should be 'too'
'cause' should be 'because'
'a repath loop' can be 'an infinite loop'
both 2D and 3D have the same description

**URL to the documentation page:**
https://docs.godotengine.org/en/4.0/classes/class_navigationagent2d.html#class-navigationagent2d-property-target-desired-distance
https://docs.godotengine.org/en/4.0/classes/class_navigationagent3d.html#class-navigationagent3d-property-target-desired-distance
If you know how to fix the issue you are reporting please
consider opening a pull request. We provide a tutorial on
using git here: https://docs.godotengine.org/en/stable/community/contributing/pr_workflow.html,
writing documentation at https://docs.godotengine.org/en/stable/community/contributing/docs_writing_guidelines.html
and contributing to the class reference here: https://docs.godotengine.org/en/stable/community/contributing/updating_the_class_reference.html

**Comment by JustinDodemaide** [comment]
Made a pull request that fixes the 'too' and 'because' typos.

**Comment by br1trs** [comment]
You can reference this issue in your PR so it can be closed when your PR is merged.
