### ISSUE TITLE
C# HTML5 support status

### ISSUE THREAD

**Issue by hydroper** [godotengine/godot-docs#7467]
**Your Godot version:** 4.0

**Issue description:** Warn about HTML5 support for C#. Currently unsupported and the documentation does not mention it. Slightly unrelated, but also why not adding "C# HTML5 support" tracking issue to the roadmap?

**URL to the documentation page (if already existing):** https://docs.godotengine.org/en/stable/tutorials/scripting/c_sharp/c_sharp_basics.html

**Comment by raulsntos** [comment]
It is mentioned in the [_Current gotchas and known issues_](https://docs.godotengine.org/en/stable/tutorials/scripting/c_sharp/c_sharp_basics.html#current-gotchas-and-known-issues) section that only desktop platforms are supported.
