### ISSUE TITLE
Instant search is not working, Algolia might have deprecated the current API

### ISSUE THREAD

**Issue by panreyes** [godotengine/godot-docs#7468]
**Your Godot version:**
Godot latests docs

**Issue description:**
Algolia's instant search is not working. When typing in the search input box, errors are thrown in the browser's console.

This is the response to the AJAX petition to Algolia service:
![image](https://github.com/godotengine/godot-docs/assets/13276823/c3587d1c-ac85-4dc5-8171-c51c7fc8213d)

It might be related to some changes mentioned here:
https://github.com/algolia/docsearch-configs#:~:text=This%20repository%20is%20not%20maintained%20anymore%20in%20favor%20of%20our%20new%20infrastructure.

**URL to the documentation page:**
https://docs.godotengine.org/en/stable/

**Comment by tetrapod00** [comment]
Can this be closed, since Algolia was removed in https://github.com/godotengine/godot-docs/pull/8568?

**Comment by clayjohn** [comment]
Yep!
