### ISSUE TITLE
List of keyboard shortcuts

### ISSUE THREAD

**Issue by vnen** [godotengine/godot-docs#75]
There's quite a few keyboard shortcuts in the editor but I miss a list of all of those. Not sure how to organize those, since many are context-dependent. I guess a single page with different context sections should be enough.

**Comment by mhilbrunner** [comment]
http://docs.godotengine.org/en/latest/learning/editor/2d_and_3d_keybindings.html could be extended

**Comment by pwab** [comment]
@mhilbrunner And should be updated as well 😅 
A hint to look for the _shortcut tab_ in the _editor settings_ could be added.

If the docs shall contain a table (like the one in the editor settings) then the standard entries can be aggregated with a script which searches for `ED_SHORTCUT` in the editor files (if I'm not wrong).

**Comment by mhilbrunner** [comment]
http://docs.godotengine.org/en/latest/learning/editor/2d_and_3d_keybindings.html was deleted because it was badly outdated.

Maybe relevant: https://github.com/godotengine/godot-docs/issues/395

**Comment by mitchcurtis** [comment]
Is there really no documentation for keyboard shortcuts for the editor?

**Comment by Calinou** [comment]
This was implemented in #3329, closing.
