### ISSUE TITLE
Editor icon DOC page.

### ISSUE THREAD

**Issue by ghost** [godotengine/godot-docs#7506]
v4.0.3.stable.official [5222a99f5]

  The Editor has over 800 icons that are available to use.  There is an "editor icon previewer" plug-in that has been created to view these icons but really there should be a documentation page that displays each icon alongside their names and how to retrieve them/save them to a file.  This information would allow users to look up what "icon" they needed easily.

**URL to the documentation page (if already existing):** N/A

**Comment by Zentrophy** [comment]
I didn't know about the icons until I downloaded that "editor icon previewer".  Why should you need a tool to display what is available to users in the Editor ?  It should be included in the documentation, but if you don't agree, you don't agree.

**Comment by AThousandShips** [comment]
You can just look at them in the theme editor btw

This only really applies in the editor (as the icons are not available on export) and only relevant to plugins and very specifically, the vast majority of users won't ever need this, I don't see how it justifies a massive page?

**Comment by Zentrophy** [comment]
The icons can be saved to a .PNG file and used external to the editor.

**Comment by AThousandShips** [comment]
Yes, sure, you can also just download them from the repository as their original SVG files, or copy them from the theme

**Comment by skyace65** [comment]
Closing per AThousandShips comments which I agree with.
