### ISSUE TITLE
Outdated docs: Custom Drawing in 2D

### ISSUE THREAD

**Issue by halotroop2288** [godotengine/godot-docs#7521]
**Your Godot version:**
4.0 -> latest

**Issue description:**
Outdated documentation, as evidenced by incorrect (Godot 3-style) `export` example code.
This may or may not be the only mistake on the page. As someone who has not performed this before without the documentation, I can't comment on that.

This page also needs attention since October 2020, see #4184.

**URL to the documentation page:**
https://docs.godotengine.org/en/stable/tutorials/2d/custom_drawing_in_2d.html#updating

**Comment by jynus** [comment]
As mentioned before, kindly asking for feedback on the refactor sent at #7532, specially from those not already familiar with the `_draw()` methods from CanvasItem to see if the proposed new redaction is more useful.

**Comment by skyace65** [comment]
Fixed by #7994
