### ISSUE TITLE
get_property_list method documentation unclear on what properties are returned

### ISSUE THREAD

**Issue by jacob-winkler** [godotengine/godot-docs#7533]
**Your Godot version:**
4.3

**Issue description:**
The documentation isn't clear that this only returns properties that have been exported. Reading the documentation I was expecting this method to return all of the properties on my class, regardless of whether they were exported or not. A Godot property is different from a C# property (not sure if "property" is a concept in gdscript that could also cause confusion). Would be great if this was clarified in the docs.
**URL to the documentation page (if already existing):**
https://docs.godotengine.org/en/stable/classes/class_object.html#id2

**Comment by mateuseap** [comment]
I've made explicit in my [PR](https://github.com/godotengine/godot/pull/81093) that the `get_method_list` method returns a list containing only the exported properties.
