### ISSUE TITLE
rigidbody2d bounce c# example incorrect method

### ISSUE THREAD

**Issue by prashantham** [godotengine/godot-docs#7541]
**Your Godot version:**
4.0.3

**Issue description:**
The collision bounce method uses
`_velocity = _velocity.Bounce(collisionInfo.Normal);`

But there is no Normal field, but a GetNormal() method;
Hence example should have been
`_velocity = _velocity.Bounce(collisionInfo.GetNormal());`

**URL to the documentation page:**
https://docs.godotengine.org/en/stable/tutorials/physics/physics_introduction.html#rigidbody2d

If you know how to fix the issue you are reporting please
consider opening a pull request. We provide a tutorial on
using git here: https://docs.godotengine.org/en/stable/community/contributing/pr_workflow.html,
writing documentation at https://docs.godotengine.org/en/stable/community/contributing/docs_writing_guidelines.html
and contributing to the class reference here: https://docs.godotengine.org/en/stable/community/contributing/updating_the_class_reference.html

**Comment by raulsntos** [comment]
This example is outdated, it used to be a property in 3.x. In 4.x the example should indeed be using the `GetNormal()` method.

For context the GDScript's version of this example was updated by https://github.com/godotengine/godot-docs/pull/7288.
Pull requests to update it in C# are welcomed :slightly_smiling_face:.

**Comment by Surya-Narayan** [comment]
Hey @raulsntos , I would love to try to fix this issue. Can I please take on the issue ?

**Comment by raulsntos** [comment]
Sure, feel free to open a PR.
