### ISSUE TITLE
Outdated interface references - Dodge the Creeps > Creating the Enemy > Node Setup

### ISSUE THREAD

**Issue by TanyaStere42** [godotengine/godot-docs#7543]
**Your Godot version:** 4.0.3 stable

**Issue description:** References for the setup of the mob collision layer are for an older interface. Interface now has Layer and Mask properties as `Light Mask` and `Visibility Layer` nested under `Visibility` section. 
![image](https://github.com/godotengine/godot-docs/assets/62726866/6d973490-6f56-4892-a426-6460a63d40b4)

**URL to the documentation page:** https://docs.godotengine.org/en/stable/tutorials/migrating/upgrading_to_godot_4.html

**Comment by Piralein** [comment]
This section is about the collision of the mobs. This is still handled inside the `CollisionObject2D`.
The properties you mention are part of the `CanvasItem` class and effect the rendering of the node in regards to visibility and lighting.

[Collision layer and mask](https://docs.godotengine.org/en/stable/classes/class_collisionobject2d.html#class-collisionobject2d-property-collision-layer)

**Comment by skyace65** [comment]
Closing per Piralein's comment. The documentation is correct.
