### ISSUE TITLE
Outdated documentation to build godot in debug mode

### ISSUE THREAD

**Issue by mrbean2000** [godotengine/godot-docs#7548]
**Your Godot version:**
English version 4.0

**Issue description:**
From the [commit](https://github.com/godotengine/godot/commit/39facb35a021f9301f742732fbbd3c6a5a548893) in the building instruction from source, to get the target flag is outdated. The flag mention that there are 3 options.

- debug
- release_debug
- release

The commit has replaced these options to
- editor
- template_debug
- template_release

There is also a new flag that is created to build in debug mode

> dev_build=yes/no

**URL to the documentation page:**
You can find the build documentation [here](https://docs.godotengine.org/en/3.0/development/compiling/introduction_to_the_buildsystem.html)
If you know how to fix the issue you are reporting please
consider opening a pull request. We provide a tutorial on
using git here: https://docs.godotengine.org/en/stable/community/contributing/pr_workflow.html,
writing documentation at https://docs.godotengine.org/en/stable/community/contributing/docs_writing_guidelines.html
and contributing to the class reference here: https://docs.godotengine.org/en/stable/community/contributing/updating_the_class_reference.html

**Comment by br1trs** [comment]
The link you shared is the documentation for building Godot 3.0, you can find the latest documentation for Godot 4.0 [here](https://docs.godotengine.org/en/stable/contributing/development/compiling/introduction_to_the_buildsystem.html).
It includes the new targets you mentioned and the dev_build flag.

**Comment by AThousandShips** [comment]
Note that the 3.0 version has been past end of support for 5 years, and wouldn't be up to date even with 3.5

**Comment by BWPanda** [comment]
So this isn't a bug and can be closed now...?

**Comment by skyace65** [comment]
Closing this issue per the comments above. You shouldn't be using the 3.0 page of the documentation when the engine version you're using is 4.0.
