### ISSUE TITLE
TileMap's "get_surrounding_cells()" could use better documentation.

### ISSUE THREAD

**Issue by LeHoovy** [godotengine/godot-docs#7553]
Godot version: 4.0.3

I didn't quite understand what "Vector2i[]" meant, and I was about to ask if an output using this code was an array or not.
I then checked the two methods that output "Vector2i[]" below it as well, and then finally realized it meant it was an array.
Changing it could help others who are new to godot as well.
A possible description change could be from "Returns the list of all neighbourings cells to the one at coords." to "Returns an array which contains a list of the cells directly neighboring the cell at coords."

[Document, plus method](https://docs.godotengine.org/en/stable/classes/class_tilemap.html#class-tilemap-method-get-surrounding-cells)

**Comment by AThousandShips** [comment]
This documentation is not handled here but over at [Godot](https://github.com/godotengine/godot/issues), the API documentation is in the engine itself
