### ISSUE TITLE
Standard material documentation is missing description of Transparency modes

### ISSUE THREAD

**Issue by lostminds** [godotengine/godot-docs#7556]
**Your Godot version:**
4.1beta3

**Issue description:**
At some point the standard material Transparency parameter was changed and now lets you pick one of several modes:
![Screenshot 2023-06-25 at 17 16 42](https://github.com/godotengine/godot-docs/assets/17763524/0ddd3b12-80a2-4d15-ac56-bf26a1f0eb53)

However, the section on this in the docs does not mention these modes or explain what they do, instead it just seems to indirectly refer to older versions of the transparency and alpha-scissor options (that may have been separate bools before?)

**URL to the documentation page:**
https://docs.godotengine.org/en/latest/tutorials/3d/standard_material_3d.html#transparency

**Comment by lmsonic** [comment]
The docs seem to reflect the options now, I think this was fixed in this [commit](https://github.com/godotengine/godot-docs/commit/d07baf38368a823f28d7f257865c9e2c47c35ef0).
