### ISSUE TITLE
Possible incorrect description for lifetime_randomness

### ISSUE THREAD

**Issue by Necronomicron** [godotengine/godot-docs#7559]
**Your Godot version:**
v4.1.beta3.official [ada712e06]

**Issue description:**
It says it scales from value to 1.0, but from what I see it scales from (1.0 - value) to 1.0. If value is 0.4, it will scale from (1.0 - 0.4), that is from 0.6 to 1.0, not from 0.4. If I set it to 1.0, it will scale from 0.0 (1.0 - 1.0) to 1.0, and default value is 0.0, which doesn't affect lifetime at all.

**URL to the documentation page (if already existing):**
[**Docs.**](https://docs.godotengine.org/en/stable/classes/class_particleprocessmaterial.html#class-particleprocessmaterial-property-lifetime-randomness)

**Comment by clayjohn** [comment]
Indeed, the description is incorrect.

Current description:

> Particle lifetime randomness ratio. The lifetime will be multiplied by a value interpolated between 1.0 and a random number less than one. For example a random ratio of 0.4 would scale the original lifetime between 0.4-1.0 of its original value.

The code for calculating the lifetime of a particle is ``lifetime * (1.0 - Math::randf() * lifetime_randomness)``
