### ISSUE TITLE
typo in getting started -> step by step.

### ISSUE THREAD

**Issue by ahliu2000** [godotengine/godot-docs#7562]
**Your Godot version:** 4.0

**Issue description:** 
Minor typo on instancing page. Currently reads:
"The tabel.tscn file from the previous lesson was an example."
**t**abel.tscn should be changed to **l**abel.tscn

**URL to the documentation page:**
https://docs.godotengine.org/en/stable/getting_started/step_by_step/instancing.html

**Comment by Piralein** [comment]
This was already fixed by #7414 in master.
