### ISSUE TITLE
Broken link on internal_rendering_architecture page - 404

### ISSUE THREAD

**Issue by zixin96** [godotengine/godot-docs#7570]
These links lead to 404 pages. 

Link: https://docs.godotengine.org/en/stable/contributing/development/core_and_modules/internal_rendering_architecture.html
```
Core GLSL material shaders:

Forward+: [servers/rendering/renderer_rd/shaders/scene_forward_clustered.glsl](https://github.com/godotengine/godot/blob/4.0/servers/rendering/renderer_rd/shaders/scene_forward_clustered.glsl)
Forward Mobile: [servers/rendering/renderer_rd/shaders/scene_forward_mobile.glsl](https://github.com/godotengine/godot/blob/4.0/servers/rendering/renderer_rd/shaders/scene_forward_mobile.glsl)
Compatibility: [drivers/gles3/shaders/scene.glsl](https://github.com/godotengine/godot/blob/4.0/drivers/gles3/shaders/scene.glsl)
```

Thanks!

**Comment by clayjohn** [comment]
Looks like they should be:
https://github.com/godotengine/godot/blob/4.0/servers/rendering/renderer_rd/shaders/forward_clustered/scene_forward_clustered.glsl

And 

https://github.com/godotengine/godot/blob/4.0/servers/rendering/renderer_rd/shaders/forward_mobile/scene_forward_mobile.glsl

Instead. 

The compatibility link appears to be working fine.
