### ISSUE TITLE
Confused about creating ViewportTexture in code

### ISSUE THREAD

**Issue by zixin96** [godotengine/godot-docs#7576]
Link: 
https://docs.godotengine.org/en/latest/classes/class_viewporttexture.html

In the page, we are saying to create a ViewportTexture in code, use the Viewport.get_texture() method on the target viewport.

Shouldn't this be "to get a ViewportTexture in code..."? 

```
Ref<ViewportTexture> Viewport::get_texture() const {
	ERR_READ_THREAD_GUARD_V(Ref<ViewportTexture>());
	return default_texture;
}
```

**Comment by clayjohn** [comment]
Ya, that makes sense. Its not really creating a Viewportexture.
