### ISSUE TITLE
Godot C# Documentation update for Visual Studio Workloads.

### ISSUE THREAD

**Issue by KazeEnji** [godotengine/godot-docs#7578]
**Your Godot version:** N/A

**Issue description:** Workloads defined in the documentation don't exist in Visual Studio 2022 by name.

**URL to the documentation page:** https://docs.godotengine.org/en/stable/tutorials/scripting/c_sharp/c_sharp_basics.html

I'm not sure what the proper workloads are now but the current workloads defined in the documentation are:

- Mobile development with .NET
- .NET Core cross-platform development

There aren't any workloads in Visual Studio 2022 that match either one of the listed workloads. There also aren't any individual components that match. It's possible they've been bundled with other workloads or their workload name has changed but I'm not sure.

**Comment by raulsntos** [comment]
I don't use Visual Studio so I don't know what are the correct names for the workloads. **.NET Core** has been renamed to just **.NET** and mobile development is not supported in Godot 4.x. So you probably only need the _.NET desktop development_ workload or something like that.

**Comment by br1trs** [comment]
Yeah, .NET desktop development should be enough, it includes all necessary .NET tools for general uses of c#, and also mobile development  .NET doesn't exist anymore, apart from what you were saying that it is no longer supported in Godot. I'm going to open a PR :)
![image](https://github.com/godotengine/godot-docs/assets/88297220/6ecdbd93-9714-4d0c-bb14-24813f24482a)
