### ISSUE TITLE
Vague documentation on how to create an enemy

### ISSUE THREAD

**Issue by mmiovv2** [godotengine/godot-docs#7581]
**Your Godot version: 4.0.3**

**Issue description: The documentation is a bit vague about what I'm supposed to do with creating a mob for the 2D game tutorial, I'm** **not sure if that's intentional or not. For instance. It doesn't specify how to use VisibleOnScreenNotifier2D.**

**URL to the documentation page (if already existing): https://docs.godotengine.org/en/stable/getting_started/first_2d_game/04.creating_the_enemy.html**

**Comment by skyace65** [comment]
Some clarification was added with #7372. I don't really see how the instructions can get more specific than that for using the VisibleOnScreenNotifier2D node. I'm going to close this issue but if there's other parts of the page you still have issues with, or if you have a more specific issue with the instructions for the notifier node please open issues for them.
