### ISSUE TITLE
Looking for Official Linux Server Binaries for Dedicated Servers: Current Links are 404's

### ISSUE THREAD

**Issue by PersonGuyGit** [godotengine/godot-docs#7600]
Godot 3.5

404 when searching for Linux Binaries, for use with Dedicated and Headless Servers.

https://docs.godotengine.org/en/3.5/tutorials/export/exporting_for_dedicated_servers.html#doc-exporting-for-dedicated-servers

My team and I noticed, that there is a 404 when trying to download the official Linux server binary from the Dedicated Server Documentation for Godot 3.5 and Godot 4.0.

Here is the link that is broken.

https://godotengine.org/download/server

**Comment by AThousandShips** [comment]
Link needs to be updated to https://godotengine.org/download/3.x/server/

All the LTS ones now have 3.x in the URL

**Comment by AThousandShips** [comment]
Might also be useful, for the future, to use permalinks for version specific downloads and such, to avoid having to hunt down links like this

**Comment by YuriSizov** [comment]
> Might also be useful, for the future, to use permalinks for version specific downloads and such, to avoid having to hunt down links like this, i.e. regardless if 4.x is the current stable version links to 4.x used in documentation would benefit from having 4.x in it

We didn't use to have separate download pages before Godot 4 came out. So there aren't any permalinks of this sort. I guess we could make `/download/4.x` an alias for the current download page to future proof it.

**Comment by ferdnyc** [comment]
@YuriSizov 

That won't really help if the documentation still gives links in the  `https://godotengine.org/download/...` form.

Better would be to flip that around: make `https://godotengine.org/download/` an alias for `https://godotengine.org/download/4.x/` (currently), and exclusively use `https://godotengine.org/download/4.x/...` URLs in the 4.x documentation. Done that way, the documentation URLs will never change their meaning.

When starting the 5.x documentation, the URL prefixes would have to be updated, but that doesn't have to be a nightmare if they're centralized in some configuration.

(Another advantage: Preview versions of 5.0 could be made available by creating the `https://godotengine.org/download/5.x/` page ahead of time. Then all that's required upon release is to redefine where the `https://godotengine.org/download/` alias points.)

**Comment by YuriSizov** [comment]
@ferdnyc The documentation is versioned. It should use versioned URLs to ensure it doesn't break in the future. When Godot 5 comes out, it's going to be very easy to find the links in the docs and update them to work with the new version.

Btw, `https://godotengine.org/download/4.x/` has been implemented since my comment, so we can update the docs now.

**Comment by skyace65** [comment]
The link to the Linux server page works again.
