### ISSUE TITLE
ChatGPT Plugin for Most Recent Godot Documentation

### ISSUE THREAD

**Issue by cramsey86** [godotengine/godot-docs#7615]
**Your Godot version:**
4.0-stable

**Issue description:**
Currently there is a challenge with using ChatGPT to access the freshest Godot documentation, especially concerning the new Godot 4. This is because Godot 4 was released after ChatGPT's training data was frozen in September 2021.

While this isn't a reflection on the comprehensive Godot documentation itself, it does spark an intriguing idea about harnessing the full potential of ChatGPT using the Godot documentation. Has anyone considered creating a ChatGPT Plugin that gives ChatGPT direct access to the Godot 4 documentation?

**URL to the documentation page (if already existing):**

Following something similar to: 

https://www.youtube.com/watch?v=kHVkAvxkuy8

**Comment by YuriSizov** [comment]
Hey! This kind of discussion fits better one of our [community platforms](https://godotengine.org/community/). There are no plans on our end to provide anything for any of LLM vendors. But community members are free to do so, as much as anyone is with the current legal implications.

**Comment by cramsey86** [comment]
Sure! And I can definitely take it there. The reason I wanted to start here, is one of the capabilities may be a requirement to either scrape the Godot documentation full site or to have the ability to call an API directly, and if I or someone from the community were to proceed with this, we obviously do not want to create what may appear to be "malicious" activity without Godot Documentation maintainers awareness. Speaking of, is there currently an API for the documentation? I guess another possibility would be for me to continually fork the documentation repo and hit my own site as well, but again the idea would be to always have the most up to date information.

**Comment by YuriSizov** [comment]
@cramsey86 There is no API. The entire documentation is statically accessible. You can just checkout the repository and read it, or checkout, build it, and read resulting HTML files.

**Comment by cramsey86** [comment]
Sounds good!
