### ISSUE TITLE
Error with first tutorial (2D) asking the user to press a nonexistent button

### ISSUE THREAD

**Issue by Uranium2331** [godotengine/godot-docs#7621]
**Your Godot version:** v4.0.3.stable.mono.official [5222a99f5]

**Issue description:** Documentation for first game (2d) asks the user to press the build button in the top left, which is nonexistent

**URL to the documentation page:** https://docs.godotengine.org/en/stable/getting_started/first_2d_game/03.coding_the_player.html

![image](https://github.com/godotengine/godot-docs/assets/138694270/82aa989e-4592-40de-9e81-1b3ff7619d91)
Button the tutorial asks the user to press

![Screenshot (1)](https://github.com/godotengine/godot-docs/assets/138694270/a57cc5c4-87c3-4afe-8b9f-2d4effbf3814)
Actual godot screen

Edit: Wrong link

**Comment by AThousandShips** [comment]
I can't find that instruction anywhere in the linked page

**Comment by Uranium2331** [comment]
I somehow got the wrong link, it's this page: https://docs.godotengine.org/en/stable/getting_started/first_2d_game/03.coding_the_player.html

**Comment by AThousandShips** [comment]
Do you have a development environment set up properly? Does the button show up in other projects? This could be a normal bug in the editor rather than the documentation, to be tracked [here](https://github.com/godotengine/godot/issues), but consider asking in the other [community channels](https://godotengine.org/community), as this is either a bug in the engine, changes to the layout that requires the documentation to be changed, or some error in your setup.

**Comment by Uranium2331** [comment]
I have no clue if I have the development environment set up properly, but I only downloaded Godot a couple of days ago and don't remember messing with any settings involving the development environment. The button does not show up in any other projects (including one that I just created using default settings). I will ask in other community channels.

**Comment by MisoMosiSpy** [comment]
The button should show up in the "Mono" version as soon as you add any .cs scripts. I can see from the screenshot you have them both so not sure why you don't see the button. 

Can you try starting godot from command prompt and see if it prints any other information?

**Comment by skyace65** [comment]
Miso is correct that the Build button should show up once you've created a C# script, so we would recommend reaching out to the community channels and filing an engine bug if it looks like that's what's going on. The said this screenshot does need to be updated now since the button has changed.

**Comment by skyace65** [comment]
This was fixed by #8180.
