### ISSUE TITLE
Non existing function "lenght" in base "String"

### ISSUE THREAD

**Issue by 0liva111** [godotengine/godot-docs#7632]
Godot: 4.1

can't get lenght of a string within a string

https://docs.godotengine.org/en/stable/classes/class_string.html#class-string-method-length

There is nothing more I can say probably, the documentation is just false but idk

**Comment by 0liva111** [comment]
when i added a str wrapper it seemes to fix the issue 

before:  ReferenceToArray[ i ].lenght()

after: str(ReferenceToArray[ i ]).lenght()

**Comment by AThousandShips** [comment]
You've spelled it wrong, it's `length` not `lenght`

**Comment by 0liva111** [comment]
f my dyslexia i spent hour on this ahhh

**Comment by AThousandShips** [comment]
I'm sorry that's hard

This could be improved on by having a "did you mean" added to the error, might be worth opening a [proposal](https://github.com/godotengine/godot-proposals) for that
