### ISSUE TITLE
RigidBody2D Contact Monitoring

### ISSUE THREAD

**Issue by HPCR-SD** [godotengine/godot-docs#7642]
Godot 4.1

Contact Monitoring for RigidBody2D states "If true, the RigidBody2D will emit signals when it collides with another RigidBody2D" but this isn't the only truth here. It will emit signals when colliding with any other PhysicsBody2D, assuming the layer and masks are setup correctly of course.

https://docs.godotengine.org/en/4.1/classes/class_rigidbody2d.html#class-rigidbody2d-property-contact-monitor

This would also need to be updated for as many previous versions this is incorrect for, or this is a bug and needs to be put in for the engine itself, but otherwise body_entered signals don't trigger for RigidBody2D.

**Comment by HPCR-SD** [comment]
I'm sure this also may apply to RigidBody3D of course too.

**Comment by AThousandShips** [comment]
Done in #79250, will be included in 4.1.1

**Comment by HPCR-SD** [comment]
Ahhh thank you for matching those up so we know! :)
