### ISSUE TITLE
Provide a better description on what does "navigation_finished" and "target_reached" signals do on NavigationAgent3D

### ISSUE THREAD

**Issue by enxas** [godotengine/godot-docs#7643]
**Your Godot version:**
4.1

**Issue description:**
"navigation_finished" and "target_reached" signal descriptions make it seem like they both do the same thing, which is fire when target is reached. What are the differences? Why would I use one over the other?

**URL to the documentation page (if already existing):**
https://docs.godotengine.org/en/4.1/classes/class_navigationagent3d.html

**Comment by smix8** [comment]
See descriptions in the linked pr.

This node documentation is part of the class doc which is part of the main godot repo, not the godot-docs repo.
