### ISSUE TITLE
Documentation for GDExtension in 4.1 still refers to 4.0

### ISSUE THREAD

**Issue by dcuny** [godotengine/godot-docs#7648]
**4.1**

**Page says it's up to date for 4.1, but still refers to version 4.0**

**[Godot Engine 4.1 documentation in English](https://docs.godotengine.org/en/stable/tutorials/scripting/gdextension/gdextension_cpp_example.html)**

The GDExtension tutorial page says that it's currently up to date with 4.1.

However, the "Note" says that "_you need to use the 4.0 branch of godot-cpp, which is only compatible with Godot 4.0 and being used here as an example._"

The code references the 4.0 version as well:

`git submodule add -b 4.0 https://github.com/godotengine/godot-cpp`

and

`git clone -b 4.0 https://github.com/godotengine/godot-cpp`

Additionally, the release notes state there is a binary incompatibility between GDExtensions built in 4.0 vs. 4.1, which requires a small change. I don't see that information referenced on the page, and this "small change" would be helpful to know about _before_ I start trying to port my 4.0 extensions to 4.1, so I can make that change.

**Comment by dcuny** [comment]
In the [discussion about what changed between Godot 4.0 and 4.1](https://github.com/godotengine/godot-docs/pull/7611), there's mention of a "tiny change to the source code":

> GDExtensions compiled for Godot 4.0 aren't compatible with Godot 4.1 - a tiny change to the source code is required, and they need to be recompiled. As soon as this PR is merged, I'm planning to make a follow-up PR that adds detailed information on what folks need to do to get their GDExtensions working in 4.1.

It appears the change is in the `example_library_init()`. This is the 4.0 version:

```
extern "C" {
// Initialization.
GDExtensionBool GDE_EXPORT example_library_init(const GDExtensionInterface *p_interface, const GDExtensionClassLibraryPtr p_library, GDExtensionInitialization *r_initialization) {
    godot::GDExtensionBinding::InitObject init_obj(p_interface, p_library, r_initialization);

    init_obj.register_initializer(initialize_example_module);
    init_obj.register_terminator(uninitialize_example_module);
    init_obj.set_minimum_library_initialization_level(MODULE_INITIALIZATION_LEVEL_SCENE);

    return init_obj.init();
}
```

And here's what appears to be the 4.1 version:

```
extern "C" {
// Initialization.
GDExtensionBool GDE_EXPORT example_library_init(GDExtensionInterfaceGetProcAddress p_get_proc_address, const GDExtensionClassLibraryPtr p_library, GDExtensionInitialization *r_initialization) {
    godot::GDExtensionBinding::InitObject init_obj(p_get_proc_address, p_library, r_initialization);

    init_obj.register_initializer(initialize_example_module);
    init_obj.register_terminator(uninitialize_example_module);
    init_obj.set_minimum_library_initialization_level(MODULE_INITIALIZATION_LEVEL_SCENE);

    return init_obj.init();
}
```
There are two changes:

1. `const GDExtensionInterface *p_interface` has been replaced by `GDExtensionInterfaceGetProcAddress p_get_proc_address`.
2. `init_obj` now passes `p_interface` as the first parameter instead of `p_get_proc_address`.

This should be addressed via a **Note** on the GDExtention page.

**Comment by dsnopek** [comment]
I've been working on changes to the "Upgrading from Godot 4.0 to Godot 4.1" page that describes this. When I asked, folks seemed to think that was the right place to put it (as opposed to the GDExtension page). I keep getting sidetracked with other things, but I hope to have the PR for that up soon!
