### ISSUE TITLE
Incorrect C# sample in Instancing_with_signals/shooting-example

### ISSUE THREAD

**Issue by JamesDepret** [godotengine/godot-docs#7650]
**Your Godot version: 4.1.stable**

**Issue description: Incorrect C# code sample:**

**URL to the documentation page: https://docs.godotengine.org/en/stable/tutorials/scripting/instancing_with_signals.html#shooting-example**

We use the `OnPlayerShoot()` function in the last function reference. This throws two errors:

- `bulletInstance.Rotation = direction`: direction is a Vector2, Rotation expects a float.
- `bulletInstance.Velocity`: In the previous code sample we setup bullet, but made Velocity a private member, making it inaccessible
- Setting Velocity to public in the bullet class gives the same issue as the first issue: `bulletInstance.Velocity.Rotated(direction)` => the Rotated method expects a float.

Potential solution (I'm not sure if this is correct)
- Make Velocity a public field in the bullet class
- change the Rotation line to
        `bulletInstance.Rotation = direction.Angle();`
- change the Velocity.Rotated line to
        `bulletInstance.Velocity = bulletInstance.Velocity.Rotated(direction.Angle());`

**Comment by raulsntos** [comment]
You are right that `Velocity` should be made public so it can be accessed from the outside.

About `Rotation`. The Player is emitting the Shoot signal with a float for the `direction` parameter, so the parameter is actually a float not a Vector2. The parameter type is wrong.

There are a couple other issues with the C# examples in this page, so I opened a PR to fix them all:
- https://github.com/godotengine/godot-docs/pull/7651.
