### ISSUE TITLE
Mutexes tutorial print nothing at the end

### ISSUE THREAD

**Issue by Infini-Creation** [godotengine/godot-docs#7669]
v4.1.1.rc1.official [e709ad4d6] on windows 7 64 bits

Mutex sample from the official documentation

(https://docs.godotengine.org/en/stable/tutorials/performance/using_multiple_threads.html)

The code as it is never print anything.

I'm not an expert in _Godot_ threading, so correct me if I'm wrong, I believe _queue_free_() need to be called at the end of __thread_function_ in order to trigger the call to __exit_tree_ function.

**Comment by AThousandShips** [comment]
The exit tree here is fired when the game exists, the printing issue is tracked in:
* https://github.com/godotengine/godot/issues/79031

**Comment by AThousandShips** [comment]
Closing as a duplicate

**Comment by Infini-Creation** [comment]
> Closing as a duplicate

I'm not sure how they are related as such small sample are most likely run inside the editor (it would be too much to export the code), so the exit process is not the same. And the text in the thread page doesn't define any particular setting to test the code.

**Comment by AThousandShips** [comment]
How do you mean? The exit is fired when closing the running project, it running in the editor doesn't change that

**Comment by Infini-Creation** [comment]
That's weird then as closing the scene doesn't do anything, if I didn't add a _queue_free_ call at the end of the thread function, the __exit_tree_ function is not called by the engine. The Debugger shows no error.

**Comment by AThousandShips** [comment]
What error doesn't it show? How are you checking that `_exit_tree` is not called?

**Comment by AThousandShips** [comment]
Test this, remove the `thread.wait_to_finish()` line from `_exit_tree` and don't call `queue_free`, does it throw an error or warning on closing?

**Comment by Infini-Creation** [comment]
If I just remove `thread.wait_to_finish()` (in  `_exit_tree`) but still calling `queue_free` (in thread function), I get the error:
```
W 0:00:02:0341   ~Thread: A Thread object is being destroyed without its completion having been realized.
Please call wait_to_finish() on it to ensure correct cleanup.
  <C++ Source>   core/os/thread.cpp:104 @ ~Thread()
```

If I also disable `queue_free` call in thread function, I get no error, I mean nothing is displayed in the debugger window, it doesn't mean there is no error at all (it may be also discarded like print statement as describe in issue #79031).

By the way, I use a mere `print` statement inside `_exit_tree` function, which is in output if I put a breakpoint just after (on `thread.wait_to_finish()` call) and let the debugger halt the execution, but a very last print statement is not displayed in output even with a breakpoint there, step over or into just end the debugging session.

**Comment by AThousandShips** [comment]
So it calls `_exit_tree`, therefore it is a duplicate, please take these observations there
