### ISSUE TITLE
erro com o codigos clamps

### ISSUE THREAD

**Issue by marcosgithubs** [godotengine/godot-docs#7679]
Your Godot version:
4,1

Issue description:
o codigo clamp no godot docs esta incorreto e não consigo aprender como progamar nada, pois todos os codigos estãos desatualizados
> *Bugsquad edit:
Problem description: the clamp code in godot docs is incorrect and I can't learn how to program anything, because all the codes are out of date*

URL to the documentation page:
https://docs.godotengine.org/en/stable/getting_started/first_2d_game/03.coding_the_player.html

**Comment by AThousandShips** [comment]
Please write in English here, even if you have to use translation software, not everyone here speaks every language

**Comment by marcosgithubs** [comment]
Godot version: 4.1
 >
 > Problem description: the clamp code in godot docs is incorrect and I can't learn how to program anything, because all the codes are out of date

**Comment by marcosgithubs** [comment]
Ok Sorry i translated the comment

**Comment by AThousandShips** [comment]
How is the clamp code out of date?

**Comment by marcosgithubs** [comment]
says that don't have a identifier i dont know how to fix this

**Comment by Piralein** [comment]
Could you please provide more information about the error, like copying the whole error message from the log.
Without it we can't say if this is an actual error, a misspelled word or something else in your script.

If you need further guidance or help please refer to one of the [godot community channels](https://godotengine.org/community/) like reddit, discord or the [Godot Q&A-Page](https://ask.godotengine.org/).

**Comment by skyace65** [comment]
Closing this issue due to a lack of a response to Piralein's comment.
