### ISSUE TITLE
Specify casing of variables storing node references in GDScript style guide

### ISSUE THREAD

**Issue by Ybaedbaenn** [godotengine/godot-docs#7688]
**Your Godot version:**
4.1.1.stable.official

**URL to the documentation page (if already existing):**
https://docs.godotengine.org/en/stable/tutorials/scripting/gdscript/gdscript_styleguide.html#classes-and-nodes

**Issue description:**
The linked documentation tells to use PascalCase for class names, **node** names, and **when loading** a class into a constant or a variable.
This can suggest that PascalCase should also be used when "loading" nodes into a variable for example:

```GDScript
var EnemiesArray = [$Enemy1, $Enemy2]
for EnemyNode in EnemiesArray:
	EnemyNode.do_something()
```
If this is not the case, then it could be specified, and a bad example could be added to the documentation for more clarity.

**Comment by AThousandShips** [comment]
It is specified, variables should be snake case

> Use snake_case to name functions and variables

**Comment by Ybaedbaenn** [comment]
Maybe a precise example of using a snake_case variable for storing a node reference should be added to this part instead then?
https://docs.godotengine.org/en/stable/tutorials/scripting/gdscript/gdscript_styleguide.html#functions-and-variables

**Comment by AThousandShips** [comment]
How is "use snake_case for variables" vague? It applies to all variables, no matter what's loaded into them

**Comment by AThousandShips** [comment]
> variables with loaded scenes (that can also be confused as nodes, since after instancing they became nodes) use PascalCase

Where is that specified?

**Comment by Ybaedbaenn** [comment]
Here I believe, but I might be wrong.
![image](https://github.com/godotengine/godot-docs/assets/84321760/9e623182-77f8-4d75-be1c-9fa5ab2c75e5)

**Comment by AThousandShips** [comment]
That's a class, not a scene

**Comment by Ybaedbaenn** [comment]
Oh, you're right, I'm sorry for the problem.

**Comment by AThousandShips** [comment]
The cases that use PascalCase are all nodes and classes, I think the "or variable" should be removed as it's not the correct way to do that, you should always use a `const` to store classes like this

**Comment by Ybaedbaenn** [comment]
Should we also add some notice like:
```gdscript
const Weapon = preload("res://weapon.gd") #note that this does not apply to scenes, only classes
```
to avoid further confusion?

**Comment by AThousandShips** [comment]
But it says "classes", scenes are never classes, to assume that the reader would have to have a flawed idea of how GDScript works, which would make general suggestions here impossible

**Comment by Ybaedbaenn** [comment]
Ok, thank you, I'm closing it, should I open a new issue for removing the "or variable"?

**Comment by AThousandShips** [comment]
That was confusion on my side so it still belongs, it is only relevant for cases where `preload` breaks due to circular references though
