### ISSUE TITLE
In shading_language > uniforms Add example of `hint` with default value

### ISSUE THREAD

**Issue by fguillen** [godotengine/godot-docs#7690]
**Your Godot version:**

4.1.stable

**Issue description:**

In this page: https://docs.godotengine.org/en/stable/tutorials/shaders/shader_reference/shading_language.html#uniforms 

There is not example of a `hint` with a default value... and there is not solution for this in Google :?

It would have saved me a precious hour of my time if I would have seen an example like:

```
uniform float variable : hint_range(0.1, 10.0) = 1.0;
```

In the documentation

**URL to the documentation page (if already existing):**

https://docs.godotengine.org/en/stable/tutorials/shaders/shader_reference/shading_language.html#uniforms

**Comment by fguillen** [comment]
I added a SO question/answer to be indexed by Google:

- https://stackoverflow.com/questions/76722844/in-godot-shader-how-to-use-hint-with-a-default-value/76722845#76722845

**Comment by paddy-exe** [comment]
I am a bit confused by this issue since there is an example in the docs:
```glsl
shader_type spatial;

uniform vec4 color : source_color;
uniform float amount : hint_range(0, 1);
uniform vec4 other_color : source_color = vec4(1.0);
uniform sampler2D image : source_color;
```

**Comment by clayjohn** [comment]
@paddy-exe the docs show how to do a hint and how to have a default values, but they don't say that the default values comes after the hint. So an example would clear that up

**Comment by paddy-exe** [comment]
> @paddy-exe the docs show how to do a hint and how to have a default values, but they don't say that the default values comes after the hint. So an example would clear that up

Ah now I get it. Thanks for clarifying👍🏻 that would be indeed clearer

**Comment by Hex-4** [comment]
Is anyone working on this issue? If not, I'd like to take it.

**Comment by paddy-exe** [comment]
> Is anyone working on this issue? If not, I'd like to take it.

Not that I know of. It's a good first PR so you can take it 👍🏻
