### ISSUE TITLE
Page on 3D feature describes it as 2D

### ISSUE THREAD

**Issue by UhGoomba** [godotengine/godot-docs#7707]
**Your Godot version:** 4.1

**Issue description:** In the description of the page, it describes 2d physics repeatedly, despite being a page on the 3D equivalent. It was probably copy pasted and not changed.

**URL to the documentation page:** https://docs.godotengine.org/en/stable/classes/class_physicsserver3d.html

**Comment by AThousandShips** [comment]
People looking to solve this, be aware that this is handled [here](https://github.com/godotengine/godot), see the [instructions](https://docs.godotengine.org/en/latest/contributing/documentation/updating_the_class_reference.html)
