### ISSUE TITLE
Add documentation for static var in GDScript reference.

### ISSUE THREAD

**Issue by Ybaedbaenn** [godotengine/godot-docs#7711]
**Your Godot version:**
4.1.1

**Issue description:**
As described in https://godotengine.org/article/godot-4-1-is-here/#gdscript, since version 4.1, it is possible to use the static keyword with variable declarations.

The GDScript reference in documentation page still does not account for this and in "keywords" section states:
<html><body>

static | Defines a static function. Static member variables are not allowed.
--|--

</body></html>

Additionaly I believe that the page should have additional (sub)section with a desription of the static member veriables, like it already has for static functions.

**URL to the documentation page (if already existing):**
https://docs.godotengine.org/en/stable/tutorials/scripting/gdscript/gdscript_basics.html#keywords

**Comment by AThousandShips** [comment]
This has been fixed, it just hasn't been cherry picked to 4.1 yet, see the [current](https://docs.godotengine.org/en/latest/tutorials/scripting/gdscript/gdscript_basics.html#static-variables) documentation

This was fixed in #7524

**Comment by Ybaedbaenn** [comment]
Great! I'm closing this accordingly.

**Comment by AThousandShips** [comment]
Please always check the latest version before opening an issue in the future, if it isn't specific to an older version, and look for other issues (this was already tracked in #7487)

**Comment by Ybaedbaenn** [comment]
Thank you, I will do that.
