### ISSUE TITLE
AStarGrid2d - C# Example uses outdated property

### ISSUE THREAD

**Issue by DarthKitten2130** [godotengine/godot-docs#7712]
Version 4.1

The C# example for the AStarGrid2D API initialises the 'Size' property, which is deprecated. It should be replaced with the 'Region' property instead.

`astarGrid.Size = new Vector2I(32, 32);`
Should be replaced by
`astarGrid.Region = new Rect2I(0, 0, 32, 32)`

https://github.com/godotengine/godot-docs/blob/master/classes/class_astargrid2d.rst

**Comment by AThousandShips** [comment]
For people wanting to fix this, this is handled in the main repository over at [godotengine/godot](https://github.com/godotengine/godot), *not* here

**Comment by DarthKitten2130** [comment]
oh sorry! this is my first issue (ever), I'll head over there. Thank you!

**Comment by AThousandShips** [comment]
The issue fits here, but don't edit the `rst` files :)
