### ISSUE TITLE
GDScript reference for 4.1 still says static member variables are not allowed even though they are

### ISSUE THREAD

**Issue by enrikqose** [godotengine/godot-docs#7714]
**Your Godot version:**
4.1.1
**Issue description:**
GDScript reference for 4.1 still says static member variables are not allowed even though starting from 4.1 they are allowed
**URL to the documentation page:**
https://docs.godotengine.org/en/stable/tutorials/scripting/gdscript/gdscript_basics.html#keywords
If you know how to fix the issue you are reporting please
consider opening a pull request. We provide a tutorial on
using git here: https://docs.godotengine.org/en/stable/community/contributing/pr_workflow.html,
writing documentation at https://docs.godotengine.org/en/stable/community/contributing/docs_writing_guidelines.html
and contributing to the class reference here: https://docs.godotengine.org/en/stable/community/contributing/updating_the_class_reference.html

**Comment by AThousandShips** [comment]
This hasn't been backported to 4.1 yet, it will eventually, please have patience
