### ISSUE TITLE
Documentation Error

### ISSUE THREAD

**Issue by dawkrish** [godotengine/godot-docs#7727]
**Your Godot version:**
3.5.2

**Issue description:**
In ProjectSettings/Display/Window/Strech/Mode, there is no option of canvas_items shown in the engine but the tutorial says so

**URL to the documentation page (if already existing):**
https://docs.godotengine.org/en/stable/getting_started/first_2d_game/01.project_setup.html

**Comment by AThousandShips** [comment]
The documentation you're looking at is version 4.1, not 3.5
