### ISSUE TITLE
Ignoring warnings with decorative @ instead of comments

### ISSUE THREAD

**Issue by BinaryCanon** [godotengine/godot-docs#7729]
**Your Godot version: 4.1.1

**Issue description: Ignoring warnings works with decorative @warning_ignore("warning-id") and not with comments as written in the docs.

**URL to the documentation page: https://docs.godotengine.org/en/stable/tutorials/scripting/gdscript/warning_system.html

**Comment by Piralein** [comment]
The problem was already reported by #6994 and may be closed by #6586.
Closing as duplicate.

Thank you for reporting the issue.
