### ISSUE TITLE
Code doesn't work: Doc

### ISSUE THREAD

**Issue by RileyDevGithub** [godotengine/godot-docs#7734]
*4.0*

In this doc, the jump doesn't work.

**Doc:** https://docs.godotengine.org/en/stable/getting_started/first_3d_game/03.player_movement_code.html

**Comment by AThousandShips** [comment]
There isn't any jump code, so there's nothing that "doesn't" work

**Comment by RileyDevGithub** [comment]
Sorry.

**Comment by RileyDevGithub** [comment]
Sorry. *Ends issue*
