### ISSUE TITLE
Documentation on Skeletons, Bones and IK are completely irrelevant

### ISSUE THREAD

**Issue by Lyxilytical** [godotengine/godot-docs#7735]
**Your Godot version: v4.1.1.stable.official [bd6af8e0e]**

**Issue description:**

https://docs.godotengine.org/en/stable/tutorials/animation/cutout_animation.html
https://docs.godotengine.org/en/stable/tutorials/animation/2d_skeletons.html

Everything relating to skeletons and bones in Godot 4's documentation is outdated, docs show menu options that don't exist anymore and describe things that you can't do in Godot 4.

**Comment by AThousandShips** [comment]
It says it's outdated at the very top

**Comment by Lyxilytical** [comment]
Sorry, I did make a mistake- however the 2D skeletons page is out of date, its the cutout animation page that clarifies that it might be outdated. Still needs to be updated, but yeah this is a duplicate.
