### ISSUE TITLE
out of date export syntax on Godot notifications page

### ISSUE THREAD

**Issue by willisplummer** [godotengine/godot-docs#7760]
**Your Godot version:**
4.1

**Issue description:**

export syntax is out of date (not using `@export`)

**URL to the documentation page:**

https://github.com/godotengine/godot-docs/blob/master/tutorials/best_practices/godot_notifications.rst

**Comment by Behdjdusus** [comment]
> **Your Godot version:**
> 4.1
> 
> **Issue description:**
> 
> export syntax is out of date (not using @export)
> 
> **URL to the documentation page:**
> 
> https://github.com/godotengine/godot-docs/blob/master/tutorials/best_practices/godot_notifications.rst
> 

~~@ ~~

**Comment by isorfilas** [comment]
The whole GDScript example under "_init vs. initializations vs. export" appears to be out of date, not just the missing @ before export.
 - The setter syntax is out of date
 - The comment in the _init() function is incorrect; changing the variable will call the setter now, even without using self.
