### ISSUE TITLE
Add several missing tooltips of project settings' properties.

### ISSUE THREAD

**Issue by Null-Ping** [godotengine/godot-docs#7771]
**Your Godot version:**
4.2.dev2

URL to the documentation page (if already existing):
https://docs.godotengine.org/en/latest/classes/class_projectsettings.html

Issue description:
The following project settings' properties (from the "General" tab)  have: "No description." in their tooltips in the Godot editor.
Adding the tooltips would make it easier for developers to use the settings in their projects.

- display/window/stretch/aspect
- display/window/stretch/scale
- editor/import/reimport_missing_imported_files
- editor/version_control/plugin_name
- editor/version_control/autoload_on_startup
- rendering/rendering_device/staging_buffer/block_size_kb
- rendering/rendering_device/staging_buffer/max_size_mb
- rendering/rendering_device/staging_buffer/texture_upload_region_size_px
- rendering/rendering_device/vulkan/max_descriptors_per_pool
- rendering/limits/time/time_rollover_secs
- rendering/limits/global_shader_variables/buffer_size
- rendering/limits/spatial_indexer/update_iterations_per_frame
- rendering/limits/spatial_indexer/threaded_cull_minimum_instances
- rendering/limits/forward_renderer/threaded_render_minimum_instances
- rendering/shader_compiler/shader_cache/compress
- rendering/shader_compiler/shader_cache/use_zstd_compression
- rendering/shader_compiler/shader_cache/strip_debug
- rendering/shader_compiler/shader_cache/strip_debug.release
- gui/fonts/dynamic_fonts/use_oversampling
- threading/worker_pool/use_system_threads_for_low_priority_tasks
- threading/worker_pool/low_priority_thread_ratio

**Comment by Piralein** [comment]
Closing as per [comment](https://github.com/godotengine/godot-docs/issues/7770#issuecomment-1664324417).

Thank you for reporting the issue nevertheless!
