### ISSUE TITLE
Identifier "_on_timer_timeout" not declared in the current scope

### ISSUE THREAD

**Issue by deogracia** [godotengine/godot-docs#7778]
**Your Godot version:**
Godot Engine v4.1.1.stable.official [bd6af8e0e]

**Issue description:**
Following https://docs.godotengine.org/en/stable/getting_started/step_by_step/signals.html#connecting-a-signal-via-code leads to the error in object, as you can see in the screenshot below.
![image](https://github.com/godotengine/godot-docs/assets/553342/3d63342b-73d8-4326-9c76-80464f66fbd3)

**URL to the documentation page:**
https://docs.godotengine.org/en/stable/getting_started/step_by_step/signals.html#connecting-a-signal-via-code

**Comment by Piralein** [comment]
It is explained beneath the code example.

`The line reads like so: we connect the Timer's "timeout" signal to the node to which the script is attached. When the Timer emits timeout, we want to call the function _on_timer_timeout(), that we need to define. Let's add it at the bottom of our script and use it to toggle our sprite's visibility.`

**Comment by deogracia** [comment]
damned! thanks a lot @Piralein ! I didn't pay attention to the rest of the page and were focus on this temporary error.

So it's not a "bug" in the documentation. But a "bug" in the way I read the documentation.

I'm closing this issue.
