### ISSUE TITLE
VehicleBody3D points to the 3.5 version of the Truck demo

### ISSUE THREAD

**Issue by creiht** [godotengine/godot-docs#7782]
**Your Godot version:**
4.1.1

**Issue description:**
The docs of VehicleBody3D point to a download of the 3.5 version of the Truck Demo, but there is a 4.0 branch in the demo repository.  Would be preferable to create a new download for 4.x or at least point to the correct github branch.  Thanks!

**URL to the documentation page:**
https://docs.godotengine.org/en/stable/classes/class_vehiclebody3d.html

If you know how to fix the issue you are reporting please
consider opening a pull request. We provide a tutorial on
using git here: https://docs.godotengine.org/en/stable/community/contributing/pr_workflow.html,
writing documentation at https://docs.godotengine.org/en/stable/community/contributing/docs_writing_guidelines.html
and contributing to the class reference here: https://docs.godotengine.org/en/stable/community/contributing/updating_the_class_reference.html

**Comment by creiht** [comment]
If I could get some guidance on preference for resolution, I don't mind working on a pull request to fix.

**Comment by AThousandShips** [comment]
See:
* #7000
