### ISSUE TITLE
Screenshot and description in getting started guide outdated

### ISSUE THREAD

**Issue by neilsf** [godotengine/godot-docs#7785]
**Your Godot version:** v4.1.1.stable.official

**Issue description:**

Animation tab is different from what is written in documentation. The documentation shows this image (note the version on the screenshot is 4.0.beta17)

![image](https://github.com/godotengine/godot-docs/assets/5172851/870dbc48-3a3e-43d2-8b5e-03c0c2cde138)

And this is what I get (note my version is 4.1.1.stable)

![image](https://github.com/godotengine/godot-docs/assets/5172851/fe87722a-e7a3-4679-9d8d-ebdbeb8a60c2)

I can't go on with the tutorial now, because in my version there is no "SpriteFrames" tab.

**URL to the documentation page:** https://docs.godotengine.org/en/stable/getting_started/first_2d_game/02.player_scene.html#sprite-animation

**Comment by AThousandShips** [comment]
You're in the wrong window, you need to open the editor, as per the instructions:
> To create one, find the Sprite Frames property under the Animation tab in the Inspector and click "[empty]" -> "New SpriteFrames". Click again to open the "SpriteFrames" panel:

**Comment by neilsf** [comment]
Right... my bad, thanks for the clarification!
