### ISSUE TITLE
CollisionShape2D.shape missing methods

### ISSUE THREAD

**Issue by pc9098** [godotengine/godot-docs#7787]
Godot version: 4.1.1

There is no information of the methods of CollisionShape2D.shape
I've tried gathering information about `CollisionShape2D.RectangleShape2D.extends( Vector2 )` but no info is in the docs.
I also wanted to see if there are more methods in RectangleShape2D that docs don't show

URL to the documentation page: 
https://docs.godotengine.org/en/stable/classes/class_rectangleshape2d.html#class-rectangleshape2d
https://docs.godotengine.org/en/stable/classes/class_shape2d.html#class-shape2d

**Comment by AThousandShips** [comment]
It isn't called this in 4.x, it's `size`, renamed from 3.x

**Comment by pc9098** [comment]
Thank you, didn't know it changed from extents to size!

**Comment by AThousandShips** [comment]
Changes are documented [here](https://docs.godotengine.org/en/latest/tutorials/migrating/upgrading_to_godot_4.html#list-of-automatically-renamed-methods-properties-signals-and-constants)
