### ISSUE TITLE
Mistake in NavigationAgent2D Tooltip

### ISSUE THREAD

**Issue by hunterbk** [godotengine/godot-docs#7788]
**Godot 4.1**

**I found a mistake while reading the in-editor documentation tooltip for NavigationAgent2D**

**N/A**
I don't know how to link the in-game documentation but I have an image showing where it is in the editor.
![image](https://github.com/godotengine/godot-docs/assets/36772761/0f2f5e46-dd41-4a1a-9d25-4704fd178a8b)

**Comment by hunterbk** [comment]
https://github.com/godotengine/godot/blob/master/doc/classes/NavigationAgent2D.xml
Line 183

**Comment by Piralein** [comment]
fixed by [#80474](https://github.com/godotengine/godot/pull/80474).
