### ISSUE TITLE
Ray-casting docs use outdated PhysicsRayQueryParameters constructors

### ISSUE THREAD

**Issue by Azeler-3** [godotengine/godot-docs#7797]
**Your Godot version:** 4.1 stable

**Issue description:** Code snippets in the page use outdated constructors for the PhysicsRayQueryParameters2D and PhysicsRayQueryParameters3D classes.

The query is written as `var query = PhysicsRayQueryParameters3D.create(origin, end)` when it should be :

`````
var query = PhysicsRayQueryParameters3D.new()
query.from = origin
query.to = end
`````

**URL to the documentation page:** https://docs.godotengine.org/en/stable/tutorials/physics/ray-casting.html

**Comment by tetrapod00** [comment]
The code currently in the docs works (and so does the proposed alternative in the OP). Closing this issue, since the current documentation example works.
