### ISSUE TITLE
After following the Documentation: compiling GDExtension in VS Code results in:  "scons: command not found"

### ISSUE THREAD

**Issue by Crakmaks** [godotengine/godot-docs#7801]
Your Godot version: 4.1

Issue description: I've followed the Tutorials in the following order:
https://docs.godotengine.org/en/stable/contributing/development/compiling/compiling_for_linuxbsd.html 
- worked, no problems

https://docs.godotengine.org/en/stable/tutorials/scripting/gdextension/gdextension_cpp_example.html 
- worked, no problems

https://docs.godotengine.org/en/stable/contributing/development/configuring_an_ide/visual_studio_code.html
-  When running the Task with Ctrl + Shift + B, I get thee following Error in Visual Studio Code(1.81.0) :
"Executing task: scons 
/bin/sh: line 1: scons: command not found
 *  The terminal process "/bin/sh '-c', 'scons'" failed to launch (exit code: 127). "

I'm on pop_os (ubuntu) and had this working in the past, but for some reason this time, VSCode (1.81.0) does not recognize scons. The OS install is completely fresh, the tutorials are basically the first thing I did after installing the OS. I hope this is easy to fix but I found nothing on google regarding this. Any idea what could be the reason for this? Help would be much appreciated!

URL to the documentation page: https://docs.godotengine.org/en/stable/contributing/development/configuring_an_ide/visual_studio_code.html

**Comment by paddy-exe** [comment]
I have some questions regarding your steps to get started with GDExtension
1. Did you compile Godot yourself or did you download the editor? 
2. Did you checkout the correct branch of Godot-cpp?
3. It seems you only tried to run VSCode through their Tasks Panel. Did you try to run the `scons` command manually in the terminal? That's at least the instruction in the tutorial.

**Comment by Crakmaks** [comment]
Hey, thank you for your time and your fast response!

Yes, I compiled Godot from source and Godot and Godot-Cpp where on the same branch.
To clarify, scons works perfectly fine, when I use the Linux Terminal. The GDextension Demo compiles and opens in the self compiled Godot Editor without error. So the core problem is, that VS Code does not now what scons is. 

Regarding your third question, do mean by terminal, the Linux Terminal or the VS Code Terminal? In the Linux Terminal it compiles without error. In the VSCode Terminal I get:
"[212 preload-host-spawn-strategy] Warning: waitpid override ignores groups
sh: scons: command not found"
when entering scons by hand.

**Comment by paddy-exe** [comment]
> To clarify, scons works perfectly fine, when I use the Linux Terminal. The GDextension Demo compiles and opens in the self compiled Godot Editor without error. So the core problem is, that VS Code does not now what scons is.

That is very odd. However then it seems like VSCode cannot access your installed pip modules (including scons)

From [googling the error message](https://github.com/flathub/com.visualstudio.code/issues/370#issuecomment-1563240250) it seems you need to disable this setting in VSCode:
![image](https://github.com/godotengine/godot-docs/assets/38077837/24c1e459-b5ff-4842-a93d-a0b95a089af6)

**Comment by Crakmaks** [comment]
Thank you very much! While the setting you mentioned is no longer available, following the rest of the ticket helped. There seems to be a bug, in the flatpak version of VSCode. In the POP!_SHOP the VSCode version can be switched from .flatpak to .deb. That solved the issue and it now works! 
Again thank you very much for your help, it is much appreciated!
