### ISSUE TITLE
[4.X] AnimatedSprite/SpriteFrames _normal et _secular suffixes

### ISSUE THREAD

**Issue by Selenyhr** [godotengine/godot-docs#7803]
**Your Godot version:**
v4.1.1.stable.arch_linux

**Issue description:**
AnimatedSprite and SpriteFrames mention the 3.X suffixes that allow for usage of _normal and _secular suffixes to define normal map or secular map of animations.
This behavior was however removed during the 4.0 lighting rework and the internal doc was updated in https://github.com/godotengine/godot/pull/71145. The online doc however doesn't seem to have been updated accordingly.

**URL to the documentation page:**
https://docs.godotengine.org/fr/stable/classes/class_animatedsprite.html
https://docs.godotengine.org/fr/stable/classes/class_spriteframes.html

**Comment by AThousandShips** [comment]
The translated documentation is not up to date, see:
* #7233

Closing as a duplicate, thank you for reporting
