### ISSUE TITLE
Possible outdated docs

### ISSUE THREAD

**Issue by imartc04** [godotengine/godot-docs#7819]
**Godot 4.1**

** In the example of GDExtension the next include is done: #include <godot_cpp/classes/sprite2d.hpp> . It seems that class header neither other of nodes is present now in the godot-cpp repository. I would like to know if it is possible to create node objects like sprite2D with GDExtension now, maybe it has to be done in another way now.**

**https://docs.godotengine.org/en/stable/tutorials/scripting/gdextension/gdextension_cpp_example.html**

**Comment by AThousandShips** [comment]
There's a specific tracker for this, please comment on https://github.com/godotengine/godot-docs/issues/5121

**Comment by imartc04** [comment]
ok thanks

**Comment by imartc04** [comment]
moving question
