### ISSUE TITLE
Warning boxes have hardcoded title "Attention: Here be dragons"

### ISSUE THREAD

**Issue by pl7y** [godotengine/godot-docs#7827]
**Your Godot version:**

**Issue description:**
Warning boxes have hardcoded title "Attention: Here be dragons"
<img width="833" alt="image" src="https://github.com/godotengine/godot-docs/assets/10465876/33492a90-7f31-4ff9-bff8-94241f7225c2">

**URL to the documentation page:**
https://docs.godotengine.org/en/latest/contributing/development/compiling/

**Comment by AThousandShips** [comment]
Only the version warning, which is a reference and not a bug, what's wrong with it?

**Comment by pl7y** [comment]
I didn't get the reference and thought it was a placeholder of some kind.

**Comment by AThousandShips** [comment]
It is a reference to old maps saying "here be dragons" on unexplored territory, and the new versions are unexplored as well
