### ISSUE TITLE
Standard 3D Materials: Image channel selection for addtional properties

### ISSUE THREAD

**Issue by pemguin005** [godotengine/godot-docs#7835]
**Your Godot version:**
Godot 4.1

**Issue description:**
Image files used for Standard 3D materials have 4 channels of color data that can be used to describe a 3D materials properties. Channel packing is a common practice to pack more data into fewer image files. Godot leverages this in 3D materials, allowing you to pick which color channel the data is coming from for the following material properties:
_Roughness, Metallic, Ambient Occlusion, Refraction._

But it doesn't allow for picking specific channels for some other properties:
_Normals, Emission, Height, Subsurface Scattering, and a few others_

I'd really like to use channel selection for the other properties as well, in particular Emission and Height the most. 

I understand Godot calculating and making compressed normal maps from the Red and Green channels, and that process may tie up channel selection for Normal maps, but since height , emission, etc channels can't be specified, and by default pull from the red channel (as i understand), I'm forced to include them separately. 

Is there a reason that Godot currently has channel selection for some properties but but not others? I'd really like to take channel packing further but the limitation to use only the red channel for some maps is preventative. 

**URL to the documentation page (if already existing):**
https://docs.godotengine.org/en/4.1/tutorials/3d/standard_material_3d.html
![materials_lacking_channel](https://github.com/godotengine/godot-docs/assets/43008564/9432ae03-7c40-4a46-a3fe-24c60df84c08)

**Comment by skyace65** [comment]
Please do not open issues in the docs repository for feature requests. Instead you're going to want to open an issue in the godot-proposals repository [here](https://github.com/godotengine/godot-proposals) where it can be properly discussed.
