### ISSUE TITLE
PhysicsServer3D speaks about PhysicsServer2D when it shouldn't?

### ISSUE THREAD

**Issue by NatGazer** [godotengine/godot-docs#7839]
**Issue description:** Look at the image below or click the link. Shouldn't it be "PhysicsServer3D is the server responsible for all 3D physics. It can directly create and manipulate all physics objects:"? I might be missing something

**URL to the documentation page:** https://docs.godotengine.org/en/stable/classes/class_physicsserver3d.html#class-physicsserver3d

![image](https://github.com/godotengine/godot-docs/assets/67602607/f21f50a1-bea1-4400-a12b-8cf4bf29e142)

**Comment by AThousandShips** [comment]
This has already been solved, the 4.1 documentation just hasn't been updated to match, see [here](https://docs.godotengine.org/en/latest/classes/class_physicsserver3d.html)
