### ISSUE TITLE
Incorrect icon file type

### ISSUE THREAD

**Issue by interrealm** [godotengine/godot-docs#7841]
Godot v4.1.1.stable.official [bd6af8e0e]

In the tutorial 'Your first 2D game', setting up the project, it says that the project folder should have an icon file named `icon.png`. However, mine loads up with `icon.svg`.

[Setting up the project — Godot Engine (stable) documentation in English](https://docs.godotengine.org/en/stable/getting_started/first_2d_game/01.project_setup.html)
![image](https://github.com/godotengine/godot-docs/assets/117502202/f2439876-775c-4899-ac49-d690ee29df51)
vs
<img width="252" alt="Screenshot 2023-08-26 at 8 29 06 pm" src="https://github.com/godotengine/godot-docs/assets/117502202/4cf83e4f-6373-4bb9-85c5-753ba5d8d415">

**Comment by AThousandShips** [comment]
That screenshot is indeed out of date, see [below](https://docs.godotengine.org/en/stable/getting_started/first_2d_game/01.project_setup.html#organizing-the-project) where the correct format is listed
