### ISSUE TITLE
Undocumented decoupling of `Camera2D` and `ParallaxBackground` by overriding `ParallaxBackground._camera_moved`

### ISSUE THREAD

**Issue by Rubonnek** [godotengine/godot-docs#7843]
**Your Godot version:**
3.x~4.x

**Issue description:**
It's possible to decouple `ParallaxBackground` from an existing `Camera2D` node by overriding `ParallaxBackground._camera_moved` but this is not mentioned in the documentation. See https://github.com/godotengine/godot/issues/42586#issuecomment-1693638013 for more information.

**URL to the documentation page (if already existing):**
https://docs.godotengine.org/en/stable/classes/class_parallaxbackground.html

**Comment by rpahut** [comment]
Possibly related: [#48342](https://github.com/godotengine/godot/issues/48342)

**Comment by AThousandShips** [comment]
This is an internal hidden method, only bound for internal use AFAIK, possibly as a leftover from the pre-callable method pointer days and might not even have been exposed if it was implemented today

**Comment by Rubonnek** [comment]
Closing this as not planned for the reasons stated above.
