### ISSUE TITLE
Godot 4.1 C# Basics--Configuring an external editor¶ describes incorrect method of setting external editor

### ISSUE THREAD

**Issue by bsmitty5000** [godotengine/godot-docs#7853]
4.1.1

It appears that incorrect information is shown in the C# Basics page for configuring external editor. Maybe it's best to link to the following section of the documentation that does have the correct procedure: https://docs.godotengine.org/en/stable/tutorials/editor/external_editor.html#using-an-external-text-editor

Configuring an external editor[¶](https://docs.godotengine.org/en/stable/tutorials/scripting/c_sharp/c_sharp_basics.html#configuring-an-external-editor)

**Comment by raulsntos** [comment]
What makes you think the information shown is incorrect?

The page you linked as the correct one describes a different setting (`text_editor/external`). The C# documentation is describing `dotnet/editor/external_editor`. The TextEditor setting applies to every file, the C# setting only applies to C# scripts.

**Comment by bsmitty5000** [comment]
> The TextEditor setting applies to every file, the C# setting only applies
to C# scripts.

Thanks for clarifying that. Maybe I was too eager to help out and created
this ticket unnecessarily.

When I'm in Editor->Editor Settings I do not find any menu item or anything
related to Dotnet and using the search/filter for 'Dotnet' finds nothing
either:

[image: image.png]


I assumed this was possibly an option in previous versions and was removed
for version 4.
