### ISSUE TITLE
C# Example for Making plugins

### ISSUE THREAD

**Issue by a2937** [godotengine/godot-docs#7859]
**Your Godot version:** 4.1 

**Issue description:** The last example is missing a C# equivalent. I'd like to that the C# versions of plugins can be automatically be loaded but I haven't tried to do this myself. 

**URL to the documentation page (if already existing):**
https://docs.godotengine.org/en/stable/tutorials/plugins/editor/making_plugins.html

**Comment by raulsntos** [comment]
Yes, registering autoloads with a C# plugin is supported. Pull requests to add the missing C# equivalent to the example are welcomed :slightly_smiling_face:.

**Comment by mateuseap** [comment]
@a2937 @raulsntos I'll open a PR adding it!
