### ISSUE TITLE
Please make it easier to use World Space Coordinates in Canvas Shaders and/or document the current working approach.

### ISSUE THREAD

**Issue by simonschreibt-code** [godotengine/godot-docs#7860]
**Your Godot version:**
4.1.1

**Issue description:**
Accessing World Space based Vertex/Pixel Positions should "just work" (for example, by using a pre-defined keyword like `POSITION_WP` or similar).
Also a problem: There are many posts on the internet which ask for this and there are many workarounds which don't work anymore in 4.x. For this case, it would be nice if the documentation would give a full example (vertex + fragment shader). In the URL below you'll find an example for the vertex shader but it would be nice to add the fragment shader for example:

```shader_type canvas_item;

varying vec2 world_position;

void vertex() {
	world_position = (MODEL_MATRIX * vec4(VERTEX, 0.0, 1.0)).xy;
}

void fragment() {
	vec2 UV_in_world_space = world_position.xy;
}
```

**URL to the documentation page (if already existing):**
https://docs.godotengine.org/en/latest/tutorials/shaders/shader_reference/canvas_item_shader.html

**Comment by clayjohn** [comment]
I think it's time for us to revisit adding a ``world_vertex_coord`` render mode to 2D like we have for 3D (see https://github.com/godotengine/godot/issues/19800)

The idea was rejected for 3.x as there were some awkward edge cases. But these have been resolved in Godot 4, so there is nothing stopping us now.

Cc @paddy-exe who may be interested in this
