### ISSUE TITLE
Add a convenient way to switch between versions

### ISSUE THREAD

**Issue by Acu1000** [godotengine/godot-docs#7868]
Currently when you search "Godot 3 [something]" on google it always gives the docs page for Godot 4, and only sometimes it also shows the Godot 3 docs as well. That often makes it more bothersome to find the article you're looking for. I believe it is a major inconvenience for many Godot 3.x users, so I propose the following:

My idea is to have each Godot 4 docs page contain a button/link on top that takes the user to the equivalent page of the latest Godot 3 release docs. (perhaps somewhere in the green "up to date" info box)

**Comment by raulsntos** [comment]
This already exists in the bottom left.

![image](https://github.com/godotengine/godot-docs/assets/3903059/59bebfbd-f0ef-403f-bced-40912d7bc2a0)

Clicking on any of those versions will take you to the equivalent page in the version that you clicked.

**Comment by Acu1000** [comment]
Oh, I had no idea, thanks a lot!
