### ISSUE TITLE
Tween cheatsheet link broken after replacing "tween_cheatsheet.png" with "tween_cheatsheet.webp"

### ISSUE THREAD

**Issue by belzecue** [godotengine/godot-docs#7871]
The tween page has a link to a cheatsheet image that is broken for all versions except 4.1.

https://docs.godotengine.org/en/stable/classes/class_tween.html

On this page, there is a link named "Tween easing and transition types cheatsheet" which links to https://raw.githubusercontent.com/godotengine/godot-docs/master/img/tween_cheatsheet.webp

For prior versions, this page has a similar link but to a png instead of the webp:

4.1 -> https://raw.githubusercontent.com/godotengine/godot-docs/master/img/tween_cheatsheet.webp
4.0 -> https://raw.githubusercontent.com/godotengine/godot-docs/master/img/tween_cheatsheet.png
3.6 -> https://raw.githubusercontent.com/godotengine/godot-docs/master/img/tween_cheatsheet.png
etc.

To fix these broken links, either the old "tween_cheatsheet.png" file needs to be readded to master or each page version prior to 4.1 needs to have its URL updated to include the version number in the URL instead of "master", e.g.

4.0 -> https://raw.githubusercontent.com/godotengine/godot-docs/4.0/img/tween_cheatsheet.png
3.6 -> https://raw.githubusercontent.com/godotengine/godot-docs/3.6/img/tween_cheatsheet.png
etc.

I don't know when the .png file was deleted, but the commit for changing the link was:
Commit 5482c93e8 ("classref: Sync with current master branch (19e7490)", 2023-06-24)

-\ `Tween easing and transition types cheatsheet <https://raw.githubusercontent.com/godotengine/godot-docs/master/img/tween_cheatsheet.png>`__\ 
+\ `Tween easing and transition types cheatsheet <https://raw.githubusercontent.com/godotengine/godot-docs/master/img/tween_cheatsheet.webp>`__\

**Comment by AThousandShips** [comment]
These have been fixed, they haven't been updated on the web yet though

**Comment by skyace65** [comment]
This has been updated on the web now.

**Comment by idbrii** [comment]
@skyace65: 3.6 still uses the link to master. The [file is still correct](https://github.com/godotengine/godot/blob/3.x/doc/classes/Tween.xml#L19) in the 3.x branch, but web doesn't have it yet.

Both 3.6 pages still use the wrong link. But 3.5 is correct. See [Tween](https://docs.godotengine.org/en/3.6/classes/class_tween.html).
