### ISSUE TITLE
HELP ME idk wat de hell i do

### ISSUE THREAD

**Issue by marcosgithubs** [godotengine/godot-docs#7879]
godot version 4.1

extends CharacterBody2D

@onready var _animated_sprite := $anim as AnimatedSprite2D

func _process(delta):
	if Input.is_action_pressed("ui_right"):
		_animated_sprite.play("walk")
		
		else :
			_animated_sprite_stop()

it says "expected statement, found "else" instead " someone help me plz

**Comment by AThousandShips** [comment]
For support questions and help please turn to the other [community channels](https://godotengine.org/community), this is for bug reporting, not a help desk. Please use other channels *first* to see if this is a bug or user error.
