### ISSUE TITLE
You need an intro on the top Doc page

### ISSUE THREAD

**Issue by allan-bonadio** [godotengine/godot-docs#7883]
**Your Godot version:**
none

**Issue description:**
I stumbed onto one of your pages, looking for webdev info.  Nowhere did it say what Godot was, Until I started reading.  It shouldn't take me 5 minutes to realize this site has nothing to do with what I'm searching for.

**URL to the documentation page:**
https://docs.godotengine.org/en/stable/index.html

Needs the intro, as quoted from this page:
https://docs.godotengine.org/en/stable/about/introduction.html

"Godot Engine is a feature-packed, ...not-for-profit."

This should go BEFORE the version number info - why would I care what version this is if I don't know what Godot is?  Hopefully, before the 'this is up to date' note, cuz I also don't care if this page is up to date, all I know is that it's from the late Pleistocene cuz it doesn't tell me what Godot is.  I know that the version number is all-important to you guys, but think of your audience for the front page - the whole entire internet.  Would your grandmother understand the front page and how she isn't interested in it?  You have to fix this.

As a programmer who might be looking for a game engine, I'll tell you that I wouldn't pick Godot, because I can guess that your documentation will probably be full of holes that you should have mentioned, but didn't.  Like the intro.  This is a common problem with programmers who write documentation and can't step back and get the big picture.  "What is it" should be the first thing every page talks about.

PS: 99.9% of the people who are pissed off because you wasted their time, will not complain or open a ticket.  Consider yourselves lucky.

**Comment by YuriSizov** [comment]
The first sentence of the first paragraph on the linked page tells you what Godot is:

> Welcome to the official documentation of [Godot Engine](https://godotengine.org/), the free and open source community-driven 2D and 3D game engine!

Also, your attitude is not appreciated. You may've stumbled upon Godot accidentally, but this platform is still covered by Godot's [code of conduct](https://godotengine.org/code-of-conduct/).
