### ISSUE TITLE
A problem about editor icons

### ISSUE THREAD

**Issue by dawnrs** [godotengine/godot-docs#7885]
https://github.com/godotengine/godot-docs/blob/7fe92ada621314fa9afcaf652a6d5e7d55cfbce2/tutorials/scripting/gdextension/gdextension_cpp_example.rst?plain=1#L445-L446
Hi, I found a bit of problem.
`[Icon]` is not working in godot4.1
I suppose it should be `[icons]` which is working well on my computer.

**Comment by paddy-exe** [comment]
Will be fixed by https://github.com/godotengine/godot-docs/pull/7820
