### ISSUE TITLE
"SpriteFrames" panel not present 

### ISSUE THREAD

**Issue by MatteoLeonesi** [godotengine/godot-docs#7886]
**Godot version: 4.1.1.stable**

**Issue description:** :[ in this documentation page](https://docs.godotengine.org/en/stable/getting_started/first_2d_game/02.player_scene.html), the "Sprite Animation" chapter mentions a "SpriteFrames" panel. However, this panel is not located in the same position as the current version, making it difficult to follow the tutorial.

**URL to the documentation page: https://docs.godotengine.org/en/stable/getting_started/first_2d_game/02.player_scene.html**

**Comment by AThousandShips** [comment]
What part has a different location than the documentation specifies?

**Comment by jressey** [comment]
> What part has a different location than the documentation specifies?
> 
> The documentation says to go to the inspector to select and assign the `Sprite Frames` property under the inspector, but then says to click it again to open the panel, it does not say that the panel is under the inspector, it talks about the property:
> 
> > To create one, find the Sprite Frames property under the Animation tab in the Inspector and click "[empty]" -> "New SpriteFrames". Click again to open the "SpriteFrames" panel:
> 
> And shows that the panel pops up at the bottom of the screen with the other panels
> 
> It could be said to be unclear, but the screenshot should make it obvious where it is

I'm a long-time professional software engineer and these instructions are more than a little unclear. A lousy welcome to a new user.

**Comment by zarbafian** [comment]
Could this issue be reopened as it has not been fixed? What is suggested by jressey works, but the issue is not with the feature but with the documentation, and the link to open an issue with the documentation leads here.
