### ISSUE TITLE
ImmediateMesh online documentation claims it is a Node when it isn't

### ISSUE THREAD

**Issue by DevKnightlie** [godotengine/godot-docs#7895]
**Your Godot version:** 4.1

**Issue description:** ImmediateMesh online documentation linked by the IDE claims it is a Node when it isn't, and the page claims to be up to date for V4.1. Internal IDE documentation correctly lists ImmediateMesh as a Resource.

**URL to the documentation page:** https://docs.godotengine.org/en/4.1/tutorials/3d/procedural_geometry/immediatemesh.html

If you know how to fix the issue you are reporting please
consider opening a pull request. We provide a tutorial on
using git here: https://docs.godotengine.org/en/stable/community/contributing/pr_workflow.html,
writing documentation at https://docs.godotengine.org/en/stable/community/contributing/docs_writing_guidelines.html
and contributing to the class reference here: https://docs.godotengine.org/en/stable/community/contributing/updating_the_class_reference.html

**Comment by AThousandShips** [comment]
This is simply a case of a page being out of date I believe, it is pretty much just renamed from the 3.x version:
https://docs.godotengine.org/en/3.6/tutorials/3d/procedural_geometry/immediategeometry.html

**Comment by DevKnightlie** [comment]
Looks that way, but it's causing confusion as it contradicts the IDE docs.

**Comment by AThousandShips** [comment]
I agree! Unsure what way to go, the page probably needs to be entirely rewritten

**Comment by patrickdown** [comment]
Also, as it is currently, I'm not sure what utility ImmediateMesh is providing that SurfaceTool doesn't cover.
