### ISSUE TITLE
Missing tutorial for Light Baking

### ISSUE THREAD

**Issue by unfa** [godotengine/godot-docs#79]
I guess some people are really waiting to learn about this topic (I know I do).

Can we expect a tutorial for it anytime soon?

BTW: Thank you for amazing work on the engine and the documentation! You are amazing!

**Comment by pwab** [comment]
Not sure but could this [blog post](https://godotengine.org/article/introducing-new-last-minute-lightmapper) be a good start for this? If so should it be "converted" into a docs page?

**Comment by Calinou** [comment]
A light baking tutorial has been added to the documentation in the `master` branch: [Baked Lightmaps](http://docs.godotengine.org/en/latest/learning/features/3d/baked_lightmaps.html)
