### ISSUE TITLE
Export / Exporting for Android: SdkManagerCli requires OpenJDK 17

### ISSUE THREAD

**Issue by Alex2782** [godotengine/godot-docs#7902]
**Your Godot version:**
Godot v4.2.dev4 - macOS 13.5.1 - Vulkan (Forward+) - integrated Apple M1 - Apple M1 (8 Threads)

**Issue description:**

I had to install **OpenJDK 17**. (Creating an APK file was also possible with version 17)

`sdkmanager --sdk_root=<android_sdk_path> "platform-tools" "build-tools;33.0.2" "platforms;android-33" "cmdline-tools;latest" "cmake;3.10.2.4988404" "ndk;23.2.8568313"`

**Error:**
`	java.lang.UnsupportedClassVersionError: com/android/sdklib/tool/sdkmanager/SdkManagerCli has been compiled by a more recent version of the Java Runtime (class file version 61.0), this version of the Java Runtime only recognizes class file versions up to 55.0`

* 55 = Java 11
* 61 = Java 17

---
new 'navigation'-URL (now `#command-line-tools-only`)
https://developer.android.com/studio#command-line-tools-only

**URL to the documentation page:**
https://docs.godotengine.org/en/latest/tutorials/export/exporting_for_android.html#install-openjdk-11

**Comment by Rindbee** [comment]
This is the JDK version requirement for `cmdline-tools;latest` (`cmdline-tools;11.0`). I tried `cmdline-tools;10.0` and JDK11 still works fine.

https://github.com/godotengine/godot-docs/blob/8b4cc3b2294a59a8d56cb0e415585a2279a960b6/contributing/development/compiling/compiling_for_android.rst?plain=1#L71

https://github.com/godotengine/godot-docs/blob/8b4cc3b2294a59a8d56cb0e415585a2279a960b6/tutorials/export/exporting_for_android.rst?plain=1#L49

The versions recommended by the above two documents are inconsistent, which will also cause some confusion.

**Comment by Alex2782** [comment]
@Rindbee 
> I tried cmdline-tools;10.0 and JDK11 still works fine.

Is it still possible to download the old version?
I tried the 'alternative' method without Android Studio. (macOS) 
With OpenJDK 17 I have not encountered any problems so far.

![image](https://github.com/godotengine/godot-docs/assets/41921395/977ea8aa-b510-47ab-a150-80f38a609aad)

**Comment by Rindbee** [comment]
> Is it still possible to download the old version? 

Download through JDK17 and `sdkmanager` in the latest version of `cmdline-tool`:
```
sdkmanager "cmdline-tools;10.0"
```
All available Packages can be queried with the following command:
```
sdkmanager --list
```

> I tried the 'alternative' method without Android Studio. (macOS) With OpenJDK 17 I have not encountered any problems so far.

There seems to be no build failure, just not wanting to see the `Deprecated in Java` message.
