### ISSUE TITLE
Update From Unity to Godot page

### ISSUE THREAD

**Issue by GersonFeDutra** [godotengine/godot-docs#7905]
**Your Godot version:** 4

**Issue description:** Given the recent events, I think it is valid to stress the importance of an updated version of the tutorial "From Unity to Godot" for Godot 4.

I would like to help with that, but I have not used Unity for a long time.

**URL to the documentation page (if already existing):** [Old page](https://docs.godotengine.org/en/3.1/getting_started/editor/unity_to_godot.html)

**Comment by IkutiDev** [comment]
It seems the page got deleted in the current documentation. I would also agree, beside recent events, this page was super helpful when I moved from Unity to Godot and having a page with at least old info removed/changed to 4.x standards would be great.

This would be another issue, but it also might be worth to think about making similar pages in the docs for other engines (From UJnreal to Godot, From Gamemaker to Godot, From Defold to Godot), if there are any willing contributors with extensive knowledge of another engines.

**Comment by AThousandShips** [comment]
This was removed in:
* https://github.com/godotengine/godot-docs/pull/3920

**Comment by skyace65** [comment]
Closing this issue. The reasons in the original PR that removed this that AThousandShips linked to are still relevant today and haven't changed.
