### ISSUE TITLE
.glb Animation Library Reimport Corrupts Scene and .glb File

### ISSUE THREAD

**Issue by nubbyninja** [godotengine/godot-docs#7913]
Version: **v4.1.1.stable.mono.official [bd6af8e0e]**

This is my first Godot project, coming from Unity, so please bear with me. 
When attempting to make use of the Animation Library feature, I select the .glb file with the animations I intend to use, 
On the Import Panel, 
Import As: Animation Library
Reimport
-editor closes and reopens-
"Scene corrupted"
The model is now also corrupted. 
Repeated these steps at least 3 times. 

All models are exported as .glb from Blender 3.3.10

**Comment by Calinou** [comment]
- Superseded by https://github.com/godotengine/godot/issues/81671.
