### ISSUE TITLE
[3.x] There are no C# code examples in `Using signals`.

### ISSUE THREAD

**Issue by whtsht** [godotengine/godot-docs#7917]
**Your Godot version:**
v3.5.2

**Issue description:**
There is no C# code example in `GETTING STARTED >> Step by Step >> Using signals`.

**URL to the documentation page (if already existing):**
https://docs.godotengine.org/en/3.5/getting_started/step_by_step/signals.html

**Comment by NEKERAFA** [comment]
You have a entry with examples of C# signals in the C# features page (Scripting > Programming Languages > C# > C# features):

[https://docs.godotengine.org/en/3.5/tutorials/scripting/c_sharp/c_sharp_features.html#c-signals](https://docs.godotengine.org/en/3.5/tutorials/scripting/c_sharp/c_sharp_features.html#c-signals)

**Comment by whtsht** [comment]
I plan to submit pull requests for changes to versions 3.4, 3.5, and 3.6 according to [C# features page](https://docs.godotengine.org/en/3.5/tutorials/scripting/c_sharp/c_sharp_features.html). No C# features page was found for other versions.

**Comment by skyace65** [comment]
Fixed by #7945.
