### ISSUE TITLE
Error in the 4.1 Internationalizing games part of the documentation

### ISSUE THREAD

**Issue by Suzakton** [godotengine/godot-docs#7921]
**Your Godot version:**
4.1.1

**Issue description:**
In the Internationalizing games / Translating the project name, part of the 4.1 doc (up to date), it say "application/name" where in the godot editor it's "application/config/name".
And it seems that there is already a way to localize the project name with the "application/config/name_localized"

Since i'm new to godot i'm not really sure but this is probably an error.

**URL to the documentation page:**
https://docs.godotengine.org/en/stable/tutorials/i18n/internationalizing_games.html#translating-the-project-name

**Comment by skyace65** [comment]
Fixed by #9020.
