### ISSUE TITLE
Clarify what "local coordinates" means in the spatial shader docs

### ISSUE THREAD

**Issue by mieldepoche** [godotengine/godot-docs#7927]
**Your Godot version:** 4.1.1

**Issue description:**

![image](https://github.com/godotengine/godot-docs/assets/71937306/9449c742-900f-4235-b6e3-fad44c59ba8e)

it is unclear what "local coordinates" refer to. I think it's view space.
It should use the same terminology as other entries that all refer to a kind of space (model, view, world).

**URL to the documentation page:** https://docs.godotengine.org/en/stable/tutorials/shaders/shader_reference/spatial_shader.html

**Comment by AThousandShips** [comment]
Look above:
> Vertex data (VERTEX, NORMAL, TANGENT, BITANGENT) are presented in local model space. If not written to, these values will not be modified and be passed through as they came.
>
> They can optionally be presented in world space by using the world_vertex_coords render mode.
>
> Users can disable the built-in modelview transform (projection will still happen later) and do it manually with the following code:

**Comment by mieldepoche** [comment]
Ah, I see.
Well I think there should be a nuance then, considering the variety of scenarios.
The fragment NORMAL has a hint to that:
![image](https://github.com/godotengine/godot-docs/assets/71937306/311aa0ea-abcf-4f22-a25b-01cbe7e76491)
but it's not enough I think.
Ideally, I'd say it should describe all of the scenarios:
- model space by default
- world space when using the `world_vertex_coords` render mode
- ??? (idk) when using the `skip_vertex_transform` render mode

The table is the first thing you look at when looking for that information, so I think it deserves to be there.

**Comment by AThousandShips** [comment]
The table would be very busy if we were to add information that's right there, repeating things over and over isn't a good idea IMO

**Comment by mieldepoche** [comment]
maybe saying it can be in various spaces and adding a link that scrolls up to the explanation is a better solution then
