### ISSUE TITLE
[Tutorial] Warning creating player scene

### ISSUE THREAD

**Issue by ArifZx** [godotengine/godot-docs#7929]
**Your Godot version:**
4.1

**Issue description:**
Warning add CollisionShaped2D

**URL to the documentation page:**
https://docs.godotengine.org/en/stable/getting_started/first_2d_game/02.player_scene.html

If you know how to fix the issue you are reporting please
consider opening a pull request. We provide a tutorial on
using git here: https://docs.godotengine.org/en/stable/community/contributing/pr_workflow.html,
writing documentation at https://docs.godotengine.org/en/stable/community/contributing/docs_writing_guidelines.html
and contributing to the class reference here: https://docs.godotengine.org/en/stable/community/contributing/updating_the_class_reference.html

![image](https://github.com/godotengine/godot-docs/assets/13897350/f87d7872-ae3e-48a8-8097-5f8708767460)

**Comment by AThousandShips** [comment]
> Finally, add a CollisionShape2D as a child of Player. This will determine the player's "hitbox", or the bounds of its collision area. For this character, a CapsuleShape2D node gives the best fit, so next to "Shape" in the Inspector, click "[empty]" -> "New CapsuleShape2D". Using the two size handles, resize the shape to cover the sprite:

**Comment by AThousandShips** [comment]
You haven't made `Player` an `Area2D` as the tutorial instructs
