### ISSUE TITLE
Add specification for `.gdextension` files

### ISSUE THREAD

**Issue by JustAnotherCodemonkey** [godotengine/godot-docs#7938]
**Issue description:**

The Godot docs as they stand include a section in [Scripting > Programming Languages > GDExtension > GDExtension C++ Example](https://docs.godotengine.org/en/stable/tutorials/scripting/gdextension/gdextension_cpp_example.html) where it is mentioned that there needs to be a "gdexample.gdextension" file to tell Godot about the extension. It also gives an example file for the example with a format resembling TOML. It briefly explains the "sections" in the example file but nothing more.

Nowhere in the docs (or anywhere else I can find) is there anything else about this mysterious file type nonetheless what is really needed, a specification of the `.gdextension` format as well as what configuration options are available to developers.

That last bit is especially important when it comes to the targets section. What is the convention behind the naming of the targets? What all targets are available? Why is the x86_64 specified in windows.debug.x86_64 but not for macos (macos.debug)?

**Comment by tetrapod00** [comment]
As far as I can tell, this was resolved by https://github.com/godotengine/godot-docs/pull/9383. The page is available at https://docs.godotengine.org/en/stable/tutorials/scripting/gdextension/gdextension_file.html

If you think anything is lacking from the new page, please open a new issue to track it!
