### ISSUE TITLE
Misleading documentation: Custom signals

### ISSUE THREAD

**Issue by MapManagement** [godotengine/godot-docs#7941]
**Your Godot version:**
4.1.1

**Issue description:** 
The documentation about signals is a bit misleading when it comes to custom signals. The description and code snippets implement the ``health_depleted`` signal within the script of the parent node. However, the embedded picture shows the signal on the sprite. Either the picture needs to be updated as shown below or the code snippets need to be replaced.
If my assumption is correct, I will open a pull request to fix the issue.

![image](https://github.com/godotengine/godot-docs/assets/49588429/19fa51e7-a366-4d05-8559-e579625c5653)

**URL to the documentation page:**
https://docs.godotengine.org/en/stable/getting_started/step_by_step/signals.html#custom-signals

**Comment by AThousandShips** [comment]
It is on `Sprite2d.gd` which isn't matching the code which is `sprite_2d.gd`, so it should be that, not `node_2d.gd`

**Comment by MapManagement** [comment]
So the code should be adjusted from this
```gd
extends Node2D

signal health_depleted

var health = 10
```
to this
```gd
extends Sprite2D

signal health_depleted

var health = 10
```
Since the signal is implemented on the sprite and not on the node, right?
