### ISSUE TITLE
Signal connection creates private method outside of class [4.x]

### ISSUE THREAD

**Issue by TypeKazt** [godotengine/godot-docs#7942]
**Your Godot version:**
4.1

**Issue description:**
When connecting a signal to a Aread2D class, the private method generated `_on_body_entered` is placed outside of the context of the class resulting in a build failure.

**URL to the documentation page:**
https://docs.godotengine.org/en/stable/getting_started/first_2d_game/03.coding_the_player.html

**Comment by AThousandShips** [comment]
Out of the context of the class how? Are you talking about C#? Then this is an error here:
* https://github.com/godotengine/godot/issues/18721

This is for errors in the documentation, not for general bugs, they belong over in that repository

**Comment by TypeKazt** [comment]
Understood, duplicate so closing
