### ISSUE TITLE
[VSCode] Unclear instructions on what folder to open

### ISSUE THREAD

**Issue by rstecca** [godotengine/godot-docs#7952]
Minor issue here but it can be unclear whether `Godot root folder` means the _project_'s root folder or the _engine_'s root folder.

https://github.com/godotengine/godot-docs/blob/950c8b9a4d625f2852729bc8d3eb0cf1c20f3ebf/contributing/development/configuring_an_ide/visual_studio_code.rst?plain=1#L17C1-L18C29

**Comment by YuriSizov** [comment]
Hey there! This is an article about engine development, there is no project in this context.

**Comment by YuriSizov** [comment]
@rstecca Well, how should this be phrased in your opinion?

**Comment by rstecca** [comment]
I suggest `Godot project's root folder`

**Comment by YuriSizov** [comment]
Sure, that sounds fine.

**Comment by skyace65** [comment]
Closing this issue. Per Yuri's comment this section is within the contributing/development section of the docs. There's no reason to assume it's talking about using VSCode with a game project. Additionally the wording you suggested, "Godot project's root folder" seems even more confusing to anyone not paying attention to what section this is in. To me, If I'm not aware of what section this is in, and I see that wording, then I'm going to assume it's talking about a game project.
