### ISSUE TITLE
Invalid velocity value in "Instancing with signals" docs.

### ISSUE THREAD

**Issue by brempusz** [godotengine/godot-docs#7963]
**Your Godot version:**
4.1

**Issue description:**
Initial value is Vector2.ZERO and it stays like that so the bullet will never move.

**URL to the documentation page:**
https://docs.godotengine.org/en/stable/tutorials/scripting/instancing_with_signals.html#shooting-example

**Comment by hdubbs** [comment]
Yeah, the bullet script has to be changed to: 

`var velocity = Vector2(1.0, 0)`, since it is being rotated in the main script.

If needed, I can fix this.

**Comment by AThousandShips** [comment]
Completed in:
* #8203
