### ISSUE TITLE
A sudden crush happens when launching Godot. 

### ISSUE THREAD

**Issue by hawahz** [godotengine/godot-docs#7966]
**Godot version:**

4.1.1 stable official

**Issue description:**

I downloaded the Godot engine at the beginning of August . It ran well that time . However, after a period of not using it, the crush happens. I tried to open with CMD, and nothing but the starting logs were displayed .
here is a video about how this happens:

https://github.com/godotengine/godot-builds/assets/145553087/f08c09f3-beb1-4958-a551-72070ae08210

I was using Godot 4.1.1 when the crush happens. Then i turned to dev5 at my group friends' suggestion, and still no work. 
It specifically happens when i click any of the buttons ,except 'New Project'. I can create a new folder in the 'New Project' screen and enter the file explorer to select a folder, but otherwise (including click the SELECT button in the file explorer) everything i did causes the crush. But at the time i turn back to use Godot 3 , it runs normally. The video shows the condition after i delete all the data files of Godot.

Additionally, between the two runs in August and September, i have once updated the NVIDIA drivers .The system is Windows 11 all the time.

**Steps to reproduce:**

With Data
- Delete, rename and create a project

Without Data
- Click any button at the begging screen.

**Comment by AThousandShips** [comment]
Thank you for reporting, issues like this should be reported [here](https://github.com/godotengine/godot), this is for issues with the documentation

**Comment by AThousandShips** [comment]
Superseded by:
* https://github.com/godotengine/godot/issues/81984
