### ISSUE TITLE
Configuring an IDE / Visual Studio -> Docs are outdated

### ISSUE THREAD

**Issue by qsrenniks** [godotengine/godot-docs#7981]
**Your Godot version:**
4.1

**Issue description:**
Reading through [these docs](https://docs.godotengine.org/en/stable/contributing/development/configuring_an_ide/visual_studio.html) and found that the documentation was outdated. 

Specifically the command line arg "vsproj=yes" will not generate visual studio project files for the godot-cpp branch.

**URL to the documentation page (if already existing):**
https://docs.godotengine.org/en/stable/contributing/development/configuring_an_ide/visual_studio.html

**Comment by Minoxs** [comment]
I followed those steps recently and they worked fine, for building the godot engine/editor (https://github.com/godotengine/godot).

If you're referring to the godot-cpp repo (https://github.com/godotengine/godot-cpp), I think the only part of the docs that refer to it is https://docs.godotengine.org/en/latest/tutorials/scripting/gdextension/gdextension_cpp_example.html.

**Comment by qsrenniks** [comment]
@Minoxs So you were able to create a VS solution file? My issues refers to not being able to create that file specifically and the fact that the command arg doesn't exist anymore.

**Comment by Minoxs** [comment]
@qsrenniks yes, `godot.sln` was created after executing `scons platform=windows vsproj=yes` in the root folder of the project.

**Comment by Minoxs** [comment]
Note that you do need an updated version of the MSVC compiler installed for this command to work, thought I'm not sure which.

**Comment by Minoxs** [comment]
You are building the godot-cpp repo, which is for GDExtension, so you should be looking under "Scripting > Programming Languages > GDExtension". See this https://docs.godotengine.org/en/latest/tutorials/scripting/gdextension/gdextension_cpp_example.html. I don't see any mention of vsproj for this kind of build. 

The docs you mentioned in the OP is for engine development, so imo it wouldn't make sense to be about the C++ bindings. In other words, the docs aren't really outdated.

If you're making your own GDExtension, you can check the [engine SConstruct file](https://github.com/godotengine/godot/blob/master/SConstruct) to see if you can find useful stuff. If you're looking to contribute for the bindings themselves, you might reach someone more useful in the godot gdextension dev chat :)

**Comment by qsrenniks** [comment]
Okay I see where my confusion was. Yes the documentation is not outdated, I was just trying to create a visual studio project for the GDExtension tutorial which is not possible to my understanding.

**Comment by Dimon4eg** [comment]
@qsrenniks @whiletrue111 here is working solution https://godotforums.org/d/32073-debug-c-gdextension/16
