### ISSUE TITLE
3D in 2D and 3D gui demos in the tutorial section are outdated

### ISSUE THREAD

**Issue by jordlord** [godotengine/godot-docs#7982]
**Your Godot version:**
Godot 4.1.1

**Issue description:**
Outdated demos. The demos in the subviewport page are currently still in version 3.5, not 4.0

**URL to the documentation page:**
https://docs.godotengine.org/en/stable/classes/class_subviewport.html

**Comment by AThousandShips** [comment]
Duplicate of https://github.com/godotengine/godot-docs/issues/7782
