### ISSUE TITLE
update documentation with new gdshader changes versus old shader 

### ISSUE THREAD

**Issue by catafest** [godotengine/godot-docs#7988]
**Your Godot version:**
4.1.x
**Issue description:**
Update the shader documentation about changes from .shader to .gdshader 
**URL to the documentation page (if already existing):**
you can find some changes in the Godot source code, but this research takes time, see [this source code](https://github.com/Chaosus/godot/blob/a8bbe570caadd0161a8db9c980296b111042a6b8/servers/rendering/shader_language.cpp#L8235-L8262).

**Comment by AThousandShips** [comment]
There is [this](https://docs.godotengine.org/en/stable/tutorials/migrating/upgrading_to_godot_4.html#updating-shaders) what is still missing?

**Comment by jynus** [comment]
I am not sure, but I wonder if this is related to #7458 and #7497 ?

**Comment by skyace65** [comment]
Closing due to a lack of information, and because we have other issues open for the shader section of the docs.
