### ISSUE TITLE
CS code missing for adding music

### ISSUE THREAD

**Issue by cj-maclean** [godotengine/godot-docs#8003]
**Your Godot version:**
4.1.1
**Issue description:**
The tutorial is overall very beginner friendly, but on the last bit it uses $Music.play() and while I've been trying to compare the GDScript to C# to try to understand how to translate it into C# I'm not quite proficient enough in both to do that yet. (My goal with this was to get practice using C#). 
**URL to the documentation page:**
https://docs.godotengine.org/en/stable/getting_started/first_2d_game/07.finishing-up.html
If you know how to fix the issue you are reporting please
consider opening a pull request. We provide a tutorial on
using git here: https://docs.godotengine.org/en/stable/community/contributing/pr_workflow.html,
writing documentation at https://docs.godotengine.org/en/stable/community/contributing/docs_writing_guidelines.html
and contributing to the class reference here: https://docs.godotengine.org/en/stable/community/contributing/updating_the_class_reference.html

**Comment by jynus** [comment]
You are completely right, that last part is very rough. I suggested the following addition - let me know if that works for you:
![Screenshot_20230923_133419](https://github.com/godotengine/godot-docs/assets/8576860/8eecd3d0-41eb-4369-9d08-e4bedf163cb8)

```csharp
public void GameOver()
{
    ...
    GetNode<AudioStreamPlayer>("Music").Stop();
    GetNode<AudioStreamPlayer>("DeathSound").Play();
}

public void NewGame()
{
    ...
    GetNode<AudioStreamPlayer>("Music").Play();
}
```
