### ISSUE TITLE
ColorRect Anchors Preset isn't applied unless under a Canvas Layer

### ISSUE THREAD

**Issue by AstrooLabe** [godotengine/godot-docs#8004]
**Your Godot version:**
4.1.1

**Issue description:**
In the documentation for the 2D game project, it says to put the ColorRect node for the background under the main node and set the Anchor to Full Rect but it doesn't strech to match Viewport unless I put it under a CanvasLayer

**URL to the documentation page (if already existing):**
https://docs.godotengine.org/en/stable/getting_started/first_2d_game/07.finishing-up.html

**Comment by skyace65** [comment]
I would advise you to double check your project and maybe reach out for help in one of the community groups ([found here](https://godotengine.org/community/)). I just tested the finished project from the demo repository in 4.2.1 and the ColorRect is behaving as it should, additionally making it the child of a CanvasLayer isn't changing behavior at all for me. I've even deleted and re-added it and set the anchors preset to make sure there isn't a missing step.
