### ISSUE TITLE
Texts documentation are up to date but not the screenshots

### ISSUE THREAD

**Issue by AstrooLabe** [godotengine/godot-docs#8005]
**Your Godot version:**
4.1.1

**Issue description:**
The text explanations on how to set a keyboard shortcut to start the game are up to date for Godot 4.1 but the screenshots aren't and don't show the plurality of options

**URL to the documentation page (if already existing):**
https://docs.godotengine.org/en/stable/getting_started/first_2d_game/07.finishing-up.html

**Comment by jynus** [comment]
I can see the manual showing an up-to-date interface since February this year, still applying to 4.1 and 4.2 (except for some minor icon change). What do you miss from here? 
![start_button_shortcut2](https://github.com/godotengine/godot-docs/assets/8576860/0f756109-dc17-4aa4-b5d5-7c8f27ba4742)
