### ISSUE TITLE
Polish possibilities suggestions for 2D game project tutorial

### ISSUE THREAD

**Issue by AstrooLabe** [godotengine/godot-docs#8006]
**Your Godot version:**
4.1.1

**Issue description:**
While the game resulting from the tutorial is fine and playable, two polishing suggestions could be added:

- Unless I skipped the step by accident, the tutorial let the player character spawn in the upper left corner on the starting screen before clicking the Start button. Telling to set the Player node at the screen center in the Main scene would be a nice addition to the polish suggestions

- We're able to move the Player character before hitting "Start". A little explanation on how to lock controls 
on such occasions would also be nice.

**URL to the documentation page (if already existing):**
https://docs.godotengine.org/en/stable/getting_started/first_2d_game/07.finishing-up.html

**Comment by Piralein** [comment]
The position of the player is set to the position of the `StartPosition (Marker2D)`, which should be in the middle of the screen according to the tutorial.

```
func new_game():
	$Player.start($StartPosition.position)
```

Furthermore, the player is hidden until the start button was pressed and then its position is reset. While such an explanation could hold value, it is out of scope for a introduction tutorial like this.

Thank you for your suggestion nonetheless!
