### ISSUE TITLE
Custom drawing in 2D code update

### ISSUE THREAD

**Issue by yanourt** [godotengine/godot-docs#8026]
**Your Godot version:**
Godot 4.1

**Issue description:**
The second code snippet does not work (export and setget):

```
extends Node2D

export (Texture) var texture setget _set_texture

func _set_texture(value):
    # If the texture variable is modified externally,
    # this callback is called.
    texture = value  # Texture was changed.
    queue_redraw()  # Trigger a redraw of the node.

func _draw():
    draw_texture(texture, Vector2())
```

instead this works fine for me:
```
extends Node2D

@export var texture : Texture :
	set(value):
		texture = value
		queue_redraw()
	get:
		return texture

func _draw():
	draw_texture(texture,Vector2())
```

**URL to the documentation page:**
[https://docs.godotengine.org/en/latest/tutorials/2d/custom_drawing_in_2d.html](https://docs.godotengine.org/en/latest/tutorials/2d/custom_drawing_in_2d.html)

**Comment by jynus** [comment]
Thank you for the report- the custom drawing section has been rewritten in #7532, including fixing the getters and setters you mention (among many other things). Could I ask you to have a look at how it looks there and if the new version is clear enough/works for you? This is the new version I wrote: https://github.com/godotengine/godot-docs/blob/888104341355db19a4ec830c51011fbee17e91c1/tutorials/2d/custom_drawing_in_2d.rst

Thank you!

**Comment by yanourt** [comment]
Oops sorry for the useless report, I didn't find the new version which I find much more developed.

The only thing is I still can't find a "clean and easy" way to refresh the preview in editor when any property is changed (except writing a setter per property, or forcing refresh in _process), but maybe there isn't.

On the same subject, toggling visibility off and on also seems to work as an option to refresh the preview :)
[https://github.com/godotengine/godot-docs/blob/888104341355db19a4ec830c51011fbee17e91c1/tutorials/2d/custom_drawing_in_2d.rst#show-the-drawing-while-editing](https://github.com/godotengine/godot-docs/blob/888104341355db19a4ec830c51011fbee17e91c1/tutorials/2d/custom_drawing_in_2d.rst#show-the-drawing-while-editing
)
