### ISSUE TITLE
Missing download link for the sound files for the "Your first 2D game" tutorial.

### ISSUE THREAD

**Issue by PhaZ90771** [godotengine/godot-docs#8040]
**Your Godot version:**
Version 4.1

**Issue description:**
Missing download link for the sound files mentioned in: "Your first 2D game" -> "Finishing up" -> "Sound effects". The zip file with the art assets at the beginning of the tutorial does not include sound files.

**URL to the documentation page:**
https://docs.godotengine.org/en/stable/getting_started/first_2d_game/07.finishing-up.html

**Comment by Piralein** [comment]
The files should be located in the **art** directory.

**Comment by skyace65** [comment]
Piralein is correct, however I think the wording on the page could be clearer
