### ISSUE TITLE
Display "uppercase" and "lowercase" in a consistent manner 

### ISSUE THREAD

**Issue by mieldepoche** [godotengine/godot-docs#8044]
**Your Godot version:**
4.1.1

**Issue description:**

Take a look at the descriptions:

![image](https://github.com/godotengine/godot-docs/assets/71937306/662d385f-908d-4457-8734-b5985f60e47c)

while it is probably clear to everyone what uppercase and lowercase mean (and it might even not be the case, for example if someone is a begginer and not a native english speaker), I think it would be nice to display them explicitely, just like how `PascalCase` and `snake_case` are shown, in this particular context.
That is, change:
   - lowercase → `lowercase`
   - uppercase → `UPPERCASE`

in the method description of `to_lower` and `to_upper`.

**URL to the documentation page (if already existing):**
https://docs.godotengine.org/en/stable/classes/class_string.html#class-string-method-to-lower

**Comment by Mickeon** [comment]
📋✏️
