### ISSUE TITLE
Setter example code is not up to date for Godot 4.1

### ISSUE THREAD

**Issue by badunius** [godotengine/godot-docs#8045]
**Your Godot version:** 4.1.1

**Issue description:**
There's green "up-to-date" banner on Godot notifications docs page, however example code in "_init vs. initialization vs. export" section uses `setget` instruction, and in the comments it is said that setting variable via `self.` calls a setter unlike setting it directly 

**URL to the documentation page:**
https://docs.godotengine.org/en/stable/tutorials/best_practices/godot_notifications.html#process-vs-physics-process-vs-input

**Comment by jynus** [comment]
This was fixed on #8114 and #8293 for 4.2, it just requires backporting.

**Comment by skyace65** [comment]
The changes from both PRs jynus referenced are part of the stable docs now.
