### ISSUE TITLE
class_characterbody3d.html#tutorials

### ISSUE THREAD

**Issue by jeremytrigano** [godotengine/godot-docs#8052]
**Your Godot version:**
v4.1.1.stable.official [bd6af8e0e]
**Issue description:**
Importing https://godotengine.org/asset-library/asset/126 
Parser Error: Member "velocity" redefined (original in native class 'CharacterBody3D')
**URL to the documentation page:**
https://docs.godotengine.org/en/4.1/classes/class_characterbody3d.html#tutorials

**Comment by tetrapod00** [comment]
Not really a docs issue. That's a 3.5 demo that you are loading in 4.x. In 4.x, CharacterBody3D has a [velocity property](https://docs.godotengine.org/en/4.3/classes/class_characterbody3d.html#class-characterbody3d-property-velocity) that the corresponding class KinematicBody didn't have in 3.x. So you get the error that it was redefined.

You can fix it by renaming the `velocity` property in the demo.
