### ISSUE TITLE
Out of date: Mouse and input coordinates page

### ISSUE THREAD

**Issue by PickleJesus123** [godotengine/godot-docs#8074]
**Your Godot version:**
4.1.1

**Issue description:**
The GDScript code snippet is not functional in 4.1.1, since get_viewport_rect() no longer exists.

Please update
`print("Viewport Resolution is: ", get_viewport_rect().size)`
to
`print("Viewport Resolution is: ", get_viewport().size)`

**URL to the documentation page:**
https://docs.godotengine.org/en/stable/tutorials/inputs/mouse_and_input_coordinates.html

If you know how to fix the issue you are reporting please
consider opening a pull request. We provide a tutorial on
using git here: https://docs.godotengine.org/en/stable/community/contributing/pr_workflow.html,
writing documentation at https://docs.godotengine.org/en/stable/community/contributing/docs_writing_guidelines.html
and contributing to the class reference here: https://docs.godotengine.org/en/stable/community/contributing/updating_the_class_reference.html

**Comment by Hex-4** [comment]
Working on this...
