### ISSUE TITLE
GDScript warning system

### ISSUE THREAD

**Issue by Alex2782** [godotengine/godot-docs#8076]
**Your Godot version:**
v4.1.1.stable.official [bd6af8e0e]

**Issue description:**
Search for `GDScript` is also possible without `Advanced Settings`

> As shown in the image above, you **must** enable `Advanced Settings` in order to see the GDScript section.

![Bildschirmfoto 2023-09-28 um 00 19 32](https://github.com/godotengine/godot-docs/assets/41921395/85bc7507-0665-4718-8603-8a0a2e64fd8f)

**URL to the documentation page:**
https://docs.godotengine.org/en/4.1/tutorials/scripting/gdscript/warning_system.html

**Comment by Hex-4** [comment]
Hi! I'm working on this issue.
