### ISSUE TITLE
Missing information in 2D tutorial for _ready

### ISSUE THREAD

**Issue by joelressell** [godotengine/godot-docs#8078]
**Your Godot version:**
4.1.1

**Issue description:**
You tell the user:
_"The _ready() function is called when a node enters the scene tree, which is a good time to find the size of the game window:"_

Is this a new script?  Is _ready() called by something else?  Where does this code go?  Do I make it?  Extremely confusing.  Whenever you call a process of show code, please show a screenshot of the file/location and exactly what the name of the file is.  This documentation is difficult to follow.

**URL to the documentation page (if already existing):**
https://docs.godotengine.org/en/stable/getting_started/first_2d_game/03.coding_the_player.html

**Comment by Piralein** [comment]
The `_ready()` function should be part of the created script for the `Player` node.
Did you deselect the `Template` checkbox, like in the picture?

I would say this is a problem with the image, by default the `Template` checkbox should be checked and the `Node: Default` template should be selected.

**Comment by joelressell** [comment]
Yes, I did deselect that to match the picture.  I figured out it was in the
Player script.  I would suggest updating the image and adding text to the
effect of:

The _ready() function, in Player script, is called when a node enters the
scene tree, which is a good time to find the size of the game window:
