### ISSUE TITLE
Document that `SeparationRayShape2D` and `SeparationRayShape3D` can be used for stairs.

### ISSUE THREAD

**Issue by theraot** [godotengine/godot-docs#8087]
**Your Godot version:**

4.2.dev5

**Issue description:**

Apparently `SeparationRayShape2D` and `SeparationRayShape3D` can be used for stairs, which means these classes more useful than the proposed use case of "spears falling from the sky" suggests.

*Personally the mention of "stairs" would have gotten me to try. As I'll proceed to do after posting this.*

With that said, I believe the documentation could expand on this shapes work or are intended to work beyond mentioning another use case.

These links support the idea that this is an use case of these shapes:

- third party: https://twitter.com/passivestar_/status/1707381014509519094
- first party: https://github.com/godotengine/godot-proposals/issues/2751#issuecomment-1647560689

Apparently "It was designed for this very use case" ([source](https://github.com/godotengine/godot-proposals/issues/2751#issuecomment-1647565676)), but that didn't make it to the documentation.

**URL to the documentation page:**

- https://docs.godotengine.org/en/stable/classes/class_separationrayshape2d.html
- https://docs.godotengine.org/en/stable/classes/class_separationrayshape3d.html

**Comment by ahintoflime** [comment]
I'd like to add that the documentation for the 3D separation ray page says this:

"A 3D ray shape, intended for use in physics. Usually used to provide a shape for a [CollisionShape2D](https://docs.godotengine.org/en/stable/classes/class_collisionshape2d.html#class-collisionshape2d)." which just doesn't make any sense at all

**Comment by MewPurPur** [comment]
I made the goof-up here, I'll edit it tonight.

**Comment by akien-mga** [comment]
Fixed by https://github.com/godotengine/godot/pull/82544.
