### ISSUE TITLE
Outdated C# example in AStarGrid2D documentation

### ISSUE THREAD

**Issue by arzi42** [godotengine/godot-docs#8090]
**Your Godot version: 4.1.1**

**Issue description: Outdated C# example in AStarGrid2D documentation**

**URL to the documentation page: https://docs.godotengine.org/en/stable/classes/class_astargrid2d.html**

The C# example uses .Size which is now deprecated and .Region should be used instead. The GDScript example seem to be up to date.

**Comment by skyace65** [comment]
This was fixed in https://github.com/godotengine/godot/pull/79794.
