### ISSUE TITLE
`RefCounted.unreference()` returns true only if the object has died, not if it succeeded decrementing.

### ISSUE THREAD

**Issue by RadiantUwU** [godotengine/godot-docs#8103]
**Your Godot version:** 4.1.1-stable

**Issue description:** `RefCounted.unreference()` returns true only if the object has died, not if it succeeded decrementing.

**URL to the documentation page:** https://docs.godotengine.org/en/stable/classes/class_refcounted.html#class-refcounted-method-unreference

[Source code](https://github.com/godotengine/godot/blob/4.1/core/object/ref_counted.cpp#L78)

**Comment by RadiantUwU** [comment]
https://github.com/godotengine/godot/pull/82557

**Comment by Piralein** [comment]
Closing per above comment.
Thank you for the report!
