### ISSUE TITLE
Godot.GlobalClassAttribute what is it?

### ISSUE THREAD

**Issue by iRumba** [godotengine/godot-docs#8106]
Godot 4.1.1 mono

Explain please what appointment of Godot.GlobalClassAttribute attribute in godot cs script?

**Comment by AThousandShips** [comment]
[this](https://docs.godotengine.org/en/stable/tutorials/scripting/c_sharp/c_sharp_global_classes.html)

For support questions and help please first turn to the other [community channels](https://godotengine.org/community), this is for bug reporting, not a help desk.

**Comment by iRumba** [comment]
> [this](https://docs.godotengine.org/en/stable/tutorials/scripting/c_sharp/c_sharp_global_classes.html)
> 
> For support questions and help please first turn to the other [community channels](https://godotengine.org/community), this is for bug reporting, not a help desk.

I'm sorry, but...
![image](https://github.com/godotengine/godot-docs/assets/12796309/30b7f2f2-eef8-4fd7-9354-c4fa8d9cf7ae)

**Comment by AThousandShips** [comment]
Well there's many other channels than the Q&A, please go to them, just because *one* other channel isn't available right now doesn't mean this is the place to go

**Comment by AThousandShips** [comment]
Closing as you are now very able to ask this in the appropriate channels
