### ISSUE TITLE
Grammar error in Input.get_action_strength()

### ISSUE THREAD

**Issue by timcode77** [godotengine/godot-docs#8110]
**Your Godot version:**
4.1

**Issue description:**
This sentence does not make grammatical sense and is therefore confusing:

> If the action is mapped to a control that has no axis as the keyboard, the value returned will be 0 or 1.

I do not know the intended behaviour of the function described so I cannot confidently suggest a fix. Could it be:

If the action is mapped to a control that has no axis _**such**_ as the keyboard, the value returned will be 0 or 1.

**URL to the documentation page:**
https://docs.godotengine.org/en/stable/classes/class_input.html

**Comment by ShatReal** [comment]
You're right, it should be "such". I will fix it.
