### ISSUE TITLE
Encourage users to use @export, not get_node()

### ISSUE THREAD

**Issue by PickleJesus123** [godotengine/godot-docs#8116]
**Your Godot version:**
4.1.1

**Issue description:**
The Godot tutorials should encourage developers to use `@export` to reference nodes, instead of get_node(). `@export` is good practice, since using get_node(str) creates "brittle code". If a developer wants to refactor their nodes/scripts (studios do this quite often in the industry, especially as projects get larger), it becomes a long, tedious, and error-prone task with get_node(). However, if they use `@export`, nodes can be renamed/moved freely without worry. The Unity equivalent to get_node(str) is transform.Find(str), and it is _highly discouraged_.

**URL to the documentation page (if already existing):**
https://docs.godotengine.org/en/stable/tutorials/scripting/nodes_and_scene_instances.html

**Comment by PickleJesus123** [comment]
Corresponding pull-request: #8122

**Comment by Mickeon** [comment]
It's worth keeping in mind `@export` nodes have a noticeable flaw, currently. That is, references to the Nodes are not transferred to new Nodes when duplicated. See https://github.com/godotengine/godot/issues/78060

**Comment by AThousandShips** [comment]
Please put \` around your mentions of `@export` or you will keep tagging a GitHub user
