### ISSUE TITLE
Add warning in editor when visibility screen notifier's is disabled

### ISSUE THREAD

**Issue by EFrion** [godotengine/godot-docs#8123]
**Your Godot version:**

4.1.2

**Issue description:**

When the VisibleOnScreenEnabler3D is invisible, RigidBody3D and AnimationPlayer3D attached to the nodes are disabled. This can be confusing for new devs. Adding a warning in the editor would avoid confusion.

**URL to the documentation page (if already existing):**

https://docs.godotengine.org/en/stable/classes/class_visibleonscreenenabler3d.html

**Comment by skyace65** [comment]
Hi, if there's anything you'd like to see as a feature in Godot you should open an issue in the Godot-docs repository [here](https://github.com/godotengine/godot-proposals). This repository is exclusively for the documentation. And if you find any bugs in Godot you want to report you can open an issue in the engine repository [here](https://github.com/godotengine/godot).
