### ISSUE TITLE
Incorrect key descriptions for KEY_PLUS and KEY_MINUS in the Key Enumerator description

### ISSUE THREAD

**Issue by AsperTheDog** [godotengine/godot-docs#8127]
**Your Godot version:**

v4.1.1.stable.official [bd6af8e0e]

**Issue description:**

The description for the Key enumerator has incorrect descriptions for the enumerators KEY_PLUS and KEY_MINUS because markdown automatically converts symbols - and + into lists

**URL to the documentation page:**

https://docs.godotengine.org/en/4.1/classes/class_%40globalscope.html#enum-globalscope-key

**Comment by transistasis** [comment]
I've confirmed this issue, which can be seen in the link that @AsperTheDog provided.

The problem stems from the _+_ and _-_ keys not being escaped in the `escape_rst` method in _make_rst.py_. It's important to address this issue transparently, as handling these characters the same way as the _*_ can result in bullet lists being broken in other _.rst_ files, such as the one generated from _EditorCommandPalette.xml_.

I went ahead and proposed a fix in this [pull request](https://github.com/godotengine/godot/pull/82697).
