### ISSUE TITLE
Addon recomendated is outdated in "multiple resolutions" tutorial

### ISSUE THREAD

**Issue by Lucasdelpiero** [godotengine/godot-docs#8131]
**4.1.1**

**In the common use case scenerio section in the pixel art suggestions there is an addon recommended that is not supported for the Godot version 4.x**

**[Multiple resolutions](https://docs.godotengine.org/en/stable/tutorials/rendering/multiple_resolutions.html)**

**Comment by skyace65** [comment]
This was fixed by #8298 which documented the new integer scaling support in 4.2.
