### ISSUE TITLE
Animation tracks missing Track Settings panel (4.1)

### ISSUE THREAD

**Issue by djmcgaughran** [godotengine/godot-docs#8141]
4.1.stable.mono

The documentation on the tutorial [Introduction to the animation features](https://docs.godotengine.org/en/stable/tutorials/animation/introduction.html) mentions a track Settings panel, which does not exist in the Animation tab of the Godot 4.1 editor.

As an example, I have a basic Elevator scene containing a `CollisionShape3D` and two meshes (`Platform` and `Shroud`), each of which has properties animated in the `Ascend` and `Descend` animations (which are separate to allow configurable delays with corresponding looping animations to play in between). There are no children of the `AnimationPlayer` node in the Scene Tree; the meshes and collision shape are sibling nodes. The `Ascend` animation is shown here, with the tracks occupying the full width of the panel:

![image](https://github.com/godotengine/godot-docs/assets/964250/36245cf5-fef5-4143-8117-8ae649ad4b44)

I cannot find where such settings have been moved to, even when toggling into the bezier curve editor. No such settings are visible in the Inspector panel, even when selecting Animation -> Open in Inspector.

**Comment by AThousandShips** [comment]
I don't think it's needed to clarify that a setting mentioned in one specific area isn't relevant to other areas, further the documentation for the Bezier track shows that the menu isn't present, so the documentation clarifies that as well, as you can see [here](https://docs.godotengine.org/en/stable/tutorials/animation/animation_track_types.html#bezier-curve-track).

So I'd say the documentation shows in screenshots that this menu isn't available for Bezier tracks, and doesn't present them as if they were global
