### ISSUE TITLE
The default script template does not match Godot editor

### ISSUE THREAD

**Issue by allenwp** [godotengine/godot-docs#8151]
**Your Godot version:**
v4.1.2.stable.official [399c9dc39]

**Issue description:**

The [default script template](https://docs.godotengine.org/en/latest/tutorials/scripting/creating_script_templates.html#default-template) does not match what the Godot editor produces with default settings. Instead, it matches what the editor will produce when "Add Type Hints" has been turned on in the Editor settings.

Default Godot editor:
```
extends Node


# Called when the node enters the scene tree for the first time.
func _ready():
	pass # Replace with function body.


# Called every frame. 'delta' is the elapsed time since the previous frame.
func _process(delta):
	pass
```

Godot editor with "Add Type Hints" turned on:
```
extends Node


# Called when the node enters the scene tree for the first time.
func _ready() -> void:
	pass # Replace with function body.


# Called every frame. 'delta' is the elapsed time since the previous frame.
func _process(delta: float) -> void:
	pass
```

It appears that the template used to use `func _ready()%VOID_RETURN%:` and `func _process(delta%FLOAT_TYPE%)%VOID_RETURN%:`, but when the template was [updated ](https://github.com/godotengine/godot-docs/issues/5887) to use the new `_XXX_` format, those were replaced with explicit type hints.

**URL to the documentation page:**
https://docs.godotengine.org/en/latest/tutorials/scripting/creating_script_templates.html#default-template

**Comment by AThousandShips** [comment]
That's what the template is, it doesn't say that it is the *output* of the default template, but that it *is* the template, so:
> so you can use these as the base for creating other templates

**Comment by allenwp** [comment]
> That's what the template is, it doesn't say that it is the _output_ of the default template, but that it _is_ the template, so:
> 
> > so you can use these as the base for creating other templates

Here are some more details on why this original wording was a usability issue for me:

- I read the previous section "Default behaviour and overriding it" and attempted to remove any overrides to ensure that I was getting the correct default behaviuor. I did not have Type Hints enabled.
- Then I read the "Default template" section that immediately follows, which says "**The `Default` templates for basic Nodes, for both GDScript and C#, are shown here** so you can use these as the base for creating other templates:"
- Since my Godot editor was not producing the default template that was described in this text, it suggested to me there was something wrong with my editor configuration.
- I spent some time double-checking to make sure nothing was overriden incorrectly in my editor configuration, only to eventually find out that what was shown in the documentation was not the default template for basic Nodes for GDScript.

**Comment by AThousandShips** [comment]
Got it, but the point remains that it *is* the actual template, and the documentation fix should instead clarify the use of the type hints, as changing that setting does not change the template, or use a different template

**Comment by allenwp** [comment]
Changing the "Add Type Hints" Editor Setting changes the default `Node` template that is used by the Godot Editor when creating new GDScripts.

**Comment by AThousandShips** [comment]
How? The file is embedded in the editor binary?

Again the *template* and the *output* of the template are different things

**Comment by allenwp** [comment]
I'm actually not sure why the output of the template when "Add Type Hints" is turned off is different than the template found [here](https://github.com/godotengine/godot/blob/master/modules/gdscript/editor/script_templates/EditorScript/basic_editor_script.gd).

Do you know why this is?

**Comment by AThousandShips** [comment]
Yes, linked the code in the PR, see [here](https://github.com/godotengine/godot/blob/bfd78bb917887cfc1fd842ba23570394cad8bedb/modules/gdscript/gdscript_editor.cpp#L77-L93)

**Comment by allenwp** [comment]
Ah, I see. I did not expect that the Godot Editor would remove type hints from script templates with its default configuration.

**Comment by allenwp** [comment]
It looks like the original issue was that I didn't read the [final section](https://docs.godotengine.org/en/latest/tutorials/scripting/creating_script_templates.html#type-placeholders) on the page that describes how type hints will be removed if the Add Type Hints editor settings is turned off.
