### ISSUE TITLE
Link to the official Questions & Answers site is outdated

### ISSUE THREAD

**Issue by GrassWarlock** [godotengine/godot-docs#8155]
Godot 4.1 Docs

Link to the official [Questions & Answers](https://godotengine.org/qa/) site is outdated. it displays a 404 error when entered.

[**URL to the documentation page:**](https://docs.godotengine.org/en/stable/getting_started/introduction/learning_new_features.html#learning-with-the-community)

**Comment by ShatReal** [comment]
The site was down, it's back up now

**Comment by YuriSizov** [comment]
That's true, but the link is indeed outdated. Worth updating the docs.
