### ISSUE TITLE
List Properties and Allow us to search for Code

### ISSUE THREAD

**Issue by 1NEGROUP** [godotengine/godot-docs#8158]
**Your Godot version:** 4.1

**Issue description:** Reading the Docs is a Bit Difficult, I know yall have the whole manual look going on but the Scripting documentation needs to be searchable like in unity. I have no idea what i am able to do with things like Transform or anything like that because i am not sure what properties i can use as they aren't listed.

**URL to the documentation page (if already existing):**

**Comment by AThousandShips** [comment]
What do you mean not listed? They are [clearly listed](https://docs.godotengine.org/en/stable/classes/class_transform3d.html#properties)?

**Comment by YuriSizov** [comment]
The same documentation is also available directly in the editor, by the way 🙂

**Comment by 1NEGROUP** [comment]
> The same documentation is also available directly in the editor, by the way 🙂

Does it us to search for code term and properties for those code terms? For example Transform.<property>
How and where?

**Comment by AThousandShips** [comment]
Search for what and where?

**Comment by YuriSizov** [comment]
Here's an introduction to the Godot editor that covers how to use the built-in class reference: https://docs.godotengine.org/en/stable/getting_started/introduction/first_look_at_the_editor.html#integrated-class-reference

**Comment by tetrapod00** [comment]
Closing, since properties and other class members *are* listed in the class reference, and the class reference *can* be searched.
