### ISSUE TITLE
Cannot select an AnimatedSprite3D node by clicking on it in the scene view

### ISSUE THREAD

**Issue by lorenzokerbrat** [godotengine/godot-docs#8161]
**Your Godot version:**

4.1.1.stable.mono.official

**Issue description:**

A node that only has an AnimatedSprite3D + SpriteFrames as its display cannot be selected by clicking on it in the scene view.

It can be selected by clicking on it in the node hierarchy. This issue is essentially about usability/QOL.
The use case would be, for example, making a 2.5D-style game where a lot of AnimatedSprite3Ds are its main actors and props.

It is still possible to select a Sprite3D node by clicking on it in the scene view though, which is why I'm reporting this as a bug.

**URL to the documentation page (if already existing):**

https://docs.godotengine.org/fr/4.x/classes/class_animatedsprite3d.html#class-animatedsprite3d
https://docs.godotengine.org/fr/4.x/classes/class_spriteframes.html#class-spriteframes
https://docs.godotengine.org/fr/4.x/classes/class_texture2d.html#class-texture2d

**Comment by lostminds** [comment]
This doesn't sound like a documentation issue, perhaps you meant to open a bug report in the regular bug issue tracker https://github.com/godotengine/godot/issues and not here for problems with documentation?

**Comment by lorenzokerbrat** [comment]
> This doesn't sound like a documentation issue, perhaps you meant to open a bug report in the regular bug issue tracker https://github.com/godotengine/godot/issues and not here for problems with documentation?

I just noticed that now, I'm sorry. I followed a link from Godot's documentation to here and didn't check the repo name. I'll close this one.
