### ISSUE TITLE
Guidelines for hiDPI support in Multiple Resolutions tutorial are outdated and incomplete

### ISSUE THREAD

**Issue by lostminds** [godotengine/godot-docs#8162]
**Your Godot version:**
Godot 4.2.dev6

**Issue description:**
The guidelines for hiDPI support in Multiple Resolutions tutorial are outdated and incomplete. They state that the setting is not enabled by default (which it is now), but indicate you can just turn it on to get hiDPI support. However, enabling the setting (now default) just makes everything smaller on hiDPI monitors, so perhaps it would be helpful to add that to actually get the higher resolution rendering you also need to increase the window content_scale_factor and size (as described in this related proposal https://github.com/godotengine/godot-proposals/issues/7968) 

**URL to the documentation page:**
https://docs.godotengine.org/en/stable/tutorials/rendering/multiple_resolutions.html#hidpi-support

**Comment by HoofedEar** [comment]
Adding to this, the article still makes reference to setting `min_window_size()` via OS when in Godot 4, these functions got moved to DisplayServer
![image](https://github.com/godotengine/godot-docs/assets/1261392/5bcb88ed-6833-4048-b369-771fbb099bda)

**Comment by skyace65** [comment]
Fixed by #9037. There's another PR already open for HoofedEar's issue. Also please do not report a different issue in the comments of an existing issue.
