### ISSUE TITLE
Unclear step in "Connecting a signal via code" guide

### ISSUE THREAD

**Issue by GrassWarlock** [godotengine/godot-docs#8169]
Godot 4.1.2
_Edit (2023/12/30):_
**It seems the issue wasn't with the screenshot but with a lack of clarity on an important step in the tutorial.
This issue should now be resolved by just making sure to remind the reader to set node2d as the main scene before running the game. This allows the timer in Node2d to work without any issues.**

=========
original name for this issue: Misleading screenshot in "Connecting a signal via code" guide

New to Godot but this might be a bug in the Godot engine itself: 
The guide tells you to add a Timer node as a child to a Sprite2D node.
If you do it the way the guide's screenshot shows (add from within the node_2d scene and not from the sprite_2d scene itself), you get an error telling you the timer node wasn't identified as a child to sprite_2d.
`E 0:00:00:0557   sprite_2d.gd:12 @ _ready(): Node not found: "Timer" (relative to "/root/Sprite2D").
  <C++ Error>    Method/function failed. Returning: nullptr
  <C++ Source>   scene/main/node.cpp:1626 @ get_node()
  <Stack Trace>  sprite_2d.gd:12 @ _ready()
`
If you do it inside the sprite_2d scene itself, it works.

[**URL to the documentation page:**](https://docs.godotengine.org/en/stable/getting_started/step_by_step/signals.html#connecting-a-signal-via-code)

Proposed Solution:
**This issue should now be resolved by just making sure to remind the reader to set node2d as the main scene.**
~if this is intended engine functionality, just change the screenshot to show you adding a child node from within the sprite_2d scene itself and not the general node_2d scene~

**Comment by martinsik** [comment]
Just stumbled upon the same thing and was thinking what am I doing wrong. Is it really a mistake in the tutorial?

**Comment by GrassWarlock** [comment]
> Just stumbled upon the same thing and was thinking what am I doing wrong. Is it really a mistake in the tutorial?
> 
> Same issue here: https://www.reddit.com/r/godot/comments/1721dyh/error_message_in_step_by_step_using_signals/
First of all, try the solution in the reddit post you linked (the one in the comments, which says to run the entire root scene and not just the sprite2d scene)

If it doesn't work, this was my solution at the time (if i remember correctly):
right click on Sprite2d and press "open in editor". a new window appears showing the Sprite2d scene. from there, right click Sprite2d again and press "add child node" and pick Timer.

still not sure if this is intended engine functionality or not. But i hope this helps.
if it still doesn't work let me know.

**Comment by Davids048** [comment]
I don't think this would be the intended functionality. Adding the timer in the sprite2D scene does solve the problem. But the timer is then included in the scene definition, which means all instantiated sprite2D would have a timer. Adding the timer under the Node2D scene means only that instance of sprite2D would have a timer.

**Comment by GrassWarlock** [comment]
> I don't think this would be the intended functionality. Adding the timer in the sprite2D scene does solve the problem. But the timer is then included in the scene definition, which means all instantiated sprite2D would have a timer. Adding the timer under the Node2D scene means only that instance of sprite2D would have a timer.

if you're following the tutorial can you please try adding the timer in Node2D, setting Node2D scene as the main scene, and then running the game from the main scene (F6)? just in case we all messed up by running only the Sprite2D scene.

**Comment by Davids048** [comment]
> if you're following the tutorial can you please try adding the timer in Node2D, setting Node2D scene as the main scene, and then running the game from the main scene (F6)? just in case we all messed up by running only the Sprite2D scene.

I think you might be right. Before, my main scene was set to be sprite2D. After I changed the main scene to Node2D, I was able to run the program with no error.

**Comment by GrassWarlock** [comment]
> > if you're following the tutorial can you please try adding the timer in Node2D, setting Node2D scene as the main scene, and then running the game from the main scene (F6)? just in case we all messed up by running only the Sprite2D scene.
> 
> I think you might be right. Before, my main scene was set to be sprite2D. After I changed the main scene to Node2D, I was able to run the program with no error.

I see. it seems the real problem was that the docs weren't clear enough about this step (seeing as at least 4 people were stalled by it).

thanks for reporting on it.

**This issue should now be resolved by just making sure to remind the reader to set node2d as the main scene.**
