### ISSUE TITLE
missing access to actions in the tutorial

### ISSUE THREAD

**Issue by skullauc** [godotengine/godot-docs#8174]
**Your Godot version:**
4.11
**Issue description:**
 missing how to access the actions from the menus and shortcuts for android

there r shortcuts for Linux/Windows and Mac like "Ctrl+D (Cmd+D for Mac) 
and no clue how to access the actions on Android

Point is, ideally the actions in the tutorial should be a catch-all. The tutorial has to specify how to access the actions from the menus. That's what users without a keyboard could do, and likewise, that's what Android users could do as well

Any way to access the features would be nice. This one too. But if there would be also a short cut like the specific linux/windows and mac ones, also for other systems the engine (editor) runs on, would be even nicer, just simply logically, following the very sense and meaning of a tutorial

Something like "pop-up context menu -> duplicate" or Ctrl+D (Cmd+D on Mac, long tap on mobile)
 - instead of just "Ctrl+D (Cmd+D on Mac) 

another example:
Close the window or press F8 (Cmd + . on macOS) to quit the running scene.
 - how to stop execution on Android? when i press "back" - "<", the window is minimized, when i maximize it, the scene is still running there. the only workaround i v found is to kill the editor, start anew, reopen the project, etc 

**URL to the documentation page (if already existing):**
https://docs.godotengine.org/en/stable/getting_started/step_by_step/nodes_and_scenes.html

**Comment by skyace65** [comment]
I'm not exactly sure what the issue is on the page that you linked to (nodes and scenes). All 3 shortcuts mentioned on that page are mentioned after telling you or showing you how to do an action without the shortcut. Could you be more specific on where in this page you're having an issue?

**Comment by skyace65** [comment]
I'm testing the editor on my phone, pressing the back button is killing the screen for me. What version of android are you on? This might be an engine/editor bug.
