### ISSUE TITLE
Step by step tutorial mentions incorrect shortcut to change to 2D workspace for macos

### ISSUE THREAD

**Issue by dan-lind** [godotengine/godot-docs#8182]
**Your Godot version:**
4.1.2

**Issue description:**

The signals chapter in the Step by step tutorial mentions a shortcut to switch to the 2D workspace

`Head back to the 2D workspace. You can either click the "2D" text at the top of the window or press Ctrl + F1 (Alt + 1 on macOS).`

I'm on mac os, so I assume that Alt + 1 really means Opt + 1. But that shortcut doesn't work. 
Looking at the defaults in Editor settings shows that the shortcut is really Command + Ctrl + 1 (which is pretty awkward to press)
<img width="582" alt="image" src="https://github.com/godotengine/godot-docs/assets/433464/0c8c22b7-9163-4ba0-9fb8-8d3f45578eb8">

**URL to the documentation page:**
https://docs.godotengine.org/en/stable/getting_started/step_by_step/signals.html

**Comment by AThousandShips** [comment]
[This](https://docs.godotengine.org/en/latest/getting_started/step_by_step/signals.html#connecting-a-signal-via-code) has already been fixed in #7792, not backported to 4.1 yet though
