### ISSUE TITLE
StringName methods don't exist for C#.

### ISSUE THREAD

**Issue by abmarnie** [godotengine/godot-docs#8190]
**Your Godot version:**
4.1.2
**Issue description:**
In C#, none of the methods listed in the `StringName` docs even exist. This can be seen [here](https://github.com/godotengine/godot/blob/6916349697a4339216469e9bf5899b983d78db07/modules/mono/glue/GodotSharp/GodotSharp/Core/StringName.cs), and in this screenshot:

![Screenshot_609](https://github.com/godotengine/godot-docs/assets/69956083/964b472a-71ae-4420-9b65-1e75792b641a)

 This should be mentioned briefly in a note on the `StringName` docs page itself. Perhaps the following:
> **Note:** None of the methods listed on this page are available in C#. Instead, use the provided `ToString()` method to cast a `StringName` to a `string`, and then use the equivalent methods in `System.String` or `StringExtensions`. For convenience, a list of equivalent methods is provided [here](https://docs.godotengine.org/en/stable/tutorials/scripting/c_sharp/c_sharp_differences.html#string).

**URL to the documentation page:**
https://docs.godotengine.org/en/stable/classes/class_stringname.html

**Comment by jcovin293** [comment]
I might be wrong, but I'm not sure this is possible as it states in the source file for this page that you should not edit the page because it is based on the engine source code. Maybe this could be added to another page?

**Comment by AThousandShips** [comment]
You do that over in the [main repository](https://github.com/godotengine/godot)

**Comment by Mickeon** [comment]
> But this should probably be listed under [here](https://docs.godotengine.org/en/stable/tutorials/scripting/c_sharp/c_sharp_differences.html) instead to the classref, it doesn't really deal with those differences

@raulsntos may beg to differ.

**Comment by raulsntos** [comment]
> > But this should probably be listed under [here](https://docs.godotengine.org/en/stable/tutorials/scripting/c_sharp/c_sharp_differences.html) instead to the classref, it doesn't really deal with those differences
> 
> @raulsntos may beg to differ.

I'm not opposed to adding a note about this in the differences page, the purpose of that page is to mention notable differences between C# and GDScript and I can see how this one can catch people off guard.

Just to be clear, these methods are not available in StringName, GDScript is just hiding an implicit conversion to String right?

**Comment by AThousandShips** [comment]
To be clear what I said was to not put it on the `StringName` page but the differences page, where these changes are navigated, but a note of seeing the differences

Indeed all of these methods on `StringName` use conversions

**Comment by Piralein** [comment]
The differences are already listed in the [C# differences page (string section)](https://docs.godotengine.org/en/stable/tutorials/scripting/c_sharp/c_sharp_differences.html#string).
[#86639](https://github.com/godotengine/godot/pull/86639) added the related note to the class reference page.

Closing as fixed.
