### ISSUE TITLE
Example in running_code_in_the_editor page uses "find_node()" function. This function has been removed.

### ISSUE THREAD

**Issue by Arnklit** [godotengine/godot-docs#8218]
**Your Godot version:**
4.1

**Issue description:**
Example in page uses "find_node()" function. This function has been removed.

**URL to the documentation page:**
https://docs.godotengine.org/en/stable/tutorials/plugins/running_code_in_the_editor.html

Edit: I had accidentally written "get_node" instead of "find_node"

**Comment by ShatReal** [comment]
I was so confused before I realized you meant "find_node"

**Comment by Arnklit** [comment]
oh dear, I'm sorry it's a bit late here and I'm obviously too tired to be logging bugs.
