### ISSUE TITLE
TIME not working on shaders

### ISSUE THREAD

**Issue by AndrewvanDijk** [godotengine/godot-docs#8238]
**4.1**

**TIME not working on Shaders**

**https://docs.godotengine.org/en/stable/tutorials/shaders/your_first_shader/your_first_2d_shader.html**

**Sample shader code the variable TIME is either being ignored or is always 0.0**

```
shader_type canvas_item;

uniform sampler2D SCREEN_TEXTURE : hint_screen_texture, filter_linear_mipmap;
uniform vec2 scale;
uniform vec4 water_color: source_color;
uniform float y_zoom; 
uniform sampler2D noise;
uniform vec2 distortion_scale;
uniform float intensity;
uniform float speed;

void fragment() {
	float distortion = texture(noise, UV * scale * distortion_scale + TIME * speed).x ;
	distortion -= 0.5;
	
	float uv_height = SCREEN_PIXEL_SIZE.y / TEXTURE_PIXEL_SIZE.y;
	vec2 reflected_screenuv = vec2(SCREEN_UV.x - distortion * intensity , SCREEN_UV.y + uv_height * UV.y * scale.y * y_zoom * -2.0);
	
	//COLOR = texture(SCREEN_TEXTURE , reflected_screenuv);
	vec4 reflection = texture(SCREEN_TEXTURE , reflected_screenuv);
	COLOR.rgb = mix(reflection.rgb, water_color.rgb , water_color.a);
	
}
```

**Comment by AThousandShips** [comment]
Does it work if you do:
```
float distortion = texture(noise, UV * scale * distortion_scale + vec2(TIME * speed)).x;
```

**Comment by AndrewvanDijk** [comment]
Hi,
Thanks for the response.
It did not work, I found some code on the web, and adjusted it a bit, this
is what worked for me...

float movement = (float(int(TIME * 100.0) % 1000 ) / 2000.0) * speed;
float distortion = texture(noise, UV * scale * distortion_scale +
movement).x ;

Kind Regards
Andrew

<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Virus-free.www.avast.com
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

**Comment by AndrewvanDijk** [comment]
Tried that as well, had no effect

**Comment by AThousandShips** [comment]
Then please open a bug report [here](https://github.com/godotengine/godot) as this is not a documentation issue

**Comment by AndrewvanDijk** [comment]
I'm going to play around a bit longer, and just see if my understanding is not our of whack.
You can close the issue, thanks for the help.
