### ISSUE TITLE
Document using CUSTOM* built-ins to access extra UVs

### ISSUE THREAD

**Issue by noidexe** [godotengine/godot-docs#8240]
**Your Godot version:** 4.2-beta1

**Issue description:** 
https://github.com/godotengine/godot/pull/52504 this PR added support for multiple UVs. When importing a gltf file, the first two uvs are mapped to the UV and UV2 vertex build-ins, while the rest go to the xy and zw channels of the CUSTOM* built-ins, supporting up to 8 uvs total. 
This doesn't seem to be documented anywhere. The table showing vertex build-ins lists CUSTOM0,1,2,3 but they have no description. I understand they are multipurpose but I think it'd be important to state somewhere that they are automatically populated with extra UVs

**URL to the documentation page (if already existing):** https://docs.godotengine.org/en/latest/tutorials/shaders/shader_reference/spatial_shader.html#vertex-built-ins

**Comment by fire** [comment]
See also the proposal https://github.com/godotengine/godot-proposals/issues/2266
