### ISSUE TITLE
EPub Doesn't Work in Apple Books Application

### ISSUE THREAD

**Issue by jcovin293** [godotengine/godot-docs#8249]
**Issue description:**

I downloaded the EPub file listed on this documentation and tried to open it in the native app for epub files on my computer, the Apple Books app. Each page says that there are errors such as these shown below:

<img width="894" alt="Screenshot 2023-10-15 at 12 40 42" src="https://github.com/godotengine/godot-docs/assets/111152655/8df17038-b3b8-448b-9684-6d86ebfed909">

The first few pages all have the same issue (I haven't checked all the pages but I assume that they all have this issue that I screenshotted).

**Here is the link to the page to download the EPub:** https://docs.godotengine.org/en/stable/index.html

**Comment by Piralein** [comment]
Thank you for the report.
There is already an open issue about this error, see: #7498
If you have new information about the problem, please add them to the existing issue.

Closing as duplicate.
