### ISSUE TITLE
"Pull Request Workflow" should point out that force push is required after rebase

### ISSUE THREAD

**Issue by BrianMacIntosh** [godotengine/godot-docs#8256]
**Your Godot version:**
v4.2.beta.custom_build [e0cb60a8a]

**Issue description:**
After locally rebasing a branch for a pull request, `git push --force` is required. Attempting to push normally unhelpfully tells the user to `git pull` again. I tripped on this in a PR (https://github.com/godotengine/godot/pull/82707). In general, the Pull Request Workflow page is very thorough and helpful for git newcomers, so I think the **Updating your branch** section should say something about this.

**URL to the documentation page (if already existing):**
https://docs.godotengine.org/en/stable/contributing/workflow/pr_workflow.html#updating-your-branch

**Comment by AThousandShips** [comment]
It does, [here](https://docs.godotengine.org/en/latest/contributing/workflow/pr_workflow.html#modifying-a-pull-request)

**Comment by BrianMacIntosh** [comment]
I had read the whole thing (days ago, of course), but the way I'm using it (and the way I think the structure suggests) is to return to it when I need to do a particular task, find the section for that task, and walk through it. Because I didn't need to amend or squash anything here, I didn't think to check the amending/squashing sections.

From reading those sections previously, I didn't connect a simple `git pull --rebase` with the need to force-push - I thought it was only necessary because those two tasks are doing 'weirder' things with modifying and rewriting existing commits.

**Comment by BrianMacIntosh** [comment]
> I'm also not sure this is what caused your issue, but an incorrect rebase
I think you're right, but the thing that led to that was that after I _correctly_ rebased, I tried to push and was told by git I still needed to pull. So I attempted to do that, and that's where the trouble started.

**Comment by AThousandShips** [comment]
Note that the section you're looking at isn't for updating a created feature branch, but for updating your own master branch before creating a feature, so this isn't relevant to that issue

**Comment by AThousandShips** [comment]
Did you use `git pull --rebase` to update your branch or `git rebase -i`?

**Comment by BrianMacIntosh** [comment]
I see what you mean about that section being intended for pulling to `master`. The directions there do work for feature branches (with the addition of `git push --force`), but if you would prefer people rebase interactively, a different possible fix could be to slightly reword the **The interactive rebase** section to point out that it's good for that situation. Currently it's framed very specifically as "this is what you do if you need to squash commits".

I used `git pull --rebase` in this case.

**Comment by AThousandShips** [comment]
Feel free to open a PR to update the documentation, but make sure to clarify the cases for this
