### ISSUE TITLE
An Image in Part 3 of the 'Your First 3D Game' Tutorial is Out of Date

### ISSUE THREAD

**Issue by Jamibaraki** [godotengine/godot-docs#8276]
**Your Godot version:**
4.1.1

**Issue description:**
The image '04.scene_tree_with_camera' is for Godot 3.

This is a specific instance of a general issue mentioned here:
https://github.com/godotengine/godot-docs/issues/6744

**URL to the documentation page (if already existing):**
https://docs.godotengine.org/en/stable/getting_started/first_3d_game/03.player_movement_code.html

**Comment by skyace65** [comment]
Fixed by #8277.
