### ISSUE TITLE
Error description of the Alternative tiles Transpose operation

### ISSUE THREAD

**Issue by verbess** [godotengine/godot-docs#8297]
**Your Godot version:**
version: 4.1.2

**Issue description:**
The statement in the [Godot documentation](https://docs.godotengine.org/en/latest/tutorials/2d/using_tilesets.html#creating-alternative-tiles) that Transpose is equivalent to rotating a tile counter-clockwise by 90 degrees seems to be entirely incorrect.

  > Rendering > Transpose: If true, the tile is rotated 90 degrees counter-clockwise.

The accurate description should be that it is equivalent to rotating the tile counter-clockwise by 90 degrees and then performing a vertical flip operation.

  > Combine this with Flip H and/or Flip V to perform 180-degree or 270-degree rotation.

When combined with `Flip H`, it performs a 90-degree rotation instead of a 180-degree rotation.

- Rotate 90 degrees clockwise:

  Enable `Flip H` and `Transpose`.

- Rotate 180 degrees clockwise:

  Enable `Flip H` and `Flip V`.

- Rotate 270 degrees clockwise:

  Enable `Flip V` and `Transpose`.

**URL to the documentation page:**
https://docs.godotengine.org/en/latest/tutorials/2d/using_tilesets.html#creating-alternative-tiles

**Comment by verbess** [comment]
A PR for a fix has been submitted. See [godotengine/godot-docs#8299](https://github.com/godotengine/godot-docs/pull/8299)

**Comment by AThousandShips** [comment]
Completed in:
* #8299
