### ISSUE TITLE
Save game tutorial code does not work (?)

### ISSUE THREAD

**Issue by stillinthe90s** [godotengine/godot-docs#83]
Please correct me if I'm getting it wrong, but it looks to me as if the example code in the tutorial ( http://docs.godotengine.org/en/latest/tutorials/engine/saving_games.html ) results in an incresing number of nodes every time a game is loaded.
Moving "var currentline = {}" inside the while loop worked in my test project, but I don't know if that is a general fix.

**Comment by NathanLovato** [comment]
Pretty old issue, closing it as the code works okay in Godot 2.1, and the guide could use an update for 3.0, see https://github.com/godotengine/godot-docs/issues/427
