### ISSUE TITLE
Small typo in PinJoint3D description

### ISSUE THREAD

**Issue by lukky-nl** [godotengine/godot-docs#8314]
Godot 4.1

PinJoint3D Description reads : 

A physics joint that attaches two **2D** physics bodies at a single point, allowing them to freely rotate. For example, a RigidBody3D can be attached to a StaticBody3D to create a pendulum or a seesaw.

2D should be 3D

(https://docs.godotengine.org/en/4.1/classes/class_pinjoint3d.html)

**Comment by AThousandShips** [comment]
Closing as solved in:
* https://github.com/godotengine/godot/pull/79781

As you can see in the latest version of the docs it is fixed, will be updated in the stable documentation at some point as well
