### ISSUE TITLE
A bit confused about Transfrom2D class reference

### ISSUE THREAD

**Issue by ronroniv** [godotengine/godot-docs#833]
> Represents one or many transformations in 3D space such as translation, rotation, or scaling. It consists of a two Vector2 x, y and Vector2 “origin”. It is similar to a 3x2 matrix.

I wonder if `3D` part is a typo? I was thinking about doing a simple pull request to fix it, but then I became unsure if it really means '2D transformations in 3D space'. (I'm pretty new to game dev after all.)

**Comment by PatheticJuan** [comment]
Not a high priority.. voting to close this! We should focus on jitter bugs and hardware level mouse cursor support.. But oh wait, don't mention this on discord, or you will get banned!

**Comment by cbscribe** [comment]
Note that class docs come from the main repo, not godot-docs

Fixed in https://github.com/godotengine/godot/pull/15016
