### ISSUE TITLE
Documentation Typo

### ISSUE THREAD

**Issue by EthanDelong** [godotengine/godot-docs#8336]
**Your Godot version:**

4.1

**Issue description:**

Typo in Dictionary section. Says "Colelctions" instead of "Collections"

**URL to the documentation page:**

https://docs.godotengine.org/en/stable/tutorials/scripting/c_sharp/c_sharp_differences.html

If you know how to fix the issue you are reporting please
consider opening a pull request. We provide a tutorial on
using git here: https://docs.godotengine.org/en/stable/community/contributing/pr_workflow.html,
writing documentation at https://docs.godotengine.org/en/stable/community/contributing/docs_writing_guidelines.html
and contributing to the class reference here: https://docs.godotengine.org/en/stable/community/contributing/updating_the_class_reference.html

**Comment by AThousandShips** [comment]
Fixed in:
* #8002

Will be cherry picked for the 4.1 documentation
