### ISSUE TITLE
Sidebar navigation links not clickable on iPad

### ISSUE THREAD

**Issue by dmvgbs** [godotengine/godot-docs#8351]
**Your Godot version:**
4.1

**Issue description:**
I just tried to use the documentation website for version 4.1 on my iPad Air and couldn't use the sidebar navigation at all.
It isn't opening the links and the links aren't revealing the sub-navigation like it does on the desktop version.

I have tested the Firefox and Safari in their newest versions.
I was also able to reproduce this behavior within the xcode simulator on my Mac as a fresh install.

I'm not sure about other iOS Hardware, haven't tested it.

Hardware to reproduce:
iPad Air 5
iPadOS Version 16.2

Browser tested:
Firefox 117.3
Safari 17.0

Do you need any further information?

**URL to the documentation page:**
https://docs.godotengine.org/en/stable/

**Comment by AyOhEe** [comment]
Can confirm this also occurs on iPhone 12 running iOS 15.4.

**Comment by YuriSizov** [comment]
Yep, Safari has problems. This is fixed by https://github.com/godotengine/godot-docs/pull/8334. Will be deployed to the 4.1 version some time this week.

**Comment by pipehat** [comment]
Resolved for me on ‘latest’ but problem remains as described any other version including ‘stable’ and ‘4.1’. 

iPhone
