### ISSUE TITLE
Editor Freezes when Cancelling a New Scene Creation

### ISSUE THREAD

**Issue by Griphen116** [godotengine/godot-docs#8353]
**Your Godot version:**
4.1.2 stable

**Issue description:**
When creating a new scene with "Scene > New Scene" from the top menu, then clicking "Cancel" the editor will freeze and the process will need to be killed and the app restarted.

**URL to the documentation page:**

If you know how to fix the issue you are reporting please
consider opening a pull request. We provide a tutorial on
using git here: https://docs.godotengine.org/en/stable/community/contributing/pr_workflow.html,
writing documentation at https://docs.godotengine.org/en/stable/community/contributing/docs_writing_guidelines.html
and contributing to the class reference here: https://docs.godotengine.org/en/stable/community/contributing/updating_the_class_reference.html

**Comment by AThousandShips** [comment]
This is for documentation errors, please open other error reports [here](https://github.com/godotengine/godot/issues)

**Comment by skyace65** [comment]
Closing per AThousandShips comment.
