### ISSUE TITLE
Breakpoints in VisualStudio C# not working with Godot Console Windows

### ISSUE THREAD

**Issue by peter6020** [godotengine/godot-docs#8356]
**Versions**
+ Godot 4.1.2 
+ VisualStudio 2019
+ .NET 6
+ OS: Windows 11

**Issue description part 1:**

Reproduce the problem by setting up a simple C# script and set a breakpoint in Visual Studio. Here are the configuration details:

- Setup a scene in Godot and attach a C# script
- In Godot goto `Editor -> Editor Settings -> Dotnet -> Editor` select `Visual Studio`
- In Godot click the Script-symbol to open Visual Studio
- In Visual Studio create a new debug profile with the following settings (the automatially created profile does not work):
  - Launch: `Executable`
  - Executable: `<path to Godot Windows>` (in my case `C:\Program Files\godot\Godot-v4.1.2\Godot_v4.1.2-stable_mono_win64.exe`)
  - Application arguments: `--path .`  (mind the space and dot after `--path`)
  - Working directory: `.` (dot)
  - Check `Enable native code debgging`
  - Save the settings

Now open your C# script in VisualStudio and modify the `Ready_()` method as shown below and set a breakpoint on the line with the  `GD.Print()` statement: 

```
public override void _Ready()
{
    GD.Print("Hello VisualStudio");  // set a breakpoint at this line
}
```

Press F5 to run the code.
**Result 1:** Program stops at the breakpoint. Continuing the program does *not* output `Hello VisualStudio` to the output-window of Visual Studio.

**Issue description part 2:**

Same setup as before, but in the editor profile set
  - Executable: `<path to Godot **Console**>` (in my case `C:\Program Files\godot\Godot-v4.1.2\Godot_v4.1.2-stable_mono_win64_console.exe`)

Press F5 to run the code.
**Result 2:** A console window opens, but the program does *not* stopp at the breakpoint and `Hello VisualStudio` is sent to the DOS window.

**Summary:**
- with the Godot Windows build, breakpoints are working, but printf-debugging is not possible
- with the Godot Console build, breakpoint don't work, but printf-debugging is possible

So, none of both ways allow efficient debugging. 
Is there a solution or workaround of how to enable breakpoints in the Godot Console build?

Thanks and kind regards,

Peter

**Comment by AThousandShips** [comment]
Is the issue here incorrect instructions for setting this up? What needs to be changed to clarify it?

If it's not about the documentation please report [here](https://github.com/godotengine/godot/issues) instead

**Comment by peter6020** [comment]
Sorry! Moved it to [here](https://github.com/godotengine/godot/issues/84314).

**Comment by peter6020** [comment]
Issue was added to Godot doc related issues instead of code related issues.

**Comment by D1mentrrr** [comment]
What if my breakpoints does not work even with Godot_v4.3-stable_mono_win64.exe. I'v done everything like in the guide. When I press F5 in vs game starts, I see my game window, but it skips all the breakpoints. Also they have some kind of error like "The breakpoint will not currently be hit. No symbols have been loaded from this document"
