### ISSUE TITLE
Contradictory info on @GlobalScope.randomize

### ISSUE THREAD

**Issue by curious-broccoli** [godotengine/godot-docs#8374]
**Your Godot version:** latest

**Issue description:**

The @GlobalScope.randomize [docs](https://github.com/godotengine/godot/blob/e07b3ee253a85d338d60a68a10209ac72cad8ba0/doc/classes/%40GlobalScope.xml#L1090) say that randomize is called every time the project is run. Yet the [tutorial for RNG](https://github.com/godotengine/godot-docs/blob/56d0a58cdf58ad3ef04a7e29b15861bfb17e4bec/tutorials/math/random_number_generation.rst?plain=1#L51) says that randomize should be called once every time the project is run. I think this is contradictory. If randomize is already called automatically, the note in the tutorial should be removed or changed to "is run automatically etc.".
Is that correct?

**Comment by AThousandShips** [comment]
The part above says this already:
> Since Godot 4.0, the random seed is automatically set to a random value when the project starts. This means you don't need to call ``randomize()`` in ``_ready()`` anymore to ensure that results are random across project runs. However, you can still use ``randomize()`` if you want to use a specific seed number, or generate it using a different method.
