### ISSUE TITLE
Clarify type of introductory shader example

### ISSUE THREAD

**Issue by wlsnmrk** [godotengine/godot-docs#8383]
**Your Godot version:** 4.1.1

**Issue description:** 
The [introductory shader page](https://docs.godotengine.org/en/stable/tutorials/shaders/introduction_to_shaders.html) includes a simple example fragment shader for changing the color of a texture. However, it's not immediately clear that it's intended as a CanvasItem fragment shader, not a Spatial fragment shader. `COLOR`, used to set the texture's color in the example, is an **inout** property for CanvasItem fragment shaders, but an **in** property for Spatial fragment shaders, and using it as illustrated in a Spatial shader will cause an error.

Presumably we don't want to over-complicate an introduction by throwing lots of extraneous information at the reader, but I'm wondering if there's some way this can be improved to prevent confusion. Maybe a simple parenthetical remark that this example is specifically for 2D, and 3D shaders will look similar but may use different property names?

**URL to the documentation page (if already existing):** https://docs.godotengine.org/en/stable/tutorials/shaders/introduction_to_shaders.html

**Comment by AThousandShips** [comment]
It's not intended as an example, just an introduction to the concept, IMO this would be irrelevant info

**Comment by skyace65** [comment]
Closing per AThousandShips comment. This isn't necessary info for these specific code snippets.
