### ISSUE TITLE
Button creation through script is outdated.

### ISSUE THREAD

**Issue by NepKitsuna** [godotengine/godot-docs#8397]
**Your Godot version: v4.1.2**

**Issue description: The script for assigning a function to the button is off and does not compile**

**URL to the documentation page: https://docs.godotengine.org/en/stable/classes/class_button.html**

The function on the docs is as such: "button.pressed.connect(self._button_pressed)"

The working function is written as such: "button.pressed.connect(self._button_pressed.bind())"

If you know how to fix the issue you are reporting please
consider opening a pull request. We provide a tutorial on
using git here: https://docs.godotengine.org/en/stable/community/contributing/pr_workflow.html,
writing documentation at https://docs.godotengine.org/en/stable/community/contributing/docs_writing_guidelines.html
and contributing to the class reference here: https://docs.godotengine.org/en/stable/community/contributing/updating_the_class_reference.html

**Comment by AThousandShips** [comment]
> The working function is written as such: "button.pressed.connect(self._button_pressed.bind())"

This is wrong, the "bind" part is not required and where do you get this from?

**Comment by NepKitsuna** [comment]
> > The working function is written as such: "button.pressed.connect(self._button_pressed.bind())"
> 
> This is wrong, the "bind" part is not required and where do you get this from?

I am working with this function right now, It would not work without the "bind" part.

**Comment by AThousandShips** [comment]
There's no error at all, I tested it right now and no errors

Can you please send the actual code you have, you likely copied it wrong, as the code in the tutorial is 100% correct, it compiles and runs correctly

**Comment by NepKitsuna** [comment]
> There's no error at all, I tested it right now and no errors
> 
> Can you please send the actual code you have, you likely copied it wrong, as the code in the tutorial is 100% correct, it compiles and runs correctly

OOOOOH, I apologize, I see what I did that broke it.

I was writing the function as : "button.pressed.connect(self._button_pressed())" which results in the error: "Invalid type in function 'connect' in base 'Signal'. Cannot convert argument 1 from Nil to Callable."

**Comment by NepKitsuna** [comment]
> There's no error at all, I tested it right now and no errors
> 
> Can you please send the actual code you have, you likely copied it wrong, as the code in the tutorial is 100% correct, it compiles and runs correctly
> 
> You probably did it like this:
> 
> ```gdscript
> func _ready():
> 	var button = Button.new()
> 	button.text = "Click me"
> 	button.pressed.connect(self._button_pressed())
> 	add_child(button)
> 
> func _button_pressed():
> 	print("Hello world!")
> ```
> 
> By mistake due to autocomplete

You are correct, Thank you for pointing this out, I will close the issue

**Comment by AThousandShips** [comment]
No worries, but please check the other [community channels](https://godotengine.org/community) before opening an issue for things like this, it helps identifying if there's some error or some confusion :)

Thank you for reporting and have a nice day
