### ISSUE TITLE
Particle Shader Built-In's

### ISSUE THREAD

**Issue by mojoyup1528** [godotengine/godot-docs#8398]
**Your Godot version:**
v4.1.3.stable.mono.official [f06b6836a]

**Issue description:**
I am modifying a shader in a ParticleProcessMaterial, and I noticed that I get errors for the built-in's in the documentation: https://docs.godotengine.org/en/stable/tutorials/shaders/shader_reference/particle_shader.html#start-and-process-built-ins. It doesn't seem to recognize them. 
Here is the shader script I have so far, and the built-in's used are "RESTART", "NUMBER", "RANDOM_SEED", "VELOCITY", "CUSTOM", "TRANSFORM", though I have not been able to check them all because of error order. Hope this helps and Ill try to work to find solutions on my end, but I think I need the built-in's. Hope all is well! SCRIPT:shader_type particles;

```
shader_type particles;

float rand_from_seed(in uint seed) {
  int k;
  int s = int(seed);
  if (s == 0)
    s = 305420679;
  k = s / 127773;
  s = 16807 * (s - k * 127773) - 2836 * k;
  if (s < 0)
    s += 2147483647;
  seed = uint(s);
  return float(seed % uint(65536)) / 65535.0;
}

uint hash(uint x) {
  x = ((x >> uint(16)) ^ x) * uint(73244475);
  x = ((x >> uint(16)) ^ x) * uint(73244475);
  x = (x >> uint(16)) ^ x;
  return x;
}

void vertex() {
  if (RESTART) {
	uint alt_seed1 = hash(NUMBER + uint(1) + RANDOM_SEED);
	uint alt_seed2 = hash(NUMBER + uint(27) + RANDOM_SEED);
	uint alt_seed3 = hash(NUMBER + uint(43) + RANDOM_SEED);
	uint alt_seed4 = hash(NUMBER + uint(111) + RANDOM_SEED);
	
	CUSTOM.x = rand_from_seed(alt_seed1);
	vec3 position = vec3(rand_from_seed(alt_seed2) * 2.0 - 1.0,
	                     rand_from_seed(alt_seed3) * 2.0 - 1.0,
	                     rand_from_seed(alt_seed4) * 2.0 - 1.0);
						
	TRANSFORM[3].xyz = position*2.0;
	float wave_frequency = 1.0;
	float wave_amplitude = 5.0;
//	VELOCITY.x = cos(TIME + CUSTOM.x * 6.28) * 4.0 + 6.0;
//	VELOCITY.y = cos(TIME + CUSTOM.x * 6.28) * 4.0 + 6.0;
//	VELOCITY.z = cos(TIME + CUSTOM.x * 6.28) * 4.0 + 6.0;
	VELOCITY.x = sin(TIME * wave_frequency + CUSTOM.x * 1.0) * wave_amplitude + 2.0;
	VELOCITY.y = sin(TIME * wave_frequency + CUSTOM.x * 2.0) * wave_amplitude + 2.0;
	VELOCITY.z = sin(TIME * wave_frequency + CUSTOM.x * 3.0) * wave_amplitude + 2.0;
	CUSTOM.y = VELOCITY.z * 0.1;
  } else {
    //
  }
}
```
**URL to the documentation page (if already existing):**
https://docs.godotengine.org/en/stable/tutorials/shaders/shader_reference/particle_shader.html#start-and-process-built-ins

**Comment by mojoyup1528** [comment]
Did start and process overtake vertex and fragment?

**Comment by AThousandShips** [comment]
There is no `vertex` stage, see the page you linked it says this:
> Particle shaders are unique because they are not used to draw the object itself; they are used to calculate particle properties, which are then used by the CanvasItem of Spatial shader. They contain two processor functions: `start()` and `process()`.

**Comment by mojoyup1528** [comment]
That's why I was asking because in the previous 3.x versions, I was using vertex() in order to control instance transforms. I was thinking that is what causes the error considering the documentation says its up to date.

**Comment by AThousandShips** [comment]
Then please see the [documentation](https://docs.godotengine.org/en/stable/tutorials/migrating/upgrading_to_godot_4.html#updating-shaders) for updating shaders, it's all very clearly documented :)

**Comment by paddy-exe** [comment]
> That's why I was asking because in the previous 3.x versions, I was using vertex() in order to control instance transforms. I was thinking that is what causes the error considering the documentation says its up to date. 

The functions were changed from 3.x to 4.0 so you have to adapt your shader accordingly

**Comment by mojoyup1528** [comment]
no comment
