### ISSUE TITLE
Re-order sections of the About category

### ISSUE THREAD

**Issue by Cerno-b** [godotengine/godot-docs#8399]
**Your Godot version:**

Head of the `master` branch of the godot-docs repo

**Issue description:**

I find the structure of the `About` section a bit odd. 

First, I don't understand why the `Troubleshooting` section is featured so prominently, I think it gives a bad first impression, since it's:

* `Introduction` (obviously)
* `FAQ`, ok, a bit too soon, but why not? 
* Immediately a list of things that don't work as expected. 

I think the `Troubleshooting` section (if needed in the docs at all), should be moved to the very bottom below `Class Reference`, or potentially even removed as there are other troubleshooting resources available. I assume its purpose is to collect certain very common problems that beginners have. Is it even up-to-date with the currently known frequent issues?

And then the rest of the sections are not in a very optimal order. In terms of what a new reader might expect or need, I would suggest the following order:

* Intro
* Feature List
* FAQ (switch with Feature List because tell me what the engine can do before trying to answer questions I may not have yet)
* Licenses (move it up because we need to talk about legal implications as soon as my questions are answered)
* Release Policy
* Changelog (put changelog last because it's some housekeeping info that I would kind of expect there)

And then, as outlined above, move the `Troubleshooting` stuff to the very bottom of the docs, if they are even needed in the docs after all.

**URL to the documentation page (if already existing):**

**Comment by YuriSizov** [comment]
> Is it even up-to-date with the currently known frequent issues?

It should be, @Calinou makes sure of it. I agree, though, that it's oddly placed among the intro articles. It can be moved to the Manual category, next to the first 3 meta sections in there. Probably next after best practices.

For the rest, I agree with the reorder. Feel free to open a PR. (If you make a PR for moving the troubleshooting article as well, make sure to update the redirects file).

**Comment by Cerno-b** [comment]
I might take some time to get to this since I'm in the middle of reviewing and streamlining the German "Getting Started" section including running the tutorials, but I'll see if I can figure out how this is done afterwards.

**Comment by Cerno-b** [comment]
@YuriSizov Just to be safe: I need to move the `troubleshooting.rst` file to a different subdir and adapt the `index.rst`.

Is Sphinx smart enough not to mess up the translations?

The way I understand it, the .po files from weblate are path-based, so I wonder what happens if I move an existing rst file to a new location. Can you clarify?

**Comment by YuriSizov** [comment]
I don't know how Weblate will handle this. We get everything as a single PO file. From the PO perspective only string IDs matter, and multiple file paths can be related to the same string. So from the PO perspective this move shouldn't change anything, won't even make translations fuzzy. But I don't know if Weblate does something on top of that.

**Comment by Cerno-b** [comment]
Nice, I don't know how it's done internally, as long as it works :)

**Comment by AThousandShips** [comment]
Does the existing translation consider redirects? Or do we lose existing translation?
