### ISSUE TITLE
Adding scenes is not completely clear

### ISSUE THREAD

**Issue by dobin** [godotengine/godot-docs#8400]
Small thing: In the "Your First 2D game" tutorial, its often mentioned something like: 

https://docs.godotengine.org/en/stable/getting_started/first_2d_game/06.heads_up_display.html:
"Create a new scene, and add a CanvasLayer node named HUD."

When i click "Scene -> New Scene", i need to (?) select a "Root Node" (2D, 3D, Other node...). In "Creating the player scene" it was described which root node needs to be selected, but after that not really.play.html:
"Create a new scene, and add a CanvasLayer node named HUD."

When i click "Scene -> New Scene", i need to (?) select a "Root Node" (2D, 3D, Other node...). In "Creating the player scene" it was described which root node needs to be selected, but after that not really.

So i think "add a CanvasLayer" is not really adding one, but setting the new root node to the CanvasLayer type? 

Maybe its more clear when writing "Create a new scene, set it to the CanvasLayer type and name it HUD". 

Edit: The rest of the tutorial worked perfectly with Godot 4.1.3 windows x64 gscript.

**Comment by AThousandShips** [comment]
The same wording is used for the previous steps, so should be obvious if you've followed those IMO, as the procedure is learned

**Comment by skyace65** [comment]
Closing per AThousandShips comment. The previous page "The main game scene" describes creating a scene in the exact same way, there shouldn't be any confusion at this point.
