### ISSUE TITLE
Incorrect information on Using ImmediateMesh doc

### ISSUE THREAD

**Issue by Sigma-dev** [godotengine/godot-docs#8419]
**The docs state that ImmediateMesh is a node which it hasn't been for quite a while, the whole thing seems completely outdated and lead me to be very confused**

**https://docs.godotengine.org/en/stable/tutorials/3d/procedural_geometry/immediatemesh.html**

**Comment by clayjohn** [comment]
This has been fixed in the "latest" version of the docs already. It just needs to be cherrypicked back to the older versions

https://github.com/godotengine/godot-docs/pull/8272

**Comment by mhilbrunner** [comment]
Closing as per the above.
