### ISSUE TITLE
4.1 ePub docs fail to open on Apple Books, Google Play Books and Amazon kindle.

### ISSUE THREAD

**Issue by Davejkane** [godotengine/godot-docs#8423]
**Your Godot version:**

4.1

**Issue description:**

The ePub docs downloaded from the main documentation page on the website (link below) fail to open on any of the big three ePub readers. On Apple Books I can see the following error:

```
This page contains the following errors:

error on line 45 at column 10:
Opening and ending tag mismatch:
meta line 43 and head

Below is a rendering of the page up to the first error
```

None of the page is rendered. The same error is on pretty much every page. 

**URL to the documentation page:**

https://docs.godotengine.org/en/stable/index.html

**Comment by Piralein** [comment]
Thank you for the report.
There is already an open issue about this error, see: #7498
If you have new information about the problem, please add them to the existing issue.

Closing as duplicate.
