### ISSUE TITLE
Include a flat .txt file as a downloadable format

### ISSUE THREAD

**Issue by aalberti333** [godotengine/godot-docs#8427]
**Your Godot version:**
4.1

**Issue description:**
Including a single flat .txt file format of the documentation could allow it to be more easily consumable by AI models, allowing us to ask questions about the doc/Godot in an easier way to an LLM.

**URL to the documentation page (if already existing):**

**Comment by Calinou** [comment]
You can already download the repository's contents as a ZIP file: https://github.com/godotengine/godot-docs/archive/refs/heads/master.zip

It should be straightforward to write a script that concatenates all `*.rst` files together into a single text file. `cat` was literally designed to con**cat**enate after all 🙂

**Comment by aalberti333** [comment]
Thanks @Calinou , ended up writing something similar in PowerShell. Leaving below in case others find a use for it:

`PowerShell
# Define the root folder to start the search
$rootFolder = "C:\<my-path-here>\godot-docs-master"

# Define the output file
$outputFile = "C:\<my-path-here>\godot-docs-master.txt"

# Clear the content of the output file if it already exists
if (Test-Path $outputFile) {
    Clear-Content $outputFile
}

# Search for .rst files and concatenate their content
Get-ChildItem -Path $rootFolder -Filter *.rst -Recurse | ForEach-Object {
    $content = Get-Content $_.FullName
    $content | Out-File -Append -FilePath $outputFile
}

# Optional: Print a completion message
Write-Host "All .rst files have been concatenated into $outputFile"
`
