### ISSUE TITLE
In Sprite2D HFrames is for coulumns and it should be rows.

### ISSUE THREAD

**Issue by 4Shage** [godotengine/godot-docs#8428]
**Your Godot version:**
4.1.3

**Issue description:**
In Sprite2D HFrames is for coulumns and it should be rows.

**URL to the documentation page:**

If you know how to fix the issue you are reporting please
consider opening a pull request. We provide a tutorial on
using git here: https://docs.godotengine.org/en/stable/community/contributing/pr_workflow.html,
writing documentation at https://docs.godotengine.org/en/stable/community/contributing/docs_writing_guidelines.html
and contributing to the class reference here: https://docs.godotengine.org/en/stable/community/contributing/updating_the_class_reference.html

**Comment by SchadowHacker** [comment]
* Sprite2D not AnimationPlayer

**Comment by AThousandShips** [comment]
> In Sprite2D HFrames is for coulumns and it should be rows.

Why, it's for *horizontal* frames, i.e. columns, and v is for *vertical* frames, i.e. rows

**Comment by 4Shage** [comment]
![image](https://github.com/godotengine/godot-docs/assets/47282189/6a30bf4c-6610-4990-b1ad-821417cf0e27)

**Comment by 4Shage** [comment]
> Why, it's for _horizontal_ frames, i.e. columns, and `vframes` is for _vertical_ frames, i.e. rows


Ok, so I let it sit for a while and i think that i now understand.
Thank you for reply and I hope you have a great day.
