### ISSUE TITLE
Document ResourceLoader load() CacheModes

### ISSUE THREAD

**Issue by lostminds** [godotengine/godot-docs#8434]
**Your Godot version:**
4.2 beta 5

**Issue description:**
I was trying to figure out more precisely how load() would create new instances of the loaded resource or reuse already loaded instances. I think it's controlled by the optional cachemode parameter(?). However, this feels like an important and useful feature so it would be good if this was explained more explicitly. For example (my additions in _italics_ if my guesses are correct?):

enum CacheMode:
[CacheMode](https://docs.godotengine.org/en/stable/classes/class_resourceloader.html#enum-resourceloader-cachemode) **CACHE_MODE_IGNORE = 0**
_Load a new instance from path, regardless if loaded instance already exists in cache._

[CacheMode](https://docs.godotengine.org/en/stable/classes/class_resourceloader.html#enum-resourceloader-cachemode) **CACHE_MODE_REUSE = 1**
_Reuse already loaded instance from cache if one exists, otherwise load a new instance._

[CacheMode](https://docs.godotengine.org/en/stable/classes/class_resourceloader.html#enum-resourceloader-cachemode) **CACHE_MODE_REPLACE = 2**
_Load a new instance from path and replace the currently cached instance if one exists._

**URL to the documentation page (if already existing):**
https://docs.godotengine.org/en/stable/classes/class_resourceloader.html#enum-resourceloader-cachemode

**Comment by erik-lance** [comment]
I have the same issues with this.  I was figuring out how to use `load_threaded_request,` and it told me:

> The `cache_mode` property defines whether and how the cache should be used or updated when loading the resource. See [CacheMode](https://docs.godotengine.org/en/stable/classes/class_resourceloader.html#enum-resourceloader-cachemode) for details.

Clicking it only led me to the cache mode options without any explanation. It would be nice to have a better understanding of how the caching works.

**Comment by YuriSizov** [comment]
These constants have been recently documented via https://github.com/godotengine/godot/pull/82884, should appear by next week in the online docs for the `latest` branch as well.
