### ISSUE TITLE
inaccurate claim that c#/c++ devs tend to not use dictionaries

### ISSUE THREAD

**Issue by ana-rchy** [godotengine/godot-docs#8435]
**Your Godot version:** 4.1

**Issue description:**
in the gdscript intro, theres this claim:
"Most programmers that come from statically typed languages (such as C++ or C#) ignore their existence and make their life unnecessarily more difficult. This datatype is generally not present in such languages (or only in limited form)."
it seems to imply that c#/c++ usually hinder themselves by not using dictionaries, even if its not the intention to do so. it also implies they have limited dictionary forms, which, idk for c++, but for c# theres definitely a full dictionary implementation
i would suggest rephrasing the paragraph to not specifically point out c++ and c#, and not make the hindrance claim

**URL to the documentation page (if already existing):** https://docs.godotengine.org/en/stable/tutorials/scripting/gdscript/gdscript_advanced.html

**Comment by YuriSizov** [comment]
I think the sentiment is generally fair, as in hash tables would be generally frowned upon if you could instead strictly type everything. But the language is unnecessarily hostile and should be rephrased.
