### ISSUE TITLE
C# layers examples use int instead of uint in c_sharp_exports.rst

### ISSUE THREAD

**Issue by tetrapod00** [godotengine/godot-docs#8439]
**Your Godot version:**
4.1.3
**Issue description:**
The C# examples for exporting physics and render layers use `int`, while C# appears to use `uint` for layers and layer masks. See examples in `VisualInstance3D`, `CollisionObject3D`. 

I have not looked to see if this issue appears elsewhere in the docs.

**URL to the documentation page:**
https://docs.godotengine.org/en/latest/tutorials/scripting/c_sharp/c_sharp_exports.html#exporting-bit-flags

Edit: created a PR to fix this particular occurrence. There may be other examples in the docs that use`int` instead of `uint`.

**Comment by paulloz** [comment]
I think this can be closed, since the linked PR was merged?

**Comment by raulsntos** [comment]
Thanks, closing per the above comment.
