### ISSUE TITLE
Ray Casting Doc Enhancements

### ISSUE THREAD

**Issue by MattHackk** [godotengine/godot-docs#8453]
**Your Godot version:**
4.1

**Issue description:**
Exclude property of ray cast queries are referred to as "Exceptions" but should be "Exclusions"

> To avoid self-intersection, the intersect_ray() parameters object can take an array of exceptions via its exclude property. 

The original wording is confusing as the word exception generally refers to an error. The word "Exception" appears several times in this doc, and never refers to an actual Exception.

A C# code snippet id missing from Ray Casting doc. The following GDScript does not have a C# translation:

```
const RAY_LENGTH = 1000

func _physics_process(delta):
	var space_state = get_world_3d().direct_space_state
	var cam = $Camera3D
	var mousepos = get_viewport().get_mouse_position()

	var origin = cam.project_ray_origin(mousepos)
	var end = origin + cam.project_ray_normal(mousepos) * RAY_LENGTH
	var query = PhysicsRayQueryParameters3D.create(origin, end)
	query.collide_with_areas = true

	var result = space_state.intersect_ray(query)
```

**URL to the documentation page (if already existing):**
https://docs.godotengine.org/en/stable/tutorials/physics/ray-casting.html

**Comment by AThousandShips** [comment]
This is in matching with: the [bodies](https://docs.godotengine.org/en/stable/classes/class_physicsbody3d.html#class-physicsbody3d-method-add-collision-exception-with) and is an established term for this, it does not exclusively refer to errors, in fact Godot does *not* have exceptions in that sense, so there's no confusion here IMO
