### ISSUE TITLE
Creating the Enemy - Wrong function for VisibleOnScreenNotifier2D

### ISSUE THREAD

**Issue by EvanoriMemoria** [godotengine/godot-docs#8455]
Godot version: 4.1

At the bottom of the Creating the Enemy [tutorial page](https://docs.godotengine.org/en/stable/getting_started/first_2d_game/04.creating_the_enemy.html) it is stated to use:

```
func _on_visible_on_screen_notifier_2d_screen_exited():
	queue_free()
```

However, I was only able to get this working using:

```
func _on_visible_on_screen_enabler_2d_screen_exited():
	queue_free()
```

Enabler vs Notifier.

This is potentially linked to #7581

**URL to the documentation page:** https://docs.godotengine.org/en/stable/getting_started/first_2d_game/04.creating_the_enemy.html

**Comment by AThousandShips** [comment]
Did you follow the instructions and add a `VisibleOnScreenNotifier2D` and not a `VisibleOnScreenEnabler2D`?

**Comment by EvanoriMemoria** [comment]
Ah, no it seems I just completely overlooked that. I do indeed have a VisibleOnScreenEnabler2D instead of notifier. Thanks for clearing up my confusion

**Comment by claritybear** [comment]
> Did you follow the instructions and add a `VisibleOnScreenNotifier2D` and not a `VisibleOnScreenEnabler2D`?

Not sure if I should reply on a closed issue, but how do I do this?
