### ISSUE TITLE
Inconsistent sliding speed in simple physics interaction

### ISSUE THREAD

**Issue by zoron98** [godotengine/godot-docs#8463]
Godot Version: 4.1.2

When porting a game from 3, there is an issue when a physics object such as characterbody3d or rigidbody3d slides across a surface (staticbody3d tested) .When creating a simple physics interaction where an object should slide across the ground and gradually come to a stop, the actual speed of the object will be much lower than the velocity value.

The issue only seems to occur when the moving object starts airborne, or at least it is more prevalent in that case.

This behavior did not occur the project i made in godot 3, so i dont believe it is intended.

Attached is a minimum reproduction project attached.
[example.zip](https://github.com/godotengine/godot-docs/files/13331031/example.zip)

**Comment by AThousandShips** [comment]
Superseded by https://github.com/godotengine/godot/issues/84854
