### ISSUE TITLE
ColorPicker : wrong place in Create New Node Window

### ISSUE THREAD

**Issue by Leedoriden** [godotengine/godot-docs#8470]
**Godot 4.1.3**

**ColoPicker is in wrong place in the window " Create new Node "
it's a subitem of VBoxContainer**

![g4 1 3_create_node_window](https://github.com/godotengine/godot-docs/assets/73864215/9493f50a-8479-47c4-b299-1e797e9f5642)

**Comment by AThousandShips** [comment]
This is the correct place, `ColorPicker` inherits from `VBoxContainer`, see [here](https://docs.godotengine.org/en/stable/classes/class_colorpicker.html)

Where would you like it to be?

Maybe you are looking for [`ColorPickerButton`](https://docs.godotengine.org/en/stable/classes/class_colorpickerbutton.html)

**Comment by AThousandShips** [comment]
Can you confirm what the issue here is? Because it is in the right place given what it inherits from.

**Comment by AThousandShips** [comment]
Closing due to lack of feedback, if you respond to the questions above this can be reopened and further discussed, but as there's nothing wrong in the code, as explained above, there's nothing to change without further information about what the issue is
