### ISSUE TITLE
Incomplete: TouchScreenButton documentation

### ISSUE THREAD

**Issue by Johnrobmiller** [godotengine/godot-docs#8487]
There is not enough information on this page to setup a TouchScreenButton. For example, does it need to be a child of a HUD? How do you view the button? Etc.

https://docs.godotengine.org/en/stable/classes/class_touchscreenbutton.html

**Comment by skyace65** [comment]
There's nothing in the class reference to imply that it would be the child of a HUD (Control Node). It explicitly states that it's intended for gameplay use and to use the regular button node for user interfaces. And you wouldn't view the button because it's for gameplay use.
