### ISSUE TITLE
[Discussion] Refactoring Assets Pipeline section

### ISSUE THREAD

**Issue by StraToN** [godotengine/godot-docs#85]
Assets Pipeline currently contains following sub-sections and pages:
- General
  - Managing image files
- Import
  - Import process
  - Import textures
  - Import fonts
  - Import audio samples
  - Import translations
- Export
  - Exporting projects
  - One-click deploy
  - Exporting for PC
  - Exporting for Android
  - Exporting for iOS

As we can see, the "Export" section does not rely to assets, but projects export. I propose that this "Export" section moves elsewhere (or becomes a new section), and to rename "Assets Pipeline" to "Import Assets", or "Managing Assets"

**Comment by bojidar-bg** [comment]
:+1: I would make Export its own section until there are some articles that might be bundled along it, and rename it to "Managing Assets" (since it is more about managing than importing IMO)

**Comment by pwab** [comment]
It is now:

```
Project workflow
- Project setup
- Assets workflow
- Export
```

Could be closed?

**Comment by akien-mga** [comment]
Yep.
