### ISSUE TITLE
I can't find the KinematicBody2d node

### ISSUE THREAD

**Issue by Lillip3** [godotengine/godot-docs#8522]
I tried to look in the "search help" as it says in the documentation and even then nothing came up. Could you help me please

**Comment by AThousandShips** [comment]
There is no such thing any more, see [here](https://docs.godotengine.org/en/stable/tutorials/migrating/upgrading_to_godot_4.html#automatically-renamed-nodes-and-resources)

This class no longer exists

**Comment by Piralein** [comment]
Please use one of the [community platforms](https://godotengine.org/community/) to ask help, this repository is for reporting issues with the documentation.

**Comment by Lillip3** [comment]
@AThousandShips Oh right, thanks so much for the help!

**Comment by Lillip3** [comment]
@Piralein Perdão, Sorry, I didn't know, thanks for the info
