### ISSUE TITLE
The CanvasItem shader reference mentions a non-existent DEPTH constant

### ISSUE THREAD

**Issue by robbertzzz** [godotengine/godot-docs#8541]
**Your Godot version:**
4.2 stable

**Issue description:**
The documentation for CanvasItem shaders contains the following sentence twice: "`xy` specifies position in window, `z` specifies fragment depth if `DEPTH` is not used". However, this `DEPTH` constant does not exist. Both occurences are in the description of `FRAGCOORD` for the fragment shader and light shader respectively.

**URL to the documentation page:**
https://docs.godotengine.org/en/stable/tutorials/shaders/shader_reference/canvas_item_shader.html

**Comment by AThousandShips** [comment]
Probably a copy/paste error from the spatial shader

**Comment by clayjohn** [comment]
Ya the mention of DEPTH can just be removed

**Comment by robbertzzz** [comment]
Most likely related, I don't think FRAGCOORD.z contains any useful values in 2D either. I'd propose removing everything after the comma in my quote.
