### ISSUE TITLE
Your first 2D game shortcut instructions

### ISSUE THREAD

**Issue by llagerlof** [godotengine/godot-docs#8542]
**Your Godot version:**

v4.1.1.stable.official [bd6af8e0e]

**Issue description:**

I finished the full tutorial. In the last part it shows how to add a shortcut to start the game pressing the ENTER key. I followed the instructions very carefully a few times, but I couldn't get it to work at all. It seems like something is missing from the explanation, but I am not sure.

**URL to the documentation page (if already existing):**

https://docs.godotengine.org/en/stable/getting_started/first_2d_game/07.finishing-up.html#keyboard-shortcut

**Comment by AThousandShips** [comment]
You missed the instructions then, it says "in the project settings" right there 🙂
