### ISSUE TITLE
In the shader materials docs, the jargon "uniform" needs to be specified

### ISSUE THREAD

**Issue by Johnrobmiller** [godotengine/godot-docs#8546]
**Your Godot version:**
4.2

**Issue description:**
In the shader material docs, the jargon "uniform" is present all throughout the page. It is wrong to assume the reader knows what this word means. Users who are unfamiliar with this jargon are likely to be confused by the word, as it is a common word in English and it is not obvious that it is jargon that requires googling.

Do not fix this by defining the jargon at the top of the page, as users do not read documentation from top to bottom. Instead, in every instance where "uniform" is used, it should link to a page that explains what this jargon means.

In general, it might be worth spending a day going through the entire documentation and doing this on every page, providing helpful links where appropriate.

**URL to the documentation page (if already existing):**
https://docs.godotengine.org/en/4.2/classes/class_shadermaterial.html

**Comment by AThousandShips** [comment]
Is [this](https://docs.godotengine.org/en/4.2/tutorials/shaders/shader_reference/shading_language.html#uniforms) not sufficient? I'd argue this page is something you are expected to read if you want to learn about shaders

**Comment by skyace65** [comment]
Closing per AThousandShips comment.
