### ISSUE TITLE
Add example for device that supports InputEventJoypadButton's pressure property

### ISSUE THREAD

**Issue by stephanbogner** [godotengine/godot-docs#8549]
### **Your Godot version:**
Not relevant

### **Context**
In my game I want to support as many controllers as possible so I want to know what I have to look out for / test with. 

### **Issue description:**
The docs for **InputEventJoypadButton**  > **pressure** states `Represents the pressure the user puts on the button with their finger, if the controller supports it.`
I have never heard of a button that also detects pressure (which is not a trigger). A note on which device / types of devices this exists would be helpful.

Maybe this is supported by less-common devices like fancy midi-keyboards / drawing tablets? 🤔

### **PR**
I am happy to phrase the sentence and open a PR once I know what devices/buttons this refers to.

### **URL to the documentation page (if already existing):**
https://docs.godotengine.org/en/stable/classes/class_inputeventjoypadbutton.html#class-inputeventjoypadbutton-property-pressure

**Comment by Mickeon** [comment]
> I have never heard of a button that also detects pressure (which is not a trigger). A note on which device / types of devices this exists would be helpful.

It's not novel. Most of the buttons on the Playstation 2 & 3's controller are pressure-sensitive, but it was relegated back to only the back triggers because the feature was fairly underutilised. Unfortunately, I do not have those controllers to test them, but this is is what they are referring to.

**Comment by stephanbogner** [comment]
@Mickeon Oh wow! I even had a ps3 and can't remember any game utilizing it.

I still have it at my parent's place. If it still works I am gonna try it out and make a PR (so even younger generations know what this refers to 😅).

Thanks for giving an example.

**Comment by stephanbogner** [comment]
This was much harder to check then I expected.

**On Mac:**
- I couldn't get the PS3 controller to work

**On Windows:**
1. I could get the PS3 controller (Sony Dualshock 3) to work through [**DsHidMini x64**](https://github.com/nefarius/DsHidMini) ([driver chart](https://www.pcgamingwiki.com/wiki/Controller:DualShock_3#Use_with_PC_platforms) which shows support for pressure sensitive buttons)
2. I then used the [**HID device mode `SXS`**](https://docs.nefarius.at/projects/DsHidMini/HID-Device-Modes-Explained/#sxs) which supports pressure sensitive buttons
3. I installed the Playstation 3 emulator [**RPCS3**](https://rpcs3.net/) and used the [**"GamePad Test homebrew"**](https://wiki.rpcs3.net/index.php?title=Help:Controller_Configuration) to verify that pressure sensitive buttons are working properly
4. Unfortunately Godot still shows `pressure=0.00` 😔 ... so I am not if it's a Godot bug or some driver issue

**PS:** I found [an interesting video](https://youtu.be/t48-FhXNmSo?si=ZRuMLFQ5_OP7YdWF&t=537) about "The Short History of Pressure Sensitive Buttons" with a great example about Metal Gear Solid utilizing it.

**Comment by stephanbogner** [comment]
However we could still update the docs with something like:
> Ranges from `0.0` to `1.0`. Represents the pressure the user puts on the button with their finger (if the controller supports it). Nowadays not a common feature but present on gamepads such as the Sony Dualshock 2 & 3 or original Xbox controller.

**Comment by Mickeon** [comment]
I asked on [RocketChat](https://chat.godotengine.org/channel/input?msg=FocEcfhFDrqgxAvxd) about this and it's pretty amusing to me.

In a nutshell, this property has existed ever since Godot became open source. But as it turns out, it was never implemented at all. Joypad drivers do not use it. It should not exist at all. It probably went completely unnoticed for how obscure this feature is. Requesting this feature nowadays would probably be a good proposal. But the description **absolutely** needs to change now.

**Comment by stephanbogner** [comment]
@Mickeon 
Haha, that is funny indeed.

It was an interesting rabbit hole though. Now I am actually kinda sad, that that feature is gone from the gaming world basically forever (not because of Godot but because of controllers not having it anymore).

Thanks for asking around.
