### ISSUE TITLE
No instructions on how to include a GDExtension for an iOS target

### ISSUE THREAD

**Issue by rshouker** [godotengine/godot-docs#8550]
**Your Godot version:**
4.2
**Issue description:**
Missing are instructions for adding a GDExtension to the app.
**URL to the documentation page (if already existing):**
https://docs.godotengine.org/en/4.2/tutorials/export/exporting_for_ios.html

**Comment by adaliszk** [comment]
Not an instruction, but an example can be found here: https://github.com/godotengine/godot-cpp/tree/master/test
