### ISSUE TITLE
Godot 4 doesn't show properly

### ISSUE THREAD

**Issue by JavRogu** [godotengine/godot-docs#8562]
Godot_v4.2-stable_win64

I have this problem with the last godot version 4.2, at the moment I start de program it doesn't show properly, it has a kind of flickering bug, where wherever I over with the mouse it starts the flickering, apparently the options are there, but the interface is not shown properly, this happens to me only on the godot 4 versions, I've been using the 3.5.3 stable version and it works perfectly

https://youtu.be/VTGknO_ML-o

**Comment by AThousandShips** [comment]
This is for bugs in the documentation, please open an issue [here](https://github.com/godotengine/godot/issues) instead, make sure to fill out everything
