### ISSUE TITLE
"Creating Instances" example project (instancing_starter.zip) crashes Godot upon opening.

### ISSUE THREAD

**Issue by Pratanjali64** [godotengine/godot-docs#8565]
**Your Godot version:** 4.0.2

**Issue description:** "Creating Instances" example project (instancing_starter.zip) crashes Godot upon importing or opening.

**URL to the documentation page:** https://docs.godotengine.org/en/stable/getting_started/step_by_step/instancing.html

I downloaded the example project and extracted it to my Godot folder. I went through the import dialog, and as soon as Godot attempted to open the project it crashed with no specific error number given in the Windows dialogue. Upon re-launching Godot, the instancing_starter project now shows up on the Project Manager launch window; opening it causes the crash again. 

I am still able to open and run Godot just fine as long as it's not this specific project. I tried redoing the zip file extraction in case I did anything funny... nope, still crashing.

**Comment by drepetto** [comment]
I'm getting the same error with Godot 4.2. Here's the --verbose output.


Godot Engine v4.2.1.stable.official.b09f793f5 - https://godotengine.org
TextServer: Added interface "Dummy"
TextServer: Added interface "ICU / HarfBuzz / Graphite (Built-in)"
[mvk-info] MoltenVK version 1.2.0, supporting Vulkan version 1.2.231.
	The following 83 Vulkan extensions are supported:
		VK_KHR_16bit_storage v1
		VK_KHR_8bit_storage v1
		VK_KHR_bind_memory2 v1
		VK_KHR_buffer_device_address v1
		VK_KHR_create_renderpass2 v1
		VK_KHR_dedicated_allocation v3
		VK_KHR_depth_stencil_resolve v1
		VK_KHR_descriptor_update_template v1
		VK_KHR_device_group v4
		VK_KHR_device_group_creation v1
		VK_KHR_driver_properties v1
		VK_KHR_dynamic_rendering v1
		VK_KHR_external_fence v1
		VK_KHR_external_fence_capabilities v1
		VK_KHR_external_memory v1
		VK_KHR_external_memory_capabilities v1
		VK_KHR_external_semaphore v1
		VK_KHR_external_semaphore_capabilities v1
		VK_KHR_fragment_shader_barycentric v1
		VK_KHR_get_memory_requirements2 v1
		VK_KHR_get_physical_device_properties2 v2
		VK_KHR_get_surface_capabilities2 v1
		VK_KHR_imageless_framebuffer v1
		VK_KHR_image_format_list v1
		VK_KHR_maintenance1 v2
		VK_KHR_maintenance2 v1
		VK_KHR_maintenance3 v1
		VK_KHR_multiview v1
		VK_KHR_portability_subset v1
		VK_KHR_push_descriptor v2
		VK_KHR_relaxed_block_layout v1
		VK_KHR_sampler_mirror_clamp_to_edge v3
		VK_KHR_sampler_ycbcr_conversion v14
		VK_KHR_separate_depth_stencil_layouts v1
		VK_KHR_shader_draw_parameters v1
		VK_KHR_shader_float_controls v4
		VK_KHR_shader_float16_int8 v1
		VK_KHR_shader_subgroup_extended_types v1
		VK_KHR_spirv_1_4 v1
		VK_KHR_storage_buffer_storage_class v1
		VK_KHR_surface v25
		VK_KHR_swapchain v70
		VK_KHR_swapchain_mutable_format v1
		VK_KHR_timeline_semaphore v2
		VK_KHR_uniform_buffer_standard_layout v1
		VK_KHR_variable_pointers v1
		VK_EXT_buffer_device_address v2
		VK_EXT_debug_marker v4
		VK_EXT_debug_report v10
		VK_EXT_debug_utils v2
		VK_EXT_descriptor_indexing v2
		VK_EXT_fragment_shader_interlock v1
		VK_EXT_hdr_metadata v2
		VK_EXT_host_query_reset v1
		VK_EXT_image_robustness v1
		VK_EXT_inline_uniform_block v1
		VK_EXT_memory_budget v1
		VK_EXT_metal_objects v1
		VK_EXT_metal_surface v1
		VK_EXT_post_depth_coverage v1
		VK_EXT_private_data v1
		VK_EXT_robustness2 v1
		VK_EXT_sample_locations v1
		VK_EXT_scalar_block_layout v1
		VK_EXT_separate_stencil_usage v1
		VK_EXT_shader_stencil_export v1
		VK_EXT_shader_viewport_index_layer v1
		VK_EXT_subgroup_size_control v2
		VK_EXT_swapchain_colorspace v4
		VK_EXT_texel_buffer_alignment v1
		VK_EXT_texture_compression_astc_hdr v1
		VK_EXT_vertex_attribute_divisor v3
		VK_AMD_gpu_shader_half_float v2
		VK_AMD_negative_viewport_height v1
		VK_AMD_shader_image_load_store_lod v1
		VK_AMD_shader_trinary_minmax v1
		VK_IMG_format_pvrtc v1
		VK_INTEL_shader_integer_functions2 v1
		VK_GOOGLE_display_timing v1
		VK_MVK_macos_surface v3
		VK_MVK_moltenvk v36
		VK_NV_fragment_shader_barycentric v1
		VK_NV_glsl_shader v1
[mvk-info] GPU device:
		model: Intel Iris Graphics
		type: Integrated
		vendorID: 0x8086
		deviceID: 0x0a2e
		pipelineCacheUUID: 000027D8-0C07-07D1-0000-000000000000
	supports the following Metal Versions, GPU's and Feature Sets:
		Metal Shading Language 2.4
		GPU Family Mac 1
		GPU Family Common 2
		GPU Family Common 1
		macOS GPU Family 1 v4
		macOS GPU Family 1 v3
		macOS GPU Family 1 v2
		macOS GPU Family 1 v1
[mvk-info] Created VkInstance for Vulkan version 1.2.0, as requested by app, with the following 4 Vulkan extensions enabled:
		VK_KHR_get_physical_device_properties2 v2
		VK_KHR_surface v25
		VK_EXT_debug_utils v2
		VK_MVK_macos_surface v3
Vulkan devices:
  #0: Intel Intel Iris Graphics - Supported, Integrated
Vulkan API 1.2.231 - Forward+ - Using Vulkan Device #0: Intel - Intel Iris Graphics
Optional extension VK_KHR_fragment_shading_rate not found
Optional extension VK_EXT_pipeline_creation_cache_control not found
Optional extension VK_KHR_incremental_present not found
- Vulkan Variable Rate Shading not supported
- Vulkan multiview supported:
  max view count: 32
  max instances: 134217727
- Vulkan subgroup:
  size: 1
  min size: 1
  max size: 1
  stages: STAGE_TESSELLATION_CONTROL, STAGE_FRAGMENT, STAGE_COMPUTE
  supported ops: FEATURE_BASIC
[mvk-info] Vulkan semaphores using MTLEvent.
[mvk-info] Created VkDevice to run on GPU Intel Iris Graphics with the following 10 Vulkan extensions enabled:
		VK_KHR_16bit_storage v1
		VK_KHR_create_renderpass2 v1
		VK_KHR_image_format_list v1
		VK_KHR_maintenance2 v1
		VK_KHR_multiview v1
		VK_KHR_shader_float16_int8 v1
		VK_KHR_storage_buffer_storage_class v1
		VK_KHR_swapchain v70
		VK_EXT_subgroup_size_control v2
		VK_GOOGLE_display_timing v1
[mvk-info] Created 3 swapchain images with initial size (1152, 648) and contents scale 1.0 for screen MPLE27QPM-R2.
[mvk-info] Created 3 swapchain images with initial size (1152, 648) and contents scale 1.0 for screen MPLE27QPM-R2.
[mvk-info] Created 3 swapchain images with initial size (2560, 1387) and contents scale 1.0 for screen MPLE27QPM-R2.
[mvk-info] Created 3 swapchain images with initial size (2560, 1387) and contents scale 1.0 for screen MPLE27QPM-R2.
Startup PSO cache (0.0 MiB)
Using "default" pen tablet driver...
Creating VMA small objects pool for memory type index 0
Shader 'CanvasSdfShaderRD' (group 0) SHA256: 7363db310d3bafccb1c5f260ae9dfca256ddbca71153e81ccde39dcb47c199d9
Shader 'SkeletonShaderRD' (group 0) SHA256: bf7f301f64d58662af62ef943aca73f928324bb25926d9a409e86e7fb3fbc67c
Shader 'SortShaderRD' (group 0) SHA256: 53267a8e27ca0d1a899f3663f314e175ccf1275cf3fc4075dc8d852b7e35cb45
Shader 'ParticlesShaderRD' (group 0) SHA256: 40c5be32072d4b56e3aa02da4237e940bf87bf8d75c77c966812e7f546b5a2a0
Shader 'ParticlesCopyShaderRD' (group 0) SHA256: ef2d7f3f1d745c52cf0e114bd3adc74c9f7c3b44893bd8cff0b84795e720e70c
Shader 'CanvasShaderRD' (group 0) SHA256: 9f552e967160fdaa1a2c9366aa5e3f11fbb53993fe64c21c6ab7d0f53b611b8c
Shader 'CanvasOcclusionShaderRD' (group 0) SHA256: d669644deecd99822dccb0a29d25eb44028758c0e28c458af9bad6052a3819ff
Shader 'ClusterRenderShaderRD' (group 0) SHA256: 8e2c77a0db6e6540c1825fa79d2464a3404ecf30351efabbec88f6cdfe5802dd
Shader 'ClusterStoreShaderRD' (group 0) SHA256: 54afde63e18582979ee28cf6b4d7a2a3667ed5c995ace119e02d767d4edcd92a
Shader 'ClusterDebugShaderRD' (group 0) SHA256: f1ceb1745188d432e023fa6a1264c75f05786cd330176ee0d6d9a8478286e9d7
Shader 'SceneForwardClusteredShaderRD' (group 0) SHA256: 204f2649ce2da33579d1b22df1e17eae733132339dec055437e4008e42a925de
Shader 'SceneForwardClusteredShaderRD' (group 1) SHA256: 8348eafc62719c14f00a44059805e51d15ee3cb1ef7e019a3d4a9dc06d4e2094
Shader 'SceneForwardClusteredShaderRD' (group 2) SHA256: dd99067bcab910892f9781092f15ce898dd0cf49697407ddec6e1900cc9a4896
Shader 'SceneForwardClusteredShaderRD' (group 3) SHA256: 42168a32320f067b64bf6716ace7265aacb03e2694916a4199cf9b4d06b2f446
Shader 'ResolveShaderRD' (group 0) SHA256: 26fe22b09fe40349608463a67af945132283b4d8ed404e4ee7cbb9831e524ded
Shader 'TaaResolveShaderRD' (group 0) SHA256: 6cbf62c3767cb0dd6f24c568fc9e1a35364490bd74a609aeff2779462afc6ab1
Shader 'Fsr2DepthClipPassShaderRD' (group 0) SHA256: ba9b970ca67a951837bf5d602307855dde113a66de894cadf12bc0598f07eb90
Shader 'Fsr2ReconstructPreviousDepthPassShaderRD' (group 0) SHA256: 744cf192a72eac0a1672802d297b54d8cc3f4ab2f2555c24ddbf2b7354f1a218
Shader 'Fsr2LockPassShaderRD' (group 0) SHA256: 7f8bbe7926ff73baf908e4090a7a29d4db67e6e59c398bd22bc04c3f342897fe
Shader 'Fsr2AccumulatePassShaderRD' (group 0) SHA256: 85520c8b596685a63280159e8b61c4347e2bb4463ec3fa7a8c2fab67c657f565
Shader 'Fsr2RcasPassShaderRD' (group 0) SHA256: 51e0c8c32d118f854f0fbddd13b8f5e08c07d764cf263019d338df07433e30d2
Shader 'Fsr2ComputeLuminancePyramidPassShaderRD' (group 0) SHA256: af79172b196f50d03bfa46824dbdc929defd4891fd6ba321bef9a2d0a8cec0ac
Shader 'Fsr2AutogenReactivePassShaderRD' (group 0) SHA256: 5b7c50a9ece890d56f18713b5c72f7c967ee58bbdef186152dabf89e5525a1eb
Shader 'Fsr2TcrAutogenPassShaderRD' (group 0) SHA256: c11410a013e2692e17bb438a914f11d07c10460969c2bb63c5e1c3ccf0603a29
Shader 'SsEffectsDownsampleShaderRD' (group 0) SHA256: 82810ebc9a848bb6279789382f4ce5ec2aee98e2719a9e5e93008b922f615c93
Shader 'SsilShaderRD' (group 0) SHA256: 7ef9c39b12ffe15570beba9df6355cfac3e692c98468d63f56b7b7c79e2d67eb
Shader 'SsilImportanceMapShaderRD' (group 0) SHA256: facf29855562817dc424e05d4c6c72e113445b294d64896fb75f99a2a8b68544
Shader 'SsilBlurShaderRD' (group 0) SHA256: e27f5ff76dbb600c9061bc4d11ea3f08b00e5db9f24be50f94b2ff0e3984d043
Shader 'SsilInterleaveShaderRD' (group 0) SHA256: 3836a9dff7e7168cda4b5146b90466fea880a08a7cc5a95d487048a4a00b4e30
Shader 'SsaoShaderRD' (group 0) SHA256: 7cf308d5a539bc4c34a7eb804e4312a63fe3fb8a92faaf927614cab54c243803
Shader 'SsaoImportanceMapShaderRD' (group 0) SHA256: 882741065bbcd64113471d4631ea9674f1e280009d6cf325c2a15ee2e7ed28ac
Shader 'SsaoBlurShaderRD' (group 0) SHA256: afc3b6a671bcda5508ff834590e3b42a3aba6fa7ba5db588dfe669e526688ef3
Shader 'SsaoInterleaveShaderRD' (group 0) SHA256: c9fbdc04026c98b427c41cbdfed61da2b9252548c1389f39c9936e4502e06119
Shader 'ScreenSpaceReflectionScaleShaderRD' (group 0) SHA256: 35c09127a4befacec94948941d39ca6c222e7236b3fa397885df511b70d4f421
Shader 'ScreenSpaceReflectionShaderRD' (group 0) SHA256: 25be9ced020f2987f1c0a71fb1572126d5942972ccd083c08bae7402fe9cede6
Shader 'ScreenSpaceReflectionFilterShaderRD' (group 0) SHA256: 95538a7e2900ba8feee836e534882e2f3f312d914f5d6ae8111e67afba1614cd
Shader 'SubsurfaceScatteringShaderRD' (group 0) SHA256: 3369947dd6d9127bba99a0d4b5c0b4e85b6d667c93570fa526ec9b41c589f6d0
Shader 'SkyShaderRD' (group 0) SHA256: b9a0e01d047c01347f5b25e124e9c75b07cb5c6a1fa6191fc57d96a7a47ec71a
Shader 'VoxelGiShaderRD' (group 0) SHA256: aa49afc02f0e411a5c7ba8c4f6b83c9e1d52ba31c3a71bcbe81ec6c45da2d341
Shader 'VoxelGiDebugShaderRD' (group 0) SHA256: 7b9441206f7ff999f5fa6caf48f6ba4e38537129ecfa7a20ab0c5556f71ed798
Shader 'SdfgiPreprocessShaderRD' (group 0) SHA256: 06e18b2deb9c4f98945d75fc613c1e0b2f3b921ce73189e64287ec464a5d1780
Shader 'SdfgiDirectLightShaderRD' (group 0) SHA256: f832cbbdaf41be54cbbc2aaf123cc4be43000d38407f0e79f4e2e8c8eb217fb9
Shader 'SdfgiIntegrateShaderRD' (group 0) SHA256: 9a81cf5a9aceb0366a22b74b84d18f0121517df03c4ea562b924bece4160c996
Shader 'GiShaderRD' (group 0) SHA256: 222cd576a86e78916de126b52537f34c0f644edd83eddf18ace8d569c5024eb6
Shader 'SdfgiDebugShaderRD' (group 0) SHA256: 02acbbf83535feb0981af4ea73d7a9cd23d5d14f61219ecfa7f3b1974553f072
Shader 'SdfgiDebugProbesShaderRD' (group 0) SHA256: 306fc8dbacffdce26e13a833e928f6037c6908548d9f3a96f300e0a4938a1bbd
Shader 'VolumetricFogShaderRD' (group 0) SHA256: f69763b6a898538fd746e2eb3489b3a3d02a540445deb03351eace52d8805683
Shader 'VolumetricFogProcessShaderRD' (group 0) SHA256: 98a12e395f02bfadc0c3b9cd53d9c85154ab037efcc4671db378239006f4370f
Shader 'BokehDofShaderRD' (group 0) SHA256: 46c9d308284cb31dbc44209c009b088c0b2f93f2a4e298f0e4166cd655810c00
Shader 'CopyShaderRD' (group 0) SHA256: b36ab674370d511f5d3dc7a9cc4aca59b7082ad480b63bcbe8ab4aea248d22f4
Shader 'CopyToFbShaderRD' (group 0) SHA256: 5f700d78ad6a760f4f5e1880bf72dd92a87f435847dc113f06af13c308936a65
Shader 'CubeToDpShaderRD' (group 0) SHA256: 757273f39733a4e00376d099ec8a6c552ae9d33e17e1aa7211495d224e65c5b0
Shader 'CubemapDownsamplerShaderRD' (group 0) SHA256: 3ef91e22737b9228c098b3c9d02d75bc2ac9e4c4129ec9a29ca1ad3f9b18775b
Shader 'CubemapFilterShaderRD' (group 0) SHA256: 6e20eac8c44f08a744e6cd76a725c452c8a232e73a7b72ab9c82a459c6a78349
Shader 'CubemapRoughnessShaderRD' (group 0) SHA256: 2a8d1595a04e062030fb8fc03619f52d6d558b0a734a5ae228bac68a4aa2a636
Shader 'SpecularMergeShaderRD' (group 0) SHA256: 9dd7a6500aa9440e1574cd4b1588212cf785fd0488c96fed28bd2aa12969c2e7
Shader 'ShadowFrustumShaderRD' (group 0) SHA256: 988733f9d65542f905d1d650ef681c9c7f1e5ecba4a68becafb4cd8c356206e8
Shader 'MotionVectorsShaderRD' (group 0) SHA256: e355eda87f3a1bc1b94959927815b3f2db9253431c669f05137c02950611a7a3
Shader 'LuminanceReduceShaderRD' (group 0) SHA256: 9e10a2d8289eebf56596974ee5dcde52088152cb02858a4e3e6df4005338242a
Shader 'TonemapShaderRD' (group 0) SHA256: afd00b08c62c507857cb29b599f31e8db76eedabe53710b27ef47a95efe4290b
Shader 'FsrUpscaleShaderRD' (group 0) SHA256: 28b13ee2e211714e98def7d1de9bf7a6f2deeb6648b3f7fbe351f09da483ba55
Shader 'BlitShaderRD' (group 0) SHA256: 387815607b0d46994802ea276694bd6de44f72c603623c7569baa6cef78d6e13
CoreAudio: detected 2 channels
CoreAudio: audio buffer frames: 512 calculated latency: 11ms
 
TextServer: Primary interface set to: "ICU / HarfBuzz / Graphite (Built-in)".
CameraServer: Registered camera FaceTime HD Camera (Display) with ID 1 and position 0 at index 0
CORE API HASH: 915626997
EDITOR API HASH: 1313472085
EditorSettings: Load OK!
WARNING: Blend file import is enabled in the project settings, but no Blender path is configured in the editor settings. Blend files will not be imported.
     at: _editor_init (modules/gltf/register_types.cpp:63)
[mvk-info] Created 3 swapchain images with initial size (2560, 1387) and contents scale 1.0 for screen MPLE27QPM-R2.
[mvk-info] Created 3 swapchain images with initial size (2560, 1387) and contents scale 1.0 for screen MPLE27QPM-R2.
[mvk-info] Created 3 swapchain images with initial size (2560, 1359) and contents scale 1.0 for screen MPLE27QPM-R2.
[mvk-info] Created 3 swapchain images with initial size (2560, 1415) and contents scale 1.0 for screen MPLE27QPM-R2.
Loaded system CA certificates
Creating VMA small objects pool for memory type index 1

================================================================
handle_crash: Program crashed with signal 11
Engine version: Godot Engine v4.2.1.stable.official (b09f793f564a6c95dc76acc654b390e68441bd01)
Dumping the backtrace. Please include this when reporting the bug to the project developer.
[1] 1   libsystem_platform.dylib            0x00007ff812febdfd _sigtramp + 29
[2] 2   ???                                 0x00007fa3bcd13140 0x0 + 140341224223040
[3] void rx::mtl::GetMatrixUniformMetal<unsigned int>(unsigned int, unsigned int*, unsigned int const*, bool)
[4] void rx::mtl::GetMatrixUniformMetal<unsigned int>(unsigned int, unsigned int*, unsigned int const*, bool)
[5] void rx::mtl::GetMatrixUniformMetal<unsigned int>(unsigned int, unsigned int*, unsigned int const*, bool)
[6] Ref<DirAccess> DirAccess::_create_builtin<DirAccessUnix>()
[7] Ref<DirAccess> DirAccess::_create_builtin<DirAccessUnix>()
[8] Ref<DirAccess> DirAccess::_create_builtin<DirAccessUnix>()
[9] RenderSceneBuffersRD::get_use_taa() const
[10] RendererSceneCull::Instance::dependency_deleted(RID const&, DependencyTracker*)
[11] Gradient::get_color_at_offset(float)
[12] Ref<DirAccess> DirAccess::_create_builtin<DirAccessMacOS>()
[13] ItemList::get_v_scroll_bar()
[14] ItemList::get_v_scroll_bar()
[15] ItemList::get_v_scroll_bar()
[16] CallableCustomExtension::default_compare_less(CallableCustom const*, CallableCustom const*)
[17] CanvasItem::get_canvas_item() const
[18] ItemList::get_v_scroll_bar()
[19] CallableCustomExtension::default_compare_less(CallableCustom const*, CallableCustom const*)
[20] Node::get_tree() const
[21] Node::get_tree() const
[22] Node::get_tree() const
[23] Node::get_tree() const
[24] Node::get_tree() const
[25] Node::get_tree() const
[26] Node::get_index(bool) const
[27] void rx::mtl::GetMatrixUniformMetal<unsigned int>(unsigned int, unsigned int*, unsigned int const*, bool)
[28] RendererCompositorRD::_create_current()
[29] 29  dyld                                0x000000011b33952e start + 462
-- END OF BACKTRACE --
================================================================
zsh: abort      /Applications/Godot.app/Contents/MacOS/Godot --verbose

**Comment by drepetto** [comment]
In case anyone else runs into this, you can get around it by making a new project then just copying over all the files (except project.godot) into the new project's directory. All of the nodes should show up in the new project and you can proceed with the tutorial.

**Comment by skyace65** [comment]
Like Piralein I'm able to open this project without any issues, and I'm using 4.2. It looks like this is an engine bug, not a documentation bug. I'd recommend opening an issue in the engine repository [here](https://github.com/godotengine/godot/issues).
