### ISSUE TITLE
Maybe Update for documentation, but unsure if I made a mistake. but following worked for me.

### ISSUE THREAD

**Issue by IceKowedd** [godotengine/godot-docs#8571]
**Your Godot version: 4.1**

Issue description:

I'm new to godot engine, just started today, and wanted to create a button and followed documentation.

And I encountered my first problem directly. couldn't get button to work properly printing text when pressed.

Documentation said:
```
func _ready():
	var button = Button.new()
	button.text = "Click me"
	button.pressed.connect(self._button_pressed)
	add_child(button)

func _button_pressed():
	print("Hello world!")
```
Though this only worked for me:

```
func _on_button_pressed():
	print("Hello world!")
```

**URL to the documentation page: https://docs.godotengine.org/en/stable/classes/class_button.html**

**Comment by IceKowedd** [comment]
> Did you copy the code exactly? You might have incorrectly written `button.pressed.connect(self._button_pressed())`
> 
> The code is valid, and it's likely you did something wrong in your code

Yes I copied the whole code. 

I had a button but it didn't print anything.

It did print with this:

func _on_button_pressed():
	print("Hello world!")
	
	
	but also found out you can connect a button with signals.
	
	Like I said kinda new, but thought I should better report it and I learn from it. 
	
	But fixed it in the wrong way it seems XD

**Comment by AThousandShips** [comment]
You Re connected with signals, just not from the editor, which you probably did with the other case, the code in question does work correctly

Did you change it to:
```gdscript
func _ready():
	var button = Button.new()
	button.text = "Click me"
	button.pressed.connect(self._on_button_pressed)
	add_child(button)

func _on_button_pressed():
	print("Hello world!")
```

**Comment by AThousandShips** [comment]
Closing due to lack of response, this is not a bug and things work as the documentation states
