### ISSUE TITLE
Incorrect instructions to call node during 2D tutorial

### ISSUE THREAD

**Issue by patchclark** [godotengine/godot-docs#8575]
v4.2.stable.official [46dc27791]

In the documentation for the Dodge the Creeps 2D tutorial _[Your first 2D game > Contents > The main game scene > Main script]_ the instructions for calling the 2DPAthFollow Node _"MobPath/MobSpawnLocation"_ shows the older _"get_node"_ method. I was stuck on this for 30 mins, because it wouldn't autofill the _"progress.ratio"_ attribute. 

After staring at the same lines over and over, I eventually remembered that **the dollar sign would call the function correctly.** I know this is somewhat low priority, but for a newbie to both code and the game engine, it would be nice to know that this could get fixed for other new folks. 
Screenshots of the incorrect/correct code.

![Godot 4 2 - get_node issue](https://github.com/godotengine/godot-docs/assets/130708382/7431c1f3-e0b0-4f4e-b45f-15b7b63c629b)

(https://docs.godotengine.org/en/4.2/getting_started/first_2d_game/05.the_main_game_scene.html)

(P.S. this stuff below is all super helpful, as I get used to the tool, I'll be sure to try a more bootstrap approach to any issues I see! Thank you so much!)
If you know how to fix the issue you are reporting please
consider opening a pull request. We provide a tutorial on
using git here: https://docs.godotengine.org/en/stable/community/contributing/pr_workflow.html,
writing documentation at https://docs.godotengine.org/en/stable/community/contributing/docs_writing_guidelines.html
and contributing to the class reference here: https://docs.godotengine.org/en/stable/community/contributing/updating_the_class_reference.html

**Comment by AirTechWick** [comment]
Hello,
I'd like to fix and work on this issue.

**Comment by mhilbrunner** [comment]
Fixed in https://github.com/godotengine/godot-docs/pull/8705. Thanks for the report! 🙏
