### ISSUE TITLE
Wrong recommended Emscripten version for compiling web

### ISSUE THREAD

**Issue by 0MirageTank0** [godotengine/godot-docs#8589]
**Your Godot version:**
Godot 4.2
**Issue description:**
The recommended version in the document is Emscripten 1.39.9+,which will cause compilation errors. Too newer version will cause a LTO error, but an older version (Within the recommended version range) will cause a GL_WORKAROUND_SAFARI_GETCONTEXT_BUG not found error.
![image](https://github.com/godotengine/godot-docs/assets/52967756/f76239ff-ff6f-41af-9b5c-9a6cda38541a)

**URL to the documentation page:**
https://docs.godotengine.org/en/latest/contributing/development/compiling/compiling_for_web.html

After my testing, Emscripten version 3.1.26 can perform compilation tasks correctly.

_Production edit: corrected LTO typo_

**Comment by AThousandShips** [comment]
Do you mean LTO error? Can't find anything about TLO error

**Comment by 0MirageTank0** [comment]
> Do you mean LTO error? Can't find anything about TLO error

Yes, I said it wrong, it should indeed be LTO

**Comment by AThousandShips** [comment]
Did you by any chance get the LTO issues with versions between 3.1.42 and 3.1.46? In that case see [here](https://github.com/emscripten-core/emscripten/issues/19781)
