### ISSUE TITLE
what is TILE_ANIMATION_MODE_RANDOM_START_TIMES 

### ISSUE THREAD

**Issue by skeddles** [godotengine/godot-docs#8595]
**Your Godot version:**
4.2
**Issue description:**

im trying to figure out how the new "random start times" feature works for timemaps, since it's behaving strangely for me. i tried to look on the docs to find an explination of how it works and it says this:

TILE_ANIMATION_MODE_RANDOM_START_TIMES -Tile animations start at random times, looking varied.

which doesnt really tell me anything. 

what does this actually do?

**URL to the documentation page (if already existing):**
https://docs.godotengine.org/en/stable/classes/class_tilesetatlassource.html#enumerations

**Comment by AThousandShips** [comment]
See also:
* https://github.com/godotengine/godot/pull/77257

CC @rakkarage

**Comment by rakkarage** [comment]
Instead of all instances starting at the exact same time (how it normally works);

![237779411-99e2ea62-2db5-4692-8c93-4dab776c8154](https://github.com/godotengine/godot-docs/assets/962340/2a444589-bc1d-4bc9-a66d-a39bb0519a78)

each instance (tile) of the animation has it's own random start time... is how it is meant to work.

![237779485-223a959e-8c7d-4a5c-bfab-0f89177ff6e4](https://github.com/godotengine/godot-docs/assets/962340/b17ae534-4ccc-4ea6-b48c-da216fc29575)

**Comment by skeddles** [comment]
okay, I see why mine doesn't work now. the problem is my tiles seem to all start within a second of each other, even though there's a frame with a long pause.

![Godot_v4 2-stable_mono_win64_2023-12-15_11-43-10](https://github.com/godotengine/godot-docs/assets/2721332/a2765f20-78a8-49b6-aef1-15e6cfacc4b2)

I have one frame with a big pause, then 3 really short frames. so they at most will be offset by the times of the 3 short frames, which is only 600ms. 

seems to me this property should be called "TILE_ANIMATION_MODE_RANDOM_START_TILES" not start times, which I took to meant it would start anywhere within the animation's 10.6s length, which I could have used. 

but at the very least, the docs should explain that this picks a random start TILE not a random start TIME.

**Comment by AThousandShips** [comment]
A more useful name might have been `_START_FRAMES` but this can't be changed now without breaking compatibility

**Comment by AThousandShips** [comment]
It does apply a random time offset so it isn't a matter of random frames though

**Comment by skeddles** [comment]
then why do all my tiles animations above start within 1 second of each other?

**Comment by AThousandShips** [comment]
Because the random offset is limited to one second? It's not a frame offset, this is a possible improvement but currently that's how it works

**Comment by kleonc** [comment]
> okay, I see why mine doesn't work now. the problem is my tiles seem to all start within a second of each other, even though there's a frame with a long pause.
> 
> ![Godot_v4 2-stable_mono_win64_2023-12-15_11-43-10](https://private-user-images.githubusercontent.com/2721332/290883977-a2765f20-78a8-49b6-aef1-15e6cfacc4b2.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDI2NjI1MTgsIm5iZiI6MTcwMjY2MjIxOCwicGF0aCI6Ii8yNzIxMzMyLzI5MDg4Mzk3Ny1hMjc2NWYyMC03OGE4LTQ5YjYtYWVmMS0xNWU2Y2ZhY2M0YjIuZ2lmP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQUlXTkpZQVg0Q1NWRUg1M0ElMkYyMDIzMTIxNSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyMzEyMTVUMTc0MzM4WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9OGYyMGYzMjlhY2JjNzc4ZDY1MGMzMjgxYWUwYmY0M2Y2MmEwOTYxMzQwNmNjNDc3ZGY0Njg5NzBhODIwZjk0YSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.9YOMfbiBrzIZ-1ogKkUP-SLFj4agy9uI3Lbp-S-rMuU) [ ![Godot_v4 2-stable_mono_win64_2023-12-15_11-43-10](https://private-user-images.githubusercontent.com/2721332/290883977-a2765f20-78a8-49b6-aef1-15e6cfacc4b2.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDI2NjI1MTgsIm5iZiI6MTcwMjY2MjIxOCwicGF0aCI6Ii8yNzIxMzMyLzI5MDg4Mzk3Ny1hMjc2NWYyMC03OGE4LTQ5YjYtYWVmMS0xNWU2Y2ZhY2M0YjIuZ2lmP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQUlXTkpZQVg0Q1NWRUg1M0ElMkYyMDIzMTIxNSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyMzEyMTVUMTc0MzM4WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9OGYyMGYzMjlhY2JjNzc4ZDY1MGMzMjgxYWUwYmY0M2Y2MmEwOTYxMzQwNmNjNDc3ZGY0Njg5NzBhODIwZjk0YSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.9YOMfbiBrzIZ-1ogKkUP-SLFj4agy9uI3Lbp-S-rMuU) ](https://private-user-images.githubusercontent.com/2721332/290883977-a2765f20-78a8-49b6-aef1-15e6cfacc4b2.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDI2NjI1MTgsIm5iZiI6MTcwMjY2MjIxOCwicGF0aCI6Ii8yNzIxMzMyLzI5MDg4Mzk3Ny1hMjc2NWYyMC03OGE4LTQ5YjYtYWVmMS0xNWU2Y2ZhY2M0YjIuZ2lmP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQUlXTkpZQVg0Q1NWRUg1M0ElMkYyMDIzMTIxNSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyMzEyMTVUMTc0MzM4WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9OGYyMGYzMjlhY2JjNzc4ZDY1MGMzMjgxYWUwYmY0M2Y2MmEwOTYxMzQwNmNjNDc3ZGY0Njg5NzBhODIwZjk0YSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.9YOMfbiBrzIZ-1ogKkUP-SLFj4agy9uI3Lbp-S-rMuU) [ ](https://private-user-images.githubusercontent.com/2721332/290883977-a2765f20-78a8-49b6-aef1-15e6cfacc4b2.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDI2NjI1MTgsIm5iZiI6MTcwMjY2MjIxOCwicGF0aCI6Ii8yNzIxMzMyLzI5MDg4Mzk3Ny1hMjc2NWYyMC03OGE4LTQ5YjYtYWVmMS0xNWU2Y2ZhY2M0YjIuZ2lmP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQUlXTkpZQVg0Q1NWRUg1M0ElMkYyMDIzMTIxNSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyMzEyMTVUMTc0MzM4WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9OGYyMGYzMjlhY2JjNzc4ZDY1MGMzMjgxYWUwYmY0M2Y2MmEwOTYxMzQwNmNjNDc3ZGY0Njg5NzBhODIwZjk0YSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.9YOMfbiBrzIZ-1ogKkUP-SLFj4agy9uI3Lbp-S-rMuU)
> 
> I have one frame with a big pause, then 3 really short frames. so they at most will be offset by the times of the 3 short frames, which is only 600ms.
> 
> seems to me this property should be called "TILE_ANIMATION_MODE_RANDOM_START_TILES" not start times, which I took to meant it would start anywhere within the animation's 10.6s length, which I could have used.
> 
> but at the very least, the docs should explain that this picks a random start TILE not a random start TIME.
> 
> unfortunately it seems this feature wont work for my game.

I've mentioned it should work timewise when it was being added (in https://github.com/godotengine/godot/pull/77257#discussion_r1199581275), to me the current behavior is absolutely a bug in the implementation. The [`random_animation_offset` passed to `draw_tile` method is in `0.0`..`1.0` range](https://github.com/godotengine/godot/blob/f8a2a9193662b2e8c1d04d65e647399dee94f31e/scene/2d/tile_map.cpp#L360-L369) and [it's used as is when passed to the RenderingServer](https://github.com/godotengine/godot/blob/f8a2a9193662b2e8c1d04d65e647399dee94f31e/scene/2d/tile_map.cpp#L3258) but it should be instead scaled according to the calculated duration of the animation. Seems we overlooked this while reviewing. This needs to be fixed.

**Comment by skeddles** [comment]
> Because the random offset is limited to one second? It's not a frame offset, this is a possible improvement but currently that's how it works
> 
> How would what I said be incompatible with that? And how would it be compatible with it being an offset of frames?

oh... that's a weird way to randomize them... 

I agree @kleonc that it seems like it should be based on the animation's length

**Comment by AThousandShips** [comment]
Except for the oversight how is it weird?

**Comment by dannflor** [comment]
As someone who has also run into this, it makes certain intermittent tile animations (like @skeddles above with the water waves) impossible to configure correctly. Limiting it to a second just doesn't consider the wide world of random offsets we might want that have a larger period.

**Comment by AThousandShips** [comment]
It's being fixed, see the issue linked above 🙂

**Comment by kleonc** [comment]
Once CI checks will finish in https://github.com/godotengine/godot/pull/86210 anyone feel free to test it by downloading the artifact ([how-to](https://docs.godotengine.org/en/4.2/contributing/workflow/testing_pull_requests.html#downloading-a-compiled-build)).

**Comment by dannflor** [comment]
@kleonc the way you currently have it the animation is sitting on the last frame while it waits for the offset to expire. Usually when you animate something, the FIRST frame is the point of rest. If you picture an animated character sprite, it would be like having him stop with his foot hovering over the ground. Or with the water, stopping with the ripple in the water.

**Comment by AThousandShips** [comment]
How do you mean it waits? It loops and doesn't hold on the end

**Comment by kleonc** [comment]
> @kleonc the way you currently have it the animation is sitting on the last frame while it waits for the offset to expire. Usually when you animate something, the FIRST frame is the point of rest. If you picture an animated character sprite, it would be like having him stop with his foot hovering over the ground. Or with the water, stopping with the ripple still in the water.


@dannflor What do you mean by "currently"? Some specific released version or https://github.com/godotengine/godot/pull/86210 or something else?
Also are you referring to some specific behavior you're experiencing in some specific use case / setup of yours?
Please be more specific.
(I also don't understand what do you mean by this "waiting".)

**Comment by dannflor** [comment]
Sorry for the confusion, I checked out the artifact but my tile timings were just misconfigured. I had the last frame extending for multiple seconds for some reason and thought that was because of your change. It's working perfectly 👍

**Comment by tetrapod00** [comment]
I'm going to close this, because it seems like the current documentation is adequate to describe the current behavior. IMO nothing more needs to be specified here:
>Tile animations start at random times, looking varied.

The linked PR, https://github.com/godotengine/godot/pull/86210, has also been merged, so I think this issue is resolved. If you disagree, feel free to leave a comment to reopen (ideally with a suggestion for a wording improvement).
