### ISSUE TITLE
GDScript - Iterating enum integers casts them to string

### ISSUE THREAD

**Issue by TheYellowArchitect** [godotengine/godot-docs#8598]
### Tested versions

Reproduced in 4.2 Stable. Probably exists earlier (if not the addition of static typing on iterations, it probably existed earlier)

### System information

Artix Linux

### Issue description

I have this class (it's not auto-loaded)
```gdscript
extends Node
class_name Constants

enum animation_states { IDLE = 0, ATTACK = 1, RUN = 2}
```

If with any other class, I input the following, it gives expected output (3)
`print(Constants.animation_states.ATTACK)`

### The Problem

The following outputs strings, not integers.
```gdscript
for picked_state in Constants.animation_states:
   print(picked_state)
```
Output:
```
IDLE
ATTACK
RUN
```

If I replace
```gdscript
enum animation_states { IDLE = 0, ATTACK = 1, RUN = 2}
```
with
```gdscript
const animation_states = { IDLE = 0, ATTACK = 1, RUN = 2}
```
the output is the same.

### Steps to reproduce

Create an enum, then iterate it.

### Minimal reproduction project (MRP)

[enum.zip](https://github.com/godotengine/godot/files/13627176/enum.zip)

**Comment by AThousandShips** [comment]
For anyone looking for add this, a simple note on the `enums` section about iteration, and an example for iterating over the values like I provided above, on either or both of those sections should be enough

**Comment by TheYellowArchitect** [comment]
I already added these as you recommended https://github.com/godotengine/godot-docs/pull/8599 :D
