### ISSUE TITLE
Setting up Visual Studio: SConstruct not found and not mentioned

### ISSUE THREAD

**Issue by dustin2711** [godotengine/godot-docs#8612]
**Godot version 4.2** 

**Issue description:**
Calling this in cmd from the Godot root folder

```scons platform=windows vsproj=yes dev_build=yes```

returns this error:

```
scons: *** No SConstruct file found.
File "C:\Users\...\AppData\Local\Programs\Python\Python312\Lib\site-packages\SCons\Script\Main.py", line 985, in _main
```

The documentation page does not state anything how to obtain the SConstruct file that is needed for scons. Should it be there by default? Do you need to generate it? The wiki should answer these questions.

**URL to the documentation page: https://docs.godotengine.org/en/stable/contributing/development/configuring_an_ide/visual_studio.html**

**Comment by AThousandShips** [comment]
The file is right there in the root directory of the repository, did you check it out correctly? Are you sure you ran it in the `godot/` folder?

**Comment by frtsprkls** [comment]
@AThousandShips comment should be in the documentation. If you download Godot from the website, you just get the .exe; there is no mention in the docs for needing a clone of the repo (deeply appreciate AThousandShips making this comment as I was losing my mind trying to figure out where the SConstruct file was).

**Comment by AThousandShips** [comment]
Not needing to clone the repo when? You mean it's not mentioned [here](https://docs.godotengine.org/en/stable/contributing/development/compiling/getting_source.html)?

**Comment by AThousandShips** [comment]
Closing due to lack of response from OP, the file is where the instructions say to go, and the documentation makes it clear that you need to clone the source

If you have some other details please comment and this can be reopened, otherwise there's nothing missing or wrong here

**Comment by akanieski** [comment]
I stumbled over the same thing.. no where in the doc does it say to clone godot.. it just references the "godot root folder" with no explanation on what that folder is, or that it needs to be cloned.

**Comment by hung-pt** [comment]
Well this seems to be referring to the development of the engine, not how to use Godot with Visual Studio.

**Comment by xanat0s** [comment]
> Not needing to clone the repo when? You mean it's not mentioned [here](https://docs.godotengine.org/en/stable/contributing/development/compiling/getting_source.html)?
> 
> Also it says clearly to go to the roof directory:
> 
> > Navigate to the Godot root folder and open a Command Prompt or PowerShell window.

That's in a completely unrelated section of the documentation, relating to building from source, not relating to integrating VS/Rider to use with Godot. Most folks, myself included, are downloading the Godot binaries directly from their website. 

I had to track this thread down to figure out what was going on and how to solve the problem. That's an issue.

**Comment by zwalden** [comment]
Yeah, you can find the document OP was referencing here: https://docs.godotengine.org/en/stable/contributing/development/configuring_an_ide/rider.html

Which may explain @AThousandShips's confusion.

**Comment by AThousandShips** [comment]
At the very top of the "Configuring an IDE" it says:
> We assume that you have already [cloned](https://github.com/godotengine/godot) and [compiled](https://docs.godotengine.org/en/stable/contributing/development/compiling/index.html#toc-devel-compiling) Godot.

So the instructions are clear that this is needed IMO, if you read the full documentation and not just the subsection, I think we shouldn't need to link to the "Configuring an IDE" category *from* each part, right?

**Comment by chrisphu** [comment]
Much like @akanieski, I'm relatively new to Godot and also just stumbled across this thread. My initial instinct wasn't to check the parent page; the left-hand side page tree suggests that it might just be a relatively empty container to organize the child pages that actually host the technical details related to their respective IDEs. If new folks keep saying they have trouble with this, then my gut feeling is that it could be made even more clear.

Maybe instead of:

Configuring an IDE
┣╸IDE 1
┗╸IDE 2

The page tree could instead be:

General IDE configuration
IDE specific configurations
┣╸IDE 1
┗╸IDE 2

And if that's overkill (there's really just that one important line in the parent page), maybe it _is_ worth it having that one important line copied at the top of each of the child pages. In any case, greatly appreciate @zwalden for pointing out the JetBrains documentation on this!
