### ISSUE TITLE
Return of GraphEdit.get_connection_list() seems to be not like what's described in documentation

### ISSUE THREAD

**Issue by ZeferinoI** [godotengine/godot-docs#8625]
**Godot version:** 
v4.2.stable.mono.official [46dc27791]

**Issue description:**
The documentation says that GraphEdit.get_connection_list() "Returns an Array containing the list of connections. A connection consists in a structure of the form { from_port: 0, **_from_**: "GraphNode name 0", to_port: 1, **_to_**: "GraphNode name 1" }." while the form should actually be like { from_port: 0, **_from_node_**: "GraphNode name 0", to_port: 1, **_to_node_**: "GraphNode name 1" } when I print a dictionary in the array.

**URL to the documentation page:**
https://docs.godotengine.org/en/stable/classes/class_graphedit.html#class-graphedit-method-get-connection-list

**Comment by YuriSizov** [comment]
Yes, this was changed recently during the node's rework. Feel free to open a PR [against the main repository](https://github.com/godotengine/godot/blob/master/doc/classes/GraphEdit.xml) to update the docs.
