### ISSUE TITLE
"Hit" (Your First 2D Game)

### ISSUE THREAD

**Issue by planariangames** [godotengine/godot-docs#8626]
**Your Godot version:**

4.2.stable

**Issue description:**

In the main game scene section of the 2D demo game, it mentions a "hit" signal. I cannot seem to find it where described. Am I missing something or is hit no longer a signal?

"You should see a list of the signals for the Player node. Find and double-click the hit signal in the list (or right-click it and select "Connect...")."

**URL to the documentation page:**

https://docs.godotengine.org/en/stable/getting_started/first_2d_game/05.the_main_game_scene.html

**Comment by AThousandShips** [comment]
It's declared [here](https://docs.godotengine.org/en/stable/getting_started/first_2d_game/03.coding_the_player.html#preparing-for-collisions)

Not a bug, but a case of missing a step in the tutorial

**Comment by planariangames** [comment]
Thanks!
