### ISSUE TITLE
2D / 3D Tools Documentation is Nonexistent

### ISSUE THREAD

**Issue by Kylemcarthur** [godotengine/godot-docs#8628]
I spent a great deal of time looking for this myself, asking others for help, and then ultimately coming to the conclusion it just doesn't exist. The tools for the 2D / 3D view, canvas, screen, whatever its name is could use documentation. As I'm new to Godot, I don't have the knowledge to write it myself. Coming from a digital art background, I generally expect to be able to find how the specifics of a given visual tool work. I can experiment and guess, especially based on prior knowledge, but that's not particularly ideal. And what if someone has no prior experience with these things? I think the fact that, while asking for help from people, someone mentioned "I've been using Godot for years and I had no idea you could do that" is really telling.

To be clear, I'm talking about these modes / tools here. 
![image](https://github.com/godotengine/godot-docs/assets/29736706/cd1d0ab6-fa62-4de0-9a59-d9c9d758c58c)

For instance, if I am in Selection Mode, and I click a node and drag the handles, I can use modifiers like Shift or Ctrl to change what the drag is going to do to my selection. I only know this from prior experience in other software, but that still ultimately leaves it up to guesswork with trying key combinations and assuming what they're doing. Documentation needs a list of these options and what they specifically do for each tool where relevant. At minimum, each tool could really use basic descriptions to aid people in learning about them.
Hovering over the tools with the mouse does reveal some information currently, but for instance "Shift + Drag" is missing from the description for Selection Mode. Or, if I'm dragging the handles of a selection and press Ctrl, I can see some sort of guidelines appearing, but I don't see anywhere documenting that that exists, nor telling me what those guides specifically mean. So what else is missing, if anything? Without a comprehensive list, everyone I asked doesn't seem to know.

**Comment by tetrapod00** [comment]
Resolved by https://github.com/godotengine/godot-docs/pull/9621 and https://github.com/godotengine/godot-docs/pull/9481.
