### ISSUE TITLE
Nonexistent function 'clear_surfaces' in base 'PlaneMesh'

### ISSUE THREAD

**Issue by Amirth24** [godotengine/godot-docs#8630]
**Your Godot version:** 4.2.1

**Issue description:** I've just started using Godot 4. I tried to experiment with terrain generation and visited the mentioned documentation page. I am using the MeshDataTool approach as I am trying to modify the plane mesh changing the y-axis value of the mesh. The PlaneMesh class doesn't have the `clear_surfaces()` method. If I run without `mesh.clear_surfaces()`, I was encountered with following error, 
```
E 0:00:01:0101   Plane.gd:9 @ _ready(): Condition "p_mesh.is_null()" is true. Returning: ERR_INVALID_PARAMETER
  <C++ Source>   scene/resources/mesh_data_tool.cpp:43 @ create_from_surface()
  <Stack Trace>  Plane.gd:9 @ _ready()
E 0:00:01:0101   Plane.gd:42 @ _ready(): Condition "p_mesh.is_null()" is true. Returning: ERR_INVALID_PARAMETER
  <C++ Source>   scene/resources/mesh_data_tool.cpp:195 @ commit_to_surface()
  <Stack Trace>  Plane.gd:42 @ _ready()
```
Am I wrong to attach the script to a plane mesh ??

**URL to the documentation page:** https://docs.godotengine.org/en/stable/tutorials/3d/procedural_geometry/meshdatatool.html

**Comment by AThousandShips** [comment]
You're using the wrong type, you are supposed to use `ArrayMesh`, as the documentation says:
> If you are dynamically updating an existing ArrayMesh, first delete the existing surface before adding a new one using commit_to_surface():

This is not a bug, you are missing the instructions, you need an `ArrayMesh` to commit to as well

**Comment by Amirth24** [comment]
Oh, my bad. 
Is there a way to manipulate `PlaneMesh` using `MeshDataTool`. are they meant to be? if not then I should have to create vertices from scratch using `ArrayMesh` and follow the tutorial. Am I getting it right?

**Comment by AThousandShips** [comment]
No, they aren't, they're primitive meshes which can only be one shape, but you can create an array mesh from a plane mesh with `SurfaceTool`
