### ISSUE TITLE
Dodge the Creep 2D Mobs Don't Spawn In

### ISSUE THREAD

**Issue by thekhking** [godotengine/godot-docs#8634]
Godot v 4.2.1

I have followed the documentation page line for line but for whatever reason when I test the Main scene my player spawns in and I can move it around but no enemies ever spawn. I can't seem to find any other documentation that is able to fix this issue.

(https://docs.godotengine.org/en/stable/getting_started/first_2d_game/05.the_main_game_scene.html)

**Comment by AThousandShips** [comment]
For support questions and help please first turn to the other [community channels](https://godotengine.org/community), this is for bug reporting, not a help desk. Please use other channels *first* to see if this is a bug or user error.

As this demo works generally it's very likely you followed the instructions incorrectly, please check that your code matches, using the *other* channels to do so 🙂

**Comment by skyace65** [comment]
Closing this per AThousandShips comment and the lack of a response. Again, If you're having trouble please use one of the community channels on the page AThousandShips linked to. Or alternatively if part of the docs do not work and you're convinced it's a bug please attach a zip file of your project, or a minimal reproduction project depending on the issue, so we can look at it and see what's going on. If you just tell us "it's not working and I don't know why" we aren't going to be able to help you.
