### ISSUE TITLE
When creating signal "Connect" and "Cancel" button are reversed 

### ISSUE THREAD

**Issue by Luxiorawa** [godotengine/godot-docs#8647]
**Your Godot version:**

4.2

**Issue description:**

I'm blindly following the docs on the signals, and when it says to create a signal on the "Toggle motion" button, it shows a screen where we can either Connect or Cancel the signal. Here is the documentation screen : 

![image](https://github.com/godotengine/godot-docs/assets/90514525/c4f52d41-d2ad-4714-88ca-379aef75d6c3)

Where the Connect button is on the right, and the Cancel button on the left

But on my version (not sure since when it is like that) those button are reversed as you can see here : 

![image](https://github.com/godotengine/godot-docs/assets/90514525/2ecda5a9-3d69-4e48-b90c-2386baef8ca5)

Connect button is on the left, and the Cancel button is on the right.

There is also minors differences in how node are named, and a new button named "Pick"

**URL to the documentation page (if already existing):**

https://docs.godotengine.org/en/stable/getting_started/step_by_step/signals.html

**Comment by YuriSizov** [comment]
The order of buttons depends on your operating system. Godot follows the convention of the host OS, where some operating systems put the affirmative action to the left and some to the right. The screenshot, obviously, cannot display both options, although we should try to keep them self-consistent at least.

**Comment by Luxiorawa** [comment]
Oh okay, i didn't know that, i see. Still, there seems to be other differences like the "Pick" button not being present on the docs
