### ISSUE TITLE
Why AddAnimation not forking in godot engine 4.2.1 with C#?

### ISSUE THREAD

**Issue by muhal24** [godotengine/godot-docs#8658]
I have this line of code:

```cs
private void CreateHighlightAnimation(string animationName, string scenePath)
{
    var animation = new Animation();
    animation.Length = 0.5f; // Duration of the animation in seconds

    // Assuming you have a TextureButton node for each tab with a modulate property
    var tabButton = GetNode<TextureButton>(scenePath);
    var tabPath = tabButton.GetPath();
    var trackIndex = animation.AddTrack(Animation.TrackType.Value);
    animation.TrackSetPath(trackIndex, tabPath + ":modulate");
    animation.TrackInsertKey(trackIndex, 0.0f, new Color(1, 1, 1, 1)); // Normal color
    animation.TrackInsertKey(trackIndex, 0.5f, new Color(0.8f, 0.8f, 0.8f, 1)); // Highlighted color

    // Set the loop property on the animation
    animation.Loop = true; // In Godot 4.2.1, the property is 'Loop', not 'LoopMode'

    // Add the animation to the AnimationPlayer
    var animationPlayer = GetNode<AnimationPlayer>("Animation"); // Replace with your actual AnimationPlayer node path
    animationPlayer.AddAnimation(animationName, animation);
}

 }
```

, and I want to using the animation for my game project in godot engine 4.2.1 version, and I am using .Net6.0 in project, but it is throw an error for this line of code "animationPlayer.AddAnimation(animationName, animation);" as a

"'AnimationPlayer' does not contain a definition for 'AddAnimation' and no accessible extension method 'AddAnimation' accepting a first argument of type 'AnimationPlayer' could be found (are you missing a using directive or an assembly reference?)CS1061"

, any idea will be appreciated.

**Comment by AThousandShips** [comment]
This method doesn't exist on `AnimationPlayer` see [here](https://docs.godotengine.org/en/latest/classes/class_animationplayer.html), no clue what method or class you are thinking about, but this isn't a method that exists

**Comment by muhal24** [comment]
How we can fix it? this line of code is not correct?

**Comment by AThousandShips** [comment]
I don't know, as I said I have no idea what method you mean to call, this method doesn't exist and never has existed in 4.x

For support questions and help please first turn to the other [community channels](https://godotengine.org/community), this is for bug reporting, not a help desk. Please use other channels *first* to see if this is a bug or user error.

**Comment by muhal24** [comment]
yes but all my C# codes not working in Godot 4.2.1 , always have bugs.

**Comment by AThousandShips** [comment]
Yes, because you can't use this code in 4.x, please ask in the other community channels because this is not a bug

The method you are calling doesn't exist, you need to use something else, and please ask for that help in some other channel, this isn't the place to ask for support 🙂
