### ISSUE TITLE
Incorrect Image in Getting Started: Your first 2D game / The main game scene

### ISSUE THREAD

**Issue by sbassan1** [godotengine/godot-docs#8665]
Your Godot version: stable v.4.2.1

The documentation shows an image after explaining the Path2D node which says "Your scene should look like this:"

![Screenshot_1](https://github.com/godotengine/godot-docs/assets/105613188/cc9facb9-2d5e-4e03-a691-035657f021d4)

The problem is that in the image the player node is set to have a connection and at that point in the tutorial it 
does not add the connection to the player node, it shouldn't have it until the next step when they add the game_over signal

The tutorial is very good and concise, but it is something that irked me a little because i spent some time figuring out what i did
wrong and what that icon (the node connection icon) meant. 

https://docs.godotengine.org/en/stable/getting_started/first_2d_game/05.the_main_game_scene.html

**Comment by sbassan1** [comment]
Excuse me for my neanderthal English i'm not used to it yet

**Comment by skyace65** [comment]
Piralein is correct. The icon for a signal should be there because of what you do in the coding the player section. The current image is correct
