### ISSUE TITLE
Please add learn-gdscript website in docs

### ISSUE THREAD

**Issue by praveeno** [godotengine/godot-docs#8668]
I found [https://gdquest.github.io/learn-gdscript](https://gdquest.github.io/learn-gdscript) website really good for beginners, Please add this in resources section.

**Comment by YuriSizov** [comment]
For Godot 3 we link it in the introduction section, but the tool wasn't ready for Godot 4. Now that it is, we do plan to put it into the introduction section for 4.x docs.

**Comment by praveeno** [comment]
ok thanks for confirming, will try to raise a PR
