### ISSUE TITLE
Git pugin has been updated

### ISSUE THREAD

**Issue by IfgiU** [godotengine/godot-docs#8675]
**Godot version: 4.2.1**

The documentation still says that the Git plugin isn't updated for 4.1. However, the [**newest**](https://github.com/godotengine/godot-git-plugin/releases) release says they're supporting Godot 4.1 and up.

**[URL to the documentation page](https://docs.godotengine.org/en/stable/tutorials/best_practices/version_control_systems.html#official-git-plugin)**

**Comment by AThousandShips** [comment]
Already fixed in [latest documentation](https://docs.godotengine.org/en/latest/tutorials/best_practices/version_control_systems.html), done in:
* https://github.com/godotengine/godot-docs/pull/8642

The changes will be carried over to older versions in a future cherry pick
