### ISSUE TITLE
Upgrading from 3 to 4 changes functions to invalid functions

### ISSUE THREAD

**Issue by Sean-Brown** [godotengine/godot-docs#8689]
**Your Godot version:**
4.2

**Issue description:**
Upgrading the project with the `--convert-3to4` flag changes functions to invalid functions. For example, the SpriteFrame's `AddAnimation` method was supposedly updated to `AddAnimationLibrary`, however this results in a compile error saying:
> 'SpriteFrames' does not contain a definition for 'AddAnimationLibrary' and no accessible extension method 'AddAnimationLibrary' accepting a first argument of type 'SpriteFrames' could be found (are you missing a using directive or an assembly reference?)

When I look in the assembly for SpriteFrames (Assembly GodotSharp, Version=4.2.0.0), I see that it contains a definition for `AddAnimation` but not `AddAnimationLibrary`. There are several other upgraded methods that result in this same error.

Am I missing something? This [cheat sheet](https://godot-3to4.vercel.app/) seems to indicate that the upgrade was supposed to change that method to `AddAnimationLibrary`, but why does the assembly define the old method name and not the new one?

**URL to the documentation page:**
https://docs.godotengine.org/en/4.0/tutorials/migrating/upgrading_to_godot_4.html

**Comment by AThousandShips** [comment]
This is not the place to report this bug, as it's related to the engine, please report it [here](https://github.com/godotengine/godot/issues)

**Comment by Sean-Brown** [comment]
Closing, moved to https://github.com/godotengine/godot/issues/86646
