### ISSUE TITLE
"Running Code in the Editor" missing info on Resources

### ISSUE THREAD

**Issue by donovani** [godotengine/godot-docs#8692]
**Your Godot version:**
Godot 4.2

**Issue description:**
It seems like Nodes that use `[Tool]` can only use Resources that also have `[Tool]`. Without it, Godot will throw the following error:

> Unable to cast object of type 'Godot.Resource' to type 'ExampleResourceType'.

This is not exactly a clear error and [has caused confusion for several people](https://github.com/godotengine/godot/issues/85459#issuecomment-1870709144). It also does not appear that the docs explain this behavior.

I think it would make sense to include a few sentences explaining that Resources are affected by `[Tool]` as well. The wording is not important to me, so long as it conveys what the developer needs to do.

**URL to the documentation page (if already existing):**
https://docs.godotengine.org/en/stable/tutorials/plugins/running_code_in_the_editor.html

**Comment by raulsntos** [comment]
There's a warning about this for GDScript in the [_Making plugins_](https://docs.godotengine.org/en/stable/tutorials/plugins/editor/making_plugins.html#the-script-file) documentation page.

![image](https://github.com/godotengine/godot-docs/assets/3903059/a55c9310-68ad-4384-a15d-4aa78779233e)

I think it makes a lot of sense to add a note/warning to the [_Running code in the editor_](https://docs.godotengine.org/en/stable/tutorials/plugins/running_code_in_the_editor.html) documentation page.

Keep in mind that classes without `[Tool]` _can_ be used from `[Tool]` scripts as long as you use the native Godot type. For example:

```csharp
public partial class MyResource : Resource
{
    [Export]
    public int MyNumber { get; set; }
}

[Tool]
public partial class MyTool : Node
{
    [Export]
    public Resource SomeResource { get; set; }

    public override void _Ready()
    {
        int number = SomeResource.Get(MyResource.PropertyName.MyNumber).As<int>();
        GD.Print($"My number is {number}");
    }
}
```
