### ISSUE TITLE
Array documentation does not explain typed arrays

### ISSUE THREAD

**Issue by Malte0** [godotengine/godot-docs#8695]
**Your Godot version:**
4.2.1

**Issue description:**
I wanted to look up some information about how to declare and use typed arrays. 
However the official documentation lacks explanaitions for that. 

**URL to the documentation page (if already existing):**
https://docs.godotengine.org/en/stable/classes/class_array.html

**Comment by AThousandShips** [comment]
This is something specific to GDScript and is documented extensively [here](https://docs.godotengine.org/en/latest/tutorials/scripting/gdscript/gdscript_basics.html#typed-arrays) but a link in the class reference would be helpful

**Comment by Malte0** [comment]
ok, thanks.

**Comment by AThousandShips** [comment]
The documentation updates in:
* https://github.com/godotengine/godot-docs/issues/8695

Will close this
