### ISSUE TITLE
2D movement docs example using undefined InputMap actions "left", "right", "up", "down"

### ISSUE THREAD

**Issue by omar-yehia** [godotengine/godot-docs#8696]
**Your Godot version:**
4.2.1

**Issue description:**
docs has wrong script for 2D movement

`var input_direction = Input.get_vector("left", "right", "up", "down")`
gives errors for all directions
`The InputMap action "up" doesn't exist. Did you mean "ui_up"?`

**URL to the documentation page:**
https://docs.godotengine.org/en/stable/tutorials/2d/2d_movement.html

**Comment by AThousandShips** [comment]
They're there in the first part of the documentation? You're instructed to add them:
> Open `Project -> Project Settings` and select the "Input Map" tab. Add the following input actions (see InputEvent for details)

When reporting a bug please make sure you've followed the tutorial, this is not an issue with the documentation

**Comment by omar-yehia** [comment]
@AThousandShips 
thank you for replying
my apologies, I was looking quickly for a working example
so I went straight to the snippet
