### ISSUE TITLE
Make description of equal() function in Shader Language reference more clear

### ISSUE THREAD

**Issue by Daniel-The-Fox** [godotengine/godot-docs#8703]
**Your Godot version:**

4.2.1

**Issue description:**

As asked in https://github.com/godotengine/godot-proposals/issues/6870#issuecomment-1873453359, I'm opening an issue reg. the description of the `equal()` function in Shader Language reference. It currently can be misunderstood for being capable of comparing any kinds of vectors, also i.e. color vectors (`vec4`).

Current docs state:

bvec_type equal (vec_type x, vec_type y) | Bool vector comparison on == int/uint/float vectors.
-- | --

"It returns, for example: `bvec2(foo.x == bar.x, foo.y == bar.y)`" (stated from @AThousandShips).

It's stated also in the docs somewhere, that we shouldn't compare floats via `==`, 
so what does this function do with floats exactly? Is the result reliable for floats?

**URL to the documentation page (if already existing):**

https://docs.godotengine.org/en/stable/tutorials/shaders/shader_reference/shading_language.html#built-in-functions

**Comment by clayjohn** [comment]
This is a built in GLSL function, so the [GLSL docs](https://registry.khronos.org/OpenGL-Refpages/gl4/html/equal.xhtml) have a bit more detail. 

AThousandShips' example is correct. It returns a `bvec*` which contains the per-component result of the `==` operator. 

It works for all vector data types (bvec, ivec, uvec, vec). Since it is just doing an `==` internally, the result is the same as if you were to compare floats manually with `==`. 

Floating point comparison is a fundamental problem with floating points, its not specific to GLSL or to Godot. Floating point comparison is reliable. For example ``0.3 == 0.3`` will always return true. However, the problem comes from users not realizing that floating point operations are _inexact_ so users assume they are comparing `0.3 == 0.3` when they are actually comparing `0.299999999999 == 0.3` which returns false.

**Comment by Daniel-The-Fox** [comment]
Wouldn't it then be easier to just link to the respective GSLS docs article for each GSLS function implemented in Godot's shader language? 🤔

**Comment by clayjohn** [comment]
I started doing that in https://github.com/godotengine/godot-docs/pull/5729, but it was taking a long time to manually copy everything so I haven't finished.

**Comment by Daniel-The-Fox** [comment]
That looks much better! 😎 👍🏻 
Need any help? 😉 
What source(s) did you use?

**Comment by clayjohn** [comment]
> That looks much better! 😎 👍🏻 Need any help? 😉

I would love some help! Particularly, I would love for someone to pick up from where I left off. 

> What source(s) did you use? Would it be possible to auto-generate this?

I am paraphrasing the official GLSL documentation directly (from here: https://registry.khronos.org/OpenGL-Refpages/gl4/html/).

I autogenerated the basic signature of the functions, but I was filling in the details for each by hand. I didn't want to do something to automatically copy the full description as the format is a bit different and I wanted to reserve the right to heavily paraphrase when the description is very long and technical.

**Comment by Daniel-The-Fox** [comment]
> I would love some help! Particularly, I would love for someone to pick up from where I left off.

Ok, so what's missing?

I can manually edit the file and see if all currently listed built-in functions are present and manually add the ones missing, incl. copying the description and inserting a link to the respective Khronos docs page. As I'm totally new to shaders in general and the Godot shading language, I'm not comfortable extending or massively editing the descriptions though.

How high is the probability of that getting approved and merged?
I want to avoid investing unnecessary time, as happened on other issues or PRs I opened in the past myself... 😞😉 

> I autogenerated the basic signature of the functions, [...]

How did you auto-generate them?


Is there a way to preview this jsdoc stuff somehow locally? 😆

**Comment by tetrapod00** [comment]
The work of improving the shader function descriptions was done in https://github.com/godotengine/godot-docs/pull/9338, so I'm closing this as resolved.

@Daniel-The-Fox If you'd like, please take a look at the new description for [equal()](https://docs.godotengine.org/en/latest/tutorials/shaders/shader_reference/shader_functions.html#shader-func-equal), and if you find it still lacking, feel free to open a PR to improve it (or just make another suggestion here).

The source for equal() in particular is here:
https://github.com/godotengine/godot-docs/blob/master/tutorials/shaders/shader_reference/shader_functions.rst?plain=1#L2087-L2108
