### ISSUE TITLE
Misleading note in Area3D/PhysicsServer3D  and Area2D/PhysicsServer2D

### ISSUE THREAD

**Issue by mvccogo** [godotengine/godot-docs#8709]
**Your Godot version:**
(latest), 4.3
**Issue description:**
The following note was added to Godot 4.3 Area3D documentation:
`Areas and bodies created with [PhysicsServer3D] might not interact as expected with [Area3D]s, and might not emit signals or track objects correctly.`

The commit description (https://github.com/godotengine/godot/commit/0081a50e327612c53b93b2848d05a107da19c9b5) says:
`Prevent mapping areas with invalid IDs for Area2D/3D`
`This occurs when areas are created directly from the servers, and no
instance is linked.`

Instead of saying that areas/bodies created with `PhysicsServer3D` might not work as expected with `Area3D`s, wouldn't it be better to say exactly what signals won't be fired? Or, maybe better, point out that bodies in `PhysicsServer3D` must have a linked `Object`. As it stands right now, it looks like `Area3D`s and the underlying `PhysicsServer3D` are not compatible.

Our use case is to use `PhysicsServer3D` entirely in a Godot C++ Module, using an ECS pattern (EnTT) to deal with multiplayer-moving entities (while terrain/static entities are in a Godot scene). We want to make sure that Godot `Area3D` and other `CollisionObject3D`s from the Godot scene will correctly collide with bodies created by `PhysicsServer3D`. 

**URL to the documentation page:**
https://docs.godotengine.org/en/latest/classes/class_area3d.html

**Comment by mvccogo** [comment]
I apologize for the incorrect label - this should be an enhancement.

**Comment by AThousandShips** [comment]
It's not that simple though, there's many different details so the note isn't misleading 🙂

**Comment by mvccogo** [comment]
Thank you for the quick reply. In that case, would it be possible to put a note in the "Optimizing using servers" or in PhysicsServer2D/3D pages explaining in more details this issue? At the very least, I think it is fair to warn users in those pages as well. 

We thought that Scene Tree CollisionObjects would correctly behave with any PhysicsServer bodies/areas, and this doesn't seem to be the case. Perhaps what _is_ misleading, in reality, is the "Optimizing using Servers" or the PhysicsServer3D pages due to omitting this limitation.

Again, thank you for maintaining the Godot Engine.

**Comment by AThousandShips** [comment]
Details there could absolutely be added, I'm not able to do it at the moment, but I'd say it mainly applies to those classes, and not elsewhere, but very welcome to add to that, it'd be difficult to add details on how to make them work right with built in types though

And thank you for feedback!
