### ISSUE TITLE
Lambda documentation does not mention "return" is required

### ISSUE THREAD

**Issue by Marenz** [godotengine/godot-docs#8729]
Version: All

The documentation for lambda functions does not mention that to return a value you need to explicitly write `return` before the expression.
All of the examples use `print()` which also does not demonstrate that need.

https://github.com/godotengine/godot-docs/blob/master/tutorials/scripting/gdscript/gdscript_basics.rst#lambda-functions
https://docs.godotengine.org/en/stable/tutorials/scripting/gdscript/gdscript_basics.html#lambda-functions

**Comment by AThousandShips** [comment]
This is only a confusing thing if you expect it to work differently than normal methods

**Comment by Marenz** [comment]
I think we argued enough in the PR, so I only want to add my user experience here so one can see where I come from:

First of, I have +1y experience with python and +10y with D/C++ and similar.

In my project, I had the line

```
winners.sort_custom(func (a, b): times[a]  < times[b]) # missing return
```

It did trigger a warning (`Standalone expression (the line has no effect).`) yes.
But I thought it was referencing the `sort_custom` function, though the documentation of that said it's `void` so I was confused
and assumed it's maybe a bug in the metadata of the function that the interpreter internally uses, things _seemed_ to work more or less as they should after all.

I read the documentation of the lambdas, nowhere was a `return` demonstrated or mentioned, so I was no wiser than before.

Only after I asked in the chat someone pointed the right thing out to me.
We could have saved both, the helpful chat persons and myself a lot of time, if this information was easily found.

More importantly, it would be a much improved user experience and in the end, isn't that what counts?
I believe that both the scenario where this happened (a lambda embedded in a call) as well as the target crowd (a person knowing python but being new to gdscript) are not rare and thus this would make an improved user experience for a non-trivial amount of people.

**Comment by AThousandShips** [comment]
I was making my opinion clear here, that's what this is for 🙂 I didn't say it shouldn't be done
