### ISSUE TITLE
Trouble exporting to Android from Linux. All located 'apksigner' tools in ../Android/Sdk/build-tools failed to execute

### ISSUE THREAD

**Issue by xwedea** [godotengine/godot-docs#8742]
Godot 4.2
Debian 12 Linux

I have followed every single step in [Exporting for Android](https://docs.godotengine.org/en/stable/tutorials/export/exporting_for_android.html), and I am sure that I have the specified versions of packages. Everything works as expected, except the apksigner. 

Warning:
`editor/export/editor_export_platform.h:179 - Code Signing: All 'apksigner' tools located in Android SDK 'build-tools' directory failed to execute. Please check that you have the correct version installed for your target sdk version. The resulting APK is unsigned.`
Error:
`All located 'apksigner' tools in /home/j/AndroidCMD/Sdk/build-tools failed to execute`

I have done the same things on Windows 11 and managed to export without any issues.

**Comment by Calinou** [comment]
@xwedea Are you using the Godot Flatpak or the official binaries?

**Comment by xwedea** [comment]
> @xwedea Are you using the Godot Flatpak or the official binaries?

**Comment by xwedea** [comment]
I am using the official binaries. 

I resolved this problem by running Godot from a terminal, instead of a shortcut I defined in ~/.local/share/applications/

Closing the issue.

**Comment by hookind** [comment]
> I am using the official binaries.
> 
> I resolved this problem by running Godot from a terminal, instead of a shortcut I defined in ~/.local/share/applications/
> 
> Closing the issue.

Thanks, I had the same problem with version 4.4 and solved it with your method.
