### ISSUE TITLE
Missing Offline Documentations Of Stable

### ISSUE THREAD

**Issue by erenpal** [godotengine/godot-docs#8744]
**Your Godot version:**
4.2.1
**Issue description:**

I always use offline documentation but only latest documentation exist ( currently 4.3 DEV) but stable version always missing.

**URL to the documentation page (if already existing):**

**Comment by YuriSizov** [comment]
What specifically do you refer to as offline documentation here? Can you show a link?

**Comment by kksharma1618** [comment]
The stable website https://docs.godotengine.org/en/stable/index.html links to offline copy:
> You can also [download an HTML copy](https://nightly.link/godotengine/godot-docs/workflows/build_offline_docs/master/godot-docs-html-master.zip) for offline reading (updated every Monday). Extract the ZIP archive then open the top-level index.html in a web browser.

The link it points to is of the master branch (currently 4.3), not stable (currently 4.2).

**Comment by AThousandShips** [comment]
Offline docs are only generated for latest and 3.6 at the moment
