### ISSUE TITLE
Exporting for macOS: Which CPU silicon (Intel vs. Apple silicon) is targeted by the default export template for Mac OS?

### ISSUE THREAD

**Issue by Daniel-The-Fox** [godotengine/godot-docs#8745]
**Your Godot version:**
4.2.1

**Issue description:**
The current docs on exporting for macOS don't state which CPU silicon (Intel vs. Apple silicon) is targeted by the default export template for Mac OS?

In the docs [article on (cross-)compiling for Mac OS](https://docs.godotengine.org/en/stable/contributing/development/compiling/compiling_for_macos.html#building-export-templates), how to build export templates for Mac OS "Universal 2" binaries is explained in detail. So I assume the default export template for Mac OS that comes with Godot Engine 4 (after downloading them via the prompt that appears for the first export) provides Mac OS "Universal 2" binaries that run on Intel as well as Apple silicon, right?

If so, I think this info should be added to the article on how to export for Mac OS, as not every user exporting via the standard export template will read the article on compiling for Mac OS.

**URL to the documentation page (if already existing):**

https://docs.godotengine.org/en/stable/tutorials/export/exporting_for_macos.html

**Comment by AThousandShips** [comment]
It says on the downloads for the editor that they're universal, and should say so on the templates as well, I haven't downloaded them myself, and the build scripts that generate them also say universal, wouldn't hurt to be explicit but I think that should be assumed

**Comment by Daniel-The-Fox** [comment]
Ok, thanks. Just wanted to be sure I got it right. 
Should I make a PR for 1 sentence to add to the "Export for Mac OS" docs article? 😄

**Comment by AThousandShips** [comment]
Could add it there too yeah

**Comment by Daniel-The-Fox** [comment]
> It says on the downloads for the editor that they're universal, and should say so on the templates as well, I haven't downloaded them myself, and the build scripts that generate them also say universal, wouldn't hurt to be explicit but I think that should be assumed
> 
> Edit: it already says so:
> 
> > Official templates are universal binaries which support both Intel x86_64 and ARM64 architectures.

If I search the docs article on exporting for Mac OS for the string "universal", I get 0 hits.
https://docs.godotengine.org/en/stable/tutorials/export/exporting_for_macos.html

I guess you're referring to the article on compiling? 😉

**Comment by Daniel-The-Fox** [comment]
> Could add it there too yeah

Ok, I'll open a PR in the docs repo soon and link this issue...

**Comment by AThousandShips** [comment]
Yes meant the compiling page, hence the "there too" 🙂
