### ISSUE TITLE
One-Click Deploy  Missing iOS information

### ISSUE THREAD

**Issue by ztc0611** [godotengine/godot-docs#8750]
**Your Godot version:**
4.2

**Issue description:**
iOS is not documented on the one click deploy page despite it now having one click deploy. The process seems pretty involved so it should probably also have a setup tutorial like Android.

**URL to the documentation page:**

https://docs.godotengine.org/en/stable/tutorials/export/one-click_deploy.html

**Comment by bruvzg** [comment]
See https://github.com/godotengine/godot-docs/pull/8547 (Note: 4.2 only support `ios-deploy` method, Xcode 15 / iOS 17+ support was added after release).

**Comment by mhilbrunner** [comment]
Closing as fixed by https://github.com/godotengine/godot-docs/pull/8547 for 4.3+ docs.
