### ISSUE TITLE
Many of the headings in the animation docs pages for English are in Czech. 

### ISSUE THREAD

**Issue by wyattbiker** [godotengine/godot-docs#8765]
**Your Godot version:**
4

**Issue description:**
Some of the headings in the animation docs pages for English are in Czech. 

**URL to the documentation page:**
Examples
https://docs.godotengine.org/cs/4.x/tutorials/animation/introduction.html
https://docs.godotengine.org/cs/4.x/tutorials/animation/index.html
https://docs.godotengine.org/cs/4.x/tutorials/animation/2d_skeletons.html
https://docs.godotengine.org/cs/4.x/tutorials/animation/animation_tree.html

**Comment by AThousandShips** [comment]
Do you mean that the pages in Czech have English text? Those are the Czech pages, this is because the pages haven't been translated fully

**Comment by wyattbiker** [comment]
Ooops closing

**Comment by wyattbiker** [comment]
closing
