### ISSUE TITLE
Mouse enter an mouse leave events not working when opening a project on 4.2.1

### ISSUE THREAD

**Issue by irafunesta** [godotengine/godot-docs#8768]
**Your Godot version:**
Godot_v4.2.1-stable_win64
Godot_v4.1.2-stable_win64

**System** :
Windows 10

**Issue description:**
I have made a testing project for some grid puzzles, i am using the mouse_entered and mouse_exited signal to see if the mouse is under a piece. When working on Godot 4.1.2, everything works as intended but if i open the project with Godot 4.2.1 the mouse signals are not fired anymore.
This is the link to the project if you want to try it out. https://github.com/irafunesta/grid-puzzle.git

**Comment by AThousandShips** [comment]
This is for bugs in the documentation, for bugs in the engine please report [here](https://github.com/godotengine/godot/issues)
