### ISSUE TITLE
Outdated warning for Git Plugin

### ISSUE THREAD

**Issue by JasonLovrien** [godotengine/godot-docs#8775]
Godot 4.2.1

There is currently a warning on the VCS docs that the official git plugin is not up to date for Godo 4.x.x
It looks like there's a version for Godot 4.x.x https://github.com/godotengine/godot-git-plugin/releases
The warning should be removed.

https://docs.godotengine.org/en/stable/tutorials/best_practices/version_control_systems.html#official-git-plugin

**Comment by AThousandShips** [comment]
This has already been solved, it just hasn't been cheery picked yet, fixed in:
* https://github.com/godotengine/godot-docs/pull/8642
