### ISSUE TITLE
Debugging visual studio

### ISSUE THREAD

**Issue by krutpik** [godotengine/godot-docs#8783]
**Your Godot version:**
4.2

**Issue description:**
The page describes the outdated version of visual studio

**URL to the documentation page:**
https://docs.godotengine.org/en/stable/contributing/development/configuring_an_ide/visual_studio.html

**Comment by AThousandShips** [comment]
What specifically is outdated?

**Comment by krutpik** [comment]
![image](https://github.com/godotengine/godot-docs/assets/69432169/7db88109-16d9-4d88-b4fb-e5939974fe3b)

![image](https://github.com/godotengine/godot-docs/assets/69432169/f67fdd62-4804-4c21-b287-0a7cc50c8af0)

**Comment by AThousandShips** [comment]
Then it should show both, of course with an English version screenshot, as both versions are currently supported and used by many
