### ISSUE TITLE
Project Import example in Step By Step uses outdated UI

### ISSUE THREAD

**Issue by r0ckwav3** [godotengine/godot-docs#8794]
**Your Godot version:**
v4.2.1.stable.official [b09f793f5]

**Issue description:**
The first four images of the In Practice section of this page include outdated screenshots of the project selection UI. Notably the Import button has been moved from the right side of the window to the top of the window.

**URL to the documentation page:**
https://docs.godotengine.org/en/stable/getting_started/step_by_step/instancing.html

If you know how to fix the issue you are reporting please
consider opening a pull request. We provide a tutorial on
using git here: https://docs.godotengine.org/en/stable/community/contributing/pr_workflow.html,
writing documentation at https://docs.godotengine.org/en/stable/community/contributing/docs_writing_guidelines.html
and contributing to the class reference here: https://docs.godotengine.org/en/stable/community/contributing/updating_the_class_reference.html

**Comment by BWPanda** [comment]
Duplicate of https://github.com/godotengine/godot-docs/issues/8673 ?

**Comment by r0ckwav3** [comment]
Yep, not sure why I couldn't find that issue
