### ISSUE TITLE
Reference>GDScript>Keywords hasn't promised list of tokens

### ISSUE THREAD

**Issue by genete** [godotengine/godot-docs#88]
See:
http://docs.godotengine.org/en/latest/reference/gdscript.html#keywords

**Comment by Ryan1729** [comment]
Specifically, the [keywords section](https://github.com/godotengine/godot-docs/blob/master/reference/gdscript.rst#keywords) only has a heading and a sentence promising a list, but no list.

**Comment by StraToN** [comment]
This list actually never existed in docs. It has to be written. We will write it very soon.
