### ISSUE TITLE
Outdated Information at: Godot's design philosophy¶

### ISSUE THREAD

**Issue by RealKaiserschmarren** [godotengine/godot-docs#8806]
**Your Godot version:**
4.2
**Issue description:**
Outdated Information in documentation [image: "A State Machine editor plugin in Godot 2 by kubecz3k"](feature removed in 4.0)
**URL to the documentation page:**
https://docs.godotengine.org/en/stable/getting_started/introduction/godot_design_philosophy.html
![engine_design_fsm_plugin](https://github.com/godotengine/godot-docs/assets/85518171/7a2ffc10-d886-4aa2-8277-8fffc1f409c8)

**Comment by RealKaiserschmarren** [comment]
there is also a second outdated picture on this page

**Comment by AThousandShips** [comment]
It isn't outdated, it clearly says it's from an old version, it isn't intended to display the engine but the philosophy

What feature was removed?

**Comment by RealKaiserschmarren** [comment]
visual scripting, correct me, if im wrong

**Comment by AThousandShips** [comment]
It's not, it's a plugin, as it says, it uses a different system, visual scripting wasn't even in 2.x

**Comment by RealKaiserschmarren** [comment]
okay then i'll close this issue, sorry
