### ISSUE TITLE
Official git plugin now supports 4.1 and later

### ISSUE THREAD

**Issue by dttrx** [godotengine/godot-docs#8810]
**Your Godot version: 4.2**

**Issue description: Version control systems documentation**

In the documentation there's a warning about the official git plugin not working with godot 4.1 and later.
Now it does with the [latest release of the plugin](https://github.com/godotengine/godot-git-plugin/releases/tag/v3.1.0).

**URL to the documentation page: https://docs.godotengine.org/en/stable/tutorials/best_practices/version_control_systems.html**

This is my first issue, if theres something wrong please let me know.

**Comment by AThousandShips** [comment]
Duplicate of https://github.com/godotengine/godot-docs/issues/8675

**Comment by dttrx** [comment]
My bad for not searching the closed issues, thanks for your work! 😁
