### ISSUE TITLE
Adding Seaven Studio as Third Party Support for Consoles

### ISSUE THREAD

**Issue by SeavenStudio** [godotengine/godot-docs#8821]
**Your Godot version:**
3.4

**Issue description:**

As we're releasing Brotato next week to Xbox One, Xbox Series, PlayStation 4 and PlayStation 5 after releasing it to Nintendo Switch last summer, we'd like to add our name to the list of providers:

- [Seaven Studio](https://www.seaven-studio.com/) offers Switch, Xbox One, Xbox Series, PlayStation 4 & PlayStation 5 porting of Godot games.

Thank you!

**URL to the documentation page (if already existing):**

https://docs.godotengine.org/en/stable/tutorials/platform/consoles.html#third-party-support

**Comment by adamscott** [comment]
Congrats for the (very successful) port of Brotato!

**Comment by SeavenStudio** [comment]
Thank you :)
