### ISSUE TITLE
Misdirected Link

### ISSUE THREAD

**Issue by wayseeker2000** [godotengine/godot-docs#8847]
Your Godot version:  4.2

Issue description:  The "Next" link on the "GUI skinning and themes" introductory page links to the "size and anchors" page under "UI building blocks" instead of linking to "Introduction to GUI skinning", which is the logical "next" page in the docs.

URL to the documentation page:  https://docs.godotengine.org/en/stable/tutorials/ui/index.html#gui-skinning-and-themes

If you know how to fix the issue you are reporting please
consider opening a pull request. We provide a tutorial on
using git here: https://docs.godotengine.org/en/stable/community/contributing/pr_workflow.html,
writing documentation at https://docs.godotengine.org/en/stable/community/contributing/docs_writing_guidelines.html
and contributing to the class reference here: https://docs.godotengine.org/en/stable/community/contributing/updating_the_class_reference.html

**Comment by skyace65** [comment]
That's not a misdirected link. That's the Index page for the UI section, it's not GUI skinning specific. It's taking you to the first page in the UI section, which is the size and anchors page.
