### ISSUE TITLE
Build for offline tasks failing

### ISSUE THREAD

**Issue by cplr** [godotengine/godot-docs#8849]
The 3.6 doc builder is failing, which is causing the 4.x builders to not execute. There are no available offline versions as the last successful build was too long ago.

**Comment by hackzilla** [comment]
I've just tried to download the documentation, and discovered this issue.

The specific error is:  `The sphinxcontrib.applehelp extension used by this project needs at least Sphinx v5.0; it therefore cannot be built with this version.`
https://github.com/godotengine/godot-docs/actions/runs/7604802152

**Comment by skyace65** [comment]
Fixed by #8857. The build was run this morning and you can download the docs again.
