### ISSUE TITLE
Memeber "name" redefined (original in native class 'Node')

### ISSUE THREAD

**Issue by Mohammad9760** [godotengine/godot-docs#8872]
Your Godot version:4.1.1.stable

Issue description: I can't make a variable called 'name' in a script that inherits/extends Node class.

Sorry if I can't be more descriptive or helpful.
Edit: typo fix

**Comment by AThousandShips** [comment]
This isn't a bug, you're shadowing a variable, namely [name](https://docs.godotengine.org/en/stable/classes/class_node.html#class-node-property-name), the error message should make this clear

The only thing that could be done here would be to have a note about it in the documentation

**Comment by Mohammad9760** [comment]
> This isn't a bug, you're shadowing a variable, namely [name](https://docs.godotengine.org/en/stable/classes/class_node.html#class-node-property-name), the error message should make this clear

Hi!
Yes I did figure that much out for myself, but I found it to be odd behavior.

in C#/Unity for example if you have a variable with the same name as the class that you are inheriting, then it 'Hides' the base class definition for that, but you can still access it by specifying the base class.
I just thought being able to name a variable 'name' should be a possibility.

But I understand if it cannot be done.

**Comment by AThousandShips** [comment]
This is by design, is it a case of:
```gdscript
extends Node

var name
```
That won't work and we don't allow it because it doesn't work when accessing it from outside the class, you also can't do it to exports in C#

**Comment by Mohammad9760** [comment]
I think the reason it doesn't make sense to me is my lack of knowledge/understanding of how classes are made in Godot.
Thanks!
