### ISSUE TITLE
`navigation_agent.set_velocity()` doesn't autocomplete in GDScript, so maybe replace it?

### ISSUE THREAD

**Issue by AdriaandeJongh** [godotengine/godot-docs#8880]
**Your Godot version:**
4.2.1

**Issue description:**
The docs mention `navigation_agent.set_velocity()`, but this doesn't autocomplete in GDScript because it's the setter of `navigation_agent.velocity`. The docs should probably be modified to use `navigation_agent.velocity` instead, so that noobs like me don't get confused as we are writing what's in the docs and the autocomplete makes it look like the method from the docs doesn't exist.

**URL to the documentation page:**
https://docs.godotengine.org/en/latest/tutorials/navigation/navigation_using_navigationagents.html

**Comment by smix8** [comment]
If I remember correct this was not a property at the beginning so the only way to set it was to call the function, but this is no longer the case, so could be changed.
