### ISSUE TITLE
No Layout Mode Description About Class Control Doc

### ISSUE THREAD

**Issue by makexiao113** [godotengine/godot-docs#8889]
**Your Godot version:**
4.2.1-stable
**Issue description:**
I am a freshman in godot, I cannot found layout mode description about Class Control in Doc,Please help me
**URL to the documentation page:**
![f16e5efc01f2f39fdf79a0bc5c378a95](https://github.com/godotengine/godot-docs/assets/63517007/28aa9609-fdfe-4afd-b66a-6e7002d4f7f2)
![image](https://github.com/godotengine/godot-docs/assets/63517007/a7c79d0d-fc50-40c4-9e11-584029c9fbb7)

**Comment by makexiao113** [comment]
I cannot found anything about layout mode in parent class doc，maybe I miss something, could someone help me?

**Comment by AThousandShips** [comment]
Resolved by:
* https://github.com/godotengine/godot/pull/87381

This is an internal property and can't (and shouldn't) be documented, now correctly says it's internal
