### ISSUE TITLE
Error in Godot 3D documentation

### ISSUE THREAD

**Issue by Overhaul66** [godotengine/godot-docs#8904]
### Tested versions

*Godot 4.2 documentation*
Transform 3D was explained incorrectly

![IMG-20240204-WA0016](https://github.com/godotengine/godot/assets/89018580/e1134b56-72ec-4772-8988-22877bb98625)

![IMG-20240204-WA0015](https://github.com/godotengine/godot/assets/89018580/dd0bd371-9e52-4f84-885d-a406c07581cf)

### System information

Internet

### Issue description

There was a mistake in explaining the matrix that transform3D represents

![IMG-20240204-WA0016](https://github.com/godotengine/godot/assets/89018580/53adbd9d-4848-4752-bee3-18e7691700c7)

A transform3D is supposed to be a 3x4 matrix

![IMG-20240204-WA0015](https://github.com/godotengine/godot/assets/89018580/a3e84acf-705b-4299-87fc-4c39c31cdad1)

### Steps to reproduce

None

### Minimal reproduction project (MRP)

None

**Comment by kleonc** [comment]
Note it's not just the `4×3` part being wrong, the rest of the sentence and the image are outdated.
![VeWEwh7G](https://github.com/godotengine/godot-docs/assets/9283098/9b531b06-f0c2-4a72-b919-252cfcdcabc4)

It was changed in the meantime how Transform3D is exposed:
![Vp0iiNIYBf](https://github.com/godotengine/godot-docs/assets/9283098/3c8d8d29-781f-472b-b477-c92dcf8af4d3)

**Comment by LunarTides** [comment]
Shouldn't this be closed now that #9174 is merged?

**Comment by clayjohn** [comment]
Yes.

Kleonc's comment is still outstanding, but I think this bug report can be closed as overhauling the 3D docs is a bit out of scope for this and is better tracked elsewhere (i.e. in the docs repo)
