### ISSUE TITLE
Add more information about the current Limitations of Godot stable C# Android Export

### ISSUE THREAD

**Issue by VidyaGameMaka** [godotengine/godot-docs#8912]
**Your Godot version:**
Godot 4.2.1

**Issue description:**
Is it possible to clarify in the documentation that the current implementation of the android export can only export 64bit when using C# and maybe state if 32bit android exports will be supported in a future release or not?

Will 32bit android export for C# will be implemented in a future release of Godot 4.x? There is still a majority of 32bit arm android devices and on Godot 3.5.3 it was possible to target 32bit and 64bit android exports when using C#.

Thank you for looking at my question, I truly appreciate it a lot. ❤

**URL to the documentation page (if already existing):**
https://docs.godotengine.org/en/stable/tutorials/scripting/c_sharp/index.html#doc-c-sharp-platforms

**Comment by raulsntos** [comment]
This is already documented in the documentation page you linked:

![image](https://github.com/godotengine/godot-docs/assets/3903059/8b58ff73-2d63-4d66-bb41-f2b7085d3433)

Android 32-bit architectures are currently unsupported but the intention is to support as many of the platforms that Godot supports in C# projects.

In case you haven't seen it already, take a look at this recent article that describes the current state of platform support for C# projects and hints at future development: https://godotengine.org/article/platform-state-in-csharp-for-godot-4-2/

Feel free to ask follow-up questions about the article in the [Godot forums](https://forum.godotengine.org/t/current-state-of-c-platform-support-in-godot-4-2/44594/2), there are already some answered questions about Android support that you may be interested in.

**Comment by skyace65** [comment]
Closing per raulsntos' comment.
