### ISSUE TITLE
Missing Documentation for PopupMenu.Connect()

### ISSUE THREAD

**Issue by M0deseven** [godotengine/godot-docs#8916]
**Your Godot version: 4.2.1 Stable (Windows and Linux)

**Issue description:
Trying to create a MenuButton with a PopupMenu that appears when the MenuButton is clicked.
The documentation does not provide an example on how to do this nor does it include any information on the
connect() method. In fact, when doing a ctrl+f on the page, the word connect does not even appear once.
As far as I can tell, the connect() function is absolutely critical if you want your popup menu to actually
do anything. 

Currently I can't seem to figure out what sort of arguments to pass to the .connect() method
All of the tutorials and copilot output seems to think that it's suppose to be something like this:

$MenuButton.get_popup().connect("id_pressed", self, "_on_menu_item_pressed")

This line is usually inside of the _ready() function which is inside my root node script
so it will crash the program as soon as you enter the scene. Usually giving an error that roughly says:
"Argument 2 is an object when a callable is expected." I made the "_on_menu_item_pressed argument" a function and passed self as a parameter" and then I started to get the same error but with argument 1 instead of argument 2. So I went and changed "id_pressed" to $MenuButton.get_popup.id_pressed and now it's saying it can't convert argument 1 from signal to StringName which I don't  understand.
The function that is receiving the signal is written like this:

func _on_menu_item_pressed(id):

writing it like this:  _on_item_pressed_(var id)
only gets me another error saying: "Expected parameter name"

I know this sounds like an issue for another repository but I feel like if there were some usage examples on the
PopupMenu page and some information about the connect() function in general that would be tremendously helpful
I'll keep working on it and update if I figure out how to give this function the parameters it wants.

**URL to the documentation page:
https://docs.godotengine.org/en/stable/classes/class_popupmenu.html#class-popupmenu

**Comment by M0deseven** [comment]
UPDATE: I was able to fix this. I found out that id_pressed() has a connect method that you can call and pass the name of your handler function as an argument.
This is what finally worked:
$MenuPopup.get_popup().id_pressed.connect(_on_menu_item_pressed)

I think it would be very helpful to add an example of this on the documentation page
because the connect() function is critical to making the PopupMenu work.

Furthermore, I searched for "connect" in the docs and since the word "connect"
is used a lot in the documentation for other things. I found one reference to it in the
"Object Class" page which was outdated.

**Comment by AThousandShips** [comment]
This is [this method](https://docs.godotengine.org/en/stable/classes/class_object.html#class-object-method-connect) and is well documented, not outdated

**Comment by skyace65** [comment]
Closing per AThousandShips comment. Though I do think we need a guide in the step by step section of the docs going over basic class reference usage, specifically for showing people to look at parent classes for methods.
