### ISSUE TITLE
2D tutorial outdated information

### ISSUE THREAD

**Issue by Kronser** [godotengine/godot-docs#8922]
**Your Godot version:** 4.2

**Issue description:** Game over function does not work according to documentation

**URL to the documentation page:** https://docs.godotengine.org/en/stable/getting_started/first_2d_game/06.heads_up_display.html

Hello, I'm not a programmer so the information I can provide will not be as useful as it should be, however, I've been follow the tutorial 2D and the game over message does not pops up. The GitHub files are not updated either I think.

Thank you!

**Comment by AThousandShips** [comment]
Please make sure you have copied all the code and followed all the steps, the code is correct and works

**Comment by skyace65** [comment]
I have confirmed the code in the game over function does work and would encourage you to double check what you've done so far. If you're certain it doesn't work and is an issue with the tutorial please provide us with a zip file of your project folder so we can take a look at your code.
