### ISSUE TITLE
Vector4i Page Says Vector3i

### ISSUE THREAD

**Issue by ShatteredRealityX** [godotengine/godot-docs#8931]
**Your Godot version:**
4.2.1

**Issue description:**
Vector4i Page Says Vector3i

> Note: In a boolean context, a Vector4i will evaluate to false if it's equal to Vector4i(0, 0, 0, 0). Otherwise, a Vector3i will always evaluate to true.

**URL to the documentation page:**
https://docs.godotengine.org/en/stable/classes/class_vector4i.html

If you know how to fix the issue you are reporting please
consider opening a pull request. We provide a tutorial on
using git here: https://docs.godotengine.org/en/stable/community/contributing/pr_workflow.html,
writing documentation at https://docs.godotengine.org/en/stable/community/contributing/docs_writing_guidelines.html
and contributing to the class reference here: https://docs.godotengine.org/en/stable/community/contributing/updating_the_class_reference.html

**Comment by skyace65** [comment]
- This was already fixed here: https://github.com/godotengine/godot/pull/87523
- The class reference just needs to be synced with the engine repository.
