### ISSUE TITLE
event.is_action_released() and Input.is_action_just_released() fires code more than once

### ISSUE THREAD

**Issue by NULLSonic** [godotengine/godot-docs#8944]
**Your Godot version:**
4.2.1

**Issue description:**
When using either Input.is_action_just_released() or event.is_action_released() the code for it fires more than once and I found out that it's tied with the current FPS the game runs on.

**URL to the documentation page:**
https://docs.godotengine.org/en/stable/classes/class_input.html

**Comment by Mickeon** [comment]
What happened?
