### ISSUE TITLE
Clarify suffix usage when importing resources with ResourceImporterScene

### ISSUE THREAD

**Issue by emre0altan** [godotengine/godot-docs#8950]
**Your Godot version: 4.2.1-stable**

**Issue description: Suffix usage when importing resources with ResourceImporterScene is not clear**

**URL to the documentation page: https://docs.godotengine.org/en/stable/tutorials/assets_pipeline/importing_3d_scenes/node_type_customization.html#create-navigation-navmesh**

Explained suffix on the page is not clear that it works with "$" (case sensitive), "-" (case insensitive) and "_" (case insensitive). This issue came up here: https://github.com/godotengine/godot/issues/87377. I'll create a PR for this.

**Comment by skyace65** [comment]
Fixed by #8951.
