### ISSUE TITLE
Clarify distinction between the two "External Editor" settings for GDScript and Dotnet

### ISSUE THREAD

**Issue by inputrandomness** [godotengine/godot-docs#8952]
**Your Godot version:**
v4.2.1.stable.mono.official [b09f793f5]

**Issue description:**
The recommendation is to place a prominent notice at the top Using an External Text Editor page that refers readers who are interested in C# scripting with an external editor such as Visual Studio to the C# Basics page, with a link to that page, and to make it clear that the information on the "Using an External Text Editor" page is not relevant to them.

Details:
The Editor Settings has two separate places for configuring an external editor: One under "Text Editor" and one under "Dotnet." If I understand correctly, those coding in C# should be using the "Dotnet" option, which properly opens the c# project and solution file, and the external editor settings under "Text Editor" should just be ignored. (I was unable to make that work and struggled for a while before finding the right area.) However, these pages in the settings dialog make no reference to each other. So a user may be unaware that the Dotnet area also has an external editor selection.

The documentation page Editor Introduction > Using an External Text Editor does not seem to reference any distinction between c# editing and GDscript editing. It notably provides info for Visual Studio Code but not Visual Studio. I was not able to see any reference to C# on that page.

The documentation page Scripting > C#/.NET > C# Basics has exactly the information that a user needs for using Visual Studio with Godot. 

It's very confusing to a new user that there are two separate places for setting an external editor, though perhaps this is obvious to experience dotnet developers that dotnet settings would be located in its own separate part of the settings.

**URL to the documentation page (if already existing):**
https://docs.godotengine.org/en/stable/tutorials/editor/external_editor.html

**Comment by raulsntos** [comment]
Thanks for the suggestion! A recent PR (https://github.com/godotengine/godot-docs/pull/8851) added a note to that documentation page, you can see it in the latest version of the documentation: https://docs.godotengine.org/en/latest/tutorials/editor/external_editor.html
