### ISSUE TITLE
Skeleton3D Insert Key button is impossible to read

### ISSUE THREAD

**Issue by hunterbk** [godotengine/godot-docs#8957]
**Your Godot version:**
Godot 4.2.stable

**Issue description:**
At the top ribbon when you are animating a Skeleton3D, there is a button to insert all bone positions/rotations as keys to an existing track, but it just about gave me a stroke reading it. Moreover, I tried to fix it myself, but I apparently can't, but I noticed that this is literally the key for all translations, which means all translations should probably be checked to make sure that they're translated properly, because the original was hardly understandable. I'm not going to fix it myself because I'm not sure how the translation keys work and I don't want to cause any issues with translations.

**URL to the documentation page:**
https://github.com/godotengine/godot/blob/e5a3fd1e53ad4e6efc1fd17deded8f4ce0973d10/editor/plugins/skeleton_3d_editor_plugin.cpp#L790

https://github.com/search?q=repo%3Agodotengine%2Fgodot+already+exist+track.&type=code&p=1

I suggest something like "Insert key of existing bone poses into an existing track." and also you might wanna look into the "Insert Key (All Bones) part too because it's hard to understand what the difference is between that and the "Insert Key (Existing Tracks) button.

**Comment by skyace65** [comment]
Just so you're aware this is an issue with the engine, not the documentation. For something like this you'd want to open a Issue in the engine repository. That aside this is so bad I just opened a PR to fix this.

**Comment by hunterbk** [comment]
> Just so you're aware this is an issue with the engine, not the documentation. For something like this you'd want to open a Issue in the engine repository. That aside this is so bad I just opened a PR to fix this.

Got it, I think last time I used the normal engine repository and was told to come here for properties when you hover over something in the engine, it's tough to tell imo, even more so with this. I also opened another issue with the button itself being broken, but that's on the normal repo. I appreciate it, should I close this issue?

**Comment by skyace65** [comment]
Ok I think I see where the confusion came from. By properties that person was probably referring to node properties specifically. Those issues should be opened here because node properties are part of the class reference for nodes. In this case this isn't a property, it's a tooltip for a editor button. You can leave this issue open.
