### ISSUE TITLE
skeleton2D no have make reset pose , version of godot is 4.2.1

### ISSUE THREAD

**Issue by lichengkun1** [godotengine/godot-docs#8958]
![image](https://github.com/godotengine/godot-docs/assets/87630030/268fb588-51ea-48c5-bf8c-26bafa67606d)
documet is error?

**Comment by AThousandShips** [comment]
The button is in the bar above the scene, see the screenshot

![image](https://github.com/godotengine/godot-docs/assets/96648715/66d32b3c-11be-4dee-b08f-6a2eb3289e1d)

**Comment by skyace65** [comment]
The wording for that section definitely needs to be improved.
