### ISSUE TITLE
SkeletonIK3D deprecated

### ISSUE THREAD

**Issue by albertok** [godotengine/godot-docs#8965]
Godot 4.X

The documentation for SkeletonIK3D lists it as deprecated however it was introduced in 4.0 and [continues to get fixes in each version](https://github.com/godotengine/godot/pull/87888). Is it really deprecated? I can't find an authoritative source and believe this might be a mistake made during a [mass edit ](https://github.com/godotengine/godot-docs/commit/82b2845f66b6f8d66212ec11ca8bffc5ca7f0248#diff-65bf6bb491acc5a527715c8aabd9d31bfa1a181d0095ff74e4942caf0cda1c1f)leading developers to avoid it.

[**URL to the documentation page:**](https://docs.godotengine.org/en/stable/classes/class_skeletonik3d.html)

**Comment by TokageItLab** [comment]
SkeletonIK3D is just left because the migration path is not there yet. The fix in https://github.com/godotengine/godot/pull/87888 is just to remove the deprecated API from there.

And we are planning to add a Node like LookAtIK3D in the future. After that, SkeletonIK3D will no longer be maintained and to encourage migration from SkeletonIK3D to LookAtIK3D.

**Comment by skyace65** [comment]
Closing per TokageItLab's comment

**Comment by americoperez49** [comment]
Are there any alternatives to this for now?

**Comment by TokageItLab** [comment]
Not yet but we are working on for 4.4

**Comment by GeorgeS2019** [comment]
@TokageItLab 
Please provide latest link to SkeletonIK3D for 4.4

**Comment by TokageItLab** [comment]
The latest progress on IK that I remember is https://github.com/godotengine/godot/pull/87888 and the discussion is https://github.com/godotengine/godot-proposals/discussions/9885#discussioncomment-9665995.

The old SkeletonIK3D mixes up the two uses and I think it needs to be separated, as I wrote there:

- LookAt should targets only one Bone, and there needs to be some sort of non-linear interpolation or angle limitation there.
- ChainedBoneIK will resolve to multiple bones, which would require some sort of PoleAxis-like axis fixation as an option.

There are no PRs for these yet, but I will post them in Discussion and ContributorsChat as soon as progress is made.

**Comment by theghostronaut** [comment]
Are there any updates on this?

**Comment by TokageItLab** [comment]
We are still experimenting, but working on it. I think we can implement at least the same level of in 3.x, but we are thinking of adding some angle limitations, so it will take a little more time.

**Comment by MYRWYR** [comment]
Hi folks - I couldn't find any reference to this post-4.4. Any news?

**Comment by MarsAstro** [comment]
> Hi folks - I couldn't find any reference to this post-4.4. Any news?

Bumping this again! We're now in 4.5 and closing in on October. Is there still no other option than the long-deprecated one? I feel like it's an unfortunate state of things for something to be highlighted as deprecated for so long without any alternative showing up. Shouldn't the best practice be to deprecate something only **after** a new and better system shows up, to avoid the confusion of having the only available IK system be listed as deprecated for more than a year?

**Comment by Bloxxel64** [comment]
seems that its still in the engine, just marked as depreciated, very dissapointing

**Comment by TokageItLab** [comment]
We are currently working on final adjustments for the IK implementation https://github.com/godotengine/godot/pull/110120 in version 4.6. Also I am working on a major rewrite of the Skeleton3D documentation separately under the hood, so most issues should be resolved in 4.6.

**Comment by Bloxxel64** [comment]
Thanks and double thanks! I was especially having trouble discovering how on earth to use the skeleton stuff because it was undocumented. Thanks to you. Others won't have to share the same pain I experienced.

Also glad that the IK stuff is being reworked. Though I'm guessing you guys won't have 4.6 out in the next couple weeks so I'll have to keep trying to use something else for my game jam game until then.
