### ISSUE TITLE
Safari: zooming the docs site can permanently break it

### ISSUE THREAD

**Issue by jamesplease** [godotengine/godot-docs#8966]
**Your Godot version:** 4.2

**Issue description:** I believe I've found a bug where it is possible to permanently break the display of the site when performing certain zoom interactions in Safari on macOS. See the image below.

<img width="727" alt="image" src="https://github.com/godotengine/godot-docs/assets/2322305/66b8dd9e-0c5c-42ee-91a5-7080ee0954a9">

From what I can tell, when the site gets in this state, there is no way to resolve it. You have to make an entirely new tab.

Steps to reproduce:

Safari version: Version 17.3 (19617.2.4.11.8)
macOS version: Version 14.3 (23D56)

1. Open any Godot docs page in Safari on macOS. For example, [this one](https://docs.godotengine.org/en/stable/tutorials/rendering/multiple_resolutions.html#stretch-mode).
2. Zoom out a few times using the Cmd - keyboard shortcut. For the sake of exact reproducibility, go ahead and tap this hotkey three times.
3. Scroll the page to the right. (I'm using a two finger scroll gesture on a MacBook trackpad to scroll.) Observe that the content slides to the left, and cannot be scrolled back the other way. Observe that refreshing the page/zooming back in/etc. does not fix the problem.

I was not able to reproduce this in Chrome or Firefox.

Although I haven't fully diagnosed the exact source of the problem, I took a peek at `custom.js` and my suspicion is that some of the code there may be causing this problem. I'd love to dive in more and maybe open a PR to try and fix this, but it might be a more substantial refactor that takes me some time to get right. Before I invested the time I wanted to run it by y'all to see if you think this is something you're interested in reviewing. I'll be mindful to fix this issue without breaking the behavior of the script.

Also, to share some of my credentials (if it matters): I'm a Senior JavaScript Engineer at Netflix, and I specialize in implementing complex interfaces so that they work well for a global (cross-browser) audience. I'll thoroughly test the browser compatibility of any changes that I make (which you can of course verify) before I submit PRs.

Thanks for reading!

**Comment by tetrapod00** [comment]
Can you still reproduce this? I don't have access to macOS to test.

**Comment by jamesplease** [comment]
Can't repro. Will close. Thanks!

**Comment by jamesplease** [comment]
Ah yeah that issue does sound similar. Appreciate you following up on this one, @tetrapod00 🙂
