### ISSUE TITLE
Clarify Building Engine vs. Building Export Template in Compiling From Source

### ISSUE THREAD

**Issue by popcar2** [godotengine/godot-docs#8969]
**Your Godot version:** 4.2

**Issue description:** There are many areas in the "Compiling from source" section in the docs that misleadingly goes from compiling the editor to compiling the export templates without warning. 

The biggest offender is this line: `"If you are compiling Godot for production use, then you can make the final executable smaller and faster by adding the SCons option target=template_release."`

This note is directly placed after documentation for building the engine, but it doesn't clarify that it's for compiling Godot **the export template** and not Godot **the editor**. Aside from that note the entire documentation would benefit from separating the two since it's likely people are looking to compile one thing and not the other. Other people have thought the same: https://github.com/godotengine/godot/issues/76783#issuecomment-1537483191

![image](https://github.com/godotengine/godot-docs/assets/16920817/b6d7cf91-3858-4306-b10c-27fabe72f6a5)

**URL to the documentation page (if already existing):**

* https://docs.godotengine.org/en/stable/contributing/development/compiling/compiling_for_linuxbsd.html

* https://docs.godotengine.org/en/stable/contributing/development/compiling/compiling_for_windows.html

**Comment by Calinou** [comment]
`production=yes` implies `lto=full` on Linux, so the mention of `lto` should be modified as well. Also, `production=yes` and `lto=full` can be used with any build type, not just export templates.
