### ISSUE TITLE
Suggested Revisions to "First Look at Godot Editor" page

### ISSUE THREAD

**Issue by TesFalcon** [godotengine/godot-docs#8974]
**Your Godot version:**
4.2.1
[FirstLook_Revised.zip](https://github.com/godotengine/godot-docs/files/14300987/FirstLook_Revised.zip)

**Issue description:**
This page as it stands is poorly ordered and does not contain enough cross-links for a deeper dive into each item or topic. Attached is my rewrite of \<section id=\"id1\"\> in a more orderly format, but I don't know the editor or the documentation well enough to know if the topics I'm linking to are even documented at all.

**URL to the documentation page (if already existing):**
https://docs.godotengine.org/en/stable/getting_started/introduction/first_look_at_the_editor.html

**Comment by skyace65** [comment]
If you have any changes you'd like to make to the documentation please open a pull request in this repository. We do not review changed page files that have been attached to issues. If you're not familiar with Git and how to open a pull request we have a tutorial [here](https://docs.godotengine.org/en/stable/contributing/workflow/pr_workflow.html).
