### ISSUE TITLE
Add grab_focus method to LineEdit node docs

### ISSUE THREAD

**Issue by samuelbeard** [godotengine/godot-docs#8975]
**Your Godot version:**
4.2

**Issue description:**
The `grab_focus()` method is missing from the docs for the LineEdit class.

**URL to the documentation page (if already existing):**
https://docs.godotengine.org/en/stable/classes/class_lineedit.html

**Comment by AThousandShips** [comment]
This method isn't missing, it's [here](https://docs.godotengine.org/en/stable/classes/class_control.html#class-control-method-grab-focus)
