### ISSUE TITLE
Project files in 3D tutorial do not match engine version for 4.2.1

### ISSUE THREAD

**Issue by MarsAstro** [godotengine/godot-docs#8994]
**Your Godot version:** v4.2.1.stable.official

**Issue description:** The tutorial asks you to download project files and import them into your Godot Local Projects directory. When you download the assets from the given link and import the project, the engine says they are from a different version and asks you whether you want to convert them to 4.2.1 or not. There's no mention of this in the tutorial.

The tutorial will either have to be updated to include a part that walks the user through the popup dialog that asks about upgrading the projects engine version, or the project files linked to need to be updated so that the user is no longer asked to update the project upon import.

**URL to the documentation page (if already existing):** https://docs.godotengine.org/en/stable/getting_started/first_3d_game/01.game_setup.html

**Comment by SilverSilence** [comment]
I've been following the tutorial and my player character isn't moving. Could it be an issue that arose from me deciding to convert the whole project instead of just the godot file?

**Comment by tetrapod00** [comment]
Resolved by https://github.com/godotengine/godot-docs/pull/9482.
