### ISSUE TITLE
Clarify that `Sprite2D` funcs ignore transform of its nodes

### ISSUE THREAD

**Issue by dustdfg** [godotengine/godot-docs#8999]
**Your Godot version:**

4.2.1

**Issue description:**

The fact that functions `get_rect` and `is_pixel_opaque` of `Sprite2D` doesn't depend on transform of the node isn't obvious. Which is absolutely understandable for `get_rect` because it returns `Rect2` which is axis aligned by design but transform can contain skew and rotation. It seems to me (I didn't look at the code) that `is_pixel_opaque` works in such way because it wants to have "synced" with `get_rect` behaviour

**It isn't very obvious.** The  example for `get_rect`: `get_rect().has_point(to_local(event.position))` shows how to determine if sprite was clicked but if you will transform the node it will work as before like the node wasn't transformed. The same is for `is_pixel_opaque`.

I propose to clarify that the function doesn't depend on transform of the node.

1. For `is_pixel_opaque` I would mention that if the transform was applied to the node to achieve expected results you will need to do `is_pixel_opaque(<position> * self.transform)`.
2. For `get_rect`... It can't be easily transformed so I would just mention that it doesn't depend on transform. And one more thing: the example of determining if click was inside the sprite can be changed from `get_rect().has_point(to_local(event.position))` to `get_rect().has_point(to_local(event.position) * transfrom)`. Multiplying the local coordinate of the click by the transform will lead to correct results even if the node is transformed   

**URL to the documentation page (if already existing):**

https://docs.godotengine.org/en/latest/classes/class_sprite2d.html

**Comment by AThousandShips** [comment]
> The fact that functions get_rect and is_pixel_opaque of Sprite2D doesn't depend on transform of the node isn't obvious

`get_rect` mentions this already? So it is clear.
> Returns a Rect2 representing the Sprite2D's boundary in local coordinates. Can be used to detect if the Sprite2D was clicked.

Also the example code is correct, it should be just `to_local`, as it is in local coordinates, your suggested code would not work

**Comment by AThousandShips** [comment]
What do you mean by "it doesn't work but it is correct"? It's not correct, except that rects are transformed differently because of how they flatten

I.e. `(xform * my_rect).has_point(p)` doesn't necessarily mean `my_rect.has_point(p * xform)`, because the rect is a bounding box

It works generally, can't check your zip file at the moment could you add some screenshots?

**Comment by AThousandShips** [comment]
`to_local(pos) * transform` takes the position of the click in local space transformed inversely by the transform of the node relative to its parent, that makes no sense

Do you mean the global transform? That's still not valid

**Comment by dustdfg** [comment]
Ok. Let see two examples. I am not about global transform

1. Sprite2D without applied to it transform. We call `get_rect` and get `[P: (-64, -64), S: (128, 128)]`
2. We have similar Sprite2D but we applied to it transform. We translated it by 100 pixels in right direction. We call `get_rect` and we still get `[P: (-64, -64), S: (128, 128)]`

**Comment by dustdfg** [comment]
> I.e. `(xform * my_rect).has_point(p)` doesn't necessarily mean `my_rect.has_point(p * xform)`, because the rect is a bounding box
> 

Attempt to transform point leads to working **rotation, translate** but attempt to transform rectangle leads to working **translate, scale** (but only if applied only one of them). I understand it is bounding box but user must be warned it can give false positive results if Sprite2D was itself transformed. If I transform parent, everything works good but if I transform Sprite2D itself I endup clicks are handled not in the place I expect

**Comment by AThousandShips** [comment]
But it's local, so you expect to have it always return the same regardless if the sprite moves

Rects transform differently as I said, they transform so that all the four corners, when transformed, remain in the new rect

You can't rotate a rect, instead you grow it to fit

**Comment by AThousandShips** [comment]
For shear you can't use `to_local` though, it expects the transform to be affine, but you shouldn't transform a node in that way anyway I'd say
