### ISSUE TITLE
Add Information About the "AutoPlay on Load" Button to the AnimationPlayer Node's Documentation

### ISSUE THREAD

**Issue by amarraff** [godotengine/godot-docs#9000]
**Your Godot version:**
v4.2.1.stable.official [b09f793f5]

**Issue description:**
I was trying to play an animation for a node on ready, to avoid playing the animation in a script. I couldn't find the button for this, so I checked the docs. I didn't know the right wording to search (autoplay on load) so I didn't find what I was looking for. A user in the Godot community Discord was kindly able to explain where the button is: in the animation window, to the right of the clip. I hadn't ever interacted with this button, so I kept looking right past it.

I was able to find references to "autoplay on load" [here](https://docs.godotengine.org/en/stable/tutorials/animation/animation_tree.html#state-machine-travel) and [here](https://docs.godotengine.org/en/stable/getting_started/first_3d_game/09.adding_animations.html#animating-the-mobs), but none exist within the docs page for the AnimationPlayer itself. It mentions the autoplay property, but not how to autoplay an animation.

I propose one of these two solutions:
1.) Add a blurb underneath the AutoPlay property mentioning the "autoplay on load" button. Explain that you can accomplish autoplaying an animation without a script utilizing this button. Provide a picture, mention that it is in the animation window.
2.) Create a relevant entry for this feature, perhaps somewhere in [this section](https://docs.godotengine.org/en/stable/tutorials/animation/animation_track_types.html), and link to it underneath the AnimationPlayer node's autoplay property.

**URL to the documentation page (if already existing):**
https://docs.godotengine.org/en/stable/classes/class_animationplayer.html#class-animationplayer-property-autoplay

**Comment by skyace65** [comment]
The best place for this would actually be the introduction to the animation features page here: https://docs.godotengine.org/en/latest/tutorials/animation/introduction.html
