### ISSUE TITLE
MeshInstance2D documentation should include better instructions on color modification.

### ISSUE THREAD

**Issue by georgie-codes** [godotengine/godot-docs#9001]
**Your Godot version:**
4.1.2.stable

**Issue description:**
MeshInstance2D documentation **lacks clear guidance** on color modification, leading to potential **confusion with MeshInstance3D behavior.**

**Proposed amendment:**
"Unlike MeshInstance3D, the color of a MeshInstance2D cannot be directly modified through its material. To achieve color changes for a MeshInstance2D, use the Modulate property found under the 'Visibility' section of the Inspector."

**URL to the documentation page (if already existing):**
https://docs.godotengine.org/en/stable/classes/class_meshinstance2d.html

**Comment by skyace65** [comment]
I'm not sure if this is a good change to make for that class reference page. It's pointing out that an parameter exists in a class that MeshInstance2D inherits from, and we generally don't do those kinds of notes in the class reference. Also, the same thing applies Sprite2D and AnimatedSprite2D nodes, and I don't think we should be adding this to those pages as well.
