### ISSUE TITLE
Array.resize() doesn't mention typed arrays

### ISSUE THREAD

**Issue by thiagola92** [godotengine/godot-docs#9005]
**Your Godot version:** v4.2.1.stable.official [b09f793f5]

**Issue description:**  
It's silly to report this but this is incorrect when the array has type:  

> If the array size is smaller, elements are cleared, if bigger, new elements are `null`.

They receive the initialization value for their type.  
```gdscript
var a = []
var b: Array = []
var c: Array[bool] = []
var d: Array[int] = []
var e: Array[float] = []
var f: Array[String] = []
var g: Array[Array] = []
var h: Array[Dictionary] = []

a.resize(1)
b.resize(1)
c.resize(1)
d.resize(1)
e.resize(1)
f.resize(1)
g.resize(1)
h.resize(1)

printt("a", a)
printt("b", b)
printt("c", c)
printt("d", d)
printt("e", e)
printt("f", f)
printt("g", g)
printt("h", h)
```

Result:
```
a	[<null>]
b	[<null>]
c	[false]
d	[0]
e	[0]
f	[""]
g	[[]]
h	[{  }]
```

**URL to the documentation page:**  
https://docs.godotengine.org/en/latest/classes/class_array.html#class-array-method-resize

**Comment by Mickeon** [comment]
I was about to say that https://github.com/godotengine/godot/pull/69451 would've solved it but even there it mentions null so I can keep this one in mind soon.

**Comment by thiagola92** [comment]
> any `null` Variant is forced to convert, the result is what you see in the code sample above. Still, worth specifying.

Hmmm interesting... I was going to guess that was calling something like `type_convert()` but it seems not.  
```gdscript
var c: Array[bool] = [type_convert(null, TYPE_BOOL)]
var d: Array[int] = [type_convert(null, TYPE_INT)]
var e: Array[float] = [type_convert(null, TYPE_FLOAT)]
var f: Array[String] = [type_convert(null, TYPE_STRING)]
var g: Array[Array] = [type_convert(null, TYPE_ARRAY)]
var h: Array[Dictionary] = [type_convert(null, TYPE_DICTIONARY)]

printt("c", c)
printt("d", d)
printt("e", e)
printt("f", f)
printt("g", g)
printt("h", h)
```

Because `null` is converted to `"<null>"` instead of empty string like `resize()` does.
```
c	[false]
d	[0]
e	[0]
f	["<null>"]
g	[[]]
h	[{  }]
```

**Comment by Mickeon** [comment]
Well, actually, it may be more appropriate to say `resized` fills the array with the "default" for the given type. In other words it's the same value as an empty constructor for the type (except Object).

All of those `type_convert` are somewhat failing and returning the default as well, except the String conversion which does exist.

**Comment by thiagola92** [comment]
I should have read `type_convert` :laughing:  
Well, everything make sense, thank you for the attention!
