### ISSUE TITLE
Singletons (AutoLoad) example project outdated

### ISSUE THREAD

**Issue by johannesgunnar** [godotengine/godot-docs#902]
Over at [Singletons (Autoload) for Godot 3](http://docs.godotengine.org/en/latest/learning/step_by_step/singletons_autoload.html?highlight=singletons%20autoload) the [example download](http://docs.godotengine.org/en/latest/_downloads/autoload.zip) does not follow the example code and instructions in the documentation. The example project is still Godot 2 based, while the documentation has been updated for Godot 3.

Problems

- project example uses .scn files while the example code on the page talks about .tscn.
- project example does not have project.godot file / project example has not been converted to Godot 3

See the linked [QA thread](https://godotengine.org/qa/21209/singletons-autoload-documentation-incorrect-or-outdated?show=21209#q21209) for more information.

**Comment by mhilbrunner** [comment]
Fixed by Supersed by https://github.com/godotengine/godot-docs/pull/1481
