### ISSUE TITLE
Calling GD.Seed() Makes my C# Project Freeze Everytime I Try to Build it

### ISSUE THREAD

**Issue by iLoveJohnFish** [godotengine/godot-docs#9030]
**Your Godot version:**
4.2.1 stable mono

**Issue description:**
Without changing anything from my working code. When I try to call GD.Seed(12345) in my _Ready function of the script attached to the root node of the scene, my project goes from building and playing too (Not Responding) forever.

I've tried building the project after commenting out the GD.Seed() bit, and it goes back to working.

I'm not sure if this is an engine issue or a me issue, but I haven't really found anything online so far about this so I thought I'd post it here and hopefully find a resolution.

The issue isn't super pressing though because I'm just going to use the built in Random class for C#

**URL to the documentation page:**
https://docs.godotengine.org/en/stable/tutorials/math/random_number_generation.html

**Comment by skyace65** [comment]
This is not the place to post if you're looking for help with something, this is only for issues with engine documentation. Your best bet is to ask in one of the community locations, you can find a list of those [here](https://godotengine.org/community/). That said I just tried building a C# project with GD.Seed() in the ready function of a script in 4.2.1 and it worked without any issues. Might be related to something you're doing with your code. Again, ask around in one of the community locations.

**Comment by iLoveJohnFish** [comment]
It was 100% a me thing, after poking around my code for a while I found a while loop that was using Random to do some stuff.

Long story short, certain seeds made the loop infinite. Lesson learned, I probably should hard code loop limits into my while loops so that they always terminate when unsuspected behaviour comes up.
