### ISSUE TITLE
CompressedTexture2DArray always returning null image from any layer

### ISSUE THREAD

**Issue by Likaos** [godotengine/godot-docs#9031]
**Your Godot version:**
4.2.2 but any version from 4.0+

**Issue description:**
I'm using a CompressedTexture2DArray for shaders, everything works in game, I'm trying to get images from that resource in code to make a map editor, the layers and object info are correct (using gdscript or c#) but when I try to get images from it the result is always null

Code example:

```
GD.Print("Textures layers = " + _textures.GetLayers() + " width = " + _textures.GetWidth() + " height = " + _textures.GetHeight() + " dataType = " + _textures.GetLayeredType()
                 + " format = " + _textures._GetFormat());       
        for (int i = 0; i < _textures.GetLayers(); i++)
        {
            var layer = _textures.GetLayerData(i);
            GD.Print("Layer " + i + " = " + (layer == null ? " null" : " not null"));
        }
```
        
Code result:

`Textures layers = 16 width = 16 height = 16 dataType = Type2DArray format = L8
Layer 0 =  null
Layer 1 =  null
Layer 2 =  null
Layer 3 =  null
Layer 4 =  null
Layer 5 =  null
Layer 6 =  null
Layer 7 =  null
Layer 8 =  null
Layer 9 =  null
Layer 10 =  null
Layer 11 =  null
Layer 12 =  null
Layer 13 =  null
Layer 14 =  null
Layer 15 =  null`

Used image
![texture_array](https://github.com/godotengine/godot-docs/assets/755766/a1604bd0-c960-4551-9341-bed3aacdacba)

Editor imported image used as [Export]
![image](https://github.com/godotengine/godot-docs/assets/755766/6c616a5b-f52c-45dd-8ed2-63154015c90c)

Import settings
![image](https://github.com/godotengine/godot-docs/assets/755766/64c192c7-2f2d-4589-8859-d7d6e1906030)

**URL to the documentation page:**
https://docs.godotengine.org/fr/4.x/classes/class_compressedtexture2darray.html

**Comment by Likaos** [comment]
[get_data_layer.zip](https://github.com/godotengine/godot-docs/files/14452856/get_data_layer.zip)
Added simple project with last stable version and gdscript

**Comment by clayjohn** [comment]
Thank you for the report. The problem here is that reading back layers from Texture2DArrays is only supported in the Mobile and Forward+ backends when using Godot 4.2. 

We just added support to our development branch 3 weeks ago and we will backport that support to 4.2 shortly. It should be in 4.2.2 or 4.2.3 and it already works in 4.3-dev4.
