### ISSUE TITLE
Missing doc on raw string literals

### ISSUE THREAD

**Issue by Turtyo** [godotengine/godot-docs#9039]
**Your Godot version:**

4.2.stable.official.46dc27791

**Issue description:**

When checking the Regex page of the doc, there is a mention of being able to use raw string literals (r-string), but I searched the doc and didn't find more information about r-string and what can be done with them in Godot.
I know it's a standard thing in programming for escape sequences, but for example I don't know if I can convert a String to a raw string
I have a loop variable that is a string and was trying to add that to a r-string to do some regex, but turns out it's not possible (or it doesn't work as I expect it to, because I don't get a compiler error).

Edit : it thought I couldn't add a string and a r-string just because i can't write properly... I still think a little bit of doc on raw string would be nice.

**URL to the documentation page (if already existing):**

The only place I know referencing raw string literals is the [RegEx page](https://docs.godotengine.org/en/stable/classes/class_regex.html) : `In GDScript, you can also use raw string literals (r-strings). For example, compile(r'"(?:\\.|[^"])*"') would be read the same.`

**Comment by AThousandShips** [comment]
They're not missing, they're right [here](https://docs.godotengine.org/en/stable/tutorials/scripting/gdscript/gdscript_basics.html#literals)

**Comment by Turtyo** [comment]
Oh, well I guess i'm just blind.
Good first issue from me on the repo :laughing: 

Thanks @AThousandShips !

**Comment by AThousandShips** [comment]
As long as the issue is resolved it's all a good day :) the GDScript docs are a bit hard to navigate, see:
* https://github.com/godotengine/godot-docs/issues/5701

So you're not alone
