### ISSUE TITLE
Confusing part in the step by step guide

### ISSUE THREAD

**Issue by JONITOKING** [godotengine/godot-docs#9048]
**Your Godot version:**
4.2.1
**Issue description:**
The tutorial has the function _on_button_pressed() in C# as OnButtonPressed() but that doesn't work in the engine. It's in the part where they talk about stopping the _Process() function.
**URL to the documentation page:**
https://docs.godotengine.org/en/stable/getting_started/step_by_step/signals.html

**Comment by raulsntos** [comment]
PascalCase is the .NET naming convention for methods, this is mentioned in other pages of the documentation:

- [C# basics / General differences between C# and GDScript](https://docs.godotengine.org/en/stable/tutorials/scripting/c_sharp/c_sharp_basics.html#general-differences-between-c-and-gdscript)
- [C# style guide / Naming conventions](https://docs.godotengine.org/en/stable/tutorials/scripting/c_sharp/c_sharp_style_guide.html#naming-conventions)
- [Your first 2D Game / Creating the player scene / Node structure](https://docs.godotengine.org/en/stable/getting_started/first_2d_game/02.player_scene.html#node-structure)
  ![image](https://github.com/godotengine/godot-docs/assets/3903059/9dd3acfc-64ac-4d43-aaf4-d5f2f674c9d6)

It looks like the code snippets in the _Your first 3D game_ tutorial use this pattern where they add a comment to these methods, to clarify that the name of the method must also be supplied in PascalCase in the signal connection dialog. Here's an example from [Your first 3D Game / Designing the mob scene / Leaving the screen](https://docs.godotengine.org/en/stable/getting_started/first_3d_game/04.mob_scene.html#leaving-the-screen):

```csharp
// We also specified this function name in PascalCase in the editor's connection window
private void OnVisibilityNotifierScreenExited()
{
    QueueFree();
}
```

We can probably reuse this pattern in other C# code snippets where the method will be used as a signal callback to remind users that the name of the method specified in the signal connection dialog needs to match the name of the method defined in your script (regardless of the language you use).

**Comment by paulloz** [comment]
I believe the issue with writing content in code comments is they aren't included in the translation process, right?

**Comment by skyace65** [comment]
> I believe the issue with writing content in code comments is they aren't included in the translation process, right?

Correct, but I feel like doing a note for every code snippet this applies to feels excessive. especially since we can't make notes only show if you're using C# tabs. That said I'll defer to what others want to do and implement it.

**Comment by raulsntos** [comment]
> Correct, but I feel like doing a note for every code snippet this applies to feels excessive.

That's what I was thinking too. Since we already have notes about this in the _C# basics_ documentation page, and at the beginning of the _Your first 2D Game_ tutorial, I didn't think it was necessary to repeat ourselves but I thought it may be OK to add a comment only as a reminder since we do a bit more hand-holding in the getting started tutorials.

Notably we don't have a note in the _Your first 3D Game_ tutorial, we could add one but you're supposed to have read the 2D tutorial first so maybe it's redundant.
