### ISSUE TITLE
"Size and Anchors" UI tutorial still uses margins

### ISSUE THREAD

**Issue by MichaelJBerk** [godotengine/godot-docs#9055]
**Your Godot version:**
4.2

**Issue description:**
The "Size and Anchors" tutorial page still references the Margin properties on controls, despite margins being replaced by 
anchor offsets in Godot 4

**URL to the documentation page:**
https://docs.godotengine.org/en/stable/tutorials/ui/size_and_anchors.html

**Comment by AThousandShips** [comment]
It is in fact already tracked on the tracker:
* https://github.com/godotengine/godot-docs/issues/5121

Consolidating there, thank you for your report
