### ISSUE TITLE
Update how to use `pre-commit`

### ISSUE THREAD

**Issue by luevano** [godotengine/godot-docs#9063]
**Your Godot version:**
NA

**Issue description:**
Current documentation still refers to using the `pre-commit` hook found in `misc/hooks` which doesn't exist anymore as it was changed by: https://github.com/godotengine/godot/pull/88866. More info: https://github.com/godotengine/godot/issues/88901.

**URL to the documentation page:**
I've only found references here:

- https://docs.godotengine.org/en/latest/contributing/development/code_style_guidelines.html#pre-commit-hook
- https://docs.godotengine.org/en/latest/contributing/development/code_style_guidelines.html#id3

**Comment by AndersonMartins1** [comment]
ara resolver o problema com a documentação do Godot Engine que faz referência a um gancho de pré-compromisso que não existe mais no local esperado, siga estas etapas:

Localize o Novo Local do Gancho de Pré-compromisso:
Pesquise no repositório do Godot Engine para encontrar o novo local do gancho de pré-compromisso. Você pode fazer isso examinando o histórico de commits, procurando por referências ao gancho de pré-compromisso ou perguntando na comunidade do Godot Engine.

Atualize os Links na Documentação:
Uma vez que você tenha encontrado o novo local do gancho de pré-compromisso, atualize os links na documentação para apontar para esse local. Isso pode envolver editar os arquivos markdown relevantes que mencionam o gancho de pré-compromisso e substituir os URLs antigos pelos novos.

Revise e Atualize as Informações:
Se necessário, revise e atualize qualquer outra informação ou instruções relacionadas ao gancho de pré-compromisso para garantir que estejam precisas e atualizadas com as mudanças.

Envie uma Solicitação de Pull:
Depois de fazer as alterações necessárias na documentação, envie uma solicitação de pull para o repositório do Godot Engine com suas atualizações. Certifique-se de incluir uma descrição clara das alterações que você fez e por que elas são necessárias.

Acompanhe e Resolva Comentários:
Fique de olho na sua solicitação de pull e responda a quaisquer comentários ou solicitações de alterações feitas pelos revisores. Isso garantirá que suas alterações sejam revisadas e mescladas com sucesso.

Verifique a Implantação das Alterações:
Após a mesclagem da sua solicitação de pull, verifique a documentação publicada para garantir que as alterações foram implementadas corretamente e que os links agora apontam para o novo local do gancho de pré-compromisso.

Seguindo estas etapas, você poderá resolver o problema com a documentação do Godot Engine e garantir que as informações estejam atualizadas e precisas para os usuários.

**Comment by kaixin-hc** [comment]
I'd like to do this!
