### ISSUE TITLE
Missing examples in documentation.

### ISSUE THREAD

**Issue by bukowa** [godotengine/godot-docs#9064]
**Your Godot version:**
`4.2.1`

**Issue description:**
Hello I think some examples would be cool in docs, for example how to use the given class:
```godot
var timer = ...
```

**URL to the documentation page (if already existing):**
https://docs.godotengine.org/en/stable/classes/class_timer.html

**Comment by skyace65** [comment]
The timer node documentation was updated in https://github.com/godotengine/godot/pull/87436, to see it on the web just choose the latest version of the docs. We're not going to add any more code examples for that node due to how self explanatory it is.
