### ISSUE TITLE
"Compiling for X11" instructions for Mageia are missing 2 packages 

### ISSUE THREAD

**Issue by HummusSamurai** [godotengine/godot-docs#907]
There are two missing packages needed for Godot 3 that are not present on a fresh Mageia install, and they are not handled by the one-liner in the latest development docs.

- `gcc-c++` for the error:"g++ command not found
- `libgomp-devel` for the error: omp.h not found (in linking /thirdparty/tinyexr)

**Comment by StraToN** [comment]
Would this work?

`urpmi scons pkgconfig libffmpeg-devel libgomp-devel "pkgconfig(alsa)" "pkgconfig(freetype2)" "pkgconfig(glu)" "pkgconfig(libpulse)" \ 
"pkgconfig(openssl)" "pkgconfig(udev)" "pkgconfig(x11)" "pkgconfig(xcursor)" "pkgconfig(xinerama)"\
"pkgconfig(xi)" "pkgconfig(xrandr)" "pkgconfig(zlib)"`

**Comment by HummusSamurai** [comment]
Yes that should fix the `libgmop-devel` issue.

I already have it installed so I won't be testing it.

**Comment by vnen** [comment]
I believe OpenMP was dropped, so it isn't needed anymore.

**Comment by StraToN** [comment]
Ok then:
```
urpmi scons pkgconfig libffmpeg-devel "pkgconfig(alsa)" "pkgconfig(freetype2)" "pkgconfig(glu)" "pkgconfig(libpulse)" \ 
"pkgconfig(openssl)" "pkgconfig(udev)" "pkgconfig(x11)" "pkgconfig(xcursor)" "pkgconfig(xinerama)" \
"pkgconfig(xi)" "pkgconfig(xrandr)" "pkgconfig(zlib)"
```
should do. Ok for you @akien-mga ?

**Comment by akien-mga** [comment]
ffmpeg is not needed, all the other ones are listed already.

I'm not sure about adding details on how to install a basic C++ compilaton environment (would be `task-c++-devel` on Mageia) as it's not really related to Godot, it's more "howto compile stuff on Linux".

**Comment by StraToN** [comment]
@akien-mga 
I've been looking at some other projects' documentation concerning g++. Some add the related meta-package in their one-liners (see [OpenMW](https://wiki.openmw.org/index.php?title=Development_Environment_Setup#Fedora_Workstation) for example). Others simply state they will need it but don't include it in the one-liner. 

Depending on the one-liner goal, we can do both. My personal opinion is that I appreciate the one-liner to include all requirements, including the obvious (but essential) ones such as the compiler. This saves me a few minutes on a freshly installed distribution.

No other modification is needed if libgomp requirement is not anymore.

**Comment by mhilbrunner** [comment]
Fixed by https://github.com/godotengine/godot-docs/commit/4574161a7e96b920180ace14ee0facefe1287a53
