### ISSUE TITLE
Should be made clear that classes marked with GlobalClass must be named the same as their file

### ISSUE THREAD

**Issue by SolidSnackDrive** [godotengine/godot-docs#9083]
**Your Godot version:**
4.2 Stable
**Issue description:**
The C# attribute [GlobalClass] which is used to mark classes which should be made available within the editor's Node selection dialogues does not work correctly unless the class name matches the file it's in. I'm not sure whether this is considered a bug or expected behaviour, but either way I think the documentation should indicate this limitation. It's difficult to determine what the issue is in this case since the project will still build without issue and the editor gives no indication as to why the class or derived classes are not available.
**URL to the documentation page (if already existing):**
https://docs.godotengine.org/en/stable/tutorials/scripting/c_sharp/c_sharp_global_classes.html

**Comment by AThousandShips** [comment]
This isn't specific to these, it applies to all classes, and is documented [here](https://docs.godotengine.org/en/stable/tutorials/scripting/c_sharp/c_sharp_basics.html#example)
