### ISSUE TITLE
3D Tutorial "Squash the creeps", Animation tutorial out of date

### ISSUE THREAD

**Issue by PA7K** [godotengine/godot-docs#9085]
Godot version: 4.3 dev3 win64

In [this part of the Tutorial](https://docs.godotengine.org/en/stable/getting_started/first_3d_game/09.adding_animations.html) we learn some quick and simple animation. 
After animating the "Player", the tutorial asks us to copy and paste the animation to the "Mob".

"
Open the Player scene, select the AnimationPlayer node and open the "float" animation. Next, click on Animation > Copy. Then open mob.tscn, create an AnimationPlayer child node and select it. Click Animation > Paste and make sure that the button with an "A+" icon (Autoplay on Load) and the looping arrows (Animation looping) are also turned on in the animation editor in the bottom panel. That's it; all monsters will now play the float animation.
"

In the my version of Gdot, there is no "Copy" behind the "Animation" button. The closest thing is the "Dublicate...", but this requires additional steps, which the documentation does not explain.

Im just a newbie, but the current method of copy n paste is (as far as i have figured it out) :
-duplicate the animation
-go to manage animation
-click the tiny unmarked button left of the "[build-in]" text
-go to the mob scene
-create the node
-go to manage animation
-click the tiny unmarked clipboard to the right of the folder, to the right of the +, to the right of "[Global]"

Please update the segment I copied above

URL to the documentation page: https://docs.godotengine.org/en/stable/getting_started/first_3d_game/09.adding_animations.html

**Comment by skyace65** [comment]
This was fixed by #8955, that PR just needs to be cherry picked.
