### ISSUE TITLE
PBM format for Click masks is not documented

### ISSUE THREAD

**Issue by nylnook** [godotengine/godot-docs#909]
For Click Masks in TextureButtons, Godot do not document which [specific sub-format](https://en.wikipedia.org/wiki/Netpbm_format) is expected (ASCII, binary, which key, how to produce it).

This is causing errors : https://github.com/godotengine/godot/issues/14828
See also https://github.com/godotengine/godot/issues/14700 for a sum-up in and a minimal project example

**Comment by reduz** [comment]
this is not a bug, you need to use pbm, not pnm. If you try to use pnm it wil fail.

**Comment by nylnook** [comment]
As explained in  https://github.com/godotengine/godot/issues/14828, we are speaking about PBM... and it is not documented at all... please reopen !

**Comment by nylnook** [comment]
For example, If I choose to export to PBM in Gimp, I have to choose between binary and ASCII format.
Which one should I choose for Godot ? No idea and no documentation ... even if PBM suggest binary.

![capture d ecran_2017-12-26_17-50-17](https://user-images.githubusercontent.com/456282/34360898-6d45e43e-ea65-11e7-98c6-3e16b1400fe1.png)

(I know the dialog is entitled with PNM, but I'm exporting PBM, try it yourself... see how much it is confusing ?)

**Comment by reduz** [comment]
PBM format is now gone, you can instead import an image as bitmap
