### ISSUE TITLE
Docs is not visible on  web

### ISSUE THREAD

**Issue by rudransh61** [godotengine/godot-docs#9091]
**Your Godot version:**
Its on Website
**Issue description:**
The website text is not visible 
**URL to the documentation page:**
https://docs.godotengine.org/en/stable/tutorials/physics/physics_introduction.html#:~:text=In%20order%20to%20detect%20collisions,directly%20in%20the%20editor%20workspace.
If you know how to fix the issue you are reporting please
consider opening a pull request. We provide a tutorial on
using git here: https://docs.godotengine.org/en/stable/community/contributing/pr_workflow.html,
writing documentation at https://docs.godotengine.org/en/stable/community/contributing/docs_writing_guidelines.html
and contributing to the class reference here: https://docs.godotengine.org/en/stable/community/contributing/updating_the_class_reference.html

![Screenshot 2024-03-13 152737](https://github.com/godotengine/godot-docs/assets/115872354/6fc3aea8-d9d3-499d-98c1-01d3696f03ed)

**Comment by AThousandShips** [comment]
This has been solved and will be fixed in stable too, see:
* https://github.com/godotengine/godot-docs/issues/4790
