### ISSUE TITLE
First game images doesn't match the values entered

### ISSUE THREAD

**Issue by survivant** [godotengine/godot-docs#910]
in the page : godot-docs/learning/step_by_step/your_first_game.rst

the image : /learning/step_by_step/img/player_scene_nodes.png

it should be : CollisionShape2D

and
/learning/step_by_step/img/add_script_button.png

Sprite should be : AnimatedSprite

**Comment by survivant** [comment]
![image](https://user-images.githubusercontent.com/191879/34186535-5b7e01fc-e4fa-11e7-9cc6-3a3193afe935.png)

**Comment by survivant** [comment]
You ask to named to visibility node to : VisibilityNotifier2D (named Visibility)

but later when you connect the signal you have the method name that doesn't match

it should be
func _on_Visibility_screen_exited():
	queue_free()

**Comment by survivant** [comment]
you could show where to enable to snap grid mode
![image](https://user-images.githubusercontent.com/191879/34187418-3e0325da-e4ff-11e7-86db-d6d55d209ef7.png)

**Comment by cbscribe** [comment]
Thanks for the suggestions! I'm doing a revision on this tutorial now to reflect a few things that have changed since it was written.

**Comment by cbscribe** [comment]
Fixed by #956
