### ISSUE TITLE
Indirect inheritance

### ISSUE THREAD

**Issue by dustdfg** [godotengine/godot-docs#9104]
**Your Godot version:**

4.2

**Issue description:**

In the description of the `ClassDB.get_parent_class` method I found term **indirect inheritance** AFAIK godot doesn't have traits or multiple inheritance (or have?). Anyway I tried to find out what it means but couldn't. So my proposal is to add description of **indirect inheritance** if it exist and add the link to the description of `ClassDB.get_parent_class`

**URL to the documentation page (if already existing):**

https://docs.godotengine.org/en/4.2/classes/class_classdb.html#class-classdb-method-get-inheriters-from-class

**Comment by AThousandShips** [comment]
There's no such word there? The text is just:
> Returns the parent class of `class`.

Did you mean some *other* function?

**Comment by dustdfg** [comment]
> Do you mean `get_inheriters_from_class`? That is:

Yeah, the link points there

>Which means "either classes who inherits from class, or classes inheriting from a class inheriting from class", so "parent" vs "grandparent"

Ahh, I thought about something less linear... Sorry...

**Comment by dustdfg** [comment]
I understood my mistake with `ClassDB.get_parent_class` it was copied before and it was not the right name...
