### ISSUE TITLE
InputEventMIDI is incorrectly written InputEventMidi (upper case MIDI instead of Midi)

### ISSUE THREAD

**Issue by Phibonacci** [godotengine/godot-docs#9120]
**Your Godot version:**
4.2.1

**Issue description:**
The `InputEventMIDI` type [in the doc](https://docs.godotengine.org/fr/4.x/classes/class_inputeventmidi.html) is actually called `InputEventMidi`. This is a minor mistake and IDE will easily spot it but the example code is invalid for this reason.

**URL to the documentation page:**

https://docs.godotengine.org/fr/4.x/classes/class_inputeventmidi.html

*I'll open a pull request myself later eventually  if I find the time.*

**Comment by AThousandShips** [comment]
Where is it called that? Do you mean in C#?

**Comment by Phibonacci** [comment]
Yes, I should have mentioned this. I used C# exclusively.
