### ISSUE TITLE
$HUD.game_over() in incorrectly written $HUD.show_game_over() in the doc

### ISSUE THREAD

**Issue by serdelcaroch17** [godotengine/godot-docs#9127]
**Your Godot version:**
4.2

**Issue description:**
Function calling is incorrectly spelled in the[ doc](https://docs.godotengine.org/en/stable/getting_started/first_2d_game/06.heads_up_display.html)
It should be $HUD.game_over() instead of $HUD.show_game_over()
The creation the function is defined a page earlier in the doc

**URL to the documentation page (if already existing):**
[link](https://docs.godotengine.org/en/stable/getting_started/first_2d_game/06.heads_up_display.html)

**Comment by AThousandShips** [comment]
What to you mean? It's defined as:
```gdscript
func show_game_over():
	show_message("Game Over")
	# Wait until the MessageTimer has counted down.
	await $MessageTimer.timeout

	$Message.text = "Dodge the Creeps!"
	$Message.show()
	# Make a one-shot timer and wait for it to finish.
	await get_tree().create_timer(1.0).timeout
	$StartButton.show()
```

**Comment by serdelcaroch17** [comment]
oops my bad, I didnt follow the naming convention of the doc, 
Closing issue

**Comment by serdelcaroch17** [comment]
oops my bad, I didnt follow the naming convention of the doc, 
Closing issue
