### ISSUE TITLE
AStarGrid2D get_point_path would return a  PackedVector -> 3 <- Array

### ISSUE THREAD

**Issue by brandtware** [godotengine/godot-docs#9136]
**Your Godot version:**
4.2

**Issue description:**
The docs for AStar2D say that they would return a PackedVector3Array while inside a thread but the typing for that function is PackedVector2Array

**URL to the documentation page:**
https://docs.godotengine.org/en/stable/classes/class_astargrid2d.html#class-astargrid2d-method-get-point-path

https://github.com/godotengine/godot/pull/89862

**Comment by brandtware** [comment]
As mentioned in the closed PR the bug was already fixed in the main-repo 3 years ago, but the typo is still online o_o

**Comment by AThousandShips** [comment]
It isn't fixed, see the code :) It's right here:
```xml
		<method name="get_point_path">
			<return type="PackedVector2Array" />
			<param index="0" name="from_id" type="Vector2i" />
			<param index="1" name="to_id" type="Vector2i" />
			<description>
				Returns an array with the points that are in the path found by [AStarGrid2D] between the given points. The array is ordered from the starting point to the ending point of the path.
				[b]Note:[/b] This method is not thread-safe. If called from a [Thread], it will return an empty [PackedVector3Array] and will print an error message.
			</description>
		</method>
```

**Comment by AThousandShips** [comment]
If you are unable to find how to solve this I can make a PR fixing this typo, but it's not fixed

**Comment by brandtware** [comment]
Ok, I think I got it right this time. New PR under https://github.com/godotengine/godot/pull/89862
First time contributer, still learning
