### ISSUE TITLE
Typo: ```EditorExportPlugin._get_export_options```'s return type is ```Array[Dictionary]``` not ```Dictionary```

### ISSUE THREAD

**Issue by NovaDC** [godotengine/godot-docs#9140]
**Your Godot version:**
Stable branch of docs

**Issue description:**
I found a small typo in the docs that confused me for a bit, before [searching around here on Github](https://github.com/search?q=EditorExportPlugin+language%3AGDScript+&type=code) for some active examples. It appears ```EditorExportPlugin._get_export_options```'s return type is ```Array[Dictionary]``` not ```Dictionary```.

**URL to the documentation page:**
[https://docs.godotengine.org/en/stable/classes/class_editorexportplugin.html#class-editorexportplugin-private-method-get-export-options](https://docs.godotengine.org/en/stable/classes/class_editorexportplugin.html#class-editorexportplugin-private-method-get-export-options)

**Comment by AThousandShips** [comment]
What's the issue here? It says correctly that it returns this, namely `Dictionary[]`, and says in the text:
> Returns the object's property list as an Array of dictionaries

Where does it say it returns a dictionary?

**Comment by NovaDC** [comment]
![image](https://github.com/godotengine/godot-docs/assets/164206531/321a0ca2-9e86-404e-851e-f42bab0e6677)


To be more clear the typo I was referencing to was the type that was listed in the heading of the method.
While it is written in the description that it is supposed to return a array of dictionaries, the heading contradicts this and may cause confusion.

Also I did link to the wrong method. It was supposed to be [https://docs.godotengine.org/en/stable/classes/class_editorexportplugin.html#class-editorexportplugin-private-method-get-export-options](https://docs.godotengine.org/en/stable/classes/class_editorexportplugin.html#class-editorexportplugin-private-method-get-export-options), however it appears this typo exists in the other method I linked as well. Either way I fixed the link now.

**Comment by AThousandShips** [comment]
There's no typo, it doesn't say it returns `Dictionary` it's returning an array of dictionaries, it's just written differently, `Dictionary[]` is an array of dictionaries, see the latest docs and they use the GDScript style instead, so there's no issue there, no typo

**Comment by skyace65** [comment]
Closing per AThousandShips comment.
