### ISSUE TITLE
VideoStreamPlayer Error

### ISSUE THREAD

**Issue by Linsugar** [godotengine/godot-docs#9142]
When I use videosteamPlayer to play ffmpg and convert mp4 to ogv format, I run the game, and after playing the video, the game is directly stuck.  I have this problem on 4.2.1windows version, may I ask if you have found it

**Comment by AThousandShips** [comment]
This is for reporting bugs with the documentation, for bugs in the engine please open an issue [here](https://github.com/godotengine/godot/issues), but I'd suggest you first ask in the [forums](https://forum.godotengine.org/) to make sure you've not made a mistake in converting
