### ISSUE TITLE
Suggestion for expansion/clarification of documentation regarding "Attached C# scripts must refer to a class that has a class name that matches the file name" gotcha

### ISSUE THREAD

**Issue by Halfmanification** [godotengine/godot-docs#9145]
**Your Godot version:**
v4.2.1.stable.mono.official [b09f793f5]

**Issue description:**
Suggestion for slight clarification/expansions of known gotchas in the c# development documentation. I suggest rewriting:

"Attached C# scripts should refer to a class that has a class name that matches the file name."

to

"Attached C# scripts must refer to a class that has a class name that matches the file name. No error will be raised in the editor or the script if this is not the case, but certain features of the script will not work. For example; exported fields and properties will not appear in the editor if the name of the class does not match the file name."

Hopefully this can, over time, direct more people to this page when they google "Export variables not working" or similar queries.

**URL to the documentation page (if already existing):**
https://docs.godotengine.org/en/stable/tutorials/scripting/c_sharp/c_sharp_basics.html#current-gotchas-and-known-issues

**Comment by skyace65** [comment]
Generally if you want something rephrased, and you know exactly what you want, we'd recommend creating a pull request yourself. If you're not familiar with Git and how to do that we have a guide [here](https://docs.godotengine.org/en/stable/contributing/workflow/pr_workflow.html).
