### ISSUE TITLE
Outdated Doc ：const array is not "flat" in 4.2

### ISSUE THREAD

**Issue by rt9391** [godotengine/godot-docs#9154]
**Your Godot version:**
4.2
**Issue description:**
![image](https://github.com/godotengine/godot-docs/assets/91177204/9e6f7777-4a6a-4148-ad02-b11b6bed7fa1)
![image](https://github.com/godotengine/godot-docs/assets/91177204/017b48bf-0da7-4bf8-b4fc-8740a1107c2b)
![image](https://github.com/godotengine/godot-docs/assets/91177204/215162b3-50f2-41f8-8376-9c9297e1c4c3)
You cannot append the element to this const array.
In 3.5 as I tested it, you can change this array, add elements, etc.
**URL to the documentation page:**
https://docs.godotengine.org/en/stable/tutorials/scripting/gdscript/gdscript_basics.html

**Comment by HolonProduction** [comment]
Fixed by #9407

**Comment by AThousandShips** [comment]
Closing as per above
