### ISSUE TITLE
Outdated documentation

### ISSUE THREAD

**Issue by ricardo-nl** [godotengine/godot-docs#9160]
**Your Godot version:** 4.2.1

**Issue description:** Documentation outdated

**URL to the documentation page:** https://docs.godotengine.org/en/stable/getting_started/step_by_step/signals.html

Where you read:

```
_func_ready():
	var timer = get_node("Timer")
	timer.timeout.connect(_on_timer_timeout)
```
	
Shoud be:

```
_func_ready():
	var timer = get_node("Timer")
	timer.connect("timeout", Callable(self, "_on_timer_timeout"))
```

**Comment by dukeman74** [comment]
Both of these are valid (aside from the _)
further I guess there are now 4 valid ways
node.signal.connect(func)
node.connect("signal",func)
node.signal.connect(Callable(scope,"func"))
node.connect("signal",Callable(scope,"func"))

I suppose this could be made clear in the docs, but I'm curious as for reasons to use that most verbose one.
I always use the first method I listed, but that is just what makes sense to me.

**Comment by AThousandShips** [comment]
This is explained [here](https://docs.godotengine.org/en/stable/classes/class_object.html#class-object-method-connect)

The documentation isn't outdated, that's the correct way

If it doesn't work for you, make sure you didn't enter:
```gdscript
func _ready():
	var timer = get_node("Timer")
	timer.timeout.connect(_on_timer_timeout())
```

**Comment by bortigon** [comment]
I don't know why people are saying its not wrong, putting it in the script literally throws an error. 

Parser Error: Identifier "_on_timer_timeout" not declared in the current scope.

`func _ready():
	var timer = get_node("Timer")
	timer.timeout.connect(_on_timer_timeout)`

This is the THIRD tutorial in the docs, and it could really deter someone from using Godot or learning to program, despite what the "well ackshuallys" say here.

**Comment by AThousandShips** [comment]
It works if you add the method properly, did you add the method manually?

The tutorial is valid, I've tested it myself, the errors are likely from people not copying things properly

**Comment by ricardo-nl** [comment]
Thank you, Bortigon.

Given that the documentation is asking us, who are learning, to communicate
if something stated in the documentation is not working in version 4.2, I
opened the issue.
I had the same error as you saw.


Em qua., 24 de abr. de 2024 às 11:47, bortigon ***@***.***>
escreveu:

**Comment by AThousandShips** [comment]
Can you run the code I showed above? I've un it and it works perfectly, are you sure you copied it correctly?

**Comment by AThousandShips** [comment]
If no one can confirm this issue with the correctly copied code above this will be closed, so please respond here if you can

**Comment by AThousandShips** [comment]
Closing due to lack of response, if someone can replicate this using *the code above* this can be reopened, but otherwise this is a copy error

Thank you for reporting
