### ISSUE TITLE
Update the Godot Docs for building using windows command line not just bash.

### ISSUE THREAD

**Issue by HeadClot** [godotengine/godot-docs#9165]
**Your Godot version:**
Godot 4.3 from Github but this applies to previous versions.

**Issue description:**
Currently the docs for building Godot engine on windows including the docs for Mono do not include commands for building using windows command line. Only bash is documented at the moment.

**URL to the documentation page (if already existing):**
https://docs.godotengine.org/en/stable/contributing/development/compiling/compiling_with_dotnet.html
https://docs.godotengine.org/en/stable/contributing/development/compiling/compiling_for_windows.html

**Comment by AThousandShips** [comment]
What in the current documentation is bash exclusive? I can't see anything that would be, can you please elaborate?

**Comment by HeadClot** [comment]
Disregard this issue. I made a mistake.
