### ISSUE TITLE
Android can still access external storage permissions without the user's consent.

### ISSUE THREAD

**Issue by xmxy-wt** [godotengine/godot-docs#9167]
**Your Godot version:**
4.3dev5
**Issue description:**
Android can still access external storage permissions without the user's consent.
The user is requesting a change in the "android:requestLegacyExternalStorage" attribute in the "AndroidManifest.xml" file from "false" to "true". This would allow the app to access external storage without the user's permission, which is not allowed in many countries and is generally disliked by users.

**Comment by AThousandShips** [comment]
Please report bugs in the engine [here](https://github.com/godotengine/godot/issues), this is for documentation, and it's not an issue in how it's documented
