### ISSUE TITLE
Please add a "Sorting Group" feature in the engine similar to Unity.

### ISSUE THREAD

**Issue by xmxy-wt** [godotengine/godot-docs#9168]
**Your Godot version:**
4.3dev5

**Issue description:**
The "Sorting Group" feature allows a parent node to treat all child nodes as a single sorting layer during sorting. This is crucial for animated characters composed of multiple body parts, as relying solely on Z_index for sorting when characters overlap can lead to poor results. For more details on this specific feature, please refer to this link: https://docs.unity.cn/2019.4/Documentation/Manual/class-SortingGroup.html.

**Comment by AThousandShips** [comment]
Feature proposals are tracked [here](https://github.com/godotengine/godot-proposals), this is for bugs. Please open a proposal instead.
