### ISSUE TITLE
First 2D tutorial - potential missing step on documentation

### ISSUE THREAD

**Issue by agu3rra** [godotengine/godot-docs#9172]
Hello everyone!

I am going thru the tutorial of the 1st 2D game with my son and we noticed the `Player` scene is just assumed to be in the `Main` scene [here](https://github.com/godotengine/godot-docs/blob/0bbf422de52377a94fc07dce788ab8874a1a9a7f/getting_started/first_2d_game/05.the_main_game_scene.rst?plain=1#L111). Is there a missing step? We have just created an `@export var mob_scene` and attached the previously created mob scene, but this part got a bit confusing.

**Comment by skyace65** [comment]
The tutorial tells you to add the player scene to the main scene at the beginning of the page. Line 12. "Click the Instance button (represented by a chain link icon) and select your saved player.tscn."
