### ISSUE TITLE
outdated documentation: .grab_focus() does not exist in 4.2 for buttons

### ISSUE THREAD

**Issue by AlaskanDruid** [godotengine/godot-docs#9175]
**Your Godot version:**
Godot 4.2 (mono/c#)

**Issue description:**
.grab_focus() does not exist for buttons

Error: Attempted to call function 'grab_focus' in base 'null instance' on a null instance.

**URL to the documentation page:**
https://docs.godotengine.org/en/stable/tutorials/ui/gui_navigation.html

If you know how to fix the issue you are reporting please
consider opening a pull request. We provide a tutorial on
using git here: https://docs.godotengine.org/en/stable/community/contributing/pr_workflow.html,
writing documentation at https://docs.godotengine.org/en/stable/community/contributing/docs_writing_guidelines.html
and contributing to the class reference here: https://docs.godotengine.org/en/stable/community/contributing/updating_the_class_reference.html

**Comment by skyace65** [comment]
I would advise you to double check your code, and go to one of the community locations like discord for help (list of those [here](https://godotengine.org/community/)). ``grab_focus()`` still exists in 4.2, you can see it in the class reference for the control node [here](https://docs.godotengine.org/en/4.2/classes/class_control.html#class-control-method-grab-focus). And I just created a basic test scene on my computer and it still works.

Also I see that you're on the C# version of Godot. If you're using a C# script make sure you're using ``GrabFocus()`` as ``grab_forcus()`` is what you use in GDScript.

**Comment by AlaskanDruid** [comment]
Thank you for the reply. Even though I am on the c# version of godot, I was using GD script when the error came up. Thanks for the community list. I'll ask in one of those if anyone had any luck.
