### ISSUE TITLE
Outdated doc on Managing node groups

### ISSUE THREAD

**Issue by jsjtxietian** [godotengine/godot-docs#9177]
**Your Godot version:**
Godot v4.3.dev (29b3d9e9e)

**Issue description:**
Due to https://github.com/godotengine/godot/pull/60965 we can manage node groups from the project settings and thus this page is outdated.

**URL to the documentation page:**

https://docs.godotengine.org/en/latest/tutorials/scripting/groups.html

**Comment by skyace65** [comment]
Fixed by #9461.
