### ISSUE TITLE
Incorrect (outdated?) usage of GodotObject.Connect

### ISSUE THREAD

**Issue by spoyri** [godotengine/godot-docs#9190]
**Your Godot version:**4.2.1

**Issue description:**When showing the example of connecting a signal using C#, the page uses incorrect, or maybe outdated (I have not used earlier versions of Godot) form of the "Connect"-method. Here is the given example:

```
// Parent
GetNode("Child").Connect("SignalName", ObjectWithMethod, "MethodOnTheObject");

// Child
EmitSignal("SignalName"); // Triggers parent-defined behavior.
```
This does not match the implementation of the method that is:

`public Error Connect(StringName signal, Callable callable, uint flags = 0u)`

**URL to the documentation page:** https://docs.godotengine.org/en/4.2/tutorials/best_practices/scene_organization.html

**Comment by raulsntos** [comment]
You are correct, looks like I missed this example when updating the page. It should be `new Callable(ObjectWithMethod, "MethodOnTheObject")` or `Callable.From(ObjectWithMethod.MethodOnTheObject)`, probably better to use the latter to be consistent with the example below. Pull requests to update it are welcomed :slightly_smiling_face:.
