### ISSUE TITLE
Tutorial missed opportunity to teach direct signal connections

### ISSUE THREAD

**Issue by moritz-t-w** [godotengine/godot-docs#9206]
https://github.com/godotengine/godot-docs/blob/f0f255ff4053132049bcdb3d15492c6fc573c15f/getting_started/first_2d_game/04.creating_the_enemy.rst?plain=1#L109-L123

Why not directly connect the signal like so:
![image](https://github.com/godotengine/godot-docs/assets/90388353/9102854c-8a83-4721-a04b-21c8574e2251)

I think this is a missed opportunity to teach that you can directly connect signals to existing functions, not just ones that are specifically made to handle the signal.

**Comment by moritz-t-w** [comment]
https://github.com/godotengine/godot-docs/blob/f0f255ff4053132049bcdb3d15492c6fc573c15f/getting_started/first_2d_game/05.the_main_game_scene.rst?plain=1#L156-L181
Here's another one, with two signals.
![image](https://github.com/godotengine/godot-docs/assets/90388353/b8ef875e-1590-4382-a40f-ea03d091484f)

**Comment by AThousandShips** [comment]
> Here's another one, with two signals.

Do you mean two methods?

**Comment by AThousandShips** [comment]
Also is this not already covered [here](https://docs.godotengine.org/en/stable/getting_started/step_by_step/signals.html#connecting-a-signal-in-the-editor) which talks about connecting signals to existing methods?

**Comment by moritz-t-w** [comment]
> Also is this not already covered [here](https://docs.godotengine.org/en/stable/getting_started/step_by_step/signals.html#connecting-a-signal-in-the-editor) which talks about connecting signals to existing methods?

Sure but if you're just following the tutorial, it would be nice to see this in practice. Speaking of practice, I think it's a bad practice to wrap a single function inside of another function. Especially when that function gets a cryptic name like `_on_visible_on_screen_notifier_2d_screen_exited()`. This makes it harder to see at a glance what's going on by adding an unnecessary extra step.

**Comment by AThousandShips** [comment]
I disagree, I'd say it's appropriate to create dedicated callbacks so you can modify them and track what's going on in your code, otherwise you're hiding the behavior behind the UI as it won't show up clearly in the script, the step isn't unnecessary IMO

But the fact is that the tutorial already says you can connect to an existing method, so there's little reason to repeat that here, and the question then is if we should prefer clear information by having a clear dedicated method, regardless if it just does a single thing

What if the user wants to add extra features, or, and this is a very simple use case, want to add a breakpoint or a debug print to this callback?

**Comment by moritz-t-w** [comment]
> hiding the behavior behind the UI

The same could be argued the other way around, hiding the behavior in code.

> What if the user wants to [...] add a breakpoint or a debug print to this callback?

That's a good point, but that's more of an issue with signals themselves imo. Why should I have to make a dedicated function just so I can add a breakpoint?

I guess it's a question of preference, UI or code. I just think that it would be nice to show a new user both sides of it in practice, dedicated handler methods and direct connections.

Considering you can unbind signal args and add call args, and even call deferred, I would say it's absolutely a supported practice to connect signals directly to existing methods, and these are prime use cases for it.

**Comment by moritz-t-w** [comment]
> Not at all, it's not hidden at all?

Well it depends if you're looking at the UI or the code editor. If you're starting from the Nodes tab you need to show the method before you can see what method it calls.

> Because there's no way to do it otherwise, in any language, that's just a basic limitation

Sure but I'm just saying, that's always the case, I wasn't arguing if the feature of connecting directly to an existing method should be used at all, just in this case. And not being able to add a breakpoint is always the case with this feature.

> you already connect to new_game and game_over, so we are absolutely showing this case

That's great. I didn't realize that. I still think it's a bad practice.
