### ISSUE TITLE
Native mode in the FileDialog Node

### ISSUE THREAD

**Issue by brosenmoller** [godotengine/godot-docs#9208]
Godot Version: Godot_v4.2.1-stable_mono_win64

When toggling on the "use_native_dialog" option in the FileDialog Node, it isn't clear how to interface with that filedialog.

When you toggle the option on, it opens the filedialog as expected, but none of the signals or properties work. I did notice that the FileDialog class contains a 'NativeInstance' property, but it is just of type 'System.IntPtr' and I can't figure out how to use it. The NativeInstance Property is also not mentioned on the documentation page.

I don't know if this feature is fully functional yet, but I would suggest updating the documentation to explain it better.
Documentation URL: (https://docs.godotengine.org/en/stable/classes/class_filedialog.html)

Thank you for your attention, I really appreciate the work that you do.

**Comment by AThousandShips** [comment]
The native instance is just part of the C# implementation, it's unrelated to this

**Comment by brosenmoller** [comment]
Aha, okay, thanks for the input, I did not know that. 

I have just now, by spitting through some open source godot projects, found a way to do what I wanted. There is a method on the "DisplayServer" class called "FileDialogShow" which I can use. But this is unrelated to the FileDialog Node.

The thing remains that I have no Idea where the  "use_native_dialog" toggle is for on the FileDialog Node. It turns it into a native dialog, but there doesn't seem to be a way to interact with it after that.

**Comment by brosenmoller** [comment]
I will look into it, thanks for your suggestion.
