### ISSUE TITLE
Broken link to Vulkan RenderingDevice implementation

### ISSUE THREAD

**Issue by mcendu** [godotengine/godot-docs#9214]
**Your Godot version:** 4.2

**Issue description:** The link to the Vulkan RenderingDevice implementation is broken. The broken link is introduced by commit d0286df2aee6b807b7e2179dffa8854e67272d21.

**URL to the documentation page:** https://docs.godotengine.org/en/stable/contributing/development/core_and_modules/internal_rendering_architecture.html

If you know how to fix the issue you are reporting please
consider opening a pull request. We provide a tutorial on
using git here: https://docs.godotengine.org/en/stable/community/contributing/pr_workflow.html,
writing documentation at https://docs.godotengine.org/en/stable/community/contributing/docs_writing_guidelines.html
and contributing to the class reference here: https://docs.godotengine.org/en/stable/community/contributing/updating_the_class_reference.html

**Comment by skyace65** [comment]
This has already been fixed by #8977, it just needs to be cherry picked to the 4.2 branch.
