### ISSUE TITLE
find_item_by_name.... not much info, on many functions what their default return value is (usually -1)

### ISSUE THREAD

**Issue by RichardEllicott** [godotengine/godot-docs#9219]
a lot of the docs do not give suffecient information, leading you to test things

this function "find_item_by_name" returns -1 if it does not find a result, this should be in reference docs

https://docs.godotengine.org/en/stable/classes/class_meshlibrary.html

is there an easy way for us to update docs in these instances? sorry if this is not the correct process but the docs link us here

**Comment by mateuseap** [comment]
Initially, I thought it wasn't necessary, but after looking around, I agree with the points raised in this issue.

I reviewed the `MeshLibrary` class documentation and found that the method descriptions indeed do not specify important nuances, such as the behavior of the `find_item_by_name()` method when a result is not found. In contrast, methods in other classes, like [`find_track()`](https://docs.godotengine.org/en/stable/classes/class_animation.html#class-animation-method-find-track) in the `Animation` class, [`find_animation()`](https://docs.godotengine.org/en/stable/classes/class_animationmixer.html#class-animationmixer-method-find-animation) and [`find_animation_library()`](https://docs.godotengine.org/en/stable/classes/class_animationmixer.html#class-animationmixer-method-find-animation-library) in the `AnimationMixer` class, and [`surface_find_by_name()`](https://docs.godotengine.org/en/stable/classes/class_arraymesh.html#class-arraymesh-method-surface-find-by-name) in the `ArrayMesh` class, do specify details about what is returned when results are not found.

Therefore, I believe it is valid and useful to add such nuances to method descriptions. Even small details like these can be very helpful to other users.

**Comment by mateuseap** [comment]
I've opened a PR to improve the description of the `find_item_by_name()` method in the `MeshLibrary` class. Many other tweaks can be made in other methods descriptions that misses nuances like this one did, but I believe this is a useful starting point.
