### ISSUE TITLE
Why isn't `COLOR` both in and out in canvas_item fragment shaders?

### ISSUE THREAD

**Issue by Zylann** [godotengine/godot-docs#923]
Godot 3.0

I noticed the doc says `COLOR` is an `in` parameter of fragment shaders. However the only way I could output pixel color in such a shader is to **assign** a value to `COLOR`.
`COLOR` should be marked as `in and out`, or a separate variable has to be created.

There is also no example of a `canvas_item` fragment shader (only `spatial`), so you can check this in the latest 2D shaders demo projects.

**Comment by mhilbrunner** [comment]
Fixed in master, COLOR is markes as **out** for CanvasItem fragment shaders, and marked as **in** for Spatial fragment shaders, where ALBEDO is the color output (marked as **out**).
