### ISSUE TITLE
get-line function from FileAccess not specifying if '\n' and '\r' are included or not [4.2.1]

### ISSUE THREAD

**Issue by BogdiB** [godotengine/godot-docs#9237]
**Your Godot version:**
4.2.1

**Issue description:**
The `get-line()` function in `FileAccess` does not specify whether or not the newline character '\n', and/or the carriage return character '\r' (if on Windows), are included in the returned string or not.

**URL to the documentation page (if already existing):**
[https://docs.godotengine.org/en/stable/classes/class_fileaccess.html#class-fileaccess-method-get-line](https://docs.godotengine.org/en/stable/classes/class_fileaccess.html#class-fileaccess-method-get-line)

**Comment by AThousandShips** [comment]
They are not included, and this would be good to specify
