### ISSUE TITLE
Documentation image does not match editor image

### ISSUE THREAD

**Issue by Torguen** [godotengine/godot-docs#9248]
**Your Godot version:**
v4.3.dev5.official [89f70e98d]
**Issue description:**

When importing bitmap fonts, the documentation shows an import menu that does not match the one shown in the version of Godot that I have indicated.

A bit of a fuss here, some options like "size" don't appear in the actual editor menu, others appear in another position.

Image shown in the documentation:

![Captura5](https://github.com/godotengine/godot-docs/assets/19652075/97dd282d-88b2-4e17-97d9-97647d4be24b)

Editor menu:

![Captura4](https://github.com/godotengine/godot-docs/assets/19652075/dd5d1260-8a83-48d0-b3b7-d7dbd980ab18)

**URL to the documentation page:**
https://docs.godotengine.org/en/stable/tutorials/ui/gui_using_fonts.html#bitmap-fonts
If you know how to fix the issue you are reporting please
consider opening a pull request. We provide a tutorial on
using git here: https://docs.godotengine.org/en/stable/community/contributing/pr_workflow.html,
writing documentation at https://docs.godotengine.org/en/stable/community/contributing/docs_writing_guidelines.html
and contributing to the class reference here: https://docs.godotengine.org/en/stable/community/contributing/updating_the_class_reference.html

**Comment by AThousandShips** [comment]
The `size` is under the character ranges no? Try expanding the vector

**Comment by Torguen** [comment]
You mean this?
It doesn't match, the options are different, the panels are not the same it seems.

Where is "size" (in my language is "tamaño" but nothing appears)

![Captura5](https://github.com/godotengine/godot-docs/assets/19652075/33c82618-f0bd-41b8-a3dc-b1afe5031d67)

**Comment by AThousandShips** [comment]
Click the box to the right of "Rangos de Caracter"

**Comment by Torguen** [comment]
Ok so that's what happened.
The documentation does not indicate that this vector was expanded and I thought it was a different menu, I close this but it could be made explicit in the documentation.
