### ISSUE TITLE
Need comprehensive guide to importing / working with 3D models and PBR textures.

### ISSUE THREAD

**Issue by nonfatmatt** [godotengine/godot-docs#925]
I've been experimenting with Godot for the last couple of weeks, but for the life of me can't get models and textures to import right.  I have experience in Unreal Engine 4 so I know it isn't a workflow problem on my end.  Godot really needs a well written and simple guide for getting static geometry from into the engine from a DCC tool (in this case I am using Blender).

Some of my problems / questions:

1) Which exporter should  I use? 

There are currently 4 possible exporters from Blender that all produce sub-par results. I've tried the Godot Collada exporter, the Khronos GLTF Exporter, the Blender Realtime GLTF exporter, and plain old .obj files.  None of these bring over textures / materials when used with the principled shader in Blender that closely matches Godot's shading model.  Both GLTF exporters produce unworkable geometry that doesn't show up in engine. The Collada and .obj exporters produce geometry but not materials.

2. How to go about basic import operations / best practices? 

Godot's node based system is strange compared to other workflows, and clunky. In Unreal, CryEngine and Unity I can just drag and drop a mesh after importing it. Godot gives me a lot of options for instantiating a mesh or scene, but I honestly have no idea what is the best way to do it. Also, each time I import a mesh it seems to take 2-3 more steps (linking the mesh to a mesh instance, etc) than other engines. This is a big turn off for us who work with a modular workflow and requires significantly more time to produce a scene than in Unreal.  Godot really needs a document to show how to simplify the process and show how to do it for people familiar with more mainstream engines. 

3. Describe best setups in DCC tools.

I know the lightmapper works now, in Godot 3.  However, there is no documentation for what the mesh setup is supposed to be like. What's the 2nd UV set supposed to be called? Also, what are the best practices for setting up meshes in a DCC tool for proper import, expecially considering that Godot 3 just imports everything automatically and makes you sort it out later. 

Anyway, making a document like this would be helpful as Godot's new renderer has a lot of interest from people who work on bigger game engines. However, it's almost impossible to use at the moment because there is no documentation for doing basic things that are quick and easy in other game engines.

**Comment by reduz** [comment]
1. Better Collada is the one that should work the best currently, but the idea is to move to GLTF as it gets better support.
2. It really depends on the game you are making. You can make an entire scene in Blender and import it to Godot, or just export separate meshes and use them independently. It also depends which added information you need such as collisions/navmesh/etc.
3. http://docs.godotengine.org/en/latest/learning/features/3d/baked_lightmaps.html

**Comment by Calinou** [comment]
Is this issue still relevant given the current state of the documentation?

I think all we need to do now is to answer the question "Should I export the whole scene from Blender or only individual objects"?
