### ISSUE TITLE
Array#sort_custom should return an error instead of failing silently

### ISSUE THREAD

**Issue by ShinyDeagle** [godotengine/godot-docs#9259]
**Your Godot version:** 
4.2

**Issue description:**
The Array#sort_custom ought to return an error when the callable misinterprets the types of the elements it's sorting through.
It's frustrating when you have to head into the debugger later when you're wondering why your array is messed up.

Callables already issue an error to the debugger when they fail, the call arguments could benefit from doing so too.

**Comment by ShinyDeagle** [comment]
`var players : Array[String] = ["player1", "player2"]`
`players.sort_custom(func(o1: int, o2: int):
  return o1 > o2
)
`
Ought to error because of the mismatch types

**Comment by AThousandShips** [comment]
This is for reporting bugs in the documentation, please propose new features over [here](https://github.com/godotengine/godot-proposals)

**Comment by skyace65** [comment]
Closing per AThousandShips comment.

**Comment by ra314** [comment]
I have created a new proposal at https://github.com/godotengine/godot-proposals/issues/9568
