### ISSUE TITLE
ConfirmationDialog - Can not change Default Dialog Option

### ISSUE THREAD

**Issue by lightfinesthour** [godotengine/godot-docs#9264]
**Your Godot version:**
v4.3.dev5.official [89f70e98d]

**Issue description:**
ConfirmationDialog has no option to change the default selected option, Default selection is Ok Button
If you want to have No/Cancel selected by default, you need to do it by code.

**URL to the documentation page (if already existing):**
https://docs.godotengine.org/en/stable/classes/class_confirmationdialog.html

**Comment by AThousandShips** [comment]
Thank you for reporting, however this is for reporting issues with the documentation, for proposing new features please go [here](https://github.com/godotengine/godot-proposals)

**Comment by Piralein** [comment]
Please create a proposal as stated by **AThousandShips**, closing.
