### ISSUE TITLE
Outdated images in "Creating instances" section.

### ISSUE THREAD

**Issue by SoyYuyin** [godotengine/godot-docs#9273]
**Your Godot version:**
4.2.2

**Issue description:**
The images shown of the Project Manager interface in the "In Practice" < "Creating instances" < "Step by step" < "Getting started", are different than what I see in the 4.2.2 version. The layout is slightly different. No biggie.

![image](https://github.com/godotengine/godot-docs/assets/33614173/da02ee4e-28d3-48b7-bfb2-2b8f7d570072)

**URL to the documentation page:**
https://docs.godotengine.org/en/4.2/getting_started/step_by_step/instancing.html

If you know how to fix the issue you are reporting please
consider opening a pull request. We provide a tutorial on
using git here: https://docs.godotengine.org/en/stable/community/contributing/pr_workflow.html,
writing documentation at https://docs.godotengine.org/en/stable/community/contributing/docs_writing_guidelines.html
and contributing to the class reference here: https://docs.godotengine.org/en/stable/community/contributing/updating_the_class_reference.html

**Comment by skyace65** [comment]
This has already been fixed by #8854, it just needs to get cherry picked to 4.2.
