### ISSUE TITLE
Make your first 2D Game "The main game scene" section. Mobs do not spawn in c#

### ISSUE THREAD

**Issue by Arman-Espiar** [godotengine/godot-docs#9286]
Godot version: v4.2.2.stable.mono.official [15273afe3]

**Issue description:**
I followed the instructions, but the Mobs do not spawn.

[**URL to the documentation page:**](https://docs.godotengine.org/en/stable/getting_started/first_2d_game/05.the_main_game_scene.html)

I don't know if the problem is from my side or from the documentation. But I followed the instructions

**Comment by AThousandShips** [comment]
Please share your code to see if it's an error in copying

**Comment by Arman-Espiar** [comment]
@AThousandShips The game runs without errors or warnings. Even I replaced the C# Main script with the GD script, it still runs the same way.

Player:
```
using Godot;

public partial class Player : Area2D
{
	[Signal]
	public delegate void HitEventHandler();
	[Export]
	public int Speed { get; set; } = 400; // How fast the player will move (pixel/sec).
	public Vector2 ScreenSize; // Size of the game window.

	// Called when the node enters the scene tree for the first time.
	public override void _Ready()
	{
		ScreenSize = GetViewportRect().Size;
		Hide();
	}

	// Called every frame. 'delta' is the elapsed time since the previous frame.
	public override void _Process(double delta)
	{
		var velocity = Vector2.Zero; // The player's movement vector.

		if (Input.IsActionPressed("move_right"))
		{
			velocity.X += 1;
		}

		if (Input.IsActionPressed("move_left"))
		{
			velocity.X -= 1;
		}

		if (Input.IsActionPressed("move_down"))
		{
			velocity.Y += 1;
		}

		if (Input.IsActionPressed("move_up"))
		{
			velocity.Y -= 1;
		}

		var animatedSprite2D = GetNode<AnimatedSprite2D>("AnimatedSprite2D");

		if (velocity.Length() > 0)
		{
			velocity = velocity.Normalized() * Speed;
			animatedSprite2D.Play();
		}
		else
		{
			animatedSprite2D.Stop();
		}

		Position += velocity * (float)delta;
		Position = new Vector2(
			x: Mathf.Clamp(Position.X, 0, ScreenSize.X),
			y: Mathf.Clamp(Position.Y, 0, ScreenSize.Y)
		);

		if (velocity.X != 0)
		{
			animatedSprite2D.Animation = "walk";
			animatedSprite2D.FlipV = false;
			animatedSprite2D.FlipH = velocity.X < 0;
		}
		else if (velocity.Y != 0)
		{
			animatedSprite2D.Animation = "up";
			animatedSprite2D.FlipV = velocity.Y > 0;
		}
	}
	private void OnBodyEntered(Node2D body)
	{
		Hide();// Player disappears after being hit.
		EmitSignal(SignalName.Hit);
		// Must be deferred as we can't change physics properties on a physics callback.
		GetNode<CollisionShape2D>(nameof(CollisionShape2D)).SetDeferred(CollisionShape2D.PropertyName.Disabled, true);
	}
	public void Start(Vector2 position)
	{
		Position = position;
		Show();
		GetNode<CollisionShape2D>(nameof(CollisionShape2D)).Disabled = false;
	}
}
```

Mob:
```
using Godot;

public partial class Mob : RigidBody2D
{
	// Called when the node enters the scene tree for the first time.
	public override void _Ready()
	{
		var animatedSprite2D = GetNode<AnimatedSprite2D>("AnimatedSprite2D");
		string[] mobTypes = animatedSprite2D.SpriteFrames.GetAnimationNames();
		animatedSprite2D.Play(mobTypes[GD.Randi() % mobTypes.Length]);
	}

	// Called every frame. 'delta' is the elapsed time since the previous frame.
	public override void _Process(double delta)
	{
	}
	private void OnVisibleOnScreenNotifier2DScreenExited()
	{
		QueueFree();
	}
}
```
Main:
```

using Godot;

public partial class Main : Node
{
	[Export]
	public PackedScene MobScene { get; set; }
	private int _score;
	public void GameOver()
	{
		GetNode<Timer>("MobTimer").Stop();
		GetNode<Timer>("ScoreTimer").Stop();
	}

	public void NewGame()
	{
		_score = 0;

		var player = GetNode<Player>("Player");
		var startPosition = GetNode<Marker2D>("StartPosition");
		player.Start(startPosition.Position);

		GetNode<Timer>("StartTimer").Start();
	}

	private void OnScoreTimerTimeout()
	{
		_score++;
	}

	private void OnStartTimerTimeout()
	{
		GetNode<Timer>("MobTimer").Start();
		GetNode<Timer>("ScoreTimer").Start();
	}
	private void OnMobTimerTimeout()
	{
		// Note: Normally it is best to use explicit types rather than the `var`
		// keyword. However, var is acceptable to use here because the types are
		// obviously Mob and PathFollow2D, since they appear later on the line.

		// Create a new instance of the Mob scene.
		Mob mob = MobScene.Instantiate<Mob>();

		// Choose a random location on Path2D.
		var mobSpawnLocation = GetNode<PathFollow2D>("MobPath/MobSpawnLocation");
		mobSpawnLocation.ProgressRatio = GD.Randf();

		// Set the mob's direction perpendicular to the path direction.
		float direction = mobSpawnLocation.Rotation + Mathf.Pi / 2;

		// Set the mob's position to a random location.
		mob.Position = mobSpawnLocation.Position;

		// Add some randomness to the direction.
		direction += (float)GD.RandRange(-Mathf.Pi / 4, Mathf.Pi / 4);
		mob.Rotation = direction;

		// Choose the velocity.
		var velocity = new Vector2((float)GD.RandRange(150.0, 250.0), 0);
		mob.LinearVelocity = velocity.Rotated(direction);

		// Spawn the mob by adding it to the Main scene.
		AddChild(mob);
	}
	// Called when the node enters the scene tree for the first time.
	public override void _Ready()
	{
		NewGame();
	}

	// Called every frame. 'delta' is the elapsed time since the previous frame.
	public override void _Process(double delta)
	{
	}
}
```

![gd](https://github.com/godotengine/godot-docs/assets/89306156/5166e4be-3bb7-4cd1-ad9e-743f4f1c1fa3)

**Comment by Arman-Espiar** [comment]
Yes, I think I have done this.
[Dodge the Creeps!.zip](https://github.com/godotengine/godot-docs/files/15138491/Dodge.the.Creeps.zip)

**Comment by AThousandShips** [comment]
You haven't connected the timer, see this part:
> Now connect the timeout() signal of each of the Timer nodes (StartTimer, ScoreTimer, and MobTimer) to the main script. StartTimer will start the other two timers. ScoreTimer will increment the score by 1.

Try connecting it, things should work then

**Comment by Arman-Espiar** [comment]
Oh yes, you are right. But after connecting all 4 signals, the mobs are still not loaded.
Do you think there is a problem with my codes? I need to revise my code.
![gd1](https://github.com/godotengine/godot-docs/assets/89306156/0cc5df5e-302e-4ab4-9f9c-c1c43a5a94a3)

**Comment by AThousandShips** [comment]
I don't know in this case, but maybe ask in the [forums](https://forum.godotengine.org/) to see that this isn't still some error in the configuration, and if it isn't come back here and report what you've found

**Comment by Arman-Espiar** [comment]
Thank you very much for your time. I didn't know there was a forum 😁💕.

**Comment by Arman-Espiar** [comment]
With the help of artificial intelligence, I got a code that connected with a little change (I think it was for the old version!) of the signals! I think it is called signal connection through code (I don't know). But I have to do this for all the signals!
The problem that exists is that the signals are not connected as described in the tutorial.
But it is done through this code!

As you can see in the picture, because I haven't changed the code of the OnBodyEntered signal yet, nothing happens when the mobs hit the player, and probably the OnVisibleOnScreenNotifier2DScreenExited signal doesn't work (unfortunately, because it's not visible in the game editor! Maybe I don't know. Anyway I just want to learn.)

main script:

```
	public void GameOver()
	{
		var mt = GetNode<Timer>("MobTimer");
		mt.Connect("timeout", new Callable(this, "GameOver"));
		mt.Stop();
		var st = GetNode<Timer>("ScoreTimer");
		st.Connect("timeout", new Callable(this, "GameOver"));
		st.Stop();
	}

	public void NewGame()
	{
		_score = 0;

		var player = GetNode<Player>("Player");
		var startPosition = GetNode<Marker2D>("StartPosition");
		player.Start(startPosition.Position);

		//GetNode<Timer>("StartTimer").Start();
		var startTimer = GetNode<Timer>("StartTimer");
		startTimer.Connect("timeout", new Callable(this, "OnStartTimerTimeout"));
		startTimer.Start();
	}

	private void OnScoreTimerTimeout()
	{
		_score++;
	}

	private void OnStartTimerTimeout()
	{
		var mobTimer = GetNode<Timer>("MobTimer");
		mobTimer.Connect("timeout", new Callable(this, "OnMobTimerTimeout"));
		mobTimer.Start();
		var scoreTimer = GetNode<Timer>("ScoreTimer");
		scoreTimer.Connect("timeout", new Callable(this, "OnScoreTimerTimeout"));
		scoreTimer.Start();
	}
```

![gd](https://github.com/godotengine/godot-docs/assets/89306156/70865538-390f-4d60-a3c7-e2d18e167a7b)

**Comment by AThousandShips** [comment]
You probably shouldn't rely on AI to generate your code, instead try to match what the tutorial says and connect the signals according to the instructions

**Comment by Arman-Espiar** [comment]
I followed the tutorial, but it doesn't work. I did not find the game source in C# language either. I connected all 4 signals but it does not enter their methods.

**Comment by AThousandShips** [comment]
Check this and make sure everything you've done matches:
https://github.com/godotengine/godot-demo-projects/tree/master/mono/dodge_the_creeps

**Comment by Arman-Espiar** [comment]
Thank you.

**Comment by skyace65** [comment]
Your project isn't working because in addition to not connecting the signals in the main scene you connected the OnBodyEntered signal of the player incorrectly. You connected it to the default "_on_body_entered" instead of "OnBodyEntered" . You also made that mistake with the "GameOver" signal. In the future please double check your code before opening a doc issue if you're not sure exactly what the problem is, in addition you can go to some of the community locations (listed [here](https://godotengine.org/community/)) for help.
