### ISSUE TITLE
Inconsistent documentation for enum Node.DuplicateFlags

### ISSUE THREAD

**Issue by schemar** [godotengine/godot-docs#9289]
**Your Godot version:** 4.2.2.stable.official.15073afe3

**Issue description:**
`DUPLICATE_USE_INSTANTIATION` is documented differently in the online docs and in the editor help. In my understanding, they even contradict each other.

Online docs:
> [DuplicateFlags](https://docs.godotengine.org/en/stable/classes/class_node.html#enum-node-duplicateflags) DUPLICATE_USE_INSTANTIATION = 8
>
> Duplicate using instancing.
>
> An instance stays linked to the original so when the original changes, the instance changes too.

Editor docs:
> ● DUPLICATE_USE_INSTANTIATION = 8
> Duplicate using PackedScene.instantiate(). If the node comes from a scene saved on disk, re-uses PackedScene.instantiate() as the base for the duplicated node and its children.

❓ Which documentation is the correct one? Does it make a difference whether we have a "simple" Node or a Node which resulted from `PackedScene.instantiate()`?

**URL to the documentation page:**
https://docs.godotengine.org/en/stable/classes/class_node.html#enum-node-duplicateflags

**URL to the editor documentation:**
https://github.com/godotengine/godot/blob/6118592c6d88350d01f74faff6fd49754f84a7d0/doc/classes/Node.xml#L1303

The editor's documentation was last updated here (this January): https://github.com/godotengine/godot/pull/68560

**Comment by AThousandShips** [comment]
It just hasn't been updated yet, the changes aren't immediately transferred, it'll be updated in the next update

**Comment by schemar** [comment]
Thanks for the swift reply 🙏🏻
