### ISSUE TITLE
Window placement probably outdated documentation

### ISSUE THREAD

**Issue by dtesniere** [godotengine/godot-docs#9295]
**Your Godot version:** v4.2.2.rc2.official [c61a68614]

**Issue description:** 
The documentation mentions certain parameters that no longer seem to exist.
In my use case, I'm looking for "run/window_placement/rect" and "run/window_placement/rect_custom_position"

These parameters are recommended by the “ProjectSettings” documentation on my embeded (inside Godot Editor) documentation. But it seems to have been updated on the online documentation.
Oneline documentation : https://docs.godotengine.org/en/4.2/classes/class_projectsettings.html#class-projectsettings-property-display-window-size-initial-position

The message I have today in the embeded Godot Engine documentation : 
> Note: This setting only affects the exported project, or when the project is run from the command line. In the editor, the value of EditorSettings.run/window_placement/rect_custom_position is used instead.

I try to add these missing parameters.
Translation was working fine (I was using Godot Editor in French)
But parameters are not taken in account. So I suppose it is outdated documentation.

I don't know how to handle this without these parameter. I don't manage to configure windows postion. So I don't have any workarround to share.

**URL to the documentation page:**
https://docs.godotengine.org/en/stable/classes/class_editorsettings.html#class-editorsettings-property-run-window-placement-rect-custom-position

**Comment by AThousandShips** [comment]
Yes this hasn't been updated online yet, it takes a while for this to be pushed over, it's something that will be done hopefully soon, just refer to the built in engine docs until then

**Comment by AThousandShips** [comment]
No the online documentation is out of date, you need to follow the built in ones, the setting exists and is how you should configure it

**Comment by skyace65** [comment]
To expand on what AThousandShips said. The changes are present in the "master" branch of the documentation, they just haven't been backported to the 4.2 branch. If you change the version that you're looking at in the online docs (button is on the bottom left, to the right of "read the docs") to the master branch you'll see the updated documentation.

**Comment by AThousandShips** [comment]
Specifically in this case the class reference hasn't been transferred from the main repo to the online docs, it's done less regularly for the `stable` docs
