### ISSUE TITLE
ResourceLoader.Load doesn't specify what happens if you try to load a path that doesn't exist.

### ISSUE THREAD

**Issue by NoahtheEpicProgrammer** [godotengine/godot-docs#9306]
**Your Godot version:** 4.2.2

**Issue description:** ResourceLoader.Load doesn't state anywhere in its description what happens if a given path does not exist; the current behavior is to push an error to the debugger, `Resource file not found: [path] (expected type: [type])`, and return `null`.

**URL to the documentation page (if already existing):** https://docs.godotengine.org/en/stable/classes/class_resourceloader.html#class-resourceloader-method-load

**Comment by NoahtheEpicProgrammer** [comment]
Oops, hold on I accidently pressed enter while trying to type.

**Comment by pgh1686** [comment]
Hello! I'm interested in taking a crack at this issue, I'll see if I can get a PR out tonight.
