### ISSUE TITLE
Missing requirement for building with mono support

### ISSUE THREAD

**Issue by AllanDaemon** [godotengine/godot-docs#931]
I have a problem building it on Arch Linux on the latest commit on master (https://github.com/godotengine/godot/commit/f11a1385054376bdc4cc01e6aa20d63508a5e6d4).

The error message is:
```
% scons p=x11 tools=yes module_mono_enabled=yes mono_glue=no
scons: Reading SConscript files ...
Enabling ALSA
Enabling PulseAudio
YASM is necessary for WebM SIMD optimizations.
WebM SIMD optimizations are disabled. Check if your CPU architecture, CPU bits or platform are supported!
Checking for C header file mntent.h... (cached) yes
scons: done reading SConscript files.
scons: Building targets ...
[Initial build] mono_build_solution(["bin/GodotSharpTools.dll"], ["modules/mono/editor/GodotSharpTools/GodotSharpTools.sln"])
scons: *** [bin/GodotSharpTools.dll] KeyError : 'xbuild_fallback'
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/SCons/Action.py", line 1197, in execute
    result = self.execfunction(target=target, source=rsources, env=env)
  File "/home/rea/build/godot-git.mono/src/godot/modules/mono/SCsub", line 153, in mono_build_solution
    xbuild_fallback = env['xbuild_fallback']
  File "/usr/lib/python2.7/site-packages/SCons/Environment.py", line 410, in __getitem__
    return self._dict[key]
KeyError: 'xbuild_fallback'
scons: building terminated because of errors.
```

The problem is that according to the post of how to built it, you only need Mono installed. And it's was true for me, but in Arch Linux the mono package doesn't provide the msbuild. The issue https://github.com/godotengine/godot/issues/12613 has helped me to figure it out. After i installed it along with mono 5.4 it did compile the glue.

I don't know if the msbuild is part of mono or if a mono installation is required to having it, but it seems to me that msbuild is a different requirement to build it on Linux, that is not explicit on the page: 
http://docs.godotengine.org/en/latest/development/compiling/compiling_with_mono.html

So it seems to me that the msbuild from Microsoft should be explicited as a requirement for building Godot 3 with Mono.

**Comment by neikeq** [comment]
Looks like there is an error when falling back to xbuild.
