### ISSUE TITLE
Tutorial using wrong class: "Using a Viewport as a texture" --> "Using a SubViewport as a texture"

### ISSUE THREAD

**Issue by blenderer** [godotengine/godot-docs#9312]
**Your Godot version:** 4.2.2

**Issue description:** I am new to Godot so correct me if I'm just wrong. It appears you can no longer add a "Viewport" to a scene. Viewport is greyed out (Abstract now?) and other documentation references adding "Subviewports". Perhaps this tutorial should be modified to use "SubViewport"

I am willing to contribute, just want to know if this is correct.

**URL to the documentation page (if already existing):** https://github.com/godotengine/godot-docs/blob/master/tutorials/shaders/using_viewport_as_texture.rst

**Comment by clayjohn** [comment]
Yep, that's correct. In Godot 4 the Viewport was made abstract and now users access the SubViewport. A lot of our docs are still out of date. Admittedly, we often casually call the SubViewport "Viewport", but we shouldn't do that in the documentation
