### ISSUE TITLE
The "Developing in C++" section name is ambiguous/confusing

### ISSUE THREAD

**Issue by NullConstant** [godotengine/godot-docs#933]
This came up on the Godot Discord server the other day.

![obraz](https://user-images.githubusercontent.com/14968217/34451482-6c249a40-ed27-11e7-9255-0d184b98cc36.png)

Basically, it's not immediately clear that the section refers to extending the engine itself (with C++), as opposed to using C++ for scripting (which is a separate matter), so I think it'd be appropriate to alter the name to more accurately represent what the section is meant to cover.

**Comment by mhilbrunner** [comment]
Most agreed new name was `Engine development with C++` or just `Engine development`

**Comment by NathanLovato** [comment]
Fixed!
