### ISSUE TITLE
the first 2d game main game sense issue

### ISSUE THREAD

**Issue by lemchen** [godotengine/godot-docs#9360]
**Your Godot version:**
4.2.2
**Issue description:**
In the first 2d game build main game sense chapter, by following the step,
![屏幕截图 2024-05-11 174304](https://github.com/godotengine/godot-docs/assets/1787646/f46645e6-7b2e-4308-aaae-228c54d50b31)
but there's no Mob Scene property in the Inspector under "Script Variables"
![屏幕截图 2024-05-11 174435](https://github.com/godotengine/godot-docs/assets/1787646/db8518ab-c46d-463e-9638-8e82fd381eea)

**URL to the documentation page:**
https://docs.godotengine.org/en/stable/getting_started/first_2d_game/05.the_main_game_scene.html#main-script

**Comment by AThousandShips** [comment]
Just to make sure, you rebuilt the project?

**Comment by lemchen** [comment]
> Just to make sure, you rebuilt the project?

yes, i do rebuilt the project

**Comment by AThousandShips** [comment]
Please upload your project to help checking the code is correct

**Comment by skyace65** [comment]
I just tested the code in 4.2.2 and it's correct, building the project adds the "mob scene" as an option in the inspector. lemchen please double check your code. If you're using the code copy and pasted from the docs like I did and the option still doesn't show when you build a project, please open an issue in the engine repository [here](https://github.com/godotengine/godot), as this would be an engine bug. In addition, if you do open an engine bug please provide a zip file of your project for contributors to check.
