### ISSUE TITLE
Minor issue with "Creating instances" page

### ISSUE THREAD

**Issue by robingamedev** [godotengine/godot-docs#9362]
**Your Godot version:**
4.2

**Issue description:**

Issue 1: The [instancing_starter.zip](https://github.com/godotengine/godot-docs-project-starters/releases/download/latest-4.x/instancing_starter.zip) file had a warning that the project was made in 4.0. 

Not a issue but maybe a notice to the reader that this is normal.

Issue 2: This image is no longer the same.

BEFORE:
![](https://docs.godotengine.org/en/stable/_images/instancing_physics_material_expand.webp)

SUGGESTED CHANGE:
![screen](https://github.com/godotengine/godot-docs/assets/153454908/234c4855-95f4-4f60-b4a7-7a9ca9bdacec)

Issue 3: 
Suggestion: This section "[Scene instances as a design language](https://docs.godotengine.org/en/stable/getting_started/step_by_step/instancing.html#scene-instances-as-a-design-language) seems out of place in this document.
Would suggest moving it to the page above it titled "Nodes and Scenes"

**URL to the documentation page (if already existing):**
https://docs.godotengine.org/en/stable/getting_started/step_by_step/instancing.html

**Comment by skyace65** [comment]
That image has already been updated in #8854. You can see it in the 4.2 and master version of the docs. Looks like the stable version just hasn't been updated to the latest 4.2 version yet. Also the instancing starter project being outdated is already being tracked in #8841
