### ISSUE TITLE
Your first 2D game > Finishing up screenshot is outdated

### ISSUE THREAD

**Issue by robingamedev** [godotengine/godot-docs#9368]
**Your Godot version:**
4.2.2

**Issue description:**
Image doesn't look like how it looks in 4.2

ORIGINAL:
![](https://docs.godotengine.org/en/stable/_images/start_button_shortcut2.webp)

SUGGESTION:
![input_event](https://github.com/godotengine/godot-docs/assets/153454908/bacd9377-106f-45d0-82ed-310a25e0afff)

**URL to the documentation page:**
https://docs.godotengine.org/en/stable/getting_started/first_2d_game/07.finishing-up.html

**Comment by skyace65** [comment]
This has already been fixed by #8946. You can see the updated screenshot on the master branch and 4.2. Stable just hasn't been updated to the latest version of the 4.2 branch.
