### ISSUE TITLE
Left Pallete doesnt work

### ISSUE THREAD

**Issue by hi-p** [godotengine/godot-docs#937]
left pallate can go out of screen and the ball goes right past it

**Comment by cbscribe** [comment]
This forum is for issues and suggestions related to the Godot Engine documentation. It is not a good place to get help with your own project.

The Godot community is very friendly and helpful. Here are some good places to go for help:

- [Godot Questions & Answers](https://godotengine.org/qa/) - you can search for similar issues here too
- [Godot Discord chat](https://discord.gg/zH7NUgz)
- [Godot Facebook group](https://www.facebook.com/groups/godotengine/)

**Comment by akien-mga** [comment]
It might have been a bug in the Pong demo of the `2.1` branch though :)
