### ISSUE TITLE
Confusing explanation about COW and Dicts, Arrays

### ISSUE THREAD

**Issue by noidexe** [godotengine/godot-docs#938]
From http://docs.godotengine.org/en/latest/development/cpp/variant_class.html
> Both have a shared mode and a COW mode. Scripts often use them in shared mode [...] or COW mode [...]. In COW mode, Both Dictionary and Array are thread-safe, otherwise a Mutex should be created to lock if multi thread access is desired.

What does 'often' mean in that sentence? If "often" covers both possibilities then what would be the "not often" case?
Should it be "often in shared mode and not very often in COW mode"? In that case how do you pick between the two in a script?

**Comment by reduz** [comment]
This was very confusing, so In 3.0, Dictionaries and Arrays are always
shared, COW is not used any more. I suppose this doc will need to be
updated.
