### ISSUE TITLE
Older versions of scons which come with the oneliner install are no longer supported

### ISSUE THREAD

**Issue by ultsi** [godotengine/godot-docs#9380]
**Your Godot version:**

Newest master

**Issue description:**

When using scons v3.1.2 which comes with `sudo apt install scons` on Ubuntu 20.04, building the engine will fail with the following error: 

```
$ scons platform=linuxbsd 
scons: Reading SConscript files ...
TypeError: 'SConsEnvironment' object is not a mapping:
  File "/home/ultsi/dev/godot/godot-src/SConstruct", line 368:
    opts.Update(env, {**ARGUMENTS, **env})

```
   
Solution to this was to uninstall old scons with `sudo apt remove scons` and install newest scons with `pip3 install scons`. 

So the issue is that the oneliner for Ubuntu on the documentation below will install an old version of scons. 

For the record this is the commit that breaks old scons compatibility: https://github.com/godotengine/godot/pull/91792

**URL to the documentation page:**

https://docs.godotengine.org/en/latest/contributing/development/compiling/compiling_for_linuxbsd.html#distro-specific-one-liners

**Comment by AThousandShips** [comment]
This should probably be reported on the main repo, I don't know it's a documentation issue unless we decide we shouldn't support 3.1.2 any longer

**Comment by skyace65** [comment]
Fixed in the engine by https://github.com/godotengine/godot/pull/92041
