### ISSUE TITLE
Nav Menu Covers Screen

### ISSUE THREAD

**Issue by denistorjai** [godotengine/godot-docs#9386]
The Nav menu of the documentation website fully covers text on the website with no option to hide it.

My resolution is 2560x1440, it also happens when I resize the window too

[**URL to the documentation page:**](https://docs.godotengine.org/en/stable/tutorials/scripting/idle_and_physics_processing.html#:~:text=Physics%20processing%20works%20with%20a,collides%20with%20the%20game%20world.)

![image](https://github.com/godotengine/godot-docs/assets/113322506/faef40ef-8801-4f05-a20b-d832755bf29a)

**Comment by skyace65** [comment]
What OS are you on and which browser are you using? Also are you using any extensions or some kind of focused reading mode?

**Comment by denistorjai** [comment]
I'm using Google Chrome, with Windows 10. The only extension I have is Malwarebytes browser guard which shouldn't intervene with it.

This only happens on **some** pages that are sourced from google. It doesn't happen when I go to the documentation website directly.

For example, 
/scripting/idle_and_physics_processing.html 
doesn't have the issue but
/scripting/idle_and_physics_processing.html#:~:text=Physics%20processing%20works%20with%20a,collides%20with%20the%20game%20world.
does have the issue

**Comment by Piralein** [comment]
related (fixed?) issue #4790 and PR #9015

The issue doesn't appear on [stable](https://docs.godotengine.org/en/latest/tutorials/scripting/idle_and_physics_processing.html#:~:text=Physics%20processing%20works%20with%20a,collides%20with%20the%20game%20world.) or [4.2](https://docs.godotengine.org/en/4.2/tutorials/scripting/idle_and_physics_processing.html#:~:text=Physics%20processing%20works%20with%20a,collides%20with%20the%20game%20world.).

**Comment by skyace65** [comment]
Akien just pushed 4.2 to the stable branch. @denistorjai are you still seeing the issue?

**Comment by denistorjai** [comment]
The issue is fixed, thank you
