### ISSUE TITLE
Example for (Basis * Vector3) is incorrect

### ISSUE THREAD

**Issue by mart3323** [godotengine/godot-docs#9394]
### **Your Godot version:** 
3.4.4 stable [419e713a2]

4.2.2 stable [15073afe3]

### **Issue description:**
The example given for (Basis * Vector3) is incorrect. It currently shows 
```python
var my_basis = Basis(Vector3(1, 1, 1), Vector3(1, 1, 1), Vector3(0, 2, 5))
print(my_basis * Vector3(1, 2, 3)) # Prints (7, 3, 16)
```
But when this code is actually run it gives (3, 9, 18). I also don't see any formula by which one could get (7,3,16) out of that

Perhaps it was intended to read as follows..?
```python
var my_basis = Basis(Vector3(1, -1, -1), Vector3(3, -1, 1), Vector3(0, 2, 5))
print(my_basis * Vector3(1, 2, 3)) # Prints (7, 3, 16)
```

### **URL to the documentation page:** 
https://docs.godotengine.org/en/stable/classes/class_basis.html#class-basis-operator-mul-vector3

**Comment by AThousandShips** [comment]
For anyone wanting to fix this note that class reference changes are done [here](https://github.com/godotengine/godot), see [here](https://docs.godotengine.org/en/latest/contributing/documentation/updating_the_class_reference.html)
