### ISSUE TITLE
Getting Started "Editing scenes and instances" Tutorial is wrong about ball bounce 0.5

### ISSUE THREAD

**Issue by aaronshaver** [godotengine/godot-docs#9396]
**Your Godot version:**

4.2.2

**Issue description:**

The tutorial says "notice how all balls now bounce a lot more" after doing the 0.5 edit; however, the documentation for Bounce clearly states: "Values range from 0 (no bounce) to 1 (full bounciness), so it's claiming the exact opposite of the case. As well, 0.5 is difficult to notice a difference. I suggest using 0.1 as the value, and updating the text to say "notice how the balls now do not bounce as much".

**URL to the documentation page:**

https://docs.godotengine.org/en/stable/getting_started/step_by_step/instancing.html#editing-scenes-and-instances

If you know how to fix the issue you are reporting please
consider opening a pull request. We provide a tutorial on
using git here: https://docs.godotengine.org/en/stable/community/contributing/pr_workflow.html,
writing documentation at https://docs.godotengine.org/en/stable/community/contributing/docs_writing_guidelines.html
and contributing to the class reference here: https://docs.godotengine.org/en/stable/community/contributing/updating_the_class_reference.html

**Comment by AThousandShips** [comment]
Ir changes from 0 to 0.5 so it absolutely becomes more bouncy

**Comment by skyace65** [comment]
AThousandShips is correct. The default value for bounciness is 0, and that's what it's set to in the instancing starter project, changing it to 0.5 makes it more bouncy.
