### ISSUE TITLE
Godot does not perform implicit String conversion for String Formatting

### ISSUE THREAD

**Issue by normandra** [godotengine/godot-docs#9397]
**Your Godot version:**
4.2.2

**Issue description:**
The tutorial on the first 3d game highlights the usage of string formatting with implicit conversion. However this breaks my build as the string conversion is not performed and a explicit conversion or the usage of %d is needed.

Not sure if this is the intended behaviour or if the doc is outdated (if its the case I'd gladly open a PR to update)

**URL to the documentation page:**
https://docs.godotengine.org/en/stable/getting_started/first_3d_game/08.score_and_replay.html#keeping-track-of-the-score
https://docs.godotengine.org/en/stable/tutorials/scripting/gdscript/gdscript_format_string.html#usage-in-gdscript

**Comment by AThousandShips** [comment]
Please explain what's not working, there's no information here on *what* actually "breaks my build"

**Comment by normandra** [comment]
Hey, pardon me. While about to copy to conversion error trace I noticed I accidentally had used the & operator instead of % in the initial walkthrough.

Closing the issue
