### ISSUE TITLE
Improve documentation for how to add Godot Executable to Linux

### ISSUE THREAD

**Issue by computer-science-student** [godotengine/godot-docs#9416]
Godot version: 4.2 on Debian 12 Linux

When I downloaded Godot on Linux, I was initially confused about how to add the Godot executable to the list of apps that I can search for on my Linux computer. By default, Linux users have to memorize the location of the Godot executable and navigate to that directory every time they want to launch Godot. This isn’t convenient and it violates Nielsen’s Usability Heuristic 6 “[Recognition Rather than Recall](https://www.nngroup.com/articles/ten-usability-heuristics/)” every time the user wants to launch Godot.

There are ways Linux users can work around this, but the documentation on it is external, outside of Godot documentation, and not straight-forward. For example, Linux users can add the Godot executable to their operating system’s $PATH directory to make Godot executable on the command line, but I had to look this up someplace else.

The Linux user who is new to Godot would benefit from being shown documentation for how to more conveniently execute Godot to make it faster and easier for them to launch Godot every time.

When I downloaded Godot from https://godotengine.org/download/linux/, the website gave me instructions on how to get started with Godot. The bulletin list of links was very nice and user friendly for beginners!  See screenshot. This bulletin list is below where the website says “If this is your first time using the Godot Engine, take a look at our beginner resources.” These links helped me a lot with getting started with Godot. That bulletin list would be an excellent place to add a link to instructions for how to add the Godot executable to the user’s path directory. This would solve the usability problem, because then Linux users would then have the link to learn how to add Godot to their $PATH directory, and no longer need to memorize the directory of their Godot executable.

![image](https://github.com/godotengine/godot-docs/assets/81597927/54ca59b7-4441-43dd-9d5b-f87b3d9f8e6f)

**Comment by AThousandShips** [comment]
Is this even remotely uniform across different distros? Beyond the `PATH` part? Which is documented [here](https://docs.godotengine.org/en/stable/tutorials/editor/command_line_tutorial.html#path), a page I'd say is something you'd read if you read anything detailed in the docs, this is an advanced usage IMO

**Comment by skyace65** [comment]
We already have information on this in the Linux FAQ [here](https://docs.godotengine.org/en/stable/about/faq.html#linux). Though that does need to be updated a little, and there's an issue open for that (#8954). I would recommend opening an issue for linking to this in the website repository [here](https://github.com/godotengine/godot-website/issues). Unfortunately I can't transfer this issue to that repository so I'm going to close it.
