### ISSUE TITLE
CPUParticles2D Must Have Collision

### ISSUE THREAD

**Issue by HasanAlilhadi** [godotengine/godot-docs#9422]
**Your Godot version: 4.2.2**

**Issue description: Godots CPUParticles2D/GPUParticles2D must support collision to collide with other objects not just with LightOccluder2D, and it's already supported in different game engines like Unreal Engine or Unity, I hope you guys make it possible for us**

**URL to the documentation page (if already existing): null**

**Comment by AThousandShips** [comment]
This is not the place to make proposals, please make a proposal [here](https://github.com/godotengine/godot-proposals) after searching for existing ones (open *and* closed) and make sure to fill in every part of the form
