### ISSUE TITLE
translated() method not behaving the way it described

### ISSUE THREAD

**Issue by Muhammad-Jamal** [godotengine/godot-docs#9428]
**GODOT 4.2.1**

translated() method not behaving the way as described

https://docs.godotengine.org/en/stable/tutorials/math/matrices_and_transforms.html

It says translated() will translate keeping in account rotation of object, if rotated 90 degrees clockwise and then translated() using vector2.up it will move to right. but I tried it in 3D i rotated player in different directions and translated() with vector3,forward but it kept moving in global vector3.forward completely negating its rotation

**Comment by AThousandShips** [comment]
`translated` is *global* not *local*, for that you need `translate_local`
