### ISSUE TITLE
Undocumented Unit Test Feature - If you need Rendering Server, Physics ect...

### ISSUE THREAD

**Issue by Kimau** [godotengine/godot-docs#9437]
**Your Godot version:** 4.x

**Issue description:** If your writing a C++ unit test and require that the Rendering Server. Then there is some code test_main.cpp which checks if your test name includes 
`if (name.contains("[SceneTree]") || name.contains("[Editor]")) {`

We should likely add documentation to the unit test or writing custom unit test docs which explains this feature.
Lost a bunch of time to it myself today.

**URL to the documentation page (if already existing):**
https://docs.godotengine.org/en/stable/contributing/development/core_and_modules/unit_testing.html
or 
https://docs.godotengine.org/en/stable/contributing/development/core_and_modules/custom_modules_in_cpp.html#doc-custom-module-unit-tests

**Comment by tetrapod00** [comment]
This was documented in https://github.com/godotengine/godot-docs/pull/9701, so this issue can be closed.
