### ISSUE TITLE
Creating signals does generate code in external editor VS Code 

### ISSUE THREAD

**Issue by victorliu5296** [godotengine/godot-docs#9451]
**Your Godot version:**
Godot Engine v4.2.2.stable.mono.official.15073afe3

**Issue description:**
I am reading the English documentation of Godot 4.2 stable, specifically the tutorial "Your first 2D game". There is a warning indicating that creating a signal does not correctly generate the callback function in an external editor: 

![image](https://github.com/godotengine/godot-docs/assets/150534352/6aa97515-1739-43f2-a154-7205b62c1420)
However, it worked fine for me with the following setup:
- OS: Windows 11
- VS Code version: 1.89.1

![image](https://github.com/godotengine/godot-docs/assets/150534352/ae7c717f-26a1-44fe-9a2d-c06e828ddf67)

I figured that this might be revisited.

**URL to the documentation page:**
https://docs.godotengine.org/en/stable/getting_started/first_2d_game/03.coding_the_player.html#preparing-for-collisions

**Comment by skyace65** [comment]
Please comment on the engine bug for that issue which is still open https://github.com/godotengine/godot/issues/41283. I'd like to refrain from removing this note until that issue is closed.

**Comment by QuotientParadox** [comment]
Works fine for me too
![Screenshot from 2024-06-12 14-03-15](https://github.com/godotengine/godot-docs/assets/117741113/5cb3c8c5-ebbb-4227-b495-635a6d6d9803)

**Comment by skyace65** [comment]
Finally got around to testing this on my own machine and the issue is still present with the latest version of VSCode (1.92.1) and Godot 4.3 RC3. Again, if this issue isn't happening for you please comment on the engine issue I linked to earlier.
