### ISSUE TITLE
Add a sample of GDExtention's `dependencies` syntax 

### ISSUE THREAD

**Issue by greenfox1505** [godotengine/godot-docs#9462]
**Your Godot version: **
4.2.2

**Issue description:**
`dependencies` is mentioned in the docs here, but there is no example here of what that syntax looks like.

**URL to the documentation page (if already existing):**
https://docs.godotengine.org/en/4.0/tutorials/scripting/gdextension/gdextension_cpp_example.html#using-the-gdextension-module

**Comment by dsnopek** [comment]
PR https://github.com/godotengine/godot-docs/pull/9383 is attempting to add more documentation about .gdextension files, but it doesn't cover `dependencies` either
