### ISSUE TITLE
Exporting Android does not have up to date editor settings configuration

### ISSUE THREAD

**Issue by chrisrabe** [godotengine/godot-docs#9464]
**Your Godot version:**
4.2.2

**Issue description:**
The "Exporting for Android" documentation does not mention anything about adding Java SDK Path in the editor settings.

**URL to the documentation page:**
https://docs.godotengine.org/en/stable/tutorials/export/exporting_for_android.html

**Comment by AThousandShips** [comment]
This was already fixed for latest but needs a 4.2 specific update as well:
* https://github.com/godotengine/godot-docs/pull/9371

**Comment by skyace65** [comment]
Fixed by #9623.
