### ISSUE TITLE
Godot Docs - 3.6 and stable ePub files defective 'Contents' links

### ISSUE THREAD

**Issue by FrederickKDP** [godotengine/godot-docs#9485]
**Your Godot version:**
3.6

**Issue description:**
Although the link for the 3.6 ePub zip is able to download (got it here [nightly link](https://nightly.link/godotengine/godot-docs/workflows/build_offline_docs/master/godot-docs-epub-3.6.zip)) and the file is able to open, the 'Contents' section seems to be broken. None of the apps I have tried to use to open it worked correctly. I have also tried to open the 3.6 file with different devices and same problem.
However, the latest documentation ePub file works correctly with 'Contents' working. The issue is only with the 3.6 version.

**URL to the documentation page (if already existing):**
[3.6 documentation](https://docs.godotengine.org/en/3.6/index.html)

**Comment by FrederickKDP** [comment]
Hi, sorry the bump, I was in the hopes that with the new weekly version it would solve itself, but both 3.6 and stable have same issue. Only latest is correct.
3.6 doc on Okular, Windows:
![image](https://github.com/godotengine/godot-docs/assets/24514819/191d612f-6fae-447d-906d-5270cd9baa07)
3.6 doc on Sumatra, Windows:
![image](https://github.com/godotengine/godot-docs/assets/24514819/13c2fd1a-ed9e-4354-8ad5-ae681a4bb394)
Stable on Sumatra, Windows:
![image](https://github.com/godotengine/godot-docs/assets/24514819/9ab5e005-7d75-4728-b0e9-8f7b1435145d)
Stable on Okular, Windows:
![image](https://github.com/godotengine/godot-docs/assets/24514819/f0f3ff68-05c8-4d3d-b970-ad95b712f8a4)


How it's expected to be, latest:
Sumatra:
![image](https://github.com/godotengine/godot-docs/assets/24514819/745c8fe0-407c-437f-b6fd-2a538d32fb2a)
Contents links are accessible.

**Comment by skyace65** [comment]
This was fixed by  #9638

**Comment by FrederickKDP** [comment]
> This was fixed by #9638

Hi, thank you for the reply for this long time issue! I was downloaded the 3.6 ePub, and it does not open. I hope to try in another machine soon, but on a Linux machine, with both Okular and Chrome browser, did not open.
