### ISSUE TITLE
When i tried to use the visual studio .ink direct access on windows11

### ISSUE THREAD

**Issue by MarckJavier** [godotengine/godot-docs#9496]
**Your Godot version:**
4.2.2

**Issue description:**
Due a configuration to use external editor visual studio.ink acces direct on windows 11 all text of godot get corrupted and it doesn't read well.
I add a picture of the bug:
![image](https://github.com/godotengine/godot-docs/assets/72543902/37f55f8a-2de6-4902-9fea-46200be92649)

**URL to the documentation page:**

If you know how to fix the issue you are reporting please
consider opening a pull request. We provide a tutorial on
using git here: https://docs.godotengine.org/en/stable/community/contributing/pr_workflow.html,
writing documentation at https://docs.godotengine.org/en/stable/community/contributing/docs_writing_guidelines.html
and contributing to the class reference here: https://docs.godotengine.org/en/stable/community/contributing/updating_the_class_reference.html

**Comment by skyace65** [comment]
This is an engine issue and should be reported in the engine repository [here](https://github.com/godotengine/godot/issues). Issues in this repository are only for problems with the documentation.

**Comment by MarckJavier** [comment]
sorry, I just posted on the correct place
