### ISSUE TITLE
Setting the main scene automatically appears when running scene for first time - Introduction

### ISSUE THREAD

**Issue by dustycyanide** [godotengine/godot-docs#9502]
**Your Godot version:**

4.2.2.stable

**Issue description:**

In engine, when running the main scene for the first time, the main scene dialogue pops up right away. In the documentation, it instructs you to manually set the main scene after running and closing. 

**URL to the documentation page:**

Setting the main scene https://docs.godotengine.org/en/stable/getting_started/step_by_step/nodes_and_scenes.html#setting-the-main-scene

**Comment by AThousandShips** [comment]
What do you mean? The procedure you're describing is exactly what the documentation says? Where does it say:
> In the documentation, it instructs you to manually set the main scene after running and closing.

**Comment by skyace65** [comment]
I think I understand what the confusion is. @dustycyanide the menu to select the main scene only shows up if you press the "Run Project" button. When the tutorial asks you to run the scene right before the "Setting the main scene" section, it asks you to do it with the "Run Current Scene" button, if you use that button the project will not ask you to set the main scene.

**Comment by AThousandShips** [comment]
It's a bit vague but the tutorial says:
> Another button next to it allows you to set and run the project's main scene

So it does say to run with that not the current scene, we could just break up the sentence to make it more obvious

**Comment by dustycyanide** [comment]
@AThousandShips I think you're right, I must have clicked the "play" button instead of the "play scene" button, and that's why it asked me to set the main scene in a different order than the step by step showed.
