### ISSUE TITLE
Wrong verb used

### ISSUE THREAD

**Issue by laupoly** [godotengine/godot-docs#9510]
**Your Godot version:**
4.2

**Issue description:**
Wrong verb used in Godot docs' best practices, scene organization section.

> The whole point of all this indirection is to avoid ending up in a situation where changing one class results in adversely **effecting** other classes dependent on it.

Should be "adversely affecting".

To effect: cause (something) to happen; bring about.
To affect: have an effect on; make a difference to.

**URL to the documentation page (if already existing):**
https://docs.godotengine.org/en/stable/tutorials/best_practices/scene_organization.html

**Comment by SeanAverS** [comment]
Hello, 

I am interested on working on this. Could I please be assigned? Thank you.

**Comment by AThousandShips** [comment]
We don't assign issues, so you can just go ahead and open a PR for this, make sure to target the `master` branch
