### ISSUE TITLE
Page "Exporting For Windows" is outdated

### ISSUE THREAD

**Issue by DDAN-17** [godotengine/godot-docs#9515]
**Your Godot version:**
4.2
**Issue description:**
On the page for Exporting For Windows, there are outdated screenshots
**URL to the documentation page:**
https://docs.godotengine.org/en/stable/tutorials/export/exporting_for_windows.html

**Comment by DDAN-17** [comment]
In the first screenshot, under the export category in the editor settings, UWP is shown, which does not exist in Godot 4.2
In the second screenshot, Identity Type is shown as an option under codesign in the windows export settings, which also does not exist in Godot 4.2.

**Comment by skyace65** [comment]
Please double check your editor. Identity Type is an option for me in Godot 4.2.2.
![IdentType](https://github.com/godotengine/godot-docs/assets/6080368/71a0f5f2-56a2-4af9-86ec-615336a293d9)

**Comment by DDAN-17** [comment]
It might just be that I'm on a mac, because it's still not showing.
