### ISSUE TITLE
Tree page doesn't document "collapsed" variable

### ISSUE THREAD

**Issue by BinarryCode** [godotengine/godot-docs#9516]
**Your Godot version:** 4.2

**Issue description:** Latest "Tree" page doesn't document `collapsed` variable.

**URL to the documentation page (if already existing):** https://docs.godotengine.org/en/stable/classes/class_tree.html

**Comment by AThousandShips** [comment]
There's no such property on `Tree`, are you looking for [`TreeItem.collapsed`](https://docs.godotengine.org/en/latest/classes/class_treeitem.html#class-treeitem-property-collapsed)?

**Comment by BinarryCode** [comment]
Oh nevermind then, guess I got confused lol
