### ISSUE TITLE
2D Getting Started Tutorial - "GetReady" Message Not Hiding on Game Start

### ISSUE THREAD

**Issue by KodahScripts** [godotengine/godot-docs#9528]
**Your Godot version:**
4.2.2 Stable

**Issue description:**
2D Getting Started Tutorial - "GetReady" Message Not Hiding on Game Start.  Everything else about the tutorial works for me but the timeout signal is not affecting the "Get Ready" message.  All other messages respond to the timeout signal but not the "Get Ready" so I have Get Ready on my screen at all times.

**Comment by AThousandShips** [comment]
Can't replicate, please make sure you copied all the code correctly, use [this](https://github.com/godotengine/godot-demo-projects/tree/master/2d/dodge_the_creeps) as a reference

**Comment by skyace65** [comment]
And please reach out to one of the community locations, such as discord or the forum, for support before assuming it's a documentation error. There's a list of them [here](https://godotengine.org/community/). Can you give us a zip file of your project so we can see what's going on?

**Comment by KodahScripts** [comment]
[gettingStarted.zip](https://github.com/user-attachments/files/15949379/gettingStarted.zip)

**Comment by AThousandShips** [comment]
You didn't connect the timer to the signal, there's no connection from `MessageTimer` to `_on_message_timer_timeout`, you missed this step:
> Connect the pressed() signal of StartButton and the timeout() signal of MessageTimer, and add the following code to the new functions:

**Comment by KodahScripts** [comment]
Ah jeeze. Thank you, my apologies

Sent from my T-Mobile 5G Device
Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________
