### ISSUE TITLE
Godot OpenXR vendors plugin doesn't work - prevents following instructions for XR project

### ISSUE THREAD

**Issue by Noisivit** [godotengine/godot-docs#9529]
**Godot version:** 4.2.2.-mono, 4.2-mono. 4.2-standard, all run on Windows 11

**Issue description:** Downloading Godot OpenXR vendors plugin cause errors preventing following instructions

**URL to the documentation page:** https://docs.godotengine.org/en/stable/tutorials/xr/deploying_to_android.html

I can't follow up instructions for setting up XR project, because of errors caused after downloading Godot OpenXR vendors plugin. Downloading plugin is causing errors as on the screen below.

![obraz](https://github.com/godotengine/godot-docs/assets/8018370/cb2f0df7-713c-4682-b905-941449e815b9)

Also Plugins tab in Projects settings remain empty, as seen on screen below.

![obraz](https://github.com/godotengine/godot-docs/assets/8018370/fd3453a3-9046-4d56-93b2-a63ea399f216)

Through search I've found the same issue described in reddit post: https://www.reddit.com/r/godot/comments/1c87dse/issue_importing_openxr_vendors_plugin_help/

**Comment by Noisivit** [comment]
I've found related topic. PR #9121 add annotation that starting from version 2.0.3 of OpenXR vendors plugin, it doesn't need to be visible on the Plugins list anymore, but this information is only visible **for the latest version** of the documentation, even tho this should also apply to previous versions as this is plugin dependent and not engine version dependent.

Might require cherry picking #9121 to other versions as this is currently misleading.
![obraz](https://github.com/godotengine/godot-docs/assets/8018370/c8a770d3-035e-4939-a131-3d882b83e5a0)

Also, in regards of the errors, after moving on with instructions, I still got most of previously mentioned errors, but I was able to run project on Meta Quest 3. What was surprising is that after installing ADB drivers and reloading the project, the errors are gone, but it's hard for me to believe that it was ADB related issue, but I have no idea why this works now...

**Comment by skyace65** [comment]
That PR will be cherry picked at some point to the 4.2 branch.

CC @BastiaanOlij what do you think in regards to the errors?

**Comment by BastiaanOlij** [comment]
To my knowledge those errors should go away on a restart, these are caused by class info not yet being cached in `.godot` until the plugin has ran atleast once.

**Comment by Noisivit** [comment]
Thank you @BastiaanOlij, this explanation is good to me. Maybe is worth to consider mentioning this in documentation, because it's very confusing.
