### ISSUE TITLE
GDExtension add documentation on hot reloading feature (C++)

### ISSUE THREAD

**Issue by Zacrain** [godotengine/godot-docs#9532]
**Your Godot version:**
v4.2.2.stable.official [15073afe3]

**Issue description:**
With PR 80284 ( https://github.com/godotengine/godot/pull/80284 ) hot reloading was added. I encountered that I wasn't able to use that feature until I looked for and read a bit on the pull request page. For example, it is necessary to add the configuration parameter:
````
reloadable = true
````
to the `[configuration]` section of the corresponding `.gdextension` file. Yet this seems to be currently undocumented. (Furthermore I have encountered some issues, which I've detailed over at godot-cpp: https://github.com/godotengine/godot-cpp/issues/1502 .)

I suppose the documentation on GDExtension with the C++ example would be a good place to add it. Furthermore, it might be meaningful to add a section detailing the `.gdextension` file and all possible parameters as I haven't found a separate documentation on that.

Regarding the additional documentation in the GDExtension C++ Example, I'll provide a first draft in a pull request probably in the next couple of days. The latter, whether such an overview manual page might be meaningufl, I'll leave open for discussion.

**URL to the documentation page (if already existing):**
https://docs.godotengine.org/en/stable/tutorials/scripting/gdextension/gdextension_cpp_example.html

**Comment by paddy-exe** [comment]
Thanks for raising this issue
Fixed already by https://github.com/godotengine/godot-docs/issues/9383
