### ISSUE TITLE
C# Global classes & hiding "Editor" class name prefix ambiguity

### ISSUE THREAD

**Issue by DDoop** [godotengine/godot-docs#9537]
**Your Godot version:**
4.2.2, mono, running on MX Linux.

**Issue description:**
I'm designing a board game map editor (not a godot editor extension, but software I will run separately). I named a class `EditorMapTile` with the `[GlobalClass]` attribute so I could find it in the Godot editor's lists (script filename also matches). From what I can tell, Godot is checking my global class names first and hiding the ones that start with Editor in the Editor itself. I made a simple `DummyClass` inheriting from Node, and that appeared in the node picker list. Renaming `EditorMapTile` to `MyEditorMapTile` makes it appear in the list. This took me some time to figure out and was more than a little frustrating/surprising.

Is it documented elsewhere and I missed it?

**URL to the documentation page (if already existing):**
[C# Global Classes](https://docs.godotengine.org/en/stable/tutorials/scripting/c_sharp/c_sharp_global_classes.html)

**Comment by AThousandShips** [comment]
This is intentional, and the issue would be documenting that it is a thing and the prefix hides them

**Comment by AThousandShips** [comment]
See:
* https://github.com/godotengine/godot/issues/88601

**Comment by DDoop** [comment]
Thank you for replying and finding the duplicate. I should have searched a little harder! I will reply to that issue with the relevant pages in the documentation and my suggested disclaimer language.
