### ISSUE TITLE
Examples in "Material" page are not matchnig the documentation's version

### ISSUE THREAD

**Issue by Klaim** [godotengine/godot-docs#9538]
**Your Godot version:**
4.2.2

**Issue description:**

The `Material` page has links which are pointing to examples using v3.x while the page is set to v4.2

**URL to the documentation page:**

https://docs.godotengine.org/en/stable/classes/class_material.html

See the links in the "Tutorials" section.

I do not know how to fix the issue because I do not know if the links should be just removed or replaced by something already existing, maybe upgrades of these examples?

**Comment by AThousandShips** [comment]
This has already been fixed, but not updated for 4.2, closing
