### ISSUE TITLE
Outdated instructions on Your first 3D game / Setting up the game area

### ISSUE THREAD

**Issue by CyberSkull** [godotengine/godot-docs#9540]
**Your Godot version:** v4.2.2.stable.mono.official [15073afe3]

**Issue description:** Instructions are for what looks like a much older version of Godot.

**URL to the documentation page:** https://docs.godotengine.org/en/stable/getting_started/first_3d_game/01.game_setup.html

The project files are for Godot 3.x, and the instructions seem to reflect that. The most glaring issue I've found so far is that there is no control-drag to snap movement to grid. Instead it should instruct that one must click on the "Use Snap" button (`Y`).

<img width="597" alt="Toolbar with the Use Snap feature turned on." src="https://github.com/godotengine/godot-docs/assets/201815/a028be9b-2457-4c2b-b5de-43d5b959011c">

**Comment by AThousandShips** [comment]
As you can see at the top of the page it isn't updated for 4.2 yet

**Comment by CyberSkull** [comment]
See #9578.

**Comment by skyace65** [comment]
Closing as #9578 was merged.
