### ISSUE TITLE
Exporting for Android page has a link that says "Required Packages" but links to recommended packages

### ISSUE THREAD

**Issue by BAM5** [godotengine/godot-docs#9547]
**Your Godot version:** 4.2.3

**Issue description:**
> Ensure that the [required packages](https://developer.android.com/studio/intro/update#recommended) are installed as well.

The text states "required packages" but the link is to recommended packages. Should the link text be changed to "Ensure that the recommended packages..." or should the link be changed to https://developer.android.com/studio/intro/update#required

**URL to the documentation page:** https://docs.godotengine.org/en/stable/tutorials/export/exporting_for_android.html#download-the-android-sdk

**Comment by ayanchavand** [comment]
I think the link should be changed
