### ISSUE TITLE
Typo on Vector4i page

### ISSUE THREAD

**Issue by Ely31** [godotengine/godot-docs#9549]
**Your Godot version:** 4.2.2

**Issue description:**
The page says "Note: In a boolean context, a Vector4i will evaluate to false if it's equal to Vector4i(0, 0, 0, 0). Otherwise, a Vector3i will always evaluate to true."
This should say Vector4i instead of Vector3i in the second sentence.

**URL to the documentation page:**
https://docs.godotengine.org/en/stable/classes/class_vector4i.html#description

**Comment by skyace65** [comment]
This was already fixed in https://github.com/godotengine/godot/pull/87523, it's just not getting cherry picked to the 4.2 branch given how close we are to the release of 4.3. You can see the corrected sentence on the master branch of the docs.
