### ISSUE TITLE
"icon" parameter in EditorPlugin.add_custom_type is not optional, but documentation says it is

### ISSUE THREAD

**Issue by aaandreeew** [godotengine/godot-docs#9555]
**Your Godot version**

4.2.1.stable.mono

**Issue description**

The up-to-date-for-4.2 documentation says that the `icon` parameter in `EditorPlugin.add_custom_type()` is optional.

> Adds a custom type, which will appear in the list of nodes or resources. An icon can be optionally passed.

However, this is not an optional parameter. It's clear that it doesn't have a default value. An editor error is generated when this function is called without the `icon` parameter.

**URL to the documentation page**
[EditorPlugin > add_custom_type](https://docs.godotengine.org/en/4.2/classes/class_editorplugin.html#class-editorplugin-method-add-custom-type)

**Comment by Piralein** [comment]
Fixed by [#93777](https://github.com/godotengine/godot/pull/93777)

**Comment by aaandreeew** [comment]
Nice!
