### ISSUE TITLE
Adding autoloads from custom plugin: example in the doc is bad practice

### ISSUE THREAD

**Issue by smedelyan** [godotengine/godot-docs#9571]
**Your Godot version:** 4.2.2 and 4.3.beta-2

**Issue description:** see the doc at link below. It shows an example of adding and removing autoloads in `_enter_tree()`, `_exit_tree()`. I think this is not correct way to to do this because:
- This messes up the order of autoloads that the user may have defined
- This does not preserve the order of autoloads, if the user reordered them
- This sometimes causes problems, e.g. an autoload is added by such plugin much later than compiler checks for the presence of this autoload when it is already referenced from other code / autoloads
- This is just ineffective. No need to add & remove autoload each time the editor starts up and shuts down

The problem is much worse than it may look at the first glance, because some plugins out there already follow this bad practice.

Correct me if I'm wrong, but the proper way to add autoloads from a plugin is:
```gdscript
@tool
extends EditorPlugin

func _enable_plugin() -> void:
	add_autoload_singleton("MyAutoload", "res://my_autoload.gd")

func _disable_plugin() -> void:
	remove_autoload_singleton("MyAutoload")
```

**URL to the documentation page (if already existing):** https://docs.godotengine.org/en/stable/tutorials/plugins/editor/making_plugins.html#registering-autoloads-singletons-in-plugins

**Comment by HolonProduction** [comment]
I'd also say that is not the best way to do it. See also godotengine/godot#94249 for another reason why.
