### ISSUE TITLE
Significant Performance Drop Using C# Compared to GDScript

### ISSUE THREAD

**Issue by DevSavvySerge** [godotengine/godot-docs#9575]
**Your Godot version:**
4.2.2

**Issue description:**
Could you please make it clear that using C# significantly impacts performance? Even with a simple process method doing nothing, performance drops to about half of what you achieve with GDScript.

This is important because I spent a lot of time troubleshooting performance issues before discovering and confirming this. Coming from someone with over 20 years of experience using C#, a forewarning would be very valuable.

**Comment by ayanchavand** [comment]
I would like to pick this issue, where should this be mentioned in the docs?
