### ISSUE TITLE
Add link to discord server in asset submitting process

### ISSUE THREAD

**Issue by m21-cerutti** [godotengine/godot-docs#9589]
**Your Godot version:**
Godot 4.2.X

**Issue description:**
Hello,
Since we have now a discord server could be interesting to add the discord link inside the documentation page.

**URL to the documentation page (if already existing):**
https://docs.godotengine.org/en/stable/community/asset_library/submitting_to_assetlib.html

**Comment by AThousandShips** [comment]
Are we talking about an asset specific discord server? Otherwise that belongs in the [community](https://godotengine.org/community/) page, where it already is listed AFAIK

**Comment by skyace65** [comment]
Closing per AThousandShips comment and due to the lack of a response.
