### ISSUE TITLE
Make "Squash the creeps tutorial" compatibility mode-friendly

### ISSUE THREAD

**Issue by eon-s** [godotengine/godot-docs#9594]
**Your Godot version:**
4.2

**Issue description:**
Users following the Squash the creeps tutorial can't complete it if they use Compatibility Mode due to the usage of VisibilityNotifier3D which is still not available in that mode.
Alternatives could be adding killboxes at the edges or just a timer on the mobs, maybe the latter could be better for this level of tutorial.

**URL to the documentation page (if already existing):**
https://docs.godotengine.org/en/stable/getting_started/first_3d_game/09.adding_animations.html#animating-the-mobs

**Comment by DuduKadu** [comment]
Hi i was the one  who reported on the official discord, thanks for putting this here!

**Comment by skyace65** [comment]
Going to close this issue for a couple reasons. One, the starter project people import for this tutorial uses Forward+, people shouldn't be changing to compatibility for no reason. Two, VisibilityNotifier was added to OpenGL in 4.3. We're not going to make a change to the tutorial like this while the next release that fixes this is in Beta.

**Comment by eon-s** [comment]
> people shouldn't be changing to compatibility for no reason.

Normally, people doing this tutorial only changes the rendering mode if it's forced by their system's limitations. So I think it should be considered when creating guides.

But is good to know that it's being solved on 4.3!
Thanks!
