### ISSUE TITLE
Visible_Notifier_3D don't work in opengl

### ISSUE THREAD

**Issue by DuduKadu** [godotengine/godot-docs#9595]
**Godot version:** 4.2.2

**Issue description:** 

In the link below in the documentation there's a issue where it is proposed to use visible_on_screen_notifier node, this node is not currently compatible with the compatibility GL backend. It should address this limitation on the documentation and show alternatives as it is a tutorial for new developers
![Captura de tela 2024-07-11 142007](https://github.com/godotengine/godot-docs/assets/74280197/891c13d8-9cb0-436c-be07-c9051d2f0da5)

**URL to the documentation page:**
 https://docs.godotengine.org/en/stable/getting_started/first_3d_game/04.mob_scene.html

**Comment by clayjohn** [comment]
For context, VisibilityNotifier was added to OpenGL in 4.3. so this issue is only relevant for the 4.2 and earlier versions of the docs

**Comment by Piralein** [comment]
Closing, see #9594

Thank you for the report.
