### ISSUE TITLE
Add Tangent / Normal Mapping Issues as Reason to Enable "Force Disable Compression" on Scene Import

### ISSUE THREAD

**Issue by Pixelmusement** [godotengine/godot-docs#9596]
Godot version:
v4.2.1.stable.official [b09f793f5]

Issue description:
I recently ran into difficulties with incorrect tangents when importing an incredibly simple mesh, leading to a normal map having an inverted Y on only a single side of the mesh. I spent over two hours trying to figure out what was wrong trying numerous potential solutions until the one which worked was to enable "Force Disable Compression" when importing the mesh. This appears to have been an ongoing issue since at least January of 2023: https://github.com/godotengine/godot/issues/71221

Given the massive amount of time I lost to this one-checkbox problem, and given that the tooltip for this checkbox doesn't presently indicate that it can solve issues with tangents or normal mapping, I propose modifying the current tooltip description for the "Force Disable Compression" option in the Godot Engine editor when doing a Scene Import to indicate that problems with tangents and normal maps being flipped in strange ways may be solved by enabling this option.

**Comment by clayjohn** [comment]
The linked issue pre-dates the mesh compression option by almost a year (mesh compression wasn't added until 4.2.0). So I suspect that mesh compression is not the issue there. 

I think, as of 4.3 beta 3, that we have solved all the remaining problems with the mesh compression option (most of the fixes have been backported to 4.2.2 as well, so I recommend you upgrade). 

In general, we don't document bugs, instead we try to gather information about the bugs and fix them. We only warm about bugs in the documentation when we are confident that they cannot be fixed or cannot be fixed soon. 

Accordingly, can you please test your mesh in 4.2.2 and 4.3 beta 3 with mesh compression on and let me know if the issue has gone away? I suspect it has. If it hasn't I'd be happy to take a look at your file and make sure that Godot can import it with mesh compression without it breaking.

**Comment by Pixelmusement** [comment]
The linked issue was still marked as open with no milestones or assignments or such thus I didn't think it was going to be solved anytime soon, let alone was already solved! :o

I actually only read so far as to find mention of using the Force Disable Compression option, tried it, and it solved everything for me. Also, I thought 4.2.2 hadn't been ported over to Steam yet as I was on the 4.2.x branch; I didn't realize you had to be on none of the branches to have the latest version going. I got 4.2.2 in place, tried turning off Force Disable Compression in my import options, and yes, the tangents and normal mapping are still correct. :)
