### ISSUE TITLE
Android Exporting Documentation Not Updated

### ISSUE THREAD

**Issue by WyattMacKay** [godotengine/godot-docs#9610]
**Your Godot version:** Godot 4.2.2

**Issue description:** Incomplete documentation regarding exporting to android. Godot now asks for Java SDK path, where the documentation only lists Android SDK Path and Debug Keystore.

![image](https://github.com/user-attachments/assets/7ca3b74f-ceeb-46a6-8dab-c62cbd6da558)

**URL to the documentation page:** https://docs.godotengine.org/en/stable/tutorials/export/exporting_for_android.html

**Comment by skyace65** [comment]
Fixed by #9623.
