### ISSUE TITLE
Export projects page has outdated screenshots

### ISSUE THREAD

**Issue by menip** [godotengine/godot-docs#963]
http://docs.godotengine.org/en/latest/learning/workflow/export/exporting_projects.html

**Comment by pwab** [comment]
The whole [Export category](http://docs.godotengine.org/en/latest/learning/workflow/export/index.html) needs a revision (screenshots and text).

**Comment by mhilbrunner** [comment]
Thanks, but closing this as it should be covered by #74 and #946!
