### ISSUE TITLE
"Contribute" button opens a page that doesn't exist

### ISSUE THREAD

**Issue by ArthurPKFX** [godotengine/godot-docs#9652]
Goes to `https://docs.godotengine.org/en/stable/community/contributing/index.html` which redirects to `https://docs.godotengine.org/en/stable/contributing/ways_to_contribute.html`. Correct URL is `https://docs.godotengine.org/en/latest/contributing/how_to_contribute.html`
Might be an issue on the docs side but I can't tell so opened the issue here 😄

**Comment by coppolaemilio** [comment]
Moved the issue to the docs page to remember to set up the redirect from the docs side just in case we use the link somewhere else. I'm pushing the changes on the website to go to the proper destination.

**Comment by AThousandShips** [comment]
This redirect should already have been fixed in:
* https://github.com/godotengine/godot-docs/pull/9631

Which has been cherry picked, it seems the redirects have not been updated with the relevant script yet

**Comment by ArthurPKFX** [comment]
Thank you !
