### ISSUE TITLE
Softbody Physics stop colliding on higher ticks per second

### ISSUE THREAD

**Issue by Skyliner-369** [godotengine/godot-docs#9671]
**Godot version:** v4.2.2.stable.arch_linux

**Issue description:** When the physics ticks per second in a project are above 60, there's a massive decrease in collision accuracy for soft body objects to the point where collisions don't occur. 

Provided project for demonstration.
[Soft Ticks Second.zip](https://github.com/user-attachments/files/16419795/Soft.Ticks.Second.zip)

**reproduction steps:**
-open project
-open node_3d.tscn
-play scene

**to reproduce without file:**
-create scene (3d)
-add static body
-add soft body
-assign mesh (I use a default plane with a higher subdivision)
-go to project -> project settings -> physics -> common, and set Physics Ticks per Second to anything 90 or above
-add camera for ability to watch the cloth go straight through the static body
-play scene

**expected behavior:**
the cloth lands on the static body

**observed behavior:**
the cloth clips right through the floor

please note, I'm relatively new to issue reporting, so if you have questions, please ask.

**Comment by AThousandShips** [comment]
This is for documentation issues, not engine issues, please report this [here](https://github.com/godotengine/godot/issues) (after searching for existing issues, open and closed)
