### ISSUE TITLE
Moving the ground: wrong order of operations.

### ISSUE THREAD

**Issue by MrTheSaw** [godotengine/godot-docs#9680]
In 4.2.2, following the **Squash The Creeps** *Setting up the game area* the docs say:

> We're going to move the ground down so we can see the floor grid. Select the Ground node, hold the Ctrl key down to turn on grid snapping, and click and drag down on the Y axis.

However, you must click on the arrow, and *then* hold the control key, otherwise you can't move the arrow.

I suggest this wording:

> We're going to move the ground down so we can see the floor grid. Select the Ground node, click the Y axis, hold the Ctrl key down to turn on grid snapping, and drag down on the Y axis.

**URL to the documentation page:**
https://docs.godotengine.org/en/stable/getting_started/first_3d_game/01.game_setup.html

**Comment by MrTheSaw** [comment]
Or not? I just did this on the player model, and it works as written. Confusing.

**Comment by skyace65** [comment]
Just tested and moving works as described in the docs.
