### ISSUE TITLE
`Array`'s `resize()` method says something wrong (or misleading)

### ISSUE THREAD

**Issue by Foxomat** [godotengine/godot-docs#9687]
**Your Godot version:**
4.2.stable

**Issue description:**
in `Array`'s `resize()` documentation it says:  
"if the array size is smaller, elements are cleared, if bigger, new elements **are null.**"  

But if you have an typed Array[Type], it can't contain null values, so a Array[Dictionary] for example will be filled with empty dictionaries. This can lead to some hard to debug bugs, as the Documentation is misleading here (I had such a bug and it took me a while to figure it out)

**URL to the documentation page:**
https://docs.godotengine.org/en/4.2/classes/class_array.html#class-array-method-resize

**Comment by AThousandShips** [comment]
Thank you for reporting, this has already been fixed, please check the [latest version](https://docs.godotengine.org/en/latest/classes/class_array.html#class-array-method-resize)
