### ISSUE TITLE
ResourceUID Doc Page - Small Grammar Mistake

### ISSUE THREAD

**Issue by amarraff** [godotengine/godot-docs#9688]
**Your Godot version:**
v4.2.2.stable.official [15073afe3]

**Issue description:**
Underneath the "Description" header on the ResourceUID documentation page:
"Resource UIDs (Unique IDentifiers) allow the engine to keep references between resources intact, even if files can renamed or moved. They can be accessed with uid://."

Instead of "even if files _can_ renamed or moved," I believe it was meant to say "even if files _are_ renamed or moved."

**URL to the documentation page:**
https://docs.godotengine.org/en/stable/classes/class_resourceuid.html

**Comment by tetrapod00** [comment]
This issue can be closed, it was fixed in https://github.com/godotengine/godot/pull/94477.
