### ISSUE TITLE
Potentially missing explanation of converting files from 3.x to 4.x in 3D Game Tutorial

### ISSUE THREAD

**Issue by mstagg49** [godotengine/godot-docs#9703]
Your Godot version: 4.2.2

Issue description: Downloading the game assets used for the 3D game tutorial and using them to start a new project in the most recent version of Godot produces a prompt to convert the resources from Godot version 3.x to Godot version 4.x. There does not seem to be any issue with the conversion itself, however there is no mention of this procedure in the documentation, either on the page where the assets are downloaded from or the tutorial pages (a link to the Github page to download the assets are in two pages, linked below). I believe this could be a source of confusion for new users and some mention of it could be made to help reduce that confusion. One solution might be to add a sentence that explains that the conversion is necessary and which option to select.

URL to the documentation page (if already existing): https://docs.godotengine.org/en/stable/getting_started/first_3d_game/01.game_setup.html
https://docs.godotengine.org/en/stable/getting_started/first_3d_game/index.html

<img width="302" alt="conversion_issue_2" src="https://github.com/user-attachments/assets/ecb5428f-85ba-4aef-9700-3632beab7827">

**Comment by mstagg49** [comment]
I would be happy to make the additions this week.

**Comment by skyace65** [comment]
Fixed by #9482
