### ISSUE TITLE
event.pressed not exist in Godot 4.2

### ISSUE THREAD

**Issue by Torguen** [godotengine/godot-docs#9712]
**Your Godot version:**
v4.3.rc2.official [3978628c6]
**Issue description:**
The documentation claims to be updated to Godot 4.2 however event.pressed does not exist in 4.2 and is now event.is_pressed.

![Captura6](https://github.com/user-attachments/assets/c8f78388-6e23-41f4-88be-a700b991a39a)

**URL to the documentation page:**
https://docs.godotengine.org/en/stable/tutorials/inputs/inputevent.html
If you know how to fix the issue you are reporting please
consider opening a pull request. We provide a tutorial on
using git here: https://docs.godotengine.org/en/stable/community/contributing/pr_workflow.html,
writing documentation at https://docs.godotengine.org/en/stable/community/contributing/docs_writing_guidelines.html
and contributing to the class reference here: https://docs.godotengine.org/en/stable/community/contributing/updating_the_class_reference.html

**Comment by Torguen** [comment]
Apologies, I thought I was wrong but... who provides "pressed"? I can't find it in any higher class or in Input

**Comment by AThousandShips** [comment]
As you can see it has `is InputEventKey` so it is this property [`pressed`](https://docs.godotengine.org/en/stable/classes/class_inputeventkey.html#class-inputeventkey-property-pressed), not an issue, this is a case of type checking

**Comment by Torguen** [comment]
True, then it can be closed, it was my mistake.

**Comment by Torguen** [comment]
Hi, why doesn't "pressed" autocomplete?

![shaderagua gif](https://github.com/user-attachments/assets/e2a88272-a60d-413e-bff1-be5b9bc9da61)
