### ISSUE TITLE
Change get_nodes_in_group description

### ISSUE THREAD

**Issue by Muleceps** [godotengine/godot-docs#9714]
**4.2**

**For consistency the description of get_nodes_in_group should be changed to explicitly call the returned value an array and not a list. This is both more accurate and will prevent confusion for programmers new to godot who might believe that a specific data structure for lists is supported by Godot. The fact that the subsequent description of get_processed_tweens does correctly call the return value an array also lends credence to this request.**

**[URL to the documentation page (if already existing)](https://docs.godotengine.org/en/stable/classes/class_scenetree.html#class-scenetree-method-get-nodes-in-group):**

**Comment by AThousandShips** [comment]
This is already fixed, see [here](https://docs.godotengine.org/en/latest/classes/class_scenetree.html#class-scenetree-method-get-nodes-in-group) make sure to check the latest documentation before making a report
