### ISSUE TITLE
NavigationSever2D 4.2 doc links to 3.5 demo project

### ISSUE THREAD

**Issue by CyberSkull** [godotengine/godot-docs#9742]
**Your Godot version:**
v4.2.2.stable.mono.official [15073afe3]
**Issue description:**
The tutorial link on the `NavigationServer2D` links to the Goddot 3.5 build of the tutorial. The correct links is https://godotengine.org/asset-library/asset/2722.
**URL to the documentation page:**
https://docs.godotengine.org/en/4.2/classes/class_navigationserver2d.html

**Comment by AThousandShips** [comment]
This has already been fixed on the latest documentation in:
* https://github.com/godotengine/godot/pull/90310

And will be updated for 4.2 docs once 4.3 has been released 

Thank you for reporting, closing as already resolved
