### ISSUE TITLE
problem with translation of documentation

### ISSUE THREAD

**Issue by Shotaru-type** [godotengine/godot-docs#9744]
**Your Godot version: v3.5.3 mono**

**Issue description: problem with translation of documentation in Russian**

**URL to the documentation page:https://docs.godotengine.org/ru/3.5/tutorials/inputs/input_examples.html**

there is a Russian version of the documentation for 3.5 but not everything is translated sometimes paragraphs remain untranslated and this is a problem it happens often this is of course not such a big problem but still it often causes discomfort and in the section "class reference" there is no translation at all please translate all the documentation if possible or correct the untranslated paragraphs thank you for your attention have a nice day

**Comment by skyace65** [comment]
Generally speaking we don't have doc issues for translations that haven't been done yet so I'm going to close this. If you'd like to you can help us by translating the documentation yourself on weblate [here](https://hosted.weblate.org/engage/godot-engine/). We're always grateful for any contributions.
