### ISSUE TITLE
Capitalization of "GLTF" and "glTF" is not standardized across class reference and manual.

### ISSUE THREAD

**Issue by tetrapod00** [godotengine/godot-docs#9750]
**Your Godot version:**
4.3
**Issue description:**
The docs have no standardization of capitalization for the glTF format (and meshes or files of that format). Both "GLTF" and "glTF" appear throughout the manual and class reference. [This page](https://docs.godotengine.org/en/4.3/classes/class_gltfaccessor.html) even uses both.

Official usage from the [glTF specs page](https://registry.khronos.org/glTF/specs/2.0/glTF-2.0.html):
- "glTF" for the format.
- "GLB" for a binary file.
- ".gltf" for the format extension.

Godot classes use all-caps GTLF, as in `GLTFAccessor`. This makes sense for class naming rules. All other uses should ideally be standardized to the official style of "glTF".

Standardizing this *would* involve a lot of churn in the class reference, so perhaps this should be a style guideline that is applied whenever a file is already being changed.

**URL to the documentation page (if already existing):**
https://docs.godotengine.org/en/4.3/classes/class_gltfaccessor.html
https://docs.godotengine.org/en/latest/classes/class_gltfstate.html
https://docs.godotengine.org/en/latest/search.html?q=gltf

**Comment by skyace65** [comment]
Once the class reference PR is merged this can be closed.
