### ISSUE TITLE
Outdated Screenshots from the Autoload Documentation

### ISSUE THREAD

**Issue by Racer911dash1** [godotengine/godot-docs#9775]
**Your Godot version: 4.3**

**Issue description: The linked Docs page uses outdated screenshots for the Project settings. [#92770](https://github.com/godotengine/godot/pull/92770) reorganized it to have Autoload be a sub-tab of Globals, but the Docs don't reflect that change.**

**URL to the documentation page: https://docs.godotengine.org/en/stable/tutorials/scripting/singletons_autoload.html#doc-singletons-autoload**

![image](https://github.com/user-attachments/assets/483eb1a8-b71c-46f4-9414-693693d7ad19)

**Comment by darkstarworks** [comment]
To match images with https://github.com/godotengine/godot/pull/92770, 

I've added a PR: https://github.com/godotengine/godot-docs/pull/9773/commits/4664e7ab19e5b4d78957274a141a8b2321716163

thereby fixing https://github.com/godotengine/godot-docs/issues/9775

**Comment by LuigiKraken** [comment]
Its not just the screenshot, also the Explanatory Text gives the wrong Path. It should be:

> We have to register it as an autoload. Head to the Project -> Project Settings… menu and click on the Global tab.

**Comment by Racer911dash1** [comment]
> Its not just the screenshot, also the Explanatory Text gives the wrong Path. It should be:
> 
> > We have to register it as an autoload. Head to the Project -> Project Settings… menu and click on the Global tab. Make sure  Autoload tab is selected.

How so? From what I'm reading it gives the up-to-date path for 4.3.

**Comment by LuigiKraken** [comment]
> How so? From what I'm reading it gives the up-to-date path for 4.3.

hmm... Either im an Idiot or it was changed already. Its definitely correct now :)

**Comment by Piralein** [comment]
Fixed by #9773
