### ISSUE TITLE
TileMap node referenced as TileMapLayer node

### ISSUE THREAD

**Issue by NotThatRqd** [godotengine/godot-docs#9778]
**Your Godot version:** v4.2.2.stable.official [15073afe3]

**Issue description:**
The page refers to a node named TileMapLayer, although if I had to guess it was renamed to simply to TileMap. I am not sure if this is actually true though.

**URL to the documentation page:** https://docs.godotengine.org/en/stable/tutorials/2d/using_tilesets.html#doc-using-tilesets

If you know how to fix the issue you are reporting please
consider opening a pull request. We provide a tutorial on
using git here: https://docs.godotengine.org/en/stable/community/contributing/pr_workflow.html,
writing documentation at https://docs.godotengine.org/en/stable/community/contributing/docs_writing_guidelines.html
and contributing to the class reference here: https://docs.godotengine.org/en/stable/community/contributing/updating_the_class_reference.html

**Comment by skyace65** [comment]
You're looking at the wrong version of the docs for your engine version. The stable version of the docs is now for 4.3 which released last week, and added the TileMapLayer node as a replacement for TileMap.
