### ISSUE TITLE
"when" keyword not listed as a keyword

### ISSUE THREAD

**Issue by MajorGonzo** [godotengine/godot-docs#9786]
Godot 4.3

Just found out "when" is a keyword used in match statements (maybe elsewhere?).  However, it's not listed on the basics page as a keyword.  It's first listed a single time as an example on the match statement section (as far as I found), and then two times on the Patterns Guard section, which should perhaps be renamed Guard Expressions to match the example in match keyword section:

```
match <expression>:
...
<pattern(s)> when <guard expression>:
...
```

It should have an entry like "in" in the keyword section.  Also, for beginners I think "guard expression"  should link to the Patterns Guard/Guard Expressions section.

(https://docs.godotengine.org/en/stable/tutorials/scripting/gdscript/gdscript_basics.html)

**Comment by tetrapod00** [comment]
I agree with you that cross-links are desireable when possible. Unfortunately, that `<guard expression>` appears in a code block, so it can't link to a section. Everything after the "match" header is meant to be read in order, so I'm not too worried about leaving it unlinked.
