### ISSUE TITLE
Allow EditorScripts to Implement _process Function

### ISSUE THREAD

**Issue by strawstack** [godotengine/godot-docs#9795]
I would like to be able to add `func _process(delta):` to an EditorScript and have that function get called every frame while I'm using the editor. This would allow me to react to nearly all changes made in the editor rather than having to manually run a function for an EditorScript to make changes.

An alternative would be to allow signals to be emitted while in editor mode and for EditorScripts to be able to receive signals while one is using the editor.

**Comment by AThousandShips** [comment]
Feature proposals are tracked [here](https://github.com/godotengine/godot-proposals), this is for bugs. Please open a proposal instead.
