### ISSUE TITLE
Documentation of exported variables no longer appears in Inspector panel

### ISSUE THREAD

**Issue by glevner** [godotengine/godot-docs#9801]
**Your Godot version:** v4.3

**Issue description:**

Comments beginning with "##" for exported variables in GDScript are no longer displayed in the Inspector panel, which just says _No description available_. I believe this was working in v4.2.

**URL to the documentation page:**

https://docs.godotengine.org/en/stable/tutorials/scripting/gdscript/gdscript_documentation_comments.html#gdscript-documentation-comments

**Comment by tetrapod00** [comment]
This sounds more like an engine bug you should report here https://github.com/godotengine/godot/issues/new/choose.

**Comment by skyace65** [comment]
Tetrapod00 is correct. That may be an engine bug and should be reported in the Godot engine repository.
