### ISSUE TITLE
Having trouble finding SpriteFrames panel.

### ISSUE THREAD

**Issue by choidavid4** [godotengine/godot-docs#9808]
**Your Godot version:**
4.3.stable

**Issue description:**
I was following the "my first 2d game" tutorial and it mentions a SpriteFrames panel with a screenshot. 
The screenshot is outdated since the SpriteFrames panel is not there anymore.

Screenshot from the docs:
![image](https://github.com/user-attachments/assets/d1c6b1e4-2ca5-4349-a19d-556c307ae005)

Actual Godot editor:
<img width="955" alt="image" src="https://github.com/user-attachments/assets/4310b62d-8033-4a5c-b684-a067089f3718">

WDYT about changing the screenshot since it is confusing and I had a hard time finding the SpriteFrames option.

**URL to the documentation page (if already existing):**
https://docs.godotengine.org/en/stable/getting_started/first_2d_game/02.player_scene.html

**Comment by AThousandShips** [comment]
This is because you missed this step in the instructions:
> Click on the SpriteFrames you just created to open the "SpriteFrames" panel:

**Comment by skyace65** [comment]
Closing per AThousandShips comment
