### ISSUE TITLE
The documentation is outdated or wrong

### ISSUE THREAD

**Issue by iSynth** [godotengine/godot-docs#981]
there is such an example code in the official documentation
![screen shot 2018-01-17 at 00 28 42](https://user-images.githubusercontent.com/7373364/35013166-8552eb94-fb1d-11e7-90f4-7e77da74aa54.png)

but it does not work at all and I get an error like this
![screen shot 2018-01-17 at 00 30 57](https://user-images.githubusercontent.com/7373364/35013266-de44dfdc-fb1d-11e7-9589-8ca2bbec6c13.png)

it seems that the maintainers do not care about the updating of the documentation

**Comment by akien-mga** [comment]
The "stable" documentation is mistakenly pointing to Godot 3.0 documentation currently. Use http://docs.godotengine.org/en/2.1/ instead.

**Comment by cbscribe** [comment]
That code is from the 3.0 demo located at
http://docs.godotengine.org/en/latest/learning/step_by_step/your_first_game.html

If you're getting that error, you're using Godot 2.1. Please use http://docs.godotengine.org/en/2.1/learning/step_by_step/ for 2.1 documentation.

**Comment by iSynth** [comment]
WOW! Thank you for such quick answers guys!
