### ISSUE TITLE
Remove redundant Json.new() when using only static methods

### ISSUE THREAD

**Issue by Xascoria** [godotengine/godot-docs#9818]
**Your Godot version:**

4.2

**Issue description:**

There's a lot instances of `JSON.new()` in cases where only JSON static methods are called in the docs. For example:
```
	var body = JSON.new().stringify({"name": "Godette"})
	error = http_request.request("https://httpbin.org/post", [], HTTPClient.METHOD_POST, body)
	if error != OK:
		push_error("An error occurred in the HTTP request.")
``` 
Inside HTTPRequest. In fact, the VSCode godot-tools actually will give you the following warning here:
```
(STATIC_CALLED_ON_INSTANCE): The function "stringify()" is a static function but was called from an instance. Instead, it should be directly called from the type: "JSON.stringify()".
```

**URL to the documentation page (if already existing):**
There could be more but at minimum the following:
https://docs.godotengine.org/en/stable/classes/class_json.html
https://docs.godotengine.org/en/stable/classes/class_httprequest.html
https://docs.godotengine.org/en/stable/tutorials/io/saving_games.html

**Comment by AThousandShips** [comment]
Feature proposals are tracked [here](https://github.com/godotengine/godot-proposals), this is for bugs. Please open a proposal instead.
