### ISSUE TITLE
Signal.is_null() method isn't describing what the function is actually doing

### ISSUE THREAD

**Issue by trFate** [godotengine/godot-docs#9831]
Godot version is 4.3

I was trying to detect if a signal has a valid object linked to it, reading the doc I ended up on the Signal.is_null() method which states "Returns `true` if the signal's name does not exist in its object, or the object is not valid." It appears to not describe the actual logic of the method. I experimented with it and someone pointed to me that the source code for this function is 
```C++
# Callable.h
_FORCE_INLINE_ bool is_null() const {
	return method == StringName() && object == 0;
}
```
I don't really know how the engine source code is structured and can't verify that myself but here is the test I performed 
```swift
var button : Button = Button.new()
var pressed_signal : Signal = button.pressed
button.free()
print(pressed_signal.is_null()) # Print false 
```
It seems like for the `Signal.is_null()` method to return true both the object and the signal name must be invalid, in my case the signal still has a name but is not attached to an object anymore

Here's the link to the method in the documentation : https://docs.godotengine.org/en/stable/classes/class_signal.html#class-signal-method-is-null

**Comment by AThousandShips** [comment]
You're looking at the wrong method (though it's pretty similar):
```cpp
_FORCE_INLINE_ bool is_null() const {
	return object.is_null() && name == StringName();
}
```
Still the exact description should be improved

**Comment by AThousandShips** [comment]
This should be fixed over in the [main repo](https://github.com/godotengine/godot), and the easiest way is to just change the description to something like that of `Callable.is_null`, adjusted to fit `Signal`
