### ISSUE TITLE
Old node group inspector in "Saving games" documentation

### ISSUE THREAD

**Issue by VseOdbornik** [godotengine/godot-docs#9845]
**Your Godot version:**
Godot 4.3 documentation website

**Issue description:**
The first PNG picture shows old node group inspector (Not both Scene Groups and Global Groups)

**URL to the documentation page (if already existing):**
https://docs.godotengine.org/en/stable/tutorials/io/saving_games.html

**Comment by tetrapod00** [comment]
For anyone interested in helping to update this, we have a general guide on contributing [here](https://docs.godotengine.org/en/stable/contributing/documentation/contributing_to_the_documentation.html), and guidelines on taking screenshots for the docs [here](https://docs.godotengine.org/en/stable/contributing/documentation/docs_image_guidelines.html)
