### ISSUE TITLE
Unused RenderingDriver enum

### ISSUE THREAD

**Issue by pochoco24** [godotengine/godot-docs#9851]
**Your Godot version:** 4.3

**Issue description:** The OS class has a RenderingDriver enum that is not used anywhere. I'm looking for a get_rendering_driver() method in the docs, but it's either undocumented or not in Godot.

**URL to the documentation page:** https://docs.godotengine.org/en/stable/classes/class_os.html#enum-os-renderingdriver

**Comment by tetrapod00** [comment]
The lack of a function is a missing feature, so you should open up a proposal to add the feature here: <https://github.com/godotengine/godot-proposals/issues>.

Internally this enum is only used in a [few places](https://github.com/search?q=repo%3Agodotengine%2Fgodot+renderingdriver&type=code). Maybe a few more that don't get found with that search.

There might already be a proposal for a way to detect which renderer is being used (forward+, compatibility, mobile), maybe https://github.com/godotengine/godot-proposals/issues/9293. But I didn't see any proposals specifically about exposing the RenderingDriver enum, which doesn't map 1:1 with the renderer. So I'd recommend making a new proposal to add this feature

**Comment by Calinou** [comment]
Closing in favor of https://github.com/godotengine/godot-proposals/issues/10609.
