### ISSUE TITLE
Improper Documentation for Custom Metadata on Tilesets

### ISSUE THREAD

**Issue by EastToastLiving** [godotengine/godot-docs#9857]
**v4.3.stable.official [77dcf97d8]**

**Improper Documentation for Custom Metadata on Tilesets**

**(https://docs.godotengine.org/en/stable/tutorials/2d/using_tilesets.html#assigning-custom-metadata-to-the-tileset-s-tiles)**

The [Tileset Tutorial page for Assigning custom metadata to the TIleSet's tiles](https://docs.godotengine.org/en/stable/tutorials/2d/using_tilesets.html#assigning-custom-metadata-to-the-tileset-s-tiles) claims that in the editor the custom property names do not appear, but rather their index is shown. Having tried this out, this appears to be untrue, at least for v4.3.stable.official [77dcf97d8]

I created a pull request for a potential correction under [EastToastLiving:tileset-custom-metadata-correction](https://github.com/EastToastLiving/godot-docs/tree/tileset-custom-metadata-correction).

In this pull request, I changed the wording of the section and updated the picture of the editor to clearly show the appropriate custom metadata values.

If anything was inappropriately enacted or any information is still needed, please let me know, Thank you.

**Comment by tetrapod00** [comment]
Your pull request doesn't actually show up in https://github.com/godotengine/godot-docs/pulls. It looks like you missed the final step of actually creating a PR from your branch.

**Comment by EastToastLiving** [comment]
Below is a picture of my Godot build when working with the Tileset Custom Metadata feature:
![using_tilesets_edit_custom_data](https://github.com/user-attachments/assets/29f9c066-315d-4964-b5ca-a673d050de81)

This is compared to what is currently shown on the Godot turotial page:
![image](https://github.com/user-attachments/assets/10bbe123-3080-4ba9-9c92-60c5cea34dd3)

If anyone else could confirm this on their build of v4.3 that would be a great sanity check.

**Comment by EastToastLiving** [comment]
> Your pull request doesn't actually show up in https://github.com/godotengine/godot-docs/pulls. It looks like you missed the final step of actually creating a PR from your branch.

I will look into this now, thank you for the heads up!

**Comment by EastToastLiving** [comment]
> Your pull request doesn't actually show up in https://github.com/godotengine/godot-docs/pulls. It looks like you missed the final step of actually creating a PR from your branch.

I have now successfully actually completed the [pulll request](https://github.com/godotengine/godot-docs/pull/9863). Thank you for double checking that!

**Comment by skyace65** [comment]
Closing this as #9863 was merged.
