### ISSUE TITLE
NotificationVisibilityChanged is 31, not 30. 30 is another notification with no explicit const name reacting to node moving.

### ISSUE THREAD

**Issue by Festinocasa** [godotengine/godot-docs#9859]
**Your Godot version:**
v4.3.stable.mono.official [77dcf97d8]

**Issue description:**
The value of NotificationVisibilityChanged is 31, not like 30 in docs. Is that a mistake? Insteadly, 30 is a notification value can be passed in "override void _Notification(int what)" displaying no const name in my intellisense, which is reacted to node moving.

**URL to the documentation page:**
https://docs.godotengine.org/en/stable/classes/class_window.html#class-window-constant-notification-visibility-changed

**Comment by AThousandShips** [comment]
No it is `30`, see the declaration:
```cpp
	enum {
		NOTIFICATION_VISIBILITY_CHANGED = 30,
		NOTIFICATION_POST_POPUP = 31,
		NOTIFICATION_THEME_CHANGED = 32
	};
```

You are looking at the notification from `CanvasItem` which *is* `31` not `30`:
```cpp
	enum {
		NOTIFICATION_TRANSFORM_CHANGED = SceneTree::NOTIFICATION_TRANSFORM_CHANGED, //unique
		NOTIFICATION_DRAW = 30,
		NOTIFICATION_VISIBILITY_CHANGED = 31,
		NOTIFICATION_ENTER_CANVAS = 32,
		NOTIFICATION_EXIT_CANVAS = 33,
		NOTIFICATION_LOCAL_TRANSFORM_CHANGED = 35,
		NOTIFICATION_WORLD_2D_CHANGED = 36,
	};
```

You are mixing up two different cases, two different values

**Comment by Festinocasa** [comment]
Ok, thanks a lot, i really mixed it up. I should search canvasItem in canvasItem docs page.

**Comment by AThousandShips** [comment]
Closing as per above, make sure you're looking in the right place
