### ISSUE TITLE
Could you make the left sidebar on the Godot documentation site toggleable?

### ISSUE THREAD

**Issue by b3lon9** [godotengine/godot-docs#9868]
**Your Godot version:** <br/> 4.4<br/>

**Issue description:** 
It would be great if the left sidebar on the Godot documentation site could be toggled between `VISIBLE` and `INVISIBLE`. Is that possible?

**URL to the documentation page (if already existing):**
<img src="https://github.com/user-attachments/assets/d526a715-df2f-4635-8270-4ce0855c0da4" alt="png" width="520" />

**Comment by AThousandShips** [comment]
Thank you for your proposal, consolidating in:
* https://github.com/godotengine/godot-docs/issues/7751
