### ISSUE TITLE
AssetLib section

### ISSUE THREAD

**Issue by NullConstant** [godotengine/godot-docs#989]
Currently Godot's Asset Library (AssetLib) is not really documented. (Well, basically entirely undocumented, even.)

Abstracting away from the fact that it in itself probably needs more work on the code side (which is beyond the scope of this repo), it's probably worth writing something about:

- What it is (and isn't)
- How to use it to download things (both on the website and in-engine)
- How to upload things (coupled with submission guidelines)
- an FAQ section

I'm not however sure what the best place *in* the docs for it would be, but I'm currently thinking of a new section within `Engine features`. (Though it might be good to have it as a top-level section instead.)

**Comment by mhilbrunner** [comment]
+1 on the submission guidelines.

And include an easy-to-link-to answer to "Can there be paid assets on the Assets Lib? Why not?" as that gets asked with some frequency, I think.

**Comment by NullConstant** [comment]
On the subject *of* submission guidelines, is anything even established in that regard?
@akien-mga

**Comment by pwab** [comment]
Regarding that topic there are also open issues in the asset-library repo itself:

- godotengine/asset-library/issues/98
- godotengine/asset-library/issues/124

**Comment by mhilbrunner** [comment]
@NullConstant Don't think there are any guidelines yet. See the linked issues. Just go ahead with your docs, and we'll have to update the pages once there are guidelines.
