### ISSUE TITLE
Incorrect description of function parameter for Array.sort_custom

### ISSUE THREAD

**Issue by bogcow** [godotengine/godot-docs#9892]
4.3

Incorrect description of function parameter for Array.sort_custom

[https://docs.godotengine.org/en/stable/classes/class_array.html#class-array-method-sort-custom](https://docs.godotengine.org/en/stable/classes/class_array.html#class-array-method-sort-custom)

The docs say the function should return true if the first element should be moved behind the second one, which is not correct. The function should return true if the first element should appear before the second element.

**Comment by AThousandShips** [comment]
Already fixed in:
* https://github.com/godotengine/godot/pull/96118

But the online documentation hasn't been updated yet for `latest` (and the 4.3 haven't been cherry-picked yet)
