### ISSUE TITLE
Singletons (Autoload) documentation using outdated screenshots

### ISSUE THREAD

**Issue by CallumMarriage** [godotengine/godot-docs#9904]
**Your Godot version:**
4.3

**Issue description:**
The screenshots in the Singletons (Autoload) documentation are out of date. They show the Project > Project Settings > Autoload instead of Project > Project Settings > Globals > Autoload.

![image](https://github.com/user-attachments/assets/f542c341-cf9c-43b4-8412-31671a3898d2)
![image](https://github.com/user-attachments/assets/b0c8bfb6-b0c6-44d6-b6d8-06d31c86075f)

[**URL to the documentation page:**
](https://docs.godotengine.org/en/stable/tutorials/scripting/singletons_autoload.html)

If you know how to fix the issue you are reporting please
consider opening a pull request. We provide a tutorial on
using git here: https://docs.godotengine.org/en/stable/community/contributing/pr_workflow.html,
writing documentation at https://docs.godotengine.org/en/stable/community/contributing/docs_writing_guidelines.html
and contributing to the class reference here: https://docs.godotengine.org/en/stable/community/contributing/updating_the_class_reference.html

**Comment by AThousandShips** [comment]
Already fixed, please check the latest version before making a report to make sure things are in fact still out of date
