### ISSUE TITLE
Error in specifying recommended system requirements

### ISSUE THREAD

**Issue by Filin-trash** [godotengine/godot-docs#9927]
**Your Godot version:** 4.3

**Issue description:** Exported Godot project > Exported Godot project > Example: Apple A11 (iPhone XS/XR) (the iphone xs does not have a11 bionic, but a12 bionic)

**URL to the documentation page:** https://docs.godotengine.org/en/stable/about/system_requirements.html

https://en.wikipedia.org/wiki/IPhone_XS > SoC > _**XS and XS Max use A12 Bionic SoC**_, which consists of 6-core CPU (2x Vortex + 4x Tempest), 4-core GPU, and 8-core Neural Engine.

**Comment by skyace65** [comment]
This was fixed in #9758
