### ISSUE TITLE
Adjust the shader code's comment on Playing Videos page

### ISSUE THREAD

**Issue by Odaimoko** [godotengine/godot-docs#9934]
**Your Godot version:**
4.2.1

**Issue description:**

The shader code in Chroma Key Videos part uses `#` as comment, but in Godot 4 the shader code uses `//`. Should it be changed for all 4.x documents?

![image](https://github.com/user-attachments/assets/603da25b-144a-4ef0-af60-264413bb1c7f)

**URL to the documentation page:**
https://docs.godotengine.org/en/stable/tutorials/animation/playing_videos.html

```[tasklist]
### Tasks
```

**Comment by tetrapod00** [comment]
It'll be fixed in `master` / `latest` then hopefully get cherrypicked to previous versions.

Working on a fix now.
