### ISSUE TITLE
export_node_path cannot use an Array like described in the documentation

### ISSUE THREAD

**Issue by patdough5** [godotengine/godot-docs#9942]
**Your Godot version:**
v4.2.2.stable.official [15073afe3]

**Issue description:**
export_node_path cannot use an Array, as showcased in the documentation

**URL to the documentation page:**
https://docs.godotengine.org/en/stable/classes/class_%40gdscript.html#class-gdscript-annotation-export-node-path

If you know how to fix the issue you are reporting please
consider opening a pull request. We provide a tutorial on
using git here: https://docs.godotengine.org/en/stable/community/contributing/pr_workflow.html,
writing documentation at https://docs.godotengine.org/en/stable/community/contributing/docs_writing_guidelines.html
and contributing to the class reference here: https://docs.godotengine.org/en/stable/community/contributing/updating_the_class_reference.html

**Comment by AThousandShips** [comment]
That's because you are on 4.2, this was not supported in 4.2 but was introduced in 4.3, as you can see in the [4.2 documentation](https://docs.godotengine.org/en/4.2/classes/class_%40gdscript.html#class-gdscript-annotation-export-node-path)

**Comment by patdough5** [comment]
Ah apologies, I thought I was on 4.3 for some reason. Sorry!
