### ISSUE TITLE
Vibration warning

### ISSUE THREAD

**Issue by mariomadproductions** [godotengine/godot-docs#9973]
**Your Godot version:**
N/A

**Issue description:**
Currently, the vibration section contains this warning:

> Vibration can be uncomfortable for certain players. Make sure to provide an in-game slider to disable vibration or reduce its intensity.

I think it would be better to suggest that there should be an option to disable it full stop, not just reduce the intensity. As even a small amount of vibration can be pretty annoying, and some controllers have motors that can't be made to run at a lower intensity.

**URL to the documentation page (if already existing):**
https://docs.godotengine.org/en/stable/tutorials/inputs/controllers_gamepads_joysticks.html#vibration

**Comment by AThousandShips** [comment]
> I think it would be better to suggest that there should be an option to disable it full stop, not just reduce the intensity. 

It does say you should provide support for disabling it, granted it says "or reduce it" but it doesn't suggest to just reduce it

**Comment by mhilbrunner** [comment]
Closing; as outlined above, this is already the case.
